import { NOTICE_VERSION } from "./policy";
export type Notice = {title:string; sections:{title:string;text:string}[]};
export const notices: Record<string,Notice> = {
 "kebijakan-privasi": {title:"Kebijakan Privasi",sections:[
 {title:"Pengelola dan kontak",text:"BahasaCerdas dikelola CV Obah Mamah (nama dagang Teras Kata), NIB 1217000151443, berdomisili di Tangerang, Banten. Hubungi halo@bahasacerdas.com untuk pertanyaan privasi dan hak data. Pendaftaran PSE sedang dipersiapkan; NIB bukan TDPSE. Identitas ini mengacu pada proposal pengelola; alamat korespondensi lengkap akan dilengkapi berdasarkan dokumen badan usaha."},
 {title:"Data dan tujuan",text:"Kami memproses nama/panggilan, email, identitas autentikasi, peran, tanggal lahir untuk kelompok usia, pengaturan privasi dan bukti persetujuan wali. Data pendidikan meliputi sekolah/kelas yang diberikan, keanggotaan, tugas, jawaban, rekaman bila diunggah, hasil latihan, umpan balik, progres, XP, badge, karya, komentar, dan pesan kelas. Data transaksi meliputi pesanan, status pembayaran, saldo/komisi dan informasi pencairan yang diperlukan. Log keamanan, perangkat/sesi, alamat IP dan laporan digunakan untuk autentikasi, pencegahan penyalahgunaan serta penanganan insiden."},
 {title:"Dasar pemrosesan",text:"Pelaksanaan layanan yang diminta dan transaksi menggunakan dasar kontrak yang relevan; pembukuan menggunakan kewajiban hukum. Keamanan menggunakan kepentingan yang sah setelah penilaian kebutuhan dan keseimbangan hak. Pemrosesan data anak memerlukan persetujuan orang tua/wali yang diverifikasi. Publikasi profil/karya dewasa, analitik opsional dan bantuan AI menggunakan pilihan terpisah. Membaca notice bukan persetujuan untuk seluruh tujuan. Pilihan opsional tidak wajib untuk belajar manual."},
 {title:"Anak dan privasi aman",text:"Layanan akun belajar ditujukan bagi usia 6 tahun ke atas. Kelompok usia 6–9, 10–12, 13–15 dan 16–17 mendapat perlindungan anak; usia 18 ke atas dewasa. Akun anak baru dapat menggunakan layanan setelah persetujuan wali diverifikasi dan kesiapan profil risiko layanan dipastikan pengelola. Profil dan karya anak privat; karya dapat ditinjau guru pengajar yang berwenang. Kami tidak menyediakan iklan berbasis profil anak atau meminta lokasi presisi. Jangan mencantumkan identitas lengkap, alamat rumah atau data sensitif dalam karya, pesan atau jawaban."},
 {title:"Penerima, penyedia dan transfer",text:"Kode menggunakan Supabase untuk autentikasi/database/storage, Vercel untuk hosting, Redis/Upstash jika dikonfigurasi untuk cache dan batas permintaan, serta Midtrans untuk pembayaran. Adapter pencairan Xendit tersedia dalam kode; penggunaannya perlu diverifikasi sebelum diaktifkan. Bantuan AI dapat memakai DeepSeek, Groq, Google Gemini atau Anthropic sesuai konfigurasi. Materi tersemat YouTube, Google/Office dan gambar eksternal dapat menghubungi penyedia terkait ketika dimuat. Google OAuth digunakan bila Anda memilih masuk dengan Google. Kami tidak menjual data pribadi. Vendor, region, kontrak pemrosesan, subprosesor, retensi dan penggunaan data untuk pelatihan harus dikonfirmasi sebelum pemrosesan produksi diaktifkan."},
 {title:"Lokasi dan pelindungan transfer",text:"Konfigurasi deployment menetapkan fungsi Vercel sin1 (Singapura). Catatan proyek menyebut region Supabase Singapura; lokasi aktual database, backup, cache dan penyedia AI harus dicocokkan dengan dashboard dan kontrak. Jangan menganggap seluruh data berada di Indonesia. Transfer internasional harus dievaluasi menurut Pasal 56 UU PDP: tingkat pelindungan setara/lebih tinggi, pelindungan memadai yang mengikat bila diperlukan, atau persetujuan bila syarat sebelumnya tidak terpenuhi. Mengaktifkan bantuan AI bukan pengganti evaluasi transfer dan kontrak vendor."},
 {title:"AI dan keputusan guru",text:"AI opsional dapat menerima teks soal/rubrik/jawaban yang Anda kirim untuk menghasilkan saran. Hilangkan identitas yang tidak diperlukan. Skor/umpan balik AI bersifat advisory, dapat salah atau bias, dan memerlukan tinjauan manusia; guru menetapkan nilai akhir dan murid dapat meminta penjelasan/koreksi. Guru tidak boleh mengunggah data murid tanpa dasar pemrosesan serta persetujuan wali yang sesuai. Latihan objektif dengan kunci jawaban berbeda dari penilaian esai oleh AI."},
 {title:"Retensi, penghapusan dan keamanan",text:"Data akun/pendidikan disimpan untuk layanan aktif dan dihapus atau dianonimkan saat tidak diperlukan atau permintaan sah dipenuhi. Riwayat alat AI tersimpan maksimal 30 hari; saran penilaian yang menjadi bukti belajar ditinjau sesuai kebutuhan penilaian dan analitik opsional 90 hari menurut kebijakan operasional. Dokumen keuangan yang diwajibkan disimpan mengikuti hukum pembukuan; hanya bukti minimum yang dipertahankan. Penghapusan meliputi penonaktifan akses, pencabutan sesi, pembersihan data pribadi dan storage, dengan antrean pemulihan jika vendor gagal. Backup tidak langsung berubah; pengelola wajib menerapkan ulang daftar penghapusan setelah pemulihan. HTTPS/TLS, kontrol akses dan audit digunakan, tanpa menjanjikan risiko nol. Detail ada di Kebijakan Retensi Data."},
 {title:"Hak, keluhan dan pembaruan",text:"Anda dapat meminta akses/salinan, koreksi, penarikan persetujuan, pembatasan/penghentian, penghapusan, keberatan atas keputusan otomatis, dan hak lain yang berlaku melalui halo@bahasacerdas.com atau halaman Laporkan. Kami memverifikasi identitas secara proporsional; tidak meminta kata sandi. Wali dapat mencabut persetujuan melalui Privasi Akun. Pilihan publik/analitik dapat dicabut kapan saja. Pembaruan material meminta pengakuan notice terbaru dan, bila tujuan anak berubah, persetujuan wali baru. Insiden yang memenuhi ketentuan akan diberitahukan sesuai UU PDP."}
 ]},
 "syarat-ketentuan":{title:"Syarat & Ketentuan",sections:[
 {title:"Layanan dan akun",text:"BahasaCerdas menyediakan pembelajaran, latihan, kelas, karya, permainan pendidikan, alat AI opsional dan transaksi materi. Pengelola: CV Obah Mamah (Teras Kata). Gunakan data akun yang benar, lindungi kredensial, dan jangan menyamar sebagai orang lain. Akun belajar minimum 6 tahun; pengguna di bawah 18 membutuhkan wali berwenang dan akses sesuai kesiapan profil risiko layanan. Guru tidak otomatis menjadi wali. Informasi usia tidak boleh diubah untuk melewati perlindungan."},
 {title:"Karya, lisensi dan komunitas",text:"Anda tetap memiliki karya sendiri dan bertanggung jawab memiliki hak unggah. Anda memberi lisensi terbatas kepada pengelola untuk menyimpan, menampilkan kepada audiens yang diizinkan, dan menjalankan layanan. Lisensi ini tidak memberi hak menjual karya atau melatih model AI umum tanpa dasar dan izin tersendiri. Karya anak privat untuk pemilik/guru yang berwenang. Larangan meliputi eksploitasi anak, pornografi, ancaman, perundungan, ujaran melanggar hukum, pembocoran data pribadi, spam dan pelanggaran hak cipta. Pedoman komunitas menjelaskan proses laporan dan banding."},
 {title:"Moderasi dan hak koreksi",text:"Laporkan konten melalui /laporkan tanpa perlu akun. Pengelola dapat membatasi atau menghapus konten/akses berdasarkan keselamatan dan kewajiban hukum, mencatat alasan serta menyediakan kanal tindak lanjut. Keputusan dapat diminta ditinjau ulang melalui halo@bahasacerdas.com dengan nomor laporan. Bukti minimum dapat dipertahankan secara terbatas untuk sengketa/penegakan hukum, tanpa memublikasikan identitas pelapor."},
 {title:"AI, latihan dan penilaian",text:"AI memberi rekomendasi yang harus diperiksa guru, bukan keputusan final otomatis untuk konsekuensi pendidikan penting. Murid dapat meminta penjelasan, koreksi atau penilaian manual. Hasil latihan/simulasi BahasaCerdas bukan sertifikat resmi UKBI dari pemerintah dan tidak menjamin hasil ujian formal. Guru bertanggung jawab memeriksa kesesuaian rubrik, materi dan nilai."},
 {title:"Pembayaran dan pengakhiran",text:"Harga, durasi paket, batas penggunaan dan ketentuan transaksi ditampilkan sebelum pembayaran. Midtrans memproses pembayaran; kami tidak meminta kata sandi bank atau menyimpan nomor kartu penuh. Pembelian oleh anak harus melalui kewenangan wali yang sesuai. Permintaan pembatalan/pengembalian ditinjau berdasarkan transaksi dan hak konsumen yang berlaku. Penghapusan akun tersedia dengan verifikasi ulang; saldo, transaksi belum selesai, atau hak akses pembeli atas materi perlu diselesaikan agar hak pihak lain tetap terjaga."},
 {title:"Kontak dan hukum",text:"Hubungi halo@bahasacerdas.com untuk bantuan, sengketa atau hak data. Ketentuan ini tunduk pada hukum Indonesia dan tidak menghapus hak pengguna menurut peraturan yang berlaku. Perubahan material disampaikan sebelum berlaku, dengan pembaruan persetujuan bila diperlukan."}
 ]},
 "privasi-anak":{title:"Privasi untuk Anak",sections:[
 {title:"Data kamu untuk belajar",text:"Kami menyimpan akun, kelas, jawaban latihan, karya dan progres agar kamu bisa belajar. Tanggal lahir hanya untuk menentukan perlindungan usia, bukan untuk ditampilkan. Akun belajar mulai usia 6 tahun. Kalau kamu belum 18, ajak orang tua atau wali untuk membaca dan menyetujui layanan."},
 {title:"Kamu tetap punya pilihan",text:"Profil dan karya kamu privat. Guru yang mengajar dapat melihat tugas/karya untuk membimbingmu. Jangan menulis alamat rumah, nomor identitas, kata sandi atau cerita sensitif tentang orang lain. Tidak perlu membuka profil publik untuk belajar. Kami tidak membuat profil iklan berdasarkan perilaku anak."},
 {title:"AI bisa salah",text:"Bantuan AI hanya digunakan jika wali mengizinkan. AI memberi saran; guru memeriksa dan menentukan hasil akhir. Kamu boleh bertanya mengapa mendapat nilai tertentu, meminta koreksi, dan memilih penilaian manual."},
 {title:"Kalau merasa tidak aman",text:"Gunakan halaman Laporkan untuk konten, komentar, pesan atau masalah privasi. Kamu tidak perlu masuk untuk melapor. Kamu dan wali bisa meminta salinan, perbaikan atau penghapusan data lewat halo@bahasacerdas.com. Wali bisa mencabut persetujuan dari Privasi Akun."}
 ]},
 "pemberitahuan-wali":{title:"Pemberitahuan Persetujuan Orang Tua / Wali",sections:[
 {title:"Siapa yang dapat menyetujui",text:"Orang tua/wali berwenang berusia 18 tahun atau lebih masuk dengan email terverifikasi yang dituju dalam undangan. Akun anak, peran guru, atau tautan undangan saja tidak dapat mengesahkan consent. Pengelola memeriksa hubungan/kewenangan wali melalui kanal independen seperti administrasi sekolah. Referensi hasil pemeriksaan dicatat; jangan mengirim KTP melalui karya atau obrolan."},
 {title:"Tujuan dan bukti",text:"Persetujuan layanan anak mencakup akun, kelas, tugas, latihan, karya privat, umpan balik, progres dan pengamanan layanan. Bantuan AI memiliki pilihan terpisah dan tidak wajib. Bukti memuat subjek anak, wali, tujuan, tindakan, metode, waktu, versi notice/ketentuan, referensi verifikasi, dan pencabutan. Kontak wali dibatasi untuk pemrosesan undangan/consent. Akun anak tidak diaktifkan sebelum verifikasi dan kesiapan profil risiko layanan."},
 {title:"Hak dan penarikan",text:"Wali dapat meninjau status serta mencabut consent melalui Privasi Akun. Pencabutan menghentikan akses layanan anak dan bantuan AI, tanpa menghapus kewajiban penyimpanan bukti minimum yang sah. Mintalah akses, koreksi, penghapusan atau penilaian manusia kepada halo@bahasacerdas.com. Perubahan tujuan/versi material membutuhkan consent baru. Anak yang mencapai usia dewasa mengelola pilihan sendiri setelah pengakuan notice terbaru."},
 {title:"Penyedia dan transfer",text:"Baca Kebijakan Privasi untuk penyedia hosting, autentikasi, cache, pembayaran dan AI. Sebagian pemrosesan dapat berlangsung di luar Indonesia. Pengelola harus memverifikasi kontrak, retensi dan pelindungan transfer sebelum digunakan. Memberi consent tidak berarti menyetujui iklan berbasis perilaku, publikasi anak, atau penggunaan karya untuk pelatihan model umum."}
 ]},
 "pedoman-komunitas":{title:"Pedoman Komunitas & Karya Pengguna",sections:[
 {title:"Berkarya dengan aman",text:"Hormati orang lain, gunakan karya sendiri atau materi berlisensi, dan hindari data pribadi. Dilarang memuat eksploitasi anak, pornografi, kekerasan/ancaman, perundungan, ujaran melanggar hukum, penipuan, spam atau pembocoran identitas. Hak cipta tetap pada pemilik; audiens mengikuti pilihan privasi dan batas perlindungan anak."},
 {title:"Laporan publik",text:"Halaman /laporkan tersedia tanpa akun. Sertakan ID/tautan, kategori dan penjelasan. Kontak tindak lanjut opsional. Jangan melampirkan salinan konten eksploitasi seksual anak. Simpan nomor laporan. Laporan keselamatan anak/ancaman ditangani prioritas; pengelola dapat melakukan pembatasan sementara dan eskalasi kepada pihak berwenang sesuai kebutuhan."},
 {title:"Keputusan dan banding",text:"Moderator memeriksa konteks, kewenangan dan risiko; keputusan berupa penghapusan, penolakan laporan dengan alasan, atau eskalasi. Alasan dan waktu dicatat, dengan pemberitahuan kepada pelapor berakun dan pemilik konten bila aman serta memungkinkan. Minta tinjauan ulang ke halo@bahasacerdas.com dengan nomor laporan. Identitas pelapor dilindungi. Perintah otoritas mengikuti tenggat hukum yang berlaku, bukan sekadar target layanan internal."}
 ]},
 "retensi-data":{title:"Kebijakan Retensi & Penghapusan Data",sections:[
 {title:"Batas penyimpanan",text:"Data akun dan pembelajaran diperlukan selama akun aktif. Pengelola meninjau kebutuhan akun tidak aktif tiap tahun; tidak menyimpan jawaban/karya pribadi tanpa batas setelah penghapusan sah. Riwayat alat AI tersimpan maksimal 30 hari; saran penilaian pada jawaban mengikuti kebutuhan bukti belajar dan tinjauan tahunan; analitik opsional 90 hari; undangan wali kedaluwarsa setelah 7 hari dan data kontak undangan yang tidak selesai dibersihkan dalam 30 hari. Target log teknis 30 hari dan laporan terselesaikan 180 hari, kecuali penyelidikan/penahanan hukum yang terdokumentasi."},
 {title:"Pengecualian terbatas",text:"Bukti consent dan audit minimum dipertahankan untuk pembuktian dan penyelesaian sengketa, ditinjau tahunan dan dibatasi aksesnya. Dokumen pembukuan/keuangan yang diwajibkan memiliki jangka simpan sesuai hukum, umumnya 10 tahun untuk dokumen yang termasuk kewajiban tersebut; ketentuan ini tidak berlaku otomatis untuk seluruh data pengguna. Catatan keuangan ditautkan pada identitas akun yang telah dianonimkan ketika profil dihapus. Dasar, penanggung jawab dan tanggal berakhir pengecualian harus dicatat."},
 {title:"Apa yang dilakukan saat akun dihapus",text:"Akses aplikasi dinonaktifkan, refresh session dicabut, identitas profil serta data pribadi terkait dibersihkan, hasil belajar/pesan/karya pribadi dihapus, storage milik akun dibersihkan melalui API vendor, dan identitas peserta permainan bersama dianonimkan. Token berbagi milik akun dicabut. Bukti minimum mencatat status pekerjaan, tanpa kata sandi/token sesi. Kegagalan vendor masuk antrean pemulihan dan tidak boleh dianggap penghapusan selesai. Karya berbayar yang sudah dibeli dan saldo berjalan memerlukan penyelesaian untuk menjaga hak pihak lain."},
 {title:"Backup, cache dan vendor",text:"Cache identitas/feed dibersihkan saat pilihan dicabut atau akun dihapus; sumber database tetap menentukan akses. Backup berakhir mengikuti siklus vendor yang harus dikonfirmasi pengelola. Setiap pemulihan wajib menerapkan ulang catatan penghapusan sebelum layanan dibuka. Pengelola menindaklanjuti penghapusan pada vendor dan data ekspor yang berada dalam kendalinya; salinan yang sudah disimpan pihak lain memerlukan penanganan sesuai kewenangan."}
 ]}
};
export const noticeVersion = NOTICE_VERSION;
