import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const UKBI_QUESTIONS = [
  {
    seksi: "MENDENGARKAN",
    text: "Perekaman audio tentang dialog di pasar antara penjual dan pembeli.听完对话，回答问题。",
    passage: "Dialog: Penjual: 'Bu, mau beli apa hari ini?' Pembeli: 'Saya mau beli ikan yang segar, Bu.' Penjual: 'Ikan yang ini baru datang tadi pagi, Bu. Masih segar.' Pembeli: 'Berapa harganya per kilogram?' Penjual: 'Rp45.000 per kilogram, Bu.'",
    type: "PILIHAN_GANDA",
    options: [
      { id: "A", text: "Ikan yang dibeli sudah tidak segar" },
      { id: "B", text: "Harga ikan Rp35.000 per kilogram" },
      { id: "C", text: "Ikan yang dijual adalah ikan yang baru datang pagi ini" },
      { id: "D", text: "Pembeli tidak jadi membeli ikan" },
    ],
    correctAnswer: "C",
    explanation: "Berdasarkan dialog, penjual menyatakan 'Ikan yang ini baru datang tadi pagi, Bu.' Artinya ikan yang dijual adalah ikan yang baru.",
    difficulty: "MEDIUM",
    cognitive: "PEMAHAMAN",
    domain: "SOSIAL",
    keywords: ["dialog", "pasar", "berbelanja"],
    isVerified: true,
  },
  {
    seksi: "MENDENGARKAN",
    text: "Perekaman monolog tentang kebijakan pemerintah dalam bidang pendidikan.听完独白，回答问题。",
    passage: "Monolog: 'Pemerintah telah menetapkan kebijakan baru dalam bidang pendidikan. Kebijakan ini mewajibkan setiap sekolah untuk memiliki perpustakaan digital. Dengan adanya perpustakaan digital, siswa dapat mengakses buku-buku elektronik kapan saja dan di mana saja. Kebijakan ini diharapkan dapat meningkatkan literasi siswa di era digital.'",
    type: "PILIHAN_GANDA",
    options: [
      { id: "A", text: "Kebijakan baru tentang perpustakaan digital bersifat opsional" },
      { id: "B", text: "Perpustakaan digital hanya dapat diakses di sekolah" },
      { id: "C", text: "Tujuan kebijakan adalah meningkatkan literasi siswa" },
      { id: "D", text: "Kebijakan ini hanya untuk sekolah menengah" },
    ],
    correctAnswer: "C",
    explanation: "Monolog menyatakan 'Kebijakan ini diharapkan dapat meningkatkan literasi siswa di era digital.'",
    difficulty: "EASY",
    cognitive: "PEMAHAMAN",
    domain: "VOKASIONAL",
    keywords: ["kebijakan", "pendidikan", "perpustakaan digital"],
    isVerified: true,
  },
  {
    seksi: "MENDENGARKAN",
    text: "Perekaman dialog dalam sebuah wawancara kerja.听完对话，回答问题。",
    passage: "Pewawancara: 'Apa yang membuat Anda tertarik dengan posisi ini?' Pelamar: 'Saya tertarik karena perusahaan ini memiliki visi yang sejalan dengan passion saya di bidang teknologi pendidikan.' Pewawancara: 'Berapa lama Anda sudah berkecimpung di bidang tersebut?' Pelamar: 'Sekitar lima tahun, Pak.'",
    type: "PILIHAN_GANDA",
    options: [
      { id: "A", text: "Pelamar belum memiliki pengalaman kerja" },
      { id: "B", text: "Pelamar tertarik karena visi perusahaan sesuai passionnya" },
      { id: "C", text: "Pewawancara menolak pelamar" },
      { id: "D", text: "Posisi yang dilamar adalah di bidang keuangan" },
    ],
    correctAnswer: "B",
    explanation: "Pelamar menyatakan tertarik karena 'perusahaan ini memiliki visi yang sejalan dengan passion saya di bidang teknologi pendidikan.'",
    difficulty: "MEDIUM",
    cognitive: "ANALISIS",
    domain: "SOSIAL",
    keywords: ["wawancara", "kerja", "teknologi"],
    isVerified: true,
  },
  {
    seksi: "MERESPONS_KAIDAH",
    text: "Perhatikan kalimat berikut dan tentukan kesalahan kaidahnya! Kalimat: 'Semua mahasiswa wajib menyerahkan ijasah yang dilegalisir.'",
    type: "PILIHAN_GANDA",
    options: [
      { id: "A", text: "Semua → seluruh" },
      { id: "B", text: "ijasah → ijazah" },
      { id: "C", text: "dilegalisir → dilegalisasi" },
      { id: "D", text: "tidak ada kesalahan" },
    ],
    correctAnswer: "C",
    explanation: "Bentuk baku dari 'dilegalisir' adalah 'dilegalisasi'. Awalan di- pada kata kerja diikuti akhiran -si untuk bentuk pasif.",
    difficulty: "MEDIUM",
    cognitive: "EVALUASI",
    domain: "SOSIAL",
    keywords: ["kaidah", "bentuk baku", "legalisasi"],
    isVerified: true,
  },
  {
    seksi: "MERESPONS_KAIDAH",
    text: "Perhatikan kalimat berikut! Kalimat: 'Revisi itu berkaitan erat dengan perubahan anggaran yang sedang dirundingkan oleh kami dengan pihak kontraktor.'",
    type: "PILIHAN_GANDA",
    options: [
      { id: "A", text: "Berkaitan → terkait" },
      { id: "B", text: "dirundingkan → kami rundingkan" },
      { id: "C", text: "oleh kami dihilangkan" },
      { id: "D", text: "Kalimat ini sudah menggunakan kaidah yang tepat" },
    ],
    correctAnswer: "C",
    explanation: "Frasa 'oleh kami' perlu dihilangkan karena penggunaan 'kami' sudah menunjukkan pelaku. Kalimat menjadi tidak ekonomis.",
    difficulty: "HARD",
    cognitive: "EVALUASI",
    domain: "SOSIAL",
    keywords: ["kaidah", "kehematan kalimat", "pronomina"],
    isVerified: true,
  },
  {
    seksi: "MERESPONS_KAIDAH",
    text: "Perhatikan penggunaan kata berikut! 'Rimpang lengkuas dapat digunakan untuk ramuan obat.'",
    type: "PILIHAN_GANDA",
    options: [
      { id: "A", text: "Lengkuas → Langkuas" },
      { id: "B", text: "Rimpang →rimpang" },
      { id: "C", text: "Ramuan → peramu" },
      { id: "D", text: "Kata-kata tersebut sudah tepat" },
    ],
    correctAnswer: "A",
    explanation: "Bentuk baku yang benar adalah 'langkuas' (bukan 'lengkuas'). KBBI menyediakan bentuk 'langkuas'.",
    difficulty: "EASY",
    cognitive: "MEMAHAMAN",
    domain: "SOSIAL",
    keywords: ["ejaan", "baku", "KBBI"],
    isVerified: true,
  },
  {
    seksi: "MERESPONS_KAIDAH",
    text: "Perhatikan kalimat! 'Seseorang harus mengikuti program pendidikan prakarsa sendiri selama dua tahun.'",
    type: "PILIHAN_GANDA",
    options: [
      { id: "A", text: "Prakarsa → prakarsai" },
      { id: "B", text: "Selama → selama-masa" },
      { id: "C", text: "Seseorang → setiap orang" },
      { id: "D", text: "Tidak ada kesalahan" },
    ],
    correctAnswer: "A",
    explanation: "Bentuk baku yang benar adalah 'prakarsai' karena kata 'program' memerlukan kata kerja yang berawalan me-.",
    difficulty: "HARD",
    cognitive: "EVALUASI",
    domain: "SOSIAL",
    keywords: ["bentuk kata", "awalan me-"],
    isVerified: true,
  },
  {
    seksi: "MERESPONS_KAIDAH",
    text: "Bacalah percakapan berikut! X: 'Pengerjaan proyek jalan tol itu menyita tenaga dan pikirannya.' Y: 'Ya, akibatnya ia hampir tidak mempedulikan hal lain.'",
    type: "PILIHAN_GANDA",
    options: [
      { id: "A", text: "Menyita → menyita tenaga dan pikiran" },
      { id: "B", text: "Mempedulikan → kepedulian" },
      { id: "C", text: "Ia → dirinya" },
      { id: "D", text: "Tidak ada kesalahan" },
    ],
    correctAnswer: "B",
    explanation: "Kata 'mempedulikan' kurang tepat. Bentuk yang lebih baik adalah 'memperdulikan' atau menggunakan 'peduli'.",
    difficulty: "MEDIUM",
    cognitive: "EVALUASI",
    domain: "SOSIAL",
    keywords: ["pilihan kata", "pronomina"],
    isVerified: true,
  },
  {
    seksi: "MEMBACA",
    text: "Bacalah wacana berikut dan jawablah pertanyaan! Wacana: 'Burung-burung heron sering bertengger di atas punggung badak. Mereka melakukan hal tersebut untuk mencari kutu dan parasit di kulit badak. Hubungan ini bersifat simbiosis mutualisme karena kedua pihak diuntungkan.'",
    passage: "Berdasarkan wacana di atas, hubungan antara burung heron dan badak termasuk simbiosis...",
    type: "PILIHAN_GANDA",
    options: [
      { id: "A", text: "Parasitisme" },
      { id: "B", text: "Komensalisme" },
      { id: "C", text: "Mutualisme" },
      { id: "D", text: "Predasi" },
    ],
    correctAnswer: "C",
    explanation: "Wacana secara eksplisit menyatakan 'Hubungan ini bersifat simbiosis mutualisme karena kedua pihak diuntungan.'",
    difficulty: "EASY",
    cognitive: "PEMAHAMAN",
    domain: "SOSIAL",
    passageType: "ilmiah",
    wordCount: 45,
    keywords: ["simbiosis", "mutualisme", "ekologi"],
    isVerified: true,
  },
  {
    seksi: "MEMBACA",
    text: "Perhatikan paragraf berikut! '(1) Semua Ortsmand telenyporaea tentu berharap agar kelak arthinya sukses. (2) Indikator dari kesuksesan biasanya dilihat dari pekerjaan. (3) Ortjmand yang sibuk bekerja kadang tidak memikirkan hal lain...'",
    passage: "Paragraf di atas menggunakan kata tidak baku. Kata tidak baku yang terdapat pada paragraf tersebut adalah...",
    type: "PILIHAN_GANDA",
    options: [
      { id: "A", text: "Ortsmand, telenyporaea, arthinya, Ortjmand" },
      { id: "B", text: "Semua, sukses, indikator" },
      { id: "C", text: "Berasal dari kata tidak baku dalam kalimat (2)" },
      { id: "D", text: "Kata tidak baku hanya pada kalimat (1)" },
    ],
    correctAnswer: "A",
    explanation: "Kalimat (1) menggunakan Ortsmand, telenyporaea, arthinya, dan kalimat (3) Ortjmand yang merupakan bentuk tidak baku.",
    difficulty: "HARD",
    cognitive: "ANALISIS",
    domain: "SOSIAL",
    passageType: "ilmiah",
    wordCount: 60,
    keywords: ["kata baku", "tidak baku"],
    isVerified: true,
  },
  {
    seksi: "MEMBACA",
    text: "Bacalah wacana tentang perubahan iklim. 'Perubahan iklim global menyebabkan peningkatan suhu bumi sebesar 1,5 derajat Celsius dalam dua dekade terakhir. Hal ini berdampak pada ekosistem laut, pertanian, dan kesehatan masyarakat.'",
    passage: "Apa dampak utama perubahan iklim berdasarkan wacana?",
    type: "PILIHAN_GANDA",
    options: [
      { id: "A", text: "Penurunan suhu bumi" },
      { id: "B", text: "Peningkatan suhu bumi yang berdampak pada ekosistem, pertanian, dan kesehatan" },
      { id: "C", text: "Perubahan hanya pada ekosistem laut" },
      { id: "D", text: "Tidak ada dampak signifikan" },
    ],
    correctAnswer: "B",
    explanation: "Wacana jelas menyebutkan perubahan iklim menyebabkan peningkatan suhu dan berdampak pada tiga sektor: ekosistem laut, pertanian, dan kesehatan.",
    difficulty: "EASY",
    cognitive: "PEMAHAMAN",
    domain: "SOSIAL",
    passageType: "ilmiah",
    wordCount: 38,
    keywords: ["perubahan iklim", "dampak", "lingkungan"],
    isVerified: true,
  },
  {
    seksi: "MEMBACA",
    text: "Perhatikan kutipan teks berikut! 'Zat antioksidan penting karena mampu menetralisir kelainan organ tubuh.'",
    passage: "Bentukan kata baku yang tepat untuk kata bergaris bawah dalam kalimat tersebut adalah...",
    type: "PILIHAN_GANDA",
    options: [
      { id: "A", text: "Menetralisasi" },
      { id: "B", text: "Menetralkan" },
      { id: "C", text: "Penetralan" },
      { id: "D", text: "Netralisasi" },
    ],
    correctAnswer: "A",
    explanation: "Bentuk baku yang benar adalah 'menetralisasi' dengan akhiran -si pada kata kerja berawalan me-.",
    difficulty: "MEDIUM",
    cognitive: "EVALUASI",
    domain: "SOSIAL",
    passageType: "ilmiah",
    wordCount: 18,
    keywords: ["kata baku", "awalan me-"],
    isVerified: true,
  },
  {
    seksi: "MEMBACA",
    text: "Bacalah kutipan berikut! 'Ketidakhadiran 王教授 dalam pertemuan itu menimbulkan spekulasi di kalangan akademisi.'",
    passage: "Kata baku yang tepat untuk menggantikan 'ketidakhadiran' adalah...",
    type: "PILIHAN_GANDA",
    options: [
      { id: "A", text: "Ketidak hadiran" },
      { id: "B", text: "Berhalangan" },
      { id: "C", text: "Tidak hadir" },
      { id: "D", text: "Ketidak hadiran王教授" },
    ],
    correctAnswer: "B",
    explanation: "'Berhalangan' adalah kata baku yang menunjukkan ketidakhadiran karena sesuatu hal.",
    difficulty: "HARD",
    cognitive: "EVALUASI",
    domain: "SOSIAL",
    passageType: "ilmiah",
    wordCount: 20,
    keywords: ["kata baku", "ejaan"],
    isVerified: true,
  },
  {
    seksi: "MEMBACA",
    text: "Bacalah paragraf berikut! 'Kemajuan teknologi informasi telah mengubah cara manusia bekerja dan berkomunikasi. Revolusi industri 4.0 membawa era digitalisasi yang memungkinkan semua hal dapat dilakukan secara daring. Namun, kesenjangan digital tetap menjadi tantangan besar.'",
    passage: "Apa topik utama paragraf tersebut?",
    type: "PILIHAN_GANDA",
    options: [
      { id: "A", text: "Revolusi industri 4.0" },
      { id: "B", text: "Kemajuan teknologi informasi dan tantangan di era digital" },
      { id: "C", text: "Cara manusia berkomunikasi" },
      { id: "D", text: "Kesenjangan digital saja" },
    ],
    correctAnswer: "B",
    explanation: "Paragraf membahas kemajuan teknologi informasi yang mengubah cara kerja dan komunikasi, serta kesenjangan digital sebagai tantangan.",
    difficulty: "EASY",
    cognitive: "PEMAHAMAN",
    domain: "SOSIAL",
    passageType: "ilmiah",
    wordCount: 52,
    keywords: ["teknologi", "digital", "kesenjangan"],
    isVerified: true,
  },
  {
    seksi: "MEMBACA",
    text: "Perhatikan paragraf argumentasi! 'Penggunaan plastik sekali pakai seharusnya dilarang karena mencemari lingkungan. Plastik membutuhkan waktu ratusan tahun untuk terurai. Jika tidak ada tindakan nyata, laut akan penuh dengan sampah plastik.'",
    passage: "Jenis paragraf apakah paragraf di atas?",
    type: "PILIHAN_GANDA",
    options: [
      { id: "A", text: "Paragraf deskripsi" },
      { id: "B", text: "Paragraf persuasi/argumentasi" },
      { id: "C", text: "Paragraf narasi" },
      { id: "D", text: "Paragraf eksposisi" },
    ],
    correctAnswer: "B",
    explanation: "Paragraf tersebut mengandung ajakan untuk melakukan sesuatu (melarang plastik sekali pakai) dengan alasan-alasan yang mendukung, ciri khas paragraf persuasi.",
    difficulty: "MEDIUM",
    cognitive: "ANALISIS",
    domain: "SOSIAL",
    passageType: "ilmiah",
    wordCount: 45,
    keywords: ["paragraf", "argumentasi", "persuasi"],
    isVerified: true,
  },
  {
    seksi: "MERESPONS_KAIDAH",
    text: "Perhatikan penggunaan kata! 'Kamu mau memesan sirop nanas.'",
    type: "PILIHAN_GANDA",
    options: [
      { id: "A", text: "Sirop → sirup" },
      { id: "B", text: "Nanas → nanas" },
      { id: "C", text: "Mememesan → memesan" },
      { id: "D", text: "Sudah tepat" },
    ],
    correctAnswer: "A",
    explanation: "Bentuk baku adalah 'sirup' (bukan 'sirop') dan 'nanas' (bukan 'nanas')",
    difficulty: "EASY",
    cognitive: "MEMAHAMAN",
    domain: "SOSIAL",
    keywords: ["ejaan", "baku"],
    isVerified: true,
  },
  {
    seksi: "MERESPONS_KAIDAH",
    text: "Kalimat: 'Zat anti-oksidan penting bagi tubuh manusia.'",
    type: "PILIHAN_GANDA",
    options: [
      { id: "A", text: "Anti-oksidan → antioksidan" },
      { id: "B", text: "Penting → betapa penting" },
      { id: "C", text: "Tubuh → badan" },
      { id: "D", text: "Tidak ada kesalahan" },
    ],
    correctAnswer: "A",
    explanation: "Bentuk baku adalah 'antioksidan' tanpa tanda hubung karena merupakan bentuk serapan yang sudah baku.",
    difficulty: "MEDIUM",
    cognitive: "EVALUASI",
    domain: "SOSIAL",
    keywords: ["serapan", "ejaan", "baku"],
    isVerified: true,
  },
  {
    seksi: "MERESPONS_KAIDAH",
    text: "Bacalah kalimat berikut! 'Laporan keuangan itu sudah di-evaluate oleh tim auditor.'",
    type: "PILIHAN_GANDA",
    options: [
      { id: "A", text: "Di-evaluate → dievaluasi" },
      { id: "B", text: "Tim auditor → tim pengaudit" },
      { id: "C", text: "Laporan keuangan → lapkeu" },
      { id: "D", text: "Sudah → telah" },
    ],
    correctAnswer: "A",
    explanation: "Bentuk baku adalah 'dievaluasi'. Kata serapan yang berakhiran -e menjadi -i dalam bentuk aktif, dan -asi dalam bentuk pasif.",
    difficulty: "HARD",
    cognitive: "EVALUASI",
    domain: "SOSIAL",
    keywords: ["kata serapan", "baku"],
    isVerified: true,
  },
  {
    seksi: "MEMBACA",
    text: "Bacalah kutipan berikut! 'UNESCO telah menetapkan bahasa Indonesia sebagai bahasa resmi dalam sidang umum tahun 2019.'",
    passage: "Informasi penting dari kutipan tersebut adalah...",
    type: "PILIHAN_GANDA",
    options: [
      { id: "A", text: "UNESCO adalah organisasi pendidikan" },
      { id: "B", text: "Bahasa Indonesia ditetapkan sebagai bahasa resmi oleh UNESCO pada tahun 2019" },
      { id: "C", text: "Sidang umum UNESCO membahas pendidikan" },
      { id: "D", text: "Bahasa Indonesia adalah bahasa resmi" },
    ],
    correctAnswer: "B",
    explanation: "Kalimat utama adalah 'UNESCO telah menetapkan bahasa Indonesia sebagai bahasa resmi' dengan keterangan waktu 'dalam sidang umum tahun 2019'.",
    difficulty: "EASY",
    cognitive: "PEMAHAMAN",
    domain: "SOSIAL",
    passageType: "berita",
    wordCount: 22,
    keywords: ["bahasa Indonesia", "UNESCO"],
    isVerified: true,
  },
  {
    seksi: "MEMBACA",
    text: "Perhatikan paragraf berikut! 'Teknologi kecerdasan buatan (AI) semakin berkembang pesat. Berbagai sektor mulai memanfaatkan AI untuk meningkatkan efisiensi. Namun, di sisi lain, banyak pekerjaan yang tergantikan oleh mesin.'",
    passage: "Kata penghubung yang menunjukkan hubungan kontras (pertentangan) dalam paragraf tersebut adalah...",
    type: "PILIHAN_GANDA",
    options: [
      { id: "A", text: "Namun" },
      { id: "B", text: "Dan" },
      { id: "C", text: "Karena" },
      { id: "D", text: "Untuk" },
    ],
    correctAnswer: "A",
    explanation: "Kata 'Namun' berfungsi sebagai konjungtor yang menunjukkan pertentangan antara manfaat AI dan dampak negatifnya.",
    difficulty: "EASY",
    cognitive: "ANALISIS",
    domain: "SOSIAL",
    passageType: "ilmiah",
    wordCount: 48,
    keywords: ["konjungsi", "pertentangan", "koherensi"],
    isVerified: true,
  },
  {
    seksi: "MENDENGARKAN",
    text: "Perekaman monolog tentang pelestarian budaya. 'Upaya pelestarian budaya daerah perlu dilakukan sejak dini. Pemerintah daerah telah mengalokasikan dana khusus untuk program ini. Namun, partisipasi masyarakat masih sangat rendah.'",
    passage: "Apa kendala utama dalam pelestarian budaya menurut monolog?",
    type: "PILIHAN_GANDA",
    options: [
      { id: "A", text: "Dana tidak tersedia" },
      { id: "B", text: "Partisipasi masyarakat yang rendah" },
      { id: "C", text: "Budaya daerah tidak penting" },
      { id: "D", text: "Pemerintah tidak peduli" },
    ],
    correctAnswer: "B",
    explanation: "Monolog menyatakan 'partisipasi masyarakat masih sangat rendah' sebagai kendala.",
    difficulty: "EASY",
    cognitive: "PEMAHAMAN",
    domain: "SOSIAL",
    keywords: ["budaya", "pelestarian", "partisipasi"],
    isVerified: true,
  },
  {
    seksi: "MENDENGARKAN",
    text: "Dialog di antara dua kolega tentang proyek. 'Proyek ini deadline-nya minggu depan. Kita perlu mempercepat progress.' 'Kalau menurutku, kita bisa kerjakan secara paralel.'",
    passage: "Apa strategi yang disarankan dalam dialog tersebut?",
    type: "PILIHAN_GANDA",
    options: [
      { id: "A", text: "Menunda deadline" },
      { id: "B", text: "Bekerja secara paralel untuk mempercepat" },
      { id: "C", text: "Menambah jumlah tim" },
      { id: "D", text: "Mengurangi fitur proyek" },
    ],
    correctAnswer: "B",
    explanation: "Kolega menyarankan untuk 'bekerja secara paralel' agar mempercepat progress.",
    difficulty: "EASY",
    cognitive: "PEMAHAMAN",
    domain: "SOSIAL",
    keywords: ["dialog", "pekerjaan", "strategi"],
    isVerified: true,
  },
  {
    seksi: "MEMBACA",
    text: "Bacalah wacana! 'Guru profesional adalah guru yang memiliki kompetensi pedagogik, profesional, sosial, dan kepribadian. Keempat kompetensi ini harus dimiliki dan terus dikembangkan.'",
    passage: "Berdasarkan wacana, kompetensi guru profesional terdiri atas...",
    type: "PILIHAN_GANDA",
    options: [
      { id: "A", text: "Dua kompetensi" },
      { id: "B", text: "Tiga kompetensi" },
      { id: "C", text: "Empat kompetensi" },
      { id: "D", text: "Lima kompetensi" },
    ],
    correctAnswer: "C",
    explanation: "Wacana secara eksplisit menyebutkan 'empat kompetensi: pedagogik, profesional, sosial, dan kepribadian.'",
    difficulty: "EASY",
    cognitive: "MEMAHAMAN",
    domain: "SOSIAL",
    passageType: "ilmiah",
    wordCount: 32,
    keywords: ["kompetensi", "guru", "profesional"],
    isVerified: true,
  },
  {
    seksi: "MEMBACA",
    text: "Wacana: 'Permainan tradisional seperti gobak sodor, engklek, dan congklak mulai jarang dimainkan anak-anak. Hal ini dikhawatirkan dapat mengancam kelestarian warisan budaya.'",
    passage: "Apa ancaman yang dikhawatirkan dalam wacana?",
    type: "PILIHAN_GANDA",
    options: [
      { id: "A", text: "Anak-anak tidak suka bermain" },
      { id: "B", text: "Permainan tradisional hilang karena jarang dimainkan" },
      { id: "C", text: "Gobak sodor dilarang pemerintah" },
      { id: "D", text: "Warisan budaya tidak penting" },
    ],
    correctAnswer: "B",
    explanation: "Wacana menyatakan permainan tradisional 'mulai jarang dimainkan' yang 'dikhawatirkan dapat mengancam kelestarian warisan budaya.'",
    difficulty: "EASY",
    cognitive: "PEMAHAMAN",
    domain: "SOSIAL",
    passageType: "berita",
    wordCount: 35,
    keywords: ["permainan tradisional", "warisan budaya"],
    isVerified: true,
  },
  {
    seksi: "MEMBACARA",
    text: "Bacalah wacana! 'Pemanasan global menyebabkan gunung-gunung es di kutub mencair. Kenaikan permukaan laut mengancam kota-kota pesisir. Mitigasi perubahan iklim perlu dilakukan secara global.'",
    passage: "Ide pokok paragraph tersebut adalah...",
    type: "PILIHAN_GANDA",
    options: [
      { id: "A", text: "Gunung es mencair" },
      { id: "B", text: "Pemanasan global dan ancaman kenaikan permukaan laut" },
      { id: "C", text: "Kota pesisir tenggelam" },
      { id: "D", text: "Perubahan iklim hanya di kutub" },
    ],
    correctAnswer: "B",
    explanation: "Seluruh kalimat mendukung satu ide pokok: pemanasan global menyebabkan naiknya permukaan laut.",
    difficulty: "EASY",
    cognitive: "ANALISIS",
    domain: "SOSIAL",
    passageType: "ilmiah",
    wordCount: 32,
    keywords: ["pemanasan global", "perubahan iklim"],
    isVerified: true,
  },
];

const TKA_QUESTIONS = [
  {
    kompetensi: "PEDAGOGIK",
    subKompetensi: "Perkembangan Peserta Didik",
    text: "Siswa usia 12-14 tahun sedang dalam masa pubertas. Ciri khas perkembangan pada masa ini adalah...",
    type: "PILIHAN_GANDA",
    options: [
      { id: "A", text: "Mulai memahami operasi formal" },
      { id: "B", text: "Perubahan biologis dan emosional yang signifikan" },
      { id: "C", text: "Sudah memiliki kemandirian penuh" },
      { id: "D", text: "Perkembangan kognitif sudah maksimal" },
    ],
    correctAnswer: "B",
    explanation: "Masa pubertas (12-14 tahun) ditandai dengan perubahan biologis (hormonal, fisik) dan emosional yang signifikan sesuai teori perkembangan Piaget dan Erikson.",
    difficulty: "MEDIUM",
    weight: 1.0,
    year: 2024,
    source: "UKPPPG 2024",
    isVerified: true,
  },
  {
    kompetensi: "PEDAGOGIK",
    subKompetensi: "Desain Pembelajaran",
    text: "Guru akan mengajarkan konsep pecahan. Strategi pembelajaran yang paling tepat adalah...",
    type: "PILIHAN_GANDA",
    options: [
      { id: "A", text: "Memberikan definisi langsung dan menghafalkan" },
      { id: "B", text: "Menggunakan manipulatif benda konkret (kertas, buah)" },
      { id: "C", text: "Menyuruh siswa membaca buku teks sendiri" },
      { id: "D", text: "Langsung memberikan latihan soal" },
    ],
    correctAnswer: "B",
    explanation: "Pembelajaran matematika kontekstual menggunakan benda konkret sesuai teori Bruner (enaktif, ikonik, simbolik).",
    difficulty: "MEDIUM",
    weight: 1.0,
    year: 2024,
    source: "UKPPPG 2024",
    isVerified: true,
  },
  {
    kompetensi: "PEDAGOGIK",
    subKompetensi: "Penilaian Pembelajaran",
    text: "Kriteria Ketuntasan Minimal (KKM) ditentukan berdasarkan...",
    type: "PILIHAN_GANDA",
    options: [
      { id: "A", text: "Harapan guru saja" },
      { id: "B", text: "Kompleksitas KD, daya dukung, dan intake siswa" },
      { id: "C", text: "Standar pemerintah yang sama untuk semua sekolah" },
      { id: "D", text: "Nilai rata-rata siswa tahun sebelumnya" },
    ],
    correctAnswer: "B",
    explanation: "KKM ditentukan berdasarkan tiga aspek: kompleksitas KD, daya dukung sekolah, dan intake (kemampuan awal) siswa.",
    difficulty: "MEDIUM",
    weight: 1.0,
    year: 2024,
    source: "Permendikbud",
    isVerified: true,
  },
  {
    kompetensi: "PEDAGOGIK",
    subKompetensi: "Pengembangan Kurikulum",
    text: "Kurikulum Merdeka mengutamakan...",
    type: "PILIHAN_GANDA",
    options: [
      { id: "A", text: "Penguasaan semua mata pelajaran secara merata" },
      { id: "B", text: "Pembelajaran berdiferensiasi sesuai kebutuhan siswa" },
      { id: "C", text: "Ujian nasional sebagai satu-satunya ukuran keberhasilan" },
      { id: "D", text: "Buku paket sebagai satu-satunya sumber belajar" },
    ],
    correctAnswer: "B",
    explanation: "Kurikulum Merdeka menekankan pembelajaran berdiferensiasi sesuai kemampuan, kebutuhan, dan minat siswa.",
    difficulty: "EASY",
    weight: 1.0,
    year: 2024,
    source: "Kemendikbudristek",
    isVerified: true,
  },
  {
    kompetensi: "PEDAGOGIK",
    subKompetensi: "Model Pembelajaran",
    text: "Model pembelajaran yang memiliki keunggulan berpikir kreatif, memecahkan masalah realistis, dan merangsang perkembangan berpikir adalah model...",
    type: "PILIHAN_GANDA",
    options: [
      { id: "A", text: "Ceramah" },
      { id: "B", text: "Problem-Based Learning (PBL)" },
      { id: "C", text: "Drill and Practice" },
      { id: "D", text: "Tanya Jawab" },
    ],
    correctAnswer: "B",
    explanation: "Problem-Based Learning (PBL) mendorong siswa memecahkan masalah autentik/realistis, berpikir kritis dan kreatif.",
    difficulty: "EASY",
    weight: 1.0,
    year: 2024,
    source: "Modul PPG",
    isVerified: true,
  },
  {
    kompetensi: "PEDAGOGIK",
    subKompetensi: "Media Pembelajaran",
    text: "Pemilihan media pembelajaran sebaiknya didasarkan pada...",
    type: "PILIHAN_GANDA",
    options: [
      { id: "A", text: "Harga media saja" },
      { id: "B", text: "Ketersediaan media di sekolah" },
      { id: "C", text: "Tujuan pembelajaran, karakteristik siswa, dan ketersediaan sumber" },
      { id: "D", text: "Kemudahan guru saja" },
    ],
    correctAnswer: "C",
    explanation: "Pemilihan media didasarkan pada prinsip ALIGN: tujuan pembelajaran, karakteristik siswa, dan ketersediaan sumber daya.",
    difficulty: "EASY",
    weight: 1.0,
    year: 2024,
    source: "Modul PPG",
    isVerified: true,
  },
  {
    kompetensi: "PEDAGOGIK",
    subKompetensi: "Penilaian Autentik",
    text: "Penilaian portofolio dapat dilaksanakan dengan cara...",
    type: "PILIHAN_GANDA",
    options: [
      { id: "A", text: "Memberikan tes tertulis setiap akhir bab" },
      { id: "B", text: "Mengumpulkan karya terbaik siswa selama periode tertentu" },
      { id: "C", text: "Memberikan nilai berdasarkan kehadiran" },
      { id: "D", text: "Menggunakan tes standar nasional" },
    ],
    correctAnswer: "B",
    explanation: "Portofolio adalah pengumpulan karya siswa terbaik selama periode tertentu untuk menunjukkan perkembangan belajar.",
    difficulty: "EASY",
    weight: 1.0,
    year: 2024,
    source: "Permendikbud",
    isVerified: true,
  },
  {
    kompetensi: "PEDAGOGIK",
    subKompetensi: "Refleksi Pembelajaran",
    text: "Pak Budi memulai pembelajaran dengan merumuskan pertanyaan, mengumpulkan data, menganalisis, dan menarik kesimpulan. Langkah-langkah ini merupakan penerapan model...",
    type: "PILIHAN_GANDA",
    options: [
      { id: "A", text: "Saintifik" },
      { id: "B", text: "Ceramah" },
      { id: "C", text: "Kooperatif" },
      { id: "D", text: "Tutor sebaya" },
    ],
    correctAnswer: "A",
    explanation: "Langkah merumuskan masalah, mengumpulkan data, menganalisis, dan menarik kesimpulan adalah langkah-langkah model saintifik/penyelidikan.",
    difficulty: "EASY",
    weight: 1.0,
    year: 2024,
    source: "Kurikulum 2013",
    isVerified: true,
  },
  {
    kompetensi: "PEDAGOGIK",
    subKompetensi: "HOTS",
    text: "Soal HOTS (Higher Order Thinking Skills) mengukur kemampuan berpikir...",
    type: "PILIHAN_GANDA",
    options: [
      { id: "A", text: "Menghafal dan memahami" },
      { id: "B", text: "Menerapkan saja" },
      { id: "C", text: "Menganalisis, mengevaluasi, dan menciptakan" },
      { id: "D", text: "Menyalin informasi" },
    ],
    correctAnswer: "C",
    explanation: "HOTS berdasarkan Taksonomi Bloom revisi mencakup kemampuan tingkat tinggi: C4 (Menganalisis), C5 (Mengevaluasi), C6 (Mencipta).",
    difficulty: "EASY",
    weight: 1.0,
    year: 2024,
    source: "Kemendikbud",
    isVerified: true,
  },
  {
    kompetensi: "PEDAGOGIK",
    subKompetensi: "Teori Belajar",
    text: "Menurut teori Vygotsky, Zone of Proximal Development (ZPD) adalah...",
    type: "PILIHAN_GANDA",
    options: [
      { id: "A", text: "Area di mana siswa dapat belajar secara mandiri tanpa bantuan" },
      { id: "B", text: "Jarak antara kemampuan aktual dan potensi perkembangan dengan bimbingan" },
      { id: "C", text: "Tingkat kesulitan soal yang sama untuk semua siswa" },
      { id: "D", text: "Perbedaan kemampuan antar siswa" },
    ],
    correctAnswer: "B",
    explanation: "ZPD adalah jarak antara tingkat perkembangan aktual (yang bisa dilakukan sendiri) dan tingkat perkembangan potensial (dengan bantuan).",
    difficulty: "MEDIUM",
    weight: 1.5,
    year: 2024,
    source: "Teori Belajar",
    isVerified: true,
  },
  {
    kompetensi: "PEDAGOGIK",
    subKompetensi: "Pembelajaran Diferensiasi",
    text: "Pembelajaran berdiferensiasi pada hakikatnya adalah...",
    type: "PILIHAN_GANDA",
    options: [
      { id: "A", text: "Mengajar semua siswa dengan cara yang sama" },
      { id: "B", text: "Menyesuaikan教学内容, proses, dan lingkungan belajar sesuai kebutuhan siswa" },
      { id: "C", text: "Memisahkan siswa berdasarkan kemampuan" },
      { id: "D", text: "Memberikan tugas berbeda untuk setiap siswa" },
    ],
    correctAnswer: "B",
    explanation: "Pembelajaran berdiferensiasi menyesuaikan konten, proses, produk, dan lingkungan belajar sesuai kemampuan, kesiapan, dan minat siswa.",
    difficulty: "MEDIUM",
    weight: 1.0,
    year: 2024,
    source: "Kurikulum Merdeka",
    isVerified: true,
  },
  {
    kompetensi: "PROFESIONAL",
    subKompetensi: "Penguasaan Materi",
    text: "Guru Bahasa Indonesia yang kompeten harus memahami...",
    type: "PILIHAN_GANDA",
    options: [
      { id: "A", text: "Hanya tata bahasa formal" },
      { id: "B", text: "Berbagai aspek kebahasaan dan kesastraan Indonesia" },
      { id: "C", text: "Hanya sastra Indonesia" },
      { id: "D", text: "Bahasa daerah saja" },
    ],
    correctAnswer: "B",
    explanation: "Guru Bahasa Indonesia harus menguasai empat komponen kemahiran: menyimak, berbicara, membaca, menulis, serta merespons kaidah.",
    difficulty: "EASY",
    weight: 1.0,
    year: 2024,
    source: "Standar Kompetensi Guru",
    isVerified: true,
  },
  {
    kompetensi: "PROFESIONAL",
    subKompetensi: "Literasi dan Numerasi",
    text: "Literasi membaca bukan hanya kemampuan membaca, tetapi juga...",
    type: "PILIHAN_GANDA",
    options: [
      { id: "A", text: "Kecepatan membaca" },
      { id: "B", text: "Mengidentifikasi huruf saja" },
      { id: "C", text: "Kemampuan memahami, menggunakan, mengevaluasi, dan refleksi teks" },
      { id: "D", text: "Menulis tanpa kesalahan ejaan" },
    ],
    correctAnswer: "C",
    explanation: "Literasi mencakup kemampuan memahami (comprehension), menggunakan (use), mengevaluasi (evaluate), dan refleksi terhadap teks dalam berbagai konteks.",
    difficulty: "EASY",
    weight: 1.0,
    year: 2024,
    source: "UNESCO",
    isVerified: true,
  },
  {
    kompetensi: "PROFESIONAL",
    subKompetensi: "Pengembangan Profesi",
    text: "Guru perlu melakukan tindakan reflektif dalam pembelajaran. Contoh tindakan reflektif adalah...",
    type: "PILIHAN_GANDA",
    options: [
      { id: "A", text: "Mengikuti semua pelatihan yang ada tanpa seleksi" },
      { id: "B", text: "Menganalisis keberhasilan dan kegagalan pembelajaran untuk perbaikan" },
      { id: "C", text: "Menyalahkan siswa atas kegagalan pembelajaran" },
      { id: "D", text: "Mengulang strategi yang sama karena sudah terbiasa" },
    ],
    correctAnswer: "B",
    explanation: "Refleksi adalah menganalisis praktik pembelajaran untuk mengidentifikasi keberhasilan, kelemahan, dan rencana perbaikan.",
    difficulty: "EASY",
    weight: 1.0,
    year: 2024,
    source: "Profesi Guru",
    isVerified: true,
  },
  {
    kompetensi: "PROFESIONAL",
    subKompetensi: "PTK",
    text: "Penelitian Tindakan Kelas (PTK) bertujuan untuk...",
    type: "PILIHAN_GANDA",
    options: [
      { id: "A", text: "Mencetak jurnal akademik untuk naik pangkat" },
      { id: "B", text: "Memperbaiki praktik pembelajaran secara berkelanjutan" },
      { id: "C", text: "Membandingkan hasil belajar antar sekolah" },
      { id: "D", text: "Memenuhi syarat Sertifikasi Guru" },
    ],
    correctAnswer: "B",
    explanation: "PTK adalah penelitian praktis yang bertujuan memperbaiki kualitas pembelajaran secara sistematis dan berkelanjutan (action research).",
    difficulty: "EASY",
    weight: 1.0,
    year: 2024,
    source: "Kemendikbud",
    isVerified: true,
  },
  {
    kompetensi: "PROFESIONAL",
    subKompetensi: "Strategi Pembelajaran Bahasa",
    text: "Pendekatan komunikatif dalam pembelajaran bahasa menekankan...",
    type: "PILIHAN_GANDA",
    options: [
      { id: "A", text: "Hafal kosakata dan tata bahasa" },
      { id: "B", text: "Penggunaan bahasa untuk berkomunikasi dalam konteks nyata" },
      { id: "C", text: "Tes tertulis yang banyak" },
      { id: "D", text: "Terjemahan dari bahasa asing" },
    ],
    correctAnswer: "B",
    explanation: "Pendekatan komunikatif menggunakan bahasa dalam konteks komunikatif nyata, bukan drill grammar atau hafalan.",
    difficulty: "MEDIUM",
    weight: 1.0,
    year: 2024,
    source: "Pendidikan Bahasa",
    isVerified: true,
  },
  {
    kompetensi: "SOSIAL",
    subKompetensi: "Komunikasi dengan Siswa",
    text: "Komunikasi yang efektif antara guru dan siswa dapat dibangun melalui...",
    type: "PILIHAN_GANDA",
    options: [
      { id: "A", text: "Guru mendominasi percakapan di kelas" },
      { id: "B", text: "Saling menghormati, aktif mendengarkan, dan memberikan umpan balik" },
      { id: "C", text: "Hanya menggunakan komunikasi satu arah" },
      { id: "D", text: "Memberikan hukuman saat siswa membuat kesalahan" },
    ],
    correctAnswer: "B",
    explanation: "Komunikasi efektif membutuhkan reciprocal (saling), active listening, dan constructive feedback.",
    difficulty: "EASY",
    weight: 1.0,
    year: 2024,
    source: "Profesi Keguruan",
    isVerified: true,
  },
  {
    kompetensi: "SOSIAL",
    subKompetensi: "Kolaborasi dengan Teman Sejawat",
    text: "Collaboration with peers dalam pembelajaran berbasis Collaborative Learning memberikan manfaat...",
    type: "PILIHAN_GANDA",
    options: [
      { id: "A", text: "Siswa hanya bekerja sendiri" },
      { id: "B", text: "Melatih kemampuan sosial dan saling menghargai perbedaan" },
      { id: "C", text: "Menyalin tugas teman" },
      { id: "D", text: "Guru tidak perlu bekerja sama" },
    ],
    correctAnswer: "B",
    explanation: "Collaborative learning melatih siswa bekerja sama, menghargai perbedaan pendapat, dan mengembangkan soft skills.",
    difficulty: "EASY",
    weight: 1.0,
    year: 2024,
    source: "Modul PPG",
    isVerified: true,
  },
  {
    kompetensi: "KEPRIBADIAN",
    subKompetensi: "Etika Guru",
    text: "Etika profesi guru meliputi hal-hal berikut, KECUALI...",
    type: "PILIHAN_GANDA",
    options: [
      { id: "A", text: "Bertindak profesional dan objektif" },
      { id: "B", text: "Menjaga kerahasiaan informasi siswa" },
      { id: "C", text: "Melakukan plagiarisme untuk keuntungan pribadi" },
      { id: "D", text: "Mengembangkan kompetensi secara berkelanjutan" },
    ],
    correctAnswer: "C",
    explanation: "Plagiarisme adalah pelanggaran etika profesi. Guru wajib jujur, menjaga integritas akademik, dan tidak plagiarisme.",
    difficulty: "EASY",
    weight: 1.0,
    year: 2024,
    source: "Kode Etik Guru Indonesia",
    isVerified: true,
  },
  {
    kompetensi: "KEPRIBADIAN",
    subKompetensi: "Konsekuensi",
    text: "Guru yang melanggar Kode Etik dapat dikenai sanksi berupa...",
    type: "PILIHAN_GANDA",
    options: [
      { id: "A", text: "Penghargaan nasional" },
      { id: "B", text: "Peringatan, pembinaan, atau sanksi moral sesuai tingkat pelanggaran" },
      { id: "C", text: "Kenaikan gaji otomatis" },
      { id: "D", text: "Penunjukkan sebagai kepala sekolah" },
    ],
    correctAnswer: "B",
    explanation: "Sanksi pelanggaran etika guru berkisar dari teguran lisan, peringatan tertulis, hingga pemecatan sesuai severity pelanggaran.",
    difficulty: "EASY",
    weight: 1.0,
    year: 2024,
    source: "Kode Etik Guru Indonesia",
    isVerified: true,
  },
  {
    kompetensi: "PEDAGOGIK",
    subKompetensi: "Pemahaman tentang Peserta Didik",
    text: "Siswa dengan gaya belajar visual akan lebih mudah memahami pelajaran jika...",
    type: "PILIHAN_GANDA",
    options: [
      { id: "A", text: "Mendengarkan penjelasan lisan" },
      { id: "B", text: "Melihat gambar, diagram, dan видео" },
      { id: "C", text: "Berdiskusi kelompok" },
      { id: "D", text: "Menulis catatan panjang" },
    ],
    correctAnswer: "B",
    explanation: "Visual learner belajar optimal melalui gambar, warna, diagram, dan representasi visual lainnya.",
    difficulty: "EASY",
    weight: 1.0,
    year: 2024,
    source: "Teori Gaya Belajar",
    isVerified: true,
  },
  {
    kompetensi: "PROFESIONAL",
    subKompetensi: "TPACK",
    text: "TPACK (Technological Pedagogical Content Knowledge) merupakan kerangka pemahaman tentang...",
    type: "PILIHAN_GANDA",
    options: [
      { id: "A", text: "Penggunaan teknologi saja dalam pembelajaran" },
      { id: "B", text: "Integrasi pengetahuan konten, pedagogi, dan teknologi secara efektif" },
      { id: "C", text: "Penguasaan teknologi tanpa kaitannya dengan pedagogi" },
      { id: "D", text: "Pengajaran bahasa asing" },
    ],
    correctAnswer: "B",
    explanation: "TPACK menekankan bagaimana guru mengintegrasikan teknologi secara tepat dalam konteks pedagogi dan konten tertentu.",
    difficulty: "MEDIUM",
    weight: 1.5,
    year: 2024,
    source: "Mishra & Koehler",
    isVerified: true,
  },
  {
    kompetensi: "PEDAGOGIK",
    subKompetensi: "Lembaga Akreditasi",
    text: "Sertifikasi guru di Indonesia dikelola oleh...",
    type: "PILIHAN_GANDA",
    options: [
      { id: "A", text: "Setiap sekolah secara mandiri" },
      { id: "B", text: "Lembange Akreditasi mandiri" },
      { id: "C", text: "Kementerian Pendidikan dan budaya" },
      { id: "D", text: "Organisasi guru masing-masing" },
    ],
    correctAnswer: "B",
    explanation: "Sertifikasi guru dilakukan melalui jalur PPG oleh Kemendikbud melalui lembaga yang berwenang.",
    difficulty: "EASY",
    weight: 1.0,
    year: 2024,
    source: "UU Guru dan Dosen",
    isVerified: true,
  },
  {
    kompetensi: "PEDAGOGIK",
    subKompetensi: "Pendekatan Pembelajaran",
    text: "Pendekatan Contextual Teaching and Learning (CTL) menekankan...",
    type: "PILIHAN_GANDA",
    options: [
      { id: "A", text: "Pembelajaran yang mengaitkan materi dengan konteks kehidupan nyata" },
      { id: "B", text: "Pembelajaran yang hanya menggunakan buku teks" },
      { id: "C", text: "Pembelajaran tanpa melibatkan siswa aktif" },
      { id: "D", text: "Pembelajaran yang sama untuk semua mata pelajaran" },
    ],
    correctAnswer: "A",
    explanation: "CTL menghubungkan pembelajaran dengan konteks nyata kehidupan siswa agar bermakna dan transfer pengetahuan optimal.",
    difficulty: "EASY",
    weight: 1.0,
    year: 2024,
    source: "Kemendikbud",
    isVerified: true,
  },
  {
    kompetensi: "SOSIAL",
    subKompetensi: "Pembelajaran Sosial Emosional",
    text: "Social Emotional Learning (SEL) bertujuan mengembangkan...",
    type: "PILIHAN_GANDA",
    options: [
      { id: "A", text: "Kemampuan akademik saja" },
      { id: "B", text: "Kesadaran diri, pengelolaan diri, kesadaran sosial, dan keterampilan sosial" },
      { id: "C", text: "Hafalan rumus matematika" },
      { id: "D", text: "Kecepatan membaca" },
    ],
    correctAnswer: "B",
    explanation: "SEL mengembangkan 5 kompetensi: self-awareness, self-management, social awareness, relationship skills, dan responsible decision-making.",
    difficulty: "EASY",
    weight: 1.0,
    year: 2024,
    source: "CASEL Framework",
    isVerified: true,
  },
];

async function main() {
  console.log("🌱 Seeding UKBI & TKA questions...");

  const existingUKBI = await prisma.uKBIQuestion.count();
  const existingTKA = await prisma.tKAQuestion.count();

  if (existingUKBI === 0) {
    await prisma.uKBIQuestion.createMany({
      data: UKBI_QUESTIONS as any[],
      skipDuplicates: true,
    });
    console.log(`✅ Added ${UKBI_QUESTIONS.length} UKBI questions`);
  } else {
    console.log(`⏩ Skipped UKBI (${existingUKBI} already exist)`);
  }

  if (existingTKA === 0) {
    await prisma.tKAQuestion.createMany({
      data: TKA_QUESTIONS as any[],
      skipDuplicates: true,
    });
    console.log(`✅ Added ${TKA_QUESTIONS.length} TKA questions`);
  } else {
    console.log(`⏩ Skipped TKA (${existingTKA} already exist)`);
  }

  const existingPaket = await prisma.paketKompetensi.count();
  if (existingPaket === 0) {
    await prisma.paketKompetensi.createMany({
      data: [
        {
          title: "Simulasi UKBI - Paket Lengkap",
          description: "Simulasi UKBI Adaptif Merdeka dengan 5 seksi lengkap. Cocok untuk latihan mandiri sebelum ujian UKBI resmi.",
          type: "UKBI_SIMULASI",
          mode: "SIMULASI",
          duration: 120,
          passingScore: 482,
          passingGrade: "MADYA",
          totalQuestions: 129,
          isActive: true,
          isPremium: false,
          attemptLimit: -1,
          sections: [],
          sectionsData: JSON.stringify([
            {
              name: "Seksi I: Mendengarkan",
              seksi: "MENDENGARKAN",
              timeLimit: 30,
              count: 10,
            },
            {
              name: "Seksi II: Merespons Kaidah",
              seksi: "MERESPONS_KAIDAH",
              timeLimit: 20,
              count: 10,
            },
            {
              name: "Seksi III: Membaca",
              seksi: "MEMBACA",
              timeLimit: 45,
              count: 10,
            },
            {
              name: "Seksi IV: Menulis",
              seksi: "MENULIS",
              timeLimit: 35,
              count: 2,
            },
          ]),
        },
        {
          title: "Latihan UKBI - Seksi I Mendengarkan",
          description: "Latihan soal UKBI Seksi I: Mendengarkan. Dialog dan monolog pemahaman audio.",
          type: "UKBI_LATIHAN",
          mode: "LATIHAN",
          duration: 30,
          passingScore: 0,
          passingGrade: "-",
          totalQuestions: 10,
          isActive: true,
          isPremium: false,
          attemptLimit: -1,
          sections: [],
          sectionsData: JSON.stringify([
            { name: "Seksi I: Mendengarkan", seksi: "MENDENGARKAN", timeLimit: 30, count: 10 },
          ]),
        },
        {
          title: "Latihan UKBI - Seksi II & III",
          description: "Latihan Seksi II Merespons Kaidah dan Seksi III Membaca.",
          type: "UKBI_LATIHAN",
          mode: "LATIHAN",
          duration: 65,
          passingScore: 0,
          passingGrade: "-",
          totalQuestions: 20,
          isActive: true,
          isPremium: false,
          attemptLimit: -1,
          sections: [],
          sectionsData: JSON.stringify([
            { name: "Seksi II: Merespons Kaidah", seksi: "MERESPONS_KAIDAH", timeLimit: 20, count: 10 },
            { name: "Seksi III: Membaca", seksi: "MEMBACA", timeLimit: 45, count: 10 },
          ]),
        },
        {
          title: "Simulasi TKA Guru - Pedagogik & Profesional",
          description: "Simulasi TKA UKPPPG dengan soal Pedagogik dan Profesional. Passing grade: 70%.",
          type: "TKA_GURU",
          mode: "SIMULASI",
          duration: 120,
          passingScore: 70,
          passingGrade: "B",
          totalQuestions: 25,
          isActive: true,
          isPremium: false,
          attemptLimit: -1,
          sections: [],
          sectionsData: JSON.stringify([
            { name: "Kompetensi Pedagogik", kompetensi: "PEDAGOGIK", timeLimit: 60, count: 12 },
            { name: "Kompetensi Profesional", kompetensi: "PROFESIONAL", timeLimit: 60, count: 8 },
          ]),
        },
        {
          title: "Latihan TKA Guru - Pedagogik",
          description: "Latihan soal Pedagogik untuk persiapan UKPPPG.",
          type: "TKA_GURU",
          mode: "LATIHAN",
          duration: 30,
          passingScore: 0,
          passingGrade: "-",
          totalQuestions: 12,
          isActive: true,
          isPremium: false,
          attemptLimit: -1,
          sections: [],
          sectionsData: JSON.stringify([
            { name: "Kompetensi Pedagogik", kompetensi: "PEDAGOGIK", timeLimit: 30, count: 12 },
          ]),
        },
        {
          title: "Latihan TKA Guru - Profesional & Sosial",
          description: "Latihan soal Kompetensi Profesional, Sosial, dan Kepribadian.",
          type: "TKA_GURU",
          mode: "LATIHAN",
          duration: 30,
          passingScore: 0,
          passingGrade: "-",
          totalQuestions: 13,
          isActive: true,
          isPremium: false,
          attemptLimit: -1,
          sections: [],
          sectionsData: JSON.stringify([
            { name: "Kompetensi Profesional", kompetensi: "PROFESIONAL", timeLimit: 20, count: 7 },
            { name: "Kompetensi Sosial & Kepribadian", kompetensi: "SOSIAL", timeLimit: 10, count: 6 },
          ]),
        },
      ],
      skipDuplicates: true,
    });
    console.log("✅ Added 6 test packages");
  } else {
    console.log(`⏩ Skipped packages (${existingPaket} already exist)`);
  }

  console.log("🎉 Seeding complete!");
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());