/**
 * Curated, hand-verified question bank for the solo games (Menara Cerdas,
 * Benar atau Salah). Each item has exactly ONE unambiguous correct answer with
 * distractors that are clearly wrong, plus a short penjelasan. Written to KBBI /
 * PUEBI conventions. This is merged with Jalur Cerdas lesson questions in the API
 * and served in random order, so every player gets a different mix.
 *
 * Shape matches the game API's normalized question:
 *   { soal, opsi[], jawaban(index), penjelasan }
 */
export interface BankQuestion {
  soal: string;
  opsi: string[];
  jawaban: number;
  penjelasan: string;
  kategori: string;
}

export const QUESTION_BANK: BankQuestion[] = [
  { soal: "Manakah penulisan kata baku yang benar?", opsi: ["Apotik","Aphotek","Apoteker","Apotek"], jawaban: 3, penjelasan: "Bentuk baku menurut KBBI adalah 'apotek'.", kategori: "Kata Baku" },
  { soal: "Bentuk baku dari 'ijazah' adalah...", opsi: ["Ijasah","Izajah","Ijazan","Ijazah"], jawaban: 3, penjelasan: "Kata baku yang benar adalah 'ijazah'.", kategori: "Kata Baku" },
  { soal: "Manakah kata baku yang benar?", opsi: ["Risiko","Resiko","Rizico","Resico"], jawaban: 0, penjelasan: "Bentuk baku adalah 'risiko', bukan 'resiko'.", kategori: "Kata Baku" },
  { soal: "Penulisan baku yang benar adalah...", opsi: ["Nasehat","Nasehad","Nasihad","Nasihat"], jawaban: 3, penjelasan: "Kata baku menurut KBBI adalah 'nasihat'.", kategori: "Kata Baku" },
  { soal: "Manakah bentuk baku yang benar?", opsi: ["Aktifitas","Aktipitas","Aktiviti","Aktivitas"], jawaban: 3, penjelasan: "Bentuk baku adalah 'aktivitas' (dari 'aktif' + '-itas').", kategori: "Kata Baku" },
  { soal: "Kata baku yang tepat adalah...", opsi: ["Kualitas","Kwalitas","Kualiti","Kwaliti"], jawaban: 0, penjelasan: "Bentuk baku adalah 'kualitas'.", kategori: "Kata Baku" },
  { soal: "Manakah penulisan yang baku?", opsi: ["Jadwal","Jadual","Jadwall","Jatwal"], jawaban: 0, penjelasan: "Bentuk baku adalah 'jadwal'.", kategori: "Kata Baku" },
  { soal: "Bentuk baku yang benar adalah...", opsi: ["Teknik","Tehnik","Tekhnik","Teknis"], jawaban: 0, penjelasan: "Kata baku adalah 'teknik'.", kategori: "Kata Baku" },
  { soal: "Manakah kata baku yang benar? (variasi 2)", opsi: ["Februari","Pebruari","Februwari","Febuari"], jawaban: 0, penjelasan: "Nama bulan yang baku adalah 'Februari'.", kategori: "Kata Baku" },
  { soal: "Penulisan baku yang tepat adalah...", opsi: ["Izin","Ijin","Idzin","Izink"], jawaban: 0, penjelasan: "Bentuk baku adalah 'izin'.", kategori: "Kata Baku" },
  { soal: "Manakah bentuk baku yang benar? (variasi 2)", opsi: ["Analisa","Analisys","Analitis","Analisis"], jawaban: 3, penjelasan: "Bentuk baku adalah 'analisis'.", kategori: "Kata Baku" },
  { soal: "Kata baku yang benar adalah...", opsi: ["Praktek","Prakktik","Practik","Praktik"], jawaban: 3, penjelasan: "Bentuk baku adalah 'praktik' (kata kerja/kegiatan).", kategori: "Kata Baku" },
  { soal: "Manakah penulisan baku?", opsi: ["Sistim","Systeem","Sistematis","Sistem"], jawaban: 3, penjelasan: "Bentuk baku adalah 'sistem'.", kategori: "Kata Baku" },
  { soal: "Bentuk baku yang tepat adalah...", opsi: ["Karir","Karrier","Kariir","Karier"], jawaban: 3, penjelasan: "Menurut KBBI, bentuk baku adalah 'karier'.", kategori: "Kata Baku" },
  { soal: "Manakah kata baku yang benar? (variasi 3)", opsi: ["Cabai","Cabe","Cabay","Cabhai"], jawaban: 0, penjelasan: "Bentuk baku adalah 'cabai', 'cabe' tidak baku.", kategori: "Kata Baku" },
  { soal: "Penulisan baku yang benar adalah... (variasi 2)", opsi: ["Antre","Antri","Antree","Anttre"], jawaban: 0, penjelasan: "Bentuk baku adalah 'antre'.", kategori: "Kata Baku" },
  { soal: "Manakah bentuk baku?", opsi: ["Komplet","Komplit","Complit","Kompleet"], jawaban: 0, penjelasan: "Bentuk baku menurut KBBI adalah 'komplet'.", kategori: "Kata Baku" },
  { soal: "Kata baku yang benar adalah... (variasi 2)", opsi: ["Frekuensi","Frekwensi","Frequensi","Frekunsi"], jawaban: 0, penjelasan: "Bentuk baku adalah 'frekuensi'.", kategori: "Kata Baku" },
  { soal: "Sinonim kata 'pandai' adalah...", opsi: ["Bodoh","Malas","Lemah","Cerdas"], jawaban: 3, penjelasan: "'Pandai' bersinonim dengan 'cerdas'.", kategori: "Sinonim" },
  { soal: "Sinonim kata 'indah' adalah...", opsi: ["Buruk","Kotor","Suram","Elok"], jawaban: 3, penjelasan: "'Indah' bersinonim dengan 'elok'.", kategori: "Sinonim" },
  { soal: "Kata yang bersinonim dengan 'gembira' adalah...", opsi: ["Sedih","Marah","Takut","Riang"], jawaban: 3, penjelasan: "'Gembira' bersinonim dengan 'riang'.", kategori: "Sinonim" },
  { soal: "Sinonim kata 'lezat' adalah...", opsi: ["Hambar","Pahit","Basi","Enak"], jawaban: 3, penjelasan: "'Lezat' bersinonim dengan 'enak'.", kategori: "Sinonim" },
  { soal: "Sinonim kata 'cepat' adalah...", opsi: ["Lambat","Pelan","Gesit","Diam"], jawaban: 2, penjelasan: "'Cepat' bersinonim dengan 'gesit'.", kategori: "Sinonim" },
  { soal: "Kata yang bersinonim dengan 'bohong' adalah...", opsi: ["Jujur","Benar","Nyata","Dusta"], jawaban: 3, penjelasan: "'Bohong' bersinonim dengan 'dusta'.", kategori: "Sinonim" },
  { soal: "Sinonim kata 'akhir' adalah...", opsi: ["Awal","Mula","Pangkal","Ujung"], jawaban: 3, penjelasan: "'Akhir' bersinonim dengan 'ujung'.", kategori: "Sinonim" },
  { soal: "Sinonim kata 'sukar' adalah...", opsi: ["Mudah","Gampang","Sulit","Ringan"], jawaban: 2, penjelasan: "'Sukar' bersinonim dengan 'sulit'.", kategori: "Sinonim" },
  { soal: "Kata yang bersinonim dengan 'tampan' adalah...", opsi: ["Jelek","Buruk","Kusam","Rupawan"], jawaban: 3, penjelasan: "'Tampan' bersinonim dengan 'rupawan'.", kategori: "Sinonim" },
  { soal: "Sinonim kata 'pintar' adalah...", opsi: ["Dungu","Malas","Lelah","Pandai"], jawaban: 3, penjelasan: "'Pintar' bersinonim dengan 'pandai'.", kategori: "Sinonim" },
  { soal: "Sinonim kata 'lelah' adalah...", opsi: ["Segar","Bugar","Penat","Kuat"], jawaban: 2, penjelasan: "'Lelah' bersinonim dengan 'penat'.", kategori: "Sinonim" },
  { soal: "Kata yang bersinonim dengan 'besar' adalah...", opsi: ["Kecil","Mungil","Akbar","Sempit"], jawaban: 2, penjelasan: "'Besar' bersinonim dengan 'akbar'.", kategori: "Sinonim" },
  { soal: "Antonim kata 'tinggi' adalah...", opsi: ["Jangkung","Panjang","Besar","Rendah"], jawaban: 3, penjelasan: "Lawan kata 'tinggi' adalah 'rendah'.", kategori: "Antonim" },
  { soal: "Antonim kata 'terang' adalah...", opsi: ["Benderang","Cerah","Silau","Gelap"], jawaban: 3, penjelasan: "Lawan kata 'terang' adalah 'gelap'.", kategori: "Antonim" },
  { soal: "Lawan kata 'rajin' adalah...", opsi: ["Giat","Tekun","Malas","Ulet"], jawaban: 2, penjelasan: "Lawan kata 'rajin' adalah 'malas'.", kategori: "Antonim" },
  { soal: "Antonim kata 'mahal' adalah...", opsi: ["Murah","Mewah","Berharga","Langka"], jawaban: 0, penjelasan: "Lawan kata 'mahal' adalah 'murah'.", kategori: "Antonim" },
  { soal: "Lawan kata 'tebal' adalah...", opsi: ["Lebar","Besar","Tipis","Padat"], jawaban: 2, penjelasan: "Lawan kata 'tebal' adalah 'tipis'.", kategori: "Antonim" },
  { soal: "Antonim kata 'menang' adalah...", opsi: ["Juara","Unggul","Kalah","Hebat"], jawaban: 2, penjelasan: "Lawan kata 'menang' adalah 'kalah'.", kategori: "Antonim" },
  { soal: "Lawan kata 'ramai' adalah...", opsi: ["Bising","Riuh","Sepi","Padat"], jawaban: 2, penjelasan: "Lawan kata 'ramai' adalah 'sepi'.", kategori: "Antonim" },
  { soal: "Antonim kata 'basah' adalah...", opsi: ["Lembap","Becek","Berair","Kering"], jawaban: 3, penjelasan: "Lawan kata 'basah' adalah 'kering'.", kategori: "Antonim" },
  { soal: "Lawan kata 'berat' adalah...", opsi: ["Ringan","Padat","Kuat","Keras"], jawaban: 0, penjelasan: "Lawan kata 'berat' adalah 'ringan'.", kategori: "Antonim" },
  { soal: "Antonim kata 'maju' adalah...", opsi: ["Berkembang","Melaju","Mundur","Bangkit"], jawaban: 2, penjelasan: "Lawan kata 'maju' adalah 'mundur'.", kategori: "Antonim" },
  { soal: "Lawan kata 'panas' adalah...", opsi: ["Hangat","Terik","Gerah","Dingin"], jawaban: 3, penjelasan: "Lawan kata 'panas' adalah 'dingin'.", kategori: "Antonim" },
  { soal: "Antonim kata 'jauh' adalah...", opsi: ["Dekat","Panjang","Lebar","Tinggi"], jawaban: 0, penjelasan: "Lawan kata 'jauh' adalah 'dekat'.", kategori: "Antonim" },
  { soal: "Bentuk kata 'me-' + 'sapu' yang benar adalah...", opsi: ["Mensapu","Menyapuh","Menyapu","Mesapu"], jawaban: 2, penjelasan: "'me-' + kata berawalan 's' luluh menjadi 'meny-': menyapu.", kategori: "Imbuhan" },
  { soal: "Bentuk kata 'me-' + 'tulis' yang benar adalah...", opsi: ["Mentulis","Menyulis","Metulis","Menulis"], jawaban: 3, penjelasan: "'me-' + kata berawalan 't' luluh menjadi 'men-': menulis.", kategori: "Imbuhan" },
  { soal: "Bentuk kata 'me-' + 'pukul' yang benar adalah...", opsi: ["Mempukul","Menpukul","Memukul","Mepukul"], jawaban: 2, penjelasan: "'me-' + kata berawalan 'p' luluh menjadi 'mem-': memukul.", kategori: "Imbuhan" },
  { soal: "Bentuk kata 'me-' + 'kira' yang benar adalah...", opsi: ["Mengkira","Menkira","Mekira","Mengira"], jawaban: 3, penjelasan: "'me-' + kata berawalan 'k' luluh menjadi 'meng-': mengira.", kategori: "Imbuhan" },
  { soal: "Kata 'pemberian' dibentuk dari kata dasar...", opsi: ["Beri","Ber","Pember","Rian"], jawaban: 0, penjelasan: "'Pemberian' = pe- + beri + -an, kata dasarnya 'beri'.", kategori: "Imbuhan" },
  { soal: "Imbuhan pada kata 'berlari' adalah...", opsi: ["me-","ter-","ber-","di-"], jawaban: 2, penjelasan: "'Berlari' berimbuhan awalan 'ber-'.", kategori: "Imbuhan" },
  { soal: "Bentuk kata 'me-' + 'cuci' yang benar adalah...", opsi: ["Mencuci","Menyuci","Mecuci","Menncuci"], jawaban: 0, penjelasan: "'me-' + kata berawalan 'c' menjadi 'men-': mencuci (c tidak luluh).", kategori: "Imbuhan" },
  { soal: "Kata 'terindah' menyatakan makna...", opsi: ["Paling indah","Sedang indah","Tidak indah","Agak indah"], jawaban: 0, penjelasan: "Awalan 'ter-' pada 'terindah' bermakna 'paling'.", kategori: "Imbuhan" },
  { soal: "Bentuk kata 'me-' + 'baca' yang benar adalah...", opsi: ["Membaca","Menbaca","Mebaca","Memmaca"], jawaban: 0, penjelasan: "'me-' + kata berawalan 'b' menjadi 'mem-': membaca.", kategori: "Imbuhan" },
  { soal: "Kata 'dimakan' menunjukkan bahwa kata itu berjenis...", opsi: ["Kata aktif","Kata benda","Kata sifat","Kata pasif"], jawaban: 3, penjelasan: "Awalan 'di-' membentuk kata kerja pasif: dimakan.", kategori: "Imbuhan" },
  { soal: "Penulisan yang benar sesuai PUEBI adalah...", opsi: ["di rumah","dirumah","di-rumah","dirumahkan"], jawaban: 0, penjelasan: "'di' sebagai kata depan (menunjuk tempat) ditulis terpisah: 'di rumah'.", kategori: "Ejaan" },
  { soal: "Penulisan yang tepat adalah...", opsi: ["dimakan","di makan","di-makan","di makan-kan"], jawaban: 0, penjelasan: "'di-' sebagai awalan (kata kerja) ditulis serangkai: 'dimakan'.", kategori: "Ejaan" },
  { soal: "Nama hari seperti 'Senin' ditulis dengan huruf...", opsi: ["Kapital di awal","Kecil semua","Kapital semua","Miring semua"], jawaban: 0, penjelasan: "Nama hari diawali huruf kapital: 'Senin'.", kategori: "Ejaan" },
  { soal: "Penulisan gabungan kata yang benar adalah...", opsi: ["tanggungjawab","tanggung-jawab","tanggung jawab","tanggungjawaban"], jawaban: 2, penjelasan: "'Tanggung jawab' ditulis terpisah karena belum berimbuhan.", kategori: "Ejaan" },
  { soal: "Pemakaian tanda koma yang benar adalah...", opsi: ["Saya membeli buku pensil dan tas.","Saya membeli, buku pensil dan tas.","Saya, membeli buku pensil dan tas.","Saya membeli buku, pensil, dan tas."], jawaban: 3, penjelasan: "Tanda koma memisahkan unsur dalam perincian: 'buku, pensil, dan tas'.", kategori: "Ejaan" },
  { soal: "Setiap unsur nama orang (misal Budi Santoso) ditulis dengan huruf...", opsi: ["Kecil semua","Kapital semua","Kapital di setiap awal kata","Miring"], jawaban: 2, penjelasan: "Setiap unsur nama orang diawali huruf kapital: 'Budi Santoso'.", kategori: "Ejaan" },
  { soal: "Penulisan kata depan 'ke' yang benar adalah...", opsi: ["kesekolah","ke-sekolah","kesekolahan","ke sekolah"], jawaban: 3, penjelasan: "'ke' penunjuk arah/tempat ditulis terpisah: 'ke sekolah'.", kategori: "Ejaan" },
  { soal: "Penulisan angka dan kata yang tepat adalah...", opsi: ["Dia membeli 2 buah apel.","Dia membeli 2buah apel.","Dia membeli dua buah apel.","Dia membeli II buah apel."], jawaban: 2, penjelasan: "Bilangan yang dapat ditulis satu-dua kata ditulis dengan huruf: 'dua buah apel'.", kategori: "Ejaan" },
  { soal: "Kalimat dengan tanda titik yang benar adalah...", opsi: ["Ibu pergi ke pasar,","Ibu pergi ke pasar?","Ibu pergi ke pasar!","Ibu pergi ke pasar."], jawaban: 3, penjelasan: "Kalimat berita diakhiri tanda titik.", kategori: "Ejaan" },
  { soal: "Pada judul karangan, setiap kata diawali huruf kapital, KECUALI...", opsi: ["Kata benda","Kata kerja","Kata tugas seperti 'dan', 'di', 'ke'","Kata sifat"], jawaban: 2, penjelasan: "Pada judul, kata tugas (dan, di, ke, dari) tidak diawali kapital, kecuali di posisi awal.", kategori: "Ejaan" },
  { soal: "Kalimat yang paling efektif adalah...", opsi: ["Para siswa-siswa berbaris.","Siswa-siswa berbaris.","Para siswa berbaris.","Semua para siswa berbaris."], jawaban: 2, penjelasan: "'Para' sudah bermakna jamak, tak perlu diulang: 'Para siswa berbaris'.", kategori: "Kalimat Efektif" },
  { soal: "Kalimat efektif yang benar adalah...", opsi: ["Dia naik ke atas.","Dia naik ke atas tangga atas.","Dia naik.","Dia naik atas."], jawaban: 2, penjelasan: "'Naik' sudah bermakna 'ke atas', jadi cukup 'Dia naik'.", kategori: "Kalimat Efektif" },
  { soal: "Kalimat yang efektif adalah...", opsi: ["Agar supaya lulus, ia belajar.","Agar lulus, ia belajar.","Supaya agar lulus, ia belajar.","Demi agar lulus, ia belajar."], jawaban: 1, penjelasan: "'Agar' dan 'supaya' bersinonim, cukup pakai satu.", kategori: "Kalimat Efektif" },
  { soal: "Pilihan kata yang tepat: 'Ayah ___ mobil ke kantor.'", opsi: ["mengendarai","menaiki","menyetir","menjalankan"], jawaban: 0, penjelasan: "Kata yang paling tepat untuk mobil adalah 'mengendarai'.", kategori: "Kalimat Efektif" },
  { soal: "Kalimat efektif yang benar adalah... (variasi 2)", opsi: ["Banyak siswa-siswa hadir.","Banyak siswa hadir.","Banyak para siswa hadir.","Banyak sekali siswa-siswa hadir."], jawaban: 1, penjelasan: "'Banyak' sudah menunjukkan jamak: 'Banyak siswa hadir'.", kategori: "Kalimat Efektif" },
  { soal: "Kata berimbuhan yang tepat: 'Ibu ___ sayur di dapur.'", opsi: ["masak","memasak","dimasak","termasak"], jawaban: 1, penjelasan: "Subjek 'Ibu' melakukan tindakan aktif: 'memasak'.", kategori: "Kalimat Efektif" },
  { soal: "Kalimat yang baku adalah...", opsi: ["Kepada Bapak Kepala Sekolah waktu dan tempat kami persilakan.","Bapak Kepala Sekolah kami persilakan.","Waktu dan tempat kami persilakan.","Kepada waktu kami persilakan."], jawaban: 1, penjelasan: "Yang dipersilakan adalah orang, bukan 'waktu dan tempat'.", kategori: "Kalimat Efektif" },
  { soal: "Pilihan kata yang tepat: 'Dia ___ hadiah dari ayahnya.'", opsi: ["memberi","menerima","mengirim","menawar"], jawaban: 1, penjelasan: "'Dari ayahnya' menunjukkan ia sebagai penerima: 'menerima'.", kategori: "Kalimat Efektif" },
  { soal: "Makna ungkapan 'buah tangan' adalah...", opsi: ["Hasil kerja","Oleh-oleh","Buah segar","Tangan kanan"], jawaban: 1, penjelasan: "'Buah tangan' berarti oleh-oleh.", kategori: "Ungkapan" },
  { soal: "Makna ungkapan 'kabar burung' adalah...", opsi: ["Kabar gembira","Kabar burung terbang","Kabar yang belum pasti","Kabar duka"], jawaban: 2, penjelasan: "'Kabar burung' berarti kabar/berita yang belum pasti kebenarannya.", kategori: "Ungkapan" },
  { soal: "Makna peribahasa 'besar pasak daripada tiang' adalah...", opsi: ["Rajin menabung","Pengeluaran lebih besar daripada pemasukan","Rumah yang kokoh","Bekerja keras"], jawaban: 1, penjelasan: "Peribahasa ini berarti pengeluaran lebih besar daripada pendapatan.", kategori: "Ungkapan" },
  { soal: "Makna ungkapan 'tangan kanan' adalah...", opsi: ["Orang kidal","Orang kepercayaan","Tangan yang kuat","Anggota tubuh"], jawaban: 1, penjelasan: "'Tangan kanan' berarti orang kepercayaan/andalan.", kategori: "Ungkapan" },
  { soal: "Makna peribahasa 'sedia payung sebelum hujan' adalah...", opsi: ["Membawa payung","Bersiap sebelum terjadi masalah","Takut hujan","Menunggu hujan"], jawaban: 1, penjelasan: "Peribahasa ini berarti bersiap sebelum sesuatu yang buruk terjadi.", kategori: "Ungkapan" },
  { soal: "Makna ungkapan 'naik daun' adalah...", opsi: ["Memanjat pohon","Sedang populer","Jatuh miskin","Merasa sedih"], jawaban: 1, penjelasan: "'Naik daun' berarti sedang terkenal atau populer.", kategori: "Ungkapan" },
  { soal: "Makna ungkapan 'kepala dingin' adalah...", opsi: ["Sakit kepala","Tenang/sabar","Marah","Kedinginan"], jawaban: 1, penjelasan: "'Kepala dingin' berarti tenang dan sabar dalam menghadapi masalah.", kategori: "Ungkapan" },
  { soal: "Makna peribahasa 'air susu dibalas air tuba' adalah...", opsi: ["Kebaikan dibalas kejahatan","Minum susu","Saling menolong","Berbuat baik"], jawaban: 0, penjelasan: "Peribahasa ini berarti kebaikan dibalas dengan keburukan.", kategori: "Ungkapan" },
  { soal: "Kata 'cantik' termasuk jenis kata...", opsi: ["Kata benda","Kata kerja","Kata sifat","Kata bilangan"], jawaban: 2, penjelasan: "'Cantik' menyatakan sifat, jadi kata sifat (adjektiva).", kategori: "Jenis Kata" },
  { soal: "Kata 'berlari' termasuk jenis kata...", opsi: ["Kata benda","Kata kerja","Kata sifat","Kata keterangan"], jawaban: 1, penjelasan: "'Berlari' menyatakan perbuatan, jadi kata kerja (verba).", kategori: "Jenis Kata" },
  { soal: "Kata 'meja' termasuk jenis kata...", opsi: ["Kata benda","Kata kerja","Kata sifat","Kata bilangan"], jawaban: 0, penjelasan: "'Meja' menyatakan benda, jadi kata benda (nomina).", kategori: "Jenis Kata" },
  { soal: "Kata 'tiga' termasuk jenis kata...", opsi: ["Kata benda","Kata bilangan","Kata sifat","Kata kerja"], jawaban: 1, penjelasan: "'Tiga' menyatakan jumlah, jadi kata bilangan (numeralia).", kategori: "Jenis Kata" },
  { soal: "Dalam kalimat 'Dia berlari cepat', kata 'cepat' berfungsi sebagai...", opsi: ["Subjek","Predikat","Keterangan","Objek"], jawaban: 2, penjelasan: "'Cepat' menerangkan cara 'berlari', jadi keterangan.", kategori: "Jenis Kata" },
  { soal: "Kata penghubung (konjungsi) terdapat pada kata...", opsi: ["dan","buku","lari","merah"], jawaban: 0, penjelasan: "'Dan' adalah kata penghubung (konjungsi).", kategori: "Jenis Kata" },
  { soal: "Kata ganti orang pertama tunggal adalah...", opsi: ["kamu","dia","saya","mereka"], jawaban: 2, penjelasan: "'Saya' adalah kata ganti orang pertama tunggal.", kategori: "Jenis Kata" },
  { soal: "Kata 'sangat' dalam 'sangat pandai' termasuk...", opsi: ["Kata benda","Kata keterangan","Kata kerja","Kata bilangan"], jawaban: 1, penjelasan: "'Sangat' menerangkan tingkat sifat, jadi kata keterangan.", kategori: "Jenis Kata" },
  { soal: "Manakah penulisan kata serapan yang benar?", opsi: ["System","Sistim","Sistem","Sisteme"], jawaban: 2, penjelasan: "Bentuk baku dalam bahasa Indonesia adalah 'sistem'.", kategori: "Kata Baku" },
  { soal: "Bentuk baku dari kata 'jenius' adalah...", opsi: ["Jenius","Genius","Jenious","Genious"], jawaban: 0, penjelasan: "Bentuk baku menurut KBBI adalah 'jenius'.", kategori: "Kata Baku" },
  { soal: "Manakah yang termasuk kata baku?", opsi: ["Jumat","Jum'at","Djumat","Jumaat"], jawaban: 0, penjelasan: "Bentuk baku nama hari adalah 'Jumat'.", kategori: "Kata Baku" },
  { soal: "Penulisan baku dari 'konsekwensi' adalah...", opsi: ["Konsekwensi","Konsekuensi","Konsequensi","Konsekuwensi"], jawaban: 1, penjelasan: "Bentuk baku adalah 'konsekuensi'.", kategori: "Kata Baku" },
  { soal: "Bentuk baku yang benar: ...", opsi: ["Konkrit","Konkret","Koncrit","Koncrek"], jawaban: 1, penjelasan: "Bentuk baku adalah 'konkret'.", kategori: "Kata Baku" },
  { soal: "Kata baku dari 'dilema' yang benar adalah...", opsi: ["Dilema","Dilemma","Dilem","Dilemba"], jawaban: 0, penjelasan: "Bentuk baku adalah 'dilema'.", kategori: "Kata Baku" },
  { soal: "Manakah penulisan baku? (variasi 2)", opsi: ["Metoda","Metode","Metoode","Metodha"], jawaban: 1, penjelasan: "Bentuk baku adalah 'metode'.", kategori: "Kata Baku" },
  { soal: "Kata baku yang tepat untuk 'esensial' adalah...", opsi: ["Esensial","Esensiall","Essensial","Esensya"], jawaban: 0, penjelasan: "Bentuk baku adalah 'esensial'.", kategori: "Kata Baku" },
  { soal: "Penulisan yang baku: ...", opsi: ["Apakah","Apa kah","Apa-kah","Apaakah"], jawaban: 0, penjelasan: "Partikel '-kah' ditulis serangkai: 'apakah'.", kategori: "Kata Baku" },
  { soal: "Bentuk baku dari 'do'a' adalah...", opsi: ["Do'a","Doa","Doah","Doaa"], jawaban: 1, penjelasan: "Bentuk baku adalah 'doa'.", kategori: "Kata Baku" },
  { soal: "Sinonim kata 'berhemat' adalah...", opsi: ["Boros","Mengirit","Menghambur","Mewah"], jawaban: 1, penjelasan: "'Berhemat' bersinonim dengan 'mengirit'.", kategori: "Sinonim" },
  { soal: "Sinonim kata 'berani' adalah...", opsi: ["Penakut","Gagah","Pengecut","Ragu"], jawaban: 1, penjelasan: "'Berani' bersinonim dengan 'gagah'.", kategori: "Sinonim" },
  { soal: "Kata yang bersinonim dengan 'malas' adalah...", opsi: ["Rajin","Tekun","Pemalas","Giat"], jawaban: 2, penjelasan: "Sinonim 'malas' adalah 'pemalas'.", kategori: "Sinonim" },
  { soal: "Sinonim kata 'berpikir' adalah...", opsi: ["Melamun","Menalar","Tidur","Bermain"], jawaban: 1, penjelasan: "'Berpikir' bersinonim dengan 'menalar'.", kategori: "Sinonim" },
  { soal: "Sinonim kata 'lugu' adalah...", opsi: ["Pintar","Polos","Licik","Cerdik"], jawaban: 1, penjelasan: "'Lugu' bersinonim dengan 'polos'.", kategori: "Sinonim" },
  { soal: "Kata yang bersinonim dengan 'bijaksana' adalah...", opsi: ["Bodoh","Arif","Ceroboh","Naif"], jawaban: 1, penjelasan: "'Bijaksana' bersinonim dengan 'arif'.", kategori: "Sinonim" },
  { soal: "Sinonim kata 'mengungkapkan' adalah...", opsi: ["Menyembunyikan","Menyatakan","Merahasiakan","Menutupi"], jawaban: 1, penjelasan: "'Mengungkapkan' bersinonim dengan 'menyatakan'.", kategori: "Sinonim" },
  { soal: "Sinonim kata 'kegiatan' adalah...", opsi: ["Aktivitas","Keadaan","Kejadian","Keterangan"], jawaban: 0, penjelasan: "'Kegiatan' bersinonim dengan 'aktivitas'.", kategori: "Sinonim" },
  { soal: "Antonim kata 'sederhana' adalah...", opsi: ["Biasa","Mewah","Lumrah","Sekadar"], jawaban: 1, penjelasan: "Lawan kata 'sederhana' adalah 'mewah'.", kategori: "Antonim" },
  { soal: "Antonim kata 'menangis' adalah...", opsi: ["Sedih","Tertawa","Bersedih","Merintih"], jawaban: 1, penjelasan: "Lawan kata 'menangis' adalah 'tertawa'.", kategori: "Antonim" },
  { soal: "Lawan kata 'bodoh' adalah...", opsi: ["Dungu","Pintar","Polos","Lambat"], jawaban: 1, penjelasan: "Lawan kata 'bodoh' adalah 'pintar'.", kategori: "Antonim" },
  { soal: "Antonim kata 'gagal' adalah...", opsi: ["Salah","Berhasil","Sesat","Keliru"], jawaban: 1, penjelasan: "Lawan kata 'gagal' adalah 'berhasil'.", kategori: "Antonim" },
  { soal: "Lawan kata 'kikir' adalah...", opsi: ["Pelit","Dermawan","Hemat","Boros"], jawaban: 1, penjelasan: "Lawan kata 'kikir' adalah 'dermawan'.", kategori: "Antonim" },
  { soal: "Antonim kata 'jujur' adalah...", opsi: ["Bohong","Lurus","Tulus","Ikhlas"], jawaban: 0, penjelasan: "Lawan kata 'jujur' adalah 'bohong'.", kategori: "Antonim" },
  { soal: "Lawan kata 'berani' adalah...", opsi: ["Gagah","Penakut","Perkasa","Nekat"], jawaban: 1, penjelasan: "Lawan kata 'berani' adalah 'penakut'.", kategori: "Antonim" },
  { soal: "Antonim kata 'miskin' adalah...", opsi: ["Kekurangan","Kaya","Fakir","Pas-pasan"], jawaban: 1, penjelasan: "Lawan kata 'miskin' adalah 'kaya'.", kategori: "Antonim" },
  { soal: "Bentuk kata 'me-' + 'sapu' menjadi 'menyapu'. Awalan 'me-' berubah karena huruf awal 's'...", opsi: ["Tidak berubah","Luluh menjadi 'ny'","Berubah menjadi 'm'","Hilang"], jawaban: 1, penjelasan: "Huruf 's' luluh menjadi 'ny' setelah awalan 'me-'.", kategori: "Imbuhan" },
  { soal: "Kata 'terbawa' berarti...", opsi: ["Sengaja membawa","Tidak sengaja ikut terbawa","Sedang membawa","Akan membawa"], jawaban: 1, penjelasan: "Awalan 'ter-' menyatakan makna 'tidak sengaja'.", kategori: "Imbuhan" },
  { soal: "Imbuhan 'per-an' pada kata 'perjalanan' menyatakan...", opsi: ["Pelaku","Tempat","Hal atau hasil","Alat"], jawaban: 2, penjelasan: "'Per-an' menyatakan hal/berkaitan: 'perjalanan'.", kategori: "Imbuhan" },
  { soal: "Kata 'pekerja' berawalan...", opsi: ["pe-","pe-an","ber-","ter-"], jawaban: 0, penjelasan: "'Pekerja' berawalan 'pe-'.", kategori: "Imbuhan" },
  { soal: "Bentuk 'ber-' + 'main' yang benar adalah...", opsi: ["Bermain","Bermainan","Memain","Berimain"], jawaban: 0, penjelasan: "'ber-' + 'main' = 'bermain'.", kategori: "Imbuhan" },
  { soal: "Awalan 'di-' pada 'dijual' membentuk kalimat...", opsi: ["Aktif","Pasif","Tanya","Perintah"], jawaban: 1, penjelasan: "Kalimat 'dijual' berawalan 'di-' bersifat pasif.", kategori: "Imbuhan" },
  { soal: "Penulisan gelar yang benar: 'Rina Wati, S.Pd.' Tanda titik dipakai...", opsi: ["Di akhir nama","Setelah singkatan gelar","Tidak perlu","Di awal"], jawaban: 1, penjelasan: "Singkatan gelar diakhiri titik: 'S.Pd.'", kategori: "Ejaan" },
  { soal: "Kalimat yang benar penggunaannya: 'Ani belajar ___ 07.00.'", opsi: ["Pada","di","Ke","Dari"], jawaban: 0, penjelasan: "Kata depan 'pada' dipakai untuk waktu.", kategori: "Ejaan" },
  { soal: "Tanda koma dipakai setelah kata...", opsi: ["Dan","Hai","Karena","Atau"], jawaban: 1, penjelasan: "Koma dipakai setelah kata seru seperti 'Hai'.", kategori: "Ejaan" },
  { soal: "Penulisan yang benar: ...", opsi: ["di 2026","Pada tahun 2026","ditahun 2026","Pada-tahun 2026"], jawaban: 1, penjelasan: "Untuk tahun dipakai 'pada tahun 2026'.", kategori: "Ejaan" },
  { soal: "Kata depan 'dari' yang benar: 'Aku pulang ___ sekolah.'", opsi: ["dari","dari-sekolah","darisekolah","dariSekolah (salah)"], jawaban: 0, penjelasan: "'Dari' penunjuk asal ditulis terpisah.", kategori: "Ejaan" },
  { soal: "Partikel 'pun' yang ditulis terpisah adalah...", opsi: ["Kendatipun","Apa pun","Meskipun","Walaupun"], jawaban: 1, penjelasan: "'Pun' ditulis terpisah pada 'apa pun'; bentuk seperti 'meskipun' serangkai.", kategori: "Ejaan" },
  { soal: "Makna peribahasa 'tong kosong nyaring bunyinya' adalah...", opsi: ["Suara kaleng nyaring","Orang bodoh banyak bicara","Bunyi keras","Barang kosong"], jawaban: 1, penjelasan: "Peribahasa ini bermakna orang yang kurang ilmu biasanya banyak bicara.", kategori: "Ungkapan" },
  { soal: "Makna ungkapan 'buah hati' adalah...", opsi: ["Hati yang sehat","Anak kesayangan","Buah segar","Organ tubuh"], jawaban: 1, penjelasan: "'Buah hati' berarti anak/orang yang sangat disayang.", kategori: "Ungkapan" },
  { soal: "Makna peribahasa 'bagai kacang lupa kulitnya' adalah...", opsi: ["Pandai melupakan","Orang yang lupa asal-usulnya","Kacang yang hilang","Kulit kacang"], jawaban: 1, penjelasan: "Peribahasa ini berarti lupa asal-usul setelah sukses.", kategori: "Ungkapan" },
  { soal: "Makna ungkapan 'tangan besi' adalah...", opsi: ["Kuat","Pemimpin yang keras","Kikir","Rapat"], jawaban: 1, penjelasan: "'Tangan besi' berarti kepemimpinan yang keras.", kategori: "Ungkapan" },
  { soal: "Makna peribahasa 'sudah jatuh tertimpa tangga' adalah...", opsi: ["Sedang jatuh","Malang bertambah malang","Jatuh lalu ditimpa","Sering jatuh"], jawaban: 1, penjelasan: "Peribahasa ini berarti kemalangan yang bertumpuk.", kategori: "Ungkapan" },
  { soal: "Makna ungkapan 'membanting tulang' adalah...", opsi: ["Berolahraga","Bekerja keras","Mematahkan tulang","Berantem"], jawaban: 1, penjelasan: "'Membanting tulang' berarti bekerja keras.", kategori: "Ungkapan" },
  { soal: "Makna peribahasa 'gajah di pelupuk mata tidak terlihat' adalah...", opsi: ["Mata besar","Tidak melihat kesalahan sendiri","Melihat jauh","Gajah besar"], jawaban: 1, penjelasan: "Peribahasa ini berarti kesalahan sendiri tidak disadari.", kategori: "Ungkapan" },
  { soal: "Kalimat yang efektif: 'Karena ia rajin, maka ia pun berhasil.' Perbaikannya...", opsi: ["Karena rajin, ia berhasil","Karena ia rajin, maka berhasil","Ia rajin maka berhasil","Semua benar"], jawaban: 0, penjelasan: "Hindari kata ganda 'karena ... maka': cukup salah satu.", kategori: "Kalimat Efektif" },
  { soal: "Pilihan kata yang tepat: 'Mereka ___ acara itu berhasil.'", opsi: ["menyetujui","memutuskan","menganggap","mengira"], jawaban: 2, penjelasan: "Kata yang tepat untuk menyatakan pendapat adalah 'menganggap'.", kategori: "Kalimat Efektif" },
  { soal: "Kalimat efektif yang benar: ...", opsi: ["Waktu dan tempat dipersilakan","Kepada hadirin kami ucapkan terima kasih","Para hadirin sekalian","Terima kasih atas waktunya"], jawaban: 1, penjelasan: "Kalimat yang jelas subjek-predikatnya adalah 'Kepada hadirin kami ucapkan terima kasih'.", kategori: "Kalimat Efektif" },
  { soal: "Kata 'para' tidak perlu dipakai pada kalimat...", opsi: ["Para tamu undangan","Para guru-guru","Para siswa","Para orang tua"], jawaban: 1, penjelasan: "'Para' + 'guru-guru' ganda jamak, cukup 'para guru'.", kategori: "Kalimat Efektif" },
  { soal: "Kata 'tetapi' sebaiknya dipakai dalam kalimat...", opsi: ["Dia pintar tetapi malas","Dia dan saya pergi","Kami ke pasar atau ke toko","Karena hujan kami pulang"], jawaban: 0, penjelasan: "'Tetapi' menyatakan pertentangan.", kategori: "Kalimat Efektif" },
  { soal: "Kata 'karena' pada kalimat 'Kami pulang ___ hujan.'", opsi: ["sebab","tetapi","atau","dan"], jawaban: 0, penjelasan: "'Sebab/karena' menyatakan alasan.", kategori: "Kalimat Efektif" },
  { soal: "Kata 'melukis' termasuk kata...", opsi: ["Benda","Kerja","Sifat","Bilangan"], jawaban: 1, penjelasan: "'Melukis' menyatakan perbuatan, kata kerja.", kategori: "Jenis Kata" },
  { soal: "Kata 'gemar' termasuk jenis kata...", opsi: ["Benda","Kerja","Sifat","Bilangan"], jawaban: 2, penjelasan: "'Gemar' menyatakan keadaan, kata sifat.", kategori: "Jenis Kata" },
  { soal: "Dalam kalimat 'Adik minum susu', kata 'susu' berfungsi sebagai...", opsi: ["Subjek","Predikat","Objek","Keterangan"], jawaban: 2, penjelasan: "'Susu' adalah objek yang dikenai perbuatan 'minum'.", kategori: "Jenis Kata" },
  { soal: "Kata ganti orang kedua tunggal adalah...", opsi: ["saya","dia","kami","kamu"], jawaban: 3, penjelasan: "'Kamu' adalah kata ganti orang kedua tunggal.", kategori: "Jenis Kata" },
  { soal: "Kata 'dengan' termasuk jenis kata...", opsi: ["Kata kerja","Kata depan","Kata sifat","Kata bilangan"], jawaban: 1, penjelasan: "'Dengan' adalah kata depan (preposisi).", kategori: "Jenis Kata" },
];


/**
 * Bank gabungan: kurasi inti (142) + ekspansi 2026 (90) — dipakai harvest
 * agar solo game & duel mendapat variasi lebih banyak. Soal ekspansi punya
 * `tingkat` (EASY/MEDIUM/HARD) yang dipetakan harvest ke lvl ramp.
 */
import { BANK_EKSPANSI_2026 } from "./question-bank-expansion";

export const QUESTION_BANK_EXPANDED: BankQuestion[] = [
  ...QUESTION_BANK,
  ...BANK_EKSPANSI_2026,
];
