import type { Konten } from "../types"
import { makeSoal } from "../types"

const konten: Konten = {
  belajar: {
    tujuan: [
      "Memahami pengertian ejaan dan fungsinya dalam bahasa Indonesia",
      "Menguasai 15+ aturan penggunaan huruf kapital dengan benar",
      "Menerapkan aturan penulisan kata: di-, ke-, kata ulang, dan partikel",
    ],
    materi: [
      {
        judul: "Apa Itu Ejaan?",
        isi: [
          "Ejaan adalah aturan cara menulis kata, huruf, dan tanda baca dalam bahasa Indonesia. Bayangkan ejaan seperti RAMBU LALU LINTAS dalam menulis — membuat tulisan seragam, jelas, dan mudah dipahami semua orang.",
          "EYD V (Ejaan yang Disempurnakan edisi V) adalah pedoman resmi terbaru yang diterbitkan tahun 2022 oleh Badan Bahasa. Setiap kata punya bentuk BAKU yang harus kamu ikuti.",
          "Mengapa ejaan penting?",
          "  • Agar tulisanmu terlihat PROFESIONAL dan KREDIBEL",
          "  • Menghindari KESALAHPAHAMAN makna (contoh: 'di rumah' vs 'dirumah')",
          "  • Memudahkan pembaca memahami pesanmu",
        ],
        contoh: [
          "BENAR: Aktivitas hari ini menyenangkan.",
          "SALAH: Aktifitas hari ini menyenangkan. (tidak baku)",
          "BENAR: Jadwal rapat sudah ditentukan.",
          "SALAH: Jadual rapat sudah ditentukan. (tidak baku)",
        ],
        catatan: "Ragu dengan bentuk baku? Cek saja di kbbi.kemdikbud.go.id — ini adalah kamus resmi bahasa Indonesia.",
      },
      {
        judul: "Aturan Dasar Huruf Kapital",
        isi: [
          "Huruf kapital dipakai dalam situasi-situasi berikut. Perhatikan baik-baik!",
          "",
          "1. AWAL KALIMAT — Setiap awal kalimat WAJIB pakai huruf kapital.",
          "  ✓ Hari ini cuaca sangat cerah.",
          "  ✗ hari ini cuaca sangat cerah.",
          "",
          "2. NAMA ORANG — Termasuk nama panggilan, julukan, dan nama tokoh.",
          "  ✓ Andi, Kartini, Ki Hajar Dewantara, Jokowi",
          "  ✗ andi, kartini, ki hajar dewantara",
          "  PENTING: Nama orang yang diikuti gelar: Dr. Soepomo, Ir. Soekarno",
          "",
          "3. NAMA TEMPAT — Pulau, gunung, sungai, jalan, kota, negara, provinsi.",
          "  ✓ Pulau Bali, Gunung Merapi, Jalan Sudirman, Kota Bandung",
          "  ✗ pulau bali, gunung merapi, jalan sudirman",
          "  PENTING: Kata seperti 'pulau', 'gunung', 'jalan' diikuti nama — keduanya kapital.",
          "",
          "4. NAMA BANGSA, SUKU, BAHASA, TAHUN",
          "  ✓ bangsa Indonesia, suku Sunda, bahasa Jawa, tahun Hijriah",
          "  ✗ bangsa indonesia, suku sunda",
          "",
          "5. JUDUL BUKU, FILM, LAGU, ARTIKEL",
          "  ✓ Novel Laskar Pelangi, film Habibie & Ainun",
          "  ✗ novel laskar pelangi",
          "  Aturan: setiap kata utama pakai kapital. Kata sambung seperti 'dan', 'di', 'ke' tidak kapital.",
          "",
          "6. SAPAAN dan GELAR",
          "  ✓ Surat Bapak sudah saya terima.",
          "  ✓ Terima kasih, Ibu.",
          "  ✗ surat bapak sudah saya terima.",
          "",
          "7. NAMA AGAMA, KITAB SUCI, TUHAN",
          "  ✓ Islam, Al-Qur'an, Allah, Tuhan Yang Maha Esa",
          "",
          "8. SINGKATAN NAMA LEMBAGA",
          "  ✓ PBB, WHO, SMA Negeri 1 Jakarta",
        ],
        contoh: [
          "BENAR: \"Hari Kemerdekaan 17 Agustus\" — H kapital karena awal kalimat, K dan A kapital karena kata utama dalam judul.",
          "SALAH: \"hari kemerdekaan 17 agustus\" — semua huruf kecil.",
          "BENAR: \"Pulau Jawa terkenal dengan budayanya.\"",
          "SALAH: \"pulau jawa terkenal dengan budayanya.\"",
        ],
        catatan: "Ingat: kata 'di' pada 'di sekolah' adalah KATA DEPAN (menunjukkan tempat) — ditulis terpisah dengan huruf kecil. Bukan kata kerja!",
      },
      {
        judul: "Kata Depan di, ke, dari",
        isi: [
          "Ini adalah aturan yang PALING SERING salah dalam tulisan sehari-hari. Perhatikan bedanya:",
          "",
          "KATA DEPAN (menunjukkan tempat) — DITULIS TERPISAH",
          "  ✓ di rumah, di sekolah, di Jakarta, di atas meja",
          "  ✗ dirumah, disekolah, dijakarta",
          "",
          "  ✓ ke pasar, ke kantor, ke Bandung",
          "  ✌ kepasar, kekantor, kebandung",
          "",
          "  ✓ dari rumah, dari Jakarta, dari atas",
          "  ✗ darirumah, darijakarta",
          "",
          "AWALAN di- (kata kerja pasif) — DITULIS SERANGKAI",
          "  ✓ dimakan, ditulis, dibeli, dimasak",
          "  ✗ di makan, di tulis, di beli",
          "",
          "CARA MEMBEDAKAN:",
          "  • Jika menunjukkan LOKASI/TEMPAT → pisah (di sini, di sana, di kantor)",
          "  • Jika menunjukkan TINDAKAN/KATA KERJA → gabung (dimakan, dicuci, dibaca)",
          "",
          "  Tes: kalau bisa diganti 'ke' → itu kata depan tempat → pisah.",
          "  Kalau bisa diganti 'telah di-' → itu kata kerja pasif → gabung.",
        ],
        contoh: [
          "BENAR: \"Adik bermain di halaman.\" (tempat → pisah)",
          "BENAR: \"Nasi itu dimakan adik.\" (kata kerja → gabung)",
          "SALAH: \"Adik bermain dihalaman.\" (gabung padahal tempat)",
          "SALAH: \"Nasi itu di makan adik.\" (pisah padahal kata kerja)",
          "BENAR: \"Dia pergi ke sekolah.\"",
          "SALAH: \"Dia pergi kesekolah.\"",
        ],
        catatan: "Mnemonic: TEMPAT → PISAH. KERJA → GABUNG. Hafalkan ini dan kamu akan menghindari 90% kesalahan ejaan!",
      },
      {
        judul: "Kata Ulang dan Partikel",
        isi: [
          "KATA ULANG — Selalu pakai TANDA HUBUNG (-):",
          "  ✓ anak-anak, buku-buku, berlari-lari, sayur-mayur",
          "  ✗ anakanak, anak anak, buku buku",
          "",
          "  Kata ulang berubah makna:",
          "  • anak-anak = banyak anak, bukan satu anak",
          "  • paman-paman = para paman, bukan 'paman dan paman'",
          "  • mobil-mobilan = mainan mobil (bukan mobil sungguhan)",
          "",
          "PARTIKEL -lah, -kah, -tah — DITULIS SERANGKAI:",
          "  ✓ bacalah, apakah, siapakah, apatah",
          "  ✗ baca lah, apakah, siapa kah",
          "",
          "PARTIKEL -pun — DITULIS TERPISAH, kecuali yang sudah baku:",
          "  ✓ apa pun, siapa pun, kapan pun, satu pun",
          "  ✗ apapun, siapapun",
          "  PENGECUALIAN (sudah baku serangkai): adapun, meskipun, walaupun, sekalipun, bagaimanapun",
        ],
        contoh: [
          "BENAR: \"Anak-anak sedang bermain di halaman.\"",
          "SALAH: \"Anakanak sedang bermain di halaman.\"",
          "BENAR: \"Bacalah buku itu sampai selesai!\"",
          "SALAH: \"Baca lah buku itu sampai selesai!\"",
          "BENAR: \"Siapa pun boleh ikut, asal daftar.\"",
          "BENAR: \"Meskipun hujan, dia tetap berangkat.\" (sudah baku serangkai)",
        ],
        catatan: "Kata ulang sering salah di media sosial. Ingat: kata ulang SELALU pakai tanda hubung. Kecuali kata seperti 'pura-pura', 'mondar-mandir' yang sudah dianggap bentuk tetap.",
      },
      {
        judul: "Kata Baku vs Tidak Baku",
        isi: [
          "Kata baku adalah kata yang penulisannya sesuai dengan KBBI (Kamus Besar Bahasa Indonesia). Berikut kata-kata yang SERING SALAH:",
          "",
          "  ✓ aktivitas          ✗ aktifitas",
          "  ✓ jadwal             ✗ jadual",
          "  ✓ cendekiawan        ✗ cendikiawan",
          "  ✓ karier             ✗ karir",
          "  ✓ frekuensi          ✗ frekwensi",
          "  ✓ apotek             ✗ apotik",
          "  ✓ praktik            ✗ praktek",
          "  ✓ nasihat             ✗ nasehat",
          "  ✓ izin               ✗ ijin",
          "  ✓ sistem             ✗ sistim",
          "  ✓ bus                ✗ bis",
          "  ✓ komplet            ✗ komplit",
          "  ✓ kualitas           ✗ kwalitas",
          "  ✓ risiko             ✗ resiko",
          "  ✓ provinsi           ✗ propinsi",
          "  ✓ andal              ✗ handal",
          "",
          "Tips menghafal:",
          "  • Kata serapan dari bahasa asing sering berubah bentuk. Hafalkan!",
          "  • Kata dengan akhiran -si/-asi biasanya baku (aktivitas, kualitas)",
          "  • Rajin-rajin cek KBBI jika ragu.",
        ],
        contoh: [
          "BENAR: \"Dia punya karier yang cemerlang.\"",
          "SALAH: \"Dia punya karir yang cemerlang.\"",
          "BENAR: \"Aktivitas hari ini padat.\"",
          "SALAH: \"Aktifitas hari ini padat.\"",
          "BENAR: \"Ibu membeli obat di apotek.\"",
          "SALAH: \"Ibu membeli obat di apotik.\"",
        ],
        catatan: "Kata 'ibu kota' ditulis DUA KATA (bukan 'ibukota'). Kata 'terima kasih' ditulis DUA KATA (bukan 'terimakasih').",
      },
    ],
    rangkuman: [
      "EYD V adalah pedoman ejaan resmi bahasa Indonesia (2022).",
      "Huruf kapital: awal kalimat, nama orang, tempat, bangsa, judul, sapaan, gelar, agama, singkatan lembaga.",
      "Kata depan 'di', 'ke', 'dari' untuk tempat → ditulis TERPISAH.",
      "Awalan 'di-' untuk kata kerja pasif → ditulis SERANGKAI.",
      "Kata ulang selalu pakai tanda hubung: anak-anak, buku-buku.",
      "Partikel -lah, -kah, -tah serangkai. Partikel -pun terpisah (kecuali yang baku).",
      "Gunakan KBBI untuk cek kata baku. Rajin-rajin mengecek!",
    ],
  },

  latihan: makeSoal([
    ["Penulisan yang sesuai EYD...", ["Aktifitas", "Aktivitas", "Aktipitas", "Aktif"], 1, "Bentuk baku: aktivitas (dengan v, bukan f)."],
    ["Penulisan judul yang benar...", ["negara Kesatuan RI", "Negara Kesatuan RI", "Negara kesatuan RI", "negara kesatuan RI"], 1, "Judul: setiap kata utama pakai kapital. 'Negara' dan 'Kesatuan' adalah kata utama."],
    ["'di' sebagai kata depan tempat ditulis...", ["Digabung", "Dipisah", "Dihubung", "Dimiringkan"], 1, "Kata depan 'di' untuk tempat → pisah. Contoh: di rumah, di sekolah."],
    ["Penulisan 'dibeli' yang benar...", ["Di beli", "Dibeli", "di-beli", "diBeli"], 1, "Kata kerja pasif 'di-' digabung. Dibeli = dibeli (serangkai)."],
    ["Penulisan kata ulang yang benar...", ["Anak-anak", "Anakanak", "Anak anak", "Anak-anak"], 0, "Kata ulang selalu pakai tanda hubung. Anak-anak (benar, opsi pertama)."],
    ["Partikel '-lah' pada 'bacalah' ditulis...", ["Terpisah", "Serangkai", "Pakai spasi", "Pakai titik"], 1, "Partikel -lah, -kah, -tah SERANGKAI dengan kata dasar."],
    ["Penulisan yang benar...", ["Pulau jawa", "Pulau Jawa", "pulau Jawa", "pulau jawa"], 1, "Nama tempat: 'Pulau' (kata geografis) dan 'Jawa' (nama) sama-sama kapital."],
    ["Penulisan 'di Jalan Merdeka'...", ["Benar — di pisah (tempat), Jalan kapital (nama)", "Salah, seharusnya digabung", "Salah, Jalan tidak perlu kapital", "Semua salah"], 0, "'di' kata depan tempat → pisah. 'Jalan Merdeka' nama jalan → kapital. Jadi benar."],
    ["Bentuk baku yang tepat...", ["Cendikiawan", "Cendekiawan", "Cendikia", "Cendekia"], 1, "Baku: cendekiawan (dengan e, bukan i)."],
    ["Kata 'ibu kota' penulisan baku...", ["Ibukota", "Ibu kota", "Ibu-kota", "Ibukota"], 1, "Baku: 'ibu kota' — dua kata terpisah. Sama seperti 'terima kasih'."],
  ]),

  praktik: {
    petunjuk: "Perbaiki ejaan, huruf kapital, dan kata baku dalam paragraf berikut:\n\nsaya dan teman2 pergi ke curug Cilember. kami berangkat jam 7 pagi dari jakarta. di sana kami bermain air dan foto2. aktifitas ini sangat menyenangkan. kami juga beli oleh2 di toko dekat air terjun. perjalanan pulang sangatmacet, tetapi kami tetap senang.",
    tips: [
      "Kapital di awal kalimat: 'Saya' bukan 'saya', 'Kami' bukan 'kami'",
      "Nama kota & tempat: 'Jakarta' dengan J kapital, 'Curug Cilember' kapital",
      "'di' kata depan tempat → dipisah: 'di sana', 'di toko'",
      "Ganti angka 2 dengan kata ulang: 'teman-teman', 'foto-foto', 'oleh-oleh'",
      "Kata baku: 'aktivitas' bukan 'aktifitas', 'macet' sudah baku",
    ],
    contoh: "Saya dan teman-teman pergi ke Curug Cilember. Kami berangkat jam 7 pagi dari Jakarta. Di sana kami bermain air dan foto-foto. Aktivitas ini sangat menyenangkan. Kami juga membeli oleh-oleh di toko dekat air terjun. Perjalanan pulang sangat macet, tetapi kami tetap senang.",
  },

  kuis: makeSoal([
    ["EYD singkatan dari...", ["Ejaan Yang Disempurnakan", "Ejaan Bahasa Indonesia", "Ejaan dan Tulisan", "Ejaan Yuridis"], 0, "EYD = Ejaan yang Disempurnakan. Edisi terbaru adalah EYD V (2022)."],
    ["Penulisan 'dimaksud' yang benar...", ["Dipisah (di maksud)", "Digabung (dimaksud)", "Pakai spasi", "Pakai tanda hubung"], 1, "'dimaksud' adalah kata kerja pasif (di- + maksud) → serangkai."],
    ["Penulisan yang SALAH...", ["Karier", "Karir", "Kreativitas", "Frekuensi"], 1, "Baku: karier (bukan karir). Kreativitas dan frekuensi sudah benar."],
    ["'ke' pada 'ke rumah' ditulis...", ["Digabung", "Dipisah", "Dimiringkan", "Dihubung"], 1, "'ke rumah' → kata depan ke + tempat → pisah."],
    ["Bentuk baku dari 'dipersilahkan'...", ["Tetap: dipersilahkan", "Dipersilakan", "Dipersonilakan", "Dipresilakan"], 1, "Baku: dipersilakan (tanpa h). Kata dasar: sila, bukan silah."],
  ]),
}

export default konten
