import type { Konten } from "../types"
import { makeSoal } from "../types"

const konten: Konten = {
  belajar: {
    tujuan: [
      "Memahami pengertian, ciri-ciri, dan jenis cerita fantasi",
      "Mengidentifikasi struktur cerita fantasi (orientasi, komplikasi, resolusi)",
      "Menganalisis kaidah kebahasaan cerita fantasi: kata keterangan waktu, konjungsi urutan, kata ganti, dialog",
      "Menulis cerita fantasi pendek dengan alur yang menarik dan unsur imajinasi yang kreatif",
    ],
    materi: [
      {
        judul: "Apa Itu Cerita Fantasi?",
        isi: [
          "Pernahkah kamu membayangkan bisa terbang di atas awan, berbicara dengan hewan, atau mengunjungi istana di negeri awan? Hal-hal yang mustahil terjadi di dunia nyata ternyata bisa 'nyata' dalam cerita fantasi!",
          "",
          "Cerita fantasi adalah cerita yang dikembangkan berdasarkan khayalan atau imajinasi penulis. Cerita ini menghadirkan hal-hal yang tidak mungkin terjadi di dunia nyata — keajaiban, sihir, makhluk supranatural, atau peristiwa di luar nalar manusia. Unsur fantasi inilah yang membedakan cerita fantasi dari jenis cerita lainnya.",
          "",
          "• Ciri-ciri cerita fantasi:",
          "  • Mengandung keajaiban atau kemustahilan: sesuatu yang tidak mungkin terjadi di dunia nyata menjadi mungkin dalam cerita (contoh: penyihir, naga, perjalanan waktu).",
          "  • Tokoh unik dan tidak biasa: tokoh bisa berupa makhluk mitologi (peri, kurcaci, raksasa), manusia dengan kekuatan super, atau hewan yang bisa bicara.",
          "  • Latar lintas ruang dan waktu: cerita bisa berpindah dari dunia nyata ke dunia imajinasi, atau melompat ke masa lampau/masa depan.",
          "  • Konflik bersifat supranatural: masalah dalam cerita sering melibatkan kekuatan gaib, sihir, atau takdir.",
          "  • Bersifat fiktif: seluruh cerita adalah hasil rekaan, bukan kejadian nyata.",
          "",
          "• Jenis cerita fantasi berdasarkan kesesuaian dengan dunia nyata:",
          "  1. Fantasi Total — Seluruh unsur cerita adalah fantasi. Latar, tokoh, dan konflik sepenuhnya hasil imajinasi. Contoh: cerita tentang kerajaan peri di negeri antah-berantah yang belum pernah ada di peta mana pun.",
          "  2. Fantasi Irisan — Dunia nyata bercampur dengan dunia fantasi. Cerita berawal dari dunia nyata lalu tokoh memasuki dunia fantasi. Contoh: seorang anak SD menemukan lorong rahasia di perpustakaan sekolah yang membawanya ke kerajaan bawah tanah.",
          "",
          "PENTING: Cerita fantasi berbeda dengan cerita imajinasi biasa. Cerita fantasi MENGHADIRKAN unsur kemustahilan sebagai inti cerita, bukan sekadar hiasan. Jika cerita hanya menggunakan imajinasi untuk menggambarkan sesuatu yang mungkin terjadi, itu belum bisa disebut cerita fantasi.",
        ],
        contoh: [
          "Contoh Fantasi Total:",
          "\"Di kerajaan Awan Permai, hiduplah seorang putri bernama Ayla yang bersayap embun. Setiap malam purnama, ia menari di atas hamparan awan berlapis emas. Suatu ketika, Raja Angin Murka datang mengamuk dan menculik ayahandanya. Ayla harus mencari Tiga Permata Cahaya untuk menyelamatkan kerajaannya.\"",
          "",
          "Contoh Fantasi Irisan:",
          "\"Rafi adalah anak kelas VII yang tidak pernah percaya pada hal-hal mistis. Namun, saat ia membersihkan gudang sekolah, ia menemukan cermin tua yang mengeluarkan cahaya kehijauan. Ketika ia menyentuhnya, tiba-tiba ia tersedot ke dalam cermin dan terdampar di sebuah hutan ajaib dengan pohon-pohon berwarna ungu yang bisa berbicara.\"",
        ],
        catatan: "Kreativitas adalah kunci cerita fantasi, tetapi ingat: cerita fantasi yang baik tetap memiliki LOGIKA internal. Dunia fantasimu harus punya aturan sendiri yang konsisten. Jika di duniamu karakter bisa terbang dengan jubah, jangan tiba-tiba mereka lupa cara terbang tanpa alasan yang jelas.",
      },
      {
        judul: "Struktur dan Kebahasaan Cerita Fantasi",
        isi: [
          "Cerita fantasi yang baik memiliki struktur yang jelas dan kaidah bahasa yang khas. Mari kita pelajari satu per satu!",
          "",
          "STRUKTUR CERITA FANTASI",
          "",
          "1. ORIENTASI — Bagian pembuka cerita. Berisi pengenalan tokoh, latar tempat, latar waktu, dan suasana. Orientasi harus menarik agar pembaca penasaran dan ingin melanjutkan membaca.",
          "  Contoh: \"Di sebuah desa kecil di lereng Gunung Tersapu Mega, hiduplah seorang anak laki-laki bernama Kael. Ia tinggal berdua dengan ibunya di sebuah gubuk bambu. Tak ada yang istimewa dari dirinya — sampai suatu malam, bintang jatuh menghantam halaman rumahnya.\"",
          "",
          "2. KOMLIKASI — Bagian pertengahan di mana konflik mulai muncul dan berkembang. Masalah demi masalah berdatangan, ketegangan meningkat. Biasanya tokoh utama menghadapi rintangan, bertemu musuh, atau menemukan rahasia besar.",
          "  Contoh: \"Bintang jatuh itu ternyata bukan batu biasa. Di dalamnya tersimpan sebuah kristal biru yang mengeluarkan suara berbisik. 'Kael... bawa aku ke Puncak Kabut... selamatkan duniamu...' Bisik kristal itu. Sejak malam itu, makhluk-makhluk bayangan mulai mengejar Kael ke mana pun ia pergi.\"",
          "",
          "3. RESOLUSI — Bagian penyelesaian konflik. Tokoh utama berhasil mengatasi masalah atau gagal (akhir tragis). Resolusi yang memuaskan adalah yang logis sesuai alur cerita.",
          "  Contoh: \"Dengan bantuan Nenek Rembulan, Kael berhasil mengalahkan Raja Bayangan. Kristal biru pecah menjadi ribuan titik cahaya yang menyebar ke seluruh penjuru desa, menyembuhkan tanah yang kering dan membawa kedamaian. Kael kembali ke gubuknya, bukan lagi anak biasa — ia adalah Penjaga Kristal.\"",
          "",
          "KAIDAH KEBAHASAAN CERITA FANTASI",
          "",
          "1. KATA KETERANGAN WAKTU — Menunjukkan urutan waktu dalam cerita.",
          "  Contoh: suatu hari, pada zaman dahulu, tiba-tiba, ketika itu, sejak saat itu, beberapa hari kemudian",
          "  ✓ \"Suatu hari, Kael menemukan sebuah gua misterius.\"",
          "  ✓ \"Tiba-tiba, langit berubah menjadi gelap gulita.\"",
          "",
          "2. KONJUNGSI URUTAN — Kata hubung yang menunjukkan urutan peristiwa.",
          "  Contoh: kemudian, lalu, setelah itu, akhirnya, sebelum, sementara itu",
          "  ✓ \"Kael memasuki gua itu, lalu pintu di belakangnya tertutup rapat.\"",
          "",
          "3. KATA GANTI ORANG — Cerita fantasi umumnya menggunakan sudut pandang orang pertama (aku) atau orang ketiga (dia, mereka).",
          "  ✓ Orang pertama: \"Aku melangkah hati-hati di lorong gelap itu.\"",
          "  ✓ Orang ketiga: \"Mereka berlari sekencang-kencangnya dikejar naga api.\"",
          "",
          "4. DIALOG — Percakapan antartokoh membuat cerita lebih hidup dan alami.",
          "  ✓ \"Siapa kau?\" tanya Kael gemetar.",
          "  ✓ \"Aku penjaga gua ini. Kau tidak boleh lewat!\" jawab suara itu.",
          "",
          "5. KATA YANG MENUNJUKKAN KEJAIBAN — Kata-kata yang memperkuat suasana fantasi.",
          "  Contoh: ajaib, misterius, gaib, supranatural, mustahil, sakti, ampuh",
        ],
        contoh: [
          "BENAR (orientasi jelas dan menarik): \"Di sudut paling gelap Pasar Bawah Tanah, seorang anak perempuan berjubah merah berlari terbirit-birit. Di tangannya tergenggam sebuah botol kecil berisi pasir keemasan. Namanya Luna, dan ia sedang dikejar oleh tiga siluman ular.\"",
          "SALAH (orientasi tidak jelas): \"Luna lari karena dikejar. Ada pasir emas di botol. Iya, itu ceritanya.\" (Pembaca tidak tahu siapa Luna, di mana lokasinya, kenapa dikejar.)",
          "BENAR (penggunaan konjungsi urutan): \"Pertama, kristal itu bersinar redup. Kemudian, sinarnya semakin terang. Lalu, tiba-tiba ledakan cahaya memenuhi ruangan. Setelah itu, semuanya gelap kembali.\"",
          "SALAH (tanpa konjungsi): \"Kristal bersinar redup. Sinar terang. Ledakan cahaya. Gelap.\" (Kalimat terputus-putus, alurnya tidak mengalir.)",
        ],
        catatan: "Struktur orientasi-komplikasi-resolusi bisa dikembangkan lebih kompleks dengan menambahkan klimaks (puncak konflik) sebelum resolusi. Untuk cerita fantasi pendek, tiga struktur utama sudah cukup. Pastikan komplikasi benar-benar menegangkan dan resolusi terasa memuaskan!",
      },
      {
        judul: "Tips Menulis Cerita Fantasi yang Menarik",
        isi: [
          "Ingin menulis cerita fantasi yang membuat pembaca terpukau? Ikuti tips-tips berikut!",
          "",
          "1. CIPTAKAN DUNIA YANG MEYAKINKAN",
          "  Meskipun dunia ceritamu penuh sihir dan keajaiban, dunia itu harus terasa 'nyata' bagi pembaca. Gambarkan detailnya: bagaimana cuacanya? Apa yang unik dari penduduknya? Apa aturan sihir yang berlaku?",
          "  ✓ \"Di Negeri Alabasta, salju tidak pernah turun — yang turun dari langit adalah butiran-butiran kristal gula. Penduduknya memanen gula kristal itu dan menjualnya ke kerajaan-kerajaan tetangga.\"",
          "",
          "2. KENALKAN TOKOH YANG KUAT DAN UNIK",
          "  Tokoh utama tidak harus sempurna. Justru tokoh dengan kelemahan lebih menarik karena pembaca bisa berempati. Beri tokohmu mimpi, ketakutan, dan rahasia.",
          "  ✓ Tokoh dengan kelemahan: \"Rara takut pada kegelapan sejak kecil. Ironisnya, ia harus melewati Hutan Angker yang gelap gulita untuk menyelamatkan adiknya.\"",
          "",
          "3. GUNAKAN KEJUTAN DAN PLOT TWIST",
          "  Pembaca menyukai kejutan. Sisipkan misteri yang perlahan terungkap. Siapa sangka sahabat dekat tokoh utama ternyata adalah penjahat yang selama ini dicari?",
          "  ✓ \"Kael terpaku. Nenek Rembulan, yang selama ini membantunya, ternyata adalah Ratu Bayangan yang menyamar. 'Kau kukorbankan untuk kristal biru itu,' katanya sambil tertawa.\"",
          "",
          "4. SEIMBANGKAN DIALOG DAN NARASI",
          "  Terlalu banyak narasi membuat cerita membosankan. Terlalu banyak dialog membuatnya dangkal. Seimbangkan keduanya.",
          "  ✓ Narasi: \"Kael membuka pintu kayu tua itu dengan hati-hati. Engselnya berderit memekakkan telinga.\" Dialog: \"Ada siapa di sini?\" bisik Kael. \"Aku...,\" jawab suara serak dari kegelapan. \"Aku sudah menunggumu sejak lama.\"",
          "",
          "5. AKHIRI DENGAN RESOLUSI YANG BERKESAN",
          "  Akhir cerita adalah yang paling diingat pembaca. Akhir bahagia, akhir tragis, atau akhir menggantung — pilih yang paling cocok dengan ceritamu. Pastikan resolusi menyelesaikan konflik utama yang dibangun.",
          "  Tips: Hindari akhir yang terlalu 'instant' atau tiba-tiba. Misalnya, tokoh tiba-tiba menang tanpa perjuangan. Itu akan mengecewakan pembaca.",
          "",
          "PENTING: Cerita fantasi bukan sekadar kumpulan keajaiban. Cerita fantasi yang hebat adalah cerita yang membuat pembaca percaya — setidaknya selama membaca — bahwa dunia ajaib itu benar-benar ada. Caranya? Beri detail yang hidup, konsisten, dan penuh perasaan!",
        ],
        contoh: [
          "Tips membuat deskripsi dunia fantasi yang hidup:",
          "\"Tidak seperti hutan biasa, Hutan Pelangi memiliki pepohonan dengan batang berwarna-warni: merah, jingga, kuning, biru, dan ungu. Daun-daunnya tidak hijau melainkan perak keperakan yang berkilau saat terkena cahaya bulan. Di malam hari, akar-akar pohon mengeluarkan cahaya kuning redup, menerangi jalan setapak. Udara di sini beraroma manis seperti campuran madu dan kayu manis. Burung-burung cendrawasih dengan bulu bercahaya beterbangan di antara dahan.\"",
          "",
          "Contoh pengembangan tokoh:",
          "\"Bimo bukan anak istimewa — nilainya pas-pasan, tidak jago olahraga, dan pemalu. Tapi ia memiliki satu kelebihan yang tidak diketahui siapa pun: ia bisa memahami bahasa hewan. Selama bertahun-tahun ia merahasiakannya. Namun, ketika sekelompok garuda emas datang memperingatkan akan datangnya bencana, Bimo harus memilih: tetap diam atau bicara dan dianggap gila oleh semua orang.\"",
        ],
        catatan: "Tips paling penting: BANYAKLAH MEMBACA! Semakin banyak cerita fantasi yang kamu baca, semakin kaya imajinasimu. Baca karya penulis Indonesia seperti 'Petualangan Nevi' atau 'Harian Seorang Pencari Sihir', dan penulis luar seperti J.K. Rowling (Harry Potter) atau C.S. Lewis (Narnia).",
      },
    ],
    rangkuman: [
      "Cerita fantasi adalah cerita yang dikembangkan berdasarkan khayalan/imajinasi, menghadirkan unsur kemustahilan, keajaiban, atau sihir sebagai inti cerita.",
      "Ciri utama: mengandung keajaiban, tokoh unik, latar lintas ruang/waktu, konflik supranatural, dan bersifat fiktif.",
      "Dua jenis cerita fantasi: fantasi total (semua unsur imajinasi) dan fantasi irisan (dunia nyata bercampur fantasi).",
      "Struktur cerita fantasi: orientasi (pengenalan) → komplikasi (konflik berkembang) → resolusi (penyelesaian). Bisa ditambah klimaks sebelum resolusi.",
      "Kaidah kebahasaan: kata keterangan waktu (suatu hari, tiba-tiba), konjungsi urutan (kemudian, lalu, setelah itu), kata ganti orang (aku, mereka), dialog, dan kata yang menunjukkan keajaiban (gaib, sakti, misterius).",
      "Tips menulis: ciptakan dunia yang meyakinkan dengan detail, kenalkan tokoh kuat dengan kelemahan, gunakan kejutan/plot twist, seimbangkan dialog dan narasi, serta akhiri dengan resolusi berkesan.",
      "Contoh cerita fantasi terkenal: Harry Potter, The Chronicles of Narnia, Percy Jackson, dan dari Indonesia: serial Kino, Petualangan Nevi, dan Kisah Tanah Jawa.",
    ],
  },

  latihan: makeSoal([
    // 5 Soal Pilihan Ganda
    ["Cerita fantasi adalah cerita yang dikembangkan berdasarkan...", ["Kejadian nyata sehari-hari", "Khayalan atau imajinasi penulis", "Data dan fakta ilmiah", "Pengalaman pribadi penulis"], 1, "Cerita fantasi berasal dari imajinasi penulis dan menghadirkan hal-hal yang tidak mungkin terjadi di dunia nyata."],
    ["Berikut ini yang merupakan CIRI cerita fantasi adalah...", ["Berisi data hasil observasi", "Latar hanya di dunia nyata", "Mengandung unsur keajaiban", "Tokoh selalu manusia biasa"], 2, "Unsur keajaiban/kemustahilan adalah ciri utama cerita fantasi. Ciri lainnya: tokoh unik, latar lintas ruang/waktu, konflik supranatural."],
    ["Bagian cerita fantasi yang berisi pengenalan tokoh dan latar disebut...", ["Resolusi", "Komplikasi", "Klimaks", "Orientasi"], 3, "Orientasi adalah bagian pembuka yang mengenalkan tokoh, tempat, waktu, dan suasana cerita."],
    ["Contoh kalimat yang menggunakan kata keterangan waktu dalam cerita fantasi adalah...", ["Kael berjalan di pasar", "Suatu hari, Kael menemukan gua misterius", "Kael suka bermain bola", "Kael adalah anak yang baik"], 1, "'Suatu hari' adalah kata keterangan waktu yang khas dalam cerita fantasi untuk memulai urutan peristiwa."],
    ["Jenis cerita fantasi yang memadukan dunia nyata dan dunia imajinasi disebut...", ["Fantasi total", "Fantasi irisan", "Fantasi murni", "Fantasi ilmiah"], 1, "Fantasi irisan adalah cerita yang berawal dari dunia nyata lalu tokoh memasuki dunia fantasi. Contoh: anak menemukan portal di sekolah dan masuk ke kerajaan ajaib."],

    // 3 Soal Betul/Salah
    ["Pernyataan: 'Cerita fantasi harus selalu berlatar di kerajaan atau negeri dongeng.'", ["Betul", "Salah"], 1, "SALAH. Cerita fantasi bisa berlatar di mana saja — di sekolah, kota modern, hutan, atau bahkan planet lain. Yang penting adalah adanya unsur kemustahilan/keajaiban."],
    ["Pernyataan: 'Resolusi adalah bagian akhir cerita yang berisi penyelesaian konflik.'", ["Betul", "Salah"], 0, "BETUL. Resolusi adalah bagian di mana konflik utama diselesaikan, entah dengan akhir bahagia, tragis, atau menggantung."],
    ["Pernyataan: 'Kata-kata seperti kemudian, lalu, dan setelah itu termasuk konjungsi urutan.'", ["Betul", "Salah"], 0, "BETUL. Konjungsi urutan (atau konjungsi temporal) berfungsi menghubungkan peristiwa secara berurutan. Contoh: kemudian, lalu, setelah itu, akhirnya."],

    // 2 Soal Isian Singkat
    ["Struktur cerita fantasi secara berurutan yang benar adalah orientasi — ... — resolusi.", ["eksposisi", "komplikasi", "evaluasi", "reorientasi"], 1, "Setelah orientasi (pengenalan), dilanjutkan komplikasi (konflik muncul dan berkembang), lalu resolusi (penyelesaian)."],
    ["'Naga api menyemburkan lidah api ke arah Kael.' Kata 'naga api' dalam kalimat tersebut menunjukkan ciri cerita fantasi berupa...", ["tokoh unik", "latar fantasi", "konflik supranatural", "keajaiban"], 0, "Naga api adalah tokoh unik/tidak biasa yang hanya ada dalam cerita fantasi. Ini menunjukkan ciri tokoh yang khas dan tidak ditemukan di dunia nyata."],
  ]),

  praktik: {
    petunjuk: "Buatlah cerita fantasi PENDEK sepanjang 3—5 paragraf dengan ketentuan berikut:\n\n1. Paragraf 1 (ORIENTASI): Perkenalkan tokoh utama dan latar ceritamu. Pastikan pembaca langsung tertarik! Gunakan kata keterangan waktu seperti 'suatu hari', 'pada zaman dahulu', atau 'di sebuah...'.\n\n2. Paragraf 2 (KOMLIKASI): Munculkan konflik atau masalah. Tokoh utama menghadapi rintangan, bertemu musuh, atau menemukan sesuatu yang mengubah segalanya.\n\n3. Paragraf 3 (RESOLUSI): Selesaikan konflik dengan cara yang menarik. Bisa akhir bahagia, sedih, atau menggantung (cliffhanger).\n\n4. Gunakan MINIMAL 2 konjungsi urutan (kemudian, lalu, setelah itu, akhirnya).\n5. Sertakan MINIMAL 1 dialog antartokoh.\n6. Pastikan ada unsur fantasi/keajaiban di dalam ceritamu.\n\nSelamat menulis, calon penulis hebat!",
    tips: [
      "Mulailah dengan kalimat pembuka yang mengejutkan atau misterius, misalnya: 'Tidak ada yang menyangka bahwa di balik lemari tua perpustakaan sekolah, tersembunyi sebuah dunia yang menunggu untuk dijelajahi.'",
      "Ciptakan tokoh dengan nama yang unik dan mudah diingat, tetapi jangan terlalu sulit diucapkan. Hindari nama yang terlalu panjang atau susah dieja.",
      "Gunakan panca indra dalam deskripsimu: bagaimana suara, bau, rasa, dan tekstur di dunia fantasi ciptaanmu?",
      "Jangan terburu-buru menyelesaikan cerita. Biarkan konflik berkembang secara alami. Pembaca perlu waktu untuk peduli pada tokoh sebelum masalah muncul.",
      "Baca ulang ceritamu dan periksa: apakah semua bagian jelas? Apakah ada bagian yang membingungkan? Minta teman membacanya dan tanya pendapat mereka!",
      "Jangan takut 'meminjam' ide dari cerita favoritmu, tetapi olah kembali dengan caramu sendiri. Inspirasi boleh sama, tetapi jiplakan tidak!",
    ],
    contoh: "Di sebuah desa di kaki Gunung Sanggabuana, hiduplah seorang anak laki-laki bernama Bima. Ia anak pendiam yang gemar mengoleksi batu-batu aneh. Tidak ada yang istimewa dari dirinya — sampai suatu malam, saat purnama penuh, batu koleksi kesayangannya tiba-tiba bersinar terang. \"Bima... bangunlah...\" bisik suara dari dalam batu itu. Bima tersentak. Batu itu bergetar dan retak, lalu dari celahnya muncul cahaya keemasan yang memenuhi seluruh kamarnya. Setelah itu, seorang peri kecil bersayap embun melayang di depannya. \"Aku Butana, penjaga Gerbang Timur. Aku sudah menunggumu selama seribu tahun. Kau Keturunan Penjaga yang terakhir.\" Bima tidak percaya. \"Aku? Penjaga? Maksudmu?\" tanyanya bingung. \"Ikut aku, dan kau akan tahu segalanya,\" jawab Butana sambil melayang ke jendela. Bima ragu sejenak, lalu mengikuti peri kecil itu melompat ke luar jendela. Malam itu adalah awal dari petualangan terbesar dalam hidupnya. Ia tidak lagi anak biasa — ia adalah Penjaga Gerbang Timur yang harus menyelamatkan keseimbangan dunia.",
  },

  kuis: makeSoal([
    ["Perbedaan utama cerita fantasi dengan cerita rekaan lainnya (seperti cerpen realis) adalah...", ["Cerita fantasi lebih panjang", "Cerita fantasi menghadirkan unsur kemustahilan sebagai inti cerita", "Cerita fantasi tidak memiliki tokoh", "Cerita fantasi selalu berakhir bahagia"], 1, "Unsur kemustahilan/keajaiban adalah pembeda utama. Cerpen realis menggambarkan kehidupan yang mungkin terjadi, sedangkan fantasi menghadirkan hal-hal mustahil."],
    ["Cermati penggalan cerita berikut: 'Lina tidak sengaja memecahkan vas antik di rumah neneknya. Tiba-tiba, asap putih membumbung dan seorang jin muncul, berkata, \"Kau telah membebaskanku. Aku akan mengabulkan tiga permintaanmu.\"' Berdasarkan jenisnya, cerita tersebut termasuk...", ["Fantasi total", "Fantasi irisan", "Fantasi ilmiah", "Dongeng biasa"], 1, "Cerita berawal dari dunia nyata (Lina memecahkan vas di rumah nenek) lalu memasuki dunia fantasi (jin muncul). Ini ciri fantasi irisan."],
    ["Kata 'tiba-tiba', 'seketika', dan 'saat itu juga' termasuk jenis kata...", ["Konjungsi urutan", "Kata sifat", "Kata keterangan waktu", "Kata ganti orang"], 2, "Kata-kata tersebut adalah kata keterangan waktu (adverbia temporal) yang menunjukkan saat terjadinya peristiwa secara tiba-tiba."],
    ["Dalam struktur cerita fantasi, bagian KOMLIKASI berfungsi untuk...", ["Memperkenalkan tokoh dan latar", "Menceritakan akhir cerita", "Menghadirkan dan mengembangkan konflik", "Memberikan pesan moral"], 2, "Komplikasi adalah bagian inti cerita di mana konflik muncul, berkembang, dan ketegangan meningkat."],
    ["Kalimat 'Peri kecil itu menari di atas daun teratai' mengandung unsur fantasi berupa...", ["Tokoh fantasi (peri)", "Latar fantasi (daun teratai)", "Sihir atau mantra", "Perjalanan waktu"], 0, "Peri adalah makhluk fantasi/tokoh unik yang tidak ada di dunia nyata. Daun teratai adalah benda nyata, bukan unsur fantasi."],
    ["Kaidah kebahasaan yang KHAS dalam cerita fantasi adalah penggunaan...", ["Kata ilmiah dan istilah teknis", "Kata keterangan waktu dan konjungsi urutan", "Kata seru dan kata perintah", "Kata bilangan dan kata ukuran"], 1, "Kata keterangan waktu (suatu hari, tiba-tiba) dan konjungsi urutan (kemudian, lalu, setelah itu) sangat khas dalam cerita fantasi untuk membangun alur."],
    ["Penulisan dialog dalam cerita fantasi yang benar sesuai EYD adalah...", ["Apa kau seekor naga? tanya kael", "\"Apa kau seekor naga?\" tanya Kael", "\"Apa kau seekor naga?\" Tanya Kael", "\"Apa kau seekor naga,\" tanya Kael"], 1, "Dialog diapit tanda petik dua, setelah tanda tanya tidak perlu titik, nama tokoh diawali kapital, dan kata 'tanya' ditulis dengan huruf kecil."],
    ["Cermati kalimat: 'Kael melangkah masuk ke gua. Kemudian, pintu di belakangnya tertutup rapat. Lalu, obor-obor menyala sendiri.' Kata 'kemudian' dan 'lalu' berfungsi sebagai...", ["Kata ganti", "Konjungsi urutan", "Kata keterangan tempat", "Kata kerja"], 1, "'Kemudian' dan 'lalu' adalah konjungsi urutan (temporal) yang menghubungkan peristiwa secara berurutan: masuk gua → pintu tertutup → obor menyala."],
    ["Berikut ini yang merupakan contoh FANTASI TOTAL adalah...", ["Seorang anak menemukan koin ajaib di pasar", "Di negeri Awan Biru, semua penduduk bersayap kupu-kupu dan tinggal di istana kapas", "Rina bermimpi menjadi penyanyi terkenal", "Doni membantu temannya yang jatuh dari sepeda"], 1, "Fantasi total adalah cerita di mana seluruh unsurnya fantasi. Negeri Awan Biru dengan penduduk bersayap adalah fantasi total karena tidak ada kaitan dengan dunia nyata."],
    ["Tips menulis cerita fantasi yang PALING TEPAT adalah...", ["Gunakan bahasa yang rumit agar terlihat keren", "Ciptakan dunia fantasi dengan detail yang meyakinkan dan konsisten", "Tiru habis-habisan cerita fantasi terkenal", "Jangan gunakan dialog karena membuang-buang waktu"], 1, "Dunia fantasi harus terasa 'nyata' dengan detail dan aturan internal yang konsisten. Menjiplak cerita orang lain adalah plagiarisme."],
  ]),
}

export default konten
