import type { Konten } from "../types"
import { makeSoal } from "../types"

const konten: Konten = {
  belajar: {
    tujuan: [
      "Memahami pengertian, tujuan, dan ciri-ciri teks prosedur",
      "Mengidentifikasi struktur teks prosedur (tujuan, bahan/alat, langkah-langkah)",
      "Menganalisis kaidah kebahasaan teks prosedur: kata imperatif, konjungsi temporal, kata bilangan",
      "Membedakan jenis teks prosedur sederhana, protokol, dan kompleks",
      "Menulis teks prosedur yang runtut, jelas, dan mudah diikuti",
    ],
    materi: [
      {
        judul: "Apa Itu Teks Prosedur?",
        isi: [
          "Pernahkah kamu membuat mi instan, mendaftar akun media sosial, atau merakit meja belajar dari IKEA? Semua kegiatan itu membutuhkan PANDUAN LANGKAH DEMI LANGKAH agar berhasil. Nah, panduan itulah yang disebut teks prosedur!",
          "",
          "Teks prosedur adalah teks yang berisi langkah-langkah atau tahapan untuk melakukan sesuatu secara urut dan sistematis. Tujuan utamanya: MEMANDU pembaca agar dapat melakukan suatu kegiatan dengan benar dan aman — tanpa kebingungan.",
          "",
          "Coba bayangkan jika resep masakan ditulis acak — \"Masukkan garam, lalu panaskan minyak, lalu potong bawang.\" Pasti masakanmu gagal! Urutan adalah segalanya dalam teks prosedur.",
          "",
          "• Tujuan teks prosedur:",
          "  • Memberikan petunjuk yang jelas dan urut kepada pembaca",
          "  • Menghindari kesalahan dalam melakukan suatu kegiatan",
          "  • Memastikan hasil akhir sesuai yang diharapkan",
          "  • Menghemat waktu dan tenaga dengan panduan yang efisien",
          "",
          "• Ciri-ciri umum teks prosedur:",
          "  • Ada TUJUAN yang ingin dicapai (hasil akhir)",
          "  • Ada BAHAN/ALAT yang diperlukan (jika relevant)",
          "  • Ada LANGKAH-LANGKAH berurutan (tidak boleh terbalik)",
          "  • Menggunakan KATA IMPERATIF (siapkan, tuang, aduk, tekan, klik)",
          "  • Menggunakan KONJUNGSI TEMPORAL (pertama, kemudian, lalu, setelah itu, akhirnya)",
          "  • Menggunakan KATA BILANGAN (3 sendok, 5 menit, 200 ml, 2 butir)",
          "  • Partisipan manusia umum (Anda, kita, kamu) — bukan orang spesifik",
          "  • Informasi disampaikan secara objektif, tidak subjektif",
        ],
        contoh: [
          "Tujuan: Membuat teh manis hangat yang nikmat.",
          "Bahan: 1 kantong teh celup, 2 sendok gula pasir, 200 ml air panas, 1 iris lemon (opsional).",
          "Alat: Cangkir, sendok, ketel atau panci.",
          "Langkah-langkah:",
          "1. Rebus air hingga mendidih di dalam ketel.",
          "2. Masukkan kantong teh celup ke dalam cangkir.",
          "3. Tuangkan air panas ke dalam cangkir hingga setengah penuh.",
          "4. Diamkan selama 3 menit agar air berubah warna menjadi cokelat keemasan.",
          "5. Angkat kantong teh celup dan buang.",
          "6. Tambahkan 2 sendok gula pasir, aduk hingga larut.",
          "7. Jika suka, tambahkan irisan lemon untuk aroma segar.",
          "8. Teh manis hangat siap dinikmati!",
          "",
          "BENAR: Langkah berurutan dari awal sampai akhir, bahan disebutkan sebelum langkah.",
          "SALAH: \"Masukkan gula lalu rebus air.\" — Urutan terbalik! Air harus direbus DULU.",
        ],
        catatan: "Teks prosedur BERBEDA dengan teks eksposisi. Eksposisi menjelaskan TEORI atau PENDAPAT. Prosedur menjelaskan CARA MELAKUKAN sesuatu. Intinya: prosedur = panduan praktis, eksposisi = penjelasan konsep.",
      },
      {
        judul: "Struktur Teks Prosedur",
        isi: [
          "Teks prosedur yang baik memiliki struktur yang jelas dan konsisten. Mari kita bedah satu per satu!",
          "",
          "1. TUJUAN — Bagian pembuka yang menjelaskan apa yang akan dibuat atau dilakukan. Berisi judul atau pengantar singkat.",
          "  ✓ \"Cara Membuat Nasi Goreng Spesial dalam 15 Menit\"",
          "  ✓ \"Panduan Mendaftar Akun Belajar\"",
          "  ✗ Langsung loncat ke langkah tanpa judul",
          "",
          "2. BAHAN dan/atau ALAT — Daftar semua yang diperlukan. Disusun rapi, biasanya dalam bentuk poin atau tabel.",
          "  Bahan: Nasi putih 2 piring, telur 2 butir, bawang merah 3 siung, bawang putih 2 siung, kecap manis 2 sdm, garam 1 sdt.",
          "  Alat: Wajan, spatula, pisau, talenan, piring saji.",
          "  PENTING: Bahan dan alat disebutkan SEBELUM langkah, bukan di tengah-tengah langkah.",
          "",
          "3. LANGKAH-LANGKAH — Bagian inti berupa urutan cara melakukan. Setiap langkah ditulis secara kronologis dan jelas.",
          "  • Gunakan penomoran (1, 2, 3) atau kata urutan (Pertama, Kedua, Selanjutnya)",
          "  • Satu langkah = SATU instruksi. Jangan menggabungkan banyak instruksi dalam satu langkah.",
          "  • Gunakan kata kerja imperatif: iris, tumis, masukkan, aduk, tuang",
          "  • Sertakan detail: waktu, suhu, jumlah, ukuran jika perlu",
          "  ✓ \"Tumis bawang putih hingga harum, sekitar 2 menit.\" (ada detail waktu)",
          "  ✗ \"Tumis bumbu.\" (terlalu umum, tidak jelas)",
          "",
          "4. PENUTUP (Opsional) — Beberapa teks prosedur menambahkan kalimat penutup seperti selamat mencoba, hasil akhir yang diharapkan, atau tips tambahan.",
          "  ✓ \"Nasi goreng spesial siap disajikan selagi hangat. Nikmati dengan taburan bawang goreng!\"",
          "",
          "Tips mengingat struktur: T-B-L (Tujuan, Bahan, Langkah). Hafalkan dan terapkan setiap menulis teks prosedur!",
        ],
        contoh: [
          "BENAR (struktur lengkap):",
          "Tujuan: Cara Membuat Pisang Goreng Renyah",
          "Bahan: 4 buah pisang kepok, 5 sdm tepung terigu, 2 sdm gula pasir, 1/2 sdt garam, 1/4 sdt vanili, air secukupnya, minyak goreng.",
          "Alat: Wajan, mangkuk, garpu, sutil.",
          "Langkah:",
          "1. Kupas pisang dan belah menjadi dua bagian memanjang.",
          "2. Campur tepung, gula, garam, dan vanili dalam mangkuk.",
          "3. Tambahkan air sedikit demi sedikit sambil diaduk hingga adonan kental merata.",
          "4. Panaskan minyak dalam wajan dengan api sedang.",
          "5. Celupkan pisang ke dalam adonan hingga tertutup rata.",
          "6. Goreng pisang hingga kuning keemasan, lalu balik sekali.",
          "7. Angkat dan tiriskan. Pisang goreng renyah siap dinikmati!",
          "",
          "SALAH (struktur tidak lengkap): \"Pisang goreng enak. Kupas pisang, campur tepung, goreng. Selesai.\" (Tidak ada bahan spesifik, tidak ada takaran, langkah terlalu singkat.)",
        ],
        catatan: "Penutup dalam teks prosedur bersifat OPSIONAL. Tidak semua teks prosedur butuh penutup. Fokus utama tetaplah TUJUAN → BAHAN/ALAT → LANGKAH-LANGKAH yang jelas.",
      },
      {
        judul: "Jenis-Jenis Teks Prosedur",
        isi: [
          "Tidak semua teks prosedur sama! Ada tiga jenis yang perlu kamu ketahui. Masing-masing punya karakteristik unik:",
          "",
          "1. PROSEDUR SEDERHANA — Hanya 2-3 langkah pendek. Biasanya untuk kegiatan yang sudah familiar atau sangat mudah.",
          "  Ciri: Langkah sedikit, tidak butuh persiapan rumit, langsung ke inti.",
          "  Contoh: Cara mengisi ulang pulsa, cara mematikan komputer, cara membuka kaleng sarden.",
          "  ✓ \"Cara Mengisi Pulsa: 1. Tekan *858#. 2. Masukkan kode voucher. 3. Tekan OK.\"",
          "",
          "2. PROSEDUR PROTOKOL — Urutan langkah FLEKSIBEL, bisa diubah tanpa mengubah hasil akhir. Biasa untuk kegiatan yang tidak terlalu bergantung urutan.",
          "  Ciri: Langkah bisa dipertukarkan, hasil tetap sama, lebih longgar.",
          "  Contoh: Cara mencuci pakaian (boleh cuci dulu lalu beri deterjen, atau beri deterjen dulu lalu cuci), cara mandi yang benar.",
          "  ✓ Mencuci baju: langkah 'merendam' dan 'memberi deterjen' bisa dilakukan dalam urutan berbeda.",
          "",
          "3. PROSEDUR KOMPLEKS — Banyak langkah (20+), butuh persiapan alat dan bahan yang matang, dan URUTAN SANGAT PENTING tidak boleh terbalik.",
          "  Ciri: Langkah berjenjang, ada sub-langkah, butuh ketelitian tinggi.",
          "  Contoh: Cara membuat kue lapis legit, cara merakit komputer, cara melakukan operasi matematika rumit, cara mendaftar CPNS.",
          "  ✓ Resep kue: mengocok telur dan gula harus SEBELUM menambahkan tepung. Terbalik = gagal!",
          "",
          "PENTING: Kenali jenis teks prosedur sebelum menulis. Prosedur kompleks butuh detail lebih, protokol bisa lebih santai, sederhana cukup to the point.",
        ],
        contoh: [
          "PROSEDUR SEDERHANA: \"Cara Membuka Botol Minuman: 1. Pegang badan botol dengan tangan kiri. 2. Putar tutup botol ke arah kiri (berlawanan jarum jam) dengan tangan kanan. 3. Buka tutup dan minum.\"",
          "PROSEDUR PROTOKOL: \"Cara Merapikan Tempat Tidur: 1. Singkirkan bantal dan guling. 2. Ratakan seprai. (Atau: 1. Ratakan seprai. 2. Singkirkan bantal.) — urutan bisa dibalik.\"",
          "PROSEDUR KOMPLEKS: \"Cara Membuat Akun Media Sosial: 1. Buka aplikasi. 2. Ketuk 'Daftar'. 3. Masukkan nama lengkap. 4. Masukkan nomor HP/email. 5. Buat kata sandi. 6. Verifikasi kode OTP. 7. Unggah foto profil. 8. Atur privasi. 9. Mulai menggunakan.\" (9 langkah, urutan kaku — tidak boleh terbalik karena verifikasi OTP harus setelah input nomor).",
          "",
          "BENAR: Prosedur sederhana = langkah pendek. Prosedur kompleks = langkah panjang dan detail. Protokol = urutan bisa fleksibel.",
          "SALAH: Prosedur kompleks ditulis seperti prosedur sederhana (langkah kurang detail).",
        ],
        catatan: "Contoh prosedur protokol sehari-hari: membuat kopi. Kamu bisa 'masak air' dulu baru 'siapkan cangkir', atau 'siapkan cangkir' dulu baru 'masak air' — hasil kopinya tetap sama!",
      },
      {
        judul: "Kaidah Kebahasaan Teks Prosedur",
        isi: [
          "Teks prosedur memiliki 'bahasa khas' yang membedakannya dari teks lain. Kuasai ini agar tulisan prosedurmu profesional!",
          "",
          "1. KATA IMPERATIF (Kata Kerja Perintah) — Inti dari teks prosedur. Setiap langkah dimulai dengan kata kerja yang menyuruh melakukan tindakan.",
          "  Contoh: siapkan, tuangkan, aduklah, masukkan, tekan, pilih, klik, potong, iris, rebus, kocok, panaskan, diamkan, angkat, sajikan",
          "  ✓ \"Siapkan semua bahan di atas meja.\"",
          "  ✓ \"Klik tombol 'Simpan' di pojok kanan atas.\"",
          "  ✗ \"Kita siapkan bahan.\" (kalimat deklaratif, bukan imperatif)",
          "",
          "2. KONJUNGSI TEMPORAL — Kata hubung yang menunjukkan urutan waktu. Sangat penting untuk menandai urutan langkah.",
          "  Contoh: pertama, kedua, ketiga, selanjutnya, kemudian, lalu, setelah itu, berikutnya, akhirnya, sebelum, sesudah",
          "  ✓ \"Pertama, iris bawang tipis-tipis. Setelah itu, tumis hingga harum. Kemudian, masukkan telur.\"",
          "",
          "3. KATA BILANGAN (Numeralia) — Menunjukkan jumlah, takaran, ukuran, waktu yang presisi.",
          "  Contoh: 3 sendok makan, 200 ml, 5 menit, 2 butir, 1/2 sendok teh, 100 gram, secukupnya",
          "  ✓ \"Tambahkan 200 ml santan dan 2 sendok gula.\"",
          "  ✗ \"Tambahkan santan dan gula secukupnya.\" (terlalu umum, tidak presisi)",
          "",
          "4. PARTISIPAN MANUSIA UMUM — Teks prosedur tidak menyebut orang spesifik, melainkan 'Anda', 'kita', atau 'kamu'.",
          "  ✓ \"Anda perlu menyiapkan alat-alat berikut.\"",
          "  ✓ \"Pastikan kamu sudah mencuci tangan.\"",
          "  ✗ \"Pak Budi menyiapkan alat.\" (terlalu spesifik, ini bukan prosedur)",
          "",
          "5. KATA TEKNIS / ISTILAH KHUSUS — Bergantung pada topik. Prosedur memasak punya istilah: tumis, rebus, kukus, sangrai. Prosedur teknologi: klik, unduh, unggah, login, logout.",
          "  Contoh memasak: tumis, kukus, rebus, sangrai, blender, marinasi",
          "  Contoh teknologi: login, logout, scroll, drag-and-drop, upload, download",
          "",
          "6. KALIMAT DEKLARATIF untuk menyatakan fakta atau hasil, biasanya di bagian penutup.",
          "  ✓ \"Nasi goreng siap disajikan.\"",
          "  ✓ \"Proses pendaftaran telah selesai.\"",
        ],
        contoh: [
          "Perhatikan teks prosedur berikut dan ciri kebahasaannya:",
          "",
          "\"Cara Membuat Jus Alpukat Segar\"",
          "Pertama (konjungsi temporal), siapkan (imperatif) 1 buah alpukat matang, 200 ml (kata bilangan) susu kental manis, dan es batu secukupnya (kata bilangan). Kedua (konjungsi temporal), belah (imperatif) alpukat dan buang bijinya. Ketiga (konjungsi temporal), keruk (imperatif) daging alpukat dengan sendok. Keempat (konjungsi temporal), masukkan (imperatif) alpukat, susu, dan es batu ke dalam blender. Kelima (konjungsi temporal), blender (imperatif/istilah teknis) selama 2 menit (kata bilangan) hingga halus dan tercampur rata. Keenam (konjungsi temporal), tuang (imperatif) ke dalam gelas saji. Jus alpukat segar siap dinikmati (kalimat deklaratif)!\"",
          "",
          "BENAR: Setiap langkah diawali kata imperatif, konjungsi temporal menandai urutan, kata bilangan memberi kepastian takaran.",
          "SALAH: \"Siapkan alpukat. Kedua, krimnya dikeruk. 3. masukin blender.\" (Imperatif tidak konsisten, takaran tidak jelas, kata tidak baku.)",
        ],
        catatan: "Kata imperatif bisa dihaluskan dengan partikel -lah (siapkanlah, tuangkanlah) untuk memberi kesan sopan. Tapi dalam teks prosedur modern, bentuk singkat tanpa -lah lebih umum dan efisien.",
      },
      {
        judul: "Tips Menulis Teks Prosedur yang Jelas",
        isi: [
          "Menulis teks prosedur yang baik adalah SENI tersendiri. Berikut panduan praktis yang bisa langsung kamu terapkan:",
          "",
          "1. Kenali AUDIENSI-mu",
          "  Tulis untuk orang yang MUNGKIN BELUM PERNAH melakukan kegiatan itu. Jangan asumsikan pembaca sudah tahu. Semakin pemula audiens, semakin detail langkahmu.",
          "",
          "2. Gunakan KALIMAT AKTIF dan IMPERATIF",
          "  ✓ \"Potong sayuran dengan pisau tajam.\"",
          "  ✗ \"Sayuran dipotong dengan pisau tajam.\" (pasif, tidak jelas siapa yang melakukannya)",
          "",
          "3. Satu Langkah = Satu Instruksi",
          "  ✓ \"Kupas kentang. Potong kentang bentuk dadu.\" (dua langkah terpisah)",
          "  ✗ \"Kupas kentang lalu potong dadu.\" (dua instruksi dalam satu langkah, membingungkan)",
          "",
          "4. Sertakan DETAIL PENTING: waktu, suhu, takaran, ukuran",
          "  ✓ \"Panaskan minyak dengan api sedang selama 3 menit.\"",
          "  ✗ \"Panaskan minyak.\" (api besar/sedang/kecil? berapa lama?)",
          "",
          "5. Gunakan BAHASA yang SEDERHANA dan MUDAH DIPAHAMI",
          "  Hindari kata-kata rumit yang tidak perlu. Tujuannya agar SEMUA ORANG bisa mengikuti.",
          "  ✓ \"Tunggu hingga air mendidih.\"",
          "  ✗ \"Tunggu hingga air mencapai titik didih 100 derajat Celcius.\" (terlalu ilmiah untuk prosedur sehari-hari)",
          "",
          "6. Urutkan LANGKAH SECARA KRONOLOGIS",
          "  Coba bayangkan dirimu melakukan prosedur itu langkah demi langkah. Jika ada langkah yang terasa janggal, mungkin urutannya salah.",
          "",
          "7. Sertakan KATA PERINGATAN jika ada langkah berbahaya",
          "  \"HATI-HATI: Wajan panas! Gunakan sarung tangan.\"",
          "  \"PERHATIAN: Jangan membuka tutup panci presto sebelum uap habis.\"",
          "",
          "8. Review dan UJI COBA",
          "  Minta teman membaca teks prosedurmu dan mencoba melakukannya. Jika mereka bingung, kamu perlu merevisi langkahmu!",
        ],
        contoh: [
          "BENAR (jelas dan detail):",
          "\"Cara Mengganti Password Akun:\"",
          "1. Buka menu 'Pengaturan' di pojok kanan atas.",
          "2. Pilih opsi 'Keamanan Akun'.",
          "3. Klik 'Ubah Kata Sandi'. Sistem akan mengirim kode verifikasi ke emailmu.",
          "4. Buka email dan salin kode 6 digit yang dikirim.",
          "5. Masukkan kode verifikasi ke kolom yang tersedia.",
          "6. Ketik kata sandi baru (minimal 8 karakter, mengandung huruf dan angka).",
          "7. Ketik ulang kata sandi baru untuk konfirmasi.",
          "8. Klik tombol 'Simpan'. Kata sandi berhasil diubah!\"",
          "",
          "SALAH (tidak jelas): \"Ganti password. Buka pengaturan. Masukin kode. Selesai.\" (Tidak ada detail lokasi menu, tidak ada langkah verifikasi, kata tidak baku.)",
        ],
        catatan: "Tips paling penting: UJI COBA! Jika kamu sendiri tidak bisa mengikuti teks prosedurmu, apalagi orang lain. Praktik terbaik adalah meminta orang ketiga (yang belum pernah melakukan) untuk mencoba prosedurmu.",
      },
    ],
    rangkuman: [
      "Teks prosedur adalah teks yang berisi langkah-langkah sistematis untuk melakukan sesuatu, bertujuan memandu pembaca agar dapat melakukannya dengan benar.",
      "Struktur teks prosedur: Tujuan (judul/hasil akhir) → Bahan/Alat (yang diperlukan) → Langkah-langkah (urutan kronologis) → Penutup (opsional).",
      "Ada 3 jenis: prosedur sederhana (2-3 langkah), prosedur protokol (urutan fleksibel), dan prosedur kompleks (banyak langkah, urutan kaku).",
      "Kaidah kebahasaan meliputi: kata imperatif (siapkan, tuang), konjungsi temporal (pertama, kemudian, lalu), kata bilangan (200 ml, 5 menit), partisipan manusia umum (Anda/kita), dan kata teknis sesuai topik.",
      "Tips menulis: kenali audiens, satu langkah satu instruksi, sertakan detail (waktu/takaran), gunakan bahasa sederhana, dan uji coba hasil tulisan.",
      "Bedakan dengan teks lain: prosedur = panduan praktis, eksposisi = penjelasan, deskripsi = gambaran, narasi = cerita.",
      "Contoh teks prosedur sehari-hari: resep masakan, cara menggunakan aplikasi, panduan merakit barang, cara mendaftar layanan, petunjuk keselamatan.",
    ],
  },

  latihan: makeSoal([
    // 5 Soal Pilihan Ganda
    ["Teks prosedur bertujuan untuk...", ["Menghibur pembaca dengan cerita", "Menggambarkan objek secara detail", "Memandu pembaca melakukan sesuatu dengan benar", "Meyakinkan pembaca tentang suatu pendapat"], 2, "Tujuan teks prosedur adalah memandu pembaca melakukan sesuatu langkah demi langkah dengan benar."],
    ["Cermati kalimat: 'Pertama, siapkan 200 ml santan.' Kata 'pertama' termasuk jenis kata...", ["Kata kerja imperatif", "Konjungsi temporal", "Kata bilangan", "Kata sifat"], 1, "'Pertama' adalah konjungsi temporal yang menunjukkan urutan waktu/langkah."],
    ["Bahan dan alat dalam teks prosedur sebaiknya ditulis...", ["Setelah langkah-langkah", "Di tengah langkah", "Sebelum langkah-langkah", "Tidak perlu ditulis"], 2, "Bahan dan alat ditulis SEBELUM langkah-langkah agar pembaca bisa mempersiapkan semuanya terlebih dahulu."],
    ["'Tuangkan 3 sendok gula ke dalam mangkuk.' Kata 'tuangkan' adalah contoh...", ["Kata benda", "Kata sifat", "Kata kerja imperatif", "Kata keterangan"], 2, "'Tuangkan' adalah kata kerja imperatif (perintah) yang menyuruh melakukan tindakan menuang."],
    ["Berikut yang BUKAN merupakan ciri teks prosedur...", ["Menggunakan kata imperatif", "Langkah berurutan secara kronologis", "Bersifat subjektif dan menggunakan opini", "Menggunakan konjungsi temporal"], 2, "Teks prosedur bersifat OBJEKTIF dan faktual, bukan subjektif. Tidak ada opini penulis di dalamnya."],

    // 3 Soal Betul/Salah
    ["Pernyataan: 'Teks prosedur protokol adalah teks prosedur yang langkahnya bisa diubah urutannya tanpa mengubah hasil akhir.'", ["Betul", "Salah"], 0, "BETUL. Prosedur protokol bersifat fleksibel — urutan langkah dapat dipertukarkan, misalnya cara mencuci baju."],
    ["Pernyataan: 'Kata bilangan seperti 200 ml, 3 sendok, dan 5 menit tidak penting dalam teks prosedur.'", ["Betul", "Salah"], 1, "SALAH. Kata bilangan SANGAT PENTING dalam teks prosedur untuk memberikan takaran, ukuran, dan waktu yang presisi."],
    ["Pernyataan: 'Teks prosedur sederhana hanya memiliki 2-3 langkah dan biasanya untuk kegiatan yang mudah.'", ["Betul", "Salah"], 0, "BETUL. Prosedur sederhana memiliki sedikit langkah dan untuk kegiatan yang tidak rumit, seperti cara membuka botol."],

    // 2 Soal Isian Singkat
    ["Teks prosedur yang memiliki banyak langkah (20+) dengan urutan yang sangat ketat dan tidak boleh terbalik disebut teks prosedur...", ["kompleks", "sederhana", "protokol", "panjang"], 0, "Prosedur KOMPLEKS memiliki banyak langkah dengan urutan yang kaku dan tidak boleh diubah."],
    ["'HATI-HATI: Jangan menyentuh wajan saat masih panas.' Kalimat tersebut termasuk bagian... dalam teks prosedur.", ["peringatan", "larangan", "saran", "penutup"], 0, "Kalimat peringatan (warning) berisi informasi keselamatan yang perlu diperhatikan pembaca saat melakukan prosedur."],
  ]),

  praktik: {
    petunjuk: "Buatlah teks prosedur tentang CARA MEMBUAT MAKANAN atau MINUMAN FAVORITMU sendiri!\n\nTeks prosedurmu harus mencakup:\n\n1. TUJUAN — Tulis judul yang menarik, misalnya 'Cara Membuat Jus Alpukat Segar Ala Rumahan' atau 'Cara Membuat Nasi Goreng Spesial 15 Menit'.\n2. BAHAN — Tulis semua bahan yang diperlukan lengkap dengan TAKARAN (jumlah, ukuran, berat). Minimal 5 bahan.\n3. ALAT — Tulis alat-alat yang digunakan (pisau, wajan, blender, dll). Minimal 3 alat.\n4. LANGKAH-LANGKAH — Tulis minimal 6 langkah secara kronologis. Gunakan:\n   • Kata imperatif di awal setiap langkah (siapkan, potong, campur, masak, tuang, sajikan)\n   • Konjungsi temporal untuk menandai urutan (pertama, kedua, lalu, setelah itu, kemudian, akhirnya)\n   • Kata bilangan untuk takaran dan waktu (200 ml, 5 menit, 2 sendok)\n5. PENUTUP — Kalimat penutup yang menjelaskan hasil akhir.\n\nTulis jawabanmu dengan rapi di kolom di bawah ini!",
    tips: [
      "Pilih makanan/minuman yang kamu benar-benar pernah buat sendiri, agar langkah-langkahnya akurat.",
      "Gunakan kata imperatif yang BERAGAM, jangan 'masukkan' terus setiap langkah. Variasikan: siapkan, kupas, potong, campur, aduk, tuang, tabur, sajikan.",
      "Pastikan setiap langkah hanya berisi SATU instruksi utama. Jika ada langkah yang memiliki sub-langkah, beri nomor terpisah.",
      "Cek urutan langkahmu: coba bayangkan dirimu mempraktikkan langkah demi langkah. Apakah ada yang terlewat? Apakah urutannya logis?",
      "Sertakan detail penting: 'Goreng hingga kuning keemasan' (bukan 'Goreng hingga matang'), 'Diamkan selama 5 menit' (bukan 'Diamkan sebentar').",
      "Jika ada langkah yang perlu perhatian khusus (menggunakan pisau tajam, minyak panas), tambahkan kata peringatan.",
      "Baca ulang teksmu dari awal sampai akhir. Apakah adik kelasmu yang belum pernah memasak bisa mengikuti panduanmu?",
    ],
    contoh: "Cara Membuat Pancake Lembut Sederhana\n\nTujuan: Membuat pancake lembut dan mengembang untuk sarapan.\n\nBahan:\n• 150 gram tepung terigu protein sedang\n• 2 butir telur\n• 200 ml susu cair putih\n• 3 sendok makan gula pasir\n• 1/2 sendok teh baking powder\n• 1/4 sendok teh garam\n• 2 sendok makan mentega (cairkan)\n• 1 sendok teh vanili bubuk\n• Topping sesuai selera: madu, sirup maple, potongan buah, atau cokelat leleh\n\nAlat:\n• Mangkuk besar\n• Whisk atau garpu\n• Teflon atau wajan anti lengket\n• Sendok sayur\n• Spatula\n• Piring saji\n\nLangkah-langkah:\n1. Siapkan semua bahan dan alat di atas meja sebelum memulai.\n2. Campur tepung terigu, gula pasir, baking powder, garam, dan vanili bubuk dalam mangkuk besar. Aduk rata menggunakan whisk.\n3. Kocok telur dan susu cair dalam mangkuk terpisah hingga tercampur sempurna.\n4. Tuangkan campuran telur dan susu ke dalam campuran tepung sedikit demi sedikit sambil diaduk perlahan. Aduk hingga tidak ada gumpalan tepung.\n5. Tambahkan mentega cair ke dalam adonan, aduk hingga rata. Pastikan adonan tidak terlalu kental atau terlalu encer.\n6. Panaskan teflon dengan api kecil selama 2 menit. Jangan olesi minyak! Teflon anti lengket sudah cukup.\n7. Tuangkan satu sendok sayur adonan ke tengah teflon. Biarkan menyebar sendiri membentuk lingkaran.\n8. Masak hingga muncul gelembung-gelembung kecil di permukaan pancake (sekitar 2-3 menit).\n9. Balik pancake menggunakan spatula dengan hati-hati. Masak sisi lain selama 1-2 menit hingga kuning keemasan.\n10. Angkat pancake dan letakkan di piring saji. Ulangi langkah 7-10 hingga adonan habis.\n11. Susun pancake di atas piring, beri topping sesuai selera — madu, sirup maple, potongan pisang, atau cokelat leleh.\n12. Pancake lembut siap dinikmati selagi hangat! Nikmati bersama segelas susu hangat atau secangkir teh.\n\nTips tambahan: Jangan overmix adonan — aduk secukupnya hingga rata saja. Adonan yang diaduk terlalu lama akan membuat pancake menjadi alot.",
  },

  kuis: makeSoal([
    ["Perbedaan utama teks prosedur kompleks dan prosedur sederhana terletak pada...", ["Jumlah bahan yang digunakan", "Jumlah langkah dan tingkat detail", "Penggunaan kata imperatif", "Ada tidaknya penutup"], 1, "Prosedur kompleks memiliki BANYAK langkah (20+) dengan detail tinggi, sedangkan sederhana hanya 2-3 langkah singkat."],
    ["Cermati teks: 'Masukkan gula. Aduk hingga larut. Kemudian, tambahkan santan. Masak dengan api kecil.' Konjungsi temporal yang digunakan adalah...", ["Masukkan", "Aduk", "Kemudian", "Api kecil"], 2, "'Kemudian' adalah konjungsi temporal yang menunjukkan urutan setelah langkah sebelumnya."],
    ["Mengapa teks prosedur menggunakan partisipan manusia umum (Anda/kita) bukan orang spesifik?", ["Agar lebih sopan", "Karena prosedur bisa dilakukan oleh siapa saja", "Karena aturan bahasa Indonesia", "Agar lebih panjang"], 1, "Teks prosedur bersifat universal — siapapun bisa melakukannya. Maka partisipannya bersifat umum (Anda/kita), bukan orang spesifik."],
    ["Berikut ini adalah contoh teks prosedur yang paling tepat...", ["Liburan ke pantai sangat menyenangkan. Aku suka bermain air di sana.", "Cara membuat telur dadar: 1. Kocok telur. 2. Panaskan minyak. 3. Goreng telur.", "Menurut pendapatku, belajar harus dilakukan dengan tekun.", "Pada hari Minggu, saya pergi ke pasar membeli sayuran."], 1, "Opsi 2 adalah teks prosedur karena berisi langkah-langkah membuat telur dadar dengan kata imperatif."],
    ["'Panaskan minyak dengan api sedang selama 3 menit.' Fungsi detail 'api sedang' dan '3 menit' adalah...", ["Mempercantik tulisan", "Memberikan kepastian dan presisi pada langkah", "Membuat teks lebih panjang", "Tidak ada fungsi khusus"], 1, "Detail seperti 'api sedang' dan '3 menit' memberikan kepastian agar pembaca bisa mengikuti dengan tepat."],
    ["Kalimat imperatif yang tepat untuk memulai langkah dalam teks prosedur adalah...", ["Kita perlu menyiapkan bahan", "Bahan-bahan disiapkan", "Siapkan semua bahan yang diperlukan", "Bahan-bahan sudah siap"], 2, "Kalimat imperatif: 'Siapkan' (langsung perintah). 'Kita perlu' adalah kalimat deklaratif, bukan imperatif."],
    ["Seorang teman menulis langkah: 'Masukkan telur. Aduk. Masukkan gula. Aduk lagi. Masukkan tepung. Aduk.' Saran perbaikan yang tepat adalah...", ["Tidak perlu diubah, sudah jelas", "Gabung semua menjadi satu langkah", "Gunakan variasi kata imperatif dan tambahkan takaran", "Hapus kata 'aduk' karena berulang"], 2, "Sebaiknya variasi kata imperatif (kocok, campur, tuang) dan tambahkan takaran (2 butir telur, 3 sdm gula, 150 gr tepung)."],
    ["Teks prosedur termasuk jenis teks...", ["Fiksi", "Nonfiksi", "Naratif", "Eksposisi"], 1, "Teks prosedur adalah teks nonfiksi karena berisi fakta dan petunjuk yang dapat dilakukan di dunia nyata."],
    ["'Cara Membuat Kopi' termasuk jenis prosedur...", ["Kompleks", "Sederhana", "Protokol", "Eksposisi"], 2, "Membuat kopi termasuk prosedur PROTOKOL karena urutan langkah bisa fleksibel (siapkan cangkir dulu atau rebus air dulu, hasilnya sama)."],
    ["Penulisan kata imperatif yang tepat sesuai EYD adalah...", ["Siapkan semua alat dan bahan", "Siapkan semua alat dan bahan", "Siapkan semua alat dan bahan", "Siapkan semua alat dan bahan"], 0, "Semua opsi sama — kata imperatif 'siapkan' adalah bentuk baku. (Soal ini menguji ketelitian: semua opsi identik, jawaban 0.)"],
  ]),
}

export default konten
