import type { Konten } from "../types"
import { makeSoal } from "../types"

const konten: Konten = {
  belajar: {
    tujuan: [
      "Memahami pengertian, ciri-ciri, dan tujuan teks laporan hasil observasi (LHO)",
      "Mengidentifikasi struktur teks LHO (pernyataan umum, deskripsi bagian, simpulan)",
      "Menganalisis kaidah kebahasaan teks LHO: kalimat definisi, klasifikasi, istilah teknis",
      "Membedakan teks LHO dengan teks deskripsi secara kritis",
      "Menyusun teks LHO berdasarkan hasil pengamatan secara sistematis dan objektif",
    ],
    materi: [
      {
        judul: "Apa Itu Teks Laporan Hasil Observasi?",
        isi: [
          "Pernahkah kamu diminta guru untuk mengamati sesuatu — misalnya tanaman di halaman sekolah, kebiasaan hewan peliharaan, atau suasana kantin — lalu menuliskan hasil pengamatanmu? Nah, itulah yang disebut laporan hasil observasi!",
          "",
          "Teks laporan hasil observasi (LHO) adalah teks yang menyajikan informasi faktual tentang suatu objek berdasarkan pengamatan yang sistematis. Teks ini bersifat objektif — artinya penulis tidak boleh menambahkan opini atau perasaan pribadi. Kata observasi berasal dari bahasa Latin observatio yang berarti 'pengamatan' atau 'pemerhatian'.",
          "",
          "✓ Ciri-ciri teks LHO:",
          "  ✓ Bersifat objektif: apa adanya, tidak memihak, berdasarkan data",
          "  ✓ Faktual: semua informasi dapat dibuktikan kebenarannya",
          "  ✓ Menggunakan istilah ilmiah atau teknis yang sesuai dengan objek yang diamati",
          "  ✓ Mengandung kata kerja material (mengamati, mengukur, mengidentifikasi, mengklasifikasikan)",
          "  ✓ Mengandung kalimat definisi (adalah, merupakan, yaitu) dan kalimat klasifikasi (terbagi menjadi, terdiri atas)",
          "  ✓ Ditulis secara sistematis: dari umum ke khusus",
          "",
          "✓ Tujuan teks LHO:",
          "  ✓ Menyajikan informasi faktual tentang objek yang diamati",
          "  • Membantu pembaca memahami karakteristik suatu objek secara objektif",
          "  • Menjadi dasar pengambilan keputusan atau penelitian selanjutnya",
          "  • Mendokumentasikan hasil pengamatan untuk referensi di masa depan",
          "",
          "PENTING: LHO berbeda dengan teks deskripsi! Teks deskripsi bersifat subjektif (berdasarkan kesan, opini, perasaan penulis), sedangkan LHO bersifat objektif (berdasarkan fakta dan data). LHO tidak boleh mengandung 'indah', 'menakjubkan', 'sejuk' — kecuali kata-kata itu memang fakta hasil pengukuran.",
        ],
        contoh: [
          "Contoh LHO (objektif):",
          "\"Kantin SMP Nusantara memiliki luas 12 × 8 meter. Terdapat 15 meja dan 60 kursi yang tersusun dalam 5 baris. Lantai kantin terbuat dari keramik putih berukuran 40 × 40 cm. Ventilasi udara berjumlah 4 jendela dengan ukuran 1 × 1,5 meter di sisi timur dan barat.\"",
          "(Laporan ini objektif: ada ukuran, jumlah, data konkret. Tidak ada opini.)",
          "",
          "Bandingkan dengan teks deskripsi (subjektif):",
          "\"Kantin SMP Nusantara sangat nyaman dan bersih. Meja-mejanya tertata rapi dan indah dipandang. Udara di dalamnya sejuk karena jendela-jendela besar yang membuat ruangan terang.\"",
          "(Deskripsi ini subjektif: 'nyaman, bersih, rapi, indah, sejuk' adalah kesan pribadi, bukan data.)",
        ],
        catatan: "Ingat mantra ini: LHO = FAKTA + DATA + OBJEKTIF. Jika ada kata seperti 'indah, nyaman, menarik' — itu pertanda kamu sedang menulis teks deskripsi, bukan LHO!",
      },
      {
        judul: "Struktur Teks LHO",
        isi: [
          "Teks LHO memiliki struktur yang khas dan sistematis. Coba perhatikan kerangka berikut dengan saksama:",
          "",
          "1. PERNYATAAN UMUM (KLASIFIKASI UMUM) — Bagian pembuka yang berisi definisi atau klasifikasi umum tentang objek yang diamati. Biasanya menjawab: apa objeknya? termasuk kategori apa?",
          "  \"Tanaman lidah buaya (Aloe vera) adalah salah satu jenis tanaman sukulen yang berasal dari Jazirah Arab. Tanaman ini termasuk keluarga Asphodelaceae dan dikenal luas karena khasiatnya di bidang kesehatan.\"",
          "",
          "2. DESKRIPSI BAGIAN — Bagian inti yang memaparkan aspek-aspek objek secara rinci. Aspek yang diamati bisa meliputi ciri fisik, habitat, cara berkembang biak, manfaat, dll. Setiap aspek dijelaskan dengan data dan fakta.",
          "  \"Daun lidah buaya berbentuk panjang meruncing dengan tepi bergerigi. Panjang daun mencapai 30—50 cm dengan lebar 5—10 cm. Permukaan daun dilapisi lilin tebal untuk mengurangi penguapan. Daging daun berwarna putih kehijauan dan mengandung gel transparan yang kaya akan vitamin dan mineral.\"",
          "",
          "3. SIMPULAN (OPSIONAL) — Bagian penutup yang merangkum temuan utama. Tidak semua teks LHO memiliki simpulan. Jika ada, simpulan bersifat ringkas dan tetap objektif.",
          "  \"Berdasarkan pengamatan, lidah buaya memiliki adaptasi fisik yang mendukung kelangsungan hidupnya di daerah kering, yaitu daun tebal berlapis lilin dan jaringan penyimpan air di dalam daun.\"",
          "",
          "PENTING: Dalam teks LHO, struktur bersifat FLEKSIBEL. Beberapa teks LHO menggabungkan pernyataan umum dengan simpulan, atau menambahkan deskripsi manfaat setelah deskripsi bagian. Yang terpenting adalah alur dari umum ke khusus dan penyajian data secara sistematis.",
        ],
        contoh: [
          "BENAR (pernyataan umum jelas): \"Kecoa (Periplaneta americana) adalah serangga dari ordo Blattodea yang hidup di lingkungan tropis dan subtropis. Serangga ini dikenal sebagai salah satu hama rumah tangga yang paling adaptif.\"",
          "SALAH (langsung ke detail): \"Kecoa memiliki panjang 3—5 cm, berwarna cokelat tua, dan memiliki sayap yang berkembang sempurna...\" (Pembaca tidak mendapat gambaran umum tentang apa yang diamati.)",
          "BENAR (deskripsi bagian sistematis): \"Berdasarkan pengamatan terhadap 10 ekor kecoa selama 7 hari, diketahui bahwa kecoa aktif pada malam hari (nokturnal). Suhu optimal aktivitas kecoa adalah 25—30°C. Kecoa lebih menyukai tempat lembap dengan kelembapan 70—80%.\"",
        ],
        catatan: "Gunakan pola: UMUM → KHUSUS. Mulai dari definisi/klasifikasi, lalu rinci ke ciri-ciri fisik, habitat, perilaku, manfaat. Laporkan apa yang kamu lihat dan ukur, bukan apa yang kamu rasa!",
      },
      {
        judul: "Kaidah Kebahasaan Teks LHO",
        isi: [
          "Teks LHO memiliki ciri bahasa yang khas dan berbeda dari teks lainnya. Yuk, pelajari satu per satu!",
          "",
          "1. KALIMAT DEFINISI — Kalimat yang menjelaskan pengertian suatu istilah atau objek. Biasanya menggunakan kata adalah, merupakan, yaitu, ialah.",
          "  ✓ \"Lidah buaya adalah tanaman sukulen yang menyimpan air di daunnya.\"",
          "  ✓ \"Observasi merupakan kegiatan mengamati secara sistematis.\"",
          "",
          "2. KALIMAT KLASIFIKASI — Kalimat yang mengelompokkan sesuatu berdasarkan jenis atau kategorinya.",
          "  ✓ \"Kecoa terbagi menjadi beberapa jenis, yaitu kecoa Amerika, kecoa Jerman, dan kecoa Asia.\"",
          "  ✓ \"Berdasarkan habitatnya, tanaman ini terdiri atas dua kelompok: hidrofit dan xerofit.\"",
          "",
          "3. KATA KERJA PASIF — Karena LHO bersifat ilmiah dan objektif, kata kerja pasif sering digunakan untuk menghilangkan subjek pelaku.",
          "  ✓ \"Pengamatan dilakukan selama tiga hari.\" (bukan: 'Saya melakukan pengamatan')",
          "  ✓ \"Data dikumpulkan melalui wawancara dan dokumentasi.\"",
          "  ✓ \"Suhu ruangan diukur menggunakan termometer digital.\"",
          "",
          "4. ISTILAH TEKNIS/ILMIAH — Penggunaan istilah khusus yang berkaitan dengan objek yang diamati.",
          "  ✓ Biologi: sukulen, nokturnal, ordo, genus, herbivor, karnivor",
          "  ✓ Geografi: topografi, elevasi, garis lintang, ekosistem",
          "  ✓ Umum: spesimen, variabel, parameter, klasifikasi, habitat",
          "",
          "5. KATA KERJA MATERIAL — Kata kerja yang menunjukkan tindakan fisik dalam proses pengamatan.",
          "  ✓ \"Peneliti mengamati perilaku kecoa selama 7 hari.\"",
          "  ✓ \"Kami mengukur tinggi tanaman setiap minggu.\"",
          "  ✓ \"Data yang diperoleh diklasifikasikan berdasarkan jenisnya.\"",
          "",
          "6. KALIMAT KOMPLEKS — LHO sering menggunakan kalimat majemuk bertingkat untuk menjelaskan hubungan sebab-akibat atau syarat.",
          "  ✓ \"Karena daun lidah buaya tebal dan berdaging, tanaman ini mampu bertahan di daerah kering.\"",
          "  ✓ \"Jika suhu lingkungan turun di bawah 15°C, pertumbuhan kecoa akan melambat.\"",
          "",
          "7. KONJUNGSI PENAMBAHAN: dan, serta, selain itu, juga, di samping itu.",
          "   ✓ \"Kecoa memiliki sayap yang berkembang sempurna serta antena yang panjang.\"",
          "",
          "Tips kuasai kebahasaan LHO: Baca artikel ilmiah populer dari majalah atau portal sains. Perhatikan bagaimana mereka mendefinisikan istilah, mengklasifikasikan objek, dan menyajikan data secara objektif. Semakin sering membaca, semakin terbiasa kamu dengan pola bahasanya!",
        ],
        contoh: [
          "BENAR dengan kalimat definisi: \"Observasi adalah kegiatan mengamati suatu objek secara langsung dengan menggunakan pancaindra untuk memperoleh data.\"",
          "BENAR dengan kalimat klasifikasi: \"Berdasarkan wujudnya, sampah terbagi menjadi tiga jenis: sampah padat, sampah cair, dan sampah gas.\"",
          "BENAR dengan kata kerja pasif: \"Pengukuran dilakukan setiap hari pukul 07.00 WIB menggunakan penggaris dan timbangan digital.\"",
          "SALAH (subjektif, bukan LHO): \"Daun lidah buaya sangat indah dengan bentuk yang unik dan warna hijau yang cantik.\"",
        ],
        catatan: "Hindari kata-kata subjektif seperti: indah, bagus, cantik, menarik, enak, nyaman, sedap. Ganti dengan data faktual: 'tinggi 30 cm' bukan 'tinggi sekali'; 'suhu 28°C' bukan 'hangat'; 'berat 250 gram' bukan 'berat'. Fakta, bukan kesan!",
      },
      {
        judul: "Langkah-Langkah Melakukan Observasi",
        isi: [
          "Sebelum menulis LHO, kamu harus melakukan observasi terlebih dahulu. Berikut langkah-langkah sistematisnya:",
          "",
          "1. MENENTUKAN OBJEK OBSERVASI — Pilih objek yang jelas dan dapat diamati secara langsung. Bisa berupa benda mati (tanaman, batu, bangunan) atau makhluk hidup (hewan, tumbuhan, manusia).",
          "  • Pastikan objek dapat diakses dengan mudah",
          "  • Tentukan batasan objek agar pengamatan fokus",
          "  • Contoh: 'Tanaman cabai di pot belakang sekolah' (bukan 'semua tanaman di sekolah')",
          "",
          "2. MENYIAPKAN INSTRUMEN OBSERVASI — Siapkan alat dan panduan observasi.",
          "  • Alat tulis: buku catatan, pulpen, pensil",
          "  • Alat ukur: penggaris, termometer, timbangan, meteran",
          "  • Alat dokumentasi: kamera/hp untuk foto",
          "  • Lembar observasi: tabel atau format catatan yang sudah disiapkan",
          "",
          "3. MELAKUKAN PENGAMATAN — Lakukan pengamatan secara cermat dan sistematis.",
          "  • Amati objek dari berbagai aspek: fisik, perilaku, lingkungan",
          "  • Catat data secara kuantitatif (angka/ukuran) dan kualitatif (warna, bentuk, tekstur)",
          "  • Lakukan pengamatan lebih dari satu kali untuk akurasi data",
          "  • Jangan menambahkan opini saat mencatat",
          "",
          "4. MENCATAT DATA — Tulis semua temuan langsung saat observasi berlangsung.",
          "  • Gunakan tabel atau poin-poin agar rapi",
          "  • Bedakan antara data (fakta) dan interpretasi (analisis)",
          "  • Contoh data: 'Daun berwarna hijau tua, panjang 8 cm, lebar 3 cm'",
          "  • BUKAN interpretasi: 'Daunnya sehat dan subur'",
          "",
          "5. MENYUSUN LAPORAN — Susun data yang sudah dicatat ke dalam teks LHO dengan struktur yang benar.",
          "  • Kelompokkan data berdasarkan aspek yang diamati",
          "  • Tulis dengan bahasa Indonesia yang baik dan benar",
          "  • Gunakan kalimat definisi, klasifikasi, dan istilah teknis",
          "  • Sertakan data pendukung (ukuran, jumlah, suhu, dll.)",
          "",
          "Tips sukses: Observasi yang baik adalah observasi yang TERENCANA. Jangan datang ke lokasi tanpa persiapan! Buat daftar pertanyaan sebelumnya: Apa yang ingin aku ketahui tentang objek ini? Aspek apa saja yang perlu diamati? Alat apa yang harus dibawa?",
        ],
        contoh: [
          "Lembar observasi sederhana (contoh untuk objek: tanaman cabai):",
          "| No | Aspek              | Data Hasil Pengamatan                          |",
          "|----|--------------------|------------------------------------------------|",
          "|  1 | Tinggi tanaman     | 25 cm                                         |",
          "|  2 | Jumlah daun        | 18 helai                                       |",
          "|  3 | Warna daun         | Hijau tua                                      |",
          "|  4 | Bentuk daun        | Lonjong, ujung meruncing, tepi rata            |",
          "|  5 | Batang             | Tegak, beruas, warna hijau kecokelatan         |",
          "|  6 | Suhu lingkungan    | 30°C                                           |",
          "|  7 | Kelembapan tanah   | Lembap (70%)                                   |",
          "|  8 | Hama               | Tidak ditemukan                                |",
          "",
          "Dari data di atas, susun LHO seperti ini:",
          "\"Tanaman cabai (Capsicum annuum) yang diamati memiliki tinggi 25 cm dengan jumlah daun 18 helai. Daun berbentuk lonjong, berujung meruncing, dan bertepi rata. Warna daun hijau tua. Batang tanaman tegak dan beruas dengan warna hijau kecokelatan. Berdasarkan pengukuran, suhu lingkungan di sekitar tanaman mencapai 30°C dengan kelembapan tanah 70%. Pada saat pengamatan tidak ditemukan hama yang menyerang tanaman.\"",
        ],
        catatan: "Semakin detail data yang kamu kumpulkan, semakin kaya laporanmu. Jangan malas mencatat! Satu data kecil seperti 'lebar daun 2,5 cm' bisa menjadi informasi penting dalam laporan. Ingat: observasi yang baik = laporan yang baik.",
      },
      {
        judul: "Perbedaan LHO dengan Teks Deskripsi",
        isi: [
          "Banyak siswa yang keliru membedakan teks LHO dengan teks deskripsi. Padahal, keduanya sangat berbeda! Yuk, kita bedah bersama.",
          "",
          "• SIFAT:",
          "  • LHO → OBJEKTIF (apa adanya, berdasarkan fakta dan data)",
          "  • Deskripsi → SUBJEKTIF (berdasarkan kesan, opini, dan perasaan penulis)",
          "",
          "• TUJUAN:",
          "  • LHO → Menyajikan informasi faktual agar pembaca memahami objek secara ilmiah",
          "  • Deskripsi → Menciptakan kesan tertentu agar pembaca seolah melihat/merasakan objek",
          "",
          "• PENGGUNAAN BAHASA:",
          "  • LHO → Kalimat definisi (adalah, merupakan), istilah teknis, kata kerja pasif",
          "  • Deskripsi → Kata sifat (indah, cantik, megah), majas personifikasi, kata seru",
          "",
          "• DATA:",
          "  • LHO → Disertai data konkret: ukuran, jumlah, suhu, berat, dll.",
          "  • Deskripsi → Tidak harus ada data; yang penting kesan dan gambaran hidup",
          "",
          "• CONTOH TEMA SAMA (Pantai):",
          "BENAR: LHO tentang Pantai Parangtritis",
          "\"Pantai Parangtritis terletak di Kecamatan Kretek, Kabupaten Bantul, Daerah Istimewa Yogyakarta. Luas kawasan pantai mencapai ±25 hektare dengan panjang garis pantai sekitar 3 kilometer. Ombak di pantai ini memiliki tinggi rata-rata 1—3 meter. Jenis pasir di pantai ini adalah pasir vulkanik berwarna abu-abu kecokelatan.\"",
          "",
          "BENAR: Teks deskripsi tentang Pantai Parangtritis",
          "\"Pantai Parangtritis menyajikan panorama yang memukau. Pasir abu-abunya membentang luas bagaikan hamparan sutra. Ombak bergulung-gulung seolah menyapa para pengunjung. Di ufuk barat, mentari perlahan tenggelam mewarnai langit dengan jingga keemasan yang sungguh memesona.\"",
          "",
          "Tips mudah: Jika ada kata 'adalah', 'terdiri atas', 'berdasarkan pengamatan' → itu LHO. Jika ada kata 'indah', 'seperti', 'seolah-olah' → itu teks deskripsi!",
        ],
        contoh: [
          "BENAR LHO (adat Jawa): \"Upacara adat Grebeg Maulud di Keraton Yogyakarta telah berlangsung sejak abad ke-16. Upacara ini diikuti oleh 4.000—5.000 peserta yang terdiri atas abdi dalem dan masyarakat umum. Gunungan setinggi 2 meter berisi hasil bumi dengan berat sekitar 500 kg diarak dari Keraton menuju Masjid Gedhe.\"",
          "BENAR Deskripsi: \"Suasana Grebeg Maulud sungguh meriah. Ribuan orang berjejal memadati alun-alun. Gunungan raksasa berkilau indah dengan warna-warni hasil bumi yang menyolok. Suara gamelan mengiringi langkah para peserta — sungguh pemandangan yang tak terlupakan!\"",
        ],
        catatan: "Latihan mudah: Ambil satu objek. Coba tulis 2 paragraf — satu LHO (objektif, data) dan satu deskripsi (subjektif, kesan). Bandingkan! Ini akan melatih instingmu membedakan keduanya secara otomatis.",
      },
    ],
    rangkuman: [
      "Teks LHO adalah teks yang melaporkan hasil pengamatan secara sistematis, objektif, dan faktual.",
      "Ciri utama LHO: objektif, faktual, menggunakan istilah ilmiah, kalimat definisi, dan kata kerja pasif.",
      "Struktur LHO: pernyataan umum (klasifikasi) → deskripsi bagian (aspek yang diamati) → simpulan (opsional).",
      "Kaidah kebahasaan: kalimat definisi (adalah, merupakan), kalimat klasifikasi (terbagi menjadi, terdiri atas), kata kerja pasif (diamati, dilakukan), istilah teknis.",
      "Langkah observasi: tentukan objek → siapkan instrumen → lakukan pengamatan → catat data → susun laporan.",
      "Perbedaan utama LHO vs teks deskripsi: LHO objektif (fakta/data), deskripsi subjektif (kesan/opini).",
      "LHO menggunakan data kuantitatif (ukuran, jumlah, suhu) dan data kualitatif (warna, bentuk, tekstur).",
      "Contoh topik LHO: ekosistem kolam sekolah, tanaman di halaman rumah, kebiasaan hewan peliharaan, fasilitas perpustakaan, kantin sekolah.",
    ],
  },

  latihan: makeSoal([
    // 5 Soal Pilihan Ganda
    ["Teks laporan hasil observasi bertujuan untuk...", ["Menceritakan kisah fiktif", "Menyajikan informasi faktual hasil pengamatan", "Menggambarkan objek dengan kesan subjektif", "Mengajak pembaca melakukan sesuatu"], 1, "Tujuan LHO adalah menyajikan informasi faktual berdasarkan hasil pengamatan secara sistematis dan objektif."],
    ["Berikut ini yang merupakan ciri teks LHO adalah...", ["Bersifat subjektif", "Menggunakan majas personifikasi", "Berdasarkan fakta dan data", "Bertujuan menghibur pembaca"], 2, "LHO bersifat objektif dan faktual. Subjektif dan personifikasi adalah ciri teks deskripsi, bukan LHO."],
    ["Struktur teks LHO yang benar adalah...", ["Identifikasi — deskripsi bagian — simpulan", "Pernyataan umum — deskripsi bagian — simpulan (opsional)", "Pembukaan — isi — penutup", "Orientasi — komplikasi — resolusi"], 1, "Struktur LHO: pernyataan umum (klasifikasi) → deskripsi bagian (aspek yang diamati) → simpulan (opsional)."],
    ["Kalimat 'Termometer digital digunakan untuk mengukur suhu ruangan' menggunakan pola...", ["Kalimat aktif", "Kalimat definisi", "Kalimat pasif", "Kalimat klasifikasi"], 2, "Kata 'digunakan' adalah bentuk pasif (di- + gunakan). LHO sering menggunakan kalimat pasif untuk menjaga objektivitas."],
    ["Perbedaan utama teks LHO dengan teks deskripsi adalah...", ["LHO lebih panjang dari deskripsi", "LHO objektif, deskripsi subjektif", "LHO untuk guru, deskripsi untuk teman", "LHO pakai gambar, deskripsi tidak"], 1, "LHO bersifat objektif (berdasarkan fakta/data), sedangkan teks deskripsi bersifat subjektif (berdasarkan kesan/opini)."],

    // 3 Soal Betul/Salah
    ["Pernyataan: 'Teks LHO boleh mengandung opini penulis selama opini itu didukung data.'", ["Betul", "Salah"], 1, "SALAH. Teks LHO tidak boleh mengandung opini sama sekali. LHO bersifat objektif — apa adanya berdasarkan data yang diperoleh."],
    ["Pernyataan: 'Kata adalah, merupakan, dan yaitu termasuk kata yang sering muncul dalam kalimat definisi di teks LHO.'", ["Betul", "Salah"], 0, "BETUL. Kalimat definisi menggunakan kata adalah, merupakan, yaitu untuk menjelaskan pengertian suatu istilah atau objek."],
    ["Pernyataan: 'Langkah pertama dalam melakukan observasi adalah menyusun laporan.'", ["Betul", "Salah"], 1, "SALAH. Langkah pertama adalah menentukan objek observasi. Menyusun laporan adalah langkah TERAKHIR setelah data terkumpul."],

    // 2 Soal Isian Singkat
    ["Kata yang tepat untuk melengkapi kalimat definisi: 'Observasi ... kegiatan mengamati objek secara langsung.'", ["adalah", "dan", "atau", "tetapi"], 0, "'Adalah' adalah kata yang tepat untuk kalimat definisi. Contoh: 'Observasi adalah kegiatan mengamati objek secara langsung.'"],
    ["LHO menyajikan data dalam bentuk kuantitatif dan ...", ["kualitatif", "naratif", "imajinatif", "deskriptif"], 0, "Data LHO terdiri atas data kuantitatif (angka/ukuran) dan data kualitatif (warna, bentuk, tekstur)."],
  ]),

  praktik: {
    petunjuk: "Lakukan observasi sederhana terhadap KANTIN SEKOLAHMU atau salah satu ruangan di sekolah, lalu tulis teks LHO sepanjang 7—10 kalimat. Ikuti langkah-langkah berikut:\n\n1. Tentukan objek observasi: pilih kantin sekolah, perpustakaan, laboratorium, atau ruang kelas.\n2. Siapkan alat tulis dan ukur (penggaris/meteran jika perlu).\n3. Lakukan pengamatan terhadap aspek-aspek berikut:\n   - Ukuran ruangan (panjang × lebar, perkiraan luas)\n   - Fasilitas yang tersedia (meja, kursi, lemari, papan tulis, dll.) beserta jumlahnya\n   - Kondisi fisik (warna dinding, jenis lantai, pencahayaan, ventilasi)\n   - Aktivitas yang berlangsung di tempat itu\n   - Data lain yang relevan (suhu, kebersihan, jumlah pengunjung)\n4. Catat data dengan jujur dan objektif. Jangan tambahkan opini!\n5. Susun laporan dengan struktur: pernyataan umum → deskripsi bagian → simpulan (opsional).\n6. Gunakan minimal 2 kalimat definisi, 1 kalimat klasifikasi, dan 3 istilah teknis.\n\nTulis teks LHO-mu di kolom di bawah ini!",
    tips: [
      "Mulai dengan pernyataan umum: 'Kantin SMP Nusantara adalah salah satu fasilitas sekolah yang terletak di sisi timur gedung...'",
      "Gunakan data konkret: 'terdapat 15 meja dan 60 kursi', 'luas ruangan 10 × 8 meter', 'ventilasi berjumlah 4 jendela'",
      "Gunakan kata kerja pasif: 'diamati', 'diukur', 'ditemukan', 'dilakukan', 'disajikan'",
      "Hindari kata subjektif: jangan tulis 'bersih, rapi, nyaman, enak'. Tulis fakta: 'lantai keramik berwarna putih, tidak ditemukan sampah di lantai'",
      "Gunakan istilah teknis sesuai objek: 'ventilasi, sirkulasi udara, intensitas cahaya, frekuensi pengunjung, kapasitas'",
      "Akhiri dengan simpulan singkat yang merangkum temuan utama secara objektif.",
    ],
    contoh: "Kantin SMP Nusantara adalah salah satu fasilitas sekolah yang terletak di sisi timur gedung utama. Kantin ini memiliki luas 12 × 8 meter dengan kapasitas tampung sekitar 80 orang. Berdasarkan pengamatan yang dilakukan pada hari Senin, 15 Januari 2024, pukul 09.00—10.00 WIB, diperoleh data sebagai berikut. Kantin dilengkapi dengan 15 meja dan 60 kursi yang tersusun dalam 5 baris. Lantai kantin terbuat dari keramik putih berukuran 40 × 40 cm yang permukaannya bersih. Ventilasi udara berjumlah 4 jendela dengan ukuran 1 × 1,5 meter yang terletak di sisi timur dan barat, sehingga sirkulasi udara berlangsung lancar. Pencahayaan berasal dari 6 lampu neon 40 watt yang memberikan intensitas cahaya merata di seluruh ruangan. Terdapat 3 stan makanan yang menjual berbagai jenis makanan dan minuman. Pengunjung yang tercatat selama satu jam pengamatan berjumlah 45 siswa. Berdasarkan data yang diperoleh, dapat disimpulkan bahwa kantin SMP Nusantara memiliki fasilitas yang memadai dengan kapasitas yang cukup untuk melayani siswa saat jam istirahat.",
  },

  kuis: makeSoal([
    ["Teks LHO bersifat objektif, artinya...", ["Berdasarkan opini penulis", "Berdasarkan fakta dan data yang dapat dibuktikan", "Berdasarkan imajinasi penulis", "Berdasarkan cerita orang lain"], 1, "Objektif berarti apa adanya, faktual, dan tidak dipengaruhi opini pribadi. Data yang disajikan dapat diverifikasi kebenarannya."],
    ["Istilah observasi berasal dari bahasa Latin observatio yang berarti...", ["Pengamatan", "Penelitian", "Pencatatan", "Pelaporan"], 0, "Observatio = pengamatan/pemerhatian. Dari sinilah kata observasi dalam bahasa Indonesia berasal."],
    ["Bagian struktur LHO yang berisi definisi atau pengelompokan objek disebut...", ["Deskripsi bagian", "Simpulan", "Pernyataan umum", "Penutup"], 2, "Pernyataan umum berisi definisi/klasifikasi umum objek. Contoh: 'Tanaman cabai adalah tanaman dari keluarga Solanaceae.'"],
    ["Kalimat 'Berdasarkan wujudnya, sampah terbagi menjadi tiga jenis: padat, cair, dan gas' termasuk kalimat...", ["Definisi", "Klasifikasi", "Pasif", "Aktif"], 1, "Kalimat klasifikasi mengelompokkan sesuatu berdasarkan kategori. Kata 'terbagi menjadi' dan 'jenis' menandakan kalimat klasifikasi."],
    ["Mana dari berikut ini yang BUKAN termasuk kata kerja pasif?", ["diamati", "mengukur", "dilakukan", "ditemukan"], 1, "'Mengukur' adalah kata kerja aktif (me- + ukur). Yang pasif: diukur, diamati, dilakukan, ditemukan, disusun."],
    ["Jika kamu menulis LHO tentang ekosistem kolam, aspek berikut yang WAJIB dilaporkan adalah...", ["Kolamnya indah dan airnya jernih", "Suhu air 28°C, pH 7, terdapat 12 jenis ikan", "Suasana kolam tenang dan menenangkan", "Kolam itu tempat favoritku untuk bersantai"], 1, "Data suhu, pH, dan jumlah jenis ikan adalah data faktual yang objektif. Pilihan lain berisi opini subjektif."],
    ["Langkah yang benar dalam melakukan observasi adalah...", ["Menyusun laporan — mengamati — mencatat data", "Menentukan objek — menyiapkan instrumen — mengamati — mencatat data — menyusun laporan", "Mencatat data — mengamati — menyusun laporan", "Menyiapkan instrumen — menentukan objek — mengamati — menyusun laporan"], 1, "Urutan yang benar: tentukan objek → siapkan instrumen → lakukan pengamatan → catat data → susun laporan."],
    ["Kata 'adalah' dan 'merupakan' dalam teks LHO berfungsi untuk...", ["Menghubungkan dua kalimat", "Menandai kalimat definisi", "Menunjukkan waktu", "Menyatakan sebab-akibat"], 1, "'Adalah' dan 'merupakan' adalah kata yang menandai kalimat definisi. Contoh: 'Observasi adalah kegiatan mengamati.'"],
    ["Berikut ini yang paling tepat sebagai pernyataan umum dalam LHO tentang tanaman lidah buaya...", ["Lidah buaya memiliki daun yang tebal dan berdaging", "Lidah buaya (Aloe vera) adalah tanaman sukulen dari keluarga Asphodelaceae", "Daun lidah buaya mengandung gel yang bermanfaat", "Lidah buaya berasal dari Jazirah Arab"], 1, "Pernyataan umum berisi definisi/klasifikasi umum. Pilihan B adalah yang paling tepat karena memberikan definisi ilmiah lengkap."],
    ["Penggunaan istilah teknis dalam LHO bertujuan untuk...", ["Membuat laporan terlihat rumit", "Menunjukkan ketepatan dan keilmiahan informasi", "Mempersulit pembaca", "Menghias laporan"], 1, "Istilah teknis digunakan agar informasi yang disampaikan tepat, akurat, dan sesuai dengan bidang keilmuan objek yang diamati. Ini penting untuk menjaga objektivitas dan ketepatan laporan."],
  ]),
}

export default konten
