import type { Konten } from "../types"
import { makeSoal } from "../types"

const konten: Konten = {
  belajar: {
    tujuan: [
      "Memahami pengertian puisi rakyat sebagai warisan sastra tradisional Nusantara",
      "Mengenal tiga jenis puisi rakyat: pantun, syair, dan gurindam beserta ciri khasnya",
      "Menganalisis perbedaan struktur, sajak, dan isi dari pantun, syair, dan gurindam",
      "Mengapresiasi nilai-nilai moral dan kearifan lokal dalam puisi rakyat",
    ],
    materi: [
      {
        judul: "Apa Itu Puisi Rakyat?",
        isi: [
          "Puisi rakyat adalah karya sastra tradisional yang lahir, tumbuh, dan berkembang di tengah masyarakat secara turun-temurun. Disebut 'rakyat' karena pengarangnya anonim (tidak dikenal) dan penyebarannya melalui lisan dari mulut ke mulut.",
          "",
          "Coba bayangkan nenek moyang kita dulu — belum ada buku, belum ada internet. Mereka menyampaikan nasihat, teguran, dan hiburan melalui kata-kata berirama yang indah. Itulah puisi rakyat!",
          "",
          "• Ciri-ciri umum puisi rakyat:",
          "  • Berbentuk bait dan larik (baris) dengan pola tertentu",
          "  • Bersajak (rima) yang khas dan teratur",
          "  • Menggunakan bahasa klasik yang puitis dan padat",
          "  • Berisi pesan moral, nasihat, atau nilai-nilai kehidupan",
          "  • Disampaikan secara lisan (tradisi lisan)",
          "  • Pengarang tidak dikenal (anonim)",
          "",
          "• Fungsi puisi rakyat dalam masyarakat:",
          "  • Mendidik — menanamkan nilai budi pekerti dan agama",
          "  • Menghibur — sebagai hiburan dalam acara adat dan perayaan",
          "  • Menyampaikan nasihat secara halus dan tidak menggurui",
          "  • Mengkritik atau menyindir secara santun",
          "  • Mempererat kebersamaan dalam acara gotong royong dan pesta rakyat",
          "",
          "PENTING: Puisi rakyat berbeda dengan puisi modern. Puisi rakyat terikat oleh aturan jumlah baris, sajak, dan suku kata yang ketat. Puisi modern bebas dan tidak terikat aturan.",
          "",
          "Jenis puisi rakyat yang akan kita pelajari ada tiga: PANTUN, SYAIR, dan GURINDAM. Masing-masing punya ciri unik. Yuk, kenali satu per satu!",
        ],
        contoh: [
          "Contoh puisi rakyat dalam kehidupan sehari-hari:",
          "Saat anak-anak bermain, mereka sering melantunkan pantun secara spontan.",
          "Dalam acara pernikahan adat Melayu, pantun digunakan sebagai alat komunikasi antara pihak mempelai.",
          "Di masyarakat Minangkabau, gurindam digunakan dalam pidato adat untuk menyampaikan nasihat.",
        ],
        catatan: "Istilah 'puisi rakyat' juga disebut 'puisi lama' karena merupakan bentuk puisi tertua dalam khasanah sastra Indonesia. Namun, 'rakyat' lebih tepat karena menekankan kepemilikan kolektif masyarakat.",
      },
      {
        judul: "Pantun — Si Jenaka Penuh Makna",
        isi: [
          "Pantun adalah jenis puisi rakyat yang paling populer di Nusantara. Hampir setiap daerah di Indonesia memiliki tradisi berpantun dengan nama yang berbeda-beda: di Jawa disebut parikan, di Sunda disebut paparikan, di Batak disebut umpasa.",
          "",
          "Ciri-ciri pantun:",
          "",
          "1. Setiap bait terdiri dari EMPAT BARIS (larik)",
          "2. Bersajak a-b-a-b (baris 1 dan 3 sama bunyi akhir, baris 2 dan 4 sama bunyi akhir)",
          "3. Baris 1-2 adalah SAMPIRAN — berupa pengantar yang biasanya berkaitan dengan alam atau benda sehari-hari. Sampiran tidak mengandung pesan langsung.",
          "4. Baris 3-4 adalah ISI — inti pesan yang ingin disampaikan. Ini adalah 'daging' pantun.",
          "5. Setiap baris terdiri dari 8—12 suku kata",
          "",
          "  ✓ Contoh sajak a-b-a-b:",
          "  Kalau ada jarum yang patah (a)",
          "  Jangan simpan di dalam peti (b)",
          "  Kalau ada kata yang salah (a)",
          "  Jangan simpan di dalam hati (b)",
          "",
          "PENTING: Sampiran dan isi dalam pantun TIDAK berhubungan secara logis. Sampiran hanya berfungsi sebagai pengantar irama dan sajak. Namun, kadang sampiran bisa mengandung kiasan yang tersirat terkait isi.",
          "",
          "Jenis-jenis pantun berdasarkan isi:",
          "• Pantun Nasihat — berisi petuah dan ajaran budi pekerti",
          "• Pantun Jenaka — bertujuan menghibur dengan humor ringan",
          "• Pantun Teka-Teki — berisi tebakan untuk mengundang jawaban",
          "• Pantun Percintaan — mengungkapkan perasaan cinta dan kasih sayang",
          "• Pantun Adat — digunakan dalam upacara adat dan tradisi",
          "• Pantun Agama — berisi pesan keagamaan dan spiritual",
        ],
        contoh: [
          "Contoh Pantun Nasihat:",
          "\"Buah manggis di tepi rawa,\"",
          "Si burung elang terbang melayang.",
          "Jikalau ingin hidup mulia,",
          "Rajin-rajinlah belajar sepanjang hayat.\"",
          "",
          "Contoh Pantun Jenaka:",
          "\"Anak kambing mencari induk,",
          "Lari ke hutan mengejar rusa.",
          "Geli hati menahan tawa,",
          "Melihat kucing memakai kupluk biru.\"",
          "",
          "Contoh Pantun Teka-Teki:",
          "\"Batu hitam di tengah sawah,",
          "Digulung ombak dari tepian.",
          "Badan ramping tidak bertulang,",
          "Bersaudara sejak lahir ke dunia.\"",
          "(Jawaban: sepak bola dan gawang)",
          "",
          "Contoh Pantun Percintaan:",
          "\"Pisang emas dibawa berlayar,",
          "Masak sebiji di atas peti.",
          "Hutang emas boleh dibayar,",
          "Hutang budi dibawa sampai mati.\"",
        ],
        catatan: "Tips membuat pantun: buat dulu baris isi (3-4) yang berisi pesanmu, lalu buat sampiran (1-2) yang rimanya cocok. Ingat a-b-a-b! Sampiran bisa dari pengamatan alam sekitarmu.",
      },
      {
        judul: "Syair — Bait Bersajak Penuh Kisah",
        isi: [
          "Syair adalah puisi rakyat yang berasal dari khazanah sastra Arab-Melayu. Kata 'syair' berasal dari bahasa Arab 'syi'r' yang berarti 'puisi'. Syair masuk ke Nusantara bersamaan dengan penyebaran agama Islam dan berkembang pesat di masyarakat Melayu.",
          "",
          "Ciri-ciri syair:",
          "",
          "1. Setiap bait terdiri dari EMPAT BARIS",
          "2. Bersajak a-a-a-a (semua baris memiliki bunyi akhir yang SAMA)",
          "3. SEMUA baris adalah ISI — tidak ada sampiran! Berbeda dengan pantun yang punya sampiran, syair langsung menyampaikan isi dari baris pertama.",
          "4. Setiap baris terdiri dari 8—14 suku kata",
          "5. Biasanya berisi cerita, nasihat, ajaran agama, atau kisah kepahlawanan",
          "6. Satu syair bisa terdiri dari puluhan bahkan ratusan bait (seperti cerita bersambung)",
          "",
          "  ✓ Contoh sajak a-a-a-a:",
          "  Wahai muda kenali dirimu (a)",
          "  Ialah perahu tamsil hidupmu (a)",
          "  Tiada berapa lama hidupmu (a)",
          "  Ke akhirat jua kekal hidupmu (a)",
          "",
          "PENTING: Karena semua baris adalah isi, syair sering digunakan untuk menyampaikan cerita panjang (syair naratif) seperti Syair Ken Tambuhan, Syair Bidasari, atau kisah perjuangan para pahlawan. Syair juga sering berisi ajaran tasawuf (spiritual Islam).",
          "",
          "Tokoh terkenal: Hamzah Fansuri (sastrawan abad ke-16 dari Aceh) — beliau adalah pelopor syair Melayu klasik. Karyanya yang terkenal: Syair Perahu, Syair Dagang, dan Syair Burung Pingai.",
        ],
        contoh: [
          "Syair Perahu — Hamzah Fansuri (kutipan):",
          "\"Wahai muda kenali dirimu,",
          "Ialah perahu tamsil hidupmu,",
          "Tiada berapa lama hidupmu,",
          "Ke akhirat jua kekal hidupmu.\"",
          "",
          "\"Hidup di dunia ibarat naik perahu,",
          "carilah bekalan jangan berlabuh,",
          "sedikit-dikit berlayar selalu,",
          "sampailah ke pantai Allah yang Maha Esa.\"",
          "",
          "Contoh syair nasihat:",
          "\"Wahai ananda intan kandung,",
          "Janganlah suka berbuat bingung,",
          "Tuntutlah ilmu siang dan malam,",
          "Agar hidupmu tidak tenggelam.\"",
          "",
          "BENAR (ciri syair): \"Rajin-rajinlah engkau belajar / Jangan putus di tengah jalan / Ilmu itu bekal yang berharga / Dunia akhirat kan selama.\" (a-a-a-a, semua baris isi)",
          "SALAH (ini pantun, bukan syair): \"Buah manggis di tepi rawa / Si burung elang terbang melayang / Jikalau ingin hidup mulia / Rajin-rajinlah belajar sepanjang hayat.\" (sajak a-b-a-b, baris 1-2 sampiran)",
        ],
        catatan: "Cara mudah membedakan pantun dan syair: pantun baris 1-2 tidak nyambung ke isi (sampiran), syair semua baris nyambung dan bersajak sama. Ingat: PANTUN = a-b-a-b (dua suara), SYAIR = a-a-a-a (satu suara).",
      },
      {
        judul: "Gurindam — Dua Baris Penuh Makna",
        isi: [
          "Gurindam adalah puisi rakyat yang paling pendek — hanya dua baris dalam setiap bait! Namun di balik kepadatannya, gurindam menyimpan nasihat yang dalam. Gurindam berasal dari sastra Tamil (India Selatan) yang masuk ke Melayu melalui pengaruh Hindu, lalu diadopsi oleh sastrawan Islam.",
          "",
          "Ciri-ciri gurindam:",
          "",
          "1. Setiap bait terdiri dari DUA BARIS (larik) saja",
          "2. Bersajak a-a (baris 1 dan 2 berima sama)",
          "3. Baris 1: SEBAB atau syarat (kondisi)",
          "4. Baris 2: AKIBAT atau hasil (nasihat)",
          "5. Bersifat nasihat, ajaran agama, atau petuah moral",
          "6. Bahasa padat, ringkas, dan lugas",
          "",
          "  ✓ Contoh sajak a-a dengan hubungan sebab-akibat:",
          "  Barang siapa meninggalkan salat (sebab)",
          "  Hidupnya gelap penuh khilafat (akibat)",
          "",
          "  Kurang pikir kurang siasat (sebab)",
          "  Tentu dirimu akan tersesat (akibat)",
          "",
          "Karya gurindam paling terkenal: GURINDAM DUA BELAS oleh Raja Ali Haji (1808—1873), seorang pujangga dan sejarawan dari Kesultanan Riau-Lingga. Gurindam Dua Belas terdiri dari 12 pasal yang berisi nasihat tentang agama, moral, dan budi pekerti. Karya ini diakui UNESCO sebagai Warisan Budaya Dunia.",
          "",
          "PENTING: Tidak semua bait dua baris bersajak a-a adalah gurindam. Gurindam harus memiliki hubungan SEBAB-AKIBAT antara baris 1 dan 2. Jika tidak ada hubungan sebab-akibat, itu bukan gurindam!",
        ],
        contoh: [
          "Gurindam Dua Belas — Raja Ali Haji (Pasal 1):",
          "\"Barang siapa tiada memegang agama,",
          "Sekali-kali tiada boleh dibilangkan nama.\"",
          "",
          "Pasal 3 (tentang akal dan budi):",
          "\"Apabila terpelihara mata,",
          "Sedikitlah cita-cita.\"",
          "",
          "\"Apabila terpelihara kuping,",
          "Kabar yang jahat tiada damping.\"",
          "",
          "Pasal 5 (tentang pergaulan):",
          "\"Jika hendak mengenal orang berbangsa,",
          "Lihat kepada budi dan bahasa.\"",
          "",
          "\"Jika hendak mengenal orang yang berilmu,",
          "Bertanya dan belajar tiadalah jemu.\"",
          "",
          "BENAR (gurindam dengan sebab-akibat): \"Jika engkau rajin membaca / Ilmu pengetahuan akan bertambah.\" (baris 1 = sebab, baris 2 = akibat)",
          "SALAH (ini bukan gurindam): \"Bunga mawar di taman indah / Hatiku rindu tak terbilang.\" (tidak ada hubungan sebab-akibat)",
        ],
        catatan: "Raja Ali Haji adalah pahlawan nasional Indonesia. Selain Gurindam Dua Belas, beliau juga menulis buku tata bahasa Melayu pertama berjudul 'Bustanul Katibin' dan kamus 'Kitab Pengetahuan Bahasa'.",
      },
      {
        judul: "Perbandingan Pantun, Syair, dan Gurindam",
        isi: [
          "Mari kita bandingkan ketiga jenis puisi rakyat ini agar lebih mudah diingat:",
          "",
          "• JUMLAH BARIS PER BAIT:",
          "  Pantun → 4 baris",
          "  Syair → 4 baris",
          "  Gurindam → 2 baris",
          "",
          "• POLA SAJAK (RIMA):",
          "  Pantun → a-b-a-b",
          "  Syair → a-a-a-a",
          "  Gurindam → a-a",
          "",
          "• STRUKTUR ISI:",
          "  Pantun → baris 1-2 sampiran, baris 3-4 isi",
          "  Syair → semua baris adalah isi (tidak ada sampiran)",
          "  Gurindam → baris 1 sebab/syarat, baris 2 akibat/hasil",
          "",
          "• JUMLAH SUKU KATA:",
          "  Pantun → 8—12 suku kata per baris",
          "  Syair → 8—14 suku kata per baris",
          "  Gurindam → 10—14 suku kata per baris",
          "",
          "• ISI PESAN:",
          "  Pantun → nasihat, jenaka, teka-teki, percintaan, beragam",
          "  Syair → cerita, nasihat, ajaran agama, kisah kepahlawanan",
          "  Gurindam → nasihat moral dan agama yang padat",
          "",
          "Tips menghafal:",
          "  • PANTUN: 4 baris, a-b-a-b, ada sampiran-isi. Bayangkan 'pantun' dan 'pasangan' (sampiran + isi, sajak berpasangan a-b-a-b).",
          "  • SYAIR: 4 baris, a-a-a-a, semua isi. Bayangkan 'syair' dan 'sama' (semua baris sajaknya sama, semua baris isi).",
          "  • GURINDAM: 2 baris, a-a, sebab-akibat. Bayangkan 'gurindam' dan 'ganda' (dua baris, hubungan ganda/sebab-akibat).",
          "",
          "PENTING: Ketiganya sama-sama puisi rakyat, sama-sama terikat aturan, dan sama-sama sarat pesan moral. Perbedaan utama ada pada struktur dan sajaknya. Hafalkan pola inci!",
        ],
        contoh: [
          "Perbandingan dalam satu tema (nasihat tentang ilmu):",
          "",
          "PANTUN:",
          "\"Ke hutan mencari kayu cendana,",
          "Kayu dibelah menjadi peti.",
          "Rajin-rajinlah menuntut ilmu,",
          "Agar masa depan cerah berseri.\"",
          "",
          "SYAIR:",
          "\"Wahai ananda yang masih muda,",
          "Tuntutlah ilmu dengan gembira,",
          "Ilmu bagai pelita di malam hari,",
          "Menerangi langkah tak tersesat lagi.\"",
          "",
          "GURINDAM:",
          "\"Jika engkau rajin membaca,",
          "Ilmu pengetahuan kan bertambah.\"",
        ],
      },
    ],
    rangkuman: [
      "Puisi rakyat adalah sastra tradisional yang lahir di masyarakat, bersifat anonim, dan disampaikan secara lisan.",
      "Pantun: 4 baris, sajak a-b-a-b, baris 1-2 sampiran, baris 3-4 isi, 8-12 suku kata. Jenisnya: nasihat, jenaka, teka-teki, percintaan, adat, agama.",
      "Syair: 4 baris, sajak a-a-a-a, semua baris adalah isi (tanpa sampiran), 8-14 suku kata. Berasal dari Arab-Melayu, sering berisi cerita dan nasihat agama.",
      "Gurindam: 2 baris, sajak a-a, baris 1 sebab/syarat dan baris 2 akibat/hasil. Bersifat nasihat moral dan agama yang sangat padat.",
      "Hamzah Fansuri adalah pelopor syair Melayu klasik (Syair Perahu). Raja Ali Haji menulis Gurindam Dua Belas yang diakui UNESCO.",
      "Perbedaan utama: jumlah baris, pola sajak, struktur isi (sampiran vs semua isi vs sebab-akibat), dan jumlah suku kata.",
      "Fungsi puisi rakyat: mendidik, menghibur, menyampaikan nasihat secara halus, mengkritik dengan santun, dan mempererat kebersamaan.",
    ],
  },

  latihan: makeSoal([
    // 5 Soal Pilihan Ganda (4 opsi)
    ["Pantun memiliki pola sajak...", ["a-a-a-a", "a-b-a-b", "a-b-b-a", "a-a-b-b"], 1, "Pantun bersajak a-b-a-b. Baris 1 dan 3 sama bunyi akhir, baris 2 dan 4 sama bunyi akhir."],
    ["Bagian pantun yang berisi pesan atau isi terdapat pada baris ke...", ["1 dan 2", "2 dan 3", "3 dan 4", "1 dan 4"], 2, "Baris 3-4 adalah ISI. Baris 1-2 adalah sampiran (pengantar)."],
    ["Syair berasal dari khazanah sastra...", ["Jawa", "Arab-Melayu", "Tamil", "Sunda"], 1, "Syair berasal dari bahasa Arab 'syi'r' dan masuk ke Nusantara melalui pengaruh Islam dan sastra Arab-Melayu."],
    ["Gurindam Dua Belas adalah karya terkenal dari...", ["Hamzah Fansuri", "Raja Ali Haji", "Chairil Anwar", "W.S. Rendra"], 1, "Gurindam Dua Belas ditulis oleh Raja Ali Haji, pujangga dari Kesultanan Riau-Lingga."],
    ["Ciri khas gurindam yang membedakannya dari pantun dan syair adalah...", ["Memiliki sampiran", "Terdiri dari 4 baris", "Baris 1 sebab, baris 2 akibat", "Bersajak a-b-a-b"], 2, "Gurindam hanya 2 baris dengan hubungan SEBAB-AKIBAT: baris 1 = syarat, baris 2 = akibat."],

    // 3 Soal Betul/Salah (2 opsi)
    ["Pernyataan: 'Pantun dan syair sama-sama terdiri dari 4 baris dalam setiap bait.'", ["Betul", "Salah"], 0, "BETUL. Baik pantun maupun syair sama-sama memiliki 4 baris dalam setiap bait."],
    ["Pernyataan: 'Dalam syair, baris 1 dan 2 adalah sampiran, sedangkan baris 3 dan 4 adalah isi.'", ["Betul", "Salah"], 1, "SALAH. Dalam syair, SEMUA baris adalah isi. Tidak ada sampiran. Ciri ini yang membedakan syair dari pantun."],
    ["Pernyataan: 'Gurindam hanya boleh berisi tema agama, tidak boleh tema lain.'", ["Betul", "Salah"], 1, "SALAH. Gurindam biasanya berisi nasihat agama dan moral, tetapibisa juga berisi nasihat tentang budi pekerti, pendidikan, dan kehidupan sehari-hari."],

    // 2 Soal Isian Singkat (4 opsi)
    ["Puisi rakyat yang setiap baitnya hanya terdiri dari 2 baris dengan sajak a-a disebut...", ["Pantun", "Syair", "Gurindam", "Seloka"], 2, "Gurindam adalah puisi rakyat yang hanya terdiri dari 2 baris per bait, bersajak a-a, dengan hubungan sebab-akibat."],
    ["Tokoh sastra yang menulis Syair Perahu adalah...", ["Raja Ali Haji", "Hamzah Fansuri", "Amir Hamzah", "Sanusi Pane"], 1, "Hamzah Fansuri (abad ke-16 dari Aceh) adalah pelopor syair Melayu klasik, termasuk Syair Perahu yang sangat terkenal."],
  ]),

  praktik: {
    petunjuk: "Buatlah sebuah PUISI RAKYAT berupa pantun atau gurindam dengan tema \"PENTINGNYA MENJAGA KEBERSIHAN LINGKUNGAN\"!\n\nKetentuan:\n\n=== JIKA MEMILIH PANTUN ===\n1. Buat 2 bait pantun (total 8 baris).\n2. Setiap bait terdiri dari 4 baris.\n3. Sajak a-b-a-b.\n4. Baris 1-2 = sampiran, baris 3-4 = isi (berisi ajakan menjaga kebersihan).\n5. Setiap baris 8—12 suku kata.\n\n=== JIKA MEMILIH GURINDAM ===\n1. Buat 4 bait gurindam (total 8 baris).\n2. Setiap bait terdiri dari 2 baris.\n3. Sajak a-a.\n4. Baris 1 = sebab/syarat, baris 2 = akibat/hasil (tentang kebersihan).\n\n=== KETENTUAN UMUM ===\n1. Gunakan bahasa Indonesia yang baik dan benar.\n2. Pesan harus jelas: ajakan menjaga kebersihan lingkungan (membuang sampah, menanam pohon, membersihkan selokan, dll).\n3. Tulis puisi rakyatmu di kolom jawaban.\n4. Setelah selesai, tuliskan penjelasan singkat: jenis apa yang kamu pilih dan bagaimana pola sajaknya.",
    tips: [
      "Untuk pantun: tulis dulu baris isi (3-4) yang berisi pesan kebersihan, lalu buat sampiran (1-2) yang rimanya cocok dengan isi.",
      "Periksa sajak: baris 1 dan 3 harus sama bunyi akhir, baris 2 dan 4 juga sama bunyi akhir.",
      "Untuk gurindam: pastikan ada hubungan sebab-akibat. Contoh: 'Jika sampah dibuang sembarangan (sebab) / Banjir melanda perkampungan (akibat).'",
      "Hitung suku kata setiap baris. Pantun: 8—12 suku kata. Gurindam: 10—14 suku kata.",
      "Gunakan kata-kata yang puitis dan klasik agar terasa seperti puisi rakyat: 'wahai', 'jika', 'barang siapa', 'hendaklah'.",
      "Baca keras-keras hasil karyamu. Apakah bunyinya enak didengar? Apakah rimanya pas? Apakah pesannya sampai?",
    ],
    contoh: "=== CONTOH PANTUN (Tema Kebersihan) ===\n\nBait 1:\nBuah kelapa jatuh ke tanah,\nDiambil ibu pakai keranjang.\nMari kita jaga lingkungan indah,\nBuanglah sampah pada tempatnya yang tepat.\n\nBait 2:\nPergi ke pasar beli pepaya,\nJangan lupa membeli sukun.\nLingkungan bersih sehat semua,\nHidup terasa nyaman dan aman sentosa.\n\n=== CONTOH GURINDAM (Tema Kebersihan) ===\n\nBait 1:\nJika sampah dibuang di selokan,\nAir pun meluap jadi banjir bandang.\n\nBait 2:\nBarang siapa menjaga kebersihan,\nHidupnya senang penuh kesejukan.\n\nBait 3:\nApabila taman dirawat selalu,\nIndah dipandang menentramkan kalbu.\n\nBait 4:\nJika setiap hari menanam pohon,\nUdara segar mengalir perlahan.\n\nPenjelasan:\n- Saya memilih membuat gurindam.\n- Ciri gurindam: 2 baris per bait, sajak a-a, baris 1 sebab dan baris 2 akibat.\n- Tema: kebersihan lingkungan. Setiap bait berisi nasihat tentang dampak dari perilaku terhadap lingkungan.",
  },

  kuis: makeSoal([
    ["Puisi rakyat yang terdiri dari 4 baris dengan sajak a-b-a-b disebut...", ["Syair", "Gurindam", "Pantun", "Seloka"], 2, "Pantun: 4 baris, sajak a-b-a-b, baris 1-2 sampiran, baris 3-4 isi."],
    ["Baris 1 dan 2 dalam pantun disebut...", ["Isi", "Sampiran", "Amanat", "Tema"], 1, "Sampiran adalah baris 1-2 yang berfungsi sebagai pengantar. Tidak mengandung pesan langsung."],
    ["Syair 'Wahai muda kenali dirimu / Ialah perahu tamsil hidupmu' adalah karya...", ["Raja Ali Haji", "Hamzah Fansuri", "Chairil Anwar", "Muhammad Yamin"], 1, "Kutipan tersebut dari Syair Perahu karya Hamzah Fansuri, sastrawan Aceh abad ke-16."],
    ["Gurindam Dua Belas terdiri dari...", ["12 pasal", "12 bait", "12 baris", "12 bab"], 0, "Gurindam Dua Belas terdiri dari 12 PASAL yang masing-masing berisi beberapa bait gurindam."],
    ["Perbedaan utama pantun dan syair adalah...", ["Jumlah baris", "Pantun ada sampiran, syair semua isi", "Pantun 2 baris, syair 4 baris", "Pantun bersajak, syair tidak"], 1, "Pantun memiliki sampiran (baris 1-2). Syair semua baris adalah isi langsung."],
    ["Ciri khas gurindam adalah hubungan antara baris 1 dan 2 bersifat...", ["Sama-sama isi", "Sebab-akibat", "Sampiran dan isi", "Pertentangan"], 1, "Baris 1 = sebab/syarat, baris 2 = akibat/hasil. Inilah ciri paling khas gurindam."],
    ["Puisi rakyat yang paling cocok untuk menyampaikan cerita panjang adalah...", ["Pantun", "Syair", "Gurindam", "Karmina"], 1, "Syair bisa terdiri dari puluhan hingga ratusan bait, cocok untuk cerita panjang seperti Syair Ken Tambuhan."],
    ["Berikut yang BUKAN termasuk jenis pantun adalah...", ["Pantun nasihat", "Pantun jenaka", "Pantun sebab-akibat", "Pantun teka-teki"], 2, "'Sebab-akibat' bukan jenis pantun. Itu adalah ciri khas gurindam. Jenis pantun: nasihat, jenaka, teka-teki, percintaan."],
    ["Baris 'Jika sampah dibuang sembarangan' pada gurindam merupakan...", ["Sebab", "Akibat", "Sampiran", "Isi"], 0, "Baris 1 gurindam adalah SEBAB atau syarat. Baris 2 adalah akibatnya."],
    ["Kata 'syair' berasal dari bahasa Arab 'syi'r' yang berarti...", ["Nasihat", "Cerita", "Puisi", "Nyanyian"], 2, "'Syi'r' dalam bahasa Arab berarti 'puisi'. Kata ini kemudian diserap ke dalam bahasa Melayu menjadi 'syair'."],
  ]),
}

export default konten
