import type { Konten } from "../types"
import { makeSoal } from "../types"

const konten: Konten = {
  belajar: {
    tujuan: [
      "Memahami pengertian, ciri-ciri, dan jenis cerita pendek (cerpen)",
      "Mengidentifikasi dan menganalisis unsur intrinsik cerpen (tema, tokoh, alur, latar, sudut pandang, amanat, gaya bahasa)",
      "Menjelaskan unsur ekstrinsik dan pengaruhnya terhadap cerpen",
      "Membedakan cerpen dengan novel, dongeng, dan cerita rakyat",
      "Menulis cerpen sederhana dengan struktur yang lengkap dan menarik",
    ],
    materi: [
      {
        judul: "Mengenal Cerita Pendek",
        isi: [
          "Pernahkah kamu membaca sebuah cerita yang selesai dalam sekali duduk? Saat istirahat sekolah, kamu pinjam buku kumpulan cerita teman, dan dalam 15 menit cerita itu sudah habis kamu baca. Itulah cerpen — cerita pendek yang padat, fokus, dan menggugah!",
          "",
          "Cerita pendek atau cerpen adalah karangan fiktif yang berbentuk prosa naratif, relatif pendek, dan selesai dibaca dalam satu kali duduk (sekitar 30 menit hingga 2 jam). Cerpen hanya mengisahkan satu konflik utama dengan jumlah tokoh terbatas dan meninggalkan kesan tunggal bagi pembacanya.",
          "",
          "PENTING: Cerpen bukan sekadar cerita yang pendek. Sebuah cerpen harus memiliki struktur naratif yang lengkap — ada pengenalan, konflik, klimaks, dan penyelesaian — meskipun dalam ruang yang terbatas.",
          "",
          "• Ciri-ciri cerpen:",
          "  • Panjang 1.000–10.000 kata (rata-rata 3.000–5.000 kata)",
          "  • Fokus pada SATU konflik atau permasalahan utama",
          "  • Jumlah tokoh terbatas (biasanya 2–5 tokoh signifikan)",
          "  • Alur tunggal (satu jalan cerita, tanpa sub-plot rumit)",
          "  • Kesan tunggal — satu perasaan atau pesan yang tersisa setelah membaca",
          "  • Menggunakan bahasa yang ekonomis, padat, dan tidak bertele-tele",
          "  • Bersifat fiktif (rekaan, meskipun bisa terinspirasi dari kisah nyata)",
          "",
          "Tips membaca cerpen: Perhatikan bagaimana penulis membangun konflik hanya dalam beberapa paragraf pertama. Penulis cerpen handal bisa membuatmu peduli pada tokohnya hanya dalam 2–3 kalimat!",
        ],
        contoh: [
          "Contoh pembukaan cerpen yang langsung membangun suasana:",
          "\"Hujan turun sejak subuh. Amir duduk di teras rumah panggung itu, menggenggam secarik kertas yang sudah kusut. Di dalamnya tertera satu kalimat pendek: 'Kita pindah minggu depan.'\"",
          "(Hanya tiga kalimat, pembaca sudah tahu: tokoh Amir, setting hujan, konflik akan pindah rumah — dan ada rasa penasaran.)",
          "",
          "Contoh cerpen 1000 kata vs novel 100 halaman:",
          "Cerpen: 'Robohnya Surau Kami' oleh A.A. Navis — mengisahkan pertobatan seorang kakek penjaga suau dalam 5 halaman.",
          "Novel: 'Laskar Pelangi' oleh Andrea Hirata — mengikuti perjalanan hidup 10 anak Belitung selama bertahun-tahun dalam 534 halaman.",
          "Keduanya sama-sama fiksi, tetapi skala cerita dan kedalaman konfliknya sangat berbeda.",
        ],
        catatan: "Istilah 'cerpen' populer di Indonesia sejak era 1950-an melalui majalah sastra seperti 'Kisah' (dipelopori oleh H.B. Jassin). Sebelumnya, cerita pendek lebih dikenal dengan istilah 'cerita pendek' atau 'short story' (serapan dari bahasa Inggris).",
      },
      {
        judul: "Unsur Intrinsik Cerpen",
        isi: [
          "Setiap cerpen dibangun oleh unsur-unsur dari dalam yang disebut unsur intrinsik. Ini seperti 'organ tubuh' cerpen — tanpa salah satunya, cerita tidak akan hidup. Mari kita bedah satu per satu:",
          "",
          "1. TEMA — Gagasan utama atau ide pokok cerita. Tema adalah 'jiwa' cerpen. Inilah yang ingin disampaikan penulis.",
          "  Tema bisa berupa: persahabatan, perjuangan, percintaan, mimpi, pengorbanan, keadilan, atau kritik sosial.",
          "  ✓ \"Dalam cerpen 'Dilarang Mencintai Bunga-bunga' karya Kuntowijoyo, temanya adalah kritik sosial terhadap ketidakadilan.\"",
          "",
          "2. TOKOH & PENOKOHAN — Tokoh adalah pelaku cerita. Penokohan adalah cara pengarang menggambarkan watak tokoh.",
          "  • Protagonis: tokoh utama yang 'baik' atau menjadi pusat simpati (contoh: Si Kancil dalam dongeng)",
          "  • Antagonis: tokoh lawan yang menimbulkan konflik (contoh: Buaya dalam cerita Si Kancil)",
          "  • Tritagonis: tokoh penengah atau pembantu (contoh: teman si Kancil, atau orang bijak)",
          "  Cara menggambarkan tokoh: melalui dialog, tingkah laku, pikiran tokoh, atau komentar langsung pengarang.",
          "",
          "3. ALUR (PLOT) — Rangkaian peristiwa yang membangun cerita. Alur ibarat 'tulang punggung' cerpen.",
          "  Tahapan alur klasik (Gustav Freytag):",
          "  a. ORIENTASI — Pengenalan tokoh, latar, dan situasi awal",
          "  b. KOMPLIKASI — Mulai muncul masalah atau konflik",
          "  c. KLIMAKS — Puncak konflik, saat paling menegangkan",
          "  d. RESOLUSI — Penyelesaian konflik (happy ending atau sad ending)",
          "  e. KODA — Amanat atau pesan yang bisa dipetik (opsional)",
          "",
          "4. LATAR (SETTING) — Tempat, waktu, dan suasana terjadinya peristiwa.",
          "  • Latar tempat: di mana cerita berlangsung (sekolah, pantai, desa, kota, rumah)",
          "  • Latar waktu: kapan cerita berlangsung (pagi, malam, musim hujan, tahun 1998)",
          "  • Latar suasana: bagaimana perasaan yang terbangun (mencekam, romantis, haru, tegang)",
          "",
          "5. SUDUT PANDANG (POINT OF VIEW) — Posisi pengarang dalam membawakan cerita.",
          "  • Orang pertama ('Aku'): tokoh utama bercerita tentang dirinya sendiri",
          "  • Orang pertama sampingan: 'Aku' hanya sebagai saksi, bukan tokoh utama",
          "  • Orang ketiga serba tahu: pengarang tahu segalanya tentang semua tokoh",
          "  • Orang ketiga terbatas: pengarang hanya mengikuti satu tokoh tertentu",
          "",
          "6. AMANAT — Pesan moral atau pelajaran yang ingin disampaikan penulis. Amanat bisa tersurat (langsung ditulis) atau tersirat (tersembunyi, pembaca menyimpulkan sendiri).",
          "",
          "7. GAYA BAHASA — Cara khas pengarang dalam merangkai kata. Ini 'sidik jari' penulis. Ada yang puitis (Sapardi Djoko Damono), lugas (Pramoedya Ananta Toer), atau jenaka (Raditya Dika).",
        ],
        contoh: [
          "Analisis singkat cerpen 'Mata yang Enak Dipandang' (Ahmad Tohari):",
          "TEMA: Keindahan kesederhanaan dan kepedulian sosial.",
          "TOKOH: Pak Tasman (protagonis — petani sederhana yang jujur).",
          "ALUR: Orientasi (Pak Tasman di sawah) → Komplikasi (ia melihat kemiskinan tetangganya) → Klimaks (ia harus memilih antara membantu atau menyimpan uangnya) → Resolusi (ia memilih berbagi).",
          "LATAR: Desa di Jawa Tengah, siang hari, suasana pedesaan yang tenang.",
          "SUDUT PANDANG: Orang ketiga serba tahu.",
          "AMANAT: Kebahagiaan sejati datang dari memberi, bukan memiliki.",
          "",
          "BENAR (alur jelas): \"Setiap pagi Rina membantu ibu di dapur. Suatu hari, ibunya jatuh sakit. Rina harus memutuskan: berhenti sekolah atau mencari kerja. Air matanya jatuh saat ia membuka tabungan kecilnya.\"",
          "SALAH (alur tidak jelas, lompat-lompat): \"Rina sedih. Ibunya sakit. Eh tiba-tiba Rina sudah kaya raya. Terus mereka bahagia selamanya.\" (Tidak ada komplikasi dan klimaks yang masuk akal.)",
        ],
        catatan: "Dalam satu cerpen, sudut pandang harus KONSISTEN. Jika memulai dengan 'Aku' sebagai tokoh utama, jangan tiba-tiba pindah ke pikiran tokoh lain tanpa transisi yang jelas!",
      },
      {
        judul: "Unsur Ekstrinsik dan Jenis Cerpen",
        isi: [
          "Selain unsur dari dalam, cerpen juga dipengaruhi oleh unsur dari luar yang disebut unsur ekstrinsik. Ini seperti 'lingkungan' tempat cerpen tumbuh.",
          "",
          "• Unsur Ekstrinsik Cerpen:",
          "  1. LATAR BELAKANG PENGARANG — Biografi, pengalaman hidup, pendidikan, profesi, dan pandangan dunia penulis sangat memengaruhi cerita yang ditulisnya.",
          "  \"Pramoedya Ananta Toer menulis cerpen berlatar penjara karena ia sendiri pernah mengalaminya pada masa Orde Baru.\"",
          "",
          "  2. NILAI SOSIAL — Cerpen mencerminkan kondisi masyarakat: kemiskinan, ketidakadilan, tradisi, modernisasi.",
          "  ✓ \"Cerpen 'Robohnya Surau Kami' mengkritik kemunafikan dalam praktik keagamaan masyarakat.\"",
          "",
          "  3. NILAI BUDAYA — Adat istiadat, tradisi, dan kebiasaan yang mewarnai cerita.",
          "  ✓ \"Cerpen berlatar Minang sering menampilkan tradisi merantau dan filosofi 'alam takambang jadi guru'.\"",
          "",
          "  4. NILAI AGAMA — Ajaran agama yang memengaruhi pandangan tokoh atau amanat cerita.",
          "",
          "  5. NILAI MORAL — Etika dan norma yang dipegang tokoh.",
          "",
          "• Jenis Cerpen Berdasarkan Isi:",
          "  • Cerpen Serius: Cerpen dengan tema serius, kritik sosial atau psikologis (Seno Gumira Ajidarma, Pramoedya)",
          "  • Cerpen Humor: Cerpen jenaka yang menghibur (Raditya Dika, B.J. Susianto)",
          "  • Cerpen Romantis: Cerpen tentang percintaan remaja (Dee Lestari, Boy Candra)",
          "  • Cerpen Inspiratif: Cerpen yang memotivasi dan menggugah semangat",
          "  • Cerpen Jenaka: Cerpen dengan kelucuan dan sindiran ringan",
          "",
          "PENTING: Unsur ekstrinsik tidak muncul langsung dalam cerita, tetapi sangat memengaruhi 'rasa' dan 'pesan' yang disampaikan. Makanya, membaca biografi pengarang bisa membantumu memahami cerpennya lebih dalam!",
        ],
        contoh: [
          "Perbedaan cerpen dengan novel:",
          "CERPEN: 'Senyum Karyamin' (Ahmad Tohari) — 3 halaman, 1 konflik (seorang pemulung yang tetap tersenyum di tengah kemiskinan), tokoh tunggal.",
          "NOVEL: 'Ronggeng Dukuh Paruk' (Ahmad Tohari) — 300+ halaman, banyak konflik dan sub-plot (cinta, sosial-politik, ekonomi), puluhan tokoh.",
          "",
          "Perbedaan cerpen dengan dongeng:",
          "CERPEN: Fokus pada realisme, tokoh manusia biasa, latar dunia nyata, amanat tersirat.",
          "DONGENG: Dunia fantasi, tokoh hewan/makhluk ajaib, pesan moral tersurat di akhir cerita ('...dan pesan moral dari cerita ini adalah...').",
          "",
          "Perbedaan cerpen dengan cerita rakyat:",
          "CERPEN: Pengarang diketahui, hak cipta terdaftar, bersifat individual.",
          "CERITA RAKYAT: Pengarang anonim (tidak diketahui), milik kolektif masyarakat, diwariskan secara lisan turun-temurun (contoh: Malin Kundang, Tanggok, Sangkuriang).",
          "",
          "Pengarang cerpen Indonesia terkenal:",
          "• Putu Wijaya — cerpen-cerpen absurd dan surealis",
          "• Seno Gumira Ajidarma — cerpen berlatar kritik sosial dan HAM",
          "• Dee Lestari — cerpen dengan tema spiritual dan romantis",
          "• Ahmad Tohari — cerpen berlatar pedesaan Jawa",
          "• Hamsad Rangkuti — maestro cerpen Indonesia dengan gaya minimalis",
          "• Sapardi Djoko Damono — cerpen puitis seperti puisinya",
          "• Leila S. Chudori — cerpen berlatar sejarah dan diaspora",
        ],
        catatan: "Menurut KBBI, cerita pendek adalah 'cerita yang pendek yang berisi tentang suatu kejadian atau peristiwa yang dialami oleh seseorang atau tokoh tertentu dalam kehidupan sehari-hari'. Definisi sederhana, tapi di dalamnya ada dunia yang luas!",
      },
    ],
    rangkuman: [
      "Cerpen adalah cerita fiktif berbentuk prosa naratif yang selesai dibaca dalam sekali duduk, fokus pada satu konflik, dengan jumlah tokoh terbatas.",
      "Ciri khas cerpen: panjang 1.000–10.000 kata, alur tunggal, kesan tunggal, bahasa ekonomis dan padat.",
      "Unsur intrinsik cerpen terdiri dari 7 elemen: tema, tokoh & penokohan (protagonis, antagonis, tritagonis), alur (orientasi–komplikasi–klimaks–resolusi–koda), latar (tempat, waktu, suasana), sudut pandang (orang pertama/ketiga), amanat, dan gaya bahasa.",
      "Unsur ekstrinsik meliputi latar belakang pengarang serta nilai sosial, budaya, agama, dan moral yang memengaruhi cerita.",
      "Alur klasik terdiri dari 5 tahap: orientasi (pengenalan), komplikasi (masalah muncul), klimaks (puncak konflik), resolusi (penyelesaian), dan koda (pesan opsional).",
      "Cerpen berbeda dengan novel (yang lebih panjang dengan banyak konflik), dongeng (fantasi dengan pesan moral eksplisit), dan cerita rakyat (anonim, milik kolektif, lisan).",
      "Menulis cerpen yang baik memerlukan ide yang kuat, konflik yang jelas, karakter yang hidup, dan sudut pandang yang konsisten.",
    ],
  },

  latihan: makeSoal([
    ["Berikut ini yang merupakan pengertian cerpen yang tepat adalah...", ["Karangan fiktif panjang dengan banyak konflik", "Cerita fiktif pendek yang selesai dibaca sekali duduk dengan satu konflik", "Karangan nonfiksi tentang kehidupan seseorang", "Cerita rakyat yang diwariskan turun-temurun"], 1, "Cerpen adalah cerita fiktif pendek dengan satu konflik utama yang dapat selesai dibaca dalam sekali duduk."],
    ["Tokoh yang menjadi lawan dari tokoh utama dan menimbulkan konflik disebut...", ["Protagonis", "Antagonis", "Tritagonis", "Figuran"], 1, "Antagonis adalah tokoh lawan yang menimbulkan konflik atau pertentangan dengan tokoh utama."],
    ["Tahapan alur di mana konflik mencapai puncak ketegangan disebut...", ["Orientasi", "Komplikasi", "Klimaks", "Resolusi"], 2, "Klimaks adalah puncak konflik, saat ketegangan berada pada titik tertinggi dalam cerita."],
    ["'Aku bangun pagi ini dengan perasaan aneh. Telepon berdering. Ibu mengangkatnya, lalu wajahnya berubah pucat.' Cuplikan tersebut menggunakan sudut pandang...", ["Orang ketiga serba tahu", "Orang pertama tokoh utama", "Orang ketiga terbatas", "Orang pertama sampingan"], 1, "Kata 'Aku' menunjukkan sudut pandang orang pertama. Karena 'Aku' adalah yang mengalami peristiwa, ini orang pertama tokoh utama."],
    ["Berikut yang BUKAN merupakan unsur intrinsik cerpen adalah...", ["Tema", "Latar belakang pengarang", "Alur", "Gaya bahasa"], 1, "Latar belakang pengarang adalah unsur EKSTRINSIK, bukan intrinsik. Unsur intrinsik meliputi tema, tokoh, alur, latar, sudut pandang, amanat, dan gaya bahasa."],

    ["Pernyataan: 'Cerpen dan novel memiliki panjang yang sama, yaitu sekitar 10.000–50.000 kata.'", ["Betul", "Salah"], 1, "SALAH. Cerpen memiliki panjang 1.000–10.000 kata, sedangkan novel bisa mencapai 50.000+ kata."],
    ["Pernyataan: 'Latar dalam cerpen mencakup tiga aspek: tempat, waktu, dan suasana.'", ["Betul", "Salah"], 0, "BETUL. Latar dibagi menjadi latar tempat (di mana), latar waktu (kapan), dan latar suasana (bagaimana perasaan)."],
    ["Pernyataan: 'Amanat dalam cerpen selalu ditulis secara tersurat di akhir cerita.'", ["Betul", "Salah"], 1, "SALAH. Amanat bisa tersurat (langsung ditulis) atau tersirat (disimpulkan sendiri oleh pembaca dari keseluruhan cerita)."],

    ["Konflik dalam cerpen yang terjadi antara tokoh utama dengan tokoh lain disebut konflik...", ["internal", "eksternal fisik", "eksternal sosial", "batin"], 2, "Konflik eksternal sosial adalah konflik antartokoh atau antara tokoh dengan lingkungan sosialnya."],
    ["Cerpen 'Robohnya Surau Kami' karya A.A. Navis mengandung kritik sosial tentang...", ["Kemiskinan di desa", "Kemunafikan dalam praktik keagamaan", "Kehidupan remaja kota", "Pendidikan di Indonesia"], 1, "Cerpen 'Robohnya Surau Kami' mengkritik kemunafikan dan praktik keagamaan yang tidak tulus dalam masyarakat."],
  ]),

  praktik: {
    petunjuk: "Tulis sebuah cerpen pendek bertema 'Kebaikan Tak Terduga' sepanjang 3—5 paragraf dengan struktur lengkap.\n\nLangkah-langkah:\n1. Tentukan tokoh utama (minimal 1, maksimal 3 tokoh) dan beri nama.\n2. Tentukan latar tempat dan waktu yang jelas.\n3. Mulailah dengan ORIENTASI — perkenalkan tokoh dan situasi awal dalam 1 paragraf.\n4. Kembangkan KOMPLIKASI — munculkan masalah atau kejutan dalam 1—2 paragraf.\n5. Capai KLIMAKS — saat konflik mencapai puncaknya.\n6. Akhiri dengan RESOLUSI — bagaimana konflik terselesaikan.\n7. Sertakan amanat tersirat (jangan ditulis langsung, biarkan pembaca menyimpulkan sendiri).\n8. Gunakan sudut pandang yang konsisten (pilih salah satu: orang pertama atau orang ketiga).\n\nTulis cerpenmu di kolom di bawah ini!",
    tips: [
      "Mulai dengan kalimat pembuka yang menarik perhatian: 'Tidak pernah terbayangkan oleh Rina bahwa secangkir kopi akan mengubah hidupnya.'",
      "Gunakan dialog untuk menghidupkan tokoh, jangan hanya bercerita tentang mereka.",
      "Tunjukkan, jangan ceritakan (show, don't tell). Contoh: 'Tangannya gemetar, dadanya naik turun' lebih baik daripada 'Ia sangat gugup'.",
      "Batasi jumlah tokoh agar cerita tetap fokus — 2 atau 3 tokoh sudah cukup.",
      "Pilih konflik yang sederhana tapi bermakna: dompet hilang, bertemu orang asing, keputusan sulit, atau pengorbanan kecil.",
      "Baca ulang dan potong kalimat yang tidak perlu. Setiap kata harus berarti dalam cerpen.",
      "Minta teman membaca cerpenmu — masukan mereka sangat berharga untuk perbaikan.",
    ],
    contoh: "Tidak pernah terbayangkan oleh Danu bahwa ban motor bocor di pinggir jalan akan membawanya mendapat sahabat baru. Hari itu hujan deras. Danu sedang dalam perjalanan ke rumah neneknya di desa. Ia sudah basah kuyup dan frustrasi karena motornya tidak bisa jalan. Tidak ada bengkel di sekitar, dan ponselnya kehabisan baterai.\n\nSeorang bapak paruh baya yang sedang berteduh di teras rumahnya melihat Danu kebingungan. 'Nak, mampir dulu. Hujannya masih lebat. Nanti setelah reda, Bapak antar ke bengkel,' katanya ramah. Danu ragu, tetapi ia juga tidak punya pilihan lain.\n\nDi dalam rumah sederhana itu, bapak itu menyuguhkan teh hangat dan pisang goreng buatan istrinya. Obrolan ringan mengalir. Ternyata bapak itu adalah pensiunan guru yang dulu mengajar di sekolah Danu — ia bahkan mengenal almarhum ayah Danu. 'Ayahmu muridku paling pintar, nak. Dia selalu teliti dan tidak pernah menyerah,' kenang sang bapak sambil tersenyum.\n\nSatu jam kemudian hujan reda. Bapak itu mengantarkan Danu ke bengkel dan bahkan membayarkan ongkos tambalnya tanpa diminta. Danu hanya bisa berterima kasih dengan mata berkaca-kaca. Sejak hari itu, setiap minggu Danu menyempatkan diri mampir ke rumah bapak itu untuk sekadar mengobrol. Ia belajar satu hal: kebaikan sering datang dari tempat yang paling tak terduga, dan satu perbuatan baik bisa mengubah hidup seseorang selamanya.",
  },

  kuis: makeSoal([
    ["Cerpen adalah singkatan dari...", ["Cerita panjang", "Cerita pendek", "Cerita penuh", "Cerita pembuka"], 1, "Cerpen = Cerita Pendek, sesuai dengan karakteristiknya yang selesai dibaca dalam sekali duduk."],
    ["Berikut ini yang termasuk ciri-ciri cerpen, KECUALI...", ["Panjang 1.000–10.000 kata", "Memiliki satu konflik utama", "Memiliki sub-plot yang kompleks", "Jumlah tokoh terbatas"], 2, "Sub-plot kompleks adalah ciri NOVEL, bukan cerpen. Cerpen hanya memiliki satu alur utama."],
    ["Tahap alur di mana masalah mulai muncul disebut...", ["Orientasi", "Komplikasi", "Klimaks", "Resolusi"], 1, "Komplikasi adalah tahap di mana konflik atau masalah mulai terlihat dan berkembang dalam cerita."],
    ["Sudut pandang orang ketiga serba tahu berarti...", ["Pengarang tidak tahu apapun tentang tokoh", "Pengarang hanya tahu satu tokoh", "Pengarang tahu segalanya tentang semua tokoh", "Tokoh utama bercerita tentang dirinya"], 2, "Orang ketiga serba tahu (omniscient): pengarang mengetahui pikiran, perasaan, dan masa lalu semua tokoh."],
    ["'Angin malam berbisik lembut di telinga Maya.' Kalimat ini mengandung majas...", ["Personifikasi", "Metafora", "Hiperbola", "Ironi"], 0, "Personifikasi karena 'angin berbisik' — angin diberi sifat seperti manusia yang bisa berbisik."],
    ["Yang membedakan cerpen dengan dongeng adalah...", ["Cerpen lebih panjang", "Dongeng bersifat fantasi dengan pesan moral eksplisit", "Cerpen selalu sedih", "Dongeng memiliki alur"], 1, "Dongeng berlatar dunia fantasi dengan tokoh hewan/makhluk ajaib dan pesan moral ditulis jelas, berbeda dengan cerpen yang realistik."],
    ["Tokoh tritagonis dalam cerpen adalah tokoh yang berperan sebagai...", ["Lawan tokoh utama", "Penengah atau pembantu", "Tokoh utama", "Tokoh figuran"], 1, "Tritagonis adalah tokoh penengah atau pembantu yang menjadi jembatan antara protagonis dan antagonis."],
    ["Amanat tersirat dalam cerpen berarti...", ["Pesan ditulis langsung di akhir", "Pesan harus disimpulkan pembaca", "Tidak ada pesan", "Pesan hanya untuk guru"], 1, "Amanat tersirat tidak ditulis eksplisit oleh pengarang, melainkan harus dipahami dan disimpulkan sendiri oleh pembaca."],
    ["Pengarang cerpen 'Senyum Karyamin' yang juga terkenal dengan latar pedesaan Jawa adalah...", ["Putu Wijaya", "Ahmad Tohari", "Seno Gumira Ajidarma", "Dee Lestari"], 1, "Ahmad Tohari dikenal dengan cerpen-cerpennya yang berlatar pedesaan Jawa, termasuk 'Senyum Karyamin' dan novel 'Ronggeng Dukuh Paruk'."],
    ["Fungsi latar suasana dalam cerpen adalah...", ["Menentukan tema cerita", "Membangun perasaan dan atmosfer tertentu", "Menjelaskan waktu kejadian", "Menunjukkan nama tempat"], 1, "Latar suasana membangun atmosfer atau perasaan tertentu pada pembaca, misalnya tegang, haru, atau romantis."],
  ]),
}

export default konten
