import type { Konten } from "../types"
import { makeSoal } from "../types"

const konten: Konten = {
  belajar: {
    tujuan: [
      "Memahami pengertian, tujuan, dan perbedaan iklan, slogan, dan poster",
      "Mengidentifikasi struktur dan kaidah kebahasaan iklan, slogan, dan poster",
      "Menganalisis jenis-jenis iklan berdasarkan media dan tujuannya",
      "Membedakan ciri-ciri slogan yang efektif dari yang tidak efektif",
      "Membuat iklan, slogan, dan poster yang menarik dan persuasif",
    ],
    materi: [
      {
        judul: "Mengenal Iklan, Slogan, dan Poster",
        isi: [
          "Setiap hari kita dikelilingi oleh ajakan, imbauan, dan promosi. Saat membuka Instagram, ada video singkat yang mengajak membeli produk. Di pinggir jalan, spanduk raksasa menampilkan gambar dengan kalimat besar. Di papan sekolah, tertulis \"Bersih itu Indah\". Ketiganya adalah bentuk komunikasi persuasif: iklan, slogan, dan poster.",
          "",
          "Apa perbedaannya? Mari kita bedah satu per satu!",
          "",
          "1. IKLAN — Iklan adalah pesan persuasif yang disampaikan melalui media massa (TV, radio, koran, internet, billboard) untuk mempromosikan produk, jasa, atau ide kepada khalayak luas. Tujuan akhirnya: membujuk audiens melakukan sesuatu — membeli, mendaftar, peduli, atau mengubah kebiasaan.",
          "  ✓ \"Dapatkan smartphone terbaru dengan kamera 108 MP! Promo awal tahun, diskon 30%!\"",
          "  ✓ \"Ayo vaksinasi! Lindungi diri dan keluarga dari COVID-19.\" (iklan layanan masyarakat)",
          "",
          "2. SLOGAN — Slogan adalah kalimat atau frasa pendek yang mudah diingat, digunakan sebagai identitas, motto, atau semboyan suatu organisasi, produk, kampanye, atau gerakan. Bedanya dengan iklan: slogan tidak selalu menjelaskan produk, tapi menjadi ingatan yang melekat.",
          "  ✓ \"Bhinneka Tunggal Ika\" (slogan negara)",
          "  ✓ \"Ada Aqua\" (slogan produk — melekat bertahun-tahun)",
          "  ✓ \"Membaca Membuka Jendela Dunia\" (slogan literasi)",
          "",
          "3. POSTER — Poster adalah plakat bergambar yang dipajang di tempat umum, berisi perpaduan gambar dan teks untuk menyampaikan pesan tertentu dalam sekali pandang. Poster menggabungkan kekuatan visual (gambar, warna, tipografi) dan verbal (teks singkat).",
          "  ✓ Poster pahlawan di kelas: gambar pahlawan + teks \"Jadilah Penerus Bangsa\"",
"  ✓ Poster antinarkoba: gambar tengkorak + teks \"Narkoba: Hancurkan Masa Depanmu!\"",
"",
"[Ilustrasi: Tiga contoh media: (1) Iklan pasta gigi di majalah dengan foto senyum sehat, (2) Slogan 'Budi Pekerti' di spanduk jalan, (3) Poster anti-narkoba berwarna merah-hitam dengan ilustrasi tengkorak. Masing-masing punya karakter visual berbeda.]",
"",
"PENTING: Slogan bisa menjadi bagian dari iklan atau poster. Poster boleh memuat slogan. Iklan boleh menggunakan slogan sebagai headline. Ketiganya saling terkait tetapi berbeda!",
        ],
        contoh: [
          "Perhatikan perbedaan ketiganya dalam satu tema yang sama — KEBERSIHAN:",
          "",
          "IKLAN (media sosial/televisi):",
          "Video singkat seorang ibu menyapu halaman, lalu muncul teks: \"Kebersihan dimulai dari rumah sendiri. Gunakan Produk Pembersih X — bersih maksimal, keluarga sehat!\" Disertai logo produk dan ajakan \"Beli Sekarang di Tokopedia!\"",
          "",
          "SLOGAN (motto kampanye):",
          "\"Kebersihan Sebagian dari Iman\" — kalimat pendek, religius, mudah diingat. Siapa pun yang mendengar langsung paham pesannya.",
          "",
          "POSTER (ditempel di mading/tempat umum):",
          "Gambar ilustrasi tangan memegang sapu dan tempat sampah, background hijau segar, dengan teks besar: \"JAGA KEBERSIHAN!\" dan subteks: \"Buang sampah pada tempatnya. Mulai dari dirimu sendiri.\"",
          "",
          "BENAR: Iklan = bujuk + media. Slogan = pendek + mudah diingat. Poster = gambar + teks.",
          "SALAH: Menganggap slogan dan poster adalah hal yang sama. Poster membutuhkan gambar, slogan cukup kalimat saja.",
        ],
        catatan: "Kata 'iklan' berasal dari bahasa Arab 'i'lan' yang berarti pemberitahuan. Dalam bahasa Inggris disebut 'advertisement' (ad). Iklan pertama di Indonesia muncul di media cetak pada era kolonial Belanda untuk mempromosikan produk impor.",
      },
      {
        judul: "Struktur dan Ciri Kebahasaan",
        isi: [
          "Mari bedah struktur dan bahasa yang membuat iklan, slogan, dan poster efektif!",
          "",
          "STRUKTUR IKLAN:",
          "1. HEADLINE (Judul) — Kalimat utama yang menarik perhatian. Harus strong, jelas, dan memicu rasa ingin tahu.",
          "  ✓ \"Diskon 50% — Hari Ini Saja!\" (urgensi)",
          "  ✓ \"Kulit Sehat Tanpa Mahal\" (manfaat)",
          "  ✗ \"Produk Baru Tersedia\" (membosankan, tidak menggugah)",
          "",
          "2. SUBHEAD — Kalimat pendukung headline yang memberikan informasi tambahan singkat.",
          "  ✓ \"Krim pemutih alami dengan bahan organik bersertifikat BPOM.\"",
          "",
          "3. BODY COPY — Penjelasan lengkap tentang produk/jasa/ide. Berisi fakta, manfaat, keunggulan, dan bujukan.",
          "  ✓ \"Dibuat dari ekstrak lidah buaya asli, formula kami telah teruji klinis. Dalam 14 hari, kulitmu terasa lebih cerah dan lembap. Tanpa efek samping, tanpa bahan kimia berbahaya.\"",
          "",
          "4. VISUAL — Gambar, ilustrasi, atau video yang mendukung pesan. 'Sebuah gambar berbicara seribu kata.'",
          "",
          "5. CALL TO ACTION (Ajakan) — Kalimat yang mendorong audiens bertindak: beli, klik, daftar, kunjungi, hubungi.",
          "  ✓ \"Pesan Sekarang! Gratis ongkir ke seluruh Indonesia.\"",
          "  ✓ \"Klik link di bio untuk sample gratis!\"",
          "",
"6. LOGO/IDENTITAS — Nama merek, logo, alamat, kontak yang memperkuat kredibilitas.",
"",
"[Ilustrasi: Struktur iklan di majalah: HEADLINE besar 'Diskon 50%!' — gambar produk — body copy menjelaskan manfaat — kalimat ajakan 'Beli Sekarang!' — logo merek di sudut bawah.]",
"",
"STRUKTUR POSTER:",
          "1. Judul — Pesan utama, biasanya dalam font besar dan mencolok.",
          "2. Gambar/Ilustrasi — Elemen visual yang mendukung pesan. Bisa foto, gambar tangan, atau grafik.",
          "3. Pesan — Teks pendukung yang menjelaskan atau memperkuat judul.",
          "4. Ajakan — Kalimat persuasif yang mendorong tindakan (jika relevant).",
          "5. Logo/Identitas — Pencantum pembuat atau sponsor.",
          "",
          "CIRI SLOGAN EFEKTIF:",
          "  • Singkat — 3–7 kata ideal, langsung ke inti",
          "  • Jelas — Makna mudah dipahami tanpa penjelasan",
          "  • Mudah diingat — Sederhana, enak diucapkan, kadang berima",
          "  • Menggugah — Menyentuh emosi atau kesadaran",
          "  • Orisinal — Tidak meniru slogan yang sudah ada",
          "  ✓ \"Berani Jujur Hebat\" (slogan KPK — singkat, berima, menggugah)",
          "  ✓ \"Gemar Membaca\" (slogan perpustakaan — simpel, jelas)",
          "  ✗ \"Produk kami adalah produk yang paling bagus untuk dipakai oleh semua orang yang menginginkan kualitas\" (terlalu panjang, tidak ringkas)",
        ],
        contoh: [
          "Analisis struktur iklan berikut:",
          "",
          "\"Rasakan Sensasi Kopi Asli Nusantara\"",
          "HEADLINE: 'Rasakan Sensasi' — kata kerja imperatif yang mengajak merasakan. 'Kopi Asli Nusantara' membangkitkan rasa bangga pada produk lokal.",
          "SUBHEAD: '100% biji kopi pilihan dari Gayo, Toraja, dan Flores.'",
          "BODY: 'Diproses secara tradisional oleh petani berpengalaman. Tanpa campuran, tanpa pengawet. Dikemas langsung dari kebun ke cangkirmu.'",
          "VISUAL: Foto secangkir kopi dengan latar pegunungan hijau, uap mengepul.",
          "CTA: 'Pesan sekarang di www.kopinusantara.com — Diskon 20% untuk pembelian pertama!'",
          "LOGO: Logo 'Kopi Nusantara' dengan tagline 'Asli Indonesia, Mendunia.'",
          "",
          "BENAR: Headline menarik, body copy informatif, CTA jelas, visual mendukung.",
          "SALAH: Iklan tanpa CTA (audiens bingung harus apa setelah membaca). Atau iklan tanpa visual (membosankan, mudah diabaikan).",
        ],
        catatan: "Dalam dunia periklanan modern, dikenal aturan AIDA: Attention (perhatikan), Interest (minat), Desire (keinginan), Action (tindakan). Iklan yang baik harus melewati keempat tahap ini. Coba cek iklan favoritmu — apakah mengandung AIDA?",
      },
      {
        judul: "Kaidah Kebahasaan Iklan, Slogan, dan Poster",
        isi: [
          "Iklan, slogan, dan poster memiliki ciri bahasa yang khas. Inilah 'senjata' mereka untuk membujuk dan memengaruhi!",
          "",
          "1. KALIMAT PERSUASIF — Kalimat yang bersifat mengajak, membujuk, atau memengaruhi. Kata kunci: ayo, mari, yuk, jangan, sebaiknya, lebih baik.",
          "  ✓ \"Mari berhenti merokok untuk masa depan yang lebih sehat!\"",
          "  ✓ \"Ayo belanja di toko kami! Diskon spesial akhir bulan!\"",
          "  ✓ \"Jangan biarkan sampah plastik mencemari laut kita.\"",
          "",
          "2. KALIMAT IMPERATIF — Kalimat perintah yang menyuruh melakukan sesuatu. Biasa dipakai di iklan dan poster.",
          "  ✓ \"Gunakan sabun ABC setiap hari untuk kulit bersih!\"",
          "  ✓ \"Beli satu gratis satu! Stok terbatas!\"",
          "  ✓ \"Pilih pemimpin yang jujur dan amanah!\"",
          "",
          "3. KATA KONKRET — Kata yang merujuk pada benda nyata yang bisa diamati/dirasakan. Membuat pesan lebih hidup dan terpercaya.",
          "  ✓ \"Krim ini mengandung vitamin E, kolagen, dan SPF 30.\" (bukan sekadar 'bagus untuk kulit')",
          "  ✓ \"Harga Rp50.000 — bukan 'murah meriah' (abstrak)\"",
          "",
          "4. RIMA DAN IRAMA — Khas pada slogan. Pengulangan bunyi membuat kalimat enak didengar dan mudah diingat.",
          "  ✓ \"Berani Jujur Hebat\" (rima akhir: -at)",
          "  ✓ \"Panas, Sehat, Pulih Cepat\" (slogan obat — irama tiga kata)",
          "  ✓ \"Ada Aqua\" (rima internal: a-a-u-a)",
          "",
          "5. KATA SUPERLATIF — Kata yang menunjukkan keunggulan atau tingkatan paling. Sering dipakai di iklan komersial.",
          "  ✓ \"Yang TERBAIK untuk keluarga Anda\"",
          "  ✓ \"Kualitas NOMOR SATU di Indonesia\"",
          "  ✓ \"Formula PALING LENGKAP dengan 12 vitamin\"",
          "",
          "6. FAKTA ATAU OPINI BERKEDOK FAKTA — Iklan sering menyertakan data, testimoni, atau statistik untuk memperkuat kredibilitas.",
          "  ✓ \"9 dari 10 dokter gigi merekomendasikan Pasta Gigi X.\"",
          "  ✓ \"Telah terjual 5 juta unit di seluruh dunia.\"",
          "",
          "Tips menulis iklan/slogan/poster: Gaya bahasa yang digunakan HARUS disesuaikan dengan target audiens. Iklan untuk remaja: bahasa gaul, santai. Iklan untuk profesional: formal, data-driven. Iklan untuk anak-anak: sederhana, penuh warna, berima.",
        ],
        contoh: [
          "Analisis kebahasaan slogan terkenal:",
          "",
          "SLOGAN: \"Berani Jujur Hebat\" (KPK)",
          "  • Kalimat persuasif: mengajak berani jujur (nilai positif)",
          "  • Imperatif: 'berani' adalah ajakan untuk bertindak",
          "  • Rima: 'jujur' - 'hebat' (suku kata akhir: -ur vs -at, tapi enak diucapkan)",
          "  • Superlatif: 'hebat' (menunjukkan keunggulan sikap jujur)",
          "  • Hanya 3 kata — sangat singkat dan mudah diingat!",
          "",
          "SLOGAN: \"Menyambung Kehidupan\" (Air mineral) — kata konkret (menyambung, kehidupan), rima (samar), pesan jelas tentang fungsi air.",
          "",
          "SLOGAN: \"Satu Indonesia\" (provider) — hanya 2 kata, superlatif tersirat (satu = nomor satu, satu = harga tunggal, satu = menyatukan Nusantara). Multiinterpretasi yang cerdas!",
          "",
          "BENAR: \"Ayo sekolah! Masa depanmu di tanganmu.\" — kalimat persuasif (ayo) + imperatif (sekolah).",
          "SALAH: \"Sekolah itu bagus menurut saya.\" — opini subjektif, tidak persuasif, tidak imperatif, terlalu lemah.",
        ],
        catatan: "Hati-hati dengan hiperbola berlebihan dalam iklan! Janji 'sembuh seketika' atau 'putih dalam 1 hari' bisa melanggar etika periklanan dan mengecewakan konsumen. Iklan yang baik bersifat jujur dan realistis.",
      },
      {
        judul: "Jenis-Jenis Iklan",
        isi: [
          "Tidak semua iklan sama. Kenali jenis-jenisnya agar kamu bisa membedakan tujuan dan strategi masing-masing!",
          "",
          "1. IKLAN KOMERSIAL — Bertujuan mempromosikan produk atau jasa untuk mendapatkan keuntungan ekonomi.",
          "  • Iklan produk: makanan, minuman, pakaian, elektronik, kosmetik, kendaraan",
          "  • Iklan jasa: pendidikan, kursus, asuransi, perbankan, transportasi",
          "  • Iklan ritel: promo diskon, obral akhir tahun, flash sale",
          "  Contoh: \"Dapatkan Mi Instan X dengan tambahan telur! Enak, murah, dan bergizi!\"",
          "",
          "2. IKLAN LAYANAN MASYARAKAT (ILM) — Iklan nonkomersial yang bertujuan mendidik, mengimbau, atau meningkatkan kesadaran masyarakat tentang isu sosial, kesehatan, atau lingkungan.",
          "  • Kesehatan: imunisasi, berhenti merokok, cuci tangan, pola hidup sehat",
          "  • Lingkungan: buang sampah, hemat energi, penanaman pohon",
          "  • Sosial: anti narkoba, anti kekerasan, kesetaraan gender",
          "  • Pendidikan: ayo membaca, sekolah gratis, vaksinasi pelajar",
          "  Contoh: \"Lindungi bumi! Kurangi penggunaan plastik sekali pakai. Mulai dari sekarang!\" (tanpa menjual produk apapun)",
          "",
          "PENTING: Iklan layanan masyarakat biasanya diproduksi oleh pemerintah, organisasi nirlaba, atau perusahaan sebagai bentuk CSR (Corporate Social Responsibility).",
          "",
          "3. IKLAN BARIS — Iklan singkat berbentuk teks tanpa gambar, dipasang di media cetak (koran/majalah), berbayar per baris.",
          "  • Lowongan kerja: \"Dibutuhkan segera admin kantor. Min. SMK. Kirim lamaran ke...\"",
          "  • Jual/beli: \"Djual Samsung A52 mulus no minus harga 2,5jt hub 0812xxxx\"",
          "  • Layanan: \"Guru privat matematika & fisika. Pengalaman 5 tahun. Hub...\"",
          "  Ciri: singkat, padat, hemat tempat, tanpa hiasan.",
          "",
          "4. IKLAN DISPLAY — Iklan yang menggunakan ruang lebih besar dengan kombinasi teks, gambar, warna, dan desain grafis. Bisa di majalah, koran, billboard, atau digital.",
          "  • Billboard: iklan raksasa di tepi jalan",
          "  • Banner digital: iklan di website dan media sosial",
          "  • Iklan majalah: full page, half page, atau kolom khusus",
          "  Ciri: visual menarik, desain profesional, pesan singkat namun kuat.",
          "",
          "Tips: Jenis iklan menentukan gaya bahasa dan medianya. Iklan baris harus efisien. Iklan display boleh lebih artistik. Iklan layanan masyarakat harus menyentuh hati. Sesuaikan!",
        ],
        contoh: [
          "Perbandingan 4 jenis iklan dalam tema yang berbeda:",
          "",
          "IKLAN KOMERSIAL (Teh Botol):",
          "\"Teh Botol Sosro — Apapun makanannya, minumnya Teh Botol Sosro!\"",
          "Media: TV, YouTube, billboard. Tujuan: menjual teh siap minum.",
          "Strategi: asosiasikan produk dengan kebiasaan sehari-hari (makan).",
          "",
          "IKLAN LAYANAN MASYARAKAT (Kampanye Antinarkoba):",
          "\"Narkoba: Hancurkan Hidupmu, Hancurkan Mimpimu!\"",
          "Media: poster di sekolah, baliho di jalan, video di media sosial.",
          "Tujuan: mencegah penyalahgunaan narkoba (nonprofit).",
          "Strategi: visual yang mengerikan, peringatan tegas.",
          "",
          "IKLAN BARIS (Koran):",
          "\"Dijual Cpt BMW 320i 2015 hitam mulus pajak panjang. 185jt nego. Hub: 0812xxxxx\"",
          "Media: koran Kompas Halaman 12. Tanpa gambar, tanpa warna.",
          "Strategi: informasi penting saja — barang, kondisi, harga, kontak.",
          "",
          "IKLAN DISPLAY (Majalah):",
          "\"Full page iklan parfum: foto model elegan dengan gaun merah, botol parfum di tangan, teks 'Elegance in Every Drop' — latar belakang hitam, font emas.\"",
          "Media: majalah fashion. Strategi: membangun citra mewah dan prestisius.",
          "",
          "BENAR: Iklan baris tidak butuh kata-kata puitis — langsung ke informasi.",
          "SALAH: Iklan layanan masyarakat mempromosikan produk (itu iklan komersial, bukan ILM).",
        ],
        catatan: "Iklan baris mulai ditinggalkan seiring menurunnya pembaca koran cetak. Namun di daerah tertentu dan untuk rubrik lowongan kerja, iklan baris masih efektif dan lebih murah dibanding iklan display.",
      },
    ],
    rangkuman: [
      "Iklan adalah pesan persuasif melalui media massa/medsos untuk mempromosikan produk, jasa, atau ide — bersifat komersial atau nonkomersial (layanan masyarakat).",
      "Slogan adalah kalimat/frasa pendek, mudah diingat, digunakan sebagai motto atau identitas — ciri: singkat (3–7 kata), jelas, menggugah, orisinal, sering berima.",
      "Poster adalah plakat bergambar + teks yang dipajang di tempat umum — menggabungkan kekuatan visual dan verbal untuk menyampaikan pesan dalam sekali pandang.",
      "Slogan bisa menjadi bagian dari iklan atau poster. Ketiganya saling terkait tetapi memiliki definisi dan struktur yang berbeda.",
      "Struktur iklan: Headline → Subhead → Body Copy → Visual → Call to Action → Logo. Struktur poster: Judul → Gambar → Pesan → Ajakan → Logo.",
      "Kaidah kebahasaan: kalimat persuasif (mari, ayo, jangan), imperatif (gunakan, beli, pilih), kata konkret, rima/irama, dan kata superlatif.",
      "Jenis iklan: komersial (produk/jasa), layanan masyarakat (sosial/kesehatan/lingkungan), iklan baris (teks singkat di koran), dan iklan display (gambar + teks, media cetak/digital).",
      "Iklan efektif mengikuti prinsip AIDA: Attention (perhatian), Interest (minat), Desire (keinginan), Action (tindakan).",
    ],
  },

  latihan: makeSoal([
    ["Berikut ini pengertian iklan yang paling tepat adalah...", ["Pesan yang hanya berisi promosi produk makanan", "Pesan persuasif melalui media massa untuk mempromosikan produk/jasa/ide", "Teks pendek yang dipasang di pinggir jalan", "Kalimat pendek yang mudah diingat sebagai identitas"], 1, "Iklan adalah pesan persuasif melalui media massa/medsos untuk mempromosikan produk, jasa, atau ide kepada khalayak luas."],
    ["Slogan yang baik memiliki ciri-ciri berikut, KECUALI...", ["Singkat dan mudah diingat", "Mengandung rima atau irama yang menarik", "Menggunakan kalimat kompleks dan panjang", "Menggugah emosi atau kesadaran"], 2, "Slogan justru harus singkat dan ringkas (3–7 kata ideal), bukan panjang dan kompleks."],
    ["Struktur poster yang tepat setelah judul adalah...", ["Call to action", "Gambar/ilustrasi", "Logo", "Harga produk"], 1, "Setelah judul, poster menampilkan gambar/ilustrasi sebagai daya tarik visual utama sebelum teks pesan."],
    ["Kalimat 'Ayo gunakan produk dalam negeri!' termasuk jenis kalimat...", ["Deklaratif", "Interogatif", "Imperatif", "Eksklamatif"], 2, "Kalimat 'Ayo gunakan' adalah kalimat imperatif (perintah/ajakan) yang mendorong audiens melakukan tindakan."],
    ["Berikut adalah jenis iklan berdasarkan tujuannya, KECUALI...", ["Iklan komersial", "Iklan layanan masyarakat", "Iklan baris", "Iklan terapi"], 3, "Iklan terapi tidak termasuk jenis iklan yang dikenal. Jenis iklan meliputi komersial, layanan masyarakat, baris, dan display."],

    ["Pernyataan: 'Poster hanya membutuhkan teks saja untuk menyampaikan pesan, gambar tidak wajib.'", ["Betul", "Salah"], 1, "SALAH. Poster adalah plakat BERGAMBAR + teks. Gambar/ilustrasi adalah elemen wajib poster yang membedakannya dari pengumuman biasa."],
    ["Pernyataan: 'Iklan layanan masyarakat bertujuan mencari keuntungan finansial bagi perusahaan.'", ["Betul", "Salah"], 1, "SALAH. Iklan layanan masyarakat bersifat NONKOMERSIAL — bertujuan mendidik, mengimbau, dan meningkatkan kesadaran, bukan mencari untung."],
    ["Pernyataan: 'Slogan 'Bhinneka Tunggal Ika' termasuk slogan kebangsaan yang menjadi semboyan Negara Indonesia.'", ["Betul", "Salah"], 0, "BETUL. 'Bhinneka Tunggal Ika' adalah slogan kebangsaan yang tercantum dalam lambang negara Garuda Pancasila."],

    ["Bagian iklan yang berisi kalimat ajakan seperti 'Beli sekarang!' atau 'Kunjungi toko kami!' disebut...", ["headline", "body copy", "call to action", "subhead"], 2, "Call to Action adalah bagian iklan yang mendorong audiens untuk segera bertindak."],
    ["Prinsip AIDA dalam periklanan adalah Attention, Interest, ..., dan Action. Kata yang tepat untuk mengisi titik-titik adalah...", ["Desire", "Design", "Decision", "Direction"], 0, "AIDA = Attention (perhatian), Interest (minat), Desire (keinginan), Action (tindakan)."],
  ]),

  praktik: {
    petunjuk: "Buatlah POSTER KAMPANYE tentang salah satu tema berikut:\n\n1. \"Cinta Bahasa Indonesia\" — Mengajak teman-teman menggunakan bahasa Indonesia yang baik dan benar.\n2. \"Hidup Sehat Tanpa Narkoba\" — Kampanye antinarkoba untuk remaja.\n3. \"Buanglah Sampah pada Tempatnya\" — Menjaga kebersihan lingkungan sekolah.\n4. \"Mari Membaca\" — Mengajak siswa gemar membaca buku.\n5. \"Hemat Energi, Selamatkan Bumi\" — Kampanye penghematan listrik dan air.\n\nTugasmu adalah menuliskan DESKRIPSI poster (bukan menggambar) yang mencakup:\n\n1. TEMA — Tema yang kamu pilih dan target audiens (pelajar SD/SMP/SMA/umum).\n2. JUDUL — Pesan utama poster, maksimal 7 kata. Gunakan font besar dan mencolok.\n3. GAMBAR — Deskripsikan gambar/ilustrasi yang akan kamu gunakan: objek apa, warna dominan, suasana, posisi. Minimal 3 kalimat deskripsi visual.\n4. PESAN — Teks pendukung yang menjelaskan judul. Bisa berupa data, fakta, atau imbauan singkat.\n5. AJAKAN — Kalimat persuasif yang mendorong tindakan, menggunakan kata ayo, mari, atau jangan.\n6. SLOGAN — Buat slogan pendek (3–7 kata) yang menyertai poster, dengan rima atau irama yang menarik.\n7. IDENTITAS — Siapa pembuat atau sponsor poster.\n\nTulis deskripsi postermu secara rinci di kolom di bawah ini!",
    tips: [
      "Visual adalah RAJA poster. Gambar yang kuat bisa menyampaikan pesan lebih cepat daripada seribu kata. Deskripsikan gambar yang ikonik dan mudah diingat.",
      "Gunakan kata-kata imperatif dan persuasif di judul dan ajakan: 'Ayo!', 'Jangan!', 'Mulai!', 'Hentikan!' — ini mendorong tindakan segera.",
      "Buat slogan yang berima: 'Bersatu Kita Teguh, Bercerai Kita Runtuh', 'Muda Berprestasi, Bangga Berkarya'. Rima membuat slogan mudah diingat.",
      "Pertimbangkan target audiens: untuk anak SD gunakan bahasa sederhana dan warna cerah. Untuk remaja, desain lebih modern dan kata-kata gaul. Untuk umum, visual universal.",
      "Jangan terlalu banyak teks! Poster harus dipahami dalam 3–5 detik. Jika pembaca butuh waktu lebih dari 5 detik untuk mengerti pesanmu, postermu terlalu rumit.",
      "Pilih kombinasi warna yang kontras dan mudah terbaca dari jarak jauh. Warna teks harus kontras dengan latar belakang.",
      "Sertakan elemen kejutan atau emosi: gambar yang mengharukan, mengejutkan, atau menggelitik akan lebih diingat audiens.",
      "Cek tata letak: judul di bagian atas (terbaca duluan), gambar di tengah (daya tarik), pesan dan ajakan di bagian bawah.",
    ],
    contoh: "TEMA: Cinta Bahasa Indonesia — Target: Siswa SMP\n\nJUDUL: \"BANGGA BERBAHASA INDONESIA!\" (font tebal warna merah marun, ukuran besar di bagian atas poster)\n\nGAMBAR: Ilustrasi sekelompok remaja berdiri melingkar dengan latar belakang bendera Merah Putih yang berkibar. Setiap remaja memegang buku atau ponsel dengan senyum ceria. Di atas kepala mereka, terdapat gelembung dialog berisi kata-kata khas bahasa Indonesia seperti 'Menarik!', 'Keren!', dan 'Asyik!' dengan gaya komik. Warna dominan: merah, putih, dan biru laut. Gaya ilustrasi flat vector modern dengan outline tebal biar terlihat vibrant.\n\nPESAN: \"Yuk gunakan bahasa Indonesia yang baik dan benar di kehidupan sehari-hari! Di era digital, bahasa Indonesia tetap keren dan relevan. Jangan malu berbahasa Indonesia!\"\n\nAJAKAN: \"Ayo lestarikan bahasa Indonesia! Mulai dari percakapan sehari-hari, tugas sekolah, hingga media sosial!\"\n\nSLOGAN: \"Bahasa Indonesia — Sayang Bangsa, Bangga Bahasa!\" (rima: bangsa-bahasa, 5 kata, mudah diingat)\n\nIDENTITAS: Diselenggarakan oleh OSIS SMP Nusantara dalam rangka Bulan Bahasa Oktober 2026.",
  },

  kuis: makeSoal([
    ["Perbedaan utama antara iklan dan slogan terletak pada...", ["Iklan lebih panjang dari slogan", "Iklan memiliki media penyebaran dan bertujuan membujuk, slogan adalah frasa pendek sebagai identitas", "Iklan hanya di TV, slogan hanya di poster", "Iklan dibuat perusahaan, slogan dibuat pemerintah"], 1, "Iklan adalah pesan persuasif melalui media massa. Slogan adalah frasa pendek sebagai identitas/motto. Iklan membujuk, slogan melekat di ingatan."],
    ["Cermati teks berikut: 'Dapatkan sepatu limited edition ini! Hanya 100 pasang di Indonesia! Klik link di bio sekarang juga!' Bagian tersebut adalah...", ["Slogan", "Poster", "Iklan komersial", "Iklan layanan masyarakat"], 2, "Teks tersebut mengandung promosi produk (sepatu), CTA (Klik link), dan menciptakan urgensi (limited edition, hanya 100 pasang) — ciri khas iklan komersial."],
    ["Fungsi utama gambar dalam poster adalah...", ["Menghias agar poster terlihat indah", "Menyampaikan pesan secara visual dan menarik perhatian dalam sekali pandang", "Menggantikan teks sepenuhnya", "Menunjukkan logo perusahaan"], 1, "Gambar dalam poster berfungsi sebagai daya tarik visual utama dan menyampaikan pesan secara cepat tanpa harus membaca teks panjang."],
    ["Kalimat 'Bersih, Wangi, dan Lembut — itulah kulitmu setelah memakai Sabun X' menggunakan kaidah kebahasaan...", ["Kalimat imperatif", "Rima dan irama", "Kalimat interogatif", "Kata superlatif"], 1, "Terdapat rima pada 'bersih, wangi, lembut' (tiga kata bersuku akhir bunyi vokal 'i') yang menciptakan irama enak didengar."],
    ["Seorang siswa membuat slogan: 'Produk pembersih lantai ini mengandung bahan aktif pembersih yang efektif mengangkat kotoran membandel dan noda minyak.' Slogan tersebut tidak efektif karena...", ["Terlalu panjang dan tidak ringkas (lebih dari 7 kata)", "Tidak menggunakan bahasa Indonesia", "Tidak sesuai EYD", "Tidak ada gambar"], 0, "Slogan idealnya 3–7 kata. Slogan tersebut 14 kata — terlalu panjang, tidak mudah diingat. Slogan efektif: 'Bersih Maksimal, Noda Hilang!'"],
    ["'Jangan buang sampah di sungai!' Jika kalimat ini diubah menjadi iklan layanan masyarakat yang lengkap, harus ditambahkan...", ["Harga produk", "[Media penyebaran + visual + identitas pembuat]", "Alamat toko", "Testimoni selebriti"], 1, "Iklan layanan masyarakat yang lengkap butuh media penyebaran (poster/video/dll), visual pendukung, dan identitas pembuat/sponsor."],
    ["Dalam iklan baris, ciri khas yang membedakannya dari iklan display adalah...", ["Menggunakan gambar berwarna", "Berbayar per baris, tanpa gambar, teks singkat", "Dipasang di televisi", "Berisi cerita panjang"], 1, "Iklan baris berbayar per baris, tanpa gambar atau warna, teks sangat singkat dan padat informasi. Biasanya di koran cetak."],
    ["Prinsip AIDA dalam iklan tahap 'Desire' berarti...", ["Audiens memperhatikan iklan", "Audiens merasa tertarik pada produk", "Audiens mulai menginginkan/membutuhkan produk", "Audiens melakukan pembelian"], 2, "Desire adalah tahap ketiga AIDA di mana audiens mulai merasa 'aku ingin/membutuhkan produk ini', bukan sekadar tertarik."],
    ["Seorang guru meminta siswa membuat poster. Siswa A membuat poster dengan gambar besar dan 3 kata saja. Siswa B membuat poster penuh teks 50 kata tanpa gambar. Poster yang lebih efektif adalah...", ["Siswa A — karena poster harus visual dan mudah dipahami 3–5 detik", "Siswa B — karena informasinya lengkap", "Sama-sama efektif", "Tidak bisa dinilai"], 0, "Poster harus dipahami dalam 3–5 detik. Poster A: gambar besar + 3 kata = langsung paham. Poster B: 50 kata tanpa gambar = butuh waktu baca, bukan poster ideal."],
    ["'Mari Membaca — Buku adalah Jendela Dunia' termasuk jenis...", ["Iklan komersial", "Poster + slogan", "Iklan baris", "Iklan display digital"], 1, "'Mari Membaca' adalah ajakan (poster/iklan), 'Buku adalah Jendela Dunia' adalah slogan. Keduanya menyatu dalam satu media — contoh poster literasi dengan slogan."],
  ]),
}

export default konten
