import type { Konten } from "../types"
import { makeSoal } from "../types"

const konten: Konten = {
  belajar: {
    tujuan: [
      "Memahami pengertian, tujuan, dan ciri-ciri teks eksposisi",
      "Mengidentifikasi struktur teks eksposisi: tesis, argumen, penegasan ulang",
      "Menganalisis kaidah kebahasaan teks eksposisi: kalimat deklaratif, konjungsi kausal, istilah teknis",
      "Membedakan jenis-jenis teks eksposisi dan fungsinya dalam penyampaian informasi",
      "Menulis teks eksposisi yang logis, objektif, dan meyakinkan berdasarkan data dan fakta",
    ],
    materi: [
      {
        judul: "Apa Itu Teks Eksposisi?",
        isi: [
          "Pernahkah kamu membaca artikel tentang manfaat olahraga, bahaya merokok, atau dampak media sosial? Artikel-artikel seperti itu termasuk teks eksposisi — teks yang bertujuan MENJELASKAN informasi atau pengetahuan secara logis dan objektif kepada pembaca.",
          "",
"Teks eksposisi adalah teks nonfiksi yang memaparkan penjelasan tentang suatu topik dengan didukung data, fakta, dan alasan yang logis. Kata eksposisi berasal dari bahasa Latin exposition yang berarti 'memaparkan' atau 'menjelaskan'. Penulis teks eksposisi tidak sekadar menyampaikan informasi, tetapi juga berusaha membuat pembaca MEMAHAMI topik yang dibahas.",
"",
"[Ilustrasi: Seorang siswa berdiri di depan kelas memegang poster 'MANFAAT OLAHRAGA' dengan 3 argumen: (1) Jantung sehat — (2) Otak cerdas — (3) Tidur nyenyak. Grafik batang di samping menunjukkan data 80% siswa aktif lebih sehat.]",
"",
"• Tujuan teks eksposisi:",
          "  • Memberi tahu pembaca tentang suatu topik secara mendalam",
          "  • Menjelaskan informasi atau pengetahuan dengan logis dan sistematis",
          "  • Meyakinkan pembaca melalui data dan fakta yang objektif",
          "  • Menambah wawasan dan pemahaman pembaca terhadap suatu isu",
          "",
          "• Ciri-ciri umum teks eksposisi:",
          "  • Bersifat INFORMATIF — memberikan pengetahuan baru kepada pembaca",
          "  • LOGIS — penjelasan masuk akal dan dapat diterima nalar",
          "  • OBJEKTIF — tidak memihak, berdasarkan fakta dan data, bukan opini pribadi",
          "  • Menggunakan DATA dan FAKTA sebagai pendukung argumen",
          "  • Menggunakan BAHASA BAKU dan istilah teknis sesuai topik",
          "  • Bersifat NONFIKSI — informasi yang disampaikan nyata dan dapat diverifikasi",
          "  • Gaya bahasa lugas, langsung, dan tidak berlebihan",
          "",
          "PENTING: Teks eksposisi berbeda dengan teks persuasi! Eksposisi FOKUS pada PENYAMPAIAN INFORMASI secara objektif, sedangkan persuasi FOKUS pada MENGAJAK/MEMENGARUHI pembaca. Eksposisi memberitahu, persuasi membujuk. Meski sama-sama menyertakan data, tujuan akhirnya berbeda.",
        ],
        contoh: [
          "Contoh teks eksposisi (fokus informasi):",
          "\"Olahraga teratur memberikan banyak manfaat bagi kesehatan fisik dan mental. Menurut penelitian yang diterbitkan dalam Journal of Sport and Health (2022), olahraga selama 30 menit setiap hari dapat menurunkan risiko penyakit jantung hingga 35%. Selain itu, olahraga juga merangsang produksi endorfin — hormon yang menimbulkan perasaan bahagia dan mengurangi stres. Data dari Kementerian Kesehatan menunjukkan bahwa masyarakat yang berolahraga rutin memiliki tingkat produktivitas 25% lebih tinggi dibandingkan yang tidak.\"",
          "",
          "Bandingkan dengan teks persuasi (fokus ajakan):",
          "\"Ayo, berolahragalah! Jangan biarkan tubuhmu malas bergerak. Mulai hari ini, luangkan waktu 30 menit untuk berjalan kaki, bersepeda, atau berlari. Kesehatanmu ada di tanganmu sendiri. Jangan tunggu sakit baru sadar pentingnya olahraga!\"",
          "",
          "BENAR: Teks eksposisi menyajikan data penelitian (35%, 25%) dan sumber (Journal of Sport and Health, Kemenkes).",
          "SALAH: Teks eksposisi yang hanya berisi opini tanpa data pendukung, seperti 'Olahraga itu penting banget menurutku karena bikin sehat.'",
        ],
        catatan: "Mudah membedakan? Cek TUJUAN AKHIRNYA: kalau tujuannya membuat pembaca TAHU dan PAHAM → eksposisi. Kalau tujuannya membuat pembaca MELAKUKAN atau PERCAYA → persuasi. Keduanya bisa pakai data, tapi 'hati' dari eksposisi adalah informasi, sedangkan 'hati' persuasi adalah ajakan.",
      },
      {
        judul: "Struktur Teks Eksposisi",
        isi: [
          "Setiap teks eksposisi yang baik memiliki struktur yang jelas. Ada tiga bagian utama yang wajib kamu pahami: TESIS, ARGUMEN, dan PENEGASAN ULANG. Mari kita bedah satu per satu!",
          "",
          "1. TESIS (PERNYATAAN PENDAPAT) — Bagian pembuka yang berisi pernyataan atau pendapat penulis tentang topik yang akan dibahas. Tesis menjawab pertanyaan: apa yang akan dijelaskan?",
          "  • Letaknya di awal paragraf atau paragraf pertama",
          "  • Berisi posisi penulis terhadap topik",
          "  • Ditulis dengan kalimat deklaratif yang jelas",
          "  ✓ \"Media sosial memiliki dampak positif dan negatif terhadap perkembangan remaja.\"",
          "  ✓ \"Bahaya merokok bagi kesehatan sudah tidak dapat disangkal lagi.\"",
          "  ✗ Langsung ke data tanpa pernyataan pembuka",
          "",
          "2. ARGUMEN (ALASAN DAN DATA PENDUKUNG) — Bagian inti yang berisi alasan, data, fakta, dan bukti untuk mendukung tesis. Inilah 'daging' dari teks eksposisi.",
          "  • Bisa terdiri dari beberapa paragraf, masing-masing dengan satu ide pokok",
          "  • Disertai data konkret: angka, hasil penelitian, kutipan ahli, contoh nyata",
          "  • Menggunakan konjungsi kausal (sebab, karena, oleh karena itu) dan argumentatif (dengan demikian, maka dari itu)",
          "  • Bersifat logis — satu argumen mendukung argumen lainnya",
          "  ✓ \"Berdasarkan data Riset Kesehatan Dasar 2023, prevalensi perokok pemula di Indonesia mencapai 9,1% — meningkat 2% dibandingkan tahun sebelumnya. Hal ini disebabkan oleh maraknya iklan rokok yang menargetkan remaja.\"",
          "  ✗ Argumen tanpa data: \"Merokok itu jelas buruk karena tidak baik.\" (tidak ada data pendukung)",
          "",
          "3. PENEGASAN ULANG (SIMPULAN) — Bagian penutup yang merangkum dan menegaskan kembali tesis dengan cara berbeda. Tidak boleh menambahkan informasi baru.",
          "  • Merupakan simpulan dari argumen yang sudah disampaikan",
          "  • Menegaskan kembali posisi penulis",
          "  • Ditulis dengan kalimat yang meyakinkan",
          "  ✓ \"Dari berbagai data dan fakta yang telah dipaparkan, jelas bahwa merokok membawa dampak buruk yang serius bagi kesehatan. Oleh karena itu, upaya pencegahan merokok pada remaja harus terus digencarkan.\"",
          "  ✗ \"Jadi, merokok itu nggak baik.\" (terlalu singkat dan tidak menegaskan kembali argumen)",
          "",
          "Tips mengingat: T-A-P (Tesis, Argumen, Penegasan). Bayangkan seperti MEMBANGUN RUMAH: tesis adalah fondasinya (pernyataan awal), argumen adalah dinding dan tiangnya (data dan fakta), penegasan ulang adalah atapnya (simpulan yang mengikat semuanya).",
"",
"[Ilustrasi: Diagram alur piramida dari atas ke bawah: TESIS (pernyataan pendapat) → ARGUMEN 1 (alasan + data) → ARGUMEN 2 (fakta pendukung) → ARGUMEN 3 (contoh konkret) → PENEGASAN ULANG (simpulan). Masing-masing dengan ikon: bintang, centang, grafik, kotak centang.]",
        ],
        contoh: [
          "BENAR (struktur lengkap):",
          "Tesis: \"Kegiatan membaca buku memiliki peran yang sangat penting dalam meningkatkan kualitas sumber daya manusia Indonesia.\"",
          "Argumen 1: \"Berdasarkan data UNESCO 2023, indeks literasi Indonesia berada di angka 0,001 — artinya dari 1.000 penduduk, hanya 1 orang yang memiliki minat baca tinggi. Ini jauh tertinggal dibandingkan negara tetangga seperti Malaysia dan Singapura.\"",
          "Argumen 2: \"Penelitian dari Central Connecticut State University (2021) menempatkan Indonesia di peringkat ke-60 dari 61 negara dalam hal minat baca. Ironisnya, Indonesia justru masuk dalam 10 besar negara dengan pengguna smartphone terbanyak di dunia.\"",
          "Argumen 3: \"Rendahnya minat baca berdampak langsung pada kualitas pendidikan. Data PISA 2022 menunjukkan skor membaca siswa Indonesia hanya 371 — di bawah rata-rata OECD yang mencapai 487.\"",
          "Penegasan Ulang: \"Berdasarkan data-data di atas, dapat disimpulkan bahwa kondisi literasi Indonesia masih memprihatinkan dan memerlukan intervensi serius dari berbagai pihak. Meningkatkan budaya membaca sejak dini adalah investasi jangka panjang yang tidak bisa ditunda lagi.\"",
          "",
          "SALAH (struktur tidak lengkap): \"Membaca itu penting. Banyak orang Indonesia malas baca. Data bilang literasi kita rendah. Pokoknya kita harus rajin baca.\" (Tidak ada tesis yang jelas, argumen tanpa sumber data spesifik, penegasan ulang terlalu sederhana.)",
        ],
        catatan: "Penegasan ulang BUKAN sekedar mengulang tesis kata demi kata. Tulis ulang dengan BAHASA YANG BERBEDA tetapi menyampaikan inti yang sama. Contoh: Tesis 'Olahraga penting' → Penegasan 'Dari berbagai bukti ilmiah, aktivitas fisik rutin adalah kunci hidup sehat.'",
      },
      {
        judul: "Jenis-Jenis Teks Eksposisi",
        isi: [
          "Teks eksposisi memiliki beragam jenis, masing-masing dengan cara penyampaian yang berbeda. Yuk, kenali sembilan jenis utama berikut!",
          "",
          "1. EKSPOSISI DEFINISI — Memaparkan pengertian atau definisi suatu topik secara rinci. Biasanya dimulai dengan kalimat definisi (adalah, merupakan).",
          "  Contoh: Eksposisi tentang pengertian demokrasi, definisi pendidikan karakter, arti literasi digital.",
          "  ✓ \"Demokrasi adalah sistem pemerintahan di mana kekuasaan tertinggi berada di tangan rakyat dan dijalankan secara langsung atau melalui perwakilan.\"",
          "",
          "2. EKSPOSISI ILUSTRASI — Menjelaskan topik dengan memberikan gambaran atau contoh konkret agar pembaca lebih mudah memahami.",
          "  Contoh: Menjelaskan inflasi dengan ilustrasi harga bakso yang naik dari Rp10.000 menjadi Rp15.000 dalam setahun.",
          "  ✓ \"Untuk memahami inflasi, bayangkan harga sepiring bakso di kantin sekolahmu. Tahun lalu harganya Rp10.000. Sekarang menjadi Rp15.000. Kenaikan harga inilah yang disebut inflasi.\"",
          "",
          "3. EKSPOSISI PERBANDINGAN — Menjelaskan topik dengan membandingkan dua hal atau lebih untuk menunjukkan persamaan dan perbedaan.",
          "  Contoh: Membandingkan sistem pendidikan Indonesia dengan Finlandia, perbedaan kurikulum merdeka dan kurikulum 2013.",
          "  ✓ \"Berbeda dengan sistem pendidikan Finlandia yang memberikan kebebasan penuh pada siswa, sistem pendidikan Indonesia masih berfokus pada pencapaian nilai ujian nasional.\"",
          "",
          "4. EKSPOSISI PERTENTANGAN — Menjelaskan topik dengan menyajikan dua sisi yang bertentangan atau berlawanan.",
          "  Contoh: Pro dan kontra pembelajaran jarak jauh, kelebihan dan kekurangan media sosial.",
          "  ✓ \"Di satu sisi, pembelajaran jarak jauh memberikan fleksibilitas waktu dan tempat. Di sisi lain, metode ini menyebabkan kesenjangan akses internet bagi siswa di daerah terpencil.\"",
          "",
          "5. EKSPOSISI KLASIFIKASI — Menjelaskan topik dengan mengelompokkan sesuatu berdasarkan kategori atau jenis.",
          "  Contoh: Jenis-jenis sampah, klasifikasi makhluk hidup, macam-macam gaya belajar.",
          "  ✓ \"Berdasarkan sumbernya, sampah terbagi menjadi sampah organik (sisa makanan, daun) dan sampah anorganik (plastik, kaca, logam).\"",
          "",
          "6. EKSPOSISI PROSES — Menjelaskan tahapan atau cara kerja sesuatu secara berurutan. Mirip teks prosedur, tapi fokusnya pada PENJELASAN, bukan panduan.",
          "  Contoh: Bagaimana proses fotosintesis terjadi, bagaimana vaksin bekerja dalam tubuh.",
          "  ✓ \"Proses fotosintesis dimulai ketika klorofil di daun menangkap sinar matahari. Energi cahaya ini kemudian digunakan untuk mengubah air dan karbon dioksida menjadi glukosa dan oksigen.\"",
          "",
          "7. EKSPOSISI LAPORAN — Menyajikan laporan tentang suatu peristiwa, objek, atau penelitian. Mirip LHO tetapi bisa lebih luas.",
          "  Contoh: Laporan kegiatan ekstrakurikuler, hasil penelitian sederhana, laporan kunjungan wisata.",
          "  ✓ \"Kegiatan bakti sosial yang dilaksanakan pada 12 Januari 2024 di Panti Asuhan Harapan Kami diikuti oleh 45 siswa dan 5 guru pendamping. Donasi yang terkumpul berupa 100 kg beras, 50 liter minyak goreng, dan 75 paket alat tulis.\"",
          "",
          "8. EKSPOSISI ANALITIS — Menjelaskan topik dengan mengurai suatu masalah menjadi bagian-bagian kecil lalu menganalisis hubungan antarbagian.",
          "  Contoh: Analisis penyebab kemacetan di kota besar, analisis faktor-faktor yang memengaruhi prestasi belajar.",
          "  ✓ \"Kemacetan di Jakarta disebabkan oleh tiga faktor utama: pertama, jumlah kendaraan pribadi yang mencapai 22 juta unit; kedua, rendahnya tingkat penggunaan transportasi umum (hanya 24%); ketiga, infrastruktur jalan yang tidak seimbang dengan pertumbuhan kendaraan.\"",
          "",
          "9. EKSPOSISI PERSUASIF (HIMBAUAN) — Menjelaskan topik dengan tujuan akhir mengimbau atau menyarankan pembaca melakukan sesuatu. Perbatasan antara eksposisi dan persuasi.",
          "  Contoh: Eksposisi tentang pentingnya vaksinasi yang diakhiri dengan imbauan untuk vaksin.",
          "  ✓ 'Berdasarkan data dan fakta yang telah dipaparkan, vaksinasi terbukti aman dan efektif menurunkan risiko infeksi berat. Oleh karena itu, masyarakat diimbau untuk segera melengkapi vaksinasinya.'",
          "",
          "PENTING: Satu teks eksposisi bisa menggabungkan BEBERAPA jenis sekaligus. Misalnya: eksposisi tentang sampah bisa menggunakan definisi (apa itu sampah) + klasifikasi (jenis sampah) + analitis (dampak sampah). Tidak harus satu jenis saja!",
        ],
        contoh: [
          "BENAR: Eksposisi klasifikasi + ilustrasi — \"Berdasarkan dampaknya terhadap kesehatan, sampah plastik dapat diklasifikasikan menjadi dua kategori. Mikroplastik — partikel plastik berukuran <5 mm — dapat masuk ke dalam rantai makanan manusia melalui ikan yang kita konsumsi. Untuk membayangkannya, setiap minggu kita diperkirakan menelan mikroplastik seberat satu kartu kredit!\"",
          "BENAR: Eksposisi perbandingan — \"Transportasi umum di Singapura mencakup 80% mobilitas warganya, sedangkan di Jakarta hanya 24%. Perbedaan ini bukan tanpa sebab — Singapura memiliki integrasi antarmoda yang baik, sementara Jakarta masih bergulat dengan tumpang tindih rute antartransportasi umum.\"",
        ],
        catatan: "Tips memilih jenis eksposisi: Sesuaikan dengan TUJUAN dan TOPIK-mu. Ingin menjelaskan pengertian? Pakai definisi. Ingin menunjukkan perbedaan? Pakai perbandingan. Ingin mengurai masalah kompleks? Pakai analitis. Pilih jenis yang paling efektif menyampaikan pesanmu!",
      },
      {
        judul: "Kaidah Kebahasaan Teks Eksposisi",
        isi: [
          "Teks eksposisi memiliki ciri bahasa yang khas, yang membedakannya dari jenis teks lain. Kuasai kaidah ini agar tulisan eksposisimu berbobot dan profesional!",
          "",
          "1. KALIMAT DEKLARATIF — Kalimat pernyataan yang menyampaikan fakta atau pendapat. Ini adalah jenis kalimat PALING DOMINAN dalam teks eksposisi.",
          "  ✓ \"Polusi udara di Jakarta mencapai level tidak sehat pada musim kemarau.\"",
          "  ✓ \"Menurut WHO, 99% populasi dunia menghirup udara yang melebihi batas aman.\"",
          "  ✗ Kalimat tanya atau seruan dominan: 'Mengapa polusi berbahaya? Ayo lawan polusi!' (ini persuasi)",
          "",
          "2. KONJUNGSI KAUSAL — Kata hubung yang menyatakan hubungan sebab-akibat. Sangat penting untuk menghubungkan argumen dengan bukti.",
          "  Contoh: sebab, karena, oleh karena itu, akibatnya, dengan demikian, maka dari itu, sehingga, oleh sebab itu",
          "  ✓ \"Tingkat literasi Indonesia rendah karena minimnya akses buku berkualitas di daerah terpencil.\"",
          "  ✓ \"Penggunaan gawai berlebihan dapat mengganggu pola tidur. Oleh karena itu, batasi waktu bermain gawai sebelum tidur.\"",
          "",
          "3. KONJUNGSI ARGUMENTATIF — Kata hubung yang memperkuat argumen atau menunjukkan hubungan logis antarkalimat.",
          "  Contoh: dengan demikian, maka dari itu, berdasarkan hal tersebut, dengan kata lain, pada dasarnya.",
          "  ✓ \"Data menunjukkan bahwa 70% siswa lebih suka belajar melalui video daripada teks. Dengan demikian, penggunaan media pembelajaran audiovisual perlu ditingkatkan.\"",
          "",
          "4. KATA RUJUKAN — Kata yang merujuk pada data, penelitian, atau pernyataan yang sudah disebutkan sebelumnya.",
          "  Contoh: data tersebut, penelitian itu, pernyataan di atas, hal ini, berdasarkan temuan tersebut.",
          "  ✓ \"Data tersebut sejalan dengan penelitian yang dilakukan oleh Universitas Indonesia pada tahun 2023.\"",
          "  ✓ \"Hal ini menunjukkan bahwa kesenjangan digital masih menjadi tantangan utama.\"",
          "",
          "5. ISTILAH TEKNIS — Kata atau frasa khusus yang berkaitan dengan topik yang dibahas. Menunjukkan bahwa penulis menguasai bidangnya.",
          "  • Topik kesehatan: kardiovaskular, metabolisme, kolesterol, hipertensi, endorfin",
          "  • Topik lingkungan: deforestasi, polutan, emisi karbon, ekosistem, biodiversitas",
          "  • Topik pendidikan: literasi, kurikulum, pedagogi, asesmen, kompetensi",
          "  • Topik teknologi: algoritma, kecerdasan buatan, big data, enkripsi, bandwidth",
          "",
          "6. KATA KERJA MENTAL — Kata kerja yang berkaitan dengan proses berpikir, keyakinan, dan perkiraan. Memberikan nuansa analitis.",
          "  Contoh: diyakini, diperkirakan, diasumsikan, disimpulkan, dianggap, dipandang",
          "  ✓ \"Diperkirakan bahwa jumlah pengguna internet di Indonesia akan mencapai 250 juta jiwa pada tahun 2026.\"",
          "  ✓ \"Disimpulkan bahwa faktor lingkungan memiliki pengaruh signifikan terhadap prestasi belajar siswa.\"",
          "",
          "7. KATA PENEGAS — Kata yang menekankan atau mempertegas suatu pernyataan.",
          "  Contoh: tentu, pasti, sesungguhnya, sebenarnya, terutama, khususnya",
          "  ✓ \"Tentu saja perubahan iklim bukanlah isapan jempol belaka. Dampaknya sudah dirasakan di seluruh dunia.\"",
          "  ✓ \" terutama di daerah perkotaan, polusi udara menjadi masalah yang semakin mendesak.\"",
          "",
          "Tips praktis: Saat menulis eksposisi, baca ulang dan tanyakan: APAKAH SETIAP KALIMAT MENDUKUNG TOPIK UTAMAKU? Buang kalimat yang tidak relevan, tambahkan data yang memperkuat argumen. Eksposisi yang baik ibarat rantai — tidak ada satu pun mata rantai yang putus!",
        ],
        contoh: [
          "Perhatikan kaidah kebahasaan dalam teks eksposisi berikut:",
          "",
          "\"Bahaya Rokok bagi Remaja\"",
          "",
          "Merokok adalah kebiasaan yang sangat berbahaya bagi kesehatan, terutama bagi remaja yang masih dalam masa pertumbuhan (kalimat deklaratif + kata penegas). Dalam sebatang rokok terkandung lebih dari 4.000 zat kimia berbahaya, termasuk nikotin, tar, dan karbon monoksida (istilah teknis).",
          "",
          "Berdasarkan data Riset Kesehatan Dasar (Riskesdas) 2023, prevalensi perokok remaja usia 10—18 tahun mengalami peningkatan dari 7,2% menjadi 9,1% (istilah teknis). Diperkirakan jumlah ini akan terus bertambah jika tidak ada intervensi serius dari pemerintah (kata kerja mental). Maka dari itu, diperlukan kebijakan yang lebih ketat dalam pengaturan iklan dan penjualan rokok pada remaja (konjungsi argumentatif).",
          "",
          "Data tersebut diperkuat oleh penelitian dari Fakultas Kesehatan Masyarakat UI yang menemukan bahwa 60% perokok remaja membeli rokok secara eceran (kata rujukan). Hal ini menunjukkan bahwa kemudahan akses menjadi faktor utama tingginya angka perokok remaja (kata rujukan).",
          "",
          "BENAR: Menggunakan kalimat deklaratif, konjungsi kausal/argumentatif, istilah teknis, kata kerja mental, dan kata rujukan secara alami.",
          "SALAH: \"Merokok tuh bahaya banget lho guys. Ayo stop merokok!\" (Bahasa tidak baku, tidak ada data, terlalu persuasif, bukan eksposisi.)",
        ],
        catatan: "Jangan memaksakan semua kaidah kebahasaan dalam satu paragraf yang pendek. Gunakan secara alami sesuai kebutuhan. Tujuan utama tetaplah menyampaikan informasi dengan jelas, bukan memamerkan semua kaidah sekaligus. Yang terpenting: KALIMAT DEKLARATIF + DATA + LOGIS.",
      },
      {
        judul: "Tips Menulis Teks Eksposisi yang Efektif",
        isi: [
          "Menulis teks eksposisi yang baik adalah keterampilan yang bisa dipelajari. Ikuti panduan langkah demi langkah berikut!",
          "",
          "1. PILIH TOPIK YANG KAMU KUASAI",
          "  Pilih topik yang kamu pahami dan memiliki cukup data. Topik yang terlalu luas akan sulit dijelaskan secara mendalam. Persempit fokusmu!",
          "  ✓ Spesifik: 'Dampak Media Sosial terhadap Kesehatan Mental Remaja'",
          "  ✗ Terlalu luas: 'Media Sosial'",
          "",
          "2. KUMPULKAN DATA DAN FAKTA",
          "  Eksposisi tanpa data bagaikan sayur tanpa garam — hambar! Kumpulkan data dari sumber terpercaya: buku, jurnal ilmiah, artikel berita, situs resmi pemerintah.",
          "  • Catat sumber data: siapa yang meneliti? tahun berapa? di mana?",
          "  • Kumpulkan data kuantitatif (angka, persentase, statistik) dan kualitatif (kutipan ahli, contoh kasus)",
          "  • Minimal 3—5 data pendukung untuk teks eksposisi yang meyakinkan",
          "",
          "3. BUAT KERANGKA KARANGAN",
          "  Susun kerangka dengan struktur T-A-P (Tesis, Argumen, Penegasan). Tentukan poin utama setiap paragraf.",
          "  Kerangka contoh:",
          "  • Tesis: Pentingnya literasi digital bagi pelajar",
          "  • Argumen 1: Data tingkat literasi digital Indonesia (UNESCO, APJII)",
          "  • Argumen 2: Dampak rendahnya literasi digital (hoaks, penipuan online)",
          "  • Argumen 3: Manfaat literasi digital (produktivitas, perlindungan data)",
          "  • Penegasan Ulang: Simpulan dan rekomendasi",
          "",
          "4. KEMBANGKAN ARGUMEN DENGAN DATA",
          "  Setiap argumen harus didukung data. Polanya: TOPIK → DATA → PENJELASAN. Jangan hanya menyebut data tanpa menjelaskan maknanya.",
          "  ✓ 'Menurut survei We Are Social (2024), rata-rata remaja Indonesia menghabiskan 5,3 jam per hari di media sosial. Angka ini termasuk tertinggi di Asia Tenggara. Dampaknya adalah menurunnya konsentrasi belajar dan terganggunya pola tidur.'",
          "  ✗ 'Remaja Indonesia main HP 5 jam sehari. Itu kebanyakan.'",
          "",
          "5. GUNAKAN BAHASA BAKU DAN LUGAS",
          "  Hindari bahasa gaul, singkatan tidak resmi, atau kata-kata ambigu. Eksposisi bersifat FORMAL dan ILMIAH POPULER.",
          "  ✓ 'Penggunaan gawai secara berlebihan berdampak negatif pada kesehatan.'",
          "  ✗ 'Main HP kebanyakan jelek buat kesehatan.'",
          "",
          "6. AKHIRI DENGAN SIMPULAN YANG KUAT",
          "  Penegasan ulang harus meninggalkan kesan mendalam. Jangan sekadar mengulang tesis — tulis ulang dengan sudut pandang baru setelah mempertimbangkan argumen.",
          "  ✓ 'Maka jelaslah bahwa literasi digital bukan lagi pilihan, melainkan kebutuhan mendesak bagi generasi muda Indonesia di era informasi ini.'",
          "",
          "7. REVISI DAN EDIT",
          "  Baca ulang teksmu. Cek: apakah tesis jelas? Apakah setiap argumen didukung data? Apakah alurnya logis? Apakah ada kesalahan ejaan? Minta teman membaca untuk mendapatkan masukan.",
          "",
          "PENTING: Menulis eksposisi yang baik BUTUH PROSES. Jangan berharap langsung sempurna di draft pertama. Tulis dulu secara kasar, lalu perbaiki secara bertahap. Penulis hebat bukan yang tidak pernah salah, melainkan yang terus merevisi tulisannya!",
        ],
        contoh: [
          "BENAR (teks eksposisi efektif):",
          "Tesis: 'Penggunaan transportasi umum adalah solusi cerdas untuk mengatasi kemacetan dan polusi di kota-kota besar Indonesia.'",
          "",
          "Argumen 1: 'Berdasarkan data Kementerian Perhubungan 2023, jumlah kendaraan bermotor di Jakarta mencapai 22,5 juta unit — meningkat 5% setiap tahun. Sementara itu, kapasitas jalan hanya bertambah 0,01% per tahun. Ketimpangan ini menyebabkan kemacetan yang merugikan ekonomi hingga Rp100 triliun per tahun.'",
          "",
          "Argumen 2: 'Di sisi lain, transportasi umum seperti MRT Jakarta mampu mengangkut 100.000 penumpang per hari dan mengurangi emisi karbon hingga 30% dibandingkan kendaraan pribadi. Dengan demikian, setiap orang yang beralih ke transportasi umum berkontribusi pada penurunan polusi udara.'",
          "",
          "Argumen 3: 'Contoh keberhasilan dapat dilihat di Singapura, di mana 80% warganya menggunakan transportasi umum. Hasilnya, Singapura masuk dalam 10 besar negara dengan kualitas udara terbaik di Asia.'",
          "",
          "Penegasan Ulang: 'Berdasarkan data dan contoh di atas, transportasi umum terbukti mampu mengurangi kemacetan dan polusi secara signifikan. Sudah saatnya masyarakat Indonesia beralih ke transportasi umum demi masa depan kota yang lebih bersih dan manusiawi.'",
          "",
          "SALAH: 'Transportasi umum itu penting karena bisa mengurangi macet. Data bilang jalan nambahnya dikit. Maka dari itu, pake transportasi umum yuk.' (Tidak ada data spesifik, argumen dangkal, tidak dikembangkan.)",
        ],
        catatan: "Keterampilan menulis eksposisi akan sangat berguna di masa depan — untuk menulis esai, artikel, laporan penelitian, proposal, hingga konten blog. Mulailah berlatih dari topik-topik sederhana di sekitar kehidupanmu sehari-hari!",
      },
    ],
    rangkuman: [
      "Teks eksposisi adalah teks nonfiksi yang bertujuan menjelaskan informasi atau pengetahuan secara logis, objektif, dan didukung data/fakta.",
      "Struktur teks eksposisi terdiri dari tiga bagian: tesis (pernyataan pendapat), argumen (data dan fakta pendukung), dan penegasan ulang (simpulan yang menegaskan tesis).",
      "Ciri utama: informatif, logis, objektif, menggunakan bahasa baku, disertai data dan fakta, serta bersifat nonfiksi.",
      "Terdapat 9 jenis eksposisi: definisi, ilustrasi, perbandingan, pertentangan, klasifikasi, proses, laporan, analitis, dan persuasif.",
      "Kaidah kebahasaan meliputi: kalimat deklaratif, konjungsi kausal (sebab, karena, oleh karena itu), konjungsi argumentatif (dengan demikian, maka dari itu), kata rujukan, istilah teknis, kata kerja mental, dan kata penegas.",
      "Perbedaan dengan teks persuasi: eksposisi fokus menyampaikan informasi (memberi tahu), persuasi fokus mengajak/memengaruhi (membujuk).",
      "Tips menulis: pilih topik spesifik, kumpulkan data dari sumber terpercaya, buat kerangka T-A-P, kembangkan argumen dengan data plus penjelasan, gunakan bahasa baku, dan akhiri dengan simpulan kuat.",
      "Contoh topik eksposisi: pentingnya literasi digital, dampak media sosial, bahaya merokok, manfaat olahraga, polusi udara, transportasi umum, perubahan iklim, dan kebijakan pendidikan.",
    ],
  },

  latihan: makeSoal([
    // 5 Soal Pilihan Ganda
    ["Teks eksposisi bertujuan untuk...", ["Menghibur pembaca dengan cerita fiksi", "Menjelaskan informasi atau pengetahuan secara logis dan objektif", "Menggambarkan objek dengan kesan subjektif", "Memandu pembaca melakukan sesuatu langkah demi langkah"], 1, "Teks eksposisi bertujuan menjelaskan informasi secara logis, objektif, dan didukung data/fakta."],
    ["Berikut ini yang merupakan struktur teks eksposisi yang benar adalah...", ["Orientasi — komplikasi — resolusi", "Pernyataan umum — deskripsi bagian — simpulan", "Tesis — argumen — penegasan ulang", "Tujuan — bahan/alat — langkah-langkah"], 2, "Struktur teks eksposisi: tesis (pernyataan pendapat) → argumen (data/fakta) → penegasan ulang (simpulan)."],
    ["Kalimat 'Tingkat literasi Indonesia rendah karena minimnya akses buku di daerah terpencil' menggunakan konjungsi...", ["Temporal", "Argumentatif", "Kausal", "Koordinatif"], 2, "'Karena' adalah konjungsi kausal yang menyatakan hubungan sebab akibat. 'Karena minimnya akses buku' = sebab, 'literasi rendah' = akibat."],
    ["Cermati kalimat: 'Diperkirakan bahwa jumlah pengguna internet di Indonesia akan mencapai 250 juta jiwa pada tahun 2026.' Kata 'diperkirakan' termasuk jenis kata...", ["Kata kerja material", "Kata kerja mental", "Kata kerja pasif", "Kata kerja imperatif"], 1, "'Diperkirakan' adalah kata kerja mental — berkaitan dengan proses berpikir dan perkiraan. Kata kerja mental sering muncul dalam teks eksposisi."],
    ["Perbedaan utama teks eksposisi dengan teks persuasi adalah...", ["Eksposisi lebih panjang dari persuasi", "Eksposisi fokus informasi, persuasi fokus ajakan", "Eksposisi untuk lisan, persuasi untuk tulisan", "Eksposisi menggunakan gambar, persuasi tidak"], 1, "Eksposisi bertujuan MEMBERI TAHU (informasi), sedangkan persuasi bertujuan MENGAJAK/MEMENGARUHI pembaca untuk melakukan sesuatu."],

    // 3 Soal Betul/Salah
    ["Pernyataan: 'Teks eksposisi boleh menggunakan opini pribadi penulis selama argumennya didukung data.'", ["Betul", "Salah"], 0, "BETUL — meski bersifat objektif, eksposisi bisa berisi pendapat penulis (tesis), tetapi pendapat tersebut HARUS didukung data dan fakta yang valid."],
    ["Pernyataan: 'Eksposisi ilustrasi adalah jenis eksposisi yang menjelaskan topik dengan memberikan contoh konkret atau gambaran.'", ["Betul", "Salah"], 0, "BETUL. Eksposisi ilustrasi menggunakan contoh nyata atau gambaran agar pembaca lebih mudah memahami topik yang dijelaskan."],
    ["Pernyataan: 'Penegasan ulang dalam teks eksposisi boleh menambahkan informasi baru yang belum disebutkan di bagian argumen.'", ["Betul", "Salah"], 1, "SALAH. Penegasan ulang hanya merangkum dan menegaskan kembali tesis serta argumen yang sudah disampaikan. Tidak boleh ada informasi baru di bagian ini."],

    // 2 Soal Isian Singkat
    ["Bagian teks eksposisi yang berisi pernyataan pendapat penulis tentang topik yang akan dibahas disebut...", ["tesis", "argumen", "penegasan", "simpulan"], 0, "Tesis adalah pernyataan pendapat penulis yang menjadi dasar pembahasan dalam teks eksposisi. Letaknya di awal paragraf."],
    ["Konjungsi 'dengan demikian', 'maka dari itu', dan 'berdasarkan hal tersebut' termasuk jenis konjungsi...", ["argumentatif", "kausal", "temporal", "koordinatif"], 0, "Konjungsi argumentatif berfungsi memperkuat argumen atau menunjukkan hubungan logis antarkalimat dalam teks eksposisi."],
  ]),

  praktik: {
    petunjuk: "Buatlah teks eksposisi tentang salah satu topik berikut:\n\n1. Dampak Media Sosial terhadap Remaja\n2. Pentingnya Membaca Buku bagi Pelajar\n3. Manfaat Olahraga bagi Kesehatan Fisik dan Mental\n4. Bahaya Merokok bagi Kesehatan\n5. Transportasi Umum sebagai Solusi Kemacetan\n\nTeks eksposisimu harus mencakup:\n\n1. TESIS — Satu paragraf pembuka yang berisi pernyataan pendapatmu tentang topik. Jelaskan posisimu dengan jelas.\n2. ARGUMEN — Minimal 3 paragraf, masing-masing dengan:\n   • Satu ide pokok yang mendukung tesis\n   • Data atau fakta pendukung (bisa dari sumber yang kamu ketahui atau buat secara logis)\n   • Penjelasan yang menghubungkan data dengan argumen\n   • Konjungsi kausal atau argumentatif (sebab, karena, oleh karena itu, dengan demikian, maka dari itu)\n3. PENEGASAN ULANG — Satu paragraf penutup yang merangkum argumen dan menegaskan kembali tesis dengan bahasa yang berbeda.\n\nGunakan minimal 3 istilah teknis yang sesuai dengan topik, serta minimal 2 kata kerja mental (diyakini, diperkirakan, disimpulkan, dll.).\n\nTulis teks eksposisimu dengan rapi di kolom di bawah ini!",
    tips: [
      "Pilih topik yang paling kamu kuasai. Semakin paham topiknya, semakin mudah mengembangkan argumen dengan data dan contoh nyata.",
      "Mulai dengan tesis yang menarik perhatian. 'Media sosial bagaikan pisau bermata dua bagi remaja' — lebih menarik daripada 'Media sosial memiliki dampak positif dan negatif'.",
      "Gunakan data spesifik: angka, persentase, tahun penelitian, nama institusi. Data yang samar ('banyak penelitian mengatakan') mengurangi kredibilitas.",
      "Setiap paragraf argumen harus memiliki SATU ide pokok. Jika dalam satu paragraf ada dua ide berbeda, pisahkan menjadi dua paragraf.",
      "Hubungkan antargumen dengan konjungsi argumentatif: 'Selain itu...', 'Di sisi lain...', 'Dengan demikian...', 'Berdasarkan data tersebut...'.",
      "Akhiri penegasan ulang dengan kalimat yang berkesan dan meninggalkan dampak pada pembaca — bukan sekadar 'Jadi kesimpulannya...'.",
      "Baca ulang teksmu dan cek: apakah data yang kamu gunakan logis? Apakah setiap argumen jelas mendukung tesis? Apakah tidak ada kontradiksi antaragumen?",
    ],
    contoh: "Dampak Media Sosial terhadap Kesehatan Mental Remaja\n\nTesis:\nMedia sosial telah menjadi bagian tak terpisahkan dari kehidupan remaja modern. Namun, di balik kemudahan berkomunikasi dan akses informasi yang ditawarkan, media sosial menyimpan dampak serius terhadap kesehatan mental penggunanya, terutama remaja yang masih dalam masa perkembangan psikologis.\n\nArgumen 1:\nBerdasarkan survei yang dilakukan oleh Kementerian Komunikasi dan Informatika pada tahun 2023, rata-rata remaja Indonesia menghabiskan 5,3 jam per hari untuk mengakses media sosial. Angka ini menjadikan Indonesia sebagai salah satu negara dengan durasi penggunaan media sosial tertinggi di Asia Tenggara. Kebiasaan ini menyebabkan menurunnya kualitas tidur karena remaja cenderung membuka media sosial sebelum tidur dan segera setelah bangun. Padahal, gangguan pola tidur pada remaja dapat memicu gangguan konsentrasi, penurunan prestasi akademik, dan risiko gangguan kecemasan.\n\nArgumen 2:\nFenomena Fear of Missing Out (FoMO) — rasa takut ketinggalan — diperkuat oleh media sosial. Remaja terus-menerus melihat unggahan teman-temannya yang tampak bahagia, sukses, dan bersenang-senang. Diperkirakan bahwa 60% remaja yang aktif di media sosial mengalami kecemasan sosial akibat membandingkan kehidupan mereka dengan kehidupan orang lain yang terlihat 'sempurna' di layar. Dengan demikian, media sosial menciptakan standar hidup yang tidak realistis dan memicu perasaan tidak percaya diri.\n\nArgumen 3:\nDi sisi lain, media sosial juga memiliki dampak positif yang tidak bisa diabaikan. Platform seperti Instagram dan TikTok dapat menjadi sarana kreativitas dan ekspresi diri. Banyak remaja yang menemukan komunitas positif, belajar keterampilan baru, atau bahkan memulai usaha melalui media sosial. Oleh karena itu, dampak media sosial sangat bergantung pada CARA penggunaannya — apakah pasif (hanya scrolling tanpa tujuan) atau aktif (berkreasi dan berinteraksi secara bermakna).\n\nPenegasan Ulang:\nDari data dan fakta yang telah dipaparkan, jelas bahwa media sosial membawa dampak yang kompleks bagi kesehatan mental remaja. Di satu sisi, ia membuka peluang kreativitas dan koneksi sosial. Di sisi lain, ia menyimpan risiko FoMO, kecemasan, dan gangguan tidur. Kunci utamanya bukanlah menjauhi media sosial sepenuhnya, melainkan mengembangkan literasi digital dan kebiasaan penggunaan yang sehat. Orang tua dan pendidik memiliki peran penting dalam mendampingi remaja menggunakan media sosial secara bijak dan bertanggung jawab.",
  },

  kuis: makeSoal([
    ["Eksposisi berasal dari bahasa Latin exposition yang berarti...", ["Menceritakan kembali", "Memaparkan atau menjelaskan", "Mengajak atau membujuk", "Mendeskripsikan"], 1, "Exposition berarti memaparkan atau menjelaskan. Dari sinilah kata eksposisi dalam bahasa Indonesia berasal."],
    ["Cermati penggalan teks: 'Berdasarkan data Badan Pusat Statistik 2023, angka partisipasi sekolah di Indonesia mencapai 97,5% untuk tingkat SD, namun menurun drastis menjadi 72,3% untuk tingkat SMA.' Fungsi data tersebut dalam teks eksposisi adalah...", ["Memperindah tulisan", "Memperkuat argumen tentang partisipasi pendidikan", "Menggantikan opini penulis", "Sebagai hiasan agar teks panjang"], 1, "Data BPS digunakan untuk MEMPERKUAT ARGUMEN tentang kesenjangan partisipasi pendidikan antara tingkat SD dan SMA."],
    ["Mana dari berikut ini yang BUKAN merupakan jenis teks eksposisi?", ["Eksposisi definisi", "Eksposisi ilustrasi", "Eksposisi narasi", "Eksposisi perbandingan"], 2, "Eksposisi NARASI tidak termasuk jenis eksposisi. Yang termasuk: definisi, ilustrasi, perbandingan, pertentangan, klasifikasi, proses, laporan, analitis, dan persuasif."],
    ["Kalimat 'Oleh karena itu, kebijakan pengurangan sampah plastik perlu segera diterapkan' mengandung konjungsi...", ["Temporal", "Kausal", "Argumentatif", "Koordinatif"], 2, "'Oleh karena itu' termasuk konjungsi ARGUMENTATIF yang menunjukkan simpulan logis dari argumen sebelumnya."],
    ["Dalam teks eksposisi, bagian argumen berfungsi untuk...", ["Menarik perhatian pembaca", "Menyajikan data dan fakta yang mendukung tesis", "Memberikan kesimpulan akhir", "Menghibur pembaca"], 1, "Argumen adalah bagian INTI teks eksposisi yang berisi data, fakta, alasan, dan bukti untuk mendukung tesis penulis."],
    ["Seorang siswa menulis: 'Diyakini bahwa penggunaan pupuk kimia berlebihan dapat merusak struktur tanah dalam jangka panjang.' Kata 'diyakini' termasuk...", ["Kata kerja material", "Kata kerja mental", "Konjungsi argumentatif", "Istilah teknis"], 1, "'Diyakini' adalah kata kerja mental yang berkaitan dengan keyakinan dan proses berpikir. Sering muncul dalam teks eksposisi untuk menyatakan pendapat yang didukung data."],
    ["Bagian penegasan ulang dalam teks eksposisi boleh...", ["Menambahkan argumen baru", "Merangkum argumen yang sudah disampaikan", ["Memperkenalkan topik baru", "Mengubah posisi penulis"], 1], 1, "Penegasan ulang hanya merangkum dan menegaskan kembali argumen yang sudah disampaikan. Tidak boleh ada informasi atau topik baru."],
    ["Perbedaan paling mendasar antara eksposisi perbandingan dan eksposisi pertentangan adalah...", ["Eksposisi perbandingan menunjukkan persamaan dan perbedaan, pertentangan menunjukkan dua sisi berlawanan", "Eksposisi perbandingan lebih pendek", "Eksposisi pertentangan tidak pakai data", "Tidak ada perbedaan"], 0, "Eksposisi PERBANDINGAN membandingkan dua hal secara umum (persamaan dan perbedaan), sedangkan PERTENTANGAN fokus pada dua sisi yang saling bertolak belakang."],
    ["Kata rujukan yang tepat untuk menghubungkan kalimat dengan data yang telah disebutkan sebelumnya adalah...", ["Menurut saya", "Data tersebut", "Oleh karena itu", "Pertama-tama"], 1, "'Data tersebut' adalah kata rujukan yang merujuk pada data yang sudah disebutkan di kalimat sebelumnya. Kata rujukan menjaga koherensi teks eksposisi."],
    ["Seorang penulis ingin menjelaskan proses fotosintesis dengan cara menggambarkan langkah demi langkah. Jenis eksposisi yang paling tepat adalah...", ["Eksposisi definisi", "Eksposisi proses", "Eksposisi klasifikasi", "Eksposisi laporan"], 1, "Eksposisi PROSES menjelaskan tahapan atau cara kerja sesuatu secara berurutan — paling cocok untuk menjelaskan fotosintesis langkah demi langkah."],
  ]),
}

export default konten
