import type { Konten } from "../types"
import { makeSoal } from "../types"

const konten: Konten = {
  belajar: {
    tujuan: [
      "Memahami pengertian dan perbedaan buku fiksi dan nonfiksi secara mendalam",
      "Mengidentifikasi unsur-unsur intrinsik dan ekstrinsik buku fiksi serta unsur faktual buku nonfiksi",
      "Membedakan jenis-jenis buku fiksi (novel, cerpen, komik, puisi, drama, dongeng) dan nonfiksi (buku pelajaran, biografi, ensiklopedia, kamus, buku ilmiah)",
      "Menganalisis cara membedakan buku fiksi dan nonfiksi melalui sampul, sinopsis, gaya bahasa, dan sumber data",
      "Menulis resensi buku fiksi atau nonfiksi dengan struktur yang lengkap dan benar",
    ],
    materi: [
      {
        judul: "Apa Itu Buku Fiksi dan Nonfiksi?",
        isi: [
          "Coba lihat rak buku di perpustakaan sekolahmu! Ada novel 'Laskar Pelangi' karya Andrea Hirata yang mengharukan, ada juga buku 'Sejarah Indonesia' yang berisi fakta-fakta perjuangan bangsa. Keduanya adalah buku, tetapi sangat berbeda. Mengapa? Karena yang satu adalah FIKSI, yang lain adalah NONFIKSI!",
          "",
          "Buku FIKSI adalah buku yang berisi cerita rekaan atau imajinasi penulis. Buku fiksi dibuat untuk menghibur, menggugah perasaan, dan menyampaikan pesan melalui cerita. Meskipun terkadang terinspirasi dari kejadian nyata, buku fiksi TIDAK terikat pada fakta — penulis bebas berimajinasi!",
          "",
          "Buku NONFIKSI adalah buku yang berisi informasi faktual dan data yang dapat dipertanggungjawabkan. Buku nonfiksi dibuat untuk memberikan pengetahuan, wawasan, dan informasi yang akurat kepada pembaca. Setiap informasi dalam buku nonfiksi harus berdasarkan fakta, data, hasil penelitian, atau sumber yang terpercaya.",
          "",
          "PENTING: Perbedaan utama ada pada TUJUAN dan SUMBER. Fiksi bertujuan menghibur melalui cerita rekaan, nonfiksi bertujuan menginformasikan melalui fakta. Fiksi lahir dari imajinasi, nonfiksi lahir dari data dan penelitian!",
          "",
          "• Contoh Buku Fiksi:",
          "  • Laskar Pelangi (Andrea Hirata) — kisah perjuangan anak-anak Belitung bersekolah",
          "  • Bumi Manusia (Pramoedya Ananta Toer) — novel sejarah pergerakan nasional",
          "  • Harry Potter (J.K. Rowling) — petualangan penyihir remaja di sekolah sihir",
          "  • Dilan: Dia adalah Dilanku (Pidi Baiq) — kisah cinta remaja di Bandung tahun 1990",
          "  • Kumpulan cerpen 'Senyum Karyamin' (Ahmad Tohari)",
          "",
          "• Contoh Buku Nonfiksi:",
          "  • Buku Pelajaran: IPA Terpadu Kelas VII, Matematika SMP, Bahasa Indonesia",
          "  • Biografi: 'Soekarno: Biografi Singkat' atau 'Steve Jobs' (Walter Isaacson)",
          "  • Ensiklopedia: 'Ensiklopedia Sains', 'Ensiklopedia Sejarah dan Budaya'",
          "  • Buku Ilmiah: 'Sapiens' (Yuval Noah Harari), 'A Brief History of Time' (Stephen Hawking)",
"  • Jurnal akademik, laporan penelitian, kamus, dan buku panduan",
"",
"[Ilustrasi: Tumpukan buku dibagi dua: sisi kiri warna-warni (fiksi) dengan judul novel, cerpen, komik, dongeng — sisi kanan warna netral (nonfiksi) dengan judul 'Sejarah', 'Biografi', 'IPA', 'Kamus'. Di tengah timbangan seimbang.]",
],
contoh: [
          "Perhatikan perbedaan mendasar antara fiksi dan nonfiksi:",
          "",
          "FIKSI:",
          "Judul: 'Laskar Pelangi'",
          "Penulis: Andrea Hirata",
          "Isi: Kisah 10 anak dari Belitung yang berjuang mendapatkan pendidikan di tengah keterbatasan. Tokoh-tokoh seperti Ikal, Lintang, dan Mahar adalah REKAAN.",
          "Tujuan: Menghibur dan menginspirasi melalui cerita.",
          "Gaya bahasa: Puitis, kaya metafora, emosional.",
          "",
          "NONFIKSI:",
          "Judul: 'Sejarah Indonesia Kelas XI'",
          "Penulis: Tim Kemdikbud",
          "Isi: Fakta sejarah Proklamasi Kemerdekaan 17 Agustus 1945, tokoh-tokoh nyata (Soekarno, Hatta), didukung data tanggal, tempat, dan dokumen asli.",
          "Tujuan: Mendidik dan memberikan pengetahuan sejarah yang akurat.",
          "Gaya bahasa: Lugas, informatif, objektif.",
          "",
          "✓ Contoh kalimat FIKSI: \"Matahari pagi itu tersenyum ramah pada Ikal yang berjalan tanpa alas kaki ke sekolah.\" (Personifikasi, imajinatif, tidak faktual)",
          "✓ Contoh kalimat NONFIKSI: \"Proklamasi Kemerdekaan Indonesia dibacakan oleh Ir. Soekarno pada tanggal 17 Agustus 1945 pukul 10.00 WIB di Jalan Pegangsaan Timur No. 56, Jakarta.\" (Data faktual, dapat diverifikasi)",
        ],
        catatan: "Menariknya, ada juga buku yang disebut FIKSI SEJARAH — seperti novel 'Bumi Manusia' — yang menggunakan latar belakang sejarah nyata tetapi tokoh-tokohnya dan dialog-dialognya adalah rekaan. Jadi, buku ini tetap digolongkan sebagai FIKSI, bukan nonfiksi!",
      },
      {
        judul: "Unsur-Unsur dan Jenis Buku Fiksi",
        isi: [
          "Seperti tubuh manusia yang memiliki organ-organ, buku fiksi juga dibangun oleh unsur-unsur tertentu. Mari kenali unsur intrinsik dan ekstrinsik pada buku fiksi!",
          "",
          "UNSUR INTRINSIK FIKSI (Unsur dari Dalam Cerita):",
          "",
          "1. TEMA — Gagasan pokok yang mendasari cerita. Tema adalah 'jiwa' dari karya fiksi.",
          "  Contoh tema: persahabatan (Laskar Pelangi), perjuangan (Bumi Manusia), cinta (Dilan), petualangan (Harry Potter).",
          "",
          "2. TOKOH DAN PENOKOHAN — Pelaku dalam cerita beserta wataknya.",
          "  • Tokoh utama/protagonis: pusat cerita (contoh: Ikal, Minke, Harry Potter)",
          "  • Tokoh lawan/antagonis: penghalang tujuan tokoh utama",
          "  • Tokoh tambahan: mendukung jalan cerita",
          "",
          "3. ALUR (PLOT) — Rangkaian peristiwa yang membangun cerita dari awal hingga akhir.",
          "  Tahapan: orientasi → komplikasi → klimaks → resolusi → koda",
          "",
          "4. LATAR (SETTING) — Tempat, waktu, dan suasana terjadinya peristiwa.",
          "  ✓ Latar tempat: Belitung (Laskar Pelangi), Bandung (Dilan), London (Harry Potter)",
          "  ✓ Latar waktu: tahun 1970-an (Laskar Pelangi), tahun 1990 (Dilan)",
          "  ✓ Latar suasana: haru, tegang, romantis, misterius",
          "",
          "5. SUDUT PANDANG — Posisi pengarang dalam membawakan cerita.",
          "  Orang pertama ('Aku') atau orang ketiga ('Dia', 'Mereka')",
          "",
          "6. AMANAT — Pesan moral atau pelajaran yang ingin disampaikan penulis.",
          "",
          "7. GAYA BAHASA — Cara khas penulis dalam menggunakan bahasa. Misalnya, Andrea Hirata puitis dan kaya metafora, Pidi Baiq santai dan jenaka, Pramoedya lugas dan penuh semangat nasionalisme.",
          "",
          "UNSUR EKSTRINSIK FIKSI (Unsur dari Luar Cerita):",
          "  1. Latar belakang penulis: pengalaman hidup, pendidikan, profesi, dan pandangan dunia penulis.",
          "  2. Nilai sosial budaya: adat istiadat, tradisi, dan kondisi masyarakat yang tergambar dalam cerita.",
          "  3. Nilai moral: ajaran tentang baik-buruk yang terkandung dalam cerita.",
          "  4. Nilai agama: nilai-nilai keagamaan yang memengaruhi pandangan tokoh.",
          "  5. Kondisi sosial politik: situasi masyarakat pada saat cerita ditulis.",
          "",
          "JENIS-JENIS BUKU FIKSI:",
          "  1. NOVEL — Karangan fiksi panjang (50.000+ kata) dengan alur kompleks dan banyak tokoh. Contoh: Laskar Pelangi, Bumi Manusia, Harry Potter.",
          "  2. CERPEN (Cerita Pendek) — Fiksi pendek yang selesai dibaca sekali duduk. Contoh: kumpulan cerpen 'Senyum Karyamin'.",
          "  3. KOMIK — Cerita bergambar yang menyampaikan narasi melalui ilustrasi dan dialog. Contoh: Komik Petualangan Tintin, komik lokal seperti Si Juki.",
          "  4. PUISI — Karya sastra dengan bahasa yang dipadatkan, menggunakan irama, rima, dan diksi puitis. Contoh: kumpulan puisi 'Hujan Bulan Juni' (Sapardi Djoko Damono).",
          "  5. DRAMA / NASKAH DRAMA — Karya fiksi yang ditulis untuk dipentaskan, terdiri dari dialog dan petunjuk lakuan. Contoh: naskah drama 'Opera Kecoa' (Rendra).",
          "  6. DONGENG — Cerita rakyat yang diwariskan turun-temurun, berisi fantasi dan pesan moral. Subjenis: fabel (tokoh hewan), legenda (asal-usul tempat), mitos (dewa/dewi), cerita rakyat.",
          "",
          "PENTING: Semua jenis buku fiksi di atas memiliki SATU kesamaan — ceritanya adalah REKAAN. Meskipun novel sejarah atau cerita berdasarkan kisah nyata, jika penulis menambahkan dialog rekaan, adegan imajinatif, atau mengubah fakta demi kepentingan cerita, maka buku itu tetap FIKSI!",
        ],
        contoh: [
          "Analisis unsur intrinsik novel 'Laskar Pelangi' (Andrea Hirata):",
          "TEMA: Semangat pendidikan dan persahabatan melawan kemiskinan.",
          "TOKOH: Ikal (protagonis, cerdas dan gigih), Lintang (jenius dari keluarga miskin), Mahar (artistik dan kreatif), Bu Muslimah (guru inspiratif).",
          "ALUR: Orientasi (pengenalan Belitung dan SD Muhammadiyah) → Komplikasi (ancaman pembubaran sekolah, kemiskinan, keterbatasan) → Klimaks (Lintang harus berhenti sekolah karena ayahnya meninggal) → Resolusi (Ikal berhasil kuliah dan mewujudkan mimpinya).",
          "LATAR: Pulau Belitung tahun 1970-an, suasana pedesaan yang sederhana.",
          "SUDUT PANDANG: Orang pertama ('Aku' = Ikal).",
          "AMANAT: Pendidikan adalah kunci mengubah nasib; jangan pernah menyerah pada keterbatasan.",
          "GAYA BAHASA: Puitis, kaya metafora, menggunakan istilah-istilah lokal Melayu Belitung.",
          "",
          "BENAR (fiksi menggunakan imajinasi): \"Lintang mengayuh sepeda tua sejauh 40 kilometer melewati hutan karet dan kebun lada. Di pelupuk matanya, angka-angka beterbangan seperti kunang-kunang.\"",
          "SALAH (tidak boleh ada di fiksi yang mengaku nonfiksi): \"Berdasarkan data BPS tahun 2005, tingkat kemiskinan di Belitung mencapai 15%.\" (Ini data faktual, cocoknya di buku nonfiksi, bukan dalam novel.)",
        ],
        catatan: "Unsur intrinsik yang PALING membedakan buku fiksi satu dengan lainnya adalah GAYA BAHASA. Coba bandingkan gaya bahasa Andrea Hirata (puitis) dengan Pidi Baiq (santai/gaul) atau Pramoedya Ananta Toer (bersemangat/revolusioner). Setiap penulis memiliki 'sidik jari' kebahasaan yang unik!",
      },
      {
        judul: "Unsur, Jenis, dan Cara Membedakan Buku Nonfiksi",
        isi: [
          "Berbeda dengan fiksi yang dibangun oleh imajinasi, buku nonfiksi dibangun oleh FAKTA. Mari pelajari unsur-unsur yang membuat sebuah buku disebut nonfiksi!",
          "",
          "UNSUR-UNSUR BUKU NONFIKSI:",
          "",
          "1. FAKTA AKURAT — Informasi dalam buku nonfiksi harus benar, dapat diverifikasi, dan didukung bukti. Buku nonfiksi yang baik mencantumkan sumber informasi.",
          "  ✓ \"Indonesia merdeka pada 17 Agustus 1945.\" (Fakta sejarah yang dapat diverifikasi.)",
          "  ✗ \"Indonesia merdeka pada 18 Agustus 1945.\" (SALAH — tidak sesuai fakta.)",
          "",
          "2. DATA DAN STATISTIK — Buku nonfiksi sering menyajikan data berupa angka, tabel, grafik, atau diagram untuk memperkuat informasi.",
          "  ✓ \"Berdasarkan data BPS tahun 2020, jumlah penduduk Indonesia mencapai 270,2 juta jiwa.\"",
          "",
          "3. REFERENSI DAN DAFTAR PUSTAKA — Sumber informasi dicantumkan untuk menunjukkan kredibilitas dan memungkinkan pembaca mengecek langsung.",
          "",
          "4. INDEKS — Daftar kata/istilah penting di akhir buku beserta nomor halamannya, membantu pembaca mencari informasi spesifik.",
          "",
          "5. GLOSARIUM — Daftar istilah penting dengan definisinya, membantu pembaca memahami kata-kata asing atau teknis.",
          "",
          "6. OBJEKTIVITAS — Penulis nonfiksi harus bersikap objektif dan tidak memihak. Informasi disajikan apa adanya berdasarkan data.",
          "",
          "JENIS-JENIS BUKU NONFIKSI:",
          "  1. BUKU PELAJARAN — Buku teks yang digunakan di sekolah, disusun berdasarkan kurikulum. Contoh: Buku IPA, Matematika, Bahasa Indonesia.",
          "  2. BIOGRAFI / OTOBIOGRAFI — Kisah hidup seseorang yang ditulis oleh orang lain (biografi) atau oleh diri sendiri (otobiografi). Contoh: 'Soekarno: Biografi Singkat', 'Bung Hatta: Otobiografi'.",
          "  3. ENSIKLOPEDIA — Buku referensi yang memuat informasi lengkap tentang berbagai bidang ilmu, disusun secara alfabetis. Contoh: 'Ensiklopedia Sains', 'Ensiklopedia Umum'.",
          "  4. KAMUS — Buku referensi yang berisi daftar kata beserta arti, ejaan, dan penggunaannya. Contoh: KBBI (Kamus Besar Bahasa Indonesia), Kamus Inggris-Indonesia.",
          "  5. BUKU ILMIAH — Karya tulis ilmiah yang menyajikan hasil penelitian atau analisis mendalam tentang suatu topik. Contoh: skripsi, tesis, disertasi, buku teks perguruan tinggi.",
          "  6. LAPORAN — Dokumen yang menyajikan hasil kegiatan, penelitian, atau observasi secara sistematis. Contoh: laporan praktikum, laporan perjalanan.",
          "  7. JURNAL — Publikasi ilmiah periodik yang berisi artikel-artikel hasil penelitian terbaru.",
          "",
          "CARA MEMBEDAKAN BUKU FIKSI DAN NONFIKSI:",
          "",
          "1. LIHAT SAMPUL — Sampul buku fiksi biasanya lebih artistik dengan ilustrasi yang menggambarkan cerita. Sampul nonfiksi lebih informatif dengan judul yang menjelaskan isi.",
          "2. BACA SINOPSIS — Sinopsis fiksi menceritakan jalan cerita. Sinopsis nonfiksi menjelaskan topik dan ruang lingkup pembahasan.",
          "3. CEK GAYA BAHASA — Fiksi: puitis, emosional, kaya kiasan. Nonfiksi: lugas, informatif, objektif.",
          "4. CEK SUMBER DATA — Nonfiksi mencantumkan daftar pustaka, indeks, glosarium. Fiksi tidak memiliki ini.",
          "5. PERHATIKAN KATEGORI PERPUSTAKAAN — Di perpustakaan, fiksi biasanya di rak tersendiri (FIC), nonfiksi dikelompokkan berdasarkan nomor klasifikasi DDC.",
          "",
          "Tips membedakan buku di toko buku: Cek bagian punggung atau halaman hak cipta. Buku nonfiksi biasanya mencantumkan kategori seperti 'Pendidikan', 'Sejarah', atau 'Ilmu Pengetahuan'. Buku fiksi mencantumkan 'Novel', 'Cerpen', atau 'Sastra'.",
        ],
        contoh: [
          "Perbandingan struktur buku fiksi dan nonfiksi:",
          "",
          "BUKU FIKSI (Novel):",
          "• Judul kreatif: 'Laskar Pelangi' (tidak langsung menjelaskan isi)",
          "• Tidak ada daftar pustaka",
          "• Tidak ada indeks atau glosarium",
          "• Berisi bab-bab cerita: Bab 1, Bab 2, dst.",
          "• Gaya bahasa: banyak majas, dialog, deskripsi emosional",
          "",
          "BUKU NONFIKSI (Biografi):",
          "• Judul informatif: 'Biografi Soekarno: Sang Proklamator'",
          "• Ada daftar pustaka dan sumber referensi",
          "• Ada indeks nama dan istilah di akhir buku",
          "• Ada glosarium untuk istilah-istilah sulit",
          "• Berisi bab tematis: 'Masa Kecil', 'Pendidikan', 'Perjuangan', 'Proklamasi'",
          "• Gaya bahasa: lugas, kronologis, faktual",
          "",
          "✓ Contoh sampul fiksi: Ilustrasi anak-anak bersepeda di atas jembatan kayu dengan latar biru laut (Laskar Pelangi) — menarik, artistik, membuat penasaran.",
          "✓ Contoh sampul nonfiksi: Foto Soekarno sedang berpidato dengan latar merah putih, judul 'Biografi Soekarno' jelas — langsung paham isi buku.",
        ],
        catatan: "Apakah kamu tahu bahwa buku NONFIKSI bisa juga menggunakan bahasa yang menarik dan 'bercerita'? Contohnya buku 'Sapiens' karya Yuval Noah Harari — meskipun nonfiksi (sejarah manusia), ditulis dengan gaya naratif yang sangat menghibur, seperti membaca cerita! Inilah yang disebut NONFIKSI NARATIF atau creative nonfiction.",
      },
    ],
    rangkuman: [
      "Buku fiksi adalah karya imajinatif/rekaan yang bertujuan menghibur dan menyampaikan pesan melalui cerita, sedangkan buku nonfiksi adalah karya faktual yang bertujuan memberikan informasi berdasarkan data dan fakta.",
      "Unsur intrinsik fiksi meliputi: tema, tokoh & penokohan, alur (orientasi–komplikasi–klimaks–resolusi–koda), latar (tempat, waktu, suasana), sudut pandang, amanat, dan gaya bahasa.",
      "Unsur ekstrinsik fiksi meliputi: latar belakang penulis, nilai sosial budaya, nilai moral, nilai agama, dan kondisi sosial politik saat buku ditulis.",
      "Unsur buku nonfiksi meliputi: fakta akurat, data/statistik, referensi, daftar pustaka, indeks, glosarium, dan objektivitas penulis.",
      "Jenis buku fiksi: novel, cerpen, komik, puisi, drama, dongeng (fabel, legenda, mitos, cerita rakyat). Jenis buku nonfiksi: buku pelajaran, biografi/otobiografi, ensiklopedia, kamus, buku ilmiah, laporan, jurnal.",
      "Cara membedakan fiksi dan nonfiksi: lihat sampul (artistik vs informatif), baca sinopsis (cerita vs topik), cek gaya bahasa (puitis vs lugas), dan cek kelengkapan daftar pustaka/indeks/glosarium.",
      "Membaca buku fiksi bermanfaat untuk mengembangkan imajinasi, empati, dan kosakata. Membaca buku nonfiksi bermanfaat untuk menambah wawasan, pengetahuan, dan kemampuan analitis. Keduanya sama pentingnya!",
    ],
  },

  latihan: makeSoal([
    ["Buku fiksi adalah buku yang berisi...", ["Informasi faktual berdasarkan data", "Cerita rekaan atau imajinasi penulis", "Kumpulan laporan penelitian", "Data statistik dan grafik"], 1, "Buku fiksi adalah karya imajinatif yang berisi cerita rekaan, bukan fakta atau data."],
    ["Berikut ini yang termasuk contoh buku FIKSI adalah...", ["Ensiklopedia Sains", "Biografi Soekarno", "Novel Laskar Pelangi", "Kamus Besar Bahasa Indonesia"], 2, "Laskar Pelangi adalah novel fiksi karya Andrea Hirata. Ensiklopedia, biografi, dan kamus termasuk nonfiksi."],
    ["Unsur intrinsik cerita fiksi yang berfungsi sebagai 'jiwa' atau gagasan pokok cerita disebut...", ["Alur", "Tema", "Tokoh", "Amanat"], 1, "Tema adalah gagasan pokok atau ide utama yang mendasari keseluruhan cerita."],
    ["Yang membedakan buku fiksi dengan buku nonfiksi adalah...", ["Jumlah halamannya", "Fiksi berdasarkan imajinasi, nonfiksi berdasarkan fakta", "Fiksi lebih tebal", "Nonfiksi bergambar"], 1, "Perbedaan mendasar: fiksi lahir dari imajinasi/rekaan, sedangkan nonfiksi berdasarkan data dan fakta yang dapat diverifikasi."],
    ["Glosarium dalam buku nonfiksi berfungsi untuk...", ["Menunjukkan urutan bab", "Memudahkan pencarian kata/istilah penting beserta definisinya", "Menampilkan daftar tokoh", "Memberikan ilustrasi gambar"], 1, "Glosarium adalah daftar istilah penting dalam buku beserta definisinya, biasanya ditempatkan di akhir buku."],

    ["Pernyataan: 'Novel Bumi Manusia karya Pramoedya Ananta Toer termasuk buku nonfiksi karena berlatar sejarah Indonesia.'", ["Betul", "Salah"], 1, "SALAH. Meskipun berlatar sejarah, Bumi Manusia tetap FIKSI karena tokoh-tokohnya (Minke, Annelies) dan dialog-dialognya adalah rekaan penulis."],
    ["Pernyataan: 'Buku nonfiksi yang baik selalu mencantumkan daftar pustaka dan sumber referensi.'", ["Betul", "Salah"], 0, "BETUL. Daftar pustaka menunjukkan kredibilitas penulis dan memungkinkan pembaca mengecek langsung sumber informasi."],
    ["Pernyataan: 'Gaya bahasa dalam buku fiksi cenderung lugas, objektif, dan informatif.'", ["Betul", "Salah"], 1, "SALAH. Gaya bahasa buku fiksi cenderung puitis, emosional, dan kaya kiasan. Bahasa lugas dan informatif adalah ciri buku NONFIKSI."],

    ["Sebutkan TIGA jenis buku nonfiksi!", ["novel, cerpen, puisi", "biografi, ensiklopedia, buku pelajaran", "dongeng, komik, drama", "fabel, legenda, mitos"], 1, "Biografi, ensiklopedia, dan buku pelajaran adalah jenis buku nonfiksi. Novel, cerpen, puisi, dongeng, komik, drama termasuk fiksi."],
    ["Indeks dalam buku nonfiksi adalah daftar...", ["Bab-bab dalam buku", "Kata/istilah penting beserta nomor halamannya", "Gambar dan ilustrasi", "Tokoh cerita"], 1, "Indeks adalah daftar kata atau istilah penting dalam buku yang disusun secara alfabetis disertai nomor halaman tempat istilah tersebut muncul."],
  ]),

  praktik: {
petunjuk: "Buatlah resensi sebuah buku fiksi atau nonfiksi yang pernah kamu baca dengan struktur berikut:\n\n[Ilustrasi: Sampul buku 'Laskar Pelangi' dengan catatan tempelan: Identitas Buku, Sinopsis, Analisis, Evaluasi — seperti peta harta karun analisis buku.]\n\n1. Identitas Buku — Cantumkan judul buku, nama penulis, penerbit, tahun terbit, jumlah halaman, dan ISBN (jika ada).\n2. Orientasi — Perkenalkan buku secara umum. Apa yang membuat buku ini menarik? Siapa penulisnya? Apa tema utamanya?\n3. Sinopsis — Ceritakan isi buku secara singkat (1—2 paragraf). Untuk fiksi: ceritakan alurnya tanpa spoiler berlebihan. Untuk nonfiksi: jelaskan topik-topik utama yang dibahas.\n4. Analisis — Analisis kelebihan buku: apa yang membuat buku ini bagus? Gaya bahasa penulis? Kedalaman riset? Karakter tokoh? Pesan yang disampaikan?\n5. Evaluasi — Sebutkan kekurangan buku (jika ada) dan opini pribadimu. Apakah kamu merekomendasikan buku ini? Kepada siapa?\n\nPanjang resensi minimal 4 paragraf.",
tips: [
      "Pilihlah buku yang benar-benar kamu sukai agar resensimu lebih bersemangat dan mendalam.",
      "Baca buku sampai selesai sebelum menulis resensi — jangan hanya membaca sinopsis di sampul belakang!",
      "Catat kutipan-kutipan menarik selama membaca untuk dijadikan contoh dalam analisis.",
      "Jadilah jujur dalam evaluasi: jika ada bagian yang membosankan atau kelemahan, sampaikan dengan sopan dan konstruktif.",
      "Untuk resensi fiksi, fokuslah pada: alur cerita, karakter tokoh, gaya bahasa, dan pesan moral yang disampaikan.",
      "Untuk resensi nonfiksi, fokuslah pada: keakuratan data, kelengkapan informasi, kemudahan dipahami, dan kredibilitas penulis.",
      "Akhiri dengan kalimat penutup yang kuat: rekomendasi atau refleksi pribadi tentang apa yang kamu dapatkan setelah membaca buku ini.",
    ],
    contoh: "IDENTITAS BUKU\nJudul: Laskar Pelangi\nPenulis: Andrea Hirata\nPenerbit: Bentang Pustaka\nTahun Terbit: 2005\nJumlah Halaman: 534 halaman\nISBN: 978-979-3062-79-4\n\nORIENTASI\nLaskar Pelangi adalah novel fenomenal yang telah menginspirasi jutaan pembaca di Indonesia. Karya perdana Andrea Hirata ini lahir dari kenangan masa kecilnya di Pulau Belitung, dan berhasil menembus pasar internasional — diterjemahkan ke lebih dari 20 bahasa. Novel ini bukan sekadar cerita tentang sekolah, tetapi sebuah perjalanan haru tentang mimpi, persahabatan, dan perjuangan melawan keterbatasan. Andrea Hirata menulis dengan gaya yang puitis, jenaka, dan penuh kejutan — membuat pembaca tertawa dan menangis dalam satu halaman.\n\nSINOPSIS\nNovel ini mengisahkan sepuluh anak dari keluarga miskin di Belitung yang bersekolah di SD Muhammadiyah — sekolah paling sederhana yang terancam dibubarkan. Ikal, Lintang, Mahar, Sahara, A Kiong, dan teman-temannya adalah 'Laskar Pelangi' yang diajar oleh Bu Muslimah dan Pak Harfan. Lintang, seorang anak jenius dari keluarga sangat miskin, harus mengayuh sepeda sejauh 40 kilometer pulang-pergi setiap hari. Saat ayahnya meninggal, Lintang harus berhenti sekolah dan menjadi nelayan. Namun, semangat pendidikan dan persahabatan mereka tidak pernah padam. Melalui perjuangan yang panjang, Ikal berhasil melanjutkan pendidikan hingga ke Sorbonne, Perancis.\n\nANALISIS\nKelebihan utama novel ini adalah gaya bahasa Andrea Hirata yang sangat khas — puitis namun natural, penuh metafora indah yang tidak terkesan dipaksakan. Ia mampu menggambarkan kemiskinan dengan cara yang tidak menyedihkan, justru penuh kehangatan dan humor. Tokoh-tokohnya hidup dan memiliki karakter yang kuat: Ikal yang sensitif, Lintang yang jenius, Mahar yang artistik, dan Bu Muslimah yang penuh pengorbanan. Alur cerita mengalir dengan ritme yang pas — tidak terburu-buru tetapi tidak membosankan. Andrea juga menyisipkan banyak pengetahuan (dari astronomi hingga sastra) dalam dialog-dialog Lintang yang cemerlang.\n\nEVALUASI\nKekurangan novel ini mungkin terletak pada beberapa bagian yang terasa terlalu panjang, terutama pada deskripsi latar yang kadang mendetail. Ada juga beberapa alur sampingan yang tidak sepenuhnya terselesaikan. Namun, secara keseluruhan, Laskar Pelangi adalah buku yang sangat layak dibaca oleh semua kalangan — dari pelajar hingga orang dewasa. Saya merekomendasikan buku ini kepada siapa pun yang membutuhkan inspirasi dan pengingat bahwa pendidikan adalah kekuatan paling dahsyat untuk mengubah nasib. Rating saya: 9/10.",
  },

  kuis: makeSoal([
    ["Perbedaan PALING MENDASAR antara buku fiksi dan nonfiksi terletak pada...", ["Jumlah halaman dan ketebalan buku", "Sumber dan tujuan penulisan: imajinasi vs fakta", "Harga buku dan penerbit", "Tahun terbit dan edisi"], 1, "Perbedaan paling mendasar: fiksi bersumber dari imajinasi penulis dengan tujuan menghibur, nonfiksi bersumber dari data/fakta dengan tujuan menginformasikan."],
    ["Cermati ciri-ciri berikut: (1) Ada daftar pustaka (2) Gaya bahasa puitis (3) Terdapat indeks (4) Cerita bersifat rekaan. Yang merupakan ciri buku nonfiksi adalah...", ["(1) dan (3)", "(2) dan (4)", "(1) dan (2)", "(3) dan (4)"], 0, "Daftar pustaka (1) dan indeks (3) adalah ciri buku nonfiksi. Gaya bahasa puitis (2) dan cerita rekaan (4) adalah ciri fiksi."],
    ["Buku yang mengisahkan kehidupan seseorang yang ditulis oleh orang lain disebut...", ["Otobiografi", "Biografi", "Novel biografis", "Ensiklopedia"], 1, "Biografi ditulis oleh orang lain tentang kehidupan seseorang. Otobiografi ditulis oleh diri sendiri tentang kehidupan sendiri."],
    ["Dalam struktur resensi buku, bagian yang berisi ringkasan isi buku disebut...", ["Identitas buku", "Orientasi", "Sinopsis", "Evaluasi"], 2, "Sinopsis adalah ringkasan isi buku secara singkat dan padat tanpa memberikan spoiler berlebihan."],
    ["Berikut ini yang BUKAN termasuk jenis buku fiksi adalah...", ["Novel", "Komik", "Ensiklopedia", "Puisi"], 2, "Ensiklopedia adalah buku NONFIKSI yang berisi informasi lengkap tentang berbagai bidang ilmu."],
    ["Fungsi daftar pustaka dalam buku nonfiksi adalah...", ["Mempercantik tampilan buku", "Menunjukkan sumber referensi dan kredibilitas penulis", "Sebagai halaman pembuka", "Tempat menulis ucapan terima kasih"], 1, "Daftar pustaka mencantumkan sumber-sumber yang dirujuk penulis, menunjukkan kredibilitas dan memungkinkan verifikasi."],
    ["Kalimat berikut yang menggunakan gaya bahasa FIKSI adalah...", ["Menurut data BPS, inflasi tahun ini mencapai 3,5%", "Matahari tersenyum hangat menyapa desa kecil di ujung timur Pulau Belitung", "Proklamasi kemerdekaan dibacakan pada 17 Agustus 1945", "Penelitian ini menggunakan metode kualitatif deskriptif"], 1, "'Matahari tersenyum' adalah personifikasi — gaya bahasa khas fiksi. Kalimat lain bersifat faktual dan termasuk gaya bahasa nonfiksi."],
    ["Buku pelajaran termasuk jenis buku nonfiksi karena...", ["Disusun oleh banyak penulis", "Berisi informasi faktual dan disusun berdasarkan kurikulum", "Memiliki gambar berwarna", "Diterbitkan oleh penerbit besar"], 1, "Buku pelajaran berisi informasi faktual/ilmiah yang dapat dipertanggungjawabkan dan disusun berdasarkan kurikulum pendidikan."],
    ["Perbedaan antara dongeng dan novel adalah...", ["Dongeng lebih panjang dari novel", "Dongeng adalah cerita rakyat anonim dengan pesan moral eksplisit, novel adalah fiksi modern dengan pengarang jelas", "Dongeng tidak memiliki tokoh", "Novel selalu tentang percintaan"], 1, "Dongeng adalah cerita rakyat anonim (pengarang tidak diketahui), diwariskan lisan, dengan pesan moral jelas. Novel adalah fiksi modern dengan pengarang jelas, alur kompleks, dan tokoh berkembang."],
    ["Manfaat membaca buku nonfiksi bagi pelajar adalah...", ["Melatih imajinasi dan kreativitas", "Menambah wawasan, pengetahuan faktual, dan kemampuan berpikir kritis", "Menghibur dan melepas penat", "Meningkatkan kemampuan menulis cerita"], 1, "Nonfiksi bermanfaat untuk menambah wawasan dan pengetahuan faktual. Imajinasi/kreativitas dan hiburan lebih terkait dengan fiksi."],
  ]),
}

export default konten
