import type { Konten } from "../types"
import { makeSoal } from "../types"

const konten: Konten = {
  belajar: {
    tujuan: [
      "Memahami perbandingan mendalam antara pantun dan syair dari segi struktur, sajak, dan isi",
      "Mengidentifikasi jenis-jenis pantun (nasihat, jenaka, teka-teki, percintaan, adat) dengan contoh konkret",
      "Menganalisis kaidah kebahasaan pantun dan syair: diksi klasik, konjungsi, dan bahasa kiasan",
      "Membedakan pantun dan syair dengan puisi rakyat lain: gurindam, karmina, dan seloka",
      "Menulis pantun dan syair sendiri dengan memperhatikan pola sajak dan struktur yang benar",
    ],
    materi: [
      {
        judul: "Mengulang Kembali: Pengertian Pantun dan Syair",
        isi: [
          "Di kelas VII semester 1, kamu sudah belajar tentang puisi rakyat — termasuk pantun dan syair. Sekarang, kita akan memperdalam pemahaman itu dengan pendekatan PERBANDINGAN. Karena meskipun sama-sama berjumlah 4 baris per bait, pantun dan syair punya perbedaan mendasar yang wajib kamu kuasai!",
          "",
          "Sebelum melangkah lebih jauh, mari review sejenak:",
          "",
          "• PANTUN adalah puisi rakyat Melayu yang setiap baitnya terdiri dari 4 baris dengan sajak a-b-a-b. Baris 1-2 disebut SAMPIRAN (pengantar yang biasanya berkaitan dengan alam), baris 3-4 disebut ISI (pesan yang ingin disampaikan). Setiap baris terdiri dari 8—12 suku kata.",
          "",
          "  ✓ Contoh:",
          "  Kalau ada jarum yang patah (a) → sampiran",
          "  Jangan simpan di dalam peti (b) → sampiran",
          "  Kalau ada kata yang salah (a) → isi",
"  Jangan simpan di dalam hati (b) → isi",
"",
"[Ilustrasi: Diagram empat baris pantun dengan kode warna: Baris 1 (MERAH) = sampiran, Baris 2 (BIRU) = sampiran, Baris 3 (HIJAU) = isi, Baris 4 (KUNING) = isi. Tanda panah melengkung menunjukkan sajak: baris 1-3 (a) dan baris 2-4 (b).]",
"",
"• SYAIR adalah puisi rakyat yang berasal dari sastra Arab-Melayu, setiap bait terdiri dari 4 baris dengan sajak a-a-a-a. BERBEDA dengan pantun, SYAIR TIDAK MEMILIKI SAMPIRAN — semua baris adalah isi. Setiap baris terdiri dari 8—14 suku kata. Syair biasanya berupa cerita panjang atau nasihat beruntun.",
          "",
          "  ✓ Contoh:",
          "  Wahai muda kenali dirimu (a) → isi",
          "  Ialah perahu tamsil hidupmu (a) → isi",
          "  Tiada berapa lama hidupmu (a) → isi",
"  Ke akhirat jua kekal hidupmu (a) → isi",
"",
"[Ilustrasi: Diagram empat baris syair dengan kode warna: SEMUA baris (HIJAU) = isi. Tanda panah lurus ke kanan menunjukkan sajak a-a-a-a. Perbandingan visual dengan pantun di sebelahnya yang memiliki 2 baris sampiran (warna berbeda).]",
"",
"PENTING: Bab ini FOKUS pada perbandingan. Kamu sudah tahu definisi dasarnya. Sekarang saatnya memahami APA YANG MEMBEDAKAN dan APA YANG MEMBUAT KEDUANYA UNIK. Hafalkan: pantun = a-b-a-b + sampiran; syair = a-a-a-a + semua isi.",
        ],
        contoh: [
          "Review cepat dengan tabel ingatan:",
          "PANTUN = 4 baris, a-b-a-b, sampiran-isi, 8-12 suku kata",
          "SYAIR = 4 baris, a-a-a-a, semua isi, 8-14 suku kata",
          "",
          "Tips mengingat perbedaan:",
          "• 'PANTUN' — bayangkan 'PASANGAN' (pasangan sampiran-isi, pasangan sajak a-b-a-b)",
          "• 'SYAIR' — bayangkan 'SAMA' (semua sajak sama, semua baris isi)",
          "",
          "BENAR: \"Pantun memiliki sampiran, syair tidak memiliki sampiran.\"",
          "SALAH: \"Pantun dan syair sama-sama memiliki sampiran.\"",
        ],
        catatan: "Meskipun sudah dipelajari di semester 1, banyak siswa yang masih tertukar antara pantun dan syair karena sama-sama 4 baris. Kunci utamanya: periksa SAJAK dan CARI SAMPIRAN. Jika baris 1-2 tidak nyambung dengan baris 3-4 (berfungsi sebagai pengantar), itu PASTI pantun.",
      },
      {
        judul: "Jenis-Jenis Pantun dan Contohnya",
        isi: [
          "Pantun memiliki banyak jenis berdasarkan isi pesannya. Memahami jenis-jenis ini penting agar kamu bisa menulis pantun yang tepat sesuai tujuan. Berikut jenis-jenis utama pantun:",
          "",
          "1. PANTUN NASIHAT — Berisi petuah, ajaran budi pekerti, dan motivasi. Jenis yang paling umum ditemukan.",
          "  Ciri: menggunakan kata ajakan (mari, hendaklah, janganlah), berisi nilai moral.",
          "  ✓ \"Buah manggis di tepi rawa / Si burung elang terbang melayang / Jikalau ingin hidup mulia / Rajin-rajinlah belajar sepanjang hayat.\"",
          "",
          "2. PANTUN JENAKA — Bertujuan menghibur dengan humor ringan, kelucuan, atau sindiran lucu.",
          "  Ciri: mengandung unsur kejutan lucu di baris isi, situasi tidak masuk akal.",
          "  ✓ \"Anak monyet di atas dulang / Digoyang-goyang jatuh ke tanah / Geli hati menahan senyum / Melihat kakek bergoyang dangdut.\"",
          "",
          "3. PANTUN TEKA-TEKI — Berisi tebakan atau pertanyaan yang mengundang jawaban.",
          "  Ciri: baris isi berisi deskripsi samar tentang suatu benda/hewan, baris sampiran netral.",
          "  ✓ \"Batu hitam di tengah sawah / Digulung ombak dari tepian / Badan ramping tak bertulang / Bersaudara sejak lahir ke dunia.\" (Jawaban: sepak bola dan gawang)",
          "",
          "4. PANTUN PERCINTAAN — Mengungkapkan perasaan rindu, kasih sayang, atau kerinduan.",
          "  Ciri: bahasa romantis, menggunakan kata seperti rindu, cinta, sayang, hati.",
          "  ✓ \"Pisang emas dibawa berlayar / Masak sebiji di atas peti / Hutang emas boleh dibayar / Hutang budi dibawa sampai mati.\"",
          "",
          "5. PANTUN ADAT — Digunakan dalam upacara adat, pernikahan, atau acara resmi tradisional.",
          "  Ciri: bahasa formal/klasik, berkaitan dengan tradisi dan nilai adat.",
          "  ✓ \"Sirih pinang kami hantarkan / Tanda penghormatan dengan setulus hati / Meneruskan adat yang sudah turun-temurun / Ikatan tali silaturahmi terjalin kembali.\"",
          "",
          "6. PANTUN AGAMA — Berisi pesan keagamaan, ajaran spiritual, dan peringatan tentang akhirat.",
          "  Ciri: menyebut nama Tuhan, surga, neraka, dosa, pahala, ibadah.",
          "  ✓ \"Pergi ke masaidng waktu subuh / Mendengar kumandang suara azan / Dunia ini hanya sementara / Bekali iman untuk kehidupan selanjutnya.\"",
          "",
          "Tips membedakan jenis pantun: lihat KATA KUNCI di baris isi. Nasihat = 'jangan', 'mari', 'rajin'. Jenaka = 'tertawa', 'geli', 'lucu'. Teka-teki = deskripsi benda. Percintaan = 'rindu', 'cinta', 'hati'. Adat = 'adat', 'tradisi', 'marga'. Agama = 'Tuhan', 'iman', 'ibadah'.",
        ],
        contoh: [
          "Perbedaan pantun nasihat dan pantun jenaka dalam tema yang mirip:",
          "",
          "PANTUN NASIHAT (tema belajar):",
          "\"Ke hutan mencari kayu gaharu / Kayu gaharu wangi semerbak / Belajarlah dengan tekun dan sabar / Agar cita-cita mudah tercapai.\"",
          "",
          "PANTUN JENAKA (tema belajar):",
          "\"Pergi ke pasar beli pepaya / Pepaya muda digulai ikan / Katanya rajin belajar tiap hari / Tapi nilai ujian tetap di bawah standar.\"",
          "",
          "Lihat perbedaannya? Pantun nasihat serius dan memotivasi, pantun jenaka menyindir dengan humor. Keduanya sama-sama sah sebagai pantun!",
          "",
          "BENAR (pantun teka-teki yang baik): \"Buah delima di dalam peti / Dibawa dari negeri seberang / Kalau tuan bijak bestari / Apa yang naik tak pernah turun?\" (jawaban: usia/umur)",
          "SALAH (bukan teka-teki karena tidak ada tebakan): \"Buah delima di dalam peti / Dibawa dari negeri seberang / Buah hatiku di dalam hati / Slalu terkenang slalu terbayang.\" (ini pantun percintaan, bukan teka-teki)",
        ],
        catatan: "Menariknya, dalam tradisi Melayu asli, pantun tidak pernah dikategorikan secara kaku seperti di atas. Masyarakat Melayu menggunakan pantun secara cair — satu pantun bisa mengandung nasihat sekaligus humor. Kategorisasi ini muncul belakangan untuk memudahkan pembelajaran di sekolah.",
      },
      {
        judul: "Syair: Sejarah, Ciri, dan Jenis",
        isi: [
          "Syair memiliki kedudukan istimewa dalam sastra Melayu. Berbeda dengan pantun yang pendek dan mandiri (satu bait sudah selesai), syair biasanya panjang dan berkesinambungan — satu cerita bisa terdiri dari puluhan bahkan ratusan bait!",
          "",
          "• SEJARAH SINGKAT SYAIR:",
          "  Syair lahir dari tradisi sastra Arab yang masuk ke Nusantara bersamaan dengan penyebaran Islam pada abad ke-13 hingga ke-17. Kata 'syair' berasal dari bahasa Arab 'syi'r' yang berarti 'puisi'. Pusat perkembangan syair di Nusantara adalah Aceh, Riau, dan Semenanjung Malaya.",
          "",
          "  Tokoh terpenting dalam sejarah syair Melayu adalah HAMZAH FANSURI (sastrawan Aceh abad ke-16). Karyanya yang paling terkenal: Syair Perahu — sebuah syair filosofis yang menggunakan metafora perahu sebagai kehidupan manusia menuju Tuhan. Karya Hamzah Fansuri memadukan ajaran tasawuf (spiritual Islam) dengan keindahan puisi Melayu.",
          "",
          "  Setelah Hamzah Fansuri, syair berkembang pesat. Muncul syair-syair naratif seperti Syair Ken Tambuhan, Syair Bidasari, Syair Singapura Dimakan Api, dan Syair Abdul Muluk. Syair-syair ini menjadi bacaan populer di kalangan masyarakat Melayu pada abad ke-18 dan 19.",
          "",
          "• CIRI-CIRI SYAIR:",
          "  1. Setiap bait terdiri dari EMPAT BARIS",
          "  2. Bersajak a-a-a-a (satu rima dari awal sampai akhir bait)",
          "  3. Semua baris adalah ISI — TIDAK ADA SAMPIRAN",
          "  4. Setiap baris 8—14 suku kata",
          "  5. Berisi cerita berkesinambungan (naratif), nasihat, atau ajaran",
          "  6. Bahasa klasih yang puitis dan penuh kiasan",
          "  7. Satu syair bisa terdiri dari puluhan hingga ratusan bait",
          "",
          "• JENIS SYAIR BERDASARKAN ISI:",
          "  a. SYAIR NARATIF — Bercerita tentang kisah tertentu: percintaan, kepahlawanan, sejarah. Contoh: Syair Ken Tambuhan (kisah tragis cinta terlarang), Syair Bidasari (kisah putri yang dibuang), Syair Singapura Dimakan Api (tentang kebakaran besar di Singapura tahun 1890).",
          "",
          "  b. SYAIR DIDAKTIK — Berisi ajaran, nasihat, dan pendidikan moral/agama. Contoh: Syair Perahu (Hamzah Fansuri — nasihat spiritual), Syair Dagang (tentang kehidupan di perantauan), Syair Nasihat (anonim — nasihat untuk anak muda).",
          "",
          "  c. SYAIR KEAGAMAAN — Berisi ajaran tasawuf, tauhid, dan spiritual Islam. Biasanya ditulis oleh ulama sufi. Contoh: Syair Burung Pingai (Hamzah Fansuri), Syair Raksi (tentang obat spiritual).",
          "",
          "  d. SYAIR SEJARAH — Mengisahkan peristiwa sejarah tertentu. Contoh: Syair Perang Mengkasar (tentang perlawanan rakyat Makassar melawan VOC), Syair Perang Johor.",
          "",
          "PENTING: Karena semua baris adalah isi dan cerita berlanjut dari satu bait ke bait berikutnya, syair sering disebut sebagai 'novel dalam bentuk puisi'. Syair adalah bentuk awal novel Melayu sebelum munculnya prosa modern.",
        ],
        contoh: [
          "Kutipan SYAIR PERAHU — Hamzah Fansuri (analisis):",
          "",
          "Bait 1:",
          "\"Wahai muda kenali dirimu / Ialah perahu tamsil hidupmu / Tiada berapa lama hidupmu / Ke akhirat jua kekal hidupmu.\"",
          "",
          "Analisis:",
          "• Sajak: a-a-a-a ( -mu, -mu, -mu, -mu )",
          "• Semua baris adalah isi → tidak ada sampiran",
          "• Pesan: hidup di dunia hanya sementara, jangan lupa akhirat",
          "• Bahasa kiasan: hidup diibaratkan perahu (metafora)",
          "",
          "Bait 2 (lanjutan):",
          "\"Hidup di dunia ibarat naik perahu / Carilah bekal jangan berlabuh / Sedikit-dikit berlayar selalu / Sampailah ke pantai Allah yang Maha Esa.\"",
          "",
          "Analisis:",
          "• Bait 2 melanjutkan tema bait 1 → sifat naratif/berkesinambungan",
          "• Metafora diperluas: perahu → bekal → berlayar → pantai Tuhan",
          "• Pesan: kumpulkan amal baik (bekal) selama hidup (berlayar) untuk mencapai Tuhan (pantai Allah)",
          "",
          "BENAR (ciri syair):",
          "\"Tuntutlah ilmu dengan tekun / Janganlah kau mudah putus asa / Ilmu itu bekal berharga / Dunia akhirat kan selamat.\" (a-a-a-a, semua isi)",
          "",
          "SALAH (pantun yang disalahartikan sebagai syair):",
          "\"Buah nanas di dalam kebun / Jatuh ke tanah diambil bebek / Rajin-rajinlah belajar slalu / Agar masa depanmu tidak suram.\" (sajak a-b-a-b, baris 1-2 sampiran, ini PANTUN bukan syair)",
        ],
        catatan: "Hamzah Fansuri adalah tokoh yang sangat penting. Beliau tidak hanya sastrawan, tetapi juga seorang sufi (ahli tasawuf) terkemuka. Karyanya dipelajari hingga ke universitas-universitas di Malaysia, Brunei, dan Belanda. Salah satu bait Syair Perahu bahkan diabadikan di Museum Nasional Malaysia.",
      },
      {
        judul: "Perbandingan Mendalam: Pantun vs Syair",
        isi: [
          "Inilah inti dari bab ini — perbandingan MENDALAM antara pantun dan syair. Bukan sekadar hafalan ciri, tapi pemahaman MENGAPA keduanya berbeda dan BAGAIMANA perbedaan itu memengaruhi cara kita menulis dan menikmatinya.",
          "",
          "• PERBANDINGAN STRUKTUR:",
          "",
          "  ASPEK                PANTUN                          SYAIR",
          "  Jumlah baris         4 baris                         4 baris",
          "  Pola sajak           a-b-a-b                         a-a-a-a",
          "  Sampiran             Ada (baris 1-2)                 Tidak ada",
          "  Isi                  Baris 3-4                      Semua baris",
          "  Suku kata            8—12 per baris                 8—14 per baris",
          "  Hubungan antar-bait  Mandiri (1 bait utuh)          Berkesinambungan",
          "  Sifat isi            Tersirat (implisit)            Tersurat (eksplisit)",
          "",
          "• PERBEDAAN MAKNA DAN FUNGSI:",
          "",
          "  ✓ PANTUN — Isinya TERSIRAT. Sampiran dan isi tidak berhubungan langsung. Makna pantun tidak langsung, perlu 'ditebak' oleh pendengar. Ini membuat pantun terasa lebih puitis dan misterius. Bayangkan seperti 'puisi berteka-teki' — indah karena tidak langsung.",
          "",
          "  ✓ SYAIR — Isinya TERSURAT. Semua baris adalah isi, sehingga pesan disampaikan secara langsung dan jelas. Syair lebih mirip 'cerita atau nasihat yang dirhymekan' — indah karena lugas dan mengalir.",
          "",
          "  ✓ Contoh perbedaan isi tersirat vs tersurat dalam TEMA SAMA (nasihat belajar):",
          "",
          "  PANTUN (tersirat):",
          "  \"Ke hutan mencari kayu cendana / Kayu dibelah menjadi peti / Rajin-rajinlah menuntut ilmu / Agar masa depan cerah berseri.\"",
          "  → Pesan tersirat: belajar = kunci masa depan. Tidak dijelaskan mengapa. Pendengar menyimpulkan sendiri.",
          "",
          "  SYAIR (tersurat):",
          "  \"Wahai ananda yang masih muda / Tuntutlah ilmu dengan gembira / Ilmu bagai pelita di malam hari / Menerangi langkah tak tersesat lagi.\"",
          "  → Pesan tersurat: ilmu = pelita yang menerangi. Langsung dijelaskan bahwa ilmu mencegah kesesatan.",
          "",
          "• PERBEDAAN PENGGUNAAN:",
          "  Pantun lebih sering digunakan dalam konteks PERCAKAPAN — saling berbalas pantun di acara pernikahan, acara adat, atau sekadar bersenda gurau. Syair lebih sering digunakan dalam konteks PEMBACAAN — dibacakan di majelis taklim, acara keagamaan, atau dibaca sendiri untuk merenung.",
          "",
"PENTING: Tidak ada yang 'lebih baik' antara pantun dan syair. Keduanya adalah bentuk seni yang berbeda, seperti lukisan pemandangan vs lukisan abstrak. Keduanya indah dengan caranya masing-masing!",
"",
"[Ilustrasi: Tabel perbandingan pantun vs syair: (1) jumlah baris: 4 vs 4, (2) sajak: a-b-a-b vs a-a-a-a, (3) sampiran: ada vs tidak ada, (4) isi: baris 3-4 vs semua baris, (5) asal: Melayu vs Arab-Melayu. Masing-masing dengan ikon dan warna berbeda.]",
],
contoh: [
          "Perbandingan langsung dalam tema 'Nasihat untuk Anak':",
          "",
          "PANTUN:",
          "\"Anak ayam turun ke bumi / Induknya memanggil cekcok bunyinya / Jika engkau inginberbakti / Hormati ibu dan ayahmu slalu.\"",
          "  → Sajak a-b-a-b, baris 1-2 sampiran (anak ayam), baris 3-4 isi (nasihat)",
          "",
          "SYAIR:",
          "\"Wahai anakku cahaya mata / Hormatilah ibu bapak slalu / Mereka yang menjagamu sejak lahir / Jangan kau lukai hati mereka.\"",
          "  → Sajak a-a-a-a, semua baris isi, langsung pada pesan",
          "",
          "Perhatikan: dalam pantun, baris 1-2 (anak ayam) tidak nyambung ke isi! Itulah sampiran. Dalam syair, semua baris bertalian langsung ke pesan.",
          "",
          "BENAR (perbedaan esensial): \"Pantun menyampaikan pesan secara tersirat melalui sampiran-isi; syair menyampaikan pesan secara tersurat tanpa sampiran.\"",
          "SALAH (kesalahan umum): \"Pantun dan syair sama-sama punya sampiran, hanya sajaknya yang berbeda.\"",
        ],
        catatan: "Dalam praktiknya, batas antara pantun dan syair kadang kabur. Ada puisi rakyat yang disebut 'pantun syair' — menggunakan sajak a-a-a-a tapi masih mempertahankan sampiran. Namun untuk pembelajaran di kelas, kita ikuti aturan standar: pantun = a-b-a-b + sampiran, syair = a-a-a-a + semua isi.",
      },
      {
        judul: "Kaidah Kebahasaan Pantun dan Syair",
        isi: [
          "Pantun dan syair memiliki kaidah kebahasaan yang khas. Bahasa yang digunakan berbeda dari bahasa sehari-hari — lebih puitis, lebih klasik, dan penuh kiasan. Mari kita bedah kaidah kebahasaannya:",
          "",
          "1. DIKSI KLASIK — Penggunaan kata-kata Melayu klasik yang jarang dipakai dalam percakapan sehari-hari.",
          "  Contoh: 'insaf' (sadar), 'tamsil' (ibarat), 'jua' (juga), 'bak' (bagai), 'serta' (bersama), 'maka', 'pun', 'adapun', 'syahdan'.",
          "  ✓ \"Tiada berapa lama hidupmu\" (bukan 'tidak berapa lama' — 'tiada' lebih klasik)",
          "  ✓ \"Sekali-kali tiada boleh dibilangkan nama\" (struktur kalimat klasik: di- + -kan + kata kerja)",
          "",
          "2. KONJUNGSI DALAM SYAIR — Syair sering menggunakan konjungsi untuk menunjukkan hubungan antar baris dan antarbait.",
          "  • 'Maka' — menunjukkan akibat: \"Maka sampailah ia ke negeri yang indah\"",
          "  • 'Syahdan' — memulai cerita: \"Syahdan, maka tersebutlah perkataan...\"",
          "  • 'Hatta' — menunjukkan waktu bersamaan: \"Hatta beberapa lamanya...\"",
          "  • 'Arkian' — menunjukkan urutan: \"Arkian maka baginda pun berangkatlah\"",
          "",
          "3. BAHASA KIASAN — Pantun dan syair kaya akan majas (gaya bahasa).",
          "  a. PERSONIFIKASI — benda mati diberi sifat manusia",
          "     ✓ \"Angin berbisik cerita tentangmu\"",
          "     ✓ \"Ombak menari-nari di tepian pantai\"",
          "",
          "  b. METAFORA — perbandingan tanpa kata pembanding",
          "     ✓ \"Hidup adalah perahu\" (hidup diibaratkan perahu)",
          "     ✓ \"Ilmu bagai pelita\" (ilmu diibaratkan pelita)",
          "",
          "  c. ASONANSI — pengulangan bunyi vokal untuk keindahan",
          "     ✓ \"Buah manggis di tepi rawa\" (pengulangan vokal a dan i)",
          "",
          "  d. ALITERASI — pengulangan bunyi konsonan",
          "     ✓ \"Cencang dua segeragai\" (pengulangan konsonan c, g, r)",
          "",
          "4. PILIHAN KATA BERDASARKAN SAJAK — Dalam pantun, pemilihan kata sangat dipengaruhi oleh kebutuhan sajak.",
          "  Contoh: untuk mendapatkan bunyi '-ang', penulis pantun memilih kata: 'terbang', 'melayang', 'pulang', 'hilang', 'senang', 'kepalang'.",
          "  Contoh untuk bunyi '-an': 'teman', 'jalan', 'makan', 'bambuan', 'tanaman'.",
          "",
          "5. STRUKTUR KALIMAT — Kalimat dalam pantun dan syair sering menggunakan struktur inversi (terbalik) untuk mengejar sajak.",
          "  Biasa: \"Kami berlayar dengan perahu kecil\"",
          "  Inversi: \"Berlayar kami dengan perahu kecil\" (kata kerja didepan)",
          "",
          "Tips menganalisis: saat membaca pantun atau syair, perhatikan kata-kata yang tidak biasa kamu gunakan sehari-hari. Itulah 'diksi klasik' yang menjadi ciri khas puisi rakyat. Catat dan cari artinya di KBBI!",
        ],
        contoh: [
          "Analisis kebahasaan pantun:",
          "",
          "\"Pisang emas dibawa berlayar / Masak sebiji di atas peti / Hutang emas boleh dibayar / Hutang budi dibawa sampai mati.\"",
          "",
          "• Diksi klasik: 'berlayar', 'sebiji', 'hutang budi'",
          "• Personifikasi: 'hutang budi dibawa sampai mati' (hutang budi diberi sifat seperti benda yang bisa 'dibawa')",
          "• Asonansi: pengulangan bunyi 'a' pada baris 1 dan 3 (pisAng, emAs, dibAwA, berlAyAr — hutAng, emAs, dibAyAr)",
          "• Sajak: a-b-a-b (berlayar-peti-dibayar-mati)",
          "• Struktur inversi: 'Masak sebiji di atas peti' (biasa: 'Sebiji masak di atas peti')",
          "",
          "Analisis kebahasaan syair:",
          "",
          "\"Wahai muda kenali dirimu / Ialah perahu tamsil hidupmu / Tiada berapa lama hidupmu / Ke akhirat jua kekal hidupmu.\"",
          "",
          "• Diksi klasik: 'wahai', 'tamsil', 'tiada', 'jua'",
          "• Metafora: 'hidup adalah perahu' (perbandingan langsung tanpa kata pembanding)",
          "• Personifikasi: 'perahu' dianggap sebagai 'kendaraan' yang membawa manusia",
          "• Aliterasi: pengulangan bunyi 'm' pada 'muda', 'perahu tamsil'",
          "• Sajak: a-a-a-a ( -mu, -mu, -mu, -mu ) — sajak yang sama di setiap baris",
          "• Struktur: semua baris adalah isi (nasihat langsung ke pembaca)",
          "",
          "BENAR (penggunaan diksi klasik): \"Hilanglah rinduku slalu / Tiada bertemu denganmu jua\"",
          "SALAH (terlalu modern untuk puisi rakyat): \"Gue kangen banget sama lo / Nggak ketemu-ketemu terus\"",
        ],
        catatan: "Kaidah kebahasaan ini tidak hanya berlaku untuk puisi rakyat lama. Banyak penulis modern yang sengaja menggunakan diksi klasik dalam puisi mereka untuk menciptakan efek puitis. Jadi, belajar diksi klasik juga berguna untuk menulis puisi kontemporer!",
      },
      {
        judul: "Menulis Pantun dan Syair",
        isi: [
          "Bagian paling seru: MENULIS! Setelah memahami teori dan perbandingan, saatnya kamu praktik menulis pantun dan syair sendiri. Ikuti panduan berikut:",
          "",
          "• PANDUAN MENULIS PANTUN:",
          "",
          "  Langkah 1 — Tentukan TEMA",
          "  Apa pesan yang ingin kamu sampaikan? Nasihat? Sindiran? Cinta? Teka-teki? Tentukan tema dulu.",
          "  ✓ Tema populer: persahabatan, pendidikan, cinta tanah air, lingkungan, keluarga.",
          "",
          "  Langkah 2 — BUAT ISI (baris 3-4) DULU",
          "  Tulis pesan inti dalam 2 baris yang bersajak. Ini adalah 'daging' pantunmu.",
          "  ✓ Contoh isi: \"Rajin-rajinlah membaca buku / Ilmu pengetahuan bertambah luas.\" (a-a)",
          "",
          "  Langkah 3 — BUAT SAMPIRAN (baris 1-2)",
          "  Cari 2 baris yang bersajak sama dengan isi. Sampiran biasanya dari alam atau benda sehari-hari. Ingat: sampiran tidak perlu nyambung dengan isi!",
          "  ✓ Contoh sampiran untuk isi di atas: \"Pergi ke pasar membeli sukun / Jangan lupa membeli buku.\" (a-a)",
          "",
          "  Langkah 4 — GABUNGKAN dengan pola a-b-a-b",
          "  Sampiran baris 1 (a) — Sampiran baris 2 (b) — Isi baris 3 (a) — Isi baris 4 (b)",
          "  ✓ Hasil akhir: \"Pergi ke pasar membeli sukun (a-sampiran) / Jangan lupa membeli buku (b-sampiran) / Rajin-rajinlah membaca buku (a-isi) / Ilmu pengetahuan bertambah luas (b-isi).\"",
          "",
          "  Langkah 5 — HITUNG SUKU KATA",
          "  Pastikan setiap baris memiliki 8—12 suku kata. Baca keras-keras dan hitung dengan jari!",
          "",
          "• PANDUAN MENULIS SYAIR:",
          "",
          "  Langkah 1 — Tentukan PESAN UTAMA",
          "  Syair biasanya lebih panjang. Tentukan satu pesan utama yang akan dikembangkan dalam beberapa bait.",
          "  ✓ Contoh pesan: 'Pentingnya berbakti kepada orang tua'.",
          "",
          "  Langkah 2 — BUAT BAIT PERTAMA",
          "  4 baris bersajak a-a-a-a, semua baris berisi nasihat/perkenalan tema.",
          "  ✓ \"Wahai ananda cahaya mata / Hormatilah ibu bapak slalu / Mereka yang menjagamu dari kecil / Jangan kau lukai hati mereka.\"",
          "",
          "  Langkah 3 — KEMBANGKAN KE BAIT BERIKUTNYA",
          "  Bait 2 melanjutkan bait 1. Bait 3 melanjutkan bait 2. Jaga konsistensi sajak dan tema.",
          "",
          "  Langkah 4 — PERIKSA SAJAK",
          "  Baris 1, 2, 3, dan 4 harus memiliki bunyi akhir yang SAMA. Tidak boleh ada yang berbeda!",
          "",
          "PENTING: Saat menulis, jangan terlalu khawatir soal 'bagus atau tidak' di percobaan pertama. Yang penting: ikuti STRUKTUR dengan benar. Keindahan akan datang dengan latihan!",
        ],
        contoh: [
          "CONTOH PROSES KREATIF MENULIS PANTUN (tema: persahabatan):",
          "",
          "Langkah 1: Tema = Persahabatan sejati.",
          "",
          "Langkah 2: Buat isi dulu (baris 3-4, sajak a-a):",
          "\"Sahabat sejati di kala susah / Menemani slalu tak pernah lengah.\"",
          "",
          "Langkah 3: Buat sampiran (baris 1-2, sajak a-b — menyesuaikan isi a-a):",
          "Sampiran baris 1 (sajak a, sama dengan 'susah'): \"Burung elang terbang di udara\"",
          "Sampiran baris 2 (sajak b, sama dengan 'lengah'): \"Mencari mangsa di waktu senja\"",
          "",
          "Langkah 4: Gabungkan (a-b-a-b):",
          "\"Burung elang terbang di udara (a) / Mencari mangsa di waktu senja (b) / Sahabat sejati di kala susah (a) / Menemani slalu tak pernah lengah (b).\"",
          "",
          "Langkah 5: Hitung suku kata:",
          "Baris 1: Bu-rung e-lang ter-bang di u-da-ra = 9 suku kata ✓",
          "Baris 2: Men-ca-ri mang-sa di wak-tu sen-ja = 9 suku kata ✓",
          "Baris 3: Sa-ha-bat se-ja-ti di ka-la su-sah = 10 suku kata ✓",
          "Baris 4: Me-ne-ma-ni sla-lu tak per-nah le-ngah = 10 suku kata ✓",
          "→ Semua dalam rentang 8-12! Berhasil!",
          "",
          "CONTOH PROSES KREATIF MENULIS SYAIR (tema: berbakti):",
          "",
          "Bait 1 (pembukaan):",
          "\"Wahai ananda cahaya mata / Hormatilah ibu bapak slalu / Mereka yang menjagamu sejak kecil / Jangan kau lukai hati mereka.\"",
          "",
          "Bait 2 (lanjutan — alasan):",
          "\"Ibu mengandungmu sembilan bulan / Bapak bekerja siang dan malam / Demi melihatmu tumbuh dewasa / Janganlah kau lupa jasa mereka.\"",
          "",
          "Bait 3 (penutup — kesimpulan):",
          "\"Berbaktilah slama mereka ada / Sebelum nyawa berpisah dari raga / Dunia fana tak berarti lagi / Jika orang tua sudah tiada.\"",
          "",
          "Perhatikan: setiap bait sajaknya a-a-a-a, semua baris isi, dan tema berkelanjutan dari bait 1 ke 3.",
        ],
        catatan: "Tips penting: penulis pantun pemula sering terjebak membuat sampiran yang terlalu 'dipaksakan' sehingga tidak bermakna. Sampiran BOLEH tidak nyambung dengan isi, tetapi sampiran harus tetap memiliki MAKNA — jangan asal rima! Sampiran yang baik adalah yang puitis dan indah didengar.",
      },
      {
        judul: "Perbandingan dengan Puisi Rakyat Lain",
        isi: [
          "Selain pantun dan syair, Indonesia memiliki beragam puisi rakyat lainnya. Memahami perbedaannya akan memperkaya wawasan sastramu. Berikut perbandingan dengan tiga puisi rakyat lain:",
          "",
          "• GURINDAM — Puisi rakyat 2 baris, sajak a-a, baris 1 = SEBAB, baris 2 = AKIBAT.",
          "  Berbeda dengan pantun (4 baris, sampiran-isi) dan syair (4 baris, semua isi, sajak sama), gurindam hanya 2 baris dengan hubungan SEBAB-AKIBAT yang khas.",
          "  ✓ \"Jika engkau rajin membaca / Ilmu pengetahuan akan bertambah.\"",
          "  Persamaan: sama-sama puisi rakyat, sama-sama terikat aturan, sama-sama berisi nasihat.",
          "",
          "• KARMINA — Puisi rakyat yang mirip pantun tetapi hanya 2 baris. Juga disebut 'pantun kilat' atau 'pantun dua baris'.",
          "  Ciri: 2 baris, sajak a-a, baris 1 = sampiran, baris 2 = isi. Berbeda dengan gurindam (2 baris, sebab-akibat), karmina berpola sampiran-isi seperti pantun versi pendek.",
          "  ✓ \"Dahulu parang, sekarang besi (sampiran) / Dahulu sayang, sekarang benci (isi).\"",
          "  Persamaan dengan pantun: ada sampiran dan isi. Perbedaan: jumlah baris (2 vs 4).",
          "",
          "• SELOKA — Puisi rakyat yang mirip pantun tetapi lebih panjang (bisa 6-8 baris per bait) dan biasanya berisi sindiran atau nasihat dengan gaya humor.",
          "  Ciri: jumlah baris tidak tetap (biasanya genap), sajak a-b-a-b-a-b (untuk 6 baris) atau a-b-a-b-c-d-c-d (untuk 8 baris), isi nyambung antar baris.",
          "  ✓ \"Anak pak tani menggembala kambing / Kambing merumput di tepi kali / Hidup di dunia janganlah bimbang / Rezeki Tuhan sudah pasti / Berusaha keras jangan pantang menyerah / Pasti sukses di kemudian hari.\"",
          "  Persamaan dengan pantun: ada pola sajak. Perbedaan: jumlah baris lebih panjang dan isi berkesinambungan.",
          "",
          "TABEL PERBANDINGAN LENGKAP:",
          "",
          "  JENIS        BARIS        SAJAK        STRUKTUR",
          "  Pantun       4            a-b-a-b      sampiran + isi",
          "  Syair        4            a-a-a-a      semua isi",
          "  Gurindam     2            a-a          sebab + akibat",
          "  Karmina      2            a-a          sampiran + isi",
          "  Seloka       6-8          bervariasi   naratif/bercerita",
          "",
          "PENTING: Tabel di atas adalah ciri STANDAR. Dalam praktiknya, ada variasi lokal di berbagai daerah. Misalnya di Jawa, ada puisi rakyat 'pantun kilat' yang hanya 2 baris — ini sebenarnya karmina, bukan pantun baku. Selalu cek konteks daerahnya!",
        ],
        contoh: [
          "Contoh perbandingan LIMA jenis puisi rakyat dalam SATU tema (nasihat tentang ilmu):",
          "",
          "PANTUN (4 baris, a-b-a-b, sampiran+isi):",
          "\"Pergi ke hutan memetik buah / Buah delima rasanya manis / Tuntutlah ilmu sepanjang hayat / Agar hidupmu tidak menyesal.\"",
          "",
          "SYAIR (4 baris, a-a-a-a, semua isi):",
          "\"Wahai ananda yang bersekolah / Tuntutlah ilmu dengan gembira / Ilmu bekal di dunia dan akhirat / Janganlah kau sia-siakan waktu.\"",
          "",
          "GURINDAM (2 baris, a-a, sebab-akibat):",
          "\"Jika engkau rajin membaca / Ilmu pengetahuan bertambah banyak.\"",
          "",
          "KARMINA (2 baris, a-a, sampiran+isi):",
          "\"Bulan purnama di malam hari / Rajin belajar pasti berprestasi.\"",
          "",
          "SELOKA (6 baris, a-b-a-b-a-b, naratif):",
          "\"Anak sekolah membawa buku / Berangkat pagi ke sekolah / Ilmu dicari dengan tekun / Agar hidup tidak tersesat / Masa depan cerah menanti / Jika belajar dengan giat.\"",
          "",
          "BENAR (perbedaan gurindam dan karmina): \"Gurindam = sebab-akibat. Karmina = sampiran-isi. Meskipun sama-sama 2 baris, keduanya berbeda!\"",
          "SALAH (menyamakan semua puisi rakyat 2 baris): \"Gurindam dan karmina itu sama saja, namanya beda.\"",
        ],
        catatan: "Kekayaan puisi rakyat Indonesia tidak terbatas pada lima jenis di atas. Masih ada banyak bentuk lain seperti MANTERA (puisi magis), TALIBUN (puisi rakyat Minangkabau), PANGRUMAN (puisi rakyat Sunda), dan DEDEHON (teka-teki tradisional). Setiap daerah punya kekhasan masing-masing!",
      },
    ],
    rangkuman: [
      "Pantun: 4 baris, sajak a-b-a-b, baris 1-2 sampiran (pengantar alam/kiasan), baris 3-4 isi (pesan), 8-12 suku kata per baris. Isi tersirat.",
      "Syair: 4 baris, sajak a-a-a-a, semua baris adalah isi (tanpa sampiran), 8-14 suku kata per baris. Berasal dari sastra Arab-Melayu, tokoh utama: Hamzah Fansuri (Syair Perahu). Isi tersurat.",
      "Jenis pantun: nasihat, jenaka, teka-teki, percintaan, adat, agama. Masing-masing punya ciri khas dari pilihan kata dan tujuannya.",
      "Kaidah kebahasaan pantun dan syair: diksi klasik (tiada, jua, tamsil, bak, maka), konjungsi naratif (syahdan, hatta, arkian), dan bahasa kiasan (personifikasi, metafora, asonansi, aliterasi).",
      "Menulis pantun: tentukan tema → buat isi (baris 3-4, sajak a-a) → buat sampiran (baris 1-2, sajak a-b) → gabung a-b-a-b → hitung suku kata (8-12).",
      "Menulis syair: tentukan pesan → buat bait pertama (4 baris a-a-a-a, semua isi) → kembangkan ke bait berikutnya → jaga konsistensi sajak dan tema.",
      "Puisi rakyat lain: Gurindam (2 baris, a-a, sebab-akibat), Karmina (2 baris, a-a, sampiran-isi), Seloka (6-8 baris, sajak bervariasi, naratif humor/sindiran).",
    ],
  },

  latihan: makeSoal([
    // 5 Soal Pilihan Ganda (4 opsi)
    ["Perbedaan paling mendasar antara pantun dan syair adalah...", ["Jumlah baris per bait", "Pantun memiliki sampiran, syair tidak", "Pantun bersajak, syair tidak", "Syair lebih panjang dari pantun"], 1, "Pantun memiliki sampiran (baris 1-2 sebagai pengantar), sedangkan syair TIDAK memiliki sampiran — semua baris adalah isi. Jumlah barisnya sama (4 baris)."],
    ["Pantun nasihat biasanya mengandung kata-kata berikut, KECUALI...", ["Mari", "Hendaklah", "Coba tebak", "Janganlah"], 2, "'Coba tebak' adalah ciri pantun TEKA-TEKI, bukan nasihat. Pantun nasihat menggunakan kata ajakan seperti mari, hendaklah, janganlah, rajin-rajinlah."],
    ["Syair 'Wahai muda kenali dirimu / Ialah perahu tamsil hidupmu' mengandung majas...", ["Personifikasi", "Metafora", "Hiperbola", "Ironi"], 1, "Metafora karena 'hidup' diibaratkan 'perahu' secara langsung tanpa kata pembanding (seperti, bagai, laksana)."],
    ["Kata 'syahdan', 'hatta', dan 'arkian' dalam syair berfungsi sebagai...", ["Kata sifat", "Konjungsi naratif", "Kata benda", "Kata kerja"], 1, "Kata-kata tersebut adalah konjungsi naratif yang digunakan dalam syair untuk menunjukkan urutan waktu atau kelanjutan cerita."],
    ["Berikut yang BUKAN merupakan jenis puisi rakyat adalah...", ["Karmina", "Seloka", "Novel", "Gurindam"], 2, "Novel adalah prosa naratif panjang, bukan puisi rakyat. Karmina, Seloka, dan Gurindam adalah jenis puisi rakyat Indonesia."],

    // 3 Soal Betul/Salah (2 opsi)
    ["Pernyataan: 'Pantun jenaka dan pantun nasihat memiliki pola sajak yang berbeda.'", ["Betul", "Salah"], 1, "SALAH. Semua jenis pantun — baik nasihat, jenaka, teka-teki, maupun lainnya — memiliki pola sajak yang SAMA, yaitu a-b-a-b. Yang membedakan adalah isi pesannya, bukan pola sajaknya."],
    ["Pernyataan: 'Syair berasal dari tradisi sastra Arab-Melayu dan tokoh pentingnya adalah Hamzah Fansuri.'", ["Betul", "Salah"], 0, "BETUL. Syair berasal dari bahasa Arab 'syi'r' dan dikembangkan di Nusantara bersamaan dengan penyebaran Islam. Hamzah Fansuri (abad ke-16 dari Aceh) adalah tokoh penting dengan karya Syair Perahu."],
    ["Pernyataan: 'Gurindam dan karmina sama-sama terdiri dari 2 baris, tetapi struktur isinya berbeda.'", ["Betul", "Salah"], 0, "BETUL. Gurindam: baris 1 = sebab, baris 2 = akibat. Karmina: baris 1 = sampiran, baris 2 = isi. Meskipun sama-sama 2 baris, struktur logisnya berbeda."],

    // 2 Soal Isian Singkat (4 opsi)
    ["Puisi rakyat yang setiap baitnya terdiri dari 4 baris dengan sajak a-a-a-a dan semua barisnya adalah isi disebut...", ["Pantun", "Syair", "Gurindam", "Seloka"], 1, "Syair: 4 baris, sajak a-a-a-a, semua baris isi (tanpa sampiran)."],
    ["Tokoh sastrawan Aceh abad ke-16 yang menulis Syair Perahu, Syair Dagang, dan Syair Burung Pingai adalah...", ["Raja Ali Haji", "Hamzah Fansuri", "Chairil Anwar", "Muhammad Yamin"], 1, "Hamzah Fansuri adalah pelopor syair Melayu klasik dari Aceh. Karyanya mengandung ajaran tasawuf dan filsafat kehidupan."],
  ]),

  praktik: {
    petunjuk: "Buatlah SATU bait PANTUN dan SATU bait SYAIR dengan tema \"PENTINGNYA MENJAGA KEBERSIHAN LINGKUNGAN\"!\n\n=== KETENTUAN PANTUN ===\n1. Terdiri dari 4 baris.\n2. Sajak a-b-a-b.\n3. Baris 1-2 = sampiran (pengantar dari alam/benda sehari-hari).\n4. Baris 3-4 = isi (ajakan menjaga kebersihan).\n5. Setiap baris 8—12 suku kata.\n6. Sampiran TIDAK harus nyambung dengan isi, tetapi harus puitis.\n\n=== KETENTUAN SYAIR ===\n1. Terdiri dari 4 baris.\n2. Sajak a-a-a-a (SEMUA baris bunyi akhir sama).\n3. SEMUA baris adalah isi — tidak ada sampiran.\n4. Setiap baris 8—14 suku kata.\n5. Pesan disampaikan secara langsung (tersurat).\n\n=== LANGKAH PENGERJAAN ===\n1. Tulis PANTUN terlebih dahulu.\n2. Tulis SYAIR setelahnya.\n3. Di bawah setiap karya, tuliskan ANALISIS singkat:\n   - Pola sajak (a-b-a-b atau a-a-a-a)\n   - Jumlah suku kata setiap baris\n   - Bagian sampiran (khusus pantun) atau semua isi (khusus syair)\n4. Gunakan diksi klasik untuk memperindah bahasa (contoh: tiada, jua, wahai, hendaklah).\n5. Periksa kembali sebelum dikumpulkan.",
    tips: [
      "Untuk pantun: tulis dulu baris ISI (3-4) yang berisi pesan kebersihan, lalu buat sampiran (1-2) yang rimanya cocok. Contoh isi: 'Mari kita jaga lingkungan asri / Buanglah sampah pada tempatnya.' (rima a-a). Maka sampiran harus a-b: baris 1 berima dengan 'asri', baris 2 berima dengan 'tempatnya'.",
      "Untuk syair: semua baris harus berima SAMA. Pilih satu bunyi akhir yang mudah (misal -ah, -kan, -ku, -mu) dan gunakan untuk keempat baris. Contoh semua baris berakhiran 'ku': 'Hendaklah aku menjaga alamku / Lingkungan bersih impianku / Kupilah sampah dengan tanganku / Hijau bumiku kan slalu.'",
      "Hitung suku kata dengan cermat! Caranya: ucapkan baris dengan keras sambil menepuk meja setiap suku kata. Pantun: 8-12 suku kata. Syair: 8-14 suku kata. Jangan kurang atau lebih!",
      "Gunakan kamus atau KBBI untuk mencari kata-kata klasik yang tepat. Contoh: 'asri' (indah), 'lestari' (abadi), 'cemar' (kotor), 'rahmat' (karunia), 'anugerah' (pemberian). Kata-kata ini akan membuat puisimu lebih berbobot.",
      "Periksa sajak: lingkari huruf terakhir setiap baris. Apakah pola pantunmu a-b-a-b? Apakah syairmu a-a-a-a? Jika tidak, perbaiki pilihan kata di akhir baris.",
      "Jangan takut bereksperimen dengan sampiran yang kreatif! Sampiran bisa dari apa saja: gunung, laut, burung, bunga, pasar, dapur — selama rimanya cocok. Semakin puitis semakin baik!",
    ],
    contoh: "=== CONTOH JAWABAN ===\n\n=== PANTUN (Tema: Kebersihan Lingkungan) ===\n\"Pergi ke kebun memetik jambu (a) — sampiran\nJambu merah di dalam peti (b) — sampiran\nMari kita rawat bumi ini (a) — isi\nAgar bersih hijau dan asri (b) — isi\"\n\nAnalisis Pantun:\n- Pola sajak: a-b-a-b (jambu-peti-ini-asri) ✓\n- Sampiran: baris 1-2 ('Pergi ke kebun memetik jambu / Jambu merah di dalam peti')\n- Isi: baris 3-4 ('Mari kita rawat bumi ini / Agar bersih hijau dan asri')\n- Jumlah suku kata:\n  Baris 1: Per-gi ke ke-bun me-me-tik jam-bu = 9 suku kata ✓\n  Baris 2: Jam-bu me-rah di da-lam pe-ti = 8 suku kata ✓\n  Baris 3: Ma-ri ki-ta ra-wat bu-mi i-ni = 9 suku kata ✓\n  Baris 4: A-gar ber-sih hi-jau dan as-ri = 8 suku kata ✓\n  Semua dalam rentang 8-12! ✓\n\n=== SYAIR (Tema: Kebersihan Lingkungan) ===\n\"Wahai kawan jagalah alam slalu (a)\nBuanglah sampah pada tempatnya (a)\nLingkungan bersih udarapun segar (a)\nHidup menjadi nyaman dan sehat (a)\"\n\nAnalisis Syair:\n- Pola sajak: a-a-a-a (slalu-tempatnya-segar-sehat) — semua baris berima 'a', dengan variasi bunyi akhir -u, -a, -ar, -at ✓\n- Semua baris adalah ISI: tidak ada sampiran ✓\n- Jumlah suku kata:\n  Baris 1: Wa-hai ka-wan ja-ga-lah a-lam sla-lu = 10 suku kata ✓\n  Baris 2: Bu-ang-lah sam-pah pa-da tem-pat-nya = 9 suku kata ✓\n  Baris 3: Ling-kung-an ber-sih u-da-ra-pun se-gar = 10 suku kata ✓\n  Baris 4: Hi-dip men-ja-di nya-man dan se-hat = 9 suku kata ✓\n  Semua dalam rentang 8-14! ✓\n\nPerbandingan:\n- Pantun: ada sampiran (alam/benda), isi tersirat, sajak a-b-a-b\n- Syair: semua isi, pesan langsung, sajak a-a-a-a\n- Keduanya 4 baris, tapi STRUKTUR dan POLA SAJAKNYA berbeda!",
  },

  kuis: makeSoal([
    ["Pantun dan syair memiliki kesamaan dalam hal...", ["Jumlah baris per bait (4 baris)", "Pola sajak", "Adanya sampiran", "Berasal dari sastra Arab"], 0, "Pantun dan syair sama-sama terdiri dari 4 baris per bait. Perbedaannya pada pola sajak (a-b-a-b vs a-a-a-a) dan ada/tidaknya sampiran."],
    ["Jika sebuah puisi rakyat memiliki sajak a-b-a-b dan baris 1-2 tidak berhubungan dengan isi, maka puisi tersebut pasti...", ["Syair", "Gurindam", "Pantun", "Seloka"], 2, "Ciri khas PANTUN: sajak a-b-a-b, baris 1-2 = sampiran (pengantar yang tidak berhubungan logis dengan isi)."],
    ["Syair Perahu adalah karya sastra terkenal dari Hamzah Fansuri. Syair tersebut berisi tentang...", ["Kisah cinta raja dan putri", "Nasihat spiritual menggunakan metafora perahu", "Petualangan nelayan di laut", "Sejarah perdagangan di Aceh"], 1, "Syair Perahu menggunakan metafora perahu sebagai kehidupan manusia yang berlayar menuju Tuhan. Berisi nasihat tasawuf dan spiritual."],
    ["Kata 'tamsil' dalam syair 'Ialah perahu tamsil hidupmu' memiliki arti...", ["Contoh", "Ibarat", "Perahu", "Hidup"], 1, "'Tamsil' berarti 'ibarat' atau 'perumpamaan'. Dalam konteks ini: 'hidup itu ibarat perahu'."],
    ["Berikut ini yang merupakan contoh karmina adalah...", ["Kalau ada jarum yang patah / Jangan simpan di dalam peti", "Barang siapa meninggalkan salat / Hidupnya gelap penuh khilafat", "Dahulu parang, sekarang besi / Dahulu sayang, sekarang benci", "Buah manggis di tepi rawa / Si burung elang terbang melayang"], 2, "Karmina adalah puisi rakyat 2 baris dengan pola sampiran-isi. 'Dahulu parang, sekarang besi (sampiran) / Dahulu sayang, sekarang benci (isi)' adalah contoh karmina."],
    ["Perbedaan gurindam dan karmina yang paling tepat adalah...", ["Jumlah baris (2 vs 4)", "Gurindam sebab-akibat, karmina sampiran-isi", "Gurindam bersajak, karmina tidak", "Karmina lebih panjang"], 1, "Gurindam: baris 1 = sebab/syarat, baris 2 = akibat/hasil. Karmina: baris 1 = sampiran, baris 2 = isi. Keduanya sama-sama 2 baris dan bersajak a-a."],
    ["Dalam menulis pantun, langkah yang paling tepat adalah...", ["Tulis sampiran dulu, lalu isi", "Tulis isi dulu, lalu sampiran yang rimanya cocok", "Tulis keempat baris sekaligus", "Tentukan sajak di akhir"], 1, "Cara termudah: buat dulu baris ISI (3-4) yang berisi pesan, lalu buat SAMPIRAN (1-2) yang rimanya cocok dengan isi. Ini memudahkan karena pesan inti sudah ditentukan."],
    ["Seloka berbeda dari pantun karena seloka memiliki ciri...", ["Hanya 2 baris per bait", "Jumlah baris lebih panjang (6-8 baris) dan berkesinambungan", "Tidak bersajak", "Berasal dari Arab"], 1, "Seloka biasanya terdiri dari 6-8 baris per bait, bersifat naratif, dan sering berisi sindiran humor. Pantun hanya 4 baris dan mandiri per bait."],
    ["Kata 'syahdan' dalam syair termasuk ke dalam kaidah kebahasaan berupa...", ["Diksi klasik jenis kata kerja", "Konjungsi naratif untuk memulai cerita", "Majas personifikasi", "Kata sifat"], 1, "'Syahdan' adalah konjungsi naratif yang digunakan dalam sastra Melayu klasik untuk memulai atau melanjutkan cerita. Artinya kurang lebih 'maka tersebutlah' atau 'alkisah'."],
    ["Jika sebuah puisi rakyat 4 baris memiliki sajak a-a-a-a dan keempat barisnya merupakan pesan langsung tentang nasihat, maka puisi tersebut adalah...", ["Pantun nasihat", "Syair didaktik", "Seloka", "Karmina"], 1, "Syair DIDAKTIK adalah syair yang berisi nasihat atau ajaran. Ciri: 4 baris, a-a-a-a, semua baris isi. Ini BUKAN pantun (pola sajak dan struktur isi berbeda)."],
  ]),
}

export default konten
