import type { Konten } from "../types"
import { makeSoal } from "../types"

const konten: Konten = {
  belajar: {
    tujuan: [
      "Menganalisis unsur 5W+1H secara mendalam: fungsi setiap elemen dan teknik merangkainya dalam teras berita",
      "Memahami dan menerapkan struktur piramida terbalik: mengapa lead adalah bagian terpenting dari berita",
      "Membedakan fakta, opini, dan opini narasumber dalam teks berita secara kritis",
      "Menguasai kaidah kebahasaan jurnalistik: kalimat efektif, kosakata baku, kalimat langsung, dan atribusi",
      "Menulis teks berita tentang peristiwa sekolah dengan teknik jurnalistik yang tepat dan objektif",
    ],
    materi: [
      {
        judul: "Menguak 5W+1H: Bukan Sekadar Identifikasi",
        isi: [
          "Di kelas VII kamu sudah belajar mengidentifikasi unsur 5W+1H dalam berita. Sekarang saatnya naik level — bukan sekadar menemukan WHAT atau WHO, tetapi MEMAHAMI bagaimana setiap unsur dikemas agar berita berbobot dan enak dibaca.",
          "",
          "Rumus 5W+1H adalah kerangka dasar setiap berita. Namun, wartawan profesional tidak sekadar mencantumkan keenam unsur itu asal ada. Setiap unsur harus diolah dengan strategi tertentu.",
          "",
          "1. WHAT — Apa yang terjadi?",
          "  Jangan hanya menulis peristiwanya. Tentukan SUDUT PANDANG (angle) berita. Peristiwa yang sama bisa ditulis dari sudut berbeda.",
          "  • Sebuah lomba puisi bisa di-angle dari: kemenangan peserta, antusiasme penonton, atau inovasi panitia",
          "  • PENGGEMPA BUMI bisa di-angle dari: dampak korban, respons pemerintah, atau kisah penyelamatan",
          "  ✓ Angle tepat: 'Siswi Difabel SMPN 5 Juara Lomba Puisi Tingkat Kota' (angle: inklusivitas)",
          "  ✗ Angle datar: 'Lomba Puisi Diadakan di SMPN 5' (hanya melaporkan tanpa sudut pandang menarik)",
          "",
          "2. WHO — Siapa yang terlibat?",
          "  Sertakan identitas NARASUMBER secara lengkap: nama, jabatan, instansi. Jangan asal 'seorang warga' atau 'pihak sekolah'.",
          "  • Gunakan atribusi: nama lengkap + jabatan + keterangan lain jika relevan",
          "  • Pilih narasumber yang KREDIBEL — saksi mata, pejabat berwenang, atau ahli",
          "  • Wartawan profesional biasanya mewawancarai MINIMAL 2—3 narasumber untuk satu berita",
          "  ✓ 'Kepala SMPN 1 Jakarta, Drs. H. Ahmad Fauzi, M.Pd., menjelaskan...' (lengkap dan resmi)",
          "  ✗ 'Pihak sekolah mengatakan...' (terlalu samar, siapa 'pihak sekolah'?)",
          "",
          "3. WHEN & WHERE — Kapan dan di mana?",
          "  Detail waktu dan lokasi harus PRESISI. Bukan 'kemarin' atau 'di sekolah' — tetapi 'Senin (25/5/2026)' dan 'Lapangan Upacara SMPN 1 Jakarta'.",
          "  • WHEN: hari + tanggal + jam (jika penting). Gunakan format tanggal Indonesia.",
          "  • WHERE: nama tempat spesifik + alamat/kelurahan/kecamatan (semakin spesifik semakin baik)",
          "  ✓ 'Gempa terjadi pukul 07.45 WITA, Senin (12/5/2026), di Kecamatan Pemenang, Lombok Utara.'",
          "  ✗ 'Gempa terjadi kemarin pagi di Lombok.' (tidak presisi)",
          "",
          "4. WHY — Mengapa terjadi?",
          "  Ini adalah unsur yang MEMBEDAKAN berita dangkal dengan berita berkualitas. WHY memberikan KONTEKS dan PENJELASAN.",
          "  • Jelaskan penyebab, latar belakang, atau faktor pemicu",
          "  • WHY sering didukung oleh DATA dan KUTIPAN AHLI",
          "  • WHY yang baik menjawab pertanyaan lanjutan setelah WHAT diketahui",
          "  ✓ 'Kebakaran diduga akibat korsleting listrik di kios pakaian. Hal ini diperparah oleh minimnya hidran di area pasar.' (ada penjelasan sebab + faktor memperparah)",
          "  ✗ 'Kebakaran karena listrik.' (terlalu sederhana, tidak ada penjelasan)",
          "",
          "5. HOW — Bagaimana prosesnya?",
          "  HOW adalah KRONOLOGI. Paparkan urutan peristiwa secara logis dan kronologis.",
          "  • Gunakan konjungsi temporal: kemudian, setelah itu, sebelumnya, akhirnya",
          "  • HOW yang baik membuat pembaca seolah 'melihat' peristiwa itu terjadi",
          "  • Bedakan HOW untuk berita bencana (kronologi kejadian) vs HOW untuk berita prestasi (proses pencapaian)",
          "  ✓ 'Api pertama terlihat pukul 01.30 dari kios pakaian. Dalam 15 menit, api merambat ke 10 kios di sekitarnya. Pemadam kebakaran tiba pukul 01.45 dan berhasil memadamkan api pukul 04.00.'",
          "  ✗ 'Apinya besar dan cepat menyebar.' (tidak ada kronologi)",
          "",
          "[Ilustrasi: Diagram 5W+1H berbentuk peta pikiran dengan ikon modern. Pusat: 'BERITA'. Enam cabang berwarna berbeda: WHAT (tanda tanya biru dengan ikon peristiwa), WHO (ikon orang hijau), WHEN (jam merah), WHERE (pin lokasi oranye), WHY (ikon kaca pembesar ungu), HOW (ikon rantai/gear abu-abu). Masing-masing cabang memiliki sub-cabang berupa 'kata kunci strategi' — seperti 'angle', 'kredibilitas', 'presisi', 'konteks', 'kronologi'.]",
          "",
          "PENTING: Kelengkapan 5W+1H adalah syarat MINIMAL, bukan jaminan berita berkualitas. Berita hebat mengolah setiap unsur dengan STRATEGI — bukan sekadar mencantumkannya. Seorang wartawan pemula bertanya 'Apa yang terjadi?', wartawan senior bertanya 'Dari sudut mana cerita ini paling menarik?'",
        ],
        contoh: [
          "BENAR (5W+1H dengan angle dan narasumber kuat):",
          "\"Siswi Difabel SMPN 5 Juara Lomba Puisi Tingkat Kota — Seorang siswi penyandang disabilitas netra dari SMPN 5 Jakarta, Alya Rahmawati (WHAT + WHO), berhasil meraih juara pertama Lomba Baca Puisi Tingkat Kota Jakarta Pusat (WHAT detail) pada Jumat (23/5/2026) di Taman Ismail Marzuki (WHEN + WHERE). Kepala Dinas Pendidikan Jakarta Pusat, Dra. Sri Wahyuni, M.Pd., mengatakan prestasi ini membuktikan bahwa disabilitas bukan halangan untuk berprestasi (WHO narasumber + WHY sudut pandang). 'Alya membacakan puisi karya Sapardi Djoko Damono dengan penghayatan luar biasa. Para juri memberikan nilai tertinggi untuk aspek ekspresi dan intonasi,' jelas ketua dewan juri, Budi Santoso (WHO + HOW). Alya mengaku berlatih selama dua bulan dengan bantuan guru Bahasa Indonesia (HOW). (Kutipan langsung) 'Saya ingin membuktikan bahwa teman-teman disabilitas juga bisa berkarya,' ujar Alya. Lomba ini diikuti oleh 45 siswa dari 30 SMP se-Jakarta Pusat (info tambahan).\"",
          "",
          "SALAH (5W+1H ada tapi hambar dan tanpa angle):",
          "\"Lomba Baca Puisi Diadakan di Jakarta — Lomba baca puisi diadakan di Jakarta pada hari Jumat. Acara ini diikuti oleh banyak siswa. Seorang siswi berhasil menang. Lomba berjalan lancar dan meriah.\" (5W+1H ada semua? WHAT=lomba, WHO=siswi, WHEN=Jumat, WHERE=Jakarta, WHY=lancar, HOW=meriah — tapi TIDAK ADA detail, angle, narasumber, atau data spesifik. Berita ini tidak informatif.)",
        ],
        catatan: "Latihan sederhana: ambil satu berita dari koran atau portal berita online. Baca dengan saksama, lalu garis bawahi: apa angle berita itu? Siapa saja narasumbernya? Apakah WHY dan HOW dijelaskan dengan baik? Semakin sering kamu 'membedah' berita, semakin tajam kemampuan menulismu.",
      },
      {
        judul: "Piramida Terbalik: Seni Menyusun Informasi",
        isi: [
          "Struktur piramida terbalik adalah fondasi utama penulisan berita. Konsep ini sederhana tapi revolusioner: INFORMASI PALING PENTING DILETAKKAN DI PALING ATAS. Semakin ke bawah, informasi semakin kurang penting. Mengapa demikian?",
          "",
          "• Alasan PIramida Terbalik:",
          "  • Pembaca modern memiliki waktu terbatas — mereka ingin langsung mendapat inti berita",
          "  • Jika berita dipotong dari bawah karena keterbatasan kolom, informasi penting tetap tersampaikan",
          "  • Lead yang kuat membuat pembaca TERTARIK melanjutkan ke detail",
          "  • Prinsip 'jangan kubur informasimu' — jangan sembunyikan inti di tengah atau akhir paragraf",
          "",
          "Berikut struktur lengkap piramida terbalik dalam berita:",
          "",
          "[Ilustrasi: Piramida terbalik berbentuk segitiga terbalik dengan 3 lapisan. Lapisan ATAS (terlebar, warna biru tua) — JUDUL + TERAS BERITA: WHAT + WHO + WHEN + WHERE, informasi paling penting. Lapisan TENGAH (sedang, warna biru sedang) — TUBUH BERITA: WHY + HOW + kutipan narasumber, detail penjelasan. Lapisan BAWAH (paling sempit, warna biru muda) — EKOR BERITA: informasi tambahan, konteks, imbauan, data pelengkap. Panah menunjuk ke bawah dengan teks 'TINGKAT KEPENTINGAN MENURUN'.]",
          "",
          "1. JUDUL (Headline) — 'Wajah' Berita",
          "  • Judul adalah gerbang pertama. Judul buruk = berita tidak dibaca.",
          "  • Ciri judul baik: SP (Subjek-Predikat), aktif, ≤ 8 kata, mengandung unsur terpenting",
          "  • Gunakan KALIMAT AKTIF, bukan pasif",
          "  ✓ 'Tim Basket SMPN 1 Juara Turnamen antar-SMP se-Jakarta' (SP aktif, 8 kata, jelas)",
          "  ✗ 'Turnamen Basket yang Diikuti oleh SMPN 1 Berhasil Dimenangkan' (pasif, 10 kata, bertele-tele)",
          "",
          "2. TERAS BERITA (Lead) — 'Jantung' Berita",
          "  • Paragraf pertama, biasanya 1—3 kalimat, menjawab 4 unsur terpenting: WHAT + WHO + WHEN + WHERE",
          "  • WHY dan HOW ditunda ke tubuh berita (kecuali sangat penting)",
          "  • Lead harus MANDIRI — jika hanya lead yang dibaca, pembaca sudah tahu intinya",
          "  • Bisa ditulis dengan beberapa model:",
          "  a. Ringkasan (summary lead): langsung ke inti — paling umum",
          "  b. Kutipan (quote lead): buka dengan kutipan narasumber yang mencolok",
          "  c. Deskripsi (descriptive lead): gambarkan suasana untuk soft news",
          "  d. Pertanyaan (question lead): buka dengan pertanyaan provokatif",
          "  ✓ Summary lead: 'Gempa bumi magnitudo 5,2 mengguncang Lombok Utara, NTB, Senin (12/5/2026) pukul 07.45 WITA. BMKG memastikan gempa tidak berpotensi tsunami.'",
          "  ✓ Descriptive lead: 'Senyum merekah menghiasi wajah 30 siswa SMPN 1 Jakarta saat mereka menerima piagam penghargaan di Aula sekolah, Selasa (20/5/2026).'",
          "  ✗ Lead bertele-tele: 'Pada hari Senin yang cerah, tepatnya tanggal 12 Mei 2026, terjadi sebuah peristiwa gempa bumi yang mengguncang wilayah Lombok Utara di Nusa Tenggara Barat.'",
          "",
          "3. TUBUH BERITA (Body) — Penjelasan dan Detail",
          "  • Berisi WHY + HOW + kutipan narasumber + data pendukung",
          "  • Kembangkan dengan pola: KLAIM → BUKTI → PENJELASAN",
          "  • Setiap paragraf sebaiknya memiliki SATU ide pokok",
          "  • Sertakan MINIMAL 1—2 kutipan langsung dari narasumber",
          "  • Gunakan konjungsi untuk menghubungkan antarkalimat: sementara itu, menurut, selain itu, sebelumnya",
          "",
          "4. LATAR BELAKANG (Background) — Informasi Konteks",
          "  • Bukan struktur wajib, tapi sangat membantu pembaca memahami berita",
          "  • Berupa informasi terkait peristiwa serupa di masa lalu, data statistik, atau perbandingan",
          "  • Letakkan di tubuh berita setelah inti penjelasan",
          "  ✓ 'Sebelumnya, gempa berkekuatan 5,8 juga mengguncang wilayah yang sama pada Januari 2026 dan menyebabkan 12 rumah rusak.'",
          "",
          "5. EKOR BERITA (Leg) — Informasi Tambahan",
          "  • Bagian terakhir, bisa berisi imbauan, rencana ke depan, atau data pelengkap",
          "  • Jika dipotong, berita tetap utuh dan informatif",
          "  • Bukan 'penutup' seperti dalam cerita — tidak perlu kesimpulan dramatis",
          "  ✓ 'BMKG mengimbau masyarakat tetap tenang. Posko siaga telah didirikan di Kantor Bupati Lombok Utara. Masyarakat dapat menghubungi nomor darurat 117 untuk informasi lebih lanjut.'",
          "",
          "Tips: Saat menulis, susun dulu INFORMASI TERPENTING ke KURANG PENTING. Tanyakan: 'Jika pembaca hanya punya waktu 10 detik, apa yang WAJIB mereka tahu?' Itulah yang harus ada di lead.",
        ],
        contoh: [
          "Perhatikan bagaimana piramida terbalik diterapkan dalam berita sekolah berikut:",
          "",
          "JUDUL: Siswa SMPN 3 Sabet Emas Olimpiade Sains Nasional di Yogyakarta",
          "",
          "TERAS (WHAT+WHO+WHEN+WHERE): \"Seorang siswa SMPN 3 Jakarta, Raihan Al-Farizi, berhasil meraih medali emas dalam Olimpiade Sains Nasional (OSN) bidang Fisika yang digelar di Universitas Gadjah Mada, Yogyakarta, pada 15—20 Mei 2026.\"",
          "",
          "TUBUH 1 (HOW + detail): \"Raihan mengalahkan 250 peserta dari seluruh Indonesia setelah melalui tiga babak penyisihan. Babak pertama berupa tes tertulis, babak kedua praktikum laboratorium, dan babak final berupa presentasi ilmiah. 'Soal paling sulit ada di babak praktikum — kami diminta merancang alat pendeteksi gempa sederhana dari barang bekas,' cerita Raihan saat ditemui di sekolahnya, Senin (22/5/2026).\"",
          "",
          "TUBUH 2 (WHY + kutipan + background): \"Keberhasilan Raihan tidak terlepas dari kerja kerasnya berlatih selama satu tahun. Setiap akhir pekan, ia menghabiskan waktu di laboratorium sekolah di bawah bimbingan guru Fisika, Bapak Dwi Hartono. 'Raihan adalah siswa yang tekun dan memiliki rasa ingin tahu tinggi. Ia tidak pernah puas dengan satu jawaban — selalu bertanya 'mengapa' dan 'bagaimana',' ujar Pak Dwi. Tahun lalu, Raihan juga meraih perak di OSN tingkat provinsi.\"",
          "",
          "EKOR (info tambahan + rencana): \"Kepala SMPN 3 Jakarta, Dr. Hj. Nurul Aini, M.Pd., menyampaikan apresiasi setinggi-tingginya. 'Prestasi ini membuktikan bahwa siswa SMPN 3 mampu bersaing di tingkat nasional.' Raihan berencana mengikuti OSN tingkat ASEAN yang akan digelar di Kuala Lumpur pada November mendatang. Sekolah menyiapkan program pembinaan khusus untuk persiapan tersebut.\"",
          "",
          "BENAR: Setiap bagian menduduki fungsi yang jelas. Lead langsung ke inti, tubuh mengembangkan detail, ekor menutup dengan informasi tambahan.",
          "SALAH: 'Hari ini kami berbahagia. SMPN 3 Jakarta kembali menorehkan prestasi. Seorang siswa bernama Raihan Al-Farizi berhasil meraih medali emas...' (Lead bertele-tele, informasi penting ditunda — melanggar prinsip piramida terbalik.)",
        ],
        catatan: "Coba cek berita di portal favoritmu: kompas.com, detik.com, atau mediaindonesia.com. Apakah mereka menggunakan piramida terbalik? Jawabannya: YA, semua media arus utama menggunakan struktur ini. Baca lead, lalu bandingkan dengan paragraf terakhir — kamu akan melihat 'penurunan kepentingan' informasi secara jelas.",
      },
      {
        judul: "Bahasa Jurnalistik: Kaidah yang Wajib Dikuasai",
        isi: [
          "Menulis berita tidak sama dengan menulis cerpen atau laporan. Berita memiliki KAIDAH BAHASA khusus yang disebut bahasa jurnalistik — bahasa yang singkat, padat, jelas, lugas, dan objektif. Mari kita bedah satu per satu.",
          "",
          "1. SINGKAT DAN PADAT — Hemat Kata!",
          "  • Setiap kata harus bermakna. Tidak ada tempat untuk kata mubazir.",
          "  • Hindari: 'dengan menggunakan' → cukup 'menggunakan' atau 'dengan'",
          "  • Hindari: 'dalam rangka' → bisa diganti 'untuk' atau dihilangkan",
          "  • Hindari: 'pada hari ini' → cukup 'hari ini'",
          "  • Hindari: 'adalah' dan 'merupakan' yang tidak perlu",
          "  ✓ 'Siswa mengikuti lomba puisi.' (3 kata, langsung ke inti)",
          "  ✗ 'Dalam rangka kegiatan lomba, maka diadakanlah sebuah perlombaan baca puisi yang diikuti oleh para siswa-siswa sekolah.' (banyak kata tidak perlu)",
          "",
          "2. OBJEKTIF — Bukan Tempat Opini",
          "  • Wartawan TIDAK boleh memasukkan opini, penilaian, atau dugaan pribadi",
          "  • Jangan tulis: 'beruntungnya', 'sayangnya', 'alhamdulillah', 'hebatnya' — ini subjektif",
          "  • Jangan membuat kesimpulan sendiri — biarkan data dan narasumber yang 'berbicara'",
          "  ✓ 'Korban selamat dievakuasi ke rumah sakit.' (objektif)",
          "  ✗ 'Beruntung para korban selamat dari musibah yang mengerikan itu.' (ada penilaian 'beruntung' dan 'mengerikan')",
          "",
          "3. KALIMAT LANGSUNG — 'Suara' Narasumber",
          "  • Kutipan langsung memberikan 'suara' pada berita dan menunjukkan wartawan mewawancarai narasumber",
          "  • Gunakan tanda kutip (\") dan kata kerja mental: mengatakan, menyatakan, menjelaskan, mengungkapkan, menambahkan",
          "  • Kutipan langsung harus benar-benar persis seperti ucapan narasumber",
          "  • Jangan mengubah isi kutipan meskipun tata bahasanya kurang sempurna — tapi wartawan boleh merapikan jika narasumber setuju",
          "  ✓ 'Saya sangat bangga dengan prestasi ini,' ujar Kepala Sekolah.",
          "  ✗ 'Kepala sekolah mengatakan bahwa beliau sangat bangga dengan prestasi ini.' (ini kalimat tidak langsung, bukan langsung)",
          "",
          "4. ATRIBUSI — Menyebut Sumber",
          "  • Setiap informasi yang bukan hasil pengamatan langsung wartawan harus DIBERI SUMBER",
          "  • Atribusi diletakkan setelah pernyataan atau di awal kalimat",
          "  • Contoh pola: '...' ujar X / Menurut X, ... / X menjelaskan bahwa ...",
          "  • Jika sumber tidak mau disebut namanya, gunakan: 'sumber yang enggan disebutkan namanya' atau 'menurut sumber terpercaya'",
          "  ✓ 'Kepala BPBD menyatakan bahwa korban gempa mencapai 500 jiwa.' (ada atribusi jelas)",
          "  ✗ 'Korban gempa mencapai 500 jiwa.' (dari mana? tanpa atribusi, informasi ini tidak bisa dipercaya)",
          "",
          "5. KONJUNGSI TEMPORAL DAN KAUSAL — Perangkai Waktu dan Sebab",
          "  • Temporal: kemudian, sebelumnya, setelah itu, sementara itu, sejak saat itu",
          "  • Kausal: karena, sebab, akibatnya, sehingga, oleh karena itu",
          "  • Gunakan untuk membangun KRONOLOGI (HOW) dan ALASAN (WHY)",
          "  ✓ 'Kebakaran terjadi akibat korsleting listrik. Sebelumnya, warga sempat mencium bau kabel terbakar sejak pukul 01.00.'",
          "",
          "6. KATA BAKU — Tidak Pakai Bahasa Gaul",
          "  • Berita menggunakan bahasa Indonesia baku, bukan bahasa sehari-hari atau slang",
          "  • Hindari: 'nggak', 'doang', 'banget', 'gitu', 'gue' — kecuali dalam kutipan langsung",
          "  • Dalam kutipan langsung, bahasa narasumber boleh ditulis apa adanya",
          "  ✓ 'Saya tidak menyangka bisa menang,' ujar Raihan.",
          "  ✗ dalam narasi wartawan: 'Raihan nggak nyangka bisa menang.'",
          "",
          "[Ilustrasi: Tampilan halaman depan koran dengan label anotasi. JUDUL (lingkaran merah) — 'Tim Basket SMPN 1 Juara'. FOTO (lingkaran biru) — pemain basket selebrasi. KUTIPAN (lingkaran hijau) — 'Kami bermain dengan hati' — Kapten Tim. TERAS (lingkaran ungu) — paragraf pertama. ATRIBUSI (lingkaran kuning) — nama wartawan. Tubuh berita dan ekor juga ditandai dengan garis putus-putus dan label keterangan.]",
          "",
          "PENTING: Bahasa jurnalistik bukan berarti miskin kosakata. Justru sebaliknya — dengan keterbatasan kata, wartawan harus mampu menyampaikan informasi secara TEPAT dan EFEKTIF. Gunakan kata yang kuat dan spesifik: bukan 'hujan deras' tapi 'hujan dengan intensitas 100 mm per jam'; bukan 'banyak orang' tapi '5.000 warga mengungsi'.",
        ],
        contoh: [
          "BENAR (kaidah bahasa jurnalistik):",
          "\"Kebakaran melanda Pasar Senen, Jakarta Pusat, pada Rabu (14/5/2026) pukul 02.30 WIB. Tidak ada korban jiwa dalam peristiwa ini. (Singkat, padat, langsung ke inti — 3 kalimat menjawab WHAT+WHERE+WHEN+WHO)\"",
          "",
          "\"Kepala Suku Dinas Penanggulangan Kebakaran dan Penyelamatan Jakarta Pusat, Bapak Suhartono, menjelaskan api diduga berasal dari korsleting listrik di kios pakaian Blok A. (Atribusi lengkap: nama, jabatan + kata kerja mental 'menjelaskan')\"",
          "",
          "\"Sebanyak 15 unit mobil pemadam diterjunkan ke lokasi. Api berhasil dipadamkan setelah menjalar ke 25 kios. (Data spesifik: 15 unit, 25 kios — bukan 'banyak mobil' atau 'beberapa kios')\"",
          "",
          "\"'Kami terus berupaya memadamkan api sejak pukul 02.30 dan akhirnya berhasil mengendalikan situasi pukul 05.00,' ujar Suhartono. (Kalimat langsung dengan atribusi benar)\"",
          "",
          "SALAH:",
          "\"Pada hari Rabu yang lalu, telah terjadi musibah kebakaran yang sangat mengerikan di Pasar Senen. Beruntung sekali tidak ada korban jiwa dalam kejadian nahas ini. Banyak warga yang kehilangan tempat usaha mereka. Sayang sekali ya. (Tidak objektif: 'mengerikan', 'beruntung sekali', 'nahas', 'sayang sekali' adalah opini wartawan. Terlalu panjang dan bertele-tele.)\"",
        ],
        catatan: "Kaidah bahasa jurnalistik ini BUTUH LATIHAN. Kebiasaan menulis seperti di media sosial atau diary harus ditinggalkan saat menulis berita. Latih dirimu dengan menulis ulang satu paragraf dari artikel biasa menjadi versi jurnalistik yang singkat, padat, dan objektif.",
      },
      {
        judul: "Fakta vs Opini: Bedah Kritis Berita",
        isi: [
          "Kemampuan membedakan fakta dan opini adalah LITERASI MEDIA — keterampilan penting di era banjir informasi seperti sekarang. Dalam konteks berita, perbedaan ini semakin krusial karena banyak media yang sengaja atau tidak sengaja mencampur adukkan keduanya.",
          "",
          "1. FAKTA — Kebenaran yang Terverifikasi",
          "  Fakta adalah informasi yang dapat dibuktikan kebenarannya secara objektif.",
          "  • Ciri fakta: mengandung data angka, nama, waktu, tempat yang spesifik",
          "  • Dapat diverifikasi: dicek ulang, dikonfirmasi, diukur",
          "  • Tidak bergantung pada pendapat atau perasaan siapa pun",
          "  ✓ 'Suhu udara di Jakarta mencapai 34°C pada 25 Mei 2026 pukul 13.00 WIB.' (bisa dicek dengan termometer)",
          "  ✓ 'Jumlah korban banjir mencapai 5.000 jiwa berdasarkan data BNPB.' (ada sumber data)",
          "",
          "2. OPINI — Pendapat Subjektif",
          "  Opini adalah pernyataan yang mencerminkan pandangan, penilaian, atau keyakinan seseorang.",
          "  • Ciri opini: mengandung KATA PENILAI (sebaiknya, seharusnya, sayangnya, hebatnya) atau kata SIFAT SUBJEKTIF (indah, mengerikan, luar biasa)",
          "  • Bisa benar menurut satu orang, belum tentu menurut orang lain",
          "  • Tidak bisa diverifikasi secara langsung",
          "  ✓ Opini wartawan: 'Penanganan banjir tahun ini lebih baik dari tahun lalu.' (subjektif — 'lebih baik' ukurannya apa?)",
          "  ✓ Opini narasumber dalam kutipan: 'Menurut Kepala BNPB, penanganan banjir tahun ini lebih baik dari tahun lalu.' (ini SAH dalam berita — wartawan hanya melaporkan pernyataan)",
          "",
          "3. OPINI NARASUMBER vs OPINI WARTAWAN — Bedanya Krusial!",
          "  • Opini narasumber: SAH dimuat dalam berita sebagai kutipan langsung. Wartawan tidak bertanggung jawab atas isi opini tersebut, hanya akurat dalam mengutip.",
          "  • Opini wartawan: TIDAK BOLEH ada dalam berita. Wartawan harus netral dan objektif.",
          "  • Batas ini sering dilanggar oleh media abal-abal atau media yang tidak profesional.",
          "",
          "4. TEKNIK MENDETEKSI OPINI TERSEMBUNYI",
          "  Kadang opini tidak diawali 'menurut saya', tapi tersembunyi dalam pilihan kata. Waspadai:",
          "  • Kata sifat subjektif: tragis, memilukan, heroik, sukses besar, gagal total",
          "  • Kata keterangan penilaian: hanya, ternyata, sayangnya, beruntungnya, akhirnya (dalam konteks penilaian)",
          "  • Kalimat yang menyimpulkan tanpa data: 'Hal ini membuktikan bahwa...' (pastikan memang terbukti dengan data)",
          "  • Perbandingan tanpa dasar: 'lebih baik', 'lebih buruk', 'paling hebat'",
          "",
          "5. COVER BOTH SIDES — Prinsip Objektivitas",
          "  Berita yang baik menyajikan sudut pandang dari SEMUA PIHAK yang terlibat.",
          "  • Jika berita tentang konflik, wawancarai kedua belah pihak",
          "  • Jika berita tentang kebijakan baru, muat pendapat pendukung dan penentang",
          "  • Jangan hanya mengutip satu sumber — itu namanya berita sepihak",
          "  • Cover both sides bukan berarti 'semua pihak benar', tapi memberi ruang yang adil",
          "  ✓ Berita tentang demo mahasiswa: muat pernyataan mahasiswa + pernyataan rektorat + pernyataan polisi (3 pihak)",
          "  ✗ Berita tentang demo: hanya muat pernyataan mahasiswa (sepihak, tidak berimbang)",
          "",
          "PENTING: Di era hoaks dan misinformasi, kemampuan membedakan fakta-opini adalah 'tameng' yang melindungimu dari penipuan informasi. Jangan percaya begitu saja — verifikasi, cek sumber, bandingkan dengan media lain. Literasi media dimulai dari pertanyaan sederhana: 'APAKAH INI FAKTA ATAU OPINI?'",
        ],
        contoh: [
          "BEDAH FAKTA VS OPINI dalam satu paragraf berita:",
          "",
          "\"Banjir setinggi 1,5 meter merendam 1.200 rumah di Kecamatan Cilincing, Jakarta Utara, pada Senin (25/5/2026). (FAKTA — ada data tinggi, jumlah rumah, lokasi, tanggal) BPBD DKI Jakarta mencatat 8.000 warga mengungsi ke 12 titik pengungsian. (FAKTA — data spesifik dari sumber resmi) Sayangnya, penanganan banjir tahun ini dinilai lambat oleh warga. (OPINI NARASUMBER — 'sayangnya' adalah kata wartawan yang TIDAK BOLEH ADA; 'dinilai lambat' adalah opini warga yang sah dikutip jika diucapkan narasumber) Seharusnya pemerintah sudah mengantisipasi banjir sejak musim kemarau. (OPINI WARTAWAN — TIDAK BOLEH! 'Seharusnya' menunjukkan penilaian pribadi penulis)\"",
          "",
          "BENAR (versi objektif):",
          "\"Banjir setinggi 1,5 meter merendam 1.200 rumah di Kecamatan Cilincing, Jakarta Utara, pada Senin (25/5/2026). BPBD DKI Jakarta mencatat 8.000 warga mengungsi ke 12 titik pengungsian. Sejumlah warga menyatakan penanganan banjir lambat. 'Kami sudah berteriak sejak pagi tapi tidak ada petugas yang datang,' ujar Siti, warga RT 05 RW 02. Sementara itu, Kepala BPBD DKI Jakarta, Arief Syahputra, mengatakan pihaknya telah menurunkan 200 personel sejak pukul 06.00 WIB. 'Kami bergerak secepat mungkin, tetapi akses jalan terbatas karena genangan,' jelasnya.\" (Semua opini diucapkan oleh NARASUMBER, bukan wartawan. Cover both sides: warga + BPBD.)",
        ],
        catatan: "Latihan seru: Buka portal berita apa pun, baca satu berita, lalu copy-paste ke dokumen. Stabilo KUNING untuk opini wartawan (jika ada) dan stabilo BIRU untuk fakta. Hitung perbandingannya. Berita profesional seharusnya didominasi biru (fakta) dengan sedikit atau tanpa kuning (opini wartawan).",
      },
      {
        judul: "Menulis Berita Sekolah: Dari Lapangan ke Halaman",
        isi: [
          "Setelah menguasai teori dan kaidah, saatnya menerapkan dalam konteks yang paling dekat dengan kehidupanmu: MENULIS BERITA SEKOLAH. Setiap hari di sekolah terjadi peristiwa yang layak diberitakan — tugas kitalah sebagai jurnalis muda untuk mengabadikannya dalam tulisan.",
          "",
          "Peristiwa sekolah apa saja yang bisa dijadikan berita?",
          "",
          "1. UPACARA BENDERA — Bisa angle-nya inovatif",
          "  • Angle 1: 'Kepala Sekolah Sampaikan Pesan Anti-Bullying dalam Upacara Hari Senin'",
          "  • Angle 2: 'Petugas Upacara Perdana: Siswi Kelas VII Sukses Pimpin Pengibaran Bendera'",
          "  • Angle 3: 'Upacara Bendera Digelar di Tengah Hujan, Siswa Tetap Khidmat'",
          "",
          "2. LOMBA DAN KOMPETISI — Prestasi siswa",
          "  • Angle 1: 'Tim Robotik SMPN 1 Sabet Juara Umum Lomba Inovasi Teknologi'",
          "  • Angle 2: 'Dua Siswi SMPN 2 Ciptakan Aplikasi Deteksi Sampah Plastik'",
          "  • Angle 3: 'Lomba Debat Bahasa Inggris: Ajang Asah Kemampuan Argumentasi Siswa'",
          "",
          "3. KEGIATAN SOSIAL DAN KEAGAMAAN",
          "  • 'Bakti Sosial SMPN 1: 500 Paket Sembako untuk Warga Terdampak Banjir'",
          "  • 'Peringatan Maulid Nabi di SMPN 3: Santunan untuk 100 Anak Yatim'",
          "  • 'Kelas Inspirasi: Alumni Berbagi Pengalaman dengan Adik Kelas'",
          "",
          "4. KEBIJAKAN DAN PROGRAM BARU",
          "  • 'SMPN 1 Terapkan Program 'Sekolah Ramah Digital': Setiap Siswa Wajib Bawa Tablet'",
          "  • 'Kantin Sehat SMPN 2: Bebas Jajanan Berbahaya, Semua Menu Uji Laboratorium'",
          "  • 'Program Satu Hari Tanpa Gawai: SMPN 3 Ajak Siswa Interaksi Langsung'",
          "",
          "5. PENCAPAIAN INFRASTRUKTUR",
          "  • 'Perpustakaan Baru SMPN 1 Diresmikan: Koleksi 5.000 Buku Siap Dipinjam'",
          "  • 'Laboratorium Bahasa Digital: SMPN 2 Jadi Pilot Project Kemdikbud'",
          "  • 'Lapangan Basket Multifungsi: Bisa Jadi Panggung Pertunjukan'",
          "",
          "Tips menentukan angle berita sekolah:",
          "  • Cari unsur yang PALING UNIK atau PALING MENARIK dari peristiwa itu",
          "  • Jangan hanya melaporkan rutinitas — cari sisi manusianya (human interest)",
          "  • Kutip tokoh yang paling relevan: ketua panitia, peserta, atau Kepala Sekolah",
          "  • Jika bisa, dapatkan data pendukung: berapa peserta? berapa donasi? berapa nilai kemenangan?",
          "",
          "PENTING: Berita sekolah tidak boleh 'menggurui' atau 'sok merakyat'. Tetaplah profesional meskipun yang kamu liput adalah lingkungan sekolahmu sendiri. Perlakukan berita sekolah dengan standar yang sama seperti berita profesional. Ini adalah latihan jurnalistik yang sesungguhnya!",
        ],
        contoh: [
          "BENAR (berita sekolah profesional):",
          "\"Siswa SMPN 1 Kumpulkan 5.000 Buku untuk Perpustakaan Desa\"",
          "",
          "SMPN 1 Jakarta — Sebanyak 5.000 buku berhasil dikumpulkan oleh siswa SMPN 1 Jakarta dalam program 'Satu Siswa Satu Buku' yang berlangsung selama dua pekan, 12—25 Mei 2026. Buku-buku tersebut akan disumbangkan ke perpustakaan desa di Kecamatan Cimenyan, Kabupaten Bandung.",
          "",
          "Ketua OSIS SMPN 1, Dinda Aulia, menjelaskan program ini digagas setelah pihaknya mendapat laporan bahwa perpustakaan di desa binaan hanya memiliki 300 buku. 'Kami ingin berbagi kesempatan yang sama untuk belajar. Buku adalah jendela dunia, dan semua anak berhak memiliki jendela itu,' ujar Dinda saat penyerahan simbolis di Aula sekolah, Senin (26/5/2026).",
          "",
          "Dari 5.000 buku yang terkumpul, 60 persen merupakan buku pelajaran, 25 persen buku cerita dan novel, serta 15 persen buku keterampilan dan ensiklopedia. Wakil Kepala Sekolah Bidang Kesiswaan, Bapak Tri Wahyudi, S.Pd., mengapresiasi antusiasme siswa. 'Kami terharu melihat partisipasi luar biasa ini. Bahkan ada siswa yang menyumbangkan buku baru hasil tabungannya,' katanya.",
          "",
          "Pihak sekolah berencana menjadikan program ini sebagai agenda tahunan. 'Tahun depan target kami 10.000 buku — semoga bisa lebih banyak lagi desa yang terbantu,' tambah Dinda. Buku-buku akan didistribusikan menggunakan mobil perpustakaan keliling Dinas Arsip dan Perpustakaan Jakarta pada pekan depan.",
          "",
          "BENAR: Ada angle jelas (aksi sosial), lead kuat (5W+1H), narasumber dari Ketua OSIS + Wakasek (cover both sides: penggagas dan pembina), data spesifik (5.000 buku, 60%, 300 buku), kutipan langsung, dan ekor berisi rencana ke depan.",
          "",
          "SALAH:",
          "\"Kegiatan Donasi Buku — Pada hari-hari yang lalu, siswa SMPN 1 Jakarta mengadakan kegiatan donasi buku. Acaranya bagus sekali dan meriah. Banyak siswa yang ikut serta dengan antusias. Kami berharap kegiatan seperti ini terus berlangsung. (Tidak ada data: berapa buku, siapa yang menginisiasi, kapan tepatnya. Bahasa subjektif: 'bagus sekali', 'meriah'. Tidak ada kutipan narasumber. Tidak profesional.)\"",
        ],
        catatan: "Mulailah dari hal kecil. Jika ada lomba di kelas atau pentas seni di sekolah, jadilah reporter dadakan! Catat 5W+1H, wawancara 2—3 orang, tulis beritanya, dan minta guru Bahasa Indonesia mengoreksi. Semakin sering latihan, semakin tajam insting jurnalistikmu.",
      },
    ],
    rangkuman: [
      "Unsur 5W+1H bukan sekadar identifikasi — setiap unsur perlu STRATEGI: angle pada WHAT, kredibilitas pada WHO, presisi pada WHEN/WHERE, konteks pada WHY, dan kronologi pada HOW.",
      "Struktur piramida terbalik: judul → teras (lead) → tubuh → latar belakang → ekor. Informasi paling penting di awal, semakin ke belakang semakin kurang penting.",
      "Lead adalah 'jantung' berita — harus mandiri, langsung ke inti, dan menjawab WHAT+WHO+WHEN+WHERE. Ada beberapa model lead: summary, quote, descriptive, question.",
      "Bahasa jurnalistik: singkat-padat, objektif (tanpa opini wartawan), kalimat langsung dengan tanda kutip, atribusi jelas pada setiap sumber, konjungsi temporal/kausal, dan kosakata baku.",
      "Fakta = informasi terverifikasi (data, angka, nama, waktu). Opini = pendapat subjektif (kata penilai, sifat subjektif). Opini narasumber SAH dalam berita (sebagai kutipan), opini wartawan TIDAK BOLEH.",
      "Cover both sides: berita berimbang menyajikan sudut pandang semua pihak. Berita sepihak melanggar prinsip objektivitas jurnalistik.",
      "Berita sekolah bisa diangkat dari berbagai angle: upacara, lomba, aksi sosial, kebijakan baru, prestasi. Cari unsur unik dan human interest.",
      "Literasi media dimulai dari kemampuan membedakan fakta-opini dan memverifikasi informasi sebelum mempercayai atau menyebarkannya.",
    ],
  },

  latihan: makeSoal([
    // 5 Soal Pilihan Ganda
    ["Dalam penulisan berita, istilah 'angle' mengacu pada...", ["Ukuran sudut kemiringan foto", "Sudut pandang atau sisi tertentu dari suatu peristiwa yang dipilih wartawan", "Jenis kamera yang digunakan wartawan", "Posisi narasumber saat diwawancarai"], 1, "Angle adalah sudut pandang atau sisi tertentu yang dipilih wartawan untuk menyajikan berita. Peristiwa yang sama bisa memiliki angle berbeda."],
    ["Ciri utama lead model summary adalah...", ["Mengutip pernyataan narasumber di awal", "Menggambarkan suasana secara detail", "Langsung menyampaikan inti berita: what, who, when, where", "Mengajukan pertanyaan provokatif kepada pembaca"], 2, "Summary lead langsung menyampaikan inti berita — biasanya menjawab WHAT, WHO, WHEN, WHERE dalam 1—3 kalimat pertama."],
    ["Pernyataan berikut yang termasuk fakta adalah...", ["Penanganan banjir tahun ini sangat lambat", ["Seharusnya pemerintah lebih sigap menghadapi bencana", "Korban banjir mencapai 5.000 jiwa berdasarkan data BNPB", "Banjir tahun ini lebih parah dari tahun lalu"], 2], 2, "'Korban banjir mencapai 5.000 jiwa berdasarkan data BNPB' adalah fakta karena dapat diverifikasi dan ada sumber jelas. Kalimat lain mengandung opini (kata 'sangat lambat', 'seharusnya', 'lebih parah')."],
    ["Kata 'mengatakan', 'menjelaskan', 'menyatakan' dalam berita termasuk jenis kata...", ["Kata kerja material", "Kata kerja mental", "Kata kerja aktif", "Kata kerja pasif"], 1, "Kata kerja mental berkaitan dengan aktivitas berpikir dan berbicara. Dalam berita, kata kerja mental digunakan untuk mengatribusi pernyataan narasumber."],
    ["Penulisan atribusi yang benar dalam berita adalah...", ["Menurut beliau, acara berjalan sukses", ["'Acara berjalan sukses,' kata Kepala Sekolah", "'Acara berjalan sukses' ujarnya", "Kata Kepala Sekolah bahwa acara berjalan sukses"], 1], 1, "Atribusi yang benar: kutipan langsung dengan tanda kutip, diikuti kata kerja mental + subjek: '\"Acara berjalan sukses,\" kata Kepala Sekolah.'"],

    // 3 Soal Betul/Salah
    ["Pernyataan: 'Dalam piramida terbalik, informasi paling penting diletakkan di tubuh berita, sedangkan lead berisi latar belakang.'", ["Betul", "Salah"], 1, "SALAH. Dalam piramida terbalik, informasi PALING PENTING diletakkan di LEAD (teras berita), bukan di tubuh. Semakin ke bawah semakin kurang penting."],
    ["Pernyataan: 'Opini narasumber yang dikutip langsung dalam berita adalah hal yang sah dan diperbolehkan dalam jurnalisme.'", ["Betul", "Salah"], 0, "BETUL. Opini narasumber dalam kutipan langsung adalah bagian sah dari berita. Wartawan hanya melaporkan apa yang dikatakan narasumber — bukan menyetujui atau menolaknya."],
    ["Pernyataan: 'Cover both sides berarti berita harus menyajikan lebih banyak sisi positif daripada sisi negatif.'", ["Betul", "Salah"], 1, "SALAH. Cover both sides berarti berita menyajikan semua sudut pandang yang relevan secara BERIMBANG — bukan timbang berat ke satu sisi. Tujuannya objektivitas, bukan propaganda atau pencitraan."],

    // 2 Soal Isian Singkat
    ["Model lead yang membuka berita dengan kutipan narasumber yang mencolok disebut lead...", ["summary", "quote", "descriptive", "question"], 1, "Quote lead membuka berita dengan kutipan narasumber yang menarik perhatian. Biasanya digunakan untuk berita human interest atau profil tokoh."],
    ["Kata 'seharusnya', 'sebaiknya', 'sayangnya', 'beruntungnya' dalam konteks berita menandakan adanya unsur...", ["fakta", "opini", ["data", "konjungsi"], 1], 1, "Kata-kata seperti 'seharusnya', 'sebaiknya', 'sayangnya', 'beruntungnya' menandakan OPINI karena menunjukkan penilaian atau sikap subjektif penulis."],
  ]),

  praktik: {
    petunjuk: "Tugasmu: Menjadi Reporter Sekolah!\n\nPilih SALAH SATU peristiwa di lingkungan sekolahmu (bisa peristiwa nyata atau kamu ciptakan secara logis) lalu tulis berita lengkap:\n\n1. Tim basket/voli/futsal sekolah meraih juara dalam turnamen antar-SMP\n2. Sekolah mengadakan acara peringatan Hari Besar Nasional (Hardiknas, Sumpah Pemuda, Pramuka, dll.)\n3. Program baru dari sekolah (kantin sehat, gerakan literasi, sekolah ramah anak, dll.)\n4. Kegiatan bakti sosial/penggalangan dana untuk korban bencana\n5. Lomba kelas dalam rangka Bulan Bahasa atau Class Meeting\n\nIkuti langkah penulisan berikut:\n\n1. Tentukan ANGLE berita — dari sisi mana cerita ini paling menarik? Jangan hanya melaporkan bahwa acara itu terjadi.\n2. Tulis JUDUL maksimal 8 kata, SP aktif, langsung ke inti.\n3. Tulis LEAD (teras berita) — 1—3 kalimat pertama yang menjawab WHAT + WHO + WHEN + WHERE. Lead harus mandiri!\n4. Kembangkan TUBUH berita — 2—3 paragraf:\n   • WHY dan HOW — jelaskan latar belakang dan kronologi\n   • Sertakan 2 kutipan langsung dari narasumber berbeda\n   • Sertakan data pendukung (jumlah peserta, donasi, skor, dll.)\n5. Sertakan LATAR BELAKANG — apakah ada peristiwa serupa sebelumnya?\n6. Akhiri dengan EKOR — informasi tambahan, rencana ke depan, atau imbauan\n7. Periksa dengan daftar periksa berikut:\n   ☐ Angle jelas dan menarik?\n   ☐ 5W+1H lengkap?\n   ☐ Tidak ada opini wartawan?\n   ☐ Atribusi dan kutipan langsung benar?\n   ☐ Bahasa singkat, padat, objektif?\n   ☐ Cover both sides (minimal 2 narasumber)?\n   ☐ Data spesifik (bukan 'banyak' atau 'beberapa')?",
    tips: [
      "Tentukan angle sebelum mulai menulis. Tanya diri: 'Apa yang PALING UNIK dari peristiwa ini?' Jawabannya menjadi angle beritamu.",
      "Wawancarai minimal 2 narasumber: satu dari pihak penyelenggara (panitia/guru) dan satu dari pihak peserta/siswa. Ini untuk cover both sides.",
      "Catat data spesifik saat meliput: jumlah peserta, jam mulai-selesai, nominal donasi, skor pertandingan, nama-nama penting. Data ini 'nyawa' berita.",
      "Gunakan alat perekam (voice recorder di HP) saat wawancara agar kutipan akurat. Minta izin dulu ke narasumber sebelum merekam.",
      "Tulis draft pertama secepat mungkin tanpa khawatir sempurna. Edit setelahnya. Yang penting ide tertuang dulu.",
      "Periksa kembali: apakah ada kata 'sayangnya', 'beruntungnya', 'hebatnya', 'alhamdulillah' dari kamu sebagai penulis? Hapus! Itu opini, bukan jurnalistik.",
      "Baca beritamu keras-keras. Apakah terdengar seperti berita di televisi? Jika iya, kamu sudah di jalur yang benar.",
      "Minta teman atau guru membaca beritamu dan memberi masukan. Perspektif orang lain sangat berharga.",
      "Jika mengalami kesulitan menentukan angle, cari tahu apa yang membuat orang lain tertarik dengan peristiwa itu. Tanya ke 3 teman: 'Apa yang ingin kamu tahu tentang acara ini?'",
      "Studi banding: baca berita sekolah di media nasional (banyak di Kompas dan Jawa Pos rubrik pendidikan). Analisis angle, lead, dan struktur mereka.",
    ],
    contoh: "Lomba Kebersihan Kelas: SMPN 1 Rajai Class Meeting dengan Inovasi Daur Ulang\n\nSMPN 1 Jakarta — Lomba kebersihan dan kerapian kelas dalam rangka Class Meeting Semester Genap digelar di SMPN 1 Jakarta pada 20—24 Mei 2026. Kegiatan ini diikuti oleh 27 kelas dari kelas VII hingga IX.\n\nBerbeda dari tahun sebelumnya, tahun ini dewan juri memberikan nilai tambah bagi kelas yang menghias ruangan menggunakan bahan daur ulang. Ketua Panitia Class Meeting, Arif Pratama (IX-A), menjelaskan inovasi ini sengaja diterapkan untuk meningkatkan kesadaran lingkungan di kalangan siswa. 'Kami ingin Class Meeting tidak sekadar ajang perlombaan, tetapi juga media edukasi. Tema daur ulang kami pilih agar siswa terbiasa berpikir kreatif dalam memanfaatkan barang bekas,' ujar Arif.\n\nSelama lima hari, dewan juri yang terdiri dari tiga guru seni budaya dan dua perwakilan OSIS berkeliling menilai setiap kelas. Kriteria penilaian meliputi kebersihan (30%), kerapian (25%), kreativitas hiasan daur ulang (35%), dan inovasi (10%). Hasilnya, kelas VIII-C keluar sebagai juara pertama dengan hiasan dinding dari botol plastik bekas yang disusun membentuk mural pemandangan alam.\n\n'Kami mengumpulkan 150 botol plastik selama dua minggu. Awalnya teman-teman ragu, tapi setelah jadi mural, semua bangga karena botol sampah bisa jadi seni,' cerita Ketua Kelas VIII-C, Sari Dewi. Kepala SMPN 1 Jakarta, Drs. H. Ahmad Fauzi, M.Pd., mengapresiasi kreativitas siswa. 'Saya sangat bangga. Lomba ini membuktikan bahwa kreativitas dan kepedulian lingkungan bisa berjalan beriringan,' katanya saat menutup Class Meeting, Jumat (24/5/2026).\n\nSekolah berencana mengembangkan program 'Eco-Class' -- kelas-kelas percontohan ramah lingkungan -- sebagai tindak lanjut dari lomba ini. Program tersebut akan dimulai pada semester depan dengan pilot project tiga kelas terbaik. Selain itu, botol plastik dari hiasan kelas akan didaur ulang menjadi pot tanaman yang akan ditempatkan di taman sekolah.\n\n---\n\nAnalisis berita di atas:\n• JUDUL: 'Lomba Kebersihan Kelas: SMPN 1 Rajai Class Meeting dengan Inovasi Daur Ulang' — ada angle (daur ulang), tidak sekadar 'Lomba Kebersihan Kelas Diadakan'\n• LEAD: Langsung menjawab WHAT (lomba), WHO (27 kelas VII-IX), WHEN (20-24 Mei 2026), WHERE (SMPN 1 Jakarta)\n• TUBUH: WHY (edukasi lingkungan) + HOW (proses penjurian 5 hari) + kutipan 2 narasumber (ketua panitia + peserta) + data (kriteria nilai 30-25-35-10, 150 botol)\n• LATAR BELAKANG: Perbandingan dengan tahun sebelumnya ('Berbeda dari tahun sebelumnya...')\n• EKOR: Rencana ke depan (program Eco-Class) — informasi tambahan\n• Tidak ada opini wartawan — semua penilaian dari narasumber\n• Cover both sides: panitia (Arif), peserta (Sari), Kepala Sekolah — 3 sudut pandang",
  },

  kuis: makeSoal([
    ["Dalam struktur piramida terbalik, bagian yang memuat informasi paling penting adalah...", ["Judul", "Lead/teras berita", "Tubuh berita", "Ekor berita"], 1, "Lead (teras berita) adalah bagian PALING ATAS dalam piramida terbalik dan memuat informasi TERPENTING — biasanya menjawab WHAT, WHO, WHEN, WHERE."],
    ["Seorang wartawan menulis: 'Korban gempa diungsikan ke tenda darurat. Sebelumnya, gempa berkekuatan 5,2 juga mengguncang wilayah yang sama pada Januari 2026.' Kalimat kedua tersebut termasuk struktur...", ["Lead", "Tubuh berita", "Latar belakang", "Ekor berita"], 2, "Kalimat 'Sebelumnya, gempa... pada Januari 2026' adalah LATAR BELAKANG — memberikan konteks peristiwa serupa di masa lalu. Letaknya di tubuh berita."],
    ["Cermati kalimat: 'Beruntungnya, tidak ada korban jiwa dalam kebakaran tersebut.' Kalimat ini bermasalah karena...", ["Terlalu panjang", ["Mengandung opini wartawan ('beruntungnya')", "Tidak ada atribusi", "Menggunakan bahasa daerah"], 1], 1, "Kata 'beruntungnya' adalah opini/subjektivitas wartawan. Berita objektif tidak boleh mengandung penilaian pribadi seperti itu. Cukup tulis: 'Tidak ada korban jiwa dalam kebakaran tersebut.'"],
    ["Perbedaan mendasar antara straight news dengan depth news adalah...", ["Straight news lebih panjang", "Straight news langsung ke inti, depth news menyajikan analisis mendalam", "Depth news tidak menggunakan 5W+1H", "Straight news hanya untuk televisi"], 1, "Straight news langsung menyampaikan inti peristiwa secara lugas, sedangkan depth news mengupas analisis, latar belakang, dan dampak secara mendalam."],
    ["Manakah penulisan judul berita yang paling tepat?", ["Lomba Debat Bahasa Inggris Antar-SMP Se-Jakarta Pusat Tahun 2026", ["Siswa SMPN 1 Juara Debat Bahasa Inggris Tingkat Kota", "Telah Diselenggarakan Lomba Debat Bahasa Inggris", "Perlombaan Debat yang Diadakan oleh Sekolah"], 1], 1, "'Siswa SMPN 1 Juara Debat Bahasa Inggris Tingkat Kota' — SP aktif, ≤ 8 kata, langsung ke inti. Judul lain terlalu panjang, pasif, atau tidak informatif."],
    ["Dalam penulisan berita, fungsi atribusi adalah...", ["Memperpanjang berita", "Menunjukkan sumber informasi agar dapat dipercaya", ["Menambahkan opini", "Membuat berita lebih menarik"], 1], 1, "Atribusi menunjukkan dari mana informasi berasal. Setiap informasi yang bukan hasil pengamatan langsung wartawan harus diberi atribusi agar dapat dipertanggungjawabkan."],
    ["Berita tentang demo mahasiswa hanya memuat pernyataan dari pihak mahasiswa saja. Berita ini melanggar prinsip...", ["Piramida terbalik", "Cover both sides", "5W+1H", "Bahasa jurnalistik"], 1, "Cover both sides mensyaratkan berita menyajikan sudut pandang semua pihak yang terlibat. Berita demo tanpa pernyataan rektorat atau polisi adalah berita sepihak."],
    ["Perhatikan kalimat: 'Wakil Kepala Sekolah, Bapak Tri Wahyudi, S.Pd., mengapresiasi antusiasme siswa.' Pola atribusi yang digunakan adalah...", ["Atribusi di awal kalimat", "Atribusi di tengah kalimat", "Atribusi di akhir kalimat", "Tanpa atribusi"], 0, "Atribusi 'Wakil Kepala Sekolah, Bapak Tri Wahyudi, S.Pd.' diletakkan di AWAL kalimat, sebelum pernyataan. Pola: SUMBER + kata kerja + pernyataan."],
    ["Seorang siswa menulis lead berita: 'Pernahkah kamu membayangkan belajar di kelas tanpa dinding? Itulah yang dialami siswa SDN 03 Cilincing yang belajar di tenda selama dua bulan terakhir.' Model lead ini disebut...", ["Summary lead", "Quote lead", "Question lead", "Descriptive lead"], 2, "Lead ini dibuka dengan PERTANYAAN 'Pernahkah kamu...' — ini ciri khas question lead. Biasanya digunakan untuk menarik perhatian sebelum menyampaikan inti berita."],
    ["Kaidah bahasa jurnalistik yang benar mengharuskan penulis berita untuk...", ["Menggunakan kata-kata indah dan puitis", "Menghindari data angka agar tidak membingungkan", "Menggunakan kalimat efektif, hemat kata, dan objektif", "Menyertakan opini pribadi agar berita berbobot"], 2, "Bahasa jurnalistik: (1) hemat kata — tidak bertele-tele, (2) efektif — langsung ke sasaran, (3) objektif — tanpa opini pribadi. Poin 1 dan 2 bertentangan dengan kaidah."],
  ]),
}

export default konten
