import type { Konten } from "../types"
import { makeSoal } from "../types"

const konten: Konten = {
  belajar: {
    tujuan: [
      "Menganalisis teknik persuasif (etos, patos, logos) dalam iklan, slogan, dan poster",
      "Mengidentifikasi target audiens dan mengevaluasi kesesuaian strategi iklan berdasarkan demografi",
      "Menganalisis hubungan visual-teks dalam poster serta struktur lengkap iklan (headline–body–CTA–logo)",
      "Mengenali teknik propaganda (transfer, bandwagon, fear appeal, testimonial) dan dampaknya",
      "Menciptakan kampanye iklan multi-platform yang persuasif, etis, dan sesuai target audiens",
    ],
    materi: [
      {
        judul: "Review Kilat: Iklan, Slogan, Poster — dan Lebih Dalam",
        isi: [
          "Di kelas VII, kamu sudah mengenal perbedaan dasar: iklan (pesan persuasif via media), slogan (frasa pendek identitas), poster (plakat bergambar + teks). Sekarang kita akan MEMBEDAHNYA secara analitis — bukan lagi sekadar definisi, tapi memahami MENGAPA dan BAGAIMANA ketiganya bekerja.",
          "",
          "Review cepat:",
          "• Iklan = pesan persuasif berbayar melalui media (TV, cetak, digital, outdoor) dengan tujuan membujuk audiens membeli, mendaftar, peduli, atau mengubah perilaku.",
          "• Slogan = kalimat pendek yang melekat di ingatan, bisa mandiri (slogan negara) atau menjadi bagian iklan/poster.",
          "• Poster = media visual statis yang menggabungkan gambar dominan + teks minimalis untuk menyampaikan pesan dalam SATU PANDANGAN.",
          "",
          "GAMBARAN BESAR: Ketiganya adalah ALAT PERSUASI. Bedanya terletak pada MEDIA, FORMAT, dan STRATEGI PENYAMPAIAN. Iklan fleksibel (video, audio, cetak), slogan murni verbal, poster mengandalkan visual. Tapi TUJUANNYA SAMA: memengaruhi pikiran dan tindakan audiens.",
          "",
          "PENTING: Di dunia nyata, ketiganya sering tumpang tindih. Sebuah poster di halte bus bisa memuat slogan produk dan berfungsi sebagai iklan — ketiganya menyatu dalam satu media. Analisislah FUNGSINYA, bukan sekadar labelnya!",
          "",
          "[Ilustrasi: Diagram Venn tiga lingkaran — Iklan, Slogan, Poster — dengan irisan 'Iklan Poster' (poster komersial di halte bus), 'Iklan Slogan' (slogan dalam iklan TV), 'Poster Slogan' (poster motivasi dengan slogan), dan irisan tengah 'Kampanye Terpadu' (ketiganya dalam satu gerakan pemasaran).]",
        ],
        contoh: [
          "Analisis FUNGSIONAL: bedah satu kasus nyata.",
          "",
          "KASUS: Kampanye \"Ayo Pakai Masker\" saat pandemi (2020-2021).",
          "",
          "IKLAN: Video 15 detik di TV dan YouTube — menampilkan tenaga kesehatan memakai masker, lalu cut ke pasien di ICU. Narasi: \"Masker bukan aksesoris. Ini perisai hidupmu. Lindungi diri, lindungi sesama. #PakaiMasker\"",
          "Fungsi: menjangkau audiens luas via media elektronik, durasi panjang memungkinkan narasi emosional.",
          "",
          "SLOGAN: \"Pakai Masker, Lawan Corona\" — 4 kata, berima (masker-corona), mudah diingat, muncul di akhir video iklan.",
          "Fungsi: membuat pesan melekat — cukup dengar sekali, orang bisa mengulanginya.",
          "",
          "POSTER: Gambar ilustrasi tangan memegang perisai bergambar masker, latar merah putih, teks besar \"#PAKAIMASKER\" dan subteks \"Lindungi Diri, Lindungi Negeri\".",
          "Fungsi: ditempel di fasilitas umum, menyampaikan pesan dalam sekali pandang tanpa audio.",
          "",
          "✓ Contoh nyata bagaimana iklan + slogan + poster bekerja SAMA-SAMA untuk tujuan yang sama, dengan kekuatan masing-masing.",
          "✗ Menganggap ketiganya bersaing atau terpisah total. Mereka justru saling memperkuat!",
        ],
        catatan: "Dalam dunia marketing modern, konsep ini disebut INTEGRATED MARKETING COMMUNICATION (IMC) — menyatukan semua saluran dan format pesan agar audiens menerima pesan yang konsisten di mana pun mereka berada. Iklan TV, postingan Instagram, billboard, dan poster di halte — semua harus bicara dengan 'satu suara'.",
      },
      {
        judul: "Analisis Bahasa Persuasif: Etos, Patos, Logos",
        isi: [
          "Ini adalah inti dari bab ini. Iklan tidak sekadar memberitahu — ia MEMENGARUHI. Para ahli retorika kuno (Aristoteles) mengidentifikasi tiga MODE PERSUASI yang hingga kini masih menjadi tulang punggung dunia periklanan: ETOS, PATOS, dan LOGOS.",
          "",
          "1. ETOS (Kredibilitas) — Membujuk melalui kredibilitas, kepercayaan, dan otoritas. Audiens lebih mudah percaya jika pesan disampaikan oleh sosok yang dihormati atau ahli.",
          "  ✓ \"9 dari 10 dokter gigi merekomendasikan Pasta Gigi X.\" — otoritas medis",
          "  ✓ \"Dibuat oleh para ahli gizi dari Universitas Indonesia.\" — kredibilitas institusi",
          "  ✓ Iklan jamu dengan Mbak Gesa (figur ibu-ibu Jawa yang bijak) — etos kultural",
          "  ✗ \"Kata tetangga saya sih bagus...\" — tidak jelas sumbernya, kredibilitas rendah",
          "",
          "2. PATOS (Emosi) — Membujuk melalui perasaan: haru, takut, gembira, khawatir, bangga, kasihan. Emosi membuat pesan lebih mudah diingat dan lebih cepat mendorong tindakan.",
          "  ✓ \"Bayangkan senyum anakmu saat melihatmu pulang dengan selamat. Bajalah dengan aman. #SafetyFirst\" — menyentuh rasa cinta orang tua",
          "  ✓ \"Jangan biarkan narkoba menghancurkan masa depan generasi muda!\" — memicu rasa takut",
          "  ✓ Iklan provider yang menampilkan tentara menelepon ibu di kampung — haru dan bangga",
          "  ✓ \"Setiap detik, satu hewan langka punah. Apakah kita akan diam saja?\" — kesedihan dan urgensi",
          "",
          "3. LOGOS (Logika) — Membujuk melalui data, fakta, angka, dan alasan rasional. Audiens yang kritis lebih mudah yakin jika disajikan bukti konkret.",
          "  ✓ \"Hemat 50% lebih banyak dibanding merek lain!\" — perbandingan kuantitatif",
          "  ✓ \"Formula baru ini mengandung vitamin C 3x lipat, kolagen, dan SPF 50.\" — komposisi faktual",
          "  ✓ \"Berdasarkan survei 1.000 pengguna, 87% merasakan perubahan dalam 7 hari.\" — data survei",
          "  ✗ \"Produk ini bagus karena memang bagus.\" — tidak ada alasan logis, hanya opini sirkuler",
          "",
          "4. CALL TO ACTION (Ajakan) — Elemen yang mendorong audiens melakukan tindakan SPESIFIK segera. CTA yang kuat memiliki kata kerja imperatif, urgensi, dan kejelasan langkah.",
          "  ✓ \"Beli sekarang — diskon berakhir 24 jam!\" — imperatif + urgensi waktu",
          "  ✓ \"Klik link di bio untuk sample gratis!\" — langkah jelas + insentif",
          "  ✓ \"Daftar di bit.ly/beasiswa25 sebelum 15 Mei!\" — spesifik dan terukur",
          "  ✗ \"Silakan jika berminat...\" — pasif, tidak mendesak, tidak jelas langkahnya",
          "",
          "Tips: Iklan TERBAIK menggabungkan ketiganya! Contoh: iklan asuransi — menampilkan keluarga bahagia (patos) + data klaim dibayar 98% (logos) + testimoni agen berpengalaman (etos) + \"Daftar sekarang, premi mulai Rp30.000/hari!\" (CTA).",
          "",
          "[Ilustrasi: Satu iklan majalah cetak utuh dengan empat stiker berwarna menempel: stiker BIRU di foto dokter (ETOS: kredibilitas), stiker MERAH di gambar anak tersenyum (PATOS: emosi), stiker HIJAU di tabel perbandingan harga (LOGOS: data), stiker KUNING di tombol 'Beli Sekarang' (CTA: ajakan).]",
        ],
        contoh: [
          "Analisis iklan nyata: bedah etos, patos, logos dalam iklan layanan masyarakat.",
          "",
          "IKLAN: Kampanye \"Jangan Nyetir Kalau Ngantuk\" (Kementerian Perhubungan).",
          "",
          "BENTUK: Video 30 detik.",
          "",
          "ETOS: Dibuka dengan logo Kementerian Perhubungan + pernyataan \"Berdasarkan data kecelakaan lalu lintas 2024...\" — kredibilitas pemerintah + data resmi.",
          "",
          "PATOS: Adegan seorang ayah mengemudi di malam hari, matanya mulai sayu. Kamera cut ke foto istri dan anak di dashboard. Musik mencekam. Tiba-tiba klakson keras — ayah tersadar hampir menabrak. Penonton ikut merasakan ketegangan dan takut.",
          "",
          "LOGOS: Muncul teks: \"60% kecelakaan malam hari disebabkan oleh mikro tidur. Hanya butuh 3 detik untuk kehilangan kendali.\" Data konkret, statistik, alasan logis.",
          "",
          "CTA: \"Istirahatlah setiap 4 jam. Keselamatan keluarga adalah prioritas utama.\" Imperatif (istirahatlah) + alasan emosional (keluarga).",
          "",
          "BENAR: Iklan ini menggabungkan etos (otoritas pemerintah), patos (takut kehilangan keluarga), dan logos (data 60%) — persuasi tiga lapis.",
          "SALAH: Iklan yang hanya mengandalkan satu mode. Misalnya: \"Produk kami nomor satu!\" (etos tanpa bukti) atau \"Beli sekarang! Beli sekarang!\" (CTA tanpa alasan). Lemah, mudah diabaikan.",
        ],
        catatan: "Dalam psikologi pemasaran modern, ketiga mode ini dikenal dengan istilah berbeda: Etos → Source Credibility, Patos → Emotional Appeal, Logos → Rational Appeal. Iklan digital sekarang juga menggunakan FAKTOR SOSIAL (social proof) seperti jumlah like, rating bintang, dan komentar positif — ini adalah variasi modern dari ETOS (kredibilitas dari orang banyak).",
      },
      {
        judul: "Target Audiens dan Hubungan Visual-Teks",
        isi: [
          "Iklan yang efektif adalah iklan yang TEPAT SASARAN. Tidak ada iklan yang cocok untuk semua orang. Sebuah iklan mainan anak yang penuh warna dan lagu ceria tidak akan menarik bagi eksekutif kantoran. Sebaliknya, iklan asuransi dengan grafik dan data membosankan bagi anak-anak.",
          "",
          "MENGENAL TARGET AUDIENS — Analisis Demografis dan Psikografis:",
          "1. DEMOGRAFI: usia, jenis kelamin, pendidikan, pekerjaan, pendapatan, lokasi.",
          "2. PSIKOGRAFI: gaya hidup, minat, nilai, kepribadian, kebiasaan konsumsi media.",
          "",
          "• ANAK-ANAK (5–12 tahun): warna cerah, karakter kartun, bahasa sederhana, lagu jingle, gerakan energik. Contoh: iklan susu dengan karakter hewan lucu, iklan mainan dengan demonstrasi seru.",
          "  \"Minum Susu X, biar kuat kayak si Koko!\" — bahasa anak-anak, tokoh kartun.",
          "",
          "• REMAJA (13–19 tahun): bahasa gaul, visual trendi, musik kekinian, referensi pop culture, influencer seumuran, estetika Instagram/TikTok. Contoh: iklan skincare dengan influencer remaja, iklan aplikasi belajar dengan tampilan vibrant.",
          "  \"Glowing maksimal tanpa ribet. Gaskeun beli di Shopee!\" — bahasa gaul, CTA casual.",
          "",
          "• DEWASA / PROFESIONAL (25–50 tahun): desain clean, font elegan, data dan fakta, value-for-money, efisiensi waktu, bahasa formal-santai. Contoh: iklan mobil keluarga menekankan safety, iklan asuransi menekankan perlindungan masa depan.",
          "  \"Investasi pendidikan anak sejak dini. Mulai dengan Rp100.000 per bulan.\" — logis, data, manfaat jangka panjang.",
          "",
          "• PROFESI SPESIFIK: iklan software akuntansi menampilkan laporan keuangan, iklan alat medis menampilkan dokter di rumah sakit, iklan alat berat menampilkan proyek konstruksi.",
          "",
          "HUBUNGAN VISUAL-TEKS DALAM POSTER:",
          "Visual dan teks dalam poster harus BAWA-MEMBAWA, bukan sekadar tempelan. Ada tiga jenis hubungan:",
          "",
          "1. REDUNDANSI — Visual dan teks menyampaikan pesan yang sama. Aman, mudah dipahami, tapi kadang membosankan.",
          "  Contoh: Poster \"Buang Sampah\" dengan gambar orang membuang sampah + teks \"Buang Sampah pada Tempatnya\".",
          "",
          "2. KOMPLEMENTER — Visual dan teks saling MELENGKAPI. Masing-masing memberikan informasi yang tidak bisa disampaikan oleh yang lain. Ini hubungan paling efektif.",
          "  Contoh: Poster \"Lindungi Hutan\" — gambar hutan gundul yang suram (visual: suasana, emosi) + teks \"Setiap pohon yang ditebang tanpa reboisasi adalah masa depan yang hilang\" (teks: data, ajakan). Gambar tidak bisa menyampaikan kata 'reboisasi', teks tidak bisa menyampaikan kemuraman hutan.",
          "",
          "3. KONTRASTIF — Visual dan teks sengaja DIPERTENTANGKAN untuk menciptakan kejutan atau ironi. Efek kuat, berisiko ambigu.",
          "  Contoh: Poster anti-rokok — gambar seorang pria bugar tersenyum (visual positif) + teks \"Tembakau yang kau hisap sekarang mengendap di paru-parumu. 10 tahun lagi? Kamu tidak akan tersenyum.\" Kontras antara senyum dan ancaman menciptakan kejutan.",
          "",
          "KOMPOSISI POSTER IDEAL (Visual Layout):",
          "• Bagian Atas (60%): Judul besar + Gambar/Visual dominan — menarik perhatian dari jauh.",
          "• Bagian Tengah (20%): Pesan pendukung atau subjudul.",
          "• Bagian Bawah (20%): Call to action, logo, identitas, kontak.",
          "",
          "[Ilustrasi: Tiga poster identik dalam satu baris perbandingan. Poster 1 (REDUNDANSI): gambar tempat sampah + teks 'Buang Sampah'. Poster 2 (KOMPLEMENTER): gambar hutan gundul + teks 'Setiap pohon berarti'. Poster 3 (KONTRASTIF): gambar senyum + teks kutukan. Masing-masing diberi label.]",
          "",
          "Tips: Untuk poster di jalan/billboard, gunakan hubungan KOMPLEMENTER — paling efektif di ruang publik karena gambar menarik perhatian, teks memperjelas pesan. Untuk poster digital di media sosial, REDUNDANSI kadang lebih baik karena feed cepat discroll.",
        ],
        contoh: [
          "Analisis target audiens: tiga versi iklan tema yang sama — KOPI.",
          "",
          "VERSI 1 (Target: Remaja):",
          "Platform: TikTok / Instagram Reels.",
          "Visual: Video fast-cut — anak muda nongkrong di kafe aesthetic, minum kopi sambil ketawa, slow-mo saat menuang kopi ke es batu. Filter hangat, font sans-serif bulky.",
          "Teks: \"It's not just coffee, it's vibe. #KopinyaAnakMuda\"",
          "CTA: \"Tag temen kopi kamu!\"",
          "Mengapa cocok: visual trendi, bahasa Inggris campuran, bahasa santai, platform sesuai demografi remaja.",
          "",
          "VERSI 2 (Target: Profesional/Eksekutif):",
          "Platform: LinkedIn, majalah bisnis, website.",
          "Visual: Foto kopi dalam cangkir keramik putih di meja kerja minimalis dengan laptop dan buku catatan. Pencahayaan natural, komposisi rapi, warna earth tone.",
          "Teks: \"Mulai hari Anda dengan fokus maksimal. Single origin Arabica Gayo — kafein premium untuk produktivitas puncak.\"",
          "CTA: \"Beli langganan bulanan — nikmati diskon 15% untuk professional.\"",
          "Mengapa cocok: bahasa formal, manfaat produktivitas, gaya visual profesional, platform sesuai eksekutif.",
          "",
          "VERSI 3 (Target: Dewasa/Keluarga):",
          "Platform: TV, koran, brosur di supermarket.",
          "Visual: Foto sekeluarga di ruang tamu — ayah, ibu, kakek, nenek — semua minum kopi sambil mengobrol hangat. Warna hangat, lighting soft.",
          "Teks: \"Kopi Nusantara — menemani kebersamaan keluarga dari dulu hingga sekarang. Rasa otentik yang tak pernah berubah.\"",
          "CTA: \"Tersedia di Indomaret, Alfamart, dan pasar tradisional terdekat.\"",
          "Mengapa cocok: nilai nostalgia dan kebersamaan, platform luas, distribusi massal.",
          "",
          "BENAR: Memilih platform, visual, bahasa, dan CTA yang sesuai dengan karakteristik masing-masing target audiens.",
          "SALAH: Membuat SATU iklan yang sama untuk semua platform dan semua target — tidak akan optimal di mana pun.",
        ],
        catatan: "Kesalahan paling umum dalam beriklan adalah 'target audience fallacy' — menganggap produk yang bagus akan laku ke semua orang. Bahkan air minum dalam kemasan pun punya segmen berbeda: Aqua target keluarga, Le Minerale target anak muda aktif, Pristine target premium/kelas atas. Bedanya ada di kemasan, harga, visual iklan, dan platform media.",
      },
      {
        judul: "Teknik Propaganda dan Slogan Efektif",
        isi: [
          "Tidak semua bujukan dalam iklan bersifat transparan. Beberapa menggunakan TEKNIK PROPAGANDA — metode persuasi yang memengaruhi audiens secara tidak sadar, sering dengan memanipulasi emosi dan logika. Memahami teknik ini penting agar kamu tidak mudah termakan iklan dan bisa membuat iklan yang etis.",
          "",
          "TEKNIK PROPAGANDA DALAM IKLAN:",
          "",
          "1. TRANSFER — Memindahkan perasaan positif atau negatif dari suatu simbol/figur ke produk. Mengasosiasikan produk dengan nilai-nilai luhur.",
          "  ✓ Iklan rokok dulu: adegan pria perkasa di gunung + lagu heroik → 'rasa kebebasan' ditransfer ke produk.",
          "  ✓ Iklan mobil: bendera Merah Putih berkibar + lagu 'Tanah Air' → nasionalisme ditransfer ke mobil.",
          "  Cara kerjanya: kita tidak membeli produk, kita membeli PERASAAN yang terkait dengan produk.",
          "",
          "2. BANDWAGON — 'Ikut-ikutan orang banyak.' Membujuk dengan argumen bahwa 'semua orang sudah pakai, masa kamu belum?' Memanfaatkan fear of missing out (FOMO).",
          "  ✓ \"Sudah 10 juta orang beralih ke Provider X! Kapan kamu?\"",
          "  ✓ \"Produk ini VIRAL di TikTok! 2 juta box sudah terjual!\"",
          "  ✓ \"Semua temanmu sudah punya sepatu ini. Masa kamu ketinggalan?\"",
          "  Efektif untuk remaja dan produk fashion/teknologi.",
          "",
          "3. FEAR APPEAL — Menakut-nakuti audiens tentang konsekuensi buruk jika TIDAK menggunakan produk/mengikuti imbauan.",
          "  ✓ \"Jika tidak memakai tabir surya, kulitmu akan rusak sebelum usia 40!\"",
          "  ✓ \"Asuransi? Atau keluargamu terlantar?\"",
          "  ✓ Iklan layanan masyarakat 'AIDS: Lebih Baik Mencegah' dengan gambar mengerikan.",
          "  Efektif tapi berisiko: terlalu menakutkan bisa membuat audiens mengabaikan (defense mechanism).",
          "",
          "4. TESTIMONIAL — Menggunakan tokoh terkenal (selebriti, influencer, atlet) atau 'orang biasa' yang dianggap mewakili target audiens untuk merekomendasikan produk.",
          "  ✓ Iklan skincare dengan artis Korea — penggemar ingin kulit seperti idolanya.",
          "  ✓ Iklan sabun dengan ibu rumah tangga — 'saya sudah pakai 10 tahun, alhamdulillah...'",
          "  ✓ Iklan susu dengan atlet bulutangkis — 'biar kuat kayak atlet!'",
          "  Bedanya dengan ETOS: testimonial tidak harus ahli, cukup populer atau relatable.",
          "",
          "5. GLITTERING GENERALITIES — Menggunakan kata-kata 'indah' yang abstrak dan bermuatan positif (kebebasan, keadilan, cinta, masa depan, tradisi) tanpa definisi konkret.",
          "  \"Kembali ke tradisi...\" (tradisi yang mana? tidak dijelaskan)",
          "  \"Untuk masa depan anak-anak kita...\" (siapa yang menolak masa depan anak?)",
          "  Kata-kata ini sulit ditolak karena semua orang setuju, tapi isinya kosong.",
          "",
          "Tips: Siswa yang cerdas harus bisa MENGENALI teknik propaganda di atas. Bukan untuk ditakuti, tapi untuk dipahami. Saat melihat iklan, tanyakan: 'Teknik apa yang dipakai? Apakah ada data nyata atau hanya manipulasi emosi?' Ini adalah LITERASI MEDIA.",
          "",
          "MEMBUAT SLOGAN EFEKTIF — Lebih dari Sekadar Pendek:",
          "Slogan yang hebat bukan sekadar pendek. Ia memiliki KEKUATAN LINGUISTIK yang membuatnya menetap di memori. Elemen-elemennya:",
          "",
          "• RHYTHM (Irama) — Pola tekanan suku kata yang enak didengar.",
          "  ✓ \"Beres — Dijamin — Beres\" (Klinik — 3 ketukan, masing-masing 2 suku kata, berirama marching)",
          "  ✓ \"Sebelum — Lo — Ngomong — Lo — Pikir — Dulu\" (iklan Rokok — 6 ketukan santai)",
          "",
          "• RHYME (Rima) — Persamaan bunyi di akhir frasa.",
          "  ✓ \"Berani Jujur Hebat\" (-at)",
          "  ✓ \"Muda Berkarya, Bangga Indonesia\" (-a dan -a samar)",
          "  ✓ \"Ada Aqua\" — rima internal vokal 'a' berulang",
          "",
          "• CONCISENESS (Ringkas) — Ideal 3–7 kata. Bisa lebih panjang jika ada rima kuat.",
          "  ✓ \"Apapun makanannya, minumnya Teh Botol Sosro\" (7 kata, berima internal 'nya')",
          "  ✗ \"Produk kami diproduksi dengan bahan-bahan terbaik pilihan dari alam Indonesia\" (15 kata — sulit diingat)",
          "",
          "• MEMORABILITY — Mengandung kejutan, humor, atau permainan kata.",
          "  ✓ \"Mak Nyus\" (iklan Mi Sedap — singkat, onomatope, bermakna ganda: enak + 'mak' dari ibu)",
          "  ✓ \"Ketagihan? Jangan-jangan!\" (iklan kerupuk — larangan yang justru mengundang)",
          "",
          "PLATFORM MEDIA DAN STRATEGI KONTEN:",
          "Setiap platform punya karakteristik yang memengaruhi cara kita beriklan:",
          "• CETAK (koran/majalah): teks lebih panjang, tidak ada audio, visual statis, audiens lebih tua.",
          "• DIGITAL (website/banner): teks singkat, visual mencolok, CTA klik, audiens segala usia.",
          "• OUTDOOR (billboard/spanduk): teks SANGAT singkat (3–5 kata), visual besar, jarak pandang jauh.",
          "• SOSIAL MEDIA (IG/TikTok/YouTube): video pendek, interaktif, hashtag, viral potential, audiens muda.",
          "• RADIO: hanya audio — kekuatan ada di suara, musik, jingle, dan kata-kata.",
          "",
          "PENTING: Satu kampanye besar biasanya menggunakan MULTI-PLATFORM. Iklan TV menarik perhatian → audiens mencari di Instagram → membaca detail di website → membeli di e-commerce. Setiap platform punya peran berbeda dalam 'customer journey'.",
          "",
          "[Ilustrasi: Sketsa tata letak poster ideal dengan grid komposisi 60/20/20. Garis putus-putus horizontal membagi poster: 60% atas (headline besar + gambar dominan), 20% tengah (subjudul + pesan), 20% bawah (CTA + logo + QR code). Anak panah menunjukkan arah baca alami: atas → tengah → bawah.]",
        ],
        contoh: [
          "Analisis teknik propaganda dalam iklan terkenal Indonesia.",
          "",
          "IKLAN: \"Shopee — Goyang Shopee\" (2018–2020).",
          "",
          "TEKNIK BANDWAGON: \"Semua orang dari artis sampai ibu-ibu goyang Shopee!\" — menciptakan kesan massal, 'semua orang melakukan ini, kamu ikut dong.'",
          "",
          "TEKNIK TRANSFER: Lagu \"Shopee... Shopee...\" yang ceria dan gerakan goyang sederhana — transfer kegembiraan dan energi positif ke aplikasi belanja. Orang tidak sekadar belanja, mereka ikut 'vibe' ceria.",
          "",
          "TESTIMONIAL: Menggunakan sederet artis papan atas (Raffi Ahmad, Gisel, dll.) — penggemar setiap artis tertarik untuk ikut.",
          "",
          "GLITTERING GENERALITIES: \"Happy shopping!\" — kata 'happy' abstrak, semua orang ingin bahagia. Tidak ada definisi konkret tentang apa itu 'happy shopping' yang membedakan dengan kompetitor.",
          "",
          "APAKAH INI ETIS? Tergantung perspektif. Shopee memang memberikan promo nyata, jadi bandwagon-nya didukung bukti. Tetapi jika sebuah iklan hanya mengandalkan propaganda tanpa substansi — misalnya '99% wanita Indonesia sudah pakai krim ini' padahal hanya 100 orang yang disurvei — itu manipulatif.",
          "",
          "BENAR: Iklan etis menggunakan teknik propaganda + data/fakta nyata. Contoh: \"Sudah 5 juta pengguna puas — bukti review rating 4.8 di Google Play.\" Propaganda (bandwagon) + logos (data) = kuat.",
          "SALAH: Iklan hanya mengandalkan propaganda tanpa bukti. Contoh: \"Produk terbaik di Indonesia\" tanpa sertifikasi, data, atau penghargaan apapun — manipulasi murni.",
        ],
        catatan: "Di Indonesia, etika periklanan diatur oleh Persatuan Perusahaan Periklanan Indonesia (P3I) dan Komisi Penyiaran Indonesia (KPI). Iklan dilarang: (1) menyesatkan konsumen, (2) melecehkan pesaing, (3) mengandung unsur SARA, (4) mendorong kekerasan, (5) mengeksploitasi anak-anak. Pelanggar bisa kena sanksi teguran hingga pencabutan izin tayang.",
      },
    ],
    rangkuman: [
      "Iklan = pesan persuasif berbayar via media, slogan = frasa pendek identitas (bisa berdiri sendiri atau menjadi bagian iklan/poster), poster = plakat bergambar + teks untuk sekali pandang. Dalam praktik, ketiganya sering menyatu dalam satu kampanye IMC.",
      "Tiga mode persuasi Aristoteles: ETOS (kredibilitas — ahli, otoritas, selebriti), PATOS (emosi — haru, takut, bangga), LOGOS (logika — data, statistik, fakta). Iklan paling kuat menggabungkan ketiganya + CTA yang jelas.",
      "Target audiens dianalisis melalui DEMOGRAFI (usia, profesi, lokasi) dan PSIKOGRAFI (gaya hidup, nilai, minat). Anak-anak suka warna/ceria, remaja suka trendi/gaul, dewasa suka logis/profesional. Iklan yang tidak sesuai target akan diabaikan.",
      "Hubungan visual-teks dalam poster: REDUNDANSI (sama-sama), KOMPLEMENTER (saling melengkapi — paling efektif), KONTRASTIF (dipertentangkan — efek kejutan). Komposisi ideal 60% visual/judul, 20% pesan, 20% CTA/logo.",
      "Teknik propaganda: TRANSFER (asosiasi simbol), BANDWAGON (ikut orang banyak), FEAR APPEAL (takut), TESTIMONIAL (tokoh terkenal), GLITTERING GENERALITIES (kata indah abstrak). Sadarilah teknik-teknik ini saat melihat iklan!",
      "Slogan efektif memiliki: rhythm (irama), rhyme (rima), conciseness (3–7 kata), dan memorability (kejutan/humor). Platform media menentukan gaya konten: cetak (teks panjang), outdoor (sangat singkat), sosial media (video interaktif).",
    ],
  },

  latihan: makeSoal([
    ["Teknik persuasif ETOS dalam iklan mengandalkan...", ["Rasa takut dan khawatir audiens", "Kredibilitas, kepercayaan, dan otoritas sumber pesan", "Data statistik dan fakta logis", "Ajakan langsung untuk membeli"], 1, "ETOS adalah persuasi melalui kredibilitas — pembicara ahli, tokoh terpercaya, institusi resmi, atau sumber yang dihormati."],
    ["Seorang pengiklan membuat poster dengan gambar hutan hijau subur dan teks 'Selamatkan Bumi, Kurangi Emisi!'. Hubungan visual-teks yang digunakan adalah...", ["Redundansi — visual dan teks menyampaikan pesan sama", "Komplementer — visual dan teks saling melengkapi", "Kontrastif — visual dan teks dipertentangkan", "Tidak ada hubungan"], 0, "Gambar hutan hijau (visual alam yang perlu dilindungi) dan teks 'Selamatkan Bumi' menyampaikan pesan yang sama — redundansi, pesan jelas dan langsung."],
    ["Iklan minuman energi menampilkan atlet bulutangkis terkenal yang bilang 'Saya minum ini setiap hari sebelum bertanding.' Teknik propaganda yang digunakan adalah...", ["Bandwagon", "Transfer", "Testimonial", "Fear appeal"], 2, "Testimonial — menggunakan figur terkenal (atlet) yang dianggap kredibel dan menjadi panutan untuk merekomendasikan produk."],
    ["Manakah slogan berikut yang PALING efektif berdasarkan prinsip rhythm dan rhyme?", ["Produk pembersih lantai yang paling bagus dan berkualitas tinggi", "Bersih Bersinar, Wangi Menawan", "Kami menjual produk kebersihan untuk rumah tangga Indonesia", "Pembersih lantai terbaik nomor satu"], 1, "'Bersih Bersinar, Wangi Menawan' — 4 kata, berima 'bersinar-menawan' (akhiran -ar/-an), irama 2 ketukan seimbang, mudah diingat."],
    ["Poster di billboard pinggir jalan tol paling efektif jika teksnya...", ["Panjang dan informatif (50+ kata)", "Sangat singkat (3–5 kata) dengan visual besar", "Berisi data statistik lengkap", "Terdiri dari 2 paragraf penjelasan produk"], 1, "Billboard dilihat dari kendaraan yang melaju — hanya 2-3 detik pandangan. Teks harus SANGAT singkat (3–5 kata), visual besar dan mencolok."],

    ["Pernyataan: 'Iklan untuk anak-anak sebaiknya menggunakan bahasa formal dan data statistik agar terlihat kredibel.'", ["Betul", "Salah"], 1, "SALAH. Anak-anak lebih responsif terhadap warna cerah, karakter kartun, bahasa sederhana, dan jingle — bukan data statistik yang membosankan bagi mereka."],
    ["Pernyataan: 'Fear appeal dalam iklan asuransi — menampilkan kecelakaan dan keluarga berduka — termasuk teknik propaganda yang menggunakan emosi takut.'", ["Betul", "Salah"], 0, "BETUL. Fear appeal sengaja memicu rasa takut akan konsekuensi buruk agar audiens terdorong membeli asuransi sebagai perlindungan."],
    ["Pernyataan: 'Hubungan kontrastif antara visual dan teks dalam poster berarti visual dan teks mendukung satu sama lain secara harmonis.'", ["Betul", "Salah"], 1, "SALAH. Kontrastif berarti visual dan teks DIPERTENTANGKAN secara sengaja untuk menciptakan kejutan/ironi. Hubungan yang saling mendukung adalah komplementer."],

    ["Teknik persuasi yang menggunakan argumen 'semua orang sudah pakai, masa kamu belum?' disebut...", ["transfer", "bandwagon", "logos", "glittering generalities"], 1, "Bandwagon — membujuk dengan menciptakan kesan massal bahwa 'semua orang sudah melakukannya', memicu FOMO dan keinginan ikut-ikutan."],
    ["Platform iklan yang paling tepat untuk menjangkau remaja dengan konten interaktif dan viral potential adalah...", ["Koran cetak", "Radio", "Billboard pinggir jalan", "Media sosial (TikTok/Instagram)"], 3, "Media sosial (TikTok/Instagram) adalah platform utama remaja — konten video pendek, tren viral, interaktif, dan algoritma yang sesuai minat."],
  ]),

  praktik: {
    petunjuk: "Buatlah KAMPANYE IKLAN MULTI-PLATFORM lengkap untuk produk atau kampanye sosial pilihanmu.\n\nPilih SALAH SATU tema berikut:\n1. Produk fiktif: \"Kopi Nusantara\" — kopi sachet instan rasa nusantara.\n2. Produk fiktif: \"Skuy!\" — aplikasi belajar bahasa daerah untuk remaja.\n3. Kampanye sosial: \"Generasi Emas 2045\" — ajakan berprestasi untuk pelajar SMP.\n4. Kampanye sosial: \"Jaga Digital Footprint\" — edukasi tentang jejak digital positif.\n5. Produk fiktif: \"Lestari Bag\" — tas belanja ramah lingkungan dari bahan daur ulang.\n\nTugasmu adalah menuliskan DOKUMEN KAMPANYE dengan 7 bagian berikut:\n\n1. RINGKASAN EKSEKUTIF — Nama produk/kampanye, target audiens (demografi + psikografi), dan tujuan utama kampanye (2–3 kalimat).\n2. ANALISIS TARGET — Profil audiens: usia, profesi, gaya hidup, kebiasaan media, dan 'pain point' (masalah yang produkmu selesaikan). Minimal 4 kalimat.\n3. STRATEGI PERSUASI — Jelaskan ETOS, PATOS, LOGOS mana yang akan kamu tekankan dan MENGAPA sesuai dengan target audiens. Beri contoh konkret.\n4. SLOGAN UTAMA — Satu slogan (3–7 kata) dengan analisis: rhythm, rhyme, dan memorability-nya. Jelaskan mengapa slogan ini efektif.\n5. IKLAN MEDIA SOSIAL (Instagram/TikTok) — Deskripsi video 15–30 detik: visual, musik, narasi, teks di layar, CTA, hashtag.\n6. POSTER CETAK — Deskripsi poster (bukan gambar): ukuran, komposisi 60/20/20, hubungan visual-teks (redundansi/komplementer/kontrastif), warna, tipografi.\n7. BILLBOARD / OUTDOOR — Teks SANGAT SINGKAT (3–5 kata) + deskripsi visual besar yang bisa dipahami dari kendaraan melaju.\n\nPanjang deskripsi kampanye minimal 5 paragraf.",
    tips: [
      "JANGAN langsung buat iklan. Mulailah dengan ANALISIS TARGET: siapa yang kamu ajak bicara? Semakin spesifik profiling-mu, semakin tepat strategi yang kamu pilih.",
      "Pilih SATU mode persuasi dominan yang sesuai target: untuk anak muda yang rasional → logos (data, perbandingan). Untuk orang tua → patos (emosi keluarga). Untuk profesional → etos (kredibilitas, sertifikasi).",
      "Slogan bukan sekadar 'yang penting pendek'. Uji sloganmu: baca keras-keras. Apakah enak diucapkan? Apakah ada rima/irama? Bisakah orang mengingatnya setelah 1 kali dengar?",
      "Satu kampanye ≠ satu konten. Iklan Instagram (video pendek, santai) HARUS berbeda dengan billboard (3 kata, visual besar) — meskipun temanya sama. Sesuaikan platform!",
      "Hubungan visual-teks KOMPLEMENTER adalah yang paling aman dan efektif. Visual menarik perhatian, teks memperjelas pesan. Pastikan keduanya bisa berdiri sendiri namun lebih kuat bersama.",
      "Teknik propaganda BOLEH digunakan, tapi harus etis — didukung data dan fakta nyata. Jangan membuat klaim palsu hanya demi menjual. Iklan yang menipu akan merusak kepercayaan dan bisa kena sanksi hukum.",
      "Periksa kampanyemu dengan prinsip AIDA: Apakah headline-mu menangkap ATTENTION? Apakah isi iklan membangkitkan INTEREST? Apakah audiens merasa DESIRE? Apakah CTA mendorong ACTION?",
      "Cek konsistensi: pastikan slogan, warna, font, dan 'brand voice' konsisten di semua platform. Audiens harus langsung mengenali merekmu, baik di TikTok, poster, maupun billboard.",
      "Pertimbangkan etika: apakah iklanmu mengandung stereotip? Apakah visualnya menghormati semua gender, suku, dan agama? Iklan yang inklusif lebih dihargai audiens modern.",
      "Sertakan analisis MENGAPA setiap keputusan diambil — bukan sekadar \"saya buat poster merah\" tapi \"saya pilih merah karena menimbulkan urgensi dan sesuai target audiens muda yang energik.\"",
    ],
    contoh: "KAMPANYE: \"Lestari Bag\" — Tas Belanja Ramah Lingkungan\n\n1. RINGKASAN EKSEKUTIF\nLestari Bag adalah tas belanja lipat berbahan daur ulang plastik PET yang ringan, kuat, dan bisa dicuci. Target audiens: perempuan dan laki-laki urban usia 25–40 tahun, kelas menengah, yang sudah sadar lingkungan dan aktif belanja di supermarket/mall. Tujuan kampanye: mendorong kebiasaan membawa tas belanja sendiri untuk mengurangi sampah plastik sekali pakai.\n\n2. ANALISIS TARGET\nTarget utama: urban profesional usia 25–40 tahun — pekerja kantoran, freelancer, ibu rumah tangga modern yang aktif belanja mingguan. Gaya hidup: mulai peduli lingkungan, suka produk estetik, aktif di Instagram, langganan e-commerce. Pain point: sering lupa bawa tas belanja, akhirnya terpaksa beli kantong plastik di kasir — merasa bersalah pada lingkungan tapi belum punya solusi praktis. Mereka butuh tas yang: (1) selalu siap di tas tangan, (2) stylish biar tidak malu dipakai, (3) kuat angkut belanjaan 5 kg+.\n\n3. STRATEGI PERSUASI\nDOMINAN: ETOS — bekerja sama dengan LSM lingkungan dan eco-influencer untuk kredibilitas. Tas ini bersertifikat 'EcoLabel Indonesia' dan hasil riset ITB. PATOS — visual sebelum-sesudah: laut bersih vs laut penuh sampah plastik, rasa bangga saat memakai tas sambil bilang 'ini dari sampah plastik lho!' LOGOS — data: \"Setiap tas Lestari Bag menyelamatkan 15 botol plastik dari TPA. Dalam 1 tahun, kamu menghemat 520 kantong plastik.\"\n\n4. SLOGAN UTAMA\n\"Lestari — Bumi Tersenyam, Kantong Tak Terisi Sampah\" (6 kata). Rhythm: 2 frase seimbang (3 kata + 4 kata). Rhyme internal: 'tersenyam' (plesetan tersenyam/senyap) dengan 'terisi' — permainan kata yang memorable. Memorability: plesetan lucu 'tersenyum' jadi 'tersenyam' membuat orang berhenti dan mikir — jadi diingat.\n\n5. IKLAN MEDIA SOSIAL (Instagram Reels 20 detik)\nBuka: Close-up tangan merogoh tas tangan, mengeluarkan Lestari Bag yang dilipat kecil (ukuran sebungkus tisu). Potong: Tangan membuka lipatan — tas mengembang jadi ukuran penuh. Potong: Scene di kasir — petugas bilang \"Mau kantong plastik?\", karakter angkat Lestari Bag sambil senyum \"Udah bawa, Kak!\" Potong: Overlay teks \"Lestari Bag — 15 botol plastik daur ulang dalam setiap tas.\" Potong: Karakter berjalan keluar mall sambil pegang Lestari Bag, latar matahari sore. CTA: \"Klik link di bio — diskon 20% untuk pre-order! #LestariBag #EcoFriendly #PlastikKurang\". Musik: Upbeat akustik, forest vibes. Hubungan visual-teks: KOMPLEMENTER — video menunjukkan kepraktisan, teks memberikan data lingkungan.\n\n6. POSTER CETAK (A3, dipajang di kafe dan co-working space)\nHEADLINE: BESAR — \"KAMU MASIH PAKE KANTONG PLASTIK?\" font bold sans-serif warna hitam, 60% bagian atas.\nVISUAL: Ilustrasi perbandingan dua sisi — kiri: lautan indah dengan ikan lumba-lumba. Kanan: lautan penuh sampah plastik, lumba-lumba terjebak kantong kresek. Gaya ilustrasi semi-realistis, warna kontras (biru jernih vs abu-abu keruh).\nSUBHEAD: \"Setiap tahun, 8 juta ton plastik mencemari laut. Mulai ubah kebiasaan dari hal kecil: bawa tas belanja sendiri.\" (pesan logos + patos).\nCTA: \"Pre-order Lestari Bag sekarang di lestaribag.id — Diskon 20%!\"\nLOGO: Logo Lestari Bag (daun hijau + motif batik) di pojok kanan bawah.\nHubungan visual-teks: KOMPLEMENTER — gambar menunjukkan dampak nyata (visual), teks memberi solusi spesifik (teks). Layout 60% atas (headline + ilustrasi), 20% tengah (subhead), 20% bawah (CTA + logo).\n\n7. BILLBOARD (4×6 meter, di jalan protokol)\nVISUAL: Foto close-up seorang ibu muda tersenyum percaya diri, memakai Lestari Bag selempang, latar biru langit cerah. Tas digambarkan cukup besar untuk terlihat dari jarak jauh.\nTEKS: Hanya 4 kata — \"BUMI HAPPY, KAMU JUGA!\" font putih bold dengan stroke hijau, melengkung mengikuti komposisi.\nLOGO: Kecil di kiri bawah — \"Lestari Bag\" + tagline \"Tas Daur Ulang, Gaya Tak Berubah.\"\nMengapa hanya 4 kata? Karena billboard di jalan raya hanya terlihat 2–3 detik. 'Bumi Happy' — bahasa campuran Indonesia-Inggris yang catchy untuk target urban. 'Kamu Juga' — CTA personal. Visual ibu muda tersenyum membuat audiens merasa 'aku juga bisa happy kayak dia.' Hubungan visual-teks: REDUNDANSI — senyum bahagia + teks 'happy' — mudah dipahami sekilas, pesan positif langsung sampai.",
  },

  kuis: makeSoal([
    ["Perbedaan mendasar antara teknik ETOS dan TESTIMONIAL dalam iklan adalah...", ["Etos menggunakan data, testimonial menggunakan gambar", "Etos mengandalkan kredibilitas KEAHLIAN/OTORITAS, testimonial mengandalkan popularitas/kedekatan figur", "Etos hanya untuk produk kesehatan, testimonial untuk semua produk", "Tidak ada perbedaan — keduanya sama"], 1, "Etos = kredibilitas dari keahlian (dokter, profesor, institusi resmi). Testimonial = figur terkenal/relatable yang belum tentu ahli, cukup populer atau dipercaya audiens target."],
    ["Cermati cuplikan iklan: 'Menurut data Kementerian Kesehatan, 7 dari 10 anak Indonesia kekurangan vitamin D. Suplemen X hadir sebagai solusi — mengandung 1000 IU vitamin D3 yang setara dengan kebutuhan harian.' Mode persuasi yang paling dominan dalam cuplikan tersebut adalah...", ["Patos — menyentuh emosi orang tua", "Etos — kredibilitas lembaga resmi + data faktual", "Bandwagon — mengikuti orang banyak", "Fear appeal — menakut-nakuti orang tua"], 1, "LOGOS (dominan) + ETOS: menggunakan data resmi dari Kementerian Kesehatan (logos) dan menyebutkan lembaga berwenang (etos). Patos tidak dominan di sini."],
    ["Seorang siswa membuat poster dengan gambar sampah berserakan di pantai yang indah. Teks posternya: 'Pantai ini masih cantik, kan?' Hubungan visual-teks yang digunakan adalah...", ["Redundansi", "Komplementer", "Kontrastif", "Paradoks"], 2, "KONTRASTIF: Gambar menunjukkan sampah (visual negatif) tetapi teks 'masih cantik, kan?' justru mempertanyakan secara ironis. Pertentangan ini menciptakan kejutan yang membuat orang berpikir lebih dalam."],
    ["Produk kecantikan mengklaim '9 dari 10 wanita Indonesia sudah beralih ke krim pemutih X.' Setelah diselidiki, survei hanya melibatkan 20 orang di satu kota. Teknik propaganda yang digunakan adalah..., dan masalah etisnya adalah...", ["Transfer — tidak masalah karena tetap persuasif", "Bandwagon — klaim menyesatkan karena sampel tidak representatif", "Glittering generalities — tidak ada masalah", "Testimonial — perlu tambahan artis"], 1, "BANDWAGON: '9 dari 10 beralih' menciptakan kesan massal. Masalah etis: sampel 20 orang di satu kota TIDAK representatif. Ini menyesatkan konsumen."],
    ["Dalam merancang kampanye multi-platform, mengapa konten Instagram dan billboard untuk produk yang SAMA harus berbeda?", ["Karena produknya berbeda", "Karena setiap platform punya karakteristik audiens dan durasi atensi yang berbeda — konten harus disesuaikan", "Karena Instagram lebih murah", "Karena billboard sudah ketinggalan zaman"], 1, "Instagram: durasi atensi pendek, video, scroll cepat — butuh konten engaging dalam detik pertama. Billboard: dilihat dari jarak jauh, 2-3 detik — butuh teks sangat singkat, visual besar. Platform menentukan format."],
    ["Iklan sebuah aplikasi belajar menampilkan anak tersenyum bahagia setelah nilai ujiannya bag berkat aplikasi X, lalu muncul teks 'Aplikasi X — #1 di Play Store Pendidikan.' Kombinasi persuasi yang digunakan adalah...", ["Patos (senyum bahagia) + Etos/Logos (rating #1)", "Hanya patos", "Hanya logos", "Hanya bandwagon"], 0, "Patos: visual anak bahagia menyentuh emosi orang tua. Etos/Logos: '#1 di Play Store' adalah data prestise (logos sekaligus etos — membangun kredibilitas melalui peringkat)."],
    ["Manakah pernyataan yang BENAR tentang hubungan visual-teks dalam poster?", ["Poster bisa tanpa teks — gambar saja cukup", "Hubungan komplementer berarti visual dan teks menyampaikan pesan berbeda yang saling melengkapi — paling efektif untuk poster informatif", "Hubungan kontrastif harus dihindari karena membingungkan", "Semakin banyak teks semakin baik agar pesan sampai"], 1, "Komplementer: visual dan teks masing-masing punya peran dan saling melengkapi — gambar tidak bisa menyampaikan data, teks tidak bisa menyampaikan emosi visual. Ini yang paling efektif untuk poster informatif."],
    ["Slogan berikut: 'Beres — Dijamin — Beres' (Klinik) dan 'Sebelum — Lo — Ngomong — Lo — Pikir — Dulu' (rokok) memiliki kesamaan dalam hal...", ["Panjang slogan (keduanya 6 kata)", "Menggunakan rima akhir yang sama", "Memiliki irama (rhythm) yang kuat dengan pola ketukan", "Keduanya menggunakan bahasa gaul"], 2, "Keduanya memiliki RHYTHM yang kuat: 'Beres — Dijamin — Beres' (3 ketukan pendek tegas), 'Sebelum — Lo — Ngomong — Lo — Pikir — Dulu' (6 ketukan santai). Rhythm membuat slogan enak diucapkan dan diingat."],
    ["Seorang pengiklan ingin membuat poster untuk anak-anak tentang pentingnya mencuci tangan. Desain yang PALING TEPAT adalah...", ["Poster hitam-putih dengan data statistik jumlah kuman di tangan", "Poster warna-warni dengan karakter kartun sabun bernama 'Soapy', teks pendek 'Cuci Tangan Yuk!', dan stiker bintang", "Poster dengan foto dokter serius memegang mikroskop", "Poster teks panjang menjelaskan 6 langkah cuci tangan WHO"], 1, "Anak-anak (5–12 tahun) paling responsif pada: warna cerah, karakter kartun, bahasa sederhana, jingle. Poster dengan karakter Soapy + teks pendek + elemen gamifikasi (stiker) paling sesuai demografi anak."],
    ["Dalam konteks dunia periklanan modern, mengapa teknik GLITTERING GENERALITIES dianggap berbahaya?", ["Karena menggunakan kata-kata asing", "Karena menggunakan kata-kata indah abstrak tanpa definisi konkret sehingga bisa menyesatkan audiens", "Karena terlalu pendek untuk dipahami", "Karena hanya efektif di media cetak"], 1, "Glittering generalities ('kebebasan', 'tradisi', 'masa depan', 'kualitas') menggunakan kata-kata bermuatan positif yang abstrak dan sulit didefinisikan. Semua orang setuju dengan kata-kata ini, tapi isinya bisa kosong. Bahaya: audiens merasa setuju tanpa benar-benar tahu apa yang mereka setujui."],
  ]),
}

export default konten
