import type { Konten } from "../types"
import { makeSoal } from "../types"

const konten: Konten = {
  belajar: {
    tujuan: [
      "Memahami pengertian, tujuan, dan struktur teks ulasan",
      "Menganalisis kelebihan dan kekurangan suatu karya secara kritis dan objektif",
      "Mengenal kaidah kebahasaan dan jenis-jenis teks ulasan",
      "Menulis teks ulasan untuk buku, film, lagu, atau karya seni dengan etika yang baik",
    ],
    materi: [
      {
        judul: "Apa Itu Teks Ulasan?",
        isi: [
          "Pernahkah kamu selesai menonton film lalu memberi komentar ke teman? Atau selesai membaca novel lalu menulis pendapatmu di media sosial? Selamat — kamu sudah melakukan aktivitas ULASAN!",
          "Teks ulasan (review) adalah teks yang mengulas, mengkritik, atau mengevaluasi suatu karya — buku, film, lagu, drama, pameran seni, aplikasi, atau produk — untuk memberikan penilaian dan pertimbangan kepada pembaca.",
          "TUJUAN TEKS ULASAN:",
          "  • Memberikan INFORMASI tentang kualitas suatu karya",
          "  • Membantu pembaca MEMUTUSKAN apakah akan menikmati/membeli karya tersebut",
          "  • Memberikan APRESIASI kepada kreator karya",
          "  • Menyajikan KRITIK MEMBANGUN untuk perbaikan karya selanjutnya",
          "",
          "Bagi seorang pelajar, kemampuan menulis ulasan sangat penting karena melatih kamu berpikir KRITIS, ANALITIS, dan OBJEKTIF. Kamu belajar melihat karya dari berbagai sudut pandang, bukan sekadar 'suka' atau 'tidak suka'.",
          "",
          "[Ilustrasi: Tampilan kartu ulasan film dengan foto poster di kiri, rating bintang (4/5) di kanan atas, dan panel-panel terlabel: Sinopsis (3 baris), Kelebihan (poin-poin hijau), Kekurangan (poin-poin merah), dan Kesimpulan/Rekomendasi di bagian bawah dengan ikon 'cocok untuk remaja'.]",
        ],
        contoh: [
          "Bandingkan dua tanggapan berikut tentang film yang sama:",
          "",
          "TANGGAPAN BIASA: \"Filmnya bagus, seru, keren deh. Recommended!\"",
          "",
          "TANGGAPAN ULASAN: \"Film ini menawarkan alur cerita yang unik dengan plot twist di menit ke-60 yang benar-benar tak terduga. Karakter utamanya kuat secara emosional, meskipun beberapa dialog terasa kaku. Sinematografinya indah, terutama adegan di pantai. Skor 8/10 — sangat cocok untuk penggemar drama keluarga.\"",
          "",
          "BENAR: Ulasan memberikan alasan spesifik, analisis kelebihan dan kekurangan, serta sasaran audiens.",
          "SALAH: Komentar umum tanpa analisis dan tanpa bukti pendukung.",
        ],
        catatan: "Ulasan berbeda dengan RESENSI. Resensi lebih panjang dan formal, biasanya dimuat di media massa atau jurnal. Ulasan bisa pendek dan santai, asalkan tetap informatif dan beralasan.",
      },
      {
        judul: "Struktur Teks Ulasan",
        isi: [
          "Teks ulasan yang baik memiliki struktur BAKU. Pahami dan hafalkan!",
          "",
          "1. IDENTITAS / ORIENTASI",
          "  Bagian pembuka yang memperkenalkan karya yang diulas. Informasi yang perlu dicantumkan:",
          "  • Judul karya",
          "  • Pengarang/sutradara/pencipta",
          "  • Penerbit/tahun rilis",
          "  • Genre/kategori",
          "  • Informasi umum lain (jumlah halaman, durasi, label, dll.)",
          "  Tujuan: pembaca langsung tahu karya APA yang sedang dibahas.",
          "",
          "2. SINOPSIS / RINGKASAN",
          "  Gambaran singkat isi karya TANPA spoiler berlebihan. Jelaskan premis cerita, konflik utama, dan tokoh-tokoh penting. Ingat: sinopsis bukan menceritakan ulang seluruh isi!",
          "  ✓ \"Novel ini berkisah tentang seorang anak nelayan di Flores yang bermimpi sekolah ke kota besar.\"",
          "  ✗ Menceritakan ending film secara detail.",
          "",
          "3. ANALISIS",
          "  Bagian TERPENTING. Penulis mengupas kelebihan dan kekurangan karya dari berbagai aspek:",
          "  • Plot/Alur — Apakah ceritanya menarik? Ada plot hole? Alurnya lambat atau cepat?",
          "  • Karakter/Penokohan — Apakah karakter berkembang? Apakah dialognya natural?",
          "  • Gaya Bahasa — Apakah bahasanya indah, mudah dipahami, atau terlalu rumit?",
          "  • Pesan Moral — Apa yang bisa dipelajari dari karya ini?",
          "  • Teknis — Sinematografi, musik, ilustrasi, tata panggung (untuk film/drama)",
          "  • Orisinalitas — Apakah karyanya unik atau mirip dengan karya lain?",
          "",
          "4. EVALUASI",
          "  Penilaian KESELURUHAN terhadap karya. Bisa berupa skor, rating bintang, atau perbandingan dengan karya lain yang sejenis.",
          "  ✓ \"Secara keseluruhan, novel ini mendapat 4/5 bintang. Lebih kuat dari novel pertama penulis yang sama.\"",
          "",
          "5. REKOMENDASI",
          "  Bagian penutup yang menyimpulkan dan menyarankan target pembaca/pemirsa.",
          "  ✓ \"Buku ini sangat cocok untuk remaja usia 13-17 tahun yang suka cerita petualangan dengan pesan moral yang kuat.\"",
          "  ✓ \"Film ini kurang cocok untuk anak di bawah 12 tahun karena beberapa adegan kekerasan.\"",
        ],
        contoh: [
          "CONTOH STRUKTUR LENGKAP ULASAN FILM:",
          "",
          "IDENTITAS:",
          "\"Laskar Pelangi\" (2008) — Sutradara: Riri Riza — Produksi: Miles Films — Durasi: 125 menit — Genre: Drama/Pendidikan — Berdasarkan novel best-seller karya Andrea Hirata.",
          "",
          "SINOPSIS:",
          "Film ini berkisah tentang perjuangan 10 anak dari keluarga miskin di Belitung Timur untuk mendapatkan pendidikan di SD Muhammadiyah yang hampir ditutup. Dipimpin oleh Bu Muslimah dan Pak Harfan, dua guru yang penuh dedikasi, anak-anak ini melawan keterbatasan dengan semangat luar biasa.",
          "",
          "ANALISIS KELEBIHAN:",
          "• Akting anak-anak sangat natural dan mengharukan, terutama Cut Mini sebagai Bu Muslimah yang penuh kehangatan.",
          "• Sinematografi indah — pemandangan Pantai Belitung dengan batu-batu granit raksasa ikonik menjadi latar yang memukau.",
          "• Skor musik oleh Erwin Gutawa berhasil membangun emosi di setiap adegan penting.",
          "• Pesan tentang pentingnya pendidikan sangat kuat dan inspiratif.",
          "",
          "ANALISIS KEKURANGAN:",
          "• Beberapa adegan terasa terlalu dramatis dan sedikit dipaksakan.",
          "• Durasi 125 menit terasa panjang untuk anak-anak.",
          "• Beberapa karakter sampingan tidak tergali dengan baik.",
          "",
          "EVALUASI:",
          "4,5/5 bintang — Film ini berhasil membawa novel legendaris ke layar lebar dengan sangat baik, meskipun ada beberapa penyederhanaan dari versi bukunya.",
          "",
          "REKOMENDASI:",
          "Cocok untuk semua umur, terutama pelajar dan guru. Wajib tonton bagi yang suka film inspiratif bertema pendidikan.",
        ],
        catatan: "Tidak semua teks ulasan harus memiliki 5 bagian secara kaku. Ulasan di blog atau media sosial bisa lebih fleksibel — tapi struktur ini adalah KERANGKA IDEAL yang akan membuat ulasanmu lebih profesional.",
      },
      {
        judul: "Kaidah Kebahasaan Teks Ulasan",
        isi: [
          "Bahasa yang digunakan dalam teks ulasan memiliki ciri-ciri khusus. Kuasai ciri-ciri ini agar ulasanmu terdengar MEYAKINKAN dan PROFESIONAL!",
          "",
          "1. KATA SIFAT OPINI (Adjektiva Evaluatif)",
          "  Kata sifat yang mengungkapkan penilaian atau pendapat penulis. Ini yang membuat ulasanmu punya 'suara'.",
          "  Contoh: menarik, membosankan, mengharukan, lucu, mendidik, menginspirasi, datar, rumit, brilian, lemah, kuat, indah, jelek, mengecewakan, memukau",
          "  ✓ \"Alur ceritanya SANGAT MENARIK dan penuh kejutan.\"",
          "  ✓ \"Akting tokoh utama terasa DATAR dan KURANG MEYAKINKAN.\"",
          "",
          "2. MAJAS PERBANDINGAN",
          "  Membandingkan karya yang diulas dengan karya lain untuk memberi perspektif.",
          "  Kata kunci: lebih...dari, sama...dengan, sebaik..., seperti, bagaikan",
          "  ✓ \"Film ini LEBIH KUAT DARI film sebelumnya dalam hal pengembangan karakter.\"",
          "  ✓ \"Gaya bertuturnya SAMA DENGAN novel-novel Andrea Hirata sebelumnya.\"",
          "  ✓ \"Sinematografinya BAGAIKAN lukisan hidup yang bergerak.\"",
          "",
          "3. KATA RUJUKAN",
          "  Kata yang merujuk pada sumber informasi atau data pendukung. Membuat ulasanmu lebih kredibel.",
          "  Contoh: menurut data, berdasarkan penelitian, dalam novel tersebut, menurut penulis, secara teknis, dari segi...",
          "  ✓ \"MENURUT catatan Box Office Indonesia, film ini ditonton 5 juta orang dalam minggu pertama.\"",
          "  ✓ \"DARI SEGI BAHASA, novel ini menggunakan diksi puitis yang khas.\"",
          "",
          "4. KONJUNGSI PERTENTANGAN",
          "  Untuk menyampaikan kelebihan dan kekurangan secara berimbang. Inilah yang membuat ulasanmu OBJEKTIF!",
          "  Contoh: namun, sedangkan, akan tetapi, meskipun, di sisi lain, sayangnya",
          "  ✓ \"Aktingnya brilian, NAMUN naskah dialognya terasa lemah.\"",
          "  ✓ \"Visualnya memukau, AKAN TETAPI alur ceritanya lambat di pertengahan film.\"",
          "  ✓ \"MESKIPUN durasinya panjang, film ini tetap berhasil mempertahankan ketegangan.\"",
          "",
          "5. KALIMAT KOMPLEKS DAN SIMPLEKS",
          "  Kalimat KOMPLEKS (majemuk) digunakan untuk analisis mendalam:",
          "  ✓ \"Film ini layak ditonton karena menyajikan cerita yang mengharukan dan sinematografi yang indah.\" (Kalimat kompleks — dua klausa)",
          "  Kalimat SIMPLEKS (tunggal) untuk pernyataan tegas:",
          "  ✓ \"Novel ini brilian.\"",
          "  ✓ \"Skor musiknya mengecewakan.\"",
        ],
        contoh: [
          "Perhatikan penggunaan kaidah kebahasaan dalam paragraf ulasan berikut:",
          "",
          "\"Novel 'Pulang' karya Tere Liye MENAWARKAN (kata kerja aktif) cerita yang MENGHARUKAN (kata sifat opini) tentang seorang anak yang mencari jati diri. ALURNYA KOMPLEKS (kata sifat opini) dengan maju mundur waktu, NAMUN (konjungsi pertentangan) penulis berhasil merangkainya dengan rapi. MENURUT BEBERAPA KRITIKUS SASTRA (kata rujukan), novel ini LEBIH DEWASA DIBANDINGKAN (majas perbandingan) karya-karya Tere Liye sebelumnya. SAYANGNYA (konjungsi pertentangan), beberapa tokoh pendukung terasa kurang dikembangkan. MESKIPUN DEMIKIAN (konjungsi pertentangan), novel ini tetap layak mendapat 4/5 bintang.\"",
          "",
          "BENAR: Menggabungkan opini, perbandingan, rujukan, dan pertentangan secara seimbang.",
          "SALAH: \"Bagus banget! Keren! Wajib baca!\" — hanya opini tanpa analisis, tanpa bukti, tanpa struktur.",
        ],
        catatan: "Kunci ulasan yang baik adalah KESEIMBANGAN. Jangan hanya memuji (terkesan fans berat) atau hanya mengkritik (terkesan pembenci). Berikan apresiasi di sana-sini dan kritik di tempat lain — ini menunjukkan kamu ulasan secara OBJEKTIF.",
      },
      {
        judul: "Jenis-Jenis Ulasan dan Etika Menulis",
        isi: [
          "Tidak semua ulasan ditulis dengan cara yang sama. Kenali jenis-jenisnya agar kamu bisa memilih gaya yang tepat!",
          "",
          "JENIS ULASAN BERDASARKAN SIFAT:",
          "1. ULASAN INFORMATIF",
          "  Fokus memberikan informasi tentang karya tanpa banyak penilaian. Cocok untuk pembaca yang ingin tahu gambaran umum.",
          "  Contoh: Ulasan buku di katalog perpustakaan, sinopsis film di jadwal TV.",
          "",
          "2. ULASAN DESKRIPTIF",
          "  Menggambarkan isi dan suasana karya secara detail, seperti melukiskan dengan kata-kata. Pembaca seolah 'merasakan' karyanya.",
          "  Contoh: Ulasan musik yang mendeskripsikan nuansa lagu, aransemen, dan vokal.",
          "",
          "3. ULASAN KRITIS",
          "  Menganalisis secara mendalam dengan argumen yang kuat, didukung bukti dari karya. Ini adalah jenis ulasan yang PALING BERGUNA karena membantu pencipta karya untuk berkembang.",
          "  Contoh: Ulasan film yang membahas sinematografi, naskah, akting, dan pesan moral secara detail.",
          "",
          "4. ULASAN ARGUMENTATIF",
          "  Ulasan yang bertujuan meyakinkan pembaca untuk setuju dengan pendapat penulis. Mirip esai persuasif.",
          "  Contoh: '5 Alasan Kenapa Novel Ini WAJIB Masuk Daftar Bacaanmu!'",
          "",
          "[Ilustrasi: Skala rating bintang 1-5 — 1 bintang (sangat buruk, tidak layak), 2 bintang (kurang, banyak kekurangan), 3 bintang (cukup, biasa saja), 4 bintang (bagus, layak dinikmati), 5 bintang (sempurna, wajib!). Masing-masing dengan ikon wajah: marah, cemberut, datar, senyum, berseri.]",
          "",
          "ETIKA MENULIS ULASAN — Ini penting!",
          "Sebagai seorang pengulas, kamu punya TANGGUNG JAWAB MORAL terhadap pembaca dan pencipta karya. Ikuti etika berikut:",
          "",
          "1. JUJUR — Sampaikan pendapatmu yang sebenarnya, jangan dipengaruhi imbalan atau pertemanan.",
          "2. OBJEKTIF — Berikan kelebihan DAN kekurangan. Tidak ada karya yang sempurna atau sepenuhnya buruk.",
          "3. KONSTRUKTIF — Kritik yang membangun disertai saran perbaikan. Bukan sekadar mencaci.",
          "  ✓ \"Dialog beberapa tokoh terdengar kaku. Akan lebih baik jika penulis menggunakan bahasa sehari-hari yang lebih natural.\"",
          "  ✗ \"Dialognya jelek banget, norak, gak banget!\"",
          "4. SOPAN — Gunakan bahasa yang santun. Kamu boleh tidak suka, tapi tetap hargai kerja keras kreator.",
          "5. BERALASAN — Setiap pendapat harus disertai ALASAN dan BUKTI dari karya. Jangan ngomong 'jelek' tanpa menjelaskan mengapa.",
          "  ✓ \"Film ini lambat karena banyak adegan yang tidak relevan dengan konflik utama, seperti adegan memasak yang berdurasi 5 menit tanpa dialog.\"",
          "  ✗ \"Film ini lambat banget, bikin ngantuk.\"",
          "",
          "Ingat: Menulis ulasan adalah SENI dan TANGGUNG JAWAB. Ulasanmu bisa memengaruhi keputusan orang lain — jadilah pengulas yang bijak!",
        ],
        contoh: [
          "KRITERIA PENILAIAN YANG BISA DIGUNAKAN:",
          "",
          "Untuk BUKU/NOBEL:",
          "• Plot — Apakah alur cerita menarik? Apakah ada plot twist? Apakah klimaksnya memuaskan?",
          "• Karakter — Apakah tokoh-tokohnya hidup dan berkembang? Apakah dialognya natural?",
          "• Gaya Bahasa — Apakah diksi dan majasnya efektif? Apakah mudah dipahami?",
          "• Pesan — Apa amanat yang ingin disampaikan? Apakah relevan?",
          "• Orisinalitas — Apakah ide ceritanya segar atau klise?",
          "",
          "Untuk FILM:",
          "• Sinematografi — Apakah pengambilan gambarnya bagus? Apakah warna dan pencahayaan mendukung suasana?",
          "• Akting — Apakah para pemain menghayati perannya? Apakah chemistry antar pemain terasa?",
          "• Musik/Skor — Apakah musik latar mendukung emosi cerita?",
          "• Editing — Apakah transisi adegan halus? Apakah durasi pas?",
          "• Sutradara — Apakah visi sutradara tersampaikan dengan baik?",
          "",
          "Untuk LAGU:",
          "• Vokal — Apakah teknik menyanyi bagus? Apakah emosi tersampaikan?",
          "• Lirik — Apakah liriknya bermakna? Apakah pilihan katanya puitis?",
          "• Aransemen — Apakah musiknya enak didengar? Apakah instrumentasi bervariasi?",
          "• Produksi — Apakah kualitas rekaman bagus? Apakah mixing dan mastering rapi?",
        ],
        catatan: "Pernah dengar istilah 'review bombing'? Itu adalah praktik memberi ulasan buruk secara massal ke suatu karya tanpa alasan yang jelas, biasanya karena sentimen di luar karya itu sendiri. Ini adalah ETIKA BURUK — jangan pernah melakukannya!",
      },
      {
        judul: "Langkah-Langkah Menulis Teks Ulasan",
        isi: [
          "Siap menulis ulasan pertamamu? Ikuti langkah-langkah berikut untuk hasil yang maksimal!",
          "",
          "[Ilustrasi: Perbandingan tabel dua kolom — kolom kiri 'Ulasan Baik' dengan checklist: jujur, objektif, berimbang, beralasan, sopan. Kolom kanan 'Ulasan Buruk' dengan tanda silang: bias, subjektif, hanya kritik/memuji, tanpa alasan, kasar. Masing-masing dengan contoh ulasan pendek di bawahnya.]",
          "",
          "LANGKAH 1: Nikmati Karya dengan Seksama",
          "Sebelum mengulas, kamu harus benar-benar menikmati karya tersebut. Tonton film sampai selesai, baca buku sampai habis, dengarkan lagu berulang kali. Catat hal-hal yang menarik perhatianmu — baik yang kamu suka maupun tidak suka.",
          "",
          "LANGKAH 2: Kumpulkan Data Identitas",
          "Catat informasi dasar: judul, pencipta, tahun rilis, genre, dan detail penting lainnya. Untuk buku: catat jumlah halaman, penerbit, ISBN jika perlu. Untuk film: sutradara, produser, durasi, pemeran utama.",
          "",
          "LANGKAH 3: Tulis Sinopsis Singkat",
          "Buat ringkasan 3-5 kalimat tentang isi karya. Ingat: TANPA SPOILER! Cukup gambarkan premis dan konflik awalnya.",
          "",
          "LANGKAH 4: Analisis Kelebihan dan Kekurangan",
          "Ini adalah inti ulasanmu. Gunakan kriteria penilaian yang sesuai dengan jenis karya. Minimal 2 kelebihan dan 2 kekurangan, masing-masing dengan penjelasan dan contoh konkret dari karya.",
          "",
          "LANGKAH 5: Beri Evaluasi dan Skor",
          "Berapa rating yang pantas untuk karya ini? 4/5? 7/10? Tiga bintang? Jelaskan alasan di balik skor tersebut.",
          "",
          "LANGKAH 6: Tulis Rekomendasi",
          "Siapa yang cocok menikmati karya ini? Usia berapa? Genre apa yang disukai? Atau jelaskan siapa yang sebaiknya TIDAK menikmati karya ini.",
          "",
          "LANGKAH 7: Review dan Edit",
          "Baca ulang ulasanmu. Apakah sudah jelas? Apakah ada typo? Apakah argumenmu didukung bukti? Apakah bahasa yang digunakan sopan? Jangan ragu untuk merevisi!",
        ],
        contoh: [
          "CONTOH ULASAN LENGKAP — NOVEL 'BUMI MANUSIA' Karya Pramoedya Ananta Toer",
          "",
          "IDENTITAS:",
          "Judul: Bumi Manusia",
          "Pengarang: Pramoedya Ananta Toer",
          "Penerbit: Lentera Dipantara",
          "Tahun: 1980 (pertama terbit di Belanda), 2005 (terbit di Indonesia)",
          "Jumlah Halaman: 570 halaman",
          "Genre: Fiksi Sejarah",
          "",
          "SINOPSIS:",
          "Novel ini berlatar akhir abad ke-19 di Jawa Timur, berkisah tentang Minke — seorang pribumi terdidik yang bersekolah di HBS Surabaya, sekolah bergengsi yang biasanya hanya untuk orang Belanda. Minke terjebak dalam pergulatan identitas: antara menjadi 'pribumi terpelajar' yang dihormati Belanda dan kesadaran akan ketidakadilan kolonial. Konflik semakin kompleks ketika ia jatuh cinta pada Annelies, gadis Indo (campuran Belanda-Jawa), dan harus berhadapan dengan hukum kolonial yang rasis.",
          "",
          "ANALISIS KELEBIHAN:",
          "1. Gaya Bahasa yang Puitis dan Kuat — Pramoedya menggunakan bahasa Indonesia yang indah, kaya metafora, dan penuh tenaga. Setiap kalimat terasa hidup. Kutipan 'Aku telah belajar dari kehidupan: melawan adalah satu-satunya jalan bagi yang tertindas' adalah contoh bagaimana bahasa bisa menjadi senjata.",
          "2. Karakter yang Kompleks — Minke bukan pahlawan yang sempurna. Ia naif, bingung, kadang pengecut. Ini membuatnya terasa manusiawi dan dekat dengan pembaca. Annelies juga digambarkan dengan kedalaman emosional yang jarang ditemukan di novel lain.",
          "3. Kritik Sosial yang Tajam — Novel ini dengan brilian mengupas rasisme, feodalisme, dan kemunafikan sistem kolonial tanpa terasa seperti 'kuliah sejarah'. Kritiknya dikemas dalam cerita yang mengalir alami.",
          "4. Riset Sejarah yang Mendalam — Detail tentang kehidupan di Hindia Belanda awal 1900-an sangat akurat: sistem pendidikan, stratifikasi sosial, hukum, dan budaya. Pembaca seolah diajak jalan-jalan ke masa lalu.",
          "",
          "ANALISIS KEKURANGAN:",
          "1. Alur yang Lambat di Beberapa Bagian — Sekitar 100 halaman pertama terasa berat, terutama bagi pembaca yang tidak terbiasa dengan sastra serius. Banyak deskripsi dan monolog yang mungkin membosankan bagi remaja.",
          "2. Karakter Perempuan Masih Stereotip — Meskipun Annelies kuat secara emosional, ia masih sering digambarkan sebagai objek yang perlu diselamatkan. Beberapa kritikus sastra feminis mencatat kelemahan ini.",
          "3. Bahasa yang Berat — Penggunaan istilah Belanda dan Jawa yang tidak diterjemahkan bisa menghambat pembaca yang tidak familier dengan kedua bahasa tersebut.",
          "",
          "EVALUASI:",
          "Skor: 4,7/5 bintang.",
          "Bumi Manusia adalah mahakarya sastra Indonesia yang wajib dibaca oleh setiap pelajar. Kekuatan utamanya ada pada kemampuannya membuka mata pembaca terhadap realitas sejarah yang pahit melalui cerita yang mengharukan. Meskipun memiliki beberapa kekurangan teknis, novel ini tetap menjadi salah satu buku paling berpengaruh dalam sejarah sastra Indonesia.",
          "",
          "PERBANDINGAN:",
          "Jika dibandingkan dengan novel sejenis — 'Tetralogi Buru' secara keseluruhan — Bumi Manusia adalah novel terkuat di antara empat serinya. Dibandingkan dengan karya Andrea Hirata (Laskar Pelangi), Bumi Manusia lebih gelap dan kompleks secara tematik, sedangkan Laskar Pelangi lebih ringan dan mudah dicerna.",
          "",
          "REKOMENDASI:",
          "Novel ini sangat cocok untuk:",
          "  • Pelajar SMA dan mahasiswa yang belajar sejarah Indonesia",
          "  • Pembaca dewasa yang suka sastra serius dengan kritik sosial",
          "  • Siapa pun yang ingin memahami akar sejarah bangsa Indonesia",
          "",
          "Kurang cocok untuk:",
          "  • Pembaca di bawah 15 tahun karena tema dewasa (kekerasan, diskriminasi, percintaan)",
          "  • Mereka yang mencari bacaan ringan untuk hiburan semata",
        ],
        catatan: "Teks ulasan di atas adalah contoh ULASAN KRITIS. Perhatikan bagaimana penulis memberikan KELEBIHAN DAN KEKURANGAN secara seimbang, menggunakan BAHASA yang sopan dan argumentatif, serta didukung ALASAN dan BUKTI dari karya. Inilah standar teks ulasan yang baik!",
      },
    ],
    rangkuman: [
      "Teks ulasan adalah teks yang mengevaluasi dan memberi penilaian terhadap suatu karya (buku, film, lagu, drama, dll.) untuk memberikan informasi dan pertimbangan kepada pembaca.",
      "Struktur teks ulasan: Identitas/Orientasi → Sinopsis → Analisis (kelebihan & kekurangan) → Evaluasi → Rekomendasi.",
      "Kaidah kebahasaan: kata sifat opini, majas perbandingan, kata rujukan, konjungsi pertentangan, kalimat kompleks/simpleks.",
      "Jenis ulasan: informatif, deskriptif, kritis, argumentatif — pilih sesuai tujuan dan audiens.",
      "Etika menulis ulasan: jujur, objektif, konstruktif, sopan, beralasan. Setiap pendapat harus didukung bukti dari karya.",
      "Langkah menulis: nikmati karya → kumpulkan data → tulis sinopsis → analisis kelebihan & kekurangan → beri evaluasi → tulis rekomendasi → review & edit.",
      "Kriteria penilaian bergantung jenis karya: untuk buku (plot, karakter, gaya bahasa, pesan, orisinalitas), untuk film (sinematografi, akting, musik, editing), untuk lagu (vokal, lirik, aransemen, produksi).",
      "Ulasan yang baik bersifat IMBANG — tidak hanya memuji atau hanya mengkritik. Gunakan konjungsi pertentangan untuk menyeimbangkan.",
    ],
  },

  latihan: makeSoal([
    // 5 Soal Pilihan Ganda
    ["Teks ulasan bertujuan untuk...", ["Menghibur pembaca dengan cerita fiksi", "Memberikan penilaian dan pertimbangan tentang suatu karya", "Melaporkan hasil observasi secara objektif", "Mengajak pembaca membeli produk tertentu"], 1, "Tujuan utama teks ulasan adalah memberikan penilaian dan pertimbangan kepada pembaca tentang kualitas suatu karya."],
    ["Struktur teks ulasan yang benar adalah...", ["Identitas — analisis — sinopsis — evaluasi — rekomendasi", "Identitas — sinopsis — analisis — evaluasi — rekomendasi", "Sinopsis — identitas — analisis — rekomendasi — evaluasi", "Identitas — sinopsis — evaluasi — analisis — rekomendasi"], 1, "Urutan yang benar: Identitas → Sinopsis → Analisis → Evaluasi → Rekomendasi."],
    ["Kata 'namun', 'sedangkan', 'akan tetapi' dalam teks ulasan berfungsi sebagai...", ["Kata rujukan", "Kata sifat opini", "Konjungsi pertentangan", "Majas perbandingan"], 2, "Kata-kata tersebut adalah konjungsi pertentangan untuk menyampaikan kelebihan dan kekurangan secara berimbang."],
    ["Berikut yang BUKAN termasuk etika menulis ulasan adalah...", ["Memberikan kritik yang membangun", "Menyertakan alasan dan bukti", "Hanya menyebutkan kekurangan tanpa kelebihan", "Menggunakan bahasa yang sopan"], 2, "Ulasan yang baik harus IMBANG — menyebutkan kelebihan DAN kekurangan. Hanya mengkritik tanpa apresiasi adalah tidak etis."],
    ["'Akting tokoh utama sangat brilian, menghasilkan penampilan yang mengharukan.' Kata 'brilian' termasuk...", ["Kata rujukan", "Kata sifat opini", "Konjungsi", "Kata kerja"], 1, "'Brilian' adalah kata sifat opini yang mengungkapkan penilaian subjektif penulis terhadap kualitas akting."],

    // 3 Soal Betul/Salah
    ["Pernyataan: 'Teks ulasan boleh berisi spoiler tentang akhir cerita karena pembaca perlu tahu isi lengkap karya.'", ["Betul", "Salah"], 1, "SALAH. Ulasan yang baik TIDAK boleh memberikan spoiler berlebihan. Sinopsis cukup menggambarkan premis tanpa membocorkan akhir cerita atau plot twist."],
    ["Pernyataan: 'Konjungsi pertentangan seperti 'namun' dan 'meskipun' penting dalam teks ulasan untuk menyeimbangkan kelebihan dan kekurangan.'", ["Betul", "Salah"], 0, "BETUL. Konjungsi pertentangan memungkinkan penulis menyampaikan sisi positif dan negatif secara berimbang dalam satu ulasan."],
    ["Pernyataan: 'Ulasan informatif berbeda dengan ulasan kritis karena ulasan informatif tidak memberikan penilaian sama sekali.'", ["Betul", "Salah"], 0, "BETUL. Ulasan informatif fokus pada penyampaian informasi tentang karya tanpa banyak penilaian, sedangkan ulasan kritis menganalisis secara mendalam."],

    // 2 Soal Isian Singkat
    ["Kata rujukan seperti 'menurut data' dan 'dalam novel tersebut' berfungsi untuk membuat ulasan lebih...", ["kredibel", "panjang", "subjektif", "singkat"], 0, "Kata rujukan membuat ulasan lebih KREDIBEL karena menunjukkan bahwa pendapat penulis didukung oleh data atau sumber yang valid."],
    ["Bagian teks ulasan yang berisi penilaian keseluruhan dan perbandingan dengan karya lain disebut...", ["sinopsis", "analisis", "evaluasi", "rekomendasi"], 2, "EVALUASI adalah bagian yang berisi penilaian keseluruhan, skor/rating, dan perbandingan dengan karya lain yang sejenis."],
  ]),

  praktik: {
    petunjuk: "Pilih SALAH SATU karya berikut, lalu tulis teks ulasan lengkap dengan struktur yang benar!\n\nPilihan Karya:\n1. Film: Laskar Pelangi, Dilan 1990, atau Soul (Pixar)\n2. Novel: Bumi Manusia, Perahu Kertas, atau Harry Potter and the Philosopher's Stone\n3. Lagu: 'Halu' (Feby Putri), 'Runtuh' (Fiersa Besari), atau 'To the Bone' (Pamungkas)\n4. Drama/Film Pendek: Pertunjukan seni yang pernah kamu tonton\n\nTeks ulasanmu harus mencakup:\n\n1. IDENTITAS — Judul, pencipta, tahun, genre, dan informasi dasar lainnya\n2. SINOPSIS — Ringkasan singkat 3-5 kalimat TANPA SPOILER\n3. ANALISIS — Minimal 2 kelebihan dan 2 kekurangan, masing-masing dengan penjelasan dan bukti dari karya\n4. EVALUASI — Skor/rating dan alasan di balik skor tersebut, serta perbandingan dengan karya sejenis\n5. REKOMENDASI — Jelaskan siapa yang cocok menikmati karya ini dan siapa yang sebaiknya tidak\n\nGunakan kaidah kebahasaan yang tepat: kata sifat opini, majas perbandingan, konjungsi pertentangan, dan kata rujukan. Pastikan bahasamu sopan, objektif, dan konstruktif!",
    tips: [
      "Pilih karya yang BENAR-BENAR sudah kamu nikmati sepenuhnya, bukan yang hanya kamu lihat trailer/cover-nya.",
      "Buat catatan kecil saat menikmati karya: adegan mana yang berkesan, dialog mana yang kuat, bagian mana yang terasa lemah.",
      "Gunakan kata sifat opini yang BERAGAM: jangan hanya 'bagus' atau 'jelek'. Variasikan dengan kata seperti memukau, mengharukan, brilian, datar, rumit, atau menginspirasi.",
      "Setiap kritik harus disertai SOLUSI atau SARAN. Bukan 'dialognya jelek', tapi 'dialognya terasa kaku, akan lebih baik jika menggunakan bahasa sehari-hari yang lebih natural'.",
      "Gunakan konjungsi pertentangan untuk menyeimbangkan: 'Meskipun alurnya lambat, pengembangan karakternya sangat kuat.'",
      "Cantumkan minimal satu perbandingan dengan karya lain dari genre yang sama untuk memberi perspektif.",
      "Baca ulang teksmu: pastikan tidak ada spoiler, tidak ada kata kasar, dan semua argumen didukung bukti dari karya.",
      "Minta teman membaca ulasanmu dan beri feedback — apakah mereka jadi tertarik menikmati karya tersebut?",
    ],
    contoh: "ULASAN FILM: SOUL (Pixar, 2020)\n\nIDENTITAS:\nJudul: Soul\nSutradara: Pete Docter (sebelumnya menyutradarai Inside Out, Up)\nStudio: Pixar Animation Studios\nTahun Rilis: 2020\nDurasi: 100 menit\nGenre: Animasi, Drama, Musikal, Filsafat\nPlatform: Disney+ Hotstar\n\nSINOPSIS:\nJoe Gardner, seorang guru musik sekolah menengah di New York, bermimpi menjadi musisi jazz profesional. Ketika akhirnya mendapat kesempatan emas untuk tampil bersama legenda jazz Dorothea Williams, Joe mengalami kecelakaan dan jiwanya terpisah dari tubuh. Ia terjebak di 'Great Before' — sebuah alam semesta tempat jiwa-jiwa baru dipersiapkan sebelum lahir ke Bumi. Di sana ia bertemu 22, jiwa muda yang pesimis dan tidak punya minat untuk hidup. Joe harus membantu 22 menemukan 'percikan' (spark)-nya, sementara ia berusaha kembali ke tubuhnya untuk mewujudkan mimpinya.\n\nANALISIS KELEBIHAN:\n1. Konsep Cerita yang Orisinal dan Mendalam — Pixar kembali berani mengangkat tema berat: makna hidup, tujuan hidup, dan apa artinya benar-benar 'hidup'. Konsep 'Great Before' dan 'spark' adalah ide segar yang belum pernah dieksplorasi film animasi sebelumnya. Ini bukan film yang menghibur secara dangkal, melainkan mengajak penonton BERPISIR.\n2. Animasi yang Luar Biasa — Dua dunia digambarkan dengan gaya visual yang kontras: New York yang realistis dan hangat versus 'Great Before' yang abstrak, biru, dan ethereal. Desain karakter 22 sebagai jiwa abstrak yang tidak punya bentuk tetap sangat kreatif. Adegan Joe bermain piano menggunakan motion capture dari musisi jazz sungguhan, menghasilkan animasi jari yang sangat realistis.\n3. Musik Jazz yang Memukau — Musik orisinal oleh Trent Reznor, Atticus Ross (musik latar), dan Jon Batiste (lagu jazz) memenangkan Oscar untuk Best Original Score. Musik bukan sekadar latar, melainkan BAGIAN INTRINSIK dari cerita — medium yang menghubungkan Joe dengan jiwanya.\n4. Pesan Filosofis yang Kuat — Soul menyampaikan pesan revolusioner: TIDAK SETIAP ORANG HARUS PUNYA TUJUAN HIDUP BESAR. 'Spark' bukanlah tujuan hidup, melainkan keinginan untuk hidup itu sendiri. Pesan ini sangat relevan di era di mana banyak orang merasa tertekan untuk sukses.\n\nANALISIS KEKURANGAN:\n1. Alur Lambat di Babak Pertama — Sekitar 30 menit pertama terasa lambat, terutama bagi anak-anak yang terbiasa dengan film animasi penuh aksi. Adegan di 'Great Before' dengan konsep abstrak mungkin sulit dicerna penonton usia di bawah 10 tahun.\n2. Karakter Pendukung Kurang Tergali — Teman-teman Joe di dunia nyata (ibu, mantan murid, tukang cukur) hanya muncul sebentar tanpa pengembangan berarti. Ibu Joe khususnya, yang diperkenalkan sebagai konflik, tampil hanya dalam 2 adegan.\n3. Klimaks Terasa Kurang Memuaskan — Setelah perjalanan emosional yang mendalam, ending-nya terasa sedikit 'safe' dan terlalu rapi. Beberapa penonton mungkin期待 twist yang lebih mengejutkan.\n\nEVALUASI:\nSkor: 4,5/5 bintang — Soul adalah mahakarya animasi yang berani dan dewasa. Meskipun beberapa aspek teknis bisa diperbaiki, kekuatan tematik dan orisinalitasnya menjadikannya salah satu film Pixar terbaik. Saya menempatkannya di atas Inside Out dalam hal kedalaman tematik, meskipun Inside Out lebih unggul dalam hal humor dan aksesibilitas.\n\nDibandingkan dengan film animasi 2020 lainnya (Wolfwalkers, Onward), Soul jelas unggul dalam hal ambisi intelektual dan artistik. Wolfwalkers lebih kuat dalam visual tradisional, tetapi Soul menang dalam skor orisinal dan naskah.\n\nREKOMENDASI:\nFilm ini sangat cocok untuk:\n• Remaja dan dewasa (15+ tahun) yang sedang mencari makna hidup\n• Musisi dan pecinta musik jazz\n• Penggemar film filosofis yang tidak takut dengan konsep abstrak\n• Siapa pun yang suka film yang membuat mereka berpikir selama berhari-hari setelah menonton\n\nKurang cocok untuk:\n• Anak-anak di bawah 10 tahun (konsep terlalu abstrak, alur lambat)\n• Penonton yang mencari film animasi ringan dan lucu-lucuan (pilih The Mitchells vs. The Machines atau Encanto saja)\n\n\"Soul tidak bertanya 'apa tujuan hidupmu?' — ia bertanya 'apa kamu sudah benar-benar hidup?' Dan itu pertanyaan yang jauh lebih penting.\"",
  },

  kuis: makeSoal([
    ["Perbedaan utama teks ulasan dengan teks laporan hasil observasi adalah...", ["Ulasan subjektif berdasarkan opini, LHO objektif berdasarkan fakta", "Ulasan lebih panjang dari LHO", "LHO berisi data, ulasan tidak", "Keduanya sama saja"], 0, "Teks ulasan bersifat SUBJEKTIF (berisi opini/penilaian penulis), sedangkan LHO bersifat OBJEKTIF (berdasarkan data dan fakta)."],
    ["Cermati kalimat: 'Secara teknis, film ini brilian. Namun, alur ceritanya lemah.' Penggunaan kata 'namun' menunjukkan...", ["Perbandingan", "Penambahan", "Pertentangan", "Penjelasan"], 2, "'Namun' adalah konjungsi pertentangan yang mempertentangkan kelebihan teknis dengan kelemahan alur cerita."],
    ["Bagian analisis dalam teks ulasan berisi...", ["Identitas buku dan pengarang", "Ringkasan cerita", "Kelebihan dan kekurangan karya", "Skor dan rating akhir"], 2, "Analisis adalah bagian yang mengupas kelebihan dan kekurangan karya dari berbagai aspek seperti plot, karakter, gaya bahasa, dll."],
    ["Manakah yang merupakan contoh kata rujukan yang tepat dalam teks ulasan?", ["Film ini bagus sekali", "Menurut data Box Office, film ini ditonton 5 juta orang", "Akan tetapi, aktingnya kurang", "Lebih baik dari film sebelumnya"], 1, "'Menurut data Box Office' adalah kata rujukan karena merujuk pada sumber data yang valid dan terpercaya."],
    ["Seorang pengulas hanya menulis kekurangan film tanpa menyebutkan satu pun kelebihannya. Hal ini melanggar etika ulasan, yaitu...", ["Kejujuran", "Objektivitas", "Kekritisan", "Kesopanan"], 1, "Ulasan harus OBJEKTIF — menyebutkan kelebihan DAN kekurangan secara berimbang. Hanya mengkritik tanpa apresiasi menunjukkan bias."],
    ["Majas perbandingan yang tepat dalam teks ulasan adalah...", ["Film ini sangat bagus", "Novel ini lebih kuat dari karya sebelumnya dalam pengembangan karakter", "Sayangnya, alur ceritanya lambat", "Menurut kritikus, film ini layak ditonton"], 1, "'Lebih kuat dari' adalah majas perbandingan yang membandingkan novel ini dengan karya sebelumnya."],
    ["'Film ini cocok untuk remaja usia 13-17 tahun yang suka cerita petualangan dengan pesan moral yang kuat.' Bagian struktur teks ulasan ini adalah...", ["Sinopsis", "Analisis", "Evaluasi", "Rekomendasi"], 3, "'Cocok untuk remaja usia 13-17 tahun' adalah REKOMENDASI — menjelaskan target audiens yang sesuai."],
    ["Dalam ulasan lagu, aspek yang tepat untuk dianalisis adalah...", ["Plot, karakter, latar", "Vokal, lirik, aransemen", "Sinematografi, editing, akting", "Penerbit, jumlah halaman, ISBN"], 1, "Untuk lagu, aspek analisis yang tepat: vokal (teknik menyanyi, emosi), lirik (makna, pilihan kata), dan aransemen (instrumentasi, musik)."],
    ["Seorang teman menulis: 'Filmnya jelek banget, gak banget, buang-buang waktu.' Masalah utama dari ulasan ini adalah...", ["Terlalu panjang", "Tidak ada alasan dan bukti pendukung", "Tidak sopan", "Menggunakan bahasa gaul"], 1, "Masalah utama: tidak ada ALASAN dan BUKTI. Mengapa filmnya jelek? Aspek apa yang buruk? Ulasan yang baik harus disertai argumen yang didukung bukti dari karya."],
    ["Perbedaan teks ulasan informatif dan argumentatif terletak pada...", ["Panjang teks", "Informatif memberi info tanpa banyak penilaian, argumentatif meyakinkan pembaca", "Informatif subjektif, argumentatif objektif", "Informatif untuk film, argumentatif untuk buku"], 1, "Ulasan INFORMATIF fokus menyampaikan informasi tentang karya, sedangkan ARGUMENTATIF bertujuan meyakinkan pembaca untuk setuju dengan pendapat penulis."],
  ]),
}

export default konten
