import type { Konten } from "../types"
import { makeSoal } from "../types"

const konten: Konten = {
  belajar: {
    tujuan: [
      "Memahami pengertian, tujuan, dan ciri-ciri teks persuasi serta perbedaannya dengan teks eksposisi dan argumentasi",
      "Mengidentifikasi struktur teks persuasi: pembuka, argumen, ajakan, dan penegasan ulang",
      "Menganalisis teknik persuasi ethos, pathos, dan logos dalam berbagai teks persuasi",
      "Mengenali teknik propaganda dan pengaruhnya dalam komunikasi persuasif",
      "Menulis teks persuasi yang efektif dengan struktur lengkap dan kaidah kebahasaan yang tepat",
    ],
    materi: [
      {
        judul: "Apa Itu Teks Persuasi?",
        isi: [
          "Pernahkah kamu membujuk teman untuk ikut kegiatan ekstrakurikuler? Atau meyakinkan orang tua untuk membelikan sesuatu? Setiap hari, tanpa sadar, kita melakukan persuasi — seni membujuk dan meyakinkan orang lain.",
          "",
          "Teks persuasi adalah teks yang bertujuan MEMENGARUHI pembaca atau pendengar agar melakukan sesuatu atau meyakini suatu pandangan tertentu. Kata persuasi berasal dari bahasa Latin persuadere, yang berarti 'membujuk' atau 'meyakinkan'. Berbeda dengan teks yang sekadar memberi informasi, teks persuasi ingin mengubah sikap, opini, atau perilaku pembacanya.",
          "",
          "[Ilustrasi: Diagram segitiga Ethos/Pathos/Logos dengan tiga sudut berlabel. Sudut kiri: ETHOS dengan ikon mahkota/lencana dan tulisan 'Kredibilitas — Percaya karena sumber terpercaya'. Sudut kanan: PATHOS dengan ikon hati dan tulisan 'Emosi — Tersentuh, takut, bangga, iba'. Sudut bawah: LOGOS dengan ikon otak/grafik dan tulisan 'Logika — Data, statistik, sebab-akibat'. Di tengah segitiga: PERSUASI dengan tanda seru.]",
          "",
          "• Perbedaan penting antara persuasi, eksposisi, dan argumentasi:",
          "  • EKSPOSISI → 'Ini faktanya...' (memberi tahu, informatif)",
          "  • ARGUMENTASI → 'Ini alasannya...' (logika dan nalar)",
          "  • PERSUASI → 'Ayo lakukan ini karena...' (membujuk dan mengajak)",
          "",
          "✓ Ciri-ciri teks persuasi:",
          "  ✓ Bertujuan memengaruhi pembaca untuk melakukan sesuatu atau meyakini suatu pandangan",
          "  ✓ Bersifat subjektif — penulis memiliki posisi dan ingin pembaca setuju",
          "  ✓ Mengandung KALIMAT AJAKAN: Mari, Ayo, Jangan, Hendaknya, Sebaiknya",
          "  ✓ Menggunakan kata-kata EMOTIF untuk menyentuh perasaan",
          "  ✓ Disertai alasan, data, atau argumen yang MENDORONG TINDAKAN",
          "  ✓ Sering menggunakan kata-kata PENEGAS: pasti, tentu, sungguh, nyata, jelas",
          "",
          "PENTING: Jangan keliru! Teks persuasi BOLEH mengandung data dan fakta, tetapi data itu digunakan untuk MEMBANGUN AJAKAN — bukan sekadar memberi informasi. Kalau teks hanya menyajikan data tanpa ajakan → itu eksposisi. Kalau ada ajakan 'Ayo...', 'Mari...', 'Jangan...' → itu persuasi!",
        ],
        contoh: [
          "BENAR: Teks Persuasi (fokus ajakan)",
          "\"Tahukah kamu bahwa setiap menit, satu truk sampah plastik dibuang ke laut? Data dari Kementerian Lingkungan Hidup menyebutkan bahwa Indonesia adalah penyumbang sampah plastik terbesar kedua di dunia. Oleh karena itu, MARI kita mulai kurangi penggunaan plastik sekali pakai! Mulailah dari hal sederhana: bawa tas belanja sendiri, gunakan botol minum isi ulang, dan tolak sedotan plastik. Bumi kita ada di tangan kita!\"",
          "(Ada data, tapi tujuannya MENGAJAK — 'MARI kita mulai kurangi...')",
          "",
          "Bandingkan dengan Teks Eksposisi (fokus informasi):",
          "\"Indonesia merupakan penyumbang sampah plastik terbesar kedua di dunia. Berdasarkan data Kementerian Lingkungan Hidup tahun 2023, total sampah plastik yang masuk ke laut mencapai 1,29 juta ton per tahun. Sampah plastik membutuhkan waktu 400—1.000 tahun untuk terurai secara alami. Dampaknya terhadap ekosistem laut sangat serius.\"",
          "(Hanya menyajikan data dan fakta — TIDAK ADA AJAKAN. Ini eksposisi.)",
          "",
          "BENAR: Teks persuasi yang kuat mengandung ETHOS + PATHOS + LOGOS",
          "Kata seorang ahli kesehatan: 'Sebagai dokter yang telah menangani 1.000 pasien penyakit paru, saya bersaksi bahwa merokok adalah bencana.' (Ethos — kredibilitas dokter). 'Bayangkan ayahmu terbaring di rumah sakit, napasnya tersengal-sengal, tubuhnya kurus karena kanker paru-paru.' (Pathos — emosi). 'Data menunjukkan 90% pasien kanker paru adalah perokok aktif.' (Logos — data).",
          "",
          "SALAH: Persuasi yang terlalu memaksa tanpa data",
          "'Pokoknya kamu harus ikut! Semua orang sudah ikut! Jangan jadi pengecut!' (Tidak ada alasan yang meyakinkan, hanya tekanan.)",
        ],
        catatan: "Ingat mantra ini: PERSUASI = AJAKAN + ALASAN. Tanpa ajakan → eksposisi. Tanpa alasan → omongan kosong. Dua-duanya harus ada untuk membentuk teks persuasi yang efektif!",
      },
      {
        judul: "Struktur Teks Persuasi",
        isi: [
          "Setiap teks persuasi yang baik memiliki struktur yang jelas. Sejak zaman Aristoteles (Yunani Kuno, 384—322 SM), struktur persuasi klasik telah dikenal dan masih digunakan hingga sekarang. Mari kita bedah keempat bagian utamanya!",
          "",
          "1. PEMBUKA/PENGANTAR — Bagian awal yang bertujuan MENARIK PERHATIAN pembaca dan memperkenalkan isu yang akan dibahas.",
          "  • Bisa berupa pertanyaan retoris, fakta mengejutkan, kutipan terkenal, atau cerita pendek",
          "  • Fungsi: membuat pembaca PENASARAN dan PEDULI terhadap topik",
          "  ✓ 'Tahukah kamu bahwa setiap hari 2.000 pohon ditebang untuk memenuhi kebutuhan kertas di Indonesia?'",
          "  ✓ 'Bayangkan bangun pagi dan mendengar burung bernyanyi — bukan klakson kendaraan. Itulah yang kita perjuangkan.'",
          "  ✗ 'Hari ini saya akan berbicara tentang lingkungan.' (Terlalu biasa, tidak menarik perhatian.)",
          "",
          "2. ARGUMEN/RANGKAIAN ALASAN — Bagian inti yang berisi bukti, data, alasan, dan logika untuk meyakinkan pembaca.",
          "  • Bisa terdiri dari beberapa paragraf, masing-masing dengan satu alasan yang mendukung ajakan",
          "  • Gunakan ETHOS (kredibilitas), PATHOS (emosi), dan LOGOS (logika) secara bergantian",
          "  • Setiap argumen harus terhubung langsung dengan ajakan yang akan disampaikan",
          "  ✓ 'Berdasarkan penelitian Universitas Indonesia, penggunaan kantong plastik sekali pakai di Jakarta mencapai 10 juta lembar per hari. Sampah plastik ini mencemari sungai dan laut. Jika tidak dikurangi, pada tahun 2030 kita akan menghadapi krisis lingkungan yang parah.'",
          "  ✗ Argumen melenceng: 'Bicara plastik, tahu nggak kalau harga minyak naik?' (Tidak relevan dengan ajakan.)",
          "",
          "3. AJAKAN/PERNYATAAN BUJUKAN — INTI dari teks persuasi! Bagian di mana penulis secara eksplisit meminta pembaca melakukan sesuatu.",
          "  • Gunakan kalimat IMPERATIF: Mari, Ayo, Yuk, Jangan, Hendaknya, Sebaiknya, Mulailah",
          "  • Ajakan harus SPESIFIK dan TINDAKAN NYATA — bukan sekadar himbauan umum",
          "  • Sampaikan dengan penuh keyakinan dan urgensi",
          "  ✓ 'Mulai hari ini, yuk bawa botol minum dan tas belanja sendiri! Tolak sedotan plastik saat membeli minuman. Ajak juga teman-temanmu untuk melakukan hal yang sama.'",
          "  ✗ 'Semoga kita semua bisa menjaga lingkungan.' (Terlalu pasif, tidak ada ajakan tegas.)",
          "",
          "4. PENEGASAN ULANG — Bagian penutup yang memperkuat ajakan dengan merangkum argumen atau meninggalkan kesan mendalam.",
          "  • Bisa berupa pernyataan visioner, kutipan inspiratif, atau gambaran masa depan",
          "  • Tidak menambahkan argumen baru, hanya memperkuat apa yang sudah disampaikan",
          "  • Ciptakan 'sense of urgency' — perasaan bahwa tindakan harus dilakukan SEKARANG",
          "  ✓ 'Ingatlah, bumi bukan warisan dari nenek moyang kita, melainkan titipan dari anak cucu kita. Pilihan ada di tanganmu: terus menggunakan plastik sekali pakai dan meninggalkan bumi yang rusak, atau memulai perubahan dari sekarang. Ayo, jadi bagian dari solusi!'",
          "  ✗ 'Sekian pidato dari saya, kurang lebihnya mohon maaf.' (Terlalu formal, tidak meninggalkan kesan.)",
          "",
          "Tips mengingat: P-A-A-P (Pembuka, Argumen, Ajakan, Penegasan). Bayangkan seperti NAIK TANGGA: Pembuka adalah langkah pertama masuk ke topik, Argumen adalah anak tangga yang menguatkan, Ajakan adalah puncak tangga (tujuan akhir), dan Penegasan adalah saat kamu melihat pemandangan dari atas — merenungkan kembali perjalanan.",
        ],
        contoh: [
          "CONTOH STRUKTUR LENGKAP — Pidato Singkat 'Ayo Hemat Listrik!'",
          "",
          "[PEMBUKA]",
          "Saudara-saudaraku sekalian, bayangkan jika suatu malam listrik di seluruh kota padam. Gelap gulita. Kipas angin berhenti berputar. AC mati. HP tidak bisa dicharge. Kulkas mencair. Inilah yang akan terjadi jika kita terus boros listrik tanpa kendali.",
          "",
          "[ARGUMEN]",
          "Berdasarkan data Kementerian ESDM, konsumsi listrik rumah tangga di Indonesia meningkat 7% setiap tahun. Ironisnya, sebagian besar pemakaian itu sebenarnya bisa dihemat — seperti menyalakan TV tanpa ditonton, lampu kamar mandi menyala sepanjang malam, atau AC yang menyala meski ruangan kosong. Jika setiap rumah tangga menghemat 10% listrik, negara bisa menghemat triliunan rupiah per tahun. Uang itu bisa digunakan untuk membangun sekolah dan rumah sakit di daerah terpencil.",
          "",
          "[AJAKAN]",
          "Mulai malam ini, matikan lampu yang tidak perlu! Cabut charger HP jika baterai sudah penuh! Gunakan AC seperlunya, dan matikan TV jika tidak ditonton! Ajak juga keluargamu di rumah untuk melakukan hal yang sama. Ingatlah, tindakan kecil yang dilakukan bersama-sama akan membawa perubahan besar!",
          "",
          "[PENEGASAN ULANG]",
          "Hemat listrik bukan sekadar mengurangi tagihan bulanan. Ini tentang tanggung jawab kita terhadap masa depan. Sumber daya energi kita terbatas, dan setiap watt yang kita hemat adalah warisan berharga bagi generasi mendatang. Jadi, tunggu apa lagi? Mari hemat listrik, mulai dari diri sendiri, mulai dari sekarang!",
          "",
          "BENAR: Setiap bagian memiliki fungsi yang jelas dan terhubung satu sama lain.",
          "SALAH: Struktur tidak lengkap → 'Listrik itu mahal, ayo hemat.' (Tidak ada pembuka menarik, tidak ada argumen pendukung, penegasan terlalu pendek.)",
        ],
        catatan: "Struktur P-A-A-P adalah panduan, bukan aturan kaku. Dalam praktiknya, kamu bisa menggabungkan pembuka dengan argumen pertama, atau menempatkan ajakan di beberapa tempat. Yang penting adalah alur yang logis: dari membuat pembaca peduli → memberi alasan → mengajak → memperkuat ajakan.",
      },
      {
        judul: "Teknik Persuasi dan Propaganda",
        isi: [
          "Dalam teks persuasi, ada tiga teknik KLASIK yang dikenal sebagai SEGITIGA RETORIKA Aristoteles: Ethos, Pathos, dan Logos. Selain itu, ada juga teknik PROPAGANDA yang sering digunakan di media dan iklan. Mari kita bedah semuanya!",
          "",
          "✦ ETHOS (Kredibilitas dan Karakter) — Membujuk melalui KEPERCAYAAN kepada pembicara atau sumber.",
          "  • Pembaca lebih mudah yakin jika sumbernya TERPERCAYA",
          "  • Cara membangun ethos: sebut kualifikasi, pengalaman, jabatan, atau track record",
          "  • Ethos juga muncul dari cara penyampaian: jujur, tegas, dan konsisten",
          "  ✓ 'Sebagai guru bahasa Indonesia yang telah mengajar selama 15 tahun, saya melihat bahwa minat baca siswa semakin menurun.'",
          "  ✓ 'Penelitian oleh WHO — organisasi kesehatan dunia — menyatakan bahwa vaksin aman dan efektif.'",
          "  ✗ 'Menurut temen saya...' (Sumber tidak jelas, tidak ada kredibilitas.)",
          "",
          "✦ PATHOS (Emosi dan Perasaan) — Membujuk dengan MENYENTUH PERASAAN pembaca.",
          "  • Teknik PALING KUAT dalam persuasi — manusia sering mengambil keputusan berdasarkan emosi",
          "  • Emosi yang bisa digunakan: iba, takut, bangga, haru, cemas, optimis, cinta, marah",
          "  • Gunakan kata-kata emotif: menyedihkan, membanggakan, mengerikan, mengharukan",
          "  • Gunakan cerita atau gambaran hidup yang membangkitkan perasaan",
          "  ✓ 'Bayangkan seorang anak kecil berusia 7 tahun yang harus berjalan 5 kilometer setiap hari hanya untuk mengambil air bersih. Kakinya lecet, badannya lelah, tapi ia tidak punya pilihan. Akankah kita diam saja?'",
          "  ✓ 'Rasa bangga memenuhi dada saat melihat bendera Merah Putih berkibar di puncak podium Olimpiade. Prestasi ini membuktikan bahwa Indonesia mampu bersaing di kancah global!'",
          "  ✗ 'Sedih deh pokoknya.' (Terlalu umum, tidak membangun gambaran emosional.)",
          "",
          "✦ LOGOS (Logika dan Nalar) — Membujuk melalui DATA, FAKTA, STATISTIK, dan ALASAN LOGIS.",
          "  • Gunakan data konkret: angka, persentase, perbandingan, penelitian",
          "  • Sertakan sumber data yang jelas dan terpercaya",
          "  • Gunakan logika SEBAB-AKIBAT: jika X maka Y",
          "  ✓ 'Data Kementerian Kesehatan menunjukkan bahwa 70% remaja Indonesia kurang mengonsumsi serat. Akibatnya, kasus obesitas pada remaja meningkat 15% dalam 5 tahun terakhir.'",
          "  ✓ 'Jika setiap siswa menanam satu pohon di halaman rumahnya, maka dalam satu tahun akan ada 50 juta pohon baru yang ditanam — cukup untuk menyerap 125.000 ton karbon dioksida.'",
          "  ✗ 'Banyak penelitian bilang olahraga itu baik.' (Data tidak spesifik, tidak meyakinkan.)",
          "",
          "[Ilustrasi: Poster persuasif dengan alur dari kiri ke kanan: (1) PROBLEM — ikon lampu pijar merah putus-putus bertuliskan 'LISTRIK BOROS → Tagihan Membengkak', panah ke (2) EMOSI — ikon wajah cemas bertuliskan 'Khawatir Masa Depan?', panah ke (3) SOLUSI — ikon bohlam hijau bertuliskan 'HEMAT LISTRIK', panah ke (4) CALL TO ACTION — ikon tangan menunjuk bertuliskan 'Matikan Lampu! Cabut Charger! Matikan AC!' dengan latar hijau ceria.]",
          "",
          "PENTING: Persuasi TERBAIK menggunakan KETIGANYA secara simultan. Ethos membangun kepercayaan, Pathos menyentuh hati, Logos meyakinkan otak. Contoh: data tentang polusi (Logos) + gambaran anak kesulitan bernapas (Pathos) + disampaikan oleh dokter paru (Ethos). Inilah yang disebut PERSUASI KUAT!",
          "",
          "✦ TEKNIK PROPAGANDA — Strategi persuasi yang sering disalahgunakan untuk memengaruhi opini publik. Kenali agar kamu tidak mudah termakan!",
          "",
          "1. NAME-CALLING (Pemberian Label Negatif) — Menjelekkan lawan atau ide dengan label buruk.",
          "  Contoh: 'Orang yang tidak mau vaksin adalah penghambat program kesehatan nasional.'",
          "  Efek: Membuat orang merasa malu atau bersalah jika tidak setuju.",
          "",
          "2. GLITTERING GENERALITIES (Kata-Kata Indah) — Menggunakan kata-kata positif yang muluk-muluk tanpa bukti.",
          "  Contoh: 'Produk ini adalah revolusi kecantikan yang akan mengubah hidupmu selamanya!'",
          "  Efek: Membangkitkan emosi positif tanpa data konkret.",
          "",
          "3. TRANSFER — Mengaitkan sesuatu dengan simbol yang dihormati atau dicintai.",
          "  Contoh: Iklan yang menampilkan bendera merah putih untuk menjual produk tertentu.",
          "  Efek: Perasaan positif terhadap simbol pindah ke produk.",
          "",
          "4. TESTIMONIAL — Menggunakan tokoh terkenal atau orang biasa yang sukses untuk mendukung produk/ide.",
          "  Contoh: 'Artis A menggunakan produk ini, jadi kamu juga harus!'",
          "  Efek: Konsumen percaya karena idola mereka menggunakan produk tersebut.",
          "",
          "5. PLAIN FOLKS (Orang Biasa) — Menampilkan pembicara/produk sebagai sesuatu yang dekat dengan rakyat biasa.",
          "  Contoh: Pejabat yang tiba-tiba pakai baju tani dan ikut panen di sawah saat kampanye.",
          "  Efek: Menciptakan kesan 'sama seperti kita' dan membangun kedekatan.",
          "",
          "6. CARD STACKING (Menumpuk Kartu) — Hanya menyajikan sisi positif, menyembunyikan sisi negatif.",
          "  Contoh: Iklan minuman manis yang hanya menonjolkan rasa segar tanpa menyebut kandungan gula tinggi.",
          "  Efek: Konsumen mendapat gambaran yang tidak lengkap dan membuat keputusan yang bias.",
          "",
          "7. BANDWAGON (Ikut-Ikutan) — Membujuk dengan argumen 'semua orang sudah melakukannya'.",
          "  Contoh: 'Jutaan orang telah beralih ke provider ini! Kapan kamu? Jangan jadi yang terakhir!'",
          "  Efek: Tekanan sosial — takut ketinggalan atau menjadi berbeda.",
          "",
          "8. FEAR APPEAL (Ketakutan) — Membangkitkan rasa takut untuk mendorong tindakan tertentu.",
          "  Contoh: Iklan asuransi yang menampilkan kecelakaan mengerikan. 'Jangan sampai keluargamu menderita.'",
          "  Efek: Kecemasan mendorong pembelian atau tindakan 'untuk jaga-jaga'.",
          "",
          "Tips kritis: Saat melihat iklan atau pidato persuasif, tanyakan: Apakah ini ETHOS yang kredibel? PATHOS yang wajar? LOGOS yang valid? Atau jebakan PROPAGANDA? Jangan mudah percaya — verifikasi, bandingkan, berpikir kritis!",
        ],
        contoh: [
          "BENAR: Perpaduan Ethos + Pathos + Logos dalam satu pidato",
          "\"Saya, Dr. Andi Pratama, Sp.A, dokter spesialis anak yang telah praktik selama 20 tahun di RSCM (ETHOS), ingin menyampaikan bahwa obesitas pada anak bukan sekadar masalah penampilan. Setiap bulan, saya menangani 30 anak dengan tekanan darah tinggi akibat obesitas. Mereka harus minum obat setiap hari di usia yang seharusnya penuh tawa dan bermain. Ini sungguh memprihatinkan (PATHOS). Data Ikatan Dokter Anak Indonesia menunjukkan bahwa 1 dari 5 anak Indonesia mengalami kelebihan berat badan. Angka ini meningkat 3 kali lipat dibandingkan 20 tahun lalu. Penyebab utamanya adalah konsumsi gula berlebih dan kurangnya aktivitas fisik (LOGOS). Oleh karena itu, mari kita batasi konsumsi makanan manis anak dan ajak mereka bermain di luar! (AJAKAN)\"",
          "",
          "BENAR: Mengenali propaganda dalam iklan",
          "Iklan: 'Semua artis Korea pakai produk kecantikan ini! Dapatkan kulit glowing seperti mereka sekarang juga!'",
          "Analisis: Ini menggunakan teknik TESTIMONIAL (artis Korea) + BANDWAGON (semua artis pakai) + GLITTERING GENERALITIES (kulit glowing). Tidak ada bukti ilmiah bahwa produk itu berfungsi. Konsumen yang kritis akan mencari data klinis atau review jujur terlebih dahulu.",
          "",
          "BENAR: Fear appeal yang etis vs tidak etis",
          "Etis: 'Berdasarkan data, 90% kasus kanker paru disebabkan oleh merokok. Berhentilah merokok sekarang juga untuk melindungi dirimu dan keluargamu.' (Didukung data, memberikan solusi.)",
          "Tidak etis: 'Kamu akan mati muda kalau tidak membeli asuransi ini sekarang!' (Memanipulasi ketakutan tanpa data yang jelas.)",
        ],
        catatan: "Ingat E-P-L: Ethos (siapa yang bicara?) → Pathos (apa yang kurasakan?) → Logos (apa datanya?). Teks persuasi yang baik menyeimbangkan ketiganya. Kuasai E-P-L, dan kamu bisa menyusun argumen yang hampir mustahil ditolak! Tapi jangan gunakan teknik PROPAGANDA yang menipu — gunakan persuasi secara ETIS!",
      },
      {
        judul: "Kaidah Kebahasaan Teks Persuasi",
        isi: [
          "Teks persuasi memiliki ciri bahasa yang khas dan berbeda dari teks lainnya. Inilah 'senjata rahasia' yang membuat teks persuasi mampu memengaruhi pembaca. Kuasai kaidah berikut untuk menulis persuasi yang memukau!",
          "",
          "1. KALIMAT IMPERATIF (Perintah/Ajakan) — Ciri PALING KUAT dari teks persuasi. Kalimat yang berisi perintah, ajakan, atau larangan.",
          "  • Kata-kata khas: Ayo, Mari, Yuk, Jangan, Hendaknya, Sebaiknya, Harus, Mulailah",
          "  • Biasanya diakhiri tanda seru (!) untuk menekankan urgensi",
          "  ✓ 'Mari kita jaga kebersihan lingkungan sekolah!'",
          "  ✓ 'Jangan buang sampah sembarangan!'",
          "  ✓ 'Mulailah dari hal kecil: bawa botol minum sendiri!'",
          "  ✓ 'Hendaknya setiap siswa menyadari pentingnya literasi.'",
          "  ✗ 'Sebaiknya kita menjaga kebersihan.' (Terlalu pasif, tidak mendesak.)",
          "",
          "2. KALIMAT PERSUASIF — Kalimat yang dirancang khusus untuk membujuk dan memengaruhi.",
          "  • Mengandung kata-kata yang membangkitkan keinginan atau keyakinan",
          "  • Sering menggunakan kata penegas: pasti, tentu, sungguh, nyata, jelas, terbukti",
          "  • Menciptakan 'sense of urgency' — perasaan bahwa musti bertindak SEKARANG",
          "  ✓ 'Tidak ada alasan untuk menunda! Mulai sekarang juga!'",
          "  ✓ 'Ini adalah kesempatan emas yang tidak boleh kamu lewatkan!'",
          "  ✓ 'Sudah terbukti bahwa membaca buku meningkatkan kecerdasan.'",
          "  ✓ 'Tentu kamu tidak ingin masa depanmu hancur hanya karena malas belajar?'",
          "  ✗ 'Mungkin kita bisa coba kalau sempat.' (Ragu-ragu, tidak meyakinkan.)",
          "",
          "3. KATA EMOTIF — Kata-kata yang membangkitkan emosi pembaca: iba, takut, bangga, haru, marah, optimis.",
          "  • Emosi NEGATIF: menyedihkan, mengerikan, memprihatinkan, mengkhawatirkan, tragis",
          "  • Emosi POSITIF: membanggakan, mengharukan, menggembirakan, menginspirasi, menyentuh",
          "  • Kata sifat bermuatan emosi: mulia, heroik, tragis, dramatis, luar biasa",
          "  ✓ 'Pemandangan anak-anak yang harus berjalan kaki 10 kilometer di bawah terik matahari sungguh memprihatinkan.'",
          "  ✓ 'Prestasi membanggakan ini menunjukkan bahwa anak-anak Indonesia mampu bersaing di tingkat global!'",
          "  ✓ 'Bayangkan betapa mengharukannya saat seorang anak desa bisa meraih beasiswa ke luar negeri.'",
          "  ✗ 'Itu lumayan bagus.' (Tidak ada muatan emosi.)",
          "",
          "4. KONJUNGSI ARGUMENTATIF — Kata hubung yang memperkuat alur argumen dan menunjukkan hubungan logis.",
          "  • Contoh: dengan demikian, oleh karena itu, maka dari itu, oleh sebab itu, dengan kata lain",
          "  • Fungsinya: menghubungkan argumen dengan ajakan secara logis",
          "  ✓ 'Data menunjukkan bahwa polusi udara di Jakarta sudah sangat berbahaya. Oleh karena itu, kita harus beralih ke transportasi umum.'",
          "  ✓ 'Membaca buku setiap hari terbukti meningkatkan kemampuan berpikir kritis. Dengan demikian, sudah seharusnya kita menjadikan membaca sebagai kebiasaan.'",
          "  ✗ 'Jadi gitu.' (Tidak formal, tidak tegas.)",
          "",
          "5. KATA AJAKAN (Persuasive Verbs) — Kata kerja khusus yang mendorong tindakan.",
          "  • Tingkat kekuatan: Ayo! > Mari > Yuk > Hendaknya > Sebaiknya",
          "  • Bisa juga berupa kalimat larangan: Jangan, Stop, Hentikan",
          "  • Kata kerja aktif: lakukan, mulai, wujudkan, dukung, ciptakan, perjuangkan",
          "  ✓ 'Wujudkan mimpimu mulai hari ini!'",
          "  ✓ 'Dukung program penghijauan di sekolah kita!'",
          "  ✓ 'Hentikan perundungan di lingkungan sekolah!'",
          "  ✗ 'Coba deh kalau sempat.' (Tidak tegas, tidak mendorong tindakan.)",
          "",
          "6. SINONIM KONOTATIF — Pemilihan kata bermuatan positif/negatif untuk memengaruhi persepsi.",
          "  • Positif: hemat (vs pelit), tegas (vs kasar), gigih (vs keras kepala), berani (vs nekat)",
          "  • Negatif: pemboros (vs dermawan), kaku (vs disiplin), boros (vs royal)",
          "  • Pilihan kata ini membentuk FRAMING — cara tertentu memandang sesuatu",
          "  ✓ 'Dia adalah pemimpin yang TEGAS dan BERANI mengambil keputusan.' (Positif)",
          "  ✗ (dengan framing negatif): 'Dia adalah pemimpin yang KAKU dan NEKAT.' (Negatif dari hal yang sama!)",
          "  ✓ 'Produk ini HEMAT listrik.' (Positif) vs 'Produk ini DAYA listriknya rendah.' (Netral)",
          "",
          "7. PERTANYAAN RETORIS — Pertanyaan yang tidak memerlukan jawaban karena jawabannya sudah jelas. Tujuannya membuat pembaca MERENUNG.",
          "  ✓ 'Siapa yang tidak ingin hidup sehat dan bahagia?'",
          "  ✓ 'Bukankah sudah saatnya kita peduli pada sesama?'",
          "  ✓ 'Mau sampai kapan kita diam melihat kerusakan lingkungan?'",
          "  ✓ 'Apakah kamu rela masa depanmu hancur karena malas?'",
          "  ✗ 'Kamu setuju kan?' (Pertanyaan biasa, bukan retoris.)",
          "",
          "Tips praktis: Baca iklan di TV, koran, atau media sosial. Lingkari semua kalimat imperatif (Ayo, Mari, Jangan), kata emotif, dan pertanyaan retoris yang kamu temukan. Hitung berapa banyak dalam satu iklan. Semakin sering kamu analisis, semakin tajam insting persuasifmu!",
        ],
        contoh: [
          "Analisis kaidah kebahasaan dalam teks persuasi berikut:",
          "",
          "\"Bangun Pagi, Raih Prestasi!\"",
          "",
          "Siapa di antara kalian yang suka bangun siang? (PERTANYAAN RETORIS) Akui saja, banyak dari kita yang susah bangun pagi. Padahal, bangun pagi memiliki segudang manfaat yang LUAR BIASA (KATA EMOTIF POSITIF)!",
          "",
          "Menurut penelitian yang diterbitkan dalam jurnal Nature Communications, orang yang bangun pagi cenderung lebih produktif, memiliki kesehatan mental yang lebih baik, dan nilai akademik yang lebih tinggi. Dengan demikian (KONJUNGSI ARGUMENTATIF), bangun pagi bukan sekadar kebiasaan — ini adalah INVESTASI untuk masa depanmu (KATA EMOTIF POSITIF).",
          "",
          "MAKANYA (KATA AJAKAN/AYO), mulai besok, biasakan bangun pagi! (KALIMAT IMPERATIF) Gunakan waktu pagi untuk belajar, berolahraga, atau membaca. Jangan (KATA AJAKAN) sia-siakan waktu emas ini hanya untuk tidur! Bayangkan, jika setiap hari kamu punya tambahan 2 jam produktif, dalam setahun kamu punya 730 jam ekstra — cukup untuk membaca 50 buku atau menguasai satu keterampilan baru!",
          "",
          "Tentu (KATA PENEGAS) kamu tidak ingin ketinggalan dari teman-temanmu yang sudah memulai hari lebih awal, bukan? Jadi, tunggu apa lagi? Atur alarmmu, bangun pagi, dan raih prestasi! (KALIMAT IMPERATIF + AJAKAN)",
          "",
          "BENAR: Teks di atas menggunakan 6 dari 7 kaidah kebahasaan secara alami dan tidak dipaksakan.",
          "SALAH: 'Ayo bangun pagi. Soalnya bangun pagi itu baik. Menurut penelitian gitu. Makanya ayo.' (Kaidah kebahasaan minimal, alur tidak berkembang.)",
        ],
        catatan: "Kaidah kebahasaan adalah ALAT, bukan ATURAN. Jangan memaksakan semua kaidah dalam satu teks pendek — pilih yang paling sesuai dan gunakan secara alami. Jika semua kalimat dimulai dengan 'Ayo, Mari, Jangan', teksmu akan terdengar seperti komandan militer, bukan persuader yang elegan. Variasikan!",
      },
      {
        judul: "Menyusun Teks Persuasi yang Efektif",
        isi: [
          "Menulis teks persuasi yang memukau adalah keterampilan yang bisa dipelajari. Berikut panduan langkah demi langkah untuk menulis persuasi yang tidak bisa ditolak!",
          "",
          "1. TETAPKAN TUJUAN PERSUASIMU",
          "  • Apa yang ingin kamu capai? Pembaca melakukan APA? Atau PERCAYA APA?",
          "  • Tujuan harus SPESIFIK dan TERUKUR",
          "  • Contoh: 'Pembaca mau ikut kegiatan kerja bakti hari Sabtu' bukan 'Pembaca jadi peduli lingkungan'",
          "",
          "2. KENALI AUDIENMU",
          "  • Siapa yang akan membaca? Teman sekelas? Guru? Orang tua? Masyarakat umum?",
          "  • Sesuaikan bahasa, data, dan pendekatan dengan audiens",
          "  • Contoh: Untuk teman sekelas, gunakan bahasa santai dan contoh kehidupan sehari-hari; untuk guru, gunakan bahasa formal dan data akademik",
          "",
          "3. KUMPULKAN ARGUMEN KUAT",
          "  • Minimal 3 alasan mengapa pembaca harus melakukan apa yang kamu ajak",
          "  • Setiap alasan didukung oleh: data (Logos), cerita (Pathos), atau sumber terpercaya (Ethos)",
          "  • Antisipasi keberatan: apa yang mungkin dikatakan pembaca untuk menolak? Siapkan jawabannya!",
          "",
          "4. GUNAKAN STRUKTUR P-A-A-P",
          "  • Pembuka: Tarik perhatian — fakta mengejutkan, pertanyaan retoris, atau cerita pendek",
          "  • Argumen: 3 alasan kuat, masing-masing dengan data/cerita pendukung",
          "  • Ajakan: Ajakan yang jelas, spesifik, dan mendesak",
          "  • Penegasan: Tutup dengan kesan mendalam — kutipan inspiratif atau gambaran masa depan",
          "",
          "5. PILIH KATA DENGAN CERMAT",
          "  • Gunakan kata EMOTIF yang membangkitkan perasaan sesuai tujuan",
          "  • Gunakan kata IMPERATIF yang mendorong tindakan",
          "  • Pilih SINONIM KONOTATIF yang memberi framing positif pada ajakanmu",
          "  • Hindari kata-kata ragu: mungkin, sepertinya, barangkali, coba-coba",
          "",
          "6. BERI CONTOH DAN ILUSTRASI",
          "  • Contoh konkret membuat ajakanmu lebih hidup dan mudah dibayangkan",
          "  • Gunakan perbandingan atau analogi yang dekat dengan keseharian pembaca",
          "  • Ilustrasi visual (dalam bentuk deskripsi) membantu pembaca membayangkan dampak",
          "",
          "7. REVISI DAN PERKUAT",
          "  • Baca ulang: apakah setiap kalimat mendorong tujuan persuasi?",
          "  • Perkuat bagian yang lemah: tambah data, perkuat emosi, perjelas ajakan",
          "  • Minta teman membaca dan tanya: 'Apa yang kamu rasakan? Apa yang kamu pikirkan?'",
          "  • Potong kata-kata yang tidak perlu — teks persuasi harus PADAT dan BERTENAGA",
          "",
          "[Ilustrasi: Dua versi teks persuasi yang sama secara berdampingan. Versi KIRI: 'Weak Persuasion' bertanda merah — teks pendek: 'Jaga lingkungan yuk. Soalnya penting. Makanya jaga ya.' dengan ikon wajah datar. Versi KANAN: 'Strong Persuasion' bertanda hijau — teks panjang dengan struktur lengkap: Pembuka (fakta mengejutkan), Argumen (3 alasan dengan data), Ajakan (kalimat imperatif tegas), Penegasan (kutipan inspiratif) dengan ikon wajah bersemangat dan grafik naik. Panah dari kiri ke kanan bertuliskan 'REVISI & PERKUAT'.]",
          "",
          "PENTING: Teks persuasi yang baik BUTUH PROSES. Draft pertama hampir pasti belum sempurna. Jangan takut merevisi! Penulis hebat bukan yang langsung sempurna, melainkan yang terus memperbaiki tulisannya. Tulis dulu secara kasar, lalu poles hingga berkilau!",
        ],
        contoh: [
          "CONTOH LENGKAP — Pidato Persuasi 'Aksi Bersih Lingkungan Sekolah'",
          "",
          "[PEMBUKA]",
          "Selamat pagi, teman-teman dan Bapak/Ibu guru yang saya hormati.",
          "",
          "Coba lihat ke kanan dan ke kiri kalian. Apa yang kalian lihat? Mungkin ada sampah plastik berserakan di pojok kelas, atau bungkus snack yang tergeletak di selokan. Kecil, ya? Tapi tahukah kalian bahwa sampah-sampah 'kecil' ini, jika dikumpulkan, bisa memenuhi seluruh halaman sekolah dalam satu bulan? Sebuah fakta yang memprihatinkan, bukan?",
          "",
          "[ARGUMEN — ETHOS]",
          "Sebagai Ketua OSIS yang setiap hari berkeliling dan melihat kondisi sekolah kita, saya menyaksikan sendiri bagaimana tumpukan sampah di belakang kantin semakin hari semakin menggunung. Saya berbicara dengan Pak Sarkam — petugas kebersihan sekolah kita — dan beliau mengatakan bahwa setiap hari ia mengangkut 3 karung besar sampah hanya dari area kantin. Bayangkan dalam seminggu: 21 karung! Dalam sebulan: 90 karung! Ini bukan masalah sepele.",
          "",
          "[ARGUMEN — LOGOS]",
          "Data dari Dinas Lingkungan Hidup kota kita menyebutkan bahwa rata-rata setiap siswa menghasilkan 0,5 kg sampah per hari. Dengan jumlah siswa 800 orang, sekolah kita menghasilkan 400 kg sampah per hari — atau 8 ton per bulan! Dari jumlah itu, 60% adalah sampah plastik yang membutuhkan 400—1.000 tahun untuk terurai. Sungguh angka yang mengerikan, bukan? Lebih mengkhawatirkan lagi, sampah plastik yang menumpuk bisa menyumbat saluran air yang akhirnya menyebabkan banjir. Bukankah kita sering kebanjiran saat hujan deras? Itu akibat ulah kita sendiri.",
          "",
          "[ARGUMEN — PATHOS]",
          "Saya ingin kalian membayangkan sesuatu. Bayangkan adik kelas kalian yang duduk di bangku SD — mereka bermain di halaman yang penuh sampah. Bayangkan petugas kebersihan yang harus memunguti sampah yang seharusnya kita buang pada tempatnya. Bayangkan sekolah yang kita cintai ini berubah menjadi tempat yang kotor dan tidak nyaman. Apakah itu yang kita inginkan? Tentu tidak!",
          "",
          "[AJAKAN]",
          "Oleh karena itu, mulai hari ini, mari kita lakukan tiga hal sederhana! SATU: buang sampah pada tempatnya — jangan menunggu ada yang menyuruh, lakukan dengan kesadaran sendiri! DUA: kurangi sampah plastik dengan membawa botol minum dan tempat makan dari rumah! TIGA: ikut serta dalam program 'Jumat Bersih' setiap minggu — luangkan 15 menit setelah pelajaran untuk membersihkan area kelas dan sekitarnya!",
          "",
          "Ajak juga teman-teman kalian! Buatlah kelompok kecil yang saling mengingatkan. Karena perubahan besar dimulai dari langkah kecil yang dilakukan bersama-sama.",
          "",
          "[PENEGASAN ULANG]",
          "Teman-teman, lingkungan sekolah adalah rumah kedua kita. Di sinilah kita menghabiskan sepertiga hari kita, belajar, bermain, dan bertumbuh. Jika rumah kita kotor, bagaimana kita bisa belajar dengan nyaman? Bagaimana kita bisa berkonsentrasi?",
          "",
          "Ingatlah kata bijak: 'Bumi bukan warisan dari nenek moyang kita, melainkan titipan dari anak cucu kita.' Sekolah yang bersih bukan hadiah dari guru atau petugas kebersihan — ini adalah TANGGUNG JAWAB kita bersama. Jadi, mulai sekarang, mari buktikan bahwa kita adalah generasi yang peduli! Ayo bersihkan sekolah kita! Ayo jaga lingkungan kita!",
          "",
          "Terima kasih.",
          "",
          "BENAR: Struktur P-A-A-P lengkap, perpaduan Ethos+Pathos+Logos, ajakan spesifik (3 langkah konkret), kalimat imperatif, kata emotif, pertanyaan retoris, ditutup dengan kutipan inspiratif.",
          "SALAH: 'Pokoknya kita harus bersih-bersih sekolah. Itu aja.' (Tidak ada struktur, tidak ada argumen, tidak ada daya tarik emosional atau logis.)",
        ],
        catatan: "Contoh di atas bisa kamu gunakan sebagai template untuk membuat pidato persuasif versimu sendiri. Ganti topik, data, dan cerita sesuai isu yang ingin kamu angkat. Semakin sering berlatih, semakin mahir kamu merangkai kata-kata yang mampu menggerakkan hati dan pikiran pembaca!",
      },
    ],
    rangkuman: [
      "Teks persuasi adalah teks yang bertujuan memengaruhi pembaca agar melakukan sesuatu atau meyakini suatu pandangan — berbeda dari eksposisi (memberi info) dan argumentasi (logika saja).",
      "Struktur teks persuasi klasik (P-A-A-P): Pembuka (tarik perhatian) → Argumen (alasan/data) → Ajakan (inti persuasi) → Penegasan Ulang (perkuat ajakan).",
      "Tiga teknik persuasi utama: Ethos (kredibilitas sumber), Pathos (emosi dan perasaan), Logos (data dan logika). Persuasi terbaik menggunakan ketiganya secara simultan.",
      "Propaganda berbeda dari persuasi etis — teknik propaganda meliputi name-calling, glittering generalities, transfer, testimonial, plain folks, card stacking, bandwagon, dan fear appeal. Penting untuk bersikap kritis.",
      "Kaidah kebahasaan teks persuasi: kalimat imperatif (Ayo, Mari, Jangan), kalimat persuasif (kata penegas), kata emotif, konjungsi argumentatif (dengan demikian, oleh karena itu), kata ajakan, sinonim konotatif, dan pertanyaan retoris.",
      "Perbedaan utama: Eksposisi → 'Ini faktanya', Argumentasi → 'Ini alasannya', Persuasi → 'Ayo lakukan ini karena...'.",
      "Tips menulis persuasi: tetapkan tujuan spesifik, kenali audien, kumpulkan argumen, gunakan struktur P-A-A-P, pilih kata cermat, beri contoh konkret, dan revisi hingga kuat.",
      "Contoh situasi persuasi: pidato lingkungan, kampanye kesehatan, iklan layanan masyarakat, pidato OSIS, surat pembaca di koran, orasi ilmiah, dan kampanye sosial media.",
    ],
  },

  latihan: makeSoal([
    // 5 Soal Pilihan Ganda
    ["Teks persuasi bertujuan untuk...", ["Memberikan informasi faktual secara objektif", "Memengaruhi pembaca agar melakukan sesuatu atau meyakini suatu pandangan", "Menceritakan pengalaman pribadi penulis", "Menggambarkan objek dengan kesan subjektif"], 1, "Tujuan teks persuasi adalah MEMENGARUHI pembaca — bukan sekadar memberi informasi (eksposisi) atau bercerita (narasi)."],
    ["Struktur teks persuasi yang benar menurut Aristoteles adalah...", ["Orientasi — komplikasi — resolusi", "Tesis — argumen — penegasan ulang", "Pembuka — argumen — ajakan — penegasan ulang", "Pernyataan umum — deskripsi bagian — simpulan"], 2, "Struktur persuasi klasik: Pembuka (menarik perhatian) → Argumen (alasan/data) → Ajakan (inti persuasi) → Penegasan ulang (perkuat)."],
    ["Teknik persuasi yang mengandalkan kredibilitas pembicara disebut...", ["Pathos", "Logos", "Ethos", "Bathos"], 2, "ETHOS adalah teknik persuasi yang mengandalkan kredibilitas, kepercayaan, karakter, atau keahlian pembicara. Semakin kredibel pembicara, semakin mudah pembaca percaya."],
    ["Kalimat 'Dengan demikian, sudah seharusnya kita mengurangi penggunaan plastik sekali pakai' mengandung kaidah kebahasaan...", ["Kata emotif", "Konjungsi argumentatif", "Kalimat imperatif", "Pertanyaan retoris"], 1, "'Dengan demikian' adalah konjungsi argumentatif yang menghubungkan argumen dengan simpulan/ajakan secara logis."],
    ["Berikut ini yang BUKAN termasuk teknik propaganda adalah...", ["Bandwagon", "Testimonial", "Logos", "Name-calling"], 2, "LOGOS adalah teknik persuasi ETIS (data/logika), bukan propaganda. Bandwagon, testimonial, dan name-calling termasuk teknik propaganda."],

    // 3 Soal Betul/Salah
    ["Pernyataan: 'Teks persuasi boleh menggunakan data dan fakta sebagai pendukung argumen, sama seperti teks eksposisi.'", ["Betul", "Salah"], 0, "BETUL — teks persuasi BOLEH menggunakan data dan fakta. Bedanya: dalam eksposisi, data adalah TUJUAN (memberi informasi); dalam persuasi, data adalah ALAT (mendukung ajakan)."],
    ["Pernyataan: 'Kalimat imperatif seperti Ayo dan Mari adalah ciri khas teks persuasi yang menunjukkan ajakan kepada pembaca.'", ["Betul", "Salah"], 0, "BETUL. Kalimat imperatif (Ayo, Mari, Jangan, Hendaknya, Mulailah) adalah ciri PALING KUAT dari teks persuasi karena langsung menyampaikan ajakan."],
    ["Pernyataan: 'Pathos adalah teknik persuasi yang mengandalkan data statistik dan fakta ilmiah.'", ["Betul", "Salah"], 1, "SALAH. Pathos adalah teknik persuasi melalui EMOSI (perasaan). Teknik yang mengandalkan data/fakta adalah LOGOS."],

    // 2 Soal Isian Singkat
    ["Teknik persuasi yang menggunakan data, statistik, dan alasan logis untuk meyakinkan pembaca disebut...", ["logos", "ethos", "pathos", "propaganda"], 0, "LOGOS (logika) menggunakan data, statistik, fakta ilmiah, dan alasan masuk akal untuk membangun argumen."],
    ["Pertanyaan yang tidak memerlukan jawaban karena jawabannya sudah jelas, bertujuan membuat pembaca merenung, disebut pertanyaan...", ["retoris", "langsung", "terbuka", "tertutup"], 0, "Pertanyaan RETORIS adalah pertanyaan yang jawabannya sudah jelas. Contoh: 'Siapa yang tidak ingin sukses?' Tujuannya membuat pembaca merenung, bukan mencari jawaban."],
  ]),

  praktik: {
    petunjuk: "Buatlah teks persuasi berupa PIDATO SINGKAT tentang salah satu topik berikut:\n\n1. Pentingnya Membaca Buku di Era Digital\n2. Ayo Kurangi Sampah Plastik di Lingkungan Sekolah!\n3. Bahaya Merokok bagi Remaja — Jangan Mulai!\n4. Bijak Bermedia Sosial — Jangan Sampai Kecanduan!\n5. Ikut Kegiatan Ekstrakurikuler — Asah Bakatmu!\n\nTeks persuasimu harus mencakup:\n\n1. PEMBUKA — Tarik perhatian audien dengan pertanyaan retoris, fakta mengejutkan, atau cerita pendek. (2—3 kalimat)\n2. ARGUMEN — Minimal 3 paragraf argumen yang menggabungkan ETHOS, PATHOS, dan LOGOS:\n   • Argumen 1: Gunakan ETHOS — sumber yang kredibel atau pengakuan tokoh\n   • Argumen 2: Gunakan LOGOS — data, statistik, fakta, dan alasan logis\n   • Argumen 3: Gunakan PATHOS — cerita menyentuh, gambaran emosional, imbauan perasaan\n3. AJAKAN — Tindakan spesifik dan jelas. Minimal 3 langkah konkret yang harus dilakukan audien. Gunakan kalimat imperatif (Ayo, Mari, Jangan, Mulailah, dll.)\n4. PENEGASAN ULANG — Tutup dengan kalimat inspiratif, kutipan bijak, atau gambaran masa depan yang kuat.\n\nGunakan minimal 3 kaidah kebahasaan: kalimat imperatif, kata emotif, konjungsi argumentatif, pertanyaan retoris, sinonim konotatif, dan/atau kata penegas.\n\nTulis pidatomu dengan rapi di kolom di bawah ini! Sertakan judul pidato di bagian atas.",
    tips: [
      "Mulailah dengan pembuka yang MENGEJUTKAN atau MENYENTUH — bukan 'Assalamualaikum, pada kesempatan ini saya akan berbicara tentang...' Coba pakai data mengejutkan atau gambaran yang membangkitkan rasa penasaran!",
      "Gunakan data SPESIFIK: 'setiap tahun 8 juta ton sampah plastik masuk ke laut' lebih kuat daripada 'banyak sampah plastik di laut'. Data spesifik menunjukkan kredibilitas (Ethos) sekaligus logika (Logos).",
      "Bangun emosi dengan CERITA, bukan hanya kata sifat. Jangan hanya bilang 'sedih', tapi gambarkan situasinya: 'Bayangkan anak kecil yang harus memulung di tempat pembuangan sampah...'",
      "Ajakan harus KONKRET dan SPESIFIK. Jangan hanya 'jaga lingkungan', tapi 'bawa botol minum sendiri, gunakan tas belanja kain, tolak sedotan plastik'. Semakin spesifik, semakin mudah diikuti.",
      "Gunakan variasi: selipkan pertanyaan retoris di sela-sela argumen, gunakan kata penegas untuk memperkuat poin penting, dan akhiri paragraf dengan kalimat yang mengarah ke ajakan.",
      "Baca pidatomu dengan suara keras. Apakah terdengar meyakinkan? Apakah ada bagian yang terasa hambar? Perbaiki intonasi tulisanmu dengan tanda seru, pertanyaan, dan variasi panjang kalimat.",
      "Pastikan penegasan ulangmu MENINGGALKAN KESAN. Kutipan terkenal, pertanyaan retoris penutup, atau gambaran masa depan yang inspiratif akan membuat pidatomu diingat lebih lama.",
    ],
    contoh: "CONTOH PIDATO PERSUASI: Bijak Bermedia Sosial — Jangan Sampai Kecanduan!\n\n[PEMBUKA]\nSelamat pagi, teman-teman dan Bapak/Ibu guru yang saya hormati.\n\nCoba angkat tangan kalian yang pagi ini sudah buka Instagram atau TikTok sebelum berangkat sekolah! (Beberapa tangan terangkat). Sekarang, coba angkat tangan kalian yang kemarin menghabiskan lebih dari 3 jam bermain media sosial. (Lebih banyak tangan terangkat). Saya yakin, sebagian besar dari kita sadar bahwa kita menghabiskan terlalu banyak waktu di media sosial. Tapi apakah kita sudah melakukan sesuatu untuk mengatasinya?\n\n[ARGUMEN 1 — ETHOS]\nSaya, sebagai Ketua OSIS yang setiap hari berinteraksi dengan kalian, melihat betapa banyak teman-teman yang lebih sibuk merekam daripada menikmati momen. Saya juga membaca laporan dari Kementerian Komunikasi dan Informatika yang menyatakan bahwa Indonesia menempati peringkat ke-5 dunia dalam durasi penggunaan media sosial — rata-rata 3 jam 26 menit per hari! Angka ini disampaikan langsung oleh Pak Menteri dalam seminar nasional bulan lalu. Beliau mengingatkan bahwa jika tidak dikendalikan, kebiasaan ini bisa menjadi candu yang merusak masa depan generasi muda.\n\n[ARGUMEN 2 — LOGOS]\nTahukah kalian, berdasarkan penelitian dari Universitas Gadjah Mada tahun 2024, remaja yang menghabiskan lebih dari 4 jam per hari di media sosial memiliki risiko 2,5 kali lebih tinggi mengalami gangguan kecemasan dan depresi. Selain itu, data dari Kementerian Kesehatan menunjukkan bahwa 40% remaja Indonesia mengalami gangguan pola tidur akibat kebiasaan scroll media sosial sebelum tidur. Dampaknya? Konsentrasi belajar menurun 30%, nilai akademik merosot, dan produktivitas harian berkurang drastis.\n\nLebih mengkhawatirkan lagi, maraknya konten hoaks dan cyberbullying di media sosial telah merusak kesehatan mental ribuan remaja. Setiap bulan, Komisi Perlindungan Anak Indonesia (KPAI) menerima puluhan laporan kasus perundungan daring yang berujung pada trauma psikologis. Oleh karena itu, sudah saatnya kita lebih bijak dalam menggunakan media sosial.\n\n[ARGUMEN 3 — PATHOS]\nSaya ingin kalian membayangkan sesuatu. Bayangkan seorang teman kalian — sebut saja namanya Dinda. Setiap hari, Dinda menghabiskan 5 jam di media sosial. Ia terus membandingkan hidupnya dengan influencer yang tampak sempurna. Kulitnya tidak seputih mereka, bajunya tidak sekeren mereka, liburannya tidak sewah mereka. Dinda mulai merasa tidak percaya diri, prestasinya di sekolah menurun, dan ia semakin menarik diri dari pergaulan nyata. Sedih, bukan? Tapi yang lebih menyedihkan — mungkin kita semua pernah menjadi 'Dinda' dalam beberapa hal. Kita semua pernah merasa tidak cukup baik karena apa yang kita lihat di media sosial.\n\n[AJAKAN]\nOleh karena itu, mulai hari ini, mari kita lakukan tiga hal sederhana!\n\nPERTAMA: Batasi waktu media sosial. Gunakan fitur screen time di HP kalian — maksimal 2 jam per hari. Setelah batas tercapai, HP akan otomatis mengunci aplikasi media sosial. Disiplinlah!\n\nKEDUA: Isi waktu luang dengan kegiatan produktif. Baca buku, berolahraga, belajar keterampilan baru, atau berkumpul dengan keluarga. Dunia nyata lebih indah daripada dunia maya!\n\nKETIGA: Jika kalian melihat konten negatif atau mengalami cyberbullying, jangan diam! Laporkan ke guru, orang tua, atau layanan pengaduan KPAI. Jangan biarkan media sosial menjadi sumber penderitaan!\n\nMari jadikan media sosial sebagai ALAT untuk belajar dan berkarya, BUKAN sebagai penjara yang mengurung kita dari dunia nyata!\n\n[PENEGASAN ULANG]\nTeman-teman, media sosial ibarat pisau. Jika digunakan dengan bijak, ia bisa membantu kita memotong — belajar, berkarya, terhubung dengan dunia. Tapi jika digunakan secara sembarangan, ia bisa melukai — merusak kesehatan mental, menghancurkan kepercayaan diri, dan menjauhkan kita dari orang-orang tercinta.\n\nPilihan ada di tangan kita. Ingatlah kata bijak dari seorang filsuf: 'Kuasai gawaimu, jangan sampai gawaimu yang menguasaimu.' Sudah saatnya kita menjadi generasi yang bijak — bukan generasi yang kecanduan layar. Jadi, mulai sekarang, yuk bijak bersosial media! Kendalikan waktumu, jaga kesehatanmu, dan raih mimpimu di dunia nyata!\n\nTerima kasih.",
  },

  kuis: makeSoal([
    ["Kata persuasi berasal dari bahasa Latin persuadere yang berarti...", ["Memaparkan", "Membujuk atau meyakinkan", "Menceritakan", "Mendeskripsikan"], 1, "Persuadere berarti 'membujuk' atau 'meyakinkan'. Dari sinilah kata persuasi dalam bahasa Indonesia berasal."],
    ["Perbedaan PALING MENDASAR antara teks persuasi dan teks eksposisi adalah...", ["Persuasi lebih panjang dari eksposisi", "Persuasi bertujuan mengajak, eksposisi bertujuan memberi informasi", "Persuasi menggunakan bahasa tidak baku", "Persuasi tidak boleh menggunakan data"], 1, "Tujuan akhir: Persuasi = MENGAJAK/MEMENGARUHI, Eksposisi = MEMBERI INFORMASI/ PENJELASAN. Inilah perbedaan paling fundamental."],
    ["Seorang pembicara memulai pidatonya dengan: 'Sebagai dokter yang telah 20 tahun menangani pasien kanker paru-paru...' Teknik persuasi yang digunakan adalah...", ["Pathos", "Logos", "Ethos", "Propaganda"], 2, "Pembicara membangun ETHOS dengan menyebut kredibilitasnya (dokter spesialis, 20 tahun pengalaman). Pembaca lebih percaya karena sumbernya kompeten."],
    ["Kalimat 'Apakah kamu rela melihat orang tuamu menua dalam kesulitan?' termasuk jenis kalimat...", ["Imperatif", "Deklaratif", "Retoris", "Interogatifbiasa"], 2, "Ini pertanyaan RETORIS — jawabannya sudah jelas (tidak ada yang rela), tujuannya membuat pendengar merenung dan tersentuh emosinya."],
    ["Cermati penggalan teks: 'Bayangkan anak-anak kecil yang harus berjalan 5 km untuk mengambil air bersih, kakinya lecet, badannya lelah...' Teknik persuasi yang dominan adalah...", ["Ethos", "Pathos", "Logos", "Bandwagon"], 1, "PATHOS dominan karena membangkitkan emosi iba dan haru melalui gambaran visual yang menyentuh perasaan."],
    ["Teknik propaganda 'Bandwagon' bekerja dengan cara...", ["Menjelekkan lawan dengan label negatif", "Mengaitkan produk dengan simbol yang dihormati", "Membujuk dengan argumen 'semua orang sudah melakukannya'", "Hanya menyajikan sisi positif, menyembunyikan sisi negatif"], 2, "Bandwagon: 'Jutaan orang telah beralih ke produk ini! Jangan jadi yang terakhir!' Tekanan sosial untuk ikut-ikutan."],
    ["Konjungsi argumentatif yang tepat untuk menghubungkan argumen dengan ajakan adalah...", ["Kemudian, selanjutnya, lalu", "Oleh karena itu, dengan demikian, maka dari itu", "Dan, serta, juga", "Atau, tetapi, namun"], 1, "Konjungsi argumentatif (oleh karena itu, dengan demikian, maka dari itu) berfungsi menghubungkan alasan/logika dengan simpulan/ajakan."],
    ["Seorang siswa menulis teks persuasi: 'Produk ini HEMAT listrik.' Kata 'HEMAT' dipilih daripada 'DAYA RENDAH' karena...", ["Lebih panjang", "Memiliki konotasi positif — menghemat adalah hal baik", ["Lebih mudah dieja", "Tidak ada bedanya"], 1], 1, "Pilihan sinonim KONOTATIF: 'hemat' memiliki konotasi positif (bijak, tidak boros), sedangkan 'daya rendah' bersifat netral/teknis. Ini adalah teknik framing dalam persuasi."],
    ["Mana dari berikut ini yang merupakan ciri teks persuasi yang TIDAK ETIS?", ["Menggunakan data dari sumber terpercaya", "Menyembunyikan risiko dan hanya menonjolkan manfaat", "Menggunakan kata-kata emotif yang wajar", "Memberikan ajakan yang spesifik dan jelas"], 1, "Teks persuasi TIDAK ETIS menyembunyikan informasi negatif (card stacking). Persuasi etis bersikap jujur dan transparan, meskipun tetap membangun argumen untuk meyakinkan."],
    ["Bagian 'penegasan ulang' dalam struktur teks persuasi berfungsi untuk...", ["Memperkenalkan topik baru", "Menambahkan argumen baru yang lebih kuat", "Memperkuat ajakan dan meninggalkan kesan mendalam", "Mengulang kata demi kata dari pembuka"], 2, "Penegasan ulang memperkuat ajakan dengan merangkum argumen, memberikan kesan mendalam, dan mendorong tindakan. Tidak menambahkan informasi atau argumen baru."],
  ]),
}

export default konten
