import type { Konten } from "../types"
import { makeSoal } from "../types"

const konten: Konten = {
  belajar: {
    tujuan: [
      "Meninjau ulang dan memperdalam pemahaman perbedaan buku fiksi dan nonfiksi secara komparatif",
      "Menganalisis perbedaan tujuan, sumber, gaya bahasa, struktur, dan target pembaca antara fiksi dan nonfiksi",
      "Mengevaluasi kualitas buku fiksi berdasarkan plot, karakter, gaya bahasa, dan pesan",
      "Mengevaluasi kualitas buku nonfiksi berdasarkan akurasi data, kedalaman riset, kejelasan, dan kredibilitas penulis",
      "Menulis resensi kritis yang menganalisis kelebihan dan kelemahan buku secara objektif",
      "Membandingkan dua buku (fiksi dan nonfiksi) dengan tema yang sama secara sistematis",
    ],
    materi: [
      {
        judul: "Review Cepat: Fiksi vs Nonfiksi",
        isi: [
          "Sebelum kita menyelam lebih dalam, mari ingat kembali apa yang sudah kamu pelajari di kelas VII. Buku fiksi dan nonfiksi adalah dua dunia yang berbeda — seperti langit dan laut, keduanya adalah buku tetapi memiliki sifat yang sangat berbeda!",
          "",
          "BUKU FIKSI adalah karya imajinatif yang lahir dari kreativitas penulis. Cerita di dalamnya tidak terikat pada fakta — penulis bebas menciptakan tokoh, tempat, dan peristiwa. Tujuan utamanya adalah menghibur dan menggugah perasaan pembaca melalui cerita yang menarik.",
          "",
          "BUKU NONFIKSI adalah karya faktual yang berisi informasi, data, dan pengetahuan yang dapat dipertanggungjawabkan. Penulis nonfiksi tidak bebas berimajinasi — ia harus berpegang pada fakta, data, dan sumber yang terpercaya. Tujuan utamanya adalah menginformasikan dan mendidik pembaca.",
          "",
          "1. FIKSI: 'Laskar Pelangi' — Ikal, Lintang, dan Mahar adalah tokoh rekaan, tetapi jutaan pembaca menangis dan terinspirasi oleh kisah mereka. Andrea Hirata tidak melaporkan fakta; ia menciptakan realitas baru melalui imajinasinya.",
          "",
          "2. NONFIKSI: 'Sapiens: Riwayat Singkat Umat Manusia' — Yuval Noah Harari menyajikan ribuan tahun sejarah manusia berdasarkan riset arkeologi, biologi, dan antropologi. Setiap klaim didukung bukti ilmiah, bukan sekadar cerita menarik.",
          "",
          "PENTING: Poin kritis yang harus kamu ingat — FIKSI menggunakan BAHASA KONOTATIF (kiasan, bermakna ganda) sedangkan NONFIKSI menggunakan BAHASA DENOTATIF (makna sebenarnya, lugas). Inilah pembeda paling mencolok di level kalimat!",
          "",
          "[Ilustrasi: Split visual — sisi kiri buku fiksi warna-warni dengan gelembung pikiran bertuliskan 'imajinasi', sisi kanan buku nonfiksi bersih dengan kaca pembesar bertuliskan 'fakta'. Di tengah, tanda 'VS' dengan api menyala.]",
        ],
        contoh: [
          "Mari bandingkan dua kalimat tentang topik yang SAMA — hutan hujan tropis:",
          "",
          "FIKSI: \"Hutan-hutan itu bernapas dalam irama purba, pepohonan raksasa saling berbisik dalam bahasa yang hanya dipahami angin dan dewa-dewa hujan. Di bawah kanopi gelap, seberkas cahaya menari-nari seperti penari ballerina di atas panggung lumut.\"",
          "  → Bahasa konotatif, personifikasi, metafora, membangun suasana misterius dan magis.",
          "",
          "NONFIKSI: \"Hutan hujan tropis adalah bioma dengan curah hujan tahunan lebih dari 2.000 mm dan suhu rata-rata 25°C. Ekosistem ini memiliki keanekaragaman hayati tertinggi di dunia, dengan lebih dari 50% spesies tumbuhan dan hewan dunia hidup di dalamnya.\"",
          "  → Bahasa denotatif, data faktual, istilah ilmiah, informatif dan objektif.",
          "",
          "✓ Contoh konotatif (fiksi): 'Matahari tersenyum pagi ini.'",
          "✓ Contoh denotatif (nonfiksi): 'Matahari terbit pukul 05.47 WIB di Jakarta.'",
          "",
          "Perhatikan: KEDUA kalimat itu sama-sama 'indah' — tapi keindahan fiksi terletak pada imajinasinya, sedangkan keindahan nonfiksi terletak pada ketepatan informasinya!",
        ],
        catatan: "Beberapa buku nonfiksi modern menggunakan gaya bercerita seperti fiksi — ini disebut NONFIKSI NARATIF atau creative nonfiction. Contohnya 'Sapiens' karya Harari yang ditulis dengan narasi mengalir layaknya novel. Tapi ingat: isinya TETAP FAKTA, bukan rekaan!",
      },
      {
        judul: "Perbandingan Mendalam: 5 Dimensi",
        isi: [
          "Sekarang kita akan membandingkan fiksi dan nonfiksi secara lebih sistematis melalui LIMA dimensi. Ini akan membantumu memahami mengapa kedua jenis buku ini 'bernafas' dengan cara yang sangat berbeda.",
          "",
          "DIMENSI 1 — TUJUAN PENULISAN:",
          "• FIKSI: Tujuan utama adalah MENGHIBUR (to entertain). Fiksi ingin membuat pembaca tertawa, menangis, merinding, atau terinspirasi melalui cerita yang menggugah emosi. Fiksi juga bisa menyampaikan pesan moral atau kritik sosial, tetapi disampaikan 'terselubung' dalam cerita.",
          "  Contoh: 'Bumi Manusia' (Pramoedya) menghibur dengan kisah cinta Minke-Annelies, sekaligus mengkritik kolonialisme.",
          "• NONFIKSI: Tujuan utama adalah MENGINFORMASIKAN (to inform). Nonfiksi ingin memberikan pengetahuan, wawasan, pemahaman baru kepada pembaca. Informasi disampaikan secara langsung, terbuka, dan dapat diverifikasi.",
          "  Contoh: 'Sejarah Nasional Indonesia' memberikan data dan analisis objektif tentang sejarah, bukan cerita rekaan.",
          "",
          "DIMENSI 2 — SUMBER MATERI:",
          "• FIKSI: IMAJINASI penulis (meskipun bisa terinspirasi dari pengalaman nyata). Penulis fiksi bebas menciptakan dunia alternatif, tokoh rekaan, dialog fiktif, dan peristiwa yang tidak pernah terjadi.",
          "  Penulis fiksi bertanya: 'Bagaimana jika...?' (What if?)",
          "• NONFIKSI: DATA, RISET, dan FAKTA. Penulis nonfiksi harus mengumpulkan data, melakukan wawancara, membaca hasil penelitian, atau merujuk pada dokumen resmi. Imajinasi tidak boleh menggantikan fakta.",
          "  Penulis nonfiksi bertanya: 'Apa yang benar-benar terjadi?' (What really happened?)",
          "",
          "DIMENSI 3 — GAYA BAHASA:",
          "• FIKSI: KONOTATIF, FIGURATIF, EMOSIONAL. Kaya akan majas (metafora, personifikasi, hiperbola, simile), diksi puitis, dan kalimat yang membangun atmosfer. Bahasa dalam fiksi adalah 'alat menciptakan dunia', bukan sekadar menyampaikan informasi.",
          "• NONFIKSI: DENOTATIF, LUGAS, INFORMATIF. Menggunakan istilah teknis yang tepat, kalimat deklaratif, dan struktur logis. Bahasa dalam nonfiksi adalah 'alat penyampai fakta', bukan untuk menghibur.",
          "",
          "DIMENSI 4 — STRUKTUR PENYAJIAN:",
          "• FIKSI: ALUR BEBAS dan FLEKSIBEL. Bisa linear (maju), non-linear (mundur/flashback), atau bahkan sirkuler. Bab-bab bisa pendek atau panjang, dan penulis bebas bereksperimen dengan struktur.",
          "• NONFIKSI: STRUKTUR SISTEMATIS. Biasanya terdiri dari: pendahuluan → bab per bab tematis → kesimpulan → daftar pustaka → indeks → glosarium. Setiap bab dibagi lagi ke sub-bab yang logis dan teratur.",
          "",
          "DIMENSI 5 — PEMBACA SASARAN:",
          "• FIKSI: Pembaca yang mencari HIBURAN, kesenangan, pengalaman emosional, dan pelarian dari realitas. Fiksi dibaca untuk 'merasakan sesuatu'.",
          "• NONFIKSI: Pembaca yang mencari PENGETAHUAN, wawasan, pemahaman, dan pengembangan diri. Nonfiksi dibaca untuk 'mengetahui sesuatu'.",
          "",
          "Tips membaca cerdas: Saat memegang buku baru, tanyakan pada dirimu: 'Apaku ingin dihibur atau ingin belajar?' Jawabannya akan menentukan buku apa yang harus kamu pilih!",
        ],
        contoh: [
          "Perbandingan 5 dimensi — Novel vs Buku Pelajaran:",
          "",
          "FIKSI (Novel 'Laskar Pelangi'):",
          "• TUJUAN: Menghibur, menginspirasi, menggugah semangat pendidikan",
          "• SUMBER: Imajinasi Andrea Hirata (terinspirasi masa kecil di Belitung, tetapi tokoh dan dialognya rekaan)",
          "• GAYA BAHASA: Puitis, penuh metafora ('Matahari jatuh ke dalam laut seperti telur api raksasa')",
          "• STRUKTUR: 34 bab tanpa bab tematis — alur maju dengan flashback sesekali",
          "• PEMBACA: Semua usia yang suka cerita inspiratif dan mengharukan",
          "",
          "NONFIKSI (Buku 'IPA Terpadu Kelas VIII'):",
          "• TUJUAN: Mengajarkan konsep IPA, mempersiapkan siswa memahami materi pelajaran",
          "• SUMBER: Kurikulum nasional, penelitian ilmiah, data dari para ahli IPA",
          "• GAYA BAHASA: Lugas, denotatif, istilah ilmiah ('Fotosintesis adalah proses...')",
          "• STRUKTUR: Bab tematis (Bab 1: Gerak, Bab 2: Gaya, Bab 3: Usaha) dengan sub-bab, soal latihan, dan rangkuman",
          "• PEMBACA: Siswa SMP kelas VIII yang belajar IPA",
          "",
          "✓ Coba sendiri: Ambil satu buku fiksi dan satu buku nonfiksi yang kamu miliki. Bandingkan kelima dimensi di atas. Catat perbedaannya dalam tabel!",
        ],
        catatan: "Apakah kamu tahu bahwa beberapa novel 'serius' ditulis dengan riset mendalam seperti nonfiksi? Novel sejarah seperti 'Bumi Manusia' membutuhkan riset tentang kehidupan sosial-politik Hindia Belanda. Tapi ingat: riset hanya sebagai BAHAN, bukan TUJUAN — novel itu tetap fiksi karena dialog dan tokohnya adalah rekaan!",
      },
      {
        judul: "Mengevaluasi Kualitas Buku",
        isi: [
          "Setelah memahami perbedaan fiksi dan nonfiksi, sekarang saatnya belajar MENGEVALUASI kualitas buku. Tidak semua buku fiksi bagus, tidak semua buku nonfiksi akurat. Sebagai pembaca cerdas, kamu harus bisa menilai kualitas bacaanmu!",
          "",
          "KRITERIA EVALUASI BUKU FIKSI:",
          "",
          "1. PLOT (Alur Cerita) — Apakah alurnya logis dan menarik? Apakah ada konsistensi? Apakah klimaksnya memuaskan?",
          "  ✓ Bagus: Alur maju mundur yang rapi, twist mengejutkan tapi masuk akal, klimaks yang mengguncang emosi.",
          "  ✗ Buruk: Alur membingungkan, lompat-lompat tanpa penjelasan, klimaks datar atau antiklimaks.",
          "",
          "2. KARAKTER DEVELOPMENT — Apakah tokoh mengalami perubahan/pertumbuhan? Apakah tokoh terasa 'nyata'?",
          "  ✓ Bagus: Karakter berubah secara meyakinkan setelah konflik; pembaca peduli pada nasib tokoh.",
          "  ✗ Buruk: Tokoh datar, tidak berkembang, atau kebetulan berubah tanpa proses psikologis yang jelas.",
          "",
          "3. GAYA BAHASA — Apakah bahasa yang digunakan enak dibaca dan sesuai dengan cerita?",
          "  ✓ Bagus: Diksi tepat, ritme kalimat pas, majas tidak berlebihan, dialog terdengar alami.",
          "  ✗ Buruk: Bahasa bertele-tele, klise, atau sebaliknya — terlalu sederhana sehingga cerita hambar.",
          "",
          "4. PESAN / AMANAT — Apakah pesan yang disampaikan bermakna dan tidak menggurui?",
          "  ✓ Bagus: Pesan tersirat secara alami melalui cerita, tidak seperti 'kotak sabun' penceramah.",
          "  ✗ Buruk: Pesan dipaksakan, tokoh tiba-tiba 'berpidato' tentang moral di akhir cerita.",
          "",
          "KRITERIA EVALUASI BUKU NONFIKSI:",
          "",
          "1. AKURASI DATA — Apakah data dan fakta yang disajikan benar dan dapat diverifikasi?",
          "  ✓ Bagus: Data dari sumber terpercaya, dapat dicek silang, tidak ada kesalahan faktual mencolok.",
          "  ✗ Buruk: Data tanpa sumber, angka tidak konsisten, klaim tanpa bukti.",
          "",
          "2. KEDALAMAN RISET — Apakah penulis benar-benar menguasai topik yang ditulis?",
          "  ✓ Bagus: Referensi luas dan beragam, penulis menunjukkan pemahaman mendalam tentang subjek.",
          "  ✗ Buruk: Hanya menyentuh permukaan, terlalu bergantung pada satu sumber, atau opini tanpa dasar riset.",
          "",
          "3. KEJELASAN PENJELASAN — Apakah penjelasan mudah dipahami oleh target pembaca?",
          "  ✓ Bagus: Konsep rumit dijelaskan dengan analogi, contoh, dan bahasa yang mudah dicerna.",
          "  ✗ Buruk: Terlalu teknis/akademis (jika targetnya umum), atau terlalu dangkal (jika targetnya profesional).",
          "",
          "4. KREDIBILITAS PENULIS — Apakah penulis memiliki latar belakang atau keahlian yang relevan?",
          "  ✓ Bagus: Penulis adalah akademisi, praktisi, atau peneliti di bidangnya dengan rekam jejak jelas.",
          "  ✗ Buruk: Penulis tidak memiliki kompetensi yang jelas di topik tersebut.",
          "",
          "PENTING: Sebagai pembaca kritis, jangan percaya begitu saja pada apa yang kamu baca — baik fiksi maupun nonfiksi! Buku fiksi bisa menyesatkan jika stereotipnya merugikan; buku nonfiksi bisa menyesatkan jika datanya salah atau bias. SELALU gunakan nalar kritis!",
        ],
        contoh: [
          "Contoh evaluasi buku fiksi — Novel 'Perburuan' (Pramoedya Ananta Toer):",
          "",
          "PLOT: ★★★★★ — Alur maju yang rapi, ketegangan terus meningkat saat tokoh utama diburu tentara Jepang. Klimaks di persimpangan hidup-mati sangat menggetarkan.",
          "KARAKTER: ★★★★☆ — Tokoh utama (Hardo) berkembang dari pemuda ketakutan menjadi pejuang berani. Sayang, tokoh antagonis (Heru) kurang dimensional.",
          "GAYA BAHASA: ★★★★★ — Bahasa Pramoedya lugas namun penuh tenaga. Setiap kalimat seperti pukulan bertubi-tubi. Tidak bertele-tele tetapi sangat ekspresif.",
          "PESAN: ★★★★☆ — Semangat nasionalisme dan pengorbanan tersampaikan kuat. Sedikit menggurui di beberapa bagian akhir.",
          "",
          "Contoh evaluasi buku nonfiksi — 'Sapiens' (Yuval Noah Harari):",
          "",
          "AKURASI DATA: ★★★★★ — Didukung riset multidisiplin (antropologi, biologi, sejarah), data dari jurnal terkemuka.",
          "RISET: ★★★★★ — Harari merangkum 70.000 tahun sejarah manusia dengan sumber yang sangat luas.",
          "KEJELASAN: ★★★★★ — Konsep rumit seperti 'revolusi kognitif' dijelaskan dengan analogi brilian yang mudah dipahami.",
          "KREDIBILITAS: ★★★★★ — Harari adalah profesor sejarah di Hebrew University of Jerusalem dengan spesialisasi world history.",
          "",
          "Tips mengevaluasi buku: Buatlah tabel bintang 1—5 untuk setiap kriteria. Ini akan membantumu membandingkan buku secara objektif dan menulis resensi yang berbobot!",
        ],
        catatan: "Evaluasi bersifat SUBJEKTIF dalam batas tertentu — apa yang menurutmu 'plot bagus' mungkin berbeda dengan temanmu. Tapi ada standar objektif yang bisa dipakai bersama. Semakin sering kamu membaca dan mengevaluasi, semakin tajam 'indra kritis' mu!",
      },
      {
        judul: "Resensi Kritis, Book Report, dan Membandingkan Buku",
        isi: [
          "Seorang pembaca yang baik juga harus bisa MENULIS tentang apa yang dibacanya. Ada dua bentuk tulisan yang sering diminta di sekolah: RESENSI dan BOOK REPORT. Apa bedanya?",
          "",
          "RESENSI BUKU adalah tulisan yang mengulas, menganalisis, dan mengevaluasi isi buku secara kritis. Resensi bukan sekadar ringkasan — ini adalah ANALISIS yang memuat penilaian subjektif yang didukung argumen.",
          "",
          "• Tujuan: Membantu calon pembaca memutuskan apakah buku itu layak dibaca.",
          "• Bersifat: ANALITIS dan EVALUATIF.",
          "• Berisi: Analisis kelebihan + kekurangan, didukung argumen dan bukti.",
          "• Pembaca: Publik umum yang mencari rekomendasi buku.",
          "",
          "BOOK REPORT (Laporan Buku) adalah tulisan yang berisi ringkasan dan fakta-fakta dasar tentang buku yang telah dibaca, biasanya untuk tugas sekolah.",
          "",
          "• Tujuan: Membuktikan bahwa siswa telah membaca dan memahami buku.",
          "• Bersifat: DESKRIPTIF dan INFORMATIF.",
          "• Berisi: Identitas buku, ringkasan isi, kesan pribadi (tanpa analisis mendalam).",
          "• Pembaca: Guru atau instruktur.",
          "",
          "1. RESENSI (kritis): 'Novel ini memiliki plot yang kuat dengan twist mengejutkan di bab 12, tetapi karakter antagonisnya terasa stereotip dan kurang dimensi. Meskipun begitu, gaya bahasa penulis yang puitis berhasil membangun atmosfer yang magis.'",
          "",
          "2. BOOK REPORT: 'Novel ini bercerita tentang seorang anak bernama Ikal yang bersekolah di SD Muhammadiyah Belitung. Tokoh utamanya adalah Ikal, Lintang, dan Mahar. Latar cerita di Belitung tahun 1970-an. Saya suka novel ini karena menginspirasi.'",
          "",
          "CARA MEMBANDINGKAN BUKU (Fiksi vs Nonfiksi Tema Sama):",
          "",
          "Langkah 1: Pilih dua buku dengan tema sama — satu fiksi, satu nonfiksi. Contoh tema 'Perjuangan Kemerdekaan': fiksi = 'Bumi Manusia' (Pramoedya), nonfiksi = 'Sejarah Nasional Indonesia' (Kemdikbud).",
          "",
          "Langkah 2: Buat tabel perbandingan mencakup:",
          "  • Tujuan buku: menghibur vs menginformasikan",
          "  • Cara penyampaian: melalui cerita vs melalui data",
          "  • Tokoh/pelaku: rekaan vs tokoh sejarah nyata",
          "  • Kebenaran: imajinatif vs faktual",
          "  • Kesan setelah membaca: emosional vs intelektual",
          "",
          "Langkah 3: Analisis — mana yang lebih efektif untuk memahami tema? Fiksi mungkin membuatmu 'merasakan' perjuangan, nonfiksi membuatmu 'memahami' konteksnya. Keduanya saling melengkapi!",
          "",
          "Langkah 4: Tulis kesimpulan — buku mana yang lebih kamu rekomendasikan untuk pembaca pemula? Mengapa?",
          "",
          "[Ilustrasi: Bagan perbandingan dua buku dengan kolom 'Plot', 'Karakter', 'Data', 'Sumber', 'Bahasa', 'Pesan' — masing-masing kolom memiliki centang (✓) atau silang (✗) sebagai evaluasi cepat — seperti lembar kerja review buku.]",
        ],
        contoh: [
          "Contoh perbandingan buku FIKSI dan NONFIKSI bertema 'Perubahan Iklim':",
          "",
          "BUKU FIKSI: 'The Ministry for the Future' (Kim Stanley Robinson, 2020)",
          "• Novel fiksi ilmiah tentang perubahan iklim pada tahun 2025—2050",
          "• Tokoh rekaan: Frank (diplomat), Mary (aktivis), Badai Panas (karakter simbolik)",
          "• Menggunakan cerita untuk membuat pembaca MERASAKAN dampak krisis iklim",
          "• Gaya: naratif, emosional, imajinatif namun berdasarkan proyeksi ilmiah",
          "• Kutipan: 'Heat kills you quietly. It doesn't shout. It doesn't shake you. It just wraps around you and waits.'",
          "",
          "BUKU NONFIKSI: 'The Uninhabitable Earth' (David Wallace-Wells, 2019)",
          "• Buku nonfiksi tentang dampak perubahan iklim berdasarkan data riset",
          "• Tidak ada tokoh — fokus pada fakta, data, dan proyeksi ilmiah",
          "• Menggunakan data untuk membuat pembaca MEMAHAMI urgensi krisis iklim",
          "• Gaya: analitis, informatif, referensi jurnal ilmiah",
          "• Kutipan: 'The Earth is warming at a rate that is unprecedented in the history of human civilization.'",
          "",
          "KESIMPULAN: Kedua buku membahas topik yang sama — perubahan iklim — tetapi dengan cara yang berbeda. Fiksi membuatmu peduli secara emosional, nonfiksi memberimu pemahaman intelektual. Membaca keduanya akan memberikan pemahaman yang LEBIH LENGKAP daripada hanya membaca salah satu!",
          "",
          "• Book report: cukup tulis ringkasan isi + kesan pribadi (3 paragraf).",
          "• Resensi kritis: identitas + orientasi + sinopsis + ANALISIS (kelebihan & kekurangan) + evaluasi + rekomendasi (5+ paragraf).",
        ],
        catatan: "Resensi kritis yang BAIK harus berimbang — sebutkan kelebihan SEKALIGUS kekurangan. Tidak ada buku yang sempurna. Resensi yang hanya memuji atau hanya mengkritik disebut resensi 'pembeli' dan tidak kredibel. Sebagai penulis resensi pemula, biasakan selalu menulis minimal SATU kelebihan dan SATU kekurangan!",
      },
      {
        judul: "Manfaat Membaca: Piramida Pengetahuan",
        isi: [
          "Mengapa kita harus membaca buku — baik fiksi maupun nonfiksi? Manfaat membaca bisa digambarkan seperti PIRAMIDA TIGA TINGKAT: dari Hiburan di dasar hingga Transformasi di puncak.",
          "",
          "TINGKAT 1 — HIBURAN (Base):",
          "Inilah manfaat paling dasar dan paling langsung. Membaca buku fiksi memberikan kesenangan, relaksasi, dan hiburan setelah penat belajar. Membaca novel seru atau cerita lucu bisa langsung memperbaiki suasana hati!",
          "  • Mengurangi stres: 6 menit membaca sudah cukup untuk menurunkan detak jantung dan ketegangan otot.",
          "  • Membawa pelarian (escapism): sejenak melupakan masalah dan masuk ke dunia lain.",
          "  • Meningkatkan mood: cerita lucu atau mengharukan melepaskan hormon dopamin dan oksitosin.",
          "",
          "TINGKAT 2 — WAWASAN (Middle):",
          "Manfaat ini datang dari membaca fiksi DAN nonfiksi secara seimbang. Pengetahuan dan pemahaman akan dunia bertambah luas.",
          "  • Kognitif: Memperkaya kosakata, meningkatkan pemahaman bacaan, melatih konsentrasi dan fokus.",
          "  • Emosional: Fiksi mengembangkan EMPATI — kemampuan memahami perasaan orang lain. Penelitian menunjukkan pembaca fiksi sastra memiliki empati lebih tinggi!",
          "  • Sosial: Memberikan bahan diskusi, topik pembicaraan, dan pengetahuan budaya.",
          "  • Akademis: Nonfiksi meningkatkan kemampuan analitis, pemahaman konsep, dan prestasi belajar.",
          "",
          "TINGKAT 3 — TRANSFORMASI (Puncak):",
          "Inilah manfaat tertinggi. Buku yang benar-benar mengubah cara pandang, pola pikir, dan bahkan kehidupan seseorang.",
          "  • Membaca 'Sapiens' membuatmu melihat seluruh sejarah manusia dari perspektif baru.",
          "  • Membaca 'Laskar Pelangi' bisa mengubah pandanganmu tentang pendidikan dan kemiskinan.",
          "  • Membaca biografi tokoh inspiratif bisa mengubah caramu menjalani hidup.",
          "  • Membaca filsafat atau psikologi bisa mengubah cara berpikirmu tentang realitas dan kebahagiaan.",
          "",
          "Tips membaca seumur hidup:",
          "  • Baca 20 halaman sehari — dalam setahun kamu sudah membaca 7.300 halaman (sekitar 15—20 buku)!",
          "  • Bacalah dengan PENSIL — tandai, garis bawahi, tulis catatan pinggir.",
          "  • Diskusikan dengan teman — membaca sendirian itu baik, mendiskusikannya lebih baik.",
          "  • Jangan takut berhenti — jika buku membosankan setelah 50 halaman, tinggalkan. Terlalu banyak buku bagus yang menunggumu!",
          "",
          "[Ilustrasi: Piramida tiga tingkat — tingkat bawah 'Hiburan' dengan ikon buku terbuka dan senyuman, tingkat tengah 'Wawasan' dengan ikon otak dan kaca pembesar, tingkat atas 'Transformasi' dengan ikon bintang bersinar. Panah naik dari bawah ke atas bertuliskan 'Semakin Dalam Membaca, Semakin Tinggi Manfaatnya'.]",
        ],
        contoh: [
          "Piramida Membaca untuk seorang siswa SMP:",
          "",
          "CONTOH SISWA A (Hanya Fiksi Hiburan):",
          "Membaca novel Dilan, Wattpad, cerita horor, dan komik setiap hari.",
          "✓ Manfaat: Hiburan maksimal, stres berkurang, imajinasi terlatih.",
          "✗ Kekurangan: Kurang wawasan faktual, analisis akademis lemah, kesulitan menulis esai nonfiksi.",
          "",
          "CONTOH SISWA B (Hanya Nonfiksi Akademis):",
          "Membaca buku pelajaran, ensiklopedia, dan artikel ilmiah setiap hari.",
          "✓ Manfaat: Wawasan luas, nilai akademis bagus, kemampuan analitis tajam.",
          "✗ Kekurangan: Kurang empati, kreativitas linguistik terbatas, cepat bosan/burnout.",
          "",
          "CONTOH SISWA C (Seimbang Fiksi + Nonfiksi):",
          "Seminggu baca novel, seminggu baca buku sains. Bergantian.",
          "✓ Manfaat: Empati tinggi + wawasan luas + kreativitas tajam + prestasi akademis bagus + stres terkendali.",
          "Inilah pembaca IDEAL!",
          "",
          "Tips membuat jadwal membaca: Senin—Rabu baca nonfiksi (30 menit), Kamis—Sabtu baca fiksi (30 menit), Minggu bebas atau membaca ulang. Atur sesuai preferensimu!",
        ],
        catatan: "Penelitian neurosains menunjukkan bahwa membaca fiksi secara rutin meningkatkan KONEKTIVITAS OTAK di area yang terkait dengan empati dan pemahaman sosial — efeknya bertahan hingga berhari-hari setelah selesai membaca! Sementara itu, membaca nonfiksi meningkatkan koneksi di area yang terkait dengan memori dan penalaran logis. Solusinya: baca KEDUANYA!",
      },
    ],
    rangkuman: [
      "Fiksi dan nonfiksi berbeda dalam 5 dimensi: tujuan (hiburan vs informasi), sumber (imajinasi vs data), gaya bahasa (konotatif vs denotatif), struktur (bebas vs sistematis), dan pembaca (kesenangan vs pengetahuan).",
      "Mengevaluasi buku fiksi menggunakan 4 kriteria: plot, karakter development, gaya bahasa, dan pesan/amanat. Buku fiksi berkualitas memiliki karakter yang berkembang secara meyakinkan dan pesan yang tersirat secara alami.",
      "Mengevaluasi buku nonfiksi menggunakan 4 kriteria: akurasi data, kedalaman riset, kejelasan penjelasan, dan kredibilitas penulis. Buku nonfiksi berkualitas didukung sumber terpercaya dan ditulis oleh penulis yang kompeten.",
      "Resensi kritis berbeda dari book report: resensi bersifat analitis-evaluatif (kelebihan + kekurangan), sedangkan book report bersifat deskriptif (ringkasan + kesan).",
      "Membandingkan buku fiksi dan nonfiksi bertema sama dilakukan dengan tabel perbandingan yang mencakup tujuan, cara penyampaian, tokoh, kebenaran, dan kesan — keduanya saling melengkapi.",
      "Manfaat membaca membentuk piramida tiga tingkat: Hiburan (dasar) → Wawasan (tengah) → Transformasi (puncak). Membaca seimbang fiksi dan nonfiksi memberikan manfaat optimal secara kognitif, emosional, sosial, dan akademis.",
    ],
  },

  latihan: makeSoal([
    ["Perbedaan PALING MENDASAR antara fiksi dan nonfiksi adalah...", ["Fiksi lebih tebal dari nonfiksi", "Fiksi bersumber dari imajinasi, nonfiksi bersumber dari fakta", "Fiksi selalu mahal, nonfiksi murah", "Fiksi hanya untuk anak-anak"], 1, "Perbedaan mendasar adalah sumbernya: fiksi dari imajinasi penulis (rekaan), nonfiksi dari data dan fakta yang dapat diverifikasi."],
    ["Berikut ini adalah KRITERIA untuk mengevaluasi kualitas buku nonfiksi, KECUALI...", ["Akurasi data dan fakta", "Kedalaman riset dan referensi", "Kreativitas plot dan alur cerita", "Kredibilitas dan keahlian penulis"], 2, "Kreativitas plot dan alur cerita adalah kriteria untuk buku FIKSI, bukan nonfiksi. Nonfiksi dievaluasi dari akurasi, riset, dan kredibilitas penulis."],
    ["Perbedaan RESENSI KRITIS dengan BOOK REPORT adalah...", ["Resensi lebih pendek dari book report", "Resensi bersifat analitis-evaluatif, book report deskriptif-informatif", "Resensi hanya untuk fiksi, book report untuk nonfiksi", "Tidak ada perbedaan"], 1, "Resensi kritis menganalisis kelebihan dan kekurangan buku dengan argumen, sedangkan book report hanya meringkas isi dan memberi kesan pribadi."],
    ["Novel 'Bumi Manusia' karya Pramoedya Ananta Toer termasuk fiksi meskipun berlatar sejarah karena...", ["Diterbitkan oleh penerbit fiksi", "Tokoh, dialog, dan adegannya adalah rekaan penulis", "Tidak ada daftar pustaka", "Sampulnya seperti novel"], 1, "Meskipun berlatar sejarah, Bumi Manusia tetap FIKSI karena tokoh-tokohnya (Minke, Annelies) dan dialog-dialognya adalah hasil imajinasi Pramoedya, bukan fakta sejarah."],
    ["Manfaat membaca pada tingkat TERTINGGI dalam piramida membaca adalah...", ["Hiburan dan relaksasi", "Wawasan dan pengetahuan", "Transformasi cara pandang dan kehidupan", "Nilai akademis yang baik"], 2, "Puncak piramida adalah TRANSFORMASI — ketika buku mengubah cara pandang, pola pikir, dan bahkan arah hidup seseorang."],

    ["Pernyataan: 'Buku nonfiksi menggunakan bahasa konotatif dan figuratif seperti fiksi.'", ["Betul", "Salah"], 1, "SALAH. Buku nonfiksi menggunakan bahasa DENOTATIF (makna sebenarnya, lugas, informatif), bukan konotatif yang merupakan ciri fiksi."],
    ["Pernyataan: 'Penelitian neurosains membuktikan bahwa membaca fiksi meningkatkan empati dan konektivitas otak di area sosial-emosional.'", ["Betul", "Salah"], 0, "BETUL. Penelitian menunjukkan membaca fiksi sastra secara rutin meningkatkan kemampuan empati dan konektivitas otak di area yang terkait dengan pemahaman sosial."],
    ["Pernyataan: 'Resensi yang baik hanya memuji kelebihan buku tanpa menyebutkan kekurangannya.'", ["Betul", "Salah"], 1, "SALAH. Resensi yang kredibel dan berimbang harus menyebutkan KELEBIHAN DAN KEKURANGAN buku. Resensi yang hanya memuji tidak objektif."],

    ["Dalam mengevaluasi buku FIKSI, aspek yang perlu dianalisis meliputi plot, karakter, gaya bahasa, dan...", ["Indeks", "Daftar pustaka", "Pesan/amanat", "Glosarium"], 2, "Empat kriteria evaluasi fiksi: plot, karakter development, gaya bahasa, dan pesan/amanat. Indeks, daftar pustaka, dan glosarium adalah unsur nonfiksi."],
    ["Ketika membandingkan dua buku (fiksi dan nonfiksi) dengan tema yang sama, langkah PERTAMA yang harus dilakukan adalah...", ["Menulis resensi panjang", "Memilih dua buku dengan tema yang sama", "Membaca buku sampai habis", "Membuat tabel perbandingan"], 1, "Langkah pertama adalah memilih dua buku dengan tema yang SAMA. Setelah itu baru membaca, membuat tabel perbandingan, menganalisis, dan menyimpulkan."],
  ]),

  praktik: {
    petunjuk: "Tulis sebuah RESENSI KRITIS dengan membandingkan SATU buku fiksi dan SATU buku nonfiksi yang memiliki tema yang SAMA (misalnya: tema perjuangan, lingkungan, pendidikan, atau persahabatan). Ikuti langkah-langkah berikut:\n\n[Ilustrasi: Dua buku terbuka berdampingan — buku kiri (fiksi) dengan ilustrasi puitis, buku kanan (nonfiksi) dengan grafik dan diagram. Di bawahnya, tabel perbandingan dengan kolom-kolom yang sudah diisi sebagian sebagai panduan.]\n\nLANGKAH 1 — Pilih Tema dan Dua Buku\nPilih SATU tema yang menarik bagimu. Lalu pilih SATU buku fiksi dan SATU buku nonfiksi yang membahas tema tersebut. Jika belum punya buku fisik, kamu bisa menggunakan buku digital atau buku yang tersedia di perpustakaan sekolah.\n\nLANGKAH 2 — Identitas Kedua Buku\nTulis identitas lengkap kedua buku: judul, penulis, penerbit, tahun terbit, jumlah halaman, ISBN, dan genre/jenis buku.\n\nLANGKAH 3 — Sinopsis Singkat\nTulis sinopsis singkat masing-masing buku (maksimal 1 paragraf per buku). Apa yang dibahas? Siapa tokohnya (untuk fiksi) atau apa topik utamanya (untuk nonfiksi)?\n\nLANGKAH 4 — Tabel Perbandingan\nBuat tabel perbandingan 5 dimensi: tujuan, sumber, gaya bahasa, struktur, dan pembaca sasaran. Isi untuk masing-masing buku.\n\nLANGKAH 5 — Analisis Kritis\nAnalisis KELEBIHAN dan KEKURANGAN masing-masing buku. Gunakan kriteria evaluasi yang sudah dipelajari: plot, karakter, gaya bahasa, pesan (untuk fiksi) — akurasi data, riset, kejelasan, kredibilitas (untuk nonfiksi).\n\nLANGKAH 6 — Kesimpulan dan Rekomendasi\nBuku mana yang lebih efektif menyampaikan tema? Buku mana yang kamu rekomendasikan untuk dibaca pertama? Mengapa? Akhiri dengan kalimat penutup yang kuat.\n\nPanjang resensi minimal 5 paragraf (tidak termasuk identitas buku).",
    tips: [
      "Pilih tema yang benar-benar kamu minati agar proses menulis lebih menyenangkan dan mendalam.",
      "Jika kesulitan menemukan dua buku dengan tema sama, pilih tema 'Perjuangan': fiksi = novel perjuangan, nonfiksi = buku sejarah perjuangan bangsa.",
      "Baca kedua buku sampai selesai — jangan hanya membaca sinopsis di sampul! Catat halaman-halaman penting yang mendukung argumenmu.",
      "Untuk tabel perbandingan, gunakan kertas terpisah atau buat di dokumen sebelum menulis resensi final.",
      "Jujurlah dalam analisis: tidak masalah jika buku fiksi lebih kamu sukai daripada nonfiksi, asalkan argumenmu logis dan didukung bukti.",
      "Perhatikan transisi antara analisis fiksi dan nonfiksi. Gunakan kata penghubung seperti 'Di sisi lain...', 'Sementara itu...', atau 'Berbeda dengan...'.",
      "Cantumkan minimal SATU kutipan dari masing-masing buku untuk memperkuat analisismu. Kutipan pendek sudah cukup!",
      "Akhiri dengan refleksi pribadi: apa yang kamu dapatkan setelah membaca dan membandingkan kedua buku tersebut?",
    ],
    contoh: "TEMA: Pendidikan dan Perjuangan di Daerah Terpencil\n\nIDENTITAS BUKU FIKSI\nJudul: Laskar Pelangi\nPenulis: Andrea Hirata\nPenerbit: Bentang Pustaka\nTahun Terbit: 2005\nJumlah Halaman: 534 halaman\nISBN: 978-979-3062-79-4\nGenre: Novel fiksi inspiratif\n\nIDENTITAS BUKU NONFIKSI\nJudul: Pendidikan di Daerah Terpencil: Potret dan Solusi\nPenulis: Prof. Dr. Arief Rachman (Tim Peneliti)\nPenerbit: Penerbit Buku Kompas\nTahun Terbit: 2018\nJumlah Halaman: 288 halaman\nISBN: 978-979-709-789-0\nGenre: Buku nonfiksi pendidikan/riset\n\nSINOPSIS FIKSI\n'Laskar Pelangi' mengisahkan sepuluh anak dari keluarga miskin di Belitung yang bersekolah di SD Muhammadiyah yang hampir dibubarkan. Ikal, Lintang, dan Mahar — bersama tujuh teman lainnya — berjuang melawan kemiskinan dan keterbatasan untuk tetap bisa bersekolah. Di bawah bimbingan Bu Muslimah dan Pak Harfan, mereka membuktikan bahwa semangat bisa mengalahkan keterbatasan. Novel ini tidak hanya bercerita tentang pendidikan, tetapi juga tentang persahabatan, mimpi, dan pengorbanan.\n\nSINOPSIS NONFIKSI\nBuku ini menyajikan hasil penelitian dan pengamatan langsung Prof. Arief Rachman dan timnya tentang kondisi pendidikan di daerah-daerah terpencil Indonesia — dari Papua hingga Nusa Tenggara. Buku ini memaparkan data faktual: rasio guru-murid, ketersediaan infrastruktur sekolah, tingkat putus sekolah, dan berbagai program intervensi yang telah dilakukan. Dilengkapi dengan foto dokumentasi, wawancara dengan guru lokal, serta rekomendasi kebijakan berbasis bukti.\n\nTABEL PERBANDINGAN\nAspek | Laskar Pelangi (Fiksi) | Pendidikan di Daerah Terpencil (Nonfiksi)\nTujuan | Menghibur dan menginspirasi melalui cerita | Menginformasikan kondisi riil dan memberikan solusi\nSumber | Imajinasi Andrea Hirata (terinspirasi masa kecil) | Data penelitian lapangan, wawancara, statistik resmi\nGaya Bahasa | Puitis, metaforis, emosional, jenaka | Lugas, akademis, informatif, objektif\nStruktur | 34 bab naratif dengan alur maju | Bab-bab tematis + data tabel/grafik + lampiran\nPembaca | Umum, remaja hingga dewasa | Akademisi, pembuat kebijakan, pegiat pendidikan\n\nANALISIS KRITIS\n'Laskar Pelangi' unggul dalam membangun EMPATI. Andrea Hirata dengan brilian membuat pembaca peduli pada nasib Ikal, Lintang, dan teman-temannya. Gaya bahasanya yang puitis (\"Matahari jatuh ke dalam laut seperti telur api raksasa\") berhasil menciptakan pengalaman membaca yang mengharukan dan tak terlupakan. Tokoh-tokohnya hidup dan memiliki perkembangan yang meyakinkan — Ikal yang pemalu tumbuh menjadi pemuda percaya diri, Lintang yang jenius harus berjuang melawan kemiskinan keluarganya. Kekurangannya: novel ini kadang terlalu mendramatisasi kemiskinan, seolah-olah semua orang miskin adalah pahlawan yang tabah — realitas tentu lebih kompleks.\n\n'Pendidikan di Daerah Terpencil' unggul dalam AKURASI dan KEDALAMAN DATA. Buku ini memberikan gambaran yang lebih presisi tentang masalah pendidikan di Indonesia — lengkap dengan angka, peta, dan analisis kebijakan. Kredibilitas penulis sebagai akademisi dan peneliti terpercaya tidak diragukan. Kekurangannya: gaya bahasa yang akademis dan kering membuat buku ini kurang 'bersahabat' untuk pembaca umum. Data yang melimpah kadang terasa membombardir pembaca, dan narasi yang kurang 'manusiawi' membuat pembaca sulit terhubung secara emosional.\n\nKESIMPULAN DAN REKOMENDASI\nKedua buku ini SALING MELENGKAPI. 'Laskar Pelangi' membuatmu PEDULI pada masalah pendidikan di daerah terpencil — hatimu tersentuh, kamu ingin melakukan sesuatu. 'Pendidikan di Daerah Terpencil' memberimu PEMAHAMAN tentang apa yang sebenarnya terjadi dan solusi apa yang mungkin dilakukan. Jika kamu hanya punya waktu untuk satu buku, bacalah 'Laskar Pelangi' dulu — biarkan novel ini membangkitkan kepedulianmu, lalu lanjutkan dengan buku nonfiksi untuk memahami masalahnya secara lebih utuh. Seperti kata pepatah: fiksi membuatmu peduli, nonfiksi membuatmu paham. Keduanya diperlukan untuk membuat perubahan!",
  },

  kuis: makeSoal([
    ["Dalam piramida membaca, tingkat WAWASAN berada di antara...", ["Hiburan dan Transformasi", "Hiburan dan Relaksasi", "Kognitif dan Emosional", "Akademis dan Sosial"], 0, "Piramida membaca: Hiburan (dasar) → Wawasan (tengah) → Transformasi (puncak). Wawasan mencakup manfaat kognitif, emosional, sosial, dan akademis."],
    ["Mengapa novel 'Bumi Manusia' tetap digolongkan sebagai FIKSI meskipun berlatar sejarah nyata?", ["Karena penulisnya terkenal sebagai penulis fiksi", "Karena tokoh, dialog, dan adegan spesifiknya adalah rekaan penulis, bukan fakta sejarah", "Karena sampulnya bergambar seperti novel", "Karena tidak ada kata pengantar dari sejarawan"], 1, "Meskipun latar sejarahnya nyata (Hindia Belanda awal 1900-an), tokoh Minke, Annelies, dan dialog-dialognya adalah ciptaan Pramoedya. Fakta sejarah hanya sebagai latar, bukan isi utama."],
    ["Manakah pernyataan yang PALING TEPAT tentang hubungan antara fiksi dan nonfiksi?", ["Fiksi lebih penting dari nonfiksi", "Nonfiksi lebih penting dari fiksi", "Fiksi dan nonfiksi saling melengkapi — fiksi membangun empati, nonfiksi membangun pemahaman", "Fiksi dan nonfiksi tidak ada hubungannya sama sekali"], 2, "Fiksi dan nonfiksi saling melengkapi. Fiksi membuat kita peduli (emosi/empati), nonfiksi membuat kita mengerti (pengetahuan/pemahaman). Keduanya diperlukan."],
    ["Jika kamu menemukan buku nonfiksi yang tidak mencantumkan daftar pustaka, apa kesimpulan yang PALING MASUK AKAL?", ["Buku itu pasti berbahaya", "Penulis mungkin tidak melakukan riset yang memadai atau sumbernya tidak dapat diverifikasi", "Buku itu lebih mudah dibaca", "Penerbit lupa mencetak"], 1, "Daftar pustaka adalah ciri penting buku nonfiksi yang baik. Ketidakhadirannya bisa menunjukkan kurangnya riset atau sumber yang tidak kredibel."],
    ["Dalam evaluasi buku fiksi, 'karakter development' mengacu pada...", ["Jumlah tokoh dalam cerita", "Perubahan dan pertumbuhan tokoh secara meyakinkan sepanjang cerita", "Nama-nama tokoh yang unik", "Kemunculan tokoh di setiap bab"], 1, "Karakter development berarti tokoh mengalami perubahan atau pertumbuhan yang masuk akal sebagai akibat dari konflik dan pengalaman dalam cerita."],
    ["Mengapa bahasa dalam fiksi cenderung KONOTATIF sedangkan nonfiksi DENOTATIF?", ["Fiksi ditulis oleh penulis yang lebih kreatif", "Tujuan fiksi adalah membangun pengalaman emosional melalui imajinasi, nonfiksi menyampaikan informasi faktual secara lugas", "Fiksi lebih sulit ditulis", "Penerbit fiksi lebih suka bahasa indah"], 1, "Fiksi menggunakan bahasa konotatif untuk membangun suasana, emosi, dan imajinasi. Nonfiksi menggunakan bahasa denotatif untuk menyampaikan informasi secara akurat dan objektif."],
    ["Seorang pembaca yang ideal sebaiknya...", ["Hanya membaca fiksi untuk hiburan", "Hanya membaca nonfiksi untuk pengetahuan", "Membaca fiksi dan nonfiksi secara seimbang", "Tidak membaca sama sekali"], 2, "Pembaca ideal membaca fiksi (untuk empati, hiburan, kreativitas) DAN nonfiksi (untuk wawasan, pengetahuan, analisis) secara seimbang."],
    ["Manakah yang BUKAN termasuk langkah dalam menulis resensi kritis?", ["Menganalisis kelebihan dan kekurangan buku", "Memberikan ringkasan isi buku", "Menyebutkan harga buku di pasaran", "Merekomendasikan buku kepada calon pembaca"], 2, "Resensi kritis mencakup identitas buku, sinopsis, analisis (kelebihan + kekurangan), dan rekomendasi. Harga buku bukan komponen wajib resensi."],
    ["Perbedaan utama antara resensi kritis dan book report adalah...", ["Resensi untuk tugas sekolah, book report untuk publikasi", "Resensi menganalisis kelebihan & kekurangan, book report hanya merangkum & memberi kesan", "Resensi lebih panjang dari book report", "Book report ditulis dalam bahasa Inggris"], 1, "Resensi bersifat analitis-evaluatif (membedah kelebihan + kekurangan), sedangkan book report bersifat deskriptif (ringkasan isi + kesan pribadi)."],
    ["Jika kamu harus membandingkan novel 'Laskar Pelangi' (fiksi) dengan buku 'Pendidikan di Daerah Terpencil' (nonfiksi), aspek apa yang PALING BERBEDA?", ["Jumlah halaman", "Sumber informasi: imajinasi vs data penelitian", "Bahasa yang digunakan: Indonesia vs Inggris", "Penerbit: besar vs kecil"], 1, "Perbedaan paling mendasar adalah sumber informasi: Laskar Pelangi bersumber dari imajinasi Andrea Hirata, sedangkan buku nonfiksi bersumber dari data penelitian lapangan dan statistik resmi."],
  ]),
}

export default konten
