import type { Konten } from "../types"
import { makeSoal } from "../types"

const konten: Konten = {
  belajar: {
    tujuan: [
      "Memahami pengertian, fungsi, dan jenis-jenis surat resmi dalam kehidupan sehari-hari",
      "Menguasai struktur lengkap surat resmi dengan 12 komponen beserta fungsinya",
      "Menerapkan kaidah kebahasaan surat resmi: kata baku, kalimat efektif, dan istilah kedinasan",
      "Menganalisis berbagai format penulisan surat resmi dan etika berkorespondensi",
      "Menulis surat resmi lengkap sesuai jenis, struktur, dan kaidah kebahasaan yang benar",
    ],
    materi: [
      {
        judul: "Apa Itu Surat Resmi?",
        isi: [
          "Surat resmi adalah surat yang digunakan untuk kepentingan kedinasan, pemerintahan, atau organisasi — menggunakan format baku, bahasa formal, dan aturan penulisan yang ketat. Berbeda dengan surat pribadi yang bebas dan santai, surat resmi adalah 'wajah resmi' dari sebuah instansi atau lembaga.",
          "",
          "Ciri utama surat resmi: (1) menggunakan kop surat atau kepala surat, (2) memiliki nomor surat, (3) menggunakan bahasa baku sesuai EYD V, (4) format sistematis dan baku, (5) ditandatangani pejabat berwenang, (6) dilengkapi stempel resmi, (7) isi bersifat kedinasan — bukan personal.",
          "",
          "[Ilustrasi: Perbandingan dua surat bersebelahan. Kiri: amplop surat pribadi dengan tulisan tangan dan perangko biasa. Kanan: surat resmi di atas kertas berkop 'PEMERINTAH PROVINSI DKI JAKARTA' lengkap dengan logo, stempel, dan nomor surat — tampak formal dan profesional.]",
          "",
          "JENIS-JENIS SURAT RESMI:",
          "",
          "1. SURAT UNDANGAN — Surat yang berisi ajakan atau permohonan kehadiran pada suatu acara resmi. Contoh: undangan rapat orang tua murid, undangan seminar, undangan pernikahan resmi.",
          "  • Ciri khas: mencantumkan hari/tanggal, waktu, tempat, acara, dan permohonan konfirmasi kehadiran.",
          "",
          "2. SURAT EDARAN — Surat pemberitahuan resmi yang ditujukan kepada banyak pihak secara serentak. Contoh: surat edaran libur nasional, edaran tentang tata tertib sekolah, edaran kenaikan UKT.",
          "  • Ciri khas: isi bersifat pengumuman atau instruksi, diedarkan ke banyak orang/unit.",
          "",
          "3. SURAT KEPUTUSAN (SK) — Surat yang berisi penetapan resmi dari pejabat berwenang. Contoh: SK pengangkatan guru tetap, SK pembentukan panitia, SK kelulusan siswa.",
          "  • Ciri khas: memiliki kekuatan hukum mengikat, biasanya dibubuhi meterai.",
          "",
          "4. SURAT TUGAS — Surat yang memberikan penugasan resmi kepada seseorang/pegawai. Contoh: surat tugas mengikuti pelatihan, surat tugas dinas ke luar kota.",
          "  • Ciri khas: mencantumkan nama yang ditugaskan, tujuan, dan jangka waktu tugas.",
          "",
          "5. SURAT IZIN — Surat permohonan izin resmi, baik dari individu ke instansi maupun antarinstitusi. Contoh: surat izin penelitian, surat izin cuti, surat izin mengadakan kegiatan.",
          "  • Ciri khas: menyebutkan alasan izin, durasi, dan tanggung jawab pemohon.",
          "",
          "6. SURAT LAMARAN PEKERJAAN — Surat dari pelamar kerja kepada perusahaan/instansi untuk melamar posisi tertentu. Contoh: surat lamaran ke BUMN, perusahaan swasta, atau instansi pemerintah.",
          "  • Ciri khas: dilengkapi CV, ijazah, dan dokumen pendukung; langsung ditujukan ke bagian HRD.",
          "",
          "7. SURAT PERNYATAAN — Surat yang berisi pernyataan resmi seseorang yang memiliki konsekuensi hukum. Contoh: surat pernyataan bersedia ditempatkan di mana saja, surat pernyataan tidak merokok, surat pernyataan bebas narkoba.",
          "  • Ciri khas: ditandatangani di atas meterai, disaksikan pejabat berwenang.",
          "",
          "8. NOTA DINAS — Surat komunikasi internal di dalam suatu instansi atau organisasi. Contoh: nota dinas dari kepala bagian ke staf, nota dinas antarunit kerja.",
          "  • Ciri khas: lebih ringkas dari surat resmi biasa, hanya menyangkut urusan internal.",
          "",
          "9. NOTULEN — Catatan resmi hasil rapat atau sidang. Contoh: notulen rapat OSIS, notulen sidang guru, notulen musyawarah desa.",
          "  • Ciri khas: berisi agenda, peserta, pembahasan, keputusan, dan penugasan.",
          "",
          "[Ilustrasi: Sebuah bagan pohon dengan akar 'SURAT RESMI' dan sembilan cabang mewakili sembilan jenis surat. Setiap cabang memiliki ikon kecil: undangan (amplop), edaran (megafon), SK (palu hakim), tugas (tas kerja), izin (centang hijau), lamaran (orang melamar), pernyataan (meterai), nota dinas (kertas internal), notulen (buku catatan).]",
          "",
          "PENTING: Setiap jenis surat resmi memiliki fungsi dan format yang sedikit berbeda. Mengirim surat undangan dengan format surat tugas — atau sebaliknya — adalah kesalahan fatal dalam administrasi perkantoran!",
        ],
        contoh: [
          "CONTOH Situasi Penggunaan Surat Resmi:",
          "",
          "• Kepala sekolah menerbitkan SURAT KEPUTUSAN tentang penetapan panitia perpisahan kelas IX.",
          "• Dinas Pendidikan mengirim SURAT EDARAN ke semua sekolah tentang jadwal ujian nasional.",
          "• Seorang guru menerima SURAT TUGAS untuk mengikuti pelatihan di provinsi.",
          "• OSIS mengirim SURAT UNDANGAN kepada sekolah lain untuk acara pentas seni.",
          "• Seorang mahasiswa mengirim SURAT IZIN penelitian ke sekolah untuk skripsinya.",
          "",
          "BENAR: \"Sehubungan dengan akan dilaksanakannya kegiatan perpisahan kelas IX, kami mohon izin untuk menggunakan aula sekolah.\" — alasan jelas, sopan, formal.",
          "SALAH: \"Kami mau pinjam aula buat acara perpisahan, ya.\" — terlalu santai, tidak resmi, tidak mencantumkan identitas pengirim.",
          "",
          "BENAR: \"Berdasarkan Keputusan Kepala Dinas Pendidikan Nomor 421/2024, dengan ini kami menyampaikan...\" — menyertakan dasar hukum.",
          "SALAH: \"Menurut berita yang kami dengar, ada aturan baru...\" — tidak menyertakan dasar hukum yang jelas.",
        ],
        catatan: "Surat resmi adalah dokumen yang memiliki kekuatan hukum. Simpan arsip surat resmi dengan baik — bisa menjadi bukti penting di kemudian hari! Setiap surat keluar harus dicatat dalam buku agenda surat.",
      },
      {
        judul: "Struktur Lengkap Surat Resmi",
        isi: [
          "Surat resmi memiliki struktur baku yang terdiri dari 12 komponen. Setiap komponen memiliki posisi, fungsi, dan aturan penulisan yang spesifik. Mari kita pelajari satu per satu!",
          "",
          "1. KOP SURAT (KEPALA SURAT) — Komponen paling atas yang berisi identitas resmi instansi. Terdiri dari logo/nama instansi, alamat lengkap, nomor telepon, fax, email, dan website.",
          "  ✓ Kop surat mencerminkan kredibilitas dan resmi tidaknya sebuah surat.",
          "  ✓ Aturan: nama instansi ditulis kapital semua atau kapital awal (tergantung aturan instansi). Alamat ditulis lengkap dengan kode pos.",
          "  ✓ Contoh: 'PEMERINTAH PROVINSI JAWA BARAT / DINAS PENDIDIKAN / SMA NEGERI 1 BANDUNG / Jalan Merdeka No. 45 Bandung 40111 / Telp. (022) 1234567'",
          "",
          "2. NOMOR SURAT — Kode unik untuk setiap surat keluar. Berfungsi untuk pencatatan, pengarsipan, dan penelusuran surat.",
          "  • Format umum: Nomor: 001/SMA.01/VII/2026",
          "    - 001 = nomor urut surat",
          "    - SMA.01 = kode instansi/bagian",
          "    - VII = angka Romawi untuk bulan",
          "    - 2026 = tahun pembuatan",
          "  • Tips: nomor surat jangan ditulis dengan singkatan 'No.' — tulis lengkap 'Nomor:' untuk surat resmi.",
          "",
          "3. LAMPIRAN — Jumlah dokumen atau barang yang disertakan bersama surat. Jika tidak ada lampiran, ditulis tanda baca '—' (strip panjang) atau '-'. Contoh: 'Lampiran: 2 lembar', 'Lampiran: —'.",
          "",
          "4. PERIHAL (HAL) — Inti atau pokok surat yang ditulis secara singkat, jelas, dan spesifik. Contoh: 'Perihal: Undangan Rapat Koordinasi Guru' — bukan hanya 'Perihal: Rapat'.",
          "  PENTING: 'Perihal' berbeda dengan 'Judul'. Perihal harus langsung menggambarkan inti surat dalam 3–5 kata.",
          "",
          "5. ALAMAT TUJUAN — Nama dan alamat lengkap penerima surat. Gunakan 'Yth.' (Yang terhormat) diikuti nama/jabatan penerima.",
          "  ✓ Benar: 'Yth. Bapak Kepala SMP Negeri 2 / di tempat'",
          "  ✓ Benar: 'Yth. Ibu Dra. Siti Rahmawati, M.Pd.'",
          "  ✗ SALAH: 'Kepada Yth.' — cukup 'Yth.' saja karena 'Yth.' sudah berarti 'Yang terhormat'.",
          "  ✗ SALAH: 'Yth. Bapak' saja tanpa nama — harus spesifik siapa yang dituju.",
          "",
          "6. SALAM PEMBUKA — Kalimat sapaan formal di awal isi surat. Paling umum:",
          "  • 'Dengan hormat,' — paling netral, bisa dipakai di semua jenis surat.",
          "  • 'Assalamualaikum warahmatullahi wabarakatuh,' — untuk instansi dengan nuansa Islami.",
          "  • 'Salam sejahtera,' — alternatif netral lainnya.",
          "  Aturan: salam pembuka diakhiri koma (,), lalu lanjut ke paragraf isi.",
          "",
          "7. ISI SURAT — Uraian maksud dan tujuan surat yang terbagi dalam tiga alinea:",
          "  a. ALINEA PEMBUKA — Membuka komunikasi, menjelaskan latar belakang, atau merujuk pada surat/dasar sebelumnya.",
          "     Ungkapan umum: 'Sehubungan dengan...', 'Berdasarkan...', 'Menindaklanjuti...', 'Dengan ini kami...'",
          "  b. ALINEA ISI — Uraian pokok yang ingin disampaikan. Berisi fakta, data, permohonan, pemberitahuan, atau instruksi secara rinci.",
          "  c. ALINEA PENUTUP — Harapan, permohonan, atau tindakan yang diharapkan dari penerima. Juga ucapan terima kasih.",
          "     Ungkapan umum: 'Demikian...', 'Atas perhatiannya...', 'Mohon...'",
          "",
          "8. SALAM PENUTUP — Kalimat penutup formal sebelum nama dan tanda tangan. Contoh:",
          "  • 'Hormat kami,' — untuk surat mewakili instansi.",
          "  • 'Hormat saya,' — untuk surat individu yang bersifat resmi.",
          "  • 'Wassalamualaikum warahmatullahi wabarakatuh,' — penutup Islami.",
          "  Aturan: salam penutup diakhiri koma (,). Posisi di kanan bawah atau kiri (tergantung format).",
          "",
          "9. NAMA DAN JABATAN PENGIRIM — Identitas penanggung jawab surat. Terdiri dari:",
          "  • Jabatan pengirim (dicetak di atas tanda tangan)",
          "  • Tanda tangan basah",
          "  • Nama jelas (bisa digarisbawahi atau di dalam kurung)",
          "  • NIP (Nomor Induk Pegawai) untuk PNS",
          "  ✓ Contoh: 'Kepala Sekolah, / (ttd) / Drs. H. Ahmad Fauzi, M.Pd. / NIP. 19680503 199203 1 012'",
          "",
          "10. STEMPEL/CAP DINAS — Stempel resmi instansi yang ditempatkan di samping atau menutupi sebagian tanda tangan. Tanpa stempel, surat resmi tidak memiliki kekuatan hukum!",
          "",
          "11. TEMBUSAN — Daftar pihak yang menerima salinan/tembusan surat. Biasanya ditempatkan di bagian bawah paling akhir. Contoh: 'Tembusan: / 1. Kepala Dinas Pendidikan / 2. Arsip'",
          "",
          "12. INISIAL — Kode pengenal yang menunjukkan konseptor dan pengetik surat. Contoh: 'AF/RS' (AF = Ahmad Fauzi konseptor, RS = Rina Sari pengetik). Inisial ditempatkan di pojok kiri bawah, tepat di bawah tembusan.",
          "",
          "Tips: Hafalkan 12 komponen ini dengan singkatan: KO-NO-LA-PE-AL-SA-ISI-SA-TA-STE-TE-IN = Kop surat, Nomor, Lampiran, Perihal, Alamat, Salam, Isi, Salam, Tanda tangan, Stempel, Tembusan, Inisial.",
          "",
          "[Ilustrasi: Template surat resmi lengkap dengan 12 label bernomor yang menunjuk ke setiap bagian. Panah merah dari setiap label mengarah ke posisi masing-masing komponen pada surat. Nomor 1 (Kop Surat) di paling atas, nomor 12 (Inisial) di pojok kiri bawah.]",
        ],
        contoh: [
          "=== CONTOH SURAT RESMI LENGKAP ===\n\n[KOP SURAT]\nPEMERINTAH KABUPATEN BANDUNG\nDINAS PENDIDIKAN DAN KEBUDAYAAN\nSMP NEGERI 1 CIMAHI\nJalan Merdeka No. 20 Cimahi 40521\nTelp. (022) 6654321 | Email: smpn1cimahi@sch.id\n—————————————————————\n\nNomor: 023/SMP.01/V/2026\nLampiran: 1 berkas\nPerihal: Undangan Rapat Koordinasi Kenaikan Kelas\n\nYth. Bapak/Ibu Guru dan Karyawan\nSMP Negeri 1 Cimahi\ndi tempat\n\nDengan hormat,\n\nSehubungan dengan akan berakhirnya tahun ajaran 2025/2026, kami bermaksud mengadakan rapat koordinasi persiapan kenaikan kelas yang akan dilaksanakan pada:\n\nHari/Tanggal: Kamis, 28 Mei 2026\nWaktu: Pukul 13.00 WIB — selesai\nTempat: Aula SMP Negeri 1 Cimahi\nAcara: Koordinasi Kenaikan Kelas Tahun Ajaran 2025/2026\n\nMengingat pentingnya agenda ini, kami mengharapkan kehadiran seluruh Bapak/Ibu guru dan karyawan tepat pada waktunya. Pembahasan meliputi kriteria kenaikan kelas, pengisian rapor, dan persiapan kegiatan akhir tahun.\n\nDemikian undangan ini kami sampaikan. Atas perhatian dan kehadiran Bapak/Ibu, kami ucapkan terima kasih.\n\nWassalamualaikum warahmatullahi wabarakatuh.\n\nCimahi, 22 Mei 2026\nKepala Sekolah,\n\n(Tertanda)\n\nDrs. H. Cecep Suherman, M.Pd.\nNIP. 19690815 199512 1 003\n\n[STEMPEL RESMI SEKOLAH]\n\nTembusan:\n1. Ketua Komite Sekolah\n2. Arsip\n\nIS/AM",
        ],
        catatan: "Perhatikan contoh di atas: kota penulisan tanggal adalah CIMAHI (tempat instansi berada) — BUKAN kota penerima. Banyak siswa keliru menulis 'Jakarta,' padahal surat dari Cimahi. Tanggal ditulis: 'Cimahi, 22 Mei 2026' — tanpa spasi setelah koma sebelum bulan.",
      },
      {
        judul: "Kaidah Kebahasaan Surat Resmi",
        isi: [
          "Surat resmi menggunakan bahasa Indonesia yang baku, formal, dan efektif. Berikut kaidah kebahasaan yang harus diperhatikan:",
          "",
          "1. BAHASA BAKU SESUAI EYD V — Setiap kata harus ditulis sesuai KBBI. Tidak boleh ada singkatan tidak baku, kata gaul, atau bahasa sehari-hari.",
          "  ✓ Baku: 'tidak', 'dengan', 'sebagai', 'mengirimkan', 'memohon', 'memberitahukan'",
          "  ✗ Tidak baku: 'tdk', 'dgn', 'sbg', 'ngirim', 'minta', 'ngasih tau'",
          "",
          "2. KALIMAT EFEKTIF — Setiap kalimat harus hemat kata, tepat makna, dan tidak ambigu. Hindari kalimat berbelit-belit.",
          "  ✓ Efektif: 'Rapat dilaksanakan pukul 09.00 WIB di aula.'",
          "  ✗ Tidak efektif: 'Rapat nanti itu akan dilaksanakan pada pukul 09.00 WIB kurang lebih dan tempatnya di aula sekolah mungkin ya.'",
          "  Tips: Setelah menulis, baca ulang dan coret kata-kata yang tidak perlu!",
          "",
          "3. ISTILAH KEDINASAN — Gunakan istilah formal yang lazim dalam administrasi perkantoran:",
          "  • 'berdasarkan' — bukan 'menurut' (untuk merujuk dasar hukum)",
          "  • 'menindaklanjuti' — bukan 'nindaklanjutin'",
          "  • 'sehubungan dengan' — bukan 'berhubung'",
          "  • 'dengan ini' — untuk memulai maksud surat",
          "  • 'demikian' — untuk mengakhiri isi surat",
          "  • 'melampirkan' — bukan 'ngasih lampiran'",
          "",
          "4. KATA SAPAAN RESMI — Gunakan sapaan formal: 'Bapak', 'Ibu', 'Saudara', 'Saudari'. Hindari 'Anda' karena terasa kurang formal dalam surat resmi.",
          "  ✓ 'Bapak/Ibu dimohon hadir tepat waktu.'",
          "  ✗ 'Anda dimohon hadir tepat waktu.'",
          "  ✗ 'Kamu diharap hadir tepat waktu.' — terlalu santai!",
          "",
          "5. UNGKAPAN BAKU — Gunakan ungkapan tetap yang sudah lazim dalam surat resmi:",
          "  • 'Dengan hormat,' (salam pembuka)",
          "  • 'Sehubungan dengan...' (alinea pembuka)",
          "  • 'Berdasarkan surat...' (rujukan surat sebelumnya)",
          "  • 'Menindaklanjuti...' (tindak lanjut)",
          "  • 'Bersama ini kami sampaikan...' (menyertakan dokumen)",
          "  • 'Demikian surat ini kami sampaikan.' (penutup)",
          "  • 'Atas perhatian dan kerja samanya, kami ucapkan terima kasih.' (ucapan terima kasih)",
          "",
          "6. PENGGUNAAN KATA GANTI — Dalam surat resmi mewakili instansi, gunakan 'kami'. Hanya jika surat bersifat pribadi tetapi resmi (seperti surat lamaran), gunakan 'saya'.",
          "  ✓ 'Kami mengundang Bapak/Ibu...' (mewakili instansi)",
          "  ✓ 'Saya yang bertanda tangan di bawah ini...' (surat lamaran/surat pernyataan pribadi)",
          "  ✗ 'Aku mengundang kamu...' — salah total!",
          "",
          "7. TIDAK MENGGUNAKAN SINGKATAN TIDAK BAKU — Singkatan yang tidak baku dilarang dalam surat resmi.",
          "  ✓ 'Nomor' — bukan 'No.' (tulis lengkap)",
          "  ✓ 'Jalan' — bukan 'Jl.' (tulis lengkap, kecuali di kop surat)",
          "  ✓ 'Telepon' — bukan 'Telp.' (tulis lengkap)",
          "  ✓ 'Yang terhormat' — ditulis 'Yth.' (ini singkatan baku yang diizinkan)",
          "",
          "PENTING: Perhatikan bahwa 'di' dalam surat resmi harus ditulis sesuai aturan ejaan. 'Di tempat' (pada alamat tujuan) — ditulis terpisah karena menunjukkan lokasi. 'Disampaikan' — digabung karena kata kerja pasif.",
        ],
        contoh: [
          "BENAR: \"Berdasarkan surat edaran Dinas Pendidikan Nomor 421/2026, dengan ini kami sampaikan bahwa seluruh siswa wajib mengikuti kegiatan ujian akhir.\"",
          "SALAH: \"Menurut edaran dinas, semua siswa harus ikut ujian akhir.\" — kata 'menurut' tidak formal, 'semua' sebaiknya 'seluruh', 'harus ikut' sebaiknya 'wajib mengikuti'.",
          "",
          "BENAR: \"Menindaklanjuti surat Saudara tanggal 10 Mei 2026 perihal permohonan izin penelitian, dengan ini kami menyampaikan bahwa permohonan Saudara dapat dikabulkan.\"",
          "SALAH: \"Kami sudah baca surat kamu soal izin penelitian, dan kami kasih izin.\" — terlalu santai, kata 'kamu' tidak sopan.",
          "",
          "BENAR: \"Sehubungan dengan akan dilaksanakannya kegiatan bakti sosial, kami mohon izin untuk menggunakan lapangan sekolah.\"",
          "SALAH: \"Kami mau pinjam lapangan buat acara, ya Pak.\" — tidak resmi, tidak mencantumkan dasar/alasan yang jelas.",
          "",
          "BENAR: \"Atas perhatian Bapak/Ibu, kami ucapkan terima kasih.\"",
          "SALAH: \"Makasih atas perhatiannya, ya.\" — 'makasih' tidak baku, 'ya' tidak sopan.",
        ],
        catatan: "Kesalahan paling umum dalam surat resmi: (1) menggunakan 'kepada Yth.' — seharusnya 'Yth.' saja, (2) menulis 'Jl.' di alamat — seharusnya 'Jalan', (3) menggunakan kata 'saya' untuk surat yang mewakili instansi — seharusnya 'kami', (4) lupa mencantumkan NIP untuk pejabat PNS, (5) tidak memberi koma setelah salam pembuka.",
      },
      {
        judul: "Format Penulisan dan Etika Surat Menyurat",
        isi: [
          "Surat resmi memiliki beberapa bentuk/format penulisan yang menentukan posisi setiap komponen. Selain itu, etika berkorespondensi juga penting untuk diperhatikan.",
          "",
          "A. FORMAT PENULISAN SURAT RESMI",
          "",
          "Ada empat bentuk format yang umum digunakan:",
          "",
          "1. BENTUK LURUS PENUH (FULL BLOCK STYLE) — Semua baris dimulai dari tepi kiri (rata kiri). Tidak ada yang menjorok ke kanan. Termasuk tanggal, salam, dan penutup. Format ini yang paling umum dan praktis.",
          "  ✓ Kop surat rata kiri, tanggal rata kiri, alamat rata kiri, semua rata kiri.",
          "  Kelebihan: rapi, cepat diketik, mudah dibaca.",
          "",
          "2. BENTUK SETENGAH LURUS (SEMI-BLOCK STYLE) — Hampir sama dengan full block, tetapi bagian tertentu (tanggal, salam penutup, nama pengirim) ditulis di sebelah kanan. Alinea isi menjorok ke dalam (indentasi).",
          "  ✓ Kop surat rata tengah, tanggal rata kanan, alamat rata kiri, isi menjorok.",
          "",
          "3. BENTUK LEKUK (INDENTED STYLE) — Setiap baris dalam alamat dan isi menjorok ke dalam (indentasi) secara bertahap. Tanggal dan penutup di kanan. Format tradisional ini sudah jarang dipakai.",
          "  ✓ Alamat diketik dengan indentasi bertingkat, baris kedua menjorok lebih dalam.",
          "",
          "4. BENTUK RESMI INDONESIA (PRESIDENTIAL STYLE) — Variasi yang lazim di instansi pemerintah Indonesia. Kop surat rata tengah, alamat tujuan dan salam pembuka rata kiri, isi menjorok, dan penutup di kanan. Ini adalah gaya yang paling sering dipakai di sekolah dan dinas.",
          "",
          "[Ilustrasi: Tiga format surat ditampilkan berdampingan dalam satu bingkai. Format 1 (Full Block): semua teks rata kiri dengan garis vertikal menunjukkan kerapian. Format 2 (Semi-Block): tanggal di kanan, alinea menjorok. Format 3 (Indented): alamat berundak seperti tangga. Masing-masing diberi label dan panah yang menunjukkan perbedaan posisi elemen.]",
          "",
          "B. ETIKA SURAT MENYURAT",
          "",
          "1. TEPAT WAKTU — Kirim surat sesuai tenggat. Urusan undangan: kirim H-7 (minimal). Surat lamaran: kirim sebelum batas akhir pendaftaran. Surat izin: kirim sebelum atau pada hari kejadian.",
          "",
          "2. SOPAN DAN HORMAT — Gunakan bahasa yang santun. Hindari nada memerintah atau menggurui. Gunakan kata 'mohon', 'silakan', 'terima kasih'.",
          "  ✓ 'Kami mohon kehadiran Bapak/Ibu...'",
          "  ✗ 'Bapak/Ibu harus hadir...'",
          "",
          "3. JELAS DAN SPESIFIK — Jangan membuat penerima bingung. Sebutkan siapa, apa, kapan, di mana, dan mengapa dengan jelas.",
          "  ✓ 'Rapat dilaksanakan pada hari Sabtu, 12 Juni 2026, pukul 09.00 WIB, di Aula Sekolah.'",
          "  ✗ 'Rapat hari Sabtu nanti jam 9 di aula, ya.'",
          "",
          "4. LENGKAP — Pastikan semua komponen surat terisi. Jangan sampai lupa nomor surat, lampiran, atau perihal.",
          "",
          "5. RAPI DAN BERSIH — Surat resmi harus diketik rapi, tidak ada coretan, kertas tidak kusut, dan bebas noda. Gunakan kertas ukuran A4 atau F4 putih.",
          "",
          "C. FORMAT AMPLOP SURAT RESMI",
          "",
          "Penulisan amplop surat resmi juga memiliki aturan:",
          "  • Alamat pengirim: pojok kiri atas amplop, ditulis lengkap dengan nama instansi.",
          "  • Alamat penerima: di tengah amplop, diawali 'Yth.', dilengkapi nama/jabatan dan alamat lengkap.",
          "  • Perangko: ditempatkan di pojok kanan atas.",
          "  • Kode pos: ditulis di pojok kanan bawah amplop (setelah alamat penerima).",
          "  • Baris alamat penerima dimulai dengan nama atau jabatan yang paling spesifik.",
          "",
          "[Ilustrasi: Amplop surat resmi tampak depan. Pojok kiri atas: nama dan alamat pengirim ('SMP Negeri 1 Cimahi, Jl. Merdeka No. 20, Cimahi 40521'). Tengah: 'Yth. Bapak Kepala Dinas Pendidikan dan Kebudayaan / Kabupaten Bandung / Jalan Raya Barat No. 100 / Bandung 40111'. Kanan atas: gambar perangko. Kanan bawah: kode pos '40111'.]",
        ],
        contoh: [
          "=== PERBANDINGAN TIGA FORMAT SURAT ===\n\nFORMA LURUS PENUH (Full Block Style):\n[KOP SURAT — Rata Tengah]\n\nNomor: 001/OSIS/V/2026                         ← rata kiri\nLampiran: —                                          ← rata kiri\nPerihal: Undangan Rapat                            ← rata kiri\n\nYth. Pengurus OSIS                                ← rata kiri\ndi tempat                                              ← rata kiri\n\nDengan hormat,                                     ← rata kiri\n\nSehubungan dengan...                                ← rata kiri\n...                                                       ← rata kiri\n\nHormat kami,                                        ← rata kiri\n\n(Tertanda)                                            ← rata kiri\n\nKetua OSIS                                            ← rata kiri\n\n\nFORMA SETENGAH LURUS (Semi-Block Style):\n[KOP SURAT — Rata Tengah]\n\nNomor: 001/OSIS/V/2026                         ← rata kiri\nLampiran: —                                          ← rata kiri\nPerihal: Undangan Rapat                            ← rata kiri\n\nYth. Pengurus OSIS                                ← rata kiri\ndi tempat                                              ← rata kiri\n\n   Dengan hormat,                                  ← menjorok 5 spasi\n\n   Sehubungan dengan...                           ← menjorok 5 spasi\n   ...                                                      ← menjorok 5 spasi\n\n                                             Hormat kami,   ← rata kanan\n\n                                        (Tertanda)          ← rata kanan\n\n                                        Ketua OSIS          ← rata kanan\n\n\nCONTOH PENULISAN AMPLOP:\n\n+————————————————————————————————————+\n| SMP NEGERI 1 CIMAHI        | PERANGKO |\n| Jl. Merdeka No. 20       |   [Gambar] |\n| Cimahi 40521               |           |\n|                             |           |\n|      Yth. Bapak/Ibu Orang Tua/Wali    |\n|      Murid Kelas IX                    |\n|      SMP Negeri 1 Cimahi              |\n|      Jalan Merdeka No. 20             |\n|      Cimahi                    40521  |\n+————————————————————————————————————+",
        ],
        catatan: "Etika penting lainnya: (1) JANGAN pernah mengirim surat resmi lewat WhatsApp atau media sosial informal — surat resmi harus dikirim secara resmi (pos, kurir, atau email resmi dengan format PDF). (2) Jika mengirim via email, gunakan subjek jelas, lampirkan PDF, dan tulis badan email singkat sebagai pengantar — jangan hanya 'Pls find attached'.",
      },
    ],
    rangkuman: [
      "Surat resmi adalah surat untuk kepentingan kedinasan dengan format baku, bahasa formal, dan aturan ketat.",
      "9 jenis surat resmi: Undangan, Edaran, SK, Tugas, Izin, Lamaran, Pernyataan, Nota Dinas, Notulen.",
      "12 komponen surat resmi: Kop surat, Nomor, Lampiran, Perihal, Alamat tujuan, Salam pembuka, Isi (3 alinea), Salam penutup, Nama/jabatan/tanda tangan, Stempel, Tembusan, Inisial.",
      "Kaidah kebahasaan: bahasa baku EYD V, kalimat efektif, istilah kedinasan, kata sapaan resmi (Bapak/Ibu/Saudara), kata 'kami' untuk instansi, hindari singkatan tidak baku.",
      "Ungkapan baku utama: 'Dengan hormat', 'Sehubungan dengan', 'Berdasarkan', 'Menindaklanjuti', 'Dengan ini', 'Demikian', 'Atas perhatian... terima kasih'.",
      "4 format penulisan: Full Block (rata kiri semua), Semi-Block (tanggal/penutup di kanan), Indented (berundak), Resmi Indonesia (kop tengah + isi menjorok).",
      "Etika surat-menyurat: tepat waktu, sopan, jelas, lengkap, rapi. Amplop: pengirim di kiri atas, penerima di tengah, perangko di kanan atas, kode pos di kanan bawah.",
      "Kesalahan fatal: menggunakan 'saya' untuk surat instansi, menulis 'kepada Yth.', melewatkan stempel, menggunakan singkatan tidak baku, dan bahasa santai.",
    ],
  },

  latihan: makeSoal([
    // 5 Soal Pilihan Ganda (4 opsi)
    ["Surat resmi yang berisi penetapan resmi pejabat berwenang dan memiliki kekuatan hukum disebut...", ["Surat edaran", "Surat undangan", "Surat keputusan (SK)", "Nota dinas"], 2, "Surat Keputusan (SK) adalah surat resmi yang berisi penetapan atau putusan dari pejabat berwenang yang bersifat mengikat dan memiliki kekuatan hukum."],
    ["Bagian surat resmi yang berfungsi untuk pencatatan, pengarsipan, dan penelusuran surat keluar adalah...", ["Perihal", "Nomor surat", "Lampiran", "Tembusan"], 1, "Nomor surat memberikan kode unik pada setiap surat keluar, memudahkan pencatatan dan pencarian arsip di kemudian hari."],
    ["Kata sapaan yang tepat untuk digunakan dalam surat resmi adalah...", ["Kamu dan kau", "Bapak, Ibu, Saudara", "Anda dan mereka", "Dia dan beliau"], 1, "'Bapak', 'Ibu', 'Saudara', dan 'Saudari' adalah kata sapaan resmi yang formal dan sopan. 'Kamu' dan 'kau' terlalu santai untuk surat resmi."],
    ["Penulisan alamat tujuan surat resmi yang BENAR adalah...", ["Kepada Yth. Bapak Kepala Sekolah", "Yth. Bapak Kepala Sekolah", "Kepada Bapak Kepala Sekolah Yth.", "Yth. kepada Bapak Kepala Sekolah"], 1, "Cukup 'Yth.' (Yang terhormat) — tidak perlu 'Kepada' karena 'Yth.' sudah mengandung arti 'kepada yang terhormat'."],
    ["Bagian surat yang berisi informasi tentang jumlah dokumen yang disertakan bersama surat disebut...", ["Perihal", "Lampiran", "Alinea pembuka", "Tembusan"], 1, "Lampiran mencantumkan jumlah atau jenis dokumen/barang yang disertakan. Jika tidak ada, ditulis '—'."],

    // 3 Soal Betul/Salah (2 opsi)
    ["Pernyataan: 'Nota dinas adalah surat resmi yang digunakan untuk komunikasi internal di dalam suatu instansi.'", ["Betul", "Salah"], 0, "BETUL. Nota dinas merupakan surat resmi yang digunakan untuk komunikasi kedinasan di lingkungan internal suatu instansi atau organisasi."],
    ["Pernyataan: 'Dalam surat resmi yang mewakili instansi, kata ganti yang tepat untuk pengirim adalah \"saya\" karena surat ditulis oleh individu.'", ["Betul", "Salah"], 1, "SALAH. Dalam surat yang mewakili instansi, kata ganti yang tepat adalah 'kami'. Kata 'saya' digunakan untuk surat bersifat pribadi seperti surat lamaran pekerjaan."],
    ["Pernyataan: 'Surat edaran ditujukan kepada banyak pihak secara serentak, misalnya pemberitahuan libur nasional.'", ["Betul", "Salah"], 0, "BETUL. Surat edaran bersifat massal — ditujukan ke banyak orang/unit secara serentak, biasanya berisi pemberitahuan atau instruksi resmi."],

    // 2 Soal Isian Singkat (4 opsi)
    ["Singkatan 'SK' pada administrasi surat menyurat berarti...", ["Surat Kabar", "Surat Keputusan", "Surat Keterangan", "Surat Khusus"], 1, "SK adalah singkatan dari Surat Keputusan, yaitu surat yang berisi penetapan resmi oleh pejabat berwenang."],
    ["Komponen surat resmi yang berisi daftar pihak penerima salinan surat disebut...", ["Lampiran", "Inisial", "Tembusan", "Perihal"], 2, "Tembusan berisi daftar pihak yang menerima salinan surat, biasanya ditempatkan di bagian paling bawah surat."],
  ]),

  praktik: {
    petunjuk: "Pilihlah SALAH SATU tugas di bawah ini dan kerjakan dengan lengkap!\n\n=== TUGAS A: Menulis Surat Undangan Resmi ===\nKamu adalah sekretaris OSIS SMP Harapan Bangsa. OSIS akan menyelenggarakan kegiatan \"Seminar Motivasi Belajar\" untuk siswa kelas VIII. Tulis surat undangan resmi kepada Kepala Sekolah untuk:\n1. Memohon izin penggunaan aula sekolah (hari/tanggal, waktu, acara)\n2. Mengundang beliau sebagai pembicara pembuka acara\n3. Memohon dukungan dana dari dana BOS (sebutkan jumlah secara wajar)\n\nKetentuan:\n• Gunakan 12 komponen surat resmi lengkap\n• Format bebas (full block, semi-block, atau resmi Indonesia)\n• Gunakan bahasa baku, kalimat efektif, kata 'kami' (OSIS)\n• Panjang surat minimal 3 paragraf isi\n\n=== TUGAS B: Menulis Surat Lamaran Pekerjaan ===\nKamu adalah lulusan SMA yang akan melamar sebagai staf administrasi di PT Cerdas Bangsa Nusantara, sebuah perusahaan penerbitan buku pendidikan yang beralamat di Jalan Pendidikan No. 45, Yogyakarta 55123. Tulis surat lamaran pekerjaan dengan ketentuan:\n\n1. Gunakan format surat resmi standar (tanpa kop surat — karena kamu melamar sebagai individu)\n2. Cantumkan:\n   a. Sumber informasi lowongan (koran/internet/referensi)\n   b. Pendidikan dan keahlian yang relevan\n   c. Pengalaman organisasi/magang (jika ada)\n   d. Lampiran: CV, ijazah, pas foto, sertifikat\n3. Gunakan kata 'saya' (karena surat lamaran bersifat pribadi)\n4. Bahasa resmi, sopan, dan percaya diri\n\n=== TUGAS C: Mengidentifikasi dan Memperbaiki Surat ===\nBerikut adalah surat yang ditulis oleh seorang siswa. Perbaiki semua kesalahan yang ditemukan!\n\n\"jakarta, 12/5/26\n\nKepada Yth.\nBapak kepala sekolah\nDi smp n 1 jakarta\n\nDengan hormat\n\nKami bermaksud mengadakan acara pensi. Acara ini dilaksanakan pada hari sabtu minggu depan jam 8 pagi. Kami mohon bpk mengizinkan kami pake aula sekolah. Makasih sebelumnya.\n\nWassalam,\n\nOSIS smp n 1 jakarta\"\n\nTulis ulang surat tersebut dengan perbaikan lengkap meliputi:\n• Format tanggal yang benar\n• Perbaikan alamat (Yth. tanpa 'Kepada', kapitalisasi)\n• Koma setelah salam pembuka\n• Bahasa baku dan kalimat efektif\n• Penambahan komponen yang hilang (nomor, lampiran, perihal, dll)\n• Salam penutup yang benar\n• Penambahan nama/jabatan/NIP (buatlah data yang logis)\n\nJawaban ditulis lengkap di kolom yang disediakan!",
    tips: [
      "Untuk Tugas A: buat kop surat OSIS sederhana — misalnya 'OSIS SMP HARAPAN BANGSA / Jalan Pendidikan No. 10 Jakarta / Telp. (021) 7890123'.",
      "Untuk Tugas A: jangan lupa mencantumkan nomor surat, lampiran, dan perihal yang jelas. Format nomor: 001/OSIS/SMP.HB/V/2026.",
      "Untuk Tugas A: gunakan konjungsi formal: 'Sehubungan dengan...', 'Berdasarkan...', 'Mengingat...', 'Demikian...'.",
      "Untuk Tugas B: surat lamaran tidak perlu kop surat. Cukup cantumkan nama, alamat, kontak pengirim di bagian atas (sebagai header), lalu tanggal, perihal, alamat perusahaan, dan isi surat.",
      "Untuk Tugas B: tonjolkan keahlian yang relevan dengan posisi administrasi — misalnya menguasai Microsoft Office, administrasi perkantoran, komunikasi yang baik.",
      "Untuk Tugas C: perhatikan setiap detail — tanggal, kapitalisasi, tanda baca, kata baku, kelengkapan komponen. Setiap kesalahan yang dibiarkan bisa mengurangi nilai!",
      "Periksa kembali: pastikan tidak ada singkatan tidak baku (tdk, dgn, sbg), kata tidak baku (makasih, ngadain), dan kesalahan ejaan.",
    ],
    contoh: "=== CONTOH JAWABAN TUGAS A (Surat Undangan Resmi) ===\n\n[KOP SURAT]\nOSIS SMP HARAPAN BANGSA\nJalan Pendidikan No. 10 Jakarta Pusat 10110\nTelp. (021) 7890123 | Email: osissmphb@sch.id\n—————————————————————\n\nNomor: 001/OSIS/SMP.HB/V/2026\nLampiran: 1 berkas (proposal kegiatan)\nPerihal: Permohonan Izin dan Undangan Seminar Motivasi\n\nYth. Bapak Kepala SMP Harapan Bangsa\ndi tempat\n\nDengan hormat,\n\nSehubungan dengan program kerja OSIS bidang pengembangan diri, kami bermaksud menyelenggarakan kegiatan \"Seminar Motivasi Belajar\" bagi siswa kelas VIII. Kegiatan ini bertujuan untuk meningkatkan semangat belajar dan mempersiapkan siswa menghadapi ujian akhir.\n\nAdapun kegiatan tersebut akan dilaksanakan pada:\n\nHari/Tanggal: Sabtu, 7 Juni 2026\nWaktu: Pukul 08.00 — 12.00 WIB\nTempat: Aula SMP Harapan Bangsa\nPembicara: Kak Farhan Maulana (Motivator Muda Indonesia)\nPeserta: Seluruh siswa kelas VIII (120 orang)\n\nBerdasarkan hal tersebut, kami mohon:\n1. Izin penggunaan aula sekolah pada hari dan waktu tersebut.\n2. Kesediaan Bapak Kepala Sekolah untuk membuka acara dan memberikan sambutan.\n3. Dukungan dana sebesar Rp500.000,00 (lima ratus ribu rupiah) dari dana BOS untuk konsumsi dan perlengkapan seminar.\n\nSebagai bahan pertimbangan, kami lampirkan proposal kegiatan yang berisi rincian acara dan anggaran. Kami sangat berharap Bapak berkenan mengabulkan permohonan kami.\n\nDemikian surat ini kami sampaikan. Atas perhatian dan izin Bapak, kami ucapkan terima kasih.\n\nWassalamualaikum warahmatullahi wabarakatuh.\n\nJakarta, 25 Mei 2026\nKetua OSIS,\n\n(Tertanda)\n\nAhmad Rizki Pratama\nNIS. 2024001\n\nSekretaris OSIS,\n\n(Tertanda)\n\nNadia Safira Putri\nNIS. 2024002\n\n[STEMPEL OSIS SMP HARAPAN BANGSA]\n\nTembusan:\n1. Wakil Kepala Sekolah Bidang Kesiswaan\n2. Arsip OSIS\n\nAR/NS\n\n\n=== CONTOH JAWABAN TUGAS B (Surat Lamaran Pekerjaan) ===\n\nAhmad Rizki Pratama\nJalan Merdeka No. 15, Yogyakarta 55123\nTelepon: 0812-3456-7890\nEmail: ahmad.rizki@email.com\n\nYogyakarta, 25 Mei 2026\n\nPerihal: Lamaran Pekerjaan Staf Administrasi\n\nYth. Bapak/Ibu Manajer HRD\nPT Cerdas Bangsa Nusantara\nJalan Pendidikan No. 45\nYogyakarta 55123\n\nDengan hormat,\n\nBerdasarkan informasi lowongan pekerjaan yang saya peroleh dari portal karir JobStreet pada tanggal 20 Mei 2026, saya bermaksud melamar posisi Staf Administrasi di PT Cerdas Bangsa Nusantara.\n\nSaya adalah lulusan SMA Negeri 3 Yogyakarta jurusan Ilmu Pengetahuan Sosial tahun 2025. Selama bersekolah, saya aktif dalam organisasi OSIS sebagai sekretaris selama dua tahun, yang membekali saya dengan kemampuan administrasi, pengarsipan, dan komunikasi yang baik. Saya juga menguasai Microsoft Office (Word, Excel, PowerPoint) dan memiliki pengalaman magang di bagian administrasi Kantor Kelurahan Gondokusuman selama tiga bulan.\n\nSaya memiliki kepribadian yang teliti, disiplin, dan mudah belajar hal baru. Saya yakin dapat memberikan kontribusi yang positif bagi PT Cerdas Bangsa Nusantara.\n\nSebagai bahan pertimbangan, saya lampirkan dokumen berikut:\n1. Daftar riwayat hidup (CV)\n2. Fotokopi ijazah dan transkrip nilai\n3. Pas foto 3×4 (dua lembar)\n4. Sertifikat organisasi dan magang\n\nBesar harapan saya untuk dapat mengikuti proses seleksi lebih lanjut. Atas perhatian Bapak/Ibu, saya ucapkan terima kasih.\n\nHormat saya,\n\n(Tertanda)\n\nAhmad Rizki Pratama\n\n\n=== CONTOH JAWABAN TUGAS C (Perbaikan Surat) ===\n\nSURAT ASLI (dengan kesalahan):\n\"jakarta, 12/5/26\n\nKepada Yth.\nBapak kepala sekolah\nDi smp n 1 jakarta\n\nDengan hormat\n\nKami bermaksud mengadakan acara pensi. Acara ini dilaksanakan pada hari sabtu minggu depan jam 8 pagi. Kami mohon bpk mengizinkan kami pake aula sekolah. Makasih sebelumnya.\n\nWassalam,\n\nOSIS smp n 1 jakarta\"\n\nDAFTAR KESALAHAN:\n1. 'jakarta' → harus kapital 'Jakarta'\n2. Tanggal '12/5/26' → harus 'Jakarta, 12 Mei 2026'\n3. 'Kepada Yth.' → cukup 'Yth.'\n4. 'Bapak kepala sekolah' → 'Bapak Kepala Sekolah' (kapital)\n5. 'Di smp n 1 jakarta' → 'di SMP Negeri 1 Jakarta'\n6. 'Dengan hormat' → harus diakhiri koma: 'Dengan hormat,'\n7. 'mengadakan' → lebih formal: 'menyelenggarakan'\n8. 'pensi' → 'pentas seni' (lengkap, tidak disingkat)\n9. 'hari sabtu' → 'hari Sabtu' (kapital nama hari)\n10. 'minggu depan jam 8 pagi' → harus spesifik: 'pada hari Sabtu, 17 Mei 2026, pukul 08.00 WIB'\n11. 'bpk' → 'Bapak' (tidak disingkat)\n12. 'pake' → 'menggunakan' atau 'meminjam'\n13. 'Makasih' → 'Terima kasih' (baku)\n14. 'Wassalam,' → 'Wassalamualaikum warahmatullahi wabarakatuh,' (lengkap)\n15. 'OSIS smp n 1 jakarta' → 'OSIS SMP Negeri 1 Jakarta'\n16. Tidak ada nomor surat, lampiran, perihal, nama jelas, dan stempel\n\nSURAT HASIL PERBAIKAN:\n\n[KOP SURAT]\nOSIS SMP NEGERI 1 JAKARTA\nJalan Merdeka No. 10 Jakarta Pusat 10110\nTelp. (021) 7890123\n—————————————————————\n\nNomor: 012/OSIS/SMP.1/V/2026\nLampiran: —\nPerihal: Permohonan Izin Kegiatan Pentas Seni\n\nYth. Bapak Kepala SMP Negeri 1 Jakarta\ndi tempat\n\nDengan hormat,\n\nDalam rangka memperingati Hari Pendidikan Nasional, kami bermaksud menyelenggarakan kegiatan pentas seni yang akan dilaksanakan pada:\n\nHari/Tanggal: Sabtu, 17 Mei 2026\nWaktu: Pukul 08.00 — 12.00 WIB\nTempat: Aula SMP Negeri 1 Jakarta\n\nKegiatan ini bertujuan untuk mengembangkan bakat dan kreativitas siswa di bidang seni. Sehubungan dengan hal tersebut, kami mohon izin Bapak Kepala Sekolah untuk menggunakan aula sekolah sebagai tempat penyelenggaraan kegiatan.\n\nDemikian permohonan ini kami sampaikan. Atas perhatian dan izin Bapak, kami ucapkan terima kasih.\n\nWassalamualaikum warahmatullahi wabarakatuh.\n\nJakarta, 12 Mei 2026\nKetua OSIS,\n\n(Tertanda)\n\nBudi Santoso\nNIS. 2023001\n\n[STEMPEL OSIS SMP NEGERI 1 JAKARTA]",
  },

  kuis: makeSoal([
    ["Perbedaan paling mendasar antara surat resmi dan surat pribadi terletak pada...", ["Jumlah paragraf", "Tujuan dan kepentingan penulisan", "Panjang surat", "Warna kertas"], 1, "Tujuan penulisan adalah perbedaan paling mendasar: surat resmi untuk kepentingan kedinasan, surat pribadi untuk keperluan personal."],
    ["Fungsi tembusan dalam surat resmi adalah...", ["Menunjukkan nomor urut surat", "Memberitahu pihak lain yang menerima salinan surat", "Menandai jenis surat yang dikirim", "Sebagai pengganti stempel"], 1, "Tembusan berfungsi untuk menginformasikan pihak-pihak yang menerima salinan/tembusan surat sebagai arsip atau pemberitahuan."],
    ["Bentuk surat di mana semua baris dimulai dari tepi kiri (rata kiri) disebut...", ["Semi-block style", "Full block style", "Indented style", "Resmi Indonesia"], 1, "Full block style adalah format surat di mana semua baris — termasuk tanggal, salam, dan penutup — dimulai dari tepi kiri (rata kiri)."],
    ["Manakah penulisan tanggal surat resmi yang BENAR?", ["Jakarta, 12/05/2026", "Jakarta, 12-5-2026", "Jakarta, 12 Mei 2026", "Jakarta 12 Mei 2026"], 2, "Tanggal surat resmi ditulis: 'Jakarta, 12 Mei 2026' — nama bulan ditulis lengkap dengan huruf, diikuti koma setelah kota. Tidak menggunakan garis miring atau strip."],
    ["Surat yang berisi komunikasi internal di dalam instansi dan bersifat lebih ringkas disebut...", ["Surat edaran", "Surat keputusan", "Nota dinas", "Notulen"], 2, "Nota dinas adalah surat resmi untuk komunikasi internal di dalam satu instansi. Biasanya lebih ringkas dari surat resmi biasa."],
    ["Dalam surat resmi, kata 'berdasarkan' digunakan untuk...", ["Menanyakan kabar penerima", "Merujuk pada dasar hukum atau surat sebelumnya", "Mengakhiri isi surat", "Menyapa penerima surat"], 1, "Kata 'berdasarkan' digunakan untuk merujuk pada landasan hukum, surat sebelumnya, atau acuan yang menjadi dasar penulisan surat."],
    ["Komponen yang membedakan surat resmi dengan surat pribadi adalah...", ["Tanggal dan salam", "Kop surat, nomor, stempel", "Nama pengirim dan alamat", "Isi dan penutup"], 1, "Kop surat, nomor surat, stempel, dan perihal adalah komponen yang hanya ada di surat resmi dan tidak ada di surat pribadi."],
    ["Penulisan inisial 'AR/NS' pada surat resmi berarti...", ["Ahmad Rizki dan Nadia Safira — dua orang penandatangan", "Ahmad Rizki (konseptor) dan Nadia Safira (pengetik)", "Arsip / Nomor Surat", "Atas perhatian / Nama Surat"], 1, "Inisial menunjukkan konseptor dan pengetik surat. AR = Ahmad Rizki (konseptor), NS = Nadia Safira (pengetik)."],
    ["Surat lamaran pekerjaan termasuk surat resmi yang menggunakan kata ganti...", ["Kami", "Aku", "Saya", "Kita"], 2, "Surat lamaran bersifat pribadi tetapi resmi — menggunakan 'saya' karena pelamar bertindak sebagai individu, bukan mewakili instansi."],
    ["Kesalahan penulisan alamat surat yang paling sering terjadi adalah...", ["Mencantumkan 'Yth.' saja", "Menulis lengkap nama dan jabatan", "Menulis 'Kepada Yth.' secara bersamaan", "Menulis alamat tanpa kode pos"], 2, "Kesalahan sangat umum: 'Kepada Yth.' — seharusnya cukup 'Yth.' karena 'Yth.' sudah berarti 'Yang terhormat'. Menambahkan 'Kepada' menjadi berlebihan."],
  ]),
}

export default konten
