import type { Konten } from "../types"
import { makeSoal } from "../types"

const konten: Konten = {
  belajar: {
    tujuan: [
      "Memahami pengertian, tujuan, dan fungsi teks tanggapan sebagai respons terhadap isu/peristiwa",
      "Mengidentifikasi struktur teks tanggapan: konteks, deskripsi, penilaian",
      "Membedakan jenis-jenis tanggapan: pujian, kritik, saran, dan komentar netral",
      "Menganalisis kaidah kebahasaan teks tanggapan: kalimat opini, konjungsi pertentangan dan kausal",
      "Menerapkan etika memberi tanggapan yang santun, logis, dan membangun dalam kehidupan sehari-hari",
    ],
    materi: [
      {
        judul: "Apa Itu Teks Tanggapan?",
        isi: [
          "Pernahkah kamu melihat postingan teman di media sosial lalu memberikan komentar? Atau mungkin kamu pernah diminta memberikan pendapat tentang pidato ketua OSIS di sekolah? Setiap kali kita merespons sesuatu dengan disertai alasan — itulah yang disebut tanggapan.",
          "",
          "Teks tanggapan adalah teks yang berisi tanggapan — berupa kritik, pujian, komentar, atau saran — terhadap suatu isu, karya, peristiwa, atau pendapat, yang disertai alasan yang logis. Bedakan dengan sekadar berkomentar tanpa dasar! Teks tanggapan selalu MENYERTAKAN ALASAN dan BERSIFAT MEMBANGUN.",
          "",
          "[Ilustrasi: Gelembung percakapan berurutan menunjukkan alur memberi tanggapan: (1) Konteks — mengamati isu, (2) Deskripsi — menggambarkan situasi, (3) Penilaian — menilai dengan alasan, (4) Saran — menawarkan solusi. Setiap gelembung terhubung dengan panah urut.]",
          "",
          "• Tujuan teks tanggapan:",
          "  • Memberikan penilaian yang objektif terhadap suatu isu atau peristiwa",
          "  • Menyampaikan kritik yang membangun, bukan menjatuhkan",
          "  • Memberikan pujian yang spesifik dan beralasan",
          "  • Menawarkan saran perbaikan yang konkret",
          "  • Melatih kemampuan berpikir kritis dan menyampaikan pendapat secara santun",
          "",
          "PENTING: Teks tanggapan berbeda dengan teks ulasan! Ulasan (resensi) FOKUS pada MENGULAS KARYA (buku, film, lagu, drama), sedangkan tanggapan FOKUS pada MERESPONS ISU, PERISTIWA, ATAU PENDAPAT. Ulasan bersifat analitis-estetis, tanggapan bersifat responsif-argumentatif.",
        ],
        contoh: [
          "Contoh teks tanggapan (merespons isu):",
          "\"Kebijakan sekolah mewajibkan semua siswa menyimpan ponsel di loker selama jam pelajaran mulai diterapkan pekan ini. Kebijakan ini bertujuan mengurangi gangguan belajar akibat penggunaan ponsel di kelas. Menurut saya, kebijakan ini cukup tepat sasaran karena berdasarkan data sekolah, nilai rata-rata siswa meningkat 12% di sekolah lain yang menerapkan aturan serupa. Namun, sekolah sebaiknya menyediakan loker yang lebih banyak karena saat ini jumlah loker hanya 200 unit, sementara jumlah siswa mencapai 800 orang. Selain itu, guru juga perlu lebih aktif mengawasi agar kebijakan berjalan efektif.\"",
          "",
          "Bandingkan dengan teks ulasan (mengulas karya):",
          "\"Novel 'Bumi Manusia' karya Pramoedya Ananta Toer mengisahkan perjuangan Minke, seorang pribumi terdidik di era kolonial. Novel ini menggunakan alur campuran dengan sudut pandang orang pertama. Kelebihan novel ini terletak pada penggambaran latar sejarah yang detail dan konflik batin tokoh yang kuat. Kekurangannya, beberapa bagian terasa lambat karena deskripsi yang terlalu panjang.\"",
          "",
          "BENAR: Teks tanggapan merespons KEBIJAKAN (isu) dengan alasan logis dan saran konkret.",
          "SALAH: Teks tanggapan yang hanya berisi 'Bagus deh, setuju!' atau 'Nggak setuju ah, jelek' — tanpa alasan sama sekali.",
        ],
        catatan: "Ingat perbedaan simpel: ULASAN = ngomongin KARYA (buku, film, lagu). TANGGAPAN = ngomongin ISU (kebijakan, peristiwa, opini, masalah sehari-hari). Tapi keduanya sama-sama harus disertai ALASAN!",
      },
      {
        judul: "Struktur dan Jenis Teks Tanggapan",
        isi: [
          "Teks tanggapan yang baik memiliki struktur yang jelas. Ada tiga bagian utama yang harus kamu pahami: KONTEKS, DESKRIPSI, dan PENILAIAN. Yuk, kita bedah!",
          "",
          "1. KONTEKS — Bagian pembuka yang memperkenalkan isu, peristiwa, atau hal yang akan ditanggapi. Pembaca perlu tahu APA yang sedang dibahas sebelum membaca tanggapanmu.",
          "  • Letaknya di awal teks",
          "  • Berisi informasi latar belakang secara singkat dan jelas",
          "  • Bersifat netral — belum berisi penilaian",
          "  ✓ 'SMP Harapan Bangsa baru saja mengumumkan kebijakan larangan membawa motor ke sekolah bagi siswa kelas VII dan VIII.'",
          "  ✓ 'Video pidato ketua OSIS yang mempromosikan program 'Jumat Bersih' viral di media sosial sekolah.'",
          "  ✗ Langsung mengkritik tanpa menjelaskan isunya",
          "",
          "2. DESKRIPSI — Bagian yang menggambarkan isu secara singkat dan objektif. Fungsinya membantu pembaca memahami isu dari berbagai sisi sebelum membaca penilaianmu.",
          "  • Paparkan fakta-fakta penting terkait isu",
          "  • Sampaikan secara netral, jangan campur opini di sini",
          "  • Bisa berisi data, kronologi, atau kutipan terkait",
          "  ✓ 'Kebijakan ini melarang siswa kelas VII dan VIII membawa kendaraan bermotor ke sekolah. Menurut data kesiswaan, terdapat 45 siswa yang selama ini naik motor ke sekolah. Pihak sekolah menyediakan layanan antar-jemput gratis sebagai alternatif.'",
          "  ✗ Deskripsi yang sudah berisi opini: 'Kebijakan ini sangat tidak adil karena siswa kelas VII dan VIII jadi susah...'",
          "",
          "3. PENILAIAN — Bagian inti yang berisi tanggapan: setuju/tidak setuju, pujian/kritik, disertai ALASAN yang logis. Bisa ditambah SARAN untuk perbaikan.",
          "  • Sampaikan pendapatmu dengan jelas",
          "  • Berikan ALASAN — jangan hanya mengatakan 'bagus' atau 'jelek'",
          "  • Sertakan saran jika perlu",
          "  ✓ 'Menurut saya, kebijakan ini sudah tepat karena melatih kemandirian siswa. Namun, alangkah lebih baik jika sekolah juga menyediakan jalur khusus untuk bersepeda agar siswa yang tinggal dekat tetap bisa ke sekolah dengan aman.'",
          "  ✗ 'Saya tidak setuju. Itu tidak adil.' (tanpa alasan)",
          "",
          "Tips mengingat: K-D-P (Konteks, Deskripsi, Penilaian). Bayangkan seperti MEMOTRET: konteks adalah memilih objek foto, deskripsi adalah mengatur fokus, penilaian adalah memberikan caption!",
          "",
          "[Ilustrasi: Timbangan keseimbangan dengan 'Kritik' di satu sisi dan 'Pujian' di sisi lain. Kedua sisi memiliki pemberat bertuliskan 'Alasan Logis' — menunjukkan bahwa kritik maupun pujian sama-sama harus didasari alasan. Di bawah timbangan tertulis kriteria: Spesifik, Sopan, Membangun.]",
          "",
          "Jenis-jenis tanggapan yang perlu kamu kenali:",
          "",
          "• PUJIAN — Menyatakan kebaikan/kelebihan sesuatu. Harus spesifik dan beralasan, bukan sekadar 'bagus'.",
          "  ✓ 'Saya sangat mengapresiasi program Jumat Bersih karena melibatkan seluruh warga sekolah secara aktif, bukan hanya petugas kebersihan. Program ini menanamkan rasa tanggung jawab pada siswa.'",
          "  ✗ 'Bagus banget deh programnya!' (tidak spesifik, tidak beralasan)",
          "",
          "• KRITIK — Menyatakan kekurangan/kelemahan dengan bahasa yang sopan dan membangun. Fokus pada MASALAH, bukan ORANG.",
          "  ✓ 'Pelaksanaan program Jumat Bersih masih kurang maksimal karena waktu yang disediakan hanya 15 menit. Sebaiknya durasi ditambah menjadi 30 menit agar area yang dibersihkan lebih luas.'",
          "  ✗ 'Programnya gagal total karena anak-anak malas. Dasar tidak disiplin!' (menyerang pribadi, tidak membangun)",
          "",
          "• SARAN — Memberikan solusi atau usulan perbaikan secara konkret. Saran yang baik bersifat spesifik dan dapat dilaksanakan.",
          "  ✓ 'Saya menyarankan agar sekolah membagi area kebersihan per kelas dan menyediakan alat kebersihan yang memadai di setiap area.'",
          "  ✗ 'Ya pokoknya diperbaiki dong.' (tidak jelas, tidak konkret)",
          "",
          "• KOMENTAR NETRAL — Analisis tanpa memihak, menyampaikan pro dan kontra secara berimbang.",
          "  ✓ 'Kebijakan ini memiliki dua sisi. Di satu sisi, melatih kemandirian siswa. Di sisi lain, siswa yang tinggal jauh butuh waktu lebih lama ke sekolah dengan angkutan umum. Perlu dicari solusi tengah yang mengakomodasi kedua kepentingan.'",
          "",
          "PENTING: Satu teks tanggapan bisa menggabungkan BEBERAPA jenis sekaligus. Misalnya: pujian dulu atas niat baiknya, lalu kritik pada pelaksanaannya, lalu saran untuk perbaikannya. Kombinasi ini menunjukkan kematangan berpikir!",
        ],
        contoh: [
          "BENAR (struktur lengkap + pujian, kritik, saran):",
          "Konteks: 'SMP Nusantara menerapkan program Kantin Jujur sejak Januari 2025 — siswa membayar sendiri makanan yang diambil tanpa ada penjaga.'",
          "Deskripsi: 'Dalam program ini, setiap makanan diberi label harga. Siswa mengambil makanan dan memasukkan uang ke kotak yang tersedia. Program ini bertujuan melatih kejujuran dan kemandirian siswa.'",
          "Penilaian: 'Menurut saya, program Kantin Jujur adalah ide yang sangat baik (pujian). Melatih kejujuran sejak dini sangat penting untuk pembentukan karakter siswa. Namun, pelaksanaannya masih perlu dievaluasi (kritik). Dalam dua bulan terakhir, terdapat selisih antara jumlah makanan yang terambil dan uang yang terkumpul hingga 35%. Artinya, masih banyak siswa yang belum jujur. Saya menyarankan sekolah mengadakan sesi refleksi mingguan bersama siswa untuk membahas pentingnya kejujuran, bukan sekadar menambah pengawasan (saran). Dengan pendekatan edukatif, kesadaran siswa akan tumbuh dari dalam diri.'",
          "",
          "SALAH: 'Program Kantin Jujur itu jelek. Banyak siswa yang curang. Harusnya dihapus aja.' (Tidak ada konteks, tidak ada deskripsi, kritik tanpa alasan dan solusi.)",
        ],
        catatan: "Latihan sederhana: Ambil satu isu di sekolahmu. Tulis tanggapan menggunakan struktur K-D-P dengan kombinasi pujian + kritik + saran. Pastikan setiap bagian memiliki alasan yang logis!",
      },
      {
        judul: "Ciri Kebahasaan dan Etika Memberi Tanggapan",
        isi: [
          "Teks tanggapan memiliki ciri bahasa yang khas. Kuasai kaidah ini agar tanggapanmu berbobot, santun, dan meyakinkan!",
          "",
          "1. KALIMAT OPINI — Kalimat yang menyatakan pendapat, keyakinan, atau pandangan pribadi. Inilah 'jiwa' dari teks tanggapan.",
          "  Ungkapan pembuka opini: menurut saya, saya berpendapat, saya setuju, saya rasa, dari sudut pandang saya",
          "  ✓ 'Menurut saya, program literasi sekolah perlu didukung oleh semua pihak.'",
          "  ✓ 'Saya berpendapat bahwa hukuman fisik tidak efektif untuk mendidik siswa.'",
          "  ✗ 'Program ini jelek.' (opini tanpa ungkapan pembuka yang santun)",
          "",
          "2. KONJUNGSI PERTENTANGAN — Kata hubung yang menyatakan hubungan berlawanan. Penting untuk menunjukkan bahwa kamu melihat isu dari berbagai sisi.",
          "  Contoh: meskipun, tetapi, namun, sebaliknya, walaupun, kendati demikian",
          "  ✓ 'Kebijakan ini bertujuan baik. Namun, pelaksanaannya masih perlu dievaluasi.'",
          "  ✓ 'Meskipun program ini sudah berjalan setahun, dampaknya belum terlihat signifikan.'",
          "",
          "3. KONJUNGSI KAUSAL — Kata hubung yang menyatakan hubungan sebab-akibat. Membantu menjelaskan ALASAN di balik tanggapanmu.",
          "  Contoh: karena, sebab, oleh karena itu, dengan demikian, sehingga, akibatnya",
          "  ✓ 'Saya mendukung kebijakan ini karena melatih kedisiplinan siswa.'",
          "  ✓ 'Oleh karena itu, diperlukan sosialisasi ulang agar semua siswa memahami aturan baru ini.'",
          "",
          "4. KATA SIFAT OPINI — Kata sifat yang bersifat evaluatif, digunakan untuk menilai atau mengapresiasi sesuatu.",
          "  Contoh: baik, buruk, menarik, kurang tepat, efektif, tidak efisien, membangun, positif, Negatif, bermanfaat, merugikan",
          "  ✓ 'Pendekatan ini sangat efektif untuk meningkatkan kesadaran siswa.'",
          "  ✓ 'Sayangnya, cara penyampaiannya kurang tepat sehingga menimbulkan kesalahpahaman.'",
          "",
          "5. KALIMAT SARAN — Kalimat yang memberikan usulan atau rekomendasi. Biasanya menggunakan kata: sebaiknya, seharusnya, disarankan, alangkah baiknya, perlu.",
          "  ✓ 'Sebaiknya sekolah menyediakan lebih banyak tempat sampah terpisah.'",
          "  ✓ 'Disarankan agar program ini dievaluasi setiap tiga bulan sekali.'",
          "  ✓ 'Alangkah baiknya jika guru juga memberikan contoh langsung dalam program ini.'",
          "",
          "[Ilustrasi: Dua contoh respons terhadap isu yang sama: (1) RESPONS EMOSIONAL — gelembung merah dengan tulisan besar 'INI SIH KETERLALUAN! DASAR GURU NGGAK PUNYA HATI' — diberi tanda X. (2) RESPONS KONSTRUKTIF — gelembung hijau dengan 'Menurut saya, kebijakan ini kurang tepat karena... Saran saya...' — diberi tanda ✓. Di bawahnya tertulis: Isu sama, cara beda.]",
          "",
          "ETIKA MEMBERI TANGGAPAN — Ini sangat penting! Tanggapan yang baik tidak hanya benar secara isi, tetapi juga santun secara penyampaian.",
          "",
          "• Kritik yang membangun: FOKUS pada MASALAH, BUKAN ORANG. Bedakan antara 'tulisannya kurang terstruktur' (fokus pada karya) dan 'penulisnya tidak becus' (fokus pada orang).",
          "  ✓ 'Argumentasi dalam pidato ini masih lemah karena tidak didukung data yang kuat.'",
          "  ✗ 'Pembicaraannya tidak masuk akal, siapa yang mau dengerin?'",
          "",
          "• Gunakan BAHASA SANTUN. Pilih kata yang sopan meskipun kamu tidak setuju. Ingat: berbeda pendapat itu wajar!",
          "  ✓ 'Maaf, saya kurang sependapat dengan pandangan tersebut. Menurut saya...'",
          "  ✗ 'Kamu salah besar! Pendapatmu ngawur!'",
          "",
          "• Berikan ALASAN, bukan sekadar 'bagus' atau 'jelek'. Jika memuji, jelaskan APA yang baik dan MENGAPA. Jika mengkritik, jelaskan APA yang kurang dan USULKAN perbaikannya.",
          "  ✓ 'Tulisan ini sangat menarik karena menggunakan data terkini dari sumber terpercaya.'",
          "  ✗ 'Keren! Suka banget!'",
          "",
          "• Akui KELEBIHAN, jangan hanya kekurangan. Tanggapan yang seimbang menunjukkan bahwa kamu objektif dan tidak bias.",
          "  ✓ 'Meskipun penyampaiannya kurang lancar, isi pidatonya sangat berbobot dan relevan dengan kondisi siswa saat ini.'",
          "  ✗ 'Pidatonya jelek, grogi terus.'",
          "",
          "• Berbeda pendapat itu WAJAR — sampaikan dengan SOPAN. Dunia tidak hitam-putih. Perbedaan pendapat adalah kekayaan berpikir, selama disampaikan dengan santun.",
          "  ✓ 'Saya menghargai pendapat Anda, tetapi izinkan saya menyampaikan sudut pandang yang berbeda.'",
          "  ✗ 'Pendapatmu salah. Yang benar versiku.'",
          "",
          "Tips praktis: SEBELUM menulis tanggapan, tanyakan pada diri sendiri — 'Apakah yang akan saya tulis ini MEMBANTU atau MENYAKITI? Apakah ada ALASAN di balik pendapat saya?' Jika jawabannya membantu dan beralasan → tulis!",
        ],
        contoh: [
          "Perhatikan perbedaan penggunaan bahasa berikut pada isu yang SAMA:",
          "",
          "Isu: 'Seorang teman mengirim tugas kelompok di WhatsApp pukul 23.00 — beberapa anggota grup sudah tidur dan tidak membalas.'",
          "",
          "TANGGAPAN KURANG TEPAT (emosional, tidak sopan, tidak membangun):",
          "\"Dasar nggak peka! Ngirim tugas jam 11 malam, mana bisa dibales? Emang lo doang yang sibuk? Yang lain juga punya kehidupan! Tolong punya otak dong kalau ngirim pesan lihat jam!\"",
          "",
          "TANGGAPAN TEPAT (sopan, membangun, beralasan):",
          "\"Menurut saya, akan lebih baik jika tugas kelompok dikirim sebelum pukul 20.00 agar semua anggota masih sempat melihat dan merespons. Saya memahami mungkin ada kesibukan, tetapi dengan mengirim lebih awal, kita bisa menghindari keterlambatan respons. Bagaimana kalau kita sepakati batas waktu pengiriman tugas kelompok maksimal pukul 19.00 ke depannya?\"",
          "",
          "BENAR: Fokus pada solusi, menggunakan 'menurut saya', 'akan lebih baik', memberi saran konkret, bahasa santun.",
          "SALAH: Menyerang pribadi ('dasar nggak peka'), penuh emosi, tidak ada solusi, bahasa kasar.",
        ],
        catatan: "Etika ini bukan hanya untuk teks tanggapan di buku tugas! Terapkan dalam kehidupan sehari-hari — saat komen di medsos, diskusi di grup WA, atau menyampaikan pendapat di kelas. Orang akan lebih menghargai pendapatmu jika kamu menyampaikannya dengan santun dan logis.",
      },
      {
        judul: "Cara Menulis Teks Tanggapan yang Baik",
        isi: [
          "Menulis teks tanggapan yang baik adalah keterampilan yang bisa dipelajari. Ikuti panduan langkah demi langkah berikut!",
          "",
          "1. AMATI ISU SECARA CERMAT",
          "  Sebelum memberi tanggapan, pahami dulu isu atau peristiwa yang akan ditanggapi. Jangan 'baca judulnya doang lalu komentar'!",
          "  • Kumpulkan informasi dari berbagai sumber",
          "  • Catat fakta-fakta penting",
          "  • Pahami konteks dan latar belakang isu",
          "  • Identifikasi pihak-pihak yang terlibat dan terdampak",
          "",
          "2. KUMPULKAN FAKTA DAN DATA",
          "  Tanggapan yang baik didukung data, bukan sekadar perasaan. Data membuat argumenmu lebih kuat dan kredibel.",
          "  • Cari data pendukung: angka, persentase, kronologi, kebijakan terkait",
          "  • Catat kutipan relevan dari sumber terpercaya",
          "  • Jika tidak ada data resmi, gunakan pengamatan atau pengalaman pribadi yang relevan",
          "",
          "3. RUMUSKAN PENDAPATMU",
          "  Tentukan posisimu: setuju, tidak setuju, atau netral? Identifikasi kelebihan dan kekurangan isu tersebut.",
          "  • Tulis poin-poin pujian (jika ada) — spesifik dan beralasan",
          "  • Tulis poin-poin kritik (jika ada) — sopan dan membangun",
          "  • Siapkan saran perbaikan — konkret dan realistis",
          "",
          "4. TULIS DENGAN STRUKTUR K-D-P",
          "  Kembangkan tulisanmu mengikuti struktur Konteks → Deskripsi → Penilaian.",
          "  • Konteks: 1—2 kalimat pengantar isu",
          "  • Deskripsi: 2—4 kalimat pemaparan fakta",
          "  • Penilaian: 3—5 kalimat berisi pujian/kritik/saran + alasan",
          "",
          "5. GUNAKAN BAHASA YANG SANTUN DAN LOGIS",
          "  Pilih kata-kata yang sopan. Gunakan konjungsi pertentangan dan kausal untuk memperkuat alasan.",
          "  ✓ 'Menurut saya...', 'Saya berpendapat...', 'Disarankan...', 'Sebaiknya...'",
          "  ✗ 'Pasti salah', 'Gak guna', 'Mending dihapus aja'",
          "",
          "6. REVISI SEBELUM MEMUBLIKASIKAN",
          "  Baca ulang tanggapanmu. Cek: apakah sudah sesuai struktur? Apakah alasan sudah logis? Apakah bahasanya santun? Apakah ada saran yang konkret?",
          "  • Minta teman membaca untuk mendapatkan perspektif baru",
          "  • Perbaiki kata-kata yang mungkin terasa kasar",
          "  • Pastikan tanggapanmu MEMBANTU, bukan MENYAKITI",
          "",
          "PENTING: Tanggapan yang baik BUKAN tentang MENANG ARGUMEN, melainkan tentang MEMBANTU memperbaiki keadaan. Fokus pada tujuan membangun, bukan menjatuhkan. Kritis itu boleh, asal tetap sopan dan logis!",
        ],
        contoh: [
          "CONTOH LENGKAP: Menanggapi Isu 'Siswa Dilarang Membawa Motor ke Sekolah'",
          "",
          "Konteks:",
          "SMP Harapan Bangsa mengeluarkan kebijakan baru yang melarang siswa kelas VII dan VIII membawa sepeda motor ke sekolah mulai semester depan. Kebijakan ini diumumkan melalui surat edaran yang dibagikan dua pekan lalu.",
          "",
          "Deskripsi:",
          "Berdasarkan data kesiswaan, terdapat 45 siswa kelas VII dan VIII yang selama ini menggunakan motor pribadi ke sekolah. Alasan pihak sekolah adalah keselamatan siswa — mengingat usia mereka yang masih di bawah 17 tahun dan belum memiliki SIM. Sebagai alternatif, sekolah menyediakan layanan antar-jemput gratis dengan dua unit mobil sekolah yang beroperasi setiap pagi dan sore.",
          "",
          "Penilaian:",
          "Menurut saya, kebijakan ini sudah tepat sasaran. Keselamatan siswa adalah prioritas utama yang tidak bisa ditawar. Data kecelakaan lalu lintas yang melibatkan pelajar di kota kita meningkat 20% tahun ini — melarang siswa membawa motor adalah langkah preventif yang bijaksana. Sekolah juga sudah menyediakan solusi alternatif berupa antar-jemput gratis, sehingga siswa tidak kehilangan akses transportasi.",
          "",
          "Namun, saya perhatikan bahwa kapasitas antar-jemput sekolah hanya 2 mobil — cukup untuk 16 siswa. Padahal ada 45 siswa yang terdampak. Artinya, 29 siswa lainnya belum terakomodasi. Sebaiknya sekolah bekerja sama dengan operator angkutan umum sekitar atau menyediakan tambahan armada agar tidak ada siswa yang kesulitan. Selain itu, sosialisasi kebijakan perlu diperkuat — masih banyak orang tua yang belum memahami alasan di balik larangan ini.",
          "",
          "Kesimpulannya, saya mendukung kebijakan ini karena mendahulukan keselamatan, tetapi pelaksanaannya perlu diperbaiki agar semua siswa yang terdampak mendapatkan solusi transportasi yang memadai.",
        ],
        catatan: "Perhatikan contoh di atas: konteks jelas, deskripsi faktual, penilaian berisi pujian (tepat sasaran) + kritik (kapasitas kurang) + saran (tambah armada, sosialisasi). Semua disertai alasan logis. Inilah ciri teks tanggapan yang baik!",
      },
    ],
    rangkuman: [
      "Teks tanggapan adalah teks yang berisi kritik, pujian, komentar, atau saran terhadap suatu isu/peristiwa disertai alasan logis.",
      "Berbeda dengan ulasan: ulasan fokus mengulas karya, tanggapan fokus merespons isu/pendapat/peristiwa.",
      "Struktur teks tanggapan: Konteks (memperkenalkan isu) → Deskripsi (menggambarkan isu secara objektif) → Penilaian (tanggapan + alasan).",
      "Jenis tanggapan: pujian (spesifik-beralasan), kritik (sopan-membangun), saran (konkret-realistis), komentar netral (berimbang).",
      "Ciri kebahasaan: kalimat opini (menurut saya), konjungsi pertentangan (meskipun, tetapi, namun), konjungsi kausal (karena, sebab, oleh karena itu), kata sifat opini (baik, efektif, kurang tepat), kalimat saran (sebaiknya, seharusnya).",
      "Etika memberi tanggapan: fokus pada masalah bukan orang, gunakan bahasa santun, berikan alasan, akui kelebihan, sampaikan perbedaan pendapat dengan sopan.",
      "Langkah menulis: amati isu → kumpulkan fakta → rumuskan pendapat → tulis dengan struktur K-D-P → gunakan bahasa santun dan logis → revisi sebelum dipublikasikan.",
      "Contoh situasi tanggapan: menanggapi aturan sekolah, opini di media sosial, pidato ketua OSIS, karya teman, kebijakan publik, program sekolah.",
    ],
  },

  latihan: makeSoal([
    // 5 Soal Pilihan Ganda
    ["Teks tanggapan bertujuan untuk...", ["Menceritakan kisah fiksi kepada pembaca", "Memberikan penilaian terhadap suatu isu/peristiwa disertai alasan logis", "Menggambarkan objek dengan kesan subjektif", "Memandu pembaca melakukan sesuatu langkah demi langkah"], 1, "Teks tanggapan bertujuan memberikan penilaian (kritik/pujian/saran) terhadap suatu isu atau peristiwa yang disertai alasan logis dan membangun."],
    ["Perbedaan utama teks tanggapan dengan teks ulasan adalah...", ["Tanggapan lebih panjang dari ulasan", "Tanggapan merespons isu/peristiwa, ulasan mengulas karya", "Tanggapan untuk lisan, ulasan untuk tulisan", "Tanggapan menggunakan data, ulasan tidak"], 1, "Tanggapan FOKUS pada MERESPONS ISU/PERISTIWA/PENDAPAT, sedangkan ulasan FOKUS pada MENGULAS KARYA (buku, film, lagu, dll.)."],
    ["Berikut ini struktur teks tanggapan yang benar adalah...", ["Orientasi — komplikasi — resolusi", "Tesis — argumen — penegasan ulang", "Konteks — deskripsi — penilaian", "Pernyataan umum — deskripsi bagian — simpulan"], 2, "Struktur teks tanggapan: Konteks (perkenalan isu) → Deskripsi (gambaran objektif isu) → Penilaian (tanggapan + alasan)."],
    ["Tanggapan yang baik sebaiknya menggunakan kalimat saran. Contoh kalimat saran yang tepat adalah...", ["Program ini gagal total", "Sebaiknya sekolah menambah jam literasi menjadi 30 menit setiap hari", ["Saya tidak suka program ini", "Programnya jelek"], 1], 1, "'Sebaiknya' adalah kata kunci kalimat saran. Kalimat 'Sebaiknya sekolah menambah jam literasi' memberikan usulan konkret dan membangun."],
    ["Cermati kalimat: 'Meskipun tujuannya baik, pelaksanaan program ini masih kurang maksimal.' Kata 'meskipun' termasuk jenis konjungsi...", ["Kausal", "Temporal", "Pertentangan", "Koordinatif"], 2, "'Meskipun' adalah konjungsi pertentangan yang menyatakan hubungan berlawanan. Digunakan untuk menunjukkan dua sisi dari suatu isu."],

    // 3 Soal Betul/Salah
    ["Pernyataan: 'Kritik yang membangun harus fokus pada masalah, bukan menyerang pribadi orangnya.'", ["Betul", "Salah"], 0, "BETUL. Kritik membangun berfokus pada MASALAH atau KARYA, bukan pada pribadi orangnya. Contoh: 'Tulisan ini kurang terstruktur' (fokus pada karya), bukan 'Penulisnya tidak becus' (fokus pada orang)."],
    ["Pernyataan: 'Teks tanggapan hanya boleh berisi kritik, tidak perlu pujian atau saran.'", ["Betul", "Salah"], 1, "SALAH. Teks tanggapan bisa berisi pujian, kritik, saran, atau kombinasi ketiganya. Tanggapan yang seimbang justru mengakui kelebihan sekaligus memberi saran perbaikan."],
    ["Pernyataan: 'Kalimat \"Menurut saya\", \"Saya berpendapat\", dan \"Saya rasa\" adalah ungkapan pembuka opini dalam teks tanggapan.'", ["Betul", "Salah"], 0, "BETUL. Ungkapan tersebut menandai kalimat opini — ciri khas teks tanggapan. Penggunaannya juga membuat tanggapan terdengar lebih santun."],

    // 2 Soal Isian Singkat
    ["Bagian teks tanggapan yang berisi pengenalan isu atau peristiwa yang akan ditanggapi disebut...", ["konteks", "deskripsi", "penilaian", "simpulan"], 0, "KONTEKS adalah bagian pembuka yang memperkenalkan isu, peristiwa, atau hal yang akan ditanggapi. Bersifat netral dan informatif."],
    ["Kata 'sebaiknya', 'seharusnya', dan 'disarankan' dalam teks tanggapan termasuk jenis kalimat...", ["saran", "opini", "kritik", "pujian"], 0, "Kata-kata tersebut adalah penanda KALIMAT SARAN yang memberikan usulan atau rekomendasi perbaikan secara konkret."],
  ]),

  praktik: {
    petunjuk: "Buatlah teks tanggapan tentang SALAH SATU isu berikut:\n\n1. Kebijakan sekolah melarang penggunaan ponsel saat jam pelajaran\n2. Program Jumat Bersih/Cer das di sekolah\n3. Aturan seragam baru yang diterapkan sekolahmu\n4. Sebuah video/pidato teman yang viral di media sosial sekolah\n5. Kebiasaan mengerjakan tugas kelompok di malam hari (seperti ilustrasi contoh)\n\nTeks tanggapanmu harus mencakup:\n\n1. KONTEKS — 1—2 kalimat pengantar yang menjelaskan isu apa yang akan ditanggapi.\n2. DESKRIPSI — 2—4 kalimat yang menggambarkan isu secara objektif (fakta, data, kronologi).\n3. PENILAIAN — 3—5 kalimat yang berisi:\n   • Pujian (jika ada): sebut kelebihan secara spesifik dan beralasan\n   • Kritik (jika perlu): sampaikan kekurangan dengan sopan, fokus pada masalah\n   • Saran: berikan solusi yang konkret dan realistis\n   • Gunakan alasan logis untuk setiap pendapatmu\n\nGunakan minimal:\n• 2 kalimat opini (menurut saya, saya berpendapat, dll.)\n• 1 konjungsi pertentangan (meskipun, tetapi, namun)\n• 1 konjungsi kausal (karena, oleh karena itu)\n• 1 kalimat saran (sebaiknya, seharusnya, disarankan)\n\nTulis teks tanggapanmu dengan rapi di kolom di bawah ini!",
    tips: [
      "Pilih isu yang paling kamu pahami dan dekat dengan kehidupanmu sehari-hari. Semakin paham isunya, semakin mudah kamu memberi tanggapan yang berbobot.",
      "Mulai dengan konteks yang jelas: 'SMP Nusantara menerapkan aturan...' atau 'Baru-baru ini, video pidato...' — pembaca harus langsung tahu apa yang kamu tanggapi.",
      "Gunakan data jika ada. Contoh: 'Berdasarkan data kesiswaan, terdapat 45 siswa yang terdampak...' — data membuat tanggapanmu lebih kredibel.",
      "Seimbangkan pujian dan kritik. Jangan hanya mengkritik tanpa mengakui hal positif, dan jangan hanya memuji tanpa melihat kekurangan. Tanggapan yang seimbang menunjukkan cara berpikir yang dewasa.",
      "Saran harus konkret: 'Sebaiknya sekolah menambah jumlah loker menjadi 400 unit' lebih baik daripada 'Sebaiknya diperbaiki'. Saran yang konkret lebih mungkin ditindaklanjuti.",
      "Gunakan bahasa yang santun. Bayangkan kamu sedang berbicara langsung dengan kepala sekolah atau penulis opini tersebut — apakah cara bicaramu sopan?",
      "Baca ulang sebelum mengumpulkan. Cek struktur K-D-P, cek alasan logis, cek ejaan dan tanda baca. Minta teman membaca untuk mendapatkan masukan.",
    ],
    contoh: "Isu: Kebijakan Sekolah Melarang Penggunaan Ponsel saat Jam Pelajaran\n\nKonteks:\nSMP Cerdas Bangsa mulai menerapkan kebijakan larangan penggunaan ponsel selama jam pelajaran pada bulan Januari 2025. Setiap siswa diwajibkan menyimpan ponsel di loker yang telah disediakan di setiap kelas sebelum bel masuk berbunyi.\n\nDeskripsi:\nBerdasarkan survei internal sekolah, 85% siswa mengaku sering membuka media sosial saat guru menjelaskan — meskipun secara sembunyi-sembunyi. Nilai rata-rata ulangan semester ganjil menunjukkan penurunan 8% dibandingkan semester sebelumnya. Pihak sekolah kemudian memutuskan untuk menerapkan kebijakan ini setelah melakukan studi banding ke tiga sekolah yang telah menerapkannya lebih dulu. Sekolah menyediakan loker khusus di setiap kelas dengan kapasitas 30 unit per kelas.\n\nPenilaian:\nMenurut saya, kebijakan ini adalah langkah yang sangat tepat dan berani (pujian). Penggunaan ponsel saat jam pelajaran terbukti mengganggu konsentrasi belajar — data penelitian dari Kementerian Pendidikan menunjukkan bahwa siswa yang menyimpan ponsel di luar jangkauan selama belajar memiliki tingkat pemahaman materi 25% lebih tinggi. Saya mengapresiasi sekolah yang berani mengambil kebijakan tegas demi kualitas pembelajaran (pujian beralasan).\n\nNamun, saya perhatikan bahwa jumlah loker yang tersedia masih terbatas (kritik). Satu kelas rata-rata berisi 36 siswa, tetapi loker hanya tersedia 30 unit. Artinya, 6 siswa di setiap kelas tidak bisa menyimpan ponsel mereka. Oleh karena itu, sebaiknya sekolah menambah jumlah loker agar semua siswa dapat mematuhi aturan ini dengan nyaman (saran konkret). Selain itu, sekolah perlu memastikan bahwa guru juga memberikan jeda penggunaan ponsel saat istirahat — ponsel disita selama 6 jam penuh tanpa akses sama sekali bisa menimbulkan kecemasan pada beberapa siswa.\n\nKesimpulannya, saya mendukung kebijakan larangan ponsel saat jam pelajaran karena terbukti meningkatkan kualitas belajar. Saya berharap sekolah segera melengkapi fasilitas loker dan memberikan pengecualian bagi siswa yang memang membutuhkan ponsel untuk keperluan khusus yang telah mendapat izin orang tua.",
  },

  kuis: makeSoal([
    ["Teks tanggapan adalah teks yang berisi tanggapan berupa kritik, pujian, atau saran yang disertai...", ["Gambar ilustrasi", "Alasan yang logis", ["Pantun pembuka", "Data penelitian"], 1], 1, "Teks tanggapan harus menyertakan ALASAN LOGIS — bukan sekadar 'bagus' atau 'jelek' tanpa dasar."],
    ["Bagian struktur teks tanggapan yang berisi paparan fakta secara objektif disebut...", ["Konteks", "Deskripsi", "Penilaian", "Kesimpulan"], 1, "DESKRIPSI adalah bagian yang menggambarkan isu secara singkat, faktual, dan objektif. Di sini belum ada opini penulis."],
    ["Kalimat 'Sebaiknya sekolah menyediakan tempat sampah terpilah di setiap sudut kelas' termasuk jenis tanggapan...", ["Pujian", "Kritik", "Saran", "Netral"], 2, "Kalimat dengan kata 'sebaiknya' adalah SARAN — memberikan usulan konkret untuk perbaikan atau solusi."],
    ["Cermati tanggapan berikut: 'Saya menghargai pendapat Anda, tetapi izinkan saya menyampaikan sudut pandang yang berbeda.' Sikap yang ditunjukkan adalah...", ["Arogan dan tidak mau kalah", "Santun dan menghargai perbedaan", ["Tidak percaya diri", "Acuh tak acuh"], 1], 1, "Kalimat tersebut menunjukkan sikap SANTUN — menghargai pendapat orang lain terlebih dahulu, baru menyampaikan sudut pandang berbeda. Ini adalah etika yang baik dalam memberi tanggapan."],
    ["Mana dari berikut ini yang BUKAN termasuk ciri kebahasaan teks tanggapan?", ["Kalimat opini", "Konjungsi pertentangan", "Kalimat definisi", "Kalimat saran"], 2, "Kalimat DEFINISI (adalah, merupakan) adalah ciri teks LHO atau teks eksposisi, BUKAN ciri khas teks tanggapan. Ciri teks tanggapan: kalimat opini, konjungsi pertentangan/kausal, kalimat saran, kata sifat opini."],
    ["Fungsi konjungsi 'meskipun', 'tetapi', dan 'namun' dalam teks tanggapan adalah...", ["Menyatakan urutan waktu", "Menyatakan hubungan sebab-akibat", "Menyatakan hubungan pertentangan", "Menyatakan penambahan informasi"], 2, "Konjungsi tersebut menyatakan PERTENTANGAN — digunakan untuk menunjukkan dua sisi yang berlawanan dari suatu isu. Misalnya: 'Meskipun tujuannya baik, pelaksanaannya masih kurang.'"],
    ["Etika memberi kritik yang benar adalah...", ["Fokus pada masalah, bukan menyerang pribadi", ["Kritik harus keras agar didengar", "Kritik hanya perlu menyebut kekurangan", "Kritik tidak perlu disertai solusi"], 0], 0, "Kritik yang baik FOKUS pada MASALAH, bukan ORANG. Sampaikan dengan bahasa santun, berikan alasan, dan sertakan saran perbaikan."],
    ["Seorang siswa menulis: 'Menurut saya, program literasi ini perlu didukung. Namun, alangkah baiknya jika buku yang disediakan lebih bervariasi.' Tanggapan tersebut termasuk jenis...", ["Pujian saja", "Kritik saja", "Kombinasi pujian dan saran", "Netral"], 2, "Tanggapan ini berisi PUJIAN ('perlu didukung') dan SARAN ('alangkah baiknya jika buku bervariasi'). Kombinasi ini menunjukkan keseimbangan dan kematangan berpikir."],
    ["Perbedaan antara 'kritik' dan 'saran' yang paling tepat adalah...", ["Kritik lebih panjang dari saran", "Kritik menyebut kekurangan, saran memberi solusi perbaikan", ["Kritik untuk guru, saran untuk siswa", "Tidak ada perbedaan"], 1], 1, "KRITIK menyebut KEKURANGAN atau kelemahan dari suatu hal. SARAN memberi SOLUSI atau usulan perbaikan. Keduanya baik dan sebaiknya berpasangan: kritik + saran."],
    ["Seorang teman memberikan komentar: 'Tulisanmu bagus, tetapi ilustrasinya kurang sesuai dengan tema. Coba gunakan gambar yang lebih relevan.' Komentar tersebut termasuk...", ["Pujian saja", "Kritik tanpa alasan", "Pujian + kritik + saran", ["Celaan"], 2], 2, "Komentar ini lengkap: PUJIAN ('tulisanmu bagus') + KRITIK ('ilustrasi kurang sesuai') + SARAN ('coba gunakan gambar yang lebih relevan'). Ini contoh tanggapan ideal!"],
  ]),
}

export default konten
