import type { Konten } from "../types"
import { makeSoal } from "../types"

const konten: Konten = {
  belajar: {
    tujuan: [
      "Memahami pengertian, tujuan, dan ciri-ciri teks laporan percobaan",
      "Mengidentifikasi struktur teks laporan percobaan secara tepat",
      "Menganalisis kaidah kebahasaan yang digunakan dalam laporan percobaan",
      "Menyusun teks laporan percobaan berdasarkan data dan fakta percobaan",
    ],
    materi: [
      {
        judul: "Apa Itu Laporan Percobaan?",
        isi: [
          "Coba bayangkan kamu sedang melakukan percobaan sains di laboratorium. Setelah selesai, kamu ingin menceritakan hasilnya — apa yang terjadi, bagaimana prosesnya, dan apa kesimpulannya. Catatan terstruktur tentang percobaan itulah yang disebut teks laporan percobaan!",
          "",
          "Teks laporan percobaan adalah teks yang menyajikan informasi tentang tujuan, proses, dan hasil suatu percobaan secara sistematis dan objektif. Teks ini bertujuan untuk mengomunikasikan hasil percobaan kepada pembaca agar mereka memahami langkah-langkah dan temuan dari percobaan tersebut.",
          "",
          "✓ Ciri-ciri teks laporan percobaan:",
          "  ✓ Bersifat faktual — berdasarkan percobaan nyata, bukan opini",
          "  ✓ Menggunakan bahasa ilmiah dan istilah teknis yang sesuai",
          "  ✓ Disusun secara sistematis dan logis (dari awal hingga akhir)",
          "  ✓ Objektif — tidak dipengaruhi perasaan pribadi penulis",
          "  ✓ Dilengkapi data (angka, pengukuran, hasil pengamatan) sebagai bukti",
          "",
          "[Ilustrasi: Seorang pelajar mengenakan jas lab putih sedang menuangkan cairan biru dari tabung reaksi ke gelas kimia. Di atas meja tersebar alat-alat laboratorium — mikroskop, timbangan digital, dan beberapa tabung reaksi berisi cairan warna-warni. Di latar belakang, papan tulis menampilkan diagram alur percobaan. Gaya ilustrasi kartun edukatif dengan warna biru-putih.]",
        ],
        contoh: [
          "Perbedaan laporan percobaan dengan teks prosedur:",
          "",
          "TEKS PROSEDUR: \"Masukkan 200 ml air ke dalam panci, rebus hingga mendidih, lalu masukkan mie.\"",
          "✓ Fokus: menginstruksikan langkah untuk mencapai hasil tertentu.",
          "",
          "LAPORAN PERCOBAAN: \"Percobaan ini bertujuan untuk menguji pengaruh suhu air terhadap waktu melarutnya gula. Air 200 ml dipanaskan hingga suhu 30°C, 50°C, dan 80°C. Hasil menunjukkan bahwa gula lebih cepat larut pada suhu yang lebih tinggi.\"",
          "✓ Fokus: melaporkan proses, data, dan kesimpulan percobaan.",
          "",
          "PENTING: Teks prosedur menjawab 'bagaimana cara melakukan', sedangkan laporan percobaan menjawab 'apa yang terjadi dan apa kesimpulannya'.",
        ],
      },
      {
        judul: "Struktur Laporan Percobaan",
        isi: [
          "Seperti bangunan yang butuh fondasi kokoh, teks laporan percobaan punya struktur tetap yang membuatnya mudah dipahami.",
          "",
          "1. JUDUL PERCOBAAN",
          "  Judul yang jelas dan spesifik, mencerminkan isi percobaan.",
          "2. TUJUAN PERCOBAAN",
          "  Menjelaskan maksud dan target dari percobaan yang dilakukan.",
          "3. ALAT DAN BAHAN",
          "  Daftar semua peralatan dan bahan yang digunakan dalam percobaan.",
          "4. LANGKAH KERJA / PROSEDUR",
          "  Urutan langkah yang dilakukan selama percobaan.",
          "5. HASIL PENGAMATAN",
          "  Data yang diperoleh dari percobaan — bisa angka, tabel, grafik, atau deskripsi.",
          "6. KESIMPULAN",
          "  Interpretasi dari hasil pengamatan, menjawab tujuan percobaan.",
          "",
          "[Ilustrasi: Diagram alur vertikal berlabel 'STRUKTUR LAPORAN PERCOBAAN' dengan 6 kotak berwarna berbeda yang saling terhubung panah. Kotak 1: Judul, Kotak 2: Tujuan, Kotak 3: Alat dan Bahan, Kotak 4: Langkah Kerja, Kotak 5: Hasil Pengamatan, Kotak 6: Kesimpulan.]",
        ],
        contoh: [
          "JUDUL: Menyelidiki Pengaruh Jenis Pupuk terhadap Pertumbuhan Tanaman Kacang Hijau",
          "TUJUAN: Mengetahui pengaruh pupuk organik dan anorganik terhadap tinggi tanaman kacang hijau selama 7 hari.",
          "ALAT DAN BAHAN: 3 pot, 15 biji kacang hijau, tanah, pupuk kandang, pupuk NPK, air, penggaris.",
          "LANGKAH KERJA: 1) Siapkan 3 pot berisi tanah sama banyak. 2) Tanam 5 biji di setiap pot. 3) Pot A tanpa pupuk, Pot B pupuk kandang, Pot C pupuk NPK. 4) Siram setiap hari. 5) Ukur tinggi setiap hari.",
          "HASIL: Rata-rata tinggi hari ke-7: Pot A = 4,2 cm, Pot B = 7,5 cm, Pot C = 8,1 cm.",
          "KESIMPULAN: Pupuk NPK paling efektif meningkatkan pertumbuhan tanaman kacang hijau.",
        ],
        catatan: "Data dalam laporan percobaan harus disajikan APA ADANYA meskipun hasilnya tidak sesuai hipotesis. Kejujuran ilmiah adalah nilai utama dalam penulisan laporan percobaan.",
      },
      {
        judul: "Kaidah Kebahasaan Laporan Percobaan",
        isi: [
          "Teks laporan percobaan memiliki ciri bahasa yang khas:",
          "",
          "1. KATA KERJA AKTIF: menuangkan, mencampurkan, mengamati, menimbang, memanaskan.",
          "2. KALIMAT PERINTAH (Imperatif): \"Siapkan alat dan bahan...\", \"Tuangkan larutan...\"",
          "3. KATA HUBUNG KRONOLOGIS: pertama, kedua, kemudian, selanjutnya, setelah itu, akhirnya.",
          "4. KATA TEKNIS / ISTILAH ILMIAH: larutan, konsentrasi, hipotesis, variabel, kontrol.",
          "5. KALIMAT PASIF: \"Air dipanaskan hingga 100°C\" (bukan \"Saya memanaskan air\").",
          "6. DATA ANGKA: Suhu 30°C, Volume 200 ml, Massa 50 gram, Waktu 5 menit.",
          "",
          "[Ilustrasi: Papan tulis digital bertuliskan 'KAIDAH KEBAHASAAN' dengan 6 sticky note tempelan warna-warni. Setiap sticky note menampilkan satu kaidah.]",
        ],
        contoh: [
          "SALAH: \"Terus gue masukin gula ke air panas, trus diaduk pake sendok.\"",
          "✗ Menggunakan bahasa tidak baku, subjektif, tanpa data.",
          "",
          "BENAR: \"Gula sebanyak 50 gram dimasukkan ke dalam 200 ml air bersuhu 80°C, kemudian diaduk selama 30 detik hingga larut sempurna.\"",
          "✓ Bahasa baku, objektif, menyertakan data.",
          "",
          "SALAH: \"Menurut gue, pupuk organik lebih bagus dari pupuk kimia.\"",
          "✗ Opini pribadi tanpa data pendukung.",
          "",
          "BENAR: \"Berdasarkan hasil pengamatan, rata-rata tinggi tanaman yang diberi pupuk kandang adalah 7,5 cm, lebih tinggi dibanding tanaman kontrol (4,2 cm).\"",
          "✓ Didukung data, objektif, dan logis.",
        ],
      },
    ],
    rangkuman: [
      "[Ilustrasi: Seorang pelajar tersenyum bangga memegang laporan percobaan lengkap dengan data tabel dan grafik di sampingnya. Latar belakang laboratorium dengan peralatan sains. Gaya ilustrasi kartun edukatif dengan warna hijau dan biru.]",
      "Teks laporan percobaan adalah teks yang melaporkan hasil percobaan secara sistematis, faktual, dan objektif.",
      "Struktur laporan percobaan: Judul → Tujuan → Alat dan Bahan → Langkah Kerja → Hasil Pengamatan → Kesimpulan.",
      "Kaidah kebahasaan: kata kerja aktif, kalimat perintah, konjungsi kronologis, istilah teknis, kalimat pasif, dan data angka.",
      "Laporan percobaan berbeda dengan teks prosedur — laporan fokus pada hasil dan kesimpulan, prosedur fokus pada instruksi langkah.",
    ],
  },
  latihan: makeSoal([
    ["Apa tujuan utama dari teks laporan percobaan?", ["Menghibur pembaca", "Mengomunikasikan hasil percobaan", "Mempromosikan produk", "Menceritakan pengalaman pribadi"], 1, "Tujuan utama laporan percobaan adalah mengomunikasikan tujuan, proses, dan hasil percobaan secara sistematis."],
    ["Manakah yang BUKAN merupakan ciri teks laporan percobaan?", ["Faktual", "Objektif", "Subjektif", "Sistematis"], 2, "Teks laporan percobaan bersifat objektif, bukan subjektif."],
    ["Bagian struktur yang berisi urutan langkah percobaan disebut...", ["Tujuan", "Hasil Pengamatan", "Langkah Kerja", "Kesimpulan"], 2, "Langkah Kerja adalah bagian yang menjelaskan urutan prosedur percobaan."],
    ["Kata 'pertama, kemudian, selanjutnya, akhirnya' termasuk dalam jenis kata...", ["Kata sifat", "Kata kerja", "Konjungsi kronologis", "Kata benda"], 2, "Kata-kata tersebut merupakan konjungsi yang menunjukkan urutan waktu atau kronologis."],
    ["Kalimat 'Air sebanyak 200 ml dipanaskan hingga 80°C' menggunakan pola kalimat...", ["Aktif", "Pasif", "Imperatif", "Tanya"], 1, "Kalimat tersebut menggunakan pola pasif (di-) karena subjek dikenai tindakan."],
    ["Teks laporan percobaan bersifat FAKTUAL. Maksudnya adalah...", ["Berdasarkan imajinasi penulis", "Berdasarkan data dan kenyataan", "Berdasarkan pendapat ahli", "Berdasarkan perasaan penulis"], 1, "Faktual berarti berdasarkan fakta/data nyata dari percobaan, bukan imajinasi atau opini."],
    ["Bagian yang menjawab 'apakah tujuan percobaan tercapai?' adalah...", ["Hasil Pengamatan", "Alat dan Bahan", "Tujuan", "Kesimpulan"], 3, "Kesimpulan berisi interpretasi hasil dan menjawab apakah tujuan percobaan tercapai."],
    ["Berikut adalah kaidah kebahasaan laporan percobaan, KECUALI...", ["Kalimat pasif", "Istilah teknis", "Majas personifikasi", "Data angka"], 2, "Majas personifikasi tidak termasuk kaidah kebahasaan khas laporan percobaan."],
    ["'Siapkan alat dan bahan berikut...' adalah contoh kalimat...", ["Berita", "Perintah/Imperatif", "Tanya", "Seruan"], 1, "Kalimat 'Siapkan...' menggunakan imperatif (perintah) karena menyuruh melakukan tindakan."],
    ["Dalam laporan percobaan, data hasil sebaiknya disajikan dalam bentuk...", ["Opini penulis", "Tabel/grafik", "Cerita fiksi", "Puisi"], 1, "Data hasil sebaiknya disajikan secara jelas — bisa dalam tabel, grafik, atau deskripsi angka, bukan opini."],
  ]),
  praktik: {
    petunjuk: "Lakukan percobaan sederhana tentang 'Pengaruh Suhu terhadap Kecepatan Melarutnya Gula', lalu buatlah laporan percobaan lengkap dengan struktur yang benar!",
    tips: [
      "Gunakan 3 gelas berisi air dengan suhu berbeda: air dingin, air suhu ruang, dan air panas",
      "Masukkan 1 sendok gula pasir secara bersamaan ke masing-masing gelas, lalu aduk dengan kecepatan yang sama",
      "Catat waktu yang dibutuhkan gula untuk larut sempurna di setiap gelas menggunakan stopwatch",
      "Sajikan data dalam bentuk tabel: suhu air, waktu larut, dan pengamatan visual",
    ],
    contoh: "Pastikan setiap bagian struktur terisi lengkap. Gunakan kalimat pasif untuk bagian prosedur dan hasil. Jangan lupa mencantumkan data angka yang akurat.",
  },
  kuis: makeSoal([
    ["Apa fungsi utama bagian 'Hasil Pengamatan' dalam laporan percobaan?", ["Menjelaskan tujuan", "Menyajikan data percobaan", "Mendeskripsikan alat", "Menarik kesimpulan"], 1, "Hasil Pengamatan berfungsi menyajikan data percobaan secara objektif."],
    ["Kata 'hipotesis' dalam laporan percobaan berarti...", ["Kesimpulan akhir", "Data hasil", "Dugaan sementara", "Alat percobaan"], 2, "Hipotesis adalah dugaan sementara yang akan diuji melalui percobaan."],
    ["Struktur laporan percobaan yang tepat adalah...", ["Tujuan - Hasil - Langkah - Kesimpulan", "Judul - Tujuan - Alat/Bahan - Langkah - Hasil - Kesimpulan", "Alat/Bahan - Langkah - Tujuan - Hasil", "Kesimpulan - Hasil - Langkah - Tujuan"], 1, "Urutan struktur yang benar: Judul → Tujuan → Alat/Bahan → Langkah → Hasil → Kesimpulan."],
    ["Mengapa laporan percobaan menggunakan banyak kalimat pasif?", ["Agar lebih panjang", "Menekankan objek/proses bukan pelaku", "Karena lebih mudah ditulis", "Agar terlihat ilmiah"], 1, "Kalimat pasif menekankan pada objek atau proses percobaan."],
    ["Jika hasil percobaan tidak sesuai dengan hipotesis, apa yang harus dilakukan?", ["Mengubah data agar sesuai", "Melaporkan tetap sesuai data asli", "Membuang data dan mengulang", "Tidak menulis kesimpulan"], 1, "Kejujuran ilmiah mengharuskan data dilaporkan apa adanya."],
    ["Bagian yang berisi daftar peralatan yang digunakan dalam percobaan adalah...", ["Langkah Kerja", "Hasil", "Alat dan Bahan", "Kesimpulan"], 2, "Alat dan Bahan berisi daftar semua peralatan dan material yang digunakan."],
    ["Kalimat 'Pertama, siapkan tiga gelas kimia berukuran 250 ml.' mengandung konjungsi...", ["Kausal", "Kronologis", "Pertentangan", "Tujuan"], 1, "'Pertama' adalah konjungsi kronologis yang menunjukkan urutan langkah."],
    ["Berikut adalah contoh istilah teknis dalam laporan percobaan, KECUALI...", ["Larutan", "Konsentrasi", "Indah", "Variabel"], 2, "'Indah' adalah kata sifat umum, bukan istilah teknis ilmiah."],
    ["Apa perbedaan utama laporan percobaan dengan teks prosedur?", ["Tidak ada perbedaan", "Prosedur memberi instruksi, laporan melaporkan hasil", "Prosedur lebih panjang", "Laporan tanpa data"], 1, "Teks prosedur menginstruksikan cara, laporan percobaan melaporkan hasil."],
    ["'Berdasarkan data di atas, dapat disimpulkan bahwa...' Kalimat ini untuk bagian...", ["Tujuan", "Hasil", "Kesimpulan", "Langkah"], 2, "Kalimat tersebut merupakan ciri khas bagian Kesimpulan."],
  ]),
}

export default konten
