import type { Konten } from "../types"
import { makeSoal } from "../types"

const konten: Konten = {
  belajar: {
    tujuan: [
      "Memahami pengertian, tujuan, dan ciri-ciri pidato persuasif",
      "Mengidentifikasi struktur pidato persuasif dengan tepat",
      "Menganalisis kaidah kebahasaan dalam pidato persuasif",
      "Menyusun teks pidato persuasif dengan struktur dan teknik yang benar",
    ],
    materi: [
      {
        judul: "Apa Itu Pidato Persuasif?",
        isi: [
          "Pernahkah kamu melihat seorang orator di televisi yang mampu membuat ribuan orang terpengaruh oleh kata-katanya? Atau mendengar pidato kepala sekolah yang membuatmu bersemangat mengikuti lomba? Itulah kekuatan pidato persuasif!",
          "",
          "Pidato persuasif adalah pidato yang bertujuan untuk memengaruhi, mengajak, atau membujuk pendengar untuk melakukan sesuatu sesuai dengan keinginan pembicara. Kata 'persuasif' berasal dari bahasa Inggris 'to persuade' yang berarti meyakinkan atau membujuk.",
          "",
          "✓ Tujuan pidato persuasif:",
          "  ✓ Membentuk opini — mengubah cara pandang pendengar terhadap suatu isu",
          "  ✓ Mengajak tindakan — mendorong pendengar untuk melakukan sesuatu",
          "  ✓ Memengaruhi sikap — mengubah perilaku atau kebiasaan pendengar",
          "  ✓ Menyampaikan informasi edukatif — memberi pengetahuan sambil membujuk",
          "",
          "Dalam pidato persuasif, dikenal 3 teknik penting yang disebut ETOS-PATOS-LOGOS:",
          "",
          "ETOS (Kredibilitas) — Pembicara harus tampil meyakinkan, berwibawa, dan dapat dipercaya. Etos dibangun melalui pengetahuan, pengalaman, dan sikap percaya diri.",
          "PATOS (Emosi) — Pembicara menyentuh perasaan pendengar — empati, haru, bangga, atau prihatin — agar mereka tergerak hatinya.",
          "LOGOS (Logika) — Argumen disampaikan dengan data, fakta, dan alasan logis sehingga pendengar yakin secara nalar.",
          "",
          "[Ilustrasi: Seorang pembicara berdiri di atas panggung dengan mikrofon di tangan, di belakangnya layar lebar bertuliskan 'ETOS - PATOS - LOGOS'. Di depannya, ratusan siswa duduk dengan ekspresi antusias. Sorot lampu panggung mengarah ke pembicara. Gaya ilustrasi semi-realistis dengan nuansa biru dan emas.]",
        ],
        contoh: [
          "Contoh kalimat ETOS: \"Sebagai seorang guru yang telah mengajar selama 15 tahun, saya menyaksikan sendiri betapa besarnya manfaat membaca bagi prestasi siswa.\"",
          "✓ Membangun kredibilitas melalui pengalaman.",
          "",
          "Contoh kalimat PATOS: \"Bayangkan adik-adik kita yang putus sekolah karena tidak mampu membeli buku. Merekalah yang akan tertinggal di masa depan.\"",
          "✓ Menyentuh emosi dan rasa iba pendengar.",
          "",
          "Contoh kalimat LOGOS: \"Data UNESCO menunjukkan bahwa minat baca Indonesia hanya 0,001% — artinya dari 1.000 orang, hanya 1 yang rajin membaca. Ini sangat memprihatinkan.\"",
          "✓ Menggunakan data dan fakta untuk meyakinkan.",
        ],
      },
      {
        judul: "Struktur Pidato Persuasif",
        isi: [
          "Pidato persuasif memiliki struktur yang rapi agar pesan mudah diterima dan diingat pendengar.",
          "",
          "1. PEMBUKAAN (Pendahuluan)",
          "  a. Salam pembuka — menyapa audiens dengan ramah",
          "  b. Attention-getter — kalimat pembuka yang menarik perhatian (kutipan, pertanyaan retoris, data mengejutkan, atau cerita singkat)",
          "  c. Pengenalan topik — menyampaikan topik yang akan dibahas",
          "",
          "2. ISI (Inti Pidato)",
          "  a. Paparan argumen — menyampaikan alasan-alasan yang mendukung tujuan pidato",
          "  b. Fakta dan data — memperkuat argumen dengan bukti konkret",
          "  c. Ajakan — kalimat yang secara langsung mengajak pendengar melakukan tindakan",
          "",
          "3. PENUTUP",
          "  a. Kesimpulan — merangkum poin-poin penting argumen",
          "  b. Ajakan final — seruan terakhir yang kuat",
          "  c. Salam penutup — menutup pidato dengan santun",
          "",
          "PENTING: Attention-getter adalah kunci pembukaan yang sukses! Kalimat pertama harus mampu membuat pendengar berhenti melamun dan fokus mendengarkan.",
          "",
          "[Ilustrasi: Diagram piramida terbalik 3 tingkat berlabel 'STRUKTUR PIDATO PERSUASIF'. Tingkat atas (kuning) bertuliskan 'PEMBUKAAN - Attention Getter + Salam + Topik'. Tingkat tengah (biru) 'ISI - Argumen + Data + Ajakan'. Tingkat bawah (hijau) 'PENUTUP - Simpulan + Ajakan Final + Salam'. Setiap tingkat dihubungkan dengan panah.]",
        ],
        contoh: [
          "PEMBUKAAN: \"Selamat pagi, teman-teman yang luar biasa! (salam) Tahukah kalian bahwa setiap menit, satu hektar hutan Indonesia hilang? (attention-getter) Hari ini saya ingin mengajak kita semua untuk peduli pada lingkungan. (topik)\"",
          "",
          "ISI: \"Hutan adalah paru-paru dunia. Tanpa hutan, udara kita akan kotor dan suhu bumi meningkat. Data KLHK menunjukkan Indonesia kehilangan 115.000 hektar hutan per tahun. Itu artinya, setiap jam—— 13 hektar hutan lenyap! (fakta) Oleh karena itu, mulai sekarang, mari kita tanam satu pohon setiap bulan. (ajakan)\"",
          "",
          "PENUTUP: \"Satu pohon mungkin tampak kecil. Tapi jika kita semua— 500 siswa di sini— menanam satu pohon, setidaknya 500 pohon baru akan tumbuh. Mulailah dari sekarang. (ajakan final) Selamat pagi dan salam hijau! (salam penutup)\"",
        ],
      },
      {
        judul: "Kaidah Kebahasaan Pidato Persuasif",
        isi: [
          "Pidato persuasif memiliki ciri bahasa khusus yang membuatnya kuat dan meyakinkan.",
          "",
          "1. KATA AJAKAN (Persuasif): mari, ayo, marilah, hendaknya, sebaiknya, janganlah — mengajak langsung pendengar.",
          "2. KATA EMOTIF: menyayat hati, membanggakan, memprihatinkan, menggembirakan, haru — menyentuh perasaan.",
          "3. KONJUNGSI ARGUMENTATIF: oleh karena itu, dengan demikian, sebab, karena, maka dari itu — menghubungkan argumen secara logis.",
          "4. KATA SERU / INTERJEKSI: wah, ayo, nah, yuk — menarik perhatian dan memberi semangat.",
          "5. KALIMAT RETORIS: pertanyaan yang tidak memerlukan jawaban — \"Siapa yang tidak ingin masa depan cerah?\"",
          "6. KOSAKATA EVALUATIF: penting, berharga, bermanfaat, merusak, berbahaya — menilai sesuatu.",
          "7. PRONOMINA (Kata Ganti): kita, kami, kalian — membangun kedekatan pembicara-pendengar.",
          "",
          "[Ilustrasi: Papan tulis interaktif dengan 7 ikon kaidah kebahasaan. Setiap ikon terdiri dari simbol dan contoh kata di bawahnya: orator (kata ajakan), hati (emotif), rantai (konjungsi), tanda seru (interjeksi), tanda tanya (retoris), bintang (evaluatif), dan orang berpegangan tangan (pronomina).]",
        ],
        contoh: [
          "BAHASA NON-PERSUASIF: \"Kita harus belajar. Belajar itu penting.\"",
          "✗ Kurang kuat, terkesan menggurui.",
          "",
          "BAHASA PERSUASIF: \"Ayo, mari kita budayakan belajar setiap hari! Dengan belajar, masa depan cerah menanti kita. Siapa yang tidak ingin sukses?\"",
          "✓ Menggunakan kata ajakan (ayo, mari), pronomina (kita), dan kalimat retoris.",
          "",
          "SALAH: \"Kalian wajib datang ke acara ini. Tidak boleh tidak!\"",
          "✗ Terkesan memaksa, tidak persuasif.",
          "",
          "BENAR: \"Hadirilah acara ini karena kalian akan mendapatkan pengalaman berharga. Yuk, jangan lewatkan kesempatan emas ini!\"",
          "✓ Mengajak dengan alasan positif dan kata persuasif.",
        ],
      },
    ],
    rangkuman: [
      "[Ilustrasi: Seorang orator muda berdiri tegak di mimbar, tangan kanan terangkat memberi gestur meyakinkan. Lampu sorot mengarah padanya. Latar belakang bendera merah putih dan papan bertuliskan 'SATU BAHASA, SATU BANGSA'. Gaya ilustrasi semi-realistis dengan warna merah dan emas.]",
      "Pidato persuasif bertujuan memengaruhi, mengajak, atau membujuk pendengar melalui teknik etos (kredibilitas), patos (emosi), dan logos (logika).",
      "Struktur pidato persuasif: Pembukaan (salam, attention-getter, topik) → Isi (argumen, data, ajakan) → Penutup (kesimpulan, ajakan final, salam).",
      "Kaidah kebahasaan meliputi: kata ajakan, kata emotif, konjungsi argumentatif, kalimat retoris, kata seru, kosakata evaluatif, dan pronomina.",
      "Pidato persuasif harus disampaikan dengan percaya diri dan intonasi yang tepat agar pesan sampai efektif.",
    ],
  },
  latihan: makeSoal([
    ["Apa tujuan utama dari pidato persuasif?", ["Menghibur pendengar", "Memengaruhi dan mengajak pendengar", "Menceritakan pengalaman pribadi", "Melaporkan data penelitian"], 1, "Tujuan utama pidato persuasif adalah memengaruhi, membujuk, atau mengajak pendengar melakukan sesuatu."],
    ["Teknik ETOS dalam pidato persuasif berkaitan dengan...", ["Emosi pendengar", "Kredibilitas pembicara", "Data dan fakta", "Struktur pidato"], 1, "Etos berkaitan dengan kredibilitas dan kepercayaan terhadap pembicara."],
    ["Manakah yang termasuk ATTENTION-GETTER dalam pembukaan pidato?", ["Selamat pagi, Bapak dan Ibu", "Tahukah Anda bahwa setiap detik satu ton sampah plastik mencemari lautan?", "Terima kasih atas kehadirannya", "Demikian pidato yang dapat saya sampaikan"], 1, "Attention-getter adalah kalimat pembuka yang mengejutkan dan menarik perhatian."],
    ["Kata 'mari', 'ayo', 'marilah' termasuk dalam kategori...", ["Konjungsi argumentatif", "Kata ajakan/persuasif", "Kata emotif", "Pronomina"], 1, "Kata-kata tersebut merupakan kata ajakan yang mengajak pendengar melakukan tindakan."],
    ["Bagian pidato yang berisi rangkuman poin penting disebut...", ["Pembukaan", "Argumen", "Kesimpulan", "Attention-getter"], 2, "Kesimpulan berisi rangkuman poin-poin penting yang telah disampaikan."],
    ["Kalimat 'Siapa yang tidak ingin masa depan yang cerah?' adalah contoh...", ["Kalimat berita", "Kalimat perintah", "Kalimat retoris", "Kalimat tanya biasa"], 2, "Kalimat retoris adalah pertanyaan yang tidak memerlukan jawaban, digunakan untuk efek persuasif."],
    ["Teknik LOGOS dalam pidato persuasif berarti...", ["Menggunakan emosi", "Menggunakan data dan fakta logis", "Menggunakan humor", "Menampilkan kredibilitas"], 1, "Logos berarti menggunakan logika, data, fakta, dan argumen rasional."],
    ["Pronomina 'kita' dalam pidato persuasif berfungsi untuk...", ["Menunjukkan diri sendiri", "Membangun kedekatan dengan pendengar", "Menghina pendengar", "Menjaga jarak"], 1, "Pronomina 'kita' membangun rasa kebersamaan antara pembicara dan pendengar."],
    ["Berikut adalah ciri bahasa pidato persuasif, KECUALI...", ["Kata emotif", "Konjungsi argumentatif", "Istilah teknis ilmiah", "Kalimat retoris"], 2, "Istilah teknis ilmiah bukan ciri khas pidato persuasif."],
    ["Bagian pidato yang berisi ajakan langsung kepada pendengar terdapat di...", ["Hanya di penutup", "Di isi dan penutup", "Hanya di pembukaan", "Hanya di isi"], 1, "Ajakan langsung biasanya muncul di bagian isi (ajakan) dan diperkuat di penutup (ajakan final)."],
  ]),
  praktik: {
    petunjuk: "Buatlah teks pidato persuasif dengan tema 'Pentingnya Membaca Buku untuk Masa Depan'! Gunakan struktur yang benar dan sertakan teknik etos, patos, dan logos.",
    tips: [
      "Mulailah dengan attention-getter yang kuat — misalnya data mengejutkan tentang minat baca di Indonesia",
      "Gunakan minimal 3 kata ajakan (mari, ayo, marilah) yang tersebar di teks",
      "Sertakan satu kalimat retoris untuk memperkuat argumen",
      "Akhiri dengan ajakan final yang menginspirasi dan mudah diingat",
      "Gunakan pronomina 'kita' untuk membangun kedekatan dengan pendengar",
    ],
    contoh: "Teks pidato minimal 3 paragraf (pembukaan, isi, penutup). Setiap paragraf terdiri dari 3-5 kalimat. Gunakan bahasa Indonesia yang baik dan benar.",
  },
  kuis: makeSoal([
    ["Apa yang dimaksud dengan attention-getter dalam pidato persuasif?", ["Salam pembuka", "Kalimat yang menarik perhatian pendengar", "Topik pidato", "Kesimpulan pidato"], 1, "Attention-getter adalah kalimat pembuka yang dirancang untuk menarik perhatian pendengar."],
    ["Contoh kata emotif yang tepat dalam pidato persuasif adalah...", ["Pertama", "Menyayat hati", "Kemudian", "Oleh karena itu"], 1, "'Menyayat hati' adalah kata emotif yang menyentuh perasaan."],
    ["Etos dalam pidato persuasif dibangun melalui...", ["Data statistik", "Kredibilitas dan pengetahuan pembicara", "Pertanyaan retoris", "Kata ajakan"], 1, "Etos dibangun melalui kredibilitas, pengetahuan, pengalaman, dan sikap percaya diri pembicara."],
    ["Konjungsi argumentatif digunakan untuk...", ["Menghubungkan waktu", "Menghubungkan argumen secara logis", "Menunjukkan urutan", "Menyatakan pertentangan"], 1, "Konjungsi argumentatif (oleh karena itu, dengan demikian) menghubungkan argumen secara logis."],
    ["Bagaimana cara menutup pidato persuasif yang efektif?", ["Mengucapkan terima kasih lalu turun", "Merangkum argumen lalu memberi ajakan final", "Memberikan data baru", "Bertanya kepada pendengar"], 1, "Penutup efektif berisi rangkuman argumen dan ajakan final yang kuat."],
    ["Kalimat 'Bayangkan jika anak-anak kita kehilangan masa depan karena narkoba' menggunakan teknik...", ["Logos", "Etos", "Patos", "Kronologis"], 2, "Kalimat tersebut menyentuh emosi (patos) dengan membayangkan situasi menyedihkan."],
    ["Apa fungsi kalimat retoris dalam pidato persuasif?", ["Meminta pendapat", "Membuat pendengar berpikir dan setuju", "Memberi informasi baru", "Menjeda pidato"], 1, "Kalimat retoris membuat pendengar merenung dan secara tidak langsung setuju dengan pembicara."],
    ["Kata 'hendaknya' dan 'sebaiknya' termasuk jenis kata...", ["Emotif", "Persuasif halus", "Teknis", "Evaluatif"], 1, "Kata 'hendaknya' dan 'sebaiknya' adalah ajakan yang disampaikan secara halus."],
    ["Bagian pidato yang berisi paparan alasan dan bukti pendukung adalah...", ["Pembukaan", "Isi/inti pidato", "Penutup", "Salam"], 1, "Bagian isi berisi paparan argumen, data, fakta, dan alasan yang mendukung tujuan pidato."],
    ["Salah satu ciri kebahasaan pidato persuasif adalah penggunaan pronomina. Contoh pronomina yang tepat adalah...", ["Membaca", "Kita", "Karena", "Penting"], 1, "'Kita' adalah pronomina persona yang membangun kebersamaan pembicara dan pendengar."],
  ]),
}

export default konten
