import type { Konten } from "../types"
import { makeSoal } from "../types"

const konten: Konten = {
  belajar: {
    tujuan: [
      "Memahami pengertian dan tujuan teks tanggapan",
      "Mengidentifikasi struktur teks tanggapan dengan benar",
      "Menganalisis kaidah kebahasaan dan etika dalam memberi tanggapan",
      "Menyusun teks tanggapan yang objektif dan santun",
    ],
    materi: [
      {
        judul: "Apa Itu Teks Tanggapan?",
        isi: [
          "Pernahkah kamu diminta memberi pendapat tentang presentasi teman di kelas? Atau mengomentari karya seni di pameran sekolah? Saat kamu memberikan penilaian yang disertai alasan, secara tidak sadar kamu sedang membuat teks tanggapan!",
          "",
          "Teks tanggapan adalah teks yang berisi pendapat, ulasan, atau evaluasi terhadap suatu karya, peristiwa, atau fenomena. Teks ini bersifat objektif — artinya didasarkan pada fakta dan alasan logis, bukan sekadar suka atau tidak suka.",
          "",
          "✓ Tujuan teks tanggapan:",
          "  ✓ Memberikan penilaian yang objektif terhadap suatu hal",
          "  ✓ Menyampaikan apresiasi atau kritik yang membangun",
          "  ✓ Membantu pembaca memahami kelebihan dan kekurangan suatu karya",
          "  ✓ Mendorong perbaikan dan pengembangan karya di masa depan",
          "",
          "Teks tanggapan berbeda dengan kritik pedas di media sosial. Teks tanggapan bersifat santun, terstruktur, dan disertai alasan yang logis. Tujuannya membangun, bukan menjatuhkan.",
          "",
          "[Ilustrasi: Seorang siswa berdiri di depan kelas memegang kertas presentasi. Di barisan kursi, seorang siswa lain mengangkat tangan dengan sopan, siap memberi tanggapan. Papan tulis di belakang bertuliskan 'TEKS TANGGAPAN: Objektif, Santun, Membangun'. Gaya ilustrasi kartun sekolah dengan warna biru dan putih.]",
        ],
        contoh: [
          "TANGGAPAN SUBJEKTIF (kurang tepat): \"Presentasimu membosankan banget. Aku enggak suka.\"",
          "✗ Subjektif, tidak beralasan, cenderung menyakitkan.",
          "",
          "TANGGAPAN OBJEKTIF (tepat): \"Presentasi tentang daur ulang sampah ini informatif. Namun, alangkah baiknya jika ditambahkan data statistik agar argumen lebih kuat. Penggunaan gambar juga bisa diperbanyak untuk menarik perhatian.\"",
          "✓ Objektif, memberi apresiasi dan kritik membangun, disertai saran perbaikan.",
          "",
          "Tips: Gunakan kata 'menurut saya', 'sebaiknya', 'alangkah baiknya' untuk menyampaikan kritik dengan santun.",
        ],
      },
      {
        judul: "Struktur Teks Tanggapan",
        isi: [
          "Seperti ulasan professional di koran atau majalah, teks tanggapan memiliki struktur baku yang membuatnya mudah dipahami.",
          "",
          "1. KONTEKS",
          "  • Pengenalan umum tentang objek yang ditanggapi",
          "  • Latar belakang mengapa objek tersebut menarik untuk ditanggapi",
          "  • Identifikasi karya/peristiwa (judul, pencipta, jenis karya)",
          "",
          "2. DESKRIPSI",
          "  • Gambaran rinci tentang objek tanggapan",
          "  • Uraian kelebihan dan kekurangan secara objektif",
          "  • Disertai bukti atau contoh konkret dari objek yang ditanggapi",
          "",
          "3. PENEGASAN (Evaluasi)",
          "  • Kesimpulan dari penilaian yang telah dipaparkan",
          "  • Saran atau rekomendasi untuk perbaikan ke depan",
          "  • Harapan penulis terhadap karya atau objek tersebut",
          "",
          "[Ilustrasi: Diagram alur tiga langkah horizontal. Kotak pertama 'KONTEKS' dengan ikon kaca pembesar — mengenali objek. Kotak kedua 'DESKRIPSI' dengan ikon buku catatan — memaparkan kelebihan dan kekurangan. Kotak ketiga 'PENEGASAN' dengan ikon bintang — menyimpulkan dan memberi saran. Panah menghubungkan ketiganya.]",
        ],
        contoh: [
          "KONTEKS: \"Lukisan 'Ibu Pertiwi' karya siswa kelas 9A yang dipamerkan di acara Gelar Seni Sekolah minggu lalu menarik perhatian banyak pengunjung. Lukisan berukuran 100x80 cm ini menggambarkan seorang ibu yang memangku bumi.\"",
          "",
          "DESKRIPSI: \"Kelebihan lukisan ini terletak pada pemilihan warna yang hangat dan ekspresi wajah ibu yang penuh kasih. Gradasi warna biru dan hijau pada bumi memberikan kesan damai. Namun, proporsi tubuh ibu masih terlihat kurang proporsional — tangan kanan lebih panjang dari tangan kiri. Tekstur cat juga terlihat tidak merata di beberapa bagian.\"",
          "",
          "PENEGASAN: \"Secara keseluruhan, lukisan 'Ibu Pertiwi' adalah karya yang mengesankan dengan konsep yang kuat. Dengan latihan proporsi anatomi dan teknik tekstur yang lebih matang, pelukis muda ini berpotensi menjadi seniman hebat. Karya ini layak mendapat apresiasi dan dukungan.\"",
        ],
      },
      {
        judul: "Kaidah dan Etika Teks Tanggapan",
        isi: [
          "Memberi tanggapan bukan sekadar menyampaikan pendapat — ada kaidah dan etika yang harus dipatuhi agar tanggapan diterima dengan baik.",
          "",
          "PRINSIP KRISAR (Kritis-Santun):",
          "Kritis — tanggapan harus disertai analisis dan alasan yang jelas",
          "Santun — gunakan bahasa yang sopan dan tidak merendahkan",
          "",
          "KAIDAH KEBAHASAAN:",
          "1. KONJUNGSI PERTENTANGAN: tetapi, namun, meskipun, sedangkan — untuk menyatakan perbedaan antara kelebihan dan kekurangan",
          "2. KATA SIFAT EVALUATIF: menarik, kurang tepat, baik, efektif, membingungkan",
          "3. KALIMAT SARAN: sebaiknya, alangkah baiknya, seharusnya, disarankan",
          "4. KATA PENYANDANG OPINI: menurut saya, dari sudut pandang saya, berdasarkan pengamatan saya",
          "5. KONJUNGSI PENJELAS: bahwa, yakni, yaitu — untuk menjelaskan alasan di balik tanggapan",
          "",
          "ETIKA DALAM MEMBERI TANGGAPAN:",
          "• Mulailah dengan apresiasi (kelebihan) sebelum kritik (kekurangan)",
          "• Gunakan bahasa yang santun dan tidak menyinggung",
          "• Berikan saran perbaikan yang konkret dan membangun",
          "• Hindari serangan pribadi — tanggapilah karya, bukan orangnya",
          "",
          "[Ilustrasi: Sebuah perisai bertuliskan 'KRISAR: Kritis & Santun'. Dua tangan berjabat di bawah perisai. Di sekitar perisai, terdapat ikon-ikon kaidah kebahasaan: tanda panah bercabang (konjungsi pertentangan), bintang (kata evaluatif), dan gelombang suara (opini).]",
        ],
        contoh: [
          "CONTOH PENERAPAN KRISAR:",
          "",
          "\"Menurut saya, pidato tentang bahaya narkoba ini sangat informatif dan penuh semangat. Namun, alangkah baiknya jika data statistik diperbarui karena data yang digunakan sudah tiga tahun lalu. Meskipun demikian, secara keseluruhan pidato ini layak diapresiasi.\"",
          "",
          "✓ Kritis: Menunjukkan kekurangan data yang usang dengan alasan jelas.",
          "✓ Santun: Diawali apresiasi, disampaikan dengan bahasa yang halus.",
          "",
          "SALAH: \"Pidatomu tidak menarik. Datanya jelek.\"",
          "✗ Tidak santun, tidak ada saran perbaikan, bersifat subjektif.",
        ],
      },
    ],
    rangkuman: [
      "[Ilustrasi: Dua siswa duduk berhadapan dengan buku terbuka di tengah. Salah satu mengacungkan jempol, yang lain tersenyum setuju. Papan tulis di belakang bertuliskan 'Tanggapan yang Santun dan Membangun'. Gaya ilustrasi kartun sekolah dengan warna biru dan putih.]",
      "Teks tanggapan adalah teks berisi penilaian objektif terhadap suatu karya atau fenomena yang disertai alasan logis.",
      "Struktur teks tanggapan: Konteks (pengenalan) → Deskripsi (kelebihan dan kekurangan) → Penegasan (simpulan dan saran).",
      "Kaidah kebahasaan: konjungsi pertentangan, kata sifat evaluatif, kalimat saran, kata penyandang opini.",
      "Prinsip KRISAR: Kritis dan Santun — menyampaikan kritik dengan cara yang membangun, bukan menjatuhkan.",
    ],
  },
  latihan: makeSoal([
    ["Apa tujuan utama teks tanggapan?", ["Menghibur pembaca", "Memberikan penilaian objektif", "Menceritakan pengalaman", "Mengiklankan produk"], 1, "Teks tanggapan bertujuan memberikan penilaian objektif terhadap suatu karya atau fenomena."],
    ["Struktur teks tanggapan yang tepat adalah...", ["Deskripsi - Konteks - Penegasan", "Konteks - Deskripsi - Penegasan", "Penegasan - Konteks - Deskripsi", "Deskripsi - Penegasan - Konteks"], 1, "Urutan struktur: Konteks (pengenalan) → Deskripsi (paparan) → Penegasan (simpulan)."],
    ["Kata 'tetapi', 'namun', 'meskipun' termasuk jenis konjungsi...", ["Kronologis", "Pertentangan", "Kausal", "Tujuan"], 1, "Konjungsi pertentangan menghubungkan dua hal yang berlawanan."],
    ["Prinsip KRISAR dalam teks tanggapan berarti...", ["Kritis dan Santun", "Kreatif dan Sederhana", "Keras dan Serius", "Ringkas dan Sistematis"], 0, "KRISAR adalah kependekan dari Kritis dan Santun."],
    ["Bagian teks tanggapan yang berisi pengenalan objek disebut...", ["Deskripsi", "Konteks", "Penegasan", "Evaluasi"], 1, "Konteks berisi pengenalan umum dan latar belakang objek yang ditanggapi."],
    ["Kalimat 'Sebaiknya penambahan ilustrasi diperbanyak' termasuk jenis kalimat...", ["Berita", "Saran", "Perintah", "Tanya"], 1, "'Sebaiknya' menandakan kalimat saran atau rekomendasi."],
    ["Etika pertama dalam memberi tanggapan adalah...", ["Langsung mengkritik", "Mulai dengan apresiasi", "Menyerang pribadi", "Bicara keras"], 1, "Mulailah dengan apresiasi terhadap kelebihan sebelum menyampaikan kritik."],
    ["Manakah contoh tanggapan yang santun?", ["\"Lukisanmu jelek\"", "\"Warna yang dipilih menarik, namun proporsi bisa lebih diperbaiki\"", "\"Kamu tidak berbakat\"", "\"Ini tidak berguna\""], 1, "Contoh tersebut memberikan apresiasi diikuti kritik membangun."],
    ["Kata evaluatif dalam teks tanggapan berfungsi untuk...", ["Menghubungkan kalimat", "Menilai kualitas objek", "Menunjukkan waktu", "Menanyakan sesuatu"], 1, "Kata evaluatif (menarik, baik, kurang tepat) menilai kualitas objek."],
    ["Bagian penegasan berisi...", ["Pengenalan objek", "Rincian kelebihan", "Simpulan dan saran", "Latar belakang"], 2, "Penegasan berisi kesimpulan penilaian dan saran perbaikan ke depan."],
  ]),
  praktik: {
    petunjuk: "Buatlah teks tanggapan terhadap sebuah karya teman sekelasmu — bisa berupa puisi, gambar, atau hasil presentasi! Gunakan struktur konteks-deskripsi-penegasan dan prinsip KRISAR.",
    tips: [
      "Mulailah dengan menyebutkan judul dan jenis karya yang kamu tanggapi",
      "Sebutkan minimal 2 kelebihan dan 2 saran perbaikan",
      "Gunakan konjungsi pertentangan (tetapi, namun) saat beralih dari apresiasi ke kritik",
      "Akhiri dengan kesimpulan dan semangat untuk pengembangan karya",
      "Hindari kata-kata absolut seperti 'sangat jelek' atau 'paling bagus'",
    ],
    contoh: "Minimal 3 paragraf sesuai struktur. Gunakan bahasa Indonesia yang santun. Jika tidak ada karya asli, kamu bisa membuat tanggapan terhadap puisi atau cerpen yang pernah kamu baca.",
  },
  kuis: makeSoal([
    ["Teks tanggapan bersifat objektif. Maksudnya adalah...", ["Berdasarkan perasaan", "Berdasarkan fakta dan alasan logis", "Berdasarkan rumor", "Berdasarkan keinginan"], 1, "Objektif berarti didasarkan pada fakta, data, dan alasan logis, bukan perasaan pribadi."],
    ["Apa perbedaan teks tanggapan dengan komentar di media sosial?", ["Teks tanggapan lebih panjang", "Teks tanggapan terstruktur dan objektif", "Tidak ada perbedaan", "Komentar lebih baik"], 1, "Teks tanggapan terstruktur, objektif, dan santun — berbeda dengan komentar yang sering subjektif."],
    ["Fungsi konjungsi pertentangan dalam teks tanggapan adalah...", ["Menunjukkan urutan", "Menghubungkan kelebihan dan kekurangan", "Menjelaskan waktu", "Menyatakan sebab"], 1, "Konjungsi pertentangan menghubungkan antara kelebihan dan kekurangan dalam tanggapan."],
    ["Kata 'menurut saya' dalam teks tanggapan termasuk...", ["Konjungsi", "Kata penyandang opini", "Kata evaluatif", "Kata saran"], 1, "'Menurut saya' adalah kata penyandang opini yang memperhalus tanggapan."],
    ["Bagian deskripsi dalam teks tanggapan berisi...", ["Kesimpulan", "Uraian kelebihan dan kekurangan", "Pengenalan objek", "Saran"], 1, "Deskripsi berisi gambaran rinci tentang kelebihan dan kekurangan objek."],
    ["Mengapa kritik dalam teks tanggapan sebaiknya diawali dengan apresiasi?", ["Agar terlihat pintar", "Agar kritik lebih mudah diterima", "Agar lebih panjang", "Tidak perlu diawali"], 1, "Apresiasi di awal membuat penerima lebih terbuka terhadap kritik yang akan disampaikan."],
    ["Kalimat 'Meskipun demikian, secara keseluruhan karya ini layak diapresiasi' merupakan bagian...", ["Konteks", "Penegasan", "Deskripsi", "Pembukaan"], 1, "Kalimat tersebut merupakan simpulan dan apresiasi akhir di bagian penegasan."],
    ["Contoh kalimat saran yang tepat dalam teks tanggapan adalah...", ["Ini salah semua", "Alangkah baiknya jika ditambahkan grafik", "Karya ini buruk", "Tidak berguna"], 1, "'Alangkah baiknya' adalah kalimat saran yang santun dan membangun."],
    ["Yang BUKAN termasuk etika memberi tanggapan adalah...", ["Menggunakan bahasa santun", "Menyerang pribadi pencipta karya", "Memberi saran konkret", "Mendahulukan apresiasi"], 1, "Menyerang pribadi adalah pelanggaran etika — tanggapi karya, bukan orangnya."],
    ["Teks tanggapan yang baik sebaiknya diakhiri dengan...", ["Tidak ada akhir", "Kesimpulan dan harapan", "Kritik pedas", "Pertanyaan"], 1, "Penegasan berisi kesimpulan dan harapan atau rekomendasi untuk perbaikan ke depan."],
  ]),
}

export default konten
