import type { Konten } from "../types"
import { makeSoal } from "../types"

const konten: Konten = {
  belajar: {
    tujuan: [
      "Memahami pengertian dan tujuan teks diskusi",
      "Mengidentifikasi struktur teks diskusi dengan tepat",
      "Menganalisis kaidah kebahasaan dalam teks diskusi",
      "Menyusun teks diskusi yang memuat argumen pro dan kontra secara seimbang",
    ],
    materi: [
      {
        judul: "Apa Itu Teks Diskusi?",
        isi: [
          "Ketika kamu dan teman-teman berdebat tentang 'Apakah lebih baik belajar online atau offline?', lalu masing-masing menyampaikan alasan — itulah awal dari teks diskusi! Bedanya, dalam teks diskusi semua pendapat disusun rapi, seimbang, dan objektif.",
          "",
          "Teks diskusi adalah teks yang menyajikan dua sudut pandang berbeda terhadap suatu isu — yaitu argumen yang mendukung (pro) dan argumen yang menentang (kontra). Tujuan teks diskusi bukan untuk memenangkan salah satu pihak, melainkan untuk memberikan gambaran komprehensif agar pembaca dapat mengambil kesimpulan sendiri.",
          "",
          "✓ Ciri-ciri teks diskusi:",
          "  ✓ Menyajikan dua sisi argumen (pro dan kontra) secara seimbang",
          "  ✓ Bersifat objektif — tidak memihak salah satu argumen",
          "  ✓ Menggunakan data, fakta, dan alasan logis untuk mendukung argumen",
          "  ✓ Diakhiri dengan simpulan yang bijak dan seimbang",
          "  ✓ Menggunakan bahasa yang santun dan tidak provokatif",
          "",
          "PENTING: Teks diskusi berbeda dengan teks debat. Dalam debat, tujuannya adalah memenangkan argumen. Dalam teks diskusi, tujuannya adalah menyajikan berbagai pandangan untuk bahan pertimbangan.",
          "",
          "[Ilustrasi: Sekelompok siswa duduk melingkar di ruang kelas modern. Di papan tulis tertulis 'PRO vs KONTRA' dengan garis pemisah di tengah. Seorang guru berdiri di samping papan dengan sikap netral. Beberapa siswa mengangkat tangan, yang lain mencatat. Gaya ilustrasi kartun dengan warna biru dan hijau.]",
        ],
        contoh: [
          "Perbandingan debat dan teks diskusi:",
          "",
          "DEBAT: \"Saya yakin belajar online lebih baik. Poin pertama... Saya menolak argumen lawan karena...\"",
          "✓ Fokus: memenangkan argumen, mengalahkan lawan.",
          "",
          "TEKS DISKUSI: \"Belajar online menawarkan fleksibilitas waktu dan tempat. Di sisi lain, belajar offline memungkinkan interaksi langsung yang lebih bermakna. Keduanya memiliki kelebihan dan kekurangan.\"",
          "✓ Fokus: menyajikan dua sudut pandang secara seimbang untuk bahan pertimbangan.",
        ],
      },
      {
        judul: "Struktur Teks Diskusi",
        isi: [
          "Agar argumen pro dan kontra tersaji rapi, teks diskusi mengikuti struktur berikut:",
          "",
          "1. ISU (Pendahuluan)",
          "  • Pengenalan topik atau masalah yang akan didiskusikan",
          "  • Latar belakang mengapa isu ini penting untuk dibahas",
          "  • Pernyataan umum yang memicu dua pandangan berbeda",
          "",
          "2. ARGUMEN PRO (Mendukung)",
          "  • Paparan alasan dan bukti yang mendukung isu",
          "  • Data atau fakta yang memperkuat posisi pro",
          "  • Biasanya diawali dengan 'Pihak yang setuju berpendapat...'",
          "",
          "3. ARGUMEN KONTRA (Menentang)",
          "  • Paparan alasan dan bukti yang menentang isu",
          "  • Data atau fakta yang memperkuat posisi kontra",
          "  • Biasanya diawali dengan 'Di sisi lain...' atau 'Namun, pihak yang tidak setuju...'",
          "",
          "4. SIMPULAN (Kesimpulan)",
          "  • Rangkuman dari kedua argumen tanpa memihak",
          "  • Bisa berisi rekomendasi atau saran berdasarkan pertimbangan kedua sisi",
          "  • Menutup diskusi dengan bijak",
          "",
          "[Ilustrasi: Diagram timbangan dengan dua piringan seimbang. Piringan kiri bertuliskan 'PRO' dengan panah ke bawah menunjukkan argumen pendukung. Piringan kanan bertuliskan 'KONTRA' dengan panah ke bawah menunjukkan argumen penentang. Di tengah tiang timbangan, bertuliskan 'ISU'. Di dasar timbangan, 'SIMPULAN'.]",
        ],
        contoh: [
          "ISU: \"Belajar online semakin populer sejak pandemi. Namun, sebagian orang merasa belajar offline lebih efektif. Mana yang sebenarnya lebih baik?\"",
          "",
          "ARGUMEN PRO: \"Pihak yang mendukung belajar online berpendapat bahwa teknologi memungkinkan siswa belajar dari mana saja. Tidak perlu macet di jalan, biaya transportasi hemat, dan materi dapat diakses kapan pun. Sebuah studi menunjukkan bahwa 70% siswa merasa lebih fokus belajar di rumah.\"",
          "",
          "ARGUMEN KONTRA: \"Di sisi lain, belajar offline dinilai lebih efektif untuk interaksi sosial. Siswa bisa bertanya langsung, berdiskusi dengan teman, dan mendapat bimbingan tatap muka dari guru. Banyak orang tua juga khawatir anak-anak terlalu lama di depan layar.\"",
          "",
          "SIMPULAN: \"Baik belajar online maupun offline memiliki kelebihan dan kekurangan. Solusi terbaik adalah menggabungkan keduanya — belajar online untuk fleksibilitas dan offline untuk interaksi sosial yang mendalam.\"",
        ],
      },
      {
        judul: "Kaidah Kebahasaan Teks Diskusi",
        isi: [
          "Teks diskusi menggunakan bahasa yang khas agar argumen tersampaikan dengan jelas dan santun.",
          "",
          "1. KONJUNGSI PERTENTANGAN: tetapi, namun, di sisi lain, sebaliknya, sementara itu — untuk mempertentangkan argumen pro dan kontra.",
          "2. KATA MODALITAS: seharusnya, sebaiknya, mungkin, pasti, harus, akan — menyatakan sikap atau keyakinan terhadap argumen.",
          "3. KONJUNGSI KAUSAL: sebab, karena, oleh karena itu, sehingga — menghubungkan sebab-akibat dalam argumen.",
          "4. KATA RUJUKAN: berdasarkan data, menurut penelitian, berdasarkan fakta — merujuk pada sumber informasi.",
          "5. KATA KERJA MENTAL: berpendapat, meyakini, menganggap, merasa — menyatakan pikiran atau perasaan.",
          "6. KOSAKATA EVALUATIF: penting, efektif, bermanfaat, merugikan, menguntungkan — menilai sesuatu dalam argumen.",
          "",
          "[Ilustrasi: Sebuah infografis berbentuk roda dengan 6 jari-jari. Pusat roda bertuliskan 'BAHASA DISKUSI'. Setiap jari-jari menuju ke satu lingkaran berisi: panah bertentangan (konjungsi pertentangan), wajah dengan ekspresi ragu (modalitas), rantai (kausal), buku (rujukan), otak (kata kerja mental), dan bintang (evaluatif).]",
        ],
        contoh: [
          "PENGGUNAAN KONJUNGSI PERTENTANGAN:",
          "\"Belajar online lebih fleksibel. NAMUN, interaksi sosial di kelas offline tidak bisa digantikan.\"",
          "",
          "PENGGUNAAN MODALITAS:",
          "\"Pemerintah SEHARUSNYA menyediakan akses internet gratis untuk mendukung belajar online.\"",
          "",
          "PENGGUNAAN KONJUNGSI KAUSAL:",
          "\"SEBAB keterbatasan perangkat, banyak siswa di daerah tertinggal tidak bisa mengikuti belajar online.\"",
          "",
          "PENGGUNAAN KATA KERJA MENTAL:",
          "\u201CBanyak ahli BERKEYAKINAN bahwa pendidikan tatap muka lebih efektif.\u201D",
        ],
      },
    ],
    rangkuman: [
      "[Ilustrasi: Lingkaran diskusi di ruang kelas dengan enam siswa duduk melingkar. Seorang siswa memegang tongkat bicara. Di papan tulis, diagram pro-kontra dengan titik-titik argumen. Gaya ilustrasi kartun kolaboratif dengan warna hijau dan oranye.]",
      "Teks diskusi menyajikan dua sudut pandang (pro dan kontra) terhadap suatu isu secara seimbang dan objektif.",
      "Struktur teks diskusi: Isu → Argumen Pro → Argumen Kontra → Simpulan.",
      "Kaidah kebahasaan: konjungsi pertentangan, modalitas, konjungsi kausal, kata rujukan, kata kerja mental, dan kosakata evaluatif.",
      "Teks diskusi berbeda dari debat — tujuannya menyajikan informasi seimbang, bukan memenangkan argumen.",
    ],
  },
  latihan: makeSoal([
    ["Apa tujuan utama teks diskusi?", ["Memenangkan argumen", "Menyajikan dua sudut pandang secara seimbang", "Menghibur pembaca", "Mengiklankan produk"], 1, "Teks diskusi bertujuan menyajikan argumen pro dan kontra secara seimbang."],
    ["Struktur teks diskusi yang benar adalah...", ["Argumen pro - Argumen kontra - Isu - Simpulan", "Isu - Argumen pro - Argumen kontra - Simpulan", "Simpulan - Isu - Argumen pro - Argumen kontra", "Isu - Simpulan - Argumen pro - Argumen kontra"], 1, "Urutan: Isu → Argumen Pro → Argumen Kontra → Simpulan."],
    ["Bagian yang berisi pengenalan topik diskusi disebut...", ["Isu", "Argumen", "Simpulan", "Penutup"], 0, "Isu adalah bagian pendahuluan yang mengenalkan topik yang akan didiskusikan."],
    ["Kata 'di sisi lain', 'sebaliknya' termasuk jenis konjungsi...", ["Kausal", "Pertentangan", "Kronologis", "Tujuan"], 1, "Konjungsi pertentangan digunakan untuk mempertentangkan argumen pro dan kontra."],
    ["Apa perbedaan teks diskusi dengan debat?", ["Teks diskusi lebih panjang", "Teks diskusi menyajikan seimbang, debat bertujuan menang", "Tidak ada perbedaan", "Debat lebih santun"], 1, "Teks diskusi menyajikan argumen seimbang; debat bertujuan memenangkan argumen."],
    ["Kata 'seharusnya', 'mungkin', 'pasti' termasuk jenis kata...", ["Konjungsi", "Modalitas", "Kata kerja", "Kata benda"], 1, "Kata modalitas menyatakan sikap atau keyakinan terhadap argumen."],
    ["Contoh kata kerja mental yang tepat adalah...", ["Berlari", "Berpendapat", "Memasak", "Menulis"], 1, "'Berpendapat' adalah kata kerja mental yang menyatakan aktivitas pikiran."],
    ["Bagian yang berisi argumen pihak yang tidak setuju disebut...", ["Isu", "Argumen pro", "Argumen kontra", "Simpulan"], 2, "Argumen kontra berisi pandangan pihak yang menentang isu."],
    ["Fungsi konjungsi kausal dalam teks diskusi adalah...", ["Mempertentangkan dua hal", "Menunjukkan hubungan sebab-akibat", "Menunjukkan urutan waktu", "Menyatakan tujuan"], 1, "Konjungsi kausal (sebab, karena, sehingga) menunjukkan hubungan sebab-akibat."],
    ["Simpulan dalam teks diskusi sebaiknya...", ["Memihak salah satu argumen", "Netral dan bijak", "Memprovokasi pembaca", "Tidak ada hubungan dengan isu"], 1, "Simpulan harus netral, merangkum kedua argumen tanpa memihak."],
  ]),
  praktik: {
    petunjuk: "Buatlah teks diskusi dengan tema 'Belajar Online vs Belajar Offline: Mana yang Lebih Efektif?'! Gunakan struktur isu-argumen pro-argumen kontra-simpulan dengan argumen seimbang di setiap sisi.",
    tips: [
      "Kumpulkan 3 alasan pro dan 3 alasan kontra sebelum mulai menulis",
      "Gunakan data dan fakta pendukung untuk memperkuat setiap argumen",
      "Pastikan porsi argumen pro dan kontra seimbang (tidak berat sebelah)",
      "Gunakan konjungsi pertentangan (namun, di sisi lain) saat beralih antar argumen",
      "Akhiri dengan simpulan yang merangkum kedua sisi secara bijak",
    ],
    contoh: "Minimal 4 paragraf: 1 paragraf isu, 1 paragraf argumen pro, 1 paragraf argumen kontra, dan 1 paragraf simpulan. Setiap paragraf minimal 3 kalimat.",
  },
  kuis: makeSoal([
    ["Yang dimaksud dengan teks diskusi adalah...", ["Teks yang memihak salah satu argumen", "Teks yang menyajikan pro dan kontra secara seimbang", "Teks yang berisi instruksi", "Teks yang menceritakan pengalaman"], 1, "Teks diskusi menyajikan dua sudut pandang secara seimbang."],
    ["Bagian 'Isu' dalam teks diskusi berfungsi untuk...", ["Menyimpulkan argumen", "Mengenalkan topik diskusi", "Menentang argumen", "Mendukung argumen"], 1, "Isu berfungsi mengenalkan topik dan latar belakang diskusi."],
    ["Contoh kalimat yang menunjukkan argumen kontra adalah...", ["Pihak yang setuju mengatakan...", "Di sisi lain, banyak yang khawatir...", "Berdasarkan data...", "Kesimpulannya..."], 1, "'Di sisi lain' menandakan peralihan ke argumen kontra."],
    ["Kata 'berdasarkan penelitian' termasuk dalam kategori...", ["Konjungsi", "Kata rujukan", "Modalitas", "Kata kerja"], 1, "Kata rujukan merujuk pada sumber informasi untuk memperkuat argumen."],
    ["Teks diskusi bersifat objektif. Artinya...", ["Memihak penulis", "Tidak memihak dan berdasarkan fakta", "Hanya menyajikan pro", "Hanya menyajikan kontra"], 1, "Objektif berarti tidak memihak dan didasarkan pada fakta."],
    ["Mengapa teks diskusi menggunakan konjungsi pertentangan?", ["Agar lebih panjang", "Untuk mempertentangkan argumen pro dan kontra", "Agar lebih indah", "Untuk menunjukkan waktu"], 1, "Konjungsi pertentangan digunakan untuk menghubungkan argumen yang berlawanan."],
    ["Contoh kata modalitas dalam teks diskusi adalah...", ["dan", "seharusnya", "tetapi", "karena"], 1, "'Seharusnya' adalah kata modalitas yang menyatakan sikap atau keyakinan."],
    ["Bagian yang berisi argumen pihak yang mendukung disebut...", ["Isu", "Argumen pro", "Argumen kontra", "Simpulan"], 1, "Argumen pro berisi pandangan dan alasan pihak yang mendukung isu."],
    ["Kalimat 'Oleh karena itu, diperlukan kebijakan yang bijak' menggunakan konjungsi...", ["Pertentangan", "Kausal", "Kronologis", "Tujuan"], 1, "'Oleh karena itu' adalah konjungsi kausal yang menunjukkan akibat."],
    ["Simpulan dalam teks diskusi yang baik adalah...", ["Menyalahkan salah satu pihak", "Merangkum kedua argumen tanpa memihak", "Mengulang isu saja", "Tidak memberikan rekomendasi"], 1, "Simpulan merangkum kedua sisi argumen secara netral dan bijak."],
  ]),
}

export default konten
