import type { Konten } from "../types"
import { makeSoal } from "../types"

const konten: Konten = {
  belajar: {
    tujuan: [
      "Memahami pengertian dan tujuan teks eksplanasi",
      "Mengidentifikasi struktur teks eksplanasi dengan tepat",
      "Menganalisis kaidah kebahasaan dalam teks eksplanasi",
      "Menyusun teks eksplanasi tentang fenomena alam atau sosial",
    ],
    materi: [
      {
        judul: "Apa Itu Teks Eksplanasi?",
        isi: [
          "Pernahkah kamu bertanya-tanya, 'Mengapa gunung berapi meletus?' atau 'Bagaimana proses terjadinya pelangi?' Jawaban dari pertanyaan-pertanyaan itulah yang dijelaskan dalam teks eksplanasi!",
          "",
          "Teks eksplanasi adalah teks yang menjelaskan proses terjadinya suatu fenomena — baik fenomena alam (gunung meletus, gempa bumi, pelangi) maupun fenomena sosial (kemacetan, tawuran, tradisi) — secara ilmiah dan logis.",
          "",
          "✓ Ciri-ciri teks eksplanasi:",
          "  ✓ Menjelaskan 'mengapa' dan 'bagaimana' suatu fenomena terjadi",
          "  ✓ Bersifat faktual dan ilmiah — berdasarkan data dan teori yang valid",
          "  ✓ Menggunakan istilah teknis yang berkaitan dengan fenomena",
          "  ✓ Disusun secara kronologis (urutan waktu) atau kausal (sebab-akibat)",
          "  ✓ Informatif dan objektif — tidak bertujuan memengaruhi pembaca",
          "",
          "[Ilustrasi: Sebuah diagram besar menampilkan siklus air — dari laut menguap, membentuk awan, lalu turun sebagai hujan ke gunung dan sungai, kembali ke laut. Di pojok, seorang anak berdiri dengan buku catatan, memandang kagum. Gaya ilustrasi infografis sains dengan warna biru-putih.]",
        ],
        contoh: [
          "Perbedaan teks eksplanasi dengan teks lain:",
          "",
          "TEKS DESKRIPSI: \"Gunung Merapi adalah gunung berapi di Jawa Tengah, memiliki ketinggian 2.930 meter.\"",
          "✓ Mendeskripsikan apa adanya, tanpa menjelaskan proses.",
          "",
          "TEKS EKSPLANASI: \"Gunung Merapi meletus karena tekanan magma di dalam perut bumi meningkat. Magma yang mengandung gas bergerak naik ke permukaan melalui saluran vulkanik. Ketika tekanan mencapai puncak, terjadi letusan yang menyemburkan abu vulkanik, lava, dan material piroklastik.\"",
          "✓ Menjelaskan proses dan penyebab secara ilmiah.",
        ],
      },
      {
        judul: "Struktur Teks Eksplanasi",
        isi: [
          "Agar penjelasan mudah dipahami, teks eksplanasi disusun dalam tiga bagian utama:",
          "",
          "1. PERNYATAAN UMUM (Identifikasi Fenomena)",
          "  • Pengenalan fenomena yang akan dijelaskan",
          "  • Definisi atau gambaran umum tentang fenomena tersebut",
          "  • Informasi latar belakang yang diperlukan pembaca",
          "",
          "2. DERETAN PENJELASAN (Proses Terjadinya)",
          "  • Urutan proses terjadinya fenomena secara kronologis atau kausal",
          "  • Penjelasan detail tentang tahapan atau penyebab fenomena",
          "  • Bisa terdiri dari beberapa paragraf — setiap paragraf menjelaskan satu tahap",
          "  • Menggunakan istilah teknis dan data pendukung",
          "",
          "3. INTERPRETASI (Penutup)",
          "  • Kesimpulan atau rangkuman dari penjelasan yang telah dipaparkan",
          "  • Bisa berisi pandangan atau opini penulis yang relevan",
          "  • Tidak wajib ada — beberapa teks eksplanasi langsung selesai setelah deretan penjelasan",
          "",
          "[Ilustrasi: Tiga kotak berjejer horizontal dengan panah besar menghubungkan. Kotak 1 (biru muda) 'PERNYATAAN UMUM — Pengenalan fenomena'. Kotak 2 (biru sedang) 'DERETAN PENJELASAN — Proses dan penyebab'. Kotak 3 (biru tua) 'INTERPRETASI — Kesimpulan'. Masing-masing memiliki ikon: kaca pembesar, gear/siklus, dan bintang.]",
        ],
        contoh: [
          "Analisis struktur teks eksplanasi 'Proses Terjadinya Pelangi':",
          "",
          "PERNYATAAN UMUM: \"Pelangi adalah fenomena optik yang terjadi ketika cahaya matahari dibiaskan oleh tetesan air hujan, menghasilkan spektrum warna di langit.\"",
          "",
          "DERETAN PENJELASAN: \"Proses terjadinya pelangi dimulai ketika cahaya matahari memasuki tetesan air hujan. Cahaya tersebut dibelokkan (refraksi) dan diuraikan menjadi warna-warna penyusunnya — merah, jingga, kuning, hijau, biru, nila, ungu. Kemudian, cahaya dipantulkan di bagian dalam tetesan air dan keluar kembali ke arah pengamat. Inilah mengapa pelangi selalu terlihat seperti busur di langit.\"",
          "",
          "INTERPRETASI: \"Pelangi adalah salah satu keajaiban alam yang menunjukkan betapa indahnya interaksi antara cahaya dan air. Memahami proses ilmiahnya justru membuat kita semakin kagum.\"",
        ],
      },
      {
        judul: "Kaidah Kebahasaan Teks Eksplanasi",
        isi: [
          "Teks eksplanasi menggunakan bahasa yang khas untuk menyampaikan informasi ilmiah secara jelas dan logis.",
          "",
          "1. KONJUNGSI KAUSAL: sebab, karena, oleh karena itu, sehingga, akibatnya — untuk menunjukkan hubungan sebab-akibat dalam proses fenomena.",
          "2. KONJUNGSI KRONOLOGIS: kemudian, selanjutnya, lalu, setelah itu, pada akhirnya — untuk menunjukkan urutan waktu proses.",
          "3. ISTILAH TEKNIS: istilah khusus yang berkaitan dengan bidang ilmu — evaporasi, magma, fotosintesis, lempeng tektonik, refraksi.",
          "4. KATA KERJA MATERIAL: meletus, menguap, membeku, mencair, bergerak — kata kerja yang menunjukkan tindakan fisik atau proses.",
          "5. KATA KERJA RELASIONAL: adalah, merupakan, yaitu, yakni — untuk mendefinisikan atau mengidentifikasi.",
          "6. KALIMAT PASIF: 'Air dipanaskan oleh sinar matahari', 'Magma didorong ke permukaan' — menekankan pada proses, bukan pelaku.",
          "",
          "[Ilustrasi: Buku sains terbuka menampilkan halaman dengan enam highlight berwarna. Highlight pertama (merah) 'kausal', kedua (oranye) 'kronologis', ketiga (kuning) 'istilah teknis', keempat (hijau) 'kata kerja material', kelima (biru) 'kata relasional', keenam (ungu) 'kalimat pasif'. Masing-masing dengan contoh kata.]",
        ],
        contoh: [
          "Penerapan kaidah kebahasaan dalam teks eksplanasi 'Gempa Bumi':",
          "",
          "\"Gempa bumi terjadi SEBAB pergerakan lempeng tektonik di kerak bumi. (konjungsi kausal) Lempeng-lempeng ini SALING BERGESER dan MENUMBUK satu sama lain. (kata kerja material) Ketika tekanan yang terkumpul AKHIRNYA mencapai batas maksimal, (konjungsi kronologis) terjadi pelepasan energi yang disebut gelombang seismik. GEMPA BUMI ADALAH getaran yang merambat melalui permukaan bumi. (kata relasional) Kekuatan gempa diukur menggunakan SKALA RICHTER. (istilah teknis)\"",
        ],
      },
    ],
    rangkuman: [
      "[Ilustrasi: Seorang siswa menjelaskan di depan kelas dengan pointer di tangan, menunjuk diagram siklus air di papan tulis interaktif. Wajah teman-teman sekelas tampak antusias. Gaya ilustrasi sains edukatif dengan warna biru dan putih.]",
      "Teks eksplanasi menjelaskan proses terjadinya fenomena alam atau sosial secara ilmiah dan logis.",
      "Struktur teks eksplanasi: Pernyataan umum → Deretan penjelasan → Interpretasi (opsional).",
      "Kaidah kebahasaan: konjungsi kausal/kronologis, istilah teknis, kata kerja material/relasional, dan kalimat pasif.",
      "Teks eksplanasi bersifat informatif dan objektif — menjelaskan tanpa memengaruhi pembaca.",
    ],
  },
  latihan: makeSoal([
    ["Apa tujuan utama teks eksplanasi?", ["Menghibur pembaca", "Menjelaskan proses terjadinya fenomena", "Mengajak melakukan sesuatu", "Menceritakan pengalaman"], 1, "Teks eksplanasi bertujuan menjelaskan proses terjadinya fenomena secara ilmiah."],
    ["Struktur teks eksplanasi yang tepat adalah...", ["Pernyataan umum - Deretan penjelasan - Interpretasi", "Orientasi - Komplikasi - Resolusi", "Isu - Argumen - Simpulan", "Pembukaan - Isi - Penutup"], 0, "Struktur: Pernyataan umum → Deretan penjelasan → Interpretasi."],
    ["Bagian yang berisi pengenalan fenomena secara umum disebut...", ["Deretan penjelasan", "Interpretasi", "Pernyataan umum", "Kesimpulan"], 2, "Pernyataan umum berisi pengenalan dan gambaran umum fenomena."],
    ["Kata 'sebab', 'karena', 'oleh karena itu' termasuk jenis konjungsi...", ["Kronologis", "Kausal", "Pertentangan", "Tujuan"], 1, "Konjungsi kausal menunjukkan hubungan sebab-akibat."],
    ["Contoh istilah teknis dalam teks eksplanasi tentang gunung berapi adalah...", ["Indah", "Magma", "Cantik", "Besar"], 1, "'Magma' adalah istilah teknis dalam ilmu vulkanologi."],
    ["Kata kerja material dalam teks eksplanasi berfungsi untuk...", ["Menunjukkan perasaan", "Menunjukkan proses fisik", "Mendefinisikan", "Menghubungkan kalimat"], 1, "Kata kerja material menunjukkan tindakan fisik seperti meletus, menguap, bergerak."],
    ["Fungsi konjungsi kronologis dalam teks eksplanasi adalah...", ["Menunjukkan sebab-akibat", "Menunjukkan urutan waktu", "Mempertentangkan ide", "Menambahkan informasi"], 1, "Konjungsi kronologis (kemudian, selanjutnya) menunjukkan urutan waktu proses."],
    ["Kalimat 'Air di laut menguap karena panas matahari' menggunakan pola kalimat...", ["Aktif", "Pasif", "Imperatif", "Tanya"], 0, "Kalimat aktif transitif dengan subjek 'Air' yang melakukan tindakan 'menguap'."],
    ["Teks eksplanasi bersifat faktual dan ilmiah. Maksudnya adalah...", ["Berdasarkan imajinasi", "Berdasarkan data dan teori yang valid", "Berdasarkan opini", "Berdasarkan perasaan"], 1, "Faktual berarti berdasarkan fakta dan data ilmiah yang dapat diverifikasi."],
    ["Bagian interpretasi dalam teks eksplanasi bersifat...", ["Wajib ada", "Opsional", "Lebih penting dari yang lain", "Tidak perlu"], 1, "Interpretasi bersifat opsional — beberapa teks eksplanasi tidak menyertakannya."],
  ]),
  praktik: {
    petunjuk: "Buatlah teks eksplanasi tentang proses terjadinya hujan! Gunakan struktur pernyataan umum - deretan penjelasan - interpretasi serta sertakan istilah teknis seperti evaporasi, kondensasi, dan presipitasi.",
    tips: [
      "Mulailah dengan definisi umum tentang hujan dan mengapa fenomena ini terjadi",
      "Jelaskan prosesnya secara berurutan: evaporasi (penguapan) → kondensasi (pembentukan awan) → presipitasi (turunnya hujan)",
      "Gunakan minimal 3 konjungsi kausal dan 2 konjungsi kronologis",
      "Sertakan istilah teknis yang relevan seperti evaporasi, kondensasi, presipitasi, dan siklus hidrologi",
      "Akhiri dengan interpretasi yang merangkum pentingnya siklus hujan bagi kehidupan",
    ],
    contoh: "Minimal 3 paragraf: 1 paragraf pernyataan umum, 1-2 paragraf deretan penjelasan, dan 1 paragraf interpretasi. Gunakan kalimat efektif dan bahasa Indonesia yang baik.",
  },
  kuis: makeSoal([
    ["Yang dimaksud dengan teks eksplanasi adalah...", ["Teks yang menceritakan kisah fiksi", "Teks yang menjelaskan proses fenomena secara ilmiah", "Teks yang mengajak pembaca", "Teks yang melaporkan percobaan"], 1, "Teks eksplanasi menjelaskan proses terjadinya fenomena secara ilmiah."],
    ["Contoh fenomena sosial yang bisa dijelaskan dalam teks eksplanasi adalah...", ["Pelangi", "Kemacetan lalu lintas", "Gempa bumi", "Fotosintesis"], 1, "Kemacetan lalu lintas adalah fenomena sosial yang dapat dijelaskan dengan teks eksplanasi."],
    ["Kata 'evaporasi', 'kondensasi', 'presipitasi' termasuk...", ["Konjungsi", "Istilah teknis", "Kata kerja material", "Kata relasional"], 1, "Istilah teknis adalah kata-kata khusus yang berkaitan dengan bidang ilmu tertentu."],
    ["Bagian deretan penjelasan dalam teks eksplanasi berfungsi untuk...", ["Mengenalkan fenomena", "Menjelaskan proses dan penyebab", "Menyimpulkan", "Memberi opini"], 1, "Deretan penjelasan menguraikan proses dan penyebab terjadinya fenomena."],
    ["Perbedaan teks eksplanasi dengan teks deskripsi adalah...", ["Teks deskripsi lebih panjang", "Eksplanasi menjelaskan proses, deskripsi menggambarkan", "Teks eksplanasi fiksi", "Tidak ada perbedaan"], 1, "Eksplanasi menjelaskan proses terjadinya; deskripsi menggambarkan sesuatu apa adanya."],
    ["Kata kerja relasional dalam teks eksplanasi berfungsi untuk...", ["Menunjukkan hubungan sebab-akibat", "Mendefinisikan atau mengidentifikasi", "Menunjukkan urutan waktu", "Menunjukkan tindakan fisik"], 1, "Kata kerja relasional (adalah, merupakan) digunakan untuk mendefinisikan."],
    ["Kalimat 'Magma didorong ke permukaan bumi' adalah contoh kalimat...", ["Aktif", "Pasif", "Imperatif", "Tanya"], 1, "Kalimat pasif dengan awalan 'di-' (didorong) menekankan pada proses."],
    ["Mengapa teks eksplanasi banyak menggunakan istilah teknis?", ["Agar terlihat sulit", "Karena menjelaskan fenomena ilmiah yang memerlukan istilah khusus", "Agar lebih panjang", "Karena aturan bahasa"], 1, "Istilah teknis diperlukan untuk menjelaskan fenomena ilmiah secara tepat."],
    ["Bagian interpretasi dapat berisi...", ["Proses terjadinya", "Kesimpulan atau pandangan penulis", "Definisi fenomena", "Urutan kronologis"], 1, "Interpretasi berisi kesimpulan atau pandangan penulis yang relevan."],
    ["Konjungsi kronologis yang tepat untuk teks eksplanasi adalah...", ["Sebab", "Selanjutnya", "Tetapi", "Oleh karena itu"], 1, "'Selanjutnya' menunjukkan urutan waktu dalam proses."],
  ]),
}

export default konten
