import type { Konten } from "../types"
import { makeSoal } from "../types"

const konten: Konten = {
  belajar: {
    tujuan: [
      "Memahami pengertian, ciri, dan jenis teks laporan",
      "Mengidentifikasi struktur teks laporan secara tepat",
      "Menganalisis kaidah kebahasaan teks laporan",
      "Menyusun teks laporan berdasarkan data dan observasi",
    ],
    materi: [
      {
        judul: "Apa Itu Laporan?",
        isi: [
          "Pernahkah kamu diminta guru untuk menceritakan hasil pengamatan di laboratorium atau kegiatan pramuka secara tertulis? Catatan terstruktur itulah yang disebut laporan!",
          "",
          "Teks laporan adalah teks yang menyajikan informasi tentang suatu objek, peristiwa, atau kegiatan secara faktual, sistematis, dan objektif. Laporan bertujuan untuk memberikan data akurat kepada pembaca berdasarkan pengamatan atau penelitian yang telah dilakukan.",
          "",
          "✓ Ciri-ciri teks laporan:",
          "  ✓ Bersifat faktual — berdasarkan data nyata, bukan opini",
          "  ✓ Sistematis — disusun dengan struktur yang jelas",
          "  ✓ Objektif — tidak memihak atau dipengaruhi perasaan pribadi",
          "  ✓ Lengkap — mencakup semua aspek yang diamati",
          "  ✓ Menggunakan bahasa baku dan istilah teknis",
          "",
          "Jenis-jenis laporan berdasarkan tujuannya:",
          "",
          "1. LAPORAN OBSERVASI",
          "  Laporan hasil pengamatan terhadap suatu objek atau fenomena. Contoh: laporan pengamatan ekosistem sawah, laporan pengamatan perilaku hewan.",
          "",
          "2. LAPORAN KEGIATAN",
          "  Laporan tentang pelaksanaan suatu kegiatan atau acara. Contoh: laporan kegiatan bakti sosial, laporan pelaksanaan pramuka, laporan study tour.",
          "",
          "3. LAPORAN PERCOBAAN",
          "  Laporan hasil percobaan atau eksperimen ilmiah. Contoh: laporan percobaan fotosintesis, laporan uji kandungan vitamin C pada buah.",
          "",
          "[Ilustrasi: Seorang pelajar duduk di meja belajar dengan buku catatan terbuka dan pena di tangan. Di sekelilingnya ada tumpukan buku dan dokumen. Di layar komputer menampilkan grafik data. Gaya ilustrasi kartun edukatif dengan warna hijau dan biru.]",
        ],
        contoh: [
          "Perbedaan laporan observasi, kegiatan, dan percobaan:",
          "",
          "LAPORAN OBSERVASI: \"Berdasarkan pengamatan selama 3 hari di ekosistem sawah, ditemukan 5 jenis serangga, 3 jenis amfibi, dan 12 jenis tumbuhan air.\"",
          "✓ Fokus: mendeskripsikan objek berdasarkan pengamatan indra.",
          "",
          "LAPORAN KEGIATAN: \"Kegiatan bakti sosial dilaksanakan pada 15 Maret 2025 di Panti Asuhan Harapan. Kegiatan meliputi donor darah, bazar, dan hiburan anak-anak.\"",
          "✓ Fokus: melaporkan pelaksanaan kegiatan dari awal hingga akhir.",
          "",
          "LAPORAN PERCOBAAN: \"Percobaan ini bertujuan menguji kadar vitamin C pada jeruk dan apel. Jeruk mengandung 53 mg vitamin C per 100 gram, sedangkan apel hanya 4,6 mg per 100 gram.\"",
          "✓ Fokus: menyajikan data hasil percobaan dan kesimpulan ilmiah.",
        ],
      },
      {
        judul: "Struktur Laporan",
        isi: [
          "Setiap jenis laporan memiliki struktur dasar yang sama, meskipun ada penyesuaian tergantung jenisnya. Secara umum, struktur laporan terdiri dari tiga bagian utama:",
          "",
          "1. PENDAHULUAN",
          "  Berisi latar belakang, tujuan, dan ruang lingkup laporan. Bagian ini menjelaskan mengapa laporan dibuat dan apa yang hendak dicapai.",
          "  • Latar belakang: alasan dilakukannya observasi/kegiatan/percobaan",
          "  • Tujuan: target yang ingin dicapai",
          "  • Waktu dan tempat: kapan dan di mana kegiatan dilakukan",
          "",
          "2. ISI LAPORAN",
          "  Bagian inti yang menyajikan data, fakta, dan informasi hasil observasi/kegiatan/percobaan. Disajikan secara sistematis dengan kemungkinan sub-bagian.",
          "  • Objek/kegiatan yang diamati",
          "  • Proses pelaksanaan",
          "  • Data dan temuan (bisa berupa tabel, grafik, atau deskripsi)",
          "",
          "3. PENUTUP",
          "  Berisi simpulan dan saran. Simpulan menjawab tujuan laporan, saran memberikan rekomendasi berdasarkan hasil yang diperoleh.",
          "  • Simpulan: ringkasan hasil utama",
          "  • Saran: rekomendasi untuk perbaikan atau penelitian lanjutan",
          "",
          "[Ilustrasi: Diagram piramida terbalik tiga tingkat berlabel 'STRUKTUR LAPORAN'. Tingkat atas: PENDAHULUAN (latar belakang, tujuan). Tingkat tengah: ISI (data, temuan). Tingkat bawah: PENUTUP (simpulan, saran). Setiap tingkat dihubungkan panah vertikal.]",
        ],
        contoh: [
          "PENDAHULUAN: \"Observasi ekosistem hutan mangrove dilakukan di Muara Angke pada 10-12 Januari 2025. Tujuan observasi adalah mengidentifikasi keanekaragaman hayati di kawasan tersebut.\"",
          "",
          "ISI: \"Hasil pengamatan menunjukkan terdapat 3 jenis pohon mangrove (Rhizophora, Avicennia, Sonneratia), 5 jenis burung, dan 2 jenis kepiting. Suhu udara rata-rata 30°C dengan kelembaban 85%.\"",
          "",
          "PENUTUP: \"Ekosistem mangrove di Muara Angke memiliki keanekaragaman hayati yang cukup tinggi. Disarankan adanya program rehabilitasi untuk menjaga kelestarian kawasan ini.\"",
        ],
        catatan: "Meskipun struktur dasarnya sama, laporan kegiatan biasanya lebih menekankan pada urutan waktu pelaksanaan, sedangkan laporan observasi lebih menekankan pada deskripsi objek yang diamati.",
      },
      {
        judul: "Kaidah Kebahasaan Laporan",
        isi: [
          "Teks laporan memiliki kaidah kebahasaan yang khas dan berbeda dari teks narasi atau deskripsi biasa. Berikut kaidah-kaidahnya:",
          "",
          "1. KALIMAT PASIF",
          "  Subjek dikenai tindakan, bukan melakukan tindakan. Contoh: 'Pengamatan dilakukan selama 3 hari' (bukan 'Kami melakukan pengamatan').",
          "",
          "2. BAHASA BAKU",
          "  Menggunakan kosakata sesuai KBBI dan kaidah tata bahasa Indonesia yang benar. Hindari bahasa sehari-hari atau slang.",
          "",
          "3. DATA ANGKA DAN FAKTA",
          "  Laporan harus didukung data kuantitatif (angka, persentase, ukuran) dan fakta yang dapat diverifikasi.",
          "",
          "4. ISTILAH TEKNIS",
          "  Menggunakan istilah khusus yang sesuai dengan bidang laporan. Contoh dalam laporan biologi: spesies, habitat, ekosistem, biodiversitas.",
          "",
          "5. KONJUNGSI KRONOLOGIS DAN KAUSAL",
          "  Konjungsi kronologis: pertama, kemudian, selanjutnya, akhirnya. Konjungsi kausal: sebab, karena, oleh karena itu, sehingga.",
          "",
          "6. KATA KERJA AKTIF DAN PASIF",
          "  Kata kerja aktif: mengamati, mengukur, mengidentifikasi. Kata kerja pasif: diamati, diukur, diidentifikasi.",
          "",
          "[Ilustrasi: Papan tulis bertuliskan 'KAIDAH KEBAHASAAN LAPORAN' dengan enam tempelan sticky note. Setiap sticky note mewakili satu kaidah dengan ikon dan contoh singkat.]",
        ],
        contoh: [
          "SALAH: \"Kita ngeliat ada 3 jenis burung di hutan mangrove. Burung-burungnya pada bagus banget warnanya.\"",
          "✗ Bahasa tidak baku, subjektif, tanpa data.",
          "",
          "BENAR: \"Pengamatan mencatat 3 jenis burung di hutan mangrove Muara Angke, yaitu burung kuntul (Egretta garzetta), cerek (Charadrius sp.), dan raja udang (Alcedo coerulescens).\"",
          "✓ Bahasa baku, objektif, menggunakan istilah teknis dan data spesifik.",
          "",
          "SALAH: \"Menurut perkiraan kami, jumlah pohon mangrovenya banyak banget.\"",
          "✗ Subjektif, tanpa data kuantitatif.",
          "",
          "BENAR: \"Kepadatan pohon mangrove di lokasi 1 adalah 1.200 pohon per hektar, sedangkan di lokasi 2 sebanyak 850 pohon per hektar.\"",
          "✓ Data kuantitatif yang jelas dan terukur.",
        ],
      },
    ],
    rangkuman: [
      "[Ilustrasi: Seorang peneliti muda memegang clipboard dengan dokumen laporan lengkap, berdiri di samping infografis dinding yang menampilkan data statistik. Lingkungan kantor modern dengan tanaman hias. Gaya ilustrasi kartun profesional dengan warna hijau dan abu-abu.]",
      "Teks laporan menyajikan informasi faktual, sistematis, dan objektif tentang hasil observasi, kegiatan, atau percobaan.",
      "Tiga jenis laporan utama: laporan observasi (pengamatan objek), laporan kegiatan (pelaksanaan acara), laporan percobaan (hasil eksperimen).",
      "Struktur laporan: Pendahuluan (latar belakang, tujuan) → Isi (data, temuan) → Penutup (simpulan, saran).",
      "Kaidah kebahasaan: kalimat pasif, bahasa baku, data angka/fakta, istilah teknis, konjungsi kronologis/kausal, kata kerja aktif dan pasif.",
    ],
  },
  latihan: makeSoal([
    ["Apa tujuan utama dari teks laporan?", ["Menghibur pembaca", "Menyajikan informasi faktual secara sistematis", "Mempromosikan produk", "Menceritakan pengalaman pribadi"], 1, "Tujuan utama teks laporan adalah menyajikan informasi faktual dan objektif secara sistematis."],
    ["Manakah yang BUKAN merupakan ciri teks laporan?", ["Faktual", "Objektif", "Subjektif", "Sistematis"], 2, "Teks laporan bersifat objektif, bukan subjektif."],
    ["Laporan hasil pengamatan terhadap suatu objek atau fenomena disebut...", ["Laporan kegiatan", "Laporan observasi", "Laporan percobaan", "Laporan keuangan"], 1, "Laporan observasi adalah laporan hasil pengamatan terhadap objek atau fenomena."],
    ["Bagian laporan yang berisi latar belakang dan tujuan disebut...", ["Isi", "Penutup", "Pendahuluan", "Lampiran"], 2, "Pendahuluan berisi latar belakang, tujuan, waktu, dan tempat laporan."],
    ["Kata 'pertama, kemudian, selanjutnya, akhirnya' termasuk konjungsi...", ["Kausal", "Kronologis", "Pertentangan", "Perbandingan"], 1, "Kata-kata tersebut menunjukkan urutan waktu, disebut konjungsi kronologis."],
    ["Kalimat 'Observasi dilakukan di hutan mangrove Muara Angke' menggunakan pola...", ["Aktif", "Pasif", "Imperatif", "Tanya"], 1, "Kalimat tersebut menggunakan pola pasif dengan imbuhan di-."],
    ["Berikut adalah jenis laporan berdasarkan tujuannya, KECUALI...", ["Laporan observasi", "Laporan kegiatan", "Laporan fiksi", "Laporan percobaan"], 2, "Laporan fiksi bukan jenis laporan karena laporan bersifat faktual."],
    ["Bagian laporan yang berisi simpulan dan saran adalah...", ["Pendahuluan", "Isi", "Penutup", "Judul"], 2, "Penutup laporan berisi simpulan dan saran berdasarkan hasil yang diperoleh."],
    ["Mengapa laporan harus menggunakan bahasa baku?", ["Agar lebih panjang", "Menjaga kredibilitas dan objektivitas", "Karena lebih mudah ditulis", "Agar terlihat rumit"], 1, "Bahasa baku menjaga kredibilitas dan objektivitas laporan."],
    ["Contoh istilah teknis dalam laporan biologi adalah...", ["Indah", "Besar", "Ekosistem", "Cepat"], 2, "'Ekosistem' adalah istilah teknis biologi, sedangkan lainnya kata sifat umum."],
  ]),
  praktik: {
    petunjuk: "Lakukan observasi terhadap kebiasaan belajar seorang teman sekelasmu selama 3 hari. Catat pola belajar, waktu, tempat, dan metode yang digunakan. Buatlah laporan observasi lengkap dengan struktur yang benar!",
    tips: [
      "Amati teman yang bersedia diobservasi dan jelaskan tujuan observasi sebelumnya",
      "Catat hal-hal seperti jam mulai belajar, durasi, tempat belajar, metode (baca/catat/diskusi), dan gangguan yang muncul",
      "Gunakan tabel untuk menyajikan data observasi agar lebih rapi",
      "Simpulkan pola belajar temanmu dan berikan saran untuk meningkatkan efektivitas belajar",
    ],
    contoh: "Pastikan laporan memiliki pendahuluan (latar belakang, tujuan, waktu observasi), isi (data observasi dalam 3 hari), dan penutup (simpulan dan saran). Gunakan kalimat pasif dan bahasa baku.",
  },
  kuis: makeSoal([
    ["Apa perbedaan utama laporan observasi dan laporan kegiatan?", ["Tidak ada perbedaan", "Observasi fokus pada objek, kegiatan fokus pada acara", "Observasi lebih panjang", "Kegiatan tanpa data"], 1, "Observasi mengamati objek/fenomena, kegiatan melaporkan pelaksanaan acara."],
    ["Bagian laporan yang menjelaskan 'mengapa laporan dibuat' adalah...", ["Tujuan", "Latar belakang", "Simpulan", "Saran"], 1, "Latar belakang menjelaskan alasan atau mengapa laporan dibuat."],
    ["Kata 'sebab, karena, oleh karena itu' termasuk konjungsi...", ["Kronologis", "Kausal", "Pertentangan", "Koordinatif"], 1, "Konjungsi kausal menyatakan hubungan sebab-akibat."],
    ["Ciri kebahasaan yang menonjol dalam teks laporan adalah...", ["Majas personifikasi", "Kalimat pasif", "Dialog", "Sajak"], 1, "Kalimat pasif adalah ciri khas kebahasaan teks laporan."],
    ["Manakah kalimat yang menggunakan bahasa baku?", ["Observasi dilakuin 3 hari", "Pengamatan dilakukan selama 3 hari", "Ngelihatin objek 3 hari", "Observasinya 3 hari lamanya"], 1, "Kalimat 'Pengamatan dilakukan selama 3 hari' menggunakan bahasa baku dan pasif."],
    ["Fungsi data angka dalam laporan adalah...", ["Memperpanjang tulisan", "Memperkuat objektivitas dan keakuratan", "Membuat laporan sulit dipahami", "Menambah halaman"], 1, "Data angka memperkuat objektivitas dan keakuratan laporan."],
    ["Struktur laporan yang tepat adalah...", ["Penutup - Isi - Pendahuluan", "Isi - Pendahuluan - Penutup", "Pendahuluan - Isi - Penutup", "Pendahuluan - Penutup - Isi"], 2, "Urutan struktur laporan yang benar: Pendahuluan → Isi → Penutup."],
    ["'Berdasarkan hasil observasi, dapat disimpulkan bahwa...' Kalimat ini cocok untuk bagian...", ["Pendahuluan", "Isi", "Penutup", "Judul"], 2, "Kalimat tersebut merupakan ciri khas bagian penutup, khususnya simpulan."],
    ["Manakah yang termasuk istilah teknis?", ["Spesies", "Bagus", "Cantik", "Panas"], 0, "'Spesies' adalah istilah teknis biologi, sedangkan lainnya kata sifat umum."],
    ["Mengapa laporan harus objektif?", ["Agar pembaca percaya pada data yang disajikan", "Agar laporan lebih panjang", "Karena lebih mudah ditulis", "Agar penulis terkenal"], 0, "Objektivitas penting agar pembaca percaya pada data dan informasi yang disajikan."],
  ]),
}

export default konten
