import type { Konten } from "../types"
import { makeSoal } from "../types"

const konten: Konten = {
  belajar: {
    tujuan: [
      "Memahami pengertian, tujuan, dan jenis teks resensi",
      "Mengidentifikasi struktur teks resensi dengan tepat",
      "Menganalisis kaidah kebahasaan dalam teks resensi",
      "Menulis resensi buku atau film secara sistematis",
    ],
    materi: [
      {
        judul: "Apa Itu Resensi?",
        isi: [
          "Pernahkah kamu membaca ulasan sebuah film di media sosial atau website sebelum memutuskan menontonnya? Ulasan semacam itu termasuk resensi — tulisan yang mengupas isi, kelebihan, dan kekurangan suatu karya!",
          "",
          "Resensi adalah tulisan yang berisi penilaian, pembahasan, dan pertimbangan tentang suatu karya (buku, film, musik, atau karya seni lainnya). Tujuan resensi adalah memberikan informasi dan pandangan kritis kepada calon pembaca atau penonton agar mereka dapat mempertimbangkan karya tersebut.",
          "",
          "✓ Ciri-ciri resensi:",
          "  ✓ Berisi identitas karya yang diulas",
          "  ✓ Memberikan gambaran isi karya (sinopsis/ikhtisar)",
          "  ✓ Mengandung analisis dan penilaian kritis",
          "  ✓ Menyebutkan kelebihan dan kekurangan",
          "  ✓ Ditutup dengan simpulan dan rekomendasi",
          "",
          "Apa perbedaan resensi dengan ulasan biasa?",
          "",
          "ULASAN BIASA: \"Filmnya bagus banget! Aktornya ganteng-ganteng. Pokoknya recommended!\"",
          "✓ Hanya opini subjektif tanpa analisis mendalam.",
          "",
          "RESENSI: \"Film 'Bumi Manusia' berhasil menghadirkan latar kolonial dengan detail visual yang memukau. Namun, penonton yang tidak membaca novelnya mungkin kesulitan memahami lompatan waktu di babak kedua. Secara keseluruhan, film ini layak ditonton karena penggambaran konflik batin Minke yang kompleks.\"",
          "✓ Analisis kritis, menyebutkan kelebihan dan kekurangan, dengan alasan yang jelas.",
          "",
          "[Ilustrasi: Sebuah meja kayu dengan buku terbuka di tengah, secangkir kopi, dan kacamata. Di samping buku, sebuah laptop menampilkan halaman blog ulasan. Latar belakang rak buku penuh warna. Gaya ilustrasi cozy dengan warna cokelat dan krem.]",
        ],
        contoh: [
          "Contoh identitas buku dalam resensi:",
          "",
          "Judul Buku: Laskar Pelangi",
          "Penulis: Andrea Hirata",
          "Penerbit: Bentang Pustaka",
          "Tahun Terbit: 2005",
          "Tebal: 534 halaman",
          "ISBN: 978-979-3062-79-3",
          "",
          "Perbedaan resensi buku dan film:",
          "",
          "RESENSI BUKU: fokus pada gaya bahasa, alur cerita, pengembangan karakter, dan pesan penulis.",
          "RESENSI FILM: fokus pada sinematografi, akting, penyutradaraan, musik, dan efek visual.",
        ],
      },
      {
        judul: "Struktur Resensi",
        isi: [
          "Resensi yang baik memiliki struktur yang teratur sehingga mudah diikuti pembaca. Struktur resensi terdiri dari lima bagian utama:",
          "",
          "1. IDENTITAS KARYA",
          "  Data lengkap karya yang diresensi. Untuk buku: judul, penulis, penerbit, tahun terbit, tebal halaman, ISBN. Untuk film: judul, sutradara, penulis skenario, produser, tahun rilis, durasi, pemeran utama.",
          "",
          "2. PENDAHULUAN",
          "  Pembuka yang menarik perhatian pembaca. Bisa berupa latar belakang karya, popularitas penulis/sutradara, atau konteks yang membuat karya ini relevan.",
          "",
          "3. SINOPSIS/Ikhtisar",
          "  Ringkasan isi karya tanpa memberikan spoiler berlebihan. Sinopsis harus cukup informatif agar pembaca memahami tentang apa karya tersebut, tetapi tidak mengungkap seluruh kejutan cerita.",
          "",
          "4. ANALISIS",
          "  Bagian inti resensi yang berisi pembahasan dan penilaian kritis. Uraikan kelebihan dan kekurangan karya dengan argumen yang jelas.",
          "  • Untuk buku: gaya bahasa, alur, karakter, tema, pesan moral",
          "  • Untuk film: akting, sinematografi, arahan sutradara, musik, efek",
          "",
          "5. SIMPULAN",
          "  Penutup berisi simpulan akhir dan rekomendasi. Apakah karya ini layak dibaca/ditonton? Untuk siapa karya ini cocok?",
          "",
          "[Ilustrasi: Bagan vertikal berlabel 'STRUKTUR RESENSI' dengan 5 kotak berwarna. Kotak 1: Identitas Karya. Kotak 2: Pendahuluan. Kotak 3: Sinopsis. Kotak 4: Analisis (Kelebihan & Kekurangan). Kotak 5: Simpulan & Rekomendasi. Panah menghubungkan setiap kotak secara berurutan.]",
        ],
        contoh: [
          "Contoh penerapan struktur resensi:",
          "",
          "IDENTITAS: \"Film 'Ngeri-Ngeri Sedap' (2022) karya sutradara Bene Dion. Durasi 116 menit, diproduksi oleh Imajinari Pictures.\"",
          "",
          "PENDAHULUAN: \"Fenomena 'pulang kampung' atau mudik selalu menjadi momen yang dinanti sekaligus ditakuti. Film ini mengangkat tema keluarga Batak dengan cara yang segar dan humoris.\"",
          "",
          "SINOPSIS: \"Berkisah tentang Domu, seorang anak pertama yang diperkirakan akan pulang ke Medan. Namun ada masalah — ketiga anaknya belum pulang. Pak Domu dan Mak Domu pun membuat rencana pura-pura cerai.\"",
          "",
          "ANALISIS: \"Kelebihan film ini adalah akrit alami para pemain dan dialog yang dekat dengan keseharian. Namun, beberapa adegan terasa sedikit dipaksakan. Sinematografi menyajikan keindahan Danau Toba dengan apik.\"",
          "",
          "SIMPULAN: \"'Ngeri-Ngeri Sedap' adalah tontonan ringan yang menghibur sekaligus menyentuh. Sangat direkomendasikan untuk ditonton bersama keluarga.\"",
        ],
        catatan: "Bagian analisis adalah jantung dari resensi. Semakin tajam dan terperinci analisisnya, semakin berbobot resensi tersebut. Gunakan kata-kata evaluatif seperti 'memukau', 'lemah', 'konsisten', 'mendalam' dengan alasan yang jelas.",
      },
      {
        judul: "Kaidah Kebahasaan dan Teknik Menulis Resensi",
        isi: [
          "Ada beberapa kaidah kebahasaan dan teknik yang perlu dikuasai untuk menulis resensi yang baik.",
          "",
          "KAIDAH KEBAHASAAN:",
          "",
          "1. KATA EVALUATIF",
          "  Kata-kata yang menunjukkan penilaian: memukau, memikat, lemah, monoton, brilian, membosankan, apik, hambar.",
          "",
          "2. KONJUNGSI PERTENTANGAN",
          "  Menghubungkan kelebihan dan kekurangan. Contoh: namun, tetapi, akan tetapi, sayangnya, di sisi lain, meskipun demikian.",
          "",
          "3. ISTILAH TEKNIS SESUAI JENIS KARYA",
          "  Resensi buku: plot, karakterisasi, klimaks, diksi, sudut pandang.",
          "  Resensi film: sinematografi, akting, penyutradaraan, scoring, editing.",
          "",
          "4. KALIMAT REKOMENDASI",
          "  Di bagian simpulan, gunakan kalimat yang memberikan saran kepada calon pembaca/penonton. Contoh: 'Buku ini sangat direkomendasikan untuk...', 'Film ini cocok bagi Anda yang...'",
          "",
          "TEKNIK KIRI:",
          "  KIRI adalah singkatan dari Kekurangan, Isi, kelebihan, dan Rekomendasi. Ini adalah kerangka praktis yang bisa membantu menulis resensi dengan cepat dan seimbang.",
          "",
          "  K — KEKURANGAN: Apa saja kelemahan karya ini?",
          "  I — ISI: Apa sinopsis atau gambaran isi karya?",
          "  R — REKOMENDASI: Untuk siapa karya ini cocok?",
          "  I — KELEBIHAN: Apa kelebihan dan keunggulan karya ini?",
          "",
          "(Catatan: urutan KIRI bisa disesuaikan, tidak harus berurutan)",
          "",
          "[Ilustrasi: Sebuah infografis dengan ikon 'KIRI' besar di tengah. Empat kotak mengelilinginya — K (Kekurangan, merah), I (Isi, biru), R (Rekomendasi, hijau), I (Kelebihan, kuning). Masing-masing dengan ikon dan deskripsi singkat.]",
        ],
        contoh: [
          "Analisis menggunakan KIRI:",
          "",
          "K — Kekurangan: \"Beberapa bagian novel terasa lambat, terutama di bab 5-8. Konflik sekunder kurang dikembangkan.\"",
          "",
          "I — Isi: \"Novel ini bercerita tentang seorang guru muda yang mengajar di daerah terpencil dan berjuang melawan keterbatasan.\"",
          "",
          "R — Rekomendasi: \"Cocok untuk pembaca yang menyukai kisah inspiratif dengan latar pendidikan.\"",
          "",
          "I — Kelebihan: \"Gaya bahasa Andrea Hirata yang puitis dan penuh metafora membuat novel ini indah dibaca. Karakter-karakternya hidup dan menyentuh.\"",
          "",
          "Penggunaan konjungsi pertentangan:",
          "",
          "\"Novel ini memiliki alur yang menarik, NAMUN beberapa bagian terasa lambat.\"",
          "\"Sinematografinya sangat memukau, SAYANGNYA akting beberapa pemain kurang meyakinkan.\"",
          "\"Di satu sisi ceritanya sederhana, TETAPI di sisi lain justru itulah kekuatannya.\"",
        ],
      },
    ],
    rangkuman: [
      "[Ilustrasi: Seorang pembaca duduk di kursi nyaman dengan buku selesai dibaca, memegang sticky note berlabel 'Review'. Di meja, laptop dengan halaman blog ulasan terbuka. Kopi dan kacamata di sampingnya. Gaya ilustrasi cozy dengan warna cokelat dan krem.]",
      "Resensi adalah tulisan yang berisi penilaian, pembahasan, dan pertimbangan tentang suatu karya (buku, film, musik, dsb).",
      "Struktur resensi: Identitas Karya → Pendahuluan → Sinopsis → Analisis → Simpulan & Rekomendasi.",
      "Kaidah kebahasaan resensi: kata evaluatif, konjungsi pertentangan, istilah teknis, dan kalimat rekomendasi.",
      "Teknik KIRI (Kekurangan, Isi, kelebihan, Rekomendasi) membantu menulis resensi yang seimbang dan terstruktur.",
    ],
  },
  latihan: makeSoal([
    ["Apa tujuan utama dari teks resensi?", ["Menghibur pembaca", "Memberikan informasi dan pandangan kritis tentang suatu karya", "Mempromosikan karya tanpa analisis", "Menceritakan ulang isi buku"], 1, "Tujuan resensi adalah memberi informasi dan pandangan kritis kepada calon pembaca."],
    ["Bagian resensi yang berisi data lengkap karya disebut...", ["Pendahuluan", "Sinopsis", "Identitas karya", "Analisis"], 2, "Identitas karya berisi data lengkap seperti judul, penulis, penerbit, tahun terbit."],
    ["Manakah yang termasuk kata evaluatif dalam resensi?", ["Dan", "Memukau", "Atau", "Kemudian"], 1, "'Memukau' adalah kata evaluatif yang menunjukkan penilaian positif."],
    ["Konjungsi yang tepat untuk menghubungkan kelebihan dan kekurangan adalah...", ["Dan", "Atau", "Namun", "Karena"], 2, "'Namun' adalah konjungsi pertentangan yang menghubungkan kelebihan dan kekurangan."],
    ["KIRI dalam teknik menulis resensi adalah singkatan dari...", ["Kiri-Isi-Ringkasan-Isi", "Kekurangan-Isi-Kelebihan-Rekomendasi", "Karya-Inti-Ringkas-Ide", "Kesimpulan-Isi-Rangkuman-Ide"], 1, "KIRI: Kekurangan, Isi, kelebihan, Rekomendasi."],
    ["Bagian resensi yang berisi ringkasan isi karya tanpa spoiler berlebihan disebut...", ["Pendahuluan", "Identitas", "Sinopsis", "Analisis"], 2, "Sinopsis adalah ringkasan isi karya yang informatif tanpa mengungkap seluruh kejutan."],
    ["Berikut adalah istilah teknis dalam resensi film, KECUALI...", ["Sinematografi", "Akting", "Plot", "Diksi"], 3, "'Diksi' adalah istilah untuk resensi buku, bukan film. Plot dan karakterisasi juga untuk buku."],
    ["Bagian yang merupakan inti dari resensi karena berisi pembahasan kritis adalah...", ["Pendahuluan", "Sinopsis", "Analisis", "Identitas"], 2, "Analisis adalah bagian inti resensi yang berisi pembahasan dan penilaian kritis."],
    ["Resensi berbeda dari ulasan biasa karena resensi...", ["Lebih pendek", "Mengandung analisis kritis", "Tidak perlu data karya", "Hanya berisi pujian"], 1, "Resensi mengandung analisis dan penilaian kritis yang mendalam."],
    ["Kalimat 'Buku ini sangat direkomendasikan untuk remaja' termasuk bagian...", ["Identitas", "Sinopsis", "Analisis", "Simpulan dan rekomendasi"], 3, "Kalimat rekomendasi berada di bagian simpulan."],
  ]),
  praktik: {
    petunjuk: "Tulislah resensi dari sebuah buku yang pernah kamu baca! Gunakan struktur resensi lengkap (identitas, pendahuluan, sinopsis, analisis, simpulan) dan teknik KIRI. Panjang tulisan minimal 300 kata.",
    tips: [
      "Pilih buku yang benar-benar kamu baca agar ulasan lebih autentik dan mendalam",
      "Catat identitas buku secara lengkap sebelum mulai menulis",
      "Gunakan kata evaluatif (memukau, menarik, lemah, monoton) untuk menjelaskan penilaianmu",
      "Seimbangkan kelebihan dan kekurangan — jangan hanya memuji atau hanya mengkritik",
    ],
    contoh: "Resensi yang baik memiliki analisis yang tajam, bukan sekadar sinopsis. Bedakan antara opini pribadi ('saya suka') dengan penilaian objektif ('gaya bahasa penulis deskriptif dan hidup').",
  },
  kuis: makeSoal([
    ["Apa perbedaan resensi buku dan resensi film?", ["Tidak ada perbedaan", "Resensi buku fokus pada gaya bahasa dan plot, resensi film fokus pada sinematografi dan akting", "Resensi buku lebih panjang", "Resensi film tanpa analisis"], 1, "Keduanya berbeda fokus analisis sesuai medium karya."],
    ["Fungsi konjungsi pertentangan dalam resensi adalah...", ["Menambah panjang tulisan", "Menghubungkan kelebihan dan kekurangan secara seimbang", "Menggantikan kata evaluatif", "Memperjelas identitas karya"], 1, "Konjungsi pertentangan membantu menyajikan kelebihan dan kekurangan secara seimbang."],
    ["Teknik KIRI membantu penulis resensi untuk...", ["Menulis lebih cepat", "Menghasilkan resensi yang seimbang dan terstruktur", "Menghindari spoiler", "Menambah tebal resensi"], 1, "KIRI membantu menulis resensi yang seimbang dengan mencakup semua aspek."],
    ["Berikut adalah contoh kata evaluatif negatif dalam resensi...", ["Memukau", "Monoton", "Brilian", "Apik"], 1, "'Monoton' berarti sesuatu yang membosankan atau itu-itu saja, bernilai negatif."],
    ["Bagian resensi yang berisi latar belakang dan konteks karya adalah...", ["Identitas", "Pendahuluan", "Sinopsis", "Simpulan dan rekomendasi"], 1, "Pendahuluan berisi latar belakang dan konteks yang membuat karya relevan."],
    ["Mengapa sinopsis tidak boleh memberikan spoiler berlebihan?", ["Karena malas menulis", "Agar calon pembaca tetap penasaran dan menikmati karya sendiri", "Karena identitas karya", "Tidak ada alasan khusus"], 1, "Sinopsis harus informatif tetapi tidak mengungkap seluruh kejutan cerita."],
    ["Istilah 'plot' dalam resensi buku berarti...", ["Penulis buku", "Rangkaian cerita", "Sampul buku", "Jumlah halaman"], 1, "Plot berarti rangkaian peristiwa atau alur cerita dalam buku."],
    ["Kata evaluatif yang tepat untuk menilai akting pemain adalah...", ["Panjang", "Meyakinkan", "Banyak dialog", "Tebal"], 1, "'Meyakinkan' adalah kata evaluatif yang tepat untuk menilai kualitas akting."],
    ["Struktur resensi yang tepat adalah...", ["Sinopsis - Identitas - Analisis - Simpulan", "Identitas - Pendahuluan - Sinopsis - Analisis - Simpulan", "Analisis - Identitas - Sinopsis - Pendahuluan", "Simpulan - Analisis - Sinopsis - Identitas"], 1, "Urutan struktur resensi yang benar: Identitas → Pendahuluan → Sinopsis → Analisis → Simpulan."],
    ["Manfaat menulis resensi bagi penulis adalah...", ["Mendapatkan uang", "Melatih berpikir kritis", "Menjadi terkenal", "Membuang waktu"], 1, "Menulis resensi melatih kemampuan berpikir kritis dan menganalisis."],
  ]),
}

export default konten
