import type { Konten } from "../types"
import { makeSoal } from "../types"

const konten: Konten = {
  belajar: {
    tujuan: [
      "Memahami pengertian, ciri, dan jenis-jenis artikel",
      "Mengidentifikasi struktur artikel dengan tepat",
      "Menganalisis kaidah kebahasaan dalam penulisan artikel",
      "Menulis artikel populer dengan struktur yang baik",
    ],
    materi: [
      {
        judul: "Apa Itu Artikel?",
        isi: [
          "Pernahkah kamu membaca kolom opini di koran atau artikel di blog tentang tips belajar efektif? Tulisan-tulisan itu adalah artikel — karya jurnalistik yang mengupas suatu topik dengan gaya bahasa yang menarik!",
          "",
          "Artikel adalah karangan faktual yang ditulis untuk dipublikasikan di media massa (koran, majalah, website, blog) dengan tujuan menyampaikan informasi, gagasan, atau opini tentang suatu topik kepada pembaca.",
          "",
          "✓ Ciri-ciri artikel:",
          "  ✓ Faktual — berdasarkan data dan fakta yang dapat diverifikasi",
          "  ✓ Sistematis — memiliki struktur yang jelas",
          "  ✓ Informatif — memberikan pengetahuan baru kepada pembaca",
          "  ✓ Menarik — menggunakan judul dan gaya bahasa yang memikat",
          "  ✓ Objektif — opini didukung data, bukan sekadar perasaan",
          "",
          "Jenis-jenis artikel berdasarkan isi dan target pembaca:",
          "",
          "1. ARTIKEL ILMIAH",
          "  Artikel yang ditulis berdasarkan penelitian ilmiah, menggunakan bahasa akademis dan metodologi yang ketat. Target: akademisi, peneliti. Contoh: jurnal penelitian.",
          "",
          "2. ARTIKEL POPULER",
          "  Artikel ringan yang membahas topik tertentu dengan bahasa yang mudah dipahami masyarakat umum. Target: pembaca awam. Contoh: artikel kesehatan di majalah, blog gaya hidup.",
          "",
          "3. ARTIKEL OPINI",
          "  Artikel yang berisi pendapat atau pandangan penulis tentang suatu isu. Meskipun opini, tetap harus didukung data dan argumen yang logis. Target: pembaca yang tertarik pada isu tertentu. Contoh: kolom opini di koran.",
          "",
          "[Ilustrasi: Sebuah meja redaksi koran dengan laptop, buku catatan, dan secangkir kopi. Di layar laptop, sebuah halaman artikel dengan judul besar dan foto ilustrasi. Latar belakang rak berisi buku dan majalah. Gaya ilustrasi jurnalistik dengan warna biru dan putih.]",
        ],
        contoh: [
          "Perbandingan jenis artikel:",
          "",
          "ARTIKEL ILMIAH: \"Berdasarkan penelitian terhadap 200 responden, ditemukan korelasi signifikan antara durasi penggunaan media sosial dan tingkat kecemasan remaja (r=0.67, p<0.05).\"",
          "✓ Bahasa akademis, data statistik, metodologi jelas.",
          "",
          "ARTIKEL POPULER: \"Siapa sangka, scrolling Instagram selama 3 jam sehari bisa bikin cemas? Yuk, simak tips mengelola waktu layar untuk remaja!\"",
          "✓ Bahasa ringan, dekat dengan pembaca, judul menarik.",
          "",
          "ARTIKEL OPINI: \"Kebijakan larangan membawa smartphone ke sekolah perlu dikaji ulang. Alih-alih melarang, sekolah sebaiknya mengedukasi siswa tentang penggunaan gadget yang bijak.\"",
          "✓ Argumentasi logis, opini didukung alasan, solutif.",
        ],
      },
      {
        judul: "Struktur Artikel",
        isi: [
          "Artikel yang baik memiliki struktur yang memudahkan pembaca mengikuti alur pemikiran penulis. Struktur artikel terdiri dari empat bagian utama:",
          "",
          "1. JUDUL (HEADLINE)",
          "  Judul adalah 'pintu masuk' artikel. Judul yang menarik akan membuat pembaca penasaran dan melanjutkan membaca. Judul harus singkat, jelas, dan menggambarkan isi artikel.",
          "",
          "  Tips judul menarik:",
          "  • Gunakan angka: '5 Tips Belajar Efektif'",
          "  • Ajukan pertanyaan: 'Kenapa Remaja Susah Fokus?'",
          "  • Janjikan manfaat: 'Cara Mudah Paham Matematika'",
          "  • Gunakan kata kuat: 'Wajib Tahu!', 'Jangan Anggap Remeh!'",
          "",
          "2. LEAD (TERAS)",
          "  Paragraf pembuka yang merangkum inti artikel. Lead harus mampu menarik perhatian dan membuat pembaca ingin terus membaca. Lead menjawab pertanyaan: apa, siapa, kapan, di mana, mengapa, bagaimana.",
          "",
          "3. ISI (BODY)",
          "  Bagian utama yang mengembangkan topik. Isi artikel disusun dengan subjudul (subheading) untuk memecah informasi dan memudahkan pembaca. Setiap paragraf idealnya pendek — 3-5 kalimat.",
          "",
          "4. PENUTUP",
          "  Bagian akhir yang memberikan simpulan, kesan, ajakan, atau harapan. Penutup yang kuat akan meninggalkan kesan mendalam pada pembaca.",
          "",
          "[Ilustrasi: Diagram alur horizontal berlabel 'STRUKTUR ARTIKEL' dengan 4 kotak. Kotak 1: JUDUL (ikon lampu). Kotak 2: LEAD (ikon mata). Kotak 3: ISI dengan subjudul (ikon buku). Kotak 4: PENUTUP (ikon bintang). Panah menghubungkan setiap kotak dari kiri ke kanan.]",
        ],
        contoh: [
          "Contoh struktur artikel populer:",
          "",
          "JUDUL: \"Pengaruh Media Sosial terhadap Kesehatan Mental Remaja: Antara Manfaat dan Risiko\"",
          "",
          "LEAD: \"Generasi Z menghabiskan rata-rata 7 jam per hari di depan layar smartphone. Dari jumlah itu, 3 jam di antaranya digunakan untuk berselancar di media sosial. Lalu, apa dampaknya bagi kesehatan mental mereka?\"",
          "",
          "ISI (dengan subjudul):",
          "",
          "Manfaat Media Sosial bagi Remaja",
          "Media sosial membantu remaja terhubung dengan teman dan komunitas, mengekspresikan diri, dan mengakses informasi edukatif. Dalam situasi pandemi, media sosial menjadi jembatan interaksi sosial yang penting.",
          "",
          "Risiko yang Mengintai",
          "Di sisi lain, penggunaan berlebihan dapat memicu kecemasan, depresi, FOMO (Fear of Missing Out), dan gangguan tidur. Perbandingan dengan kehidupan orang lain yang 'sempurna' di media sosial sering membuat remaja merasa tidak percaya diri.",
          "",
          "Tips Bijak Bermedia Sosial",
          "Para ahli menyarankan untuk membatasi waktu layar maksimal 2 jam per hari, meng-unfollow akun yang memicu perasaan negatif, dan memperbanyak interaksi langsung di dunia nyata.",
          "",
          "PENUTUP: \"Media sosial adalah alat — bukan musuh atau tuan. Bijaklah dalam menggunakannya agar manfaatnya terasa tanpa harus mengorbankan kesehatan mental.\"",
        ],
        catatan: "Artikel populer di media digital biasanya menggunakan paragraf pendek (2-3 kalimat), diselingi subjudul setiap 3-5 paragraf, dan dilengkapi gambar atau infografis untuk memecah teks.",
      },
      {
        judul: "Kaidah Kebahasaan Artikel",
        isi: [
          "Artikel memiliki kaidah kebahasaan yang berbeda tergantung jenisnya. Namun ada beberapa kaidah umum yang perlu diperhatikan:",
          "",
          "1. KOMUNIKATIF",
          "  Bahasa artikel harus mudah dipahami target pembaca. Artikel ilmiah boleh menggunakan istilah teknis, tetapi artikel populer harus menggunakan bahasa yang sederhana dan akrab.",
          "",
          "2. DATA DAN FAKTA",
          "  Informasi dalam artikel harus didukung data dan fakta yang akurat. Sertakan sumber jika mengutip data atau pendapat ahli. Ini menjaga kredibilitas artikel.",
          "",
          "3. JUDUL MENARIK",
          "  Judul adalah senjata utama artikel. Judul yang membosankan akan membuat artikel tidak dibaca meskipun isinya bagus.",
          "",
          "4. PARAGRAF PENDEK",
          "  Untuk artikel digital, paragraf pendek (2-4 kalimat) lebih disukai karena mudah dibaca di layar. Paragraf panjang membuat pembaca cepat bosan.",
          "",
          "5. SUBJUDUL (SUBHEADING)",
          "  Subjudul membantu pembaca yang hanya memindai (scanning) artikel. Subjudul juga memecah informasi menjadi bagian-bagian yang lebih mudah dicerna.",
          "",
          "6. KALIMAT AKTIF",
          "  Gunakan kalimat aktif untuk membuat tulisan lebih hidup dan langsung. 'Peneliti menemukan...' lebih baik daripada 'Ditemukan oleh peneliti...'",
          "",
          "[Ilustrasi: Papan tulis digital bertuliskan 'KAIDAH KEBAHASAAN ARTIKEL' dengan 6 ikon. Ikon 1: gelembung dialog (komunikatif). Ikon 2: grafik batang (data/fakta). Ikon 3: tanda seru (judul menarik). Ikon 4: paragraf pendek. Ikon 5: heading H2 (subjudul). Ikon 6: panah maju (kalimat aktif).]",
        ],
        contoh: [
          "Perbandingan penulisan artikel yang baik dan kurang baik:",
          "",
          "KURANG BAIK: \"Dilaporkan oleh hasil penelitian bahwa ditemukan sebanyak 70 persen dari responden yang menyatakan bahwa mereka sering merasa cemas setelah menggunakan media sosial yang dimiliki oleh mereka dalam jangka waktu yang lama.\"",
          "✗ Kalimat pasif berpanjang-panjang, sulit dipahami.",
          "",
          "LEBIH BAIK: \"Penelitian menunjukkan 70% remaja merasa cemas setelah bermedia sosial lebih dari 3 jam sehari.\"",
          "✓ Kalimat aktif, data jelas, langsung ke inti.",
          "",
          "KURANG BAIK: \"Kesimpulannya adalah bahwa media sosial mempunyai dampak positif dan juga negatif sehingga kita harus bijak dalam menggunakannya dan juga jangan sampai berlebihan dalam menggunakannya.\"",
          "✗ Bertele-tele dan berulang.",
          "",
          "LEBIH BAIK: \"Media sosial seperti pisau — tergantung siapa yang menggunakannya. Bijaklah agar manfaatnya maksimal.\"",
          "✓ Singkat, padat, menggunakan metafora yang mudah diingat.",
        ],
      },
    ],
    rangkuman: [
      "[Ilustrasi: Meja jurnalis dengan laptop, buku catatan, dan mug kopi. Layar laptop menampilkan artikel yang sudah selesai dengan judul besar dan foto. Papan mood di dinding dengan kliping koran. Gaya ilustrasi jurnalistik dengan warna biru navy dan putih.]",
      "Artikel adalah karangan faktual yang dipublikasikan di media massa untuk menyampaikan informasi, gagasan, atau opini.",
      "Jenis artikel: ilmiah (akademis), populer (umum), dan opini (pandangan penulis).",
      "Struktur artikel: Judul → Lead → Isi (dengan subjudul) → Penutup.",
      "Kaidah kebahasaan: komunikatif, didukung data/fakta, judul menarik, paragraf pendek, subjudul, kalimat aktif.",
    ],
  },
  latihan: makeSoal([
    ["Apa pengertian artikel yang paling tepat?", ["Cerita fiksi pendek", "Karangan faktual yang dipublikasikan di media massa", "Puisi panjang", "Laporan hasil penelitian"], 1, "Artikel adalah karangan faktual yang dipublikasikan di media massa."],
    ["Jenis artikel yang menggunakan bahasa akademis dan metodologi ketat disebut...", ["Artikel populer", "Artikel ilmiah", "Artikel opini", "Artikel ringan"], 1, "Artikel ilmiah menggunakan bahasa akademis dan metodologi penelitian yang ketat."],
    ["Bagian artikel yang berfungsi sebagai 'pintu masuk' dan harus menarik adalah...", ["Lead", "Isi", "Judul", "Penutup"], 2, "Judul adalah pintu masuk artikel yang harus menarik perhatian pembaca."],
    ["Lead dalam struktur artikel adalah...", ["Judul utama", "Paragraf pembuka yang merangkum inti artikel", "Subjudul penjelas", "Kesimpulan"], 1, "Lead adalah paragraf pembuka yang merangkum inti artikel."],
    ["Berikut adalah tips membuat judul artikel yang menarik, KECUALI...", ["Menggunakan angka", "Mengajukan pertanyaan", "Menggunakan kata panjang", "Menjanjikan manfaat"], 2, "Judul yang baik singkat dan padat, bukan menggunakan kata panjang."],
    ["Mengapa artikel populer menggunakan paragraf pendek?", ["Agar lebih mudah dibaca di layar", "Karena malas menulis", "Agar terlihat banyak", "Tidak ada alasan khusus"], 0, "Paragraf pendek memudahkan pembaca membaca di layar digital."],
    ["Fungsi subjudul dalam artikel adalah...", ["Memperpanjang artikel", "Membantu pembaca memindai dan memecah informasi", "Menggantikan judul", "Menambah halaman"], 1, "Subjudul membantu pembaca scanning dan memecah informasi."],
    ["Manakah yang termasuk artikel opini?", ["Laporan penelitian di jurnal", "Tips memasak di blog", "Kolom opini di koran", "Berita bencana alam"], 2, "Kolom opini adalah contoh artikel opini yang berisi pandangan penulis."],
    ["Kalimat aktif lebih disukai dalam artikel karena...", ["Lebih panjang", "Lebih hidup dan langsung", "Lebih formal", "Lebih sulit dipahami"], 1, "Kalimat aktif membuat tulisan lebih hidup dan langsung."],
    ["Ciri artikel yang baik adalah...", ["Hanya opini tanpa data", "Faktual dan didukung data", "Menggunakan bahasa jargon", "Tidak memiliki struktur"], 1, "Artikel yang baik bersifat faktual dan didukung data yang akurat."],
  ]),
  praktik: {
    petunjuk: "Tulislah sebuah artikel populer tentang 'Dampak Media Sosial terhadap Remaja'! Gunakan struktur artikel lengkap (judul menarik, lead, isi dengan subjudul, penutup). Panjang tulisan minimal 400 kata.",
    tips: [
      "Buat judul yang membuat pembaca penasaran — gunakan angka, pertanyaan, atau kata yang memicu rasa ingin tahu",
      "Mulai lead dengan data atau pertanyaan yang relevan untuk menarik perhatian",
      "Gunakan subjudul untuk membagi artikel menjadi 3-4 bagian tematik",
      "Tutup dengan kesimpulan yang kuat dan ajakan (call to action) untuk pembaca",
    ],
    contoh: "Artikel populer harus menggunakan bahasa yang ringan dan dekat dengan pembaca remaja. Hindari istilah terlalu teknis. Gunakan analogi atau cerita singkat untuk membuat artikel lebih hidup.",
  },
  kuis: makeSoal([
    ["Perbedaan utama artikel ilmiah dan artikel populer adalah...", ["Panjang tulisan", "Bahasa dan target pembaca", "Jumlah paragraf", "Ada tidaknya gambar"], 1, "Artikel ilmiah menggunakan bahasa akademis untuk akademisi, artikel populer bahasa ringan untuk umum."],
    ["Bagian artikel yang menjawab 5W+1H disebut...", ["Judul", "Lead", "Isi", "Penutup"], 1, "Lead menjawab apa, siapa, kapan, di mana, mengapa, dan bagaimana."],
    ["Mengapa artikel opini tetap harus didukung data?", ["Karena data lebih panjang", "Agar argumen lebih kredibel dan logis", "Karena sopan", "Tidak perlu data"], 1, "Opini yang didukung data lebih kredibel dan meyakinkan pembaca."],
    ["Tips membuat judul artikel yang efektif, KECUALI...", ["Singkat dan padat", "Mengandung kata klikbait berlebihan", "Menggambarkan isi", "Menarik perhatian"], 1, "Klikbait berlebihan justru mengecewakan pembaca dan merusak kredibilitas."],
    ["Struktur artikel yang tepat adalah...", ["Lead - Judul - Isi - Penutup", "Judul - Lead - Isi - Penutup", "Isi - Judul - Lead - Penutup", "Penutup - Isi - Judul - Lead"], 1, "Urutan struktur artikel: Judul → Lead → Isi → Penutup."],
    ["Fungsi penutup dalam artikel adalah...", ["Menambah panjang artikel", "Memberi simpulan dan kesan mendalam", "Mengulangi judul", "Memperkenalkan topik baru"], 1, "Penutup memberikan simpulan, kesan, ajakan, atau harapan."],
    ["Manakah contoh judul artikel yang menarik?", ["Belajar Bahasa Indonesia", "5 Tips Jago Nulis Artikel dalam Sehari", "Mata Pelajaran", "Pengertian Artikel"], 1, "Judul dengan angka dan janji manfaat lebih menarik perhatian."],
    ["Kalimat yang lebih sesuai untuk artikel populer adalah...", ["Berdasarkan analisis regresi...", "Tahukah kamu, scrolling Instagram 3 jam sehari bisa bikin cemas?", "Hipotesis diterima", "Metode penelitian kuantitatif"], 1, "Artikel populer menggunakan bahasa yang ringan dan dekat dengan pembaca."],
    ["Mengapa penting mencantumkan sumber data dalam artikel?", ["Agar artikel lebih panjang", "Menjaga kredibilitas dan keakuratan informasi", "Karena sumber wajib", "Agar terlihat ilmiah"], 1, "Mencantumkan sumber menjaga kredibilitas dan keakuratan informasi."],
    ["Peran subjudul dalam artikel digital sangat penting karena...", ["Mempercantik tampilan", "Membantu pembaca yang hanya memindai artikel", "Menggantikan isi", "Menambah berat halaman"], 1, "Subjudul membantu pembaca yang melakukan scanning untuk menemukan informasi."],
  ]),
}

export default konten
