import type { Konten } from "../types"
import { makeSoal } from "../types"

const konten: Konten = {
  belajar: {
    tujuan: [
      "Memahami pengertian, ciri, dan tujuan teks anekdot sebagai kritik humoris",
      "Mengidentifikasi struktur teks anekdot: abstraksi, orientasi, krisis, reaksi, koda",
      "Menganalisis kaidah kebahasaan yang khas dalam teks anekdot",
      "Menyusun teks anekdot berdasarkan pengalaman lucu yang mengandung kritik",
    ],
    materi: [
      {
        judul: "Mengenal Teks Anekdot",
        isi: [
          "Pernahkah kamu mendengar cerita lucu yang sebenarnya menyindir sesuatu? Misalnya, cerita tentang seorang pejabat yang sibuk berfoto di acara bencana sementara korban menunggu bantuan. Itulah anekdot — cerita lucu yang mengandung kritik!",
          "",
          "Teks anekdot adalah cerita singkat yang lucu dan menghibur, tetapi mengandung kritik atau sindiran terhadap sesuatu — biasanya kebijakan publik, perilaku sosial, atau tokoh terkenal. Tujuannya bukan sekadar membuat orang tertawa, tetapi juga menyadarkan.",
          "",
          "✓ Ciri-ciri teks anekdot:",
          "  ✓ Bersifat lucu atau menggelitik",
          "  ✓ Mengandung kritik atau sindiran (tersirat maupun tersurat)",
          "  ✓ Berdasarkan kejadian nyata atau pengalaman yang relevan",
          "  ✓ Memiliki pesan moral yang ingin disampaikan",
          "  ✓ Menggunakan gaya bahasa yang hidup dan menarik",
          "",
          "[Ilustrasi: Panggung komedi dengan satu lampu sorot menyinari seorang pelawak yang berdiri di depan mikrofon. Di belakangnya, layar menampilkan gambar tokoh kartun sindiran. Penonton duduk di kursi, ada yang tertawa, ada yang berpikir. Gaya ilustrasi panggung komedi dengan warna merah dan kuning.]",
        ],
        contoh: [
          "Contoh anekdot singkat:",
          "",
          "Seorang menteri berkunjung ke rumah sakit. Ia melihat pasien dirawat di lorong karena kurangnya kamar. Sang menteri berkata, \"Jangan khawatir, kami akan bangun rumah sakit baru.\"",
          "Keesokan harinya, koran memuat berita: \"Menteri tidak jadi bangun rumah sakit baru karena pasien sudah tidak dirawat di lorong — mereka sudah dipulangkan.\"",
          "",
          "Lucu? Iya. Tapi ini juga kritik terhadap kebijakan yang justru merugikan rakyat.",
        ],
      },
      {
        judul: "Struktur Teks Anekdot",
        isi: [
          "Seperti cerita lucu yang runtut, anekdot punya struktur yang membuatnya enak diikuti.",
          "",
          "1. ABSTRAKSI",
          "  Kalimat pembuka yang memberikan gambaran umum tentang isi cerita. Menarik perhatian dan membuat penasaran. Contoh: \"Hari itu adalah hari yang sibuk di kantor kecamatan.\"",
          "",
          "2. ORIENTASI",
          "  Latar belakang cerita: siapa, kapan, di mana. Membangun suasana sebelum masuk ke bagian lucu. Contoh: \"Pak RT dan beberapa warga sedang mengantre untuk mengurus surat.\"",
          "",
          "3. KRISIS",
          "  Inti dari anekdot — bagian lucu atau tidak terduga yang menunjukkan masalah. Inilah puncak cerita. Contoh: \"Ketika giliran Pak RT tiba, petugas berkata, 'Maaf, komputer lagi error. Datang lagi besok.'\"",
          "",
          "4. REAKSI",
          "  Tanggapan tokoh terhadap krisis. Biasanya lucu, sinis, atau kocak. Contoh: \"Pak RT tersenyum dan bertanya, 'Loh, komputer error-nya dari minggu lalu, Pak?'\"",
          "",
          "5. KODA",
          "  Bagian penutup yang berisi kesimpulan atau pesan moral dari cerita. Contoh: \"Ternyata, birokrasi bisa jadi lelucon paling tidak lucu.\"",
          "",
          "[Ilustrasi: Diagram alur cerita berbentuk komik strip 5 panel. Panel 1 (Abstraksi): tanda seru. Panel 2 (Orientasi): gedung kantor. Panel 3 (Krisis): orang terjatuh karena kursi patah — ekspresi kaget. Panel 4 (Reaksi): orang lain tertawa. Panel 5 (Koda): gelembung pikiran berisi pesan moral. Gaya ilustrasi komik strip dengan warna cokelat dan krem.]",
        ],
        contoh: [
          "Penerapan struktur dalam anekdot 'Ujian':",
          "",
          "ABSTRAKSI: \"Ujian nasional adalah ajang tahunan yang paling ditunggu — ditunggu untuk segera berlalu.\"",
          "ORIENTASI: \"Di sebuah sekolah, ruang ujian hening. Para siswa tekun mengerjakan soal.\"",
          "KRISIS: \"Seorang siswa mengacungkan tangan. 'Pak, maaf, soalnya tidak sesuai kisi-kisi.' Pengawas menjawab, 'Tenang saja, kisi-kisinya sudah diperbarui di website — tapi website-nya down.'\"",
          "REAKSI: \"Seluruh kelas tertawa. Siswa itu hanya geleng-geleng kepala.\"",
          "KODA: \"Bukan ilmu yang diuji, melainkan kesabaran yang ditempa.\"",
        ],
      },
      {
        judul: "Kaidah Kebahasaan Anekdot",
        isi: [
          "Anekdot menggunakan bahasa yang khas — santai tapi mengena.",
          "",
          "1. KALIMAT RETORIS",
          "  Pertanyaan yang tidak butuh jawaban, untuk efek sindiran. Contoh: 'Bukankah itu lucu?'",
          "",
          "2. KONJUNGSI TEMPORAL (URUTAN WAKTU)",
          "  Menghubungkan peristiwa: kemudian, lalu, setelah itu, akhirnya, tiba-tiba.",
          "",
          "3. KATA KERJA AKTIF",
          "  Membuat cerita lebih hidup: menjawab, bertanya, berkata, tersenyum, tertawa.",
          "",
          "4. MAJAS SINDIRAN",
          "  Ironi: berkata sebaliknya dari maksud sebenarnya.",
          "  Sinisme: sindiran langsung yang tajam.",
          "  Sarkasme: sindiran kasar yang menyakiti.",
          "",
          "5. BAHASA SEHARI-HARI",
          "  Menggunakan bahasa lisan yang santai dan alami agar terasa dekat dengan pembaca.",
          "",
          "[Ilustrasi: Papan tulis dengan 5 kartu kaidah kebahasaan yang ditempel. Kartu 1 (Retoris): tanda tanya dalam gelembung. Kartu 2 (Temporal): ikon jam panah. Kartu 3 (Aktif): ikon orang berlari. Kartu 4 (Majas): ikon wajah tersenyum sinis. Kartu 5 (Santai): ikon gelembung percakapan. Di bawah kartu, contoh kalimat lucu ditulis dengan kapur. Gaya ilustrasi papan tulis kelas dengan warna putih dan hijau.]",
        ],
        contoh: [
          "Perbandingan penggunaan bahasa dalam anekdot:",
          "",
          "KURANG LUCU: \"Seorang pejabat berkata bahwa rakyat harus bersabar. Kemudian rakyat bersabar. Selesai.\"",
          "✗ Terlalu datar, tidak ada majas atau retoris.",
          "",
          "LEBIH LUCU: \"Pejabat itu tersenyum lebar, 'Sabar, Bapak-Ibu, pembangunan itu butuh proses.' Rakyat pun bersabar. Sepuluh tahun kemudian, mereka masih bersabar. Mungkin sabar adalah warisan paling berharga dari negara ini.\"",
          "✓ Menggunakan ironi ('warisan paling berharga'), kronologis, dan bahasa santai yang hidup.",
        ],
      },
    ],
    rangkuman: [
      "[Ilustrasi: Seorang pelawak kecil duduk di kursi sambil memegang papan bertuliskan 'TERTAWA ITU KRITIK'. Di sekelilingnya, gelembung-gelembung berisi gambar-gambar lucu: kura-kura bersepeda, kucing pakai dasi, dan burung pakai topi. Latar belakang panggung komedi dengan lampu warna-warni. Gaya ilustrasi kartun humor dengan warna kuning dan merah.]",
      "Anekdot adalah cerita lucu yang mengandung kritik atau sindiran terhadap suatu masalah.",
      "Struktur: Abstraksi → Orientasi → Krisis → Reaksi → Koda.",
      "Kaidah kebahasaan: kalimat retoris, konjungsi temporal, kata kerja aktif, majas sindiran, bahasa sehari-hari.",
      "Tujuan anekdot bukan sekadar humor — tetapi menyadarkan pembaca melalui kritik yang dikemas ringan.",
    ],
  },
  latihan: makeSoal([
    ["Apa tujuan utama teks anekdot?", ["Sekadar menghibur", "Mengkritik dengan cara lucu", "Mendeskripsikan objek", "Melaporkan kejadian"], 1, "Tujuan anekdot adalah mengkritik atau menyindir melalui cerita lucu."],
    ["Bagian anekdot yang berisi puncak kelucuan disebut...", ["Orientasi", "Krisis", "Reaksi", "Koda"], 1, "Krisis adalah bagian puncak cerita yang lucu atau tidak terduga."],
    ["'Bukankah itu menggelikan?' adalah contoh kalimat...", ["Berita", "Retoris", "Perintah", "Tanya biasa"], 1, "Kalimat retoris adalah pertanyaan yang tidak memerlukan jawaban."],
    ["Kata 'tiba-tiba', 'lalu', 'kemudian' termasuk konjungsi...", ["Kausal", "Temporal", "Pertentangan", "Tujuan"], 1, "Konjungsi temporal menunjukkan urutan waktu."],
    ["Majas sindiran halus yang menyatakan kebalikan dari maksud sebenarnya disebut...", ["Sarkasme", "Sinisme", "Ironi", "Personifikasi"], 2, "Ironi adalah majas yang menyatakan kebalikan dari maksud sebenarnya."],
    ["Bagian yang berisi latar waktu dan tempat dalam anekdot adalah...", ["Abstraksi", "Orientasi", "Krisis", "Koda"], 1, "Orientasi berisi latar belakang cerita: siapa, kapan, di mana."],
    ["Ciri khas bahasa anekdot yang membedakannya dari teks lain adalah...", ["Bahasa formal dan kaku", "Bahasa santai dan hidup", "Bahasa ilmiah", "Bahasa puisi"], 1, "Anekdot menggunakan bahasa santai dan hidup agar terasa dekat."],
    ["Fungsi abstraksi dalam anekdot adalah...", ["Menutup cerita", "Memberi gambaran umum pembuka", "Menjelaskan krisis", "Memberi pesan moral"], 1, "Abstraksi adalah gambaran umum yang menarik perhatian di awal."],
    ["Berikut ini contoh majas sarkasme adalah...", ["'Wah, pintar sekali kamu sampai nilai nol'", "'Dia memang rajin belajar'", "'Makanan ini enak sekali'", "'Hari ini cerah'"], 0, "'Pintar sekali sampai nilai nol' adalah sarkasme — pujian palsu yang mengejek."],
    ["Koda dalam anekdot berisi...", ["Pengenalan tokoh", "Kesimpulan atau pesan moral", "Bagian lucu", "Latar cerita"], 1, "Koda adalah bagian penutup yang berisi kesimpulan atau pesan moral."],
  ]),
  praktik: {
    petunjuk: "Buatlah teks anekdot berdasarkan pengalaman lucu yang pernah kamu alami atau saksikan. Pastikan ceritamu mengandung kritik atau sindiran — bisa tentang kebijakan sekolah, kemacetan, antrean, atau birokrasi. Gunakan struktur abstraksi, orientasi, krisis, reaksi, dan koda.",
    tips: [
      "Pilih pengalaman yang benar-benar terjadi atau minimal masuk akal — anekdot bukan fiksi murni",
      "Gunakan majas ironi atau sinisme untuk memperkuat sindiran",
      "Jaga keseimbangan antara lucu dan kritik — jangan terlalu serius atau terlalu main-main",
      "Akhiri dengan koda yang membuat pembaca tersenyum sambil berpikir",
      "Gunakan dialog untuk membuat cerita lebih hidup",
    ],
    contoh: "Teks minimal 3 paragraf. Gunakan 1-2 kalimat retoris dan 1 majas sindiran. Pastikan ada bagian yang lucu sekaligus mengkritik.",
  },
  kuis: makeSoal([
    ["Perbedaan anekdot dengan cerita lucu biasa adalah...", ["Anekdot lebih panjang", "Anekdot mengandung kritik", "Cerita lucu lebih lucu", "Tidak ada perbedaan"], 1, "Anekdot mengandung kritik atau sindiran, bukan sekadar lucu."],
    ["'Hari Senin adalah hari yang ditunggu — oleh mereka yang libur Selasa.' Kalimat ini mengandung majas...", ["Personifikasi", "Ironi", "Hiperbola", "Metafora"], 1, "Ini ironi karena sebenarnya Senin tidak ditunggu, tetapi sindiran tentang buku yang habis lebih dulu."],
    ["Bagian 'reaksi' dalam anekdot berfungsi...", ["Memperkenalkan tokoh", "Menunjukkan tanggapan terhadap krisis", "Menutup cerita", "Membangun suasana"], 1, "Reaksi adalah tanggapan tokoh terhadap krisis yang terjadi."],
    ["Anekdot yang baik sebaiknya...", ["Panjang dan bertele-tele", "Singkat, padat, dan mengena", "Penuh kata ilmiah", "Serius dan formal"], 1, "Anekdot yang baik singkat, padat, humoris, dan mengandung kritik."],
    ["Kata 'konon' dan 'alkisah' sering digunakan dalam anekdot sebagai...", ["Pembuka cerita", "Penutup cerita", "Kata tanya", "Kata sambung"], 0, "'Konon' dan 'alkisah' adalah kata pembuka yang lazim dalam anekdot."],
    ["Sarkasme termasuk majas sindiran yang...", ["Halus", "Kasar dan menyakiti", "Tersembunyi", "Indah"], 1, "Sarkasme adalah sindiran kasar yang bersifat menyakiti."],
    ["Teks anekdot termasuk jenis teks...", ["Faktual", "Fiksi kreatif", "Ilmiah", "Prosedur"], 1, "Anekdot termasuk teks fiksi kreatif (sastra) karena bersifat cerita rekaan."],
    ["Agar anekdot terasa alami, sebaiknya...", ["Menggunakan bahasa kaku", "Menggunakan dialog dan bahasa sehari-hari", "Panjang dan detail", "Formal dan resmi"], 1, "Dialog dan bahasa sehari-hari membuat anekdot terasa alami."],
    ["'Dua orang mahasiswa bingung mencari ruang kuliah yang pindah tanpa pemberitahuan.' Ini adalah bagian...", ["Krisis", "Orientasi", "Abstraksi", "Koda"], 1, "Ini orientasi karena memperkenalkan tokoh dan situasi."],
    ["Pesan moral dalam anekdot biasanya terletak di bagian...", ["Abstraksi", "Koda", "Krisis", "Orientasi"], 1, "Koda berisi pesan moral atau kesimpulan dari cerita."],
  ]),
}

export default konten
