import type { Konten } from "../types"
import { makeSoal } from "../types"

const konten: Konten = {
  belajar: {
    tujuan: [
      "Memahami pengertian, ciri, dan karakteristik hikayat sebagai sastra Melayu klasik",
      "Mengidentifikasi unsur intrinsik dan ekstrinsik hikayat",
      "Menganalisis kaidah kebahasaan yang khas dalam hikayat (konjungsi, arkais, majas)",
      "Membandingkan hikayat dengan cerita pendek modern",
      "Mengapresiasi nilai-nilai budaya dan moral dalam hikayat",
    ],
    materi: [
      {
        judul: "Mengenal Hikayat",
        isi: [
          "Zaman dulu, sebelum televisi dan internet, hiburan rakyat adalah mendengarkan cerita. Di tanah Melayu, cerita-cerita epik ini disebut hikayat — kisah kepahlawanan, petualangan, dan percintaan yang dibacakan sebagai hiburan istana maupun rakyat biasa.",
          "",
          "Hikayat adalah karya sastra Melayu klasik berbentuk prosa yang menceritakan tentang kehidupan istana, kepahlawanan, petualangan, atau kisah cinta. Kata 'hikayat' sendiri berasal dari bahasa Arab yang berarti 'cerita' atau 'kisah'.",
          "",
          "✓ Karakteristik hikayat:",
          "  ✓ Istanasentris — berlatar kerajaan dan kehidupan bangsawan",
          "  ✓ Statis — tokoh biasanya tidak mengalami perkembangan watak",
          "  ✓ Mengandung kemustahilan — kekuatan supranatural, benda ajaib, tokoh sakti",
          "  ✓ Anonim — pengarang tidak dikenal (cerita rakyat yang berkembang lisan)",
          "  ✓ Didaktis — mengandung pesan moral dan nilai-nilai budaya",
          "",
          "[Ilustrasi: Seorang tua berjubah duduk di serambi istana, dikelilingi anak-anak yang duduk melingkar. Ia membacakan buku besar dengan cerita tentang pangeran dan naga. Latar belakang istana Melayu dengan ukiran kayu dan tiang-tiang tinggi. Suasana hangat dan penuh perhatian. Gaya ilustrasi klasik Melayu dengan warna cokelat, emas, dan hijau.]",
        ],
        contoh: [
          "Hikayat terkenal dalam sastra Melayu:",
          "",
          "1. HIKAYAT HANG TUAH",
          "  Kisah laksamana Melaka yang pemberani dan setia. Hang Tuah memiliki sahabat Hang Jebat yang memberontak karena fitnah. Konflik antara kesetiaan dan persahabatan.",
          "",
          "2. HIKAYAT SERI RAMA",
          "  Adaptasi Melayu dari Ramayana. Kisah Rama yang mencari Sinta yang diculik Rahwana. Dibantu oleh Anoman si kera putih.",
          "",
          "3. HIKAYAT BAYAN BUDIMAN",
          "  Kisah seekor burung bayan yang cerdik menyelamatkan seekor itik dari berbagai bahaya. Penuh pesan moral tentang kecerdasan dan kebaikan.",
        ],
        catatan: "Meskipun hikayat terasa 'jadul', banyak nilai-nilai di dalamnya yang masih relevan — seperti kesetiaan, keberanian, dan keadilan. Mempelajari hikayat berarti mempelajari akar budaya sastra Indonesia.",
      },
      {
        judul: "Unsur Intrinsik Hikayat",
        isi: [
          "Seperti cerita pada umumnya, hikayat juga memiliki unsur pembangun dari dalam. Mari kita bedah.",
          "",
          "1. TEMA",
          "  Tema hikayat biasanya berkisar pada kepahlawanan, percintaan, kesetiaan, petualangan, dan agama. Contoh: Hikayat Hang Tuah bertema kesetiaan dan pengabdian.",
          "",
          "2. TOKOH",
          "  Tokoh hikayat umumnya dari kalangan istana: raja, ratu, pangeran, putri, perdana menteri. Tokoh protagonis dan antagonis sangat jelas (hitam-putih).",
          "",
          "3. ALUR",
          "  Alur hikayat biasanya maju (kronologis) dan linier. Cerita bergerak dari awal hingga akhir secara berurutan dengan konflik yang jelas.",
          "",
          "4. LATAR",
          "  Latar tempat: istana, kerajaan, hutan, laut. Latar waktu: zaman dahulu (kerajaan-kerajaan Nusantara). Latar sosial: kehidupan bangsawan dan rakyat biasa.",
          "",
          "5. SUDUT PANDANG",
          "  Umumnya menggunakan sudut pandang orang ketiga serba tahu — pengarang tahu segalanya tentang tokoh dan peristiwa.",
          "",
          "6. AMANAT",
          "  Pesan moral yang ingin disampaikan: kejujuran, kesetiaan, keberanian, kebijaksanaan. Hikayat bersifat didaktis — mengajarkan nilai-nilai kehidupan.",
          "",
          "[Ilustrasi: Peta pikiran berbentuk kompas dengan 6 arah mata angin. Pusat kompas: HIKAYAT. Cabang 1 (Utara): TEMA — ikon mahkota. Cabang 2 (Timur): TOKOH — ikon ksatria. Cabang 3 (Selatan): ALUR — ikon jalan berliku. Cabang 4 (Barat): LATAR — ikon istana. Cabang 5 (Timur Laut): SUDUT PANDANG — ikon mata. Cabang 6 (Barat Daya): AMANAT — ikon bintang. Gaya ilustrasi peta pikiran dengan warna emas dan merah.]",
        ],
        contoh: [
          "Analisis unsur intrinsik Hikayat Hang Tuah:",
          "",
          "TEMA: Kesetiaan dan pengabdian kepada raja dan negara.",
          "TOKOH: Hang Tuah (protagonis — setia, pemberani), Hang Jebat (antagonis — pemberontak tapi memiliki alasan), Sultan (penguasa yang mudah terpengaruh fitnah).",
          "ALUR: Maju — dari masa kecil Hang Tuah, pengangkatannya sebagai laksamana, fitnah yang diterimanya, konflik dengan Hang Jebat, hingga akhirnya kembali diistana.",
          "LATAR: Kerajaan Melaka abad ke-15, istana, hutan, laut.",
          "SUDUT PANDANG: Orang ketiga serba tahu.",
          "AMANAT: Kesetiaan harus dijunjung, tetapi keadilan juga penting. Jangan mudah terpengaruh fitnah.",
        ],
      },
      {
        judul: "Kaidah Kebahasaan Hikayat",
        isi: [
          "Hikayat menggunakan bahasa Melayu klasik yang berbeda dari bahasa Indonesia modern. Inilah yang membuatnya unik.",
          "",
          "1. KATA ARKAIS",
          "  Kata-kata kuno yang sudah jarang digunakan: syahdan (maka, lalu), hatta (maka, kemudian), sebermula (pada mulanya), konon (kata orang), titah (perintah raja).",
          "",
          "2. KONJUNGSI TEMPORAL",
          "  Syahdan, hatta, maka, lalu, kemudian, sebermula, alkisah — menghubungkan peristiwa secara berurutan.",
          "",
          "3. MAJAS KLASIK",
          "  Banyak menggunakan majas perbandingan dan personifikasi: \"bagai bulan jatuh ke riba\", \"laksana purnama\", \"seperti kumbang dan bunga\".",
          "",
          "4. KATA PENANDA ISTANA",
          "  Bertitah, bersemayam, baginda, patik, hamba, tuanku, kakanda, adinda, putri, permaisuri.",
          "",
          "5. KALIMAT LANGSUNG (Dialog)",
          "  Dialog para tokoh sering menggunakan bahasa istana yang halus dan penuh tata krama.",
          "",
          "[Ilustrasi: Buku kuno terbuka dengan halaman menguning dan aksara Jawi di beberapa bagian. Di samping buku, tinta dan pena bulu ayam. Dari halaman buku, kata-kata Melayu klasik berterbangan: 'syahdan', 'hatta', 'konon', 'patik'. Gaya ilustrasi manuskrip klasik dengan warna sepia dan cokelat tua.]",
        ],
        contoh: [
          "Bandingkan bahasa Melayu klasik dengan bahasa Indonesia modern:",
          "",
          "HIKAYAT (BAHASA MELAYU): \"Syahdan, maka Hang Tuah pun berangkatlah ke negeri Siam. Maka baginda pun bertitah, 'Hai patik, pergilah dengan selamat.' Maka Hang Tuah pun menyembah lalu berlayar.\"",
          "",
          "MODERN: \"Kemudian Hang Tuah berangkat ke negeri Siam. Raja berkata, 'Pergilah dengan selamat.' Hang Tuah membungkuk hormat lalu berlayar.\"",
          "",
          "Perbedaan: arkais (syahdan, titah, patik, menyembah) vs modern (kemudian, berkata, membungkuk). Keduanya benar — hanya menunjukkan zaman bahasa yang berbeda.",
        ],
      },
    ],
    rangkuman: [
      "[Ilustrasi: Sebuah perahu layar kuno berlayar di laut biru menuju istana di kejauhan. Di perahu, seorang ksatria dengan keris di pinggang berdiri tegak memandang ke depan. Layar perahu bertuliskan 'HIKAYAT'. Awan di langit membentuk huruf-huruf Melayu klasik. Gaya ilustrasi petualangan epik dengan warna biru laut dan emas.]",
      "Hikayat adalah prosa sastra Melayu klasik yang menceritakan kisah istana, kepahlawanan, dan petualangan.",
      "Karakteristik: istanasentris, statis, kemustahilan, anonim, didaktis.",
      "Unsur intrinsik: tema, tokoh, alur, latar, sudut pandang, amanat — sama seperti cerpen tetapi bernuansa klasik.",
      "Kaidah kebahasaan: kata arkais (syahdan, hatta), konjungsi temporal, majas klasik, dan istilah istana.",
    ],
  },
  latihan: makeSoal([
    ["Apa yang dimaksud dengan hikayat?", ["Cerita pendek modern", "Prosa sastra Melayu klasik", "Puisi rakyat", "Drama modern"], 1, "Hikayat adalah prosa sastra Melayu klasik."],
    ["Kata 'syahdan' dalam hikayat berarti...", ["Selesai", "Maka, lalu", "Sedih", "Senang"], 1, "'Syahdan' berarti 'maka' atau 'lalu' — penanda urutan cerita."],
    ["Ciri khas hikayat yang menunjukkan latar kerajaan disebut...", ["Didaktis", "Istanasetris", "Anonim", "Statis"], 1, "Istanasetris berarti berpusat pada kehidupan istana dan kerajaan."],
    ["Tokoh dalam hikayat biasanya bersifat...", ["Statis (tidak berkembang)", "Dinamis (berkembang)", "Kompleks", "Misterius"], 0, "Tokoh hikayat bersifat statis — wataknya tetap dari awal hingga akhir."],
    ["Hikayat Hang Tuah mengajarkan nilai...", ["Kekayaan", "Kesetiaan dan pengabdian", "Kekuasaan", "Kecantikan"], 1, "Hikayat Hang Tuah mengajarkan kesetiaan kepada raja dan negara."],
    ["Kata 'hatta' dalam hikayat memiliki arti yang sama dengan...", ["Syahdan", "Tetapi", "Atau", "Karena"], 0, "'Hatta' dan 'syahdan' sama-sama berarti 'maka' atau 'kemudian'."],
    ["Berikut adalah hikayat terkenal dalam sastra Melayu, KECUALI...", ["Hikayat Hang Tuah", "Hikayat Bayan Budiman", "Laskar Pelangi", "Hikayat Seri Rama"], 2, "'Laskar Pelangi' adalah novel modern, bukan hikayat klasik."],
    ["Majas 'bagai bulan jatuh ke riba' termasuk jenis...", ["Personifikasi", "Perbandingan", "Hiperbola", "Ironi"], 1, "Majas tersebut membandingkan seseorang dengan bulan — perbandingan/ simile."],
    ["Salah satu ciri hikayat yang berbeda dari cerpen adalah...", ["Cerpen lebih panjang", "Hikayat mengandung kemustahilan", "Cerpen tidak punya amanat", "Hikayat tidak punya tokoh"], 1, "Hikayat mengandung unsur kemustahilan seperti kekuatan supranatural."],
    ["Kata 'patik' digunakan dalam hikayat oleh...", ["Raja", "Rakyat/bawahan kepada raja", "Dewi", "Pahlawan"], 1, "Patik adalah kata ganti orang pertama untuk rakyat/bawahan saat berbicara dengan raja."],
  ]),
  praktik: {
    petunjuk: "Tuliskan sebuah cerita pendek bergaya hikayat dengan tema 'Kesetiaan Seorang Ksatria'. Gunakan minimal 3 kata arkais (syahdan, hatta, konon, dll), latar istana/kerajaan, dan satu unsur kemustahilan. Panjang cerita 3-5 paragraf.",
    tips: [
      "Mulailah dengan 'Konon pada zaman dahulu kala...' atau 'Syahdan, di sebuah kerajaan...'",
      "Gunakan kata istana: baginda, titah, patik, hamba, bersemayam",
      "Ciptakan satu tokoh protagonis dan satu antagonis yang jelas (hitam-putih)",
      "Tambahkan unsur magis — misalnya keris sakti, kalung ajaib, atau naga",
      "Akhiri dengan pesan moral yang jelas",
    ],
    contoh: "Cerita minimal 3 paragraf. Gunakan 3 kata arkais, 1 tokoh protagonis dan 1 antagonis, dan 1 unsur kemustahilan.",
  },
  kuis: makeSoal([
    ["Hikayat termasuk jenis sastra...", ["Modern", "Klasik/Melayu", "Kontemporer", "Lisan"], 1, "Hikayat termasuk sastra Melayu klasik."],
    ["Fungsi kata 'alkisah' dalam hikayat adalah...", ["Penutup cerita", "Pembuka cerita", "Penanda dialog", "Penjelas latar"], 1, "'Alkisah' berfungsi sebagai kata pembuka cerita."],
    ["Perbedaan hikayat dengan cerita pendek modern adalah...", ["Tidak ada perbedaan", "Hikayat anonim, cerpen diketahui pengarangnya", "Sama-sama modern", "Cerpen lebih tua"], 1, "Hikayat anonim (pengarang tidak dikenal), berbeda dengan cerpen modern."],
    ["Nilai yang paling menonjol dalam Hikayat Bayan Budiman adalah...", ["Keberanian", "Kecerdasan/kebijaksanaan", "Kekuatan", "Kekayaan"], 1, "Hikayat Bayan Budiman mengajarkan kecerdasan dalam menyelesaikan masalah."],
    ["'Titah' dalam hikayat berarti...", ["Perintah raja", "Pertanyaan", "Permintaan", "Dendam"], 0, "'Titah' berarti perintah atau ucapan raja."],
    ["Mengapa hikayat sering disebut 'istanasentris'?", ["Karena ditulis oleh sultan", "Karena latar dan tokohnya dari lingkungan istana", "Karena dibaca di istana", "Karena bahasa istana"], 1, "Istanasetris karena latar dan tokohnya dari lingkungan istana."],
    ["Hikayat bersifat didaktis, artinya...", ["Menghibur", "Mendidik/mengandung pesan moral", "Menceritakan", "Mendeskripsikan"], 1, "Didaktis berarti mengandung ajaran atau pesan moral."],
    ["'Baginda sedang bersemayam di singgasana.' Kata 'bersemayam' berarti...", ["Tidur", "Duduk (untuk raja)", "Berdiri", "Berjalan"], 1, "'Bersemayam' berarti duduk — khusus untuk raja atau bangsawan."],
    ["Unsur kemustahilan dalam hikayat contohnya adalah...", ["Tokoh pergi ke pasar", "Tokoh terbang menggunakan sejadah", "Tokoh makan", "Tokoh tidur"], 1, "Terbang menggunakan sejadah adalah unsur kemustahilan."],
    ["Hikayat yang menceritakan petualangan pangeran mencari obat untuk ayahnya termasuk tema...", ["Percintaan", "Petualangan", "Agama", "Persahabatan"], 1, "Cerita pangeran mencari obat termasuk tema petualangan."],
  ]),
}

export default konten
