import type { Konten } from "../types"
import { makeSoal } from "../types"

const konten: Konten = {
  belajar: {
    tujuan: [
      "Memahami pengertian, ciri, dan jenis teks biografi",
      "Mengidentifikasi struktur teks biografi dengan tepat",
      "Menganalisis kaidah kebahasaan teks biografi",
      "Menulis teks biografi berdasarkan data tokoh secara sistematis",
      "Meneladani nilai-nilai dari tokoh inspiratif dalam biografi",
    ],
    materi: [
      {
        judul: "Mengenal Teks Biografi",
        isi: [
          "Pernahkah kamu membaca kisah hidup seorang tokoh yang menginspirasi? B.J. Habibie, Cut Nyak Dien, atau Ki Hajar Dewantara? Kisah hidup yang ditulis secara sistematis itulah yang disebut biografi.",
          "",
          "Biografi adalah teks yang berisi riwayat hidup seseorang yang ditulis oleh orang lain. Biografi menyajikan fakta, pengalaman, dan perjalanan hidup tokoh secara kronologis — dari lahir hingga mencapai kesuksesan atau akhir hayat.",
          "",
          "✓ Ciri-ciri teks biografi:",
          "  ✓ Faktual — berdasarkan data dan fakta yang dapat diverifikasi",
          "  ✓ Kronologis — disusun berdasarkan urutan waktu kejadian",
          "  ✓ Inspiratif — mengandung nilai-nilai positif yang patut diteladani",
          "  ✓ Menggunakan sudut pandang orang ketiga (ia, dia, beliau)",
          "  ✓ Disertai data pendukung: tanggal, tempat, peristiwa penting",
          "",
          "[Ilustrasi: Sebuah rak buku perpustakaan tua dengan deretan buku biografi tokoh-tokoh terkenal. Sampul buku menampilkan foto-foto tokoh seperti R.A. Kartini, B.J. Habibie, dan Ki Hajar Dewantara. Suasana hangat dengan cahaya matahari masuk melalui jendela. Gaya ilustrasi perpustakaan klasik dengan warna cokelat dan krem.]",
        ],
        contoh: [
          "Bandingkan dengan teks fiksi:",
          "",
          "FIKSI: \"Pada suatu hari, hiduplah seorang pemuda bernama Raka yang memiliki mimpi besar. Ia tinggal di sebuah desa di tepi pantai.\"",
          "✓ Tokoh fiktif, waktu tidak spesifik, bersifat imajinatif.",
          "",
          "BIOGRAFI: \"Ir. Soekarno, lahir di Surabaya pada 6 Juni 1901. Beliau adalah Presiden pertama Republik Indonesia yang memproklamasikan kemerdekaan Indonesia pada 17 Agustus 1945.\"",
          "✓ Tokoh nyata, waktu dan tempat spesifik, berdasarkan fakta.",
        ],
        catatan: "Biografi berbeda dengan autobiografi. Biografi ditulis oleh orang lain, sedangkan autobiografi ditulis oleh tokoh itu sendiri. Contoh autobiografi: 'The Story of My Life' oleh Helen Keller.",
      },
      {
        judul: "Struktur Teks Biografi",
        isi: [
          "Seperti novel atau cerita, biografi juga memiliki struktur yang khas dan sistematis.",
          "",
          "1. ORIENTASI",
          "  Berisi pengenalan tokoh: nama lengkap, tempat dan tanggal lahir, latar belakang keluarga, pendidikan awal. Bagian ini memberikan gambaran umum tentang siapa tokoh tersebut.",
          "",
          "2. PERISTIWA PENTING / KEJADIAN UTAMA",
          "  Berisi rangkaian perjalanan hidup tokoh yang menarik dan penting: perjuangan, rintangan, pencapaian, momen-momen kunci. Bagian ini adalah inti dari biografi.",
          "",
          "3. REORIENTASI (Opsional)",
          "  Berisi kesimpulan, pandangan penulis terhadap tokoh, pesan moral, atau inspirasi yang bisa diambil. Bagian ini bersifat penutup.",
          "",
          "[Ilustrasi: Garis waktu (timeline) horizontal dengan tiga titik besar. Titik 1: 'ORIENTASI' dengan ikon bayi dan buku (masa kecil & pendidikan). Titik 2: 'PERISTIWA PENTING' dengan ikon berbagai momen — piala, bendera, buku, mikrofon. Titik 3: 'REORIENTASI' dengan ikon bintang dan piala. Garis waktu dihiasi dengan warna-warna cerah. Gaya ilustrasi infografis modern dengan warna biru dan emas.]",
        ],
        contoh: [
          "Contoh penerapan struktur pada biografi R.A. Kartini:",
          "",
          "ORIENTASI: \"Raden Adjeng Kartini lahir di Jepara pada 21 April 1879. Ia adalah putri dari Raden Mas Adipati Ario Sosroningrat, Bupati Jepara. Kartini bersekolah di ELS (Europese Lagere School) hingga usia 12 tahun.\"",
          "",
          "PERISTIWA PENTING: \"Setelah usia 12 tahun, Kartini harus dipingit sesuai tradisi. Selama masa pingitan, ia membaca banyak buku dan berkorespondensi dengan teman-temannya di Belanda. Surat-suratnya berisi gagasan tentang emansipasi perempuan. Tahun 1903, Kartini mendirikan sekolah perempuan pertama di Jepara.\"",
          "",
          "REORIENTASI: \"Kartini wafat di usia muda 25 tahun, namun pemikirannya terus hidup dan menginspirasi perjuangan kesetaraan perempuan di Indonesia.\"",
        ],
      },
      {
        judul: "Kaidah Kebahasaan Teks Biografi",
        isi: [
          "Teks biografi memiliki ciri bahasa yang khas. Yuk, kita pelajari satu per satu!",
          "",
          "1. KATA KERJA TINDAKAN",
          "  Menggambarkan aktivitas tokoh: berjuang, memimpin, mendirikan, menulis, berpidato, menolak.",
          "",
          "2. KATA SIFAT",
          "  Menggambarkan karakter tokoh: gigih, cerdas, berani, rendah hati, visioner, pantang menyerah.",
          "",
          "3. KATA HUBUNG WAKTU / KRONOLOGIS",
          "  Kemudian, setelah itu, pada tahun X, setahun kemudian, sejak kecil, pada akhirnya.",
          "",
          "4. KATA KERJA PASIF",
          "  Digunakan untuk fokus pada tokoh yang dikenai tindakan: 'Beliau dianugerahi gelar pahlawan nasional...'",
          "",
          "5. PRONOMINA (KATA GANTI) ORANG KETIGA",
          "  Ia, dia, beliau, -nya. Contoh: 'Beliau dikenal sebagai Bapak Pendidikan Nasional.'",
          "",
          "[Ilustrasi: Sebuah infografis berbentuk kipas dengan 5 panel. Panel 1: ikon tinju (kata kerja tindakan). Panel 2: ikon bintang (kata sifat). Panel 3: ikon jam (konjungsi waktu). Panel 4: ikon perisai (kata pasif). Panel 5: ikon orang (pronomina). Setiap panel berwarna berbeda membentuk spektrum pelangi. Gaya ilustrasi kipas edukasi dengan warna-warni cerah.]",
        ],
        contoh: [
          "Bandingkan penggunaan bahasa:",
          "",
          "KURANG TEPAT: \"Ki Hajar Dewantara itu orang baik. Dia suka membantu orang. Beliau pintar dan terkenal.\"",
          "✗ Kata sifat umum, tidak ada detail tindakan konkret.",
          "",
          "LEBIH TEPAT: \"Ki Hajar Dewantara mendirikan Perguruan Taman Siswa pada tahun 1922 sebagai bentuk perjuangan pendidikan untuk pribumi. Beliau gigih memperjuangkan hak pendidikan tanpa membedakan golongan. Atas jasanya, beliau dianugerahi gelar Bapak Pendidikan Nasional.\"",
          "✓ Ada kata kerja tindakan (mendirikan, memperjuangkan), kata sifat konkret (gigih), konjungsi waktu (tahun 1922), dan pronomina (beliau).",
        ],
      },
      {
        judul: "Langkah Menulis Teks Biografi",
        isi: [
          "Siap menulis biografi seorang tokoh inspiratif? Ikuti panduan berikut!",
          "",
          "PENTING: Biografi yang baik didukung oleh data yang akurat. Jangan asal menulis — pastikan informasimu benar!",
          "",
          "1. Pilih tokoh yang menarik dan menginspirasi",
          "  Bisa tokoh nasional, pahlawan, ilmuwan, seniman, atlet, atau bahkan tokoh lokal di daerahmu.",
          "",
          "2. Kumpulkan data dan fakta",
          "  Cari informasi dari buku, artikel, situs terpercaya, atau wawancara langsung jika tokoh masih hidup.",
          "",
          "3. Susun kerangka kronologis",
          "  Urutkan peristiwa dari masa kecil hingga pencapaian utama tokoh.",
          "",
          "4. Tulis dengan bahasa yang hidup",
          "  Gunakan kata kerja tindakan dan kata sifat yang konkret. Hindari kalimat yang monoton.",
          "",
          "5. Sertakan nilai inspiratif",
          "  Biografi bukan sekadar daftar fakta — sampaikan pesan dan nilai yang bisa diteladani.",
          "",
          "[Ilustrasi: Seorang siswa duduk di meja belajar dengan laptop, buku-buku berserakan, dan secangkir kopi. Di layar laptop terlihat dokumen dengan judul 'BIOGRAFI'. Di sekelilingnya terdapat foto-foto tokoh inspiratif yang ditempel di papan. Gaya ilustrasi ruang belajar modern dengan warna hijau dan kuning.]",
        ],
        contoh: [
          "Kerangka biografi sederhana:",
          "",
          "JUDUL: \"B.J. Habibie: Sang Visioner Teknologi\"",
          "",
          "ORIENTASI: Lahir di Parepare, 25 Juni 1936. Putra keempat Alwi Abdul Jalil Habibie. Ayahnya seorang guru besar. Pendidikan: SD Parepare, SMP, SMA Bandung, kemudian kuliah teknik di ITB dan RWTH Aachen Jerman.",
          "",
          "PERISTIWA PENTING: Meraih gelar doktor dengan predikat summa cum laude. Bekerja di MBB GmbH Jerman. Kembali ke Indonesia atas panggilan Soeharto. Menjadi Menteri Riset dan Teknologi. Memimpin pengembangan pesawat N-250 Gatotkaca. Menjadi Presiden RI ke-3.",
          "",
          "REORIENTASI: Habibie adalah bukti bahwa dengan kecerdasan dan kerja keras, putra daerah bisa bersaing di tingkat global.",
        ],
      },
    ],
    rangkuman: [
      "[Ilustrasi: Tumpukan buku biografi dengan pita bertuliskan 'INSPIRASI'. Dari balik halaman buku muncul kilau cahaya keemasan dengan ikon-ikon: bintang (nilai teladan), panah waktu (kronologis), tanda kutip (fakta). Gaya ilustrasi buku terbuka dengan efek cahaya hangat.]",
      "Biografi adalah teks riwayat hidup seseorang yang ditulis oleh orang lain, bersifat faktual, kronologis, dan inspiratif.",
      "Struktur biografi: Orientasi (pengenalan) → Peristiwa Penting (inti perjalanan hidup) → Reorientasi (opsional, penutup inspiratif).",
      "Kaidah kebahasaan: kata kerja tindakan, kata sifat, konjungsi waktu, kata pasif, pronomina orang ketiga (ia, dia, beliau).",
      "Langkah menulis: pilih tokoh → kumpulkan data → susun kerangka → tulis dengan bahasa hidup → sematkan nilai inspiratif.",
    ],
  },
  latihan: makeSoal([
    ["Apa pengertian biografi?", ["Cerita fiksi tentang tokoh", "Riwayat hidup seseorang yang ditulis oleh orang lain", "Catatan harian seorang tokoh", "Puisi tentang kehidupan"], 1, "Biografi adalah riwayat hidup yang ditulis oleh orang lain tentang seseorang."],
    ["Perbedaan biografi dan autobiografi adalah...", ["Tidak ada perbedaan", "Biografi ditulis orang lain, autobiografi ditulis sendiri", "Biografi lebih panjang", "Autobiografi lebih objektif"], 1, "Autobiografi ditulis oleh tokoh itu sendiri, biografi oleh orang lain."],
    ["Bagian biografi yang berisi pengenalan tokoh disebut...", ["Orientasi", "Peristiwa Penting", "Reorientasi", "Koda"], 0, "Orientasi berisi pengenalan latar belakang tokoh: nama, kelahiran, keluarga."],
    ["Kata 'beliau' dalam biografi termasuk...", ["Kata kerja", "Pronomina orang ketiga", "Kata sifat", "Konjungsi"], 1, "'Beliau' adalah pronomina (kata ganti) orang ketiga yang sopan."],
    ["Biografi disusun secara...", ["Acak", "Kronologis", "Tematis", "Spasial"], 1, "Biografi disusun berdasarkan urutan waktu (kronologis)."],
    ["Berikut ini yang BUKAN ciri biografi adalah...", ["Faktual", "Inspiratif", "Fiktif", "Kronologis"], 2, "Biografi bersifat faktual, bukan fiktif atau rekaan."],
    ["Fungsi reorientasi dalam biografi adalah...", ["Mengenalkan tokoh", "Memberi kesimpulan dan pesan moral", "Menjelaskan peristiwa", "Menambah fakta"], 1, "Reorientasi berisi kesimpulan atau pesan inspiratif dari perjalanan hidup tokoh."],
    ["Contoh kata kerja tindakan dalam biografi adalah...", ["Beliau", "Kemudian", "Mendirikan", "Gigih"], 2, "'Mendirikan' adalah kata kerja tindakan yang menunjukkan aktivitas tokoh."],
    ["Tokoh biografi haruslah...", ["Tokoh fiktif", "Tokoh nyata", "Tokoh masa lalu", "Tokoh terkenal"], 1, "Tokoh biografi harus nyata — bisa terkenal atau tidak, yang penting menginspirasi."],
    ["Kata hubung kronologis yang tepat dalam biografi adalah...", ["Akan tetapi", "Pada tahun 1945", "Oleh karena itu", "Sebaliknya"], 1, "'Pada tahun 1945' menunjukkan waktu spesifik yang merupakan ciri penulisan kronologis."],
  ]),
  praktik: {
    petunjuk: "Pilihlah salah satu tokoh inspiratif berikut: (1) Ki Hajar Dewantara, (2) Cut Nyak Dien, (3) Chairil Anwar, atau (4) tokoh lokal di daerahmu. Tulislah teks biografi lengkap dengan struktur orientasi, peristiwa penting, dan reorientasi. Minimal 4 paragraf. Gunakan minimal 3 kata kerja tindakan, 3 kata sifat, dan 3 konjungsi waktu.",
    tips: [
      "Kumpulkan data dari minimal 3 sumber berbeda untuk memastikan akurasi",
      "Catat tanggal-tanggal penting dalam perjalanan hidup tokoh",
      "Fokus pada 2-3 peristiwa paling penting, jangan mencoba menulis semua detail",
      "Gunakan kutipan langsung tokoh jika ada untuk membuat cerita lebih hidup",
      "Akhiri dengan pesan inspiratif — apa yang bisa kita pelajari dari tokoh ini?",
    ],
    contoh: "Teks minimal 4 paragraf. Sertakan 3 kata kerja tindakan, 3 kata sifat, 3 konjungsi waktu, dan 1 kutipan langsung dari tokoh (jika tersedia).",
  },
  kuis: makeSoal([
    ["Biografi termasuk jenis teks...", ["Fiksi", "Nonfiksi faktual", "Puisi", "Drama"], 1, "Biografi termasuk teks nonfiksi faktual karena berdasarkan data nyata."],
    ["Yang dimaksud orientasi dalam biografi adalah...", ["Kesimpulan cerita", "Pengenalan tokoh dan latar belakang", "Perjuangan tokoh", "Pesan moral"], 1, "Orientasi mengenalkan tokoh, latar belakang keluarga, tempat dan tanggal lahir."],
    ["Mengapa biografi menggunakan sudut pandang orang ketiga?", ["Karena ditulis oleh orang lain", "Agar lebih objektif", "Karena tokohnya terkenal", "Semua jawaban benar"], 0, "Biografi ditulis oleh orang lain, sehingga wajar menggunakan sudut pandang orang ketiga."],
    ["Kata sifat yang tepat untuk menggambarkan tokoh pejuang adalah...", ["Malas", "Gigih", "Pemalu", "Cuek"], 1, "'Gigih' adalah kata sifat positif yang menggambarkan semangat juang tokoh."],
    ["Bagian biografi yang bersifat opsional adalah...", ["Orientasi", "Peristiwa Penting", "Reorientasi", "Judul"], 2, "Reorientasi bersifat opsional — tidak semua biografi mencantumkannya."],
    ["Biografi berbeda dengan CV (Curriculum Vitae) karena...", ["CV lebih lengkap", "Biografi berbentuk narasi kronologis, CV daftar data", "Sama saja", "Biografi untuk lamaran kerja"], 1, "Biografi berupa narasi yang mengalir, CV berupa data poin-poin faktual."],
    ["Salah satu nilai yang bisa dipetik dari biografi adalah...", ["Cara cepat kaya", "Semangat pantang menyerah", "Tips terkenal", "Rahasia sukses instan"], 1, "Nilai utama biografi adalah semangat pantang menyerah dan kerja keras tokoh."],
    ["Manakah penulisan pronomina yang tepat?", ["Aku bertemu Habibie", "Beliau adalah presiden ke-3 RI", "Kami membaca buku", "Mereka pergi"], 1, "'Beliau' adalah pronomina orang ketiga yang lazim dalam biografi."],
    ["Fakta dalam biografi harus...", ["Dapat diverifikasi kebenarannya", "Menarik meski tidak benar", "Dibesar-besarkan", "Fiktif"], 0, "Fakta biografi harus dapat diverifikasi — bisa dicek kebenarannya."],
    ["Contoh reorientasi yang baik adalah...", ["'Habibie lahir di Parepare'", "'Dari kisah Habibie, kita belajar bahwa keterbatasan bukan halangan untuk berkarya'", "'Habibie sekolah di Jerman'", "'Habibie menikah dengan Hasri Ainun'"], 1, "Reorientasi berisi kesimpulan atau pesan inspiratif, bukan fakta baru."],
  ]),
}

export default konten
