import type { Konten } from "../types"
import { makeSoal } from "../types"

const konten: Konten = {
  belajar: {
    tujuan: [
      "Memahami pengertian dan ciri-ciri puisi kontemporer",
      "Mengidentifikasi jenis-jenis puisi kontemporer",
      "Menganalisis diksi, rima, dan tipografi dalam puisi kontemporer",
      "Menulis puisi kontemporer dengan gaya dan tema yang relevan",
      "Mengapresiasi puisi kontemporer sebagai bentuk ekspresi seni modern",
    ],
    materi: [
      {
        judul: "Mengenal Puisi Kontemporer",
        isi: [
          "Puisi bukan hanya tentang rima dan irama yang indah. Ada jenis puisi yang lebih bebas, lebih eksperimental, dan lebih dekat dengan kehidupan sehari-hari — itulah puisi kontemporer.",
          "",
          "Puisi kontemporer adalah puisi modern yang lahir pada era 1970-an hingga sekarang. Puisi ini bebas dari aturan-aturan klasik seperti jumlah baris, rima akhir, atau suku kata. Yang terpenting adalah ekspresi, makna, dan kreasinya.",
          "",
          "✓ Ciri-ciri puisi kontemporer:",
          "  ✓ Bebas dari aturan konvensional (tidak terikat rima, jumlah baris, atau suku kata)",
          "  ✓ Menggunakan bahasa sehari-hari bahkan bahasa gaul",
          "  ✓ Bermain dengan tipografi (bentuk visual puisi di atas kertas)",
          "  ✓ Mengandung kritik sosial, kegelisahan, atau refleksi hidup modern",
          "  ✓ Sering menggunakan enjambemen (pemotongan baris di tengah kalimat)",
          "",
          "[Ilustrasi: Sebuah panggung puisi malam hari dengan lampu temaram. Seorang penyair berdiri di depan mikrofon, memegang buku puisi. Di latar belakang ada layar besar menampilkan tipografi puisi yang artistik. Penonton duduk di lantai dengan tatapan khusyuk. Gaya ilustrasi pertunjukan seni dengan warna ungu dan biru malam.]",
        ],
        contoh: [
          "Bandingkan puisi lama vs kontemporer:",
          "",
          "PUISI KLASIK (Pantun):",
          "\"Kalau ada jarum yang patah, / Jangan disimpan di dalam peti. / Kalau ada kata yang salah, / Jangan disimpan di dalam hati.\"",
          "✓ Terikat aturan: 4 baris, a-b-a-b, 8-12 suku kata.",
          "",
          "PUISI KONTEMPORER (Sutardji Calzoum Bachri):",
          "\"aku / ingin / mencintaimu / dengan sederhana / dengan kata yang tak sempat / diucapkan / kayu kepada api / yang menjadikannya abu.\"",
          "✓ Bebas, tipografi unik, bahasa sederhana, makna filosofis.",
        ],
        catatan: "Pelopor puisi kontemporer Indonesia antara lain Sutardji Calzoum Bachri, Sapardi Djoko Damono, Goenawan Mohamad, dan Afrizal Malna. Sutardji bahkan dijuluki 'Presiden Penyair Indonesia' karena gaya puisinya yang revolusioner.",
      },
      {
        judul: "Jenis-Jenis Puisi Kontemporer",
        isi: [
          "Puisi kontemporer hadir dalam berbagai bentuk yang unik dan menarik. Mari kita kenali satu per satu!",
          "",
          "1. PUISI MANTRA",
          "  Puisi yang menggunakan pengulangan kata-kata tertentu sehingga menimbulkan efek magis atau hipnotis. Kata-kata tidak selalu logis, lebih mementingkan bunyi dan suasana. Pelopor: Sutardji Calzoum Bachri.",
          "",
          "2. PUISI TIPOGRAFI / KONKRET",
          "  Puisi yang bentuk visualnya (tata letak, huruf, simbol) ikut membangun makna. Puisi ini 'dibaca' tidak hanya dari kata-katanya, tetapi juga dari bentuknya. Pelopor: Helvy Tiana Rosa, Sitor Situmorang.",
          "",
          "3. PUISI MIMESIS",
          "  Puisi yang meniru bentuk benda yang dibicarakan. Misalnya puisi tentang pisang ditulis melengkung seperti pisang, puisi tentang jalan ditulis berbelok seperti jalan.",
          "",
          "4. PUISI LIRIK MODERN",
          "  Puisi yang tetap mempertahankan unsur lirik (perasaan, keindahan) tetapi dikemas dengan gaya kontemporer — bebas, segar, dan eksperimental.",
          "",
          "[Ilustrasi: Empat panel seni kolase. Panel 1 'MANTRA' — tangan menabuh rebana dengan kata-kata melingkar. Panel 2 'TIPOGRAFI' — huruf-huruf membentuk wajah. Panel 3 'MIMESIS' — teks meliuk seperti ular. Panel 4 'LIRIK' — hati dengan sayap dari kata-kata. Gaya ilustrasi kolase digital dengan warna-warna kontras.]",
        ],
        contoh: [
          "Contoh PUISI TIPOGRAFI — 'Ibu' karya Sapardi Djoko Damono versi tipografi:",
          "",
          "  i",
          "  bu",
          "  ibu",
          "  ibuku",
          "  dulu",
          "  pernah",
          "  berjanji",
          "  takkan",
          "  pernah",
          "  menangis",
          "",
          "Bentuk menara ke bawah menggambarkan kenangan yang meruncing ke masa lalu.",
        ],
      },
      {
        judul: "Diksi, Rima, dan Tipografi dalam Puisi Kontemporer",
        isi: [
          "Puisi kontemporer tetap menggunakan elemen-elemen puisi, tetapi dengan cara yang lebih bebas dan kreatif.",
          "",
          "1. DIKSI (Pilihan Kata)",
          "  Puisi kontemporer menggunakan diksi yang segar, tidak klise, dan sering mengejutkan. Penyair menciptakan metafora baru, bermain dengan majas, dan mencampur bahasa (Indonesia, daerah, asing, gaul).",
          "  Contoh: 'kata-kata / bersayap / melayang / di ubun-ubun malam' — metafora segar.",
          "",
          "2. RIMA",
          "  Tidak terikat rima akhir (a-b-a-b). Rima bisa internal (di dalam baris) atau tidak ada sama sekali. Yang penting adalah ritme dan musikalitas alami bahasa.",
          "",
          "3. TIPOGRAFI",
          "  Tipografi adalah seni mengatur huruf dan tata letak puisi. Puisi kontemporer sering memanfaatkan tipografi sebagai elemen estetika dan makna. Penulisan huruf kapital, kecil, miring, spasi, dan baris baru memiliki makna.",
          "",
          "[Ilustrasi: Meja kerja seorang penyair dengan kertas-kertas berisi coretan puisi, pulpen, dan secangkir teh. Di dinding ada papan inspirasi dengan kata-kata yang dipotong dari majalah dan ditempel. Laptop terbuka dengan dokumen puisi. Suasana kreatif yang hangat. Gaya ilustrasi meja penuh inspirasi dengan warna krem dan biru.]",
        ],
        contoh: [
          "Analisis tipografi dalam puisi 'Perahu Kertas' — Sapardi Djoko Damono:",
          "",
          "\"Perahu kertas / meluncur / di kolam / jernih\"",
          "",
          "Setiap kata dipisah baris baru. Ini menciptakan efek visual seperti perahu yang benar-benar bergerak pelan di atas air. Pembaca dipaksa membaca perlahan, menghayati setiap kata.",
          "",
          "Bandingkan jika ditulis normal: \"Perahu kertas meluncur di kolam jernih.\"",
          "Maknanya sama, tetapi efeknya berbeda — lebih cepat, kehilangan nuansa.",
        ],
      },
      {
        judul: "Menulis Puisi Kontemporer",
        isi: [
          "Sekarang giliranmu! Menulis puisi kontemporer tidak sulit. Ikuti tips berikut.",
          "",
          "PENTING: Tidak ada aturan baku dalam puisi kontemporer. Bebaskan imajinasimu! Yang penting adalah kejujuran emosi dan kreativitas.",
          "",
          "1. Tentukan tema yang dekat denganmu",
          "  Cinta, persahabatan, alam, kota, kritik sosial, kegelisahan, atau hal-hal sepele sehari-hari.",
          "",
          "2. Amati sekelilingmu dengan saksama",
          "  Puisi kontemporer sering lahir dari hal-hal sederhana: suara hujan, antrean di kantin, layar HP, atau bahkan bau kopi.",
          "",
          "3. Mainkan kata-kata",
          "  Ciptakan metafora unik. Jangan takut menggunakan kata tidak biasa. Campur bahasa Indonesia dengan bahasa daerah atau Inggris.",
          "",
          "4. Eksperimen dengan bentuk",
          "  Tulis puisi menyerupai benda yang kamu bicarakan. Mainkan huruf kapital-kecil. Gunakan spasi yang tidak biasa.",
          "",
          "5. Bacakan keras-keras",
          "  Puisi kontemporer lahir untuk dibacakan. Rasakan ritmenya. Jangan ragu merevisi jika terdengar janggal.",
          "",
          "[Ilustrasi: Tangan seorang remaja menulis di buku catatan dengan spidol warna-warni. Halaman buku penuh dengan coretan, revisi, dan variasi kata yang dicoret-coret. Beberapa kertas berisi puisi yang sudah jadi ditempel di dinding. Gaya ilustrasi jurnal pribadi dengan warna oranye dan kuning.]",
        ],
        contoh: [
          "Tips membuat metafora segar:",
          "",
          "KLISE: \"Cintaku seperti lautan\" (terlalu sering dipakai)",
          "",
          "SEGAR: \"Cintaku seperti kode QR / tak terbaca tanpa lensa yang tepat\" (metafora baru, relevan dengan zaman digital)",
          "",
          "KLISE: \"Hidup adalah perjalanan\" (biasa)",
          "",
          "SEGAR: \"Hidup adalah refresh TikTok / tak pernah sama setiap scroll\" (kontekstual dengan keseharian remaja)",
        ],
      },
    ],
    rangkuman: [
      "[Ilustrasi: Kolase kata-kata puisi dari berbagai warna dan ukuran huruf membentuk gradien pelangi. Di tengah-tengah ada garis putih berbentuk hati dan bintang. Kata-kata seperti 'bebas', 'ekspresi', 'makna', 'kreatif' menonjol di antara baris puisi. Gaya ilustrasi kolase tipografi abstrak.]",
      "Puisi kontemporer adalah puisi modern yang bebas dari aturan klasik, mengutamakan ekspresi, makna, dan kreativitas.",
      "Jenis puisi kontemporer: mantra, tipografi/konkret, mimesis, dan lirik modern.",
      "Elemen puisi kontemporer: diksi segar dan mengejutkan, rima bebas, tipografi artistik sebagai bagian dari makna.",
      "Tips menulis: tema dekat denganmu → amati sekeliling → mainkan kata → eksperimen bentuk → bacakan keras-keras.",
    ],
  },
  latihan: makeSoal([
    ["Apa yang membedakan puisi kontemporer dari puisi klasik?", ["Tidak ada perbedaan", "Puisi kontemporer bebas dari aturan klasik", "Puisi kontemporer lebih panjang", "Puisi kontemporer bersajak a-b-a-b"], 1, "Puisi kontemporer bebas dari aturan jumlah baris, rima, dan suku kata."],
    ["Siapa yang dijuluki 'Presiden Penyair Indonesia'?", ["Sapardi Djoko Damono", "Sutardji Calzoum Bachri", "Chairil Anwar", "Goenawan Mohamad"], 1, "Sutardji Calzoum Bachri dijuluki Presiden Penyair Indonesia."],
    ["Puisi yang bentuk visualnya ikut membangun makna disebut...", ["Puisi mantra", "Puisi tipografi", "Puisi mimesis", "Puisi lirik"], 1, "Puisi tipografi (konkret) memanfaatkan bentuk visual sebagai bagian dari makna."],
    ["Salah satu ciri puisi mantra adalah...", ["Menggunakan rima a-b-a-b", "Pengulangan kata yang menimbulkan efek magis", "Bentuk meniru benda", "Bahasa formal"], 1, "Puisi mantra menggunakan pengulangan kata yang menimbulkan efek hipnotis atau magis."],
    ["Diksi dalam puisi kontemporer cenderung...", ["Klise dan konvensional", "Segar, mengejutkan, dan tidak terduga", "Formal dan baku", "Sama seperti prosa"], 1, "Diksi puisi kontemporer segar, orisinal, dan sering mengejutkan."],
    ["'Tipografi' dalam puisi berarti...", ["Jenis huruf", "Tata letak dan bentuk visual puisi", "Jumlah baris", "Rima akhir"], 1, "Tipografi adalah seni mengatur huruf dan tata letak puisi sebagai elemen makna."],
    ["Contoh puisi mimesis adalah...", ["Puisi ditulis melingkar seperti bola", "Puisi bersajak bebas", "Puisi tentang cinta", "Puisi 4 baris"], 0, "Puisi mimesis meniru bentuk benda yang dibicarakan, misalnya melingkar seperti bola."],
    ["Enjambemen dalam puisi adalah...", ["Pengulangan kata", "Pemotongan baris di tengah kalimat", "Rima akhir", "Jumlah suku kata"], 1, "Enjambemen adalah pemotongan baris puisi di tengah kalimat untuk efek tertentu."],
    ["Puisi kontemporer lahir pada era...", ["1950-an", "1970-an hingga sekarang", "Zaman penjajahan", "2000-an"], 1, "Puisi kontemporer berkembang mulai 1970-an hingga kini."],
    ["'Cintaku seperti kode QR' adalah contoh...", ["Rima", "Metafora segar", "Tipografi", "Mantra"], 1, "Metafora segar menggunakan perbandingan baru yang kontekstual dengan zaman."],
  ]),
  praktik: {
    petunjuk: "Buatlah sebuah puisi kontemporer bertema bebas (bisa tentang sekolah, pertemanan, media sosial, alam, atau kegelisahanmu). Tulis minimal 10 baris. Gunakan tipografi yang unik, ciptakan minimal 2 metafora segar, dan mainkan dengan enjambemen. Bacakan puisimu di depan kelas dan mintalah tanggapan teman-temanmu!",
    tips: [
      "Mulailah dengan satu baris pertama yang kuat — bisa berupa pertanyaan, pernyataan mengejutkan, atau gambaran konkret",
      "Jangan menjelaskan — puisi tidak perlu \"cerita\" seperti prosa, cukup kesan dan suasana",
      "Gunakan panca indra: apa yang kamu lihat, dengar, cium, raba? Deskripsikan secara puitis",
      "Bacakan puisimu beberapa kali dan rasakan apakah alurnya sudah enak",
      "Mintalah teman membaca puisimu — jika mereka tersenyum, merenung, atau terkejut, puisimu berhasil",
    ],
    contoh: "Puisi minimal 10 baris dengan tipografi unik. Sertakan 2 metafora segar dan minimal 1 enjambemen. Bebas tema.",
  },
  kuis: makeSoal([
    ["Siapa penyair yang terkenal dengan puisi mantranya?", ["Sapardi Djoko Damono", "Sutardji Calzoum Bachri", "W.S. Rendra", "Taufik Ismail"], 1, "Sutardji Calzoum Bachri terkenal dengan puisi mantranya yang revolusioner."],
    ["Mengapa puisi kontemporer disebut puisi 'bebas'?", ["Tidak dijual", "Tidak terikat aturan puisi klasik", "Tidak punya makna", "Tidak perlu dibaca"], 1, "Puisi kontemporer bebas dari aturan puisi klasik seperti rima, baris, dan suku kata."],
    ["Puisi yang meniru bentuk benda yang dibicarakan disebut...", ["Puisi mantra", "Puisi tipografi", "Puisi mimesis", "Puisi naratif"], 2, "Mimesis berarti meniru — puisi yang bentuknya meniru benda yang dibahas."],
    ["Salah satu fungsi tipografi dalam puisi kontemporer adalah...", ["Memperpanjang puisi", "Menambah makna visual", "Membuat rima", "Menambah jumlah kata"], 1, "Tipografi menambah dimensi makna melalui bentuk visual."],
    ["'Ibu' karya Sapardi Djoko Damono yang ditulis menurun adalah contoh...", ["Puisi mantra", "Puisi tipografi", "Puisi mimesis", "Puisi epik"], 1, "Bentuk menurun ke bawah menggambarkan kenangan yang meruncing."],
    ["Bahasa yang digunakan dalam puisi kontemporer cenderung...", ["Formal dan baku", "Sehari-hari, segar, bahkan gaul", "Klasik dan puitis", "Asing"], 1, "Puisi kontemporer menggunakan bahasa sehari-hari, segar, dan eksperimental."],
    ["Puisi kontemporer berbeda dengan puisi klasik dalam hal...", ["Keduanya sama", "Kebebasan bentuk dan ekspresi", "Panjang baris", "Jenis kertas"], 1, "Perbedaan utamanya adalah kebebasan bentuk dan ekspresi."],
    ["Apa yang dimaksud dengan 'diksi' dalam puisi?", ["Panjang puisi", "Pilihan kata", "Jenis puisi", "Tema puisi"], 1, "Diksi adalah pilihan kata yang digunakan penyair."],
    ["Contoh enjambemen terdapat pada...", ["'Aku / ingin / mencintaimu / dengan sederhana'", "'Aku ingin mencintaimu dengan sederhana'", "'Aku ingin'", "'Mencintaimu'"], 0, "Enjambemen adalah pemotongan baris, terlihat pada penulisan baris per kata."],
    ["Nilai utama yang bisa dipetik dari puisi kontemporer adalah...", ["Kepatuhan pada aturan", "Kebebasan berekspresi dan kreativitas", "Keindahan rima", "Panjangnya puisi"], 1, "Puisi kontemporer mengajarkan kebebasan ekspresi dan kreativitas tanpa batas."],
  ]),
}

export default konten
