import type { Konten } from "../types"
import { makeSoal } from "../types"

const konten: Konten = {
  belajar: {
    tujuan: [
      "Memahami pengertian dan ciri-ciri cerpen sebagai karya fiksi",
      "Mengidentifikasi unsur intrinsik dan ekstrinsik cerpen",
      "Menganalisis alur, penokohan, dan latar dalam cerpen",
      "Menulis cerpen berdasarkan pengalaman atau imajinasi dengan struktur yang tepat",
      "Mengapresiasi cerpen sebagai media ekspresi dan refleksi kehidupan",
    ],
    materi: [
      {
        judul: "Mengenal Cerpen",
        isi: [
          "Pernahkah kamu membaca cerita yang selesai dalam sekali duduk? Saat istirahat, saat menunggu bus, atau sebelum tidur? Itulah keistimewaan cerpen — cerita pendek yang padat, berisi, dan langsung pada intinya.",
          "",
          "Cerpen (cerita pendek) adalah prosa fiksi yang menceritakan satu peristiwa utama dengan jumlah tokoh terbatas. Cerpen biasanya selesai dibaca dalam satu kali duduk (sekitar 30 menit hingga 1 jam).",
          "",
          "✓ Ciri-ciri cerpen:",
          "  ✓ Cerita fiktif (rekaan), bukan berdasarkan kejadian nyata",
          "  ✓ Fokus pada satu konflik atau peristiwa utama",
          "  ✓ Jumlah tokoh terbatas (biasanya 2-5 tokoh)",
          "  ✓ Alur tunggal (tidak bercabang-cabang seperti novel)",
          "  ✓ Selesai dibaca dalam satu kali duduk",
          "  ✓ Menimbulkan satu efek atau kesan tertentu bagi pembaca",
          "",
          "[Ilustrasi: Seorang remaja duduk santai di kursi baca perpustakaan, memegang buku cerpen dengan sampul warna-warni. Di sekelilingnya ada tumpukan buku cerpen lain. Ekspresinya tersenyum kecil, seolah larut dalam cerita. Gaya ilustrasi perpustakaan modern dengan warna cokelat dan hijau.]",
        ],
        contoh: [
          "Perbedaan cerpen dengan novel:",
          "",
          "CERPEN: \"Malaikat Juga Tahu\" karya Dee Lestari — kisah cinta segitiga antara dua sahabat dan seorang perempuan. Fokus pada konflik batin tokoh utama. 10 halaman.",
          "✓ Satu konflik, satu efek, satu kali duduk.",
          "",
          "NOVEL: \"Laskar Pelangi\" karya Andrea Hirata — kisah perjuangan 10 anak di Belitung untuk mendapatkan pendidikan. Banyak tokoh, alur bercabang, banyak konflik. 500+ halaman.",
          "✓ Banyak konflik, banyak tokoh, butuh waktu berhari-hari.",
        ],
        catatan: "Cerpen Indonesia modern mulai berkembang pada era Pujangga Baru (1930-an) dengan tokoh seperti Sutan Takdir Alisjahbana dan Armijn Pane. Salah satu cerpen legendaris adalah 'Robohnya Surau Kami' karya A.A. Navis (1955).",
      },
      {
        judul: "Unsur Intrinsik Cerpen",
        isi: [
          "Setiap cerpen memiliki unsur-unsur pembangun dari dalam yang membuatnya hidup. Mari kita bedah satu per satu!",
          "",
          "1. TEMA",
          "  Gagasan pokok yang mendasari cerita. Tema bisa berupa: cinta, persahabatan, perjuangan, pengorbanan, kritik sosial, atau keluarga.",
          "",
          "2. ALUR (PLOT)",
          "  Rangkaian peristiwa dalam cerita. Alur maju (kronologis), alur mundur (flashback), atau alur campuran.",
          "  Tahapan alur: pengenalan → konflik → klimaks → antiklimaks → penyelesaian.",
          "",
          "3. TOKOH DAN PENOKOHAN",
          "  Tokoh: protagonis (baik), antagonis (lawan), tritagonis (penengah).",
          "  Penokohan: cara menggambarkan karakter tokoh — melalui dialog, tindakan, pikiran, atau komentar tokoh lain.",
          "",
          "4. LATAR (SETTING)",
          "  Tempat, waktu, dan suasana terjadinya cerita. Latar bisa bersifat fisik (ruang kelas, pantai) dan sosial (budaya, adat).",
          "",
          "5. SUDUT PANDANG",
          "  Posisi pengarang dalam cerita: orang pertama ('aku'), orang ketiga ('ia/dia'), atau orang ketiga serba tahu.",
          "",
          "6. AMANAT",
          "  Pesan moral yang ingin disampaikan pengarang kepada pembaca. Biasanya tersirat, tidak langsung disebutkan.",
          "",
          "[Ilustrasi: Diagram rumah dengan 6 pilar. Setiap pilar diberi label: TEMA (atap), ALUR (pilar kiri), TOKOH (pilar kanan), LATAR (pilar belakang), SUDUT PANDANG (pilar depan), AMANAT (fondasi). Setiap pilar memiliki ikon masing-masing. Gaya ilustrasi bangunan edukasi dengan warna-warna pastel.]",
        ],
        contoh: [
          "Analisis cerpen 'Robohnya Surau Kami' — A.A. Navis:",
          "",
          "TEMA: Kritik terhadap fanatisme agama yang berlebihan.",
          "ALUR: Campuran — ada flashback ke masa lalu tokoh Garin dan kakeknya.",
          "TOKOH: Garin (protagonis, kritis), Kakek (antagonis, fanatik), Aku (tritagonis, narator).",
          "LATAR: Surau, rumah Garin, kota — tahun 1950-an.",
          "SUDUT PANDANG: Orang pertama ('aku' sebagai narator).",
          "AMANAT: Jangan menjalankan agama secara fanatik tanpa memahami esensinya.",
        ],
      },
      {
        judul: "Unsur Ekstrinsik Cerpen",
        isi: [
          "Selain unsur dari dalam, cerpen juga dipengaruhi oleh hal-hal dari luar. Ini disebut unsur ekstrinsik.",
          "",
          "1. LATAR BELAKANG PENGARANG",
          "  Pengalaman hidup, pendidikan, profesi, dan pandangan dunia pengarang memengaruhi cerita yang ditulisnya. Cerpen karya guru, jurnalis, psikolog, atau petualang akan berbeda nuansanya.",
          "",
          "2. LATAR BELAKANG SOSIAL BUDAYA",
          "  Kondisi masyarakat saat cerpen ditulis: politik, ekonomi, adat, nilai-nilai sosial, dan budaya. Cerpen era 1960-an akan berbeda dengan era Reformasi 1998 atau era digital saat ini.",
          "",
          "3. NILAI-NILAI (MORAL, AGAMA, SOSIAL)",
          "  Cerpen merefleksikan nilai-nilai yang dianut masyarakat. Nilai moral tentang baik-buruk, nilai agama tentang ketuhanan, nilai sosial tentang gotong royong dan kebersamaan.",
          "",
          "[Ilustrasi: Tiga lingkaran konsentris. Lingkaran terdalam: teks cerpen. Lingkaran tengah: 'PENGARANG' dengan ikon pena dan buku. Lingkaran terluar: 'MASYARAKAT' dengan ikon rumah, pabrik, sekolah, dan masjid. Di antara lingkaran ada panah dua arah. Gaya ilustrasi diagram pengaruh dengan warna biru dan oranye.]",
        ],
        contoh: [
          "Pengaruh latar belakang pengarang pada cerpen:",
          "",
          "Cerpen 'Senyum Karyamin' — Ahmad Tohari.",
          "Latar belakang: Ahmad Tohari adalah penulis yang tumbuh di desa Banyumas dengan latar pedesaan Jawa.",
          "",
          "Cerpen ini sangat kuat menggambarkan kehidupan rakyat desa yang berjuang melawan kemiskinan. Detail tentang bukit kapur, tukang batu, dan pasar tradisional terasa autentik karena pengarang benar-benar mengenal dunia itu.",
          "",
          "Pengaruh latar sosial budaya: Cerpen 'Mega, Mega' — Arswendo Atmowiloto (era 1980-an) menggambarkan kehidupan kelas menengah di kota yang mulai terpengaruh budaya Barat.",
        ],
      },
      {
        judul: "Langkah Menulis Cerpen",
        isi: [
          "Sekarang waktunya kamu menulis cerpen sendiri! Tidak perlu bingung, ikuti panduan sederhana ini.",
          "",
          "PENTING: Cerpen yang baik tidak perlu panjang. Yang penting adalah konflik yang menarik dan penyampaian yang efektif.",
          "",
          "1. Temukan ide",
          "  Ide bisa datang dari mana saja: pengalaman pribadi, pengalaman teman, berita di TV, mimpi, atau imajinasi liar. Catat semua ide menarik yang muncul.",
          "",
          "2. Tentukan tokoh dan konflik",
          "  Siapa tokoh utamanya? Masalah apa yang ia hadapi? Konflik inilah yang akan menjadi inti cerpenmu.",
          "",
          "3. Susun kerangka alur",
          "  Buat poin-poin: pengenalan → muncul masalah → konflik memuncak → menuju penyelesaian → selesai.",
          "",
          "4. Tulis draf pertama",
          "  Jangan terlalu memikirkan kesempurnaan. Tulis saja dulu sampai selesai. Biarkan cerita mengalir.",
          "",
          "5. Revisi dan edit",
          "  Setelah selesai, istirahat dulu. Kemudian baca lagi. Perbaiki dialog, alur, pilihan kata, dan ejaan. Potong bagian yang tidak penting.",
          "",
          "[Ilustrasi: Tiga bocah duduk melingkar di taman, masing-masing memegang buku catatan dan pulpen. Salah satu dari mereka sedang membacakan cerita dengan ekspresi antusias. Latar belakang taman bermain dengan ayunan dan perosotan. Gaya ilustrasi taman kanak-kanak kreatif dengan warna cerah.]",
        ],
        contoh: [
          "Kerangka cerpen sederhana:",
          "",
          "JUDUL: \"Nasi Bungkus Terakhir\"",
          "",
          "PENGENALAN: Rina, siswi SMA, setiap hari membawa nasi bungkus untuk bekal sekolah.",
          "KONFLIK: Suatu hari Rina melihat seorang anak jalanan kelaparan di depan sekolah. Rina ragu — memberi bekalnya atau tidak? Kalau memberi, ia akan kelaparan.",
          "KLIMAKS: Rina memutuskan memberi nasi bungkusnya. Anak itu tersenyum dan mengucapkan terima kasih.",
          "PENYELESAIAN: Sepulang sekolah, Rina tak sengaja menemukan dompet berisi uang di jalan. Ia mengembalikannya pada pemiliknya. Pemilik dompet ternyata orang tua anak jalanan yang tadi.",
        ],
      },
    ],
    rangkuman: [
      "[Ilustrasi: Tumpukan buku cerpen berbagai ukuran dan warna di atas meja kayu. Buku paling atas terbuka dan dari halamannya muncul elemen-elemen seperti: ikon orang (tokoh), jam (alur), rumah (latar), dan hati (amanat). Ada secangkir kopi di sampingnya. Gaya ilustrasi meja baca yang hangat dengan warna cokelat dan krem.]",
      "Cerpen adalah prosa fiksi yang fokus pada satu konflik, tokoh terbatas, dan selesai dibaca satu kali duduk.",
      "Unsur intrinsik: tema, alur, tokoh, latar, sudut pandang, amanat. Unsur ekstrinsik: latar belakang pengarang dan sosial budaya.",
      "Alur cerpen: pengenalan → konflik → klimaks → antiklimaks → penyelesaian.",
      "Langkah menulis: temukan ide → tentukan tokoh/konflik → susun kerangka → tulis draf → revisi.",
    ],
  },
  latihan: makeSoal([
    ["Apa pengertian cerpen?", ["Cerita panjang berisi banyak konflik", "Prosa fiksi dengan satu konflik utama dan tokoh terbatas", "Puisi modern", "Karya ilmiah"], 1, "Cerpen adalah prosa fiksi pendek dengan satu konflik utama dan tokoh terbatas."],
    ["Unsur intrinsik cerpen meliputi...", ["Tema, alur, tokoh, latar, sudut pandang, amanat", "Latar belakang pengarang, sosial budaya", "Harga buku, penerbit", "Jumlah halaman, sampul"], 0, "Unsur intrinsik adalah unsur pembangun dari dalam cerita."],
    ["Amanat dalam cerpen biasanya disampaikan secara...", ["Tersirat", "Tersurat", "Langsung", "Di awal cerita"], 0, "Amanat biasanya tersirat — tidak langsung disebutkan, pembaca menyimpulkan sendiri."],
    ["Alur yang menceritakan masa lalu disebut...", ["Alur maju", "Alur mundur", "Alur campuran", "Alur lurus"], 1, "Alur mundur (flashback) menceritakan peristiwa masa lalu."],
    ["Tokoh yang menjadi lawan tokoh utama disebut...", ["Protagonis", "Antagonis", "Tritagonis", "Figuran"], 1, "Antagonis adalah tokoh yang berlawanan dengan protagonis."],
    ["Yang BUKAN termasuk unsur ekstrinsik cerpen adalah...", ["Latar belakang pengarang", "Nilai sosial budaya", "Tema cerita", "Kondisi politik saat cerita ditulis"], 2, "Tema adalah unsur intrinsik, bukan ekstrinsik."],
    ["Sudut pandang 'aku' dalam cerpen berarti...", ["Pengarang serba tahu", "Pengarang sebagai tokoh dalam cerita", "Pengarang sebagai pengamat", "Pengarang tidak terlibat"], 1, "Sudut pandang orang pertama ('aku') berarti pengarang menjadi tokoh dalam cerita."],
    ["Contoh cerpen legendaris Indonesia adalah...", ["Laskar Pelangi", "Robohnya Surau Kami", "Ronggeng Dukuh Paruk", "Bumi Manusia"], 1, "'Robohnya Surau Kami' karya A.A. Navis adalah cerpen legendaris Indonesia."],
    ["Fungsi latar dalam cerpen adalah...", ["Memperindah cerita", "Memberi gambaran tempat, waktu, dan suasana", "Menambah tokoh", "Mengubah alur"], 1, "Latar memberi gambaran tentang di mana, kapan, dan bagaimana suasana cerita."],
    ["Cerpen yang baik memiliki konflik yang...", ["Banyak dan rumit", "Menarik dan relevan dengan tema", "Tidak penting", "Selesai di awal"], 1, "Konflik harus menarik dan relevan dengan tema yang diangkat."],
  ]),
  praktik: {
    petunjuk: "Tulislah sebuah cerpen berdasarkan pengalaman pribadi atau imajinasi dengan tema 'Kebaikan yang Berbalas'. Panjang cerpen 2-3 halaman (500-700 kata). Gunakan struktur alur lengkap: pengenalan, konflik, klimaks, penyelesaian. Sertakan minimal 3 tokoh, 2 latar berbeda, dan sudut pandang orang pertama.",
    tips: [
      "Gunakan pengalaman pribadi sebagai inspirasi — lebih mudah menulis apa yang kamu rasakan",
      "Buat pembukaan yang menarik — bisa berupa dialog, pertanyaan, atau deskripsi yang mengejutkan",
      "Gunakan dialog untuk menghidupkan cerita, jangan hanya narasi",
      "Tunjukkan, jangan beri tahu — misalnya, 'Rina menggigit bibir, tangannya gemetar' lebih hidup daripada 'Rina gugup'",
      "Akhiri dengan kesan yang membekas — twist, kejutan, atau amanat yang halus",
    ],
    contoh: "Cerpen 500-700 kata dengan alur lengkap. Sertakan 3 tokoh, 2 latar, sudut pandang orang pertama, dan dialog minimal 5 baris.",
  },
  kuis: makeSoal([
    ["Prosa fiksi pendek dengan satu konflik utama disebut...", ["Novel", "Cerpen", "Puisi", "Drama"], 1, "Cerpen adalah prosa fiksi pendek dengan satu konflik utama."],
    ["Tahapan alur yang benar adalah...", ["Klimaks → konflik → penyelesaian", "Pengenalan → konflik → klimaks → antiklimaks → penyelesaian", "Konflik → pengenalan → klimaks", "Penyelesaian → konflik → pengenalan"], 1, "Alur standar: pengenalan → konflik → klimaks → antiklimaks → penyelesaian."],
    ["Tokoh tritagonis dalam cerpen berfungsi sebagai...", ["Lawan tokoh utama", "Penengah atau pendukung", "Tokoh utama", "Tokoh figuran"], 1, "Tritagonis adalah penengah atau tokoh yang mendukung protagonis."],
    ["Mengapa cerpen disebut 'selesai sekali duduk'?", ["Karena harus dibaca cepat", "Karena efektif dan tidak panjang", "Karena tidak menarik", "Karena susah dipahami"], 1, "Cerpen efektif dan pendek sehingga selesai dalam satu kali duduk."],
    ["Salah satu cara menggambarkan karakter tokoh adalah melalui...", ["Panjang cerita", "Dialog dan tindakan", "Jumlah halaman", "Sampul buku"], 1, "Karakter tokoh digambarkan melalui dialog, tindakan, pikiran, dan komentar tokoh lain."],
    ["Unsur ekstrinsik cerpen berkaitan dengan...", ["Struktur cerita", "Faktor luar yang memengaruhi cerita", "Tokoh cerita", "Latar cerita"], 1, "Unsur ekstrinsik adalah faktor di luar cerita yang memengaruhinya."],
    ["'Aku tersenyum pahit. Langit seolah ikut sedih.' Ini adalah contoh sudut pandang...", ["Orang ketiga", "Orang pertama", "Orang kedua", "Serba tahu"], 1, "Kata 'aku' menunjukkan sudut pandang orang pertama."],
    ["Tema 'kritik sosial' dalam cerpen berarti cerita menyoroti...", ["Masalah dalam masyarakat", "Cinta segitiga", "Petualangan"], 0, "Kritik sosial menyoroti masalah-masalah dalam masyarakat."],
    ["Hal terpenting dalam menulis cerpen adalah...", ["Panjang cerita", "Konflik yang menarik", "Harga kertas", "Jumlah kata"], 1, "Konflik adalah inti dari cerpen — tanpa konflik, cerita tidak menarik."],
    ["Amanat yang baik disampaikan secara...", ["Langsung dan jelas", "Halus dan tersirat", "Di judul", "Di akhir saja"], 1, "Amanat yang baik disampaikan secara halus dan tersirat, pembaca menyimpulkan sendiri."],
  ]),
}

export default konten
