import type { Konten } from "../types"
import { makeSoal } from "../types"

const konten: Konten = {
  belajar: {
    tujuan: [
      "Membedakan buku fiksi dan nonfiksi secara jelas",
      "Mengidentifikasi ciri-ciri buku fiksi dan nonfiksi",
      "Memahami teknik meresensi buku fiksi dan nonfiksi",
      "Menyusun resensi buku dengan struktur yang tepat",
      "Mengembangkan minat baca dan sikap kritis terhadap bacaan",
    ],
    materi: [
      {
        judul: "Apa Itu Buku Fiksi dan Nonfiksi?",
        isi: [
          "Di perpustakaan sekolah, rak buku dibagi menjadi dua bagian besar: fiksi dan nonfiksi. Apa sebenarnya perbedaan keduanya?",
          "",
          "FIKSI adalah buku yang berisi cerita rekaan (imajinasi) pengarang. Tujuan utamanya adalah menghibur dan menyampaikan pesan estetis. Contoh: novel, cerpen, kumpulan puisi, komik, dongeng.",
          "",
          "✓ Ciri buku fiksi:",
          "  ✓ Berdasarkan imajinasi, bukan fakta",
          "  ✓ Menggunakan bahasa konotatif dan figuratif",
          "  ✓ Bertujuan menghibur (rekreatif)",
          "  ✓ Memiliki unsur intrinsik: tema, tokoh, alur, latar",
          "  ✓ Kebenaran bersifat relatif (tidak harus faktual)",
          "",
          "NONFIKSI adalah buku yang berisi informasi faktual dan objektif berdasarkan data, penelitian, atau pengalaman nyata. Tujuannya adalah memberikan pengetahuan, pendidikan, atau informasi. Contoh: ensiklopedia, biografi, buku pelajaran, laporan penelitian, jurnal.",
          "",
          "✓ Ciri buku nonfiksi:",
          "  ✓ Berdasarkan fakta dan data nyata",
          "  ✓ Menggunakan bahasa denotatif (lugas, apa adanya)",
          "  ✓ Bertujuan memberikan informasi dan pengetahuan",
          "  ✓ Bersifat objektif dan dapat diverifikasi",
          "  ✓ Dilengkapi data pendukung: tabel, grafik, daftar pustaka",
          "",
          "[Ilustrasi: Dua tumpukan buku. Tumpukan kiri berlabel 'FIKSI' dengan sampul penuh warna dan ilustrasi fantasi — naga, kastil, pesawat luar angkasa. Tumpukan kanan berlabel 'NONFIKSI' dengan sampul sederhana dan rapi — diagram, foto, grafik. Kedua tumpukan dipisahkan oleh garis tengah. Gaya ilustrasi perbandingan dengan warna biru dan oranye.]",
        ],
        contoh: [
          "Perbandingan fiksi vs nonfiksi dengan tema sama:",
          "",
          "FIKSI — Novel 'Laskar Pelangi' karya Andrea Hirata:",
          "✓ Cerita tentang perjuangan 10 anak di Belitung. Tokohnya fiktif (Ikal, Lintang, Mahar), tetapi latarnya terinspirasi dari kenyataan. Bahasanya puitis, sarat metafora. Tujuannya menghibur dan menginspirasi.",
          "",
          "NONFIKSI — Buku 'Pendidikan di Daerah Terpencil' (laporan penelitian):",
          "✓ Berisi data faktual: jumlah sekolah, angka putus sekolah, kualitas guru di daerah terpencil. Dilengkapi tabel statistik dan grafik. Tujuannya memberikan informasi dan rekomendasi kebijakan.",
        ],
        catatan: "Beberapa buku berada di 'antara' fiksi dan nonfiksi. Misalnya memoar (pengalaman nyata yang ditulis dengan gaya cerita), atau jurnalisme sastra (fakta yang dikemas dengan gaya fiksi). Ini disebut creative non-fiction.",
      },
      {
        judul: "Unsur Buku Fiksi dan Nonfiksi",
        isi: [
          "Seperti cerpen, buku fiksi juga memiliki unsur intrinsik. Sementara nonfiksi memiliki struktur yang berbeda.",
          "",
          "UNSUR FIKSI:",
          "1. Sampul buku — sering mengandung ilustrasi yang mewakili cerita",
          "2. Tema — pokok pikiran cerita",
          "3. Tokoh dan penokohan — karakter-karakter dalam cerita",
          "4. Alur — rangkaian peristiwa",
          "5. Latar — tempat, waktu, suasana",
          "6. Bahasa — gaya bahasa, majas, diksi puitis",
          "",
          "UNSUR NONFIKSI:",
          "1. Sampul buku — biasanya sederhana, informatif",
          "2. Daftar isi — memuat bab dan subbab secara sistematis",
          "3. Isi buku — disusun berdasarkan klasifikasi ilmu, bukan kronologis",
          "4. Glosarium — daftar istilah penting dengan penjelasan",
          "5. Daftar pustaka — sumber referensi yang digunakan",
          "6. Indeks — daftar kata penting dengan nomor halaman",
          "",
          "[Ilustrasi: Perbandingan dua buku terbuka. Buku kiri (FIKSI) menampilkan gambar pemandangan, paragraf dengan font dekoratif, dan dialog antartokoh. Buku kanan (NONFIKSI) menampilkan tabel data, grafik batang, dan teks informatif dengan poin-poin. Gaya ilustrasi buku terbuka dengan warna kuning dan biru.]",
        ],
        contoh: [
          "Cara membedakan fiksi/nonfiksi dari sampul:",
          "",
          "SAMPUL FIKSI: Judul 'Perahu Kertas' dengan ilustrasi perahu kertas di kolam. Warna pastel. Font artistik. Tidak ada penjelasan isi.",
          "",
          "SAMPUL NONFIKSI: Judul 'Sejarah Indonesia Modern' dengan foto hitam-putih. Font tegas dan rapi. Ada subjudul: '1200-2008'. Ada blurb berisi penjelasan buku.",
        ],
      },
      {
        judul: "Meresensi Buku Fiksi dan Nonfiksi",
        isi: [
          "Resensi adalah ulasan atau penilaian terhadap sebuah buku. Tujuannya memberi gambaran kepada pembaca tentang isi, kelebihan, dan kekurangan buku.",
          "",
          "STRUKTUR RESENSI:",
          "",
          "1. IDENTITAS BUKU",
          "  Judul, pengarang, penerbit, tahun terbit, tebal halaman, ISBN.",
          "",
          "2. RINGKASAN ISI BUKU",
          "  Untuk fiksi: sinopsis cerita tanpa spoiler berlebihan.",
          "  Untuk nonfiksi: garis besar isi buku per bab.",
          "",
          "3. KEUNGGULAN BUKU",
          "  Apa yang menarik dari buku ini? Bahasa, gaya penulisan, data, ilustrasi, atau temanya.",
          "",
          "4. KELEMAHAN BUKU",
          "  Apa yang kurang? Apakah ada data yang tidak akurat? Alur yang membingungkan? Cetakan yang buram?",
          "",
          "5. PENUTUP / KESIMPULAN",
          "  Apakah buku ini layak dibaca? Siapa target pembaca yang cocok? Beri rating.",
          "",
          "[Ilustrasi: Seorang kritikus muda duduk di meja kerja dengan laptop dan tumpukan buku di sekelilingnya. Di layar laptop ada dokumen berjudul 'RESENSI'. Tangan kanan memegang pulpen, tangan kiri memegang buku yang sedang diulas. Gaya ilustrasi ruang kerja modern dengan warna hijau dan putih.]",
        ],
        contoh: [
          "Contoh identitas buku:",
          "",
          "RESENSI FIKSI:",
          "Judul: 'Perahu Kertas'",
          "Pengarang: Dee Lestari",
          "Penerbit: Bentang Pustaka",
          "Tahun Terbit: 2009",
          "Tebal: 444 halaman",
          "ISBN: 978-602-881-210-0",
          "",
          "RESENSI NONFIKSI:",
          "Judul: 'Sapiens: A Brief History of Humankind'",
          "Pengarang: Yuval Noah Harari",
          "Penerbit: HarperCollins",
          "Tahun Terbit: 2011",
          "Tebal: 464 halaman",
          "ISBN: 978-006-231-609-7",
        ],
      },
      {
        judul: "Langkah Menulis Resensi",
        isi: [
          "Siap menulis resensi buku favoritmu? Simak langkah-langkahnya!",
          "",
          "PENTING: Resensi yang baik bersifat objektif dan seimbang. Jangan hanya memuji atau hanya mengkritik. Berikan penilaian yang adil.",
          "",
          "1. Baca buku dengan saksama",
          "  Jangan lompat-lompat. Catat bagian-bagian penting, kutipan menarik, dan kesanmu saat membaca.",
          "",
          "2. Catat identitas buku",
          "  Lihat halaman hak cipta untuk data lengkap: judul, pengarang, penerbit, tahun, ISBN.",
          "",
          "3. Buat ringkasan singkat",
          "  Untuk fiksi: ceritakan inti cerita tanpa spoiler. Untuk nonfiksi: sebutkan topik utama dan sub-topik.",
          "",
          "4. Analisis keunggulan dan kelemahan",
          "  Keunggulan: apa yang membuat buku ini istimewa? Gaya bahasa? Data? Cerita?",
          "  Kelemahan: apa yang kurang? Plot berlubang? Data tidak akurat? Terlalu tebal?",
          "",
          "5. Tulis kesimpulan",
          "  Siapa yang cocok membaca buku ini? Berapa ratingmu?",
          "",
          "[Ilustrasi: Seorang siswa memegang buku yang sedang dibaca sambil duduk di tangga perpustakaan. Di pangkuannya ada buku catatan kecil dan pulpen. Di sekelilingnya, rak-rak buku tinggi menjulang. Wajahnya fokus, sesekali menulis. Gaya ilustrasi perpustakaan klasik dengan warna cokelat dan emas.]",
        ],
        contoh: [
          "Kerangka resensi sederhana:",
          "",
          "JUDUL RESENSI: \"Perahu Kertas: Antara Mimpi dan Kenyataan\"",
          "",
          "IDENTITAS: Dee Lestari, Bentang Pustaka, 2009, 444 hal.",
          "RINGKASAN: Novel ini bercerita tentang Kugy dan Keenan yang bertemu dalam situasi tidak biasa. Kugy bercita-cita menjadi penulis dongeng, Keenan ingin melukis. Keduanya berjuang mengejar mimpi di tengah realitas kehidupan.",
          "KEUNGGULAN: Bahasa puitis yang khas Dee Lestari. Karakter kuat dan relatable. Tema tentang mengejar mimpi sangat menginspirasi.",
          "KELEMAHAN: Alur di pertengahan terasa lambat. Beberapa konflik terasa dipaksakan.",
          "KESIMPULAN: Cocok untuk remaja dan dewasa muda. Rating: 4/5 bintang.",
        ],
      },
    ],
    rangkuman: [
      "[Ilustrasi: Timbangan dengan dua piringan. Piringan kiri berisi buku-buku dengan sampul warna-warni (FIKSI). Piringan kanan berisi buku dengan sampul polos dan diagram (NONFIKSI). Timbangan seimbang, melambangkan kedua jenis buku sama pentingnya. Gaya ilustrasi timbangan vintage dengan warna emas dan hitam.]",
      "Fiksi: buku rekaan/imajinasi, bertujuan menghibur, menggunakan bahasa konotatif.",
      "Nonfiksi: buku faktual/ilmiah, bertujuan memberi informasi, menggunakan bahasa denotatif.",
      "Resensi adalah ulasan buku yang mencakup identitas, ringkasan, keunggulan, kelemahan, dan kesimpulan.",
      "Struktur resensi: identitas buku → ringkasan isi → keunggulan → kelemahan → penutup.",
    ],
  },
  latihan: makeSoal([
["Apa perbedaan utama buku fiksi dan nonfiksi?", ["Tidak ada perbedaan", "Fiksi rekaan, nonfiksi faktual", "Fiksi lebih tebal", "Nonfiksi lebih tipis"], 1, "Fiksi berdasarkan imajinasi, nonfiksi berdasarkan fakta dan data."],
["Contoh buku nonfiksi adalah...", ["Novel", "Biografi", "Cerpen", "Komik"], 1, "Biografi adalah buku nonfiksi karena berdasarkan data dan fakta riwayat hidup."],
["Ciri bahasa buku nonfiksi adalah...", ["Konotatif dan puitis", "Denotatif dan lugas", "Bermajas", "Berima"], 1, "Nonfiksi menggunakan bahasa denotatif — lugas dan apa adanya."],
    ["Fungsi resensi buku adalah...", ["Menjual buku", "Memberi gambaran dan penilaian terhadap buku", "Mengganti buku", "Menulis ulang buku"], 1, "Resensi mengulas isi buku dan memberikan penilaian kepada calon pembaca."],
    ["Unsur yang TIDAK termasuk dalam identitas buku adalah...", ["Judul", "Pengarang", "Harga buku", "Tahun terbit"], 2, "Harga buku tidak termasuk dalam identitas buku pada resensi."],
    ["Dalam resensi, keunggulan dan kelemahan buku disajikan secara...", ["Subjektif", "Objektif dan seimbang", "Berlebihan", "Acak"], 1, "Resensi harus objektif dan seimbang — tidak hanya memuji atau mengkritik."],
    ["Yang membedakan sampul buku fiksi dan nonfiksi adalah...", ["Fiksi lebih sederhana", "Fiksi sering bergambar ilustratif, nonfiksi informatif", "Sama saja", "Nonfiksi lebih berwarna"], 1, "Sampul fiksi cenderung artistik, nonfiksi cenderung informatif."],
    ["Kata 'glosarium' dalam buku nonfiksi berarti...", ["Daftar isi", "Daftar istilah dan penjelasannya", "Daftar pustaka", "Indeks"], 1, "Glosarium adalah daftar istilah penting lengkap dengan penjelasannya."],
    ["Salah satu buku yang termasuk creative non-fiction adalah...", ["Novel Harry Potter", "Memoar 'The Diary of a Young Girl'", "Komik", "Buku pelajaran"], 1, "Memoar termasuk creative non-fiction — fakta dikemas dengan gaya bercerita."],
    ["Tujuan utama buku fiksi adalah...", ["Memberi informasi", "Menghibur dan menyampaikan pesan estetis", "Mendidik", "Melaporkan data"], 1, "Tujuan utama fiksi adalah hiburan dan nilai estetis."],
  ]),
  praktik: {
    petunjuk: "Pilihlah satu buku fiksi atau nonfiksi yang pernah kamu baca. Tulislah resensi buku tersebut dengan struktur lengkap: (1) identitas buku, (2) ringkasan isi (untuk fiksi: sinopsis, untuk nonfiksi: garis besar bab), (3) keunggulan buku (minimal 3 poin), (4) kelemahan buku (minimal 2 poin), (5) kesimpulan dan rating. Panjang resensi 300-500 kata.",
    tips: [
      "Pilih buku yang benar-benar kamu baca sampai habis agar ulasanmu akurat",
      "Jangan memberikan spoiler berlebihan untuk buku fiksi",
      "Gunakan data konkret saat membahas keunggulan — misalnya 'dialognya natural', 'data yang disajikan lengkap dengan grafik'",
      "Kelemahan bukan berarti buku itu jelek — bisa berupa 'cetakan terlalu kecil' atau 'bab 3 agak membingungkan'",
      "Tutup dengan kalimat yang membuat pembaca tertarik untuk membaca buku tersebut",
    ],
    contoh: "Resensi 300-500 kata dengan struktur lengkap: identitas, ringkasan, keunggulan (3 poin), kelemahan (2 poin), kesimpulan + rating.",
  },
  kuis: makeSoal([
    ["Buku yang berisi cerita rekaan berdasarkan imajinasi disebut...", ["Fiksi", "Nonfiksi", "Ensiklopedia", "Biografi"], 0, "Fiksi adalah cerita rekaan berdasarkan imajinasi pengarang."],
    ["Buku nonfiksi biasanya dilengkapi dengan...", ["Dialog antartokoh", "Daftar pustaka dan indeks", "Ilustrasi fantasi", "Puisi"], 1, "Nonfiksi dilengkapi data pendukung seperti daftar pustaka dan indeks."],
    ["Salah satu ciri bahasa dalam buku fiksi adalah...", ["Lugas dan denotatif", "Konotatif dan penuh majas", "Objektif", "Ilmiah"], 1, "Fiksi menggunakan bahasa konotatif, figuratif, dan penuh majas."],
    ["Bagian resensi yang berisi data teknis buku disebut...", ["Ringkasan", "Identitas buku", "Kelebihan", "Kesimpulan"], 1, "Identitas buku berisi judul, pengarang, penerbit, ISBN, dll."],
    ["Mengapa resensi harus objektif?", ["Agar penjualan naik", "Agar pembaca mendapat gambaran akurat", "Agar buku laku", "Agar penulis senang"], 1, "Objektivitas membantu pembaca mendapat gambaran yang jujur dan akurat."],
    ["Contoh genre buku fiksi adalah...", ["Novel misteri", "Ensiklopedia", "Buku sejarah", "Jurnal ilmiah"], 0, "Novel misteri adalah fiksi — cerita rekaan yang menghibur."],
    ["Fungsi daftar isi dalam buku nonfiksi adalah...", ["Memperindah buku", "Memudahkan pembaca menemukan bab tertentu", "Mengganti indeks", "Mencantumkan harga"], 1, "Daftar isi memudahkan navigasi dalam buku nonfiksi."],
    ["Resensi yang baik mencakup...", ["Hanya kelebihan buku", "Kelebihan dan kelemahan secara seimbang", "Hanya ringkasan", "Harga buku"], 1, "Resensi seimbang mencakup kelebihan dan kelemahan."],
    ["Yang membedakan resensi dengan sinopsis adalah...", ["Tidak ada perbedaan", "Resensi mencakup penilaian, sinopsis hanya ringkasan", "Sinopsis lebih panjang", "Resensi hanya untuk nonfiksi"], 1, "Resensi mencakup analisis dan penilaian, sinopsis hanya ringkasan cerita."],
    ["Tujuan akhir dari sebuah resensi adalah...", ["Menjual buku", "Membantu pembaca memutuskan apakah buku layak dibaca", "Mengkritik penulis", "Membuat buku terkenal"], 1, "Resensi membantu pembaca memutuskan apakah buku itu layak dibaca atau tidak."],
  ]),
}

export default konten
