import type { Konten } from "../types"
import { makeSoal } from "../types"

const konten: Konten = {
  belajar: {
    tujuan: [
      "Memahami pengertian dan ciri-ciri teks prosedur kompleks",
      "Mengidentifikasi struktur dan kaidah kebahasaan teks prosedur",
      "Membedakan teks prosedur sederhana dan kompleks",
      "Menyusun teks prosedur kompleks dengan langkah yang sistematis",
      "Mengaplikasikan teks prosedur dalam kehidupan sehari-hari",
    ],
    materi: [
      {
        judul: "Mengenal Teks Prosedur Kompleks",
        isi: [
          "Pernahkah kamu membuat akun media sosial? Atau mendaftar sekolah online? Atau mencoba resep masakan dari internet? Semua itu adalah contoh teks prosedur!",
          "",
          "Teks prosedur adalah teks yang berisi langkah-langkah atau tahapan untuk melakukan sesuatu secara sistematis. Teks prosedur kompleks adalah teks prosedur yang memiliki banyak langkah dan membutuhkan pemahaman yang cermat.",
          "",
          "✓ Ciri-ciri teks prosedur:",
          "  ✓ Berisi langkah-langkah yang terperinci dan sistematis",
          "  ✓ Bersifat informatif dan instruktif (memberi petunjuk)",
          "  ✓ Menggunakan kalimat imperatif (perintah)",
          "  ✓ Menggunakan kata kerja aksi (beli, tekan, buka, pilih)",
          "  ✓ Menggunakan konjungsi temporal (pertama, kemudian, setelah itu, selanjutnya)",
          "  ✓ Disusun secara kronologis (berurutan)",
          "",
          "[Ilustrasi: Seorang remaja duduk di meja dengan laptop terbuka, di sampingnya ada buku catatan dan pulpen. Di layar laptop terlihat halaman tutorial langkah demi langkah. Ekspresinya serius mengikuti petunjuk. Latar belakang kamar rapi dengan poster-poster motivasi. Gaya ilustrasi ruang belajar digital dengan warna biru dan putih.]",
        ],
        contoh: [
          "Perbedaan prosedur sederhana dan kompleks:",
          "",
          "SEDERHANA — Cara merebus telur:",
          "✓ 3 langkah. Bahan: telur, air. Waktu: 10 menit.",
          "",
          "KOMPLEKS — Cara membuat akun GitHub:",
          "1. Buka situs github.com",
          "2. Klik tombol 'Sign up'",
          "3. Masukkan alamat email",
          "4. Buat password (minimal 8 karakter, kombinasi huruf dan angka)",
          "5. Verifikasi email melalui kode OTP yang dikirim",
          "6. Pilih akun Free atau Pro",
          "7. Isi profil (nama, bio, foto)",
          "8. Selesai — akun siap digunakan",
          "✓ 8 langkah, butuh pemahaman teknis, melibatkan verifikasi dan pilihan.",
        ],
        catatan: "Teks prosedur kompleks berbeda dengan teks prosedur sederhana dari segi jumlah langkah, tingkat kerumitan, dan kebutuhan akan ketelitian. Prosedur kompleks juga sering dilengkapi dengan peringatan (caution) dan catatan penting.",
      },
      {
        judul: "Struktur Teks Prosedur Kompleks",
        isi: [
          "Seperti jenis teks lain, teks prosedur juga memiliki struktur yang baku.",
          "",
          "1. JUDUL",
          "  Menjelaskan apa yang akan dibuat atau dilakukan. Judul harus spesifik dan informatif.",
          "",
          "2. TUJUAN",
          "  Berisi penjelasan singkat tentang hasil akhir yang akan dicapai. Bisa juga berisi manfaat dari melakukan prosedur tersebut.",
          "",
          "3. ALAT DAN BAHAN / SYARAT",
          "  Untuk prosedur pembuatan: daftar alat dan bahan yang diperlukan.",
          "  Untuk prosedur aktivitas: syarat atau prasyarat yang harus dipenuhi.",
          "",
          "4. LANGKAH-LANGKAH",
          "  Inti dari teks prosedur. Berisi tahapan yang harus dilakukan secara berurutan. Setiap langkah ditulis secara jelas, rinci, dan tidak ambigu.",
          "",
          "5. PENUTUP (Opsional)",
          "  Berisi harapan, manfaat, atau catatan tambahan. Bisa juga berupa ajakan untuk mencoba.",
          "",
          "[Ilustrasi: Diagram alur vertikal dengan 5 tahapan berbentuk anak tangga. Tangga 1 'JUDUL' — ikon label. Tangga 2 'TUJUAN' — ikon target. Tangga 3 'ALAT & BAHAN' — ikon kotak alat dan kantong belanja. Tangga 4 'LANGKAH' — ikon telapak kaki. Tangga 5 'PENUTUP' — ikon bintang. Setiap anak tangga berwarna gradasi dari biru ke hijau. Gaya ilustrasi infografis tangga dengan warna biru-hijau.]",
        ],
        contoh: [
          "Penerapan struktur pada 'Cara Mendaftar Ujian Sekolah Online':",
          "",
          "JUDUL: Cara Mendaftar Ujian Sekolah Online",
          "",
          "TUJUAN: Panduan ini membantu siswa mendaftar ujian sekolah secara online dengan benar agar data terverifikasi.",
          "",
          "SYARAT:",
          "- Laptop/HP dengan koneksi internet stabil",
          "- NISN (Nomor Induk Siswa Nasional)",
          "- Scan foto 3x4 ukuran maksimal 200KB",
          "",
          "LANGKAH-LANGKAH:",
          "1. Buka situs ujian.bahasacerdas.com",
          "2. Klik 'Daftar Baru' di pojok kanan atas",
          "3. Masukkan NISN dan tanggal lahir",
          "4. Unggah foto 3x4",
          "5. Pilih mata pelajaran yang akan diujikan",
          "6. Klik 'Submit' untuk mengirim pendaftaran",
          "7. Cetak kartu ujian (setelah mendapat email konfirmasi)",
          "",
          "PENUTUP: Selamat mengikuti ujian! Pastikan kamu datang tepat waktu.",
        ],
      },
      {
        judul: "Kaidah Kebahasaan Teks Prosedur",
        isi: [
          "Teks prosedur memiliki ciri bahasa yang khas. Kamu harus menguasainya agar bisa menulis prosedur yang baik.",
          "",
          "1. KALIMAT IMPERATIF",
          "  Kalimat perintah. Contoh: Buka, klik, masukkan, pilih, ulangi, jangan tekan.",
          "",
          "2. KATA KERJA AKTIF (VERBA MATERIAL)",
          "  Kata kerja yang menunjukkan tindakan fisik. Contoh: memotong, menuangkan, menekan, mengklik, mengaduk.",
          "",
          "3. KATA HUBUNG KRONOLOGIS (TEMPORAL)",
          "  Pertama, kedua, ketiga, kemudian, setelah itu, selanjutnya, lalu, akhirnya.",
          "",
          "4. KATA KETERANGAN CARA",
          "  Dengan hati-hati, secara perlahan, secepat mungkin, secara manual, otomatis.",
          "",
          "5. KATA KETERANGAN ALAT",
          "  Dengan sendok, menggunakan gunting, memakai kuas, melalui laptop.",
          "",
          "6. KALIMAT PERSYARATAN",
          "  Jika... maka..., apabila... sebaiknya..., bila perlu...",
          "",
          "[Ilustrasi: Papan tulis interaktif dengan 6 kategori kaidah kebahasaan yang ditampilkan dalam bentuk 6 tab folder. Tab 1 'IMPERATIF' — ikon seru (!). Tab 2 'VERBA MATERIAL' — ikon tangan melakukan aksi. Tab 3 'TEMPORAL' — ikon jam. Tab 4 'KATA KETERANGAN CARA' — ikon kaca pembesar. Tab 5 'KATA KETERANGAN ALAT' — ikon obeng. Tab 6 'PERSYARATAN' — ikon tanda panah bercabang. Gaya ilustrasi tab antarmuka digital dengan warna biru dan putih.]",
        ],
        contoh: [
          "Analisis kebahasaan dalam teks prosedur:",
          "",
          "Kalimat asli: \"Selanjutnya Anda harus membuka aplikasi dengan hati-hati menggunakan sidik jari.\"",
          "",
          "Analisis:",
          "- 'Selanjutnya' → kata hubung kronologis",
          "- 'membuka' → verba material (kata kerja tindakan)",
          "- 'dengan hati-hati' → kata keterangan cara",
          "- 'menggunakan sidik jari' → kata keterangan alat",
          "- Kalimat: deklaratif (pernyataan). Bisa diubah ke imperatif: \"Buka aplikasi dengan hati-hati menggunakan sidik jari!\"",
        ],
      },
      {
        judul: "Langkah Menulis Teks Prosedur Kompleks",
        isi: [
          "Siap menulis teks prosedur kompleks? Ikuti langkah-langkah ini agar hasilmu rapi dan mudah diikuti!",
          "",
          "PENTING: Teks prosedur yang baik harus bisa diikuti oleh orang yang belum pernah melakukan aktivitas tersebut sama sekali. Bayangkan kamu sedang menjelaskan kepada teman yang buta sama sekali tentang cara melakukan sesuatu.",
          "",
          "1. Tentukan aktivitas yang akan dijelaskan",
          "  Pilih aktivitas yang kamu kuasai dengan baik. Semakin kamu paham, semakin jelas langkah-langkah yang kamu tulis.",
          "",
          "2. Lakukan sendiri aktivitas tersebut",
          "  Jika perlu, lakukan aktivitas itu sambil mencatat setiap langkah. Ini membantu kamu tidak melewatkan detail penting.",
          "",
          "3. Urutkan langkah secara kronologis",
          "  Pastikan urutannya logis. Jangan melompat atau terbalik. Gunakan kata hubung kronologis.",
          "",
          "4. Gunakan bahasa yang jelas dan konsisten",
          "  Gunakan kalimat imperatif. Hindari kata ambigu. Jika perlu, tambahkan ilustrasi atau diagram.",
          "",
          "5. Uji coba petunjukmu",
          "  Minta teman mengikuti petunjukmu tanpa bertanya. Jika mereka berhasil, prosedurmu sudah baik.",
          "",
          "[Ilustrasi: Dua siswa duduk berhadapan di meja. Siswa A memegang kertas bertuliskan 'PETUNJUK' dan membacakannya. Siswa B mengikuti petunjuk itu — mengoperasikan laptop dengan konsentrasi. Di meja ada alat-alat: kabel, flashdisk, mouse. Suasana laboratorium komputer yang kondusif. Gaya ilustrasi laboratorium dengan warna abu-abu dan biru.]",
        ],
        contoh: [
          "Perbandingan petunjuk KURANG JELAS dan LEBIH JELAS:",
          "",
          "KURANG JELAS: \"Buka aplikasi, lalu login. Terus upload file. Nanti muncul notifikasi. Klik OK, selesai.\"",
          "✗ Tidak detail, ada kata 'terus' dan 'nanti' yang ambigu, tidak ada peringatan.",
          "",
          "LEBIH JELAS: \"1. Buka aplikasi 'E-Learning' di HP. 2. Masukkan NISN dan password. 3. Pilih menu 'Tugas'. 4. Klik tombol 'Upload' di sudut kanan atas. 5. Pilih file dari galeri (format PDF, maksimal 5 MB). 6. Tunggu notifikasi 'Upload Berhasil' (jika gagal, periksa koneksi internet). 7. Klik 'OK' untuk mengonfirmasi.\"",
          "✓ Detail, ada syarat format, ukuran file, dan penanganan error.",
        ],
      },
    ],
    rangkuman: [
      "[Ilustrasi: Buku panduan terbuka dengan sampul bergambar ikon-ikon petunjuk: tanda panah, checklist, tanda seru peringatan, roda gigi. Dari halaman buku muncul ilustrasi tangan yang menunjuk ke langkah-langkah. Gaya ilustrasi buku panduan teknis dengan warna biru dan oranye.]",
      "Teks prosedur kompleks berisi langkah-langkah sistematis untuk melakukan sesuatu yang membutuhkan ketelitian.",
      "Struktur: Judul → Tujuan → Alat/Bahan/Syarat → Langkah-langkah → Penutup (opsional).",
      "Kaidah kebahasaan: kalimat imperatif, verba material, konjungsi kronologis, kata keterangan cara/alat, kalimat persyaratan.",
      "Tips menulis: kuasai aktivitas → catat langkah sambil praktik → urutkan kronologis → gunakan bahasa jelas → uji coba ke teman.",
    ],
  },
  latihan: makeSoal([
["Apa tujuan dari teks prosedur?", ["Menghibur pembaca", "Memberi petunjuk melakukan sesuatu", "Menceritakan pengalaman", "Mendeskripsikan benda"], 1, "Teks prosedur bertujuan memberi petunjuk atau panduan melakukan sesuatu."],
["Yang membedakan prosedur kompleks dan sederhana adalah...", ["Sederhana lebih panjang", "Kompleks memiliki banyak langkah dan butuh ketelitian", "Tidak ada perbedaan", "Kompleks lebih mudah"], 1, "Prosedur kompleks memiliki lebih banyak langkah dan tingkat kerumitan lebih tinggi."],
["Kalimat 'Buka aplikasi dengan hati-hati' mengandung...", ["Konjungsi temporal", "Kata keterangan cara", "Kata keterangan alat", "Kalimat persyaratan"], 1, "'Dengan hati-hati' adalah kata keterangan cara."],
["Struktur teks prosedur yang benar adalah...", ["Judul - langkah - tujuan", "Judul - tujuan - alat/bahan - langkah - penutup", "Tujuan - langkah - judul", "Alat - langkah - tujuan"], 1, "Struktur: Judul → Tujuan → Alat/Bahan → Langkah → Penutup."],
["Contoh konjungsi kronologis adalah...", ["Akan tetapi", "Kemudian", "Oleh karena itu", "Meskipun"], 1, "'Kemudian' adalah konjungsi kronologis yang menunjukkan urutan waktu."],
["Kata 'jika koneksi terputus, ulangi dari langkah 1' termasuk kalimat...", ["Imperatif", "Persyaratan", "Deklaratif", "Interogatif"], 1, "Kalimat tersebut menyatakan syarat (jika... ulangi)."],
["Mengapa teks prosedur menggunakan kalimat imperatif?", ["Agar lebih indah", "Karena memberi perintah atau petunjuk", "Agar lebih panjang", "Karena harus berima"], 1, "Kalimat imperatif digunakan untuk memberi perintah atau instruksi."],
["Contoh verba material dalam teks prosedur adalah...", ["Memotong", "Cantik", "Kemudian", "Dengan"], 0, "'Memotong' adalah verba material — kata kerja fisik."],
["Teks prosedur yang baik harus...", ["Ambisius", "Jelas, rinci, dan tidak ambigu", "Panjang dan rumit", "Mengulang-ulang"], 1, "Teks prosedur harus jelas, rinci, dan tidak menimbulkan kebingungan."],
    ["Fungsi bagian 'alat dan bahan' dalam teks prosedur adalah...", ["Menambah panjang teks", "Memberi informasi apa saja yang perlu disiapkan", "Menghibur pembaca", "Menjelaskan tujuan"], 1, "Bagian ini memberi tahu pembaca apa yang perlu disiapkan sebelum memulai."],
  ]),
  praktik: {
    petunjuk: "Buatlah teks prosedur kompleks tentang salah satu aktivitas berikut: (1) Cara mendaftar organisasi/ekstrakurikuler di sekolah, (2) Cara membuat akun media sosial yang aman, (3) Cara membuat kerajinan tangan sederhana, atau (4) Cara mengatasi HP yang lemot. Gunakan struktur lengkap: judul, tujuan, alat/bahan atau syarat, langkah-langkah (minimal 7 langkah), dan penutup. Sertakan kalimat imperatif, konjungsi kronologis, dan kalimat persyaratan.",
    tips: [
      "Pilih aktivitas yang sering kamu lakukan agar langkah-langkahnya terasa alami",
      "Tulis langkah dengan format numbering agar mudah diikuti",
      "Setiap langkah cukup 1-2 kalimat — jangan terlalu panjang",
      "Tambahkan peringatan (misalnya 'Hati-hati...' atau 'Pastikan...') pada langkah yang berisiko",
      "Uji coba petunjukmu dengan teman sebelum dikumpulkan",
    ],
    contoh: "Teks prosedur minimal 7 langkah dengan struktur lengkap. Sertakan 3 kalimat imperatif, 3 konjungsi kronologis, dan 1 kalimat persyaratan.",
  },
  kuis: makeSoal([
    ["Teks prosedur kompleks termasuk jenis teks...", ["Fiksi", "Nonfiksi instruktif", "Puisi", "Naratif"], 1, "Teks prosedur adalah teks nonfiksi yang bersifat instruktif."],
    ["Kata 'pertama, kedua, ketiga' termasuk...", ["Kata sifat", "Konjungsi kronologis", "Kata kerja", "Kata benda"], 1, "Kata tersebut adalah konjungsi yang menunjukkan urutan waktu."],
    ["Syarat teks prosedur yang baik adalah...", ["Bahasa berbelit-belit", "Langkah urut dan jelas", "Panjang maksimal", "Menggunakan istilah asing"], 1, "Teks prosedur harus urut, jelas, dan mudah diikuti."],
    ["Bedanya teks prosedur dengan teks eksposisi adalah...", ["Tidak ada bedanya", "Prosedur memberi petunjuk, eksposisi menjelaskan", "Sama-sama informatif", "Prosedur lebih panjang"], 1, "Prosedur memberi petunjuk langkah, eksposisi menjelaskan suatu topik."],
    ["Contoh kalimat imperatif yang tepat dalam prosedur adalah...", ["Saya membuka aplikasi", "Buka aplikasi", "Membuka aplikasi", "Aplikasi dibuka"], 1, "Kalimat imperatif menggunakan kata kerja dasar tanpa awalan: Buka, Tekan, Pilih."],
    ["Mengapa prosedur kompleks sering dilengkapi peringatan?", ["Agar lebih serius", "Karena ada langkah berisiko yang perlu perhatian khusus", "Agar lebih panjang", "Karena penulis suka memberi peringatan"], 1, "Peringatan penting untuk langkah yang memerlukan kehati-hatian."],
    ["Bagian penutup dalam teks prosedur bersifat...", ["Wajib", "Opsional", "Paling penting", "Harus panjang"], 1, "Penutup opsional — bisa berisi harapan atau ajakan."],
    ["Kata keterangan alat dalam prosedur ditandai dengan...", ["Menggunakan + alat", "Dengan + cara", "Kemudian", "Pertama"], 0, "Kata keterangan alat: 'menggunakan gunting', 'dengan kuas'."],
    ["Kalimat 'Pastikan koneksi internet stabil sebelum memulai' termasuk...", ["Kalimat imperatif dengan peringatan", "Kalimat tanya", "Kalimat berita", "Kalimat seru"], 0, "Kalimat ini imperatif yang memberi peringatan untuk memastikan sesuatu."],
    ["Nilai yang bisa dipetik dari teks prosedur adalah...", ["Kreativitas tanpa batas", "Sistematis, teliti, dan sabar dalam melakukan sesuatu", "Kecepatan tanpa perencanaan", "Hasil instan"], 1, "Prosedur mengajarkan kita untuk sistematis, teliti, dan sabar."],
  ]),
}

export default konten
