import type { Konten } from "../types"
import { makeSoal } from "../types"

const konten: Konten = {
  belajar: {
    tujuan: [
      "Memahami pengertian dan karakteristik teks prosedur kompleks tingkat lanjut",
      "Mengidentifikasi struktur teks prosedur dengan tepat",
      "Menganalisis kaidah kebahasaan teks prosedur secara mendalam",
      "Menyusun teks prosedur untuk berbagai konteks dan keperluan",
      "Menyempurnakan teks prosedur berdasarkan hasil evaluasi",
    ],
    materi: [
      {
        judul: "Mengenal Teks Prosedur Tingkat Lanjut",
        isi: [
          "Di kelas X, kamu sudah belajar tentang teks prosedur kompleks. Sekarang, kita akan memperdalamnya — tidak hanya membuat, tetapi juga menganalisis, menyempurnakan, dan mengevaluasi teks prosedur.",
          "",
          "Teks prosedur adalah teks yang berisi langkah-langkah sistematis untuk mencapai suatu tujuan. Di tingkat lanjut, kamu akan menghadapi prosedur yang lebih rumit — seperti SOP (Standard Operating Procedure), manual teknis, atau panduan penelitian.",
          "",
          "✓ Ciri-ciri teks prosedur lanjutan:",
          "  ✓ Langkah terperinci dan bersyarat (jika-maka)",
          "  ✓ Memerlukan pemahaman konseptual, bukan sekadar langkah mekanis",
          "  ✓ Dilengkapi diagram, tabel, atau bagan alir (flowchart)",
          "  ✓ Memuat peringatan dan penanganan kesalahan (troubleshooting)",
          "  ✓ Menggunakan bahasa teknis yang spesifik sesuai bidang",
          "",
          "[Ilustrasi: Seorang mahasiswa teknik duduk di meja laboratorium, dikelilingi peralatan dan diagram alir di papan tulis. Tangan kanan memegang obeng, tangan kiri memegang buku panduan teknis. Di latar belakang, rak berisi komponen elektronik. Gaya ilustrasi laboratorium teknik dengan warna biru dan abu-abu.]",
        ],
        contoh: [
          "Perbandingan prosedur dasar vs lanjutan:",
          "",
          "PROSEDUR DASAR — Cara mengisi ulang pulsa:",
          "1. Buka aplikasi",
          "2. Pilih menu 'Isi Ulang'",
          "3. Masukkan nomor",
          "4. Pilih nominal",
          "5. Konfirmasi pembayaran",
          "",
          "PROSEDUR LANJUTAN — Cara mengatur server lokal untuk pengembangan web:",
          "1. Pastikan Node.js dan npm sudah terinstal (cek dengan node -v dan npm -v)",
          "2. Buka terminal dan buat direktori proyek baru",
          "3. Inisialisasi proyek dengan npm init -y",
          "4. Instal express: npm install express",
          "5. Buat file server.js dan tulis kode dasar Express",
          "6. Jalankan server: node server.js",
          "7. Buka browser ke http://localhost:3000",
          "8. Jika error 'port in use', ganti port di server.js atau matikan proses lain",
          "✓ Lebih banyak langkah, ada prasyarat, ada penanganan error.",
        ],
        catatan: "Teks prosedur tingkat lanjut sering digunakan di dunia kerja. Kemampuan menulis prosedur yang jelas dan sistematis sangat dihargai — karena kesalahan sekecil apapun dalam prosedur bisa berakibat fatal, terutama di bidang medis, teknik, atau keselamatan.",
      },
      {
        judul: "Struktur dan Isi Teks Prosedur Lanjutan",
        isi: [
          "Teks prosedur lanjutan memiliki struktur yang lebih kaya daripada versi dasarnya.",
          "",
          "1. JUDUL DAN TUJUAN",
          "  Judul harus spesifik dan informatif. Tujuan menjelaskan hasil akhir dan manfaat.",
          "",
          "2. PRASYARAT / SPESIFIKASI",
          "  Berisi hal-hal yang harus dipenuhi sebelum memulai: kualifikasi, alat khusus, lisensi, atau izin.",
          "",
          "3. LANGKAH-LANGKAH DENGAN SUBCABANG",
          "  Langkah utama bisa memiliki sub-langkah dan percabangan bersyarat (jika A, lakukan B; jika C, lakukan D).",
          "",
          "4. PERINGATAN DAN TROUBLESHOOTING",
          "  Peringatan ditempatkan sebelum langkah berisiko. Troubleshooting berisi solusi untuk masalah umum.",
          "",
          "5. VERIFIKASI / VALIDASI",
          "  Cara memeriksa apakah setiap langkah sudah dilakukan dengan benar.",
          "",
          "6. PENUTUP",
          "  Rangkuman, harapan, atau referensi tambahan.",
          "",
          "[Ilustrasi: Diagram pohon keputusan dengan 6 cabang besar. Setiap cabang memiliki ranting dan daun yang merepresentasikan sub-langkah. Cabang 1 'TUJUAN' (akar). Cabang 2 'PRASYARAT' (batang). Cabang 3-6 adalah langkah-langkah dengan simbol keputusan (berlian) dan peringatan (segitiga). Gaya ilustrasi flowchart organik dengan warna hijau dan biru.]",
        ],
        contoh: [
          "Contoh struktur SOP 'Cara Mengoperasikan Mesin Fotokopi':",
          "",
          "JUDUL: SOP Pengoperasian Mesin Fotokopi Canon IR5000",
          "TUJUAN: Memastikan mesin fotokopi dioperasikan dengan benar dan aman.",
          "",
          "PRASYARAT:",
          "- Kertas ukuran A4 (minimal 50 lembar)",
          "- Toner tidak dalam status 'low' (cek indikator panel)",
          "",
          "LANGKAH:",
          "1. Hidupkan mesin dengan menekan tombol POWER (tunggu 30 detik hingga siap)",
          "2. Buka penutup kaca, letakkan dokumen menghadap ke bawah",
          "   PERINGATAN: Jangan sentuh kaca dengan tangan kotor",
          "3. Tutup kembali penutup kaca dengan lembut",
          "4. Atur jumlah kopian menggunakan tombol angka di panel",
          "5. Pilih ukuran kertas (A4/R4) dan jenis (1 sisi/2 sisi)",
          "6. Tekan tombol START hijau",
          "7. Jika kertas macet (jam), buka panel samping dan tarik kertas perlahan",
          "   PERINGATAN: Matikan mesin sebelum membersihkan kertas macet",
          "VERIFIKASI: Pastikan hasil kopian jelas, tidak miring, dan jumlah sesuai",
        ],
      },
      {
        judul: "Kaidah Kebahasaan Teks Prosedur Lanjutan",
        isi: [
          "Teks prosedur lanjutan menggunakan bahasa yang lebih beragam dan kompleks. Mari kita pelajari!",
          "",
          "1. KALIMAT IMPERATIF DAN DEKLARATIF",
          "  Imperatif: 'Tekan tombol START'. Deklaratif: 'Mesin akan mulai memproses dalam 5 detik.'",
          "",
          "2. KONJUNGSI SYARAT DAN TUJUAN",
          "  Syarat: jika, apabila, bila, seandainya. Tujuan: agar, supaya, untuk.",
          "",
          "3. KATA KERJA MATERIAL DAN TINDAKAN MENTAL",
          "  Material: buka, tekan, sambungkan, putar. Mental: pastikan, periksa, verifikasi, amati.",
          "",
          "4. KATA KETERANGAN YANG SPESIFIK",
          "  Cara: secara perlahan, searah jarum jam, dengan hati-hati.",
          "  Alat: menggunakan obeng plus, melalui port USB, dengan multimeter.",
          "  Ukuran: tepat 5 cm, maksimal 70°C, minimal 30 menit.",
          "",
          "5. NOMINALISASI",
          "  Mengubah kata kerja menjadi kata benda: 'memasang' → 'pemasangan', 'mengukur' → 'pengukuran'.",
          "",
          "[Ilustrasi: Papan tulis interaktif dengan 5 kategori bahasa. Kategori 1: kalimat perintah/berita. Kategori 2: diagram cabang 'jika-maka'. Kategori 3: ikon tangan dan kepala. Kategori 4: penggaris dan alat ukur. Kategori 5: panah perubahan bentuk kata. Gaya ilustrasi papan tulis digital dengan warna putih dan oranye.]",
        ],
        contoh: [
          "Analisis kebahasaan dalam kalimat prosedur:",
          "",
          "Kalimat: \"Setelah kabel terhubung, periksa apakah lampu indikator menyala hijau. Jika tidak, ulangi langkah 3-5.\"",
          "",
          "Analisis:",
          "- 'periksa' → imperatif + kata kerja mental (verifikasi)",
          "- 'Setelah' → konjungsi temporal",
          "- 'Jika tidak' → konjungsi syarat + percabangan",
          "- 'ulangi' → imperatif + kata kerja material",
          "- 'lampu indikator' → istilah teknis spesifik",
          "",
          "Kalimat: \"Pengukuran tegangan harus dilakukan dengan multimeter digital.\"",
          "- 'Pengukuran' → nominalisasi (dari 'mengukur')",
          "- 'harus' → modalitas kewajiban",
          "- 'multimeter digital' → istilah teknis",
        ],
      },
      {
        judul: "Menyempurnakan Teks Prosedur",
        isi: [
          "Teks prosedur yang baik harus diuji dan disempurnakan. Berikut panduan evaluasinya!",
          "",
          "PENTING: Prosedur yang tidak jelas bisa menyebabkan kecelakaan, kerusakan, atau kegagalan. Evaluasi adalah langkah wajib!",
          "",
          "1. UJI KELENGKAPAN",
          "  Apakah semua langkah tercantum? Apakah ada langkah yang terlewat? Coba ikuti prosedur dari awal hingga akhir.",
          "",
          "2. UJI KEJELASAN",
          "  Apakah setiap langkah mudah dipahami? Minta orang lain mengikuti prosedur tanpa bertanya.",
          "",
          "3. UJI KONSISTENSI",
          "  Apakah istilah yang digunakan konsisten? Jangan berganti-ganti antara 'tekan' dan 'pencet'.",
          "",
          "4. UJI KEAMANAN",
          "  Apakah ada peringatan untuk langkah berisiko? Apakah troubleshooting sudah mencakup masalah yang mungkin terjadi?",
          "",
          "5. UJI EFEKTIVITAS",
          "  Apakah prosedur ini metode terbaik? Apakah ada cara yang lebih efisien?",
          "",
          "[Ilustrasi: Sebuah meja kerja dengan dokumen prosedur yang dicoret-coret merah, stiker 'REVISI' dan 'APPROVED', serta alat tulis. Di sampingnya, tiga orang sedang berdiskusi sambil menunjuk ke bagan alir di dinding. Gaya ilustrasi ruang rapat quality control dengan warna putih dan hijau.]",
        ],
        contoh: [
          "Contoh revisi prosedur:",
          "",
          "SEBELUM (kurang jelas): \"Panaskan oven. Masukkan adonan. Tunggu sampai matang.\"",
          "✗ Berapa suhu? Berapa lama? Oven apa?",
          "",
          "SESUDAH (lebih baik): \"1. Panaskan oven listrik hingga suhu 180°C (tunggu 10 menit). 2. Masukkan loyang berisi adonan ke rak tengah. 3. Panggang selama 25-30 menit hingga permukaan kecokelatan. 4. Untuk mengecek kematangan, tusuk dengan lidi — jika tidak ada adonan yang menempel, kue sudah matang.\"",
          "✓ Spesifik: suhu, waktu, posisi, cara verifikasi.",
        ],
      },
    ],
    rangkuman: [
      "[Ilustrasi: Buku manual teknis terbuka dengan halaman penuh diagram alir berwarna. Dari tengah buku, muncul ikon-ikon: checklist (verifikasi), kunci inggris (alat), segitiga peringatan, dan tanda centang (validasi). Gaya ilustrasi buku panduan teknis dengan warna biru dan kuning.]",
      "Teks prosedur lanjutan memiliki langkah lebih kompleks, percabangan bersyarat, dan penanganan error.",
      "Struktur: judul/tujuan → prasyarat → langkah bersubcabang → peringatan/troubleshooting → verifikasi → penutup.",
      "Kaidah: imperatif, deklaratif, konjungsi syarat, verba material/mental, nominalisasi.",
      "Evaluasi prosedur: uji kelengkapan, kejelasan, konsistensi, keamanan, efektivitas.",
    ],
  },
  latihan: makeSoal([
    ["Perbedaan utama teks prosedur dasar dan lanjutan adalah...", ["Tidak ada perbedaan", "Prosedur lanjutan memiliki subcabang dan percabangan bersyarat", "Prosedur lanjutan lebih pendek", "Prosedur dasar lebih rumit"], 1, "Prosedur lanjutan memiliki subcabang, percabangan bersyarat, dan troubleshooting."],
    ["'Pastikan kabel sudah terhubung sebelum menyalakan mesin.' Kalimat ini menggunakan kata kerja...", ["Material", "Mental (verifikasi)", "Pasif", "Aktif"], 1, "'Pastikan' adalah kata kerja mental yang berkaitan dengan verifikasi."],
    ["Bagian yang menjelaskan solusi untuk masalah umum dalam prosedur disebut...", ["Prasyarat", "Troubleshooting", "Verifikasi", "Peringatan"], 1, "Troubleshooting berisi solusi untuk masalah yang mungkin terjadi."],
    ["Fungsi prasyarat dalam teks prosedur adalah...", ["Memperpanjang teks", "Memastikan pengguna siap sebelum memulai", "Menjelaskan alat", "Menambahkan peringatan"], 1, "Prasyarat memastikan semua kondisi yang diperlukan sudah terpenuhi."],
    ["Contoh nominalisasi yang tepat adalah...", ["Memasang kabel", "Pemasangan kabel", "Kabel dipasang", "Pasang kabel"], 1, "'Pemasangan kabel' adalah nominalisasi dari 'memasang kabel'."],
    ["Mengapa teks prosedur harus diuji coba?", ["Agar terlihat profesional", "Untuk memastikan langkah-langkahnya jelas dan efektif", "Untuk menambah jumlah halaman", "Agar lebih mahal"], 1, "Uji coba memastikan prosedur jelas, lengkap, dan efektif."],
    ["Konjungsi yang tepat untuk percabangan bersyarat adalah...", ["Dan", "Jika", "Kemudian", "Atau"], 1, "'Jika' adalah konjungsi syarat untuk percabangan."],
    ["Bagian verifikasi dalam prosedur berisi...", ["Cara memeriksa keberhasilan setiap langkah", "Daftar alat", "Peringatan keselamatan", "Biaya yang diperlukan"], 0, "Verifikasi berisi cara memeriksa apakah langkah sudah dilakukan dengan benar."],
    ["Kalimat deklaratif dalam prosedur berfungsi untuk...", ["Memberi perintah", "Memberi informasi atau penjelasan", "Bertanya", "Melarang"], 1, "Kalimat deklaratif memberi informasi atau penjelasan tentang proses."],
    ["Yang BUKAN termasuk evaluasi prosedur adalah...", ["Uji kelengkapan", "Uji kejelasan", "Uji kecepatan", "Uji keamanan"], 2, "Uji kecepatan bukan bagian dari evaluasi prosedur standar."],
  ]),
  praktik: {
    petunjuk: "Buatlah teks prosedur lanjutan untuk salah satu aktivitas berikut: (1) Cara membuat akun dan mengatur profil di platform e-learning, (2) Cara melakukan percobaan sederhana di laboratorium IPA, (3) Cara membersihkan dan merawat laptop agar awet. Gunakan struktur lengkap termasuk prasyarat, langkah bersubcabang, peringatan, troubleshooting, dan verifikasi. Minimal 10 langkah.",
    tips: [
      "Buat diagram alir sederhana sebelum menulis langkah-langkah",
      "Identifikasi titik-titik rawan error dan tambahkan troubleshooting",
      "Gunakan kata 'jika-maka' untuk percabangan bersyarat",
      "Tambahkan peringatan dengan kata 'PERINGATAN' atau 'HATI-HATI'",
      "Tulis langkah verifikasi setelah setiap langkah penting",
    ],
    contoh: "Teks prosedur minimal 10 langkah dengan struktur lengkap: judul, tujuan, prasyarat, langkah (dengan subcabang dan percabangan), peringatan, troubleshooting, verifikasi, penutup.",
  },
  kuis: makeSoal([
    ["Yang membedakan teks prosedur tingkat lanjut dari tingkat dasar adalah...", ["Jumlah kata", "Percabangan bersyarat dan troubleshooting", "Warna font", "Panjang kalimat"], 1, "Prosedur lanjutan memiliki percabangan bersyarat dan troubleshooting."],
    ["'Pengukuran suhu harus dilakukan secara berkala.' Kata 'pengukuran' adalah contoh...", ["Verba material", "Nominalisasi", "Konjungsi", "Adverbia"], 1, "'Pengukuran' adalah nominalisasi dari kata kerja 'mengukur'."],
    ["Bagian yang memuat syarat yang harus dipenuhi sebelum memulai prosedur adalah...", ["Tujuan", "Prasyarat", "Verifikasi", "Penutup"], 1, "Prasyarat berisi hal-hal yang harus disiapkan sebelum memulai."],
    ["Teks prosedur yang baik harus diuji...", ["Harga", "Kejelasan dan kelengkapan", "Keindahan bahasa", "Ketebalan"], 1, "Prosedur harus diuji kejelasan, kelengkapan, konsistensi, dan keamanan."],
    ["Fungsi bagian troubleshooting adalah...", ["Mencegah masalah", "Memberi solusi jika terjadi masalah", "Menambah langkah", "Mengganti peringatan"], 1, "Troubleshooting memberikan solusi untuk masalah yang umum terjadi."],
    ["Contoh kata kerja verifikasi dalam prosedur adalah...", ["Potong", "Periksa", "Buka", "Tarik"], 1, "'Periksa' adalah kata kerja mental untuk verifikasi."],
    ["'Jika lampu indikator tidak menyala, periksa koneksi kabel.' Kalimat ini menggunakan...", ["Konjungsi temporal", "Konjungsi syarat", "Konjungsi tujuan", "Konjungsi perlawanan"], 1, "'Jika' menunjukkan konjungsi syarat."],
    ["Salah satu tujuan penulisan prosedur yang baik adalah...", ["Membingungkan pembaca", "Meminimalkan kesalahan dalam pelaksanaan", "Memperpanjang waktu", "Menambah biaya"], 1, "Prosedur yang baik meminimalkan kesalahan dalam pelaksanaan."],
    ["Dalam SOP, singkatan SOP berarti...", ["System Operation Plan", "Standard Operating Procedure", "Simple Operating Process", "Special Operation Protocol"], 1, "SOP = Standard Operating Procedure."],
    ["Verifikasi dalam prosedur penting karena...", ["Memperindah teks", "Memastikan langkah berhasil sebelum lanjut", "Mengganti instruksi", "Menambah jumlah halaman"], 1, "Verifikasi memastikan langkah berhasil sebelum melanjutkan ke langkah berikutnya."],
  ]),
}

export default konten
