import type { Konten } from "../types"
import { makeSoal } from "../types"

const konten: Konten = {
  belajar: {
    tujuan: [
      "Memahami pengertian dan ciri-ciri teks eksplanasi kompleks",
      "Mengidentifikasi struktur teks eksplanasi dengan tepat",
      "Menganalisis hubungan kausalitas dalam teks eksplanasi",
      "Menyusun teks eksplanasi tentang fenomena alam, sosial, atau budaya",
      "Menyajikan teks eksplanasi secara lisan dan tertulis dengan runtut",
    ],
    materi: [
      {
        judul: "Mengenal Teks Eksplanasi Tingkat Lanjut",
        isi: [
          "Teks eksplanasi adalah teks yang menjelaskan proses terjadinya suatu fenomena — baik alam, sosial, maupun budaya. Di kelas XI, kita akan mempelajari eksplanasi yang lebih kompleks dengan analisis hubungan sebab-akibat yang mendalam.",
          "",
          "✓ Ciri-ciri teks eksplanasi:",
          "  ✓ Berisi fakta, bukan opini",
          "  ✓ Menjelaskan proses 'mengapa' dan 'bagaimana'",
          "  ✓ Hubungan kausalitas (sebab-akibat) bersifat ilmiah dan logis",
          "  ✓ Menggunakan istilah teknis sesuai bidang",
          "  ✓ Bersifat informatif dan objektif",
          "",
          "[Ilustrasi: Infografis gunung berapi yang memperlihatkan penampang melintang — dari magma di perut bumi, letusan, hingga awan panas dan aliran lava. Panah-panah penjelas menunjukkan setiap tahapan dengan label ilmiah. Gaya ilustrasi infografis geologi dengan warna merah, oranye, dan cokelat.]",
        ],
        contoh: [
          "PERBANDINGAN TEKS EKSPLANASI SEDERHANA DAN KOMPLEKS:",
          "",
          "SEDERHANA — Hujan:",
          "Hujan terjadi karena uap air di awan mengembun dan jatuh ke bumi.",
          "",
          "KOMPLEKS — Hujan Asam:",
          "Hujan asam terbentuk melalui serangkaian reaksi kimia. Gas sulfur dioksida (SO2) dan nitrogen oksida (NOx) dari emisi industri dan kendaraan bermotor naik ke atmosfer. Gas-gas ini bereaksi dengan oksigen dan uap air membentuk asam sulfat (H2SO4) dan asam nitrat (HNO3). Ketika turun sebagai hujan, air yang mengandung asam ini dapat merusak bangunan, mengasamkan tanah dan air, serta mengancam ekosistem.",
          "✓ Lebih detail, ada istilah kimia, ada hubungan sebab-akibat yang jelas.",
        ],
        catatan: "Teks eksplanasi berbeda dengan teks prosedur. Eksplanasi menjawab 'mengapa' dan 'bagaimana' suatu fenomena terjadi, sedangkan prosedur menjawab 'bagaimana cara melakukannya'. Jangan tertukar!",
      },
      {
        judul: "Struktur Teks Eksplanasi",
        isi: [
          "Teks eksplanasi memiliki tiga bagian utama yang wajib dipahami.",
          "",
          "1. PERNYATAAN UMUM (IDENTIFIKASI FENOMENA)",
          "  Berisi pengantar tentang fenomena yang akan dijelaskan. Menyebutkan topik secara umum dan menarik minat pembaca.",
          "",
          "2. DERETAN PENJELASAN (EKSPLANASI)",
          "  Berisi rangkaian penjelasan tentang proses terjadinya fenomena. Bagian ini terdiri dari beberapa paragraf yang menjelaskan sebab-akibat secara berurutan. Semakin kompleks fenomena, semakin panjang deretan penjelasannya.",
          "",
          "3. INTERPRETASI (PENUTUP)",
          "  Berisi kesimpulan, makna, atau dampak dari fenomena yang dijelaskan. Bagian ini bersifat opsional tetapi sangat dianjurkan untuk memberikan pemahaman utuh.",
          "",
          "[Ilustrasi: Diagram alur tiga kotak besar yang saling terhubung panah. Kotak 1 'Identifikasi Fenomena' dengan ikon kaca pembesar. Kotak 2 'Deretan Penjelasan' dengan ikon rantai yang menghubungkan beberapa lingkaran (sebab-akibat). Kotak 3 'Interpretasi' dengan ikon tanda seru di dalam segitiga. Gaya ilustrasi diagram organisasi dengan warna biru laut, hijau, dan kuning.]",
        ],
        contoh: [
          "CONTOH STRUKTUR — Fenomena Pelangi:",
          "",
          "1. PERNYATAAN UMUM:",
          "Pelangi adalah fenomena optik alami yang terjadi ketika cahaya matahari berinteraksi dengan tetesan air di atmosfer. Keindahan pelangi dengan tujuh warnanya telah memukau manusia sejak zaman dahulu.",
          "",
          "2. DERETAN PENJELASAN:",
          "Pelangi terbentuk melalui proses pembiasan cahaya. Ketika sinar matahari memasuki tetesan air hujan, kecepatan cahaya berkurang dan membelok — ini disebut refraksi. Cahaya putih kemudian terurai menjadi spektrum warna (merah, jingga, kuning, hijau, biru, nila, ungu) karena setiap warna memiliki panjang gelombang yang berbeda. Setelah mencapai dinding belakang tetesan, cahaya dipantulkan kembali ke permukaan depan dan keluar dengan sudut tertentu — inilah mengapa pelangi selalu berbentuk setengah lingkaran.",
          "",
          "3. INTERPRETASI:",
          "Pelangi bukan sekadar keindahan visual — fenomena ini menunjukkan betapa kompleksnya interaksi antara cahaya dan materi. Pemahaman tentang spektrum cahaya telah melahirkan berbagai teknologi, dari fotografi hingga komunikasi serat optik.",
        ],
      },
      {
        judul: "Kaidah Kebahasaan Teks Eksplanasi",
        isi: [
          "Mari pelajari kaidah bahasa yang membuat teks eksplanasi ilmiah dan objektif!",
          "",
          "1. KALIMAT DEFINITIF DAN FAKTUAL",
          "  Menggunakan fakta yang terverifikasi. Hindari opini pribadi. Contoh: 'Gunung meletus karena tekanan magma' (fakta), bukan 'Gunung meletus sepertinya marah' (opini).",
          "",
          "2. KONJUNGSI KAUSALITAS DAN KRONOLOGIS",
          "  Kausalitas: karena, sebab, akibatnya, oleh karena itu, sehingga, dengan demikian.",
          "  Kronologis: kemudian, setelah itu, lalu, pada akhirnya, selanjutnya.",
          "",
          "3. KATA KERJA MATERIAL DAN RELASIONAL",
          "  Material: meletus, mengalir, menguap, membeku, menghancurkan.",
          "  Relasional: adalah, merupakan, yaitu, terdiri atas, disebut.",
          "",
          "4. ISTILAH TEKNIS / ILMIAH",
          "  Menggunakan kosakata spesifik bidang: 'evaporasi', 'kondensasi', 'presipitasi' untuk hidrologi; 'fotosintesis', 'klorofil' untuk biologi.",
          "",
          "5. KATA SERAPAN YANG TEPAT",
          "  Banyak istilah eksplanasi berasal dari bahasa asing yang sudah diserap ke bahasa Indonesia. Gunakan dengan tepat dan konsisten.",
          "",
          "[Ilustrasi: Buku catatan terbuka dengan 5 kategori kebahasaan yang masing-masing memiliki stiker berwarna. Kategori 1: stiker 'FAKTA' biru. Kategori 2: stiker panah sebab-akibat merah. Kategori 3: stiker ikon tangan dan orang hijau. Kategori 4: stiker tabung reaksi ungu. Kategori 5: stiker globe oranye. Gaya ilustrasi catatan pelajar dengan warna pastel.]",
        ],
        contoh: [
          "Analisis kebahasaan paragraf eksplanasi:",
          "",
          "Paragraf: \"Tsunami terjadi akibat pergeseran lempeng tektonik di dasar laut. Ketika lempeng bergerak secara tiba-tiba, energi besar terlepas dan mendorong massa air. Gelombang kemudian bergerak dengan kecepatan tinggi menuju pantai. Oleh karena itu, daerah pesisir yang dekat dengan zona subduksi sangat rentan terhadap tsunami.\"",
          "",
          "Analisis:",
          "- 'terjadi akibat' → konjungsi kausalitas",
          "- 'pergeseran lempeng tektonik' → istilah teknis geologi",
          "- 'ketika' → konjungsi temporal/kronologis",
          "- 'mendorong, bergerak' → kata kerja material",
          "- 'adalah' → kata kerja relasional (implisit dalam 'tsunami terjadi')",
          "- 'Oleh karena itu' → konjungsi kausalitas",
          "- 'rentan' → istilah teknis kebencanaan",
        ],
      },
      {
        judul: "Menyusun Teks Eksplanasi yang Baik",
        isi: [
          "Setelah memahami struktur dan kaidah kebahasaan, saatnya menyusun teks eksplanasi!",
          "",
          "PENTING: Teks eksplanasi harus berdasarkan data dan fakta yang valid. Gunakan sumber terpercaya seperti buku teks, jurnal ilmiah, atau situs resmi.",
          "",
          "LANGKAH MENYUSUN TEKS EKSPLANASI:",
          "",
          "1. Pilih fenomena yang menarik dan kamu kuasai",
          "  Alam: gempa bumi, tsunami, siklus air, fotosintesis, gerhana.",
          "  Sosial: kemacetan, inflasi, bullying, urbanisasi, digitalisasi.",
          "  Budaya: tradisi, kesenian, perubahan sosial.",
          "",
          "2. Kumpulkan data dan fakta",
          "  Cari informasi tentang proses, penyebab, dan dampak fenomena.",
          "",
          "3. Buat kerangka dengan struktur baku",
          "  Identifikasi → Deretan Penjelasan (sebab-akibat) → Interpretasi.",
          "",
          "4. Kembangkan kerangka menjadi paragraf",
          "  Gunakan kalimat efektif dan istilah teknis yang tepat.",
          "",
          "5. Review dan revisi",
          "  Periksa keakuratan fakta, kejelasan hubungan kausal, dan kebahasaan.",
          "",
          "[Ilustrasi: Meja belajar dengan laptop yang menampilkan dokumen teks eksplanasi tentang perubahan iklim. Di samping laptop ada buku referensi, jurnal ilmiah, dan secangkir kopi. Papan sticky notes di dinding berisi kerangka tulisan: 'Fenomena → Penyebab → Proses → Dampak → Solusi'. Gaya ilustrasi ruang belajar modern dengan warna cokelat kayu dan hijau.]",
        ],
        contoh: [
          "Kerangka teks eksplanasi — 'Urbanisasi di Indonesia':",
          "",
          "IDENTIFIKASI:",
          "Fenomena perpindahan penduduk dari desa ke kota yang terus meningkat setiap tahun.",
          "",
          "DERETAN PENJELASAN (kausalitas):",
          "Faktor pendorong (desa): lapangan kerja terbatas, upah rendah, fasilitas minim.",
          "Faktor penarik (kota): banyak pekerjaan, upah lebih tinggi, fasilitas lengkap.",
          "Akibat: kepadatan penduduk kota, permukiman kumuh (slum area), kemacetan, kesenjangan sosial.",
          "",
          "INTERPRETASI:",
          "Urbanisasi adalah fenomena yang tak terhindarkan seiring pembangunan. Namun, jika tidak dikelola dengan baik, dampak negatifnya bisa lebih besar dari manfaatnya.",
        ],
      },
    ],
    rangkuman: [
      "[Ilustrasi: Buku terbuka dengan halaman yang memuat diagram siklus. Dari halaman buku muncul berbagai ikon: kaca pembesar (identifikasi), rantai (sebab-akibat), buku (fakta), dan otak (interpretasi). Gaya ilustrasi buku pengetahuan dengan warna biru dan putih.]",
      "Teks eksplanasi menjelaskan proses terjadinya fenomena alam, sosial, atau budaya.",
      "Struktur: pernyataan umum → deretan penjelasan (kausalitas) → interpretasi.",
      "Kaidah: kalimat faktual, konjungsi kausalitas, kata kerja material/relasional, istilah teknis.",
      "Langkah penyusunan: pilih fenomena → kumpulkan data → buat kerangka → kembangkan → review.",
    ],
  },
  latihan: makeSoal([
    ["Teks eksplanasi bertujuan untuk...", ["Menghibur pembaca", "Menjelaskan proses terjadinya suatu fenomena", "Membujuk pembaca", "Menceritakan kisah fiksi"], 1, "Teks eksplanasi bertujuan menjelaskan mengapa dan bagaimana suatu fenomena terjadi."],
    ["Struktur teks eksplanasi yang benar adalah...", ["Orientasi-komplikasi-resolusi", "Pernyataan umum-deretan penjelasan-interpretasi", "Abstraksi-orientasi-krisis", "Tesis-argumentasi-penegasan"], 1, "Struktur teks eksplanasi terdiri dari pernyataan umum, deretan penjelasan (eksplanasi), dan interpretasi."],
    ["Contoh konjungsi kausalitas yang tepat adalah...", ["Kemudian", "Selanjutnya", "Akibatnya", "Setelah itu"], 2, "'Akibatnya' adalah konjungsi yang menunjukkan hubungan sebab-akibat."],
    ["Berikut yang termasuk fenomena alam yang bisa dijelaskan dengan teks eksplanasi adalah...", ["Kisah Malin Kundang", "Proses terjadinya pelangi", "Cara membuat nasi goreng", "Resensi novel"], 1, "Proses terjadinya pelangi adalah fenomena alam yang sesuai untuk teks eksplanasi."],
    ["Kata kerja relasional dalam teks eksplanasi berfungsi untuk...", ["Menunjukkan tindakan fisik", "Menghubungkan subjek dengan deskripsinya", "Menyatakan perintah", "Menunjukkan kepemilikan"], 1, "Kata kerja relasional seperti 'adalah', 'merupakan', 'yaitu' menghubungkan subjek dengan deskripsi atau definisinya."],
    ["Bagian interpretasi dalam teks eksplanasi berisi...", ["Pengantar topik", "Rincian proses terjadinya fenomena", "Kesimpulan atau makna dari fenomena", "Daftar pustaka"], 2, "Interpretasi berisi kesimpulan, makna, atau dampak dari fenomena."],
    ["Yang BUKAN ciri teks eksplanasi adalah...", ["Berdasarkan fakta", "Bersifat objektif", "Berisi opini penulis", "Menggunakan istilah teknis"], 2, "Teks eksplanasi bersifat objektif dan faktual, bukan opini."],
    ["'Hujan asam terjadi karena reaksi kimia antara polutan dan air hujan.' Kata 'karena' menunjukkan...", ["Hubungan kronologis", "Hubungan kausalitas", "Hubungan pertentangan", "Hubungan penambahan"], 1, "'Karena' adalah konjungsi yang menunjukkan hubungan sebab-akibat (kausalitas)."],
    ["Istilah 'evaporasi', 'kondensasi', dan 'presipitasi' berkaitan dengan fenomena...", ["Gempa bumi", "Siklus air", "Fotosintesis", "Pemanasan global"], 1, "Ketiga istilah tersebut adalah tahapan dalam siklus air (hidrologi)."],
    ["Teks eksplanasi harus ditulis secara objektif, artinya...", ["Berdasarkan perasaan penulis", "Berdasarkan fakta dan data yang valid", "Menggunakan bahasa yang indah", "Berisi imajinasi penulis"], 1, "Objektif berarti berdasarkan fakta dan data, bukan opini atau perasaan pribadi."],
  ]),
  praktik: {
    petunjuk: "Pilihlah salah satu fenomena berikut, lalu buatlah teks eksplanasi lengkap dengan struktur yang benar: (1) Terjadinya gempa bumi, (2) Proses fotosintesis pada tumbuhan, (3) Fenomena kemacetan di kota besar, (4) Proses terjadinya banjir bandang. Tulis minimal 5 paragraf dengan memperhatikan hubungan kausalitas dan kaidah kebahasaan.",
    tips: [
      "Mulai dengan pernyataan umum yang menarik perhatian pembaca",
      "Gunakan kata penghubung kausalitas seperti 'karena', 'sehingga', 'oleh karena itu'",
      "Sertakan minimal satu istilah teknis yang relevan dengan topik",
      "Akhiri dengan interpretasi yang memberikan makna atau kesimpulan",
      "Periksa kembali fakta-fakta yang kamu tulis — pastikan akurat",
    ],
    contoh: "Teks eksplanasi 5 paragraf dengan struktur: paragraf 1 pernyataan umum, paragraf 2-4 deretan penjelasan (sebab-akibat), paragraf 5 interpretasi.",
  },
  kuis: makeSoal([
    ["Fungsi deretan penjelasan dalam teks eksplanasi adalah...", ["Memperkenalkan topik", "Menjelaskan proses secara rinci", "Menyimpulkan isi", "Memberikan opini"], 1, "Deretan penjelasan berisi rincian proses terjadinya fenomena."],
    ["'Letusan gunung berapi terjadi akibat tekanan magma yang sangat tinggi di dalam perut bumi.' Kalimat ini menggunakan konjungsi...", ["Kronologis", "Kausalitas", "Pertentangan", "Perbandingan"], 1, "'Akibat' menunjukkan hubungan sebab-akibat (kausalitas)."],
    ["Bagian yang berisi kesimpulan dari fenomena yang dijelaskan disebut...", ["Identifikasi", "Interpretasi", "Eksplanasi", "Orientasi"], 1, "Interpretasi adalah bagian penutup yang berisi kesimpulan atau makna."],
    ["Contoh kata kerja material dalam teks eksplanasi adalah...", ["Adalah", "Meletus", "Merupakan", "Yaitu"], 1, "'Meletus' adalah kata kerja material yang menunjukkan tindakan fisik."],
    ["Kata 'merupakan' termasuk jenis kata kerja...", ["Material", "Relasional", "Mental", "Aktif"], 1, "'Merupakan' adalah kata kerja relasional yang menghubungkan subjek dengan deskripsinya."],
    ["Yang harus dihindari dalam teks eksplanasi adalah...", ["Fakta ilmiah", "Opini pribadi", "Istilah teknis", "Data statistik"], 1, "Teks eksplanasi harus objektif dan tidak boleh berisi opini pribadi."],
    ["Kalimat 'Setelah uap air naik ke atmosfer, terjadilah kondensasi' menggunakan konjungsi...", ["Kausalitas", "Kronologis", "Syarat", "Tujuan"], 1, "'Setelah' adalah konjungsi kronologis yang menunjukkan urutan waktu."],
    ["Teks eksplanasi tentang fenomena sosial yang tepat adalah...", ["Proses turunnya hujan", "Faktor penyebab kemacetan", "Siklus hidup kupu-kupu", "Cara membuat kerajinan"], 1, "Kemacetan adalah fenomena sosial yang dapat dijelaskan dengan teks eksplanasi."],
    ["Istilah yang tepat untuk 'penguapan air' dalam siklus hidrologi adalah...", ["Presipitasi", "Evaporasi", "Kondensasi", "Sublimasi"], 1, "Evaporasi adalah proses penguapan air menjadi uap air."],
    ["Tujuan utama interpretasi dalam teks eksplanasi adalah...", ["Menambah panjang teks", "Memberi makna dan kesimpulan", "Membingungkan pembaca", "Memperkenalkan topik baru"], 1, "Interpretasi bertujuan memberikan kesimpulan atau makna dari fenomena."],
  ]),
}

export default konten
