import type { Konten } from "../types"
import { makeSoal } from "../types"

const konten: Konten = {
  belajar: {
    tujuan: [
      "Memahami pengertian, tujuan, dan jenis-jenis teks ceramah",
      "Mengidentifikasi struktur dan ciri kebahasaan teks ceramah",
      "Menganalisis isi, kebahasaan, dan kelogisan argumentasi dalam ceramah",
      "Menyusun teks ceramah tentang berbagai topik aktual",
      "Menyampaikan teks ceramah dengan intonasi, gestur, dan artikulasi yang tepat",
    ],
    materi: [
      {
        judul: "Mengenal Teks Ceramah",
        isi: [
          "Ceramah adalah paparan lisan tentang suatu topik di hadapan khalayak dengan tujuan memberikan informasi, memengaruhi, atau menghibur. Di kelas XI, kita akan belajar menyusun dan menyampaikan ceramah yang efektif.",
          "",
          "✓ Ciri-ciri teks ceramah:",
          "  ✓ Disampaikan secara lisan di depan audiens",
          "  ✓ Memiliki tujuan yang jelas (informatif, persuasif, atau rekreatif)",
          "  ✓ Menggunakan bahasa yang komunikatif dan mudah dipahami",
          "  ✓ Memiliki struktur pembuka, isi, dan penutup",
          "  ✓ Argumentasi yang logis dan didukung data atau fakta",
          "",
          "Perbedaan ceramah, pidato, dan khotbah:",
          "  - Ceramah: lebih interaktif, bisa dialogis, topik umum",
          "  - Pidato: formal, resmi, biasanya dalam acara kenegaraan",
          "  - Khotbah: keagamaan, bersifat dakwah",
          "",
          "[Ilustrasi: Seorang pembicara berdiri di podium dengan mikrofon di tangan, menghadapi audiens yang duduk di kursi. Layar presentasi di belakang menampilkan poin-poin materi. Ekspresi pembicara serius namun ramah. Gaya ilustrasi seminar modern dengan warna biru dan putih.]",
        ],
        contoh: [
          "CONTOH PEMBUKA CERAMAH:",
          "",
          "\"Assalamualaikum warahmatullahi wabarakatuh. Selamat pagi, Bapak/Ibu guru dan teman-teman sekalian yang saya hormati. Pertama-tama, mari kita panjatkan puji syukur ke hadirat Tuhan Yang Maha Esa karena pada pagi hari ini kita masih diberikan kesehatan untuk berkumpul di acara yang bermanfaat ini.\"",
          "",
          "CONTOH ISI CERAMAH (tentang literasi digital):",
          "",
          "\"Tahukah kalian bahwa menurut laporan We Are Social tahun 2024, rata-rata orang Indonesia menghabiskan 7 jam per hari menggunakan internet? Namun, sayangnya, tingkat literasi digital kita masih rendah — banyak yang terjebak hoaks, ujaran kebencian, dan penipuan online. Oleh karena itu, sebagai generasi muda, kita harus membekali diri dengan kemampuan literasi digital.\"",
          "",
          "CONTOH PENUTUP CERAMAH:",
          "",
          "\"Demikian yang dapat saya sampaikan. Semoga bermanfaat dan dapat kita terapkan dalam kehidupan sehari-hari. Mohon maaf apabila ada tutur kata yang kurang berkenan. Wassalamualaikum warahmatullahi wabarakatuh.\"",
        ],
        catatan: "Ceramah yang baik bukan hanya soal isi, tetapi juga cara penyampaian. Latihlah intonasi, kontak mata, dan gesturmu agar pesan tersampaikan dengan maksimal!",
      },
      {
        judul: "Struktur Teks Ceramah",
        isi: [
          "Setiap teks ceramah memiliki struktur baku yang terdiri dari tiga bagian utama.",
          "",
          "1. PEMBUKA (PENDAHULUAN)",
          "  Berisi salam, sapaan, ucapan syukur, dan pengantar topik. Pembuka harus mampu menarik perhatian audiens. Bisa dimulai dengan kutipan, pertanyaan retoris, anekdot singkat, atau data mengejutkan.",
          "",
          "2. ISI (INTI)",
          "  Bagian terpenting ceramah. Berisi uraian topik, argumen, fakta, data, contoh, dan bukti. Biasanya terdiri dari beberapa sub-tema yang disusun secara sistematis. Setiap poin perlu dijelaskan dengan bahasa yang mudah dipahami.",
          "",
          "3. PENUTUP",
          "  Berisi simpulan, pesan, ajakan (call to action), permohonan maaf, dan salam penutup. Penutup yang kuat akan meninggalkan kesan mendalam pada audiens.",
          "",
          "[Ilustrasi: Diagram piramida tiga tingkat. Tingkat bawah 'PEMBUKA' berisi ikon mikrofon dan tangan melambai (salam). Tingkat tengah 'ISI' berisi ikon buku, grafik, dan lampu ide. Tingkat puncak 'PENUTUP' berisi ikon bintang dan tangan berdoa. Panah mengalir dari bawah ke atas. Gaya ilustrasi piramida pendidikan dengan warna hijau, biru, dan ungu.]",
        ],
        contoh: [
          "KERANGKA CERAMAH — 'Pentingnya Menjaga Kesehatan Mental':",
          "",
          "PEMBUKA:",
          "- Salam dan sapaan",
          "- Data: 'Menurut Riset Kesehatan Dasar 2023, 1 dari 10 remaja Indonesia mengalami gangguan mental.'",
          "- Pertanyaan retoris: 'Sudahkah kita peduli dengan kesehatan mental kita?'",
          "",
          "ISI:",
          "A. Pengertian kesehatan mental",
          "B. Faktor-faktor yang memengaruhi kesehatan mental remaja",
          "C. Dampak buruk jika kesehatan mental terganggu",
          "D. Tips menjaga kesehatan mental: olahraga, curhat, meditasi, manajemen stres",
          "",
          "PENUTUP:",
          "- Simpulan: kesehatan mental sama pentingnya dengan kesehatan fisik",
          "- Ajakan: 'Mulai hari ini, mari peduli pada kesehatan mental kita dan orang sekitar.'",
          "- Permohonan maaf dan salam penutup",
        ],
      },
      {
        judul: "Kaidah Kebahasaan Teks Ceramah",
        isi: [
          "Teks ceramah memiliki ciri bahasa yang khas. Mari kita pelajari!",
          "",
          "1. KALIMAT PERSUASIF",
          "  Mengajak, membujuk, atau memengaruhi audiens. Ditandai kata-kata: mari, ayo, sebaiknya, hendaknya, janganlah.",
          "",
          "2. KALIMAT INTEROGATIF RETORIS",
          "  Pertanyaan yang tidak memerlukan jawaban, tetapi untuk memicu pemikiran. Contoh: 'Siapa yang tidak ingin sukses?'",
          "",
          "3. KATA SERUAN (INTERJEKSI)",
          "  Wah, aduh, oh, nah, ya — untuk mengekspresikan emosi atau menarik perhatian.",
          "",
          "4. KALIMAT DEKLARATIF UNTUK MENYATAKAN FAKTA",
          "  Ceramah yang baik didukung data dan fakta yang meyakinkan.",
          "",
          "5. PRONOMINA PERSONA (KATA GANTI ORANG)",
          "  Menggunakan 'kita' (inklusif) untuk membangun kedekatan dengan audiens, 'saya' untuk menyampaikan pendapat pribadi, 'Bapak/Ibu/Saudara' untuk menghormati audiens.",
          "",
          "[Ilustrasi: Papan tulis interaktif dengan 5 kategori bahasa ceramah. Kategori 1: megafon dengan kata 'AYO' dan 'MARI' (persuasif). Kategori 2: tanda tanya besar dengan wajah berpikir (retoris). Kategori 3: gelembung ucapan dengan 'Wah!' (interjeksi). Kategori 4: buku dengan simbol centang (deklaratif). Kategori 5: lingkaran orang 'KITA' (pronomina). Gaya ilustrasi papan tulis kelas dengan warna putih dan warna-warni.]",
        ],
        contoh: [
          "Analisis kebahasaan dalam teks ceramah:",
          "",
          "Kalimat: \"Marilah kita tingkatkan kepedulian terhadap sesama. Bukankah kita semua ingin hidup dalam lingkungan yang harmonis? Wah, alangkah indahnya jika setiap orang saling membantu!\"",
          "",
          "Analisis:",
          "- 'Marilah kita' → kalimat persuasif (ajakan) + pronomina inklusif",
          "- 'Bukankah kita semua ingin hidup dalam lingkungan yang harmonis?' → kalimat interogatif retoris",
          "- 'Wah' → interjeksi (kata seruan)",
          "- 'kita' → pronomina persona inklusif",
          "",
          "Kalimat: \"Menurut data BPS, angka kemiskinan di Indonesia turun 0,5% pada tahun lalu.\"",
          "- Kalimat deklaratif → menyatakan fakta",
          "- 'Menurut data BPS' → menunjukkan sumber yang kredibel",
        ],
      },
      {
        judul: "Teknik Menyusun dan Menyampaikan Ceramah",
        isi: [
          "Ceramah yang baik lahir dari persiapan yang matang. Berikut panduan lengkapnya!",
          "",
          "PENTING: Audiens adalah raja. Sesuaikan bahasa, gaya, dan isi ceramah dengan karakteristik audiensmu!",
          "",
          "A. TEKNIK MENYUSUN CERAMAH:",
          "1. Tentukan topik dan tujuan (informatif/persuasif/rekreatif)",
          "2. Kenali audiens: usia, latar belakang, minat, kebutuhan",
          "3. Kumpulkan materi: data, fakta, contoh, kutipan, ilustrasi",
          "4. Buat kerangka: pembuka → isi (3-5 poin) → penutup",
          "5. Kembangkan kerangka menjadi teks utuh",
          "6. Latih penyampaian: vokal, intonasi, jeda, gestur",
          "",
          "B. TEKNIK PENYAMPAIAN:",
          "  • Kontak mata — pandang audiens secara merata",
          "  • Intonasi — bervariasi, tidak monoton",
          "  • Artikulasi — ucapkan kata dengan jelas",
          "  • Gestur — gunakan gerakan tangan yang natural",
          "  • Kecepatan bicara — tidak terlalu cepat atau lambat",
          "  • Humor — selingi dengan humor yang relevan",
          "",
          "[Ilustrasi: Seorang remaja berlatih ceramah di depan cermin kamar. Di tangannya ada naskah. Di dinding ada poster tips public speaking: 'Kontak Mata', 'Intonasi', 'Gestur', 'Artikulasi'. Di lantai ada buku-buku referensi. Gaya ilustrasi kamar remaja dengan warna ungu dan biru.]",
        ],
        contoh: [
          "CONTOH TEKS CERAMAH SINGKAT — 'Bahaya Narkoba bagi Remaja':",
          "",
          "PEMBUKA:",
          "\"Assalamualaikum warahmatullahi wabarakatuh. Selamat siang, teman-teman yang saya banggakan. Sebelum kita mulai, saya ingin bertanya: siapa di sini yang ingin masa depannya hancur? Tentu tidak ada, kan?\"",
          "",
          "ISI:",
          "\"Narkoba adalah musuh besar generasi muda. Menurut BNN, angka penyalahgunaan narkoba di kalangan pelajar meningkat setiap tahun. Narkoba tidak hanya merusak kesehatan fisik — merusak otak, jantung, dan paru-paru — tetapi juga menghancurkan masa depan. Pengguna narkoba akan kehilangan konsentrasi belajar, dikeluarkan dari sekolah, dan dijauhi oleh keluarga. Oleh karena itu, kita harus menjauhi narkoba. Isi waktu luang dengan kegiatan positif: olahraga, seni, atau organisasi.\"",
          "",
          "PENUTUP:",
          "\"Kesimpulannya, narkoba tidak memberikan manfaat sedikit pun. Mari kita jauhi narkoba dan raih masa depan gemilang. Sekian yang dapat saya sampaikan, mohon maaf apabila ada kekurangan. Wassalamualaikum warahmatullahi wabarakatuh.\"",
        ],
      },
    ],
    rangkuman: [
      "[Ilustrasi: Panggung seminar dengan podium di tengah, sorot lampu mengarah ke podium. Di layar besar di belakang tertulis 'CERAMAH'. Di sekeliling panggung ada ikon-ikon: struktur (piramida), bahasa (gelembung kata), teknik penyampaian (mikrofon). Gaya ilustrasi panggung modern dengan warna emas dan biru.]",
      "Ceramah adalah paparan lisan di depan umum dengan tujuan informatif, persuasif, atau rekreatif.",
      "Struktur: pembuka (salam, sapaan, pengantar) → isi (argumentasi, fakta) → penutup (simpulan, ajakan, salam).",
      "Kaidah: persuasif, interogatif retoris, interjeksi, deklaratif, pronomina persona inklusif.",
      "Teknik penyampaian: kontak mata, intonasi, artikulasi, gestur, kecepatan bicara, dan humor relevan.",
    ],
  },
  latihan: makeSoal([
    ["Tujuan utama teks ceramah adalah...", ["Menghibur dengan cerita lucu", "Menyampaikan informasi, memengaruhi, atau menghibur audiens", "Menceritakan pengalaman pribadi", "Menulis artikel ilmiah"], 1, "Ceramah bertujuan informatif, persuasif, atau rekreatif."],
    ["Bagian pembuka teks ceramah sebaiknya berisi...", ["Kesimpulan topik", "Salam, sapaan, dan pengantar yang menarik", "Argumentasi dan data", "Ajakan kepada audiens"], 1, "Pembuka berisi salam, sapaan, dan pengantar topik yang menarik perhatian."],
    ["Contoh kalimat persuasif dalam ceramah adalah...", ["Harga beras naik 5%", "Mari kita jaga kebersihan lingkungan", "Saya lahir di Jakarta", "Budi adalah siswa teladan"], 1, "'Mari kita jaga kebersihan lingkungan' adalah kalimat ajakan (persuasif)."],
    ["'Siapa yang tidak ingin sukses?' Kalimat ini termasuk jenis...", ["Interogatif biasa", "Interogatif retoris", "Deklaratif", "Imperatif"], 1, "Kalimat tersebut adalah pertanyaan retoris yang tidak memerlukan jawaban."],
    ["Kata 'kita' dalam ceramah berfungsi untuk...", ["Menjaga jarak dengan audiens", "Membangun kedekatan dan rasa kebersamaan", "Menunjuk pihak ketiga", "Menyatakan kepemilikan"], 1, "Pronomina 'kita' bersifat inklusif dan membangun kedekatan."],
    ["Berikut adalah contoh interjeksi yang tepat dalam ceramah...", ["Ayo", "Wah", "Jika", "Karena"], 1, "'Wah' adalah kata seruan (interjeksi) yang mengekspresikan perasaan."],
    ["Yang membedakan ceramah dengan pidato adalah...", ["Ceramah lebih resmi", "Ceramah bisa lebih interaktif dan dialogis", "Pidato lebih santai", "Tidak ada perbedaan"], 1, "Ceramah cenderung lebih interaktif daripada pidato yang formal."],
    ["Struktur teks ceramah yang benar adalah...", ["Orientasi-komplikasi-resolusi", "Pembuka-isi-penutup", "Tesis-argumentasi-penegasan", "Abstrak-isi-penutup"], 1, "Struktur ceramah terdiri dari pembuka, isi, dan penutup."],
    ["Teknik yang harus diperhatikan saat menyampaikan ceramah adalah...", ["Membaca naskah terus menerus", "Kontak mata dengan audiens", "Menunduk sepanjang waktu", "Berbicara secepat mungkin"], 1, "Kontak mata penting untuk membangun koneksi dengan audiens."],
    ["Yang BUKAN termasuk ciri teks ceramah adalah...", ["Disampaikan secara lisan", "Menggunakan bahasa ilmiah yang rumit", "Memiliki tujuan yang jelas", "Argumentasi logis"], 1, "Ceramah harus menggunakan bahasa yang komunikatif, bukan bahasa rumit."],
  ]),
  praktik: {
    petunjuk: "Buatlah teks ceramah lengkap sesuai struktur tentang salah satu topik berikut: (1) Pentingnya membaca buku di era digital, (2) Bahaya bullying di lingkungan sekolah, (3) Generasi muda dan cinta tanah air, (4) Disiplin sebagai kunci kesuksesan. Panjang teks minimal 250 kata. Setelah selesai, berlatihlah menyampaikannya di depan teman atau keluarga!",
    tips: [
      "Mulai dengan pembuka yang menarik — gunakan data, pertanyaan, atau kutipan",
      "Gunakan kata 'kita' untuk membangun kedekatan dengan audiens",
      "Sisipkan humor ringan yang relevan dengan topik",
      "Akhiri dengan ajakan yang konkret dan mudah dilakukan",
      "Latih di depan cermin untuk memperbaiki gestur dan ekspresi",
    ],
    contoh: "Teks ceramah 3 paragraf (pembuka-isi-penutup) minimal 250 kata dengan struktur lengkap dan kaidah kebahasaan yang sesuai.",
  },
  kuis: makeSoal([
    ["Kalimat 'Bukankah kita semua ingin hidup bahagia?' adalah contoh...", ["Kalimat deklaratif", "Kalimat interogatif retoris", "Kalimat imperatif", "Kalimat eksklamatif"], 1, "Kalimat tersebut adalah pertanyaan retoris yang tidak membutuhkan jawaban."],
    ["Fungsi kata 'marilah' dalam teks ceramah adalah...", ["Menunjukkan waktu", "Mengajak audiens", "Menjelaskan fakta", "Mengakhiri ceramah"], 1, "'Marilah' adalah kata persuasif yang mengajak audiens."],
    ["Bagian isi ceramah sebaiknya memuat...", ["Salam dan sapaan", "Argumentasi, data, dan contoh", "Permohonan maaf", "Salam penutup"], 1, "Isi ceramah berisi uraian topik, argumen, dan data pendukung."],
    ["Pronomina yang tepat untuk membangun kedekatan dengan audiens adalah...", ["Saya", "Kita", "Mereka", "Dia"], 1, "'Kita' bersifat inklusif dan membangun rasa kebersamaan."],
    ["Teknik penyampaian ceramah yang baik adalah...", ["Membaca naskah terus menerus", "Menggunakan intonasi yang bervariasi", "Berbicara monoton", "Menghindari kontak mata"], 1, "Intonasi bervariasi membuat ceramah tidak membosankan."],
    ["Teks ceramah tentang pentingnya vaksinasi termasuk tujuan...", ["Rekreatif", "Informatif-persuasif", "Ekspresif", "Estetis"], 1, "Ceramah tentang vaksinasi bertujuan memberi informasi dan mengajak audiens."],
    ["Contoh kalimat deklaratif dalam ceramah adalah...", ["Ayo kita belajar!", "Menurut WHO, 70% penyakit dapat dicegah dengan vaksin", "Bukankah itu luar biasa?", "Wah, hebat sekali!"], 1, "'Menurut WHO...' adalah kalimat deklaratif yang menyatakan fakta."],
    ["Kata 'hendaknya' dalam ceramah termasuk ciri kebahasaan...", ["Interogatif", "Persuasif", "Interjeksi", "Deklaratif"], 1, "'Hendaknya' adalah kata persuasif yang menyarankan atau mengharapkan."],
    ["Yang harus dilakukan saat berlatih ceramah adalah...", ["Hafal semua kata", "Berlatih di depan cermin", "Tidak perlu persiapan", "Berbicara cepat"], 1, "Berlatih di depan cermin membantu memperbaiki gestur dan ekspresi."],
    ["Bagian penutup ceramah sebaiknya berisi...", ["Data dan fakta baru", "Simpulan, ajakan, dan permohonan maaf", "Pengantar topik", "Argumentasi panjang"], 1, "Penutup berisi simpulan, ajakan, dan permohonan maaf."],
  ]),
}

export default konten
