import type { Konten } from "../types"
import { makeSoal } from "../types"

const konten: Konten = {
  belajar: {
    tujuan: [
      "Memahami sejarah periodisasi puisi Indonesia dari masa ke masa",
      "Mengidentifikasi ciri khas setiap angkatan dalam puisi Indonesia",
      "Menganalisis puisi dari berbagai angkatan berdasarkan tema, gaya, dan diksi",
      "Membandingkan karakteristik puisi antarangkatan",
      "Menciptakan puisi dengan gaya khas salah satu angkatan",
    ],
    materi: [
      {
        judul: "Periodisasi Puisi Indonesia",
        isi: [
          "Puisi Indonesia telah melalui perjalanan panjang sejak awal abad ke-20. Setiap periode memiliki ciri khas tersendiri, dipengaruhi oleh kondisi sosial, politik, dan budaya pada zamannya. Periodisasi ini dikenal sebagai 'Angkatan'.",
          "",
          "✓ Angkatan dalam puisi Indonesia:",
          "",
          "1. ANGKATAN PUJANGGA BARU (1930-an)",
          "  Dipelopori oleh Sutan Takdir Alisjahbana, Armijn Pane, dan Amir Hamzah. Puisi Pujangga Baru romantis, idealis, dan banyak menggunakan bahasa Melayu tinggi.",
          "",
          "2. ANGKATAN 45 (1945-1950-an)",
          "  Dipelopori Chairil Anwar, Asrul Sani, dan Rivai Apin. Puisi Angkatan 45 bersifat revolusioner, ekspresif, dan individualistis. Lahir dari semangat kemerdekaan.",
          "",
          "3. ANGKATAN 66 (1966-1970-an)",
          "  Taufiq Ismail, W.S. Rendra, dan Goenawan Mohamad. Puisi Angkatan 66 lebih realistik, protes sosial, dan politis — merespons situasi politik Indonesia.",
          "",
          "4. ANGKATAN 80-AN (1980-1990-an)",
          "  Sutardji Calzoum Bachri, Sapardi Djoko Damono, dan Afrizal Malna. Eksperimental, main-main dengan bahasa, dan lebih personal.",
          "",
          "5. ANGKATAN REFORMASI (2000-an)",
          "  Lebih bebas, beragam, dan banyak muncul di media sosial. Gaya bahasa lebih santai dan populer.",
          "",
          "[Ilustrasi: Garis waktu (timeline) horizontal dari tahun 1930 hingga 2020 dengan 5 titik utama. Setiap titik memiliki ikon khas: Pujangga Baru (bulu ayam), Angkatan 45 (bendera merah putih), Angkatan 66 (palu dan microphone), Angkatan 80-an (kubus dan segitiga abstrak), Reformasi (simbol @ dan wifi). Gaya ilustrasi timeline museum dengan warna-warna vintage.]",
        ],
        contoh: [
          "PERBANDINGAN PUISI ANTARANGKATAN:",
          "",
          "PUJANGGA BARU — 'Padamu Jua' (Amir Hamzah):",
          "\"Habis kikis / Segala cintaku hilang terbang / Pulang kembali aku padamu / Seperti dahulu\"",
          "Ciri: romantis, bahasa Melayu tinggi, religius.",
          "",
          "ANGKATAN 45 — 'Aku' (Chairil Anwar):",
          "\"Aku mau hidup seribu tahun lagi / Aku binatang jalang / Dari kumpulannya terbuang\"",
          "Ciri: ekspresif, individualistis, memberontak.",
          "",
          "ANGKATAN 66 — 'Sajak Kepada Kawan' (Taufiq Ismail):",
          "\"Engkau telah memilih jalan ini / Jalan yang penuh onak dan duri / Tetapi engkau tak pernah menyesal\"",
          "Ciri: semangat perjuangan, protes sosial.",
        ],
        catatan: "Periodisasi ini adalah alat bantu, bukan aturan kaku. Banyak penyair yang karyanya tidak bisa dimasukkan ke dalam satu angkatan saja. Jadikan periodisasi sebagai pintu masuk untuk menikmati puisi, bukan sebagai penjara.",
      },
      {
        judul: "Angkatan Pujangga Baru (1930-an)",
        isi: [
          "Pujangga Baru adalah angkatan pertama dalam kesusastraan Indonesia modern. Lahir dari majalah 'Pujangga Baru' yang didirikan pada tahun 1933.",
          "",
          "✓ Ciri-ciri Puisi Pujangga Baru:",
          "  ✓ Menggunakan bahasa Melayu tinggi (klasik)",
          "  ✓ Tema romantis, alam, cinta, dan religius",
          "  ✓ Bentuk puisi masih terikat (bait, rima, jumlah baris)",
          "  ✓ Idealistis dan cenderung indah-indah",
          "  ✓ Banyak menggunakan kata-kata seperti: 'jiwa', 'ratna', 'intan', 'duka', 'cinta'",
          "",
          "Tokoh Utama:",
          "- Amir Hamzah: 'Padamu Jua', 'Tuhan, Aku Cinta PadaMu' — puisi religius-romantis",
          "- Sutan Takdir Alisjahbana: puisi tentang kebangunan nasional",
          "- Armijn Pane: 'Jiwa Berdiri Di Pinggir Tubuh' — kontemplatif",
          "- Sanusi Pane: 'Pancaran Cinta' — filosofis",
          "",
          "[Ilustrasi: Sebuah ruang redaksi majalah zaman kolonial. Meja kayu dengan mesin ketik tua, tumpukan kertas, dan beberapa eksemplar majalah 'Pujangga Baru'. Di dinding ada foto para sastrawan. Jendela menghadap ke perkebunan. Gaya ilustrasi semi-realistis dengan warna sepia dan krem.]",
        ],
        contoh: [
          "KUTIPAN PUISI 'Tuhan, Aku Cinta PadaMu' — Amir Hamzah:",
          "",
          "\"Tuhan, aku cinta padaMu / Bukan karena surga-Mu / Dan bukan karena neraka-Mu / Tetapi karena cinta-Mu\"",
          "",
          "Analisis:",
          "- Tema: religius — cinta kepada Tuhan",
          "- Bahasa Melayu tinggi: 'padaMu', 'cinta-Mu' (menggunakan huruf kapital)",
          "- Bentuk terikat: 4 baris per bait, rima akhir a-a-a-a",
          "- Gaya: romantis-spiritual, sederhana namun dalam",
          "- Makna: cinta yang tulus kepada Tuhan tanpa pamrih",
        ],
      },
      {
        judul: "Angkatan 45 (1945-1950-an)",
        isi: [
          "Angkatan 45 lahir dari semangat revolusi kemerdekaan. Pelopornya adalah Chairil Anwar — 'Si Binatang Jalang' — yang karyanya menjadi ikon puisi Indonesia modern.",
          "",
          "✓ Ciri-ciri Puisi Angkatan 45:",
          "  ✓ Ekspresif, dinamis, dan penuh semangat",
          "  ✓ Individualistis — mengangkat 'aku' sebagai subjek",
          "  ✓ Berontak terhadap kemapanan dan tradisi",
          "  ✓ Bahasa sehari-hari (tidak lagi Melayu tinggi)",
          "  ✓ Bentuk bebas — tidak terikat rima dan jumlah baris",
          "  ✓ Tema: perjuangan, kematian, eksistensi, pemberontakan",
          "",
          "Tokoh Utama:",
          "- Chairil Anwar: 'Aku', 'Krawang-Bekasi', 'Diponegoro'",
          "- Asrul Sani: puisi filosofis-religius",
          "- Rivai Apin: puisi perjuangan",
          "- M. Akbar: puisi sosial",
          "",
          "[Ilustrasi: Latar belakang bendera merah putih berkibar. Di depannya, siluet seorang pemuda berdiri tegak dengan tangan mengepal ke atas. Di sekelilingnya, kata-kata 'Aku', 'Merdeka', 'Bangkit', 'Badai' melayang. Gaya ilustrasi poster propaganda dengan warna merah, putih, dan hitam.]",
        ],
        contoh: [
          "PUISI 'Aku' — Chairil Anwar:",
          "",
          "\"Kalau sampai waktuku / 'Ku mau tak seorang 'kan merayu / Tidak juga kau\"",
          "\"Aku mau hidup seribu tahun lagi\"",
          "",
          "Analisis:",
          "- Tema: eksistensi dan kemauan keras",
          "- Gaya: ekspresif, penuh energi, provokatif",
          "- Bahasa: sehari-hari ('ku mau', bukan 'aku mau' — singkatan tipis)",
          "- Bentuk: bebas, tidak berima teratur",
          "- Makna: keinginan untuk hidup abadi melalui karya — semangat pantang menyerah",
        ],
      },
      {
        judul: "Angkatan 66, 80-an, dan Reformasi",
        isi: [
          "Setelah Angkatan 45, puisi Indonesia terus berkembang dengan wajah yang semakin beragam.",
          "",
          "A. ANGKATAN 66 (1966-1970-an)",
          "  Lahir dari pergolakan politik G30S/PKI. Puisi bersifat protes, realistik, dan humanis. Tokoh: Taufiq Ismail, W.S. Rendra, Goenawan Mohamad, dan Sitor Situmorang.",
          "  Ciri: lugas, tajam, sering menyindir penguasa.",
          "  Contoh: 'Kekasihku' (W.S. Rendra) — puisi cinta yang kritis.",
          "",
          "B. ANGKATAN 80-AN (1980-1990-an)",
          "  Puisi eksperimental. Sutardji Calzoum Bachri memperkenalkan puisi mantra — mengutamakan bunyi daripada makna. Sapardi Djoko Damono populer dengan puisi liris sederhana seperti 'Hujan Bulan Juni'. Afrizal Malna dengan puisi bergaya surealis.",
          "  Ciri: bermain dengan bahasa, bentuk tidak konvensional, bebas.",
          "",
          "C. ANGKATAN REFORMASI (2000-an-sekarang)",
          "  Puisi semakin demokratis. Muncul platform digital: blog, media sosial, dan aplikasi puisi. Penyair seperti M. Aan Mansyur, Joko Pinurbo, dan F. Aziz Manna mempopulerkan puisi dengan bahasa sehari-hari yang dekat dengan kehidupan milenial.",
          "  Ciri: santai, populer, dekat dengan keseharian, mudah dipahami.",
          "",
          "[Ilustrasi: Kolase tiga panel. Panel kiri (Angkatan 66): seorang demonstran dengan poster dan pengeras suara. Panel tengah (Angkatan 80-an): seorang seniman dengan kuas melukis kata-kata abstrak di kanvas. Panel kanan (Reformasi): seorang remaja dengan smartphone menulis puisi di media sosial. Gaya ilustrasi kolase dengan warna masing-masing panel berbeda.]",
        ],
        contoh: [
          "CONTOH PUISI DARI SETIAP ANGKATAN:",
          "",
          "ANGKATAN 66 — 'Yang Kami Tahu' (Taufiq Ismail):",
          "\"Yang kami tahu / Negeri ini gemah ripah / Tapi yang kami lihat / Banyak petani kehilangan tanah\"",
          "Ciri: protes sosial, lugas, realistik.",
          "",
          "ANGKATAN 80-AN — 'Hujan Bulan Juni' (Sapardi Djoko Damono):",
          "\"Tak ada yang lebih tabah / Dari hujan bulan Juni / Dirahasiakannya rintik rindunya / Kepada pohon berbunga itu\"",
          "Ciri: liris, sederhana, penuh makna tersirat.",
          "",
          "REFORMASI — 'Sajak Cinta' (Joko Pinurbo):",
          "\"Aku mencintaimu dengan cara / meminjam kata-kata dari puisimu / lalu mengembalikannya dalam bentuk diam\"",
          "Ciri: santai, menggunakan diksi sehari-hari, permainan kata segar.",
        ],
      },
    ],
    rangkuman: [
      "[Ilustrasi: Perpustakaan sastra dengan rak buku berisi kumpulan puisi dari berbagai angkatan. Di atas rak terpajang nama angkatan: Pujangga Baru, Angkatan 45, Angkatan 66, Angkatan 80-an, Reformasi. Sebuah buku puisi terbuka dengan ilustrasi pena dan kertas. Gaya ilustrasi perpustakaan klasik dengan warna cokelat dan emas.]",
      "Puisi Indonesia dibagi dalam periodisasi angkatan: Pujangga Baru, 45, 66, 80-an, dan Reformasi.",
      "Pujangga Baru (1930-an): romantis, bahasa Melayu tinggi, bentuk terikat.",
      "Angkatan 45: ekspresif, individualistis, revolusioner — Chairil Anwar sebagai tokoh sentral.",
      "Angkatan 66: protes sosial-politik. Angkatan 80-an: eksperimental. Reformasi: demokratis dan digital.",
    ],
  },
  latihan: makeSoal([
    ["Majalah yang menjadi pelopor lahirnya Angkatan Pujangga Baru adalah...", ["Horison", "Pujangga Baru", "Sastra", "Kompas"], 1, "Majalah 'Pujangga Baru' didirikan tahun 1933 dan menjadi wadah sastrawan angkatan tersebut."],
    ["Tokoh sentral Angkatan 45 yang dijuluki 'Si Binatang Jalang' adalah...", ["Amir Hamzah", "Chairil Anwar", "Taufiq Ismail", "W.S. Rendra"], 1, "Chairil Anwar dijuluki 'Si Binatang Jalang' dari puisinya yang berjudul 'Aku'."],
    ["Ciri khas puisi Angkatan Pujangga Baru adalah...", ["Ekspresif dan memberontak", "Romantis dan menggunakan bahasa Melayu tinggi", "Protes sosial dan politis", "Eksperimental dan surealis"], 1, "Pujangga Baru romantis, idealistis, dan menggunakan bahasa Melayu tinggi."],
    ["Puisi 'Hujan Bulan Juni' adalah karya...", ["Chairil Anwar", "Sapardi Djoko Damono", "Taufiq Ismail", "W.S. Rendra"], 1, "'Hujan Bulan Juni' adalah puisi liris karya Sapardi Djoko Damono."],
    ["Angkatan yang puisinya bersifat protes sosial dan merespons situasi politik adalah...", ["Angkatan 45", "Angkatan 66", "Pujangga Baru", "Angkatan 80-an"], 1, "Angkatan 66 lahir dari pergolakan politik dan bersifat protes sosial."],
    ["Puisi mantra yang mengutamakan bunyi daripada makna diperkenalkan oleh...", ["Afrizal Malna", "Sutardji Calzoum Bachri", "Goenawan Mohamad", "Joko Pinurbo"], 1, "Sutardji Calzoum Bachri memperkenalkan puisi mantra yang mengutamakan bunyi."],
    ["'Aku mau hidup seribu tahun lagi' adalah kutipan puisi dari...", ["Padamu Jua", "Aku", "Krawang-Bekasi", "Diponegoro"], 1, "Kutipan 'Aku mau hidup seribu tahun lagi' berasal dari puisi 'Aku'."],
    ["Yang membedakan puisi Angkatan 45 dengan Pujangga Baru adalah...", ["Puisi 45 masih terikat rima", "Puisi 45 menggunakan bahasa sehari-hari", "Puisi 45 romantis", "Puisi 45 bersifat religius"], 1, "Angkatan 45 menggunakan bahasa sehari-hari, tidak lagi Melayu tinggi."],
    ["Tema yang dominan dalam puisi Angkatan Reformasi adalah...", ["Perjuangan kemerdekaan", "Keseharian dan kehidupan modern", "Religius dan mistis", "Feodal dan istana sentris"], 1, "Puisi Reformasi dekat dengan kehidupan sehari-hari dan modern."],
    ["Tokoh yang termasuk Angkatan 66 adalah...", ["Amir Hamzah", "Taufiq Ismail", "Chairil Anwar", "Sutan Takdir Alisjahbana"], 1, "Taufiq Ismail adalah tokoh Angkatan 66."],
  ]),
  praktik: {
    petunjuk: "Buatlah sebuah puisi yang terinspirasi oleh gaya salah satu angkatan yang telah dipelajari (Pujangga Baru, Angkatan 45, 66, 80-an, atau Reformasi). Tentukan angkatan yang kamu pilih, lalu ciptakan puisi minimal 2 bait (8 baris). Sertakan penjelasan singkat tentang ciri angkatan yang kamu gunakan dalam puisimu.",
    tips: [
      "Baca 2-3 puisi dari angkatan yang kamu pilih untuk menangkap ciri khasnya",
      "Untuk gaya Pujangga Baru: gunakan diksi yang indah dan rima yang teratur",
      "Untuk gaya Angkatan 45: gunakan bahasa yang ekspresif dan penuh semangat",
      "Untuk gaya Angkatan 66: angkat isu sosial yang dekat denganmu",
      "Untuk gaya 80-an: main-main dengan struktur dan bunyi kata",
      "Untuk gaya Reformasi: gunakan bahasa sehari-hari dan tema kekinian",
    ],
    contoh: "Puisi 2 bait (8 baris) dengan penjelasan gaya angkatan yang digunakan.",
  },
  kuis: makeSoal([
    ["Puisi 'Padamu Jua' adalah karya...", ["Chairil Anwar", "Amir Hamzah", "Taufiq Ismail", "W.S. Rendra"], 1, "Puisi 'Padamu Jua' adalah karya Amir Hamzah (Pujangga Baru)."],
    ["Angkatan 45 lahir dari semangat...", ["Reformasi 1998", "Revolusi kemerdekaan 1945", "Kebangkitan nasional 1908", "Sumpah Pemuda 1928"], 1, "Angkatan 45 lahir dari semangat revolusi kemerdekaan."],
    ["Ciri puisi Angkatan 80-an yang paling menonjol adalah...", ["Romantis", "Eksperimental dan bermain bahasa", "Protes sosial", "Religius"], 1, "Angkatan 80-an dikenal dengan eksperimen bahasa dan bentuk."],
    ["Salah satu tokoh Angkatan Reformasi dalam puisi adalah...", ["Chairil Anwar", "Joko Pinurbo", "Amir Hamzah", "Sanusi Pane"], 1, "Joko Pinurbo adalah penyair Angkatan Reformasi."],
    ["Puisi Angkatan 45 umumnya bertema...", ["Cinta dan alam", "Eksistensi dan perjuangan", "Teknologi dan internet", "Feodal dan kerajaan"], 1, "Eksistensi, perjuangan, dan pemberontakan adalah tema Angkatan 45."],
    ["Bahasa yang digunakan dalam puisi Pujangga Baru adalah...", ["Bahasa sehari-hari", "Bahasa Melayu tinggi", "Bahasa daerah", "Bahasa asing"], 1, "Pujangga Baru menggunakan bahasa Melayu tinggi."],
    ["Puisi 'Krawang-Bekasi' membahas tentang...", ["Cinta", "Perjuangan para pahlawan", "Alam", "Teknologi"], 1, "'Krawang-Bekasi' adalah puisi tentang perjuangan pahlawan karya Chairil Anwar."],
    ["Angkatan yang muncul pada era 2000-an dengan platform digital disebut...", ["Angkatan 66", "Angkatan Reformasi", "Angkatan 80-an", "Angkatan 45"], 1, "Angkatan Reformasi muncul tahun 2000-an dengan dukungan platform digital."],
    ["Sutan Takdir Alisjahbana termasuk dalam angkatan...", ["Angkatan 45", "Pujangga Baru", "Angkatan 66", "Angkatan 80-an"], 1, "Sutan Takdir Alisjahbana adalah tokoh Pujangga Baru."],
    ["Puisi yang mementingkan bunyi dan suku kata disebut puisi...", ["Mantra", "Liris", "Naratif", "Epik"], 0, "Puisi mantra mengutamakan bunyi daripada makna."],
  ]),
}

export default konten
