import type { Konten } from "../types"
import { makeSoal } from "../types"

const konten: Konten = {
  belajar: {
    tujuan: [
      "Memahami pengertian, jenis, dan ciri-ciri teks drama",
      "Mengidentifikasi unsur intrinsik dan ekstrinsik drama",
      "Menganalisis dialog, konflik, dan karakter dalam naskah drama",
      "Menyusun naskah drama satu babak dengan struktur yang tepat",
      "Mementaskan drama berdasarkan naskah yang telah disusun",
    ],
    materi: [
      {
        judul: "Mengenal Teks Drama",
        isi: [
          "Drama adalah karya sastra yang dipentaskan. Drama menggabungkan seni sastra (naskah) dan seni pertunjukan (acting, tata panggung, tata cahaya, musik). Di kelas XI, kita akan belajar menulis naskah drama dan memahami teknik pementasannya.",
          "",
          "✓ Ciri-ciri drama:",
          "  ✓ Berupa dialog — bukan narasi",
          "  ✓ Dilengkapi petunjuk teknis (stage direction / kramagung)",
          "  ✓ Memiliki konflik sebagai inti cerita",
          "  ✓ Terdiri dari babak dan adegan",
          "  ✓ Dipentaskan atau minimal bisa dibayangkan pementasannya",
          "",
          "Jenis drama berdasarkan bentuk:",
          "  - Drama tragedi: cerita sedih, berakhir malapetaka",
          "  - Drama komedi: cerita lucu, menghibur",
          "  - Drama tragedi-komedi: gabungan sedih dan lucu",
          "  - Melodrama: penuh emosi dan dramatisasi berlebihan",
          "  - Drama absurd: tidak logis, penuh simbolisme",
          "",
          "[Ilustrasi: Panggung teater dengan lampu sorot menyinari dua aktor yang sedang beradegan. Latar belakang berupa lukisan pemandangan kota. Di sisi panggung ada properti meja, kursi, dan lampu jalan. Kursi penonton terlihat gelap. Gaya ilustrasi teater realis dengan warna merah marun dan emas.]",
        ],
        contoh: [
          "CONTOH DIALOG DRAMA (petikan naskah 'Matinya Seorang Pahlawan'):",
          "",
          "(Panggung menggambarkan ruang tamu sederhana. MALAM, 25 tahun, duduk termenung. PAK TUA, 60 tahun, masuk dengan langkah gontai.)",
          "",
          "PAK TUA: \"Kau masih di sini? Kupikir kau sudah pergi.\"",
          "MALAM: \"Ke mana saya harus pergi, Pak? Di luar hanya ada kegelapan.\"",
          "PAK TUA: \"Kegelapan? Di luar ada jalan. Selalu ada jalan.\"",
          "MALAM: \"Tapi jalan itu tidak menuju ke mana-mana.\"",
          "PAK TUA: \"Karena kau tidak punya tujuan. Seperti dulu aku.\"",
          "",
          "Analisis:",
          "- Dialog berbentuk percakapan, bukan narasi",
          "- Ada stage direction dalam tanda kurung",
          "- Ada konflik batin (Malam yang merasa putus asa)",
          "- Karakter tergambar dari dialog (Pak Tua bijak, Malam pesimis)",
        ],
        catatan: "Naskah drama berbeda dengan cerpen. Dalam drama, semua cerita harus disampaikan melalui dialog dan tindakan tokoh — tidak ada 'kata pengarang' yang menjelaskan perasaan tokoh secara langsung.",
      },
      {
        judul: "Unsur Intrinsik Drama",
        isi: [
          "Unsur intrinsik drama adalah elemen-elemen yang membangun drama dari dalam. Pahami keenam unsur ini!",
          "",
          "1. TEMA — Gagasan pokok yang mendasari cerita drama. Tema bisa berupa cinta, pengorbanan, keadilan, ambisi, atau kritik sosial.",
          "",
          "2. ALUR (PLOT) — Rangkaian peristiwa dalam drama. Struktur alur drama: eksposisi (pengenalan) → konflik (pertikaian dimulai) → komplikasi (konflik berkembang) → klimaks (puncak konflik) → resolusi (penyelesaian).",
          "",
          "3. TOKOH DAN KARAKTER — Drama memiliki tokoh protagonist (tokoh baik), antagonis (tokoh jahat), dan tritagonis (penengah). Karakter digambarkan melalui dialog, tindakan, dan penampilan fisik.",
          "",
          "4. DIALOG — Jantung drama. Dialog harus alami, sesuai karakter, dan mendorong alur cerita.",
          "",
          "5. LATA — Tempat, waktu, dan suasana. Dalam drama, latar diwujudkan secara fisik di panggung.",
          "",
          "6. AMANAT — Pesan moral yang ingin disampaikan penulis kepada penonton.",
          "",
          "[Ilustrasi: Sebuah panggung mini dengan 6 area yang masing-masing mewakili satu unsur. Area 1: tulisan 'TEMA' dengan ikon lampu ide. Area 2: panah melingkar 'ALUR'. Area 3: tiga siluet 'TOKOH'. Area 4: gelembung ucapan 'DIALOG'. Area 5: latar belakang kota 'LATAR'. Area 6: hati 'AMANAT'. Gaya ilustrasi panggung boneka dengan warna cerah.]",
        ],
        contoh: [
          "ANALISIS UNSUR INTRINSIK DRAMA 'Bunga Penutup Abad' — Wisran Hadi:",
          "",
          "TEMA: Perubahan sosial dan konflik generasi di Minangkabau.",
          "",
          "ALUR:",
          "- Eksposisi: pengenalan keluarga adat di Sumatera Barat",
          "- Konflik: pertentangan antara tradisi dan modernitas",
          "- Komplikasi: konflik semakin memanas, tokoh terpecah",
          "- Klimaks: peristiwa penghancuran rumah gadang",
          "- Resolusi: kehancuran tradisi, tokoh utama pergi meninggalkan kampung",
          "",
          "TOKOH:",
          "- Malin: protagonist, generasi muda yang ingin perubahan",
          "- Inyiak: antagonis, tetua adat yang kaku memegang tradisi",
          "- Siti: tritagonis, penengah antara Malin dan Inyiak",
          "",
          "DIALOG: Menggunakan bahasa Minang campur Indonesia, mencerminkan konflik budaya.",
          "",
          "LATAR: Rumah gadang, surau, lapangan — Sumatera Barat awal 2000-an.",
          "",
          "AMANAT: Tradisi dan modernitas harus berjalan beriringan, tidak perlu saling memusnahkan.",
        ],
      },
      {
        judul: "Kaidah Kebahasaan Teks Drama",
        isi: [
          "Teks drama memiliki kaidah bahasa yang khas dan berbeda dari teks lainnya.",
          "",
          "1. DIALOG YANG KOMUNIKATIF",
          "  Bahasa dalam drama harus alami — seperti percakapan sehari-hari. Namun, bukan berarti sembarangan — setiap kata dipilih untuk mencerminkan karakter dan mendorong plot.",
          "",
          "2. KALIMAT LANGSUNG (TANDA PETIK)",
          "  Seluruh dialog ditulis dalam kalimat langsung dan diapit tanda petik dua atau tanpa petik (tergantung konvensi penulisan naskah).",
          "",
          "3. STAGE DIRECTION / KRAMAGUNG",
          "  Petunjuk teknis yang ditulis dalam tanda kurung. Berisi deskripsi tentang gerak, ekspresi, intonasi, tata panggung, dan properti.",
          "",
          "4. BAHASA YANG MENCERMINKAN KARAKTER",
          "  Tokoh yang berbeda harus memiliki cara bicara yang berbeda. Tokoh terpelajar bicara formal, tokoh preman bicara kasar, tokoh anak kecil bicara lugu.",
          "",
          "5. KONJUNGSI TEMPORAL DAN KAUSALITAS",
          "  Kata seperti 'sebelum', 'setelah', 'kemudian', 'karena', 'sehingga' membantu membangun urutan dan logika cerita.",
          "",
          "[Ilustrasi: Naskah drama terbuka di atas meja sutradara. Halaman naskah penuh dengan dialog dan catatan tangan merah (stage direction). Di samping naskah ada pensil, penghapus, dan lampu meja. Background ruang latihan teater dengan kursi-kursi kosong. Gaya ilustrasi ruang rehearsal dengan warna hangat.]",
        ],
        contoh: [
          "CONTOH PENULISAN NASKAH DRAMA:",
          "",
          "Judul: 'Titip Rindu'",
          "Karya: Siswa Kelas XI",
          "",
          "(Pagi hari di stasiun kereta. ANI, 17 tahun, duduk di bangku sambil memegang tiket. Ia tampak gelisah. WINDA, sahabatnya, datang tergopoh-gopoh.)",
          "",
          "WINDA: (berlari, napas tersengal) \"Ani! Syukurlah aku masih sempat.\"",
          "ANI: (tersenyum tipis) \"Kupikir kau tidak akan datang.\"",
          "WINDA: \"Masa iya? Sahabat sepertimu akan kutinggalkan?\"",
          "ANI: \"Maafkan aku, Win. Aku harus pergi.\"",
          "WINDA: (matanya berkaca-kaca) \"Aku tahu. Tapi janji ya... kau akan kembali.\"",
          "ANI: (mengangguk, suara bergetar) \"Aku janji.\"",
          "",
          "(Suara peluit kereta berbunyi. Ani berdiri, memeluk Winda erat. Keduanya menangis. Ani lalu berjalan menuju peron dan naik ke kereta. Winda melambaikan tangan.)",
        ],
      },
      {
        judul: "Menulis Naskah Drama Satu Babak",
        isi: [
          "Naskah drama satu babak adalah drama pendek yang hanya terdiri dari satu babak (tidak berganti set panggung besar). Ini adalah langkah awal yang bagus untuk belajar menulis drama.",
          "",
          "PENTING: Drama satu babak harus fokus pada satu konflik utama. Tidak ada waktu untuk subplot yang rumit!",
          "",
          "LANGKAH MENULIS NASKAH DRAMA SATU BABAK:",
          "",
          "1. Tentukan tema dan konflik — Apa yang akan diperjuangkan tokohmu?",
          "2. Ciptakan tokoh — Beri nama, usia, karakter, dan cara bicara yang khas",
          "3. Tentukan latar — Tempat, waktu, dan suasana panggung",
          "4. Buat sinopsis — Cerita singkat dari awal hingga akhir",
          "5. Tulis dialog — Mulai dengan perkenalan, bangun konflik, capai klimaks, selesaikan",
          "6. Tambahkan stage direction — Gerak, ekspresi, intonasi, properti",
          "7. Baca ulang dan edit — Baca keras-keras untuk memastikan dialog terdengar alami",
          "",
          "✓ Tips dialog yang baik:",
          "  ✓ Setiap dialog harus memajukan cerita — tidak boleh sekadar basa-basi",
          "  ✓ Gunakan subteks — apa yang tidak diucapkan sama pentingnya dengan apa yang diucapkan",
          "  ✓ Jangan menulis dialog yang terlalu panjang — drama adalah seni efisiensi",
          "  ✓ Baca dialog keras-keras — jika terdengar janggal, tulis ulang",
          "",
          "[Ilustrasi: Sebuah meja kerja dengan laptop yang menampilkan dokumen naskah drama. Di layar tertulis 'BABAK 1' dengan beberapa baris dialog. Di meja ada buku 'Panduan Menulis Drama', sticky notes berisi ide cerita, dan segelas air. Tangan penulis memegang pena sambil berpikir. Gaya ilustrasi penulis di ruang kerja kreatif dengan warna biru dan hijau.]",
        ],
        contoh: [
          "SINOPSIS DRAMA SATU BABAK — 'Kursi Kosong':",
          "",
          "TEMA: Penyesalan dan pengampunan dalam keluarga.",
          "",
          "TOKOH:",
          "- RINA (18 tahun): anak yang durhaka, pergi dari rumah",
          "- BU HARTATI (45 tahun): ibu Rina yang sabar",
          "- PAK ADI (50 tahun): ayah Rina yang tegas",
          "",
          "LATAR: Ruang tamu rumah sederhana, malam hari.",
          "",
          "SINOPSIS:",
          "Rina pulang ke rumah setelah dua tahun pergi tanpa kabar. Ia menemukan kursi makannya yang dulu selalu ia tempati kini kosong. Bu Hartati dan Pak Adi menyambutnya — bukan dengan kemarahan, tetapi dengan kehangatan yang justru membuat Rina semakin merasa bersalah. Klimaks terjadi ketika Rina mengaku bahwa ia pulang karena gagal di kota. Orang tuanya justru bersyukur — karena kegagalan adalah awal dari perbaikan. Drama ini mengajarkan bahwa rumah adalah tempat pulang, apa pun keadaannya.",
        ],
      },
    ],
    rangkuman: [
      "[Ilustrasi: Panggung teater megah dengan tirai merah terbuka. Di atas panggung ada set ruang keluarga lengkap dengan sofa, meja, dan lampu. Tiga aktor sedang beradegan. Di langit-langit panggung, kata-kata 'TEMA', 'ALUR', 'TOKOH', 'DIALOG', 'AMANAT' bersinar seperti bintang. Gaya ilustrasi teater klasik dengan warna merah, emas, dan biru.]",
      "Drama adalah karya sastra yang dipentaskan, menggabungkan seni sastra dan pertunjukan.",
      "Unsur intrinsik drama: tema, alur, tokoh/karakter, dialog, latar, amanat.",
      "Kaidah kebahasaan: dialog komunikatif, kalimat langsung, stage direction, bahasa sesuai karakter.",
      "Drama satu babak fokus pada satu konflik — langkah awal belajar menulis naskah.",
    ],
  },
  latihan: makeSoal([
    ["Teks drama berbeda dengan cerpen karena...", ["Menggunakan narasi panjang", "Berupa dialog dan stage direction", "Tidak memiliki alur", "Tidak memiliki tokoh"], 1, "Drama mengandalkan dialog dan petunjuk teknis, bukan narasi."],
    ["Bagian yang menjelaskan gerak, ekspresi, dan tata panggung dalam naskah drama disebut...", ["Monolog", "Stage direction (kramagung)", "Dialog", "Episode"], 1, "Stage direction adalah petunjuk teknis dalam tanda kurung."],
    ["Struktur alur drama yang benar adalah...", ["Orientasi-komplikasi-klimaks-resolusi", "Eksposisi-konflik-komplikasi-klimaks-resolusi", "Abstrak-isi-penutup", "Tesis-argumentasi-penegasan"], 1, "Alur drama: eksposisi, konflik, komplikasi, klimaks, resolusi."],
    ["Tokoh yang menjadi penengah antara protagonist dan antagonis disebut...", ["Protagonis", "Tritagonis", "Antagonis", "Figuran"], 1, "Tritagonis adalah tokoh penengah."],
    ["'Mengapa kau diam saja? Aku sudah menunggumu sejak pagi!' Kalimat ini termasuk...", ["Monolog", "Dialog", "Narasi", "Stage direction"], 1, "Kalimat tersebut adalah dialog antara dua tokoh."],
    ["Fungsi stage direction dalam naskah drama adalah...", ["Memperindah tulisan", "Memberi petunjuk teknis pementasan", "Menggantikan dialog", "Menambah jumlah halaman"], 1, "Stage direction memberi petunjuk tentang gerak, ekspresi, dan tata panggung."],
    ["Drama yang berakhir dengan malapetaka disebut...", ["Komedi", "Tragedi", "Absurd", "Melodrama"], 1, "Tragedi adalah drama sedih yang berakhir dengan malapetaka."],
    ["Hal terpenting dalam menulis dialog drama adalah...", ["Panjang dan indah", "Alami dan mencerminkan karakter", "Penuh kata sulit", "Berima indah"], 1, "Dialog harus alami dan sesuai karakter tokoh."],
    ["'Pagi hari di ruang tamu. SITI duduk sambil merajut.' Kalimat ini termasuk...", ["Dialog", "Stage direction", "Monolog", "Narasi"], 1, "Stage direction menggambarkan latar dan tindakan tokoh."],
    ["Drama satu babak berarti...", ["Drama yang hanya terdiri dari satu babak", "Drama yang hanya satu halaman", "Drama tanpa dialog", "Drama yang tidak dipentaskan"], 0, "Drama satu babak hanya memiliki satu babak (tidak berganti set panggung besar)."],
  ]),
  praktik: {
    petunjuk: "Buatlah naskah drama satu babak dengan tema bebas. Ketentuan: (1) Panjang naskah 3-5 halaman, (2) Minimal 3 tokoh (protagonis, antagonis, tritagonis), (3) Struktur alur lengkap: eksposisi, konflik, komplikasi, klimaks, resolusi, (4) Sertakan stage direction yang jelas, (5) Dialog alami dan mencerminkan karakter masing-masing tokoh. Tema yang bisa dipilih: persahabatan, keluarga, perjuangan, atau kritik sosial.",
    tips: [
      "Tentukan konflik utama sebelum menulis — semua dialog harus mengarah ke konflik itu",
      "Beri setiap tokoh 'cara bicara' yang berbeda — mudah dikenali tanpa membaca nama tokoh",
      "Gunakan stage direction secukupnya — jangan terlalu banyak sehingga mengganggu dialog",
      "Baca dialog keras-keras untuk menguji kealamiannya",
      "Minta teman membaca salah satu peran untuk mendengar bagaimana dialogmu terdengar",
    ],
    contoh: "Naskah drama satu babak 3-5 halaman dengan struktur lengkap dan stage direction.",
  },
  kuis: makeSoal([
    ["Jenis drama yang menggabungkan unsur lucu dan sedih adalah...", ["Tragedi", "Tragedi-komedi", "Melodrama", "Absurd"], 1, "Tragedi-komedi menggabungan unsur sedih dan lucu."],
    ["'Aku tidak akan pernah memaafkanmu!' Ujaran ini termasuk...", ["Monolog", "Dialog", "Stage direction", "Narasi"], 1, "Ujaran tersebut adalah bagian dari dialog."],
    ["Yang BUKAN termasuk unsur intrinsik drama adalah...", ["Tema", "Biografi penulis", "Alur", "Dialog"], 1, "Biografi penulis adalah unsur ekstrinsik."],
    ["Fungsi eksposisi dalam alur drama adalah...", ["Puncak konflik", "Pengenalan tokoh dan latar", "Penyelesaian konflik", "Pengembangan konflik"], 1, "Eksposisi adalah bagian pengenalan."],
    ["Tokoh antagonis dalam drama berperan sebagai...", ["Pendukung tokoh utama", "Lawan/penentang tokoh utama", "Penengah konflik", "Tokoh netral"], 1, "Antagonis adalah lawan dari protagonis."],
    ["'Bunyi telepon berdering. Rina berlari ke meja dan mengangkat gagang telepon.' Ini adalah...", ["Dialog", "Stage direction", "Monolog", "Episode"], 1, "Kalimat tersebut adalah stage direction yang menggambarkan aksi."],
    ["Drama absurd memiliki ciri...", ["Cerita logis", "Tidak logis dan penuh simbolisme", "Selalu berakhir bahagia", "Dialog sangat panjang"], 1, "Drama absurd tidak logis dan penuh simbol."],
    ["Salah satu ciri dialog yang baik dalam drama adalah...", ["Setiap dialog memajukan cerita", "Dialog sepanjang mungkin", "Menggunakan kata-kata sulit", "Tidak ada subteks"], 0, "Dialog yang baik harus memajukan cerita."],
    ["Istilah lain untuk stage direction dalam drama adalah...", ["Kramagung", "Monolog", "Babak", "Adegan"], 0, "Kramagung adalah istilah lain untuk stage direction."],
    ["Resolusi dalam alur drama berisi...", ["Puncak ketegangan", "Penyelesaian konflik", "Pengenalan tokoh", "Perkenalan konflik"], 1, "Resolusi adalah bagian penyelesaian konflik."],
  ]),
}

export default konten
