import type { Konten } from "../types"
import { makeSoal } from "../types"

const konten: Konten = {
  belajar: {
    tujuan: [
      "Memahami pengertian, tujuan, dan jenis resensi karya sastra",
      "Mengidentifikasi struktur resensi yang sistematis dan objektif",
      "Menganalisis kaidah kebahasaan dalam teks resensi tingkat lanjut",
      "Menyusun resensi buku fiksi atau nonfiksi secara kritis dan mendalam",
      "Menyunting resensi berdasarkan kaidah penulisan dan etika akademik",
    ],
    materi: [
      {
        judul: "Mengenal Resensi Tingkat Lanjut",
        isi: [
          "Pernahkah kamu membaca review buku di Goodreads atau ulasan film di Instagram? Di kelas XI, kamu akan belajar menulis resensi yang lebih mendalam — bukan sekadar 'suka atau tidak suka', tetapi analisis kritis yang terstruktur.",
          "",
          "Resensi adalah tulisan yang mengupas isi, kelebihan, dan kekurangan suatu karya. Di tingkat lanjut, resensi tidak hanya menilai — tetapi juga menganalisis konteks, membandingkan dengan karya lain, dan memberikan perspektif akademik.",
          "",
          "✓ Ciri-ciri resensi tingkat lanjut:",
          "  ✓ Analisis mendalam tentang struktur dan gaya penulisan karya",
          "  ✓ Perbandingan dengan karya lain atau teori tertentu",
          "  ✓ Konteks sosial, budaya, atau historis yang memengaruhi karya",
          "  ✓ Penilaian yang seimbang — objektif, bukan subjektif",
          "  ✓ Dilengkapi dengan argumen yang dapat dipertanggungjawabkan",
          "",
          "[Ilustrasi: Sebuah meja dengan buku terbuka, laptop yang menampilkan halaman blog resensi, dan secangkir teh. Di atas meja ada kertas coretan dengan kata 'IDENTITAS', 'SINOPSIS', 'ANALISIS', 'KELEBIHAN', 'KEKURANGAN'. Gaya ilustrasi meja kerja penulis dengan warna cokelat hangat dan hijau.]",
        ],
        contoh: [
          "CONTOH PERBANDINGAN RESENSI DASAR VS LANJUTAN:",
          "",
          "RESENSI DASAR (kelas X):",
          "'Buku ini bagus. Ceritanya menarik. Bahasanya mudah dipahami. Saya suka tokoh utamanya. Recommended!'",
          "→ Subjektif, tanpa analisis, tanpa bukti.",
          "",
          "RESENSI LANJUTAN (kelas XI):",
          "'Novel ini menggunakan teknik alur maju-mundur (flashback) yang efektif untuk membangun misteri. Penggambaran latar tahun 1965 sangat detail — penulis jelas melakukan riset sejarah. Namun, beberapa dialog terasa kaku dan tidak natural, terutama pada tokoh muda. Dibandingkan dengan karya sebelumnya, novel ini menunjukkan peningkatan dalam pengelolaan konflik, tetapi masih lemah dalam pengembangan karakter sekunder.'",
          "→ Objektif, analisis teknis, perbandingan, bukti konkret.",
        ],
        catatan: "Resensi yang baik bukan sekadar pujian atau kritik. Ia adalah analisis yang membantu pembaca memutuskan apakah suatu karya layak dibaca atau ditonton — dan mengapa.",
      },
      {
        judul: "Struktur Resensi yang Sistematis",
        isi: [
          "Resensi yang baik harus ditulis secara sistematis agar mudah diikuti pembaca.",
          "",
          "1. JUDUL RESENSI",
          "  Judul harus menarik dan mencerminkan isi resensi. Bisa berupa pernyataan, pertanyaan, atau permainan kata yang relevan dengan karya.",
          "",
          "2. IDENTITAS KARYA",
          "  Berisi informasi lengkap tentang karya: judul, penulis, penerbit, tahun terbit, tebal halaman, ISBN, dan harga (untuk buku). Untuk film: sutradara, produser, durasi, rumah produksi.",
          "",
          "3. SINOPSIS / IKHTISAR",
          "  Gambaran singkat isi karya tanpa spoiler berlebihan. Sinopsis harus membuat pembaca penasaran, bukan menceritakan seluruh jalan cerita.",
          "",
          "4. ANALISIS DAN PENILAIAN",
          "  Bagian inti resensi. Analisis dilakukan dengan melihat: kelebihan (kekuatan) dan kekurangan (kelemahan). Setiap penilaian harus disertai bukti dan argumen.",
          "",
          "5. SIMPULAN DAN REKOMENDASI",
          "  Kesimpulan akhir dan rekomendasi: apakah karya ini layak dibaca? Untuk siapa karya ini cocok?",
          "",
          "[Ilustrasi: Diagram alur struktur resensi dengan 5 kotak berwarna berbeda. Kotak 1 JUDUL (merah), Kotak 2 IDENTITAS (biru), Kotak 3 SINOPSIS (hijau), Kotak 4 ANALISIS (kuning), Kotak 5 SIMPULAN (ungu). Setiap kotak terhubung dengan panah. Gaya ilustrasi flowchart modern dengan warna-warna cerah.]",
        ],
        contoh: [
          "CONTOH STRUKTUR RESENSI BUKU:",
          "",
          "JUDUL: 'Menyelami Lautan Rasa: Resensi Novel Laut Bercerita'",
          "",
          "IDENTITAS:",
          "Judul: Laut Bercerita | Penulis: Leila S. Chudori",
          "Penerbit: Kepustakaan Populer Gramedia (KPG) | Tahun: 2017",
          "Tebal: 394 halaman | ISBN: 978-602-424-696-5",
          "",
          "SINOPSIS:",
          "Novel ini mengisahkan perjalanan sekelompok aktivis mahasiswa di era Orde Baru. Tokoh utama Biru Laut, seorang aktivis yang diculik dan menghilang, diceritakan melalui perspektif sahabat dan keluarganya.",
          "",
          "ANALISIS:",
          "KELEBIHAN: Latar sejarah yang detail, narasi multi-perspektif yang kuat, karakter yang hidup.",
          "KEKURANGAN: Beberapa bagian terasa lambat, alur di pertengahan agak melambat.",
          "",
          "SIMPULAN:",
          "Novel ini wajib dibaca bagi yang tertarik sejarah Indonesia. Rating: 4.5/5.",
        ],
      },
      {
        judul: "Kaidah Kebahasaan Resensi",
        isi: [
          "Teks resensi memiliki ciri kebahasaan yang khas, berbeda dari teks lainnya.",
          "",
          "1. MENGGUNAKAN KATA SIFAT OPINI",
          "  Kata sifat yang menunjukkan penilaian: 'menarik', 'mendalam', 'kuat', 'lemah', 'konsisten', 'rumit'. Namun, setiap opini harus didukung bukti.",
          "",
          "2. MENGGUNAKAN ISTILAS SASTRA / TEKNIS",
          "  Istilah seperti: 'alur', 'penokohan', 'latar', 'tema', 'gaya bahasa', 'sudut pandang', 'konflik', 'klimaks'. Gunakan istilah dengan tepat.",
          "",
          "3. MENGGUNAKAN KALIMAT KOMPLEKS",
          "  Resensi sering menggunakan kalimat majemuk setara dan bertingkat untuk menyampaikan analisis yang bernuansa.",
          "",
          "4. MENGGUNAKAN KATA KERJA MENTAL",
          "  Kata kerja yang berkaitan dengan aktivitas mental: 'menurut', 'menggambarkan', 'menunjukkan', 'menyiratkan', 'mencerminkan'.",
          "",
          "5. MENGGUNAKAN PEMBANDINGAN",
          "  Resensi sering membandingkan karya dengan karya lain — menggunakan kata: 'dibandingkan', 'seperti', 'lebih... daripada', 'sama... dengan'.",
          "",
          "[Ilustrasi: Sebuah buku kamus terbuka dengan istilah-istilah sastra yang disorot. Di sekelilingnya ada sticky notes dengan contoh kata: 'menarik (kata sifat opini)', 'alur (istilah sastra)', 'menunjukkan (kata kerja mental)', 'dibandingkan (pembandingan)'. Gaya ilustrasi kamus sastra dengan warna krem dan biru.]",
        ],
        contoh: [
          "Analisis kebahasaan dalam kalimat resensi:",
          "",
          "'Novel ini menggunakan teknik alur mundur yang efektif untuk membangun ketegangan.'",
          "- 'alur mundur' → istilah sastra",
          "- 'efektif' → kata sifat opini + bukti (membangun ketegangan)",
          "",
          "'Penggambaran tokoh utama sangat mendalam — pembaca bisa merasakan pergulatan batinnya.'",
          "- 'mendalam' → kata sifat opini",
          "- 'penggambaran' → nominalisasi",
          "- 'merasakan' → kata kerja mental",
          "",
          "'Dibandingkan dengan novel pertamanya, karya ini menunjukkan peningkatan signifikan dalam pengelolaan konflik.'",
          "- 'dibandingkan' → pembandingan",
          "- 'menunjukkan' → kata kerja mental",
          "- 'signifikan' → kata sifat opini",
        ],
      },
      {
        judul: "Menulis Resensi yang Kritis",
        isi: [
          "Menulis resensi yang kritis dan berbobot bukanlah hal yang sulit jika kamu mengikuti langkah-langkah berikut!",
          "",
          "PENTING: Resensi bukan ringkasan. Jika resensimu hanya berisi sinopsis, itu bukan resensi — itu laporan buku! Resensi harus mengandung penilaian dan analisis.",
          "",
          "LANGKAH MENULIS RESENSI:",
          "",
          "1. Baca atau tonton karya secara menyeluruh",
          "  Jangan meresensi setengah jalan. Catat hal-hal penting, kutipan menarik, dan bagian yang mengganggu.",
          "",
          "2. Catat identitas dan fakta dasar",
          "  Judul, penulis, penerbit, genre, tahun terbit — semua harus lengkap.",
          "",
          "3. Analisis secara sistematis",
          "  Gunakan unsur intrinsik sebagai kerangka analisis: tema, alur, tokoh, latar, gaya bahasa, amanat.",
          "",
          "4. Tentukan kelebihan dan kekurangan",
          "  Setidaknya 2-3 kelebihan dan 1-2 kekurangan. Jangan ragu mengkritik, tapi lakukan secara santun dan objektif.",
          "",
          "5. Tulis dengan struktur yang jelas",
          "  Identitas → Sinopsis → Analisis → Simpulan. Jangan lupa beri bukti untuk setiap klaim.",
          "",
          "[Ilustrasi: Seorang siswa duduk di perpustakaan dengan buku di tangan dan buku catatan di pangkuan. Di catatan tertulis: 'Kelebihan: karakter kuat. Kekurangan: alur lambat.' Rak buku tinggi di belakang. Gaya ilustrasi perpustakaan sekolah dengan warna krem dan hijau lumut.]",
        ],
        contoh: [
          "CONTOH RESENSI SINGKAT:",
          "",
          "Judul Resensi: 'Perjalanan Panjang dalam 200 Halaman'",
          "",
          "IDENTITAS:",
          "Buku: 'Pulang' | Penulis: Tere Liye | Penerbit: Republika | Tahun: 2015",
          "",
          "SINOPSIS:",
          "Bercerita tentang Bujang, seorang anak yang ditinggal ibunya merantau. Ia harus bertahan hidup sendirian dan mencari jati diri.",
          "",
          "ANALISIS:",
          "Kelebihan: (1) Gaya bahasa sederhana namun menyentuh, mudah dipahami remaja. (2) Tokoh Bujang berkembang secara meyakinkan. (3) Konflik keluarga digambarkan realistis.",
          "Kekurangan: (1) Alur terlalu lambat di 50 halaman pertama. (2) Beberapa tokoh sekunder kurang dikembangkan.",
          "",
          "SIMPULAN:",
          "Novel 'Pulang' cocok untuk remaja yang suka cerita keluarga dengan pesan moral. Rating: 4/5 — layak dibaca sekali.",
        ],
      },
    ],
    rangkuman: [
      "[Ilustrasi: Tumpukan buku fiksi dan nonfiksi dengan label 'SUDAH DIRESENSI' di samping sebuah laptop yang menampilkan blog resensi. Ikon bintang 5, pensil, dan kaca pembesar melayang di atasnya. Gaya ilustrasi perpustakaan modern dengan warna biru dan kuning.]",
      "Resensi adalah tulisan yang mengupas isi, kelebihan, dan kekurangan suatu karya secara kritis.",
      "Struktur resensi: judul → identitas → sinopsis → analisis → simpulan dan rekomendasi.",
      "Kaidah kebahasaan: kata sifat opini, istilah sastra, kalimat kompleks, kata kerja mental, pembandingan.",
      "Menulis resensi: baca secara menyeluruh, catat identitas, analisis sistematis, tentukan kelebihan dan kekurangan, tulis dengan struktur jelas.",
    ],
  },
  latihan: makeSoal([
    ["Perbedaan resensi tingkat lanjut dengan resensi dasar adalah...", ["Resensi lanjutan tidak perlu data", "Resensi lanjutan berisi analisis mendalam dan perbandingan", "Resensi dasar lebih panjang", "Resensi lanjutan hanya untuk buku"], 1, "Resensi lanjutan berisi analisis mendalam, perbandingan, dan argumen yang dapat dipertanggungjawabkan."],
    ["Bagian yang berisi informasi lengkap tentang karya dalam resensi disebut...", ["Sinopsis", "Identitas karya", "Analisis", "Simpulan"], 1, "Identitas karya berisi judul, penulis, penerbit, tahun, ISBN, dll."],
    ["Fungsi sinopsis dalam resensi adalah...", ["Menilai kelebihan buku", "Memberi gambaran singkat isi karya tanpa spoiler", "Menulis ulang seluruh isi buku", "Mengkritik penulis"], 1, "Sinopsis memberi gambaran isi karya tanpa spoiler berlebihan."],
    ["Kata sifat opini dalam resensi harus...", ["Berdiri sendiri tanpa alasan", "Didukung bukti dan argumen", "Subjektif tanpa dasar", "Panjang dan rumit"], 1, "Setiap kata sifat opini harus didukung bukti."],
    ["Contoh istilah sastra yang tepat dalam resensi novel adalah...", ["Alur, penokohan, latar", "Rima, irama, mantra", "Grafik, tabel, diagram", "Pajak, investasi, saham"], 0, "'Alur', 'penokohan', 'latar' adalah istilah sastra yang tepat untuk menganalisis novel."],
    ["Yang dimaksud dengan nominalisasi dalam resensi adalah...", ["Mengubah kata kerja menjadi kata benda", "Menambah kata sifat", "Mengubah kata benda menjadi kata kerja", "Mengganti kata dengan sinonim"], 0, "Nominalisasi adalah perubahan kata kerja menjadi kata benda, misalnya 'menggambarkan' menjadi 'penggambaran'."],
    ["Salah satu kesalahan umum dalam menulis resensi adalah...", ["Memberikan penilaian objektif", "Hanya berisi sinopsis tanpa analisis", "Menggunakan istilah sastra", "Menyebutkan kelebihan dan kekurangan"], 1, "Resensi yang hanya berisi sinopsis tanpa analisis disebut laporan buku, bukan resensi."],
    ["Bagian akhir resensi biasanya berisi...", ["Identitas buku", "Sinopsis", "Analisis detail", "Simpulan dan rekomendasi"], 3, "Bagian akhir resensi berisi simpulan dan rekomendasi."],
    ["Konjungsi pembandingan yang tepat dalam resensi adalah...", ["Dan", "Dibandingkan dengan", "Atau", "Kemudian"], 1, "'Dibandingkan dengan' adalah konjungsi pembandingan yang tepat."],
    ["Tujuan utama resensi adalah...", ["Membuat penulis terkenal", "Memberi informasi dan pandangan kritis kepada calon pembaca", "Menjual buku", "Meniru karya orang lain"], 1, "Tujuan resensi adalah memberikan informasi dan pandangan kritis."],
  ]),
  praktik: {
    petunjuk: "Pilihlah satu novel atau buku nonfiksi yang pernah kamu baca. Tulislah resensi dengan struktur lengkap: (1) Judul resensi yang menarik, (2) Identitas karya, (3) Sinopsis singkat tanpa spoiler, (4) Analisis kelebihan dan kekurangan minimal 3 poin masing-masing disertai bukti, (5) Simpulan dan rekomendasi. Panjang tulisan 400-600 kata.",
    tips: [
      "Baca buku sampai selesai sebelum menulis resensi — jangan meresensi dari sampul atau review orang lain",
      "Gunakan sticky notes untuk menandai bagian penting saat membaca",
      "Buat kerangka analisis berdasarkan unsur intrinsik sebelum menulis",
      "Setiap kritik harus disertai saran perbaikan — jangan mengkritik tanpa solusi",
      "Baca ulang resensimu dan pastikan tidak ada spoiler berlebihan",
    ],
    contoh: "Resensi 400-600 kata dengan struktur lengkap: judul, identitas, sinopsis, analisis (kelebihan + kekurangan), simpulan dan rekomendasi.",
  },
  kuis: makeSoal([
    ["Yang BUKAN termasuk ciri resensi tingkat lanjut adalah...", ["Analisis mendalam", "Penilaian subjektif tanpa bukti", "Perbandingan dengan karya lain", "Argumen yang dapat dipertanggungjawabkan"], 1, "Resensi tingkat lanjut harus objektif dan didukung bukti, bukan sekadar opini subjektif."],
    ["Bagian identitas karya dalam resensi berfungsi untuk...", ["Memperindah tampilan", "Memberi informasi lengkap tentang karya", "Menambah halaman", "Menggantikan sinopsis"], 1, "Identitas karya memberi informasi detail tentang karya yang diresensi."],
    ["Kata 'mendalam' dalam resensi termasuk...", ["Kata kerja mental", "Kata sifat opini", "Istilah sastra", "Konjungsi"], 1, "'Mendalam' adalah kata sifat opini yang menunjukkan penilaian."],
    ["Sinopsis dalam resensi sebaiknya...", ["Menceritakan seluruh detail cerita", "Memberi gambaran singkat tanpa spoiler", "Tidak perlu ada", "Panjang minimal 500 kata"], 1, "Sinopsis harus singkat dan tanpa spoiler berlebihan."],
    ["Contoh kata kerja mental dalam resensi adalah...", ["Memotong", "Menunjukkan", "Berlari", "Memasak"], 1, "'Menunjukkan' adalah kata kerja mental yang berkaitan dengan aktivitas mental."],
    ["'Dibandingkan dengan novel pertamanya, karya ini lebih matang.' Kalimat ini menggunakan...", ["Konjungsi temporal", "Pembandingan", "Konjungsi sebab-akibat", "Konjungsi perlawanan"], 1, "Kalimat tersebut membandingkan dua karya, menggunakan pembandingan."],
    ["Bagian analisis dalam resensi sebaiknya...", ["Hanya berisi pujian", "Berisi kelebihan dan kekurangan dengan bukti", "Hanya berisi kritik", "Tidak perlu argumen"], 1, "Analisis harus seimbang, mencakup kelebihan dan kekurangan dengan bukti."],
    ["Resensi yang baik harus ditulis secara...", ["Sistematis dan objektif", "Acak dan subjektif", "Panjang dan rumit", "Pendek dan tanpa data"], 0, "Resensi harus sistematis dan objektif agar mudah dipahami dan kredibel."],
    ["Salah satu etika menulis resensi adalah...", ["Mengkritik penulis secara personal", "Mengkritik karya secara santun dan objektif", "Memuji tanpa syarat", "Menjelekkan karya tanpa alasan"], 1, "Kritik harus ditujukan pada karya, bukan pribadi penulis, dan disampaikan secara santun."],
    ["Tujuan rekomendasi dalam resensi adalah...", ["Memaksa pembaca membeli", "Membantu pembaca memutuskan apakah karya layak dibaca", "Mempromosikan penerbit", "Membuat penulis terkenal"], 1, "Rekomendasi membantu pembaca mempertimbangkan karya tersebut."],
  ]),
}

export default konten
