import type { Konten } from "../types"
import { makeSoal } from "../types"

const konten: Konten = {
  belajar: {
    tujuan: [
      "Memahami pengertian, karakteristik, dan jenis karya tulis ilmiah",
      "Mengidentifikasi sistematika penulisan karya tulis ilmiah yang baku",
      "Menganalisis kaidah kebahasaan dan keilmiahan dalam KTI",
      "Menyusun karya tulis ilmiah sederhana dengan data dan referensi yang valid",
      "Menyajikan karya tulis ilmiah dalam seminar kelas dengan percaya diri",
    ],
    materi: [
      {
        judul: "Mengenal Karya Tulis Ilmiah",
        isi: [
          "Karya tulis ilmiah (KTI) adalah tulisan yang menyajikan gagasan, analisis, atau hasil penelitian berdasarkan data dan fakta yang dapat dipertanggungjawabkan secara ilmiah. KTI menggunakan metode berpikir ilmiah: sistematis, logis, objektif, dan empiris.",
          "",
          "✓ Ciri-ciri KTI:",
          "  ✓ Objektif — berdasarkan fakta, bukan opini pribadi",
          "  ✓ Sistematis — disusun dengan urutan yang logis",
          "  ✓ Logis — argumentasi masuk akal dan dapat diikuti",
          "  ✓ Empiris — berdasarkan pengamatan atau data nyata",
          "  ✓ Menggunakan bahasa baku dan istilah ilmiah",
          "  ✓ Dilengkapi daftar pustaka dan sumber referensi",
          "",
          "Jenis KTI di tingkat SMA:",
          "  - Makalah: analisis suatu topik berdasarkan studi pustaka",
          "  - Artikel ilmiah populer: untuk dimuat di majalah atau jurnal",
          "  - Laporan penelitian: hasil penelitian sederhana (observasi, eksperimen)",
          "  - Esai ilmiah: argumen logis tentang suatu isu berdasarkan data",
          "",
          "[Ilustrasi: Sebuah meja laboratorium dengan laptop yang menampilkan dokumen KTI. Di layar terlihat bab 'PENDAHULUAN' dan 'LANDASAN TEORI'. Tumpukan buku referensi, jurnal, dan kertas catatan berserakan. Ada mikroskop dan alat laboratorium di latar belakang. Gaya ilustrasi laboratorium penelitian dengan warna putih dan biru.]",
        ],
        contoh: [
          "CONTOH SISTEMATIKA MAKALAH SEDERHANA:",
          "",
          "JUDUL: 'Pengaruh Media Sosial terhadap Motivasi Belajar Siswa SMA'",
          "",
          "BAB I PENDAHULUAN",
          "  1.1 Latar Belakang",
          "  1.2 Rumusan Masalah",
          "  1.3 Tujuan Penelitian",
          "  1.4 Manfaat Penelitian",
          "",
          "BAB II LANDASAN TEORI",
          "  2.1 Media Sosial",
          "  2.2 Motivasi Belajar",
          "  2.3 Penelitian Relevan",
          "",
          "BAB III METODE PENELITIAN",
          "  3.1 Jenis Penelitian",
          "  3.2 Populasi dan Sampel",
          "  3.3 Teknik Pengumpulan Data",
          "  3.4 Teknik Analisis Data",
          "",
          "BAB IV HASIL DAN PEMBAHASAN",
          "  4.1 Hasil Penelitian",
          "  4.2 Pembahasan",
          "",
          "BAB V PENUTUP",
          "  5.1 Simpulan",
          "  5.2 Saran",
          "",
          "DAFTAR PUSTAKA",
        ],
        catatan: "Karya tulis ilmiah bukanlah 'opini yang dibungkus rapi'. Setiap klaim dalam KTI harus didukung oleh data atau referensi yang valid. Bedanya dengan artikel opini: KTI menggunakan metode ilmiah dan struktur baku.",
      },
      {
        judul: "Sistematika Karya Tulis Ilmiah",
        isi: [
          "KTI memiliki sistematika yang baku. Meskipun bisa bervariasi tergantung jenis dan tujuannya, secara umum struktur KTI terdiri dari:",
          "",
          "1. BAGIAN AWAL (PRAKATA)",
          "  - Halaman judul",
          "  - Kata pengantar",
          "  - Daftar isi",
          "  - Daftar tabel/gambar (jika ada)",
          "",
          "2. BAGIAN INTI",
          "  Bab I Pendahuluan: latar belakang, rumusan masalah, tujuan, manfaat",
          "  Bab II Landasan Teori: kajian pustaka, kerangka berpikir",
          "  Bab III Metode Penelitian: pendekatan, teknik pengumpulan data, analisis",
          "  Bab IV Hasil dan Pembahasan: temuan penelitian, analisis",
          "  Bab V Penutup: simpulan, saran",
          "",
          "3. BAGIAN AKHIR",
          "  - Daftar pustaka",
          "  - Lampiran (angket, data mentah, foto kegiatan)",
          "",
          "PENTING: Setiap bab dalam KTI saling berhubungan. Bab I mengarah ke Bab II, Bab III menjelaskan cara menjawab pertanyaan di Bab I, Bab IV menyajikan hasil, dan Bab V menyimpulkan semuanya.",
          "",
          "[Ilustrasi: Diagram alur vertikal yang menunjukkan hubungan antar bab KTI. Bab I (Pendahuluan) mengarah ke Bab II (Landasan Teori), lalu Bab III (Metode), Bab IV (Hasil), Bab V (Penutup). Tanda panah menunjukkan hubungan timbal balik. Gaya ilustrasi struktur organisasi dengan warna biru gradasi.]",
        ],
        contoh: [
          "CONTOH PENULISAN RUMUSAN MASALAH:",
          "",
          "Topik: Pengaruh Media Sosial terhadap Motivasi Belajar",
          "",
          "Rumusan Masalah (dalam bentuk pertanyaan):",
          "1. Bagaimana tingkat penggunaan media sosial pada siswa SMA Negeri 1?",
          "2. Bagaimana tingkat motivasi belajar siswa SMA Negeri 1?",
          "3. Adakah pengaruh penggunaan media sosial terhadap motivasi belajar siswa SMA Negeri 1?",
          "",
          "→ Rumusan masalah harus spesifik, terukur, dan dapat dijawab melalui penelitian.",
          "",
          "CONTOH PENULISAN TUJUAN:",
          "",
          "Tujuan Penelitian:",
          "1. Mendeskripsikan tingkat penggunaan media sosial siswa SMA Negeri 1",
          "2. Mendeskripsikan tingkat motivasi belajar siswa SMA Negeri 1",
          "3. Menganalisis pengaruh penggunaan media sosial terhadap motivasi belajar siswa SMA Negeri 1",
          "",
          "→ Tujuan penelitian harus sejalan dengan rumusan masalah.",
        ],
      },
      {
        judul: "Kaidah Kebahasaan KTI",
        isi: [
          "Bahasa dalam KTI berbeda dengan bahasa dalam cerpen atau artikel opini. KTI menggunakan ragam bahasa ilmiah yang baku dan formal.",
          "",
          "1. MENGGUNAKAN BAHASA INDONESIA BAKU",
          "  Patuhi EYD, gunakan istilah yang tepat, dan hindari bahasa daerah, gaul, atau singkatan tidak resmi.",
          "",
          "2. KALIMAT EFEKTIF DAN OBJEKTIF",
          "  Hindari kata-kata subjektif seperti 'menurut saya', 'saya pikir'. Gunakan 'peneliti berpendapat', 'berdasarkan analisis', 'data menunjukkan'.",
          "",
          "3. PENGGUNAAN ISTILAH ILMIAH",
          "  Gunakan istilah yang tepat sesuai bidang. Misal: variabel, hipotesis, populasi, sampel, korelasi. Jika perlu, jelaskan istilah tersebut.",
          "",
          "4. KALIMAT PASIF YANG OBJEKTIF",
          "  KTI lebih banyak menggunakan kalimat pasif untuk menjaga objektivitas. Contoh: 'Penelitian dilakukan pada bulan Januari' (bukan 'Saya melakukan penelitian...').",
          "",
          "5. KONJUNGSI LOGIS DAN ARGUMENTATIF",
          "  Gunakan konjungsi yang menunjukkan hubungan logis: 'oleh karena itu', 'dengan demikian', 'berdasarkan hasil', 'sehubungan dengan'.",
          "",
          "[Ilustrasi: Buku pedoman EYD dan buku panduan penulisan ilmiah terbuka berdampingan. Di sekelilingnya ada kartu-kartu dengan contoh: 'Variabel (istilah)', 'Berdasarkan data (objektif)', 'Penelitian dilakukan (pasif)'. Gaya ilustrasi buku referensi dengan warna putih dan hijau.]",
        ],
        contoh: [
          "Perbandingan bahasa non-ilmiah vs ilmiah:",
          "",
          "NON-ILMIAH: 'Menurut saya, media sosial bikin siswa malas belajar. Saya lihat sendiri di kelas saya.'",
          "→ Subjektif, tidak baku, tanpa data.",
          "",
          "ILMIAH: 'Berdasarkan hasil survei yang dilakukan pada 100 siswa SMA Negeri 1, ditemukan bahwa 65% responden mengaku kesulitan berkonsentrasi belajar setelah menggunakan media sosial lebih dari 3 jam per hari.'",
          "→ Objektif (berdasarkan data), terukur (65%, 3 jam), baku.",
          "",
          "NON-ILMIAH: 'Penelitian ini penting banget karena banyak siswa kecanduan medsos.'",
          "→ Tidak baku ('banget', 'medsos').",
          "",
          "ILMIAH: 'Penelitian ini penting dilakukan mengingat tingginya tingkat penggunaan media sosial di kalangan remaja yang berpotensi memengaruhi prestasi akademik.'",
          "→ Baku, formal, alasan logis.",
        ],
      },
      {
        judul: "Menyusun KTI Sederhana",
        isi: [
          "Menulis KTI tidak harus rumit. Mulailah dari hal sederhana dengan langkah-langkah berikut!",
          "",
          "PENTING: Langkah paling krusial adalah menentukan topik. Pilih topik yang: (1) kamu kuasai, (2) data mudah diperoleh, (3) cukup spesifik untuk dibahas dalam 15-20 halaman.",
          "",
          "LANGKAH MENYUSUN KTI:",
          "",
          "1. Tentukan topik dan judul",
          "  Pilih topik yang menarik dan relevan. Judul harus mencerminkan isi secara tepat.",
          "",
          "2. Buat rumusan masalah",
          "  Rumuskan dalam bentuk pertanyaan yang spesifik dan dapat dijawab.",
          "",
          "3. Cari dan baca referensi",
          "  Gunakan buku, jurnal, artikel ilmiah, atau sumber terpercaya. Minimal 5 referensi.",
          "",
          "4. Kumpulkan data",
          "  Observasi, angket, wawancara, atau studi pustaka. Data harus sesuai dengan metode yang dipilih.",
          "",
          "5. Tulis secara sistematis",
          "  Ikuti struktur bab yang baku. Gunakan bahasa ilmiah dan kutip sumber dengan benar.",
          "",
          "[Ilustrasi: Seorang siswa sedang mengetik di laptop dengan tumpukan buku referensi di sampingnya. Layar menampilkan dokumen dengan heading 'BAB III METODE PENELITIAN'. Di papan tulis belakang ada diagram alir penelitian. Gaya ilustrasi kamar belajar remaja dengan warna biru dan kuning.]",
        ],
        contoh: [
          "CONTOH KERANGKA KTI SEDERHANA:",
          "",
          "Judul: 'Kebiasaan Membaca dan Pengaruhnya terhadap Prestasi Belajar Bahasa Indonesia Siswa Kelas XI SMAN 1'",
          "",
          "BAB I PENDAHULUAN",
          "- Latar belakang: minat baca siswa Indonesia rendah (data PISA 2022)",
          "- Rumusan: Adakah hubungan antara kebiasaan membaca dan prestasi belajar?",
          "- Tujuan: Menganalisis hubungan kebiasaan membaca dengan prestasi belajar",
          "",
          "BAB II LANDASAN TEORI",
          "- Teori membaca, faktor yang memengaruhi minat baca",
          "- Penelitian relevan",
          "",
          "BAB III METODE",
          "- Survei dengan angket (40 responden kelas XI)",
          "- Analisis korelasi sederhana",
          "",
          "BAB IV HASIL",
          "- Tabel distribusi frekuensi kebiasaan membaca",
          "- Analisis korelasi: r = 0,65 (hubungan kuat positif)",
          "",
          "BAB V PENUTUP",
          "- Simpulan: Ada hubungan positif signifikan",
          "- Saran: Perlu program penguatan literasi sekolah",
        ],
      },
    ],
    rangkuman: [
      "[Ilustrasi: Tumpukan jurnal ilmiah dan makalah berjilid rapi dengan label 'KTI KELAS XI'. Dari tumpukan itu muncul ikon-ikon: kaca pembesar (penelitian), buku (referensi), grafik (data), dan tanda centang (validasi). Gaya ilustrasi akademik dengan warna biru tua dan putih.]",
      "KTI adalah tulisan yang menyajikan gagasan atau hasil penelitian berdasarkan data dan fakta yang dapat dipertanggungjawabkan secara ilmiah.",
      "Sistematika: pendahuluan → landasan teori → metode → hasil dan pembahasan → penutup → daftar pustaka.",
      "Kaidah kebahasaan: bahasa baku, objektif, istilah ilmiah, kalimat pasif, konjungsi logis.",
      "Langkah menulis: tentukan topik, rumuskan masalah, cari referensi, kumpulkan data, tulis sistematis.",
    ],
  },
  latihan: makeSoal([
    ["Ciri utama karya tulis ilmiah yang membedakannya dari tulisan non-ilmiah adalah...", ["Menggunakan bahasa puitis", "Berdasarkan data dan fakta yang dapat dipertanggungjawabkan", "Panjang minimal 50 halaman", "Tidak perlu daftar pustaka"], 1, "KTI harus berdasarkan data dan fakta yang dapat dipertanggungjawabkan secara ilmiah."],
    ["Bagian KTI yang berisi kajian teori dan penelitian relevan adalah...", ["Pendahuluan", "Landasan teori", "Metode penelitian", "Penutup"], 1, "Landasan teori berisi kajian pustaka dan penelitian yang relevan."],
    ["Rumusan masalah dalam KTI ditulis dalam bentuk...", ["Pernyataan", "Pertanyaan", "Perintah", "Ajakan"], 1, "Rumusan masalah ditulis dalam bentuk pertanyaan yang spesifik."],
    ["Fungsi daftar pustaka dalam KTI adalah...", ["Memperindah tampilan", "Menunjukkan sumber referensi yang digunakan", "Mengganti lampiran", "Menambah halaman"], 1, "Daftar pustaka menunjukkan sumber referensi yang dikutip dalam KTI."],
    ["Contoh kalimat pasif yang tepat dalam KTI adalah...", ["Saya melakukan penelitian pada bulan Januari", "Penelitian dilakukan pada bulan Januari", "Kami mengumpulkan data", "Peneliti pergi ke lapangan"], 1, "Kalimat pasif 'Penelitian dilakukan' lebih objektif daripada 'Saya melakukan'."],
    ["Yang dimaksud dengan 'objektif' dalam KTI adalah...", ["Berdasarkan opini penulis", "Berdasarkan fakta dan data, bukan prasangka pribadi", "Mengikuti keinginan pembaca", "Menghibur pembaca"], 1, "Objektif berarti berdasarkan fakta, bukan opini atau prasangka pribadi."],
    ["Sistematika KTI yang benar adalah...", ["Pendahuluan-metode-hasil-landasan teori-penutup", "Pendahuluan-landasan teori-metode-hasil-penutup", "Landasan teori-pendahuluan-metode-hasil-penutup", "Penutup-pendahuluan-landasan teori-metode-hasil"], 1, "Urutan yang benar: pendahuluan, landasan teori, metode, hasil, penutup."],
    ["Perbedaan makalah dan laporan penelitian terletak pada...", ["Makalah lebih pendek", "Laporan penelitian menyajikan data hasil riset langsung", "Makalah tidak perlu daftar pustaka", "Laporan penelitian tidak punya bab pendahuluan"], 1, "Laporan penelitian menyajikan data hasil riset langsung, makalah bisa berdasarkan studi pustaka."],
    ["Kata 'berdasarkan analisis data' termasuk contoh...", ["Opini subjektif", "Peryataan objektif berbasis data", "Bahasa puitis", "Ajakan"], 1, "Pernyataan tersebut menunjukkan kesimpulan berdasarkan analisis data."],
    ["Salah satu syarat referensi yang baik untuk KTI adalah...", ["Dari blog pribadi", "Kredibel dan relevan dengan topik", "Dari media sosial", "Tanpa nama penulis"], 1, "Referensi harus kredibel (buku, jurnal, sumber resmi) dan relevan dengan topik."],
  ]),
  praktik: {
    petunjuk: "Buatlah karya tulis ilmiah sederhana dengan salah satu topik berikut: (1) Pengaruh gadget terhadap prestasi belajar siswa, (2) Kebiasaan membaca dan kemampuan menulis siswa, (3) Dampak media sosial terhadap interaksi sosial remaja. Gunakan sistematika lengkap: Bab I Pendahuluan (latar belakang, rumusan masalah, tujuan), Bab II Landasan Teori, Bab III Metode Penelitian, Bab IV Hasil dan Pembahasan, Bab V Penutup. Sertakan daftar pustaka minimal 5 sumber. Data bisa dikumpulkan melalui angket sederhana atau observasi.",
    tips: [
      "Pilih topik yang dekat dengan kehidupan sehari-hari agar data mudah diperoleh",
      "Buat angket sederhana (10-15 pertanyaan) dan sebarkan ke 20-30 teman sekelas",
      "Gunakan Google Scholar atau buku perpustakaan untuk mencari referensi",
      "Gunakan bahasa yang objektif, hindari kata 'saya', 'kami', 'menurut saya'",
      "Minta guru membimbing setiap bab sebelum melanjutkan ke bab berikutnya",
    ],
    contoh: "KTI lengkap 5 bab dengan data penelitian sederhana (angket/observasi), daftar pustaka minimal 5 sumber, dan bahasa ilmiah yang baku.",
  },
  kuis: makeSoal([
    ["Yang BUKAN merupakan ciri karya tulis ilmiah adalah...", ["Objektif", "Berdasarkan data", "Mengandung opini pribadi", "Sistematis"], 2, "KTI bersifat objektif, tidak mengandung opini pribadi tanpa data."],
    ["Bagian yang berisi latar belakang dan rumusan masalah adalah...", ["Bab I Pendahuluan", "Bab II Landasan Teori", "Bab III Metode", "Bab IV Hasil"], 0, "Pendahuluan berisi latar belakang, rumusan masalah, tujuan, dan manfaat."],
    ["Fungsi landasan teori dalam KTI adalah...", ["Menyajikan hasil penelitian", "Memberikan dasar teoritis dan kajian penelitian relevan", "Menjelaskan metode pengumpulan data", "Menarik simpulan"], 1, "Landasan teori memberikan dasar ilmiah untuk penelitian."],
    ["Kalimat yang tepat untuk KTI adalah...", ["Menurut gue, ini masalah serius", "Berdasarkan data yang diperoleh, ditemukan bahwa", "Kayaknya sih ini penting", "Pokoknya penelitian ini keren"], 1, "KTI harus menggunakan bahasa baku dan objektif."],
    ["Contoh rumusan masalah yang tepat adalah...", ["Media sosial itu buruk", "Adakah pengaruh penggunaan media sosial terhadap prestasi belajar siswa?", "Siswa suka main medsos", "Media sosial harus dilarang"], 1, "Rumusan masalah berbentuk pertanyaan yang spesifik dan dapat dijawab."],
    ["Bagian metode penelitian berisi...", ["Hasil analisis data", "Cara dan teknik pengumpulan serta analisis data", "Kesimpulan penelitian", "Daftar pustaka"], 1, "Metode penelitian menjelaskan cara pengumpulan dan analisis data."],
    ["Tujuan penulisan daftar pustaka adalah...", ["Menunjukkan banyaknya buku yang dibaca", "Memberi kredit pada sumber yang dikutip", "Menghias halaman akhir", "Memenuhi syarat jumlah halaman"], 1, "Daftar pustaka memberi kredit dan menunjukkan sumber referensi."],
    ["Salah satu perbedaan KTI dengan artikel opini adalah...", ["KTI lebih pendek", "KTI menggunakan metode ilmiah dan struktur baku", "Artikel opini memiliki daftar pustaka", "KTI tidak perlu data"], 1, "KTI menggunakan metode ilmiah dengan struktur baku, berbeda dari artikel opini."],
    ["Kalimat pasif dalam KTI digunakan untuk...", ["Menjaga objektivitas", "Memperpendek kalimat", "Menambah variasi", "Membuat rumit"], 0, "Kalimat pasif menjaga objektivitas karena tidak menonjolkan subjek peneliti."],
    ["Jenis KTI yang paling tepat untuk penelitian sederhana di SMA adalah...", ["Skripsi", "Laporan penelitian", "Disertasi", "Tesis"], 1, "Laporan penelitian adalah bentuk KTI yang paling sesuai untuk tingkat SMA."],
  ]),
}

export default konten
