import type { Konten } from "../types"
import { makeSoal } from "../types"

const konten: Konten = {
  belajar: {
    tujuan: [
      "Memahami pengertian, ciri, dan jenis teks cerita sejarah",
      "Mengidentifikasi struktur dan kebahasaan teks cerita sejarah",
      "Menganalisis fakta dan fiksi dalam novel/lagu sejarah",
      "Menyusun teks cerita sejarah berdasarkan data dan fakta sejarah",
      "Mengevaluasi pesan moral dan relevansi peristiwa sejarah dengan masa kini",
    ],
    materi: [
      {
        judul: "Apa Itu Cerita Sejarah?",
        isi: [
          "Sejarah bukan hanya kumpulan tanggal dan nama pahlawan yang harus dihafal. Sejarah adalah kisah tentang manusia, perjuangan, kegagalan, dan kemenangan. Di kelas XII, kita akan melihat sejarah bukan sebagai ilmu mati, melainkan sebagai cerita yang hidup dan relevan dengan kehidupan kita hari ini.",
          "",
          "Teks cerita sejarah adalah teks yang memuat kisah atau peristiwa masa lampau yang memiliki nilai sejarah. Teks ini bisa berbentuk faktual (nonfiksi seperti buku sejarah) maupun fiksional (novel, cerpen, puisi, atau lagu yang berlatar belakang peristiwa sejarah).",
          "",
          "✓ Ciri-ciri teks cerita sejarah:",
          "  ✓ Berkaitan dengan peristiwa masa lampau yang benar-benar terjadi",
          "  ✓ Disajikan secara kronologis atau berdasarkan urutan waktu",
          "  ✓ Mengandung fakta sejarah yang dapat diverifikasi",
          "  ✓ Dalam bentuk fiksi, fakta sejarah menjadi latar cerita (setting)",
          "  ✓ Memiliki nilai-nilai yang dapat dipetik pembaca",
          "  ✓ Menggunakan konjungsi temporal (sejak, sebelum, setelah, kemudian, akhirnya)",
          "",
          "Perbedaan fakta dan fiksi dalam cerita sejarah:",
          "",
          "  FAKTA SEJARAH → data, tanggal, nama tokoh, lokasi, peristiwa yang benar-benar terjadi",
          "  FIKSI → dialog rekaan, detail emosi tokoh, adegan yang diimajinasikan penulis",
          "  Batasnya: penulis fiksi sejarah tidak boleh mengubah fakta inti, tapi boleh mengisi 'celah kosong' dengan imajinasi",
          "",
          "[Ilustrasi: Rak buku tua dengan jajaran buku sejarah bersampul cokelat dan merah. Di antara buku-buku, sebuah foto hitam-putih zaman kolonial. Dari foto, asap tipis membentuk gambar-gambar masa lalu seperti kilas balik. Gaya ilustrasi surealis dengan warna sepia dan cokelat tua.]",
        ],
        contoh: [
          "CONTOH TEKS CERITA SEJARAH FAKTUAL:",
          "",
          "'Proklamasi kemerdekaan Indonesia dibacakan oleh Soekarno dan Hatta pada tanggal 17 Agustus 1945 pukul 10.00 WIB di Jalan Pegangsaan Timur No. 56, Jakarta. Naskah proklamasi diketik oleh Sayuti Melik menggunakan mesin ketik yang dipinjam dari kantor Kepala Perwakilan Angkatan Laut Jerman.'",
          "✓ Fakta: tanggal, jam, lokasi, tokoh, semua dapat diverifikasi.",
          "",
          "",
          "CONTOH TEKS CERITA SEJARAH FIKSIONAL (novel):",
          "",
          "'Malam itu, 16 Agustus 1945, suasana di rumah Laksamana Maeda tegang. Para pemuda berdiskusi sengit dengan golongan tua. Di sudut ruangan, seorang pemuda berusia 19 tahun — sebut saja Raga — diam mendengarkan. Dadanya berdegup kencang. Esok hari, Indonesia akan merdeka — atau mungkin tidak sama sekali.'",
          "✓ Fakta: peristiwa Rengasdengklok, diskusi di rumah Maeda, proklamasi. Fiksi: tokoh Raga, dialog, detail emosi.",
        ],
        catatan: "Salah satu karya sastra sejarah paling monumental di Indonesia adalah 'Bumi Manusia' karya Pramoedya Ananta Toer. Novel ini berlatar belakang awal abad ke-20, masa awal pergerakan nasional. Pramoedya berhasil memadukan fakta sejarah dengan kisah fiksi yang menyentuh, sehingga pembaca tidak hanya belajar sejarah tetapi juga merasakannya. Novel ini sempat dilarang beredar pada era Orde Baru karena dianggap mengandung ideologi tertentu.",
      },
      {
        judul: "Struktur Teks Cerita Sejarah",
        isi: [
          "Teks cerita sejarah, baik faktual maupun fiksional, memiliki struktur yang khas. Berikut adalah struktur umum yang membangun sebuah teks cerita sejarah:",
          "",
          "1. ORIENTASI",
          "  Bagian pembuka yang memperkenalkan latar: waktu, tempat, suasana, dan tokoh-tokoh yang terlibat. Orientasi berfungsi untuk 'membawa' pembaca masuk ke dalam dunia cerita.",
          "",
          "  Contoh: 'Pada awal tahun 1942, ketika sinar mentari pagi menyinari pelabuhan Tanjung Priok, suasana kota Jakarta diliputi kecemasan. Tentara Jepang dikabarkan akan segera mendarat.'",
          "",
          "2. URUTAN PERISTIWA",
          "  Rangkaian kejadian yang disusun secara kronologis (berdasarkan urutan waktu). Bagian ini merupakan inti dari cerita sejarah. Peristiwa disajikan dengan detail, termasuk tokoh, tempat, dan dampak dari setiap kejadian.",
          "",
          "  Contoh: 'Pada 8 Maret 1942, Belanda menyerah tanpa syarat kepada Jepang di Kalijati. Kekuasaan Hindia Belanda resmi berakhir. Selama 3,5 tahun berikutnya, rakyat Indonesia hidup di bawah pendudukan Jepang yang kejam.'",
          "",
          "3. KRISIS / KONFLIK",
          "  Puncak ketegangan dalam cerita. Dalam konteks teks sejarah, ini adalah momen kritis di mana nasib suatu bangsa atau tokoh dipertaruhkan. Inilah 'titik balik' dari rangkaian peristiwa.",
          "",
          "  Contoh: 'Tanggal 16 Agustus 1945, sekelompok pemuda menculik Soekarno dan Hatta ke Rengasdengklok. Mereka mendesak proklamasi dilaksanakan secepatnya. Para pemuda khawatir Jepang akan menghalangi kemerdekaan.'",
          "",
          "4. RESOLUSI",
          "  Penyelesaian dari krisis. Bagian ini menjelaskan bagaimana peristiwa krisis diatasi dan apa dampaknya. Pada cerita sejarah, resolusi sering kali merupakan peristiwa besar yang mengubah arah sejarah.",
          "",
          "5. KODA / REORIENTASI",
          "  Bagian penutup yang berisi simpulan, amanat, atau refleksi penulis tentang peristiwa yang diceritakan. Koda menghubungkan peristiwa masa lalu dengan kehidupan masa kini.",
          "",
          "[Ilustrasi: Diagram struktur teks cerita sejarah berbentuk gunung: ORIENTASI (lereng landai), URUTAN PERISTIWA (lereng menanjak), KRISIS (puncak), RESOLUSI (lereng turun), KODA (kaki gunung). Setiap tahap diwarnai berbeda. Gaya ilustrasi diagram perjalanan dengan warna oranye, merah, biru, hijau, dan ungu.]",
        ],
        contoh: [
          "CONTOH STRUKTUR TEKS CERITA SEJARAH 'PERTEMPURAN SURABAYA':",
          "",
          "ORIENTASI: 'Pada bulan Oktober 1945, suasana Surabaya memanas. Sekutu, yang diboncengi NICA Belanda, mulai mendarat di kota pahlawan. Rakyat Surabaya yang bersenjatakan bambu runcing siap mempertahankan kemerdekaan.'",
          "",
          "URUTAN PERISTIWA: 'Tanggal 27 Oktober 1945, ultimatum Sekutu memerintahkan rakyat Surabaya menyerahkan senjata. Ultimatum itu ditolak. Pada 10 November 1945, pertempuran dahsyat pecah. Tokoh-tokoh seperti Bung Tomo membakar semangat arek-arek Suroboyo melalui siaran radio yang membahana.'",
          "",
          "KRISIS: 'Puncak pertempuran terjadi pada 10 November 1945, sekitar pukul 06.00 pagi. Sekutu melancarkan serangan darat, laut, dan udara. Ribuan pejuang gugur, tetapi tidak satu pun yang mundur. Bung Tomo terus berorasi melalui radio: \"Allahu Akbar! Allahu Akbar! Merdeka atau mati!\"'",
          "",
          "RESOLUSI: 'Meskipun kalah secara militer, perlawanan heroik rakyat Surabaya mengguncang dunia. Ratusan korban dari pihak Sekutu membuat Inggris mempertimbangkan ulang strateginya di Indonesia. Pertempuran ini menjadi simbol perjuangan kemerdekaan Indonesia.'",
          "",
          "KODA: 'Hari ini, setiap tanggal 10 November kita peringati sebagai Hari Pahlawan. Semangat arek-arek Suroboyo mengajarkan kita bahwa kemerdekaan bukan hadiah, melainkan hasil dari pengorbanan dan keberanian.'",
        ],
      },
      {
        judul: "Kaidah Kebahasaan Teks Cerita Sejarah",
        isi: [
          "Teks cerita sejarah memiliki ciri kebahasaan yang khas, berbeda dengan teks naratif biasa. Penguasaan kaidah ini akan membantumu menulis cerita sejarah yang autentik dan menarik.",
          "",
          "1. KONJUNGSI TEMPORAL",
          "  Kata hubung yang menunjukkan urutan waktu: sejak, sebelum, ketika, setelah, kemudian, lalu, akhirnya, pada akhirnya. Konjungsi ini membuat alur cerita terasa kronologis dan mengalir.",
          "",
          "  Contoh: 'Sejak 1942, Indonesia berada di bawah pendudukan Jepang. Setelah Jepang menyerah pada Agustus 1945, Indonesia memproklamasikan kemerdekaannya.'",
          "",
          "2. KATA KERJA MENTAL",
          "  Kata kerja yang berkaitan dengan aktivitas pikiran dan perasaan: memikirkan, merasakan, mengingat, berharap, memutuskan, merencanakan.",
          "",
          "  Contoh: 'Soekarno merenungkan nasib bangsanya. Ia memutuskan bahwa kemerdekaan harus segera diproklamasikan.'",
          "",
          "3. KATA KERJA MATERIAL",
          "  Kata kerja yang menunjukkan tindakan fisik: berperang, memproklamasikan, menandatangani, melawan, mengibarkan.",
          "",
          "4. PENGGUNAAN KATA GANTI ORANG KETIGA",
          "  Teks cerita sejarah umumnya menggunakan kata ganti orang ketiga: mereka, dia, ia, Beliau (untuk tokoh yang dihormati).",
          "",
          "5. KALIMAT MASA LAMPUN",
          "  Menggunakan bentuk lampau: 'Pada tahun 1945, Indonesia memproklamasikan kemerdekaannya' (bukan 'memproklamasikan' dalam konteks masa kini). Perhatikan penggunaan kata 'telah', 'sudah', 'pada masa itu'.",
          "",
          "6. FRASA ADVERBIA (KETERANGAN WAKTU DAN TEMPAT)",
          "  Detail keterangan waktu dan tempat sangat penting untuk memberikan konteks historis: 'di pelabuhan Tanjung Priok', 'pada dini hari tanggal 17 Agustus 1945', 'di ruang tengah rumah Laksamana Maeda'.",
          "",
          "[Ilustrasi: Buku sejarah terbuka dengan halaman kiri dan kanan. Dari halaman, huruf-huruf berterbangan membentuk kata-kata yang mewakili kaidah kebahasaan: 'sejak, ketika, kemudian' (konjungsi temporal), 'merenungkan, memutuskan' (kata kerja mental), 'berperang, mengibarkan' (kata kerja material). Gaya ilustrasi tipografi artistik dengan warna kuning tua dan cokelat.]",
        ],
        contoh: [
          "ANALISIS KAIDAH KEBAHASAAN DALAM KUTIPAN NOVEL 'BUMI MANUSIA':",
          "",
          "KUTIPAN:",
          "\"Malam itu, ketika dini hari mulai menepi, aku duduk di beranda rumah. Tidak bisa tidur. Pikiranku kalut. Minke — demikian panggilanku — belum genap berusia sembilan belas tahun, tapi sudah dihadapkan pada kenyataan yang begitu rumit. Di satu pihak, aku mengagumi Nyai Ontosoroh yang begitu cerdas dan mandiri. Di lain pihak, aku sadar bahwa masyarakat pribumi dipandang rendah oleh orang Eropa. Aku merasakan gejolak — antara kekaguman dan kemarahan.\"",
          "",
          "ANALISIS:",
          "",
          "Konjungsi temporal: 'ketika' — menunjukkan waktu (dini hari).",
          "Kata kerja mental: 'merasakan', 'mengagumi', 'sadar' — aktivitas batin tokoh.",
          "Kata ganti orang pertama: 'aku' — novel ini menggunakan sudut pandang orang pertama (Minke).",
          "Keterangan tempat: 'di beranda rumah' — memberi latar spesifik.",
          "Kalimat masa lampau: 'aku duduk', 'pikiranku kalut' — menceritakan peristiwa yang sudah berlalu.",
        ],
      },
      {
        judul: "Nilai-Nilai dalam Teks Cerita Sejarah",
        isi: [
          "Teks cerita sejarah tidak hanya menceritakan peristiwa, tetapi juga mengandung nilai-nilai yang dapat dipetik pembaca. Di kelas XII, kamu diharapkan mampu menganalisis dan mengaitkan nilai-nilai ini dengan kehidupan sehari-hari.",
          "",
          "NILAI-NILAI DALAM CERITA SEHARI-HARI:",
          "",
          "1. NILAI KEPAHLAWANAN",
          "  Keberanian, rela berkorban, dan pantang menyerah. Nilai ini tercermin dalam kisah para pahlawan seperti Pattimura, Cut Nyak Dien, atau pahlawan revolusi.",
          "  Relevansi hari ini: berani membela kebenaran di sekolah, berani mengakui kesalahan, tidak mudah menyerah dalam belajar.",
          "",
          "2. NILAI KEBANGSAAN / NASIONALISME",
          "  Cinta tanah air, bangga sebagai bangsa Indonesia, dan menjaga persatuan. Nilai ini muncul dalam cerita tentang Sumpah Pemuda, Proklamasi, dan perjuangan diplomasi.",
          "  Relevansi hari ini: menggunakan produk dalam negeri, melestarikan budaya, menjaga kerukunan antar teman yang berbeda suku/agama.",
          "",
          "3. NILAI KEMANUSIAAN",
          "  Menghormati hak asasi manusia, menjunjung keadilan, dan anti penindasan. Nilai ini sering muncul dalam cerita tentang kolonialisme dan perjuangan melawan ketidakadilan.",
          "  Relevansi hari ini: tidak membully teman, menghormati perbedaan, peduli terhadap sesama.",
          "",
          "4. NILAI PENDIDIKAN",
          "  Pentingnya ilmu pengetahuan dan pendidikan sebagai alat perjuangan. Tokoh seperti Soekarno, Hatta, Ki Hadjar Dewantara, dan RA Kartini adalah contoh nyata.",
          "  Relevansi hari ini: rajin belajar, mengejar ilmu setinggi mungkin, menggunakan pengetahuan untuk kemajuan bangsa.",
          "",
          "5. NILAI PERJUANGAN TANPA KEKERASAN",
          "  Beberapa tokoh sejarah seperti Mohandas Gandhi dan Ki Hadjar Dewantara mengajarkan bahwa perubahan bisa dicapai melalui jalan damai: pendidikan, diplomasi, dan perlawanan moral.",
          "",
          "[Ilustrasi: Kolase lima lingkaran yang masing-masing berisi simbol: perisai dan pedang (kepahlawanan), bendera merah putih (kebangsaan), dua tangan saling menggenggam (kemanusiaan), buku dan lilin (pendidikan), ranting zaitun dan tangan kosong (perjuangan damai). Setiap lingkaran terhubung ke lingkaran pusat bertuliskan 'NILAI SEJARAH'. Gaya ilustrasi infografis dengan warna merah, putih, biru, hijau, dan emas.]",
        ],
        contoh: [
          "CONTOH ANALISIS NILAI DALAM CERITA SEJARAH 'CUT NYAK DIAIN':",
          "",
          "KISAH SINGKAT:",
          "'Cut Nyak Dien, istri Teuku Umar, melanjutkan perjuangan setelah suaminya gugur. Dalam keadaan buta karena sakit, ia tetap memimpin pasukan gerilya melawan Belanda di pedalaman Aceh. Ia akhirnya ditangkap dan diasingkan ke Sumedang, Jawa Barat.'",
          "",
          "ANALISIS NILAI:",
          "",
          "1. Nilai Kepahlawanan: tidak menyerah meskipun buta dan sudah sepuh — 'pantang menyerah'.",
          "2. Nilai Kemanusiaan: perjuangannya melawan ketidakadilan kolonialisme.",
          "3. Nilai Emansipasi: sebagai perempuan Aceh yang memimpin laki-laki dalam perang — melampaui batasan gender zamannya.",
          "4. Relevansi hari ini: semangat Cut Nyak Dien bisa kita teladani dengan tidak membiarkan keterbatasan fisik menghalangi cita-cita.",
          "",
          "CONTOH ANALISIS NILAI DALAM LAGU 'BENDERA' (COLOUR):",
          "",
          "'Bangun pemudi pemuda Indonesia / Tangan melambai-lambai / Mulut tersenyum manis / Siap sedia untuk rela berkorban / Demi bangsaku yang tercinta'",
          "",
          "Analisis: Lagu ini mengandung nilai kebangsaan (cinta tanah air) dan nilai pengorbanan (rela berkorban untuk bangsa). Lagu ini tidak secara eksplisit bercerita tentang peristiwa tertentu, tetapi spiritualitas dan semangatnya merujuk pada perjuangan kemerdekaan.",
        ],
      },
    ],
    rangkuman: [
      "[Ilustrasi: Tangan seorang pemuda memegang buku sejarah yang terbuka. Dari halaman buku, muncul ilustrasi tiga dimensi peristiwa bersejarah: pembacaan proklamasi, pertempuran Surabaya, dan Sumpah Pemuda. Warna hangat keemasan menyinari adegan. Gaya ilustrasi surealis naratif dengan warna emas, merah, dan cokelat.]",
      "Teks cerita sejarah adalah teks yang memuat kisah peristiwa masa lampau, bisa berbentuk faktual (nonfiksi) maupun fiksional (novel, lagu, puisi).",
      "Struktur: orientasi → urutan peristiwa → krisis/konflik → resolusi → koda/reorientasi.",
      "Kaidah kebahasaan: konjungsi temporal, kata kerja mental, kata kerja material, kata ganti orang ketiga, kalimat masa lampau, frasa adverbia.",
      "Nilai-nilai dalam cerita sejarah: kepahlawanan, kebangsaan, kemanusiaan, pendidikan, dan perjuangan damai — semuanya relevan dengan kehidupan masa kini.",
    ],
  },
  latihan: makeSoal([
    ["Teks cerita sejarah dapat berbentuk faktual maupun fiksional. Contoh teks fiksional adalah...", ["Buku teks sejarah Indonesia", "Novel 'Bumi Manusia' karya Pramoedya Ananta Toer", "Dokumen arsip nasional", "Biodata pahlawan"], 1, "'Bumi Manusia' adalah novel fiksi yang berlatar sejarah, bukan teks faktual murni."],
    ["Bagian struktur teks cerita sejarah yang berisi simpulan dan amanat penulis disebut...", ["Orientasi", "Krisis", "Urutan peristiwa", "Koda"], 3, "Koda atau reorientasi adalah bagian penutup yang berisi simpulan, amanat, atau refleksi."],
    ["Konjungsi temporal adalah kata hubung yang menunjukkan...", ["Hubungan sebab-akibat", "Urutan waktu", "Hubungan perlawanan", "Hubungan penambahan"], 1, "Konjungsi temporal seperti 'sejak', 'ketika', 'setelah' menunjukkan urutan waktu."],
    ["Kata 'merenungkan' dan 'memutuskan' dalam teks cerita sejarah termasuk kategori...", ["Kata kerja material", "Kata kerja mental", "Kata sifat", "Konjungsi"], 1, "Kata kerja mental berkaitan dengan aktivitas pikiran, seperti 'merenungkan', 'memikirkan', 'memutuskan'."],
     ["Perbedaan utama antara teks cerita sejarah faktual dan fiksional adalah...", ["Faktual lebih panjang", "Fiksional tidak boleh mengandung fakta", "Faktual berdasarkan data dan dokumen, fiksional menggunakan imajinasi dengan latar fakta", "Fiksional lebih pendek"], 2, "Faktual berdasarkan data historis; fiksional menggunakan imajinasi untuk mengisi celah di antara fakta."],
    ["Nilai yang tercermin dalam kisah Cut Nyak Dien yang melanjutkan perjuangan meskipun buta adalah...", ["Nilai materiel", "Nilai kepahlawanan dan pantang menyerah", "Nilai ekonomi", "Nilai sosial"], 1, "Semangat Cut Nyak Dien yang tidak menyerah meskipun buta mencerminkan nilai kepahlawanan."],
    ["Fungsi orientasi dalam teks cerita sejarah adalah...", ["Menutup cerita", "Memperkenalkan latar waktu, tempat, dan tokoh", "Memberi simpulan", "Menceritakan krisis"], 1, "Orientasi berfungsi memperkenalkan latar cerita: waktu, tempat, suasana, dan tokoh."],
    ["Mengapa novel 'Bumi Manusia' dianggap sebagai karya sastra sejarah penting?", ["Karena novelnya tebal", "Karena berhasil memadukan fakta sejarah dengan kisah fiksi yang menyentuh", "Karena dilarang beredar", "Karena menang lomba"], 1, "Pramoedya berhasil memadukan fakta sejarah dengan narasi fiksi yang kuat sehingga pembaca merasakan sejarahnya."],
     ["'Pada 10 November 1945, pertempuran dahsyat pecah di Surabaya.' Kalimat ini mengandung unsur...", ["Fiksi", "Fakta sejarah", "Opini penulis", "Amanat"], 1, "Tanggal, tempat, dan peristiwa adalah fakta sejarah yang dapat diverifikasi."],
    ["Nilai yang mengajarkan pentingnya ilmu pengetahuan dan pendidikan sebagai alat perjuangan adalah...", ["Nilai kebangsaan", "Nilai pendidikan", "Nilai kemanusiaan", "Nilai kepahlawanan"], 1, "Nilai pendidikan menekankan pentingnya ilmu sebagai alat perjuangan, seperti yang dicontohkan Ki Hadjar Dewantara dan RA Kartini."],
  ]),
  praktik: {
    petunjuk: "Pilihlah satu peristiwa bersejarah di Indonesia (misalnya: Serangan Umum 1 Maret 1949, Konferensi Meja Bundar, Peristiwa G30S, Reformasi 1998, atau peristiwa sejarah di daerahmu). Tulislah teks cerita sejarah dengan struktur lengkap: orientasi, urutan peristiwa, krisis, resolusi, dan koda. Panjang minimal 500 kata. Sertakan minimal 3 fakta sejarah yang terverifikasi. Gunakan minimal 5 konjungsi temporal dan 3 kata kerja mental dalam tulisanmu.",
    tips: [
      "Cari referensi dari minimal 3 sumber berbeda untuk memverifikasi fakta (buku, artikel, video dokumenter, atau wawancara dengan saksi sejarah)",
      "Buat kerangka kronologis sebelum menulis — urutkan peristiwa dari awal hingga akhir",
      "Gunakan konjungsi temporal untuk membuat alur mengalir: 'sejak', 'ketika', 'setelah', 'kemudian', 'akhirnya'",
      "Sisipkan kata kerja mental untuk menghidupkan tokoh: 'ia merasakan', 'mereka memutuskan', 'para pemimpin merenungkan'",
      "Akhiri dengan koda yang menghubungkan peristiwa masa lalu dengan pelajaran untuk masa kini",
    ],
    contoh: "Teks cerita sejarah yang baik membuat pembaca merasa seperti menyaksikan langsung peristiwa tersebut. Gunakan detail sensorik (apa yang dilihat, didengar, dirasakan) untuk menghidupkan suasana. Misalnya: 'Asap mesiu memenuhi udara. Teriakan 'Merdeka!' bersahutan di antara deru pesawat Sekutu. Darah dan keringat bercampur di tanah Surabaya yang panas.'",
  },
  kuis: makeSoal([
    ["Dalam struktur teks cerita sejarah, puncak ketegangan disebut...", ["Orientasi", "Krisis", "Resolusi", "Koda"], 1, "Krisis adalah puncak ketegangan atau titik balik dalam cerita sejarah."],
    ["Kata kerja 'menandatangani', 'mengibarkan', 'berperang' termasuk jenis...", ["Kata kerja mental", "Kata kerja material", "Kata sifat", "Konjungsi"], 1, "Kata kerja material menunjukkan tindakan fisik: menandatangani, mengibarkan, berperang."],
    ["Peristiwa 'Rengasdengklok' dalam sejarah kemerdekaan Indonesia termasuk bagian struktur...", ["Orientasi", "Krisis", "Resolusi", "Koda"], 1, "Rengasdengklok adalah titik kritis ketika para pemuda menculik Soekarno-Hatta untuk mendesak proklamasi segera."],
    ["Nilai yang tercermin dari tokoh Ki Hadjar Dewantara yang mendirikan Taman Siswa adalah...", ["Nilai kepahlawanan fisik", "Nilai pendidikan dan perjuangan damai", "Nilai ekonomi", "Nilai politik"], 1, "Ki Hadjar Dewantara berjuang melalui pendidikan, bukan kekerasan — nilai pendidikan dan perjuangan damai."],
    ["Fungsi koda dalam teks cerita sejarah adalah...", ["Memperkenalkan tokoh", "Memberi amanat dan menghubungkan masa lalu dengan masa kini", "Menceritakan krisis", "Mengakhiri cerita tanpa pesan"], 1, "Koda adalah penutup yang berisi refleksi atau amanat, menghubungkan peristiwa masa lalu dengan relevansinya saat ini."],
    ["Manakah yang merupakan contoh konjungsi temporal?", ["Akan tetapi", "Oleh karena itu", "Setelah", "Di sisi lain"], 2, "'Setelah' adalah konjungsi temporal yang menunjukkan urutan waktu."],
    ["Perbedaan mendasar antara fakta dan fiksi dalam cerita sejarah adalah...", ["Fakta panjang, fiksi pendek", "Fakta dapat diverifikasi, fiksi merupakan imajinasi di celah fakta", "Fakta menarik, fiksi membosankan", "Tidak ada perbedaan"], 1, "Fakta sejarah dapat diverifikasi dari sumber, fiksi adalah imajinasi yang mengisi celah di antara fakta."],
     ["'Pada awal abad ke-20, Bung Hatta kecil sudah gemar membaca buku tentang pergerakan kemerdekaan.' Kalimat ini mengandung kata kerja...", ["Mental (gemar membaca)", "Material (membaca buku)", "Temporal (pada awal)", "Tidak ada"], 0, "'Gemar membaca' menunjukkan aktivitas mental — ketertarikan intelektual Hatta pada bacaan."],
    ["Contoh teks cerita sejarah yang bersifat fiksional adalah...", ["Buku 'Sejarah Nasional Indonesia'", "Novel 'Sang Pemimpi'", "Ensiklopedia", "Biografi resmi Soekarno"], 1, "'Sang Pemimpi' adalah novel fiksi — meskipun tidak berlatar sejarah perang, ia menceritakan kehidupan di Indonesia masa lalu yang bisa dikategorikan sebagai fiksi dengan latar sosial-historis."],
    ["Mengapa penting mempelajari cerita sejarah di kelas XII?", ["Karena diwajibkan kurikulum", "Agar kita bisa mengambil pelajaran dari masa lalu untuk menghadapi masa depan", "Agar bisa menghafal tanggal", "Supaya pandai bercerita"], 1, "Sejarah memberikan pelajaran berharga yang bisa diterapkan untuk menghadapi tantangan masa kini dan masa depan."],
  ]),
}

export default konten
