import type { Konten } from "../types"
import { makeSoal } from "../types"

const konten: Konten = {
  belajar: {
    tujuan: [
      "Memahami pengertian, unsur, dan jenis novel sebagai karya sastra",
      "Mengidentifikasi unsur intrinsik dan ekstrinsik novel secara mendalam",
      "Menganalisis nilai-nilai moral, sosial, dan budaya dalam novel",
      "Mengevaluasi teknik penceritaan dan gaya bahasa novelis Indonesia",
      "Menyusun resensi atau kritik sastra terhadap sebuah novel",
    ],
    materi: [
      {
        judul: "Mengenal Novel sebagai Karya Sastra",
        isi: [
          "Novel adalah salah satu bentuk karya sastra yang paling populer di dunia. Tidak seperti cerpen yang bisa dibaca sekali duduk, novel menawarkan perjalanan panjang — ratusan halaman — yang membawa pembaca menyelami kehidupan tokoh-tokohnya secara mendalam. Di kelas XII, kita akan mempelajari novel tidak hanya sebagai cerita, tetapi sebagai cermin masyarakat dan medium kritik sosial.",
          "",
          "Novel adalah karya fiksi prosa yang ditulis dalam bentuk naratif, dengan panjang tertentu (biasanya di atas 40.000 kata), yang menceritakan kisah tentang tokoh-tokoh dalam suatu latar dan alur yang kompleks.",
          "",
          "Jenis novel berdasarkan genre:",
          "",
          "1. NOVEL ROMANTIS — berfokus pada kisah cinta dan hubungan antartokoh",
          "  Contoh: 'Tenggelamnya Kapal Van der Wijck' (Hamka), 'Perahu Kertas' (Dee Lestari)",
          "",
          "2. NOVEL SEJARAH — berlatar belakang peristiwa sejarah",
          "  Contoh: 'Bumi Manusia' (Pramoedya Ananta Toer), 'Arus Balik' (Pramoedya)",
          "",
          "3. NOVEL SOSIAL — mengangkat isu-isu kemasyarakatan (kemiskinan, ketidakadilan, gender)",
          "  Contoh: 'Ronggeng Dukuh Paruk' (Ahmad Tohari), 'Laskar Pelangi' (Andrea Hirata)",
          "",
          "4. NOVEL PSIKOLOGIS — menyelami kejiwaan dan konflik batin tokoh",
          "  Contoh: 'Saman' (Ayu Utami), 'Ziarah' (Iwan Simatupang)",
          "",
          "5. NOVEL MISTIS/FANTASI — mengandung unsur supranatural atau dunia imajiner",
          "  Contoh: 'Pengakuan Pariyem' (Linus Suryadi AG), 'Supernova' (Dee Lestari)",
          "",
          "[Ilustrasi: Tumpukan novel berbagai warna dan ukuran. Dari sampul novel yang paling atas, muncul ilustrasi tiga dimensi: tokoh-tokoh yang keluar dari halaman, melayang di udara dengan ekspresi dan latar yang berbeda-beda. Gaya ilustrasi surealis buku terbang dengan warna-warna cerah yang hangat.]",
        ],
        contoh: [
          "PERBANDINGAN NOVEL DAN CERPEN:",
          "",
          "NOVEL 'BUMI MANUSIA' (531 halaman):",
          "- 20+ tokoh dengan perkembangan karakter yang kompleks",
          "- Alur majemuk: kehidupan Minke, Nyai Ontosoroh, Annelies, dan gerakan politik",
          "- Latar luas: Surabaya, Bojong, dan Hindia Belanda awal abad 20",
          "- Tema: kolonialisme, rasisme, emansipasi, dan nasionalisme",
          "- Membutuhkan waktu baca berhari-hari hingga berminggu-minggu",
          "",
          "CERPEN 'SENYUM KARYAMIN' (5 halaman):",
          "- 2-3 tokoh dengan karakter yang statis",
          "- Alur tunggal dan sederhana",
          "- Latar terbatas pada satu lokasi",
          "- Tema tunggal: ironi hidup",
          "- Dibaca sekali duduk dalam 15-30 menit",
        ],
        catatan: "Novel Indonesia modern dimulai pada awal abad ke-20 dengan terbitnya 'Sitti Nurbaya' (1922) oleh Marah Rusli. Novel ini dianggap sebagai novel pertama dalam sastra Indonesia modern. Menariknya, novel ini awalnya ditulis dalam bahasa Melayu dan menggunakan aksara Arab-Melayu (Jawi). Hingga saat ini, 'Sitti Nurbaya' tetap dikenang sebagai 'roman' klasik yang mengajarkan tentang perlawanan terhadap adat yang menindas.",
      },
      {
        judul: "Unsur Intrinsik Novel",
        isi: [
          "Untuk memahami novel secara mendalam, kamu perlu menganalisis unsur-unsur pembangunnya. Unsur intrinsik adalah unsur yang membangun novel dari dalam, yang langsung berkaitan dengan cerita.",
          "",
          "1. TEMA",
          "  Gagasan sentral atau ide pokok yang mendasari cerita. Tema novel bisa eksplisit (disebut langsung) atau implisit (tersirat). Contoh tema: ketidakadilan kolonial, perjuangan emansipasi perempuan, pencarian jati diri.",
          "",
          "2. ALUR (PLOT)",
          "  Rangkaian peristiwa yang membentuk cerita. Alur bisa:",
          "  - Maju (kronologis): A → B → C → D",
          "  - Mundur (flashback): A → C → B → D",
          "  - Campuran: maju dengan kilas balik",
          "  Alur yang kompleks bisa memiliki sub-plot (cerita sampingan) yang saling terkait.",
          "",
          "3. TOKOH DAN PENOKOHAN",
          "  Tokoh adalah pelaku dalam cerita. Penokohan adalah cara penggambaran watak tokoh. Metode penokohan:",
          "  - Analitik: langsung disebutkan pengarang ('ia adalah orang yang keras kepala')",
          "  - Dramatik: tersirat dari dialog, tindakan, dan pikiran tokoh",
          "  - Kontekstual: terlihat dari reaksi tokoh lain terhadapnya",
          "",
          "4. LATAR (SETTING)",
          "  Tempat, waktu, dan suasana terjadinya cerita. Latar dalam novel biasanya detail dan kompleks. Novel sejarah seperti 'Arus Balik' memiliki latar yang sangat detail — kota pelabuhan abad ke-16, pakaian, senjata, makanan, hingga sistem perdagangannya.",
          "",
          "5. SUDUT PANDANG (POINT OF VIEW)",
          "  Posisi pengarang dalam membawakan cerita: orang pertama ('aku'), orang ketiga serba tahu ('ia' yang tahu segalanya), atau orang ketiga terbatas (hanya tahu pikiran satu tokoh).",
          "",
          "6. GAYA BAHASA",
          "  Ciri khas pengarang dalam menggunakan bahasa — pilihan kata, majas, kalimat. Pramoedya cenderung realis-romantik, Ayu Utami puitis dan eksperimental, Andrea Hirata sederhana dan humoris.",
          "",
          "7. AMANAT",
          "  Pesan moral yang ingin disampaikan pengarang kepada pembaca. Bisa tersurat (jelas) atau tersirat (harus disimpulkan sendiri).",
          "",
          "[Ilustrasi: Diagram lingkaran dengan 7 segmen, masing-masing mewakili satu unsur intrinsik: TEMA (lampu), ALUR (panah berkelok), TOKOH (topeng), LATAR (rumah), SUDUT PANDANG (mata), GAYA BAHASA (pita kata), AMANAT (bintang). Di tengah lingkaran: 'NOVEL'. Gaya ilustrasi diagram kue dengan warna pelangi.]",
        ],
        contoh: [
          "ANALISIS UNSUR INTRINSIK NOVEL 'RANGGENG DUKUH PARUK' (Ahmad Tohari):",
          "",
          "TEMA: Dampak perubahan sosial-politik pada masyarakat tradisional. Novel ini menggambarkan bagaimana tragedi 1965 meluluhlantakkan sebuah desa kecil.",
          "",
          "ALUR: Alur maju dengan flashback. Dimulai dari masa kecil Srintil dan Rasus, berlanjut ke peristiwa G30S yang menghancurkan Dukuh Paruk.",
          "",
          "TOKOH UTAMA:",
          "- Srintil: gadis desa yang menjadi ronggeng, simbol seni dan gairah hidup",
          "- Rasus: pemuda yang mencintai Srintil, simbol rasionalitas dan perubahan",
          "- Sakarya: kakek Srintil, simbol keterikatan pada tradisi",
          "",
          "LATAR: Dukuh Paruk, desa kecil di Banyumas, Jawa Tengah. Waktu: 1950-an hingga 1965.",
          "",
          "SUDUT PANDANG: Orang ketiga serba tahu, tetapi fokus pada Rasus.",
          "",
          "GAYA BAHASA: Realis dengan sentuhan puitis. Ahmad Tohari menggunakan bahasa sederhana namun kaya akan metafora yang bersumber dari alam pedesaan.",
          "",
          "AMANAT: Tradisi dan modernitas bisa berbenturan dengan tragis. Kemanusiaan harus dijaga di tengah gejolak politik.",
        ],
      },
      {
        judul: "Unsur Ekstrinsik dan Nilai dalam Novel",
        isi: [
          "Selain unsur intrinsik, novel juga dipengaruhi oleh unsur dari luar — latar belakang pengarang, kondisi sosial-politik saat novel ditulis, dan nilai-nilai yang berkembang di masyarakat.",
          "",
          "UNSUR EKSTRINSIK NOVEL:",
          "",
          "1. LATAR BELAKANG PENGARANG",
          "  Biografi, pendidikan, pengalaman hidup, dan ideologi pengarang sangat memengaruhi karyanya. Pramoedya menulis 'Bumi Manusia' di dalam penjara Pulau Buru — itu menjelaskan mengapa tema penindasan begitu kuat dalam novelnya. Andrea Hirata menulis 'Laskar Pelangi' berdasarkan pengalaman masa kecilnya di Belitung.",
          "",
          "2. KONDISI SOSIAL-POLITIK",
          "  Novel tidak lahir dalam ruang hampa. Novel adalah produk zamannya. 'Ronggeng Dukuh Paruk' mencerminkan trauma pasca-1965. 'Saman' (Ayu Utami) lahir dari semangat reformasi. 'Norton' adalah novel yang lahir dari krisis moneter 1998.",
          "",
          "3. NILAI-NILAI SOSIAL",
          "  Novel mengajarkan nilai-nilai yang berlaku dalam masyarakat: gotong royong, kesetiaan, keadilan, atau sebaliknya — kritik terhadap nilai yang menindas. Novel membentuk kesadaran sosial pembacanya.",
          "",
          "4. NILAI-NILAI BUDAYA",
          "  Novel mencerminkan budaya suatu masyarakat. 'Ronggeng Dukuh Paruk' memperkenalkan tradisi ronggeng di Banyumas. 'Ngrambat' dan 'Laskar Pelangi' menampilkan budaya Melayu Belitung. Novel membuka jendela ke dunia budaya yang mungkin asing bagi pembaca.",
          "",
          "5. NILAI MORAL DAN SPIRITUAL",
          "  Novel sering mengandung pertanyaan-pertanyaan moral: Apa yang benar dan salah? Apa arti pengorbanan? Apa makna hidup? Novel religius seperti 'Ayat-Ayat Cinta' (Habiburrahman El Shirazy) mengangkat tema spiritual secara eksplisit.",
          "",
          "[Ilustrasi: Buku novel terbuka di tengah. Dari sisi kiri buku, gambar pena dan foto pengarang (latar belakang pengarang). Dari sisi kanan, gambar koran dengan berita politik dan kerumunan orang (kondisi sosial-politik). Dari atas, ikon-ikon: gotong royong, tarian tradisional, dan hati (nilai sosial, budaya, moral). Gaya ilustrasi konseptual dengan warna cokelat, biru, dan emas.]",
        ],
        contoh: [
          "ANALISIS NILAI EKSTRINSIK NOVEL 'LASIKAR PELANGI' (Andrea Hirata):",
          "",
          "LATAR BELAKANG PENGARANG:",
          "Andrea Hirata lahir dan besar di Belitung, provinsi termiskin di Indonesia pada zamannya. Ia bersekolah di SD Muhammadiyah yang hampir tutup karena kekurangan murid. Pengalaman ini menjadi inspirasi 'Laskar Pelangi'.",
          "",
          "KONDISI SOSIAL-POLITIK:",
          "Novel ini menggambarkan Indonesia era 1970-an di daerah tertinggal. Kemiskinan, keterbatasan akses pendidikan, dan perjuangan guru-guru yang heroik.",
          "",
          "NILAI YANG TERKANDUNG:",
          "1. Nilai Pendidikan: 'pendidikan adalah satu-satunya jalan keluar dari kemiskinan'",
          "2. Nilai Sosial: persahabatan lintas latar belakang, gotong royong",
          "3. Nilai Budaya: kehidupan masyarakat Melayu Belitung, tradisi lisan, mitos setempat",
          "4. Nilai Moral: kejujuran, kerja keras, pantang menyerah",
          "5. Nilai Spiritual: keyakinan bahwa Allah tidak akan membiarkan hamba-Nya yang berjuang",
        ],
      },
      {
        judul: "Teknik Penceritaan dan Gaya Bahasa Novel",
        isi: [
          "Setiap novelis memiliki teknik penceritaan dan gaya bahasa yang khas. Mengenali teknik ini akan membantumu mengapresiasi novel dengan lebih baik dan mengembangkan kemampuan menulismu sendiri.",
          "",
          "TEKNIK PENCERITAAN:",
          "",
          "1. TEKNIK STREAM OF CONSCIOUSNESS (Arus Kesadaran)",
          "  Menyajikan pikiran tokoh secara langsung, tanpa filter, seperti pikiran yang mengalir bebas. Dipopulerkan oleh James Joyce, Virginia Woolf. Di Indonesia, Ayu Utami menggunakan teknik ini dalam 'Saman'.",
          "",
          "2. TEKNIK EPISTOLER",
          "  Novel disusun dari kumpulan surat, catatan harian, atau dokumen. Contoh: 'Bumi Manusia' sering menggunakan surat sebagai media pengembangan cerita.",
          "",
          "3. TEKNIK BINGKAI (FRAME STORY)",
          "  Cerita di dalam cerita. Seorang tokoh bercerita kepada tokoh lain, dan di dalam cerita itu ada cerita lagi. Contoh: 'The Thousand and One Nights', pengaruhnya terlihat pada beberapa novel Indonesia.",
          "",
          "4. TEKNIK NON-LINEAR",
          "  Alur tidak kronologis, melompat-lompat antara masa lalu, sekarang, dan masa depan. Membutuhkan konsentrasi lebih dari pembaca.",
          "",
          "GAYA BAHASA NOVELIS INDONESIA:",
          "",
          "  - PRAMOEDYA ANANTA TOER: bahasa realis yang kaya akan detail historis, kalimat kompleks, dan narasi yang menggugah",
          "  - ANDREA HIRATA: bahasa sederhana, humoris, puitis, mudah dicerna, kaya akan metafora sehari-hari",
          "  - AYU UTAMI: bahasa eksperimental, padat, simbolis, sering menggunakan bahasa Inggris dan istilah asing",
          "  - HAMKA: bahasa Melayu klasik yang indah, penuh pepatah dan petuah, gaya naratif yang mengalir",
          "  - SENO GUMIRA AJIDARMA: bahasa surealis, absurd, dan sering mengaburkan batas realitas dan mimpi",
          "",
          "[Ilustrasi: Sebuah meja penulis di malam hari dengan mesin tik, lampu minyak, tumpukan kertas, dan foto-foto penulis terkenal di dinding. Dari halaman yang setengah jadi di mesin tik, kata-kata berterbangan dan membentuk gambar-gambar abstrak. Gaya ilustrasi surealis dengan warna biru malam dan kuning lampu.]",
        ],
        contoh: [
          "PERBANDINGAN GAYA BAHASA DUA NOVELIS:",
          "",
          "PRAMOEDYA ANANTA TOER (dari 'Bumi Manusia'):",
          "'Oh, wanita itu, ia telah menjadikan aku manusia, lahir batin. Dari padanya aku mendapat tidak hanya nama, tetapi juga watak. Ia yang memberi aku hidup. Dan novel yang ia berikan padaku adalah kehidupan itu sendiri.'",
          "Ciri: kalimat panjang, emosional, puitis, mengalir seperti sungai.",
          "",
          "ANDREA HIRATA (dari 'Laskar Pelangi'):",
          "'Kami sepuluh orang. Melawan kemiskinan dan keterbatasan dengan senjata tekad dan mimpi. Di sekolah yang hampir roboh itu, kami belajar bahwa kemiskinan bukan penghalang untuk bermimpi setinggi langit.'",
          "Ciri: kalimat pendek, bersemangat, mudah diingat, optimistis.",
          "",
          "",
          "CONTOH TEKNIK STREAM OF CONSCIOUSNESS:",
          "'Kenapa ia pergi — tidak — ia tersenyum — itu senyum palsu — ataukah aku yang salah lihat — lampu temaram — kopi pahit — jam dinding berdetak — pukul dua belas — ia tidak akan kembali — tidak akan pernah — ah, sudahlah.'",
          "Ciri: tanpa tanda baca yang rapi, pikiran melompat, asosiatif.",
        ],
      },
    ],
    rangkuman: [
      "[Ilustrasi: Sebuah perpustakaan dengan rak-rak tinggi penuh novel. Di tengah ruangan, sebuah meja bundar dengan beberapa novel terbuka. Lampu gantung kuningan menerangi meja. Tiga orang duduk membaca — satu anak muda, satu dewasa, satu lanjut usia — menunjukkan novel menyatukan lintas generasi. Gaya ilustrasi perpustakaan hangat dengan warna cokelat kayu dan emas.]",
      "Novel adalah karya fiksi prosa panjang yang menceritakan kisah dengan tokoh, alur, dan latar yang kompleks. Jenis: romantis, sejarah, sosial, psikologis, fantasi.",
      "Unsur intrinsik: tema, alur, tokoh/penokohan, latar, sudut pandang, gaya bahasa, amanat.",
      "Unsur ekstrinsik: latar belakang pengarang, kondisi sosial-politik, nilai sosial, budaya, moral, spiritual.",
      "Teknik penceritaan: arus kesadaran, epistoler, bingkai, non-linear. Gaya bahasa setiap novelis unik — Pramoedya realis-historis, Hirata sederhana-puitis, Ayu Utami eksperimental.",
    ],
  },
  latihan: makeSoal([
    ["Novel 'Bumi Manusia' termasuk jenis novel...", ["Romantis", "Sejarah", "Psikologis", "Fantasi"], 1, "'Bumi Manusia' adalah novel sejarah yang berlatar awal abad ke-20 di Hindia Belanda."],
    ["Unsur intrinsik yang berkaitan dengan rangkaian peristiwa dalam novel adalah...", ["Tema", "Alur", "Tokoh", "Amanat"], 1, "Alur atau plot adalah rangkaian peristiwa yang membentuk cerita."],
    ["Yang BUKAN merupakan metode penokohan adalah...", ["Analitik", "Dramatik", "Kontekstual", "Ilustratif"], 3, "Metode penokohan: analitik (langsung disebut), dramatik (tersirat), kontekstual (reaksi tokoh lain). 'Ilustratif' bukan metode penokohan."],
    ["Novel 'Ronggeng Dukuh Paruk' mengandung unsur ekstrinsik berupa...", ["Latar belakang pengarang sebagai wartawan", "Kondisi sosial-politik pasca-1965", "Teknik stream of consciousness", "Penggunaan bahasa Inggris"], 1, "'Ronggeng Dukuh Paruk' mencerminkan trauma dan dampak sosial-politik pasca-peristiwa 1965."],
    ["Gaya bahasa Andrea Hirata dalam 'Laskar Pelangi' dikenal...", ["Kompleks dan akademis", "Sederhana, humoris, dan puitis", "Eksperimental dan surealis", "Klasik dan formal"], 1, "Andrea Hirata menggunakan bahasa sederhana, humoris, dan puitis dengan metafora sehari-hari."],
    ["Novel pertama dalam sastra Indonesia modern adalah...", ["'Bumi Manusia'", "'Sitti Nurbaya'", "'Laskar Pelangi'", "'Tenggelamnya Kapal Van der Wijck'"], 1, "'Sitti Nurbaya' (1922) oleh Marah Rusli dianggap sebagai novel pertama sastra Indonesia modern."],
    ["Perbedaan utama novel dan cerpen terletak pada...", ["Novel lebih mahal", "Kompleksitas cerita, jumlah tokoh, dan panjang narasi", "Novel tidak bergambar", "Novel lebih mudah dibaca"], 1, "Novel memiliki kompleksitas lebih tinggi, lebih banyak tokoh, alur lebih rumit, dan lebih panjang."],
    ["Teknik penceritaan yang menyajikan pikiran tokoh secara langsung tanpa filter disebut...", ["Epistoler", "Stream of consciousness", "Bingkai", "Non-linear"], 1, "Stream of consciousness atau arus kesadaran menyajikan aliran pikiran tokoh secara langsung."],
    ["Nilai pendidikan dalam 'Laskar Pelangi' tercermin dalam pesan...", ["'Kaya raya itu penting'", "'Pendidikan adalah jalan keluar dari kemiskinan'", "'Ikuti tradisi leluhur'", "'Bekerjalah untuk pemerintah'"], 1, "Pesan sentral novel ini adalah bahwa pendidikan dapat mengubah nasib."],
    ["Fungsi latar belakang pengarang dalam analisis novel adalah...", ["Menambah panjang resensi", "Membantu memahami perspektif dan ideologi yang memengaruhi karya", "Membuat novel lebih menarik", "Menentukan harga novel"], 1, "Latar belakang pengarang membantu memahami mengapa novel ditulis dengan cara tertentu dan pesan apa yang ingin disampaikan."],
  ]),
  praktik: {
    petunjuk: "Pilihlah satu novel Indonesia yang sudah kamu baca (atau baca novel baru minimal 150 halaman). Tulislah analisis sastra lengkap yang mencakup: (1) identitas novel (judul, pengarang, penerbit, tahun terbit, tebal), (2) sinopsis singkat (200-300 kata), (3) analisis unsur intrinsik (tema, alur, tokoh dan penokohan, latar, sudut pandang, gaya bahasa, amanat), (4) analisis unsur ekstrinsik (latar belakang pengarang, kondisi sosial saat novel ditulis, nilai-nilai yang terkandung), dan (5) simpulan dan penilaian pribadi kamu terhadap novel tersebut.",
    tips: [
      "Baca novel dua kali — pertama untuk menikmati cerita, kedua untuk menganalisis unsur-unsurnya",
      "Catat kutipan-kutipan penting yang mendukung analisismu",
      "Untuk analisis latar belakang pengarang, cari biografi singkat dan wawancara dengan pengarang",
      "Gunakan contoh kutipan langsung dari novel untuk memperkuat setiap poin analisismu",
      "Jangan lupa mencantumkan nilai-nilai yang bisa dipetik — novel yang baik selalu mengajarkan sesuatu",
    ],
    contoh: "Analisis novel yang baik tidak sekadar mendeskripsikan, tetapi menginterpretasi. Misalnya, jangan hanya menyebut 'tema novel ini adalah persahabatan', tetapi jelaskan 'bagaimana persahabatan digambarkan melalui konflik dan perkembangan tokoh, dan apa yang ingin dikatakan pengarang tentang persahabatan melalui karyanya'. Semakin dalam interpretasi, semakin baik analisismu.",
  },
  kuis: makeSoal([
    ["Unsur intrinsik novel yang berkaitan dengan pesan yang ingin disampaikan pengarang adalah...", ["Tema", "Alur", "Amanat", "Sudut pandang"], 2, "Amanat adalah pesan moral yang ingin disampaikan pengarang kepada pembaca."],
    ["Novel 'Saman' karya Ayu Utami menggunakan teknik penceritaan...", ["Epistoler", "Stream of consciousness", "Bingkai", "Linier"], 1, "Ayu Utami dikenal menggunakan teknik arus kesadaran (stream of consciousness) dengan bahasa eksperimental."],
    ["Yang dimaksud dengan sudut pandang orang pertama dalam novel adalah...", ["Pengarang serba tahu", "Tokoh 'aku' yang menjadi pusat cerita", "Narator di luar cerita", "Tokoh sampingan yang bercerita"], 1, "Sudut pandang orang pertama menggunakan tokoh 'aku' sebagai narator dan pusat kesadaran."],
    ["Faktor ekstrinsik yang paling memengaruhi novel 'Laskar Pelangi' adalah...", ["Pendidikan pengarang di Belitung yang miskin", "Peristiwa politik 1965", "Pengaruh sastra Barat", "Teknologi penerbitan"], 0, "Andrea Hirata menulis berdasarkan pengalaman masa kecilnya di Belitung yang tertinggal."],
    ["Gaya bahasa yang khas dari Pramoedya Ananta Toer adalah...", ["Sederhana dan humoris", "Realis dengan detail historis yang kaya", "Surealis dan absurd", "Eksperimental dan padat"], 1, "Pramoedya dikenal dengan gaya realis yang kaya akan detail sejarah dan kalimat yang menggugah."],
    ["Perbedaan alur maju dan alur mundur adalah...", ["Alur maju lebih panjang", "Maju kronologis A→B→C, mundur menggunakan flashback", "Alur maju membosankan", "Maju untuk novel, mundur untuk cerpen"], 1, "Alur maju bergerak maju secara kronologis, alur mundur menggunakan kilas balik."],
    ["Nilai budaya dalam 'Ronggeng Dukuh Paruk' ditunjukkan melalui...", ["Teknologi modern", "Tradisi ronggeng di Banyumas", "Sistem politik", "Gaya berpakaian Eropa"], 1, "Novel ini kaya akan penggambaran tradisi ronggeng, kesenian khas Banyumas."],
    ["Metode penokohan yang menggambarkan watak melalui dialog dan tindakan disebut...", ["Analitik", "Dramatik", "Kontekstual", "Langsung"], 1, "Penokohan dramatik: watak tersirat dalam dialog, tindakan, dan pikiran tokoh."],
    ["Fungsi sub-plot (cerita sampingan) dalam novel adalah...", ["Memperpanjang halaman", "Memperkaya cerita dan memberikan dimensi tambahan pada tema utama", "Membingungkan pembaca", "Menggantikan alur utama"], 1, "Sub-plot memperkaya cerita dan memberikan dimensi tambahan yang mendukung tema utama."],
    ["\"Sitti Nurbaya\" dianggap sebagai novel pertama sastra Indonesia modern karena...", ["Ditulis dalam bahasa Belanda", "Menjadi pelopor bentuk novel modern dalam bahasa Melayu/Indonesia", "Paling laris", "Paling tebal"], 1, "Sitti Nurbaya (1922) adalah novel pertama yang menggunakan bahasa Melayu/Indonesia dengan bentuk novel modern."],
  ]),
}

export default konten
