import type { Konten } from "../types"
import { makeSoal } from "../types"

const konten: Konten = {
  belajar: {
    tujuan: [
      "Memahami pengertian, ciri, dan jenis artikel ilmiah populer",
      "Mengidentifikasi struktur dan kaidah kebahasaan artikel",
      "Menganalisis keefektifan argumen dan data dalam artikel",
      "Menyusun artikel ilmiah populer dengan topik aktual dan data pendukung",
      "Mempublikasikan artikel di media cetak, online, atau jurnal siswa",
    ],
    materi: [
      {
        judul: "Apa Itu Artikel?",
        isi: [
          "Setiap hari kita membaca artikel — di portal berita, majalah, blog, atau media sosial. Artikel adalah tulisan yang paling sering kita konsumsi di era digital. Tapi apakah kamu tahu apa yang membedakan artikel berkualitas dengan tulisan biasa? Di kelas XII, kita akan mempelajari artikel bukan hanya sebagai bacaan, tetapi sebagai medium untuk menyampaikan gagasan ilmiah secara populer.",
          "",
          "Artikel adalah karangan faktual yang lengkap dengan panjang tertentu (biasanya 500-5000 kata) yang dibuat untuk dimuat di media massa (koran, majalah, portal berita, jurnal) dan membahas suatu masalah secara mendalam. Artikel bersifat faktual dan informatif, tetapi ditulis dengan gaya yang menarik agar mudah dipahami khalayak umum.",
          "",
          "Jenis artikel berdasarkan isi:",
          "",
          "1. ARTIKEL ILMIAH",
          "  Artikel yang didasarkan pada penelitian atau kajian akademis. Biasanya dimuat di jurnal ilmiah. Menggunakan metodologi yang ketat, bahasa formal, dan struktur yang baku (abstrak, pendahuluan, metode, hasil, pembahasan, simpulan).",
          "",
          "2. ARTIKEL ILMIAH POPULER",
          "  Artikel yang membahas topik ilmiah/akademis tetapi ditulis dengan bahasa yang populer — mudah dipahami masyarakat umum. Inilah jenis yang paling sering kita temui di koran, majalah, dan portal berita seperti Kompas, Tempo, atau The Conversation.",
          "",
          "3. ARTIKEL OPINI",
          "  Artikel yang berisi pendapat pribadi penulis tentang suatu isu. Mirip dengan editorial, tetapi opini adalah suara individu (mencantumkan nama penulis), bukan suara media.",
          "",
          "4. ARTIKEL FEATURE",
          "  Artikel yang lebih mendalam, biasanya tentang profil tokoh, liputan khusus, atau kisah di balik suatu peristiwa. Gaya penulisan lebih naratif dan sastra.",
          "",
          "[Ilustrasi: Sebuah smartphone dan laptop menampilkan portal berita dengan berbagai artikel. Di sampingnya, koran cetak terbuka di halaman opini. Latar belakang meja kafe dengan secangkir kopi. Gaya ilustrasi kehidupan digital dengan warna hijau toska dan putih.]",
        ],
        contoh: [
          "PERBANDINGAN JENIS ARTIKEL PADA TOPIK YANG SAMA:",
          "",
          "TOPIK: Dampak Media Sosial pada Remaja",
          "",
          "ARTIKEL ILMIAH (jurnal):",
          "'Penelitian ini bertujuan untuk menganalisis korelasi antara durasi penggunaan media sosial dan tingkat kecemasan pada remaja usia 13-17 tahun. Metode yang digunakan adalah survei kuantitatif dengan 500 responden di 5 SMA Negeri Jakarta. Hasil uji regresi menunjukkan korelasi positif signifikan (r=0.67, p<0.01)...'",
          "✓ Formal, metodologis, untuk akademisi.",
          "",
          "ARTIKEL ILMIAH POPULER (Kompas):",
          "'Remaja zaman sekarang lahir dengan smartphone di tangan. Tapi di balik kemudahan bersosialisasi, ada ancaman yang mengintai. Sebuah penelitian terbaru menemukan bahwa remaja yang menghabiskan lebih dari 4 jam sehari di media sosial cenderung mengalami kecemasan 40% lebih tinggi dibandingkan mereka yang hanya 1 jam. Kenapa bisa begitu?'",
          "✓ Ilmiah tapi populer, untuk masyarakat umum.",
          "",
          "ARTIKEL OPINI:",
          "'Sebagai seorang guru yang setiap hari berhadapan dengan remaja, saya prihatin melihat perubahan perilaku siswa pasca-pandemi. Mereka lebih asyik dengan ponsel daripada berinteraksi langsung. Saya berpendapat bahwa perlu ada batasan penggunaan media sosial di lingkungan sekolah.'",
          "✓ Opini pribadi, argumentatif, personal.",
        ],
        catatan: "Di era digital, genre artikel mengalami evolusi. Muncul istilah 'longform article' (artikel panjang 2000-5000 kata) dan 'listicle' (artikel berbentuk daftar). Keduanya populer karena algoritma media sosial menyukai konten yang 'menggulir' (scrollable). Namun, kualitas artikel tetaplah yang utama — data yang valid, analisis yang tajam, dan gaya penulisan yang menarik. Jurnalisme berkualitas justru semakin dihargai di tengah banjir informasi dangkal.",
      },
      {
        judul: "Struktur dan Sistematika Artikel",
        isi: [
          "Artikel yang baik memiliki struktur yang memudahkan pembaca mengikuti alur pemikiran penulis. Meskipun tidak serumit karya tulis ilmiah, artikel tetap harus terorganisir dengan rapi.",
          "",
          "Berikut struktur umum artikel ilmiah populer:",
          "",
          "1. JUDUL (HEADLINE)",
          "  Judul adalah 'pintu masuk' artikel. Judul yang baik harus menarik perhatian, informatif, dan mencerminkan isi artikel. Panjang ideal: 5-12 kata. Judul bisa berupa pernyataan, pertanyaan, atau pernyataan yang menggugah rasa penasaran.",
          "",
          "  Contoh: 'Darurat Literasi Digital di Kalangan Remaja' (pernyataan)",
          "  Contoh: 'Siapa yang Bertanggung Jawab atas Polusi Udara Jakarta?' (pertanyaan)",
          "",
          "2. TERAS (LEAD)",
          "  Paragraf pembuka yang sangat penting. Lead harus mampu menarik pembaca untuk terus membaca. Lead yang baik menjawab 5W+1H secara ringkas atau menyajikan 'hook' yang kuat — fakta mengejutkan, anekdot menarik, atau pertanyaan retoris.",
          "",
          "  Lead yang buruk: 'Dalam artikel ini, saya akan membahas tentang pentingnya literasi digital.'",
          "  Lead yang baik: 'Tahukah kamu bahwa 78% remaja Indonesia tidak bisa membedakan berita asli dan hoaks? Angka ini menempatkan Indonesia di peringkat keempat dunia dalam kerentanan informasi palsu.'",
          "",
          "3. ISI / BADAN ARTIKEL",
          "  Bagian utama yang mengembangkan gagasan penulis. Terdiri dari beberapa sub-bagian dengan argumen, data, fakta, contoh, dan analisis. Setiap paragraf harus mendukung satu gagasan utama.",
          "",
          "  Struktur isi yang efektif:",
          "  - Mulai dengan argumen terkuat",
          "  - Berikan data dan fakta pendukung",
          "  - Sertakan contoh konkret atau kasus nyata",
          "  - Antisipasi dan bantah argumen lawan (jika ada)",
          "  - Akhiri dengan analisis atau kesimpulan parsial",
          "",
          "4. PENUTUP",
          "  Bagian akhir yang merangkum argumen utama dan memberikan kesimpulan atau rekomendasi. Penutup yang kuat meninggalkan kesan mendalam pada pembaca — bisa berupa ajakan, pertanyaan reflektif, atau pernyataan visioner.",
          "",
          "[Ilustrasi: Diagram struktur artikel dengan 4 lapisan vertikal: JUDUL (paling atas, besar), TERAS (sedikit lebih kecil), ISI/BADAN (yang terbesar, beberapa sub-bagian), PENUTUP (paling bawah, ringkas). Setiap lapisan diwarnai gradasi biru dari gelap ke terang. Gaya ilustrasi infografis piramida dengan warna biru dan putih.]",
        ],
        contoh: [
          "CONTOH STRUKTUR ARTIKEL LENGKAP:",
          "",
          "JUDUL: 'Ketika Teknologi Mengancam Konsentrasi Belajar Generasi Z'",
          "",
          "LEAD:",
          "'Notifikasi media sosial berbunyi setiap 12 menit. Pesan WhatsApp masuk tanpa henti. Video TikTok bergulir tanpa akhir. Di tengah hiruk-pikuk digital ini, bagaimana mungkin seorang remaja bisa fokus belajar? Sebuah studi dari Harvard University tahun 2025 mengungkapkan fakta mengejutkan: rata-rata perhatian manusia telah menurun dari 12 detik pada tahun 2000 menjadi hanya 6 detik pada tahun 2025 — lebih pendek dari ingatan ikan mas!'",
          "",
          "ISI (paragraf kedua):",
          "'Fenomena ini bukan tanpa akibat. Nilai rata-rata ujian nasional untuk kemampuan literasi terus menurun dalam 5 tahun terakhir. Guru-guru melaporkan bahwa siswa semakin sulit membaca teks panjang. Seorang guru Bahasa Indonesia di SMA Negeri 3 Jakarta mengatakan, 'Siswa saya panik jika disuruh membaca novel setebal 200 halaman. Mereka terbiasa dengan teks pendek di media sosial.' '",
          "",
          "ISI (paragraf ketiga — data dan analisis):",
          "'Data dari Kementerian Pendidikan menunjukkan bahwa hanya 30% siswa SMA yang memiliki kebiasaan membaca buku nonteks pelajaran. Sisanya lebih memilih menonton video atau scrolling media sosial. Padahal, membaca buku melatih konsentrasi mendalam (deep focus) yang tidak bisa digantikan oleh konsumsi konten pendek.'",
          "",
          "PENUTUP:",
          "'Teknologi bukanlah musuh. Tapi seperti pisau, ia bisa bermanfaat atau berbahaya tergantung penggunanya. Sudah saatnya kita — orang tua, guru, dan siswa — bersama-sama menciptakan keseimbangan antara dunia digital dan dunia nyata. Karena konsentrasi adalah superpower di era distraksi.'",
        ],
      },
      {
        judul: "Kaidah Kebahasaan dan Data dalam Artikel",
        isi: [
          "Artikel ilmiah populer memiliki kaidah kebahasaan yang khas: ia harus ilmiah tetapi tetap bisa dicerna oleh pembaca awam. Menulis artikel yang 'ilmiah tapi populer' adalah keterampilan yang membutuhkan latihan.",
          "",
          "1. BAHASA FORMAL-FLEKSIBEL",
          "  Artikel ilmiah populer menggunakan bahasa Indonesia baku, tetapi tidak sekaku bahasa jurnal ilmiah. Boleh menggunakan majas, analogi, atau gaya bercerita. Yang penting: mudah dipahami.",
          "",
          "  Perbandingan:",
          "  - Jurnal ilmiah: 'Berdasarkan hasil analisis data, terdapat korelasi signifikan...'",
          "  - Artikel populer: 'Penelitian membuktikan bahwa keduanya saling terkait erat...'",
          "",
          "2. DATA DAN FAKTA",
          "  Artikel yang baik didukung oleh data dan fakta. Sumber data harus jelas dan kredibel: penelitian, laporan resmi, pernyataan ahli, statistik pemerintah. Data membuat artikel lebih meyakinkan.",
          "",
          "  Sumber data kredibel: BPS, Kementerian, WHO, UNESCO, jurnal akademik bereputasi, lembaga riset independen",
          "  Sumber data perlu dihindari: blog pribadi, media sosial tanpa verifikasi, opini tanpa dasar",
          "",
          "3. KALIMAT EFEKTIF",
          "  Gunakan kalimat aktif dan langsung. Hindari kalimat bertele-tele. Satu ide = satu paragraf. Variasikan panjang kalimat untuk menjaga ritme bacaan.",
          "",
          "4. ISTILAH TEKNIS DENGAN PENJELASAN",
          "  Artikel boleh menggunakan istilah teknis, tetapi harus dijelaskan agar pembaca awam paham. Contoh: 'Inflasi — yaitu kenaikan harga barang secara umum — telah mencapai 5,5% tahun ini.'",
          "",
          "5. KOHERENSI ANTARPARAGRAF",
          "  Gunakan konjungsi dan kata transisi untuk menghubungkan paragraf: 'Tidak hanya itu...', 'Di sisi lain...', 'Lebih jauh lagi...', 'Data terbaru menunjukkan...'",
          "",
          "[Ilustrasi: Sebuah artikel di layar laptop dengan beberapa bagian dilingkari dan diberi label: DATA (lingkaran merah — bagian dengan angka statistik), ISTILAH (lingkaran biru — kata teknis yang dijelaskan), KALIMAT EFEKTIF (lingkaran hijau — kalimat pendek dan jelas). Kaca pembesar di atas area data. Gaya ilustrasi layar komputer dengan warna biru dan hijau.]",
        ],
        contoh: [
          "CARA MENYAJIKAN DATA DALAM ARTIKEL:",
          "",
          "KURANG BAIK:",
          "'Banyak remaja yang kecanduan gadget. Ini masalah serius.'",
          "✗ Terlalu umum, tidak ada data, tidak meyakinkan.",
          "",
          "CUKUP:",
          "'Berdasarkan survei Kominfo tahun 2025, 65% remaja Indonesia menggunakan smartphone lebih dari 6 jam sehari.'",
          "✓ Ada data, ada sumber, tetapi tidak ada analisis.",
          "",
          "BAIK:",
          "'Data Kominfo tahun 2025 menunjukkan bahwa 65% remaja Indonesia menggunakan smartphone lebih dari 6 jam sehari. Jika dirata-rata, waktu tidur remaja Indonesia hanya 5,8 jam per hari — di bawah rekomendasi WHO yang 8-10 jam. Artinya, remaja Indonesia menghabiskan lebih banyak waktu di depan layar daripada waktu tidur mereka! Ini ironi yang perlu kita sadari bersama.'",
          "✓ Data jelas + analisis + perbandingan + implikasi.",
          "",
          "",
          "CONTOH LEAD DENGAN DATA:",
          "'Bayangkan: dalam satu menit, 500 jam konten diunggah ke YouTube, 66.000 foto diunggah ke Instagram, dan 6.000 twit dikirim di X (Twitter). Di tengah tsunami konten ini, bagaimana cara kita memastikan bahwa yang kita konsumsi adalah informasi yang benar?'",
        ],
      },
      {
        judul: "Teknik Menulis Artikel yang Menarik",
        isi: [
          "Menulis artikel yang baik adalah keterampilan yang bisa dipelajari. Berikut adalah teknik-teknik yang digunakan penulis profesional untuk membuat artikel mereka dibaca hingga tuntas.",
          "",
          "PENTING: Di era digital, rata-rata pembaca hanya menghabiskan 37 detik untuk membaca artikel. Kamu harus bisa menarik mereka dalam 37 detik pertama!",
          "",
          "TEKNIK 1 — HOOK YANG KUAT",
          "  Mulai dengan sesuatu yang mengejutkan, provokatif, atau menyentuh. Fakta mengejutkan, pertanyaan yang menggugah, atau kutipan yang kuat. Lead adalah satu-satunya kesempatanmu untuk membuat pembaca tidak menutup halaman.",
          "",
          "  Contoh hook: 'Kamu mungkin tidak menyadari, tapi setiap kali kamu scroll TikTok selama 3 menit, algoritma sudah merekam 17 data tentang dirimu.'",
          "",
          "TEKNIK 2 — VISUALISASI DATA",
          "  Jangan hanya menyebut data, visualisasikan data dalam bentuk cerita. Bandingkan dengan sesuatu yang familiar. 'Sampah plastik Indonesia mencapai 64 juta ton per tahun.' (angka abstrak) vs 'Sampah plastik Indonesia setara dengan 400.000 ekor gajah — setiap tahun.' (visualisasi).",
          "",
          "TEKNIK 3 — NARATIF DAN PERSONAL",
          "  Data itu penting, tapi pembaca lebih mudah terhubung dengan cerita manusia. Mulailah dengan kisah seseorang, lalu tarik ke konteks yang lebih besar. Teknik jurnalisme ini disebut 'human angle'.",
          "",
          "TEKNIK 4 — VARIASI STRUKTUR KALIMAT",
          "  Jangan menulis dengan kalimat yang panjangnya sama. Variasikan: kalimat pendek (dramatis), kalimat sedang (informatif), kalimat panjang (analitis). Ritme yang bervariasi membuat artikel enak dibaca.",
          "",
          "TEKNIK 5 — SUB-JUDUL DAN BULLET POINT",
          "  Pembaca online tidak membaca, mereka 'memindai' (scanning). Gunakan sub-judul (H2/H3), bullet point, dan paragraf pendek (maksimal 4-5 baris) untuk memudahkan scanning.",
          "",
          "[Ilustrasi: Seorang penulis duduk di meja kerja dengan beberapa layar. Di layar utama, artikel sedang diketik. Di layar kedua, data statistik. Di meja, buku catatan dengan sketsa hook artikel. Post-it di dinding: '37 DETIK!' '8 PEMBACA TIDAK MENGGULIR KE BAWAH'. Gaya ilustrasi penulis digital dengan warna oranye dan biru.]",
        ],
        contoh: [
          "PERBANDINGAN PENULISAN BIASA VS TEKNIK MENARIK:",
          "",
          "BIASA:",
          "'Polusi udara di Jakarta sangat buruk. Banyak orang sakit karena udara kotor. Pemerintah harus melakukan sesuatu.'",
          "✗ Datar, tidak ada hook, tidak ada data, tidak ada urgensi.",
          "",
          "DENGAN TEKNIK:",
          "'Tahukah kamu bahwa setiap kali kamu menarik napas di Jakarta, kamu menghirup setara 5 batang rokok? Data IQAir tahun 2025 menempatkan Jakarta sebagai kota dengan udara terpolusi nomor 6 di dunia. Bayangkan: 11 juta warga Jakarta setiap hari berbagi paru-paru dengan asap kendaraan dan cerobong pabrik. Di rumah sakit, kasus ISPA naik 40% dalam 3 bulan terakhir. Lalu, apa yang kita lakukan?'",
          "✓ Hook kuat (analogi rokok), data mengejutkan (peringkat 6), visualisasi (berbagi paru-paru), data lokal (ISPA naik 40%), pertanyaan reflektif.",
        ],
      },
    ],
    rangkuman: [
      "[Ilustrasi: Kantor redaksi portal berita online dengan tim editor bekerja di meja masing-masing. Layar besar menampilkan dashboard artikel terpopuler. Suasana dinamis dan modern. Gaya ilustrasi redaksi digital dengan warna hijau toska, putih, dan abu-abu.]",
      "Artikel adalah karangan faktual yang dimuat di media massa. Jenis: ilmiah (jurnal), ilmiah populer (koran/portal), opini (individu), feature (mendalam).",
      "Struktur: judul (headline) → teras (lead) → isi/badan artikel (argumen + data) → penutup (simpulan/rekomendasi).",
      "Kaidah kebahasaan: bahasa formal-fleksibel, data dan fakta kredibel, kalimat efektif, istilah teknis dengan penjelasan, koherensi antarteks.",
      "Teknik menulis menarik: hook kuat, visualisasi data, naratif human angle, variasi struktur kalimat, sub-judul/bullet point untuk scanning.",
    ],
  },
  latihan: makeSoal([
    ["Artikel ilmiah populer berbeda dengan artikel ilmiah dalam hal...", ["Artikel populer lebih panjang", "Artikel populer menggunakan bahasa yang mudah dipahami masyarakat umum", "Artikel populer tidak menggunakan data", "Artikel populer tidak perlu fakta"], 1, "Artikel ilmiah populer menggunakan bahasa populer agar mudah dipahami, tanpa mengurangi keilmiahannya."],
    ["Fungsi utama lead/teras dalam artikel adalah...", ["Menyajikan data lengkap", "Menarik perhatian pembaca agar terus membaca", "Menutup artikel", "Memberikan daftar pustaka"], 1, "Lead berfungsi sebagai hook untuk menarik pembaca membaca lebih lanjut."],
    ["Yang BUKAN merupakan sumber data kredibel untuk artikel adalah...", ["BPS", "Jurnal akademik bereputasi", "Blog pribadi tanpa verifikasi", "Laporan WHO"], 2, "Blog pribadi yang tidak terverifikasi tidak termasuk sumber data kredibel."],
    ["Contoh lead dengan hook yang kuat adalah...", ["Dalam artikel ini saya akan membahas polusi", "Tahukah kamu bahwa udara Jakarta setara dengan 5 batang rokok setiap napas?", "Polusi adalah masalah", "Pemerintah perlu bertindak"], 1, "Hook kuat menggunakan fakta mengejutkan atau analogi yang menarik."],
    ["Teknik 'human angle' dalam artikel berarti...", ["Menggunakan sudut pandang manusia/kisah personal untuk terhubung dengan pembaca", "Menulis dari sudut pandang pemerintah", "Menggunakan data statistik", "Menulis dengan bahasa formal"], 0, "Human angle menggunakan kisah personal untuk membuat artikel lebih dekat dan emosional."],
    ["Mengapa artikel online perlu menggunakan sub-judul dan paragraf pendek?", ["Agar lebih panjang", "Karena pembaca online cenderung memindai (scanning), bukan membaca detail", "Agar terlihat profesional", "Karena aturan SEO"], 1, "Pembaca online adalah pembaca 'pemindai' — mereka melihat judul dan sub-judul sebelum memutuskan membaca."],
    ["Perbedaan artikel opini dan editorial adalah...", ["Tidak ada perbedaan", "Opini adalah pendapat individu (mencantumkan nama), editorial adalah suara media (anonim)", "Opini lebih subjektif", "Editorial lebih panjang"], 1, "Opini adalah pendapat individu yang ditandatangani; editorial adalah sikap resmi media tanpa nama penulis."],
    ["Fungsi visualisasi data dalam artikel adalah...", ["Membuat halaman lebih panjang", "Membuat data lebih mudah dipahami dan diingat pembaca", "Menghias artikel", "Menggantikan analisis"], 1, "Visualisasi data (misal: analogi 'setara 400.000 gajah') membantu pembaca memahami angka abstrak."],
    ["Kriteria judul artikel yang baik adalah...", ["Panjang dan detail", "Menarik, informatif, dan mencerminkan isi (5-12 kata)", "Mengandung singkatan", "Berima"], 1, "Judul harus menarik perhatian, informatif, dan mencerminkan isi, idealnya 5-12 kata."],
    ["'Meskipun demikian' dan 'di sisi lain' dalam artikel berfungsi sebagai...", ["Kata transisi untuk koherensi antargagasan", "Pembuka artikel", "Penutup artikel", "Data pendukung"], 0, "Konjungsi seperti 'meskipun demikian' dan 'di sisi lain' berfungsi sebagai transisi antargagasan."],
  ]),
  praktik: {
    petunjuk: "Pilihlah satu topik aktual yang menarik minatmu (lingkungan, teknologi, pendidikan, sosial, atau budaya). Tulislah artikel ilmiah populer dengan struktur lengkap (judul, lead, badan artikel minimal 5 paragraf, penutup) sepanjang 500-700 kata. Sertakan minimal 3 data dari sumber kredibel dengan mencantumkan sumbernya dalam teks. Gunakan teknik hook yang kuat, visualisasi data, dan variasi struktur kalimat.",
    tips: [
      "Tentukan angle yang unik — jangan menulis topik yang sama persis seperti yang sudah banyak ditulis orang",
      "Kumpulkan data dari 3 sumber berbeda sebelum mulai menulis, baru pilih data yang paling menarik",
      "Tulis lead terakhir — setelah kamu tahu isi artikelmu, kamu bisa menulis hook yang benar-benar mencerminkan isi",
      "Baca ulang dengan suara keras untuk merasakan ritme dan aliran tulisan",
      "Minta teman membaca artikelmu dan tanya: 'Apa yang paling kamu ingat?' — jika jawabannya sesuai pesan utamamu, artikelmu berhasil",
    ],
    contoh: "Artikel ilmiah populer yang baik membuat pembaca merasa lebih pintar setelah membacanya. Mereka mendapatkan wawasan baru, data menarik, dan perspektif yang sebelumnya tidak mereka sadari. Tujuanmu bukan sekadar menyampaikan informasi, tetapi MENGUBAH cara pembaca memandang suatu topik.",
  },
  kuis: makeSoal([
    ["Jenis artikel yang membahas topik ilmiah dengan bahasa populer disebut...", ["Artikel ilmiah", "Artikel ilmiah populer", "Artikel opini", "Artikel feature"], 1, "Artikel ilmiah populer adalah artikel ilmiah yang ditulis dengan bahasa yang mudah dipahami masyarakat luas."],
    ["Fungsi data dalam artikel adalah...", ["Mempercantik tulisan", "Memperkuat argumen dan memberikan kredibilitas", "Membingungkan pembaca", "Menggantikan analisis"], 1, "Data memberikan kekuatan dan kredibilitas pada argumen penulis."],
    ["Bagian artikel yang berfungsi sebagai 'pintu masuk' dan harus menarik perhatian adalah...", ["Isi", "Judul dan lead", "Penutup", "Daftar pustaka"], 1, "Judul dan lead adalah bagian pertama yang dilihat pembaca — harus menarik."],
    ["Perbedaan artikel ilmiah dan artikel ilmiah populer terutama pada...", ["Panjang artikel", "Bahasa yang digunakan (formal vs populer)", "Topik yang dibahas", "Jumlah penulis"], 1, "Artikel ilmiah menggunakan bahasa formal akademis; artikel ilmiah populer menggunakan bahasa populer."],
    ["Teknik 'visualisasi data' yang tepat adalah...", ["'Inflasi naik 0,5%'", "'Sampah plastik Indonesia setara 400.000 ekor gajah per tahun'", "'Data menunjukkan penurunan'", "'Angka signifikan'"], 1, "Visualisasi data mengubah angka abstrak menjadi gambaran yang mudah dibayangkan, seperti perbandingan dengan gajah."],
    ["Mengapa sumber data harus disebutkan dalam artikel?", ["Agar terlihat ilmiah", "Agar pembaca bisa memverifikasi keakuratan data", "Agar lebih panjang", "Karena aturan"], 1, "Menyebutkan sumber data memungkinkan pembaca memverifikasi dan menilai kredibilitas tulisan."],
    ["Ciri khas artikel feature adalah...", ["Menggunakan bahasa formal kaku", "Gaya penulisan naratif dan mendalam", "Tidak menggunakan data", "Hanya untuk koran"], 1, "Artikel feature ditulis secara naratif dan mendalam, sering tentang profil atau liputan khusus."],
    ["Fungsi paragraf penutup dalam artikel adalah...", ["Memperkenalkan ide baru", "Merangkum dan meninggalkan kesan mendalam", "Menyajikan data tambahan", "Mengulang lead"], 1, "Penutup merangkum argumen dan meninggalkan kesan akhir yang kuat pada pembaca."],
    ["'Bayangkan: setiap menit, 500 jam konten diunggah ke YouTube.' Kalimat ini termasuk...", ["Data kering", "Hook dengan visualisasi", "Opini penulis", "Kesimpulan"], 1, "Kalimat ini menggunakan fakta konkret dan mengajak pembaca membayangkan, teknik hook yang efektif."],
    ["Tujuan utama artikel ilmiah populer adalah...", ["Mendapatkan nilai akademis", "Menyampaikan informasi ilmiah secara menarik dan mudah dipahami masyarakat", "Menghibur pembaca", "Menjual produk"], 1, "Tujuan artikel ilmiah populer adalah menyampaikan informasi ilmiah dengan cara yang menarik dan mudah dipahami."],
  ]),
}

export default konten
