import type { Konten } from "../types"
import { makeSoal } from "../types"

const konten: Konten = {
  belajar: {
    tujuan: [
      "Memahami hakikat puisi sebagai karya sastra yang padat makna",
      "Menganalisis unsur fisik dan batin puisi secara mendalam",
      "Mengidentifikasi gaya bahasa, imaji, dan simbol dalam puisi",
      "Menganalisis puisi berdasarkan pendekatan semiotik dan struktural",
      "Menulis puisi dengan kesadaran estetika dan diksi yang tepat",
    ],
    materi: [
      {
        judul: "Hakikat dan Unsur Puisi",
        isi: [
          "Di antara semua bentuk karya sastra, puisilah yang paling padat, paling singkat, tetapi paling kaya makna. Puisi bukan sekadar kumpulan kata yang berima — puisi adalah cara penyair 'melihat' dunia dan menuangkannya dalam bahasa yang diikat oleh estetika. Di kelas XII, kita akan menyelami puisi bukan hanya sebagai pembaca, tetapi sebagai pengkaji yang kritis.",
          "",
          "Puisi adalah bentuk karya sastra yang menggunakan kata-kata indah dan padat untuk mengungkapkan pikiran, perasaan, dan pengalaman penyair. Puisi memiliki kepadatan makna — setiap kata dipilih dengan saksama, setiap baris dipertimbangkan efek bunyi dan maknanya.",
          "",
          "Unsur pembangun puisi dibagi menjadi dua:",
          "",
          "A. UNSUR FISIK (STRUKTUR FISIK):",
          "  1. DIKSI — pilihan kata yang tepat dan bermakna konotatif",
          "  2. IMAJI — gambaran dalam pikiran (visual, auditori, taktil, olfaktori, gustatif)",
          "  3. KATA KONKRET — kata yang merujuk pada sesuatu yang bisa ditangkap indra",
          "  4. MAJAS/GAYA BAHASA — bahasa kiasan untuk efek estetis",
          "  5. RIMA/RITMA — pengulangan bunyi dan irama",
          "  6. TIPOGRAFI — tata wajah puisi (baris, bait, larik)",
          "",
          "B. UNSUR BATIN (STRUKTUR BATIN):",
          "  1. TEMA — gagasan pokok yang mendasari puisi",
          "  2. RASA — sikap penyair terhadap tema (senang, sedih, marah, kagum)",
          "  3. NADA — sikap penyair terhadap pembaca (menggurui, merenung, memberontak)",
          "  4. AMANAT — pesan yang ingin disampaikan penyair",
          "",
          "[Ilustrasi: Sebuah buku puisi terbuka. Dari halaman yang terbuka, kata-kata melayang ke udara dan berubah menjadi gambar-gambar: bunga mawar, ombak, bulan, dan burung. Di latar belakang, langit senja gradasi ungu dan jingga. Gaya ilustrasi surealis puitis dengan warna-warna hangat dan lembut.]",
        ],
        contoh: [
          "ANALISIS PUISI 'DOA' KARYA CHAIRIL ANWAR:",
          "",
          "Kepada Pemeluk Teguh",
          "",
          "Tuhanku",
          "Dalam termangu",
          "Aku masih menyebut nama-Mu",
          "",
          "Biar susah sungguh",
          "Mengingat Kau penuh seluruh",
          "cahaya-Mu panas suci",
          "tinggal kerdip lilin di muka sunyi",
          "",
          "ANALISIS UNSUR FISIK:",
          "- Diksi: 'termangu' (kebingungan eksistensial), 'kerdip lilin' (iman yang kecil tapi bertahan)",
          "- Imaji visual: 'cahaya-Mu panas suci', 'kerdip lilin di muka sunyi'",
          "- Majas: metafora ('lilin' = iman, 'sunyi' = kegelapan hidup)",
          "- Rima: a-b-a-b, c-c-d-d (tidak konsisten, khas puisi modern)",
          "",
          "ANALISIS UNSUR BATIN:",
          "- Tema: kerinduan spiritual, keresahan eksistensial di hadapan Tuhan",
          "- Rasa: khusyuk, merendah, penuh harap",
          "- Nada: meditatif, kontemplatif",
          "- Amanat: dalam situasi paling gelap sekalipun, manusia tetap bisa berpegang pada iman — walau sekecil lilin",
        ],
        catatan: "Chairil Anwar (1922-1949) adalah pelopor puisi modern Indonesia. Ia hanya hidup 27 tahun tetapi meninggalkan warisan yang tak ternilai. Puisi-puisinya seperti 'Aku', 'Krawang-Bekasi', dan 'Doa' mengubah wajah sastra Indonesia. Menariknya, Chairil tidak pernah menyelesaikan pendidikan formalnya — ia belajar secara otodidak dengan membaca karya sastra dunia. Ini membuktikan bahwa puisi lahir dari kepekaan dan keberanian, bukan dari gelar akademik.",
      },
      {
        judul: "Majas dan Gaya Bahasa dalam Puisi",
        isi: [
          "Majas adalah bahasa kiasan yang digunakan penyair untuk menciptakan efek estetis dan menyampaikan makna secara tidak langsung. Pemahaman tentang majas adalah kunci untuk mengapresiasi keindahan puisi.",
          "",
          "Majas yang sering digunakan dalam puisi:",
          "",
          "1. PERSONIFIKASI",
          "  Memberi sifat manusia pada benda mati atau abstrak.",
          "  Contoh: 'Angin berbisik cerita tentangmu' — angin tidak bisa berbisik, tetapi metafora ini menciptakan suasana personal.",
          "",
          "2. METAFORA",
          "  Perbandingan langsung tanpa kata pembanding (seperti, bagai, laksana).",
          "  Contoh: 'Hidup adalah rantai tanpa ujung' — hidup bukan rantai, tetapi dibandingkan langsung untuk menekankan perasaan terperangkap.",
          "",
          "3. SIMILE",
          "  Perbandingan dengan kata pembanding.",
          "  Contoh: 'Rambutnya bagai mayang terurai' — jelas membandingkan dengan 'bagai'.",
          "",
          "4. HIPERBOLA",
          "  Melebih-lebihkan sesuatu untuk efek dramatis.",
          "  Contoh: 'Aku menggendutkan lautan air mataku' — mustahil secara harfiah, tetapi efektif secara emosional.",
          "",
          "5. LITOTES",
          "  Merendahkan diri/meremehkan untuk efek sebaliknya (kesopanan atau ironi).",
          "  Contoh: 'Terimalah karya kecil ini' padahal karyanya besar.",
          "",
          "6. IRONI / SINISME",
          "  Menyampaikan makna kebalikan dari kata yang diucapkan, sering untuk kritik.",
          "  Contoh: 'Alangkah indahnya negeri ini, di mana yang kaya semakin kaya dan yang miskin semakin lapar'.",
          "",
          "7. SIMBOL",
          "  Lambang yang mewakili sesuatu yang lebih besar. Bunga mawar = cinta, air = kehidupan, rantai = penindasan.",
          "",
          "[Ilustrasi: Sebuah taman sastra dengan patung-patung kata. Setiap patung melambangkan jenis majas: patung angin berwajah manusia (personifikasi), dua benda yang melebur (metafora), terompet raksasa (hiperbola), dan topeng (ironi). Di tengah, air mancur dengan bunga teratai (simbol). Gaya ilustrasi surealis taman sastra dengan warna pastel.]",
        ],
        contoh: [
          "IDENTIFIKASI MAJAS DALAM PUISI 'AKU' CHAIRIL ANWAR:",
          "",
          "Kalau sampai waktuku",
          "'Ku mau tak seorang kan merayu",
          "Tidak juga kau",
          "",
          "Tak perlu sedu sedan itu",
          "",
          "Aku ini binatang jalang",
          "Dari kumpulannya terbuang",
          "",
          "Biar peluru menembus kulitku",
          "Aku tetap meradang menerjang",
          "",
          "Luka dan bisa kubawa berlari",
          "Berlari",
          "Hingga hilang pedih peri",
          "",
          "Dan aku akan lebih tidak peduli",
          "Aku mau hidup seribu tahun lagi",
          "",
          "IDENTIFIKASI MAJAS:",
          "",
          "1. Metafora: 'Aku ini binatang jalang' — penyair menyamakan dirinya dengan binatang buangan",
          "2. Hiperbola: 'Aku mau hidup seribu tahun lagi' — melebih-lebihkan keinginan hidup",
          "3. Personifikasi: 'peluru menembus kulitku' — peluru diberi kemampuan aktif",
          "4. Simbol: 'binatang jalang' = simbol pemberontakan dan keterasingan",
          "",
          "MAKNA: Puisi ini adalah manifesto pemberontakan Chairil terhadap norma dan kemapanan. 'Binatang jalang' melambangkan semangat liar yang tidak mau dijinakkan oleh aturan sosial. 'Hidup seribu tahun lagi' bukan keinginan harfiah, melainkan pernyataan bahwa semangatnya akan abadi.",
        ],
      },
      {
        judul: "Imaji dan Kata Konkret dalam Puisi",
        isi: [
          "Salah satu kekuatan puisi adalah kemampuannya menciptakan 'gambar dalam pikiran' pembaca. Inilah yang disebut imaji. Semakin kuat imaji yang diciptakan, semakin hidup puisi tersebut.",
          "",
          "Jenis imaji berdasarkan indra:",
          "",
          "1. IMAJI VISUAL (penglihatan)",
          "  Menggambarkan sesuatu yang bisa dilihat: warna, bentuk, gerakan, cahaya.",
          "  Contoh: 'Lukisan senja di ujung laut, / Merah saga membakar cakrawala.'",
          "",
          "2. IMAJI AUDITORI (pendengaran)",
          "  Menggambarkan suara atau bunyi.",
          "  Contoh: 'Gemercik air di pancuran bambu, / Berbisik pada malam yang sunyi.'",
          "",
          "3. IMAJI TAKTIL (perabaan/sentuhan)",
          "  Menggambarkan tekstur, suhu, atau sensasi raba.",
          "  Contoh: 'Kasar tanah di telapak tanganku, / Hangat mentari menyentuh kulit.'",
          "",
          "4. IMAJI OLFAKTORI (penciuman)",
          "  Menggambarkan bau atau aroma.",
          "  Contoh: 'Wangii melati di malam purnama / Mengingatkanku pada rumah.'",
          "",
          "5. IMAJI GUSTATIF (pengecapan)",
          "  Menggambarkan rasa.",
          "  Contoh: 'Pahit kopi di ujung lidah / Seperti pahitnya perpisahan.'",
          "",
          "KATA KONKRET adalah kata yang merujuk pada benda nyata yang bisa ditangkap indra. Penyair menggunakan kata konkret untuk membuat puisi lebih 'terasa nyata'. Contoh: Chairil menggunakan 'lilin' (bukan 'harapan'), 'peluru' (bukan 'kekerasan'), 'binatang' (bukan 'kebebasan'). Kata-kata konkret lebih kuat daripada kata abstrak.",
          "",
          "[Ilustrasi: Wajah seorang pembaca puisi dengan mata terpejam. Dari sekeliling kepalanya, muncul gelembung-gelembung imaji: di satu gelembung ada pemandangan senja (visual), di gelembung lain ada suara gemercik air (auditori), di gelembung lain ada tangan menyentuh tanah (taktil). Gaya ilustrasi surealis dengan warna-warna impresif.]",
        ],
        contoh: [
          "ANALISIS IMAJI DAN KATA KONKRET:",
          "",
          "KUTIPAN DARI PUISI 'DERAI DERAI CEMARA' KARYA WS RENDRA:",
          "",
          "Derai-derai cemara",
          "di pinggir danau",
          "bagai lima atau sepuluh",
          "tangan yang menggapai-gapai",
          "dari dalam air",
          "",
          "ANALISIS IMAJI:",
          "- 'derai-derai cemara' — imaji visual: pohon cemara berderet",
          "- 'di pinggir danau' — imaji visual: latar air tenang",
          "- 'tangan yang menggapai-gapai' — imaji visual + personifikasi: ranting cemara seperti tangan",
          "- 'dari dalam air' — imaji visual: bayangan pohon di air",
          "",
          "KATA KONKRET: cemara, danau, tangan, air — semua kata yang bisa dilihat dan dibayangkan secara fisik.",
          "",
          "MAKNA: WS Rendra menggambarkan pohon cemara yang bergerak ditiup angin sehingga bayangannya di danau seperti tangan yang menggapai. Ada kesan kerinduan atau keputusasaan dalam gerakan 'menggapai-gapai' — sesuatu yang merindukan tetapi tidak bisa meraih.",
        ],
      },
      {
        judul: "Pendekatan Analisis Puisi",
        isi: [
          "Di kelas XII, kamu tidak hanya membaca dan menikmati puisi, tetapi juga menganalisis secara sistematis. Berikut dua pendekatan yang bisa digunakan:",
          "",
          "A. PENDEKATAN STRUKTURAL",
          "  Menganalisis puisi berdasarkan unsur-unsur pembangunnya (fisik dan batin) tanpa melihat konteks luar. Fokus pada 'apa yang ada di dalam teks'.",
          "",
          "  Langkah analisis struktural:",
          "  1. Baca puisi berulang-ulang (minimal 3 kali)",
          "  2. Identifikasi unsur fisik: diksi, imaji, kata konkret, majas, rima, tipografi",
          "  3. Identifikasi unsur batin: tema, rasa, nada, amanat",
          "  4. Analisis bagaimana setiap unsur berkontribusi pada makna keseluruhan",
          "  5. Simpulkan makna puisi berdasarkan interaksi semua unsur tersebut",
          "",
          "B. PENDEKATAN SEMIOTIK",
          "  Menganalisis puisi sebagai sistem tanda. Setiap kata, frasa, atau baris adalah 'tanda' yang memiliki makna denotatif (harfiah) dan konotatif (kiasan).",
          "",
          "  Konsep kunci semiotika puisi:",
          "  - SIGNIFIER (penanda): bentuk fisik kata (bunyi, huruf)",
          "  - SIGNIFIED (petanda): konsep/makna yang ditunjuk",
          "  - DENOTASI: makna harfiah/literal",
          "  - KONOTASI: makna kiasan/tambahan",
          "",
          "  Contoh: kata 'rantai' secara denotatif berarti benda dari logam berjalin. Secara konotatif, rantai bisa berarti penindasan, ikatan, atau belenggu.",
          "",
          "C. PENDEKATAN KONTEKSTUAL",
          "  Menganalisis puisi dengan mempertimbangkan konteks: latar belakang penyair, kondisi sosial-politik saat puisi ditulis, dan referensi budaya.",
          "",
          "[Ilustrasi: Sebuah meja kerja dengan tiga buku terbuka mewakili tiga pendekatan. Buku kiri: 'STRUKTURAL' dengan diagram unsur puisi. Buku tengah: 'SEMIOTIK' dengan diagram penanda-petanda. Buku kanan: 'KONTEKSTUAL' dengan foto penyair dan kliping koran. Kaca pembesar di atas meja. Gaya ilustrasi meja akademik dengan warna biru, hijau, dan oranye.]",
        ],
        contoh: [
          "ANALISIS PUISI 'KRAWANG-BEKASI' KARYA CHAIRIL ANWAR DENGAN TIGA PENDEKATAN:",
          "",
          "Kami yang kini terbaring antara Krawang-Bekasi",
          "Tidak bisa teriak 'Merdeka' lagi",
          "Tapi siapakah yang tidak lagi mendengar deru kami",
          "Terbayang kami maju dan berjuang?",
          "",
          "PENDEKATAN STRUKTURAL:",
          "- Diksi: 'terbaring' (mati/syahid), 'teriak Merdeka' (semangat perjuangan)",
          "- Majas: ironi — 'tidak bisa teriak Merdeka lagi' (mereka yang gugur sudah tidak bisa berteriak, tapi justru dengan kematian mereka, semangat merdeka hidup)",
          "- Imaji: auditori ('deru kami'), visual ('terbayang kami maju')",
          "- Tema: pengorbanan para pejuang kemerdekaan",
          "- Rasa: duka bercampur kagum",
          "- Amanat: kemerdekaan dibayar dengan nyawa para pejuang — kita harus menghargainya",
          "",
          "PENDEKATAN SEMIOTIK:",
          "- 'Krawang-Bekasi' → denotasi: dua kota di Jawa Barat. Konotasi: medan pertempuran, lokasi perjuangan",
          "- 'terbaring' → denotasi: berbaring. Konotasi: mati/tewas dalam perjuangan",
          "- 'deru' → denotasi: suara gemuruh. Konotasi: semangat dan teriakan perjuangan yang terus bergema",
          "",
          "PENDEKATAN KONTEKSTUAL:",
          "- Puisi ditulis tahun 1948, masa revolusi fisik (1945-1949)",
          "- Krawang dan Bekasi adalah lokasi pertempuran sengit antara pejuang Indonesia dan Sekutu/Belanda",
          "- Chairil sendiri terlibat dalam perjuangan secara kultural — puisinya adalah bentuk perlawanan dengan pena",
          "- Puisi ini adalah kritik halus kepada generasi yang lupa akan jasa pahlawan",
        ],
      },
    ],
    rangkuman: [
      "[Ilustrasi: Seorang penyair duduk di tepi tebing menghadap laut. Matahari terbenam di kejauhan. Ia menulis di buku catatan. Di sekelilingnya, kata-kata berterbangan tertiup angin. Latar langit jingga keunguan. Gaya ilustrasi romantik-surealis dengan warna senja yang hangat.]",
      "Puisi adalah karya sastra padat makna yang dibangun oleh unsur fisik (diksi, imaji, kata konkret, majas, rima, tipografi) dan unsur batin (tema, rasa, nada, amanat).",
      "Majas utama: personifikasi, metafora, simile, hiperbola, litotes, ironi, simbol. Imaji: visual, auditori, taktil, olfaktori, gustatif.",
      "Pendekatan analisis: struktural (fokus pada teks), semiotik (sistem tanda — penanda/petanda, denotasi/konotasi), kontekstual (konteks penyair dan sosial-politik).",
      "Kekuatan puisi adalah pada kepadatan dan ambiguitas makna — satu puisi bisa memiliki banyak interpretasi, dan itu yang membuat puisi indah.",
    ],
  },
  latihan: makeSoal([
    ["Yang dimaksud dengan 'diksi' dalam puisi adalah...", ["Pengulangan bunyi", "Pilihan kata yang tepat dan bermakna", "Tata wajah puisi", "Jumlah bait"], 1, "Diksi adalah pilihan kata yang cermat untuk menghasilkan efek makna dan estetis tertentu."],
    ["Majas yang memberi sifat manusia pada benda mati disebut...", ["Metafora", "Personifikasi", "Hiperbola", "Simile"], 1, "Personifikasi adalah majas yang memberi sifat manusia pada benda mati atau abstrak."],
    ["'Aku ini binatang jalang' termasuk majas...", ["Simile", "Personifikasi", "Hiperbola", "Metafora"], 3, "Metafora adalah perbandingan langsung tanpa kata pembanding — 'aku' langsung disamakan dengan 'binatang jalang'."],
    ["Imaji yang berkaitan dengan indra pendengaran disebut...", ["Imaji visual", "Imaji auditori", "Imaji taktil", "Imaji gustatif"], 1, "Imaji auditori berkaitan dengan pendengaran, seperti gemercik air, deru, bisikan."],
    ["Pendekatan analisis puisi yang fokus pada sistem tanda disebut...", ["Struktural", "Semiotik", "Kontekstual", "Sosiologis"], 1, "Pendekatan semiotik menganalisis puisi sebagai sistem tanda (penanda dan petanda)."],
    ["Kata 'rantai' dalam puisi secara konotatif bisa berarti...", ["Benda dari logam", "Penindasan atau belenggu", "Perhiasan", "Alat"], 1, "Secara konotatif, 'rantai' sering melambangkan penindasan, ikatan yang membatasi, atau belenggu."],
    ["Puisi 'Krawang-Bekasi' karya Chairil Anwar bertema tentang...", ["Cinta", "Pengorbanan para pejuang kemerdekaan", "Keindahan alam", "Sosial"], 1, "Puisi ini bertema pengorbanan pejuang di medan perang Krawang-Bekasi."],
    ["Unsur batin puisi yang berkaitan dengan sikap penyair terhadap tema adalah...", ["Tema", "Rasa", "Nada", "Amanat"], 1, "Rasa adalah sikap penyair terhadap tema — apakah sedih, marah, kagum, atau rindu."],
    ["WS Rendra dalam 'Derai Derai Cemara' menggunakan kata 'cemara' sebagai...", ["Majas hiperbola", "Kata konkret untuk menciptakan imaji visual", "Simbol abstrak", "Rima"], 1, "'Cemara' adalah kata konkret yang menciptakan imaji visual pohon cemara di tepi danau."],
    ["Perbedaan makna denotatif dan konotatif terletak pada...", ["Denotatif lebih panjang", "Denotatif adalah makna harfiah, konotatif adalah makna kiasan", "Konotatif lebih pendek", "Tidak ada perbedaan"], 1, "Denotasi adalah makna harfiah/literal; konotasi adalah makna kiasan/tambahan yang melekat pada kata."],
  ]),
  praktik: {
    petunjuk: "Pilihlah satu puisi Indonesia modern (karya Chairil Anwar, WS Rendra, Sutardji Calzoum Bachri, Sapardi Djoko Damono, atau Goenawan Mohamad). Tulislah analisis lengkap dengan menggunakan tiga pendekatan: (1) struktural (analisis unsur fisik dan batin), (2) semiotik (identifikasi penanda-petanda, denotasi-konotasi), dan (3) kontekstual (latar belakang penyair dan kondisi saat puisi ditulis). Panjang analisis minimal 500 kata. Sertakan kutipan langsung dari puisi untuk mendukung setiap poin analisismu.",
    tips: [
      "Pilih puisi yang 'berbicara' kepadamu — jangan pilih puisi hanya karena terkenal atau pendek",
      "Baca puisi minimal 5 kali: pertama nikmati, kedua pahami diksi, ketiga cari majas, keempat cari imaji, kelima renungkan maknanya",
      "Cari tahu biografi penyair dan kapan puisi ditulis — konteks sangat membantu interpretasi",
      "Jangan takut dengan interpretasi yang berbeda — puisi indah karena bisa dimaknai dari berbagai sudut",
      "Kutip baris puisi yang spesifik untuk mendukung setiap klaim analisismu",
    ],
    contoh: "Analisis puisi yang baik tidak sekadar mengidentifikasi unsur, tetapi MENGHUBUNGKAN bagaimana setiap unsur bekerja bersama menciptakan makna. Misalnya: 'Penggunaan metafora binatang jalang, ditambah diksi 'terbuang' dan 'meradang', menciptakan gambaran pemberontakan total — bukan sekadar puisi protes, tetapi pernyataan eksistensial tentang identitas.' Analisislah seperti detektif sastra yang mencari bukti dan menarik kesimpulan.",
  },
  kuis: makeSoal([
    ["Fungsi kata konkret dalam puisi adalah...", ["Membuat puisi lebih panjang", "Membuat puisi lebih terasa nyata dan bisa diindra", "Memperindah bunyi", "Menggantikan majas"], 1, "Kata konkret merujuk pada benda nyata yang bisa ditangkap indra, membuat puisi lebih hidup."],
    ["'Rambutnya bagai mayang terurai' menggunakan majas...", ["Metafora", "Simile", "Personifikasi", "Hiperbola"], 1, "'Bagai' adalah kata pembanding dalam simile — membandingkan rambut dengan mayang."],
    ["Pendekatan struktural dalam analisis puisi berfokus pada...", ["Biografi penyair", "Unsur-unsur pembangun dalam teks puisi", "Kondisi sosial-politik", "Pengaruh sastra asing"], 1, "Struktural menganalisis puisi berdasarkan unsur intrinsiknya, tanpa melihat konteks luar."],
    ["Dalam puisi 'Doa' Chairil Anwar, kata 'lilin' secara konotatif melambangkan...", ["Penerangan rumah", "Iman yang kecil namun bertahan di tengah kegelapan", "Benda mudah meleleh", "Kemewahan"], 1, "'Kerdip lilin di muka sunyi' melambangkan iman yang rapuh tetapi masih menyala di tengah kegelapan eksistensial."],
    ["Imaji taktil berkaitan dengan indra...", ["Penglihatan", "Perabaan/sentuhan", "Pendengaran", "Penciuman"], 1, "Imaji taktil berkaitan dengan sensasi sentuhan: panas, dingin, kasar, halus."],
    ["Tipografi dalam puisi mengacu pada...", ["Jenis kertas", "Tata wajah puisi (baris, bait, larik)", "Pilihan kata", "Bunyi akhir"], 1, "Tipografi adalah tata wajah atau pengaturan visual puisi di halaman."],
    ["Puisi 'Aku' Chairil Anwar menggunakan metafora 'binatang jalang' untuk...", ["Menunjukkan kecintaan pada binatang", "Melambangkan pemberontakan dan keterasingan dari norma sosial", "Menceritakan kisah binatang", "Sekadar gaya bahasa"], 1, "'Binatang jalang' melambangkan semangat liar yang tidak mau dijinakkan aturan sosial."],
    ["Perbedaan nada dan rasa dalam puisi adalah...", ["Sama saja", "Rasa = sikap pada tema, nada = sikap pada pembaca", "Nada = tema, rasa = amanat", "Rasa lebih penting"], 1, "Rasa adalah sikap penyair terhadap tema; nada adalah sikap penyair terhadap pembaca."],
    ["'Aku menggendutkan lautan air mataku' adalah contoh majas...", ["Personifikasi", "Hiperbola", "Metafora", "Litotes"], 1, "Hiperbola adalah melebih-lebihkan — secara harfiah tidak mungkin seseorang bisa menggendutkan lautan dengan air mata."],
    ["Kelebihan pendekatan semiotik dalam analisis puisi adalah...", ["Lebih mudah dan cepat", "Mampu mengungkap makna tersembunyi melalui sistem tanda dan konotasi", "Tidak perlu baca puisi", "Hanya untuk puisi modern"], 1, "Pendekatan semiotik mampu mengungkap makna di balik tanda-tanda linguistik, termasuk konotasi yang tidak tertulis eksplisit."],
  ]),
}

export default konten
