import type { Konten } from "../types"
import { makeSoal } from "../types"

const konten: Konten = {
  belajar: {
    tujuan: [
      "Memahami hakikat, fungsi, dan jenis kritik sastra dalam konteks akademik dan budaya",
      "Mengidentifikasi pendekatan kritik sastra: mimetik, ekspresif, objektif, dan pragmatik",
      "Menganalisis karya sastra dengan menerapkan pendekatan kritik yang relevan",
      "Menyusun teks kritik sastra terhadap novel, cerpen, atau puisi secara sistematis",
      "Mengevaluasi kualitas kritik sastra berdasarkan kedalaman analisis dan argumentasi",
    ],
    materi: [
      {
        judul: "Apa Itu Kritik Sastra?",
        isi: [
          "Pernahkah kamu membaca ulasan buku di media sosial atau koran dan berpikir, 'Wah, analisisnya dalam sekali'? Itulah kritik sastra — seni menganalisis, menafsirkan, dan mengevaluasi karya sastra secara ilmiah dan argumentatif.",
          "",
          "Kritik sastra berbeda dengan resensi. Resensi bersifat informatif dan rekomen-datif: memperkenalkan buku, merangkum isi, dan memberi penilaian umum. Kritik sastra lebih mendalam: membedah struktur, gaya bahasa, tema, simbolisme, dan konteks sosial-budaya karya, lalu menghubungkannya dengan teori sastra tertentu.",
          "",
          "Fungsi kritik sastra menurut Abrams (1953):",
          "",
          "1. FUNGSI INTERPRETATIF — membantu pembaca memahami makna tersirat dalam karya sastra, termasuk simbol, metafora, dan ironi yang mungkin tidak tertangkap saat membaca sepintas",
          "",
          "2. FUNGSI EVALUATIF — menilai kualitas estetika karya berdasarkan standar tertentu, seperti orisinalitas, kohesi struktural, kedalaman karakter, atau relevansi tematik",
          "",
          "3. FUNGSI KONTRIBUTIF — ikut membentuk perkembangan kesusastraan melalui diskusi kritis yang mendorong penulis untuk berkarya lebih baik dan memperkaya wacana sastra",
          "",
          "Seorang kritikus sastra bukanlah 'hakim' yang menentukan benar-salah karya, melainkan 'pemandu' yang membuka perspektif baru. Kritik yang baik bukan menjatuhkan, melainkan membangun pemahaman.",
          "",
          "[Ilustrasi: Seorang kritikus duduk di perpustakaan dengan buku terbuka di tangan, dikelilingi tumpukan novel klasik dan kontemporer. Di atas buku tampak anotasi tulisan tangan: simbol, garis bawah, dan catatan pinggir. Di latar belakang, rak buku tinggi menjulang dari lantai hingga langit-langit. Gaya ilustrasi akademik dengan warna cokelat tua dan krem.]",
        ],
        contoh: [
          "BANDINGKAN RESENSI vs KRITIK SASTRA UNTUK NOVEL 'BUMI MANUSIA' KARYA PRAMOEDYA ANANTA TOER:",
          "",
          "RESENSI (informatif):",
          "'Bumi Manusia adalah novel pertama dari Tetralogi Buru karya Pramoedya Ananta Toer. Novel ini menceritakan Minke, seorang pribumi yang bersekolah di HBS Surabaya. Bahasa Pramoedya indah dan deskriptif. Novel ini layak dibaca karena memberikan perspektif sejarah dari sudut pandang pribumi. Rating: 8/10.'",
          "",
          "KRITIK SASTRA (analitis):",
          "'Pramoedya menggunakan Minke sebagai narator orang pertama untuk menciptakan efek subjektivitas sejarah — pembaca tidak diberi 'kebenaran objektif' melainkan kesaksian personal yang terbatas. Teknik ini secara cerdas mengkritik narasi sejarah kolonial yang mengklaim objektivitas. Penggunaan bahasa Melayu-Tinggi oleh Minke versus bahasa Jawa oleh ibunya menciptakan dikotomi identitas yang merefleksikan krisis identitas pribumi terdidik di awal abad XX — sebuah representasi mikro dari konflik kolonialisme itu sendiri.'",
          "✓ Kritik sastra memberikan analisis struktural dan teoretis yang jauh lebih dalam.",
        ],
        catatan: "Kritik sastra adalah ranah akademik yang membutuhkan dasar teori yang kuat. Jangan khawatir jika pada awalnya kamu merasa kesulitan — keterampilan kritik sastra berkembang seiring banyaknya membaca dan berlatih. Mulailah dengan membaca kritik-kritik dari kritikus terkenal seperti Goenawan Mohamad, Sapardi Djoko Damono, atau Faruk HT untuk melihat contoh analisis yang baik.",
      },
      {
        judul: "Empat Pendekatan Kritik Sastra (Abrams)",
        isi: [
          "M.H. Abrams, dalam bukunya 'The Mirror and the Lamp' (1953), mengemukakan empat pendekatan kritik sastra yang hingga kini masih menjadi acuan utama. Keempat pendekatan ini berbeda dalam 'titik masuk' analisisnya terhadap karya sastra.",
          "",
          "1. PENDEKATAN MIMETIK — berfokus pada hubungan karya dengan realitas. Kritikus mimetik bertanya: 'Seberapa akurat karya ini mencerminkan kehidupan nyata? Apakah karakter, konflik, dan latar terasa autentik?' Pendekatan ini cocok untuk karya realis dan naturalis.",
          "",
          "2. PENDEKATAN EKSPRESIF — berfokus pada hubungan karya dengan pengarang. Pendekatan ini menganalisis bagaimana latar belakang hidup, psikologi, dan pandangan dunia pengarang tercermin dalam karyanya. 'Apa motif penulis menulis ini? Apa trauma atau pengalaman yang mendorong lahirnya karya ini?'",
          "",
          "3. PENDEKATAN OBJEKTIF — berfokus pada karya itu sendiri secara otonom. Kritikus objektif hanya menganalisis elemen intrinsik: alur, penokohan, latar, sudut pandang, gaya bahasa, dan tema — tanpa menghubungkan dengan pengarang atau realitas. Pendekatan ini dominan dalam kritik sastra modern.",
          "",
          "4. PENDEKATAN PRAGMATIK — berfokus pada efek karya terhadap pembaca. 'Apa yang dirasakan pembaca? Bagaimana karya ini memengaruhi emosi, moral, atau pandangan mereka?' Pendekatan ini sering digunakan dalam kritik sastra feminis, Marxis, dan poskolonial.",
          "",
          "PENTING: Kritikus sastra yang baik tidak terpaku pada satu pendekatan saja. Kombinasi beberapa pendekatan justru menghasilkan analisis yang lebih kaya dan multidimensi.",
          "",
          "[Ilustrasi: Diagram Venn dengan 4 lingkaran saling tumpang tindih berlabel: Mimetik (hubungan dengan realitas), Ekspresif (hubungan dengan pengarang), Objektif (karya itu sendiri), Pragmatik (efek pada pembaca). Di tengah tumpang tindih tertulis 'Kritik Sastra'. Setiap lingkaran punya ikon: cermin, kuas, buku tertutup, dan mata. Gaya ilustrasi diagram konsep dengan warna-warna pastel.]",
        ],
        contoh: [
          "ANALISIS PUISI 'AKU' KARYA CHAIRIL ANWAR DENGAN 4 PENDEKATAN:",
          "",
          "MIMETIK: Puisi 'Aku' mencerminkan semangat revolusi dan individualisme yang sedang tumbuh di Indonesia pasca-Proklamasi 1945. 'Aku mau hidup seribu tahun lagi' adalah representasi hasrat generasi muda untuk keluar dari feodalisme dan penjajahan.",
          "",
          "EKSPRESIF: Chairil Anwar lahir di Medan, tumbuh tanpa ayah sejak usia 19 tahun, dan hidup dalam pergolakan revolusi. Kehidupan yang keras dan memberontak tercermin dalam diksi puisi yang liar, agresif, dan tidak mau tunduk pada konvensi.",
          "",
          "OBJEKTIF: Puisi menggunakan diksi yang kuat dan provokatif ('binatang jalang'), struktur tidak terikat aturan syair klasik, rima bebas, dan penggunaan kata konkret ('peluru', 'merangkum') yang menciptakan efek visual dan auditori. Enjambemen digunakan untuk memberikan penekanan pada kata-kata kunci.",
          "",
          "PRAGMATIK: Pembaca puisi 'Aku' pada era 1950-an merasakan energi pemberontakan dan semangat kemerdekaan, sedangkan pembaca milenial mungkin memaknainya sebagai ajakan untuk menjadi autentik di tengah tekanan sosial — makna yang berubah sesuai konteks pembaca.",
        ],
      },
      {
        judul: "Langkah-Langkah Menulis Kritik Sastra",
        isi: [
          "Menulis kritik sastra bukanlah kegiatan 'sambilan' — ini adalah proses akademik yang sistematis. Berikut langkah-langkah yang bisa kamu ikuti untuk menghasilkan kritik sastra yang berbobot.",
          "",
          "LANGKAH 1 — MEMBACA SECARA KRITIS (CLOSE READING)",
          "Baca karya tidak sekali, tetapi berulang kali. Pada bacaan pertama, nikmati karya. Pada bacaan kedua, mulailah mencatat: tema utama, simbol-simbol, pilihan diksi yang menarik, struktur naratif, dan kejanggalan yang terasa menonjol.",
          "",
          "LANGKAH 2 — MENENTUKAN FOKUS ANALISIS",
          "Jangan mencoba menganalisis semua aspek sekaligus — itu akan menghasilkan kritik yang dangkal dan melebar. Pilih satu atau dua aspek spesifik. Contoh: 'Analisis simbolisme air dalam novel Ronggeng Dukuh Paruk' atau 'Representasi poskolonialitas dalam cerpen-cerpen Seno Gumira Ajidarma'.",
          "",
          "LANGKAH 3 — MENENTUKAN PENDEKATAN KRITIK",
          "Berdasarkan fokus yang dipilih, tentukan pendekatan yang paling relevan: mimetik (untuk analisis realitas sosial), ekspresif (untuk kaitan dengan pengarang), objektif (untuk analisis struktural), atau pragmatik (untuk resepsi pembaca). Bisa juga kombinasi dua pendekatan.",
          "",
          "LANGKAH 4 — MENGUMPULKAN BUKTI TEKSTUAL",
          "Kumpulkan kutipan-kutipan spesifik dari karya yang mendukung argumenmu. Kritik sastra yang baik adalah kritik yang evidence-based — setiap klaim harus didukung oleh bukti tekstual yang jelas, bukan sekadar opini pribadi.",
          "",
          "LANGKAH 5 — MENULIS DENGAN STRUKTUR AKADEMIK",
          "Struktur standar: (a) Pendahuluan — memperkenalkan karya, penulis, dan tesis kritik; (b) Pembahasan — analisis mendalam dengan bukti tekstual dan rujukan teori; (c) Kesimpulan — merangkum temuan dan memberikan penilaian kritis. Gunakan bahasa yang formal, argumentatif, dan impersonal.",
          "",
          "[Ilustrasi: Alur kerja menulis di atas meja: langkah 1 (buku + kaca pembesar) → langkah 2 (kertas dengan lingkaran fokus) → langkah 3 (diagram 4 pendekatan) → langkah 4 (kertas dengan kutipan-kutipan) → langkah 5 (dokumen jadi dengan tinta). Tangan memegang pensil di atas kertas. Gaya ilustrasi meja kerja dengan warna biru navy dan putih.]",
        ],
        contoh: [
          "CONTOH KRITIK SASTRA: ANALISIS NOVEL 'SUTJE' KARYA ALI AUDIAH (fragmen):",
          "",
          "'Sutje' karya Ali Audiah (2020) menghadirkan tokoh Sutje, seorang ibu rumah tangga di Jakarta yang mengalami kehancuran batin setelah anak semata wayangnya meninggal. Menggunakan pendekatan objektif, novel ini menarik untuk dianalisis dari segi narasi dan alur.",
          "",
          "Salah satu kekuatan novel ini adalah penggunaan alur maju-mundur (flashback) yang tidak linear. Ali Audiah dengan cermat menempatkan fragmen-fragmen masa lalu di tengah adegan Sutje di dapur, menciptakan kontras antara rutinitas dapur yang monoton dan kekacauan batin tokoh. Teknik ini memaksa pembaca untuk aktif merekonstruksi kronologi tragedi — sebuah pengalaman membaca yang menuntut empati, bukan sekadar konsumsi pasif.",
          "",
          "Namun, penggunaan alur maju-mundur ini juga memiliki kelemahan. Pada beberapa bagian, transisi antarwaktu terasa mendadak dan membingungkan, terutama di bab 7-9. Hal ini mengurangi koherensi naratif dan membuat pembaca harus berulang kali kembali ke halaman sebelumnya — yang mungkin disengaja untuk menimbulkan efek disorientasi, tetapi bagi sebagian pembaca terasa mengganggu. Kritik terhadap aspek teknis ini justru menjadi pintu diskusi yang menarik: apakah kebingungan pembaca adalah 'cacat' atau justru 'efek yang diinginkan' untuk meniru pengalaman disosiatif tokoh?",
          "",
          "✓ Kritik memberikan analisis struktural (alur), mengevaluasi kelebihan dan kekurangan, serta mengajukan pertanyaan teoretis yang membuka diskusi lebih lanjut.",
        ],
      },
      {
        judul: "Etika Kritik Sastra dan Kesalahan Umum",
        isi: [
          "Menjadi kritikus sastra bukan berarti kamu bisa bebas menulis apa pun tanpa tanggung jawab. Ada etika dan kode etik yang harus dipatuhi, terutama karena opini kritis yang kamu tulis bisa memengaruhi persepsi publik terhadap suatu karya dan bahkan karier pengarangnya.",
          "",
          "ETIKA KRITIK SASTRA:",
          "",
          "1. OBJEKTIVITAS — bedakan antara analisis dan preferensi pribadi. 'Novel ini membosankan' adalah preferensi. 'Novel ini menggunakan alur lambat dengan deskripsi yang panjang tanpa konflik yang memadai di 50 halaman pertama' adalah analisis objektif yang dilengkapi bukti.",
          "",
          "2. ARGUMENTASI BERBUKTI — setiap klaim harus didukung kutipan atau bukti tekstual. Jangan menilai 'penokohan lemah' tanpa menunjukkan bagian mana yang gagal mengembangkan karakter dan menjelaskan mengapa.",
          "",
          "3. KONSTRUKTIF — kritik bukan untuk 'menghabisi' karya, melainkan untuk membangun pemahaman yang lebih baik. Bahkan kritik yang tajam sekalipun harus tetap menghormati proses kreatif pengarang.",
          "",
          "4. KEUJURAN INTELEKTUAL — jangan memaksakan teori atau pendekatan yang tidak relevan hanya untuk terlihat 'ilmiah'. Kritik yang baik memilih pendekatan yang paling tepat untuk karya yang dikritik.",
          "",
          "KESALAHAN UMUM KRITIKUS PEMULA:",
          "• Menulis sinopsis panjang — kritik bukan ringkasan cerita",
          "• Hanya memuji tanpa analisis — itu pujian, bukan kritik",
          "• Menggunakan jargon teoretis tanpa menjelaskan — membuat kritik sulit dipahami",
          "• Tidak menyertakan bukti tekstual — kritik jadi opini kosong",
          "• Membandingkan secara tidak adil — 'karya ini tidak sebagus Pram' tanpa konteks yang sepadan",
          "",
          "[Ilustrasi: Timbangan keseimbangan di atas meja kayu. Di sisi kiri timbangan ada buku sastra, di sisi kanan ada kertas berisi anotasi dan tanda tangan. Di latar belakang, papan tulis kecil bertuliskan 'Kode Etik Kritik Sastra'. Tangan memegang pena di dekat kertas. Gaya ilustrasi meja pengadilan simbolis dengan warna emas dan hitam.]",
        ],
        contoh: [
          "CONTOH KRITIK TIDAK ETIS VS ETIS:",
          "",
          "TIDAK ETIS (opini tanpa bukti):",
          "'Novel ini jelek. Penulisnya tidak berbakat. Karakternya payah. Saya tidak suka. Skor 2/10.'",
          "✗ Ini bukan kritik sastra, ini komentar subjektif tanpa analisis dan tanpa bukti.",
          "",
          "ETIS TAPI LEMAH (analisis tapi tidak mendalam):",
          "'Novel ini menggunakan bahasa sehari-hari yang mudah dipahami. Alurnya cukup menarik. Cocok untuk remaja.'",
          "✓ Ini sudah berusaha analitis tetapi masih dangkal — belum menggunakan pendekatan kritik tertentu.",
          "",
          "KRITIK SASTRA YANG BAIK:",
          "'Menggunakan pendekatan objektif, novel ini memiliki kelemahan signifikan dalam konsistensi sudut pandang. Pada bab 1-3, narator menggunakan sudut pandang orang pertama (tokoh 'aku'), tetapi pada bab 4 tiba-tiba bergeser ke orang ketiga serba tahu tanpa transisi yang jelas. Inkonsistensi ini mengganggu immersi pembaca karena menciptakan jarak naratif yang tidak diantisipasi. Jika pergeseran ini disengaja (mungkin untuk efek tertentu), seharusnya ada penanda atau pola yang konsisten — yang tidak ditemukan dalam novel ini.'",
          "✓ Spesifik, evidence-based, menggunakan istilah teknis dengan tepat, dan memberikan analisis yang konstruktif.",
        ],
      },
    ],
    rangkuman: [
      "[Ilustrasi: Sekelompok mahasiswa duduk melingkar di perpustakaan, berdiskusi dengan buku-buku terbuka. Salah satu mahasiswa menunjuk ke halaman buku yang dianotasi. Suasana diskusi intelektual yang hidup. Gaya ilustrasi ruang baca dengan warna cokelat hangat dan hijau zaitun.]",
      "Kritik sastra adalah analisis, interpretasi, dan evaluasi karya sastra secara ilmiah dan argumentatif — berbeda dengan resensi yang bersifat informatif.",
      "Empat pendekatan Abrams: Mimetik (realitas), Ekspresif (pengarang), Objektif (karya), Pragmatik (pembaca) — kritikus baik mengombinasikan beberapa pendekatan.",
      "Langkah menulis kritik: close reading → menentukan fokus → memilih pendekatan → mengumpulkan bukti tekstual → menulis dengan struktur akademik.",
      "Etika kritik: objektif, argumentasi berbukti, konstruktif, dan kejujuran intelektual. Hindari sinopsis panjang, pujian tanpa analisis, dan jargon tanpa penjelasan.",
      "Kritik sastra yang baik membuka perspektif baru — bukan menjatuhkan karya, melainkan memperkaya pemahaman pembaca dan pengarang.",
    ],
  },
  latihan: makeSoal([
    ["Perbedaan utama antara resensi dan kritik sastra adalah...", ["Resensi lebih panjang dari kritik", "Kritik sastra bersifat analitis dan teoretis, resensi bersifat informatif", "Resensi ditulis oleh kritikus, kritik oleh pembaca biasa", "Tidak ada perbedaan"], 1, "Resensi bersifat informatif dan rekomen-datif, sedangkan kritik sastra menganalisis secara mendalam dengan pendekatan teoretis."],
    ["Manakah yang BUKAN termasuk empat pendekatan kritik sastra menurut Abrams?", ["Mimetik", "Ekspresif", "Objektif", "Dekonstruktif"], 3, "Keempat pendekatan Abrams adalah mimetik, ekspresif, objektif, dan pragmatik — dekonstruktif adalah pendekatan dari teori Derrida, bukan bagian dari klasifikasi Abrams."],
    ["Pendekatan kritik yang berfokus pada hubungan karya dengan realitas disebut...", ["Ekspresif", "Objektif", "Mimetik", "Pragmatik"], 2, "Pendekatan mimetik menilai seberapa akurat karya mencerminkan realitas kehidupan."],
    ["Contoh analisis yang menggunakan pendekatan EKSPRESIF adalah...", ["Menghitung frekuensi kata dalam puisi", "Menghubungkan latar belakang traumatis pengarang dengan tema puisi", "Menilai efek puisi terhadap pembaca", "Menganalisis struktur rima dan ritme"], 1, "Pendekatan ekspresif menghubungkan karya dengan pengarang, termasuk latar belakang hidup dan psikologi pengarang."],
    ["Langkah pertama yang harus dilakukan kritikus sebelum menulis kritik adalah...", ["Menentukan judul kritik", "Membaca karya secara kritis berulang kali", "Mencari teori yang paling rumit", "Menulis kesimpulan"], 1, "Close reading atau membaca kritis adalah langkah pertama dan paling fundamental dalam kritik sastra."],
    ["Mengapa kritikus dianjurkan mengombinasikan beberapa pendekatan?", ["Agar terlihat pintar", "Karena setiap karya hanya cocok untuk satu pendekatan", "Agar menghasilkan analisis yang lebih kaya dan multidimensi", "Karena pendekatan Abrams sudah usang"], 2, "Kombinasi pendekatan menghasilkan analisis yang lebih kaya karena setiap pendekatan membuka aspek yang berbeda dari karya."],
    ["Yang dimaksud 'objektivitas' dalam etika kritik sastra adalah...", ["Kritikus harus netral dan tidak berpihak", "Membedakan antara analisis dan preferensi pribadi, serta didukung bukti tekstual", "Kritikus dilarang memuji", "Semua kritik harus panjang"], 1, "Objektivitas berarti analisis didasarkan pada bukti tekstual, bukan opini subjektif pribadi."],
    ["Kesalahan paling umum kritikus pemula dalam menulis kritik adalah...", ["Menggunakan istilah asing", "Menulis sinopsis panjang tanpa analisis", "Mengutip terlalu banyak", "Menulis terlalu pendek"], 1, "Kesalahan umum adalah menulis sinopsis panjang yang seharusnya adalah ringkasan cerita, bukan analisis kritis."],
    ["Jika seorang kritikus ingin menganalisis efek novel terhadap kesadaran sosial pembaca, pendekatan yang paling tepat adalah...", ["Objektif", "Mimetik", "Ekspresif", "Pragmatik"], 3, "Pendekatan pragmatik berfokus pada efek karya terhadap pembaca, termasuk kesadaran sosial dan moral."],
    ["Kritik sastra yang baik harus bersifat evidence-based, artinya...", ["Setiap klaim didukung kutipan atau bukti tekstual dari karya", "Kritik harus panjang minimal 10 halaman", "Kritik harus menggunakan bahasa Inggris", "Kritik harus disetujui penulis"], 0, "Evidence-based berarti argumen kritikus didukung oleh bukti tekstual yang jelas dari karya yang dikritik."],
  ]),
  praktik: {
    petunjuk: "Pilihlah satu cerpen dari majalah sastra (seperti Horison) atau kumpulan cerpen yang kamu miliki. Bacalah cerpen tersebut minimal 3 kali dengan metode close reading. Tulislah kritik sastra sepanjang 500-700 kata dengan ketentuan: (1) tentukan fokus analisis yang spesifik, (2) gunakan minimal satu pendekatan Abrams, (3) sertakan bukti tekstual berupa kutipan langsung, (4) evaluasi kelebihan dan kekurangan karya secara seimbang, (5) gunakan struktur akademik (pendahuluan-pembahasan-kesimpulan).",
    tips: [
      "Catat semua yang menarik perhatian saat membaca pertama — jangan khawatir tentang struktur dulu",
      "Pilih fokus yang sempit dan spesifik: 'simbolisme warna' lebih baik daripada 'semua aspek sastra'",
      "Tentukan pendekatan setelah membaca, bukan sebelumnya — biarkan karya 'memilih' pendekatannya sendiri",
      "Kumpulkan 3-5 kutipan kuat dari cerpen sebelum mulai menulis — ini akan menjadi tulang punggung argumenmu",
      "Minta teman membaca draf kritikmu dan lihat apakah mereka setuju atau tidak — kritik yang baik memicu perdebatan, bukan sekadar persetujuan",
    ],
    contoh: "Kritik yang baik dimulai dari thesis statement yang jelas. Contoh: 'Cerpen ini menggunakan sudut pandang anak kecil sebagai strategi naratif untuk mengkritik kemunafikan dunia orang dewasa — sebuah teknik yang berhasil pada sebagian besar cerita, meskipun menemui kendala konsistensi pada bagian klimaks.' Dari tesis ini, kamu bisa mengembangkan analisis dengan bukti tekstual dari dialog dan narasi cerpen.",
  },
  kuis: makeSoal([
    ["Siapa pencetus empat pendekatan kritik sastra?", ["Sapardi Djoko Damono", "M.H. Abrams", "Faruk HT", "Goenawan Mohamad"], 1, "Abrams dalam bukunya 'The Mirror and the Lamp' (1953) mengemukakan empat pendekatan kritik sastra."],
    ["Pendekatan yang hanya menganalisis unsur intrinsik karya tanpa menghubungkan faktor luar disebut...", ["Mimetik", "Ekspresif", "Objektif", "Pragmatik"], 2, "Pendekatan objektif memandang karya sebagai otonom dan hanya menganalisis elemen intrinsiknya."],
    ["Fungsi kritik sastra yang membantu pembaca memahami makna tersirat adalah fungsi...", ["Evaluatif", "Kontributif", "Interpretatif", "Dekoratif"], 2, "Fungsi interpretatif membantu pembaca memahami simbol, metafora, dan makna tersirat dalam karya."],
    ["Yang membedakan kritik sastra dari ulasan buku biasa adalah...", ["Kritik sastra menggunakan pendekatan teoretis dan analisis mendalam", "Kritik sastra harus panjang", "Ulasan buku tidak boleh memuji", "Kritik sastra hanya untuk novel"], 0, "Kritik sastra menggunakan landasan teoretis dan analisis sistematis, bukan sekadar opini."],
    ["Dalam etika kritik, 'konstruktif' berarti...", ["Kritik harus lembut dan tidak menyinggung", "Kritik ditujukan untuk membangun pemahaman yang lebih baik, bukan menghabisi karya", "Kritik hanya boleh menyebut kelebihan", "Kritik harus disetujui penulis"], 1, "Kritik konstruktif membangun pemahaman yang lebih baik, bukan untuk menjatuhkan karya atau pengarang."],
    ["Teknik membaca berulang dengan mencatat detail dan pola dalam karya disebut...", ["Skimming", "Scanning", "Close reading", "Speed reading"], 2, "Close reading adalah teknik membaca kritis dengan mencatat detail, pola, dan makna tersirat secara saksama."],
    ["Jika seorang kritikus menganalisis novel untuk memahami kondisi sosial-politik saat novel ditulis, ia menggunakan pendekatan...", ["Objektif", "Mimetik", "Ekspresif", "Pragmatik"], 1, "Pendekatan mimetik menghubungkan karya dengan realitas, termasuk kondisi sosial-politik."],
    ["Kesalahan etika ketika kritikus memaksakan teori yang tidak relevan ke dalam sebuah karya disebut...", ["Plagiarisme", "Objektivitas", "Ketidakjujuran intelektual", "Subjektivitas"], 2, "Ketidakjujuran intelektual terjadi ketika kritikus memaksakan teori yang tidak relevan hanya untuk terlihat ilmiah."],
    ["Bagian kritik sastra yang berisi tesis dan pengenalan karya disebut...", ["Pembahasan", "Kesimpulan", "Abstrak", "Pendahuluan"], 3, "Pendahuluan dalam kritik sastra berisi pengenalan karya, penulis, dan tesis kritik."],
    ["Tujuan akhir dari kritik sastra yang baik adalah...", ["Membuktikan bahwa sebuah karya jelek", "Membuka perspektif baru dan memperkaya pemahaman pembaca", "Menjual buku", "Membuat pengarang terkenal"], 1, "Kritik sastra bertujuan membuka perspektif baru dan memperkaya pemahaman, bukan sekadar menilai."],
  ]),
}
export default konten
