import type { Konten } from "../types"
import { makeSoal } from "../types"

const konten: Konten = {
  belajar: {
    tujuan: [
      "Memahami pengertian, ciri, dan jenis esai sebagai tulisan argumentatif personal",
      "Mengidentifikasi struktur esai: tesis, argumen, counter-argument, dan kesimpulan",
      "Menganalisis penggunaan diksi, gaya bahasa, dan retorika dalam esai populer",
      "Menyusun esai argumentatif dengan tesis yang jelas dan argumen yang logis",
      "Mengevaluasi kekuatan argumentasi dalam esai berdasarkan bukti dan koherensi",
    ],
    materi: [
      {
        judul: "Apa Itu Esai?",
        isi: [
          "Esai adalah tulisan prosa yang mengungkapkan pandangan pribadi penulis terhadap suatu topik secara argumentatif, reflektif, dan sering kali personal. Kata 'esai' berasal dari bahasa Prancis 'essayer' yang berarti 'mencoba' — esai adalah upaya penulis untuk 'mencoba' memahami dan menjelaskan suatu persoalan.",
          "",
          "Ciri khas esai yang membedakannya dari tulisan ilmiah formal:",
          "",
          "1. SUBJEKTIFITAS YANG TERKONTROL — esai menyuarakan 'aku' penulis, opini pribadi yang didukung argumen. Namun bukan opini emosional tanpa dasar — opini dalam esai tetap harus logis dan berbasis fakta.",
          "",
          "2. NADA PERSONAL — esai ditulis dengan suara (voice) yang khas. Pembaca bisa 'mendengar' kepribadian penulis melalui pilihan kata, ritme kalimat, dan cara bertutur.",
          "",
          "3. STRUKTUR ARGUMENTATIF — meskipun personal, esai bukan curhatan. Esai yang baik memiliki tesis jelas, argumen logis, counter-argument, dan kesimpulan yang memuaskan secara intelektual.",
          "",
          "4. MENARIK DAN REFLEKTIF — esai tidak hanya memberi informasi, tetapi juga mengajak pembaca berpikir. Esai yang sukses membuat pembaca berhenti sejenak, merenung, atau bahkan mengubah pandangan.",
          "",
          "Jenis esai berdasarkan konten: (a) Esai Deskriptif — melukiskan sesuatu dengan detail sensorik, (b) Esai Naratif — bercerita dengan makna reflektif, (c) Esai Argumentatif — meyakinkan dengan logika dan bukti, (d) Esai Reflektif — merenungkan pengalaman pribadi, (e) Esai Kritik — analisis kritis terhadap karya atau fenomena.",
          "",
          "[Ilustrasi: Seorang penulis duduk di meja kayu dekat jendela besar, menulis di buku catatan dengan pena. Di luar jendela terlihat pepohonan rindang. Di atas meja: secangkir kopi, tumpukan buku, dan laptop tertutup. Cahaya matahari masuk melalui jendela, menciptakan bayangan hangat. Gaya ilustrasi santai kontemplatif dengan warna krem dan cokelat.]",
        ],
        contoh: [
          "PERBANDINGAN CARA PENULISAN ESAI vs KARYA ILMIAH:",
          "",
          "KARYA ILMIAH (objektif, impersonal):",
          "'Berdasarkan data BPS tahun 2025, tingkat literasi digital di Indonesia berada di angka 62,3%. Angka ini menunjukkan peningkatan sebesar 4,5% dibanding tahun sebelumnya. Faktor-faktor yang memengaruhi antara lain penetrasi internet dan program literasi pemerintah.'",
          "",
          "ESAI (personal, argumentatif):",
          "'Saya termasuk generasi yang tumbuh bersama internet — dan saya jujur prihatin. Angka literasi digital 62,3% mungkin naik 4,5%, tapi apa artinya jika kenaikan itu lebih banyak didorong oleh TikTok daripada oleh pemahaman kritis terhadap informasi? Saya khawatir kita sedang menciptakan generasi yang 'melek' secara teknis buta secara intelektual. Esai ini bukan untuk menyerang teknologi, melainkan mengajak kamu — pembaca — bertanya: seberapa kritis kita sebenarnya saat menggulir layar setiap hari?'",
          "✓ Esai menggunakan 'saya', nada personal, dan mengajak pembaca berpikir.",
        ],
        catatan: "Esai adalah bentuk tulisan paling 'bebas' di antara jenis tulisan lainnya — tapi jangan terkecoh dengan kebebasannya. Esai yang terlihat 'mengalir begitu saja' sebenarnya ditulis dengan struktur yang ketat dan pilihan kata yang cermat. Esais hebat seperti Goenawan Mohamad atau Seno Gumira Ajidarma bisa menulis esai yang terasa seperti obrolan santai, tetapi setiap katanya sudah dipertimbangkan dengan teliti.",
      },
      {
        judul: "Struktur Esai: Dari Tesis hingga Kesimpulan",
        isi: [
          "Esai bukanlah 'tulisan bebas tanpa aturan'. Esai yang baik memiliki struktur internal yang logis dan koheren. Tanpa struktur, esai akan terasa seperti kumpulan opini yang melompat-lompat dan tidak meyakinkan.",
          "",
          "STRUKTUR ESAI ARGUMENTATIF 5-PARAGRAF (standar akademik):",
          "",
          "1. PENDAHULUAN (1 paragraf)",
          "  • Hook — kalimat pembuka yang menarik perhatian (kutipan mengejutkan, pertanyaan retoris, statistik, atau anekdot singkat)",
          "  • Latar belakang — konteks singkat topik yang dibahas",
          "  • Tesis — pernyataan inti esai (1 kalimat) yang menjadi fokus seluruh tulisan",
          "",
          "2. ARGUMEN 1 — bukti, contoh, dan analisis yang mendukung tesis",
          "",
          "3. ARGUMEN 2 — bukti dan analisis tambahan, bisa dari sudut pandang berbeda",
          "",
          "4. COUNTER-ARGUMEN & REFUTASI — akui sudut pandang lawan, lalu bantah dengan logika. Inilah yang membedakan esai bagus dari sekadar 'opini sepihak'.",
          "",
          "5. KESIMPULAN (1 paragraf)",
          "  • Ringkasan argumen tanpa mengulang kata-kata yang sama persis",
          "  • Restatement tesis dengan cara baru",
          "  • Call to action atau pertanyaan untuk perenungan pembaca",
          "",
          "PENTING: Struktur 5-paragraf adalah 'kerangka dasar', bukan 'kandang'. Esais profesional sering memodifikasi struktur ini — menggabungkan paragraf, menambahkan sub-argumen, atau mengubah urutan — sesuai kebutuhan tulisan. Yang penting adalah koherensi logis, bukan kepatuhan buta pada format.",
          "",
          "[Ilustrasi: Diagram esai 5 paragraf dalam bentuk piramida terbalik → kotak-kotak → piramida tegak. Pendahuluan sebagai piramida terbalik (dari hook lebar ke tesis sempit), argumen 1-3 sebagai kotak-kotak sejajar, counter-argument sebagai kotak bergerigi, kesimpulan sebagai piramida tegak (dari ringkasan ke call to action). Gaya ilustrasi infografis akademik dengan warna biru dan abu-abu.]",
        ],
        contoh: [
          "CONTOH ESAI SINGKAT (fragmen) — 'Mengapa Saya Berhenti Scroll TikTok':",
          "",
          "PENDAHULUAN dengan hook: 'Tiga bulan lalu, saya menghapus TikTok dari ponsel saya. Bukan karena orang tua saya menyuruh — justru mereka yang paling sering mengirimkan video lucu ke grup keluarga. Saya berhenti karena saya sadar: aplikasi bernilai 50 miliar dolar itu dirancang untuk membuat saya tidak bisa berhenti.'",
          "",
          "TESIS: 'Esai ini berargumen bahwa media sosial berbasis algoritma, meskipun memberikan hiburan, secara sistematis mengurangi kemampuan kita untuk fokus, berpikir panjang, dan merenung — dan generasi Z adalah korban utamanya.'",
          "",
          "COUNTER-ARGUMEN: 'Tentu, ada yang berargumen bahwa TikTok bisa menjadi alat edukasi — banyak kreator konten yang mengajarkan sejarah, sains, atau bahasa dalam format pendek, dan itu memang benar.'",
          "",
          "REFUTASI: 'Namun, format pendek justru menjadi masalah. Pengetahuan yang disajikan dalam 60 detik cenderung disederhanakan secara berlebihan. Sejarah tidak bisa diringkas dalam 30 detik tanpa kehilangan nuansa dan kompleksitas — dan membiasakan otak menerima simplifikasi adalah langkah mundur bagi cara kita berpikir.'",
        ],
      },
      {
        judul: "Retorika dan Gaya Bahasa dalam Esai",
        isi: [
          "Esai yang meyakinkan tidak hanya membutuhkan argumen yang kuat, tetapi juga cara penyampaian yang memikat. Retorika — seni berbicara/menulis secara persuasif — adalah alat esais untuk membuat argumen tidak hanya logis, tetapi juga berkesan dan menyentuh.",
          "",
          "TIGA PILAR RETORIKA (Aristoteles):",
          "",
          "1. ETHOS (kredibilitas) — pembaca harus percaya pada penulis. Bangun ethos dengan: menunjukkan pengetahuan tentang topik, menggunakan sumber terpercaya, bersikap jujur (mengakui keterbatasan argumen sendiri), dan menggunakan bahasa yang sesuai dengan topik dan audiens.",
          "",
          "2. PATHOS (emosi) — sentuh perasaan pembaca. Gunakan anekdot personal, metafora yang kuat, deskripsi sensorik, dan pilihan kata yang bermuatan emosi. Namun hati-hati: pathos tanpa logos adalah manipulasi.",
          "",
          "3. LOGOS (logika) — argumen harus masuk akal. Gunakan data statistik, fakta, analogi logis, dan reasoning yang ketat. Setiap klaim harus memiliki justifikasi.",
          "",
          "TEKNIK GAYA BAHASA DALAM ESAI:",
          "• Anekdot — cerita pendek personal yang relevan untuk mengilustrasikan argumen",
          "• Metafora dan analogi — 'Media sosial adalah candu digital' lebih kuat dari 'Media sosial membuat ketagihan'",
          "• Pertanyaan retoris — 'Apa artinya menjadi pintar di era informasi yang melimpah?' — melibatkan pembaca",
          "• Klimaks dan antiklimaks — membangun tensi lalu melepasnya untuk efek dramatis",
          "• Ironi dan paradoks — mengejutkan pembaca dengan kontradiksi yang mencerahkan",
          "",
          "[Ilustrasi: Panggung retorika Yunani kuno dengan tiga tiang besar berlabel Ethos (topeng kepercayaan), Pathos (topeng emosi), Logos (topeng logika). Di depan panggung, seorang pembicara berdiri dengan tangan terbuka. Di latar belakang, penonton yang terpukau. Gaya ilustrasi perpaduan klasik dan modern dengan warna marmer dan emas.]",
        ],
        contoh: [
          "CONTOH PENGGUNAAN RETORIKA DALAM ESAI:",
          "",
          "ETHOS (membangun kredibilitas):",
          "'Sebagai jurnalis yang meliput isu pendidikan sejak 2015, saya telah menyaksikan langsung bagaimana kebijakan zonasi sekolah — yang awalnya dirancang untuk menghapus diskriminasi — justru menciptakan bentuk ketidakadilan baru di lapangan.'",
          "",
          "PATHOS (menyentuh emosi):",
          "'Saya ingat Rina, siswa kelas 9 di pinggiran Jakarta. Setiap hari ia bangun pukul 4 pagi, naik angkot tiga kali, hanya untuk sampai ke sekolah 'unggulan' yang berjarak 25 km dari rumahnya. Zonasi seharusnya mendekatkan, bukan menjauhkan.'",
          "",
          "LOGOS (menggunakan logika dan data):",
          "'Data Kemendikbud 2025 menunjukkan bahwa 63% siswa yang mendaftar ke sekolah di luar zona mereka gagal mendapatkan kursi, sementara 28% kursi di sekolah favorit tetap kosong karena tidak ada siswa dalam zona yang memenuhi nilai ambang batas. Ini adalah ironi: kuota kosong, tapi anak-anak di luar zona tidak bisa mengisinya.'",
          "",
          "✓ Esai yang kuat memadukan ketiga elemen: ethos mempercayakan, pathos menyentuh, logos meyakinkan.",
        ],
      },
      {
        judul: "Langkah Menulis Esai dan Etika Akademik",
        isi: [
          "Menulis esai yang berbobot membutuhkan proses, bukan sekadar menuangkan ide yang melintas di kepala. Esais profesional memiliki rutinitas dan metode yang bisa kamu tiru.",
          "",
          "LANGKAH-LANGKAH MENULIS ESAI:",
          "",
          "1. PEMILIHAN TOPIK DAN TESIS",
          "  Pilih topik yang (a) kamu pedulikan, (b) memiliki kontroversi atau kompleksitas, dan (c) cukup sempit untuk dibahas dalam satu esai. Contoh sempit: 'Dampak AI terhadap kreativitas menulis mahasiswa' lebih baik dari 'Dampak AI terhadap pendidikan'.",
          "",
          "2. RISET DAN BRAINSTORMING",
          "  Kumpulkan data, fakta, dan perspektif yang beragam. Baca pendapat yang setuju dan yang menentang. Semakin paham kamu dengan sisi lawan, semakin kuat argumenmu — karena kamu sudah siap membantahnya.",
          "",
          "3. OUTLINING",
          "  Buat kerangka esai: tesis → 3 argumen utama → counter-argument → kesimpulan. Tentukan bukti apa yang akan digunakan di setiap bagian. Outlining mencegah tulisan melebar tidak terkendali.",
          "",
          "4. PENULISAN DRAF",
          "  Tulis tanpa mengedit dulu. Biarkan ide mengalir. Khawatir tentang struktur dan pilihan kata nanti. Banyak esais hebat menulis draf 'jelek' yang kemudian disempurnakan.",
          "",
          "5. REVISI DAN EDITING",
          "  Revisi isi: apakah argumen masuk akal? Apakah ada bukti yang cukup? Apakah urutan logis? Editing bahasa: periksa ejaan, pilihan kata, variasi kalimat, dan tone. Potong kata-kata yang tidak perlu.",
          "",
          "ETIKA PENULISAN ESAI: jangan plagiat, jangan manipulasi data, jangan buat klaim palsu. Esai adalah karya intelektual — kejujuran adalah fondasinya.",
          "",
          "[Ilustrasi: Meja penulis dengan 5 area: (1) topik tertulis di sticky note, (2) tumpukan buku referensi, (3) kerangka di papan tulis kecil, (4) laptop dengan draf terbuka, (5) kertas revisi dengan coretan merah. Tangan memegang kopi di dekat laptop. Gaya ilustrasi meja kerja produktif dengan warna hijau toska dan kayu.]",
        ],
        contoh: [
          "CONTOH ESAI LENGKAP: 'PUISI DI TENGAH AI' (fragmen kesimpulan):",
          "",
          "'Mungkin kita tidak perlu takut pada AI yang bisa menulis puisi. Yang perlu kita takuti adalah generasi yang berhenti menulis puisi karena 'sudah ada yang buat'. Karena pada akhirnya, menulis bukanlah soal menghasilkan teks — melainkan soal proses memahami diri sendiri. AI bisa meniru kata-kata Chairil Anwar, tapi AI tidak pernah mengalami kegelisahan yang melahirkannya. Dan selama manusia masih memiliki kegelisahan, puisi tidak akan mati. Ia hanya menunggu dituliskan oleh tangan yang berani meraba jiwanya sendiri.'",
          "",
          "✓ Esai ini menggunakan gaya bahasa puitis, retorika (pertanyaan retoris, kontras), dan argumen yang jelas.",
        ],
      },
    ],
    rangkuman: [
      "[Ilustrasi: Kompilasi esai-esai terkenal dari berbagai penulis Indonesia — buku Goenawan Mohamad 'Catatan Pinggir', Seno Gumira Ajidarma 'Ketika Jurnalisme Dibungkam Sastra Harus Bicara', dan Pandji Pragiwaksono 'Merdeka dalam Batas'. Buku-buku tersusun rapi dengan pembatas buku. Gaya ilustrasi perpustakaan minimalis dengan warna krem dan cokelat.]",
      "Esai adalah tulisan argumentatif personal dengan ciri: subjektifitas terkontrol, nada personal, struktur argumentatif, dan reflektif.",
      "Struktur esai: Pendahuluan (hook, latar belakang, tesis) → Argumen 1-3 → Counter-argument & Refutasi → Kesimpulan.",
      "Tiga pilar retorika Aristoteles: Ethos (kredibilitas), Pathos (emosi), Logos (logika) — esai kuat memadukan ketiganya.",
      "Langkah menulis: pilih topik + tesis → riset → outlining → draf → revisi & editing.",
      "Kejujuran intelektual adalah fondasi esai — jangan plagiat, jangan manipulasi data, jangan klaim palsu.",
    ],
  },
  latihan: makeSoal([
    ["Asal kata 'esai' dari bahasa Prancis 'essayer' yang berarti...", ["Menulis", "Mencoba", "Berdebat", "Meyakinkan"], 1, "Essayer berarti 'mencoba' — esai adalah upaya penulis untuk mencoba memahami dan menjelaskan suatu persoalan."],
    ["Yang membedakan esai dari karya ilmiah formal adalah...", ["Esai menggunakan bahasa asing", "Esai bersifat subjektif dengan 'suara' personal penulis", "Esai harus panjang", "Esai tidak boleh menggunakan data"], 1, "Esai menyuarakan pandangan pribadi penulis dengan nada personal yang khas, sementara karya ilmiah bersifat impersonal."],
    ["Bagian esai yang berfungsi sebagai 'hook' adalah...", ["Kalimat pembuka yang menarik perhatian", "Argumen utama", "Counter-argument", "Kesimpulan"], 0, "Hook adalah kalimat pembuka esai yang bertujuan menarik perhatian pembaca."],
    ["Tiga pilar retorika menurut Aristoteles adalah...", ["Ethos, Epos, Mythos", "Ethos, Pathos, Logos", "Pathos, Logos, Sophos", "Ethos, Pathos, Nomos"], 1, "Tiga pilar retorika Aristoteles adalah Ethos, Pathos, dan Logos."],
    ["Fungsi counter-argument dalam esai adalah...", ["Melemahkan tesis", "Mengakui sudut pandang lawan lalu membantahnya untuk memperkuat argumen", "Menambah panjang esai", "Menghilangkan argumen utama"], 1, "Counter-argument mengakui sudut pandang lawan lalu membantahnya dengan logika."],
    ["Contoh teknik retorika yang menggunakan cerita pendek personal adalah...", ["Metafora", "Analogi", "Anekdot", "Ironi"], 2, "Anekdot adalah cerita pendek personal yang relevan untuk mengilustrasikan argumen."],
    ["Pernyataan tesis dalam esai sebaiknya...", ["Panjang dan detail", "Samar agar misterius", "Jelas, spesifik, dan menjadi fokus seluruh esai", "Berupa pertanyaan"], 2, "Tesis harus jelas, spesifik, dan menjadi fondasi seluruh argumen esai."],
    ["Mengapa esais perlu membaca pendapat yang menentang tesisnya?", ["Agar bingung", "Untuk memperkuat argumen dengan siap membantah sudut pandang lawan", "Agar setuju dengan lawan", "Supaya esai lebih panjang"], 1, "Memahami sisi lawan mempersiapkan penulis untuk membantahnya dengan logika."],
    ["Yang BUKAN termasuk jenis esai berdasarkan konten adalah...", ["Esai deskriptif", "Esai naratif", "Esai argumentatif", "Esai matematis"], 3, "Jenis esai: deskriptif, naratif, argumentatif, reflektif, dan kritik."],
  ]),
  praktik: {
    petunjuk: "Pilihlah satu topik kontroversial yang dekat dengan kehidupan remaja (misalnya: 'Seragam sekolah perlu dihapus', 'Anak SMA boleh membawa HP ke kelas', atau 'Pelajaran Bahasa Indonesia di era AI: masih relevan?'). Tulislah esai argumentatif sepanjang 600-800 kata dengan struktur: (1) hook yang menarik, (2) tesis yang jelas, (3) tiga argumen utama dengan bukti, (4) satu counter-argument dan refutasi, (5) kesimpulan dengan call to action. Gunakan setidaknya satu teknik retorika (ethos/pathos/logos) di setiap bagian.",
    tips: [
      "Pilih topik yang benar-benar kamu pedulikan — antusiasme akan terdengar dalam tulisanmu",
      "Tulis tesis dalam satu kalimat dan tempelkan di dekat layar — jangan sampai tulisan melenceng dari tesis",
      "Kumpulkan 2-3 data/fakta pendukung sebelum menulis — data membuat argumen tidak sekadar opini",
      "Jangan takut menulis draf 'jelek' — esai hebat lahir dari revisi, bukan dari draf pertama yang sempurna",
      "Baca ulang esaimu dengan keras — telinga lebih peka mendeteksi kalimat yang kaku atau tidak alami daripada mata",
    ],
    contoh: "Hook yang kuat untuk topik 'Seragam sekolah perlu dihapus': 'Setiap Senin pagi, 40 juta siswa Indonesia memakai pakaian yang sama. Bukan karena mereka sepakat, tapi karena peraturan. Tapi apakah kebijakan yang lahir di era kolonial Belanda ini masih relevan untuk membentuk karakter generasi abad ke-21?' — Hook ini menggunakan fakta mengejutkan (40 juta), konteks historis, dan pertanyaan retoris yang langsung mengarah ke tesis.",
  },
  kuis: makeSoal([
    ["Ciri paling khas yang membedakan esai dari jenis tulisan lain adalah...", ["Bersifat ilmiah dan objektif", "Mengungkapkan pandangan pribadi penulis dengan nada personal", "Harus menggunakan data statistik", "Tidak boleh menggunakan 'saya'"], 1, "Ciri khas esai adalah pandangan pribadi penulis dengan nada personal."],
    ["Dalam struktur esai 5-paragraf, bagian yang membedakan esai bagus dari opini sepihak adalah...", ["Argumen 1", "Argumen 2", "Counter-argument dan refutasi", "Kesimpulan"], 2, "Counter-argument dan refutasi membedakan esai dari opini sepihak."],
    ["Kalimat berikut yang termasuk 'hook' efektif adalah...", ["Esai ini membahas pendidikan", "Pernahkah kamu merasa terjebak di tengah hiruk pikuk media sosial?", "Pendidikan adalah hal penting", "Saya akan menulis tentang AI"], 1, "Pertanyaan retoris 'Pernahkah kamu...?' adalah hook yang efektif."],
    ["Ethos dalam retorika berkaitan dengan...", ["Emosi pembaca", "Logika argumen", "Kredibilitas penulis", "Gaya bahasa"], 2, "Ethos berkaitan dengan kredibilitas dan kepercayaan pembaca pada penulis."],
    ["Mengapa esais tidak boleh hanya menggunakan pathos tanpa logos?", ["Karena pathos tidak penting", "Tanpa logos, esai menjadi manipulasi emosional tanpa dasar nalar", "Karena logos lebih mudah", "Karena pembaca tidak suka emosi"], 1, "Pathos tanpa logos adalah manipulasi emosional tanpa dasar nalar."],
    ["Fungsi 'restatement tesis' dalam kesimpulan esai adalah...", ["Mengulang tesis persis kata per kata", "Menyatakan ulang tesis dengan cara baru yang menunjukkan perkembangan argumen", "Menghapus tesis", "Menambahkan argumen baru"], 1, "Restatement mengulang tesis dengan cara baru yang menunjukkan perkembangan argumen."],
    ["Contoh pertanyaan retoris dalam esai adalah...", ["Berapa umurmu?", "Apa artinya menjadi pintar di era informasi yang melimpah?", "Siapa namamu?", "Dimana rumahmu?"], 1, "Pertanyaan retoris bertujuan membuat pembaca merenung, bukan dijawab."],
    ["Yang BUKAN langkah dalam proses menulis esai adalah...", ["Pemilihan topik", "Riset", "Plagiarisme", "Revisi"], 2, "Plagiarisme adalah pelanggaran etika, bukan langkah penulisan."],
    ["Mengapa topik esai sebaiknya sempit dan spesifik?", ["Agar lebih mudah", "Agar pembahasan fokus dan mendalam dalam batasan yang terkelola", "Karena guru menyuruh", "Agar lebih panjang"], 1, "Topik sempit memungkinkan analisis mendalam dalam batasan esai."],
    ["Tujuan utama menulis esai adalah...", ["Mendapat nilai bagus", "Mengajak pembaca berpikir, merenung, dan melihat perspektif baru", "Membuat pembaca setuju", "Menjadi terkenal"], 1, "Esai bertujuan mengajak pembaca berpikir kritis dan membuka perspektif baru."],
  ]),
}
export default konten
