import type { Konten } from "../types"
import { makeSoal } from "../types"

const konten: Konten = {
  belajar: {
    tujuan: [
      "Memahami pengertian, fungsi, dan jenis resensi buku fiksi dan nonfiksi",
      "Mengidentifikasi struktur resensi yang lengkap dan profesional",
      "Menganalisis unsur intrinsik dan ekstrinsik karya dalam resensi",
      "Menyusun resensi buku yang kritis, informatif, dan objektif",
      "Mengevaluasi kualitas resensi berdasarkan kedalaman analisis dan kejelasan rekomendasi",
    ],
    materi: [
      {
        judul: "Apa Itu Resensi?",
        isi: [
          "Resensi adalah ulasan atau penilaian terhadap suatu karya — bisa buku, film, drama, album musik, atau pameran seni. Kata 'resensi' berasal dari bahasa Latin 'recensere' yang berarti 'memeriksa kembali' atau 'menimbang'. Jadi, meresensi berarti memeriksa karya dengan saksama lalu menimbang kualitasnya.",
          "",
          "Fungsi resensi dalam dunia literasi:",
          "",
          "1. FUNGSI INFORMATIF — memberikan informasi tentang karya kepada calon pembaca: sinopsis singkat, genre, penulis, dan konteks karya. Ini membantu pembaca memutuskan apakah karya tersebut layak dibaca atau tidak.",
          "",
          "2. FUNGSI EVALUATIF — menilai kualitas karya dengan argumen yang jelas: apa kekuatan dan kelemahannya, bagaimana gaya penulisan, apakah temanya relevan, dan sebagainya.",
          "",
          "3. FUNGSI PROMOTIF — resensi yang baik bisa meningkatkan minat baca masyarakat terhadap suatu buku. Ulasan positif dari resensi terpercaya sering menjadi faktor penentu seseorang membeli buku.",
          "",
          "4. FUNGSI KRITIS — resensi juga menjadi ruang diskusi intelektual. Resensor bisa mengkritisi ide penulis, membandingkan dengan karya lain, atau menghubungkan dengan isu yang lebih luas.",
          "",
          "Jenis resensi: (a) Resensi Informatif — fokus pada deskripsi isi, cocok untuk katalog atau pengumuman, (b) Resensi Evaluatif — fokus pada penilaian kritis, biasa di media massa atau jurnal, (c) Resensi Deskriptif — gambaran umum tanpa penilaian mendalam, (d) Resensi Akademik — analisis ilmiah dengan pendekatan keilmuan tertentu.",
          "",
          "[Ilustrasi: Meja kafe dengan secangkir kopi, buku terbuka yang sedang diulas, dan laptop di sampingnya. Di halaman buku terlihat catatan tempel berwarna-warni. Tangan memegang pulpen di atas buku catatan yang bertuliskan draf resensi. Suasana santai namun literat. Gaya ilustrasi kafe literer dengan warna cokelat hangat dan krem.]",
        ],
        contoh: [
          "CONTOH RESENSI INFORMATIF vs EVALUATIF UNTUK NOVEL 'PERGI' KARYA TERE LIYE:",
          "",
          "RESENSI INFORMATIF:",
          "'Pergi' adalah novel ketiga dari seri 'Dunia Paralel' karya Tere Liye, diterbitkan oleh Gramedia Pustaka Utama pada 2024. Novel setebal 456 halaman ini bercerita tentang Raib, seorang remaja yang memiliki kemampuan menghilang, dan petualangannya di dunia paralel. Novel ini merupakan kelanjutan dari 'Bulan' dan 'Matahari'.",
          "",
          "RESENSI EVALUATIF:",
          "'Pergi' melanjutkan tradisi Tere Liye dalam membangun dunia fantasi yang imersif. Dunia paralel yang ia ciptakan memiliki sistem sihir, politik, dan sejarah yang konsisten — sebuah pencapaian yang tidak mudah dalam genre fantasi. Namun, novel ini memiliki kelemahan pada pacing: 150 halaman pertama terasa lambat dengan deskripsi yang berlebihan. Karakter baru diperkenalkan dengan informasi dump yang membuat pembaca kewalahan. Meskipun demikian, klimaks di 100 halaman terakhir sangat memuaskan dan membuat frustrasi awal terbayar. 'Pergi' layak dibaca oleh penggemar setia Tere Liye, tetapi pembaca baru disarankan memulai dari seri pertama ('Bulan') untuk memahami konteksnya.",
          "✓ Resensi evaluatif memberikan penilaian kritis dengan argumen dan bukti spesifik.",
        ],
        catatan: "Menulis resensi itu seperti menjadi 'jembatan' antara buku dan calon pembacanya. Kamu bukan hakim yang menghukum buku, melainkan pemandu yang membantu pembaca memutuskan. Resensi yang baik tidak harus panjang — yang penting adalah jujur, argumentatif, dan membantu. Bahkan resensi 200 kata di Goodreads bisa lebih bermanfaat daripada esai 2000 kata yang tidak fokus.",
      },
      {
        judul: "Struktur Resensi Buku yang Profesional",
        isi: [
          "Resensi profesional memiliki struktur yang sistematis. Dengan mengikuti struktur ini, resensimu akan mudah dipahami, informatif, dan meyakinkan.",
          "",
          "STRUKTUR BAKU RESENSI BUKU:",
          "",
          "1. IDENTITAS BUKU (DATA BIBLIOGRAFI)",
          "  Judul buku, penulis, penerbit, tahun terbit, tebal halaman, ISBN. Pastikan data akurat — kesalahan pada identitas buku mengurangi kredibilitas resensor.",
          "",
          "2. PEMBUKAAN (LEAD)",
          "  Paragraf pembuka yang menarik — bisa berupa kutipan menarik dari buku, fakta tentang penulis, relevansi tema dengan situasi terkini, atau pertanyaan retoris. Lead adalah 'gerbang' — jika membosankan, pembaca tidak akan melanjutkan.",
          "",
          "3. SINOPSIS / RINGKASAN ISI",
          "  Jelaskan isi buku secara singkat (jangan spoiler berlebihan! terutama untuk novel). Untuk nonfiksi, sebutkan tesis utama penulis dan argumen-argumen kunci. Sinopsis yang baik adalah 2-3 paragraf, tidak lebih dari 30% total resensi.",
          "",
          "4. ANALISIS DAN EVALUASI",
          "  Ini adalah 'jantung' resensi. Analisis: kekuatan dan kelemahan buku, gaya penulisan, kualitas argumen, struktur, karakter (untuk fiksi), orisinalitas, dan kontribusi terhadap bidangnya. Evaluasi harus objektif — sebutkan bukti spesifik, jangan hanya 'bagus' atau 'jelek'.",
          "",
          "5. PERBANDINGAN (OPSIONAL)",
          "  Bandingkan dengan karya lain dari penulis yang sama atau dari tema serupa. Ini membantu pembaca yang sudah familiar dengan genre tertentu untuk memposisikan buku.",
          "",
          "6. KESIMPULAN DAN REKOMENDASI",
          "  Siapa target pembaca yang cocok? 'Buku ini cocok untuk...' atau 'Tidak disarankan untuk...' Beri rating jika relevan. Tutup dengan kalimat yang berkesan.",
          "",
          "[Ilustrasi: Template resensi di layar laptop dengan 6 bagian berwarna berbeda: Identitas (biru), Pembuka (hijau), Sinopsis (kuning), Analisis (jingga), Perbandingan (ungu), Kesimpulan (merah). Masing-masing bagian diwakili ikon: buku, pintu, ringkasan, kaca pembesar, timbangan, bintang. Gaya ilustrasi dashboard dengan warna-warna pastel.]",
        ],
        contoh: [
          "CONTOH RESENSI (fragmen — analisis dan evaluasi):",
          "",
          "ANALISIS KELEBIHAN:",
          "'Salah satu kekuatan utama buku 'Filosofi Teras' karya Henry Manampiring adalah kemampuannya menyajikan filosofi Stoa — yang berasal dari Yunani kuno — dalam konteks yang sangat relevan dengan kehidupan urban modern. Analogi-analoginya tentang macet, gaji, dan media sosial membuat pembaca merasa: 'Oh, ini tentang gue banget.' Gaya bahasa yang ringan, jenaka, dan bebas jargon filosofis menjadikan buku ini aksesibel bagi pembaca awam tanpa mengorbankan kedalaman konsep.'",
          "",
          "ANALISIS KELEMAHAN:",
          "'Namun, buku ini memiliki kelemahan dalam struktur argumen. Pada beberapa bab (terutama bab 5 dan 8), Manampiring cenderung mengulang argumen yang sama dengan contoh yang berbeda, membuat buku terasa repetitif. Selain itu, kritik terhadap keterbatasan Stoa — misalnya dalam menghadapi trauma mendalam atau ketidakadilan struktural — hanya disinggung sepintas di bab akhir tanpa pembahasan yang memadai. Pembaca yang ingin pendekatan kritis mungkin merasa kurang puas.'",
          "",
          "REKOMENDASI:",
          "'Buku ini sangat direkomendasikan untuk pembaca yang baru mengenal filosofi Stoa dan mencari panduan praktis untuk hidup lebih tenang. Namun, pembaca yang sudah familiar dengan Stoicisme klasik (seperti Marcus Aurelius atau Seneca) mungkin akan merasa buku ini terlalu dasar. Rating: 4/5.'",
        ],
      },
      {
        judul: "Unsur yang Dinilai dalam Resensi",
        isi: [
          "Agar resensi berbobot, kamu perlu tahu aspek-aspek apa yang harus dinilai. Resensi yang baik tidak menilai 'suka atau tidak suka', melainkan mengevaluasi kualitas berdasarkan kriteria yang jelas.",
          "",
          "UNTUK BUKU FIKSI (novel, cerpen, kumpulan puisi):",
          "",
          "1. TEMA — apakah temanya relevan, universal, atau justru klise? Apakah penulis mampu mengembangkan tema dengan konsisten dari awal hingga akhir?",
          "",
          "2. ALUR (PLOT) — apakah alur logis dan tidak ada lubang cerita (plot hole)? Bagaimana pacing — apakah ada bagian yang terlalu lambat atau terburu-buru?",
          "",
          "3. KARAKTER (PENOKOHAN) — apakah karakter terasa 'hidup' dan memiliki kedalaman psikologis? Apakah perkembangan karakter (character arc) meyakinkan?",
          "",
          "4. GAYA BAHASA — apakah bahasa yang digunakan indah, efektif, dan sesuai dengan tone cerita? Apakah penulis memiliki 'suara' yang khas?",
          "",
          "5. LATAR (SETTING) — apakah latar waktu dan tempat digambarkan dengan vivid dan mendukung atmosfer cerita?",
          "",
          "UNTUK BUKU NONFIKSI (self-help, sains, sejarah, biografi):",
          "",
          "1. TESIS DAN ARGUMEN — apakah argumen penulis logis dan didukung bukti? Apakah tesis jelas dari awal?",
          "2. KUALITAS RISET — apakah data dan fakta akurat dan terbaru? Apakah sumbernya kredibel?",
          "3. STRUKTUR DAN ORGANISASI — apakah buku terorganisir dengan baik? Apakah bab-bab saling terhubung?",
          "4. AKSESIBILITAS — apakah buku mudah dipahami oleh target pembacanya?",
          "5. ORISINALITAS — apakah buku menawarkan perspektif baru atau hanya mengulang yang sudah ada?",
          "",
          "[Ilustrasi: Timbangan keseimbangan dengan dua piringan. Piringan kiri bertuliskan unsur fiksi: tema, alur, karakter, bahasa, latar. Piringan kanan bertuliskan unsur nonfiksi: tesis, riset, struktur, aksesibilitas, orisinalitas. Di antara kedua piringan, buku terbuka dengan sinar. Gaya ilustrasi keseimbangan evaluatif dengan warna emas dan putih.]",
        ],
        contoh: [
          "CONTOH EVALUASI FIKSI — 'BUMI MANUSIA' KARYA PRAMOEDYA ANANTA TOER:",
          "",
          "TEMA: (9/10) Tema kolonialisme, identitas, dan perlawanan disajikan dengan kompleksitas moral yang jarang ditemukan dalam sastra Indonesia. Tidak ada tokoh yang sepenuhnya baik atau jahat — termasuk tokoh Belanda seperti Nyai Ontosoroh — memberikan nuansa abu-abu yang realistis.",
          "",
          "KARAKTER: (10/10) Minke sebagai narator orang pertama mengalami perkembangan yang luar biasa — dari pemuda naif yang mengagumi Eropa menjadi intelektual yang sadar akan ketidakadilan kolonial. Nyai Ontosoroh adalah salah satu karakter perempuan terkuat dalam sastra Indonesia.",
          "",
          "ALUR: (7/10) Alur maju dengan beberapa kilas balik efektif. Namun, bagian pertengahan novel (saat Minke di Betawi) terasa melambat dan beberapa sub-plot tidak terselesaikan dengan memuaskan.",
          "",
          "KELEMAHAN: Beberapa dialog terasa terlalu 'pintar' untuk tokoh kelas bawah tertentu, mengurangi realisme. Juga, penggunaan istilah Belanda yang berlebihan di beberapa bagian bisa membingungkan pembaca yang tidak fasih bahasa Belanda.",
          "",
          "✓ Evaluasi menggunakan data spesifik, skala jelas, dan menyebut kelebihan serta kekurangan secara seimbang.",
        ],
      },
      {
        judul: "Teknik Menulis Resensi yang Menarik",
        isi: [
          "Resensi yang baik tidak cukup hanya informatif dan evaluatif — ia juga harus menarik untuk dibaca. Di era digital, pembaca memiliki rentang perhatian yang pendek. Resensimu harus bisa memikat mereka sejak kalimat pertama.",
          "",
          "TEKNIK 1 — LEAD YANG KUAT",
          "Jangan mulai dengan 'Buku ini berjudul...'. Itu membosankan. Mulailah dengan kutipan mengejutkan, fakta unik, anekdot, atau pertanyaan yang menggelitik. Contoh lead kuat: 'Pernahkah kamu merasa bahwa semua nasihat self-help terdengar seperti kopian satu sama lain? 'Filosofi Teras' datang dengan klaim berani: kebahagiaan bukan tentang mendapatkan lebih, tapi tentang menginginkan lebih sedikit.'",
          "",
          "TEKNIK 2 — HINDARI SPOILER BERLEBIHAN",
          "Untuk resensi fiksi, jangan pernah mengungkapkan twist, kematian karakter, atau ending. Tujuan resensi adalah membuat orang ingin membaca, bukan menggantikan pengalaman membaca. Batasi sinopsis pada 30% pertama cerita.",
          "",
          "TEKNIK 3 — GUNAKAN KUTIPAN DARI BUKU",
          "Kutipan langsung dari buku memperkuat argumenmu. Jika kamu bilang 'gaya bahasa penulis indah', buktikan dengan menyertakan satu paragraf yang memperlihatkan keindahan itu. Kutipan juga memberi 'rasa' buku kepada pembaca.",
          "",
          "TEKNIK 4 — JANGAN TAKUT BERBEDA",
          "Resensi yang paling berkesan adalah yang punya sudut pandang unik. Setuju dengan mayoritas? Jelaskan dengan argumenmu sendiri. Tidak setuju dengan pujian umum? Itu lebih menarik — selama argumenmu logis dan berbukti.",
          "",
          "TEKNIK 5 — TULIS UNTUK PEMBACA, BUKAN UNTUK PENULIS",
          "Ingat: pembaca resensimu adalah calon pembaca buku, bukan penulisnya. Tanyakan pada diri sendiri: 'Informasi apa yang saya butuhkan untuk memutuskan apakah akan membaca buku ini?'",
          "",
          "[Ilustrasi: Blog resensi di layar tablet dengan highlight pada bagian lead, kutipan, dan kesimpulan. Ikon-ikon teknik berjejer di samping layar: kait (lead), mata tertutup (no spoiler), tanda kutip (kutipan), bintang (beda), dan target (pembaca). Gaya ilustrasi tampilan blog dengan warna putih dan aksen biru.]",
        ],
        contoh: [
          "CONTOH LEAD RESENSI YANG KUAT:",
          "",
          "LEAD LEMAH:",
          "'Buku Atomic Habits karya James Clear adalah buku self-help yang membahas kebiasaan. Buku ini terbit tahun 2018 dan bestseller internasional. Berikut ulasannya...'",
          "✗ Informatif tapi membosankan. Tidak ada yang membuat pembaca ingin lanjut.",
          "",
          "LEAD KUAT:",
          "'Pada 2003, James Clear mengalami cedera parah saat dipukul bisbol di wajah — matanya hampir buta, hidungnya patah, dan ia koma selama seminggu. Namun, dari pengalaman traumatis itulah lahir filosofi yang kini mengubah cara jutaan orang membentuk kebiasaan: jangan fokus pada goal, fokus pada sistem. Atomic Habits bukan sekadar buku self-help lain — ini adalah manual reprogramming otak untuk menjadi 1% lebih baik setiap hari.'",
          "✓ Lead menggunakan anekdot personal yang dramatis, fakta mengejutkan, dan tesis buku — membuat pembaca penasaran.",
          "",
          "TIPS: Jika kesulitan membuat lead, tulislah bagian lain dulu. Lead sering kali lebih mudah ditulis setelah kamu selesai menganalisis buku secara keseluruhan.",
        ],
      },
    ],
    rangkuman: [
      "[Ilustrasi: Sebuah blog resensi buku dengan tampilan modern. Di layar terlihat rating bintang, kutipan buku yang distabilo, dan bagian komentar pembaca. Tangan sedang mengetik resensi baru. Latar meja kayu dengan buku-buku yang sudah diresensi. Gaya ilustrasi blogger literer dengan warna putih dan aksen merah muda.]",
      "Resensi adalah ulasan kritis terhadap karya (buku, film, dll.) dengan fungsi informatif, evaluatif, promotif, dan kritis.",
      "Struktur resensi: Identitas buku → Pembukaan (lead) → Sinopsis → Analisis & Evaluasi → Perbandingan (opsional) → Kesimpulan & Rekomendasi.",
      "Unsur penilaian fiksi: tema, alur, karakter, gaya bahasa, latar. Nonfiksi: tesis, riset, struktur, aksesibilitas, orisinalitas.",
      "Teknik menulis: lead kuat, hindari spoiler, gunakan kutipan buku, berani punya sudut pandang, tulis untuk calon pembaca.",
      "Resensi yang baik tidak harus panjang — yang penting jujur, argumentatif, dan membantu pembaca memutuskan.",
    ],
  },
  latihan: makeSoal([
    ["Fungsi resensi yang memberikan penilaian kualitatif terhadap karya disebut...", ["Informatif", ["Evaluatif", "Promotif", "Kritis"], 1, "Fungsi evaluatif menilai kualitas karya dengan argumen dan bukti yang jelas."], 0, "Fungsi evaluatif menilai kualitas karya dengan argumen."],
    ["Bagian resensi yang berisi judul, penulis, penerbit, dan ISBN disebut...", ["Pembukaan", ["Identitas buku", "Sinopsis", "Analisis"], 1, "Identitas buku atau data bibliografi mencantumkan informasi teknis tentang buku."], 0, "Identitas buku mencantumkan data bibliografi."],
    ["Resensi yang baik harus menghindari spoiler berlebihan karena...", ["Spoiler tidak etis", "Tujuan resensi adalah membuat pembaca ingin membaca buku, bukan menggantikan pengalaman membaca", ["Spoiler dilarang penerbit", "Spoiler membuat resensi panjang"], 1, "Resensi bertujuan mendorong orang membaca, bukan menggantikan pengalaman membaca."], 0, "Tujuan resensi membuat orang ingin membaca buku, bukan menggantikannya."],
    ["Yang BUKAN termasuk unsur penilaian dalam resensi buku fiksi adalah...", ["Tema", ["Indeks buku", "Alur", "Penokohan"], 1, "Indeks buku adalah elemen teknis penerbitan, bukan unsur intrinsik yang dinilai dalam resensi fiksi."], 0, "Indeks buku bukan unsur penilaian resensi fiksi."],
    ["Teknik 'lead' dalam resensi berfungsi untuk...", ["Menutup resensi", ["Menarik perhatian pembaca sejak kalimat pertama", "Mencantumkan data buku", "Menyebutkan kekurangan"], 1, "Lead adalah paragraf pembuka yang bertujuan memikat pembaca untuk melanjutkan membaca."], 0, "Lead menarik perhatian pembaca sejak kalimat pertama."],
    ["Resensi yang berfokus pada penilaian kritis dengan argumen mendalam disebut...", ["Resensi informatif", ["Resensi evaluatif", "Resensi deskriptif", "Resensi akademik"], 1, "Resensi evaluatif berfokus pada penilaian kritis dengan argumen dan bukti yang mendalam."], 0, "Resensi evaluatif berfokus pada penilaian kritis mendalam."],
    ["Mengapa resensor perlu membandingkan buku yang diresensi dengan karya lain?", ["Agar terlihat pintar", ["Untuk membantu pembaca yang familiar dengan genre memposisikan buku", "Karena harus ada perbandingan", "Agar resensi lebih panjang"], 1, "Perbandingan membantu pembaca yang sudah familiar dengan genre tertentu memahami posisi buku."], 0, "Perbandingan membantu memposisikan buku bagi pembaca yang familiar dengan genre."],
    ["Aspek yang dinilai dalam resensi buku nonfiksi adalah...", ["Alur dan penokohan", ["Tesis, kualitas riset, struktur, aksesibilitas, orisinalitas", "Gaya bahasa dan latar", "Konflik dan klimaks"], 1, "Resensi nonfiksi menilai tesis, riset, struktur, aksesibilitas, dan orisinalitas."], 0, "Resensi nonfiksi menilai tesis, riset, struktur, aksesibilitas, orisinalitas."],
    ["Contoh lead yang kuat untuk resensi adalah...", ["Buku ini berjudul...", ["Pada 2003, James Clear mengalami cedera parah... dari pengalaman itulah lahir Atomic Habits", "Buku ini bagus", "Saya akan meresensi buku X"], 1, "Lead yang kuat menggunakan anekdot, fakta mengejutkan, atau pertanyaan yang menarik."], 0, "Lead kuat menggunakan anekdot atau fakta mengejutkan."],
    ["Fungsi kutipan langsung dari buku dalam resensi adalah...", ["Memenuhi halaman", ["Memperkuat argumen resensor dengan bukti tekstual", "Menggantikan sinopsis", "Agar terlihat profesional"], 1, "Kutipan langsung berfungsi sebagai bukti tekstual yang memperkuat argumen resensor."], 0, "Kutipan langsung memperkuat argumen dengan bukti tekstual."],
  ]),
  praktik: {
    petunjuk: "Pilihlah satu buku fiksi atau nonfiksi yang sudah kamu baca dalam 6 bulan terakhir. Tulislah resensi sepanjang 400-600 kata dengan ketentuan: (1) cantumkan identitas buku lengkap, (2) buat lead yang kuat, (3) sinopsis maksimal 2 paragraf tanpa spoiler, (4) analisis minimal 3 unsur (tema/karakter/alur/gaya bahasa untuk fiksi, atau tesis/riset/struktur untuk nonfiksi), (5) sebutkan kelebihan dan kekurangan secara seimbang, (6) beri rekomendasi untuk target pembaca tertentu. Publikasikan di Goodreads atau blog pribadi jika memungkinkan.",
    tips: [
      "Pilih buku yang benar-benar kamu kuasai — resensi akan lebih berbobot jika kamu paham konteks dan genre buku",
      "Baca resensi dari resensor profesional (seperti di Mojok.co atau Goodreads) untuk mempelajari gaya dan pendekatan mereka",
      "Catat halaman spesifik saat membaca untuk memudahkan pencarian kutipan yang ingin digunakan dalam resensi",
      "Jangan ragu mengkritik buku bestseller — popularitas tidak menjamin kualitas, dan kritik yang argumentatif lebih berharga daripada pujian buta",
      "Minta teman membaca resensimu dan tanya: 'Apakah setelah membaca ini kamu tertarik membaca bukunya?' — jika tidak, perbaiki lead dan argumenmu",
    ],
    contoh: "Lead alternatif untuk resensi 'Filosofi Teras': 'Bayangkan kamu sedang macet di jalan tol selama 2 jam. Mobil tidak bergerak. Udara panas. Akal sehatmu bilang: marah saja. Tapi filosof Stoa akan bilang: mengapa? Kamu tidak bisa mengubah kemacetan — jadi mengapa membiarkannya mengubah ketenanganmu? Inilah inti dari 'Filosofi Teras' yang ditulis Henry Manampiring: kebahagiaan bukan tentang mengendalikan dunia, tapi tentang mengendalikan responsmu terhadap dunia.' — Lead ini menggunakan skenario relatable, kontras antara respons umum dan filosofi Stoa, dan langsung menyampaikan tesis buku.",
  },
  kuis: makeSoal([
    ["Kata 'resensi' berasal dari bahasa Latin 'recensere' yang berarti...", ["Membaca", "Memeriksa kembali atau menimbang", ["Menulis", "Mengulas"], 1, "Recensere berarti 'memeriksa kembali' atau 'menimbang' — sesuai dengan fungsi resensi untuk memeriksa dan menilai karya."], 0, "Recensere berarti memeriksa kembali atau menimbang."],
    ["Bagian 'jantung' resensi tempat resensor menganalisis kekuatan dan kelemahan buku adalah...", ["Pembukaan", ["Analisis dan evaluasi", "Sinopsis", "Kesimpulan"], 1, "Analisis dan evaluasi adalah inti resensi tempat resensor membahas kualitas buku secara mendalam."], 0, "Analisis dan evaluasi adalah inti resensi."],
    ["Resensi informatif berbeda dari resensi evaluatif dalam hal...", ["Resensi informatif lebih panjang", ["Resensi informatif fokus deskripsi, resensi evaluatif fokus penilaian kritis", "Resensi informatif tidak penting", "Resensi evaluatif tidak boleh memuji"], 1, "Resensi informatif mendeskripsikan isi, resensi evaluatif menilai kualitas secara kritis."], 0, "Informatif deskripsi, evaluatif penilaian kritis."],
    ["Yang harus dihindari saat menulis sinopsis dalam resensi fiksi adalah...", ["Menjelaskan tema", ["Mengungkapkan twist atau akhir cerita", "Menyebutkan genre", "Menyebutkan nama penulis"], 1, "Spoiler twist atau akhir cerita merusak pengalaman membaca dan harus dihindari."], 0, "Mengungkapkan twist atau akhir cerita harus dihindari."],
    ["Dalam resensi buku nonfiksi, 'kualitas riset' mengacu pada...", ["Jumlah halaman", ["Akurasi, kebaruan, dan kredibilitas data dan sumber yang digunakan penulis", "Jumlah bab", "Panjang daftar pustaka"], 1, "Kualitas riset menilai keakuratan, kebaruan, dan kredibilitas sumber yang digunakan penulis."], 0, "Kualitas riset menilai akurasi dan kredibilitas sumber."],
    ["Fungsi 'promotif' dari resensi berarti...", ["Resensi menjual buku", ["Resensi yang baik dapat meningkatkan minat baca dan pembelian buku", "Resensi mempromosikan penulis", "Resensi harus berisi pujian"], 1, "Fungsi promotif berarti resensi dapat mendorong minat dan keputusan pembaca untuk membeli/membaca buku."], 0, "Fungsi promotif meningkatkan minat baca dan pembelian buku."],
    ["Cara terbaik membuat lead yang kuat menurut materi adalah...", ["Menyebutkan judul buku di kalimat pertama", ["Menggunakan anekdot, fakta mengejutkan, atau pertanyaan retoris", "Menyebutkan harga buku", "Mengucapkan terima kasih"], 1, "Lead kuat menggunakan anekdot, fakta mengejutkan, atau pertanyaan retoris yang menarik."], 0, "Lead kuat menggunakan anekdot, fakta, atau pertanyaan retoris."],
    ["Yang BUKAN termasuk unsur intrinsik buku fiksi adalah...", ["Tema", ["Kualitas riset", "Alur", "Gaya bahasa"], 1, "Kualitas riset adalah unsur penilaian nonfiksi, bukan intrinsik fiksi."], 0, "Kualitas riset adalah unsur nonfiksi."],
    ["Rekomendasi dalam resensi sebaiknya menyebutkan...", ["Harga buku", ["Target pembaca yang cocok untuk buku tersebut", "Toko tempat membeli", "Tanggal baca"], 1, "Rekomendasi yang baik menyebutkan siapa target pembaca yang paling cocok dengan buku."], 0, "Rekomendasi menyebutkan target pembaca yang cocok."],
    ["Tujuan utama menulis resensi adalah...", ["Mendapatkan buku gratis", ["Membantu calon pembaca memutuskan apakah buku layak dibaca", "Mengkritik penulis", "Menjadi terkenal"], 1, "Tujuan utama resensi adalah membantu calon pembaca membuat keputusan melalui informasi dan analisis."], 0, "Tujuan utama resensi membantu calon pembaca memutuskan."],
  ]),
}
export default konten
