import type { Konten } from "../types"
import { makeSoal } from "../types"

const konten: Konten = {
  belajar: {
    tujuan: [
      "Memahami pengertian, ciri, dan jenis teks prosedur kompleks dalam konteks kehidupan modern",
      "Menganalisis struktur teks prosedur: tujuan, alat/bahan, langkah, dan penutup",
      "Mengidentifikasi kaidah kebahasaan teks prosedur: kalimat imperatif, konjungsi temporal, verba material",
      "Menyusun teks prosedur kompleks yang logis, terperinci, dan mudah diikuti",
      "Mengevaluasi efektivitas teks prosedur berdasarkan kejelasan, urutan, dan hasil akhir",
    ],
    materi: [
      {
        judul: "Apa Itu Teks Prosedur Kompleks?",
        isi: [
          "Teks prosedur adalah teks yang memberikan petunjuk atau panduan untuk melakukan sesuatu secara sistematis. 'Kompleks' berarti prosedur tersebut melibatkan banyak langkah, alat, dan/atau keputusan — tidak sesederhana 'cara merebus mi instan'.",
          "",
          "Ciri-ciri teks prosedur kompleks:",
          "",
          "1. BERTUJUAN MEMANDU — teks ditulis untuk membantu pembaca mencapai hasil tertentu. Tujuan harus jelas dan spesifik sejak awal.",
          "",
          "2. LANGKAH SISTEMATIS — langkah-langkah disusun secara kronologis dan tidak boleh dibolak-balik. Setiap langkah harus jelas apa yang harus dilakukan dan mengapa.",
          "",
          "3. BAHASA INSTRUKSIONAL — menggunakan kalimat perintah (imperatif), kata kerja aktif, dan istilah teknis yang konsisten.",
          "",
          "4. LENGKAP DAN TEPAT — prosedur kompleks harus mencakup semua informasi yang diperlukan: alat, bahan, waktu, suhu, takaran, dan kondisi khusus.",
          "",
          "5. MENCAKUP KONDISI DAN KEPUTUSAN — prosedur kompleks sering memiliki cabang: 'Jika X terjadi, lakukan A. Jika Y terjadi, lakukan B.'",
          "",
          "Contoh teks prosedur sederhana vs kompleks: 'Cara mengoperasikan remote AC' (sederhana, 3 langkah) vs 'Cara merakit PC gaming' (kompleks, 30+ langkah dengan pilihan komponen).",
          "",
          "[Ilustrasi: Meja kerja dengan berbagai alat dan bahan: obeng, solder, komponen elektronik, kabel, dan buku manual. Tangan sedang mengikuti langkah di buku manual yang terbuka. Di latar belakang, rak dengan berbagai kotak komponen. Gaya ilustrasi bengkel/workshop dengan warna abu-abu dan oranye.]",
        ],
        contoh: [
          "PERBANDINGAN PROSEDUR SEDERHANA vs KOMPLEKS:",
          "",
          "SEDERHANA — 'Cara Mengisi Ulang Pulsa':",
          "1. Buka aplikasi dompet digital.",
          "2. Pilih menu 'Pulsa'.",
          "3. Masukkan nomor telepon.",
          "4. Pilih nominal. Konfirmasi.",
          "",
          "KOMPLEKS — 'Cara Membuat Lamaran Kerja yang Profesional':",
          "1. RISET PERUSAHAAN — pelajari visi-misi, produk, dan budaya perusahaan dari website dan LinkedIn.",
          "2. PERSIAPKAN DOKUMEN — (a) CV disesuaikan dengan posisi (maks 2 halaman, PDF), (b) Surat lamaran dikustomisasi, (c) Portofolio jika relevan.",
          "   CATATAN: Jika perusahaan meminta format tertentu (misal: PDF maks 5MB), patuhi. Jangan kirim .docx kecuali diminta.",
          "3. KIRIM LAMARAN — pilih portal yang benar: JobStreet, LinkedIn, atau email langsung. Jika email, subjek: 'Lamaran Posisi X — Nama Lengkap'.",
          "   PENTING: Jangan kirim lamaran ke 100 perusahaan dengan template sama. HRD bisa mendeteksi spam.",
          "4. FOLLOW-UP — jika tidak ada balasan dalam 7 hari, kirim email follow-up sopan.",
          "",
          "✓ Prosedur kompleks memiliki cabang, catatan, peringatan, dan keputusan yang harus diambil.",
        ],
        catatan: "Di dunia profesional, teks prosedur dikenal dengan berbagai nama: SOP (Standard Operating Procedure), user manual, panduan teknis, atau workflow. Kemampuan menulis prosedur yang jelas adalah soft skill yang sangat dihargai di dunia kerja — karena prosedur yang buruk bisa menyebabkan kerugian waktu, uang, dan bahkan kecelakaan.",
      },
      {
        judul: "Struktur Teks Prosedur",
        isi: [
          "Seperti jenis teks lainnya, teks prosedur memiliki struktur baku yang membuatnya mudah diikuti. Struktur yang baik adalah yang membuat pembaca tidak perlu bertanya 'Langkah selanjutnya apa?'",
          "",
          "STRUKTUR BAKU TEKS PROSEDUR:",
          "",
          "1. JUDUL — harus spesifik dan informatif. Bukan 'Cara Membuat Kue' tapi 'Cara Membuat Kue Brownies Kukus Sederhana (Tanpa Oven)'. Judul yang baik memberi gambaran lengkap tentang apa yang akan dicapai.",
          "",
          "2. TUJUAN — penjelasan singkat tentang hasil akhir yang akan dicapai dan mengapa prosedur ini perlu dilakukan. Bisa juga berisi estimasi waktu, tingkat kesulitan, dan prasyarat.",
          "",
          "3. ALAT DAN BAHAN — daftar lengkap semua yang dibutuhkan. Untuk prosedur kompleks, sertakan spesifikasi: 'Kabel LAN kategori 6 (minimal 5 meter)', 'Processor AMD Ryzen 5 5600X atau Intel i5-12400F'.",
          "",
          "4. LANGKAH-LANGKAH — bagian terpenting. Setiap langkah harus: (a) satu instruksi per langkah, (b) menggunakan nomor urut, (c) bahasa imperatif jelas, (d) disertai alasan jika perlu ('agar...').",
          "",
          "5. PENUTUP (OPSIONAL) — berisi penegasan hasil akhir, tips tambahan, atau troubleshooting untuk masalah yang mungkin muncul.",
          "",
          "Tips: Gunakan format bertingkat (1, 1.1, 1.2) untuk prosedur yang memiliki sub-langkah. Ini memudahkan pembaca melacak posisi mereka dalam proses.",
          "",
          "[Ilustrasi: Buku manual terbuka menampilkan diagram perakitan. Halaman kiri: daftar alat dan bahan dengan ilustrasi ikon. Halaman kanan: langkah bernomor dengan diagram alur. Tangan menunjuk ke langkah 3. Gaya ilustrasi manual teknis dengan warna biru dan putih.]",
        ],
        contoh: [
          "CONTOH STRUKTUR LENGKAP — 'CARA MEMBUAT WEBSITE PORTOFOLIO SEDERHANA':",
          "",
          "TUJUAN: Membuat website portofolio satu halaman (single page) yang dapat diakses online dalam 30 menit. Prasyarat: akun GitHub (gratis).",
          "",
          "ALAT DAN BAHAN:",
          "• Laptop/PC dengan koneksi internet",
          "• Akun GitHub (daftar di github.com jika belum punya)",
          "• Browser web (Chrome/Firefox/Edge)",
          "• Teks editor (Notepad/VS Code — opsional)",
          "",
          "LANGKAH-LANGKAH:",
          "1. BUKA github.com dan login ke akun Anda.",
          "2. KLIK tombol '+' di pojok kanan atas, pilih 'New repository'.",
          "3. ISI Repository name dengan '[username].github.io' (ganti [username] dengan username GitHub Anda).",
          "   PENTING: Nama repository harus PERSIS ini agar GitHub Pages aktif secara otomatis.",
          "4. PILIH 'Public', lalu klik 'Create repository'.",
          "",
          "5. UPLOAD FILE:",
          "   5.1. Klik 'Add file' → 'Upload files'.",
          "   5.2. Siapkan file index.html (bisa gunakan template dari w3schools).",
          "   5.3. Drag-and-drop file ke halaman upload.",
          "   5.4. Scroll ke bawah, klik 'Commit changes'.",
          "",
          "6. BUKA Settings → Pages. Jika langkah 3 benar, akan terlihat: 'Your site is published at https://[username].github.io'.",
          "7. TUNGGU 1-2 menit, buka URL tersebut. Website portofolio Anda sudah live!",
          "",
          "TROUBLESHOOTING: Jika website tidak muncul: (1) Periksa nama repository, (2) Pastikan ada file index.html di root, (3) Tunggu 5 menit, refresh.",
        ],
      },
      {
        judul: "Kaidah Kebahasaan Teks Prosedur",
        isi: [
          "Teks prosedur memiliki kaidah kebahasaan yang khas dan relatif baku. Pemahaman terhadap kaidah ini akan membuat prosedur yang kamu tulis efektif dan profesional.",
          "",
          "1. KALIMAT IMPERATIF (PERINTAH)",
          "  Dominan menggunakan kata kerja perintah: 'Buka', 'Klik', 'Siapkan', 'Pastikan', 'Ulangi'. Hindari kalimat pasif atau pertanyaan. Langkah harus langsung dan jelas.",
          "",
          "  Contoh benar: 'Potong bawang menjadi dadu kecil.'",
          "  Contoh salah: 'Bawang sebaiknya dipotong menjadi dadu kecil.' (pasif, kurang tegas)",
          "",
          "2. KONJUNGSI TEMPORAL (KATA HUBUNG WAKTU)",
          "  Gunakan kata hubung yang menunjukkan urutan: 'setelah itu', 'kemudian', 'selanjutnya', 'lalu', 'sebelum', 'sementara'. Hindari 'dan' yang ambigu — apakah bersamaan atau berurutan?",
          "",
          "3. VERBA MATERIAL (KATA KERJA FISIK)",
          "  Gunakan kata kerja yang menunjukkan tindakan fisik: 'potong', 'campur', 'tekan', 'tarik', 'sambungkan', 'atur'. Hindari verba mental seperti 'pikirkan', 'bayangkan' — prosedur harus konkret.",
          "",
          "4. ISTILAH TEKNIS YANG KONSISTEN",
          "  Jika prosedur menggunakan istilah khusus, gunakan secara konsisten. Jangan berganti-ganti istilah untuk hal yang sama. Jika perlu, sertakan glosarium.",
          "",
          "5. KALIMAT EFEKTIF DAN SINGKAT",
          "  Setiap langkah idealnya 1-2 kalimat. Langkah yang terlalu panjang membingungkan. Jika langkah kompleks, pecah menjadi sub-langkah.",
          "",
          "[Ilustrasi: Papan tulis dengan contoh kalimat imperatif yang dicoret-coret: kalimat pasif dicoret merah, kalimat aktif diperbaiki dengan spidol hijau. Ikon-ikon kata kerja: gunting (potong), api (panaskan), tangan (tekan). Gaya ilustrasi papan tulis kelas dengan warna putih dan aksen merah-hijau.]",
        ],
        contoh: [
          "BANDINGKAN PENULISAN LANGKAH YANG EFEKTIF vs TIDAK EFEKTIF:",
          "",
          "TIDAK EFEKTIF (bertele-tele, pasif, ambigu):",
          "'Setelah itu, Anda bisa mulai memotong-motong bawang yang sudah disiapkan tadi. Disarankan untuk memotongnya dengan ukuran yang tidak terlalu besar dan tidak terlalu kecil, kira-kira sedang saja, agar nantinya ketika ditumis, bawangnya matang dengan merata.'",
          "",
          "EFEKTIF (imperatif, singkat, jelas):",
          "'Potong bawang menjadi dadu berukuran 1 cm agar matang merata saat ditumis.'",
          "",
          "TIDAK EFEKTIF (langkah tidak terurai):",
          "'Siapkan semua bahan dan alat lalu campurkan tepung dengan telur dan aduk hingga rata jangan lupa tambahkan gula dan vanili setelah itu masukkan ke loyang dan panggang selama 30 menit.'",
          "",
          "EFEKTIF (langkah terurai):",
          "1. Siapkan semua bahan dan alat.",
          "2. Campurkan tepung, telur, gula, dan vanili dalam mangkuk. Aduk hingga rata.",
          "3. Tuang adonan ke dalam loyang yang sudah diolesi mentega.",
          "4. Panggang dalam oven bersuhu 180 derajat Celsius selama 30 menit.",
        ],
      },
      {
        judul: "Prosedur Digital: Menulis Panduan untuk Era Modern",
        isi: [
          "Di era digital, teks prosedur tidak hanya ditemukan di buku manual cetak, tetapi juga di berbagai platform digital: artikel blog, video tutorial, infografis, dan dokumentasi perangkat lunak. Format digital menuntut pendekatan yang berbeda.",
          "",
          "PROSEDUR VISUAL vs TEKSTUAL:",
          "Prosedur modern sering mengombinasikan teks dan visual. Tangkapan layar (screenshot), diagram alur, dan ikon membantu pembaca memahami langkah lebih cepat. Prinsipnya: visual untuk 'di mana', teks untuk 'apa dan bagaimana'.",
          "",
          "TIPS MENULIS PROSEDUR DIGITAL:",
          "1. Gunakan HEADING dan sub-heading — pembaca digital tidak membaca linear, mereka memindai (scanning). Heading membantu mereka menemukan langkah yang relevan.",
          "",
          "2. BULLET POINT dan NUMBERING — nomor untuk urutan wajib, bullet untuk daftar alat/bahan atau opsi.",
          "",
          "3. SCREENSHOT — setiap langkah yang melibatkan antarmuka digital sebaiknya disertai screenshot. Tandai area yang harus diklik dengan panah atau lingkaran merah.",
          "",
          "4. PERINGATAN dan TIPS — gunakan kotak berwarna: merah untuk 'Peringatan' (jangan lakukan ini), kuning untuk 'Catatan' (informasi penting), hijau untuk 'Tips' (saran tambahan).",
          "",
          "5. TESTING — sebelum mempublikasikan prosedur, minta seseorang yang awam mengikutinya. Jika ia tersesat, prosedurnya perlu diperbaiki. Ini disebut 'usability testing'.",
          "",
          "[Ilustrasi: Layar laptop menampilkan halaman dokumentasi digital dengan panel kiri daftar isi, panel kanan konten dengan screenshot dan kotak peringatan. Tangan memegang mouse. Di samping laptop, buku catatan dengan sketsa diagram alur. Gaya ilustrasi workspace digital dengan warna putih dan biru.]",
        ],
        contoh: [
          "CONTOH PROSEDUR DIGITAL YANG BAIK — 'CARA MENGGANTI PASSWORD AKUN':",
          "",
          "[HEADING] Langkah 1: Buka Halaman Pengaturan",
          "",
          "1. Klik ikon profil di pojok kanan atas layar.",
          "2. Pilih 'Settings' dari menu dropdown.",
          "   [SCREENSHOT: menu dropdown dengan 'Settings' dilingkari merah]",
          "",
          "[HEADING] Langkah 2: Buka Menu Keamanan",
          "",
          "1. Di panel kiri, klik 'Security' (ikon gembok).",
          "",
          "[HEADING] Langkah 3: Ganti Password",
          "",
          "1. Klik tombol 'Change Password'.",
          "2. Masukkan password lama Anda.",
          "   PERINGATAN: Password lama salah 3 kali akan mengunci akun selama 30 menit.",
          "3. Masukkan password baru (min. 8 karakter, kombinasi huruf dan angka).",
          "4. Konfirmasi password baru. Klik 'Save'.",
          "",
          "[HEADING] Langkah 4: Verifikasi",
          "",
          "1. Cek email Anda untuk tautan verifikasi.",
          "2. Klik tautan tersebut dalam 24 jam. Jika tidak, perubahan tidak akan berlaku.",
          "   TIPS: Jika tidak menerima email, cek folder Spam atau minta kirim ulang.",
          "",
          "✓ Prosedur digital yang baik memandu pembaca langkah demi langkah dengan visual dan peringatan yang jelas.",
        ],
      },
    ],
    rangkuman: [
      "[Ilustrasi: Sebuah pabrik/workshop dengan SOP terpajang di dinding. Pekerja mengikuti langkah-langkah dengan alat pelindung. Diagram alir proses produksi di papan putih. Gaya ilustrasi industri modern dengan warna biru, kuning, dan abu-abu.]",
      "Teks prosedur kompleks adalah panduan sistematis dengan banyak langkah, alat, dan keputusan bercabang.",
      "Struktur: Judul spesifik → Tujuan → Alat & Bahan → Langkah (bertingkat jika perlu) → Penutup/Troubleshooting.",
      "Kaidah kebahasaan: kalimat imperatif, konjungsi temporal, verba material, istilah teknis konsisten, kalimat efektif.",
      "Prosedur digital: gunakan heading, numbering, screenshot, kotak peringatan/tips, dan uji coba pada pemula.",
      "Kemampuan menulis prosedur yang jelas adalah soft skill berharga di dunia kerja — prosedur buruk merugikan waktu dan biaya.",
    ],
  },
  latihan: makeSoal([
    ["Yang membedakan teks prosedur kompleks dari teks prosedur sederhana adalah...", ["Prosedur kompleks lebih panjang", "Prosedur kompleks melibatkan banyak langkah, alat, dan keputusan bercabang", "Prosedur kompleks menggunakan bahasa Inggris", "Prosedur kompleks tidak memiliki tujuan"], 1, "Prosedur kompleks memiliki langkah lebih banyak, alat/bahan lebih variatif, dan sering bercabang."],
    ["Kaidah kebahasaan yang DOMINAN dalam teks prosedur adalah...", ["Kalimat deklaratif", "Kalimat imperatif", "Kalimat interogatif", "Kalimat eksklamatif"], 1, "Kalimat imperatif (perintah) adalah ciri khas teks prosedur: Buka, Klik, Siapkan, Potong."],
    ["Fungsi 'Alat dan Bahan' dalam struktur teks prosedur adalah...", ["Menambah panjang teks", "Memberi daftar lengkap semua yang dibutuhkan sebelum memulai", "Pengganti langkah", "Hiasan"], 1, "Alat dan bahan memberi daftar kebutuhan sebelum memulai."],
    ["Kata hubung yang menunjukkan urutan waktu dalam prosedur disebut...", ["Konjungsi kausal", "Konjungsi temporal", "Konjungsi koordinatif", "Konjungsi korelatif"], 1, "Konjungsi temporal menunjukkan urutan waktu."],
    ["Mengapa setiap langkah dalam prosedur sebaiknya hanya berisi 1-2 kalimat?", ["Agar cepat selesai", "Agar tidak membingungkan pembaca — langkah panjang sulit diikuti", "Karena aturan", "Agar lebih mudah ditulis"], 1, "Langkah pendek tidak membingungkan pembaca."],
    ["Contoh verba material yang tepat dalam teks prosedur adalah...", ["Memikirkan", "Memotong", "Membayangkan", "Percaya"], 1, "Verba material adalah kata kerja fisik seperti memotong."],
    ["Yang BUKAN elemen dalam struktur teks prosedur adalah...", ["Judul", "Abstrak", "Langkah-langkah", "Tujuan"], 1, "Abstrak bukan elemen teks prosedur."],
    ["Fungsi kotak 'Peringatan' dalam prosedur digital adalah...", ["Menambah warna", "Memberi informasi tentang bahaya atau kesalahan yang harus dihindari", "Menggantikan langkah", "Hiasan"], 1, "Kotak peringatan memberi informasi tentang risiko yang harus dihindari."],
    ["Sebelum mempublikasikan prosedur, sebaiknya dilakukan...", ["Testing pada orang awam untuk melihat apakah prosedur mudah diikuti", "Menjualnya", "Mencetak banyak", "Menerjemahkan"], 0, "Usability testing memastikan prosedur mudah diikuti."],
    ["Judul prosedur yang baik harus...", ["Pendek", "Spesifik dan informatif tentang apa yang akan dicapai", "Berima", "Mengandung humor"], 1, "Judul harus spesifik dan informatif."],
  ]),
  praktik: {
    petunjuk: "Pilihlah satu keterampilan yang kamu kuasai dan bisa diajarkan kepada orang lain (misal: cara membuat akun LinkedIn, cara mengedit video dengan CapCut, cara merawat sepeda, atau cara membuat infografis di Canva). Tulislah teks prosedur kompleks dengan ketentuan: (1) judul spesifik, (2) tujuan dan prasyarat, (3) alat dan bahan lengkap dengan spesifikasi, (4) langkah-langkah dengan sub-langkah (minimal 10 langkah total), (5) mengandung minimal 2 peringatan/catatan/tips, (6) menggunakan kalimat imperatif dan konjungsi temporal, (7) sertakan screenshot atau diagram jika relevan.",
    tips: [
      "Bayangkan kamu menulis untuk adik kelas yang belum pernah melakukan ini sama sekali — jangan lewatkan 'langkah yang jelas' seperti 'buka aplikasi'",
      "Minta teman mengikuti prosedur yang kamu tulis tanpa bertanya — jika ia tersesat, perbaiki bagian yang ambigu",
      "Gunakan kata kerja imperatif yang konsisten — jangan campur 'klik' dengan 'tekan' untuk aksi yang sama",
      "Tambahkan estimasi waktu di setiap langkah agar pembaca bisa merencanakan: '(5 menit)'",
      "Sertakan 'kriteria keberhasilan' di akhir: 'Jika berhasil, kamu akan melihat halaman dashboard seperti pada gambar ini'",
    ],
    contoh: "Prosedur 'Cara Membuat Website Portofolio Gratis dengan GitHub Pages' (contoh di atas) bisa dikembangkan dengan sub-langkah untuk mendesain halaman menggunakan HTML/CSS, menambahkan gambar, dan menghubungkan domain kustom. Pastikan untuk menyertakan troubleshooting untuk error umum seperti '404 page not found'.",
  },
  kuis: makeSoal([
    ["Teks prosedur kompleks bertujuan untuk...", ["Menghibur pembaca", "Memandu pembaca melakukan sesuatu secara sistematis", "Mendeskripsikan objek", "Meyakinkan pembaca"], 1, "Teks prosedur memandu pembaca secara sistematis."],
    ["Ciri teks prosedur yang membedakannya dari teks eksplanasi adalah...", ["Teks prosedur menggunakan data statistik", "Teks prosedur berisi langkah-langkah untuk melakukan sesuatu, bukan menjelaskan fenomena", "Teks prosedur lebih panjang", "Teks prosedur menggunakan bahasa ilmiah"], 1, "Prosedur memberi panduan, eksplanasi menjelaskan fenomena."],
    ["Kata 'klik', 'tekan', 'pilih' dalam teks prosedur termasuk jenis...", ["Verba mental", "Verba material", "Verba relasional", "Nomina"], 1, "Klik, tekan, pilih adalah verba material."],
    ["Fungsi 'Tujuan' dalam teks prosedur adalah...", ["Menjelaskan hasil akhir, estimasi waktu, dan prasyarat", "Menulis ulang judul", "Menambah panjang teks", "Menggantikan langkah"], 0, "Tujuan menjelaskan hasil akhir dan prasyarat."],
    ["Yang BUKAN kaidah kebahasaan teks prosedur adalah...", ["Kalimat imperatif", "Konjungsi temporal", "Kalimat pasif dominan", "Verba material"], 2, "Kalimat pasif bukan kaidah teks prosedur."],
    ["Usability testing dalam konteks penulisan prosedur berarti...", ["Menguji kecepatan menulis", "Menguji apakah prosedur dapat diikuti oleh orang awam", "Menguji perangkat keras", "Menguji kualitas kertas"], 1, "Usability testing menguji kemudahan prosedur diikuti."],
    ["Format penulisan langkah yang tepat untuk prosedur dengan sub-langkah adalah...", ["1. Langkah A. 2. Langkah B.", "1. Langkah utama\n  1.1 Sub-langkah\n  1.2 Sub-langkah\n2. Langkah utama berikutnya", "Langkah 1, Langkah 2", "a, b, c"], 1, "Format bertingkat memudahkan pelacakan posisi dalam proses."],
    ["Mengapa teks prosedur digital sebaiknya menyertakan screenshot?", ["Agar terlihat profesional", "Screenshot membantu pembaca mengetahui 'di mana' harus melakukan suatu aksi", "Agar loading lebih lambat", "Karena aturan"], 1, "Screenshot membantu pembaca mengetahui 'di mana' melakukan aksi."],
    ["Kriteria keberhasilan dalam teks prosedur berfungsi untuk...", ["Menambah panjang", "Memberi indikator kepada pembaca bahwa langkah telah berhasil dilakukan", "Menggantikan tujuan", "Hiasan"], 1, "Kriteria keberhasilan memberi indikator verifikasi."],
    ["Contoh penulisan judul prosedur yang baik adalah...", ["Memasak", "Cara Membuat Nasi Goreng Sederhana (15 Menit)", "Makanan", "Resep"], 1, "Judul spesifik dengan informasi hasil dan waktu lebih informatif."],
  ]),
}
export default konten
