import type { Konten, Soal } from "../types";

const kd = "3.3/4.3";

function buatSoal(count: number, opsi: number, tema: string): Soal[] {
  return Array.from({ length: count }, (_, i) => ({
    id: i + 1,
    soal: `Contoh soal ${tema} nomor ${i + 1}?`,
    opsi: ["Pilihan A", "Pilihan B", "Pilihan C", "Pilihan D"],
    jawaban: 0,
    penjelasan: `Penjelasan untuk soal ${tema} nomor ${i + 1}`,
  }));
}

/* =============================================
   Unit 2: Teks Drama — VIII S1
   KD 3.3/4.3 — Mengidentifikasi unsur, struktur, dan kebahasaan teks drama
   serta menyajikannya secara lisan dan tulis
   ============================================= */
const konten: Konten = {
    belajar: {
      tujuan: [
        "Memahami hakikat, ciri-ciri, dan jenis-jenis teks drama",
        "Mengidentifikasi unsur intrinsik drama meliputi tema, tokoh, alur, latar, dialog, dan amanat",
        "Menganalisis struktur teks drama yang terdiri dari prolog, dialog, dan epilog",
        "Menerapkan kaidah kebahasaan drama dalam penulisan naskah",
        "Memproduksi naskah drama sederhana dengan unsur dan struktur yang lengkap",
      ],
      materi: [
        {
          judul: "1. Hakikat Teks Drama",
          catatan: "Drama adalah karya sastra yang menggambarkan kehidupan manusia melalui dialog dan gerak panggung.",
          isi: [
            "Teks drama adalah karya sastra yang ditulis dalam bentuk dialog dan dirancang untuk dipentaskan di atas panggung. Drama menggambarkan kehidupan manusia melalui konflik, emosi, dan tindakan para tokohnya.",
            "",
            "Ciri-ciri teks drama:",
            "• Berbentuk dialog — seluruh cerita disampaikan melalui percakapan antartokoh",
            "• Dilengkapi petunjuk panggung (stage direction / kramagong) yang ditulis dalam tanda kurung",
            "• Memiliki konflik sebagai inti cerita yang menggerakkan alur",
            "• Dipentaskan oleh aktor di atas panggung di hadapan penonton",
            "• Menggunakan bahasa lisan yang komunikatif dan ekspresif",
            "• Terdiri atas babak, adegan, dan dialog",
            "",
            "Fungsi drama dalam kehidupan:",
            "✓ Sebagai media hiburan (tontonan yang menghibur)",
            "✓ Sebagai media pendidikan (menyampaikan pesan moral dan nilai-nilai kehidupan)",
            "✓ Sebagai media kritik sosial (menggambarkan masalah dalam masyarakat)",
            "✓ Sebagai media pelestarian budaya (mengangkat tradisi dan kearifan lokal)",
            "",
            "PENTING: Drama berbeda dengan prosa dan puisi. Drama ditulis untuk dipentaskan, bukan hanya dibaca. Oleh karena itu, penulisan drama harus mempertimbangkan aspek visual dan auditif — bagaimana kata-kata akan diucapkan dan bagaimana gerakan akan dilakukan di atas panggung.",
          ],
          contoh: [
            "Contoh cuplikan teks drama terkenal dari Indonesia:",
            "",
            "Cuplikan drama 'Bunga Rumah Makan' karya Utuy Tatang Sontani:",
            "",
            "(Panggung menggambarkan sebuah rumah makan sederhana. Piring-piring kotor menumpuk di meja. SITI sibuk melayani pelanggan.)",
            "SITI: (tersenyum ramah) Selamat datang, Pak. Silakan duduk. Ada yang bisa saya bantu?",
            "PELANGGAN: Saya pesan nasi goreng dan es teh, Mbak.",
            "SITI: Baik, Pak. Tunggu sebentar ya.",
            "(Siti bergegas ke dapur. Wajahnya lelah tetapi tetap ceria.)",
            "SITI: (bergumam pada diri sendiri) Semoga hari ini lebih ramai dari kemarin...",
            "",
            "Cuplikan ini menunjukkan ciri khas drama: dialog antartokoh, petunjuk panggung dalam kurung, dan gambaran latar tempat.",
          ],
        },
        {
          judul: "2. Unsur Intrinsik Drama",
          isi: [
            "Unsur intrinsik adalah unsur-unsur yang membangun teks drama dari dalam. Memahami unsur intrinsik membantu kita menganalisis dan mengapresiasi drama secara lebih mendalam.",
            "",
            "1. Tema",
            "• Gagasan pokok yang mendasari seluruh cerita drama",
            "• Tema bisa berupa: cinta, persahabatan, perjuangan, pengorbanan, kesenjangan sosial, pendidikan",
            "• Tema harus dirumuskan dalam satu kata atau frasa, misalnya: 'Ketidakadilan Sosial'",
            "",
            "2. Tokoh dan Penokohan",
            "• Tokoh: pelaku yang terlibat dalam cerita drama",
            "• Tokoh dibedakan menjadi:",
            "  — Protagonis: tokoh utama yang memiliki sifat baik (pahlawan)",
            "  — Antagonis: tokoh lawan yang menentang protagonis (penjahat)",
            "  — Tritagonis: tokoh penengah antara protagonis dan antagonis",
            "  — Figuran: tokoh pembantu yang melengkapi cerita",
            "• Penokohan: cara pengarang menggambarkan watak tokoh melalui dialog, perilaku, dan petunjuk panggung",
            "",
            "3. Alur (Plot)",
            "• Rangkaian peristiwa yang membentuk cerita drama",
            "• Tahapan alur drama: pengenalan → konflik muncul → konflik memuncak (klimaks) → antiklimaks → penyelesaian",
            "• Alur dalam drama biasanya disusun dalam babak dan adegan",
            "",
            "4. Latar (Setting)",
            "• Tempat, waktu, dan suasana terjadinya peristiwa dalam drama",
            "• Latar tempat: ruang kelas, halaman rumah, pasar, istana, dll.",
            "• Latar waktu: pagi, siang, malam, musim kemarau, tahun 1990-an, dll.",
            "• Latar suasana: tegang, haru, gembira, mencekam, romantis",
            "",
            "5. Dialog",
            "• Percakapan antartokoh yang menjadi inti dari teks drama",
            "• Dialog harus mencerminkan karakter tokoh yang mengucapkannya",
            "• Dialog ditulis dalam bentuk kalimat langsung tanpa tanda petik",
            "",
            "6. Amanat",
            "• Pesan moral atau pelajaran yang ingin disampaikan penulis drama kepada penonton",
            "• Amanat disampaikan secara tersirat melalui jalan cerita, bukan secara langsung",
            "",
            "Tips Menganalisis: Saat menonton drama, catat unsur intrinsik yang kamu temukan. Diskusikan dengan teman bagaimana unsur-unsur tersebut saling terkait membangun cerita yang utuh.",
          ],
          contoh: [
            "Analisis unsur intrinsik drama singkat:",
            "",
            "Tema: Persahabatan dan kejujuran",
            "Tokoh: Rina (protagonis, jujur dan pemberani), Dedi (antagonis, suka berbohong), Bu Guru (tritagonis, bijaksana)",
            "Alur: Rina menemukan dompet → Dedi mengaku pemiliknya → Rina ragu → Bu Guru membantu mengecek → Pemilik asli ditemukan → Dedi malu dan mengaku",
            "Latar: Kelas VII SMP, pagi hari, suasana tegang lalu haru",
            "Dialog: Penuh dengan percakapan yang menunjukkan karakter masing-masing tokoh",
            "Amanat: Kejujuran adalah sifat yang harus dijaga meskipun dalam situasi sulit.",
          ],
        },
        {
          judul: "3. Struktur Drama",
          isi: [
            "Teks drama memiliki struktur yang khas, terdiri dari tiga bagian utama: prolog, dialog, dan epilog.",
            "",
            "1. Prolog (Pembukaan)",
            "• Bagian awal drama yang berisi pengantar cerita",
            "• Biasanya disampaikan oleh narator atau tokoh tertentu kepada penonton",
            "• Berisi gambaran umum tentang latar, tokoh, dan konflik yang akan terjadi",
            "• Berfungsi untuk menarik perhatian penonton dan menyiapkan suasana",
            "• Contoh: \"Di sebuah desa kecil, hiduplah seorang petani miskin bersama ketiga anaknya. Namun, keserakahan mulai menghancurkan keluarga kecil itu...\"",
            "",
            "2. Dialog (Inti Cerita)",
            "• Bagian utama drama yang berisi percakapan antartokoh",
            "• Dialog terbagi ke dalam babak dan adegan:",
            "  — Babak: bagian besar dari drama yang menandai perubahan waktu atau tempat",
            "  — Adegan: bagian kecil dalam babak yang menandai perubahan situasi atau masuk/keluarnya tokoh",
            "• Struktur dialog mencakup tiga tahap:",
            "",
            "  a. Orientasi (Perkenalan)",
            "  • Memperkenalkan tokoh, latar, dan awal mula cerita",
            "  • Belum ada konflik yang serius",
            "",
            "  b. Komplikasi (Konflik)",
            "  • Munculnya masalah atau pertentangan di antara tokoh",
            "  • Konflik berkembang dari ringan menjadi semakin serius",
            "  • Bagian ini merupakan inti drama yang membuat penonton penasaran",
            "",
            "  c. Resolusi (Penyelesaian)",
            "  • Konflik mulai menemukan jalan keluar",
            "  • Tokoh mengambil keputusan atau menerima akibat dari perbuatannya",
            "  • Biasanya diakhiri dengan pesan moral atau pelajaran",
            "",
            "3. Epilog (Penutup)",
            "• Bagian akhir drama yang berisi kesimpulan atau pesan dari cerita",
            "• Biasanya disampaikan oleh narator atau salah satu tokoh",
            "• Berfungsi untuk memberikan refleksi kepada penonton setelah menyaksikan drama",
            "• Contoh: \"Demikianlah kisah tentang ketamakan yang membawa kehancuran. Semoga kita semua dapat mengambil pelajaran darinya.\"",
          ],
          contoh: [
            "Contoh struktur drama tiga babak sederhana:",
            "",
            "PROLOG:",
            "(Narator maju ke depan panggung. Lampu panggung redup.)",
            "NARATOR: Dua sahabat, Amir dan Budi, telah bersahabat sejak kecil. Namun, sebuah kesalahpahaman akan menguji persahabatan mereka. Saksikanlah kisah mereka...",
            "",
            "BABAK I — Orientasi (Di ruang kelas, pagi hari)",
            "AMIR: (tersenyum) Bud, besok jadi ke perpustakaan?",
            "BUDI: Jadi, dong. Sekalian kita cari buku biologi.",
            "",
            "BABAK II — Komplikasi (Di lapangan sekolah, jam istirahat)",
            "BUDI: (marah) Amir! Kenapa kamu bilang aku yang mencuri buku?",
            "AMIR: Aku tidak bilang begitu! Itu fitnah!",
            "BUDI: Jangan bohong! Semua orang bilang kamu yang menyebarkan rumor itu!",
            "(Keduanya saling berpaling. Suasana tegang.)",
            "",
            "BABAK III — Resolusi (Di ruang BK, siang hari)",
            "BU GURU: Sebenarnya buku itu dipinjam oleh Dani, bukan kalian. Maafkan kesalahpahaman ini.",
            "AMIR: (menunduk) Bud, maafkan aku. Aku seharusnya tidak mudah marah.",
            "BUDI: Aku juga salah. Aku terlalu cepat percaya rumor.",
            "(Mereka berjabat tangan. Suasana mencair.)",
            "",
            "EPILOG:",
            "NARATOR: Persahabatan yang diuji akan menjadi lebih kuat. Amir dan Budi belajar bahwa komunikasi adalah kunci untuk menghindari kesalahpahaman.",
          ],
        },
        {
          judul: "4. Kaidah Kebahasaan Drama",
          isi: [
            "Teks drama memiliki kaidah kebahasaan yang khas karena ditulis untuk diucapkan di atas panggung.",
            "",
            "1. Kalimat Langsung (Dialog)",
            "• Seluruh isi drama disampaikan melalui dialog antartokoh",
            "• Tidak menggunakan tanda petik — nama tokoh diikuti titik dua dan dialognya",
            "• Contoh: RINA: Aku tidak percaya kamu melakukan itu!",
            "",
            "2. Kata Ganti Orang (Pronomina)",
            "• Kata ganti orang pertama: aku, saya, kami, kita",
            "• Kata ganti orang kedua: kamu, Anda, kalian",
            "• Kata ganti orang ketiga: dia, ia, mereka, -nya",
            "• Penggunaan kata ganti mencerminkan hubungan antartokoh",
            "• Contoh: 'Kami tidak akan menyerah!' vs 'Aku tidak bisa melakukannya sendiri.'",
            "",
            "3. Kata Kerja Tindakan (Verba Aktif)",
            "• Kata kerja yang menggambarkan aksi tokoh di atas panggung",
            "• Contoh: berlari, berteriak, menangis, tertawa, duduk, berdiri",
            "• Sering muncul dalam petunjuk panggung",
            "• Contoh: (Rina berlari ke arah pintu sambil berteriak.)",
            "",
            "4. Konjungsi",
            "• Konjungsi temporal: lalu, kemudian, setelah itu, sebelumnya",
            "• Konjungsi kausal: karena, sebab, sehingga, akibatnya",
            "• Konjungsi pertentangan: tetapi, namun, meskipun",
            "• Digunakan untuk menghubungkan antarkalimat dalam dialog",
            "",
            "5. Bahasa Figuratif (Majas)",
            "• Drama sering menggunakan majas untuk memperindah dialog",
            "• Contoh majas:",
            "  — Personifikasi: 'Angin malam berbisik lembut di telingaku.'",
            "  — Metafora: 'Kau adalah bintang dalam gelap hidupku.'",
            "  — Hiperbola: 'Aku sudah menunggu seribu tahun lamanya.'",
            "",
            "6. Petunjuk Panggung (Kramagong)",
            "• Instruksi yang ditulis dalam tanda kurung untuk aktor",
            "• Menjelaskan gerakan, ekspresi, intonasi, dan tata panggung",
            "• Contoh: (dengan suara lirih), (sambil menunduk malu), (dari kejauhan terdengar suara petir)",
          ],
          rangkuman: [
            "Rumus 'K-P-K-K-B-P' untuk kaidah kebahasaan drama:",
            "K = Kalimat langsung (dialog antartokoh)",
            "P = Pronomina (kata ganti orang)",
            "K = Kata kerja tindakan (aksi tokoh)",
            "K = Konjungsi (temporal, kausal, pertentangan)",
            "B = Bahasa figuratif (majas)",
            "P = Petunjuk panggung (kramagong)",
          ],
        },
        {
          judul: "5. Jenis-Jenis Drama",
          isi: [
            "Berdasarkan bentuk, isi, dan cara penyajiannya, drama dapat dibedakan menjadi beberapa jenis.",
            "",
            "1. Drama Tragedi",
            "• Drama yang menceritakan kisah sedih atau menyayat hati",
            "• Berakhir dengan kesedihan, kekalahan, atau kematian tokoh utama",
            "• Tokoh protagonis biasanya mengalami nasib buruk akibat takdir atau kelemahan dirinya",
            "• Contoh: 'Romeo and Juliet' karya William Shakespeare, 'Bunga Rumah Makan' karya Utuy Tatang Sontani",
            "",
            "2. Drama Komedi",
            "• Drama ringan yang bersifat lucu dan menghibur",
            "• Berisi situasi konyol, salah paham lucu, atau tingkah laku tokoh yang menggelikan",
            "• Berakhir bahagia (happy ending)",
            "• Tujuan utama: menghibur penonton dan membuat mereka tertawa",
            "• Contoh: 'Opera Kecoa' karya Rendra",
            "",
            "3. Drama Melodrama",
            "• Drama yang menguras emosi penonton dengan adegan yang menyentuh",
            "• Dialog dan musik digunakan untuk membangun suasana haru",
            "• Tokoh digambarkan secara hitam-putih: baik sangat baik, jahat sangat jahat",
            "• Biasanya berakhir dengan kemenangan kebaikan atas kejahatan",
            "",
            "4. Drama Tari (Sendratari)",
            "• Drama yang disajikan melalui gerakan tari, bukan dialog verbal",
            "• Cerita disampaikan melalui gerak, ekspresi, dan iringan musik",
            "• Contoh: Sendratari Ramayana di Candi Prambanan",
            "",
            "5. Drama Musikal (Opera)",
            "• Drama yang menggabungkan dialog, nyanyian, dan tarian",
            "• Adegan diselingi lagu-lagu yang mendukung cerita",
            "• Musik berfungsi sebagai pengiring dan penunjuk suasana",
            "• Contoh: 'Laskar Pelangi' dalam versi musikal, 'West Side Story'",
            "",
            "PENTING: Dalam perkembangannya, batas antarjenis drama sering kabur. Sebuah drama bisa mengandung unsur tragedi sekaligus komedi — disebut tragikomedi.",
          ],
          contoh: [
            "Perbandingan jenis drama:",
            "",
            "| Jenis | Ciri Utama | Akhir Cerita | Contoh |",
            "|-------|-----------|-------------|--------|",
            "| Tragedi | Kisah sedih, penuh penderitaan | Kekalahan/kematian | Romeo and Juliet |",
            "| Komedi | Lucu, konyol, ringan | Bahagia | Opera Kecoa |",
            "| Melodrama | Emosional, haru | Kebaikan menang | Drama TV |",
            "| Sendratari | Tanpa dialog, gerak tari | Bervariasi | Ramayana |",
            "| Musikal | Dialog + lagu + tari | Bervariasi | West Side Story |",
          ],
        },
        {
          judul: "6. Nilai-Nilai dalam Drama",
          isi: [
            "Drama tidak hanya berfungsi sebagai hiburan, tetapi juga mengandung nilai-nilai yang dapat dipetik oleh penonton.",
            "",
            "1. Nilai Moral",
            "• Ajaran tentang baik dan buruk dalam kehidupan",
            "• Contoh: kejujuran, keberanian, kasih sayang, tanggung jawab",
            "• Dalam drama, nilai moral tersirat dari konsekuensi perbuatan tokoh",
            "• Tokoh jahat akan mendapat ganjaran, tokoh baik akan memperoleh kebahagiaan",
            "",
            "2. Nilai Sosial",
            "• Menggambarkan hubungan antarmanusia dalam masyarakat",
            "• Contoh: gotong royong, toleransi, musyawarah, solidaritas",
            "• Drama sering mengkritik ketimpangan sosial atau ketidakadilan yang terjadi di masyarakat",
            "",
            "3. Nilai Budaya",
            "• Tradisi, adat istiadat, dan kearifan lokal yang tercermin dalam drama",
            "• Drama daerah biasanya mengangkat budaya setempat",
            "• Contoh: upacara adat, pakaian tradisional, bahasa daerah",
            "• Berfungsi melestarikan dan memperkenalkan budaya kepada generasi muda",
            "",
            "4. Nilai Pendidikan",
            "• Pelajaran atau pengetahuan yang dapat dipetik dari drama",
            "• Contoh: pentingnya pendidikan, dampak pergaulan bebas, bahaya narkoba",
            "• Drama edukatif sering dipentaskan di sekolah-sekolah untuk menyampaikan pesan pembelajaran",
            "",
            "5. Nilai Estetika (Keindahan)",
            "• Keindahan bahasa, gerak, musik, dan tata panggung",
            "• Drama yang baik menggabungkan nilai keindahan dengan nilai-nilai lainnya",
            "",
            "PENTING: Satu drama biasanya mengandung lebih dari satu nilai. Saat menonton drama, catat nilai-nilai yang kamu temukan dan diskusikan bagaimana nilai-nilai tersebut relevan dengan kehidupan sehari-hari.",
          ],
          contoh: [
            "Analisis nilai dalam drama 'Bunga Rumah Makan' karya Utuy Tatang Sontani:",
            "",
            "Nilai Moral: Perjuangan seorang ibu untuk menghidupi anak-anaknya dengan jujur dan halal.",
            "Nilai Sosial: Kehidupan kelas bawah yang harus bertahan di tengah kesulitan ekonomi.",
            "Nilai Budaya: Penggambaran kehidupan masyarakat Sunda dengan nilai kekeluargaan yang kuat.",
            "Nilai Pendidikan: Pentingnya kerja keras dan kejujuran dalam menghadapi kesulitan hidup.",
            "Nilai Estetika: Penggunaan bahasa Sunda yang indah dan dialog yang natural.",
          ],
        },
        {
          judul: "7. Prosedur Menulis Naskah Drama",
          isi: [
            "Menulis naskah drama membutuhkan pemahaman tentang unsur dan struktur drama. Ikuti langkah-langkah berikut:",
            "",
            "Langkah 1: Tentukan Tema dan Ide Cerita",
            "• Pilih tema yang menarik dan dikuasai (persahabatan, keluarga, sekolah, lingkungan)",
            "• Tentukan pesan moral yang ingin disampaikan",
            "• Kembangkan ide cerita sederhana yang mudah dipentaskan",
            "",
            "Langkah 2: Buat Sinopsis dan Kerangka Cerita",
            "• Tulis sinopsis singkat tentang alur cerita secara keseluruhan",
            "• Buat kerangka: pembukaan → konflik → klimaks → penyelesaian",
            "• Tentukan jumlah babak dan adegan yang akan dibuat",
            "",
            "Langkah 3: Tentukan Tokoh dan Karakternya",
            "• Buat daftar tokoh yang akan muncul dalam drama",
            "• Tentukan watak masing-masing tokoh secara jelas",
            "• Beri nama tokoh yang mencerminkan karakter atau latar cerita",
            "",
            "Langkah 4: Tulis Prolog",
            "• Tulis bagian pembukaan yang menjelaskan latar dan pengantar cerita",
            "• Prolog bisa disampaikan oleh narator atau salah satu tokoh",
            "",
            "Langkah 5: Kembangkan Dialog",
            "• Tulis dialog antartokoh sesuai dengan babak dan adegan",
            "• Pastikan dialog mencerminkan karakter masing-masing tokoh",
            "• Sertakan petunjuk panggung yang menjelaskan gerak dan ekspresi",
            "• Gunakan bahasa yang sesuai dengan latar dan karakter tokoh",
            "",
            "Langkah 6: Tulis Epilog",
            "• Tulis bagian penutup yang berisi kesimpulan atau pesan moral",
            "• Epilog bisa disampaikan oleh narator atau salah satu tokoh",
            "",
            "Langkah 7: Sunting dan Revisi",
            "• Periksa kembali: apakah struktur sudah lengkap? (prolog, dialog, epilog)",
            "• Apakah dialog terdengar natural ketika diucapkan?",
            "• Periksa ejaan, tanda baca, dan petunjuk panggung",
            "• Bacakan naskah dengan suara keras untuk memeriksa kealamian dialog",
            "• Minta teman membaca naskah dan memberi masukan",
          ],
          rangkuman: [
            "Rumus menulis naskah drama: TEMA → SINOPIS → TOKOH → PROLOG → DIALOG → EPILOG → SUNING",
            "",
            "Tips penting: Bayangkan panggung di depan matamu saat menulis. Visualisasikan bagaimana tokoh bergerak, berbicara, dan berinteraksi. Drama yang baik drama yang dapat 'dilihat' hanya dengan membaca naskahnya.",
          ],
        },
      ],
    },
    latihan: [
      {
        id: 1,
        soal: "Teks drama adalah karya sastra yang berbentuk...",
        opsi: ["Cerita panjang", "Dialog", "Puisi", "Karangan bebas"],
        jawaban: 1,
        penjelasan: "Teks drama ditulis dalam bentuk dialog antartokoh yang dilengkapi petunjuk panggung.",
      },
      {
        id: 2,
        soal: "Petunjuk panggung dalam teks drama disebut juga...",
        opsi: ["Prolog", "Dialog", "Kramagong", "Epilog"],
        jawaban: 2,
        penjelasan: "Kramagong adalah petunjuk panggung yang ditulis dalam tanda kurung, menjelaskan gerak, ekspresi, dan suasana.",
      },
      {
        id: 3,
        soal: "Bagian awal drama yang berisi pengantar cerita disebut...",
        opsi: ["Prolog", "Epilog", "Dialog", "Adegan"],
        jawaban: 0,
        penjelasan: "Prolog adalah bagian pembuka drama yang berisi pengantar cerita, biasanya disampaikan oleh narator.",
      },
      {
        id: 4,
        soal: "Tokoh yang menjadi lawan dari tokoh protagonis disebut...",
        opsi: ["Tritagonis", "Figuran", "Antagonis", "Narator"],
        jawaban: 2,
        penjelasan: "Antagonis adalah tokoh yang menentang atau menjadi lawan dari tokoh protagonis.",
      },
      {
        id: 5,
        soal: "Berikut ini yang bukan merupakan unsur intrinsik drama adalah...",
        opsi: ["Tema", "Alur", "Sinopsis", "Amanat"],
        jawaban: 2,
        penjelasan: "Sinopsis adalah ringkasan cerita, bukan unsur intrinsik. Unsur intrinsik drama meliputi tema, tokoh, alur, latar, dialog, dan amanat.",
      },
      {
        id: 6,
        soal: "Drama yang menceritakan kisah sedih dan biasanya berakhir dengan kematian tokoh utama disebut...",
        opsi: ["Komedi", "Tragedi", "Melodrama", "Musikal"],
        jawaban: 1,
        penjelasan: "Tragedi adalah drama yang mengisahkan kesedihan atau penderitaan tokoh utama, sering berakhir dengan kekalahan atau kematian.",
      },
      {
        id: 7,
        soal: "Kalimat '(Rina berlari ke arah pintu sambil berteriak.)' dalam naskah drama termasuk...",
        opsi: ["Dialog", "Prolog", "Petunjuk panggung", "Epilog"],
        jawaban: 2,
        penjelasan: "Kalimat dalam tanda kurung adalah petunjuk panggung (kramagong) yang memberi instruksi kepada aktor.",
      },
      {
        id: 8,
        soal: "Konflik mulai muncul dan berkembang dalam tahapan alur drama pada bagian...",
        opsi: ["Prolog", "Orientasi", "Komplikasi", "Resolusi"],
        jawaban: 2,
        penjelasan: "Komplikasi adalah bagian di mana konflik mulai muncul dan berkembang dalam cerita drama.",
      },
      {
        id: 9,
        soal: "Nilai yang berkaitan dengan ajaran tentang perbuatan baik dan buruk dalam drama disebut nilai...",
        opsi: ["Sosial", "Moral", "Budaya", "Estetika"],
        jawaban: 1,
        penjelasan: "Nilai moral adalah ajaran tentang baik dan buruk yang dapat dipetik dari cerita drama.",
      },
      {
        id: 10,
        soal: "Langkah pertama dalam menulis naskah drama adalah...",
        opsi: ["Menulis dialog", "Menentukan tema dan ide cerita", "Membuat epilog", "Menyusun petunjuk panggung"],
        jawaban: 1,
        penjelasan: "Langkah pertama adalah menentukan tema dan ide cerita sebagai dasar pengembangan naskah drama.",
      },
    ],
    praktik: {
      tujuan: "Menulis naskah drama pendek dengan struktur, unsur, dan kaidah kebahasaan yang tepat.",
      instruksi: "Buatlah sebuah naskah drama pendek satu babak dengan tema persahabatan atau kehidupan sekolah. Tulis dengan struktur yang lengkap: prolog, dialog, dan epilog.",
      langkah: [
        "Tentukan tema drama (misalnya: persahabatan, kejujuran, tanggung jawab, atau tolong-menolong)",
        "Buat sinopsis singkat: perkenalan tokoh, konflik yang terjadi, dan bagaimana penyelesaiannya",
        "Tentukan 3-4 tokoh dengan karakter yang jelas (protagonis, antagonis, tritagonis)",
        "Tulis prolog yang menarik untuk membuka cerita",
        "Kembangkan dialog berdasarkan babak/adegan: orientasi → komplikasi → resolusi",
        "Sertakan petunjuk panggung yang menjelaskan gerakan, ekspresi, dan suasana",
        "Tulis epilog yang berisi pesan moral atau kesimpulan cerita",
        "Bacakan naskah dengan suara keras, perbaiki dialog yang terdengar tidak natural",
      ],
      tips: [
        "Pilih tema yang dekat dengan kehidupan sehari-hari agar lebih mudah menulis dialog",
        "Berikan nama tokoh yang mudah diingat dan mencerminkan karakternya",
        "Gunakan bahasa yang sesuai dengan usia dan latar tokoh (jika tokoh anak-anak, gunakan bahasa anak-anak)",
        "Jangan lupa menambahkan petunjuk panggung untuk membantu aktor memahami suasana dan gerakan",
        "Minta teman memerankan dialog secara sederhana untuk menguji kealamian naskah",
      ],
      contoh: "Lihat contoh struktur drama tiga babak pada materi Struktur Drama di atas sebagai panduan menulis naskah.",
    },
    kuis: [
      {
        id: 1,
        soal: "Perbedaan utama teks drama dengan teks prosa adalah...",
        opsi: ["Drama lebih panjang dari prosa", "Drama berbentuk dialog, prosa berbentuk narasi", "Drama tidak memiliki tokoh", "Prosa tidak memiliki alur"],
        jawaban: 1,
        penjelasan: "Drama disajikan dalam bentuk dialog antartokoh, sedangkan prosa disajikan dalam bentuk narasi atau cerita.",
      },
      {
        id: 2,
        soal: "'Kau adalah bintang dalam gelap hidupku' termasuk contoh majas...",
        opsi: ["Personifikasi", "Metafora", "Hiperbola", "Litotes"],
        jawaban: 1,
        penjelasan: "Metafora adalah majas perbandingan tanpa kata pembanding. 'Kau adalah bintang' membandingkan seseorang dengan bintang secara langsung.",
      },
      {
        id: 3,
        soal: "Berikut ini yang bukan merupakan fungsi petunjuk panggung (kramagong) adalah...",
        opsi: ["Menjelaskan gerakan tokoh", "Menjelaskan ekspresi wajah tokoh", "Menyampaikan dialog tokoh", "Menjelaskan tata panggung dan properti"],
        jawaban: 2,
        penjelasan: "Petunjuk panggung tidak menyampaikan dialog. Dialog adalah bagian yang diucapkan oleh tokoh, sedangkan petunjuk panggung adalah instruksi untuk aktor.",
      },
      {
        id: 4,
        soal: "Drama tari yang terkenal dari Indonesia yang dipentaskan di Candi Prambanan adalah...",
        opsi: ["Sendratari Ramayana", "Wayang Orang", "Ketoprak", "Ludruk"],
        jawaban: 0,
        penjelasan: "Sendratari Ramayana adalah drama tari yang dipentaskan di Candi Prambanan, Yogyakarta, menceritakan kisah Ramayana tanpa dialog.",
      },
      {
        id: 5,
        soal: "Bagian dalam dialog drama di mana konflik mencapai puncaknya disebut...",
        opsi: ["Orientasi", "Komplikasi", "Klimaks", "Resolusi"],
        jawaban: 2,
        penjelasan: "Klimaks adalah puncak konflik dalam drama, yaitu saat ketegangan mencapai titik tertinggi sebelum akhirnya menemukan penyelesaian.",
      },
      {
        id: 6,
        soal: "Kalimat 'Angin malam berbisik lembut di telingaku' mengandung majas...",
        opsi: ["Metafora", "Personifikasi", "Hiperbola", "Ironi"],
        jawaban: 1,
        penjelasan: "Personifikasi adalah majas yang memberikan sifat-sifat manusia pada benda mati. Angin digambarkan 'berbisik' seperti manusia.",
      },
      {
        id: 7,
        soal: "Tokoh tritagonis dalam drama berfungsi sebagai...",
        opsi: ["Tokoh utama", "Tokoh jahat", "Tokoh penengah", "Tokoh pembantu tanpa peran penting"],
        jawaban: 2,
        penjelasan: "Tritagonis adalah tokoh penengah yang berusaha mendamaikan protagonis dan antagonis atau memberikan solusi atas konflik.",
      },
      {
        id: 8,
        soal: "Drama yang menggabungkan dialog, nyanyian, dan tarian disebut...",
        opsi: ["Tragedi", "Komedi", "Melodrama", "Drama musikal"],
        jawaban: 3,
        penjelasan: "Drama musikal adalah drama yang menggabungkan tiga unsur: dialog, nyanyian (lagu), dan tarian dalam penyajiannya.",
      },
      {
        id: 9,
        soal: "Nilai estetika dalam drama berkaitan dengan...",
        opsi: ["Pesan moral cerita", "Keindahan bahasa, gerak, dan tata panggung", "Hubungan antartokoh", "Latar belakang penulis"],
        jawaban: 1,
        penjelasan: "Nilai estetika adalah nilai keindahan yang meliputi keindahan bahasa, gerakan tari, musik, dan tata panggung dalam pementasan drama.",
      },
      {
        id: 10,
        soal: "Seorang siswa menulis naskah drama. Setelah selesai, ia membacakannya dengan suara keras. Tujuan kegiatan ini adalah...",
        opsi: ["Menambah panjang naskah", "Memeriksa kealamian dialog", "Menghafalkan naskah", "Mencari kesalahan ejaan"],
        jawaban: 1,
        penjelasan: "Membacakan naskah dengan suara keras membantu penulis mendengar apakah dialog terdengar natural dan sesuai dengan karakter tokoh saat diucapkan.",
      },
    ],
  };

export default konten;
