// @ts-nocheck
import type { Konten } from "../types";

const kd = "3.2/4.2";

/* =============================================
   Unit 2: Teks Cerpen — IX S1
   KD 3.2/4.2 — Mengidentifikasi Unsur Pembangun & Menulis Cerpen
   ============================================= */
const konten: Konten = {
    belajar: {
      tujuan: [
        "Memahami hakikat, ciri-ciri, dan jenis-jenis teks cerpen (cerita pendek)",
        "Mengidentifikasi dan menganalisis unsur intrinsik cerpen: tema, tokoh, alur, latar, sudut pandang, amanat",
        "Mengidentifikasi dan menganalisis unsur ekstrinsik cerpen: latar belakang pengarang, nilai sosial, nilai moral, nilai budaya",
        "Memahami struktur teks cerpen: orientasi, rangkaian peristiwa, komplikasi, resolusi, koda",
        "Menganalisis kaidah kebahasaan cerpen: kata konkret, kalimat deskriptif, dialog, konjungsi temporal, majas",
        "Menulis cerpen dengan memperhatikan unsur pembangun, struktur, dan kaidah kebahasaan yang tepat",
      ],
      materi: [
        {
          judul: "1. Hakikat Teks Cerpen",
          catatan: "Cerpen adalah karya sastra prosa yang pendek, padat, dan memiliki kesan tunggal.",
          isi: [
            "Teks cerpen (cerita pendek) adalah karangan fiksi berbentuk prosa yang mengisahkan sepenggal kehidupan tokoh dengan konflik yang terbatas. Cerpen dapat dibaca dalam sekali duduk — biasanya terdiri atas 1.000–10.000 kata.",
            "",
            "Ciri-ciri teks cerpen:",
            "• Bersifat fiktif atau rekaan, meskipun dapat terinspirasi dari kisah nyata",
            "• Memiliki panjang yang pendek — cukup dibaca dalam 15–30 menit",
            "• Mengangkat satu konflik atau permasalahan utama (kesan tunggal)",
            "• Jumlah tokoh terbatas, biasanya 2–5 tokoh sentral",
            "• Alur cerita sederhana dan tidak berbelit-belit",
            "• Berfokus pada satu peristiwa atau momen penting dalam hidup tokoh",
            "• Menggunakan bahasa yang ekonomis, padat, dan bermakna",
            "• Bertujuan menyampaikan pesan atau amanat tertentu kepada pembaca",
            "",
            "Perbedaan cerpen dengan novel:",
            "✓ Cerpen: pendek, konflik tunggal, tokoh terbatas, selesai sekali duduk",
            "✗ Novel: panjang, konflik kompleks (bisa sub-plot), banyak tokoh, berbabak-babak",
            "",
            "PENTING: Cerpen bukanlah ringkasan novel. Cerpen adalah bentuk sastra mandiri yang mengutamakan kepadatan dan efisiensi cerita. Setiap kata dalam cerpen harus bermakna dan mendukung keseluruhan cerita.",
          ],
          contoh: [
            "Contoh judul cerpen terkenal dalam sastra Indonesia:",
            "",
            "• \"Robohnya Surau Kami\" — A.A. Navis (1955)",
            "  Kritik sosial tentang kemiskinan, agama, dan tanggung jawab sosial.",
            "",
            "• \"Senyum Karyamin\" — Ahmad Tohari (1989)",
            "  Kisah perjuangan hidup rakyat kecil dengan penuh kehangatan dan humanisme.",
            "",
            "• \"Malam Jahanam\" — Motinggo Busye (1962)",
            "  Cerita horor psikologis dengan latar Perang Kemerdekaan.",
            "",
            "• \"Dilarang Mencintai Bunga-Bunga\" — Kuntowijoyo (1968)",
            "  Cerpen eksperimental dengan gaya surealis yang khas.",
            "",
            "Cerpen-cerpen di atas menunjukkan bahwa cerpen juga bisa memiliki bobot sastra yang setara dengan novel. Kekuatan cerpen terletak pada kepadatan makna dalam ruang yang terbatas.",
          ],
        },
        {
          judul: "2. Unsur Intrinsik Cerpen: Tema, Tokoh, Alur, Latar, Sudut Pandang, Amanat",
          isi: [
            "Unsur intrinsik adalah unsur-unsur yang membangun cerpen dari dalam dan membentuk keutuhan cerita. Pemahaman terhadap unsur intrinsik menjadi kunci untuk menganalisis dan mengapresiasi cerpen secara mendalam.",
            "",
            "1. Tema",
            "• Gagasan pokok atau ide sentral yang mendasari seluruh cerita",
            "• Tema bersifat abstrak dan dapat dirumuskan dalam satu frasa atau kalimat",
            "• Contoh tema: kejujuran, pengorbanan, perjuangan, cinta tanah air, persahabatan, kesenjangan sosial",
            "• Dalam cerpen, tema biasanya hanya satu karena prinsip kesan tunggal",
            "",
            "2. Tokoh dan Penokohan",
            "• Tokoh: pelaku yang menjalani peristiwa dalam cerita",
            "• Penokohan: cara pengarang menggambarkan watak atau karakter tokoh",
            "• Jenis tokoh berdasarkan peran:",
            "  — Protagonis: tokoh utama yang mewakili nilai baik",
            "  — Antagonis: tokoh lawan yang menentang protagonis",
            "  — Tritagonis: tokoh penengah atau pendukung",
            "• Jenis tokoh berdasarkan watak:",
            "  — Tokoh bulat (round): wataknya kompleks, berkembang sepanjang cerita",
            "  — Tokoh datar (flat): wataknya tetap, tidak berubah",
            "• Metode penggambaran watak: melalui dialog, tindakan, pikiran tokoh, komentar pengarang",
            "",
            "3. Alur (Plot)",
            "• Rangkaian peristiwa yang membangun cerita secara berurutan dan logis",
            "• Tahapan alur:",
            "  1. Pengenalan (eksposisi) — memperkenalkan tokoh, latar, situasi awal",
            "  2. Munculnya konflik — masalah mulai terlihat",
            "  3. Konflik memuncak (klimaks) — puncak ketegangan cerita",
            "  4. Peleraian (antiklimaks) — ketegangan mulai menurun",
            "  5. Penyelesaian (resolusi) — konflik terselesaikan",
            "• Jenis alur: alur maju (kronologis), alur mundur (flashback), alur campuran",
            "",
            "4. Latar (Setting)",
            "• Tempat, waktu, dan suasana terjadinya peristiwa",
            "• Latar tempat: rumah, sekolah, pasar, kota, desa, dll.",
            "• Latar waktu: pagi, siang, malam, tahun 1945, era reformasi, dll.",
            "• Latar suasana: mencekam, haru, gembira, tegang, romantis",
            "• Latar sosial: status sosial tokoh, adat istiadat, nilai masyarakat",
            "",
            "5. Sudut Pandang (Point of View)",
            "• Posisi pengarang dalam membawakan cerita",
            "• Sudut pandang orang pertama (aku/saya): pengarang menjadi tokoh dalam cerita",
            "  — \"Aku\" sebagai tokoh utama (aku-an protagonistis)",
            "  — \"Aku\" sebagai tokoh sampingan (aku-an pengamat)",
            "• Sudut pandang orang ketiga (dia/ia): pengarang di luar cerita",
            "  — \"Dia\" mahatahu: pengarang tahu segalanya tentang semua tokoh",
            "  — \"Dia\" terbatas: pengarang hanya tahu satu tokoh tertentu",
            "",
            "6. Amanat (Pesan Moral)",
            "• Pesan yang ingin disampaikan pengarang kepada pembaca",
            "• Dapat disampaikan secara eksplisit (langsung melalui narasi) atau implisit (tersirat dalam cerita)",
            "• Amanat berkaitan erat dengan tema cerita",
            "",
            "Tips Menganalisis: Gunakan tabel untuk memetakan keenam unsur intrinsik setiap kali membaca cerpen. Catat temuanmu dalam bentuk poin-poin singkat.",
          ],
          contoh: [
            "Analisis unsur intrinsik cerpen 'Robohnya Surau Kami' karya A.A. Navis:",
            "",
            "Tema: Konflik antara ketaatan beragama yang keliru dengan tanggung jawab sosial.",
            "",
            "Tokoh Utama: Kakek (Haji Saleh) — seorang yang taat beribadah tapi lupa tanggung jawab sosial. Ia digambarkan sebagai tokoh bulat karena wataknya berubah drastis setelah percakapan dengan Tuhan dalam mimpinya.",
            "",
            "Alur: Alur maju dimulai dari pengenalan tokoh kakek dan surau, konflik muncul saat kakek dihadapkan pada pertanyaan-pertanyaan kritis dari Ajo Sidi, hingga klimaks ketika kakek bunuh diri karena merasa gagal sebagai manusia.",
            "",
            "Latar: Kota Padang (latar tempat), masa pascakemerdekaan (latar waktu), suasana religius dan penuh ironi (latar suasana).",
            "",
            "Sudut Pandang: Orang ketiga mahatahu — pengarang mengetahui isi hati dan pikiran semua tokoh, termasuk kakek dan Ajo Sidi.",
            "",
            "Amanat: Ibadah ritual saja tidak cukup; manusia juga harus peduli pada sesama dan kehidupan sosialnya.",
          ],
        },
        {
          judul: "3. Unsur Ekstrinsik Cerpen",
          isi: [
            "Unsur ekstrinsik adalah unsur-unsur yang berada di luar cerpen tetapi turut memengaruhi isi dan terbentuknya cerita. Analisis unsur ekstrinsik membantu kita memahami konteks lahirnya sebuah cerpen.",
            "",
            "1. Latar Belakang Pengarang",
            "• Biografi pengarang: riwayat hidup, pendidikan, pengalaman, profesi",
            "• Pandangan dunia (worldview) pengarang: ideologi, keyakinan, filsafat hidup",
            "• Psikologi pengarang: kondisi kejiwaan saat menulis cerpen",
            "• Contoh: A.A. Navis yang berlatar budaya Minang banyak menulis cerpen tentang kritik sosial dan agama dalam konteks budaya Minangkabau.",
            "",
            "2. Nilai Sosial-Budaya Masyarakat",
            "• Kondisi sosial masyarakat saat cerpen ditulis",
            "• Adat istiadat, tradisi, dan norma yang berlaku",
            "• Struktur sosial: kelas sosial, kesenjangan ekonomi, relasi kekuasaan",
            "• Contoh: Cerpen 'Senyum Karyamin' karya Ahmad Tohari mencerminkan kehidupan petani miskin di Jawa pada masa Orde Baru.",
            "",
            "3. Kondisi Zaman atau Sejarah",
            "• Peristiwa sejarah yang melatarbelakangi penulisan",
            "• Situasi politik dan ekonomi suatu era",
            "• Contoh: Cerpen-cerpen Pramoedya Ananta Toer banyak dipengaruhi oleh situasi politik rezim Orde Baru yang represif.",
            "",
            "4. Nilai Religius dan Filosofis",
            "• Keyakinan keagamaan yang dianut pengarang atau masyarakat",
            "• Pandangan filosofis tentang kehidupan yang tersirat dalam cerita",
            "• Contoh: Cerpen 'Penggugah' karya Danarto sarat dengan nilai-nilai sufistik dan mistisisme Jawa.",
            "",
            "PENTING: Unsur ekstrinsik tidak boleh dijadikan alat untuk 'menghakimi' cerpen (misalnya menilai buruk karena pengarangnya bermasalah). Unsur ekstrinsik berfungsi sebagai konteks untuk memahami cerpen secara lebih utuh, bukan sebagai tolok ukur kualitas sastra.",
          ],
          contoh: [
            "Contoh analisis unsur ekstrinsik cerpen 'Robohnya Surau Kami':",
            "",
            "Latar Belakang Pengarang: A.A. Navis lahir di Padangpanjang, Sumatra Barat, 1924. Ia besar dalam budaya Minang yang religius dan menjunjung tinggi adat. Pengalamannya sebagai redaktur majalah dan wartawan membentuk gaya kritisnya terhadap masalah sosial.",
            "",
            "Nilai Sosial-Budaya: Cerpen ini mengkritik praktik keagamaan yang hanya mementingkan ibadah ritual tanpa peduli pada kesejahteraan sosial. Ini relevan dengan budaya Minang yang memadukan adat dan agama (Adat basandi syarak, syarak basandi Kitabullah).",
            "",
            "Kondisi Zaman: Cerpen ditulis pada 1950-an, masa ketika Indonesia baru merdeka dan masyarakat sedang mencari jati diri. Pertanyaan tentang tanggung jawab sosial vs kepatuhan agama menjadi topik yang hangat.",
          ],
        },
        {
          judul: "4. Struktur Teks Cerpen",
          isi: [
            "Struktur teks cerpen adalah kerangka yang membangun keutuhan cerita dari awal hingga akhir. Struktur ini membantu penulis menyusun cerita secara logis dan membantu pembaca memahami cerita dengan runtut.",
            "",
            "1. Orientasi (Pengenalan)",
            "• Bagian awal cerita yang memperkenalkan tokoh, latar tempat, latar waktu, dan suasana",
            "• Memberikan gambaran awal tentang situasi sebelum konflik muncul",
            "• Biasanya dimulai dengan deskripsi yang menarik perhatian pembaca",
            '• Contoh: "Pagi itu, Mentari baru saja merekah di ufuk timur. Seorang anak laki-laki berdiri di pinggir jembatan kayu, memandangi sungai yang mengalir lambat. Matanya sayu, seperti menyimpan seribu rahasia."',
            "",
            "2. Rangkaian Peristiwa (Rising Action)",
            "• Urutan kejadian yang mengarah pada konflik utama",
            "• Peristiwa-peristiwa kecil yang membangun ketegangan",
            "• Tokoh mulai menghadapi rintangan atau masalah yang semakin kompleks",
            "• Bagian ini biasanya paling panjang dalam cerpen",
            "",
            "3. Komplikasi (Konflik)",
            "• Puncak masalah atau pertentangan yang dihadapi tokoh",
            "• Konflik dapat bersifat internal (dalam diri tokoh) atau eksternal (dengan tokoh lain/lingkungan)",
            "• Klimaks adalah titik ketegangan tertinggi dalam cerita",
            // eslint-disable-next-line
            '• Contoh: "\'Aku tidak bisa terus begini! Aku harus memilih: ikuti kata hatiku atau ikuti kata ayahku?\' teriak Rina sambil mengepalkan tangannya."',
            "",
            "4. Resolusi (Penyelesaian)",
            "• Masalah mulai menemukan jalan keluar",
            "• Tokoh mengambil keputusan atau menerima kenyataan",
            "• Ketegangan mereda menuju akhir cerita",
            "• Resolusi bisa bersifat happy ending, sad ending, atau open ending",
            "",
            "5. Koda (Penutup/Amanat)",
            "• Bagian akhir cerita yang berisi kesimpulan atau pesan moral",
            "• Tidak semua cerpen memiliki koda secara eksplisit",
            "• Koda dapat berupa kalimat reflektif, kutipan bijak, atau gambaran masa depan tokoh",
            '• Contoh: "Dari kejauhan, ia melihat senja yang sama. Namun kini, senja itu tidak lagi membuatnya sedih. Karena ia tahu, esok matahari akan terbit lagi."',
            "",
            "Tips Membaca struktur: Baca cerpen dua kali. Pertama, nikmati ceritanya secara utuh. Kedua, tandai perpindahan antarbagian struktur. Perhatikan perubahan suasana, waktu, dan intensitas konflik.",
          ],
          contoh: [
            "Analisis struktur cerpen pendek (contoh):",
            "",
            "Judul: 'Sepotong Roti untuk Ibu'",
            "",
            'Orientasi: "Rina duduk di dapur kecil rumah kontrakannya. Di hadapannya, sepotong roti tawar dan segelas teh manis. Ia menunggu ibunya pulang dari pasar seperti biasa." — Memperkenalkan tokoh Rina, latar dapur rumah kontrakan, waktu sore hari.',
            "",
            'Rangkaian Peristiwa: "Sudah satu jam Rina menunggu. Ibunya belum pulang. Ponselnya tak juga berbunyi. Rina mulai gelisah. Ia ingat ibunya batuk-batuk sejak semalam." — Ketegangan mulai dibangun dengan kecemasan Rina.',
            "",
            // eslint-disable-next-line
            'Komplikasi: "Tiba-tiba, tetangganya, Bu Ratna, mengetuk pintu. \'Rina... ibumu... dia jatuh di pasar. Sekarang di Puskesmas.\' Roti di tangan Rina jatuh. Jantungnya berdegup kencang." — Puncak konflik ketika Rina mendengar ibunya jatuh sakit.',
            "",
            'Resolusi: "Rina berlari ke Puskesmas. Di sana, ibunya terbaring lemah tapi tersenyum. \'Maaf, Nak, bikin khawatir.\' Rina memeluk ibunya erat. Tak ada yang lebih berharga selain ibunya." — Konflik mereda, ketegangan mencair.',
            "",
            'Koda: "Sepotong roti itu tetap utuh di meja dapur. Namun cinta Rina pada ibunya telah terisi penuh malam itu." — Pesan bahwa kasih sayang lebih berharga dari benda apa pun.',
          ],
        },
        {
          judul: "5. Kaidah Kebahasaan Cerpen",
          isi: [
            "Kaidah kebahasaan cerpen adalah ciri khas penggunaan bahasa yang membedakan cerpen dengan jenis teks lainnya. Penguasaan kaidah ini penting untuk menulis cerpen yang hidup dan bermakna.",
            "",
            "1. Kata Konkret",
            "• Kata yang merujuk pada objek nyata yang dapat ditangkap panca indra",
            "• Membantu pembaca membayangkan suasana dan benda dalam cerita",
            "• Contoh: bukan 'kendaraan' tapi 'becak usang', bukan 'minuman' tapi 'secangkir kopi pahit'",
            "• Semakin konkret kata yang dipilih, semakin hidup cerita yang tercipta",
            "",
            "2. Kalimat Deskriptif",
            "• Kalimat yang menggambarkan sesuatu secara terperinci sehingga pembaca seolah melihat, mendengar, atau merasakan",
            "• Digunakan untuk melukiskan latar, penampilan tokoh, atau suasana",
            '• Contoh: "Rambutnya yang panjang dan berombak tergerai lembut ditiup angin sore, membingkai wajahnya yang pucat namun tenang."',
            "",
            "3. Dialog (Kalimat Langsung)",
            "• Percakapan antartokoh yang ditandai dengan tanda petik",
            "• Membuat cerita lebih hidup dan dinamis",
            "• Contoh: \"'Kau yakin mau pergi?' tanya Ibu dengan suara bergetar. Rina menunduk. 'Aku harus, Bu. Ini kesempatanku.'\"",
            "",
            "4. Konjungsi Temporal dan Kausalitas",
            "• Konjungsi temporal: kemudian, lalu, setelah itu, sementara itu, tiba-tiba, akhirnya",
            "• Konjungsi kausalitas: karena, sebab, sehingga, oleh karena itu",
            "• Berfungsi menghubungkan antarreistiwa secara kronologis dan logis",
            "",
            "5. Majas (Gaya Bahasa)",
            "• Majas perbandingan: simile (bagai, laksana), metafora (adalah, merupakan), personifikasi (benda mati berlaku seperti manusia)",
            "• Majas penegasan: repetisi (pengulangan), pleonasme (kata berlebih)",
            '• Contoh personifikasi: "Angin malam itu berbisik pelan di telinganya."',
            '• Contoh simile: "Wajahnya pucat bagai bulan tersaput awan."',
            "",
            "6. Kata Ganti (Pronomina)",
            "• Digunakan untuk menggantikan nama tokoh agar tidak berulang",
            "• Contoh: ia, dia, mereka, -nya",
            "• Penggunaan variasi pronomina membuat cerita lebih luwes",
            "",
            "PENTING: Pemilihan kata (diksi) dalam cerpen sangat penting. Penulis cerpen harus cermat memilih kata yang paling tepat — bukan sekadar benar — karena setiap kata berkontribusi pada suasana dan makna keseluruhan cerita.",
          ],
          rangkuman: [
            "Rumus 'K3D-MP' untuk kaidah kebahasaan cerpen:",
            "K1 = Kata konkret (benda nyata, spesifik)",
            "K2 = Kalimat deskriptif (gambaran terperinci)",
            "K3 = Konjungsi temporal + kausalitas (hubungan waktu/sebab)",
            "D = Dialog (kalimat langsung antartokoh)",
            "M = Majas (gaya bahasa: metafora, personifikasi, simile)",
            "P = Pronomina (kata ganti: ia, dia, mereka)",
          ],
        },
        {
          judul: "6. Nilai-Nilai dalam Cerpen",
          isi: [
            "Setiap cerpen yang baik tidak hanya menghibur, tetapi juga mengandung nilai-nilai yang dapat dipetik dan diterapkan dalam kehidupan. Nilai-nilai ini tersirat melalui konflik, tokoh, dan amanat cerita.",
            "",
            "1. Nilai Moral",
            "• Ajaran tentang baik-buruk, benar-salah dalam kehidupan",
            "• Contoh: kejujuran, keberanian, tanggung jawab, kesetiaan, rela berkorban",
            "• Dalam cerpen 'Robohnya Surau Kami': kritik terhadap ketaatan buta yang melupakan tanggung jawab sosial",
            "",
            "2. Nilai Sosial",
            "• Nilai yang berkaitan dengan hubungan manusia dalam masyarakat",
            "• Contoh: gotong royong, toleransi, kepedulian pada sesama, solidaritas",
            "• Dalam cerpen 'Senyum Karyamin': semangat kebersamaan dan gotong royong warga desa",
            "",
            "3. Nilai Budaya",
            "• Tradisi, adat istiadat, dan kebiasaan yang tercermin dalam cerita",
            "• Memberikan pengetahuan tentang kearifan lokal suatu daerah",
            "• Contoh: tata cara pernikahan adat, upacara tradisional, sistem kekerabatan",
            "",
            "4. Nilai Religius/Spiritual",
            "• Ajaran keagamaan, hubungan manusia dengan Tuhan",
            "• Contoh: kekuatan doa, pentingnya bersyukur, tobat, pasrah pada Tuhan",
            "• Dalam cerpen 'Mata yang Enak Dipandang' karya Ahmad Tohari: keikhlasan menerima takdir",
            "",
            "5. Nilai Pendidikan",
            "• Pelajaran hidup yang dapat dipetik dan diterapkan pembaca",
            "• Contoh: rajin belajar, rendah hati, berani bermimpi, tidak mudah menyerah",
            "• Cerpen motivasi sering menonjolkan nilai pendidikan ini",
            "",
            "6. Nilai Estetika (Keindahan)",
            "• Nilai keindahan bahasa, gaya penceritaan, dan imajinasi",
            "• Membaca cerpen yang indah memberi pengalaman batin yang kaya",
            "• Cerpen dengan nilai estetika tinggi menggunakan majas, diksi puitis, dan struktur kalimat yang artistik",
            "",
            "PENTING: Nilai-nilai dalam cerpen jarang berdiri sendiri. Satu cerpen biasanya mengandung beberapa nilai sekaligus. Tugas pembaca adalah mengidentifikasi dan menggali nilai-nilai tersebut untuk memperkaya wawasan dan pengalaman batin.",
          ],
        },
        {
          judul: "7. Prosedur Menulis Cerpen",
          isi: [
            "Menulis cerpen adalah keterampilan yang dapat dipelajari dan dilatih. Ikuti langkah-langkah berikut untuk menghasilkan cerpen yang baik dan bermakna.",
            "",
            "Langkah 1: Temukan Ide",
            "• Gali ide dari pengalaman pribadi, pengamatan sehari-hari, berita, atau imajinasi",
            "• Tentukan satu konflik atau momen penting yang akan diceritakan",
            "• Rumuskan ide dalam satu kalimat: 'Cerita tentang seorang anak yang...'",
            "• Catat semua ide dalam buku catatan atau ponsel",
            "",
            "Langkah 2: Tentukan Tema dan Pesan",
            "• Apa tema utama cerpenmu? (persahabatan, perjuangan, cinta, dll.)",
            "• Pesan apa yang ingin kamu sampaikan kepada pembaca?",
            "• Pastikan tema dan pesan selaras dengan ide cerita",
            "",
            "Langkah 3: Kembangkan Tokoh dan Karakter",
            "• Tentukan tokoh utama dan tokoh pendukung",
            "• Buat profil singkat setiap tokoh: nama, usia, sifat, kebiasaan, latar belakang",
            "• Pikirkan bagaimana tokoh akan bereaksi terhadap konflik",
            "",
            "Langkah 4: Buat Kerangka Alur",
            "• Susun peristiwa secara kronologis berdasarkan struktur cerpen",
            "• Orientasi → Rangkaian Peristiwa → Komplikasi → Resolusi → Koda",
            "• Tentukan di mana klimaks akan ditempatkan",
            "",
            "Langkah 5: Tulis Draf Pertama",
            "• Kembangkan kerangka menjadi cerita utuh",
            "• Jangan khawatir tentang kesempurnaan — tulis saja dulu",
            "• Gunakan kalimat deskriptif, dialog, dan majas sesuai kebutuhan",
            "• Perhatikan sudut pandang yang kamu pilih (aku/dia)",
            "",
            "Langkah 6: Beri Judul yang Menarik",
            "• Judul harus mencerminkan isi cerita",
            "• Judul yang baik membuat pembaca penasaran",
            "• Contoh judul efektif: 'Sepotong Roti untuk Ibu', 'Matahari di Ujung Senja'",
            "",
            "Langkah 7: Sunting dan Revisi",
            "• Periksa struktur: apakah orientasi, komplikasi, resolusi sudah lengkap?",
            "• Periksa bahasa: ejaan, tanda baca, pilihan kata (diksi)",
            "• Baca dengan suara keras untuk mendeteksi kalimat yang janggal",
            "• Minta teman membaca dan memberi masukan",
            "",
            "Langkah 8: Publikasikan",
            "• Kumpulkan di kelas untuk dinilai guru",
            "• Unggah di blog pribadi atau platform literasi sekolah",
            "• Ikut lomba menulis cerpen untuk mengasah kemampuan",
            "",
            "Tips: Menulis cerpen yang baik membutuhkan latihan rutin. Mulailah dengan menulis 200–300 kata per hari tentang apa pun yang kamu lihat atau rasakan. Semakin sering berlatih, semakin tajam insting menulismu.",
          ],
          rangkuman: [
            "Rumus menulis cerpen: IDE → TEMA → TOKOH → ALUR → DRAF → JUDUL → SUNING → PUBLIKASI",
            "",
            "Ingat prinsip 'CERPEN':",
            "C = Ceritakan satu konflik",
            "E = Efisien dalam kata (padat)",
            "R = Runtut dalam alur",
            "P = Penuhi unsur intrinsik",
            "E = Ejaan dan bahasa yang baik",
            "N = Nikmati proses menulis!",
          ],
        },
      ],
    },
    latihan: [
      {
        id: 1,
        soal: "Teks cerpen adalah karangan fiksi berbentuk prosa yang...",
        opsi: [
          "Panjang, berbabak-babak, dan memiliki banyak tokoh",
          "Pendek, konflik tunggal, dan selesai dibaca sekali duduk",
          "Menceritakan kisah nyata seorang tokoh terkenal",
          "Berisi fakta ilmiah dan data penelitian",
        ],
        jawaban: 1,
        penjelasan: "Cerpen adalah prosa fiksi yang pendek, mengangkat satu konflik tunggal, dan dapat dibaca dalam sekali duduk (15–30 menit).",
      },
      {
        id: 2,
        soal: "Berikut ini yang bukan merupakan ciri teks cerpen adalah...",
        opsi: [
          "Jumlah tokoh terbatas",
          "Alur cerita sederhana",
          "Memiliki sub-plot yang kompleks",
          "Bahasa yang ekonomis dan padat",
        ],
        jawaban: 2,
        penjelasan: "Cerpen memiliki alur yang sederhana dengan satu konflik utama, bukan sub-plot kompleks. Sub-plot kompleks adalah ciri novel.",
      },
      {
        id: 3,
        soal: "Perbedaan utama antara cerpen dan novel terletak pada...",
        opsi: [
          "Jenis alur yang digunakan",
          "Panjang cerita dan kompleksitas konflik",
          "Penggunaan majas",
          "Jumlah pembaca",
        ],
        jawaban: 1,
        penjelasan: "Cerpen pendek dengan konflik tunggal, novel panjang dengan konflik kompleks (bisa memiliki sub-plot).",
      },
      {
        id: 4,
        soal: "Unsur intrinsik cerpen yang berupa gagasan pokok yang mendasari cerita disebut...",
        tipe: "ISIAN",
        opsi: ["tema"],
        jawaban: "tema",
        penjelasan: "Tema adalah gagasan pokok atau ide sentral yang mendasari seluruh cerita. Tema bersifat abstrak dan menjadi fondasi cerita.",
      },
      {
        id: 5,
        soal: "Tokoh dalam cerpen yang wataknya kompleks dan berkembang sepanjang cerita disebut...",
        opsi: ["Tokoh datar (flat)", "Tokoh bulat (round)", "Tokoh antagonis", "Tokoh statis"],
        jawaban: 1,
        penjelasan: "Tokoh bulat (round character) adalah tokoh yang wataknya kompleks dan mengalami perkembangan atau perubahan selama cerita berlangsung.",
      },
      {
        id: 6,
        soal: "Klimaks adalah puncak konflik dalam cerpen yang menentukan perubahan nasib tokoh.",
        tipe: "BENAR_SALAH",
        opsi: ["Benar", "Salah"],
        jawaban: 0,
        penjelasan: "Klimaks adalah titik puncak ketegangan dalam cerita, bagian paling menegangkan dari konflik yang dialami tokoh.",
      },
      {
        id: 7,
        soal: "Jika pengarang menceritakan tokoh 'aku' yang menjadi tokoh utama, sudut pandang yang digunakan adalah...",
        opsi: [
          "Orang ketiga mahatahu",
          "Orang ketiga terbatas",
          "Orang pertama sebagai tokoh utama",
          "Orang pertama sebagai pengamat",
        ],
        jawaban: 2,
        penjelasan: "Sudut pandang orang pertama sebagai tokoh utama menggunakan kata ganti 'aku' dan tokoh 'aku' menjadi pusat cerita (aku-an protagonistis).",
      },
      {
        id: 8,
        soal: "Kalimat 'Angin malam berbisik pelan di telinganya' mengandung majas...",
        opsi: ["Metafora", "Personifikasi", "Simile", "Hiperbola"],
        jawaban: 1,
        penjelasan: "Personifikasi adalah majas yang memberikan sifat manusia pada benda mati. Angin 'berbisik' adalah perilaku manusia, sehingga termasuk personifikasi.",
      },
      {
        id: 9,
        soal: "Latar belakang pengarang memengaruhi tema dan gaya penulisan cerpen.",
        tipe: "BENAR_SALAH",
        opsi: ["Benar", "Salah"],
        jawaban: 0,
        penjelasan: "Latar belakang pengarang mencakup biografi, riwayat hidup, pendidikan, pengalaman, dan pandangan dunia pengarang yang memengaruhi karyanya.",
      },
      {
        id: 10,
        soal: "Yang dimaksud dengan kata konkret dalam cerpen adalah kata yang...",
        opsi: [
          "Memiliki arti kiasan",
          "Merujuk pada objek nyata yang dapat ditangkap panca indra",
          "Berasal dari bahasa asing",
          "Digunakan sebagai kata penghubung",
        ],
        jawaban: 1,
        penjelasan: "Kata konkret adalah kata yang merujuk pada objek nyata yang dapat dilihat, didengar, diraba, dicium, atau dirasakan. Contoh: 'becak usang' lebih konkret daripada 'kendaraan'.",
      },
    ],
    praktik: {
      tujuan: "Menulis cerpen pendek dengan memperhatikan unsur intrinsik, struktur, dan kaidah kebahasaan yang tepat.",
      instruksi: "Buatlah sebuah cerpen bertema bebas (pilih salah satu: persahabatan, keluarga, perjuangan, atau lingkungan) dengan panjang 500–800 kata. Gunakan struktur cerpen yang lengkap dan perhatikan unsur intrinsik serta kaidah kebahasaan.",
      langkah: [
        "Tentukan tema cerpen yang akan kamu tulis. Pilih satu dari empat tema: persahabatan, keluarga, perjuangan, atau lingkungan.",
        "Buat profil singkat tokoh utama: beri nama, tentukan usia, sifat, dan latar belakangnya. Tentukan juga satu tokoh pendukung.",
        "Tulis kerangka alur berdasarkan struktur cerpen: orientasi (2–3 kalimat) → rangkaian peristiwa (3–4 kalimat) → komplikasi/klimaks (2–3 kalimat) → resolusi (2–3 kalimat) → koda (1–2 kalimat).",
        "Kembangkan kerangka menjadi cerpen utuh sepanjang 500–800 kata. Gunakan kalimat deskriptif untuk menggambarkan latar dan suasana.",
        "Sematkan dialog antartokoh untuk membuat cerita lebih hidup. Gunakan tanda petik dan variasi kata pengiring (berkata, berbisik, berteriak, bertanya).",
        "Gunakan minimal dua jenis majas (personifikasi, metafora, atau simile) dalam cerpenmu.",
        "Beri judul yang menarik dan mencerminkan isi cerita. Hindari judul yang terlalu umum seperti 'Persahabatan' atau 'Keluarga'.",
        "Periksa kembali cerpenmu: apakah struktur sudah lengkap? Apakah konflik tersampaikan dengan jelas? Perbaiki ejaan, tanda baca, dan pilihan kata. Minta teman membaca dan memberi masukan.",
      ],
      tips: [
        "Mulailah dengan kalimat pembuka yang menarik perhatian, misalnya dengan dialog atau deskripsi yang kuat.",
        "Gunakan panca indra dalam deskripsi — jangan hanya visual, tapi juga suara, bau, rasa, dan sentuhan.",
        "Jangan terburu-buru menyelesaikan cerita. Biarkan konflik berkembang secara alami sebelum mencapai resolusi.",
        "Baca ulang cerpenmu dengan suara keras. Jika ada kalimat yang terdengar janggal, perbaiki.",
        "Minta pendapat orang lain. Terkadang kita butuh perspektif baru untuk melihat kekurangan cerita kita.",
      ],
      contoh: "Lihat contoh analisis struktur cerpen 'Sepotong Roti untuk Ibu' pada materi Struktur Teks Cerpen sebagai panduan dalam menyusun kerangka cerita.",
    },
    kuis: [
      {
        id: 1,
        soal: "Gagasan pokok yang mendasari cerita dan bersifat abstrak disebut...",
        opsi: ["Alur", "Tema", "Amanat", "Latar"],
        jawaban: 1,
        penjelasan: "Tema adalah gagasan pokok atau ide sentral yang mendasari cerita. Tema bersifat abstrak dan menjadi landasan seluruh cerita.",
      },
      {
        id: 2,
        soal: "Berikut ini urutan struktur teks cerpen yang benar adalah...",
        opsi: [
          "Orientasi → Komplikasi → Rangkaian Peristiwa → Resolusi → Koda",
          "Orientasi → Rangkaian Peristiwa → Komplikasi → Resolusi → Koda",
          "Rangkaian Peristiwa → Orientasi → Komplikasi → Koda → Resolusi",
          "Orientasi → Rangkaian Peristiwa → Resolusi → Komplikasi → Koda",
        ],
        jawaban: 1,
        penjelasan: "Urutan struktur teks cerpen yang benar: Orientasi (pengenalan) → Rangkaian Peristiwa (menuju konflik) → Komplikasi/Klimaks (puncak konflik) → Resolusi (penyelesaian) → Koda (penutup/pesan).",
      },
      {
        id: 3,
        soal: "Cerpen 'Robohnya Surau Kami' menggunakan sudut pandang...",
        opsi: [
          "Orang pertama tokoh utama",
          "Orang pertama pengamat",
          "Orang ketiga mahatahu",
          "Orang ketiga terbatas",
        ],
        jawaban: 2,
        penjelasan: "A.A. Navis menggunakan sudut pandang orang ketiga mahatahu dalam 'Robohnya Surau Kami'. Pengarang mengetahui isi hati dan pikiran semua tokoh, termasuk kakek dan Ajo Sidi.",
      },
      {
        id: 4,
        soal: "Penggunaan kata 'bagai', 'laksana', 'seperti' dalam cerpen menunjukkan majas...",
        tipe: "ISIAN",
        opsi: ["simile"],
        jawaban: "simile",
        penjelasan: "Simile adalah majas perbandingan yang menggunakan kata penghubung seperti 'bagai', 'laksana', 'seperti', 'bagaikan', atau 'bak' untuk membandingkan dua hal yang berbeda.",
      },
      {
        id: 5,
        soal: "Perbedaan antara tokoh protagonis dan antagonis terletak pada...",
        opsi: [
          "Jumlah dialog dalam cerita",
          "Pihak yang didukung atau dilawan dalam konflik",
          "Latar belakang sosialnya",
          "Panjang deskripsi yang diberikan pengarang",
        ],
        jawaban: 1,
        penjelasan: "Protagonis adalah tokoh yang mendukung nilai baik dan menjadi pusat simpati pembaca. Antagonis adalah tokoh yang menentang protagonis dan menjadi sumber konflik.",
      },
      {
        id: 6,
        soal: "Alur mundur (flashback) menceritakan peristiwa yang terjadi sebelum masa kini.",
        tipe: "BENAR_SALAH",
        opsi: ["Benar", "Salah"],
        jawaban: 0,
        penjelasan: "Alur mundur atau flashback adalah teknik penceritaan yang menceritakan peristiwa yang telah terjadi di masa lalu, biasanya dimulai dari bagian akhir atau tengah cerita.",
      },
      {
        id: 7,
        soal: "Nilai yang terkandung dalam cerpen ketika tokoh menunjukkan sikap gotong royong dan peduli sesama termasuk nilai...",
        opsi: ["Moral", "Sosial", "Budaya", "Religius"],
        jawaban: 1,
        penjelasan: "Nilai sosial berkaitan dengan hubungan antarmanusia dalam masyarakat, seperti gotong royong, solidaritas, toleransi, dan kepedulian pada sesama.",
      },
      {
        id: 8,
        soal: "Jika seorang pengarang hanya mengetahui perasaan dan pikiran tokoh utama, tetapi tidak mengetahui isi hati tokoh lain, sudut pandang yang digunakan adalah...",
        opsi: [
          "Orang ketiga mahatahu",
          "Orang ketiga terbatas",
          "Orang pertama tokoh utama",
          "Orang pertama pengamat",
        ],
        jawaban: 1,
        penjelasan: "Sudut pandang orang ketiga terbatas (third person limited) menggunakan kata ganti 'dia' untuk tokoh utama, dan pengarang hanya mengetahui isi hati/pikiran tokoh utama saja, tidak tokoh lainnya.",
      },
      {
        id: 9,
        soal: "'Wajahnya bagaikan bulan purnama' adalah contoh majas metafora.",
        tipe: "BENAR_SALAH",
        opsi: ["Benar", "Salah"],
        jawaban: 1,
        penjelasan: "Kalimat tersebut adalah contoh majas simile, bukan metafora. Simile menggunakan kata pembanding seperti 'bagai', 'laksana', atau 'seperti', sedangkan metafora menggunakan kata 'adalah' atau 'merupakan' tanpa kata pembanding.",
      },
      {
        id: 10,
        soal: "Berikut ini yang membedakan 'tokoh bulat' (round character) dengan 'tokoh datar' (flat character) dalam cerpen adalah...",
        opsi: [
          "Tokoh bulat hanya muncul di awal cerita, tokoh datar di akhir",
          "Tokoh bulat memiliki watak kompleks dan berkembang, tokoh datar wataknya tetap",
          "Tokoh bulat selalu protagonis, tokoh datar selalu antagonis",
          "Tokoh bulat digambarkan secara fisik, tokoh datar secara psikologis",
        ],
        jawaban: 1,
        penjelasan: "Tokoh bulat (round character) memiliki watak yang kompleks, multidimensional, dan dapat berkembang sepanjang cerita. Tokoh datar (flat character) memiliki watak yang sederhana dan tidak mengalami perubahan.",
      },
    ],
  };

export default konten;
