import type { Konten, Soal } from "../types";

const kd = "3.4/4.4";

/* =============================================
   Unit 4: Teks Laporan (Penelitian) Percobaan — IX S2
   KD 3.4/4.4 — Mengidentifikasi Informasi & Menyusun Teks Laporan Percobaan
   ============================================= */
const konten: Konten = {
    belajar: {
      tujuan: [
        "Memahami hakikat, ciri, dan tujuan teks laporan percobaan",
        "Mengidentifikasi struktur teks laporan percobaan: judul, tujuan, alat/bahan, langkah, hasil, simpulan",
        "Menganalisis kaidah kebahasaan teks laporan percobaan: istilah teknis, kalimat pasif, dan konjungsi",
        "Membedakan teks laporan percobaan dengan teks prosedur",
        "Menyusun teks laporan percobaan secara sistematis berdasarkan data percobaan yang dilakukan",
      ],
      materi: [
        {
          judul: "1. Hakikat Teks Laporan Percobaan",
          catatan: "Teks laporan percobaan adalah tulisan yang menyampaikan hasil dari suatu kegiatan percobaan atau eksperimen secara objektif dan sistematis.",
          isi: [
            "Teks laporan percobaan (sering disebut juga laporan praktikum atau laporan eksperimen) adalah teks yang berisi paparan tentang tujuan, proses, dan hasil suatu percobaan yang dilakukan secara ilmiah. Teks ini disusun berdasarkan fakta dan data yang diperoleh selama percobaan berlangsung.",
            "",
            "Dalam pembelajaran Bahasa Indonesia di kelas IX, teks laporan percobaan menjadi salah satu jenis teks yang penting dikuasai karena melatih kemampuan berpikir ilmiah, sistematis, dan objektif. Teks ini banyak digunakan di berbagai bidang ilmu, terutama sains dan penelitian.",
            "",
            "Ciri-ciri teks laporan percobaan:",
            "• Disusun berdasarkan hasil percobaan yang dilakukan secara nyata",
            "• Bersifat objektif — tidak dipengaruhi opini atau perasaan pribadi penulis",
            "• Menggunakan data dan fakta sebagai dasar penulisan",
            "• Disusun secara sistematis dan logis",
            "• Menggunakan bahasa ilmiah yang tepat dan jelas",
            "• Dilengkapi dengan simpulan yang menjawab tujuan percobaan",
            "",
            "Tujuan teks laporan percobaan:",
            "✓ Melaporkan hasil percobaan secara terperinci dan akurat",
            "✓ Mendokumentasikan proses dan temuan untuk referensi di masa mendatang",
            "✓ Mengomunikasikan temuan kepada pembaca, baik kalangan akademis maupun umum",
            "✓ Membuktikan atau menguji suatu hipotesis melalui data empiris",
            "",
            "PENTING: Teks laporan percobaan berbeda dengan catatan harian laboratorium. Laporan percobaan disusun setelah percobaan selesai dan bersifat formal, sedangkan catatan laboratorium ditulis saat percobaan berlangsung dan boleh bersifat informal.",
          ],
          contoh: [
            "Contoh judul laporan percobaan yang baik:",
            "• \"Pengaruh Suhu Air terhadap Kecepatan Larutnya Gula\"",
            "• \"Menguji Kekuatan Daya Serap Berbagai Merek Kertas Tisu\"",
            "• \"Pengaruh Cahaya Matahari terhadap Pertumbuhan Tanaman Kacang Hijau\"",
            "• \"Pengamatan Perubahan Warna Daun akibat Klorofil\"",
            "• \"Uji Kandungan Vitamin C pada Berbagai Buah Jeruk\"",
            "",
            "Setiap judul di atas mencerminkan isi percobaan, variabel yang diuji, dan objek yang diteliti.",
          ],
        },
        {
          judul: "2. Ciri dan Tujuan Laporan Percobaan",
          isi: [
            "Untuk dapat menulis teks laporan percobaan dengan baik, kita perlu memahami ciri-ciri dan tujuannya secara mendalam.",
            "",
            "A. Ciri-Ciri Teks Laporan Percobaan",
            "",
            "1. Berdasarkan Fakta",
            "• Semua informasi yang disajikan dalam laporan harus berdasarkan data hasil percobaan",
            "• Data dapat berupa angka (kuantitatif) maupun deskripsi (kualitatif)",
            "• Tidak boleh ada opini atau spekulasi tanpa dasar data",
            "• Contoh: \"Suhu air mencapai 90°C saat mendidih\" (fakta), bukan \"Airnya terasa sangat panas\" (opini)",
            "",
            "2. Objektif",
            "• Penulis tidak boleh memihak atau memasukkan perasaan pribadi",
            "• Laporan ditulis apa adanya sesuai hasil yang diperoleh",
            "• Jika hasil tidak sesuai harapan, tetap dilaporkan dengan jujur",
            "",
            "3. Sistematis",
            "• Informasi disusun dalam urutan yang logis dan terstruktur",
            "• Mengikuti format baku: judul → tujuan → alat/bahan → langkah → hasil → simpulan",
            "• Setiap bagian memiliki fungsi dan isi yang jelas",
            "",
            "4. Menggunakan Bahasa Ilmiah",
            "• Pilihan kata bersifat tepat, baku, dan sesuai kaidah bahasa Indonesia",
            "• Menggunakan istilah teknis yang relevan dengan percobaan",
            "• Kalimat efektif, jelas, dan tidak ambigu",
            "",
            "5. Lengkap dan Menyeluruh",
            "• Mencakup semua aspek percobaan dari awal hingga akhir",
            "• Data disajikan secara utuh, tidak dipilih yang mendukung saja",
            "• Simpulan menjawab tujuan yang telah ditetapkan",
            "",
            "B. Tujuan Laporan Percobaan",
            "• Mendokumentasikan proses dan hasil percobaan secara ilmiah",
            "• Menyediakan data bagi peneliti lain untuk verifikasi atau pengembangan",
            "• Melatih kemampuan berpikir kritis dan sistematis",
            "• Mengembangkan keterampilan komunikasi ilmiah tertulis",
            "",
            "PENTING: Semakin objektif dan sistematis laporan percobaan, semakin tinggi nilai ilmiahnya. Hindari menambahkan informasi yang tidak relevan atau data yang tidak akurat.",
          ],
          contoh: [
            "Perbandingan laporan yang baik dan kurang baik:",
            "",
            "Laporan Kurang Baik: \"Airnya berubah warna jadi ungu. Menurut saya ini karena bahannya berkualitas bagus. Warnanya cantik sekali.\"",
            "  → Berisi opini (\"menurut saya\", \"cantik sekali\"), tidak objektif.",
            "",
            "Laporan Baik: \"Setelah ditambahkan indikator universal sebanyak 3 tetes, larutan berubah menjadi ungu dengan pH 8,5 yang menunjukkan sifat basa.\"",
            "  → Objektif, menyertakan data (pH 8,5), menggunakan istilah teknis (indikator universal).",
          ],
        },
        {
          judul: "3. Struktur Teks Laporan Percobaan",
          isi: [
            "Teks laporan percobaan memiliki struktur baku yang harus diikuti agar informasi tersampaikan secara runtut dan lengkap. Berikut struktur lengkap teks laporan percobaan:",
            "",
            "1. Judul",
            "• Mencerminkan isi percobaan secara singkat dan jelas",
            "• Biasanya menyebutkan variabel yang diuji dan objek yang diteliti",
            "• Contoh: \"Pengaruh Jenis Pupuk terhadap Tinggi Tanaman Bawang Merah\"",
            "• Judul yang baik: informatif, spesifik, dan mudah dipahami",
            "",
            "2. Tujuan Percobaan",
            "• Berisi pernyataan tentang apa yang ingin dicapai atau dibuktikan",
            "• Dirumuskan secara jelas dan terukur",
            "• Contoh: \"Untuk mengetahui pengaruh suhu air terhadap kecepatan larutnya gula pasir.\"",
            "• Tujuan harus selaras dengan judul dan hasil akhir percobaan",
            "",
            "3. Alat dan Bahan",
            "• Daftar semua alat yang digunakan dalam percobaan",
            "• Daftar semua bahan yang digunakan beserta jumlahnya",
            "• Disajikan dalam bentuk poin atau tabel agar rapi",
            "• Contoh: Alat: gelas kimia 100 mL, termometer, pengaduk, stopwatch",
            "  Bahan: air 200 mL, gula pasir 50 gram, es batu 5 buah",
            "",
            "4. Langkah-Langkah Percobaan (Prosedur)",
            "• Berisi urutan kegiatan yang dilakukan selama percobaan",
            "• Ditulis secara kronologis dan detail",
            "• Menggunakan kalimat imperatif atau kalimat pasif",
            "• Setiap langkah harus jelas dan dapat diulang oleh orang lain",
            "• Contoh: \"Siapkan gelas kimia dan isi dengan 200 mL air.\"",
            "",
            "5. Hasil Percobaan",
            "• Menyajikan data yang diperoleh selama percobaan",
            "• Data dapat berupa tabel, grafik, atau deskripsi",
            "• Disajikan secara objektif tanpa interpretasi",
            "• Contoh: tabel yang menunjukkan perubahan suhu setiap 1 menit",
            "",
            "6. Simpulan",
            "• Menjawab tujuan percobaan berdasarkan data hasil",
            "• Merupakan interpretasi singkat dari data yang diperoleh",
            "• Ditulis secara padat dan jelas",
            "• Contoh: \"Berdasarkan percobaan, dapat disimpulkan bahwa semakin tinggi suhu air, semakin cepat gula larut.\"",
            "",
            "Tips Menulis Struktur: Gunakan format penomoran yang konsisten untuk setiap bagian. Pastikan setiap bagian terisi lengkap sebelum laporan dikumpulkan.",
          ],
          contoh: [
            "Contoh struktur laporan percobaan sederhana — \"Membuat Pelangi dalam Gelas\":",
            "",
            "Judul: Membuat Pelangi dalam Gelas",
            "",
            "Tujuan: Mengamati perbedaan massa jenis berbagai larutan gula sehingga terbentuk lapisan warna seperti pelangi.",
            "",
            "Alat dan Bahan:",
            "• 5 gelas plastik bening",
            "• Sendok, gelas ukur, pipet tetes",
            "• Air hangat, gula pasir, pewarna makanan (merah, kuning, hijau, biru, ungu)",
            "",
            "Langkah:",
            "1. Siapkan 5 gelas dan isi masing-masing dengan 100 mL air hangat.",
            "2. Tambahkan gula dengan takaran berbeda: gelas 1 (0 sdm), 2 (1 sdm), 3 (2 sdm), 4 (3 sdm), 5 (4 sdm).",
            "3. Aduk hingga gula larut sempurna.",
            "4. Teteskan pewarna makanan berbeda pada setiap gelas.",
            "5. Masukkan larutan ke dalam satu gelas besar secara perlahan dari yang paling pekat (terbanyak gula) ke yang paling encer.",
            "",
            "Hasil: Terbentuk lima lapisan warna yang tidak tercampur. Lapisan terbawah adalah ungu (gula terbanyak), teratas adalah merah (tanpa gula).",
            "",
            "Simpulan: Semakin banyak gula yang dilarutkan, semakin besar massa jenis larutan. Larutan dengan massa jenis lebih besar berada di lapisan bawah, sehingga terbentuk efek pelangi.",
          ],
        },
        {
          judul: "4. Kaidah Kebahasaan Teks Laporan Percobaan",
          isi: [
            "Teks laporan percobaan memiliki ciri kebahasaan yang khas. Memahami kaidah ini penting agar laporan yang ditulis sesuai dengan konvensi ilmiah.",
            "",
            "1. Istilah Teknis (Terminologi)",
            "• Penggunaan kata-kata khusus yang berkaitan dengan bidang ilmu percobaan",
            "• Contoh: variabel, hipotesis, indikator, konsentrasi, pH, suhu, kalibrasi, kontrol",
            "• Istilah teknis membuat laporan lebih tepat dan profesional",
            "• Istilah yang digunakan harus sesuai dengan Kamus Besar Bahasa Indonesia (KBBI) atau konvensi ilmiah",
            "",
            "2. Kalimat Pasif",
            "• Kalimat yang subjeknya dikenai tindakan, bukan melakukan tindakan",
            "• Contoh: \"Larutan diaduk hingga rata\" (bukan \"Kami mengaduk larutan\")",
            "• Kalimat pasif lebih sering digunakan dalam laporan percobaan karena menekankan pada proses dan hasil, bukan pada pelaku",
            "• Pola umum: di- + kata kerja dasar + -kan/-i",
            "• Contoh: disiapkan, ditambahkan, diukur, diamati, dicatat",
            "",
            "3. Konjungsi (Kata Hubung)",
            "• Konjungsi temporal: kemudian, selanjutnya, setelah itu, lalu, akhirnya — menunjukkan urutan langkah",
            "• Konjungsi kausal: karena, sebab, sehingga, oleh karena itu — menunjukkan hubungan sebab-akibat",
            "• Konjungsi koordinatif: dan, serta — untuk merangkaikan informasi setara",
            "• Contoh: \"Larutan dipanaskan hingga 70°C, kemudian ditambahkan indikator sebanyak 3 tetes. Larutan berubah warna menjadi merah karena sifat asamnya.\"",
            "",
            "4. Kata Kerja Material dan Relasional",
            "• Kata kerja material: kata kerja yang menunjukkan tindakan fisik — mencampur, memanaskan, mengukur, mengamati",
            "• Kata kerja relasional: kata kerja yang menunjukkan hubungan — adalah, merupakan, terdiri atas, disebut",
            "• Contoh: \"Langkah pertama adalah menyiapkan alat dan bahan.\" (relasional)",
            "",
            "5. Menggunakan Data Angka dan Istilah Satuan",
            "• Data kuantitatif disertai satuan yang tepat",
            "• Contoh: 50 mL, 100°C, 5 gram, pH 7, 3 menit",
            "• Konsistensi satuan penting untuk keakuratan laporan",
            "",
            "PENTING: Dalam laporan percobaan, hindari kalimat aktif dengan subjek 'saya' atau 'kami' di bagian prosedur. Gunakan kalimat pasif untuk menjaga objektivitas.",
          ],
          rangkuman: [
            "Rumus kebahasaan laporan percobaan: PIKIR — Pasif, Istilah teknis, Konjungsi, Istilah angka/satuan, Relasional",
            "",
            "P = Pasif (larutan dipanaskan, bukan kami memanaskan)",
            "I = Istilah teknis (variabel, konsentrasi, indikator)",
            "K = Konjungsi (kemudian, setelah itu, karena, sehingga)",
            "I = Istilah angka & satuan (50 mL, 100°C, 5 gram)",
            "R = Relasional (adalah, merupakan, disebut)",
          ],
        },
        {
          judul: "5. Data dan Fakta dalam Laporan Percobaan",
          isi: [
            "Data merupakan inti dari teks laporan percobaan. Tanpa data yang akurat, laporan percobaan kehilangan nilai ilmiahnya. Oleh karena itu, pengumpulan, pencatatan, dan penyajian data harus dilakukan dengan cermat.",
            "",
            "A. Jenis Data",
            "",
            "1. Data Kuantitatif",
            "• Data yang berupa angka dan dapat diukur",
            "• Contoh: suhu 80°C, volume 50 mL, waktu 3 menit, pH 5",
            "• Data kuantitatif lebih objektif dan mudah dianalisis",
            "• Disajikan dalam bentuk tabel atau grafik untuk memudahkan pembacaan",
            "",
            "2. Data Kualitatif",
            "• Data yang berupa deskripsi, sifat, atau keadaan",
            "• Contoh: larutan berwarna biru, tekstur licin, bau menyengat",
            "• Data kualitatif melengkapi data kuantitatif",
            "• Meskipun deskriptif, data ini tetap harus objektif",
            "",
            "B. Cara Menyajikan Data",
            "",
            "1. Tabel",
            "• Digunakan untuk menyajikan data angka secara terstruktur",
            "• Dilengkapi judul kolom dan satuan yang jelas",
            "• Contoh: tabel hubungan suhu dan waktu pemanasan",
            "",
            "2. Grafik atau Diagram",
            "• Membantu visualisasi data agar lebih mudah dipahami",
            "• Grafik batang untuk perbandingan, grafik garis untuk tren",
            "• Sumbu X dan Y diberi label yang jelas",
            "",
            "3. Deskripsi Naratif",
            "• Uraian tertulis tentang hasil pengamatan",
            "• Digunakan untuk data kualitatif",
            "• Ditulis secara objektif dan rinci",
            "",
            "C. Prinsip Data yang Baik",
            "• Akurat: sesuai dengan hasil pengukuran yang sebenarnya",
            "• Lengkap: mencakup semua aspek yang diamati",
            "• Reproduksibel: percobaan yang sama menghasilkan data yang sama",
            "• Jujur: data disajikan apa adanya, meskipun tidak sesuai hipotesis",
            "",
            "PENTING: Jangan pernah memanipulasi data percobaan. Data yang tidak sesuai hipotesis bukanlah kegagalan, melainkan temuan yang tetap berharga untuk dipelajari.",
          ],
          contoh: [
            "Contoh penyajian data dalam tabel:",
            "",
            "| Menit ke- | Suhu (°C) | Kondisi Gula |",
            "|-----------|-----------|--------------|",
            "| 0         | 28        | Mulai dimasukkan |",
            "| 1         | 28        | Mulai larut |",
            "| 2         | 35        | Setengah larut |",
            "| 3         | 50        | Hampir seluruhnya larut |",
            "| 4         | 65        | Larut sempurna |",
            "| 5         | 80        | Larut sempurna |",
            "",
            "Data di atas menggabungkan data kuantitatif (suhu, waktu) dan kualitatif (kondisi gula). Tabel seperti ini memudahkan pembaca melihat hubungan antara suhu dan proses pelarutan.",
          ],
        },
        {
          judul: "6. Membedakan Laporan Percobaan dengan Teks Prosedur",
          isi: [
            "Siswa sering kali kesulitan membedakan teks laporan percobaan dengan teks prosedur. Keduanya memang memiliki kemiripan karena sama-sama menjelaskan langkah-langkah. Namun, terdapat perbedaan mendasar yang perlu dipahami.",
            "",
            "A. Persamaan",
            "• Keduanya menyajikan langkah-langkah secara sistematis",
            "• Keduanya menggunakan kalimat imperatif atau pasif",
            "• Keduanya membutuhkan urutan yang logis",
            "• Keduanya bertujuan memandu pembaca melakukan sesuatu",
            "",
            "B. Perbedaan Mendasar",
            "",
            "| Aspek | Laporan Percobaan | Teks Prosedur |",
            "|-------|-------------------|---------------|",
            "| Tujuan | Melaporkan hasil percobaan | Memberi petunjuk melakukan sesuatu |",
            "| Fokus | Pada hasil dan analisis data | Pada cara/langkah yang benar |",
            "| Struktur | Judul, tujuan, alat/bahan, langkah, hasil, simpulan | Tujuan, alat/bahan, langkah (tidak ada simpulan) |",
            "| Data | Harus menyertakan data hasil | Tidak perlu data |",
            "| Simpulan | Ada simpulan | Tidak ada simpulan |",
            "| Sifat | Informatif dan analitis | Instruktif dan prosedural |",
            "| Contoh | Laporan praktikum pengaruh pupuk | Resep masakan, cara menggunakan mesin cuci |",
            "",
            "C. Contoh Kasus",
            "• Teks Prosedur: \"Cara Membuat Kopi\" — berisi langkah menyeduh kopi, tidak perlu melaporkan hasil rasa atau suhu",
            "• Laporan Percobaan: \"Pengaruh Suhu Air terhadap Kualitas Seduhan Kopi\" — berisi langkah, data suhu, hasil rasa/warna, dan simpulan",
            "",
            "PENTING: Jika sebuah teks hanya berisi langkah-langkah tanpa data hasil dan simpulan, itu adalah teks prosedur. Jika ada bagian hasil, analisis data, dan simpulan, itu adalah laporan percobaan.",
          ],
          contoh: [
            "Perbandingan konkret Teks Prosedur vs Laporan Percobaan dengan tema yang sama — 'Kecambah Kacang Hijau':",
            "",
            "TEKS PROSEDUR: Cara Menanam Kecambah Kacang Hijau",
            "1. Rendam kacang hijau dalam air selama 8 jam.",
            "2. Siapkan wadah berlubang dan lapisi dengan kain basah.",
            "3. Taburkan kacang hijau di atas kain.",
            "4. Tutup dengan kain basah dan simpan di tempat gelap.",
            "5. Siram setiap pagi dan sore.",
            "6. Panen setelah 3-4 hari.",
            "→ Tujuan: memberi petunjuk menanam. Tidak ada data/simpulan.",
            "",
            "LAPORAN PERCOBAAN: Pengaruh Cahaya terhadap Pertumbuhan Kecambah Kacang Hijau",
            "Judul: Pengaruh Cahaya terhadap Pertumbuhan Kecambah Kacang Hijau",
            "Tujuan: Mengetahui pengaruh cahaya matahari terhadap pertumbuhan kecambah.",
            "Alat/Bahan: 10 biji kacang hijau, 2 wadah, kapas, air.",
            "Langkah: (sama seperti prosedur, tetapi dengan variabel — 1 wadah di tempat terang, 1 di tempat gelap)",
            "Hasil: Kecambah di tempat gelap lebih tinggi namun berwarna pucat. Kecambah di tempat terang lebih pendek namun berwarna hijau segar.",
            "Simpulan: Cahaya memengaruhi pertumbuhan kecambah. Tanpa cahaya, kecambah tumbuh lebih tinggi (etiolasi) tetapi tidak sehat.",
            "→ Tujuan: melaporkan hasil dan menarik simpulan.",
          ],
        },
        {
          judul: "7. Prosedur Menulis Laporan Percobaan",
          isi: [
            "Setelah memahami seluruh aspek teks laporan percobaan, saatnya berlatih menulis. Ikuti langkah-langkah berikut untuk menghasilkan laporan percobaan yang baik dan sistematis.",
            "",
            "Langkah 1: Tentukan Topik dan Rumuskan Tujuan",
            "• Pilih topik percobaan yang menarik dan dapat dilakukan",
            "• Rumuskan tujuan secara spesifik dan terukur",
            "• Contoh topik: \"Uji Kandungan Boraks pada Makanan\"",
            "  Tujuan: \"Mengidentifikasi kandungan boraks pada beberapa sampel makanan jajanan.\"",
            "",
            "Langkah 2: Siapkan Alat dan Bahan",
            "• Catat semua alat dan bahan yang diperlukan",
            "• Tentukan jumlah/takaran yang tepat",
            "• Pastikan alat dan bahan tersedia sebelum memulai",
            "",
            "Langkah 3: Lakukan Percobaan dan Catat Data",
            "• Ikuti prosedur yang telah dirancang secara cermat",
            "• Catat semua data dan pengamatan langsung saat percobaan berlangsung",
            "• Jangan mengandalkan ingatan — selalu catat segera",
            "• Ulangi percobaan jika perlu untuk memastikan keakuratan",
            "",
            "Langkah 4: Olah dan Sajikan Data",
            "• Kelompokkan data yang terkumpul",
            "• Sajikan dalam bentuk tabel, grafik, atau narasi",
            "• Pastikan penyajian data jelas dan mudah dipahami",
            "",
            "Langkah 5: Analisis dan Tarik Simpulan",
            "• Analisis data dengan menghubungkannya dengan tujuan percobaan",
            "• Tarik simpulan yang menjawab tujuan",
            "• Jika hasil tidak sesuai dugaan, jelaskan kemungkinan penyebabnya",
            "",
            "Langkah 6: Tulis Laporan Lengkap",
            "• Susun laporan sesuai struktur baku",
            "• Gunakan bahasa ilmiah yang jelas dan tepat",
            "• Perhatikan kaidah kebahasaan: kalimat pasif, istilah teknis, konjungsi",
            "",
            "Langkah 7: Revisi dan Edit",
            "• Periksa kembali kelengkapan struktur",
            "• Perbaiki ejaan, tanda baca, dan pilihan kata",
            "• Pastikan data dan simpulan konsisten",
            "• Minta teman atau guru membaca untuk memberi masukan",
            "",
            "Langkah 8: Sajikan dengan Rapi",
            "• Gunakan format yang rapi dan konsisten",
            "• Tambahkan dokumentasi foto percobaan jika perlu",
            "• Susun daftar pustaka jika menggunakan referensi",
          ],
          rangkuman: [
            "Rumus menulis laporan percobaan: TEMA → SIAP → LAKUKAN → OLAH → SIMPULKAN → TULIS → EDIT → SAJIKAN",
            "",
            "Tips sukses: Mulailah dengan percobaan sederhana yang bisa dilakukan di rumah atau di sekolah. Semakin sering berlatih menulis laporan, semakin terampil kamu menyusunnya secara sistematis dan ilmiah.",
          ],
        },
      ],
    },
    latihan: [
      {
        id: 1,
        soal: "Teks laporan percobaan disusun berdasarkan...",
        opsi: ["Opini penulis", "Hasil percobaan yang dilakukan", "Ramalan masa depan", "Cerita fiksi ilmiah"],
        jawaban: 1,
        penjelasan: "Teks laporan percobaan disusun berdasarkan hasil percobaan atau eksperimen yang dilakukan secara nyata, bukan opini atau fiksi.",
      },
      {
        id: 2,
        soal: "Berikut ini yang termasuk data kuantitatif dalam laporan percobaan adalah...",
        opsi: ["Larutan berubah warna menjadi biru", "Suhu air mencapai 85°C", "Bau yang dihasilkan menyengat", "Tekstur bahan terasa licin"],
        jawaban: 1,
        penjelasan: "Data kuantitatif adalah data yang berupa angka dan dapat diukur. Suhu 85°C adalah data kuantitatif, sedangkan warna, bau, dan tekstur adalah data kualitatif.",
      },
      {
        id: 3,
        tipe: "BENAR_SALAH",
        soal: "Bagian struktur teks laporan percobaan yang berisi jawaban dari tujuan percobaan adalah simpulan.",
        opsi: ["Benar", "Salah"],
        jawaban: 0,
        penjelasan: "Simpulan berisi interpretasi data yang menjawab tujuan percobaan. Simpulan ditarik berdasarkan hasil yang telah diperoleh.",
      },
      {
        id: 4,
        soal: "Kalimat 'Larutan dipanaskan hingga suhu 80°C' menggunakan kaidah kebahasaan...",
        opsi: ["Kalimat aktif", "Kalimat pasif", "Kalimat imperatif", "Kalimat tanya"],
        jawaban: 1,
        penjelasan: "Kalimat 'dipanaskan' menggunakan awalan di- yang merupakan ciri kalimat pasif. Subjek (larutan) dikenai tindakan memanaskan.",
      },
      {
        id: 5,
        soal: "Perbedaan utama teks laporan percobaan dengan teks prosedur adalah...",
        opsi: ["Jumlah langkah yang disajikan", "Keberadaan data hasil dan simpulan", "Alat dan bahan yang digunakan", "Panjang teks"],
        jawaban: 1,
        penjelasan: "Teks laporan percobaan memiliki data hasil dan simpulan, sedangkan teks prosedur hanya berisi langkah-langkah tanpa data dan simpulan.",
      },
      {
        id: 6,
        soal: "Contoh konjungsi kausal yang tepat dalam laporan percobaan adalah...",
        opsi: ["Kemudian, selanjutnya", "Karena, sehingga", "Dan, atau", "Akan tetapi, namun"],
        jawaban: 1,
        penjelasan: "Konjungsi kausal menunjukkan hubungan sebab-akibat. Kata 'karena' (sebab) dan 'sehingga' (akibat) termasuk konjungsi kausal.",
      },
      {
        id: 7,
        tipe: "ISIAN",
        soal: "Kata 'konsentrasi', 'variabel', 'indikator' termasuk ke dalam kategori istilah apa?",
        opsi: ["istilah teknis"],
        jawaban: "0",
        penjelasan: "Kata-kata tersebut adalah istilah teknis (terminologi) yang lazim digunakan dalam laporan percobaan ilmiah.",
      },
      {
        id: 8,
        soal: "Bagian laporan percobaan yang menyajikan data dalam bentuk tabel atau grafik adalah...",
        opsi: ["Tujuan", "Alat dan bahan", "Hasil", "Simpulan"],
        jawaban: "2",
        penjelasan: "Hasil percobaan menyajikan data yang diperoleh selama percobaan. Data dapat disajikan dalam bentuk tabel, grafik, atau deskripsi naratif.",
      },
      {
        id: 9,
        tipe: "BENAR_SALAH",
        soal: "Teks laporan percobaan yang baik bersifat objektif berdasarkan data dan fakta.",
        opsi: ["Benar", "Salah"],
        jawaban: 0,
        penjelasan: "Teks laporan percobaan harus bersifat objektif, yaitu berdasarkan data dan fakta hasil percobaan, bukan opini atau perasaan pribadi.",
      },
      {
        id: 10,
        soal: "Dalam laporan percobaan 'Pengaruh Cahaya terhadap Pertumbuhan Kecambah', simpulan yang tepat adalah...",
        opsi: ["Kecambah sebaiknya diletakkan di tempat terang saja", "Cahaya memengaruhi pertumbuhan kecambah; tanpa cahaya terjadi etiolasi", "Menanam kecambah itu mudah dan menyenangkan", "Semua tanaman membutuhkan cahaya untuk tumbuh"],
        jawaban: 1,
        penjelasan: "Simpulan harus menjawab tujuan dan didasarkan pada data. Simpulan yang tepat menyatakan hubungan antara cahaya dan pertumbuhan kecambah sesuai hasil percobaan.",
      },
    ],
    praktik: {
      tujuan: "Menyusun teks laporan percobaan secara lengkap dan sistematis berdasarkan percobaan sederhana yang dilakukan.",
      instruksi: "Lakukan percobaan sederhana di rumah atau di sekolah bersama kelompok. Catat seluruh proses dan hasilnya, kemudian susunlah laporan percobaan yang lengkap dengan struktur baku: judul, tujuan, alat/bahan, langkah, hasil, dan simpulan.",
      langkah: [
        "Pilih satu percobaan sederhana yang dapat dilakukan di rumah (contoh: uji vitamin C pada buah, membuat pelangi dalam gelas, menanam kecambah dengan dua perlakuan berbeda).",
        "Rumuskan judul dan tujuan percobaan secara jelas dan spesifik. Pastikan judul mencerminkan isi percobaan.",
        "Siapkan alat dan bahan yang diperlukan. Catat semua alat dan bahan lengkap dengan jumlah/takarannya.",
        "Lakukan percobaan sesuai langkah yang telah dirancang. Catat setiap pengamatan dan data yang diperoleh secara langsung.",
        "Kelompokkan data yang terkumpul. Sajikan data dalam bentuk tabel atau grafik agar mudah dipahami.",
        "Analisis data dengan menghubungkannya dengan tujuan percobaan. Apa yang dapat kamu simpulkan dari data tersebut?",
        "Tulis laporan percobaan lengkap dengan struktur baku. Gunakan kalimat pasif, istilah teknis, dan konjungsi yang tepat.",
        "Periksa kembali laporan: kelengkapan struktur, ejaan, tanda baca, konsistensi data dan simpulan. Kumpulkan dalam format yang rapi.",
      ],
      tips: [
        "Pilih percobaan yang sederhana namun menarik agar laporanmu memiliki nilai informasi yang baik.",
        "Gunakan tabel untuk menyajikan data kuantitatif dan deskripsi untuk data kualitatif.",
        "Jangan lupa mencantumkan satuan pada setiap data angka, misalnya mL, gram, °C, menit.",
        "Pastikan simpulan benar-benar menjawab tujuan percobaan, bukan sekadar mengulang hasil.",
        "Gunakan kalimat pasif di bagian langkah dan hasil, misalnya 'Larutan diaduk hingga rata' bukan 'Kami mengaduk larutan'.",
      ],
      contoh: "Lihat contoh analisis struktur laporan percobaan 'Membuat Pelangi dalam Gelas' pada materi Struktur Teks Laporan Percobaan di atas sebagai panduan menulis laporan.",
    },
    kuis: [
      {
        id: 1,
        soal: "Manakah pernyataan yang paling tepat tentang teks laporan percobaan?",
        opsi: [
          "Teks yang berisi langkah melakukan sesuatu tanpa data hasil",
          "Teks yang melaporkan hasil percobaan secara objektif dan sistematis",
          "Teks yang menceritakan pengalaman pribadi di laboratorium",
          "Teks yang berisi hipotesis tanpa perlu melakukan percobaan",
        ],
        jawaban: 1,
        penjelasan: "Teks laporan percobaan adalah teks yang melaporkan hasil percobaan secara objektif, sistematis, dan berdasarkan data faktual.",
      },
      {
        id: 2,
        soal: "Seorang siswa melakukan percobaan tetapi hasilnya tidak sesuai hipotesis. Sikap yang tepat dalam menulis laporan adalah...",
        opsi: [
          "Memalsukan data agar sesuai hipotesis",
          "Tidak menuliskan hasil percobaan tersebut",
          "Tetap menuliskan hasil apa adanya dan menganalisis kemungkinan penyebabnya",
          "Mengulang percobaan terus-menerus sampai hasilnya sesuai",
        ],
        jawaban: 2,
        penjelasan: "Sikap ilmiah yang benar adalah jujur dalam melaporkan data. Hasil yang tidak sesuai hipotesis tetap berharga dan perlu dianalisis penyebabnya.",
      },
      {
        id: 3,
        soal: "Cermati kalimat berikut: 'Air dipanaskan hingga mendidih, kemudian gula dimasukkan sedikit demi sedikit.' Kaidah kebahasaan yang menonjol dalam kalimat tersebut adalah...",
        opsi: [
          "Istilah teknis dan konjungsi temporal",
          "Kalimat pasif dan konjungsi temporal",
          "Kalimat aktif dan kata kerja material",
          "Kata sifat dan konjungsi kausal",
        ],
        jawaban: 1,
        penjelasan: "Kalimat tersebut menggunakan kalimat pasif ('dipanaskan', 'dimasukkan') dan konjungsi temporal ('kemudian').",
      },
      {
        id: 4,
        soal: "Jika tujuan percobaan adalah 'Menguji pengaruh suhu terhadap kelarutan gula', simpulan yang tepat adalah...",
        opsi: [
          "Gula adalah bahan pemanis yang larut dalam air",
          "Semakin tinggi suhu air, semakin cepat gula larut",
          "Air panas lebih enak daripada air dingin",
          "Gula larut lebih baik jika diaduk dengan cepat",
        ],
        jawaban: 1,
        penjelasan: "Simpulan harus menjawab tujuan percobaan, yaitu hubungan antara suhu (variabel bebas) dan kelarutan gula (variabel terikat).",
      },
      {
        id: 5,
        soal: "Perbedaan mendasar antara data kuantitatif dan kualitatif dalam laporan percobaan adalah...",
        opsi: [
          "Data kuantitatif berupa angka, data kualitatif berupa deskripsi",
          "Data kuantitatif lebih penting daripada data kualitatif",
          "Data kualitatif tidak perlu dicantumkan dalam laporan",
          "Data kuantitatif hanya digunakan dalam percobaan kimia",
        ],
        jawaban: 0,
        penjelasan: "Data kuantitatif adalah data yang berupa angka dan dapat diukur (misal: suhu, volume). Data kualitatif adalah data deskriptif (misal: warna, bau). Keduanya sama-sama penting.",
      },
      {
        id: 6,
        tipe: "BENAR_SALAH",
        soal: "Persamaan utama teks prosedur dan laporan percobaan adalah sama-sama menyajikan langkah-langkah secara sistematis.",
        opsi: ["Benar", "Salah"],
        jawaban: 0,
        penjelasan: "Persamaan utama antara teks prosedur dan laporan percobaan adalah sama-sama menyajikan langkah-langkah secara sistematis dan urut.",
      },
      {
        id: 7,
        soal: "Seorang siswa menulis: 'Setelah ditambahkan 5 mL HCl 0,1 M, larutan berubah menjadi merah.' Ini adalah contoh...",
        opsi: [
          "Simpulan percobaan",
          "Data hasil percobaan",
          "Tujuan percobaan",
          "Hipotesis percobaan",
        ],
        jawaban: 1,
        penjelasan: "Kalimat tersebut mencatat apa yang terjadi setelah suatu tindakan dilakukan pada percobaan. Ini adalah data hasil percobaan, bukan simpulan atau tujuan.",
      },
      {
        id: 8,
        tipe: "BENAR_SALAH",
        soal: "Teks laporan percobaan cenderung menggunakan kalimat pasif karena kalimat pasif menekankan proses dan hasil, bukan pelaku.",
        opsi: ["Benar", "Salah"],
        jawaban: 0,
        penjelasan: "Kalimat pasif digunakan untuk menekankan pada proses dan hasil percobaan, bukan pada siapa yang melakukan. Ini menjaga objektivitas laporan.",
      },
      {
        id: 9,
        soal: "Jika dalam laporan percobaan tidak ada bagian simpulan, maka teks tersebut lebih tepat disebut...",
        opsi: [
          "Laporan percobaan yang tidak lengkap",
          "Teks prosedur",
          "Teks eksposisi",
          "Teks deskripsi",
        ],
        jawaban: 1,
        penjelasan: "Tanpa bagian simpulan, teks tersebut kehilangan salah satu elemen pembeda utama laporan percobaan. Teks yang hanya berisi langkah-langkah tanpa data hasil dan simpulan tergolong teks prosedur.",
      },
      {
        id: 10,
        tipe: "ISIAN",
        soal: "Prinsip dalam metode ilmiah yang menuntut pencatatan alat dan bahan secara rinci agar percobaan dapat diulang disebut...",
        opsi: ["reproduksibilitas"],
        jawaban: "0",
        penjelasan: "Pencatatan alat dan bahan yang rinci memungkinkan percobaan direproduksi (diulang) oleh orang lain dengan hasil yang sama. Ini merupakan prinsip reproduksibilitas dalam metode ilmiah.",
      },
    ],
  };

export default konten;
