// @ts-nocheck
import type { Konten } from "../types";

const kd = "3.3/4.3";

/* =============================================
   Unit 3: Teks Pidato Persuasif — IX S1
   KD 3.3/4.3 — Mengidentifikasi informasi & Menyusun Teks Pidato Persuasif
   ============================================= */
const konten: Konten = {
    belajar: {
      tujuan: [
        "Memahami hakikat, tujuan, dan fungsi pidato persuasif dalam komunikasi publik",
        "Mengidentifikasi struktur teks pidato persuasif meliputi pembukaan, isi, dan penutup",
        "Menganalisis kaidah kebahasaan pidato persuasif: kalimat persuasif, imperatif, dan emotif",
        "Membedakan jenis-jenis pidato berdasarkan tujuannya: informatif, persuasif, dan rekreatif",
        "Menerapkan teknik berpidato yang baik meliputi intonasi, gestur, dan kontak mata",
        "Menyusun naskah pidato persuasif dengan struktur dan kebahasaan yang tepat",
      ],
      materi: [
        {
          judul: "1. Hakikat Pidato Persuasif",
          catatan: "Pidato persuasif adalah seni berbicara di depan umum untuk memengaruhi keyakinan dan tindakan pendengar.",
          isi: [
            "Pidato persuasif adalah bentuk komunikasi lisan yang bertujuan memengaruhi sikap, pendapat, atau perilaku audiens. Pidato ini tidak sekadar menyampaikan informasi, melainkan mengajak pendengar untuk melakukan sesuatu atau mengubah pandangan mereka.",
            "",
            "Ciri-ciri pidato persuasif:",
            "• Bertujuan memengaruhi atau mengajak audiens melakukan sesuatu",
            "• Disampaikan dengan argumen yang logis dan data pendukung",
            "• Menggunakan bahasa yang menarik, emosional, dan menggugah",
            "• Memiliki struktur yang jelas: pembukaan, isi, penutup",
            "• Disampaikan dengan intonasi, gestur, dan ekspresi yang mendukung",
            "• Berisi ajakan, imbauan, atau seruan kepada audiens",
            "",
            "Perbedaan pidato persuasif dengan pidato biasa:",
            "✓ Pidato informatif hanya bertujuan memberi informasi",
            "✓ Pidato persuasif bertujuan memengaruhi dan mengajak bertindak",
            "✓ Pidato persuasif menggunakan lebih banyak kalimat ajakan dan seruan",
            "✓ Pidato persuasif memerlukan argumen yang lebih kuat dan meyakinkan",
            "",
            "PENTING: Pidato persuasif tidak boleh bersifat memaksa atau manipulatif. Ajakan yang disampaikan harus didasari argumen yang logis dan etis, menghormati kebebasan audiens untuk memutuskan.",
            "",
            "Contoh topik pidato persuasif:",
            "• \"Pentingnya Menjaga Kebersihan Lingkungan Sekolah\"",
            "• \"Ayo Berhenti Merokok demi Generasi Sehat\"",
            "• \"Bijak dalam Menggunakan Media Sosial\"",
            "• \"Gerakan Literasi: Membaca Membuka Jendela Dunia\"",
            "• \"Stop Bullying: Wujudkan Sekolah Ramah Anak\"",
          ],
          contoh: [
            "Contoh kalimat pembuka pidato persuasif:",
            "",
            "\"Assalamu'alaikum warahmatullahi wabarakatuh. Yang terhormat Bapak/Ibu guru dan teman-teman yang saya cintai. Marilah kita panjatkan puja dan puji syukur ke hadirat Tuhan Yang Maha Esa karena pada pagi hari ini kita masih diberikan kesehatan untuk berkumpul di acara yang sangat penting ini.\"",
            "",
            "Perhatikan bahwa pembuka ini tidak hanya menyapa, tetapi juga membangun hubungan emosional dengan audiens sebelum masuk ke inti ajakan.",
          ],
        },
        {
          judul: "2. Tujuan dan Fungsi Pidato Persuasif",
          isi: [
            "Pidato persuasif memiliki tujuan dan fungsi yang penting dalam kehidupan bermasyarakat, terutama dalam konteks pendidikan, organisasi, dan kegiatan publik.",
            "",
            "A. Tujuan Pidato Persuasif",
            "• Membentuk opini — memengaruhi cara pandang audiens terhadap suatu isu",
            "• Mengubah sikap — mendorong audiens meninggalkan kebiasaan lama yang negatif",
            "• Mendorong tindakan — menggerakkan audiens untuk melakukan sesuatu yang positif",
            "• Memperkuat keyakinan — meneguhkan nilai-nilai yang sudah dimiliki audiens",
            "• Membangkitkan empati — menyentuh perasaan audiens terhadap suatu masalah sosial",
            "",
            "B. Fungsi Pidato Persuasif",
            "• Fungsi Edukatif: mendidik dan menyadarkan masyarakat akan suatu masalah",
            "• Fungsi Motivasional: membangkitkan semangat dan gairah audiens",
            "• Fungsi Kontrol Sosial: mengkritik atau meluruskan perilaku yang menyimpang",
            "• Fungsi Kampanye: menggalang dukungan untuk program atau gerakan sosial",
            "• Fungsi Rekreatif-Edukatif: menghibur sambil memberikan pesan moral",
            "",
            "Contoh tujuan spesifik:",
            "• \"Setelah mendengar pidato ini, audiens diharapkan bersedia membuang sampah pada tempatnya.\"",
            "• \"Setelah mendengar pidato ini, audiens diharapkan berpartisipasi dalam gerakan literasi sekolah.\"",
            "• \"Setelah mendengar pidato ini, audiens diharapkan tidak lagi melakukan bullying.\"",
            "",
            "PENTING: Setiap pidato persuasif harus memiliki tujuan yang jelas dan terukur. Tanpa tujuan yang spesifik, pidato akan kehilangan arah dan sulit meyakinkan audiens.",
          ],
          contoh: [
            "Perbandingan tujuan pidato berdasarkan jenis:",
            "",
            "| Jenis Pidato | Tujuan Utama | Contoh Topik |",
            "|--------------|--------------|--------------|",
            "| Informatif | Memberi pengetahuan | \"Proses Terjadinya Hujan\" |",
            "| Persuasif | Memengaruhi/mengajak | \"Ayo Menanam Pohon\" |",
            "| Rekreatif | Menghibur | \"Cerita Lucu di Pesantren Kilat\" |",
            "",
            "Dari tabel di atas terlihat bahwa pidato persuasif memiliki dimensi 'ajakan' yang tidak dimiliki oleh jenis pidato lainnya.",
          ],
        },
        {
          judul: "3. Struktur Pidato Persuasif",
          isi: [
            "Struktur teks pidato persuasif terdiri dari tiga bagian utama: pembukaan, isi, dan penutup. Setiap bagian memiliki fungsi dan elemen yang khas.",
            "",
            "1. Pembukaan",
            "  a. Salam pembuka — ucapan hormat kepada audiens",
            "  b. Ucapan syukur — ungkapan terima kasih kepada Tuhan",
            "  c. Sapaan akrab — membangun kedekatan dengan audiens",
            "  d. Latar belakang singkat — pengantar ke topik utama",
            "  e. Pernyataan posisi — sikap pembicara terhadap isu yang dibahas",
            "",
            "  Contoh pembukaan:",
            "  \"Assalamu'alaikum wr. wb. Selamat pagi dan salam sejahtera bagi kita semua. Pertama-tama, marilah kita bersyukur ke hadirat Allah Swt. karena pada hari ini kita dapat berkumpul dalam keadaan sehat. Teman-teman yang saya banggakan, hari ini saya ingin mengajak kita semua untuk merenungkan sebuah masalah yang sangat dekat dengan kehidupan kita sehari-hari, yaitu sampah plastik.\"",
            "",
            "2. Isi (Inti Pidato)",
            "  a. Pernyataan argumen — gagasan utama yang ingin disampaikan",
            "  b. Alasan dan bukti — data, fakta, atau contoh yang mendukung argumen",
            "  c. Penguatan emosional — kalimat yang menyentuh perasaan audiens",
            "  d. Ajakan — seruan konkret untuk melakukan sesuatu",
            "  e. Antisipasi sanggahan — jawaban atas kemungkinan keberatan audiens",
            "",
            "  Isi pidato merupakan bagian terpanjang dan terpenting. Di sinilah pembicara membangun argumen secara bertahap dan meyakinkan.",
            "",
            "3. Penutup",
            "  a. Simpulan — ringkasan poin-poin penting",
            "  b. Ajakan final — seruan terakhir yang kuat dan mengesankan",
            "  c. Harapan — ungkapan optimisme terhadap perubahan yang diinginkan",
            "  d. Permohonan maaf — jika ada kesalahan selama berpidato",
            "  e. Salam penutup — ucapan hormat di akhir pidato",
            "",
            "  Contoh penutup:",
            "  \"Demikianlah pidato singkat dari saya. Mari kita mulai dari hal kecil: bawa botol minum sendiri, kurangi penggunaan plastik sekali pakai. Ingatlah, bumi bukan warisan dari nenek moyang kita, melainkan titipan dari anak cucu kita. Akhir kata, kurang lebihnya mohon maaf. Wassalamu'alaikum wr. wb.\"",
            "",
            "Tips Menyusun Struktur: Buatlah kerangka pidato terlebih dahulu. Tentukan poin-poin utama di bagian isi, baru kembangkan menjadi paragraf utuh. Pastikan setiap bagian mengalir secara logis.",
          ],
          contoh: [
            "Contoh kerangka pidato persuasif \"Ayo Bijak Bermedia Sosial\":",
            "",
            "PEMBUKAAN:",
            "- Salam hormat dan ucapan syukur",
            "- Pengantar: Media sosial sudah menjadi bagian tak terpisahkan dari hidup kita",
            "- Posisi: Saya yakin kita semua bisa menggunakan media sosial secara lebih bijak",
            "",
            "ISI:",
            "- Argumen 1: Dampak negatif media sosial (cyberbullying, hoaks, kecanduan)",
            "- Bukti: Data pengguna media sosial di Indonesia, kasus bullying online",
            "- Argumen 2: Manfaat media sosial jika digunakan dengan bijak",
            "- Bukti: Contoh gerakan positif di media sosial",
            "- Ajakan: 1) Pikir sebelum posting, 2) Verifikasi berita, 3) Batasi waktu scrolling",
            "",
            "PENUTUP:",
            "- Simpulan: Media sosial adalah pisau bermata dua",
            "- Ajakan final: Jadilah generasi yang cerdas bermedsos!",
            "- Permohonan maaf dan salam penutup",
          ],
        },
        {
          judul: "4. Kaidah Kebahasaan Pidato Persuasif",
          isi: [
            "Pidato persuasif memiliki ciri kebahasaan yang khas yang membedakannya dari jenis teks lainnya. Kaidah ini berfungsi untuk membujuk, memengaruhi, dan menggerakkan audiens.",
            "",
            "1. Kalimat Persuasif (Ajakan)",
            "• Kalimat yang berisi bujukan halus untuk melakukan sesuatu",
            "• Ciri: menggunakan kata ajakan seperti mari, ayo, marilah, hendaknya, sebaiknya",
            "• Contoh: \"Marilah kita jaga kebersihan lingkungan sekolah.\"",
            "• Contoh: \"Hendaknya kita mulai mengurangi penggunaan plastik sekali pakai.\"",
            "",
            "2. Kalimat Imperatif (Perintah)",
            "• Kalimat yang berisi perintah atau larangan",
            "• Dibedakan menjadi imperatif halus dan imperatif keras",
            "• Imperatif halus: \"Cobalah bayangkan...\" \"Janganlah kita...\"",
            "• Imperatif keras: \"Berhenti merokok!\" \"Buang sampah pada tempatnya!\"",
            "• Dalam pidato persuasif, imperatif keras digunakan di bagian ajakan final",
            "",
            "3. Kalimat Emotif",
            "• Kalimat yang menyentuh perasaan dan emosi audiens",
            "• Menggunakan kata-kata bermuatan emosi: prihatin, bangga, sedih, haru, iba",
            "• Contoh: \"Sungguh memprihatinkan, masih banyak anak seusia kita yang putus sekolah.\"",
            "• Contoh: \"Betapa bangganya kita memiliki budaya gotong royong yang luhur.\"",
            "",
            "4. Kata Ganti (Pronomina) yang Tepat",
            "• Penggunaan 'kita' untuk membangun rasa kebersamaan",
            "• Penggunaan 'Anda' atau 'Bapak/Ibu/Saudara' untuk menghormati audiens",
            "• Contoh: \"Kita semua tentu sepakat bahwa pendidikan adalah kunci masa depan.\"",
            "",
            "5. Konjungsi Argumentatif",
            "• Kata hubung yang memperkuat argumen: karena, oleh karena itu, dengan demikian, sebab",
            "• Contoh: \"Oleh karena itu, kita harus segera bertindak.\"",
            "",
            "6. Kata Seru (Interjeksi)",
            "• Ungkapan perasaan: aduh, wah, oh, ayo, nah",
            "• Contoh: \"Wah, betapa indahnya negeri kita jika bersih dari sampah!\"",
            "",
            "7. Pernyataan Retoris",
            "• Pertanyaan yang tidak memerlukan jawaban, hanya untuk efek dramatis",
            "• Contoh: \"Bukankah kita semua menginginkan masa depan yang cerah?\"",
            "",
            "PENTING: Penggunaan kaidah kebahasaan harus disesuaikan dengan konteks audiens. Pidato untuk siswa SMP tentu berbeda gaya bahasanya dengan pidato untuk guru atau pejabat.",
          ],
          rangkuman: [
            "Rumus PESAN-KI untuk kaidah kebahasaan pidato persuasif:",
            "P = Persuasif (kalimat ajakan: mari, ayo, marilah)",
            "E = Emotif (kata bermuatan emosi: prihatin, bangga, sedih)",
            "S = Seru (interjeksi: wah, nah, oh)",
            "A = Argumentatif (konjungsi: karena, oleh karena itu)",
            "N = Nada (intonasi yang mendukung pesan)",
            "K = Kata ganti (kita, Anda, Saudara)",
            "I = Imperatif (perintah halus/keras)",
            "",
            "Gunakan rumus PESAN-KI saat menulis naskah pidato persuasif untuk memastikan semua kaidah kebahasaan terpenuhi.",
          ],
        },
        {
          judul: "5. Jenis-Jenis Pidato Berdasarkan Tujuan",
          isi: [
            "Berdasarkan tujuannya, pidato diklasifikasikan menjadi tiga jenis utama. Memahami perbedaan ini penting agar kita dapat menyusun pidato yang sesuai dengan maksud dan audiens.",
            "",
            "A. Pidato Informatif",
            "• Tujuan: menyampaikan informasi, pengetahuan, atau penjelasan kepada audiens",
            "• Fokus pada fakta, data, dan penjelasan yang objektif",
            "• Tidak bertujuan mengubah sikap atau mengajak melakukan sesuatu",
            "• Contoh: pidato tentang sejarah proklamasi, laporan kegiatan, penjelasan materi pelajaran",
            "• Ciri bahasa: lugas, jelas, menggunakan istilah teknis jika diperlukan",
            "",
            "B. Pidato Persuasif",
            "• Tujuan: memengaruhi sikap, opini, atau tindakan audiens",
            "• Menggabungkan fakta dan pendapat yang didukung argumen logis",
            "• Mengandung ajakan atau imbauan yang eksplisit",
            "• Contoh: pidato kampanye, pidato gerakan sosial, pidato literasi",
            "• Ciri bahasa: menggunaan kalimat ajakan, emotif, dan retoris",
            "",
            "C. Pidato Rekreatif (Hiburan)",
            "• Tujuan: menghibur audiens sambil menyampaikan pesan ringan",
            "• Sering disampaikan dalam acara santai, perpisahan, atau perayaan",
            "• Mengandung humor, anekdot, atau cerita lucu",
            "• Contoh: pidato perpisahan sekolah, sambutan acara pensi, ceramah santai",
            "• Ciri bahasa: ringan, komunikatif, tidak terlalu formal, banyak humor",
            "",
            "Tips Membedakan: Tanyakan pada diri sendiri — 'Apa yang saya harapkan terjadi pada audiens setelah pidato ini?' Jika jawabannya 'tahu sesuatu' → informatif, 'melakukan sesuatu' → persuasif, 'merasa terhibur' → rekreatif.",
          ],
          contoh: [
            "Contoh kalimat khas setiap jenis pidato:",
            "",
            "INFORMATIF: \"Tahukah Anda bahwa Indonesia menempati peringkat kedua sebagai negara penyumbang sampah plastik di laut? Data dari Kementerian Lingkungan Hidup menunjukkan bahwa setiap tahunnya...\"",
            "",
            "PERSUASIF: \"Berdasarkan data yang memprihatinkan tersebut, marilah kita mulai mengurangi penggunaan plastik sekali pakai. Mulailah dari diri sendiri, dari hal kecil, dan dari sekarang!\"",
            "",
            "REKREATIF: \"Teman-teman, ada cerita lucu tentang seorang bapak yang sangat hemat. Ia tidak mau membeli sampah plastik, jadi ketika membeli gorengan, sampainya dimakan juga!\"",
          ],
        },
        {
          judul: "6. Teknik Berpidato yang Efektif",
          isi: [
            "Pidato yang baik tidak hanya bergantung pada isi naskah, tetapi juga pada cara penyampaiannya. Teknik berpidato yang efektif membantu pesan sampai dengan jelas dan berkesan.",
            "",
            "1. Intonasi (Nada Bicara)",
            "• Variasi tinggi-rendah, cepat-lambat, dan keras-lembut suara",
            "• Intonasi naik: untuk pertanyaan retoris atau ajakan yang menggugah",
            "• Intonasi turun: untuk pernyataan tegas dan penutup",
            "• Intonasi lambat dan pelan: untuk bagian yang mengharukan atau serius",
            "• Intonasi cepat dan bersemangat: untuk ajakan yang enerjik",
            "• Hindari nada datar (monoton) yang membuat audiens bosan",
            "",
            "2. Gestur (Gerakan Tubuh)",
            "• Gerakan tangan yang wajar untuk menekankan poin penting",
            "• Gestur terbuka (telapak tangan menghadap ke atas) menunjukkan kejujuran",
            "• Gestur tertutup (tangan di dada) menunjukkan kesungguhan",
            "• Gunakan gerakan yang proporsional, jangan berlebihan",
            "• Posisi tubuh tegak, rileks, dan percaya diri",
            "",
            "3. Kontak Mata",
            "• Pandanglah audiens secara merata ke seluruh penjuru ruangan",
            "• Kontak mata 3-5 detik per orang atau per area, lalu pindah",
            "• Jangan terus-menerus melihat naskah atau layar",
            "• Kontak mata membangun kepercayaan dan menunjukkan ketulusan",
            "• Jika gugup, lihat dahi atau hidung audiens",
            "",
            "4. Artikulasi dan Kecepatan Bicara",
            "• Ucapkan kata dengan jelas, jangan terlalu cepat",
            "• Kecepatan ideal: 120-150 kata per menit",
            "• Berhenti sejenak (jeda) di tempat-tempat penting untuk memberi efek dramatis",
            "• Jeda juga berfungsi memberi waktu audiens mencerna informasi",
            "",
            "5. Ekspresi Wajah",
            "• Sesuaikan ekspresi dengan isi pidato: serius, gembira, prihatin",
            "• Senyum yang tulus di awal pidato mencairkan suasana",
            "• Ekspresi wajah yang tepat membuat pidato lebih hidup dan meyakinkan",
            "",
            "Tips Sebelum Berpidato: Latih pidato di depan cermin atau rekam suara sendiri. Evaluasi intonasi, gestur, dan kecepatan bicara. Minta teman memberi masukan. Semakin sering berlatih, semakin percaya diri.",
          ],
          rangkuman: [
            "Rumus PINTAR-G untuk teknik berpidato:",
            "P = Pandangan (kontak mata merata)",
            "I = Intonasi (nada bervariasi, tidak monoton)",
            "N = Nafas (atur napas, jeda di tempat tepat)",
            "T = Tubuh (gestur wajar, posisi tegak percaya diri)",
            "A = Artikulasi (ucap jelas, kecepatan ideal)",
            "R = Raut muka (ekspresi sesuai isi pidato)",
            "G = Gerak (proporsional, tidak berlebihan)",
            "",
            "Latih PINTAR-G setiap kali akan berpidato. Semakin sering berlatih, teknik akan terasa alami dan tidak kaku.",
          ],
        },
        {
          judul: "7. Prosedur Menulis Naskah Pidato Persuasif",
          isi: [
            "Menulis naskah pidato persuasif memerlukan langkah-langkah sistematis agar hasilnya terstruktur, meyakinkan, dan sesuai dengan audiens. Ikuti prosedur berikut:",
            "",
            "Langkah 1: Tentukan Topik dan Tujuan",
            "• Pilih topik yang relevan dengan audiens dan situasi",
            "• Rumuskan tujuan spesifik: apa yang ingin dicapai setelah pidato?",
            "• Contoh topik: \"Pentingnya Membaca Buku di Era Digital\"",
            "",
            "Langkah 2: Kenali Audiens",
            "• Siapa audiensnya? (usia, latar belakang, minat)",
            "• Apa yang sudah mereka ketahui tentang topik?",
            "• Apa kekhawatiran atau keberatan mereka?",
            "• Sesuaikan bahasa dan gaya bicara dengan audiens",
            "",
            "Langkah 3: Kumpulkan Bahan dan Data",
            "• Cari fakta, data, atau contoh yang mendukung argumen",
            "• Gunakan sumber yang terpercaya dan relevan",
            "• Siapkan kutipan dari tokoh terkenal jika perlu",
            "",
            "Langkah 4: Buat Kerangka Pidato",
            "• Tentukan struktur: pembukaan → isi (argumen 1, 2, 3) → penutup",
            "• Tulis poin-poin utama setiap bagian",
            "• Pastikan argumen tersusun secara logis dan berurutan",
            "",
            "Langkah 5: Kembangkan Menjadi Naskah Utuh",
            "• Tulis kalimat pembuka yang menarik perhatian",
            "• Kembangkan setiap argumen dengan data dan contoh",
            "• Sematkan ajakan di bagian isi dan penutup",
            "• Gunakan kaidah kebahasaan pidato persuasif (PESAN-KI)",
            "",
            "Langkah 6: Gunakan Bahasa Tubuh dalam Naskah",
            "• Beri tanda pada naskah untuk jeda, intonasi naik/turun, atau gestur",
            "• Tandai kata-kata yang perlu ditekankan dengan huruf kapital atau garis bawah",
            "• Ini membantu saat latihan dan penyampaian",
            "",
            "Langkah 7: Revisi dan Latihan",
            "• Baca naskah dengan suara keras, rasakan alurnya",
            "• Perbaiki kalimat yang terdengar janggal atau sulit diucapkan",
            "• Latih dengan timer: sesuaikan durasi dengan waktu yang diberikan",
            "• Minta masukan dari teman atau guru",
            "",
            "Langkah 8: Siapkan Catatan Kecil (Mental Note)",
            "• Jangan membaca naskah utuh saat berpidato, gunakan kartu catatan",
            "• Tulis poin-poin kunci di kartu kecil (ukuran 10×15 cm)",
            "• Ini membuat pidato terdengar alami dan tidak seperti pembacaan",
          ],
          rangkuman: [
            "Rumus menulis naskah pidato persuasif: TOPIK → AUDIENS → DATA → KERANGKA → KEMBANGKAN → TANDA → REVISI → CATAT",
            "",
            "Ingat: Naskah yang baik adalah naskah yang terdengar alami saat diucapkan, bukan yang terlihat indah saat dibaca. Tulislah dengan gaya bicara, bukan gaya tulisan.",
            "",
            "Tips: Rekam latihan pidatomu, lalu dengarkan kembali. Perbaiki bagian yang terdengar kurang meyakinkan. Lakukan tiga kali latihan penuh sebelum tampil.",
          ],
        },
      ],
    },
    latihan: [
      {
        id: 1,
        soal: "Berikut ini yang merupakan tujuan utama pidato persuasif adalah...",
        opsi: ["Menghibur audiens dengan cerita lucu", "Menyampaikan informasi secara objektif", "Memengaruhi sikap dan tindakan audiens", "Melaporkan hasil penelitian"],
        jawaban: 2,
        penjelasan: "Tujuan utama pidato persuasif adalah memengaruhi sikap, opini, atau tindakan audiens. Pidato informatif bertujuan menyampaikan informasi, sedangkan rekreatif bertujuan menghibur.",
      },
      {
        id: 2,
        soal: "Susunan struktur teks pidato persuasif yang benar adalah...",
        opsi: ["Isi — Pembukaan — Penutup", "Penutup — Pembukaan — Isi", "Pembukaan — Isi — Penutup", "Pembukaan — Penutup — Isi"],
        jawaban: 2,
        penjelasan: "Struktur teks pidato persuasif terdiri dari pembukaan (salam, sapaan, pengantar), isi (argumen, data, ajakan), dan penutup (simpulan, ajakan final, salam).",
      },
      {
        id: 3,
        tipe: "BENAR_SALAH",
        soal: "Kalimat persuasif bertujuan memengaruhi pembaca atau pendengar.",
        opsi: ["Benar", "Salah"],
        jawaban: 0,
        penjelasan: "Pernyataan tersebut benar. Kalimat persuasif adalah kalimat ajakan yang bertujuan memengaruhi sikap, opini, atau tindakan pembaca/pendengar.",
      },
      {
        id: 4,
        soal: "Berikut yang bukan merupakan kaidah kebahasaan pidato persuasif adalah...",
        opsi: ["Kalimat persuasif dengan kata mari/ayo", "Kalimat imperatif", "Menggunakan istilah teknis ilmiah yang rumit", "Kalimat emotif yang menyentuh perasaan"],
        jawaban: 2,
        penjelasan: "Pidato persuasif sebaiknya menggunakan bahasa yang mudah dipahami audiens. Istilah teknis yang rumit justru menghambat persuasi karena audiens mungkin tidak memahaminya.",
      },
      {
        id: 5,
        tipe: "ISIAN",
        soal: "Pidato yang bertujuan memberikan penjelasan tentang suatu topik tanpa mengajak audiens melakukan sesuatu disebut pidato...",
        opsi: "informatif",
        jawaban: "informatif",
        penjelasan: "Pidato informatif bertujuan menyampaikan informasi, pengetahuan, atau penjelasan secara objektif tanpa bermaksud mengubah sikap atau mengajak audiens.",
      },
      {
        id: 6,
        soal: "Teknik pengaturan tinggi-rendah, cepat-lambat suara saat berpidato disebut...",
        opsi: ["Artikulasi", "Gestur", "Intonasi", "Kontak mata"],
        jawaban: 2,
        penjelasan: "Intonasi adalah variasi nada bicara meliputi tinggi-rendah, cepat-lambat, dan keras-lembut suara. Intonasi yang baik membuat pidato tidak monoton dan lebih meyakinkan.",
      },
      {
        id: 7,
        soal: "Kata \"kita\" dalam pidato persuasif berfungsi untuk...",
        opsi: ["Menggantikan nama pembicara", "Membangun rasa kebersamaan dengan audiens", "Menunjukkan hierarki pembicara", "Mempertegas perbedaan dengan audiens"],
        jawaban: 1,
        penjelasan: "Penggunaan kata 'kita' membangun rasa kebersamaan dan solidaritas antara pembicara dan audiens, sehingga ajakan terasa lebih inklusif dan tidak menggurui.",
      },
      {
        id: 8,
        tipe: "BENAR_SALAH",
        soal: "Kalimat retoris sama dengan kalimat tanya biasa karena sama-sama membutuhkan jawaban.",
        opsi: ["Benar", "Salah"],
        jawaban: 1,
        penjelasan: "Pernyataan tersebut salah. Kalimat retoris adalah pertanyaan yang tidak memerlukan jawaban, berbeda dengan kalimat tanya biasa yang membutuhkan jawaban. Fungsinya untuk efek dramatis dan menguatkan argumen.",
      },
      {
        id: 9,
        soal: "Bagian pidato yang berisi simpulan dan ajakan final terdapat pada...",
        opsi: ["Pembukaan", "Isi argumen pertama", "Isi argumen terakhir", "Penutup"],
        jawaban: 3,
        penjelasan: "Penutup pidato berisi simpulan dari seluruh argumen, ajakan final yang kuat, harapan, permohonan maaf, dan salam penutup.",
      },
      {
        id: 10,
        soal: "Salah satu fungsi pidato persuasif sebagai kontrol sosial adalah...",
        opsi: ["Menghibur audiens di acara perpisahan", "Menyampaikan data penelitian terbaru", "Mengkritik atau meluruskan perilaku yang menyimpang di masyarakat", "Membacakan puisi karya sendiri"],
        jawaban: 2,
        penjelasan: "Fungsi kontrol sosial berarti pidato digunakan untuk mengkritik atau meluruskan perilaku yang menyimpang, seperti pidato anti-narkoba, anti-bullying, atau gerakan hidup bersih.",
      },
    ],
    praktik: {
      tujuan: "Menyusun dan menyampaikan teks pidato persuasif dengan struktur, kaidah kebahasaan, dan teknik penyampaian yang tepat.",
      instruksi: "Pilihlah satu topik persuasif yang relevan dengan lingkungan sekolah atau masyarakat. Susun naskah pidato lengkap dengan struktur pembukaan, isi, dan penutup. Gunakan kaidah kebahasaan pidato persuasif. Latih penyampaiannya, lalu presentasikan di depan kelas.",
      langkah: [
        "Pilih satu topik pidato persuasif dari daftar berikut: (a) Pentingnya Disiplin Waktu, (b) Ayo Gemar Membaca, (c) Stop Perundungan di Sekolah, (d) Bijak Menggunakan Ponsel, atau (e) topik pilihanmu sendiri yang disetujui guru.",
        "Tentukan tujuan spesifik: apa yang ingin kamu capai setelah audiens mendengar pidatomu? Tulis dalam satu kalimat.",
        "Kumpulkan minimal 3 data atau fakta yang mendukung argumenmu. Gunakan sumber yang terpercaya.",
        "Buat kerangka pidato dengan struktur: pembukaan (salam, sapaan, pengantar) → isi (3 argumen + data pendukung + ajakan di setiap argumen) → penutup (simpulan, ajakan final, salam).",
        "Kembangkan kerangka menjadi naskah pidato utuh sebanyak 500—700 kata.",
        "Sematkan kaidah kebahasaan: minimal 3 kalimat persuasif (mari/marilah), 2 kalimat imperatif, 2 kalimat emotif, dan 1 pertanyaan retoris.",
        "Berlatih menyampaikan pidato di depan cermin. Perhatikan intonasi, gestur, kontak mata, dan ekspresi wajah. Gunakan kartu catatan kecil, jangan membaca naskah utuh.",
        "Sampaikan pidato di depan kelas atau rekam video untuk dinilai guru. Durasi: 3—5 menit.",
      ],
      tips: [
        "Pilih topik yang kamu kuasai dan pedulikan. Gairah dan keyakinanmu akan terpancar saat berpidato dan menular ke audiens.",
        "Gunakan kartu catatan ukuran 10×15 cm yang berisi poin-poin utama, bukan naskah utuh. Ini membuat pidatomu terdengar alami.",
        "Latih pidato minimal 3 kali sebelum tampil. Rekam dan evaluasi: perhatikan bagian mana yang perlu diperbaiki.",
        "Awali pidato dengan hook yang menarik — bisa berupa pertanyaan, kutipan, data mengejutkan, atau cerita singkat yang relevan.",
        "Jangan panik jika lupa sebagian naskah. Tenang, lihat kartu catatan, lalu lanjutkan. Audiens tidak tahu naskah aslimu!",
      ],
      contoh: "Lihat contoh kerangka pidato \"Ayo Bijak Bermedia Sosial\" pada materi Struktur Pidato Persuasif. Gunakan format serupa untuk topik yang kamu pilih. Contoh naskah lengkap tersedia di buku paket halaman 60—62 sebagai referensi tambahan.",
    },
    kuis: [
      {
        id: 1,
        soal: "Perhatikan kalimat berikut: \"Sungguh memprihatinkan, masih banyak remaja yang menghabiskan waktu 6 jam sehari hanya untuk scrolling media sosial tanpa menghasilkan sesuatu yang bermanfaat.\" Kalimat tersebut mengandung kaidah kebahasaan berupa...",
        opsi: ["Kalimat imperatif", "Kalimat persuasif", "Kalimat emotif", "Kalimat retoris"],
        jawaban: 2,
        penjelasan: "Kalimat tersebut menggunakan kata 'memprihatinkan' yang bermuatan emosi, sehingga termasuk kalimat emotif. Fungsinya menyentuh perasaan audiens agar peduli terhadap masalah yang diangkat.",
      },
      {
        id: 2,
        soal: "Seorang orator ingin menyampaikan pidato tentang bahaya narkoba di hadapan siswa SMP. Struktur isi yang paling tepat adalah...",
        opsi: [
          "Data statistik pengguna narkoba → definisi narkoba → ajakan menjauhi narkoba",
          "Definisi narkoba → data statistik → dampak narkoba bagi remaja → ajakan menjauhi narkoba dengan langkah konkret",
          "Ajakan menjauhi narkoba → data statistik → definisi narkoba",
          "Dampak narkoba → ajakan → definisi → data statistik"
        ],
        jawaban: 1,
        penjelasan: "Urutan yang paling logis dan persuasif adalah mulai dari definisi (audiens tahu apa yang dibahas), lalu data (membangun kesadaran), dilanjutkan dampak (menyentuh emosi), dan diakhiri ajakan konkret. Struktur ini membangun argumen secara bertahap.",
      },
      {
        id: 3,
        soal: "Dalam sebuah pidato persuasif, kalimat \"Jangan biarkan masa depanmu hancur hanya karena sebatang rokok!\" termasuk jenis kalimat...",
        opsi: ["Persuasif halus", "Imperatif keras", "Emotif", "Deklaratif"],
        jawaban: 1,
        penjelasan: "Kalimat tersebut menggunakan kata 'jangan' yang merupakan perintah/larangan tegas, sehingga termasuk imperatif keras. Biasanya digunakan di bagian ajakan final pidato untuk efek yang kuat.",
      },
      {
        id: 4,
        tipe: "BENAR_SALAH",
        soal: "Perbedaan teks pidato persuasif dengan teks informatif terletak pada adanya ajakan atau imbauan.",
        opsi: ["Benar", "Salah"],
        jawaban: 0,
        penjelasan: "Pernyataan tersebut benar. Pidato informatif bertujuan memberi pengetahuan tanpa mengajak, sedangkan pidato persuasif secara eksplisit mengandung ajakan untuk memengaruhi sikap atau tindakan audiens.",
      },
      {
        id: 5,
        tipe: "BENAR_SALAH",
        soal: "Intonasi yang datar dan monoton justru membuat pidato persuasif lebih meyakinkan.",
        opsi: ["Benar", "Salah"],
        jawaban: 1,
        penjelasan: "Pernyataan tersebut salah. Intonasi yang datar dan monoton membuat pidato membosankan dan tidak meyakinkan. Intonasi yang baik bervariasi — naik-turun, cepat-lambat — sesuai dengan pesan yang disampaikan.",
      },
      {
        id: 6,
        soal: "Cermati penggalan pidato berikut: \"Oleh karena itu, dengan segala kerendahan hati, saya mengajak teman-teman sekalian untuk mulai membudayakan antre. Antre bukanlah tanda kelemahan, melainkan tanda kedewasaan dan rasa hormat kita terhadap orang lain.\" Bagian tersebut merupakan bagian...",
        opsi: ["Pembukaan", "Isi argumen", "Penutup", "Salam pembuka"],
        jawaban: 1,
        penjelasan: "Kalimat tersebut berisi argumen dan ajakan yang menjelaskan mengapa antre itu penting. Ini adalah bagian isi pidato, bukan pembukaan (yang berisi salam/sapaan) atau penutup (simpulan/ajakan final).",
      },
      {
        id: 7,
        tipe: "ISIAN",
        soal: "Kalimat perintah yang menggunakan kata 'mohon' atau 'silakan' disebut kalimat...",
        opsi: "imperatif halus",
        jawaban: "imperatif halus",
        penjelasan: "Kalimat imperatif halus adalah kalimat perintah yang disampaikan dengan sopan menggunakan kata seperti 'mohon', 'silakan', 'hendaknya', atau 'cobalah'. Berbeda dengan imperatif keras yang bersifat tegas dan langsung.",
      },
      {
        id: 8,
        soal: "Fungsi jeda (pause) saat berpidato yang paling tepat adalah...",
        opsi: ["Memberi waktu pembicara mengingat naskah", "Memberi efek dramatis dan waktu audiens mencerna informasi", "Menandai bahwa pidato akan segera berakhir", "Mengganti kalimat yang lupa"],
        jawaban: 1,
        penjelasan: "Jeda berfungsi memberi efek dramatis pada poin penting dan memberi waktu audiens mencerna informasi yang baru disampaikan. Jeda di tempat yang tepat membuat pidato lebih berkesan.",
      },
      {
        id: 9,
        soal: "Perhatikan topik pidato berikut: (1) Proses fotosintesis pada tumbuhan, (2) Ayo selamatkan bumi dari sampah plastik, (3) Pengalaman lucu saat kemah. Urutan jenis pidato yang tepat sesuai topik adalah...",
        opsi: ["Persuasif — Informatif — Rekreatif", "Informatif — Persuasif — Rekreatif", "Informatif — Rekreatif — Persuasif", "Rekreatif — Informatif — Persuasif"],
        jawaban: 1,
        penjelasan: "Topik (1) proses fotosintesis = informatif (memberi pengetahuan), topik (2) ayo selamatkan bumi = persuasif (mengajak), topik (3) pengalaman lucu = rekreatif (menghibur).",
      },
      {
        id: 10,
        soal: "Langkah pertama yang harus dilakukan sebelum menulis naskah pidato persuasif adalah...",
        opsi: ["Langsung menulis paragraf pembuka", "Menentukan topik dan tujuan pidato", "Mencari data dan fakta pendukung", "Berlatih di depan cermin"],
        jawaban: 1,
        penjelasan: "Langkah pertama adalah menentukan topik dan tujuan. Tanpa topik yang jelas dan tujuan yang spesifik, langkah-langkah selanjutnya (mencari data, menulis naskah, berlatih) tidak akan terarah.",
      },
    ],
  };

export default konten;
