import type { Konten } from "../types";

/* =============================================
   Unit 7: Teks Cerita Fantasi — VII S2
   KD 3.7/4.7 — Mengidentifikasi & Menulis Teks Cerita Fantasi
   ============================================= */
const konten: Konten = {
    belajar: {
      tujuan: [
        "Memahami hakikat, ciri, dan jenis-jenis teks cerita fantasi",
        "Mengidentifikasi struktur teks cerita fantasi: orientasi, komplikasi, resolusi",
        "Menganalisis unsur intrinsik dan kebahasaan dalam cerita fantasi",
        "Membedakan cerita fantasi dengan teks naratif lainnya",
        "Memproduksi teks cerita fantasi dengan imajinasi yang kreatif dan struktur yang runtut",
      ],
      materi: [
        {
          judul: "1. Hakikat Teks Cerita Fantasi",
          isi: [
            "Teks cerita fantasi adalah teks naratif yang mengembangkan kisah berdasarkan imajinasi dan daya khayal penulis. Cerita fantasi menghadirkan dunia, tokoh, dan peristiwa yang tidak terbatas oleh realitas nyata.",
            "",
            "Ciri-ciri cerita fantasi:",
            "• Mengandung keajaiban, kemustahilan, atau hal-hal yang tidak masuk akal secara ilmiah",
            "• Tokoh memiliki kekuatan super atau kemampuan luar biasa",
            "• Latar melintasi ruang dan waktu (masa lalu, masa depan, dunia paralel)",
            "• Ada konflik antara kebaikan dan kejahatan",
            "• Menggunakan imajinasi tanpa batas sebagai dasar cerita",
            "",
            "Perbedaan cerita fantasi dengan cerita rakyat:",
            "| Aspek | Cerita Fantasi | Cerita Rakyat |",
            "|-------|----------------|---------------|",
            "| Pengarang | Diketahui (ada penulis) | Anonim |",
            "| Dunia | Modern/kreasi baru | Tradisional |",
            "| Tokoh | Bisa makhluk baru (elf, naga) | Manusia/hewan umum |",
            "| Sifat | Fiktif modern | Fiktif tradisional |",
            "",
            "PENTING: Cerita fantasi berbeda dengan khayalan biasa. Fantasi yang baik memiliki logika internal — meskipun dunianya tidak nyata, aturan di dalamnya harus konsisten. Misalnya, jika penyihir hanya bisa mengeluarkan api dari tangan kiri, maka sepanjang cerita aturan itu harus diikuti.",
          ],
          contoh: [
            "Contoh cerita fantasi terkenal:",
            "• Harry Potter (J.K. Rowling) — dunia sihir di samping dunia Muggle",
            "• The Chronicles of Narnia (C.S. Lewis) — dunia paralel melalui lemari",
            "• Percy Jackson (Rick Riordan) — dewa-dewi Yunani di dunia modern",
            "• Bumi (Tere Liye) — petualangan lintas dunia paralel",
            "• Sihir di Sekolah (karya lokal) — cerita fantasi dengan latar Indonesia",
            "",
            "Dari contoh di atas, semua memiliki ciri yang sama: ada unsur mustahil yang dijadikan 'masuk akal' dalam logika cerita.",
          ],
        },
        {
          judul: "2. Jenis-Jenis Cerita Fantasi",
          isi: [
            "Cerita fantasi dapat dibedakan berdasarkan kedekatannya dengan dunia nyata.",
            "",
            "1. Fantasi Total (Fantasi Murni)",
            "• Seluruh cerita berada di dunia imajinasi yang tidak terkait dunia nyata",
            "• Tokoh, latar, dan konflik semuanya hasil imajinasi",
            "• Contoh: kisah di negeri dongeng, planet asing, dunia paralel",
            "• Tokoh: naga, elf, penyihir, makhluk aneh",
            "• Latar: istana awan, hutan ajaib, planet Zargoth",
            "",
            "2. Fantasi Irisan (Fantasi Modern)",
            "• Dunia nyata dan dunia imajinasi beririsan/bertabrakan",
            "• Tokoh biasa masuk ke dunia fantasi, atau makhluk fantasi masuk ke dunia nyata",
            "• Contoh: Harry Potter (penyihir hidup di antara manusia biasa), Narnia (masuk ke dunia lain lewat lemari)",
            "• Lebih dekat dengan pengalaman pembaca karena ada unsur dunia nyata",
            "",
            "3. Fantasi Ilmiah (Science Fantasy)",
            "• Menggabungkan unsur fantasi dengan teknologi canggih atau sains",
            "• Contoh: kisah robot yang memiliki perasaan, perjalanan waktu dengan mesin",
            "",
            "Tips: Untuk pemula, mulailah dengan fantasi irisan — kamu bisa menggunakan latar sekolahmu, lalu menambahkan unsur ajaib di dalamnya.",
          ],
          contoh: [
            "Perbandingan Fantasi Total dan Irisan:",
            "",
            "Fantasi Total: 'Di Kerajaan Awan, hiduplah seorang pangeran bersayap elang. Setiap pagi ia terbang mengelilingi istana yang terbuat dari kapas dan cahaya bintang.'",
            "",
            "Fantasi Irisan: 'Rina, siswi kelas VII SMP Pelita, menemukan sebuah buku tua di perpustakaan sekolah. Saat ia membuka halaman pertamanya, ia tersedot ke dalam dunia di mana hewan bisa berbicara dan pohon berjalan.'",
            "",
            "Mana yang lebih mudah ditulis? Fantasi irisan, karena latar dunia nyata sudah kamu kenali.",
          ],
        },
        {
          judul: "3. Struktur Teks Cerita Fantasi",
          isi: [
            "Cerita fantasi memiliki struktur naratif yang sama dengan cerita rekaan lainnya, namun dengan pengembangan yang lebih bebas.",
            "",
            "1. Orientasi (Pengenalan)",
            "  • Pengenalan tokoh, latar, dan suasana cerita",
            "  • Biasanya dimulai dengan deskripsi dunia atau tokoh utama",
            "  • Bisa langsung masuk ke 'keanehan' untuk memikat pembaca",
            "  • Contoh: \"Alena tidak pernah menyangka bahwa cermin kamar neneknya adalah pintu menuju dunia lain.\"",
            "",
            "2. Komplikasi (Konflik)",
            "  • Munculnya masalah, tantangan, atau petualangan",
            "  • Konflik bisa bersifat fisik (melawan monster) atau batin (menentukan pilihan sulit)",
            "  • Klimaks: puncak ketegangan saat tokoh menghadapi tantangan terbesar",
            "  • Contoh: Alena harus memilih antara menyelamatkan dunia fantasi atau kembali ke keluarganya.",
            "",
            "3. Resolusi (Penyelesaian)",
            "  • Konflik menemukan jalan keluar",
            "  • Tokoh berhasil atau gagal (bisa juga akhir terbuka)",
            "  • Biasanya ada pelajaran atau perubahan pada tokoh",
            "  • Contoh: Alena berhasil menyeimbangkan kedua dunia dan mendapatkan kekuatan baru.",
            "",
            "Tips: Cerita fantasi yang seru biasanya langsung 'menceburkan' pembaca ke dalam keajaiban di paragraf pertama (in medias res). Jangan terlalu lama dengan deskripsi pengantar.",
          ],
          contoh: [
            "Struktur cerita fantasi 'Petualangan di Dunia Bawah Laut':",
            "",
            "Orientasi: \"Gilang adalah anak biasa yang tinggal di desa nelayan. Suatu hari saat menyelam, ia menemukan gerbang cahaya di dasar laut.\"",
            "",
            "Komplikasi: \"Di dunia bawah laut, kerajaan ikan sedang dilanda kekeringan. Hanya 'Batu Matahari' yang bisa menyelamatkan mereka, dan Gilang-lah satu-satunya manusia yang bisa mengambilnya dari Gunung Api Laut dalam.\"",
            "",
            "Resolusi: \"Dengan bantuan kura-kura raksasa dan ikan duyung, Gilang berhasil mengambil Batu Matahari. Kerajaan laut kembali subur, dan Gilang pulang dengan membawa persahabatan lintas dunia.\"",
          ],
        },
        {
          judul: "4. Unsur Intrinsik Cerita Fantasi",
          isi: [
            "Cerita fantasi memiliki unsur intrinsik yang sama dengan cerita naratif lainnya, tetapi dengan pengembangan yang lebih kreatif.",
            "",
            "1. Tema",
            "• Gagasan pokok cerita",
            "• Tema umum fantasi: petualangan, persahabatan, keberanian, kebaikan vs kejahatan",
            "• Bisa juga tema yang lebih kompleks: penerimaan perbedaan, kesetiaan, pengorbanan",
            "",
            "2. Tokoh dan Penokohan",
            "• Protagonis: tokoh utama (biasanya yang baik)",
            "• Antagonis: tokoh lawan/penghalang",
            "• Tokoh fantasi bisa berupa: manusia dengan kekuatan super, makhluk ajaib, hewan bicara",
            "• Penokohan bisa disampaikan melalui dialog, tingkah laku, atau deskripsi fisik",
            "",
            "3. Alur (Plot)",
            "• Cerita fantasi biasanya menggunakan alur maju",
            "• Bisa juga alur campuran (flashback) untuk mengungkap misteri",
            "• Alur melingkar (akhir kembali ke awal dengan perubahan) juga populer",
            "",
            "4. Latar (Setting)",
            "• Paling kreatif dibanding teks lain — bisa berupa dunia apa pun",
            "• Latar tempat: istana awan, dasar laut, planet lain, sekolah sihir",
            "• Latar waktu: masa depan, masa lalu, waktu tak terbatas",
            "• Latar suasana: misterius, menegangkan, magis",
            "",
            "5. Amanat (Pesan Moral)",
            "• Pesan yang ingin disampaikan penulis",
            "• Meskipun dunianya fantasi, amanatnya relevan dengan kehidupan nyata",
            "• Contoh: \"Persahabatan bisa mengalahkan kejahatan.\"",
          ],
          contoh: [
            "Analisis unsur intrinsik 'Harry Potter' (contoh populer):",
            "Tema: Persahabatan, keberanian melawan kejahatan",
            "Tokoh: Harry (protagonis, pemberani), Voldemort (antagonis, jahat), Hermione/Ron (pendukung)",
            "Alur: Harry masuk Hogwarts → bertemu Voldemort → petualangan setiap buku → klimaks final",
            "Latar: Hogwarts (sekolah sihir), dunia Muggle (dunia nyata), masa sekarang dengan elemen magis",
            "Amanat: 'Cinta dan persahabatan adalah kekuatan terkuat.'",
          ],
        },
        {
          judul: "5. Kaidah Kebahasaan Cerita Fantasi",
          isi: [
            "Cerita fantasi memiliki ciri kebahasaan yang membuatnya berbeda dari teks naratif lainnya.",
            "",
            "1. Kata Kerja Tindakan (Verba Aktif)",
            "• Menceritakan aksi tokoh dalam petualangan",
            "• Contoh: melompat, menerjang, menghilang, menyihir, terbang, berubah",
            "",
            "2. Kata Sifat (Adjektiva) untuk Deskripsi",
            "• Menggambarkan tokoh, tempat, dan suasana secara hidup",
            "• Contoh: misterius, megah, menyeramkan, mempesona, ajaib",
            "",
            "3. Kata Ganti untuk Tokoh",
            "• Ia, dia, mereka, -nya",
            "• Digunakan untuk menghindari pengulangan nama tokoh",
            "",
            "4. Konjungsi Temporal dan Kausal",
            "• Temporal: kemudian, tiba-tiba, setelah itu, sementara itu",
            "• Kausal: karena, sehingga, maka, akibatnya",
            "• Contoh: 'Tiba-tiba, tanah di bawahnya terbuka dan ia jatuh ke dunia lain.'",
            "",
            "5. Kalimat Langsung (Dialog)",
            "• Menghidupkan interaksi antartokoh",
            "• Contoh: '\"Kau siapa?\" tanya Rina dengan suara gemetar.'",
            "",
            "6. Majas (Gaya Bahasa)",
            "• Personifikasi: benda mati bertingkah seperti manusia ('Pohon-pohon berbisik rahasia')",
            "• Metafora: perbandingan tanpa kata pembanding ('Dunia itu lautan bintang')",
            "• Hiperbola: melebih-lebihkan ('Tangisnya membanjiri lembah')",
          ],
          rangkuman: [
            "Rumus 'A-SAKTI' untuk kaidah kebahasaan cerita fantasi:",
            "A = Aksi (kata kerja aktif)",
            "SA = Sifat (kata sifat deskriptif)",
            "K = Konjungsi (temporal & kausal)",
            "T = Tuturan (dialog/kalimat langsung)",
            "I = Imajinasi (majas/gaya bahasa)",
          ],
        },
        {
          judul: "6. Nilai-Nilai dalam Cerita Fantasi",
          isi: [
            "Meskipun berlatar dunia khayalan, cerita fantasi sarat dengan nilai-nilai yang dapat diterapkan dalam kehidupan sehari-hari.",
            "",
            "1. Nilai Moral",
            "• Keberanian untuk menghadapi ketakutan",
            "• Kejujuran dan integritas dalam situasi sulit",
            "• Tanggung jawab atas kekuatan atau kemampuan yang dimiliki",
            "",
            "2. Nilai Sosial",
            "• Pentingnya persahabatan dan kerja sama",
            "• Saling membantu meskipun berbeda latar belakang",
            "• Loyalitas pada teman dan keluarga",
            "",
            "3. Nilai Pendidikan",
            "• Pengetahuan adalah kekuatan (buku, mantra, ilmu sihir sebagai metafora)",
            "• Kegigihan dalam belajar dan berlatih",
            "• Kreativitas dalam memecahkan masalah",
            "",
            "4. Nilai Budaya",
            "• Cerita fantasi lokal bisa memperkenalkan mitologi Nusantara",
            "• Contoh: cerita tentang genderuwo, jin, atau makhluk mitologi Indonesia",
            "• Menggabungkan kearifan lokal dalam kemasan fantasi modern",
            "",
            "PENTING: Ketika membaca cerita fantasi, jangan hanya fokus pada keajaibannya. Temukan nilai-nilai yang bisa kamu petik dan terapkan dalam kehidupan nyata.",
          ],
          contoh: [
            "Analisis nilai dalam cerita 'Bumi' karya Tere Liye:",
            "Nilai moral: Raib belajar menerima kekuatannya dan bertanggung jawab",
            "Nilai sosial: Persahabatan Raib, Seli, dan Ali adalah inti cerita",
            "Nilai pendidikan: Pengetahuan tentang klan dan ilmu silang membuka wawasan",
            "Nilai budaya: Memadukan mitologi Nusantara dengan petualangan modern",
          ],
        },
        {
          judul: "7. Prosedur Menulis Cerita Fantasi",
          isi: [
            "Sekarang saatnya menulis cerita fantasi sendiri. Ikuti panduan berikut untuk menghasilkan cerita yang kreatif dan runtut.",
            "",
            "Langkah 1: Tentukan Dunia Fantasi",
            "• Pilih jenis: fantasi total atau irisan?",
            "• Ciptakan aturan dunia fantasimu: bagaimana cara kerja sihir? Ada makhluk apa saja?",
            "• Beri nama dunia atau tempat yang unik",
            "",
            "Langkah 2: Ciptakan Tokoh",
            "• Tentukan tokoh utama (protagonis) — apa kelebihan dan kelemahannya?",
            "• Ciptakan tokoh lawan (antagonis) — apa motivasinya?",
            "• Beri tokoh pendukung yang membantu atau menghalangi",
            "",
            "Langkah 3: Buat Konflik",
            "• Apa masalah yang akan dihadapi tokoh?",
            "• Apa yang dipertaruhkan? (dunia, keluarga, teman, identitas)",
            "• Bagaimana konflik akan mencapai klimaks?",
            "",
            "Langkah 4: Susun Alur",
            "• Buat kerangka: orientasi → komplikasi → resolusi",
            "• Tentukan beberapa adegan kunci (plot point)",
            "• Pastikan alur logis meskipun dunianya fantasi",
            "",
            "Langkah 5: Tulis dengan Hidup",
            "• Gunakan kata sifat yang kuat untuk deskripsi",
            "• Selingi narasi dengan dialog",
            "• Gunakan majas untuk memperindah cerita",
            "",
            "Langkah 6: Revisi dan Edit",
            "• Periksa konsistensi aturan dunia fantasi",
            "• Periksa alur: apakah ada loncatan yang membingungkan?",
            "• Minta teman membaca dan memberi masukan",
          ],
          rangkuman: [
            "Rumus menulis cerita fantasi: DUNIA → TOKOH → KONFLIK → ALUR → TULIS → REVISI",
            "",
            "Tips Penting:",
            "✓ Buat aturan dunia yang konsisten — pembaca akan bingung jika aturan berubah-ubah",
            "✓ Mulai dengan 'hook' yang kuat di paragraf pertama",
            "✓ Jangan terlalu banyak info di awal — ungkap sedikit demi sedikit",
            "✓ Akhiri dengan pesan moral yang jelas",
            "",
            "Ingat: Dalam fantasi, apa pun bisa terjadi — asalkan konsisten dengan aturan yang sudah kamu buat!",
          ],
        },
      ],
    },
    latihan: [
      {
        id: 1,
        tipe: "PG",
        soal: "Teks cerita fantasi adalah teks yang mengembangkan kisah berdasarkan...",
        opsi: ["Fakta ilmiah", "Imajinasi dan daya khayal", "Pengalaman pribadi", "Berita aktual"],
        jawaban: 1,
        penjelasan: "Cerita fantasi dikembangkan berdasarkan imajinasi dan daya khayal penulis, bukan fakta atau realitas.",
      },
      {
        id: 2,
        tipe: "PG",
        soal: "Berikut yang merupakan ciri cerita fantasi adalah...",
        opsi: ["Berdasarkan kisah nyata", "Tokoh manusia biasa tanpa kekuatan", "Mengandung keajaiban atau kemustahilan", "Latar hanya di sekolah"],
        jawaban: 2,
        penjelasan: "Cerita fantasi mengandung keajaiban, hal-hal mustahil, atau tidak masuk akal secara ilmiah.",
      },
      {
        id: 3,
        tipe: "PG",
        soal: "Cerita fantasi yang seluruhnya berada di dunia imajinasi disebut fantasi...",
        opsi: ["Irisan", "Total", "Ilmiah", "Mini"],
        jawaban: 1,
        penjelasan: "Fantasi total/murni: seluruh cerita berada di dunia imajinasi tanpa kaitan dengan dunia nyata.",
      },
      {
        id: 4,
        tipe: "PG",
        soal: "Contoh cerita fantasi irisan adalah...",
        opsi: ["Kisah naga di negeri awan", "Harry Potter (penyihir di antara manusia)", "Petualangan di planet Mars", "Dongeng putri tidur"],
        jawaban: 1,
        penjelasan: "Harry Potter adalah fantasi irisan karena dunia sihir beririsan dengan dunia manusia biasa (Muggle).",
      },
      {
        id: 5,
        tipe: "PG",
        soal: "Bagian struktur cerita fantasi yang berisi puncak ketegangan disebut...",
        opsi: ["Orientasi", "Komplikasi", "Klimaks", "Resolusi"],
        jawaban: 2,
        penjelasan: "Klimaks adalah puncak ketegangan saat tokoh menghadapi tantangan terbesar, bagian dari komplikasi.",
      },
      {
        id: 6,
        tipe: "PG",
        soal: "Tokoh yang menjadi lawan atau penghalang dalam cerita disebut...",
        opsi: ["Protagonis", "Antagonis", "Tritagonis", "Figuran"],
        jawaban: 1,
        penjelasan: "Antagonis adalah tokoh lawan yang menjadi penghalang atau musuh protagonis.",
      },
      {
        id: 7,
        tipe: "PG",
        soal: "'Pohon-pohon berbisik rahasia saat malam tiba' adalah contoh majas...",
        opsi: ["Metafora", "Personifikasi", "Hiperbola", "Litotes"],
        jawaban: 1,
        penjelasan: "Personifikasi memberikan sifat manusia pada benda mati (pohon bisa berbisik).",
      },
      {
        id: 8,
        tipe: "PG",
        soal: "Perbedaan utama cerita fantasi dengan cerita rakyat adalah...",
        opsi: ["Cerita fantasi lebih pendek", "Cerita fantasi diketahui pengarangnya", "Cerita fantasi bersifat anonim", "Cerita rakyat punya pesan moral"],
        jawaban: 1,
        penjelasan: "Cerita fantasi diketahui pengarangnya (ada penulis), sedangkan cerita rakyat bersifat anonim.",
      },
      {
        id: 9,
        tipe: "PG",
        soal: "Hal terpenting dalam membangun dunia fantasi adalah...",
        opsi: ["Dunia harus mirip dengan dunia nyata", "Aturan dunia harus konsisten", "Tidak boleh ada sihir", "Harus ada raja dan ratu"],
        jawaban: 1,
        penjelasan: "Aturan dunia fantasi harus konsisten — pembaca akan bingung jika aturan berubah-ubah sepanjang cerita.",
      },
      {
        id: 10,
        tipe: "PG",
        soal: "Penggunaan majas dalam cerita fantasi bertujuan untuk...",
        opsi: ["Membingungkan pembaca", "Memperindah dan menghidupkan cerita", "Membuat cerita lebih panjang", "Mengganti dialog"],
        jawaban: 1,
        penjelasan: "Majas memperindah bahasa dan menghidupkan gambaran dalam cerita fantasi.",
      },
    ],
    praktik: {
      tujuan: "Menulis cerita fantasi pendek dengan struktur yang runtut, unsur intrinsik yang jelas, dan penggunaan majas yang tepat.",
      instruksi: "Tulis sebuah cerita fantasi pendek (minimal 2 paragraf) dengan tema bebas. Pastikan memiliki orientasi, komplikasi, dan resolusi.",
      langkah: [
        "Tentukan jenis fantasi: total atau irisan?",
        "Ciptakan dunia fantasi dengan aturan yang jelas (contoh: 'Di dunia ini, setiap manusia bisa mengendalikan satu elemen alam')",
        "Ciptakan minimal 2 tokoh: protagonis dan antagonis",
        "Buat kerangka alur: orientasi → komplikasi (termasuk klimaks) → resolusi",
        "Tulis cerita dengan paragraf pembuka yang menarik (mulai langsung dengan aksi/keanehan)",
        "Gunakan majas minimal 2 kali (personifikasi, metafora, atau hiperbola)",
        "Sisipkan dialog antartokoh untuk menghidupkan cerita",
        "Periksa konsistensi aturan dunia fantasi, lalu minta teman membaca dan memberi masukan",
      ],
      tips: [
        "Mulailah dengan 'Bagaimana jika...?' — pertanyaan ini adalah awal fantasi yang bagus.",
        "Gunakan pengalaman sehari-hari sebagai inspirasi, lalu tambahkan unsur ajaib.",
        "Baca contoh cerita fantasi untuk mendapatkan ide gaya penulisan.",
        "Jangan takut berimajinasi liar — dalam fantasi, tidak ada yang mustahil!",
        "Pastikan pembaca bisa 'melihat' duniamu melalui deskripsi yang hidup.",
      ],
      contoh: "Lihat analisis struktur cerita fantasi 'Petualangan di Dunia Bawah Laut' pada materi Struktur Cerita Fantasi di atas.",
    },
    kuis: [
      {
        id: 1,
        tipe: "PG",
        soal: "Cerita fantasi berbeda dengan realitas karena mengandung unsur...",
        opsi: ["Fakta", "Keajaiban", "Sejarah", "Opini"],
        jawaban: 1,
        penjelasan: "Cerita fantasi mengandung keajaiban dan hal-hal yang tidak mungkin terjadi di dunia nyata.",
      },
      {
        id: 2,
        tipe: "PG",
        soal: "Struktur yang tepat dalam cerita fantasi adalah...",
        opsi: ["Abstrak → orientasi → krisis → koda", "Orientasi → komplikasi → resolusi", "Pernyataan umum → deskripsi bagian → manfaat", "Tujuan → bahan → langkah"],
        jawaban: 1,
        penjelasan: "Struktur cerita fantasi sama dengan naratif: orientasi → komplikasi (konflik) → resolusi.",
      },
      {
        id: 3,
        tipe: "PG",
        soal: "'Matanya bagaikan bintang di malam hari' adalah contoh majas...",
        opsi: ["Personifikasi", "Metafora", "Hiperbola", "Ironi"],
        jawaban: 1,
        penjelasan: "Metafora adalah perbandingan dua hal tanpa kata pembanding ('bagai', 'seperti').",
      },
      {
        id: 4,
        tipe: "PG",
        soal: "Cerita fantasi irisan ditandai dengan...",
        opsi: ["Dunia yang benar-benar terpisah", "Perpaduan dunia nyata dan fantasi", "Tidak ada tokoh manusia", "Latar hanya di masa depan"],
        jawaban: 1,
        penjelasan: "Fantasi irisan: dunia nyata dan dun ia imajinasi beririsan atau bertabrakan.",
      },
      {
        id: 5,
        tipe: "PG",
        soal: "Kata 'tiba-tiba' dalam cerita fantasi termasuk dalam kaidah kebahasaan...",
        opsi: ["Kata sifat", "Konjungsi temporal", "Kata ganti", "Kata kerja"],
        jawaban: 1,
        penjelasan: "'Tiba-tiba' adalah konjungsi temporal yang menunjukkan perubahan situasi secara mendadak.",
      },
      {
        id: 6,
        tipe: "PG",
        soal: "Salah satu nilai yang sering ditemukan dalam cerita fantasi adalah...",
        opsi: ["Cara memasak", "Keberanian melawan kejahatan", "Rumus matematika", "Sejarah kerajaan"],
        jawaban: 1,
        penjelasan: "Nilai keberanian melawan kejahatan adalah tema universal dalam cerita fantasi.",
      },
      {
        id: 7,
        tipe: "PG",
        soal: "Hal pertama yang harus ditentukan saat menulis cerita fantasi adalah...",
        opsi: ["Judul cerita", "Dunia fantasi dan aturannya", "Harga buku", "Jumlah halaman"],
        jawaban: 1,
        penjelasan: "Langkah pertama adalah menentukan dunia fantasi dan aturan yang berlaku di dalamnya.",
      },
      {
        id: 8,
        tipe: "PG",
        soal: "Perbedaan cerita fantasi dan cerita rakyat dari segi pengarang adalah...",
        opsi: ["Sama-sama anonim", "Fantasi diketahui pengarang, cerita rakyat anonim", "Cerita rakyat diketahui pengarang, fantasi anonim", "Keduanya diketahui pengarang"],
        jawaban: 1,
        penjelasan: "Cerita fantasi modern memiliki pengarang yang jelas, sedangkan cerita rakyat bersifat anonim.",
      },
      {
        id: 9,
        tipe: "PG",
        soal: "Fungsi klimaks dalam cerita fantasi adalah...",
        opsi: ["Pengenalan tokoh", "Puncak ketegangan cerita", "Penutup cerita", "Deskripsi latar"],
        jawaban: 1,
        penjelasan: "Klimaks adalah puncak ketegangan saat konflik mencapai titik paling serius.",
      },
      {
        id: 10,
        tipe: "PG",
        soal: "Cerita fantasi yang baik harus memiliki...",
        opsi: ["Aturan dunia yang konsisten", "Tokoh yang sempurna", "Akhir yang bahagia", "Latar di luar negeri"],
        jawaban: 0,
        penjelasan: "Konsistensi aturan dunia fantasi adalah kunci — pembaca harus percaya pada logika internal cerita.",
      },
    ],
  };

export default konten;
