import type { Konten, Soal } from "../types";

const kd = "3.3/4.3";

function buatSoal(count: number, opsi: number, tema: string): Soal[] {
  return Array.from({ length: count }, (_, i) => ({
    id: i + 1,
    soal: `Contoh soal ${tema} nomor ${i + 1}?`,
    opsi: ["Pilihan A", "Pilihan B", "Pilihan C", "Pilihan D"],
    jawaban: 0,
    penjelasan: `Penjelasan untuk soal ${tema} nomor ${i + 1}`,
  }));
}

/* =============================================
   Unit 7: Teks Pariwara (Iklan) — VIII S2
   KD 3.3/4.3 — Mengidentifikasi Unsur, Struktur, dan Kebahasaan Teks Iklan
   serta Menyajikannya Secara Lisan dan Tulis
   ============================================= */
const konten: Konten = {
    belajar: {
      tujuan: [
        "Memahami hakikat, fungsi, dan tujuan teks pariwara (iklan) dalam kehidupan sehari-hari",
        "Mengidentifikasi unsur-unsur iklan berdasarkan prinsip AIDA (Attention, Interest, Desire, Action)",
        "Menganalisis struktur teks iklan yang meliputi judul, tubuh iklan, dan penutup",
        "Mengenali kaidah kebahasaan iklan: kalimat persuasif, imperatif, superlatif, dan singkat",
        "Membedakan jenis-jenis iklan berdasarkan isi (niaga/non-niaga) dan media (cetak/elektronik/digital)",
        "Memahami tujuan dan fungsi iklan dalam konteks komunikasi pemasaran dan sosial",
        "Menyusun teks iklan dengan memperhatikan unsur, struktur, dan kebahasaan yang tepat",
      ],
      materi: [
        {
          judul: "1. Hakikat Iklan/Pariwara",
          catatan: "Iklan (pariwara) adalah pemberitahuan kepada khalayak tentang suatu barang, jasa, atau gagasan yang bertujuan membujuk.",
          isi: [
            "Kata 'pariwara' berasal dari bahasa Sansekerta yang berarti 'pemberitahuan' atau 'pengumuman'. Dalam kehidupan modern, iklan menjadi salah satu sarana komunikasi paling kuat yang kita temui setiap hari — dari papan reklame di jalan, iklan di televisi, hingga unggahan sponsor di media sosial.",
            "",
            "Pengertian teks iklan menurut para ahli:",
            "• Iklan adalah bentuk komunikasi nonpersonal yang disampaikan melalui media massa untuk membujuk khalayak melakukan tindakan sesuai keinginan pengiklan (Kotler)",
            "• Iklan adalah pesan yang menawarkan produk, jasa, atau gagasan yang ditujukan kepada masyarakat melalui media (Kasali)",
            "• Pariwara merupakan istilah dalam bahasa Indonesia yang bermakna sama dengan iklan",
            "",
            "Ciri-ciri teks iklan:",
            "✓ Bersifat persuasif — bertujuan membujuk dan memengaruhi khalayak",
            "✓ Menggunakan bahasa yang menarik, singkat, dan mudah diingat",
            "✓ Disampaikan melalui media massa (cetak, elektronik, digital)",
            "✓ Komunikasi satu arah (nonpersonal) — tidak ada dialog langsung",
            "✓ Berbayar — pemasang iklan membayar ruang atau waktu pada media",
            "✓ Memiliki target sasaran yang jelas (segmen pasar tertentu)",
            "",
            "PENTING: Iklan berbeda dengan pengumuman biasa. Pengumuman bersifat informatif dan netral, sedangkan iklan bersifat persuasif — bertujuan meyakinkan dan menggerakkan khalayak untuk melakukan sesuatu (membeli, mendaftar, mendukung, dll.).",
          ],
          contoh: [
            "Contoh teks iklan sederhana:",
            "",
            "\"Dapatkan sepatu olahraga terbaru dengan harga spesial! Hanya Rp199.000. Nyaman, ringan, dan bergaya. Klik sekarang sebelum kehabisan!\"",
            "",
            "Analisis:",
            "• Kalimat ajakan: 'Dapatkan...', 'Klik sekarang...'",
            "• Kata superlatif: 'terbaru', 'spesial'",
            "• Informasi produk: sepatu olahraga",
            "• Harga: Rp199.000",
            "• Target: pembeli yang menginginkan sepatu olahraga murah dan berkualitas",
          ],
        },
        {
          judul: "2. Unsur Iklan: Prinsip AIDA",
          isi: [
            "Sebuah iklan yang efektif harus mengandung unsur-unsur yang mampu menarik perhatian dan menggerakkan khalayak. Prinsip yang paling dikenal dalam dunia periklanan adalah AIDA.",
            "",
            "A — Attention (Perhatian)",
            "• Iklan harus mampu menarik perhatian khalayak sasaran",
            "• Dilakukan melalui: judul mencolok, gambar/visual menarik, warna cerah, musik, atau gerakan",
            "• Contoh: 'Diskon 70% Akhir Tahun! Jangan Sampai Kehabisan!'",
            "• Pada iklan cetak: ukuran huruf besar, tata letak yang unik, dan kontras warna",
            "",
            "I — Interest (Ketertarikan)",
            "• Setelah perhatian tertarik, iklan harus membangkitkan rasa ingin tahu",
            "• Menjelaskan keunggulan produk atau manfaat yang relevan dengan kebutuhan khalayak",
            "• Contoh: 'Dengan teknologi NanoClean, sepatumu tetap putih meski terkena lumpur.'",
            "• Gunakan fakta, data, atau testimoni untuk memperkuat ketertarikan",
            "",
            "D — Desire (Keinginan)",
            "• Membangkitkan hasrat atau keinginan untuk memiliki produk/jasa",
            "• Tunjukkan bagaimana produk dapat memecahkan masalah atau memenuhi kebutuhan",
            "• Contoh: 'Bayangkan kenyamanan berlari tanpa lelah dengan sol empuk bantalan udara.'",
            "• Gunakan bahasa yang menyentuh emosi dan membayangkan manfaat",
            "",
            "A — Action (Tindakan)",
            "• Mendorong khalayak untuk segera bertindak",
            "• Berisi ajakan konkret: bell sekarang, daftar, kunjungi, klik, hubungi",
            "• Sertakan informasi kontak atau mekanisme tindakan",
            "• Contoh: 'Pesan sekarang di bit.ly/sepatuku atau hubungi 0812-3456-7890.'",
            "• Batas waktu ('Stok terbatas!') atau bonus ('Gratis ongkir!') untuk mempercepat tindakan",
            "",
            "Tips Menulis Iklan AIDA: Mulailah dengan judul yang menghentikan scroll (Attention), lalu buat pembaca penasaran (Interest), bangkitkan keinginan dengan manfaat nyata (Desire), dan tutup dengan ajakan tegas (Action).",
          ],
          contoh: [
            "Analisis AIDA pada iklan minuman kemasan:",
            "",
            "\"Haus di tengah terik? Coba SegarSegar!\"",
            "→ Attention: Pertanyaan retoris yang mengena di situasi sehari-hari",
            "",
            "\"Dibuat dari 100% buah asli tanpa gula tambahan. Vitamin C-nya setara dengan 3 jeruk!\"",
            "→ Interest: Informasi menarik tentang bahan alami dan kandungan vitamin",
            "",
            "\"Rasakan kesegaran alami yang langsung mengalir di tenggorokanmu.\"",
            "→ Desire: Membayangkan sensasi segar yang nikmat",
            "",
            "\"Beli 2 gratis 1 di minimarket terdekat! Periode terbatas.\"",
            "→ Action: Ajakan membeli dengan bonus dan batas waktu",
          ],
        },
        {
          judul: "3. Struktur Teks Iklan",
          isi: [
            "Teks iklan memiliki struktur yang khas dan berbeda dengan jenis teks lainnya. Struktur ini dirancang untuk memaksimalkan daya tarik dan efektivitas pesan.",
            "",
            "1. Judul (Headline)",
            "• Bagian paling penting — kalimat pertama yang dilihat/didengar khalayak",
            "• Harus singkat, padat, dan menarik perhatian (memenuhi unsur Attention)",
            "• Jenis judul: pertanyaan ('Mau kulit sehat?'), perintah ('Coba sekarang!'), pernyataan ('Ini revolusi terbaru!'), atau berita ('Hadir di Indonesia!')",
            "• Contoh: 'Diskon Besar-besaran!', 'Kulit Sehat dalam 7 Hari'",
            "",
            "2. Tubuh Iklan (Body Copy)",
            "• Bagian penjelasan yang mengembangkan pesan judul",
            "• Berisi informasi tentang produk/jasa: manfaat, keunggulan, harga, fitur",
            "• Memenuhi unsur Interest dan Desire",
            "• Dapat berupa: paragraf deskriptif, poin-poin manfaat, testimoni, atau narasi",
            "• Contoh: 'Krim ini mengandung kolagen dan vitamin E yang melembapkan kulit secara alami. Hasilnya terlihat dalam 7 hari pemakaian rutin.'",
            "",
            "3. Penutup (Closing)",
            "• Berisi ajakan bertindak (call to action) dan informasi kontak",
            "• Memenuhi unsur Action",
            "• Dapat berupa slogan, tagline, atau ajakan langsung",
            "• Contoh: 'Hubungi 0800-123-456. Pesan sekarang, dapatkan bonus eksklusif!'",
            "• Sertakan: nomor telepon, website, alamat toko, atau media sosial",
            "",
            "Tips Menyusun Struktur: Gunakan rumus 'J-T-P' — Judul menarik, Tubuh menjelaskan, Penutup mengajak. Pastikan ketiga bagian saling terhubung dan mengalir secara logis.",
          ],
          contoh: [
            "Contoh struktur iklan layanan masyarakat:",
            "",
            "Judul: \"Buang Sampah pada Tempatnya — Mulai dari Dirimu!\"",
            "",
            "Tubuh: \"Setiap hari, Indonesia menghasilkan 175.000 ton sampah. Hanya 60% yang terkelola dengan baik. Sisanya mencemari sungai, laut, dan lingkungan kita. Kamu bisa menjadi bagian dari perubahan. Mulailah dengan langkah sederhana: pilah sampah organik dan anorganik, lalu buang pada tempat yang sudah disediakan.\"",
            "",
            "Penutup: \"Indonesia Bersih, Mulai dari Kita. Bagikan pesan ini ke 10 temanmu! #BuangSampahPadaTempatnya\"",
          ],
        },
        {
          judul: "4. Kaidah Kebahasaan Iklan",
          isi: [
            "Bahasa iklan memiliki ciri khas yang membedakannya dengan teks lain. Kaidah kebahasaan ini dirancang untuk membuat pesan iklan lebih efektif, persuasif, dan mudah diingat.",
            "",
            "1. Kalimat Persuasif",
            "• Kalimat yang bertujuan membujuk, mengajak, atau memengaruhi khalayak",
            "• Sering menggunakan kata: ayo, mari, yuk, jangan lewatkan, tunggu apa lagi",
            "• Contoh: 'Yuk, wujudkan rumah impianmu bersama kami!'",
            "• Ciri khas: menggunakan bahasa yang hangat dan akrab seperti ajakan teman",
            "",
            "2. Kalimat Imperatif",
            "• Kalimat perintah yang meminta khalayak melakukan sesuatu",
            "• Bentuk: perintah, larangan, atau himbauan",
            "• Contoh: 'Daftar sekarang!', 'Jangan tunda lagi!', 'Kunjungi toko kami!'",
            "• Tanda seru (!) sering digunakan untuk mempertegas",
            "",
            "3. Kata Superlatif (Tingkat Paling)",
            "• Menggunakan kata yang menunjukkan keunggulan atau tingkat tertinggi",
            "• Contoh: terbaik, termurah, termewah, terpopuler, paling, nomor satu",
            "• Contoh: 'Produk perawatan kulit nomor satu di Indonesia.'",
            "• PENTING: Gunakan superlatif yang dapat dipertanggungjawabkan agar tidak menyesatkan konsumen",
            "",
            "4. Bahasa yang Singkat, Padat, dan Mudah Diingat",
            "• Iklan tidak boleh bertele-tele — gunakan kata sesedikit mungkin",
            "• Slogan sering menggunakan rima atau pengulangan bunyi",
            "• Contoh: 'Ada Aqua, haus hilang.' (hanya 3 kata)",
            "• Gunakan kata-kata konkret dan mudah dipahami semua kalangan",
            "",
            "5. Penggunaan Kata Ganti Orang Kedua",
            "• 'Kamu', 'Anda', 'Kita' untuk menciptakan kedekatan",
            "• Contoh: 'Untuk kulit sehatmu.' atau 'Anda pasti puas.'",
            "",
            "6. Penggunaan Istilah Teknis atau Bahasa Iklan Khas",
            "• Kata-kata seperti: limited edition, promo, gratis, diskon, spesial, eksklusif, dll.",
            "• Memberi kesan bahwa produk bernilai lebih atau terbatas ketersediaannya",
          ],
          rangkuman: [
            "Ingat rumus 'PISIK' untuk kaidah kebahasaan iklan:",
            "P = Persuasif (kalimat bujukan)",
            "I = Imperatif (kalimat perintah)",
            "S = Superlatif (kata paling/ter-)",
            "I = Istilah khas iklan (promo, spesial, gratis)",
            "K = Komunikatif (singkat, padat, mudah diingat)",
          ],
        },
        {
          judul: "5. Jenis-Jenis Iklan",
          isi: [
            "Iklan dapat diklasifikasikan berdasarkan berbagai sudut pandang. Memahami jenis-jenis iklan membantu kita memilih media dan pendekatan yang tepat.",
            "",
            "A. Berdasarkan Isi",
            "• Iklan Niaga (Komersial) — bertujuan mempromosikan produk/jasa untuk meraih keuntungan",
            "  — Contoh: iklan sabun, makanan, pakaian, aplikasi digital",
            "  — Bahasa: cenderung persuasif dengan sugesti tentang manfaat produk",
            "",
            "• Iklan Non-Niaga (Layanan Masyarakat) — bertujuan menyampaikan pesan sosial, edukasi, atau kampanye",
            "  — Contoh: iklan bahaya narkoba, hemat energi, vaksinasi, antikorupsi",
            "  — Bahasa: informatif-edukatif namun tetap menarik",
            "  — Dibuat oleh: pemerintah, organisasi sosial, atau perusahaan sebagai CSR",
            "",
            "B. Berdasarkan Media",
            "• Iklan Media Cetak — koran, majalah, tabloid, brosur, pamflet, baliho, spanduk",
            "  — Kelebihan: dapat dilihat berulang, bertahan lama",
            "  — Kekurangan: tidak ada audio/gerak, jangkauan terbatas",
            "",
            "• Iklan Media Elektronik — televisi, radio",
            "  — Kelebihan: jangkauan luas, audio/visual menarik",
            "  — Kekurangan: biaya mahal, durasi terbatas",
            "  — Iklan televisi: menggabungkan gambar, suara, gerak, dan teks",
            "  — Iklan radio: hanya mengandalkan suara, musik, dan efek audio",
            "",
            "• Iklan Media Digital/Online — media sosial, website, YouTube, aplikasi, email",
            "  — Kelebihan: target tepat, interaktif, biaya terjangkau, terukur",
            "  — Contoh: iklan Instagram, iklan Google, sponsored post, pop-up",
            "  — Keunggulan: bisa menargetkan usia, lokasi, hobi, dan perilaku pengguna",
            "",
            "PENTING: Iklan digital saat ini menjadi primadona karena efisiensi biaya dan ketepatan sasaran. Namun, iklan media cetak dan elektronik tetap relevan untuk segmen tertentu.",
          ],
          contoh: [
            "Perbandingan iklan di berbagai media:",
            "",
            "| Aspek | Cetak | Elektronik | Digital |",
            "|-------|-------|------------|---------|",
            "| Biaya | Rendah-sedang | Tinggi | Rendah-sedang |",
            "| Jangkauan | Lokal/nasional | Nasional | Global |",
            "| Interaktif | Tidak | Tidak | Ya |",
            "| Durasi | Permanen (selama cetak) | Terbatas (detik) | Fleksibel |",
            "| Target | Massa umum | Massa umum | Spesifik |",
            "| Contoh Media | Koran, majalah | TV, radio | IG, YouTube, Google |",
            "",
            "Contoh iklan digital: 'Cukup Rp50.000/bulan, kamu bisa belajar Bahasa Inggris dengan native speaker. Coba gratis 7 hari! Klik link di bio.'",
          ],
        },
        {
          judul: "6. Tujuan dan Fungsi Iklan",
          isi: [
            "Setiap iklan yang dibuat memiliki tujuan spesifik. Secara umum, tujuan dan fungsi iklan dapat dikelompokkan sebagai berikut.",
            "",
            "Tujuan Iklan:",
            "• Tujuan Informatif — memberitahukan khalayak tentang produk/jasa baru",
            "  — Contoh: 'Hadir di Indonesia! Smartphone terbaru dengan kamera 108 MP.'",
            "  — Biasanya pada tahap peluncuran (launching)",
            "",
            "• Tujuan Persuasif — membujuk khalayak untuk memilih atau membeli produk",
            "  — Contoh: 'Mengapa ribuan ibu memilih susu ini? Karena 100% organik dan bebas gula.'",
            "  — Menguatkan preferensi merek di benak konsumen",
            "",
            "• Tujuan Mengingatkan (Reminder) — menjaga merek tetap diingat khalayak",
            "  — Contoh: 'Indomie — rasanya sudah terkenal sejak 1972.'",
            "  — Penting untuk produk yang sudah mapan di pasaran",
            "",
            "Fungsi Iklan bagi Berbagai Pihak:",
            "",
            "Fungsi bagi Produsen/Pengiklan:",
            "✓ Memperkenalkan produk atau jasa kepada khalayak luas",
            "✓ Meningkatkan penjualan dan pangsa pasar",
            "✓ Membangun citra merek (brand image) yang positif",
            "✓ Menghadapi persaingan dengan kompetitor",
            "✓ Menjangkau segmen pasar tertentu secara efektif",
            "",
            "Fungsi bagi Konsumen/Masyarakat:",
            "✓ Mendapatkan informasi tentang produk dan layanan terbaru",
            "✓ Membantu membandingkan produk sebelum membeli",
            "✓ Mengetahui promo, diskon, atau penawaran khusus",
            "✓ Mendapatkan edukasi melalui iklan layanan masyarakat",
            "",
            "Fungsi bagi Perekonomian:",
            "✓ Menggerakkan roda ekonomi melalui konsumsi",
            "✓ Membuka lapangan kerja di industri kreatif (copywriter, desainer, videografer)",
            "✓ Membiayai media massa (televisi, koran, platform digital)",
            "✓ Mendorong inovasi karena persaingan pasar",
          ],
          contoh: [
            "Analisis tujuan iklan berikut:",
            "",
            "\"Vaksinasi adalah perisai kita melawan COVID-19. Ayo lindungi diri, lindungi sesama. Vaksinasi lengkap di puskesmas terdekat. Gratis!\"",
            "",
            "Tujuan: Informatif-persuasif — memberikan informasi tentang vaksinasi dan membujuk masyarakat untuk vaksin. Bersifat layanan masyarakat (non-niaga).",
            "",
            "\"Hanya minggu ini! Beli 1 dapat 2 untuk semua produk skincare. Gratis ongkir seluruh Indonesia.\"",
            "",
            "Tujuan: Persuasif-reminder — mendorong pembelian segera dengan promo terbatas. Bersifat niaga/komersial.",
          ],
        },
        {
          judul: "7. Prosedur Membuat Iklan",
          isi: [
            "Membuat iklan yang efektif memerlukan perencanaan yang matang. Ikuti langkah-langkah berikut untuk menghasilkan iklan yang menarik dan tepat sasaran.",
            "",
            "Langkah 1: Tentukan Produk/Jasa dan Tujuan",
            "• Apa yang akan diiklankan? (produk, jasa, gagasan, atau kampanye sosial?)",
            "• Apa tujuan iklan? (informatif, persuasif, atau reminder?)",
            "• Siapa target sasaran? (remaja, ibu rumah tangga, profesional, pelajar?)",
            "",
            "Langkah 2: Kenali Target Audiens",
            "• Usia, jenis kelamin, pekerjaan, lokasi, dan kebiasaan calon konsumen",
            "• Apa kebutuhan dan masalah mereka?",
            "• Bagaimana produk/jawamu dapat menjawab kebutuhan itu?",
            "• Semakin detail mengenali audiens, semakin tepat pesan iklan",
            "",
            "Langkah 3: Tentukan Media yang Tepat",
            "• Sesuaikan media dengan kebiasaan target audiens",
            "• Remaja: media sosial (Instagram, TikTok, YouTube)",
            "• Orang tua: koran, televisi, radio",
            "• Profesional: LinkedIn, email, website",
            "• Pertimbangkan biaya dan jangkauan media",
            "",
            "Langkah 4: Tulis Pesan Iklan dengan Prinsip AIDA",
            "• Attention: buat judul yang menghentikan mereka",
            "• Interest: beri informasi yang membuat mereka penasaran",
            "• Desire: bangkitkan keinginan dengan manfaat nyata",
            "• Action: ajak mereka bertindak sekarang",
            "",
            "Langkah 5: Gunakan Bahasa Iklan yang Tepat",
            "• Singkat, padat, dan mudah diingat",
            "• Gunakan kalimat persuasif dan imperatif",
            "• Pilih kata superlatif yang relevan dan jujur",
            "• Gunakan kata ganti orang kedua untuk kedekatan emosional",
            "",
            "Langkah 6: Tambahkan Elemen Visual Pendukung",
            "• Gambar, ilustrasi, logo, atau video yang relevan",
            "• Pilih warna yang sesuai dengan merek dan pesan",
            "• Pastikan tata letak rapi dan tidak terlalu ramai",
            "• Iklan yang baik adalah yang 'berbicara' bahkan tanpa kata-kata",
            "",
            "Langkah 7: Evaluasi dan Revisi",
            "• Periksa kembali: apakah pesan sudah jelas?",
            "• Minta pendapat teman atau guru",
            "• Perbaiki jika ada kata-kata yang ambigu atau kurang menarik",
            "• Uji coba pada kelompok kecil sebelum publikasi luas",
            "",
            "Langkah 8: Publikasikan dan Pantau Respons",
            "• Siarkan iklan melalui media yang dipilih",
            "• Jika digital, pantau jumlah views, klik, dan konversi",
            "• Evaluasi efektivitas: apakah tujuan tercapai?",
            "• Catat pelajaran untuk pembuatan iklan berikutnya",
          ],
          rangkuman: [
            "Rumus membuat iklan: TARGET → MEDIA → PESAN → VISUAL → UJI → PUBLIKASI",
            "",
            "Tips: Iklan yang hebat lahir dari pemahaman mendalam tentang siapa yang diajak bicara. Kenali audiensmu, maka pesan akan mengalir dengan sendirinya.",
          ],
        },
      ],
    },
    latihan: [
      {
        id: 1,
        soal: "Teks yang bertujuan membujuk khalayak untuk melakukan sesuatu sesuai keinginan pengiklan disebut...",
        opsi: ["Teks eksposisi", "Teks persuasi", "Teks pariwara (iklan)", "Teks deskripsi"],
        jawaban: 2,
        penjelasan: "Teks pariwara (iklan) adalah teks yang bertujuan membujuk khalayak untuk melakukan tindakan tertentu, seperti membeli produk atau mendukung suatu gagasan.",
      },
      {
        id: 2,
        soal: "Prinsip AIDA dalam iklan terdiri dari Attention, Interest, Desire, dan...",
        opsi: ["Activity", "Action", "Agreement", "Awareness"],
        jawaban: 1,
        penjelasan: "AIDA adalah singkatan dari Attention (perhatian), Interest (ketertarikan), Desire (keinginan), dan Action (tindakan).",
      },
      {
        id: 3,
        soal: "Bagian struktur iklan yang berisi ajakan bertindak dan kontak disebut...",
        opsi: ["Judul (headline)", "Tubuh iklan (body copy)", "Penutup (closing)", "Slogan"],
        jawaban: 2,
        penjelasan: "Penutup (closing) berisi ajakan bertindak (call to action) dan informasi kontak, memenuhi unsur Action dalam AIDA.",
      },
      {
        id: 4,
        soal: "Kalimat 'Jangan tunda lagi! Dapatkan segera produk kami!' menggunakan kaidah kebahasaan...",
        opsi: ["Kalimat superlatif", "Kalimat imperatif", "Kalimat persuasif", "Istilah teknis"],
        jawaban: 1,
        penjelasan: "Kalimat imperatif adalah kalimat perintah yang meminta khalayak melakukan sesuatu, ditandai dengan kata 'Jangan', 'Dapatkan' dan tanda seru.",
      },
      {
        id: 5,
        soal: "Iklan tentang bahaya narkoba yang dibuat oleh BNN termasuk jenis iklan...",
        opsi: ["Iklan niaga", "Iklan baris", "Iklan layanan masyarakat", "Iklan kolom"],
        jawaban: 2,
        penjelasan: "Iklan layanan masyarakat (non-niaga) bertujuan menyampaikan pesan sosial atau edukasi, seperti imbauan tentang bahaya narkoba.",
      },
      {
        id: 6,
        soal: "Kata 'terbaik', 'termurah', dan 'nomor satu' dalam iklan termasuk kaidah kebahasaan...",
        opsi: ["Kalimat persuasif", "Kalimat imperatif", "Kata superlatif", "Istilah khas iklan"],
        jawaban: 2,
        penjelasan: "Kata superlatif adalah kata yang menunjukkan tingkat paling/ter- untuk menonjolkan keunggulan produk dibanding kompetitor.",
      },
      {
        id: 7,
        soal: "Berikut ini yang termasuk kelebihan iklan media digital dibanding media cetak adalah...",
        opsi: ["Biaya lebih mahal", "Tidak bisa diukur efektivitasnya", "Dapat menarget audiens secara spesifik", "Hanya menjangkau orang tua"],
        jawaban: 2,
        penjelasan: "Iklan digital unggul dalam penargetan spesifik (usia, lokasi, hobi, perilaku) dan hasilnya dapat diukur secara real-time.",
      },
      {
        id: 8,
        soal: "Iklan yang bertujuan menjaga merek tetap diingat konsumen disebut iklan...",
        opsi: ["Informatif", "Persuasif", "Reminder", "Kompetitif"],
        jawaban: 2,
        penjelasan: "Iklan reminder (pengingat) bertujuan menjaga merek tetap diingat khalayak, biasanya digunakan untuk produk yang sudah mapan.",
      },
      {
        id: 9,
        soal: "Cermati iklan berikut: 'Hanya Rp10.000! Dapatkan minuman segar ini di minimarket terdekat. Periode terbatas!' Unsur AIDA yang paling dominan adalah...",
        opsi: ["Attention", "Interest", "Desire", "Action"],
        jawaban: 3,
        penjelasan: "Kalimat tersebut menekankan ajakan bertindak (Action) dengan menyebutkan harga, tempat membeli, dan batas waktu ('Periode terbatas').",
      },
      {
        id: 10,
        soal: "Perbedaan utama iklan dengan pengumuman adalah...",
        opsi: ["Iklan lebih panjang dari pengumuman", "Iklan bersifat persuasif, pengumuman bersifat informatif", "Iklan tidak menggunakan media, pengumuman menggunakan media", "Iklan selalu berbayar, pengumuman selalu gratis"],
        jawaban: 1,
        penjelasan: "Iklan bersifat persuasif (membujuk dan memengaruhi), sedangkan pengumuman bersifat informatif (memberi tahu) tanpa ajakan melakukan sesuatu.",
      },
    ],
    praktik: {
      tujuan: "Menyusun teks iklan yang menarik, persuasif, dan sesuai dengan prinsip AIDA serta kaidah kebahasaan yang tepat.",
      instruksi: "Buatlah sebuah teks iklan untuk produk, jasa, atau gagasan yang kamu pilih. Perhatikan unsur AIDA, struktur iklan (judul, tubuh, penutup), dan kaidah kebahasaan yang telah dipelajari.",
      langkah: [
        "Tentukan topik iklan: pilih produk (misalnya: minuman, alat tulis, aplikasi belajar), jasa (bimbel, laundry, fotokopi), atau gagasan (kampanye lingkungan, anti-bullying, gemar membaca) yang ingin kamu iklankan.",
        "Tentukan target audiens: siapa yang akan membaca/melihat iklanmu? (pelajar SMP, remaja, guru, masyarakat umum?)",
        "Tentukan media yang akan digunakan: apakah iklan cetak (poster/brosur) atau iklan digital (posting Instagram/story)?",
        "Buat judul (headline) yang menarik perhatian — gunakan kata-kata yang menghentikan scrolling atau membuat orang menoleh.",
        "Tulis tubuh iklan yang menjelaskan manfaat dan keunggulan produk/jasa/gagasanmu. Gunakan AIDA: bangkitkan Interest dan Desire.",
        "Tulis penutup dengan ajakan bertindak (call to action) yang jelas. Sertakan informasi kontak atau cara mendapatkan produk.",
        "Gunakan kaidah kebahasaan iklan: kalimat persuasif, imperatif, superlatif, dan bahasa yang singkat serta mudah diingat.",
        "Baca ulang seluruh iklan. Periksa ejaan, tanda baca, dan pilihan kata. Minta teman memberi masukan, lalu revisi jika perlu.",
      ],
      tips: [
        "Mulailah dengan judul yang menggunakan angka atau pertanyaan, karena lebih menarik perhatian (contoh: '5 Alasan Kamu Harus...' atau 'Mau Nilai 100?')",
        "Gunakan kata 'Kamu' atau 'Kau' untuk menciptakan kedekatan dengan pembaca.",
        "Jangan takut menggunakan humor — iklan lucu lebih mudah diingat.",
        "Pastikan gambar/visual yang kamu pilih mendukung pesan iklan, bukan malah mengalihkan perhatian.",
        "Uji iklanmu dengan bertanya pada 3 teman: apakah mereka tertarik? Apakah mereka paham pesannya? Apakah mereka mau melakukan ajakanmu?",
      ],
      contoh: "Lihat contoh analisis AIDA pada minuman kemasan di materi 'Unsur Iklan: Prinsip AIDA' sebagai panduan menyusun iklan dengan struktur yang tepat.",
    },
    kuis: [
      {
        id: 1,
        soal: "Apa kepanjangan dari AIDA dalam prinsip pembuatan iklan?",
        opsi: ["Attention, Interest, Desire, Action", "Awareness, Information, Decision, Action", "Attention, Idea, Desire, Activity", "Awareness, Interest, Decision, Activity"],
        jawaban: 0,
        penjelasan: "AIDA = Attention (perhatian), Interest (ketertarikan), Desire (keinginan), Action (tindakan).",
      },
      {
        id: 2,
        soal: "Berikut ini yang merupakan contoh iklan layanan masyarakat adalah...",
        opsi: ["Iklan sabun cuci piring di televisi", "Iklan minuman energi di radio", "Iklan kampanye cuci tangan pakai sabun", "Iklan sepatu olahraga di majalah"],
        jawaban: 2,
        penjelasan: "Iklan kampanye cuci tangan adalah iklan layanan masyarakat yang bertujuan mengedukasi masyarakat tentang perilaku hidup bersih.",
      },
      {
        id: 3,
        soal: "Bagian struktur iklan yang berfungsi sebagai 'pengait' perhatian pertama adalah...",
        opsi: ["Tubuh iklan", "Penutup", "Judul (headline)", "Slogan"],
        jawaban: 2,
        penjelasan: "Judul (headline) adalah bagian pertama yang dilihat khalayak dan harus mampu menarik perhatian (Attention).",
      },
      {
        id: 4,
        soal: "Kalimat 'Produk perawatan kulit terlaris di Asia' mengandung kaidah kebahasaan...",
        opsi: ["Kalimat imperatif", "Kalimat persuasif", "Kata superlatif", "Istilah khas iklan"],
        jawaban: 2,
        penjelasan: "Kata 'terlaris' adalah kata superlatif (tingkat paling) yang menunjukkan keunggulan produk di tingkat Asia.",
      },
      {
        id: 5,
        soal: "Media iklan yang memungkinkan interaksi langsung dengan konsumen adalah...",
        opsi: ["Koran", "Televisi", "Radio", "Media sosial"],
        jawaban: 3,
        penjelasan: "Media sosial memungkinkan interaksi dua arah — konsumen dapat berkomentar, bertanya, dan membagikan iklan. Koran, TV, dan radio bersifat satu arah.",
      },
      {
        id: 6,
        soal: "Cermati iklan berikut: 'Cintai bumi, kurangi plastik. Bawa tumbler mu setiap hari! Mulai dari sekarang.' Tujuan iklan tersebut adalah...",
        opsi: ["Mengingatkan tentang produk", "Membujuk melakukan aksi sosial", "Menawarkan produk komersial", "Menjelaskan cara kerja produk"],
        jawaban: 1,
        penjelasan: "Iklan tersebut bersifat persuasif untuk aksi sosial (mengurangi plastik) — termasuk iklan layanan masyarakat, bukan komersial.",
      },
      {
        id: 7,
        soal: "Dalam struktur iklan, call to action (CTA) biasanya ditempatkan di bagian...",
        opsi: ["Judul", "Tubuh iklan", "Penutup", "Seluruh bagian"],
        jawaban: 2,
        penjelasan: "Call to action (ajakan bertindak) ditempatkan di bagian penutup agar khalayak langsung bertindak setelah membaca manfaat produk.",
      },
      {
        id: 8,
        soal: "Kelebihan iklan radio dibanding iklan cetak adalah...",
        opsi: ["Dapat melihat produk", "Ada unsur suara dan musik", "Lebih murah biayanya", "Bisa disimpan lama"],
        jawaban: 1,
        penjelasan: "Iklan radio memiliki keunggulan unsur suara dan musik yang dapat membangun suasana dan emosi pendengar.",
      },
      {
        id: 9,
        soal: "Kata 'gratis', 'diskon', dan 'spesial' dalam iklan termasuk dalam kategori...",
        opsi: ["Kalimat superlatif", "Istilah khas iklan", "Kalimat imperatif", "Konjungsi temporal"],
        jawaban: 1,
        penjelasan: "Kata-kata seperti gratis, diskon, spesial, limited edition adalah istilah khas iklan yang menciptakan kesan nilai lebih atau urgensi.",
      },
      {
        id: 10,
        soal: "Langkah pertama yang harus dilakukan sebelum membuat iklan adalah...",
        opsi: ["Menulis body copy", "Memilih gambar", "Menentukan produk/jasa dan tujuan", "Membuat slogan"],
        jawaban: 2,
        penjelasan: "Langkah pertama adalah menentukan produk/jasa yang akan diiklankan dan tujuan iklan (informatif, persuasif, atau reminder). Semua langkah lain mengikuti keputusan ini.",
      },
    ],
  };

export default konten;
