import type { Konten } from "../types";

const kd = "3.2/4.2";

/* =============================================
   Unit 2: Teks Cerita Rakyat (Fabel dan Legenda) — VII S1
   KD 3.2/4.2 — Mengidentifikasi & Menceritakan Kembali Cerita Rakyat
   ============================================= */
const konten: Konten = {
    belajar: {
      tujuan: [
        "Memahami hakikat, ciri, dan jenis-jenis teks cerita rakyat (fabel dan legenda)",
        "Mengidentifikasi struktur teks cerita rakyat meliputi orientasi, komplikasi, resolusi, dan koda",
        "Menganalisis unsur intrinsik dan kebahasaan dalam fabel dan legenda",
        "Membedakan karakteristik fabel dan legenda sebagai dua jenis cerita rakyat",
        "Menceritakan kembali dan memproduksi teks cerita rakyat dengan bahasa sendiri",
      ],
      materi: [
        {
          judul: "1. Hakikat Teks Cerita Rakyat",
          catatan: "Cerita rakyat adalah warisan budaya lisan yang diwariskan turun-temurun.",
          isi: [
            "Teks cerita rakyat adalah kisah anonim yang berkembang di masyarakat tradisional secara lisan. Cerita rakyat mencerminkan nilai-nilai, kepercayaan, dan kearifan lokal suatu daerah.",
            "",
            "Ciri-ciri teks cerita rakyat:",
            "• Disampaikan secara lisan dan turun-temurun (tradisi lisan)",
            "• Bersifat anonim — tidak diketahui pengarangnya",
            "• Mengandung pesan moral atau amanat yang mendidik",
            "• Menggunakan alur maju (kronologis) yang sederhana",
            "• Tokoh digambarkan secara stereotip (baik sekali / jahat sekali)",
            "• Latar bersifat tradisional: kerajaan, hutan, desa, zaman dahulu",
            "• Sering menggunakan kata-kata arkais dan ungkapan tradisional",
            "",
            "Fungsi cerita rakyat dalam masyarakat:",
            "✓ Sebagai hiburan (fungsi rekreatif)",
            "✓ Sebagai media pendidikan moral dan budi pekerti",
            "✓ Sebagai alat pemelihara norma dan nilai sosial",
            "✓ Sebagai penguat identitas budaya suatu daerah",
            "",
            "PENTING: Cerita rakyat berbeda dengan dongeng biasa. Cerita rakyat memiliki fungsi sosial-budaya yang lebih kuat dan diyakini oleh masyarakat pendukungnya, meskipun tidak selalu dianggap benar-benar terjadi.",
          ],
          contoh: [
            "Contoh cerita rakyat terkenal dari berbagai daerah:",
            "• Legenda Malin Kundang (Sumatra Barat) — kisah anak durhaka yang dikutuk menjadi batu",
            "• Fabel Si Kancil dan Buaya (Jawa) — kisah Kancil yang cerdik menipu buaya",
            "• Legenda Tangkuban Perahu (Jawa Barat) — asal-usul Gunung Tangkuban Perahu",
            "• Fabel Kura-kura dan Monyet — kisah persahabatan yang berujung pengkhianatan",
            "• Legenda Danau Toba (Sumatra Utara) — asal-usul terbentuknya Danau Toba",
            "",
            "Setiap cerita rakyat di atas mengandung nilai moral dan kearifan lokal yang dapat dipetik sebagai pelajaran hidup.",
          ],
        },
        {
          judul: "2. Jenis-Jenis Cerita Rakyat: Fabel dan Legenda",
          isi: [
            "Cerita rakyat memiliki beberapa jenis berdasarkan tokoh dan latar belakang ceritanya. Dua jenis utama yang dipelajari di kelas VII adalah fabel dan legenda.",
            "",
            "A. Fabel",
            "• Cerita yang tokoh utamanya adalah hewan yang berperilaku seperti manusia",
            "• Hewan dalam fabel dapat berbicara, berpikir, dan memiliki emosi seperti manusia",
            "• Tujuan utama: menyampaikan pesan moral melalui tingkah laku hewan",
            "• Tokoh hewan mewakili sifat-sifat manusia tertentu",
            "  — Kancil: cerdik, licik",
            "  — Kura-kura: lambat tapi tekun",
            "  — Serigala: rakus dan licik",
            "  — Semut: rajin dan pekerja keras",
            "• Contoh fabel Nusantara: Si Kancil, Kura-kura dan Monyet, Gajah dan Semut",
            "",
            "B. Legenda",
            "• Cerita rakyat yang dianggap benar-benar terjadi oleh masyarakat setempat",
            "• Tokoh: manusia biasa yang memiliki kesaktian atau hubungan dengan alam gaib",
            "• Latar: tempat-tempat yang benar-benar ada di dunia nyata",
            "• Fungsi: menjelaskan asal-usul suatu tempat, benda, atau tradisi",
            "• Sering disebut 'cerita asal-usul' (origin story)",
            "• Contoh legenda Nusantara: Malin Kundang, Tangkuban Perahu, Danau Toba, Roro Jonggrang",
            "",
            "PENTING: Jangan tertukar! Fabel identik dengan tokoh hewan dan bersifat fiktif penuh. Legenda memiliki tokoh manusia dan diyakini kebenarannya oleh masyarakat setempat.",
          ],
          contoh: [
            "Perbandingan Fabel vs Legenda:",
            "",
            "| Aspek | Fabel | Legenda |",
            "|-------|-------|---------|",
            "| Tokoh | Hewan berperilaku seperti manusia | Manusia (biasa atau sakti) |",
            "| Latar | Hutan, sungai, alam bebas | Tempat nyata (gunung, danau, desa) |",
            "| Sifat | Fiktif murni | Diyakini benar-benar terjadi |",
            "| Fungsi | Pendidikan moral | Asal-usul tempat/tradisi |",
            "| Contoh | Si Kancil | Malin Kundang |",
          ],
        },
        {
          judul: "3. Struktur Teks Cerita Rakyat",
          isi: [
            "Teks cerita rakyat memiliki struktur yang khas dan berbeda dengan jenis teks lain. Struktur ini membantu pembaca memahami jalan cerita secara runtut.",
            "",
            "1. Orientasi (Pembukaan)",
            "  • Memperkenalkan tokoh, latar tempat, latar waktu, dan suasana cerita",
            "  • Memberikan gambaran awal tentang siapa, di mana, dan kapan cerita berlangsung",
            "  • Contoh: \"Pada zaman dahulu, di sebuah desa di Sumatra Barat, hiduplah seorang janda miskin bersama anaknya yang bernama Malin Kundang.\"",
            "",
            "2. Komplikasi (Konflik)",
            "  • Munculnya masalah atau pertentangan antara tokoh",
            "  • Konflik berkembang dari yang ringan menjadi semakin serius",
            "  • Bagian ini merupakan inti cerita yang membuat pembaca penasaran",
            "  • Contoh: Malin Kundang pergi merantau, sukses, lalu pulang dan tidak mengakui ibunya yang miskin.",
            "",
            "3. Resolusi (Penyelesaian)",
            "  • Konflik mulai menemukan jalan keluar",
            "  • Tokoh mendapatkan akibat dari perbuatannya (dalam fabel/legenda, biasanya bersifat karma)",
            "  • Contoh: Malin Kundang dikutuk menjadi batu karena durhaka kepada ibunya.",
            "",
            "4. Koda (Amanat/Pesan Moral)",
            "  • Bagian penutup yang berisi pesan moral dari cerita",
            "  • Kadang disampaikan secara eksplisit, kadang implisit",
            "  • Contoh: \"Dari cerita ini kita belajar bahwa anak harus berbakti kepada orang tua.\"",
            "",
            "Tips Membaca struktur cerita rakyat: Bacalah cerita sekali penuh, lalu identifikasi bagian orientasi, komplikasi, resolusi, dan kodanya. Tandai kalimat-kalimat kunci yang menandai perpindahan antarbagian.",
          ],
          contoh: [
            "Contoh analisis struktur pada fabel 'Si Kancil dan Buaya':",
            "",
            "Orientasi: \"Si Kancil berjalan-jalan di tepi sungai. Ia merasa lapar dan ingin menyeberang ke seberang yang penuh rumput hijau.\"",
            "",
            "Komplikasi: \"Namun, sungai itu lebar dan penuh buaya yang kelaparan. Para buaya berjanji akan memakan Kancil jika ia berani menyeberang.\"",
            "",
            "Resolusi: \"Kancil berkata pada buaya, 'Aku membawa daging segar untuk kalian. Berbarislah dari sini ke seberang, hitung jumlah kalian.' Buaya-buaya berbaris. Kancil melompat-lompat dari punggung buaya hingga sampai ke seberang dengan selamat.\"",
            "",
            "Koda: \"Kecerdikan dapat mengalahkan kekuatan. Namun, jangan meniru Kancil yang suka berbohong.\"",
          ],
        },
        {
          judul: "4. Unsur Intrinsik Cerita Rakyat",
          isi: [
            "Unsur intrinsik adalah unsur-unsur yang membangun cerita dari dalam. Memahami unsur intrinsik membantu kita menganalisis dan mengapresiasi cerita rakyat secara lebih mendalam.",
            "",
            "1. Tema",
            "• Gagasan pokok yang mendasari cerita",
            "• Contoh tema: keteguhan hati, durhaka pada orang tua, persahabatan, kejujuran",
            "• Tema pada fabel dan legenda biasanya bersifat universal dan abadi",
            "",
            "2. Tokoh dan Penokohan",
            "• Tokoh: pelaku dalam cerita (manusia/hewan/makhluk lain)",
            "• Penokohan: cara pengarang menggambarkan watak tokoh",
            "• Tokoh dibedakan menjadi: protagonis (baik), antagonis (jahat), tritagonis (penengah)",
            "• Dalam cerita rakyat, tokoh biasanya bersifat hitam-putih (baik vs jahat)",
            "",
            "3. Alur (Plot)",
            "• Rangkaian peristiwa yang membentuk cerita",
            "• Alur dalam cerita rakyat biasanya alur maju (kronologis)",
            "• Tahapan: pengenalan → konflik → klimaks → antiklimaks → penyelesaian",
            "",
            "4. Latar (Setting)",
            "• Tempat, waktu, dan suasana terjadinya cerita",
            "• Latar tempat: hutan, sungai, istana, desa, gunung",
            "• Latar waktu: pagi, siang, malam, zaman dahulu",
            "• Latar suasana: mencekam, gembira, haru, tegang",
            "",
            "5. Amanat (Pesan Moral)",
            "• Pesan yang ingin disampaikan pengarang kepada pembaca",
            "• Dalam cerita rakyat, pesan moral biasanya disampaikan secara eksplisit di bagian koda",
            "• Contoh: \"Berbaktilah kepada orang tuamu.\"",
            "",
            "Tips Menganalisis: Gunakan peta pikiran (mind map) untuk memetakan unsur intrinsik setiap cerita rakyat yang dibaca.",
          ],
          contoh: [
            "Analisis unsur intrinsik Fabel 'Kura-kura dan Monyet':",
            "",
            "Tema: Persahabatan dan pengkhianatan",
            "Tokoh: Kura-kura (baik, lugu, sabar), Monyet (licik, serakah, pengkhianat)",
            "Alur: Kura-kura dan Monyet berteman → menanam pisang bersama → Monyet curang → Kura-kura diusir → Kura-kura balas dendam dengan cara baik → Monyet mendapat pelajaran",
            "Latar: Hutan, kebun pisang, tepi sungai",
            "Amanat: Kesabaran dan kebaikan hati pada akhirnya akan menang, sementara keserakahan akan mendapat ganjarannya.",
          ],
        },
        {
          judul: "5. Kaidah Kebahasaan Cerita Rakyat",
          isi: [
            "Teks cerita rakyat memiliki ciri bahasa yang khas. Memahami kaidah kebahasaan membantu kita menulis cerita rakyat dengan lebih baik.",
            "",
            "1. Kata Kerja Tindakan (Verba Aktif)",
            "• Kata kerja yang menunjukkan perbuatan tokoh",
            "• Contoh: berlari, memakan, berkata, memukul, menangis, melompat",
            "• Fungsinya: menggerakkan cerita dan menggambarkan aksi tokoh",
            "• \"Si Kancil melompat kegirangan.\"",
            "",
            "2. Kata Ganti (Pronomina)",
            "• Menggantikan nama tokoh agar tidak berulang-ulang",
            "• Contoh: ia, dia, mereka, -nya",
            "• \"Malin Kundang berlayar. Ia tidak pernah kembali selama bertahun-tahun.\"",
            "",
            "3. Konjungsi Temporal (Kata Hubung Waktu)",
            "• Kata hubung yang menunjukkan urutan waktu",
            "• Contoh: kemudian, setelah itu, pada suatu hari, akhirnya, sementara itu, tiba-tiba",
            "• \"Pada suatu hari, Kancil berjalan-jalan. Tiba-tiba, ia melihat buaya.\"",
            "",
            "4. Kata Keterangan Waktu dan Tempat",
            "• Menjelaskan kapan dan di mana peristiwa terjadi",
            "• Contoh: pada zaman dahulu, di tepi hutan, suatu hari, keesokan harinya",
            "",
            "5. Kalimat Langsung (Dialog)",
            "• Menggambarkan percakapan antartokoh",
            "• Menggunakan tanda petik (\"...\") dan kata kerja pengiring (berkata, bertanya, menjawab)",
            "• Contoh: \"Hai Kancil, mau ke mana kau?\" tanya buaya.",
            "",
            "6. Kata Arkais (Bahasa Lama)",
            "• Kata-kata yang jarang digunakan dalam percakapan sehari-hari",
            "• Contoh: sahaya (saya), baginda (raja), hamba (saya), konon (kata orang), syahdan (maka)",
            "• Memberi nuansa 'zaman dahulu' pada cerita",
          ],
          rangkuman: [
            "Ingat rumus 'AKAK-DK' untuk kaidah kebahasaan cerita rakyat:",
            "A = Aksi (kata kerja tindakan)",
            "K = Kata ganti (pronomina)",
            "A = Aturan waktu (konjungsi temporal)",
            "K = Keterangan waktu/tempat",
            "D = Dialog (kalimat langsung)",
            "K = Kuno (kata arkais)",
          ],
        },
        {
          judul: "6. Nilai-Nilai dalam Cerita Rakyat",
          isi: [
            "Cerita rakyat tidak hanya menghibur, tetapi juga mengandung nilai-nilai luhur yang dapat diterapkan dalam kehidupan sehari-hari.",
            "",
            "1. Nilai Moral",
            "• Ajaran tentang baik dan buruk dalam kehidupan",
            "• Contoh: berbakti pada orang tua, jujur, tidak serakah, tolong-menolong",
            "• Dalam fabel 'Kura-kura dan Monyet': keserakahan membawa celaka",
            "• Dalam legenda 'Malin Kundang': anak durhaka akan mendapat ganjaran",
            "",
            "2. Nilai Sosial",
            "• Hubungan antarmanusia dalam masyarakat",
            "• Contoh: gotong royong, saling menghormati, musyawarah",
            "• Dalam fabel 'Gajah dan Semut': meskipun kecil, semut dapat membantu gajah",
            "",
            "3. Nilai Budaya",
            "• Tradisi, adat istiadat, dan kepercayaan masyarakat",
            "• Legenda danau, gunung, dan tempat keramat mencerminkan hubungan manusia dengan alam",
            "• Contoh: upacara adat yang digambarkan dalam cerita rakyat",
            "",
            "4. Nilai Religius",
            "• Ajaran keagamaan dan kepercayaan kepada Tuhan",
            "• Contoh: kekuatan doa, kutukan sebagai akibat dosa, takdir",
            "",
            "5. Nilai Pendidikan",
            "• Pelajaran yang dapat dipetik dan diterapkan",
            "• Contoh: tekun belajar, rendah hati, berani mengakui kesalahan",
            "",
            "PENTING: Satu cerita rakyat biasanya mengandung lebih dari satu nilai. Identifikasilah nilai-nilai tersebut saat membaca cerita rakyat, lalu diskusikan dengan teman bagaimana menerapkannya dalam kehidupan sekarang.",
          ],
        },
        {
          judul: "7. Prosedur Menulis Kembali Cerita Rakyat",
          isi: [
            "Setelah memahami struktur, unsur, dan nilai cerita rakyat, saatnya berlatih memproduksi teks cerita rakyat. Ikuti langkah-langkah berikut:",
            "",
            "Langkah 1: Pilih Cerita Rakyat",
            "• Pilih satu cerita rakyat yang sudah dikenal (fabel atau legenda)",
            "• Baca kembali dengan saksama untuk memahami alur dan detailnya",
            "",
            "Langkah 2: Catat Struktur Cerita",
            "• Bagi cerita menjadi bagian orientasi, komplikasi, resolusi, koda",
            "• Tulis poin-poin penting setiap bagian",
            "",
            "Langkah 3: Gunakan Bahasa Sendiri",
            "• Tulis ulang dengan bahasa yang mudah dipahami",
            "• Pertahankan alur dan pesan moral aslinya",
            "• Gunakan kata-kata sendiri, jangan menyalin mentah-mentah",
            "",
            "Langkah 4: Sematkan Kaidah Kebahasaan",
            "• Gunakan kata kerja aktif, konjungsi temporal, dialog",
            "• Tambahkan kata arkais secukupnya untuk nuansa tradisional",
            "• Gunakan latar yang jelas (waktu, tempat, suasana)",
            "",
            "Langkah 5: Sunting dan Revisi",
            "• Periksa kembali: apakah struktur sudah lengkap?",
            "• Periksa ejaan, tanda baca, dan pilihan kata",
            "• Apakah pesan moral tersampaikan dengan jelas?",
            "• Minta teman membaca dan memberi masukan",
            "",
            "Langkah 6: Sajikan dengan Menarik",
            "• Beri judul yang menarik",
            "• Tambahkan ilustrasi jika perlu",
            "• Bacakan di depan kelas atau unggah di platform kelas digital",
          ],
          rangkuman: [
            "Rumus menulis cerita rakyat: PILIH → CATAT → TULIS → SEMATKAN → SUNING → SAJIKAN",
            "",
            "Tips: Pilih cerita rakyat yang kamu kuasai dengan baik. Semakin paham cerita aslinya, semakin mudah menuliskan kembali dengan bahasamu sendiri.",
          ],
        },
      ],
    },
    latihan: [
      {
        id: 1,
        tipe: "PG",
        soal: "Cerita rakyat yang tokoh utamanya hewan yang berperilaku seperti manusia disebut...",
        opsi: ["Legenda", "Fabel", "Mite", "Sage"],
        jawaban: 1,
        penjelasan: "Fabel adalah cerita rakyat dengan tokoh hewan yang berperilaku seperti manusia.",
      },
      {
        id: 2,
        tipe: "PG",
        soal: "Malin Kundang termasuk jenis cerita rakyat...",
        opsi: ["Fabel", "Mite", "Legenda", "Dongeng biasa"],
        jawaban: 2,
        penjelasan: "Malin Kundang adalah legenda dari Sumatra Barat yang menceritakan asal-usul Batu Malin Kundang.",
      },
      {
        id: 3,
        tipe: "PG",
        soal: "Berikut yang bukan merupakan ciri-ciri teks cerita rakyat adalah...",
        opsi: ["Disampaikan secara lisan", "Bersifat anonim", "Memiliki pengarang yang jelas", "Mengandung pesan moral"],
        jawaban: 2,
        penjelasan: "Cerita rakyat bersifat anonim, artinya tidak diketahui pengarangnya.",
      },
      {
        id: 4,
        tipe: "PG",
        soal: "Bagian struktur cerita rakyat yang berisi pesan moral adalah...",
        opsi: ["Orientasi", "Komplikasi", "Resolusi", "Koda"],
        jawaban: 3,
        penjelasan: "Koda adalah bagian penutup yang berisi amanat atau pesan moral dari cerita.",
      },
      {
        id: 5,
        tipe: "PG",
        soal: "Kata 'konon', 'syahdan', dan 'baginda' termasuk dalam kaidah kebahasaan...",
        opsi: ["Konjungsi temporal", "Kata arkais", "Kata kerja tindakan", "Kalimat langsung"],
        jawaban: 1,
        penjelasan: "Kata arkais adalah kata-kata lama atau kuno yang jarang digunakan dalam percakapan sehari-hari, memberi nuansa zaman dahulu.",
      },
      {
        id: 6,
        tipe: "PG",
        soal: "Berikut ini yang membedakan fabel dan legenda adalah...",
        opsi: ["Fabel bersifat anonim, legenda tidak", "Fabel tokohnya hewan, legenda tokohnya manusia", "Fabel tidak memiliki pesan moral, legenda memiliki", "Fabel lebih panjang dari legenda"],
        jawaban: 1,
        penjelasan: "Perbedaan utama: fabel bertokoh hewan berperilaku manusia, sedangkan legenda bertokoh manusia.",
      },
      {
        id: 7,
        tipe: "PG",
        soal: "Contoh konjungsi temporal yang tepat dalam cerita rakyat adalah...",
        opsi: ["dan, atau, tetapi", "karena, sehingga, meskipun", "kemudian, setelah itu, akhirnya", "yang, di, ke"],
        jawaban: 2,
        penjelasan: "Konjungsi temporal menunjukkan urutan waktu: kemudian, setelah itu, akhirnya, pada suatu hari, dll.",
      },
      {
        id: 8,
        tipe: "PG",
        soal: "Nilai yang berkaitan dengan ajaran baik dan buruk dalam cerita rakyat disebut nilai...",
        opsi: ["Sosial", "Budaya", "Moral", "Pendidikan"],
        jawaban: 2,
        penjelasan: "Nilai moral adalah ajaran tentang perbuatan baik dan buruk yang dapat dipetik dari cerita.",
      },
      {
        id: 9,
        tipe: "PG",
        soal: "Bagian cerita yang memperkenalkan tokoh, tempat, dan waktu disebut...",
        opsi: ["Orientasi", "Komplikasi", "Klimaks", "Koda"],
        jawaban: 0,
        penjelasan: "Orientasi memperkenalkan siapa (tokoh), di mana (tempat), kapan (waktu), dan bagaimana (suasana) cerita berlangsung.",
      },
      {
        id: 10,
        tipe: "PG",
        soal: "Salah satu nilai budaya dalam legenda Tangkuban Perahu adalah...",
        opsi: ["Cara membuat perahu", "Hormat pada orang tua", "Asal-usul gunung dan hubungannya dengan adat Sunda", "Teknik bercocok tanam"],
        jawaban: 2,
        penjelasan: "Legenda Tangkuban Perahu mengandung nilai budaya karena menjelaskan asal-usul Gunung Tangkuban Perahu yang berkaitan dengan kepercayaan dan tradisi masyarakat Sunda.",
      },
    ],
    praktik: {
      tujuan: "Menulis kembali cerita rakyat dengan bahasa sendiri secara runtut dan menarik.",
      instruksi: "Pilihlah satu cerita rakyat (fabel atau legenda) yang kamu kenal. Tuliskan kembali dengan bahasamu sendiri dengan mengikuti langkah-langkah yang telah dipelajari.",
      langkah: [
        "Pilih satu cerita rakyat Nusantara yang kamu sukai (contoh: Si Kancil, Malin Kundang, Danau Toba, Roro Jonggrang, dll.)",
        "Baca cerita aslinya dengan saksama. Catat tokoh, alur, latar, dan pesan moralnya.",
        "Buat kerangka cerita berdasarkan struktur: orientasi → komplikasi → resolusi → koda.",
        "Kembangkan kerangka menjadi cerita utuh menggunakan bahasamu sendiri.",
        "Gunakan kaidah kebahasaan: kata kerja tindakan, konjungsi temporal, dialog, dan kata arkais secukupnya.",
        "Periksa kembali: apakah struktur sudah lengkap? Apakah pesan moral tersampaikan? Perbaiki ejaan dan tanda baca.",
        "Mintalah teman membaca ceritamu dan memberi masukan. Revisi jika perlu.",
        "Kumpulkan dalam bentuk tulisan rapi (boleh ditambah ilustrasi) dan presentasikan di depan kelas.",
      ],
      tips: [
        "Pilih cerita yang paling kamu kuasai agar lebih lancar menulis.",
        "Gunakan kata 'Pada zaman dahulu...' atau 'Konon...' sebagai pembuka yang menarik.",
        "Jangan takut mengubah gaya bahasa, yang penting alur dan pesan moral tetap sama.",
        "Baca hasil tulisan dengan suara keras untuk memeriksa keruntutan cerita.",
      ],
      contoh: "Lihat contoh analisis struktur fabel 'Si Kancil dan Buaya' pada materi Struktur Teks Cerita Rakyat di atas sebagai panduan.",
    },
    kuis: [
      {
        id: 1,
        tipe: "PG",
        soal: "Siapa tokoh utama dalam legenda Malin Kundang?",
        opsi: ["Seorang raja", "Seorang nelayan miskin", "Seorang anak yang durhaka", "Seekor kancil"],
        jawaban: 2,
        penjelasan: "Malin Kundang adalah anak yang durhaka karena tidak mengakui ibunya setelah sukses merantau.",
      },
      {
        id: 2,
        tipe: "PG",
        soal: "Cerita rakyat yang menjelaskan asal-usul suatu tempat disebut...",
        opsi: ["Fabel", "Mite", "Legenda", "Cerpen"],
        jawaban: 2,
        penjelasan: "Legenda adalah cerita rakyat yang biasanya menjelaskan asal-usul suatu tempat, benda, atau tradisi.",
      },
      {
        id: 3,
        tipe: "PG",
        soal: "Urutan struktur teks cerita rakyat yang benar adalah...",
        opsi: ["Komplikasi → Orientasi → Resolusi → Koda", "Orientasi → Resolusi → Komplikasi → Koda", "Orientasi → Komplikasi → Resolusi → Koda", "Koda → Orientasi → Komplikasi → Resolusi"],
        jawaban: 2,
        penjelasan: "Urutan yang benar: Orientasi (pengenalan) → Komplikasi (konflik) → Resolusi (penyelesaian) → Koda (pesan moral).",
      },
      {
        id: 4,
        tipe: "PG",
        soal: "Berikut ini yang termasuk kata arkais adalah...",
        opsi: ["Rumah", "Syahdan", "Buku", "Meja"],
        jawaban: 1,
        penjelasan: "Syahdan adalah kata arkais yang berarti 'maka' atau 'selanjutnya', biasa digunakan dalam cerita lama.",
      },
      {
        id: 5,
        tipe: "PG",
        soal: "Amanat yang dapat dipetik dari legenda Malin Kundang adalah...",
        opsi: ["Rajinlah bekerja agar menjadi kaya", "Anak harus berbakti kepada orang tua", "Jangan pergi merantau", "Hindari bersahabat dengan orang kaya"],
        jawaban: 1,
        penjelasan: "Pesan utama legenda Malin Kundang adalah pentingnya berbakti kepada orang tua. Durhaka akan mendapat balasan.",
      },
      {
        id: 6,
        tipe: "PG",
        soal: "Kata 'kemudian', 'setelah itu', 'akhirnya' dalam cerita rakyat berfungsi sebagai...",
        opsi: ["Kata kerja", "Kata sifat", "Konjungsi temporal", "Kata ganti"],
        jawaban: 2,
        penjelasan: "Kata-kata tersebut adalah konjungsi temporal yang menunjukkan urutan waktu kejadian dalam cerita.",
      },
      {
        id: 7,
        tipe: "PG",
        soal: "Dalam fabel 'Kura-kura dan Monyet', tokoh kura-kura menggambarkan watak...",
        opsi: ["Licik dan serakah", "Cerdik dan pintar", "Sabar dan baik hati", "Pemarah dan kejam"],
        jawaban: 2,
        penjelasan: "Kura-kura digambarkan sebagai tokoh yang sabar, baik hati, dan lugu, berbeda dengan Monyet yang licik.",
      },
      {
        id: 8,
        tipe: "PG",
        soal: "Perbedaan utama fabel dan legenda terletak pada...",
        opsi: ["Panjang cerita", "Jenis tokohnya", "Bahasa yang digunakan", "Jumlah tokoh"],
        jawaban: 1,
        penjelasan: "Fabel menggunakan tokoh hewan, sedangkan legenda menggunakan tokoh manusia.",
      },
      {
        id: 9,
        tipe: "PG",
        soal: "Bagian cerita di mana konflik mulai muncul dan berkembang disebut...",
        opsi: ["Orientasi", "Komplikasi", "Resolusi", "Koda"],
        jawaban: 1,
        penjelasan: "Komplikasi adalah bagian di mana masalah atau konflik mulai muncul dan berkembang dalam cerita.",
      },
      {
        id: 10,
        tipe: "PG",
        soal: "Tujuan utama fabel adalah...",
        opsi: ["Menjelaskan asal-usul tempat", "Menyampaikan pesan moral melalui perilaku hewan", "Menghibur tanpa pesan tertentu", "Menceritakan kisah nyata"],
        jawaban: 1,
        penjelasan: "Fabel bertujuan menyampaikan pesan moral melalui tingkah laku hewan yang diibaratkan sebagai perilaku manusia.",
      },
    ],
  };

export default konten;
