// @ts-nocheck
import type { Konten } from "../types";

/* =============================================
   Unit 1: Teks Tanggapan Kritis — IX S1
   KD 3.1/4.1 — Mengidentifikasi & Menyusun Teks Tanggapan Kritis
   ============================================= */
const konten: Konten = {
    belajar: {
      tujuan: [
        "Memahami hakikat, ciri, dan tujuan teks tanggapan kritis",
        "Mengidentifikasi struktur teks tanggapan kritis (konteks, deskripsi, evaluasi)",
        "Menganalisis kaidah kebahasaan dalam teks tanggapan kritis",
        "Membedakan jenis tanggapan (pujian, kritik, saran) dan etika dalam menyampaikannya",
        "Menyusun teks tanggapan kritis secara sistematis, objektif, dan santun",
      ],
      materi: [
        {
          judul: "1. Hakikat Teks Tanggapan Kritis",
          catatan: "Tanggapan kritis bukan sekadar komentar — ia adalah evaluasi terstruktur yang didukung data dan alasan logis.",
          isi: [
            "Teks tanggapan kritis adalah teks yang berisi penilaian, ulasan, atau evaluasi terhadap suatu karya (buku, film, lukisan, pidato, artikel, dll.), peristiwa, atau fenomena berdasarkan data dan alasan yang logis. Teks ini menuntut penulisnya untuk berpikir kritis, objektif, dan santun.",
            "",
            "Ciri-ciri teks tanggapan kritis:",
            "• Bersifat objektif — didasarkan pada fakta, bukan opini pribadi semata",
            "• Mengandung alasan logis yang mendukung setiap pernyataan",
            "• Terstruktur dengan jelas: konteks, deskripsi, dan evaluasi",
            "• Menggunakan bahasa yang santun dan tidak emosional",
            "• Bertujuan membangun, bukan menjatuhkan atau menyerang",
            "• Disertai data, contoh, atau bukti yang memperkuat argumen",
            "",
            "Tujuan teks tanggapan kritis:",
            "✓ Memberikan penilaian yang objektif terhadap suatu karya atau fenomena",
            "✓ Menyampaikan apresiasi (pujian) atas kelebihan yang dimiliki",
            "✓ Menyampaikan kritik dan saran yang membangun untuk perbaikan",
            "✓ Membantu pembaca memahami kelebihan dan kekurangan suatu hal",
            "✓ Mendorong terciptanya karya yang lebih baik di masa depan",
            "",
            "PENTING: Tanggapan kritis sangat berbeda dengan 'komen pedas' atau bullying di media sosial. Tanggapan kritis selalu disertai alasan dan bertujuan memperbaiki, bukan menyakiti perasaan orang lain.",
          ],
          contoh: [
            "Contoh tanggapan kritis terhadap novel remaja:",
            "",
            "Konteks: \"Novel 'Laskar Pelangi' karya Andrea Hirata telah menjadi fenomena sastra Indonesia sejak terbit tahun 2005. Novel ini mengisahkan perjuangan sepuluh anak Belitung dalam mengejar pendidikan di tengah keterbatasan.\"",
            "",
            "Deskripsi: \"Novel ini ditulis dengan gaya bahasa yang sederhana namun menyentuh. Andrea Hirata berhasil menggambarkan kemiskinan, semangat juang, dan keindahan mimpi anak-anak desa. Tokoh-tokoh seperti Ikal, Lintang, dan Bu Muslimah terasa hidup dan dekat dengan pembaca.\"",
            "",
            "Evaluasi (pujian): \"Kekuatan utama novel ini terletak pada kemampuannya menginspirasi pembaca. Nilai optimisme dan perjuangan yang ditawarkan sangat relevan bagi generasi muda Indonesia. Cerita ini berhasil membangkitkan kesadaran akan pentingnya pendidikan.\"",
            "",
            "Evaluasi (saran): \"Namun, beberapa bagian cerita terasa terlalu cepat, terutama saat menceritakan masa dewasa tokoh-tokohnya. Alur yang melompat-lompat di bagian akhir sedikit mengurangi kedalaman cerita. Sebaiknya transisi antarbab dibuat lebih halus agar cerita mengalir dengan alami.\"",
          ],
        },
        {
          judul: "2. Struktur Teks Tanggapan Kritis",
          isi: [
            "Teks tanggapan kritis memiliki struktur baku yang terdiri dari tiga bagian utama: konteks, deskripsi, dan evaluasi. Struktur ini membantu penulis menyampaikan tanggapan secara sistematis.",
            "",
            "1. Konteks (Pengantar)",
            "• Berisi latar belakang mengenai hal yang akan ditanggapi",
            "• Menjelaskan secara singkat tentang karya, peristiwa, atau fenomena yang menjadi objek tanggapan",
            "• Fungsi: memberi pembaca gambaran awal sebelum membaca penilaian",
            "• Contoh: \"Film 'Keluarga Cemara' yang dirilis tahun 2018 mengangkat cerita tentang keluarga sederhana yang kehilangan harta bendanya.\"",
            "",
            "2. Deskripsi (Paparan Data)",
            "• Berisi gambaran rinci tentang objek tanggapan",
            "• Menyajikan fakta, data, kutipan, atau contoh konkret dari objek yang dinilai",
            "• Bersifat netral — belum berisi penilaian, baru pemaparan",
            "• Fungsi: memberikan bukti yang akan digunakan sebagai dasar penilaian",
            "• Contoh: \"Film ini disutradarai oleh Yandy Laurens dan dibintangi oleh Nirina Zubir, Ringgo Agus Rahman, serta Adhisty Zara. Durasi film sekitar 110 menit dengan genre drama keluarga.\"",
            "",
            "3. Evaluasi (Penilaian)",
            "• Bagian inti yang berisi penilaian, ulasan, atau tanggapan terhadap objek",
            "• Menyebutkan kelebihan dan/atau kekurangan disertai alasan logis",
            "• Dibagi menjadi: evaluasi positif (pujian) dan evaluasi negatif (kritik/saran)",
            "• Fungsi: menyampaikan pendapat penulis secara santun dan argumentatif",
            "• Contoh (positif): \"Film ini berhasil menyampaikan pesan tentang kesederhanaan dan kebersamaan keluarga secara menyentuh tanpa terkesan menggurui.\"",
            "• Contoh (saran): \"Namun, konflik pada pertengahan film terasa sedikit lambat. Penambahan konflik pendukung bisa membuat cerita lebih dinamis.\"",
            "",
            "Tips Membaca struktur: Saat membaca teks tanggapan kritis, cari kata kunci seperti 'secara umum', 'dari segi', 'kelebihan', 'kekurangan', 'sebaiknya' untuk mengidentifikasi bagian evaluasi.",
          ],
          contoh: [
            "Contoh struktur lengkap tanggapan kritis terhadap lagu daerah:",
            "",
            "[KONTEKS]",
            "Lagu 'Ampar-Ampar Pisang' adalah lagu daerah dari Kalimantan Selatan yang sangat populer di seluruh Nusantara. Lagu ini sering dinyanyikan dalam acara-acara budaya dan pelajaran seni musik di sekolah.",
            "",
            "[DESKRIPSI]",
            "Lagu ini memiliki tempo riang dan lirik yang menceritakan tentang pisang yang diampar (dijemur) serta kepiting yang menyelinap di bawahnya. Melodi lagu cukup sederhana, hanya menggunakan beberapa nada dasar, sehingga mudah dinyanyikan oleh anak-anak.",
            "",
            "[EVALUASI]",
            "Kelebihan: Lagu 'Ampar-Ampar Pisang' sangat mudah diingat dan dinyanyikan karena melodinya yang ceria. Liriknya juga mengandung unsur kearifan lokal yang memperkenalkan budaya Kalimantan Selatan kepada generasi muda.",
            "",
            "Kekurangan: Namun, lirik lagu ini menggunakan bahasa daerah Banjar sehingga tidak semua masyarakat Indonesia memahami artinya. Akan lebih baik jika dalam penyajiannya disertakan terjemahan atau penjelasan makna lirik agar pesan lagu tersampaikan secara utuh.",
          ],
        },
        {
          judul: "3. Kaidah Kebahasaan Teks Tanggapan Kritis",
          isi: [
            "Teks tanggapan kritis memiliki ciri kebahasaan yang khas. Memahami kaidah ini membantu kamu menulis tanggapan yang efektif dan meyakinkan.",
            "",
            "1. Kalimat Kompleks",
            "• Menggunakan kalimat majemuk setara dan bertingkat",
            "• Menghubungkan gagasan secara logis: sebab-akibat, syarat, tujuan, dll.",
            "• Contoh: \"Novel ini layak dibaca karena menyuguhkan cerita yang inspiratif sekaligus menghibur.\"",
            "",
            "2. Konjungsi Intrakalimat dan Antarkalimat",
            "• Konjungsi intrakalimat: dan, atau, tetapi, karena, sehingga",
            "• Konjungsi antarkalimat: oleh karena itu, selain itu, di samping itu, dengan demikian",
            "• Contoh: \"Lukisan ini menggunakan komposisi warna yang kuat. Selain itu, teknik kuas yang digunakan sangat detail pada bagian latar.\"",
            "",
            "3. Kata Sifat (Adjektiva) untuk Menilai",
            "• Menggunakan kata sifat yang menunjukkan penilaian",
            "• Contoh positif: menarik, inspiratif, memukau, sederhana, cemerlang",
            "• Contoh negatif: membosankan, lemah, kurang tepat, ambigu, monoton",
            "• Contoh: \"Penokohan dalam novel ini sangat kuat dan meyakinkan.\"",
            "",
            "4. Kalimat Persuasif",
            "• Kalimat yang bersifat mengajak atau merekomendasikan",
            "• Contoh: \"Sebaiknya penulis menambahkan latar belakang tokoh agar cerita lebih kaya.\"",
            "• Contoh: \"Film ini sangat direkomendasikan bagi pencinta drama keluarga.\"",
            "",
            "5. Istilah Teknis",
            "• Menggunakan istilah yang berkaitan dengan objek yang ditanggapi",
            "• Contoh (tanggapan film): sinematografi, akting, alur, setting, karakterisasi",
            "• Contoh (tanggapan buku): gaya bahasa, diksi, plot, latar, sudut pandang",
            "",
            "6. Kata Rujukan (Penunjuk) untuk Membandingkan",
            "• Kata: seperti, sebagaimana, berbeda dengan, dibandingkan dengan",
            "• Contoh: \"Berbeda dengan film sebelumnya, sekuel ini lebih fokus pada pengembangan karakter.\"",
          ],
          rangkuman: [
            "Rumus kaidah kebahasaan teks tanggapan kritis: 'KIS-PERI'",
            "K = Kalimat kompleks (majemuk)",
            "I = Istilah teknis sesuai objek",
            "S = Sifat (adjektiva penilaian)",
            "P = Persuasif (rekomendasi/saran)",
            "E = Evaluatif (kata yang menunjukkan penilaian)",
            "R = Rujukan (perbandingan)",
            "I = Intrakalimat & Antarkalimat (konjungsi)",
          ],
        },
        {
          judul: "4. Jenis Tanggapan: Pujian, Kritik, dan Saran",
          isi: [
            "Dalam teks tanggapan kritis, terdapat tiga jenis tanggapan yang masing-masing memiliki fungsi dan cara penyampaian yang berbeda.",
            "",
            "A. Pujian (Apresiasi)",
            "• Pernyataan positif terhadap kelebihan suatu karya atau fenomena",
            "• Harus disertai alasan yang jelas, bukan sekadar 'bagus' atau 'keren'",
            "• Contoh: \"Lukisan ini sangat menarik karena penggunaan warna komplementer yang berani dan teknik impasto yang memberikan tekstur unik pada permukaan kanvas.\"",
            "• Fungsi: memberikan penguatan dan motivasi kepada pencipta karya",
            "",
            "B. Kritik (Evaluasi Negatif)",
            "• Pernyataan tentang kekurangan atau kelemahan suatu karya",
            "• Bukan untuk menjatuhkan, melainkan untuk perbaikan",
            "• Harus konstruktif dan disertai bukti konkret",
            "• Contoh: \"Sayangnya, alur cerita di bagian tengah terasa lambat. Adegan-adegan yang tidak esensial membuat film kehilangan ketegangan.\"",
            "• Fungsi: menunjukkan aspek yang perlu diperbaiki",
            "",
            "C. Saran (Rekomendasi)",
            "• Usulan konkret untuk perbaikan atau pengembangan",
            "• Saran melengkapi kritik — setelah menyebut kekurangan, beri solusi",
            "• Contoh: \"Penulis sebaiknya menambahkan konflik sampingan yang memperkuat karakter utama agar cerita tidak terasa datar. Alternatifnya, latar waktu bisa dibuat lebih bervariasi.\"",
            "• Fungsi: memberikan solusi atas kekurangan yang diidentifikasi",
            "",
            "PENTING: Dalam satu teks tanggapan kritis yang baik, ketiga jenis tanggapan ini biasanya hadir secara seimbang. Teks yang hanya berisi pujian terkesan tidak kritis. Teks yang hanya berisi kritik terkesan negatif dan tidak membangun.",
          ],
          contoh: [
            "Perbandingan ketiga jenis tanggapan untuk objek yang sama (sebuah pidato ketua OSIS):",
            "",
            "| Jenis | Contoh | Tujuan |",
            "|-------|--------|--------|",
            "| Pujian | \"Pidato Anda sangat terstruktur dengan pembukaan yang kuat. Penggunaan data jumlah prestasi tahun ini sebagai pembuka sangat efektif menarik perhatian.\" | Memperkuat hal yang sudah baik |",
            "| Kritik | \"Namun, intonasi pada saat menyampaikan poin ketiga hingga kelima cenderung monoton, sehingga audiens mulai kehilangan fokus.\" | Menunjukkan kekurangan secara objektif |",
            "| Saran | \"Sebaiknya, latih intonasi dengan memberi jeda di poin-poin penting dan variasikan volume suara. Coba gunakan gestur tangan yang lebih ekspresif untuk mempertahankan perhatian audiens.\" | Memberi solusi perbaikan |",
          ],
        },
        {
          judul: "5. Etika dalam Memberi Tanggapan",
          isi: [
            "Memberi tanggapan bukan hanya soal apa yang disampaikan, tetapi juga bagaimana cara menyampaikannya. Etika dalam bertanggapan sangat penting agar pesan kita diterima dengan baik.",
            "",
            "1. Gunakan Bahasa yang Santun",
            "• Hindari kata-kata kasar, merendahkan, atau menyakitkan",
            "• Gunakan ungkapan yang halus seperti 'menurut pendapat saya', 'sebaiknya', 'akan lebih baik jika'",
            "• Jangan menggunakan kata 'jelek', 'bodoh', 'payah', atau istilah merendahkan lainnya",
            "",
            "2. Objektif dan Berdasarkan Data",
            "• Jangan menilai berdasarkan perasaan pribadi atau prasangka",
            "• Dukung setiap pernyataan dengan bukti, contoh, atau data",
            "• Bedakan antara fakta dan opini pribadi",
            "",
            "3. Hargai Karya Orang Lain",
            "• Akui usaha dan kerja keras pencipta karya",
            "• Mulailah dengan hal positif sebelum menyampaikan kritik (metode 'sandwich': positif - negatif - positif)",
            "• Ingat bahwa setiap karya memiliki nilai meskipun tidak sempurna",
            "",
            "4. Fokus pada Karya, Bukan Pembuatnya",
            "• Kritik ditujukan pada karya, bukan pribadi pembuatnya",
            "• Jangan menyerang karakter atau kepribadian seseorang",
            "• Contoh SALAH: \"Kamu memang tidak berbakat menulis.\"",
            "• Contoh BENAR: \"Tulisan ini membutuhkan pengembangan karakter yang lebih dalam.\"",
            "",
            "5. Beri Saran, Bukan Sekadar Mengeluh",
            "• Jika menemukan kekurangan, sertakan saran perbaikan",
            "• Kritik tanpa solusi adalah keluhan, bukan tanggapan kritis",
            "",
            "6. Bersikap Terbuka terhadap Tanggapan Balik",
            "• Jika kita memberi tanggapan pada orang lain, kita juga harus siap menerima tanggapan",
            "• Jadikan diskusi sebagai ajang belajar bersama, bukan perdebatan",
            "",
            "PENTING: Ingat prinsip 'Berkata baik atau diam' — sampaikan tanggapan dengan cara yang kamu sendiri ingin diperlakukan jika karyamu ditanggapi orang lain.",
          ],
          contoh: [
            "Contoh perbandingan tanggapan yang tidak santun VS santun:",
            "",
            "TIDAK SANTUN: \"Gambar ini jelek banget. Warnanya norak dan orangnya gak proporsional. Kamu harus les lagi deh.\"",
            "",
            "SANTUN: \"Menurut pendapat saya, gambar ini memiliki ide yang unik, terutama pada pemilihan tema alam. Namun, proporsi tubuh tokoh utama masih perlu diperbaiki agar terlihat lebih natural. Saya sarankan untuk banyak berlatih menggambar anatomi dasar. Semangat terus!\"",
          ],
        },
        {
          judul: "6. Membedakan Tanggapan Kritis dengan Opini Biasa",
          isi: [
            "Banyak orang mengira setiap pendapat adalah tanggapan kritis. Padahal, tidak semua opini bisa disebut sebagai tanggapan kritis. Mari pahami perbedaannya.",
            "",
            "A. Opini Biasa",
            "• Hanya berisi perasaan atau kesan pribadi",
            "• Tidak disertai alasan, data, atau bukti",
            "• Cenderung subjektif (suka/tidak suka, bagus/jelek)",
            "• Sering bersifat emosional dan spontan",
            "• Contoh: \"Film ini keren banget!\" atau \"Buku itu membosankan.\"",
            "",
            "B. Tanggapan Kritis",
            "• Berisi penilaian yang didukung alasan dan bukti logis",
            "• Mengikuti struktur: konteks - deskripsi - evaluasi",
            "• Objektif dan berimbang (menyebut kelebihan dan kekurangan)",
            "• Menggunakan bahasa yang santun dan argumentatif",
            "• Bertujuan membangun dan memberikan perspektif baru",
            "• Contoh: \"Film ini patut diapresiasi karena sinematografinya yang memukau, terutama pada adegan pantai saat matahari terbit. Namun, konflik utama terasa kurang tajam karena penjelasan latar belakang tokoh yang minim. Sebaiknya penulis naskah menambahkan prolog singkat untuk memperkuat motivasi tokoh.\"",
            "",
            "Perbedaan utama:",
            "✓ Opini biasa: 'Saya suka' atau 'Saya tidak suka' tanpa alasan",
            "✓ Tanggapan kritis: 'Saya menilai demikian karena...' disertai bukti",
            "",
            "PENTING: Di era media sosial saat ini, banyak opini biasa yang dikemas seolah-olah tanggapan kritis. Jadilah pribadi yang kritis: biasakan bertanya 'mengapa?' dan 'apa buktinya?' sebelum menerima atau menyampaikan suatu pendapat.",
          ],
          contoh: [
            "Perbandingan opini biasa vs tanggapan kritis pada objek yang sama (sebuah artikel opini di koran):",
            "",
            "OPINI BIASA: \"Artikel ini bagus, setuju!\"",
            "",
            "TANGGAPAN KRITIS: \"Artikel ini menyajikan argumen yang kuat tentang pentingnya literasi digital di kalangan remaja. Penulis berhasil menggunakan data dari survei Kominfo 2023 yang menunjukkan peningkatan 40% penggunaan internet pada usia 13-18 tahun. Argumentasi tentang kurikulum digital di poin ketiga sangat relevan dengan kondisi saat ini. Namun, solusi yang ditawarkan di bagian akhir masih bersifat umum. Akan lebih baik jika penulis menyertakan contoh konkret program literasi digital yang sudah berjalan di sekolah-sekolah tertentu.\"",
          ],
        },
        {
          judul: "7. Prosedur Menulis Tanggapan Kritis",
          isi: [
            "Setelah memahami teori, saatnya berlatih menulis teks tanggapan kritis. Ikuti langkah-langkah berikut untuk menghasilkan tanggapan yang baik dan benar.",
            "",
            "Langkah 1: Pilih dan Pahami Objek Tanggapan",
            "• Pilih satu karya atau fenomena yang ingin kamu tanggapi",
            "• Amati, baca, atau tonton dengan saksama",
            "• Catat detail penting: judul, pencipta, tahun, genre, dan informasi dasar lainnya",
            "",
            "Langkah 2: Identifikasi Kelebihan dan Kekurangan",
            "• Buat dua kolom: 'kelebihan' dan 'kekurangan'",
            "• Tulis poin-poin spesifik beserta alasannya",
            "• Kumpulkan bukti: kutipan, data, atau contoh dari objek",
            "",
            "Langkah 3: Susun Kerangka Sesuai Struktur",
            "• Konteks: latar belakang objek yang akan ditanggapi",
            "• Deskripsi: paparan data dan fakta tentang objek",
            "• Evaluasi: pujian, kritik, dan saran secara berimbang",
            "",
            "Langkah 4: Kembangkan Kerangka Menjadi Teks Utuh",
            "• Tulis dalam paragraf yang padu dan logis",
            "• Gunakan kaidah kebahasaan yang tepat",
            "• Perhatikan etika dan kesantunan bahasa",
            "",
            "Langkah 5: Beri Judul yang Menarik",
            "• Judul harus mencerminkan isi teks tanggapan",
            "• Bisa berupa pernyataan atau pertanyaan retoris",
            "• Contoh: 'Novel Bumi Manusia: Sebuah Mahakarya yang Abadi' atau 'Lukisan Abstrak: Antara Apresiasi dan Kebingungan'",
            "",
            "Langkah 6: Sunting dan Revisi",
            "• Periksa: apakah konteks, deskripsi, dan evaluasi sudah lengkap?",
            "• Periksa: apakah alasan dan bukti sudah mendukung setiap pernyataan?",
            "• Periksa: apakah bahasa yang digunakan santun dan tidak menyinggung?",
            "• Periksa ejaan, tanda baca, dan pilihan kata (EYD)",
            "",
            "Langkah 7: Minta Tanggapan dari Teman",
            "• Minta teman membaca dan memberi masukan",
            "• Apakah tanggapanmu mudah dipahami?",
            "• Apakah ada bagian yang terasa subjektif atau kurang objektif?",
            "",
            "Langkah 8: Publikasikan atau Presentasikan",
            "• Bacakan di depan kelas untuk didiskusikan bersama",
            "• Unggah di forum kelas digital atau blog sekolah",
            "• Terbuka terhadap diskusi dan tanggapan balik",
          ],
          rangkuman: [
            "Rumus menulis tanggapan kritis: PILIH → IDENTIFIKASI → KERANGKA → KEMBANGKAN → JUDUL → SUNING → MINTAMASUK → PUBLIKASI",
            "",
            "Tips: Mulailah dari objek yang kamu kuasai dengan baik. Semakin paham kamu terhadap suatu karya, semakin tajam dan berbobot tanggapan yang dapat kamu tulis.",
          ],
        },
      ],
    },
    latihan: [
      {
        id: 1,
        soal: "Teks tanggapan kritis adalah teks yang berisi...",
        opsi: ["Opini subjektif tanpa alasan", "Penilaian objektif disertai alasan logis", "Ringkasan cerita suatu karya", "Biografi pencipta karya"],
        jawaban: 1,
        penjelasan: "Teks tanggapan kritis berisi penilaian objektif yang didukung alasan logis, data, dan bukti — bukan sekadar opini pribadi.",
      },
      {
        id: 2,
        soal: "Urutan struktur teks tanggapan kritis yang benar adalah...",
        opsi: ["Deskripsi — Evaluasi — Konteks", "Evaluasi — Konteks — Deskripsi", "Konteks — Deskripsi — Evaluasi", "Konteks — Evaluasi — Deskripsi"],
        jawaban: 2,
        penjelasan: "Struktur yang benar: Konteks (pengantar/latar belakang) → Deskripsi (paparan data) → Evaluasi (penilaian).",
      },
      {
        id: 3,
        tipe: "ISIAN",
        soal: "Bagian struktur yang berisi gambaran rinci tentang objek tanggapan secara netral disebut...",
        opsi: "deskripsi",
        jawaban: "deskripsi",
        penjelasan: "Deskripsi adalah bagian yang memaparkan data dan fakta tentang objek secara netral, sebelum masuk ke penilaian.",
      },
      {
        id: 4,
        tipe: "BENAR_SALAH",
        soal: "Salah satu ciri teks tanggapan kritis adalah bertujuan menjatuhkan pihak yang dikritik.",
        opsi: ["Benar", "Salah"],
        jawaban: 1,
        penjelasan: "Teks tanggapan kritis bertujuan membangun, bukan menjatuhkan. Disertai alasan dan saran perbaikan.",
      },
      {
        id: 5,
        soal: "Contoh kalimat yang menunjukkan saran dalam tanggapan kritis adalah...",
        opsi: ["Film ini mengharukan.", "Saya tidak suka film ini.", "Sebaiknya penambahan musik latar dibuat lebih variatif.", "Filmnya jelek."],
        jawaban: 2,
        penjelasan: "Saran ditandai dengan kata 'sebaiknya' dan memberikan solusi konkret untuk perbaikan.",
      },
      {
        id: 6,
        soal: "Salah satu kaidah kebahasaan teks tanggapan kritis adalah penggunaan kata sifat penilaian. Contoh yang tepat adalah...",
        opsi: ["dan, atau, tetapi", "menarik, inspiratif, monoton", "di, ke, dari", "saya, kamu, mereka"],
        jawaban: 1,
        penjelasan: "Kata sifat penilaian seperti 'menarik', 'inspiratif', 'monoton' digunakan untuk mengevaluasi objek tanggapan.",
      },
      {
        id: 7,
        tipe: "BENAR_SALAH",
        soal: "Etika dalam tanggapan kritis mengharuskan kita fokus pada karya, bukan pribadi pembuatnya.",
        opsi: ["Benar", "Salah"],
        jawaban: 0,
        penjelasan: "Etika penting: fokus pada karya yang dinilai, jangan menyerang pribadi pembuatnya.",
      },
      {
        id: 8,
        soal: "Perbedaan utama antara opini biasa dan tanggapan kritis adalah...",
        opsi: ["Panjang tulisannya", "Opini biasa disertai alasan, tanggapan kritis tidak", "Tanggapan kritis disertai alasan dan bukti, opini biasa tidak", "Opini biasa ditulis oleh ahli"],
        jawaban: 2,
        penjelasan: "Opini biasa hanya berisi perasaan pribadi tanpa alasan, sedangkan tanggapan kritis selalu disertai alasan logis dan bukti.",
      },
      {
        id: 9,
        soal: "Metode 'sandwich' dalam etika memberi tanggapan berarti...",
        opsi: ["Kritik saja tanpa pujian", "Pujian — kritik/saran — pujian", "Pujian saja tanpa kritik", "Langsung menyampaikan kekurangan"],
        jawaban: 1,
        penjelasan: "Metode sandwich: mulai dengan hal positif (pujian), sampaikan kritik/saran, lalu akhiri dengan penguatan positif.",
      },
      {
        id: 10,
        soal: "Bagian evaluasi dalam teks tanggapan kritis berfungsi untuk...",
        opsi: ["Memperkenalkan objek", "Memaparkan data", "Menyampaikan penilaian disertai alasan", "Menyimpulkan seluruh teks"],
        jawaban: 2,
        penjelasan: "Evaluasi adalah inti teks tanggapan kritis yang berisi penilaian atas kelebihan dan kekurangan objek, disertai alasan logis.",
      },
    ],
    praktik: {
      tujuan: "Menulis teks tanggapan kritis terhadap sebuah karya atau fenomena secara sistematis, objektif, dan santun.",
      instruksi: "Pilihlah satu karya (buku, film, lagu, lukisan, pidato, atau artikel) atau fenomena yang kamu kenal dengan baik. Tulislah teks tanggapan kritis dengan mengikuti struktur dan kaidah yang telah dipelajari.",
      langkah: [
        "Pilih satu objek tanggapan yang kamu kuasai — bisa novel, film, lagu, pidato, karya seni, atau fenomena sosial di sekitarmu.",
        "Amati, baca, atau tonton objek tersebut dengan saksama. Catat detail penting: judul, pencipta, tahun, genre, dan informasi dasar lainnya.",
        "Buat dua kolom: 'Kelebihan' dan 'Kekurangan'. Tulis minimal 3 poin masing-masing beserta alasan dan bukti konkret.",
        "Susun kerangka teks berdasarkan struktur: konteks (2-3 kalimat), deskripsi (3-4 kalimat), evaluasi (5-7 kalimat mencakup pujian, kritik, dan saran).",
        "Kembangkan kerangka menjadi teks utuh. Gunakan kalimat kompleks, kata sifat penilaian, dan konjungsi yang tepat.",
        "Beri judul yang menarik dan mencerminkan isi tanggapanmu.",
        "Periksa kembali: apakah struktur lengkap? Apakah bahasa santun? Apakah setiap pernyataan didukung alasan? Perbaiki ejaan dan tanda baca.",
        "Mintalah teman membaca teks tanggapanmu dan memberi masukan. Revisi jika diperlukan, lalu kumpulkan dalam bentuk tulisan rapi.",
      ],
      tips: [
        "Pilih objek yang benar-benar kamu kuasai agar tanggapan lebih mendalam dan berbobot.",
        "Gunakan frasa seperti 'menurut pengamatan saya', 'dari segi', 'di sisi lain' untuk variasi bahasa.",
        "Pastikan perbandingan antara pujian dan kritik seimbang — jangan terlalu banyak salah satunya.",
        "Baca ulang dengan suara keras untuk mengecek apakah kalimat terdengar alami dan santun.",
        "Cari referensi tanggapan kritis dari majalah, blog, atau portal berita untuk melihat contoh nyata.",
      ],
      contoh: "Lihat contoh analisis struktur dan tanggapan kritis pada materi 'Hakikat Teks Tanggapan Kritis' dan 'Struktur Teks Tanggapan Kritis' di atas sebagai panduan menulis.",
    },
    kuis: [
      {
        id: 1,
        soal: "Manakah pernyataan yang paling tepat menggambarkan teks tanggapan kritis?",
        opsi: ["Komentar singkat di media sosial", "Ulasan panjang tanpa data yang jelas", "Penilaian terstruktur dengan alasan logis dan bukti konkret", "Ringkasan isi suatu karya tanpa opini"],
        jawaban: 2,
        penjelasan: "Teks tanggapan kritis adalah penilaian terstruktur (konteks-deskripsi-evaluasi) yang didukung alasan logis dan bukti konkret.",
      },
      {
        id: 2,
        soal: "Dalam struktur teks tanggapan kritis, bagian konteks berisi...",
        opsi: ["Penilaian mendalam tentang kelebihan karya", "Data dan fakta rinci tentang objek", "Latar belakang dan pengantar tentang objek yang akan ditanggapi", "Kesimpulan akhir dari seluruh tanggapan"],
        jawaban: 2,
        penjelasan: "Konteks berisi latar belakang atau pengantar singkat tentang objek tanggapan, memberi gambaran awal kepada pembaca.",
      },
      {
        id: 3,
        soal: "Penulisan tanggapan kritis yang baik menggunakan metode 'sandwich', yaitu...",
        opsi: ["Pujian — kritik — saran", "Kritik — saran — pujian", "Saran — kritik — pujian", "Pujian — saran — kritik"],
        jawaban: 0,
        penjelasan: "Metode sandwich yang benar: pujian (positif) -> kritik/saran -> pujian (positif). Hal ini membuat tanggapan terasa seimbang.",
      },
      {
        id: 4,
        tipe: "ISIAN",
        soal: "Kalimat yang bersifat mengajak atau merekomendasikan, ditandai dengan kata 'sebaiknya' disebut kalimat...",
        opsi: "persuasif",
        jawaban: "persuasif",
        penjelasan: "Kalimat persuasif bersifat mengajak atau merekomendasikan, ditandai dengan kata seperti 'sebaiknya', 'akan lebih baik jika'.",
      },
      {
        id: 5,
        soal: "Seorang siswa menulis: 'Film ini bagus. Saya suka. Aktingnya keren.' Tanggapan ini termasuk...",
        opsi: ["Tanggapan kritis yang baik", "Opini biasa tanpa alasan", "Deskripsi objektif", "Evaluasi terstruktur"],
        jawaban: 1,
        penjelasan: "Pernyataan tersebut adalah opini biasa karena hanya berisi kesan pribadi tanpa alasan.",
      },
      {
        id: 6,
        tipe: "BENAR_SALAH",
        soal: "Menyerang pribadi pembuat karya adalah etika yang diperbolehkan dalam tanggapan kritis.",
        opsi: ["Benar", "Salah"],
        jawaban: 1,
        penjelasan: "Menyerang pribadi pembuat karya adalah pelanggaran etika. Tanggapan harus fokus pada karya.",
      },
      {
        id: 7,
        soal: "Cermati kalimat berikut: 'Berbeda dengan novel pertamanya yang bertema petualangan, novel terbaru penulis ini mengangkat isu sosial yang lebih serius.' Kalimat tersebut menggunakan kaidah kebahasaan...",
        opsi: ["Kalimat persuasif", "Kata rujukan untuk membandingkan", "Istilah teknis", "Kata sifat penilaian"],
        jawaban: 1,
        penjelasan: "Frasa 'berbeda dengan' adalah kata rujukan yang digunakan untuk membandingkan dua hal.",
      },
      {
        id: 8,
        tipe: "BENAR_SALAH",
        soal: "Bagian struktur yang berisi paparan fakta dan data secara netral sebelum penilaian disebut evaluasi.",
        opsi: ["Benar", "Salah"],
        jawaban: 1,
        penjelasan: "Bagian yang memaparkan fakta dan data secara netral adalah deskripsi, bukan evaluasi.",
      },
      {
        id: 9,
        soal: "Dalam menulis tanggapan kritis, langkah pertama yang harus dilakukan adalah...",
        opsi: ["Langsung menulis penilaian", "Menyusun kerangka teks", "Memilih dan memahami objek tanggapan", "Memberi judul"],
        jawaban: 2,
        penjelasan: "Langkah pertama adalah memilih dan memahami objek tanggapan dengan saksama. Tanpa pemahaman yang baik, tanggapan tidak akan berbobot.",
      },
      {
        id: 10,
        soal: "Seorang kritikus menulis: 'Lukisan ini menggunakan palet warna monokrom yang berani. Namun, komposisi objek di bagian kanvas terasa tidak seimbang. Sebaiknya, seniman mempertimbangkan prinsip rule of thirds untuk penempatan objek utama.' Teks tersebut menunjukkan...",
        opsi: ["Opini biasa tanpa data", "Tanggapan kritis lengkap dengan pujian, kritik, dan saran", "Deskripsi tanpa evaluasi", "Konteks tanpa deskripsi dan evaluasi"],
        jawaban: 1,
        penjelasan: "Teks tersebut berisi pujian ('palet warna monokrom yang berani'), kritik ('komposisi tidak seimbang'), dan saran ('gunakan rule of thirds') — ciri tanggapan kritis yang lengkap.",
      },
    ],
  };

export default konten;
