// @ts-nocheck
import type { Konten, Soal } from "../types";

const kd = "3.5/4.5";

/* ============================================
   Unit 4: Teks Puisi Baru — VIII S1
   KD 3.5/4.5 — Mengidentifikasi Unsur Pembangun Puisi Baru
   serta Menulis Puisi Baru dengan Memperhatikan Unsur Pembangunnya
   ============================================ */
const konten: Konten = {
    belajar: {
      tujuan: [
        "Memahami hakikat, ciri-ciri, dan perbedaan puisi baru dengan puisi rakyat",
        "Mengidentifikasi unsur fisik puisi baru (diksi, imaji, kata konkret, majas, rima/irama, tipografi)",
        "Menganalisis unsur batin puisi baru (tema, rasa, nada, amanat)",
        "Membedakan jenis-jenis puisi baru berdasarkan isi dan bentuknya",
        "Memahami kaidah kebahasaan yang khas dalam puisi baru",
        "Mengapresiasi puisi baru melalui pembacaan yang ekspresif",
        "Menulis puisi baru dengan memperhatikan unsur-unsur pembangunnya",
      ],
      materi: [
        {
          judul: "1. Hakikat Puisi Baru",
          catatan: "Puisi baru adalah jenis puisi yang tidak terikat oleh aturan tradisional seperti jumlah baris, rima, dan irama tetap.",
          isi: [
            "Puisi baru adalah jenis puisi yang lahir setelah masa puisi tradisional (puisi rakyat). Puisi baru tidak lagi terikat oleh aturan-aturan ketat seperti jumlah baris per bait, jumlah suku kata per baris, atau skema rima yang baku. Kebebasan ini memberikan ruang bagi penyair untuk mengekspresikan perasaan dan gagasannya dengan lebih leluasa.",
            "",
            "Perbedaan Puisi Baru dengan Puisi Rakyat (Puisi Lama):",
            "| Aspek | Puisi Rakyat | Puisi Baru |",
            "|-------|-------------|------------|",
            "| Bentuk | Terikat aturan tetap (jumlah baris, rima, suku kata) | Bebas, tidak terikat aturan baku |",
            "| Pengarang | Anonim (tidak diketahui) | Diketahui dan tercatat |",
            "| Penyebaran | Lisan, turun-temurun | Tertulis, melalui media cetak/digital |",
            "| Bahasa | Sering menggunakan kata arkais dan klise | Lebih variatif, inovatif, puitis |",
            "| Isi | Nasihat, adat, kepercayaan | Perasaan, pemikiran, kritik sosial, renungan |",
            "| Contoh | Pantun, syair, gurindam | \"Doa\" karya Chairil Anwar, \"Aku Ingin\" karya Sapardi Djoko Damono |",
            "",
            "Ciri-ciri puisi baru:",
            "✓ Bentuknya bebas — tidak terikat jumlah baris, rima, atau suku kata",
            "✓ Nama pengarangnya diketahui dan tercatat dalam sejarah sastra",
            "✓ Menggunakan bahasa yang indah, padat, dan penuh makna konotatif",
            "✓ Mengandung unsur irama yang teratur meskipun tidak terikat rima baku",
            "✓ Gaya bahasa (majas) digunakan secara intensif untuk memperkuat makna",
            "✓ Isinya beragam: cinta, kegelisahan, kritik sosial, alam, religius, kemanusiaan",
            "",
            "Sejarah singkat: Puisi baru mulai berkembang di Indonesia pada awal abad ke-20 seiring dengan kebangkitan nasional. Tokoh-tokoh awal seperti Muhammad Yamin, Rustam Effendi, dan Sanusi Pane mulai meninggalkan bentuk puisi tradisional dan menulis puisi dengan bentuk yang lebih bebas. Puncak perkembangan puisi baru terjadi pada Angkatan '45 dengan tokoh utamanya Chairil Anwar.",
            "",
            "PENTING: Meskipun disebut 'baru', puisi baru sudah ada sejak era Pujangga Baru (1930-an). Yang membedakannya dari puisi rakyat adalah kebebasan bentuk dan kesadaran pengarang sebagai individu kreatif.",
          ],
          contoh: [
            "Contoh puisi baru terkenal:",
            "",
            "\"Aku\" — Chairil Anwar (Angkatan '45)",
            "Kalau sampai waktuku",
            "'Ku mau tak seorang 'kan merayu",
            "Tidak juga kau",
            "",
            "Tak perlu sedu sedan itu",
            "Aku ini binatang jalang",
            "Dari kumpulannya terbuang",
            "",
            "Biar peluru menembus kulitku",
            "Aku tetap meradang menerjang",
            "Luka dan bisa kubawa berlari",
            "Berlari",
            "Hingga hilang pedih peri",
            "",
            "\"Aku Ingin\" — Sapardi Djoko Damono",
            "Aku ingin mencintaimu dengan sederhana",
            "dengan kata yang tak sempat diucapkan",
            "kayu kepada api yang menjadikannya abu",
            "",
            "Aku ingin mencintaimu dengan sederhana",
            "dengan isyarat yang tak sempat disampaikan",
            "awan kepada hujan yang menjadikannya tiada",
            "",
            "Kedua puisi di atas menunjukkan kebebasan bentuk puisi baru — tidak terikat aturan jumlah baris, rima, atau jumlah suku kata per baris.",
          ],
        },
        {
          judul: "2. Unsur Fisik Puisi Baru",
          isi: [
            "Unsur fisik adalah unsur-unsur yang tampak secara langsung dalam susunan kata-kata puisi. Unsur ini membangun 'tubuh' puisi yang dapat dilihat dan didengar.",
            "",
            "1. Diksi (Pilihan Kata)",
            "• Pemilihan kata yang tepat untuk menciptakan efek puitis tertentu",
            "• Penyair memilih kata bukan hanya berdasarkan makna, tetapi juga bunyi, suasana, dan asosiasi yang ditimbulkan",
            "• Contoh: kata \"senja\" tidak hanya berarti waktu sore, tetapi juga bisa melambangkan keremangan, kesedihan, atau perpisahan",
            "• \"Biar peluru menembus kulitku\" (Chairil Anwar) — kata \"peluru\" dan \"menembus\" menciptakan kesan keras, berani, dan penuh perjuangan",
            "",
            "2. Imaji (Citraan)",
            "• Gambaran angan yang diciptakan penyair melalui kata-kata",
            "• Imaji visual (penglihatan): \"Daun-daun berguguran di halaman sunyi\"",
            "• Imaji auditif (pendengaran): \"Kudengar suara gemericik air di kejauhan\"",
            "• Imaji taktil (peraba): \"Angin malam menyentuh kulitku yang dingin\"",
            "• Imaji olfaktori (penciuman): \"Wangii melati merayap dalam kamar\"",
            "• Imaji gustatif (pengecapan): \"Sepahit kopi yang kuseduh sendiri\"",
            "",
            "3. Kata Konkret",
            "• Kata yang merujuk pada sesuatu yang nyata dan dapat ditangkap indra",
            "• Digunakan untuk membangkitkan imaji yang lebih hidup",
            "• Contoh: \"kerikil tajam\" bukan \"kesakitan\"; \"bunga mawar merah\" bukan \"keindahan\"",
            "• \"aku ini binatang jalang\" — kata \"binatang jalang\" sangat konkret untuk menggambarkan jiwa yang liar dan bebas",
            "",
            "4. Majas (Gaya Bahasa)",
            "• Bahasa kiasan yang digunakan untuk memperindah dan memperkuat makna puisi",
            "• Majas personifikasi: benda mati seolah hidup — \"Angin berbisik cerita tentangmu\"",
            "• Majas metafora: perbandingan tanpa kata pembanding — \"Kau adalah matahariku\"",
            "• Majas simile: perbandingan dengan kata pembanding — \"Wajahmu bagaikan bulan purnama\"",
            "• Majas hiperbola: pernyataan berlebihan — \"Aku menangis dalam lautan air mata\"",
            "",
            "5. Rima dan Irama",
            "• Rima: persamaan bunyi pada akhir baris atau dalam baris puisi",
            "• Rima akhir: a-a-a-a (sama), a-b-a-b (berselang), a-a-b-b (berpeluk)",
            "• Rima dalam: persamaan bunyi di tengah baris",
            "• Irama: tinggi-rendah, panjang-pendek, keras-lembutnya bunyi dalam puisi",
            "• Irama tercipta dari pergantian suku kata yang ditekankan dan tidak ditekankan",
            "",
            "6. Tipografi (Tata Wajah)",
            "• Bentuk visual puisi di atas kertas: larik-larik, bait, margin, huruf kapital, tanda baca",
            "• Tipografi puisi baru sangat khas: ada yang rata kiri, rata kanan, atau ditata membentuk pola tertentu",
            "• Contoh: puisi \"Tuhan, Aku Cinta Pada-Mu\" — kata-kata disusun menyerupai bentuk salib",
            "• Tipografi memengaruhi makna dan suasana puisi secara visual",
          ],
          contoh: [
            "Analisis unsur fisik pada puisi \"Aku\" Chairil Anwar:",
            "",
            "Diksi: \"binatang jalang\", \"meradang\", \"menerjang\" — kata-kata keras dan penuh semangat perlawanan",
            "Imaji: visual (\"peluru menembus kulitku\"), taktil (\"luka dan bisa kubawa berlari\")",
            "Kata konkret: \"peluru\", \"kulit\", \"luka\", \"binatang jalang\"",
            "Majas: metafora (\"aku ini binatang jalang\") — penyair menyamakan dirinya dengan binatang buas",
            "Rima: tidak teratur (\"waktu\"~\"rayu\", \"jalang\"~\"terbuang\"), memberi kesan bebas dan liar",
            "Irama: baris pendek-pendek, cepat, dan terpotong — mencerminkan kegelisahan jiwa",
          ],
        },
        {
          judul: "3. Unsur Batin Puisi Baru",
          isi: [
            "Unsur batin adalah unsur yang membangun makna dan kedalaman puisi dari dalam. Unsur ini tidak tampak langsung, tetapi dapat dirasakan dan ditafsirkan oleh pembaca.",
            "",
            "1. Tema",
            "• Gagasan pokok yang mendasari seluruh isi puisi",
            "• Tema bisa berupa: ketuhanan, kemanusiaan, cinta, alam, kritik sosial, perjuangan, kesepian, kegelisahan eksistensial",
            "• Tema puisi baru sangat beragam karena penyair bebas memilih subjek",
            "• Cara menemukan tema: baca puisi berulang-ulang, lalu tanyakan \"tentang apa puisi ini secara keseluruhan?\"",
            "• Contoh: puisi \"Doa\" Chairil Anwar bertema ketuhanan; \"Sajak Putih\" Chairil Anwar bertema cinta dan pengorbanan",
            "",
            "2. Rasa (Feeling)",
            "• Perasaan penyair yang diungkapkan dalam puisi",
            "• Rasa bisa berupa: gembira, sedih, marah, kecewa, rindu, kagum, gelisah, tenang",
            "• Rasa tercermin dalam pilihan kata, irama, dan suasana yang diciptakan",
            "• Contoh: \"Senja di Pelabuhan Kecil\" karya Chairil Anwar — rasa sunyi, sepi, dan kehilangan sangat terasa",
            "• Pembaca diajak ikut merasakan apa yang dirasakan penyair",
            "",
            "3. Nada (Tone)",
            "• Sikap penyair terhadap pembaca atau terhadap objek yang dibicarakan",
            "• Nada bisa berupa: menggurui, menasihati, memberontak, merenung, memprotes, merayu, bercanda",
            "• Nada puisi \"Aku\" adalah memberontak dan penuh semangat perlawanan",
            "• Nada puisi \"Aku Ingin\" Sapardi adalah lembut, tenang, dan penuh kasih",
            "• Perbedaan rasa dan nada: rasa adalah perasaan yang disampaikan, nada adalah cara penyair menyampaikannya",
            "",
            "4. Amanat (Message)",
            "• Pesan yang ingin disampaikan penyair kepada pembaca",
            "• Amanat bisa tersurat (eksplisit) atau tersirat (implisit)",
            "• Dalam puisi baru, amanat biasanya tersirat — pembaca harus menafsirkannya",
            "• Contoh: amanat puisi \"Aku\" adalah semangat untuk tetap hidup dengan penuh martabat meskipun terbuang dan sendiri",
            "• Contoh: amanat puisi \"Aku Ingin\" adalah bahwa cinta sejati adalah cinta yang sederhana, tanpa pencitraan berlebihan",
            "",
            "Tips Menemukan Unsur Batin:",
            "• Bacalah puisi dengan suara keras beberapa kali",
            "• Renungkan: perasaan apa yang muncul saat membaca puisi ini?",
            "• Tanyakan: mengapa penyair memilih kata-kata ini? Sikap apa yang tercermin?",
            "• Diskusikan dengan teman untuk mendapatkan perspektif yang berbeda",
          ],
          contoh: [
            "Analisis unsur batin pada puisi \"Doa\" Chairil Anwar:",
            "",
            "Kepada Peminta-minta",
            "Tuhanku,",
            "Dalam termangu",
            "Aku masih menyebut nama-Mu",
            "",
            "Biar susah sungguh",
            "Mengingat Kau penuh seluruh",
            "",
            "Tema: Ketuhanan — hubungan manusia dengan Tuhannya di saat kesulitan",
            "Rasa: kegelisahan, kerinduan, dan kepasrahan bercampur menjadi satu",
            "Nada: merendah, memohon, khusyuk — penyair berbicara pada Tuhan dengan penuh kerendahan hati",
            "Amanat: Dalam kesulitan hidup, manusia tetap harus mengingat Tuhan. Kesadaran spiritual justru muncul saat manusia berada di titik terendah.",
          ],
        },
        {
          judul: "4. Jenis-Jenis Puisi Baru",
          isi: [
            "Puisi baru dapat dikelompokkan berdasarkan isi dan suasana yang diungkapkan. Berikut adalah jenis-jenis utama puisi baru:",
            "",
            "1. Balada",
            "• Puisi yang berisi kisah atau cerita tentang suatu peristiwa",
            "• Bersifat naratif — menceritakan kejadian, tokoh, atau legenda",
            "• Biasanya terdiri dari tiga bait, masing-masing delapan baris",
            "• Contoh: \"Balada Orang-orang Tercinta\" karya W.S. Rendra",
            "",
            "2. Romansa",
            "• Puisi yang berisi luapan perasaan cinta dan kasih sayang",
            "• Mengungkapkan kerinduan, kebahagiaan, kesedihan, atau kepedihan dalam cinta",
            "• Bahasa yang digunakan cenderung indah, lembut, dan puitis",
            "• Contoh: \"Cinta\" karya Sapardi Djoko Damono, \"Aku Ingin\" karya Sapardi Djoko Damono",
            "",
            "3. Elegi",
            "• Puisi yang mengungkapkan kesedihan, duka cita, atau ratapan",
            "• Biasanya ditulis untuk mengenang seseorang yang meninggal atau peristiwa menyedihkan",
            "• Nada yang dominan: sendu, pilu, penuh duka",
            "• Contoh: \"Elegi Jakarta\" karya Asrul Sani, \"Senja di Pelabuhan Kecil\" karya Chairil Anwar",
            "",
            "4. Ode",
            "• Puisi pujian yang mengagungkan seseorang, pahlawan, atau hal yang dihormati",
            "• Nada yang digunakan: kagum, hormat, dan penuh kekaguman",
            "• Bahasa yang indah dan agung",
            "• Contoh: \"Ode Buat Proklamator\" karya Taufiq Ismail",
            "",
            "5. Himne",
            "• Puisi yang berisi pujian kepada Tuhan, bangsa, atau sesuatu yang dianggap suci",
            "• Bersifat religius atau patriotik",
            "• Nada: khidmat, agung, penuh penghormatan",
            "• Contoh: \"Himne\" karya Taufiq Ismail, \"Syukur\" karya Sutardji Calzoum Bachri",
            "",
            "6. Epigram",
            "• Puisi pendek yang berisi ajaran hidup, filsafat, atau nasihat",
            "• Singkat, padat, dan penuh makna",
            "• Bersifat reflektif — mengajak pembaca merenungkan kehidupan",
            "• Contoh: \"Epigram\" karya Goenawan Mohamad, \"Surat dari Ibu\" karya Asrul Sani",
            "",
            "7. Satire",
            "• Puisi yang berisi kritik sosial, sindiran, atau kecaman terhadap keadaan",
            "• Menggunakan bahasa yang tajam, ironis, atau sinis",
            "• Bertujuan menyadarkan pembaca akan ketidakadilan atau keburukan sosial",
            "• Contoh: \"Sajak Sosial\" karya Taufiq Ismail, \"Potret\" karya W.S. Rendra",
            "",
            "PENTING: Sebuah puisi bisa termasuk dalam lebih dari satu jenis. Misalnya, \"Balada Orang-orang Tercinta\" mengandung unsur balada (cerita) sekaligus satire (kritik sosial). Penggolongan jenis puisi membantu kita memahami isi dan tujuan puisi, bukan untuk membatasi kreativitas penyair.",
          ],
          contoh: [
            "Contoh masing-masing jenis puisi baru:",
            "",
            "Balada — kutipan \"Balada Orang-orang Tercinta\" (W.S. Rendra):",
            "\"Kucing hitam melompat pagar. / Bulan tersangkut di pohon randu. / Di jalan bebatuan yang licin / dua kekasih berjalan bergandengan.\"",
            "",
            "Elegi — kutipan \"Senja di Pelabuhan Kecil\" (Chairil Anwar):",
            "\"Ini kali tiada yang mencari cinta / di antara gudang, rumah tua, pada cerita / tiada lagi.\"",
            "",
            "Ode — kutipan \"Ode Buat Proklamator\" (Taufiq Ismail):",
            "\"Kami yang kini berbaring di antara anyaman sejarah / mendengar lagi gemuruh suaramu / memanggil-manggil dari ujung mimbar.\"",
            "",
            "Satire — kutipan \"Potret\" (W.S. Rendra):",
            "\"Wajah-wajah yang selalu sibuk / dengan urusan perutnya sendiri / lupa bahwa ada bau mesiu / dan asap yang membakar mimpi.\"",
          ],
        },
        {
          judul: "5. Kaidah Kebahasaan Puisi Baru",
          isi: [
            "Puisi baru menggunakan bahasa yang khas dan berbeda dari bahasa sehari-hari. Berikut kaidah kebahasaan yang sering ditemukan dalam puisi baru:",
            "",
            "1. Makna Konotatif",
            "• Kata-kata dalam puisi tidak selalu bermakna denotatif (makna sebenarnya), tetapi sering mengandung makna konotatif (makna kiasan)",
            "• Contoh: kata \"malam\" dalam puisi bisa berarti kesedihan, kegelapan, atau masa sulit — bukan sekadar waktu antara siang dan pagi",
            "• \"Biar peluru menembus kulitku\" — \"peluru\" bermakna konotatif sebagai segala rintangan dan ancaman dalam hidup",
            "",
            "2. Lambang (Simbol)",
            "• Penggunaan benda, makhluk, atau peristiwa sebagai lambang suatu ide atau perasaan",
            "• Lambang-lambang umum dalam puisi:",
            "  — Mawar: cinta, keindahan, romantisme",
            "  — Ombak: semangat, perjuangan, dinamika hidup",
            "  — Jalan: perjalanan hidup, pilihan, nasib",
            "  — Burung: kebebasan, cita-cita, jiwa yang merdeka",
            "  — Sunyi: kesepian, keheningan batin, kematian",
            "• Contoh: \"Kupu-kupu itu terbang di taman\" — kupu-kupu bisa melambangkan kebebasan atau keindahan yang singkat",
            "",
            "3. Personifikasi",
            "• Memberikan sifat-sifat manusia pada benda mati atau makhluk bukan manusia",
            "• Membuat puisi menjadi lebih hidup dan imajinatif",
            "• Contoh: \"Bulan tersenyum padaku tadi malam\" (bulan diberi sifat tersenyum)",
            "• Contoh: \"Angin mengeluh di antara dahan\" (angin diberi kemampuan mengeluh)",
            "• Contoh: \"Hujan menangis sepanjang malam\" (hujan dipersonifikasikan menangis)",
            "",
            "4. Metafora",
            "• Perbandingan langsung tanpa menggunakan kata pembanding (seperti, bagaikan, laksana)",
            "• Sesuatu yang dibandingkan seolah-olah menjadi hal yang lain",
            "• Contoh: \"Kau adalah matahariku\" — orang yang dicintai disamakan dengan matahari",
            "• Contoh: \"Hidup ini panggung sandiwara\" — hidup disamakan dengan pertunjukan drama",
            "• Contoh: \"Aku ini binatang jalang\" (Chairil Anwar) — penyair menyamakan dirinya dengan binatang buas",
            "",
            "5. Simile (Perbandingan)",
            "• Perbandingan eksplisit menggunakan kata pembanding seperti, bagaikan, laksana, bak, seumpama",
            "• Contoh: \"Wajahnya bagaikan bulan purnama\"",
            "• Contoh: \"Cintaku sejauh cakrawala\"",
            "• Contoh: \"Hatiku seperti air yang mengalir tenang\"",
            "",
            "6. Pengulangan (Repetisi)",
            "• Pengulangan kata, frasa, atau baris untuk menekankan makna dan menciptakan irama",
            "• Contoh pengulangan baris: \"Aku ingin mencintaimu dengan sederhana / Aku ingin mencintaimu dengan sederhana\" (Sapardi)",
            "• Contoh pengulangan kata: \"Berlari / Berlari / Hingga hilang pedih peri\" (Chairil Anwar)",
            "",
            "7. Kata Seru (Interjeksi)",
            "• Kata yang mengungkapkan perasaan: oh, ah, wah, aduh, hai",
            "• Memberi efek emosional pada puisi",
            "• Contoh: \"Oh, betapa buruknya nasib ini!\" — kata \"oh\" menekankan kepedihan",
          ],
          rangkuman: [
            "Ingat rumus 'KPS-LMR' untuk kaidah kebahasaan puisi baru:",
            "K = Konotasi (makna kiasan)",
            "P = Personifikasi (benda mati bersifat manusia)",
            "S = Simbol/lambang (benda melambangkan ide/perasaan)",
            "L = (Lanjutan) — gunakan simbol secara konsisten",
            "M = Metafora (perbandingan langsung)",
            "R = Repetisi (pengulangan untuk penekanan)",
            "",
            "Plus Simile dan Interjeksi sebagai pelengkap. Semakin kaya penggunaan majas, semakin puitis puisi yang dihasilkan.",
          ],
        },
        {
          judul: "6. Mengapresiasi Puisi Baru",
          isi: [
            "Mengapresiasi puisi berarti menghargai dan menikmati puisi secara utuh. Salah satu bentuk apresiasi yang penting adalah pembacaan puisi yang ekspresif. Puisi yang baik akan terasa lebih hidup ketika dibacakan dengan penghayatan yang tepat.",
            "",
            "1. Memahami Nada dan Suasana Puisi",
            "• Sebelum membaca, pahami dulu jenis dan suasana puisi",
            "• Apakah puisi itu sedih, marah, gembira, khusyuk, atau merenung?",
            "• Nada membaca harus sesuai dengan nada puisi: puisi marah dibaca dengan suara keras dan tegas, puisi sedih dibaca pelan dan sendu",
            "",
            "2. Intonasi dan Lafal",
            "• Intonasi: naik-turunnya suara saat membaca puisi",
            "• Jangan membaca datar — beri tekanan pada kata-kata penting",
            "• Lafal: ucapkan setiap kata dengan jelas, jangan tergesa-gesa",
            "• Perhatikan tanda baca: titik (.) berarti jeda panjang, koma (,) berarti jeda pendek",
            "",
            "3. Jeda dan Tempo",
            "• Jeda: berhenti sejenak di akhir baris atau di tengah baris yang memiliki makna penting",
            "• Tempo: kecepatan membaca — puisi dengan suasana tegang dibaca cepat, puisi sedih dibaca lambat",
            "• Jeda yang tepat membuat pendengar lebih mudah menangkap makna puisi",
            "",
            "4. Ekspresi Wajah (Mimik)",
            "• Ekspresi wajah harus mendukung isi puisi",
            "• Puisi sedih: wajah muram, alis berkerut",
            "• Puisi gembira: senyum, wajah cerah",
            "• Puisi marah: wajah tegang, mata tajam",
            "",
            "5. Gestur dan Gerakan Tubuh",
            "• Gerakan tangan, posisi tubuh, dan pandangan mata mendukung penyampaian puisi",
            "• Gunakan gerakan yang wajar, jangan berlebihan",
            "• Pandangan mata: lihat ke arah pendengar secara merata",
            "• Berdiri tegak dan percaya diri",
            "",
            "6. Penghayatan Total",
            "• Hayati puisi seolah-olah itu adalah pengalaman pribadimu",
            "• Rasakan setiap emosi yang ada dalam puisi",
            "• Penghayatan yang tulus akan menular kepada pendengar",
            "",
            "Tips: Latih membaca puisi di depan cermin. Rekam suaramu dan dengarkan kembali untuk mengevaluasi intonasi dan ekspresi. Semakin sering berlatih, semakin alami dan menghayati pembacaanmu.",
          ],
          contoh: [
            "Teknik membaca puisi \"Aku\" karya Chairil Anwar:",
            "",
            "Baris 1-3: \"Kalau sampai waktuku / 'Ku mau tak seorang 'kan merayu / Tidak juga kau\"",
            "  — Intonasi: tegas, sedikit menantang",
            "  — Jeda: berhenti sejenak setelah 'waktuku' dan 'merayu'",
            "  — Ekspresi: mata tajam, dagu sedikit terangkat",
            "",
            "Baris 4-6: \"Tak perlu sedu sedan itu / Aku ini binatang jalang / Dari kumpulannya terbuang\"",
            "  — Suara: mulai naik, penuh semangat",
            "  — Tekanan pada kata: \"BINATANG JALANG\" dan \"TERBUANG\"",
            "  — Gestur: telapak tangan terbuka ke depan (gestur menolak)",
            "",
            "Baris 7-11: \"Biar peluru menembus kulitku / Aku tetap meradang menerjang / Luka dan bisa kubawa berlari / Berlari / Hingga hilang pedih peri\"",
            "  — Tempo: semakin cepat, menggambarkan semangat membara",
            "  — Klimaks: kata \"Berlari\" diulang dengan suara meninggi",
            "  — Ekspresi: penuh keyakinan, mata menyala",
            "",
            "PENTING: Tidak ada cara 'salah' dalam membaca puisi selama ekspresi dan penghayatannya tulus. Setiap pembaca bisa memberikan interpretasi yang berbeda.",
          ],
        },
        {
          judul: "7. Prosedur Menulis Puisi Baru",
          isi: [
            "Menulis puisi baru adalah proses kreatif yang dapat dipelajari dan dilatih. Tidak perlu menunggu 'ilham' — dengan mengikuti langkah-langkah sistematis, siapa pun bisa menulis puisi.",
            "",
            "Langkah 1: Tentukan Tema dan Rasa",
            "• Pilih satu tema yang dekat dengan pengalaman atau perasaanmu",
            "• Contoh tema: kekecewaan, kebahagiaan, persahabatan, alam, cita-cita, keluarga",
            "• Tentukan rasa yang ingin kamu sampaikan: sedih, marah, rindu, bahagia, kagum?",
            "",
            "Langkah 2: Kumpulkan Kata-Kata",
            "• Tulis semua kata yang berhubungan dengan tema — jangan disaring dulu",
            "• Gunakan teknik clustering: tulis kata kunci di tengah, lalu kembangkan cabang-cabang kata yang terkait",
            "• Contoh untuk tema 'rindu': sepi, malam, jarak, kenangan, foto usang, hujan, jendela, waktu",
            "",
            "Langkah 3: Pilih dan Susun Kata dengan Indah (Diksi)",
            "• Pilih kata-kata yang paling kuat dan puitis dari kumpulan kata tadi",
            "• Gunakan kata konotatif: bukan 'sedih' tapi 'sunyi', bukan 'rindu' tapi 'sesak'",
            "• Perhatikan bunyi kata — pilih yang enak didengar",
            "",
            "Langkah 4: Gunakan Majas",
            "• Sematkan personifikasi, metafora, atau simile untuk memperindah puisi",
            "• Ubah kalimat biasa menjadi kalimat bermajas",
            "  Biasa: \"Aku sendirian di malam hari\"",
            "  Bermajas: \"Malam merangkulku dalam kesunyian yang panjang\" (personifikasi)",
            "",
            "Langkah 5: Atur Tipografi",
            "• Tulis puisi dalam bentuk bait-bait",
            "• Tentukan panjang pendek baris — jangan semua sama, variasikan",
            "• Gunakan baris pendek untuk efek dramatis, baris panjang untuk deskripsi atau perenungan",
            "",
            "Langkah 6: Periksa Rima dan Irama",
            "• Meskipun bebas, puisi yang enak dibaca memiliki irama alami",
            "• Bacakan dengan suara keras — apakah ada bagian yang tersendat?",
            "• Sesuaikan kembali pilihan kata jika iramanya kurang pas",
            "",
            "Langkah 7: Sunting dan Revisi",
            "• Setelah draft selesai, simpan dulu beberapa jam (atau sehari)",
            "• Baca kembali dengan pikiran segar — adakah kata yang bisa diganti?",
            "• Periksa: apakah tema dan rasa sudah tersampaikan?",
            "• Kurangi jika terlalu panjang, tambah jika terlalu pendek",
            "",
            "Langkah 8: Beri Judul",
            "• Judul yang baik mewakili isi puisi tanpa harus menjelaskan semuanya",
            "• Bisa menggunakan kata kunci dari puisi, atau frasa yang mencolok",
            "• Hindari judul yang terlalu umum seperti 'Cinta' atau 'Rindu' — lebih baik 'Secangkir Kopi Pahit' atau 'Daun yang Jatuh'",
          ],
          rangkuman: [
            "Rumus menulis puisi baru: TEMA → KATA → DIKSI → MAJAS → TIPOGRAFI → IRAMA → SUNING → JUDUL",
            "",
            "Tips Golden: Jangan takut menulis jelek. Semua penyair besar memulai dari draft yang buruk. Yang penting adalah MENULIS dulu, baru menyempurnakan. Seperti kata Goenawan Mohamad: 'Puisi tidak ditulis, tetapi ditemukan.'",
          ],
        },
      ],
    },
    latihan: [
      {
        id: 1,
        soal: "Puisi baru tidak terikat aturan jumlah baris dan rima baku, berbeda dengan puisi rakyat.",
        tipe: "BENAR_SALAH",
        opsi: ["Benar", "Salah"],
        jawaban: 0,
        penjelasan: "Puisi baru bersifat bebas, tidak terikat aturan jumlah baris, rima, atau suku kata per baris, berbeda dengan puisi rakyat yang terikat aturan ketat.",
      },
      {
        id: 2,
        soal: "Pemilihan kata yang tepat untuk menciptakan efek puitis dalam puisi disebut ...",
        tipe: "ISIAN",
        opsi: ["diksi"],
        jawaban: "diksi",
        penjelasan: "Diksi adalah pemilihan kata yang tepat dan cermat untuk menciptakan efek puitis dan menyampaikan makna secara indah.",
      },
      {
        id: 3,
        soal: "Kutipan puisi 'Angin berbisik cerita tentangmu' menggunakan majas...",
        opsi: ["Metafora", "Hiperbola", "Personifikasi", "Simile"],
        jawaban: "2",
        penjelasan: "Personifikasi karena angin (benda mati) diberi sifat manusia, yaitu berbisik. Ini memberikan sifat hidup pada benda mati.",
      },
      {
        id: 4,
        soal: "Unsur batin puisi yang berkaitan dengan sikap penyair terhadap pembaca disebut...",
        opsi: ["Tema", "Rasa", "Nada", "Amanat"],
        jawaban: 2,
        penjelasan: "Nada adalah sikap penyair terhadap pembaca atau objek yang dibicarakan, seperti memberontak, merendah, menggurui, atau merenung.",
      },
      {
        id: 5,
        soal: "Balada adalah jenis puisi yang berisi kisah atau cerita tentang suatu peristiwa.",
        tipe: "BENAR_SALAH",
        opsi: ["Benar", "Salah"],
        jawaban: 0,
        penjelasan: "Balada adalah puisi naratif yang berisi kisah atau cerita tentang suatu peristiwa, tokoh, atau legenda.",
      },
      {
        id: 6,
        soal: "Bait puisi berikut menggunakan majas... 'Wajahmu bagaikan bulan purnama'.",
        opsi: ["Metafora", "Simile", "Personifikasi", "Hiperbola"],
        jawaban: 1,
        penjelasan: "Simile adalah perbandingan eksplisit yang menggunakan kata pembanding seperti 'bagai', 'laksana', 'seperti'. Dalam kutipan digunakan kata 'bagaikan'.",
      },
      {
        id: 7,
        soal: "Kata 'sunyi' dalam puisi lebih sering digunakan secara...",
        opsi: ["Denotatif", "Konotatif", "Leksikal", "Gramatikal"],
        jawaban: 1,
        penjelasan: "Kata 'sunyi' dalam puisi biasanya bermakna konotatif, melambangkan kesepian, keheningan batin, atau bahkan kematian, bukan sekadar tidak ada suara.",
      },
      {
        id: 8,
        soal: "Puisi yang berisi pujian kepada Tuhan, bangsa, atau sesuatu yang dianggap suci disebut...",
        opsi: ["Ode", "Satire", "Himne", "Epigram"],
        jawaban: 2,
        penjelasan: "Himne adalah puisi pujian kepada Tuhan, bangsa, atau hal yang dianggap suci. Nada yang digunakan khidmat dan agung.",
      },
      {
        id: 9,
        soal: "Yang dimaksud dengan tipografi dalam puisi adalah...",
        opsi: [
          "Persamaan bunyi pada akhir baris",
          "Gambaran angan yang diciptakan oleh kata-kata",
          "Tata wajah atau bentuk visual puisi di atas kertas",
          "Pilihan kata yang indah dan puitis",
        ],
        jawaban: 2,
        penjelasan: "Tipografi adalah tata wajah puisi, termasuk pengaturan baris, bait, margin, dan huruf kapital. Ini memengaruhi makna dan keindahan visual puisi.",
      },
      {
        id: 10,
        soal: "Puisi 'Senja di Pelabuhan Kecil' karya Chairil Anwar termasuk jenis puisi...",
        opsi: ["Ode", "Romansa", "Elegi", "Balada"],
        jawaban: 2,
        penjelasan: "Puisi tersebut termasuk elegi karena mengungkapkan kesedihan, duka, dan perasaan kehilangan. Suasananya sendu dan melankolis.",
      },
    ],
    praktik: {
      tujuan: "Menulis satu puisi baru bertema bebas dengan memperhatikan unsur fisik dan unsur batin yang telah dipelajari.",
      instruksi: "Tuliskan sebuah puisi baru dengan tema pilihanmu sendiri. Puisi minimal terdiri dari 2 bait (12-16 baris). Perhatikan diksi, majas, imaji, dan tipografi. Sertakan amanat yang tersirat di dalamnya.",
      langkah: [
        "Tentukan tema yang dekat dengan pengalaman atau perasaanmu saat ini (contoh: rindu, persahabatan, alam, cita-cita, keluarga, kegelisahan).",
        "Buat daftar kata-kata yang berhubungan dengan tema. Gunakan teknik clustering atau mind map. Jangan menyaring — tulis semua yang terlintas.",
        "Pilih kata-kata yang paling kuat dari daftar. Ubah kata-kata biasa menjadi lebih puitis (konotatif). Misal: 'sedih' menjadi 'sunyi dalam kalbu'.",
        "Susun kata menjadi larik-larik. Gunakan majas (personifikasi, metafora, simile) untuk memperindah. Ciptakan imaji visual atau auditif.",
        "Atur larik menjadi bait-bait. Variasikan panjang-pendek baris untuk menciptakan irama. Baris pendek untuk kesan dramatis, baris panjang untuk deskripsi.",
        "Bacakan dengan suara keras. Dengarkan iramanya. Perbaiki jika ada bagian yang terdengar janggal atau tersendat.",
        "Berikan judul yang menarik. Judul bisa berupa kata kunci dari puisi atau frasa yang menggambarkan isi secara puitis.",
        "Baca kembali seluruh puisi, periksa ejaan dan tanda baca. Minta teman membaca dan memberi tanggapan. Revisi jika perlu.",
      ],
      tips: [
        "Mulailah dari pengalaman pribadi — puisi yang lahir dari perasaan tulus akan lebih mudah ditulis dan lebih mengena di hati pembaca.",
        "Jangan takut bereksperimen dengan bentuk. Coba tata baris tidak selalu rata kiri, atau gunakan satu kata sebagai satu baris untuk efek dramatis.",
        "Baca puisi penyair terkenal untuk mendapatkan inspirasi dan memperkaya kosakatamu. Perhatikan bagaimana mereka bermain dengan kata dan majas.",
        "Jangan terpaku pada sempurna di draft pertama. Yang penting selesaikan dulu, baru kemudian edit dan poles. Puisi yang baik adalah puisi yang sudah disunting.",
        "Simpan hasil puisimu di jurnal atau unggah di platform kelas. Semakin sering menulis, semakin terasah kemampuan puitismu.",
      ],
      contoh: "Berikut contoh puisi karya siswa bertema 'Rindu':\n\nJudul: Hujan di Jendela Kaca\n\nHujan jatuh perlahan di jendela kaca\nsetiap titik mengukir nama yang lama\nkudekatkan jemari pada embun dingin\nseolah kau menulis jawab di atas kaca.\n\nJarak merentang sejauh waktu\nantara langkah dan kenangan yang membiru\nnamun di sela rintik yang tak putus\naku masih mendengar tawamu dulu.\n\nBiarlah hujan terus bercerita\ntentang rindu yang tak pernah usai.\n\nCatatan: Puisi di atas menggunakan personifikasi (\"hujan... mengukir nama\", \"hujan terus bercerita\"), imaji visual (\"hujan jatuh perlahan di jendela kaca\", \"embun dingin\"), dan imaji auditif (\"rintik\", \"tawamu\"). Tema: rindu dan jarak. Nada: sendu dan penuh harap.",
    },
    kuis: [
      {
        id: 1,
        soal: "Perhatikan kutipan puisi berikut: 'Aku ini binatang jalang / Dari kumpulannya terbuang'. Majas yang digunakan pada larik tersebut adalah...",
        opsi: ["Personifikasi", "Simile", "Metafora", "Hiperbola"],
        jawaban: 2,
        penjelasan: "Metafora karena penyair menyamakan dirinya dengan 'binatang jalang' secara langsung tanpa kata pembanding. Ini adalah perbandingan langsung yang menjadi ciri khas metafora.",
      },
      {
        id: 2,
        soal: "Pada puisi, kata 'mawar' sering digunakan sebagai lambang dari...",
        opsi: ["Kesedihan", "Kematian", "Cinta dan keindahan", "Kebebasan"],
        jawaban: 2,
        penjelasan: "Mawar dalam puisi melambangkan cinta, keindahan, dan romantisme. Warna mawar juga memengaruhi maknanya: merah untuk cinta, putih untuk kesucian.",
      },
      {
        id: 3,
        soal: "Perbedaan antara nada dan rasa dalam puisi adalah...",
        opsi: [
          "Nada adalah irama, rasa adalah rima",
          "Nada adalah kecepatan baca, rasa adalah intonasi",
          "Nada adalah sikap penyair, rasa adalah perasaan yang diungkapkan",
          "Nada dan rasa adalah istilah yang sama",
        ],
        jawaban: 2,
        penjelasan: "Nada adalah sikap penyair terhadap pembaca (misalnya memberontak, merendah), sedangkan rasa adalah perasaan yang diungkapkan dalam puisi (misalnya sedih, gembira, gelisah).",
      },
      {
        id: 4,
        soal: "Satire adalah puisi yang berisi sindiran atau kritik sosial dengan bahasa yang tajam dan ironis.",
        tipe: "BENAR_SALAH",
        opsi: ["Benar", "Salah"],
        jawaban: 0,
        penjelasan: "Satire adalah puisi yang berisi kritik atau sindiran sosial dengan bahasa yang tajam, ironis, atau sinis. Contohnya puisi 'Potret' karya W.S. Rendra.",
      },
      {
        id: 5,
        soal: "Jenis imaji yang berhubungan dengan indra penciuman disebut imaji ...",
        tipe: "ISIAN",
        opsi: ["olfaktori"],
        jawaban: "olfaktori",
        penjelasan: "Imaji olfaktori adalah citraan yang berhubungan dengan indra penciuman. Kata 'wangi' dan 'melati' merangsang indra penciuman pembaca.",
      },
      {
        id: 6,
        soal: "Perhatikan larik puisi berikut: 'Malam merangkulku dalam sunyi / Bintang berpendar menyapa sendiri'. Unsur fisik yang dominan dalam larik tersebut adalah...",
        opsi: ["Diksi dan rima", "Imaji dan majas", "Tipografi dan diksi", "Kata konkret dan rima"],
        jawaban: "1",
        penjelasan: "Larik tersebut mengandung imaji (visual: 'bintang berpendar', taktil: 'merangkul') dan majas (personifikasi: 'malam merangkulku', 'bintang... menyapa').",
      },
      {
        id: 7,
        soal: "Yang membedakan puisi baru angkatan Pujangga Baru dengan Angkatan '45 adalah...",
        opsi: [
          "Pujangga Baru tidak menggunakan majas, Angkatan '45 menggunakan majas",
          "Pujangga Baru masih terikat rima dan bentuk, Angkatan '45 lebih bebas dan ekspresif",
          "Pujangga Baru bertema sosial, Angkatan '45 bertema cinta",
          "Tidak ada perbedaan yang signifikan",
        ],
        jawaban: 1,
        penjelasan: "Puisi Pujangga Baru (1930-an) masih cukup terikat pada bentuk yang rapi dan rima teratur. Sementara Angkatan '45 yang dipelopori Chairil Anwar lebih bebas, ekspresif, dan individualistis.",
      },
      {
        id: 8,
        soal: "Larik 'Kutulis surat ini dengan air mata / kata-kata mengalir deras tak terbendung' mengandung imaji...",
        opsi: ["Visual saja", "Visual dan auditif", "Auditif dan taktil", "Visual dan olfaktori"],
        jawaban: 0,
        penjelasan: "Kedua larik mengandung imaji visual: 'air mata' (yang terlihat) dan 'kata-kata mengalir' (yang divisualisasikan seperti aliran). Tidak ada imaji auditif atau taktil yang dominan.",
      },
      {
        id: 9,
        soal: "Puisi satire adalah jenis puisi yang paling tepat untuk mengkritik pemimpin yang korup.",
        tipe: "BENAR_SALAH",
        opsi: ["Benar", "Salah"],
        jawaban: 0,
        penjelasan: "Satire adalah jenis puisi yang tepat untuk kritik sosial atau politik. Satire menggunakan sindiran tajam dan ironi untuk menyampaikan kritik, berbeda dengan romansa (cinta), elegi (kesedihan), atau himne (pujian).",
      },
      {
        id: 10,
        soal: "Perhatikan larik puisi berikut: 'Danau hatiku mengering perlahan / sejak kau pergi tanpa pesan'. Unsur batin yang paling dominan adalah...",
        opsi: [
          "Tema: persahabatan, Nada: menggurui",
          "Tema: kehilangan, Rasa: sedih dan ditinggalkan",
          "Tema: alam, Amanat: jaga alam",
          "Tema: perjalanan, Nada: semangat",
        ],
        jawaban: 1,
        penjelasan: "Larik puisi tersebut bertema kehilangan ('kau pergi tanpa pesan') dengan rasa sedih dan perasaan ditinggalkan. Metafora 'danau hatiku mengering' memperkuat rasa kehilangan dan kekosongan jiwa.",
      },
    ],
  };

export default konten;
