// @ts-nocheck
import type { Konten, Soal } from "../types";

const kd = "3.5/4.5";

function buatSoal(count: number, opsi: number, tema: string): Soal[] {
  return Array.from({ length: count }, (_, i) => ({
    id: i + 1,
    soal: `Contoh soal ${tema} nomor ${i + 1}?`,
    opsi: ["Pilihan A", "Pilihan B", "Pilihan C", "Pilihan D"],
    jawaban: 0,
    penjelasan: `Penjelasan untuk soal ${tema} nomor ${i + 1}`,
  }));
}

/* =============================================
   Unit 5: Giat Literasi I — Teks Fiksi — VIII S1
   KD 3.5/4.5 — Mengidentifikasi, Menganalisis, dan Menyajikan Teks Fiksi
   ============================================= */
const konten: Konten = {
    belajar: {
      tujuan: [
        "Memahami hakikat fiksi sebagai karya sastra imajinatif dan perannya dalam literasi",
        "Menganalisis unsur intrinsik dan ekstrinsik yang membangun karya fiksi secara utuh",
        "Mengidentifikasi berbagai jenis buku fiksi populer dan karakteristiknya",
        "Membedakan jenis-jenis alur (maju, mundur, campuran) dalam cerita fiksi",
        "Menganalisis kebahasaan fiksi meliputi majas, diksi, dan gaya bahasa",
        "Membandingkan dua karya fiksi dari segi tema, karakter, dan gaya penceritaan",
        "Menulis resensi buku fiksi dengan prosedur yang tepat dan sistematis",
      ],
      materi: [
        {
          judul: "1. Hakikat Fiksi dan Literasi",
          catatan: "Fiksi adalah karya sastra yang dibangun dari imajinasi, bukan fakta semata.",
          isi: [
            "Fiksi berasal dari bahasa Latin fictio yang berarti 'membentuk' atau 'menciptakan'. Dalam dunia sastra, fiksi adalah cerita rekaan yang lahir dari imajinasi pengarang, meskipun sering kali terinspirasi dari realitas kehidupan.",
            "",
            "Perkembangan Literasi Fiksi di Indonesia:",
            "• Era 1950-an–1970-an: Fiksi Indonesia modern lahir dengan angkatan Balai Pustaka dan angkatan 66. Karya seperti 'Siti Nurbaya' dan 'Layar Terkembang' menjadi pelopor.",
            "• Era 1980-an–1990-an: Munculnya novel-novel populer seperti 'Ronggeng Dukuh Paruk' dan 'Saman'. Penerbitan massal buku sastra mulai marak.",
            "• Era 2000-an–sekarang: Ledakan novel remaja, wattpad, dan fiksi digital. Komunitas literasi seperti 'Indonesia Buku' dan 'Goodreads Indonesia' tumbuh pesat.",
            "• Platform digital: Wattpad, Cabaca, dan aplikasi baca daring mengubah wajah literasi fiksi di kalangan remaja.",
            "",
            "Manfaat Membaca Fiksi:",
            "✓ Mengembangkan empati — pembaca ikut merasakan emosi tokoh",
            "✓ Memperkaya kosakata dan kemampuan berbahasa",
            "✓ Melatih kemampuan berpikir kritis dan analitis",
            "✓ Memberikan hiburan dan pelepasan stres (escapism)",
            "✓ Membuka wawasan tentang budaya, sejarah, dan perspektif hidup baru",
            "",
            "PENTING: Literasi bukan sekadar kemampuan membaca, tetapi juga kemampuan memahami, menganalisis, dan merefleksikan bacaan. Membaca fiksi secara aktif berarti mempertanyakan, menginterpretasi, dan menghubungkan cerita dengan pengalaman hidup.",
          ],
          contoh: [
            "Contoh perkembangan fiksi remaja Indonesia:",
            "",
            "• 'Dilan: Dia adalah Dilanku' karya Pidi Baiq (2014) — novel remaja yang menjadi fenomena nasional, diadaptasi menjadi film laris. Gaya bahasa sederhana, percakapan sehari-hari, dan setting Bandung tahun 1990-an.",
            "",
            "• 'Bumi' karya Tere Liye (2014) — serial fiksi petualangan fantasi yang digemari remaja. Menggabungkan unsur sains, mitologi, dan petualangan dalam satu cerita.",
            "",
            "• 'Hujan' karya Tere Liye (2016) — fiksi ilmiah dengan tema ingatan, waktu, dan pengorbanan. Mengajak pembaca merenungkan arti kehilangan dan cinta.",
            "",
            "• Karya-karya dari penulis Wattpad seperti 'My Nerd Girl' dan 'Mariposa' — menunjukkan bahwa platform digital telah membuka pintu bagi penulis muda untuk menerbitkan karya fiksi mereka.",
          ],
        },
        {
          judul: "2. Unsur Intrinsik dan Ekstrinsik Fiksi",
          isi: [
            "Setiap karya fiksi dibangun oleh dua kelompok unsur: intrinsik (dari dalam cerita) dan ekstrinsik (dari luar cerita). Memahami keduanya adalah kunci untuk menganalisis fiksi secara menyeluruh.",
            "",
            "A. Unsur Intrinsik Fiksi",
            "",
            "1. Tema",
            "• Gagasan sentral yang mendasari seluruh cerita",
            "• Tema bisa eksplisit (tersurat) atau implisit (tersirat)",
            "• Contoh tema: cinta, persahabatan, perjuangan kelas, identitas, keadilan",
            "• Tips: Tema biasanya bisa dirumuskan dalam satu frasa, misalnya 'perjuangan seorang ibu' atau 'pencarian jati diri remaja'",
            "",
            "2. Tokoh dan Penokohan",
            "• Tokoh: pelaku cerita yang mengalami peristiwa",
            "• Penokohan: cara pengarang menggambarkan karakter tokoh",
            "• Berdasarkan peran: protagonis (pahlawan), antagonis (lawan), tritagonis (penengah)",
            "• Berdasarkan perkembangan: statis (tidak berubah) dan dinamis (berkembang)",
            "• Teknik penggambaran: analitik (langsung), dramatik (tidak langsung lewat dialog/tingkah laku), dan kontekstual (lewat lingkungan)",
            "",
            "3. Alur (Plot)",
            "• Rangkaian peristiwa yang saling terkait sebab-akibat",
            "• Tahapan alur klasik: pengenalan → konflik → klimaks → antiklimaks → resolusi",
            "• Dibahas lebih mendalam di materi 4",
            "",
            "4. Latar (Setting)",
            "• Tempat, waktu, dan suasana cerita berlangsung",
            "• Latar tempat: geografis (kota, desa, sekolah, rumah)",
            "• Latar waktu: historis (tahun, zaman) dan temporal (pagi, siang, malam)",
            "• Latar sosial: status sosial, budaya, adat istiadat yang melingkupi cerita",
            "",
            "5. Sudut Pandang (Point of View)",
            "• Orang pertama (aku): pengarang sebagai tokoh dalam cerita",
            "• Orang ketiga serba tahu (dia maha tahu): pengarang tahu segalanya tentang tokoh",
            "• Orang ketiga terbatas: pengarang hanya mengikuti satu tokoh tertentu",
            "",
            "6. Gaya Bahasa",
            "• Cara khas pengarang dalam memilih kata dan menyusun kalimat",
            "• Mencakup: diksi, majas, imaji, ritme kalimat",
            "• Dibahas lebih mendalam di materi 5",
            "",
            "7. Amanat (Pesan Moral)",
            "• Nilai atau pesan yang ingin disampaikan pengarang",
            "• Bisa tersurat (jelas dikatakan) atau tersirat (tersembunyi di balik cerita)",
            "",
            "B. Unsur Ekstrinsik Fiksi",
            "",
            "1. Latar Belakang Pengarang",
            "• Riwayat hidup, pendidikan, profesi, pengalaman pribadi pengarang",
            "• Pandangan dunia (worldview) pengarang memengaruhi isi cerita",
            "• Contoh: novel 'Laskar Pelangi' sangat dipengaruhi oleh latar belakang Andrea Hirata sebagai anak Belitung",
            "",
            "2. Kondisi Sosial-Politik",
            "• Situasi masyarakat saat cerita ditulis",
            "• Contoh: novel 'Bumi Manusia' karya Pramoedya merefleksikan kolonialisme dan pergerakan nasional",
            "",
            "3. Nilai Budaya dan Agama",
            "• Nilai-nilai yang dianut masyarakat pada masa cerita ditulis",
            "• Fiksi kerap menjadi kritik atau penguatan nilai budaya tertentu",
            "",
            "PENTING: Analisis fiksi yang baik tidak cukup hanya dengan menyebut unsur intrinsik. Pembaca kritis harus mampu menghubungkan unsur-unsur tersebut dengan konteks ekstrinsik: mengapa pengarang memilih tema ini? Apa yang ingin ia kritik? Bagaimana kondisi sosial saat itu?",
          ],
          contoh: [
            "Analisis unsur intrinsik dan ekstrinsik novel 'Laskar Pelangi' karya Andrea Hirata:",
            "",
            "Unsur Intrinsik:",
            "• Tema: Semangat pendidikan dan perjuangan mengatasi kemiskinan",
            "• Tokoh: Ikal (protagonis, cerdas, gigih), Lintang (jenius dari keluarga miskin), Bu Mus (guru inspiratif)",
            "• Alur: Campuran (maju dengan kilas balik) — dimulai dari masa dewasa Ikal, lalu flashback ke masa SD",
            "• Latar: Belitung tahun 1970-an, sekolah SD Muhammadiyah yang hampir roboh",
            "• Sudut pandang: Orang pertama (Ikal sebagai narator)",
            "• Amanat: Pendidikan adalah senjata paling ampuh untuk mengubah nasib",
            "",
            "Unsur Ekstrinsik:",
            "• Latar belakang pengarang: Andrea Hirata lahir di Belitung dari keluarga sederhana, merantau hingga ke Sorbonne — pengalaman hidupnya tercermin dalam semangat tokoh Ikal",
            "• Kondisi sosial: Kesenjangan pendidikan antara kota dan pelosok, dampak kolonialisme tambang timah di Belitung",
            "• Nilai budaya: Semangat gotong royong dan kegigihan masyarakat Melayu Belitung",
          ],
        },
        {
          judul: "3. Jenis Buku Fiksi Populer",
          isi: [
            "Dunia fiksi sangat beragam. Setiap jenis buku fiksi memiliki karakteristik, target pembaca, dan keunikan tersendiri. Berikut adalah jenis-jenis buku fiksi yang populer, khususnya di kalangan remaja.",
            "",
            "1. Novel",
            "• Karya fiksi prosa yang panjang, kompleks, dan memiliki banyak konflik",
            "• Ciri: lebih dari 200 halaman, banyak tokoh, alur kompleks, setting detail",
            "• Subjenis: novel remaja (teenlit), novel sastra, novel populer, novel fantasi, novel sejarah",
            "• Contoh novel remaja: 'Dilan', 'Hujan', 'Sunshine Becomes You', 'Pulang'",
            "",
            "2. Kumpulan Cerpen (Kumpulan Cerita Pendek)",
            "• Kumpulan beberapa cerita pendek dalam satu buku",
            "• Ciri: setiap cerita berdiri sendiri, bisa bertema sama atau berbeda",
            "• Jumlah halaman per cerpen: 2–20 halaman (dibaca sekali duduk)",
            "• Contoh: 'Senyum Karyamin' karya Ahmad Tohari, 'Berhentilah Mencintaimu' karya Boy Candra",
            "",
            "3. Antologi Puisi",
            "• Kumpulan puisi dari satu atau beberapa penyair dalam satu buku",
            "• Ciri: menggunakan bahasa padat, kaya majas, sarat makna kiasan",
            "• Antologi bisa bertema khusus (cinta, alam, sosial) atau bersifat umum",
            "• Contoh: 'Hujan Bulan Juni' karya Sapardi Djoko Damono, 'Aku Ingin' karya Chairil Anwar",
            "",
            "4. Naskah Drama",
            "• Karya fiksi yang ditulis untuk dipentaskan di atas panggung",
            "• Ciri: berbentuk dialog antartokoh, dilengkapi petunjuk lakuan (stage direction)",
            "• Struktur naskah drama: prolog → dialog → epilog",
            "• Contoh: 'Opera Kecoa' karya Rendra, 'Dag Dig Dug' karya Putu Wijaya",
            "",
            "5. Fiksi Mini (Flash Fiction / Microfiction)",
            "• Cerita sangat pendek yang bisa dibaca dalam waktu 1–5 menit",
            "• Jumlah kata: 100–1.000 kata per cerita",
            "• Populer di media sosial dan platform digital",
            "• Menuntut kepadatan makna dalam ruang terbatas",
            "",
            "Tips Memilih Buku Fiksi:",
            "• Sesuaikan dengan minat: suka fantasi? petualangan? romance? misteri?",
            "• Mulai dari novel remaja yang bahasanya ringan dan dekat dengan keseharian",
            "• Baca sinopsis atau review di Goodreads untuk gambaran awal",
            "• Jangan takut berhenti jika buku tidak menarik — coba buku lain!",
          ],
          contoh: [
            "Contoh perbandingan jenis fiksi berdasarkan tema yang sama 'cinta dan kehilangan':",
            "",
            "| Jenis | Judul & Penulis | Ciri Khas |",
            "|-------|-----------------|-----------|",
            "| Novel | 'Hujan' — Tere Liye | Alur kompleks, banyak tokoh, latar futuristik |",
            "| Cerpen | 'Mata yang Enak Dipandang' — Ahmad Tohari | Satu konflik, selesai dalam 10 menit baca |",
            "| Puisi | 'Aku Ingin' — Sapardi | Bahasa padat, metaforis, satu halaman |",
            "| Naskah Drama | 'Tunggu Apa Lagi' — Rendra | Dialog dominan, ada petunjuk pementasan |",
          ],
        },
        {
          judul: "4. Struktur dan Alur Fiksi",
          isi: [
            "Alur (plot) adalah tulang punggung cerita fiksi. Alur yang baik membuat pembaca terus penasaran dan terlibat secara emosional. Mari kita pelajari jenis-jenis alur dan bagaimana menganalisisnya.",
            "",
            "A. Tahapan Alur Klasik (Struktur Dramatik)",
            "",
            "1. Pengenalan (Eksposisi)",
            "• Memperkenalkan tokoh utama, latar tempat, waktu, dan suasana awal",
            "• Memberikan informasi latar belakang yang diperlukan untuk memahami cerita",
            "• Contoh: perkenalan tokoh Dilan di bandara saat akan pergi ke Universitas Indonesia",
            "",
            "2. Konflik Muncul (Rising Action)",
            "• Mulai muncul masalah atau rintangan yang dihadapi tokoh",
            "• Konflik berkembang secara bertahap, semakin rumit dan menegangkan",
            "• Biasanya bagian terpanjang dalam cerita — pembaca dibuat penasaran",
            "",
            "3. Klimaks",
            "• Puncak ketegangan: titik tertinggi konflik",
            "• Tokoh harus membuat keputusan penting atau menghadapi tantangan terbesar",
            "• Contoh: pertemuan kembali Dilan dan Milea setelah perpisahan yang menyakitkan",
            "",
            "4. Antiklimaks (Falling Action)",
            "• Ketegangan mulai menurun",
            "• Konflik mulai menemukan arah penyelesaian",
            "• Konsekuensi dari keputusan di klimaks mulai terlihat",
            "",
            "5. Resolusi (Penyelesaian)",
            "• Cerita sampai pada titik akhir",
            "• Bisa berupa happy ending, sad ending, atau open ending",
            "• Open ending: pembaca diajak menebak sendiri kelanjutannya",
            "",
            "B. Jenis Alur Berdasarkan Urutan Waktu",
            "",
            "1. Alur Maju (Kronologis)",
            "• Cerita bergerak maju dari awal ke akhir secara linear",
            "• Mudah diikuti, cocok untuk cerita detektif dan petualangan",
            "• Contoh: 'The Hobbit' — perjalanan Bilbo dari awal hingga pulang",
            "",
            "2. Alur Mundur (Flashback / Regresif)",
            "• Cerita dimulai dari akhir atau tengah, lalu mundur ke masa lalu",
            "• Sering digunakan untuk membangun misteri atau mengungkap latar tokoh",
            "• Contoh: 'Dilan' — dimulai dari masa dewasa, flashback ke masa SMA",
            "",
            "3. Alur Campuran (Maju-Mundur)",
            "• Kombinasi alur maju dan mundur dalam satu cerita",
            "• Memberikan perspektif waktu yang kaya dan dinamis",
            "• Banyak digunakan novel sastra kontemporer",
            "• Contoh: 'Laskar Pelangi' — diawali masa dewasa lalu flashback ke masa SD",
            "",
            "C. Alur Berdasarkan Struktur",
            "1. Alur Linier: peristiwa berurutan secara logis dan kronologis",
            "2. Alur Nonlinier: peristiwa tidak berurutan (loncat-loncat) — butuh konsentrasi lebih",
            "3. Alur Lingkar: cerita berakhir di titik awal (circular narrative)",
            "",
            "Tips Menganalisis Alur: Bacalah cerita sekali penuh, catat peristiwa-peristiwa penting, lalu petakan dalam diagram alur. Identifikasi di mana klimaks terjadi dan bagaimana pengarang membangun ketegangan.",
          ],
          contoh: [
            "Perbandingan jenis alur dalam tiga novel populer:",
            "",
            "| Novel | Jenis Alur | Penjelasan |",
            "|-------|-----------|------------|",
            "| 'Sunshine Becomes You' — Ilana Tan | Maju | Kisah cinta Ellie dan Alex mengalir dari pertemuan → konflik → penyelesaian secara linear |",
            "| 'Dilan' — Pidi Baiq | Mundur | Dimulai dari Milea dewasa merenung, lalu flashback ke masa SMA |",
            "| 'Laskar Pelangi' — Andrea Hirata | Campuran | Pembukaan di masa dewasa → kilas balik masa SD → kembali ke masa sekarang |",
            "",
            "PENTING: Tidak ada jenis alur yang 'lebih baik' dari yang lain. Alur yang baik adalah alur yang sesuai dengan kebutuhan cerita dan mampu membuat pembaca tetap terlibat dari awal hingga akhir.",
          ],
        },
        {
          judul: "5. Kebahasaan Fiksi: Majas, Diksi, dan Gaya Bahasa",
          isi: [
            "Kekuatan sebuah karya fiksi tidak hanya terletak pada ceritanya, tetapi juga pada cara pengarang menggunakan bahasa. Setiap pengarang memiliki gaya bahasa yang khas — seperti sidik jari sastra.",
            "",
            "A. Majas (Bahasa Kiasan)",
            "Majas adalah gaya bahasa yang digunakan untuk menciptakan efek tertentu, memperindah, atau memperkuat makna.",
            "",
            "1. Majas Perbandingan",
            "• Personifikasi: benda mati diberi sifat manusia — 'Angin berbisik di telingaku.'",
            "• Metafora: perbandingan tanpa kata pembanding — 'Dia adalah pelita di kegelapan.'",
            "• Simile: perbandingan dengan kata 'bagai', 'seperti' — 'Wajahnya bagai bulan purnama.'",
            "• Hiperbola: pernyataan berlebihan — 'Air matanya membantai jutaan sungai.'",
            "",
            "2. Majas Pertentangan",
            "• Ironi: sindiran halus — 'Bagus benar kerjamu, sampai meja itu rusak.'",
            "• Paradoks: pernyataan seolah bertentangan — 'Semakin dikejar, semakin ia menjauh.'",
            "",
            "3. Majas Penegasan",
            "• Repetisi: pengulangan kata untuk penekanan — 'Aku datang, aku lihat, aku menang.'",
            "• Klimaks: urutan meningkat — 'Semua orang, dari anak-anak, remaja, hingga orang tua, menonton pertunjukan itu.'",
            "",
            "B. Diksi (Pilihan Kata)",
            "• Diksi adalah pemilihan kata yang tepat untuk mengungkapkan gagasan",
            "• Fiksi menggunakan diksi lebih kaya dan variatif dibanding teks nonfiksi",
            "• Contoh: 'berjalan' vs 'melangkah' vs 'melenggang' vs 'bergelayut' — masing-masing memberi nuansa berbeda",
            "• Diksi konkret: kata yang merujuk pada benda nyata (meja, kursi, hujan, senja)",
            "• Diksi abstrak: kata yang merujuk pada konsep (cinta, harapan, kesedihan, keadilan)",
            "",
            "C. Gaya Bahasa Pengarang",
            "• Setiap pengarang memiliki gaya khas: kalimat pendek dan lugas (Pidi Baiq), kalimat panjang dan puitis (Tere Liye), atau narasi deskriptif yang detail (Andrea Hirata)",
            "• Gaya bahasa mencerminkan kepribadian dan pandangan dunia pengarang",
            "",
            "Tips: Untuk mengenali gaya bahasa pengarang, baca dua buku berbeda dari pengarang yang sama. Perhatikan pola pemilihan kata, panjang kalimat, dan penggunaan majas yang konsisten.",
          ],
          contoh: [
            "Perbandingan gaya bahasa tiga pengarang Indonesia:",
            "",
            "Pidi Baiq ('Dilan'):",
            "• Gaya: Ringan, percakapan sehari-hari, kalimat pendek, banyak dialog",
            "• Contoh: 'Milea, kamu cantik hari ini.' 'Memangnya kemarin tidak?' 'Kemarin juga, tapi hari ini lebih.'",
            "",
            "Tere Liye ('Hujan'):",
            "• Gaya: Puitis, kalimat panjang, banyak metafora, deskriptif, emosional",
            "• Contoh: 'Hujan turun malam itu menemani kesedihanku. Rintiknya seperti air mata yang tak henti jatuh dari langit — sama seperti hatiku yang remuk redam.'",
            "",
            "Andrea Hirata ('Laskar Pelangi'):",
            "• Gaya: Deskriptif kaya, humor cerdas, istilah ilmiah, narasi kuat",
            "• Contoh: 'Ia telah mengubah kacamata dunia tentang Belitung yang semula hanya dikenal sebagai lumbung timah, menjadi lumbung imajinasi dan inspirasi.'",
          ],
        },
        {
          judul: "6. Membandingkan Dua Karya Fiksi",
          isi: [
            "Kemampuan membandingkan dua karya fiksi adalah salah satu keterampilan literasi tingkat tinggi. Dengan membandingkan, kita dapat memahami keunikan setiap karya secara lebih mendalam.",
            "",
            "A. Aspek-Aspek Perbandingan",
            "",
            "1. Tema dan Pesan",
            "• Apakah kedua karya mengangkat tema yang sama atau berbeda?",
            "• Bagaimana cara masing-masing karya menyampaikan pesannya?",
            "• Apakah ada perbedaan sudut pandang moral atau ideologis?",
            "",
            "2. Karakter Tokoh",
            "• Bagaimana karakter tokoh utama digambarkan?",
            "• Apakah tokoh mengalami perkembangan (dinamis) atau tetap (statis)?",
            "• Perbedaan motivasi, konflik batin, dan resolusi tokoh",
            "",
            "3. Alur dan Struktur",
            "• Perbedaan jenis alur (maju, mundur, campuran)",
            "• Kecepatan cerita: apakah lambat dan detail, atau cepat dan padat?",
            "• Bagaimana klimaks dibangun dan diselesaikan?",
            "",
            "4. Gaya Bahasa",
            "• Perbedaan diksi, majas, dan panjang kalimat",
            "• Apakah bahasanya formal, sehari-hari, puitis, atau sarkastik?",
            "• Bagaimana dialog ditulis? Natural atau formal?",
            "",
            "5. Latar dan Suasana",
            "• Perbedaan setting tempat, waktu, dan sosial",
            "• Bagaimana latar memengaruhi jalan cerita dan karakter tokoh?",
            "",
            "B. Metode Membandingkan",
            "",
            "1. Metode Baca-Banding: Baca kedua karya secara utuh, lalu buat tabel perbandingan",
            "2. Metode Fokus: Pilih satu aspek (misal: tokoh), analisis secara mendalam di kedua karya",
            "3. Metode Tematik: Identifikasi tema bersama, lalu bandingkan cara penanganannya",
            "",
            "Contoh Kerangka Perbandingan:",
            "• Pembukaan: Perkenalan kedua karya (judul, penulis, tahun terbit)",
            "• Isi: Perbandingan per aspek (tema, tokoh, alur, gaya bahasa, latar)",
            "• Analisis: Mengapa ada perbedaan? Apa yang membuat masing-masing unik?",
            "• Kesimpulan: Mana yang lebih efektif menyampaikan pesannya? Mengapa?",
          ],
          contoh: [
            "Perbandingan 'Dilan' (Pidi Baiq) dan 'Hujan' (Tere Liye):",
            "",
            "| Aspek | 'Dilan' | 'Hujan' |",
            "|-------|---------|---------|",
            "| Tema | Cinta remaja, kenangan SMA, persahabatan | Kehilangan, ingatan, waktu, pengorbanan |",
            "| Tokoh Utama | Dilan (karismatik, romantis, nakal) | Esok (kuat, penyayang, rela berkorban) |",
            "| Alur | Mundur — flashback dari masa dewasa | Maju — linear dari masa kecil hingga dewasa |",
            "| Gaya Bahasa | Santai, dialog ringan, humor romantis | Puitis, metaforis, narasi emosional yang kuat |",
            "| Latar | Bandung 1990-an (dunia nyata) | Kota futursitik (dunia imajiner) |",
            "| Pesan | Cinta pertama adalah kenangan paling indah dalam hidup | Terkadang mengorbankan kebahagiaan sendiri adalah bentuk cinta tertinggi |",
            "",
            "Kesimpulan: Kedua novel sama-sama kuat dalam membangun emosi pembaca, tetapi dengan pendekatan yang sangat berbeda. 'Dilan' mengandalkan dialog dan kharisma tokoh, sementara 'Hujan' mengandalkan narasi puitis dan alur yang emosional.",
          ],
        },
        {
          judul: "7. Prosedur Menulis Resensi Buku Fiksi",
          isi: [
            "Resensi adalah ulasan atau penilaian terhadap suatu karya, dalam hal ini buku fiksi. Menulis resensi melatih kita untuk membaca secara kritis dan mengomunikasikan pendapat secara terstruktur.",
            "",
            "A. Pengertian dan Tujuan Resensi",
            "• Resensi berasal dari bahasa Latin revidere atau recensere yang berarti 'memeriksa kembali' atau 'menimbang'",
            "• Tujuan: memberikan informasi, analisis, dan penilaian tentang buku fiksi kepada calon pembaca",
            "• Resensi yang baik bersifat objektif, didukung data dan argumen, bukan sekadar suka atau tidak suka",
            "",
            "B. Langkah-Langkah Menulis Resensi",
            "",
            "1. Membaca Buku secara Menyeluruh",
            "• Baca buku dari awal hingga akhir dengan saksama",
            "• Catat bagian-bagian penting, kutipan menarik, kelemahan yang ditemukan",
            "• Jangan menulis resensi hanya berdasarkan sinopsis atau review orang lain",
            "",
            "2. Mengidentifikasi Data Buku",
            "• Judul buku, nama pengarang, penerbit, tahun terbit, tebal halaman",
            "• ISBN, genre, harga (jika perlu)",
            "• Data ini biasanya ada di halaman awal atau sampul belakang buku",
            "",
            "3. Meringkas Isi Buku",
            "• Tulis sinopsis singkat tanpa spoiler berlebihan",
            "• Gambarkan garis besar cerita: tokoh utama, latar, konflik awal",
            "• Jaga agar ringkasan proporsional — jangan lebih dari 30% dari total resensi",
            "",
            "4. Menganalisis Unsur Karya",
            "• Analisis tema, tokoh, alur, latar, gaya bahasa, sudut pandang",
            "• Gunakan istilah sastra yang tepat (protagonis, klimaks, metafora, dll.)",
            "• Hubungkan unsur-unsur tersebut: apakah tema didukung oleh alur? Apakah gaya bahasa memperkuat suasana?",
            "",
            "5. Memberi Penilaian",
            "• Sampaikan kelebihan buku: apa yang membuatnya menarik?",
            "• Sampaikan kekurangan buku: alur lambat di tengah? tokoh kurang berkembang?",
            "• Beri skala penilaian (misal: 4/5 bintang) dengan argumen yang jelas",
            "• Penilaian harus objektif dan didukung bukti dari teks",
            "",
            "6. Menulis Kesimpulan dan Rekomendasi",
            "• Siapa target pembaca yang cocok untuk buku ini?",
            "• Apakah buku ini layak dibaca? Mengapa?",
            "• Bandingkan dengan buku lain yang serupa jika relevan",
            "",
            "7. Menyunting dan Memublikasikan",
            "• Periksa ejaan, tata bahasa, dan keruntutan argumen",
            "• Pastikan tidak ada spoiler besar yang merusak pengalaman calon pembaca",
            "• Publikasikan di blog, media sosial, Goodreads, atau tugas sekolah",
            "",
            "C. Struktur Resensi yang Baik",
            "1. Judul Resensi: Menarik dan mencerminkan isi resensi",
            "2. Identitas Buku: Data lengkap buku",
            "3. Pembukaan: Pengantar tentang buku dan kesan awal",
            "4. Sinopsis: Ringkasan cerita (tanpa spoiler berlebihan)",
            "5. Analisis: Pembahasan unsur intrinsik dan ekstrinsik",
            "6. Penilaian: Kelebihan dan kekurangan",
            "7. Penutup: Kesimpulan dan rekomendasi",
          ],
          rangkuman: [
            "Rumus menulis resensi: BACA → CATAT → RINGKAS → ANALISIS → NILAI → SIMPULKAN → TERBITKAN",
            "",
            "Ingat: Resensi bukan sekadar 'bagus' atau 'jelek'. Resensi adalah analisis kritis yang didukung argumen dan bukti dari teks. Pembaca resensi ingin tahu MENGAPA buku ini layak (atau tidak layak) dibaca.",
            "",
            "Tips: Mulailah dengan meresensi buku favoritmu! Semakin kamu mengenal bukunya, semakin mudah menulis resensi yang mendalam.",
          ],
        },
      ],
    },
    latihan: [
      {
        id: 1,
        soal: "Fiksi berasal dari bahasa Latin 'fictio' yang artinya...",
        opsi: ["Kenyataan", "Membentuk atau menciptakan", "Cerita nyata", "Karangan ilmiah"],
        jawaban: 1,
        penjelasan: "Fiktio berarti 'membentuk' atau 'menciptakan', merujuk pada sifat fiksi sebagai hasil imajinasi dan kreasi pengarang.",
      },
      {
        id: 2,
        soal: "Berikut ini yang termasuk unsur intrinsik karya fiksi adalah...",
        opsi: ["Latar belakang pengarang", "Kondisi sosial-politik", "Alur cerita", "Nilai budaya masyarakat"],
        jawaban: 2,
        penjelasan: "Alur (plot) adalah unsur intrinsik — unsur yang membangun cerita dari dalam. Latar belakang pengarang, kondisi sosial-politik, dan nilai budaya termasuk unsur ekstrinsik.",
      },
      {
        id: 3,
        soal: "Novel 'Dilan: Dia adalah Dilanku' menggunakan jenis alur...",
        opsi: ["Maju", "Mundur (flashback)", "Campuran", "Lingkar"],
        jawaban: 1,
        penjelasan: "Novel Dilan menggunakan alur mundur: dimulai dari Milea dewasa yang merenung, lalu flashback ke masa SMA-nya.",
      },
      {
        id: 4,
        soal: "Kalimat 'Angin berbisik di telingaku' mengandung majas...",
        opsi: ["Metafora", "Hiperbola", "Personifikasi", "Ironi"],
        jawaban: 2,
        penjelasan: "Personifikasi adalah majas yang memberikan sifat manusia kepada benda mati. Angin tidak bisa berbisik, tetapi digambarkan seolah bisa melakukannya.",
      },
      {
        id: 5,
        soal: "Berikut yang merupakan contoh buku kumpulan cerpen adalah...",
        opsi: ["'Hujan' karya Tere Liye", "'Senyum Karyamin' karya Ahmad Tohari", "'Dilan' karya Pidi Baiq", "'Laskar Pelangi' karya Andrea Hirata"],
        jawaban: 1,
        penjelasan: "'Senyum Karyamin' adalah kumpulan cerpen karya Ahmad Tohari. Tiga lainnya adalah novel.",
      },
      {
        id: 6,
        soal: "Unsur ekstrinsik yang memengaruhi isi novel 'Laskar Pelangi' adalah...",
        opsi: ["Alur yang kompleks", "Tokoh Ikal yang cerdas", "Latar Belitung yang miskin tambang timah", "Sudut pandang orang pertama"],
        jawaban: 2,
        penjelasan: "Kondisi sosial-ekonomi Belitung sebagai daerah tambang timah yang dikuasai asing adalah unsur ekstrinsik yang memengaruhi cerita. Alur, tokoh, dan sudut pandang adalah unsur intrinsik.",
      },
      {
        id: 7,
        soal: "Bagian resensi yang berisi analisis unsur-unsur pembangun cerita disebut...",
        opsi: ["Sinopsis", "Identitas buku", "Analisis karya", "Penutup"],
        jawaban: 2,
        penjelasan: "Analisis karya adalah bagian resensi di mana penulis membahas unsur intrinsik dan ekstrinsik buku fiksi secara mendalam.",
      },
      {
        id: 8,
        soal: "Novel dengan alur nonlinier biasanya...",
        opsi: ["Mudah diikuti karena urut", "Peristiwanya tidak berurutan secara kronologis", "Hanya menggunakan satu sudut pandang", "Tidak memiliki klimaks"],
        jawaban: 1,
        penjelasan: "Alur nonlinier berarti peristiwa dalam cerita tidak disusun secara kronologis. Pembaca harus aktif menyusun urutan waktu cerita.",
      },
      {
        id: 9,
        soal: "Majas yang menggunakan kata 'bagai' atau 'seperti' untuk membandingkan disebut...",
        opsi: ["Metafora", "Personifikasi", "Simile", "Hiperbola"],
        jawaban: 2,
        penjelasan: "Simile adalah majas perbandingan yang menggunakan kata pembanding seperti 'bagai', 'seperti', 'laksana', 'ibarat'.",
      },
      {
        id: 10,
        soal: "Resensi yang baik sebaiknya...",
        opsi: ["Hanya berisi pujian agar penulis senang", "Berdasarkan sinopsis tanpa membaca buku", "Objektif dengan argumen dan bukti dari teks", "Fokus pada kekurangan buku saja"],
        jawaban: 2,
        penjelasan: "Resensi yang baik bersifat objektif, didukung argumen dan bukti dari teks, serta membahas kelebihan dan kekurangan secara berimbang.",
      },
    ],
    praktik: {
      tujuan: "Menulis resensi buku fiksi secara sistematis dengan menganalisis unsur intrinsik dan ekstrinsik.",
      instruksi: "Pilihlah satu buku fiksi yang pernah kamu baca (novel, kumpulan cerpen, atau antologi puisi). Tulislah resensi buku tersebut dengan mengikuti langkah-langkah yang telah dipelajari.",
      langkah: [
        "Pilih satu buku fiksi yang sudah pernah kamu baca dari awal hingga akhir. Pastikan kamu benar-benar mengenal isinya.",
        "Catat identitas buku: judul, penulis, penerbit, tahun terbit, tebal halaman, ISBN jika ada.",
        "Tulis sinopsis singkat (3–5 kalimat) yang menggambarkan cerita tanpa memberikan spoiler berlebihan.",
        "Identifikasi dan analisis unsur intrinsik: tema, tokoh, alur, latar, sudut pandang, dan gaya bahasa. Berikan contoh kutipan dari buku sebagai bukti.",
        "Kaitkan dengan unsur ekstrinsik: bagaimana latar belakang pengarang atau kondisi sosial saat buku ditulis memengaruhi cerita?",
        "Beri penilaian: apa kelebihan dan kekurangan buku ini? Gunakan argumen yang didukung bukti. Beri rating (misal 3,5/5 bintang).",
        "Tulis kesimpulan dan rekomendasi: untuk siapa buku ini cocok? Apakah kamu merekomendasikannya? Mengapa?",
        "Sunting resensi: periksa ejaan, tata bahasa, keruntutan argumen, dan pastikan tidak ada spoiler besar. Kumpulkan dalam bentuk tulisan rapi.",
      ],
      tips: [
        "Pilih buku favoritmu untuk resensi pertama — lebih mudah menulis tentang buku yang kamu sukai.",
        "Gunakan kutipan langsung dari buku untuk memperkuat argumen analisismu.",
        "Jangan takut menyampaikan kekurangan buku, tetapi sampaikan dengan bahasa yang santun dan konstruktif.",
        "Baca contoh resensi dari Goodreads atau blog sastra untuk melihat variasi gaya penulisan resensi.",
        "Mintalah teman membaca resensimu sebelum dikumpulkan untuk mendapat masukan dan perspektif lain.",
      ],
      contoh: "Lihat contoh analisis perbandingan 'Dilan' dan 'Hujan' pada materi 'Membandingkan Dua Karya Fiksi' sebagai model untuk menulis analisis dalam resensi. Gunakan tabel perbandingan jika kamu meresensi lebih dari satu buku.",
    },
    kuis: [
      {
        id: 1,
        soal: "Perbedaan utama antara unsur intrinsik dan ekstrinsik dalam karya fiksi adalah...",
        opsi: [
          "Intrinsik berkaitan dengan isi cerita, ekstrinsik berkaitan dengan fisik buku",
          "Intrinsik berasal dari dalam cerita, ekstrinsik berasal dari luar cerita",
          "Intrinsik hanya untuk novel, ekstrinsik untuk cerpen",
          "Intrinsik ditemukan pembaca, ekstrinsik ditentukan pengarang",
        ],
        jawaban: 1,
        penjelasan: "Unsur intrinsik adalah unsur dari dalam cerita (tema, tokoh, alur, latar, dll.), sedangkan unsur ekstrinsik berasal dari luar cerita (latar belakang pengarang, kondisi sosial-politik, nilai budaya).",
      },
      {
        id: 2,
        soal: "Dalam analisis fiksi, klimaks adalah...",
        opsi: [
          "Bagian awal cerita yang memperkenalkan tokoh",
          "Puncak ketegangan atau titik tertinggi konflik",
          "Bagian akhir cerita yang berisi penyelesaian",
          "Konflik kecil yang muncul di tengah cerita",
        ],
        jawaban: 1,
        penjelasan: "Klimaks adalah puncak ketegangan dalam cerita, titik di mana konflik mencapai intensitas tertinggi dan tokoh harus membuat keputusan penting.",
      },
      {
        id: 3,
        soal: "Kalimat 'Wajahnya bagai bulan purnama yang bersinar di malam gelap' mengandung majas...",
        opsi: ["Metafora", "Personifikasi", "Simile", "Hiperbola"],
        jawaban: 2,
        penjelasan: "Kalimat tersebut menggunakan kata 'bagai' sebagai pembanding, sehingga termasuk majas simile (perbandingan eksplisit).",
      },
      {
        id: 4,
        soal: "Novel dengan alur campuran (maju-mundur) menuntut pembaca untuk...",
        opsi: [
          "Membaca dari halaman terakhir terlebih dahulu",
          "Tidak perlu memahami urutan waktu",
          "Aktif mengikuti lompatan waktu dan menyusun kronologi cerita",
          "Hanya fokus pada satu tokoh saja",
        ],
        jawaban: 2,
        penjelasan: "Alur campuran menuntut pembaca aktif mengikuti perpindahan waktu maju-mundur dan menyusun kronologi cerita secara mental agar cerita dapat dipahami secara utuh.",
      },
      {
        id: 5,
        soal: "Seorang pengarang menggunakan tokoh hewan yang bisa berbicara untuk menyindir perilaku manusia. Ini termasuk jenis fiksi...",
        opsi: ["Fantasi murni", "Fabel modern", "Cerita sejarah", "Fiksi ilmiah"],
        jawaban: 1,
        penjelasan: "Fabel modern adalah cerita yang menggunakan tokoh hewan berperilaku manusia untuk menyampaikan kritik atau pesan tentang kehidupan manusia kontemporer.",
      },
      {
        id: 6,
        soal: "Andre membaca novel 'Pulang' dan ingin menulis resensi. Langkah pertama yang harus ia lakukan adalah...",
        opsi: [
          "Menulis sinopsis berdasarkan review di internet",
          "Membaca novel dari awal hingga akhir dengan saksama",
          "Langsung memberi penilaian berdasarkan sampul buku",
          "Membandingkan dengan novel lain yang pernah dibaca",
        ],
        jawaban: 1,
        penjelasan: "Langkah pertama menulis resensi adalah membaca buku secara menyeluruh. Resensi yang baik harus didasarkan pada pemahaman utuh terhadap isi buku, bukan pada review orang lain atau sampul buku.",
      },
      {
        id: 7,
        soal: "Tokoh yang mengalami perubahan sifat atau kepribadian sepanjang cerita disebut tokoh...",
        opsi: ["Protagonis", "Antagonis", "Statis", "Dinamis"],
        jawaban: 3,
        penjelasan: "Tokoh dinamis (berkembang) mengalami perubahan kepribadian, sikap, atau pandangan sepanjang cerita, berbeda dengan tokoh statis yang tidak berubah.",
      },
      {
        id: 8,
        soal: "Majas yang menyatakan sesuatu dengan cara berlawanan dari maksud sebenarnya, biasanya untuk menyindir, disebut...",
        opsi: ["Paradoks", "Ironi", "Sinekdoke", "Metonimia"],
        jawaban: 1,
        penjelasan: "Ironi adalah majas yang menyatakan sebaliknya dari maksud sebenarnya. Contoh: 'Bagus benar pekerjaanmu, sampai kaca jendela pecah.' Maksud sebenarnya adalah menegur.",
      },
      {
        id: 9,
        soal: "Dalam meresensi buku fiksi, bagian sinopsis sebaiknya...",
        opsi: [
          "Menceritakan seluruh detail cerita agar pembaca tahu semuanya",
          "Tidak lebih dari 30% dari total resensi dan tanpa spoiler berlebihan",
          "Berisi penilaian penulis tentang buku tersebut",
          "Hanya mencantumkan nama tokoh tanpa deskripsi",
        ],
        jawaban: 1,
        penjelasan: "Sinopsis dalam resensi harus proporsional (tidak lebih dari 30% total resensi) dan tidak boleh memberikan spoiler berlebihan yang merusak pengalaman calon pembaca.",
      },
      {
        id: 10,
        soal: "Seorang pembaca kritis membaca novel fiksi sejarah. Ia ingin menganalisis mengapa tokoh utama digambarkan memberontak terhadap pemerintah kolonial. Analisis yang paling tepat adalah menghubungkan dengan unsur ekstrinsik berupa...",
        opsi: [
          "Gaya bahasa pengarang yang puitis",
          "Alur cerita yang menggunakan campuran",
          "Kondisi sosial-politik masa kolonial dan latar belakang pengarang",
          "Sudut pandang orang pertama yang digunakan",
        ],
        jawaban: 2,
        penjelasan: "Pemberontakan tokoh terhadap pemerintah kolonial paling tepat dianalisis melalui unsur ekstrinsik: kondisi sosial-politik masa kolonialisme dan latar belakang pengarang yang mungkin memiliki pandangan antikolonial. Gaya bahasa, alur, dan sudut pandang adalah unsur intrinsik.",
      },
    ],
  };

export default konten;
