import type { Konten, Soal } from "../types";

const kd = "3.9/4.9";

/* =============================================
   Unit 9: Giat Literasi II: Teks Nonfiksi (Pengaya) — VIII S2
   KD 3.9/4.9 — Menganalisis, mengidentifikasi, dan menyajikan teks nonfiksi sebagai bacaan pengaya
   ============================================= */
const konten: Konten = {
    belajar: {
      tujuan: [
        "Memahami hakikat literasi pengaya dan manfaat membaca teks nonfiksi sebagai pengayaan pengetahuan",
        "Mengidentifikasi berbagai jenis buku nonfiksi seperti biografi, buku ilmiah populer, buku referensi, atlas, dan kamus",
        "Menganalisis struktur buku nonfiksi mulai sampul hingga daftar pustaka",
        "Mengenali dan menggunakan kaidah kebahasaan dalam teks nonfiksi, termasuk istilah teknis, kalimat definisi, dan kalimat klasifikasi",
        "Membaca kritis teks nonfiksi dengan memverifikasi fakta, membedakan fakta dan opini, serta mengevaluasi sumber bacaan",
      ],
      materi: [
        {
          judul: "1. Hakikat Literasi Pengaya",
          catatan: "Literasi pengaya adalah kegiatan membaca yang bertujuan memperluas wawasan di luar buku teks pelajaran.",
          isi: [
            "Literasi pengaya merupakan salah satu pilar Gerakan Literasi Sekolah (GLS) yang dicanangkan oleh Kementerian Pendidikan dan Kebudayaan. Kegiatan ini mendorong peserta didik untuk membaca buku-buku nonfiksi yang memperkaya pengetahuan di luar materi wajib kelas.",
            "",
            "Apa itu literasi pengaya?",
            "• Kegiatan membaca buku nonfiksi untuk memperdalam pemahaman pada bidang tertentu",
            "• Bersifat suplementer — melengkapi, bukan menggantikan buku pelajaran utama",
            "• Mencakup berbagai jenis bacaan: buku ilmiah populer, artikel, jurnal, ensiklopedia, dan lain-lain",
            "• Dilakukan secara terprogram oleh sekolah dengan alokasi waktu khusus (misalnya 15 menit membaca sebelum pelajaran)",
            "",
            "Manfaat membaca nonfiksi sebagai bacaan pengaya:",
            "✓ Memperluas cakrawala pengetahuan dan wawasan keilmuan",
            "✓ Mengembangkan kemampuan berpikir kritis dan analitis",
            "✓ Meningkatkan kosakata akademik dan pemahaman istilah ilmiah",
            "✓ Melatih literasi informasi — kemampuan menemukan, mengevaluasi, dan menggunakan informasi",
            "✓ Menumbuhkan minat belajar sepanjang hayat (long-life learning)",
            "✓ Membantu memahami konsep abstrak melalui penjelasan yang lebih mendalam",
            "",
            "Ragam bacaan nonfiksi pengaya:",
            "1. Buku ilmiah populer — menyajikan sains dan pengetahuan dengan bahasa yang mudah dipahami",
            "2. Biografi dan autobiografi — kisah perjalanan hidup tokoh inspiratif",
            "3. Buku referensi — ensiklopedia, kamus, atlas, almanak",
            "4. Artikel ilmiah — tulisan hasil penelitian yang dimuat di jurnal atau majalah",
            "5. Buku panduan/praktis — buku resep, buku keterampilan, buku petunjuk",
            "6. Laporan perjalanan — catatan perjalanan ke suatu tempat atau peristiwa",
            "",
            "PENTING: Literasi pengaya berbeda dengan literasi dasar. Literasi dasar berfokus pada kemampuan membaca, menulis, dan berhitung. Literasi pengaya berfokus pada penguasaan konten dan perluasan wawasan. Keduanya saling melengkapi.",
          ],
          contoh: [
            "Contoh penerapan literasi pengaya di sekolah:",
            "",
            "• Program 'Jumat Membaca' — setiap hari Jumat, siswa membaca buku nonfiksi pilihan selama 30 menit, lalu membuat ringkasan singkat di jurnal baca.",
            "• Sudut baca kelas — setiap kelas menyediakan rak berisi 20-30 buku nonfiksi yang digilir antarkelas setiap bulan.",
            "• Proyek literasi lintas mata pelajaran — misalnya, saat belajar IPA tentang tata surya, siswa membaca buku 'Mengenal Planet-Planet' dari sudut baca.",
            "• Lomba resensi buku — siswa menulis resensi buku nonfiksi favorit, dipajang di mading sekolah.",
            "",
            "Tips: Pilihlah buku nonfiksi yang sesuai dengan minatmu. Suka alam? Baca buku tentang hewan atau tumbuhan. Suka sejarah? Baca biografi pahlawan nasional. Minat adalah kunci konsistensi membaca.",
          ],
        },
        {
          judul: "2. Mengenal Buku Nonfiksi",
          isi: [
            "Buku nonfiksi adalah buku yang berisi informasi faktual, data, dan pengetahuan yang dapat diverifikasi kebenarannya. Berbeda dengan buku fiksi yang mengutamakan imajinasi, buku nonfiksi mengutamakan fakta dan akurasi.",
            "",
            "Berikut adalah jenis-jenis buku nonfiksi yang umum dijumpai:",
            "",
            "A. Biografi dan Autobiografi",
            "• Biografi: riwayat hidup seseorang yang ditulis oleh orang lain",
            "• Autobiografi: riwayat hidup yang ditulis sendiri oleh tokohnya",
            "• Bertujuan menginspirasi dan memberikan teladan melalui perjalanan hidup tokoh",
            "• Contoh: 'Habibie & Ainun' (biografi B.J. Habibie), 'Bung Hatta: Pribadi dan Keteladanannya'",
            "",
            "B. Buku Ilmiah Populer",
            "• Menyajikan pengetahuan ilmiah dengan bahasa yang mudah dipahami masyarakat umum",
            "• Tidak serumit jurnal akademik, tetapi tetap mempertahankan kebenaran ilmiah",
            "• Sering dilengkapi ilustrasi, foto, dan diagram yang memudahkan pemahaman",
            "• Contoh: 'Sapiens' (Yuval Noah Harari), 'Fisika untuk Semua Orang', 'Sejarah Dunia yang Disembunyikan'",
            "",
            "C. Buku Referensi",
            "• Buku yang digunakan untuk mencari informasi spesifik, bukan dibaca dari awal sampai akhir",
            "• Contoh: ensiklopedia, kamus besar bahasa, tesaurus, almanak, buku tahunan statistik",
            "• Disusun secara sistematis dengan indeks dan sistem rujuk-menyilang (cross-reference)",
            "",
            "D. Atlas",
            "• Kumpulan peta geografis yang dilengkapi data tentang suatu wilayah",
            "• Berisi informasi: batas wilayah, topografi, iklim, sumber daya alam, kepadatan penduduk",
            "• Jenis atlas: atlas dunia, atlas nasional, atlas tematik (misalnya atlas sejarah)",
            "• Contoh: 'Atlas Dunia untuk Pelajar', 'Atlas Sejarah Indonesia'",
            "",
            "E. Kamus",
            "• Buku yang memuat daftar kata beserta arti, pelafalan, dan contoh penggunaannya",
            "• Jenis: kamus bahasa (kamus Indonesia, kamus Inggris-Indonesia), kamus istilah (kamus biologi, kamus hukum), kamus tematik (kamus sinonim, kamus peribahasa)",
            "• Contoh: KBBI (Kamus Besar Bahasa Indonesia), Oxford Dictionary, Kamus Biologi Bergambar",
            "",
            "F. Buku Panduan/Praktis",
            "• Berisi petunjuk langkah demi langkah untuk melakukan sesuatu",
            "• Contoh: buku resep masakan, buku panduan berkebun, buku petunjuk penggunaan perangkat lunak",
            "• Struktur: tujuan → alat/bahan → langkah → tips → hasil akhir",
          ],
          contoh: [
            "Perbandingan ciri buku fiksi dan nonfiksi:",
            "",
            "| Aspek | Buku Fiksi | Buku Nonfiksi |",
            "|-------|-----------|--------------|",
            "| Isi | Imajinatif, rekaan | Faktual, berdasarkan data |",
            "| Sumber | Daya cipta pengarang | Observasi, riset, data lapangan |",
            "| Sifat | Subjektif, interpretatif | Objektif, faktual |",
            "| Tujuan | Hiburan, estetika | Informasi, edukasi |",
            "| Bahasa | Konotatif, figuratif | Denotatif, lugas, baku |",
            "| Contoh | Novel, cerpen, puisi | Biografi, ensiklopedia, atlas |",
          ],
        },
        {
          judul: "3. Struktur Buku Nonfiksi",
          isi: [
            "Buku nonfiksi memiliki struktur yang teratur dan sistematis. Memahami struktur ini memudahkan kita dalam membaca, memahami, dan menelusuri informasi dalam buku nonfiksi.",
            "",
            "1. Sampul Buku (Cover)",
            "  • Sampul depan: judul buku, nama penulis, penerbit, ilustrasi yang mewakili isi buku",
            "  • Sampul belakang: sinopsis atau ringkasan isi buku, testimoni, barcode ISBN",
            "  • Punggung buku: judul, nama penulis, logo penerbit (untuk buku fisik)",
            "  • Fungsi sampul: identitas buku sekaligus media promosi",
            "",
            "2. Kata Pengantar",
            "  • Ditulis oleh penulis, editor, atau tokoh yang relevan dengan isi buku",
            "  • Berisi ucapan terima kasih, latar belakang penulisan, tujuan buku",
            "  • Membantu pembaca memahami konteks dan maksud penulis",
            "",
            "3. Daftar Isi",
            "  • Memuat judul bab dan subbab beserta nomor halaman",
            "  • Berfungsi sebagai peta buku — memudahkan pembaca menemukan topik tertentu",
            "  • Daftar isi yang baik bersifat hierarkis: bab → subbab → sub-subbab",
            "",
            "4. Isi Buku (Batang Tubuh)",
            "  • Berisi uraian materi pokok yang terbagi dalam bab-bab dan subbab",
            "  • Setiap bab biasanya terdiri atas pendahuluan, uraian inti, dan rangkuman",
            "  • Dilengkapi dengan ilustrasi, tabel, grafik, atau infografis untuk memperjelas penjelasan",
            "  • Terdapat catatan kaki (footnote) untuk sumber rujukan tertentu",
            "",
            "5. Indeks",
            "  • Daftar kata-kata penting yang disusun secara alfabetis lengkap dengan nomor halaman",
            "  • Memudahkan pembaca mencari topik atau istilah tertentu tanpa membaca seluruh buku",
            "  • Contoh: indeks 'Biodiesel 45, 67, 89' artinya kata biodiesel muncul di halaman 45, 67, dan 89",
            "",
            "6. Glosarium",
            "  • Daftar istilah penting beserta definisinya yang disusun secara alfabetis",
            "  • Membantu pembaca memahami istilah-istilah teknis yang digunakan dalam buku",
            "  • Biasanya ditempatkan sebelum indeks di bagian akhir buku",
            "",
            "7. Daftar Pustaka",
            "  • Daftar semua sumber rujukan yang digunakan penulis dalam menyusun buku",
            "  • Disusun secara alfabetis berdasarkan nama penulis",
            "  • Mengikuti format tertentu: APA, MLA, Chicago, atau gaya selingkung penerbit",
            "  • Memungkinkan pembaca melacak sumber asli untuk verifikasi atau studi lanjutan",
            "",
            "Tips Membaca Buku Nonfiksi: Mulailah dengan membaca daftar isi untuk memahami gambaran besar buku. Gunakan indeks untuk mencari topik spesifik. Bacalah kata pengantar untuk mengetahui tujuan penulisan buku.",
          ],
          contoh: [
            "Contoh urutan struktur buku nonfiksi secara lengkap:",
            "",
            "1. Sampul Depan — judul: 'Ensiklopedia Sains untuk Remaja', penulis: Tim Penerbit",
            "2. Kata Pengantar — penjelasan tujuan: buku ini disusun untuk memperkaya pengetahuan sains siswa SMP",
            "3. Daftar Isi — 8 bab: Tata Surya, Makhluk Hidup, Ekosistem, Energi, dll.",
            "4. Bab 1: Tata Surya — subbab: Planet, Asteroid, Komet, Gerhana",
            "5. Glosarium — definisi istilah: 'Asteroid = benda langit kecil yang mengorbit matahari'",
            "6. Indeks — 'Planet: 12, 15, 22-25', 'Gravitasi: 10-11, 18'",
            "7. Daftar Pustaka — sumber: buku astronomi, jurnal NASA, artikel ilmiah",
            "",
            "Dengan memahami struktur ini, kamu tidak perlu membaca seluruh buku dari awal—cukup gunakan indeks atau daftar isi untuk langsung menuju halaman yang relevan dengan topik yang kamu cari.",
          ],
        },
        {
          judul: "4. Kebahasaan Nonfiksi",
          catatan: "Bahasa dalam teks nonfiksi bersifat denotatif, lugas, dan baku — berbeda dengan bahasa figuratif dalam teks fiksi.",
          isi: [
            "Teks nonfiksi memiliki ciri kebahasaan yang khas. Memahami kaidah ini membantu kita menulis dan menyajikan informasi secara akurat dan efektif.",
            "",
            "1. Istilah Teknis/Ilmiah (Terminologi)",
            "• Penggunaan kata-kata khusus yang berkaitan dengan bidang ilmu tertentu",
            "• Istilah teknis bersifat spesifik dan memiliki makna yang pasti",
            "• Contoh bidang biologi: fotosintesis, ekosistem, klorofil, karnivora",
            "• Contoh bidang geografi: topografi, garis lintang, dataran tinggi, erosi",
            "• Contoh bidang fisika: gravitasi, momentum, frekuensi, resonansi",
            "• Istilah teknis biasanya dicetak tebal atau miring pada pertama kali muncul, lalu dijelaskan di glosarium",
            "",
            "2. Kalimat Definisi",
            "• Kalimat yang menjelaskan pengertian atau batasan suatu istilah/konsep",
            "• Ciri: menggunakan kata 'adalah', 'ialah', 'yaitu', 'merupakan'",
            "• Struktur: Istilah + adalah/ialah/merupakan + penjelasan",
            "• Contoh: 'Fotosintesis adalah proses pengubahan energi cahaya menjadi energi kimia pada tumbuhan.'",
            "• Contoh: 'Ekosistem merupakan suatu sistem ekologi yang terbentuk dari hubungan timbal balik antara makhluk hidup dan lingkungannya.'",
            "",
            "3. Kalimat Klasifikasi",
            "• Kalimat yang mengelompokkan sesuatu berdasarkan kategori atau jenis",
            "• Ciri: menggunakan kata 'dibagi menjadi', 'terdiri atas', 'meliputi', 'dikelompokkan menjadi'",
            "• Struktur: Kelompok umum + dibagi/terdiri + anggota kelompok",
            "• Contoh: 'Berdasarkan jenisnya, batuan dibagi menjadi tiga: batuan beku, batuan sedimen, dan batuan metamorf.'",
            "• Contoh: 'Hewan vertebrata meliputi mamalia, reptil, amfibi, burung, dan ikan.'",
            "",
            "4. Data dan Angka",
            "• Teks nonfiksi sering menyertakan data kuantitatif untuk memperkuat informasi",
            "• Data dapat berupa: statistik, persentase, ukuran, skala, perbandingan",
            "• Contoh: 'Penduduk Indonesia mencapai 270 juta jiwa pada tahun 2020.'",
            "• Contoh: 'Suhu permukaan bumi meningkat 1,1°C sejak era pra-industri.'",
            "• Data harus akurat dan disertai sumber yang jelas",
            "",
            "5. Konjungsi Kausal (Sebab-Akibat)",
            "• Kata hubung yang menunjukkan hubungan sebab dan akibat",
            "• Contoh: karena, sebab, oleh karena itu, sehingga, dengan demikian, akibatnya",
            "• Contoh: 'Karena kandungan karbon dioksida meningkat, suhu bumi pun naik.'",
            "",
            "PENTING: Bahasa nonfiksi harus bersifat denotatif (makna sebenarnya), bukan konotatif (makna kiasan). Hindari majas, ungkapan, atau peribahasa yang dapat menimbulkan multitafsir.",
          ],
          rangkuman: [
            "Rumus ciri kebahasaan teks nonfiksi: 'ITU DATA'",
            "I = Istilah teknis/ilmiah",
            "T = Tepat (denotatif, tidak bermakna ganda)",
            "U = Ungkapan definisi dan klasifikasi",
            "",
            "D = Data dan angka akurat",
            "A = Alasan (konjungsi kausal)",
            "T = Teliti dalam pemilihan kata",
            "A = Akademik (ragam bahasa baku/resmi)",
          ],
        },
        {
          judul: "5. Membaca Kritis Nonfiksi",
          isi: [
            "Membaca kritis adalah kemampuan membaca yang tidak sekadar memahami isi teks, tetapi juga mengevaluasi kebenaran, keakuratan, dan kredibilitas informasi yang disajikan. Kemampuan ini sangat penting di era banjir informasi seperti sekarang.",
            "",
            "1. Memverifikasi Fakta (Fact-Checking)",
            "• Periksa apakah data dan pernyataan dalam teks didukung oleh sumber yang jelas",
            "• Bandingkan informasi dengan sumber lain yang tepercaya (prinsip triangulasi)",
            "• Waspadai klaim yang terlalu sensasional atau bombastis",
            "• Cari tahu: kapan data dikumpulkan? Siapa yang mengumpulkan? Bagaimana metodenya?",
            "• Gunakan situs pengecekan fakta jika ragu, seperti factcheck.id atau turnbackhoax.id",
            "",
            "2. Membedakan Fakta dan Opini",
            "Fakta:",
            "• Pernyataan yang dapat dibuktikan kebenarannya secara objektif",
            "• Bersifat universal dan tidak tergantung pada sudut pandang",
            "• Ciri: mengandung data, angka, tanggal, nama, tempat yang spesifik",
            "• Contoh: 'Indonesia merdeka pada tanggal 17 Agustus 1945.' (dapat diverifikasi)",
            "",
            "Opini:",
            "• Pernyataan yang bersifat subjektif, berupa pendapat, keyakinan, atau penilaian pribadi",
            "• Tidak dapat dibuktikan benar-salah secara mutlak",
            "• Ciri: menggunakan kata bersifat penilaian (menurut saya, sebaiknya, seharusnya, mungkin, tampaknya)",
            "• Contoh: 'Menurut saya, pendidikan di Indonesia perlu diperbaiki.' (pendapat subjektif)",
            "",
            "3. Mengevaluasi Sumber Bacaan",
            "Periksa kredibilitas sumber dengan pertanyaan berikut:",
            "• Siapa penulisnya? Apakah ia ahli di bidang yang ditulisnya?",
            "• Apa latar belakang penulis? (akademisi, jurnalis, praktisi, atau awam?)",
            "• Kapan buku/tulisan diterbitkan? Semakin baru semakin relevan untuk topik sains/teknologi",
            "• Siapa penerbitnya? Apakah penerbit bereputasi baik?",
            "• Apakah buku dilengkapi daftar pustaka? Buku nonfiksi yang baik selalu mencantumkan sumber rujukan",
            "• Apakah ada bias atau kepentingan tertentu di balik tulisan tersebut?",
            "",
            "4. Mengidentifikasi Propaganda dan Bias",
            "• Perhatikan penggunaan bahasa yang emosional atau provokatif",
            "• Waspadai generalisasi yang terlalu luas (selalu, tidak pernah, semua, setiap)",
            "• Periksa apakah penulis hanya menyajikan satu sisi tanpa menyebutkan sisi lain",
            "• Identifikasi apakah ada data yang sengaja dihilangkan atau dimanipulasi",
          ],
          contoh: [
            "Latihan membedakan fakta dan opini:",
            "",
            "Kalimat 1: 'Indonesia memiliki lebih dari 17.000 pulau.'",
            "→ FAKTA (data geografis yang dapat diverifikasi)",
            "",
            "Kalimat 2: 'Indonesia adalah negara terindah di dunia.'",
            "→ OPINI (penilaian estetika yang bersifat subjektif)",
            "",
            "Kalimat 3: 'Berdasarkan data BPS, angka melek huruf Indonesia mencapai 96% pada tahun 2023.'",
            "→ FAKTA (data statistik dengan sumber jelas: BPS)",
            "",
            "Kalimat 4: 'Sebaiknya pemerintah lebih fokus pada pembangunan pendidikan di daerah terpencil.'",
            "→ OPINI (saran/rekomendasi yang bersifat subjektif)",
            "",
            "Kalimat 5: 'Gunung Semeru tercatat meletus pada tanggal 4 Desember 2021.'",
            "→ FAKTA (peristiwa yang tercatat secara resmi oleh PVMBG)",
          ],
        },
        {
          judul: "6. Menulis Laporan Membaca Nonfiksi",
          isi: [
            "Setelah membaca buku nonfiksi, langkah selanjutnya adalah menyusun laporan membaca. Laporan membaca berfungsi sebagai bukti kegiatan literasi sekaligus dokumentasi pemahaman terhadap buku yang dibaca.",
            "",
            "A. Format Laporan Membaca",
            "Sebuah laporan membaca yang baik memuat komponen berikut:",
            "",
            "1. Identitas Buku",
            "  • Judul buku (lengkap dengan anak judul jika ada)",
            "  • Nama penulis",
            "  • Penerbit dan tahun terbit",
            "  • Jumlah halaman",
            "  • ISBN (International Standard Book Number)",
            "",
            "2. Ringkasan Isi Buku",
            "  • Uraian singkat tentang isi pokok buku secara runtut",
            "  • Fokus pada ide-ide utama setiap bab, bukan detail kecil",
            "  • Ditulis dengan bahasa sendiri (parafrase), bukan menyalin",
            "  • Panjang ringkasan: sekitar 200-300 kata untuk satu buku",
            "",
            "3. Simpulan",
            "  • Intisari dari keseluruhan isi buku",
            "  • Jawaban dari pertanyaan: 'Apa inti pesan buku ini?'",
            "  • Ditulis dalam 2-3 kalimat padat",
            "",
            "4. Tanggapan Pribadi",
            "  • Pendapatmu tentang buku yang telah dibaca",
            "  • Hal menarik yang kamu dapatkan dari buku tersebut",
            "  • Kaitan isi buku dengan kehidupan sehari-hari atau pelajaran di sekolah",
            "  • Kelebihan dan kekurangan buku (jika ada)",
            "  • Contoh: 'Buku ini membuat saya lebih memahami pentingnya menjaga ekosistem laut.'",
            "",
            "5. Kutipan Favorit",
            "  • Pilih 2-3 kalimat dari buku yang paling berkesan atau bermakna bagimu",
            "  • Tulis kutipan dan jelaskan mengapa kalimat itu menarik",
            "",
            "B. Kaidah Penulisan Laporan Membaca",
            "• Gunakan bahasa Indonesia yang baik dan benar (EYD)",
            "• Tulis dengan paragraf yang runtut dan koheren",
            "• Hindari pengulangan informasi yang tidak perlu",
            "• Sertakan data pendukung (kutipan halaman, fakta menarik dari buku)",
            "• Simpan laporan dalam portofolio literasi atau jurnal baca pribadi",
          ],
          rangkuman: [
            "Rumus laporan membaca: 'IRSTK'",
            "I = Identitas buku (judul, penulis, penerbit)",
            "R = Ringkasan isi (ide utama setiap bab)",
            "S = Simpulan (inti pesan buku)",
            "T = Tanggapan pribadi (pendapat dan refleksi)",
            "K = Kutipan favorit (kalimat berkesan)",
            "",
            "Tips: Gunakan kartu literasi atau template laporan membaca yang sudah disediakan sekolah. Beberapa sekolah menggunakan format digital di Google Form atau aplikasi literasi.",
          ],
        },
        {
          judul: "7. Prosedur Membuat Kliping dan Catatan Literasi",
          isi: [
            "Selain menulis laporan membaca, kegiatan literasi pengaya dapat didokumentasikan dalam bentuk kliping dan catatan literasi. Kedua kegiatan ini melatih keterampilan mengorganisasi informasi sekaligus menumbuhkan kreativitas.",
            "",
            "A. Kliping Artikel",
            "Kliping adalah kumpulan guntingan artikel dari koran, majalah, atau internet yang dikelompokkan berdasarkan tema tertentu.",
            "",
            "Langkah 1: Pilih Tema",
            "• Tentukan tema spesifik yang ingin dikoleksi (misal: 'Teknologi Ramah Lingkungan' atau 'Tokoh Muda Indonesia')",
            "• Tema yang spesifik memudahkan pencarian dan pengelompokan artikel",
            "",
            "Langkah 2: Kumpulkan Artikel",
            "• Cari artikel dari berbagai sumber: koran, majalah, situs berita terpercaya",
            "• Pastikan artikel relevan dengan tema dan mengandung informasi faktual",
            "• Minimal 5-7 artikel untuk satu tema kliping",
            "",
            "Langkah 3: Gunting dan Kelompokkan",
            "• Gunting artikel beserta sumber dan tanggal terbitnya",
            "• Kelompokkan artikel berdasarkan subtema (misal: artikel tentang energi surya, energi angin, energi air)",
            "• Urutkan dari yang paling umum ke paling spesifik",
            "",
            "Langkah 4: Tempel dan Beri Keterangan",
            "• Tempel artikel pada kertas ukuran A4 atau folio dengan rapi",
            "• Di bawah setiap artikel, tulis: sumber, tanggal, dan ringkasan 2-3 kalimat",
            "• Beri komentar pribadi: apa yang kamu pelajari dari artikel tersebut?",
            "",
            "Langkah 5: Sampul dan Halaman Judul",
            "• Buat sampul kliping: tema kliping, nama, kelas, dan tanggal pembuatan",
            "• Sertakan daftar isi dan daftar sumber (referensi)",
            "",
            "B. Scrapbook Literasi",
            "Scrapbook adalah buku catatan literasi yang lebih kreatif dan personal. Berbeda dengan kliping yang hanya berisi guntingan artikel, scrapbook memadukan catatan pribadi, ilustrasi, dan kutipan.",
            "",
            "Langkah 1: Siapkan Buku Catatan",
            "• Gunakan buku tulis tebal, binder, atau buku sketsa",
            "• Hias sampul sesuai selera untuk membuatmu semangat menulis",
            "",
            "Langkah 2: Buat Format Halaman",
            "• Setiap buku nonfiksi yang dibaca mendapat 2-4 halaman khusus",
            "• Cantumkan: judul buku, nama penulis, tanggal selesai baca",
            "• Rating baca (1-5 bintang) dan status baca (selesai / belum selesai)",
            "",
            "Langkah 3: Isi Halaman Scrapbook",
            "✓ Ringkasan isi buku dalam bentuk mind map atau poin-poin",
            "✓ Kutipan favorit yang dihias dengan stiker atau spidol warna",
            "✓ Ilustrasi atau gambar yang menggambarkan isi buku",
            "✓ Refleksi pribadi: hal baru yang dipelajari, pertanyaan yang muncul",
            "✓ Rencana aksi: apa yang ingin dilakukan setelah membaca buku ini",
            "",
            "Tips Membuat Catatan Literasi: Gunakan metode 'Cornell Notes' — bagi halaman menjadi tiga bagian: catatan utama, kata kunci/pertanyaan di margin kiri, dan ringkasan di bagian bawah. Metode ini membantu otak mengorganisasi informasi dengan lebih baik.",
          ],
          rangkuman: [
            "Pilihan dokumentasi literasi pengaya:",
            "⊲ Kliping → cocok untuk mengoleksi artikel dari koran/majalah berdasarkan tema",
            "⊲ Scrapbook literasi → cocok untuk dokumentasi kreatif dan personal",
            "⊲ Jurnal baca → catatan harian tentang buku yang sedang dibaca",
            "⊲ Kartu literasi → format ringkas untuk setiap buku (depan: identitas, belakang: ringkasan)",
            "",
            "PENTING: Pilih format yang paling sesuai dengan gaya belajarmu. Tidak ada format yang 'paling benar' — yang terpenting adalah konsistensi mendokumentasikan kegiatan literasi.",
          ],
        },
      ],
    },
    latihan: [
      {
        id: 1,
        soal: "Berikut ini yang termasuk buku nonfiksi adalah...",
        opsi: ["Novel Laskar Pelangi", "Kumpulan cerpen Senja di Pelabuhan Kecil", "Ensiklopedia Sains untuk Remaja", "Antologi puisi Hujan Bulan Juni"],
        jawaban: 2,
        penjelasan: "Ensiklopedia Sains untuk Remaja adalah buku nonfiksi karena berisi informasi faktual dan ilmiah. Tiga pilihan lainnya adalah karya fiksi.",
      },
      {
        id: 2,
        soal: "Bagian buku nonfiksi yang berfungsi sebagai peta untuk menemukan topik tertentu adalah...",
        opsi: ["Kata pengantar", "Daftar isi", "Glosarium", "Indeks"],
        jawaban: 1,
        penjelasan: "Daftar isi memuat judul bab dan subbab beserta nomor halaman, berfungsi sebagai peta buku yang memudahkan pembaca menemukan topik tertentu.",
      },
      {
        id: 3,
        soal: "Kalimat berikut yang termasuk kalimat definisi adalah...",
        opsi: ["Hewan karnivora memakan daging, herbivora memakan tumbuhan", "Menurut saya, belajar sains itu menyenangkan", "Fotosintesis adalah proses pengubahan energi cahaya menjadi energi kimia pada tumbuhan", "Indonesia memiliki banyak gunung berapi yang tersebar di berbagai pulau"],
        jawaban: 2,
        penjelasan: "Kalimat 'Fotosintesis adalah...' merupakan kalimat definisi karena menjelaskan pengertian suatu istilah menggunakan kata 'adalah'.",
      },
      {
        id: 4,
        tipe: "BENAR_SALAH",
        soal: "Fakta adalah pernyataan yang dapat dibuktikan kebenarannya, sedangkan opini bersifat subjektif.",
        opsi: ["Benar", "Salah"],
        jawaban: 0,
        penjelasan: "Fakta adalah pernyataan yang dapat dibuktikan kebenarannya secara objektif, sedangkan opini adalah pendapat subjektif yang tidak dapat diuji kebenarannya secara mutlak.",
      },
      {
        id: 5,
        tipe: "ISIAN",
        soal: "Buku yang berisi kumpulan peta geografis dan data wilayah disebut...",
        opsi: ["atlas"],
        jawaban: "atlas",
        penjelasan: "Atlas adalah kumpulan peta geografis yang dilengkapi data seperti batas wilayah, topografi, dan kepadatan penduduk.",
      },
      {
        id: 6,
        tipe: "BENAR_SALAH",
        soal: "Istilah 'fotosintesis', 'ekosistem', dan 'klorofil' termasuk dalam kategori kata sifat.",
        opsi: ["Benar", "Salah"],
        jawaban: "1",
        penjelasan: "Istilah-istilah tersebut adalah terminologi ilmiah dalam bidang biologi yang memiliki makna spesifik dan pasti, bukan kata sifat.",
      },
      {
        id: 7,
        soal: "Berikut ini yang bukan merupakan komponen laporan membaca adalah...",
        opsi: ["Identitas buku", "Ringkasan isi", "Daftar harga buku", "Tanggapan pribadi"],
        jawaban: 2,
        penjelasan: "Daftar harga buku bukan merupakan komponen laporan membaca. Laporan membaca terdiri atas identitas buku, ringkasan isi, simpulan, tanggapan pribadi, dan kutipan favorit.",
      },
      {
        id: 8,
        soal: "Contoh buku biografi yang tepat adalah...",
        opsi: ["Panduan Berkebun untuk Pemula", "Habibie & Ainun", "Atlas Dunia", "Kamus Besar Bahasa Indonesia"],
        jawaban: 1,
        penjelasan: "'Habibie & Ainun' adalah buku biografi yang menceritakan kisah hidup B.J. Habibie dan istrinya. Pilihan lain adalah buku panduan, atlas, dan kamus.",
      },
      {
        id: 9,
        soal: "Saat membaca kritis buku nonfiksi, langkah yang tepat untuk memverifikasi fakta adalah...",
        opsi: ["Langsung percaya pada semua data yang disajikan", "Membandingkan informasi dengan sumber lain yang terpercaya", "Mengabaikan data yang sulit dipahami", "Membaca hanya bagian yang menarik saja"],
        jawaban: 1,
        penjelasan: "Untuk memverifikasi fakta, bandingkan informasi dengan sumber lain yang tepercaya (triangulasi) dan periksa kredibilitas penulis serta penerbit.",
      },
      {
        id: 10,
        soal: "Glosarium dalam buku nonfiksi berfungsi untuk...",
        opsi: ["Menunjukkan nomor halaman istilah penting", "Menjelaskan arti istilah-istilah teknis yang digunakan dalam buku", "Memuat ucapan terima kasih penulis", "Menampilkan daftar isi secara alfabetis"],
        jawaban: 1,
        penjelasan: "Glosarium adalah daftar istilah penting beserta definisinya yang membantu pembaca memahami istilah teknis yang digunakan dalam buku tersebut.",
      },
    ],
    praktik: {
      tujuan: "Membaca satu buku nonfiksi pilihan dan menyusun laporan membaca lengkap beserta kliping atau catatan literasi.",
      instruksi: "Pilihlah satu buku nonfiksi dari perpustakaan sekolah atau sudut baca kelas. Bacalah dengan saksama, lalu buat laporan membaca sesuai format. Sebagai pelengkap, buatlah kliping satu artikel yang relevan dengan tema buku yang kamu baca.",
      langkah: [
        "Pilih satu buku nonfiksi yang sesuai dengan minatmu — bisa berupa biografi, buku ilmiah populer, atau ensiklopedia.",
        "Baca buku secara menyeluruh. Catat bagian-bagian penting, fakta menarik, dan kutipan yang berkesan selama membaca.",
        "Tulis identitas buku: judul, penulis, penerbit, tahun terbit, jumlah halaman, dan ISBN.",
        "Buat ringkasan isi buku sepanjang 200-300 kata. Tulis dengan bahasamu sendiri, fokus pada ide pokok setiap bab.",
        "Tulis simpulan berupa inti pesan buku dalam 2-3 kalimat padat.",
        "Tulis tanggapan pribadi: apa hal baru yang kamu pelajari? Apa yang paling menarik? Bagaimana kaitannya dengan kehidupan sehari-hari? Sertakan kelebihan dan kekurangan buku.",
        "Pilih 2-3 kutipan favorit dari buku dan jelaskan alasanmu memilihnya.",
        "Cari satu artikel dari koran, majalah, atau internet yang relevan dengan tema buku. Buat kliping sederhana: gunting/tempel atau print artikel, tulis sumber dan ringkasan, serta beri komentar pribadi.",
      ],
      tips: [
        "Pilih buku nonfiksi yang sesuai dengan hobimu — membaca akan terasa lebih menyenangkan jika topiknya kamu sukai.",
        "Gunakan sticky notes untuk menandai halaman-halaman penting saat membaca.",
        "Jangan menyalin kalimat langsung dari buku — gunakan teknik parafrase agar ringkasanmu orisinal.",
        "Untuk kliping digital, kamu bisa menggunakan aplikasi seperti Pinterest atau Notion untuk menyimpan artikel secara rapi.",
        "Konsistenlah menulis laporan membaca setiap kali selesai membaca satu buku — kumpulkan sebagai portofolio literasi pribadi.",
      ],
      contoh: "Contoh laporan membaca buku 'Sapiens' oleh Yuval Noah Harari: Identitas buku (judul, penulis, penerbit HarperCollins, 2015, 464 hlm) → Ringkasan: buku ini mengupas sejarah peradaban manusia dari era pemburu-pengumpul hingga revolusi sains → Simpulan: kemampuan manusia bercerita dan bekerja sama dalam skala besar adalah kunci dominasi Homo sapiens → Tanggapan: buku ini membuka wawasan saya tentang bagaimana uang, negara, dan agama adalah 'fiksi bersama' yang kita sepakati → Kutipan favorit: 'Kesuksesan Homo sapiens adalah karena satu-satunya hewan yang dapat bekerja sama secara fleksibel dalam jumlah besar.'",
    },
    kuis: [
      {
        id: 1,
        tipe: "BENAR_SALAH",
        soal: "Perbedaan utama buku fiksi dan nonfiksi terletak pada jumlah halaman dan ketebalan buku.",
        opsi: ["Benar", "Salah"],
        jawaban: 1,
        penjelasan: "Perbedaan utama: buku fiksi bersifat imajinatif (hasil rekaan), sedangkan buku nonfiksi bersifat faktual (berdasarkan data dan informasi yang dapat diverifikasi).",
      },
      {
        id: 2,
        soal: "Kalimat 'Berdasarkan jenis makanannya, hewan dibagi menjadi karnivora, herbivora, dan omnivora' termasuk kalimat...",
        opsi: ["Definisi", "Klasifikasi", "Perbandingan", "Perintah"],
        jawaban: 1,
        penjelasan: "Kalimat tersebut adalah kalimat klasifikasi karena mengelompokkan hewan berdasarkan jenis makanannya menggunakan kata 'dibagi menjadi'.",
      },
      {
        id: 3,
        tipe: "ISIAN",
        soal: "Bagian dari buku nonfiksi yang memuat daftar kata penting beserta nomor halamannya secara alfabetis adalah...",
        opsi: ["indeks"],
        jawaban: "indeks",
        penjelasan: "Indeks adalah daftar kata penting yang disusun alfabetis lengkap dengan nomor halaman. Glosarium berisi definisi istilah, bukan nomor halaman.",
      },
      {
        id: 4,
        soal: "Seorang siswa membaca buku 'Sejarah Dunia yang Disembunyikan'. Untuk mengecek kredibilitas buku tersebut, langkah paling tepat adalah...",
        opsi: ["Membaca sampul belakang buku saja", "Mencek daftar pustaka dan latar belakang penulis", "Melihat jumlah halaman buku", "Membaca testimoni di sampul depan"],
        jawaban: "1",
        penjelasan: "Kredibilitas buku nonfiksi dapat dievaluasi dengan memeriksa daftar pustaka (apakah sumbernya terpercaya?) dan latar belakang penulis (apakah ia ahli di bidangnya?).",
      },
      {
        id: 5,
        soal: "Pernyataan berikut yang merupakan opini adalah...",
        opsi: ["Gunung Merapi terletak di perbatasan DIY dan Jawa Tengah", "Berdasarkan data BMKG, gempa berkekuatan 5,2 SR mengguncang Lombok", "Menurut saya, kurikulum merdeka lebih baik dari kurikulum sebelumnya", "Indonesia memiliki 38 provinsi pada tahun 2024"],
        jawaban: 2,
        penjelasan: "Pernyataan 'Menurut saya...' adalah opini karena mengandung penilaian subjektif yang ditandai oleh frasa 'menurut saya'. Tiga pilihan lain adalah pernyataan faktual yang dapat diverifikasi.",
      },
      {
        id: 6,
        tipe: "BENAR_SALAH",
        soal: "Autobiografi adalah riwayat hidup seseorang yang ditulis oleh orang lain.",
        opsi: ["Benar", "Salah"],
        jawaban: 1,
        penjelasan: "Autobiografi ditulis oleh tokohnya sendiri (first-person), sedangkan biografi ditulis oleh orang lain (third-person) tentang riwayat hidup seorang tokoh.",
      },
      {
        id: 7,
        soal: "Tujuan utama mencantumkan daftar pustaka dalam buku nonfiksi adalah...",
        opsi: ["Mempercantik tampilan buku", "Menunjukkan banyaknya sumber yang dibaca penulis", "Memberi kredit pada sumber rujukan dan memudahkan verifikasi", "Memenuhi syarat penerbitan buku"],
        jawaban: 2,
        penjelasan: "Daftar pustaka berfungsi untuk memberikan pengakuan (kredit) kepada sumber rujukan yang digunakan penulis sekaligus memungkinkan pembaca melacak dan memverifikasi sumber asli.",
      },
      {
        id: 8,
        soal: "Manakah pernyataan yang tepat tentang literasi pengaya?",
        opsi: ["Hanya berlaku untuk mata pelajaran Bahasa Indonesia", "Menggantikan buku teks wajib di sekolah", "Bertujuan memperluas wawasan di luar buku pelajaran utama", "Hanya dilakukan oleh siswa yang gemar membaca"],
        jawaban: 2,
        penjelasan: "Literasi pengaya bersifat suplementer — bertujuan memperluas wawasan di luar buku teks pelajaran utama, bukan menggantikannya. Berlaku untuk semua mata pelajaran.",
      },
      {
        id: 9,
        soal: "Kalimat 'Akibatnya, suhu permukaan bumi meningkat 1,1°C sejak era pra-industri' mengandung konjungsi...",
        opsi: ["Temporal", "Kausal", "Koordinatif", "Subordinatif waktu"],
        jawaban: 1,
        penjelasan: "Kata 'akibatnya' adalah konjungsi kausal yang menunjukkan hubungan sebab-akibat. Dalam kalimat tersebut, 'akibatnya' merujuk pada dampak dari penyebab yang disebut sebelumnya.",
      },
      {
        id: 10,
        soal: "Scrapbook literasi berbeda dengan kliping karena scrapbook...",
        opsi: ["Hanya berisi gambar tanpa tulisan", "Lebih kreatif dan personal, memadukan catatan, ilustrasi, dan kutipan", "Tidak memerlukan buku atau kertas", "Hanya digunakan untuk buku fiksi"],
        jawaban: 1,
        penjelasan: "Scrapbook literasi lebih kreatif dan personal karena memadukan catatan pribadi, ilustrasi, kutipan favorit, mind map, dan refleksi — tidak sekadar mengoleksi artikel seperti kliping.",
      },
    ],
  };

export default konten;
