// @ts-nocheck
import type { Konten, Soal } from "../types";

const konten: Konten = {
    belajar: {
      tujuan: [
        "Memahami hakikat, ciri, dan unsur-unsur teks berita",
        "Mengidentifikasi unsur 5W+1H dalam teks berita secara tepat",
        "Menganalisis struktur teks berita: judul, kepala berita, tubuh berita, ekor berita",
        "Menerapkan kaidah kebahasaan teks berita dalam penulisan",
        "Memproduksi teks berita dengan unsur dan struktur yang lengkap",
      ],
      materi: [
        {
          judul: "1. Hakikat Teks Berita",
          isi: [
            "Teks berita adalah teks yang menyampaikan informasi tentang peristiwa atau kejadian faktual dan aktual kepada masyarakat. Berita harus berdasarkan fakta (faktual) dan baru terjadi (aktual).",
            "",
            "Ciri-ciri teks berita:",
            "• Faktual — berdasarkan kenyataan, bukan opini atau karangan",
            "• Aktual — peristiwa baru terjadi, bukan basi",
            "• Informatif — memberikan informasi yang jelas dan lengkap",
            "• Objektif — tidak memihak, berdasarkan data",
            "• Menggunakan bahasa baku dan komunikatif",
            "",
            "Fungsi berita:",
            "• Memberi informasi terkini kepada masyarakat",
            "• Mendidik masyarakat melalui informasi factual",
            "• Mengawasi jalannya pemerintahan dan kebijakan publik",
            "• Menghibur dengan berita ringan atau feature",
            "",
            "PENTING: Berita palsu (hoaks) adalah berita yang tidak faktual. Sebelum menyebarkan berita, pastikan kebenarannya dengan memeriksa sumber berita.",
          ],
          contoh: [
            "Contoh berita faktual vs hoaks:",
            "",
            "Faktual: \"Badan Meteorologi, Klimatologi, dan Geofisika (BMKG) melaporkan gempa bumi berkekuatan 5,2 SR mengguncang wilayah Malang pada pukul 08.15 WIB.\"",
            "",
            "Hoaks: \"Gempa bumi dahsyat akan melanda Indonesia dalam waktu dekat, kata seorang paranormal terkenal.\"",
            "",
            "Ciri berita hoaks: sumber tidak jelas, tidak ada data pendukung, menggunakan bahasa provokatif.",
          ],
        },
        {
          judul: "2. Unsur Berita — 5W+1H",
          isi: [
            "Setiap teks berita harus menjawab enam pertanyaan dasar yang dikenal dengan rumus 5W+1H.",
            "",
            "1. What (Apa) — Peristiwa apa yang terjadi?",
            "  • Inti dari berita: apa yang sedang dibicarakan?",
            "  • Contoh: Gempa bumi mengguncang Malang.",
            "",
            "2. Who (Siapa) — Siapa yang terlibat?",
            "  • Pelaku, korban, atau saksi peristiwa",
            "  • Contoh: Warga Malang dan sekitarnya.",
            "",
            "3. When (Kapan) — Kapan peristiwa terjadi?",
            "  • Waktu kejadian yang jelas (hari, tanggal, jam)",
            "  • Contoh: Hari Senin, 10 Maret 2026, pukul 08.15 WIB.",
            "",
            "4. Where (Di mana) — Di mana peristiwa terjadi?",
            "  • Lokasi kejadian secara spesifik",
            "  • Contoh: Kabupaten Malang, Jawa Timur.",
            "",
            "5. Why (Mengapa) — Mengapa peristiwa itu terjadi?",
            "  • Penyebab atau latar belakang peristiwa",
            " ",
            "6. How (Bagaimana) — Bagaimana proses terjadinya?",
            "  • Kronologi atau urutan peristiwa",
            "",
            "Tips mengingat 5W+1H: 'Aku Siapa? Kapan Di mana? Mengapa Bagaimana?'",
          ],
          contoh: [
            "Analisis 5W+1H pada berita:",
            "",
            "\"Gempa bumi berkekuatan 5,2 SR mengguncang Malang, Jawa Timur, Senin (10/3/2026) pukul 08.15 WIB. Guncangan dirasakan selama 10 detik dan menyebabkan warga berhamburan keluar rumah. Menurut BMKG, gempa ini disebabkan oleh aktivitas sesar aktif di selatan Jawa.\"",
            "",
            "What: Gempa bumi 5,2 SR",
            "Who: Warga Malang",
            "When: Senin, 10/3/2026, 08.15 WIB",
            "Where: Malang, Jawa Timur",
            "Why: Aktivitas sesar aktif",
            "How: Guncangan 10 detik, warga berhamburan",
          ],
        },
        {
          judul: "3. Struktur Teks Berita",
          isi: [
            "Teks berita memiliki struktur piramida terbalik: informasi paling penting di awal, lalu diikuti informasi pendukung.",
            "",
            "1. Judul (Headline)",
            "  • Menarik perhatian pembaca dengan kata-kata yang singkat dan padat",
            "  • Mencerminkan isi berita secara ringkas",
            "  • Contoh: \"Gempa 5,2 SR Guncang Malang, Warga Berhamburan\"",
            "",
            "2. Kepala Berita (Lead/Teras Berita)",
            "  • Paragraf pertama yang mengandung unsur terpenting",
            "  • Menjawab pertanyaan: Apa, Siapa, Kapan, Di mana",
            "  • Contoh: \"Gempa bumi berkekuatan 5,2 SR mengguncang Kabupaten Malang, Jawa Timur, Senin pagi.\"",
            "",
            "3. Tubuh Berita (Body)",
            "  • Berisi informasi tambahan dan penjelasan lebih detail",
            "  • Menjawab pertanyaan: Mengapa dan Bagaimana",
            "  • Berisi kutipan dari narasumber, data pendukung",
            "",
            "4. Ekor Berita (Leg)",
            "  • Informasi yang kurang penting (boleh dihilangkan)",
            "  • Berita lain yang terkait atau informasi tambahan",
            "",
            "Tips: Jika reader hanya membaca lead, mereka sudah tahu inti berita. Tubuh dan ekor hanya sebagai pelengkap.",
          ],
          contoh: [
            "Contoh struktur berita:",
            "",
            "Judul: Lomba Puisi Tingkat Kota Digelar di Balai Kota",
            "",
            "Lead: \"Sebanyak 150 siswa SMP se-Kota Bandung mengikuti lomba puisi yang digelar di Balai Kota Bandung, Sabtu (15/3/2026).\"",
            "",
            "Tubuh: \"Lomba dibuka oleh Wali Kota Bandung pada pukul 08.00 WIB. Para peserta tampil bergiliran membacakan puisi karya sendiri dengan tema 'Kotaku Tercinta'. Menurut ketua panitia, lomba ini bertujuan menumbuhkan kecintaan siswa pada sastra. 'Kami ingin generasi muda mencintai puisi sebagai warisan budaya,' ujarnya.\"",
            "",
            "Ekor: \"Lomba serupa direncanakan akan digelar di tingkat provinsi pada Mei mendatang.\"",
          ],
        },
        {
          judul: "4. Kaidah Kebahasaan Teks Berita",
          isi: [
            "Teks berita memiliki kaidah kebahasaan khusus yang membedakannya dari teks lain.",
            "",
            "1. Bahasa Baku",
            "• Menggunakan kosakata baku sesuai KBBI dan EYD",
            "• Menghindari singkatan tidak resmi, bahasa gaul, atau slang",
            "• Contoh: 'tidak' bukan 'nggak', 'mengatakan' bukan 'bilang'",
            "",
            "2. Kalimat Langsung",
            "• Mengutip langsung pernyataan narasumber dengan tanda petik",
            "• Menunjukkan bahwa berita memiliki sumber yang jelas",
            "• Contoh: 'Kami akan menyelidiki kasus ini lebih lanjut,' ujar Kapolsek.",
            "",
            "3. Kata Kerja Mental",
            "• Kata kerja yang berkaitan dengan pikiran atau perasaan",
            "• Contoh: menduga, memperkirakan, berharap, menginginkan",
            "• Digunakan saat melaporkan pernyataan narasumber",
            "",
            "4. Konjungsi Temporal dan Kausal",
            "• Temporal: kemudian, setelah itu, sebelumnya",
            "• Kausal: karena, sebab, akibatnya, sehingga",
            "",
            "5. Keterangan Waktu dan Tempat",
            "• Memberikan informasi spesifik tentang kapan dan di mana",
            "• Contoh: di Jakarta, pada hari Senin, pukul 14.00 WIB",
          ],
          rangkuman: [
            "Rumus 'B-K-K-K' untuk kaidah kebahasaan berita:",
            "B = Bahasa baku",
            "K = Kalimat langsung (kutipan)",
            "K = Kata kerja mental",
            "K = Keterangan waktu & tempat",
          ],
        },
        {
          judul: "5. Jenis-Jenis Berita",
          isi: [
            "Berdasarkan sifat dan cara penyajiannya, berita dapat dibedakan menjadi beberapa jenis.",
            "",
            "1. Berita Langsung (Straight News)",
            "• Berita singkat yang langsung menyampaikan inti informasi",
            "• Struktur piramida terbalik: inti di awal",
            "• Contoh: berita kecelakaan, bencana alam, peristiwa politik",
            "",
            "2. Berita Opini (Opinion News)",
            "• Berita yang berisi pendapat atau opini narasumber",
            "• Tetap faktual karena opini berasal dari sumber yang jelas",
            "• Contoh: pernyataan pejabat tentang kebijakan baru",
            "",
            "3. Berita Investigasi (Investigative News)",
            "• Berita hasil penyelidikan mendalam oleh wartawan",
            "• Membutuhkan waktu dan data yang banyak",
            "• Contoh: berita tentang korupsi, pelanggaran HAM",
            "",
            "4. Berita Feature",
            "• Berita ringan yang lebih fokus pada sisi human interest",
            "• Gaya penulisan lebih bebas dan menarik",
            "• Contoh: profil tokoh inspiratif, kisah unik masyarakat",
            "",
            "5. Berita Foto (Photo News)",
            "• Berita yang mengandalkan foto sebagai media utama",
            "• Teks hanya sebagai keterangan singkat",
          ],
        },
        {
          judul: "6. Menyunting Teks Berita",
          isi: [
            "Menyunting berita penting untuk memastikan keakuratan dan kualitas berita sebelum dipublikasikan.",
            "",
            "Langkah menyunting berita:",
            "",
            "1. Periksa Fakta",
            "• Apakah semua data sudah benar? (nama, tempat, waktu, angka)",
            "• Apakah sumber informasi jelas dan terpercaya?",
            "• Apakah ada klaim yang perlu diverifikasi?",
            "",
            "2. Periksa Unsur 5W+1H",
            "• Apakah semua unsur sudah tercakup?",
            "• Jika ada yang kurang, tambahkan informasinya",
            "",
            "3. Periksa Struktur",
            "• Apakah lead sudah mengandung unsur terpenting?",
            "• Apakah informasi diurutkan dari yang terpenting ke kurang penting?",
            "",
            "4. Periksa Bahasa",
            "• Gunakan bahasa baku, hindari kata tidak baku",
            "• Perhatikan ejaan dan tanda baca sesuai EYD",
            "• Pastikan kalimat langsung ditulis dengan benar",
            "",
            "PENTING: Jangan mengubah fakta saat menyunting. Sunting hanya dari segi bahasa dan struktur, bukan isi.",
          ],
          contoh: [
            "Contoh penyuntingan:",
            "",
            "Sebelum: \"Kemaren ada kebakaran di pasar. Katanya sih dari korsleting listrik. Untung ga ada korban jiwa.\"",
            "",
            "Sesudah: \"Kebakaran melanda Pasar Induk Caringin, Bandung, pada Selasa (18/3/2026) dini hari. Diduga api berasal dari korsleting listrik di salah satu kios. Tidak ada korban jiwa dalam peristiwa ini.\"",
            "",
            "Perubahan: bahasa baku, unsur 5W+1H lengkap, struktur piramida terbalik.",
          ],
        },
        {
          judul: "7. Prosedur Menulis Teks Berita",
          isi: [
            "Berikut langkah-langkah menulis teks berita yang baik dan benar.",
            "",
            "Langkah 1: Cari Peristiwa",
            "• Cari peristiwa faktual dan aktual yang layak diberitakan",
            "• Pastikan peristiwa memiliki nilai berita (penting, menarik, dekat dengan pembaca)",
            "",
            "Langkah 2: Kumpulkan Data",
            "• Wawancarai narasumber yang terkait",
            "• Catat fakta: nama, waktu, tempat, kronologi",
            "• Kumpulkan bukti: foto, video, dokumen",
            "",
            "Langkah 3: Verifikasi Data",
            "• Periksa kebenaran data dari minimal 2 sumber berbeda",
            "• Pastikan tidak ada kesalahan fakta",
            "",
            "Langkah 4: Tulis Lead",
            "• Tulis paragraf pertama yang mengandung 5W+1H terpenting",
            "• Lead harus menarik dan membuat pembaca ingin terus membaca",
            "",
            "Langkah 5: Kembangkan Tubuh Berita",
            "• Tambahkan detail, kutipan narasumber, dan latar belakang",
            "• Urutkan dari informasi penting ke kurang penting",
            "",
            "Langkah 6: Beri Judul",
            "• Judul yang singkat, padat, dan menarik",
            "• Mencerminkan isi berita secara akurat",
            "",
            "Langkah 7: Sunting dan Publikasikan",
            "• Periksa kembali fakta, struktur, ejaan",
            "• Minta teman atau editor membaca sebelum publikasi",
          ],
          rangkuman: [
            "Rumus menulis berita: PERISTIWA → DATA → VERIFIKASI → LEAD → KEMBANGKAN → JUDUL → SUNING",
            "",
            "Ingat 3 pilar berita: FAKTUAL + AKTUAL + OBJEKTIF",
          ],
        },
      ],
    },
    latihan: [
      {
        id: 1,
        soal: "Berita harus bersifat faktual, artinya berdasarkan ... dan kenyataan.",
        tipe: "ISIAN",
        opsi: "fakta",
        jawaban: "fakta",
        penjelasan: "Faktual berarti berdasarkan fakta dan kenyataan yang dapat diverifikasi kebenarannya.",
      },
      {
        id: 2,
        soal: "Unsur 'What' dalam 5W+1H menanyakan...",
        opsi: ["Siapa yang terlibat", "Apa yang terjadi", "Kapan kejadiannya", "Di mana kejadiannya"],
        jawaban: "1",
        penjelasan: "What menanyakan 'Apa yang terjadi?' — yaitu inti peristiwa dalam berita.",
      },
      {
        id: 3,
        soal: "Bagian berita yang berisi inti informasi paling penting dan menjawab 5W+1H utama adalah...",
        opsi: ["Judul", "Lead/Kepala berita", "Tubuh berita", "Ekor berita"],
        jawaban: 1,
        penjelasan: "Lead atau kepala berita adalah paragraf pertama yang berisi inti informasi paling penting.",
      },
      {
        id: 4,
        soal: "Ciri bahasa teks berita adalah...",
        opsi: ["Menggunakan bahasa tidak baku", "Menggunakan bahasa baku", "Penuh majas", "Menggunakan bahasa daerah"],
        jawaban: 1,
        penjelasan: "Teks berita menggunakan bahasa baku sesuai KBBI dan EYD agar informasi tersampaikan secara jelas dan profesional.",
      },
      {
        id: 5,
        soal: "Kalimat langsung dalam berita ditandai dengan...",
        opsi: ["Tanda kurung", "Tanda petik", "Tanda seru", "Tanda tanya"],
        jawaban: 1,
        penjelasan: "Kalimat langsung menggunakan tanda petik (\"...\") untuk mengutip pernyataan narasumber.",
      },
      {
        id: 6,
        soal: "Piramida terbalik adalah struktur penulisan berita yang menempatkan informasi terpenting di awal.",
        tipe: "BENAR_SALAH",
        opsi: ["Benar", "Salah"],
        jawaban: 0,
        penjelasan: "Piramida terbalik: informasi paling penting di awal (lead), lalu informasi pendukung di bagian tubuh dan ekor.",
      },
      {
        id: 7,
        soal: "Berita yang fokus pada sisi kemanusiaan dan gaya penulisan lebih bebas disebut...",
        opsi: ["Straight news", "Feature", "Investigasi", "Opini"],
        jawaban: 1,
        penjelasan: "Feature adalah berita ringan yang menonjolkan sisi human interest dengan gaya penulisan yang lebih menarik.",
      },
      {
        id: 8,
        soal: "Kata 'menduga', 'memperkirakan', dan 'berharap' termasuk kata kerja mental dalam teks berita.",
        tipe: "BENAR_SALAH",
        opsi: ["Benar", "Salah"],
        jawaban: 0,
        penjelasan: "Kata kerja mental berkaitan dengan aktivitas pikiran atau perasaan, sering digunakan dalam kutipan narasumber.",
      },
      {
        id: 9,
        soal: "Langkah pertama dalam menulis berita adalah...",
        opsi: ["Menulis judul", "Mencari peristiwa dan mengumpulkan data", "Menyunting", "Mempublikasikan"],
        jawaban: 1,
        penjelasan: "Langkah pertama adalah mencari peristiwa faktual dan mengumpulkan data melalui wawancara dan observasi.",
      },
      {
        id: 10,
        soal: "Berita hoaks adalah berita yang...",
        opsi: ["Berdasarkan fakta", "Tidak faktual atau palsu", "Aktual dan terpercaya", "Bersumber dari narasumber resmi"],
        jawaban: 1,
        penjelasan: "Hoaks adalah berita palsu yang tidak berdasarkan fakta. Cirinya: sumber tidak jelas, tidak ada data pendukung.",
      },
    ],
    praktik: {
      tujuan: "Menulis teks berita dengan unsur 5W+1H lengkap, struktur piramida terbalik, dan kaidah kebahasaan yang tepat.",
      instruksi: "Amati sebuah peristiwa di lingkungan sekolah atau rumah. Tulis teks berita dengan struktur yang benar.",
      langkah: [
        "Amati peristiwa faktual di sekitarmu (upacara, lomba, kegiatan kelas, dll.)",
        "Catat unsur 5W+1H: apa, siapa, kapan, di mana, mengapa, bagaimana",
        "Wawancarai 1-2 narasumber untuk mendapatkan kutipan langsung",
        "Tulis lead (paragraf pertama) yang mengandung unsur terpenting",
        "Kembangkan tubuh berita dengan detail, kutipan, dan data pendukung",
        "Tulis judul yang singkat, padat, dan menarik",
        "Periksa kembali unsur 5W+1H — pastikan semua tercakup",
        "Sunting bahasa: gunakan bahasa baku, periksa ejaan dan tanda baca",
      ],
      tips: [
        "Pilih peristiwa yang benar-benar kamu saksikan langsung.",
        "Catat nama narasumber dengan ejaan yang benar.",
        "Gunakan rumus 5W+1H sebagai daftar periksa sebelum mengumpulkan.",
        "Baca berita dari portal berita online sebagai referensi gaya penulisan.",
        "Minta teman membaca beritamu — jika mereka paham, berarti berita sudah jelas.",
      ],
      contoh: "Lihat contoh struktur berita 'Lomba Puisi Tingkat Kota' pada materi Struktur Teks Berita di atas.",
    },
    kuis: [
      {
        id: 1,
        soal: "Teks berita yang baik harus memenuhi dua syarat utama, yaitu faktual dan ...",
        tipe: "ISIAN",
        opsi: "aktual",
        jawaban: "aktual",
        penjelasan: "Berita harus faktual (berdasarkan fakta) dan aktual (baru terjadi).",
      },
      {
        id: 2,
        soal: "Pertanyaan 'Why' dalam 5W+1H menanyakan penyebab atau latar belakang terjadinya peristiwa.",
        tipe: "BENAR_SALAH",
        opsi: ["Benar", "Salah"],
        jawaban: "0",
        penjelasan: "Why menanyakan penyebab atau latar belakang terjadinya peristiwa.",
      },
      {
        id: 3,
        soal: "Bagian berita yang berisi kutipan dari narasumber biasanya terdapat di...",
        opsi: ["Judul", "Lead", "Tubuh berita", "Ekor berita"],
        jawaban: 2,
        penjelasan: "Tubuh berita berisi pengembangan informasi, termasuk kutipan dari narasumber.",
      },
      {
        id: 4,
        soal: "Media yang menyampaikan berita melalui gambar sebagai utama disebut...",
        opsi: ["Straight news", "Feature", "Photo news", "Investigasi"],
        jawaban: 2,
        penjelasan: "Photo news adalah berita foto yang mengandalkan gambar sebagai media utama penyampaian informasi.",
      },
      {
        id: 5,
        soal: "Kalimat 'Kami akan menyelidiki kasus ini,' ujar Kapolsek adalah contoh...",
        opsi: ["Kalimat tidak langsung", "Kalimat langsung", "Kalimat pasif", "Kalimat tanya"],
        jawaban: 1,
        penjelasan: "Kalimat langsung ditandai dengan tanda petik dan mengutip langsung perkataan narasumber.",
      },
      {
        id: 6,
        soal: "Berita yang ditulis berdasarkan hasil penyelidikan mendalam disebut...",
        opsi: ["Straight news", "Feature", "Investigasi", "Opini"],
        jawaban: 2,
        penjelasan: "Berita investigasi adalah hasil penyelidikan mendalam oleh wartawan yang membutuhkan waktu dan data yang banyak.",
      },
      {
        id: 7,
        soal: "Kata 'sebab', 'akibatnya', dan 'karena' termasuk konjungsi kausal.",
        tipe: "BENAR_SALAH",
        opsi: ["Benar", "Salah"],
        jawaban: 0,
        penjelasan: "Konjungsi kausal menunjukkan hubungan sebab-akibat: karena, sebab, akibatnya, sehingga.",
      },
      {
        id: 8,
        soal: "Langkah terpenting sebelum menulis berita adalah...",
        opsi: ["Menulis judul", "Mengumpulkan dan memverifikasi data", "Menyunting", "Mencari foto"],
        jawaban: 1,
        penjelasan: "Data yang akurat adalah fondasi berita. Verifikasi data dari minimal 2 sumber sebelum menulis.",
      },
      {
        id: 9,
        soal: "Ekor berita berisi informasi yang bersifat...",
        opsi: ["Paling penting", "Kurang penting (tambahan)", "Paling menarik", "Kontroversial"],
        jawaban: 1,
        penjelasan: "Ekor berita berisi informasi tambahan yang kurang penting dan boleh dihilangkan jika perlu.",
      },
      {
        id: 10,
        soal: "Sikap yang perlu dimiliki seorang penulis berita adalah...",
        opsi: ["Memihak salah satu pihak", "Objektif dan tidak memihak", "Sensasional", "Emosional"],
        jawaban: 1,
        penjelasan: "Penulis berita harus objektif, tidak memihak, dan menyajikan fakta apa adanya.",
      },
    ],
  };

export default konten;
