// @ts-nocheck
import type { Konten, Soal } from "../types";

/* =============================================
   Unit 1: Teks Deskripsi (VII S1)
   ============================================= */
const konten: Konten = {
    belajar: {
      tujuan: [
        "Memahami hakikat, ciri, dan fungsi teks deskripsi dalam kehidupan sehari-hari",
        "Mengidentifikasi pokok-pokok isi dan jenis-jenis teks deskripsi",
        "Menganalisis pola struktur dan kaidah kebahasaan teks deskripsi",
        "Mendalami penggunaan majas dan kalimat rincian dalam teks deskripsi",
        "Memproduksi teks deskripsi dengan langkah yang sistematis",
      ],
      materi: [
        {
          judul: "1. Hakikat Teks Deskripsi",
          isi: [
            "Teks deskripsi adalah teks yang menggambarkan suatu objek, tempat, atau peristiwa dengan kata-kata yang jelas dan terperinci sehingga pembaca seolah-olah melihat, mendengar, atau merasakan sendiri objek tersebut.",
            "",
            "Ciri-ciri teks deskripsi:",
            "• Menggambarkan objek secara konkret dan terperinci",
            "• Menggunakan kata-kata yang melibatkan pancaindra (visual, auditori, taktil)",
            "• Membaca teks deskripsi seolah mengalami langsung apa yang digambarkan",
            "• Bersifat subjektif karena melibatkan kesan penulis",
            "",
            "Contoh kalimat deskripsi yang baik:",
            "✓ Tembok tua itu berlumut hijau, retak-retak dimakan usia, dan di sudutnya tumbuh tanaman liar yang merambat.",
            "",
            "Bandingkan dengan kalimat biasa:",
            "✗ Tembok itu tua.",
            "",
            "Fungsi teks deskripsi dalam kehidupan sehari-hari:",
            "• Melaporkan hasil pengamatan secara terperinci",
            "• Menuliskan kesan terhadap suatu tempat wisata atau peristiwa",
            "• Memasarkan produk dengan deskripsi yang menarik",
            "• Menuangkan pengalaman pribadi dalam bentuk tulisan",
          ],
          contoh: [
            "Contoh teks deskripsi singkat:",
            "Pantai Pasir Putih di pagi hari sungguh memukau. Pasir putihnya terasa lembut di telapak kaki. Ombak kecil berkejaran menuju tepian, meninggalkan buih-buih putih yang segera lenyap. Di kejauhan, matahari baru saja menampakkan diri, menyapa dunia dengan sinar jingganya yang hangat.",
          ],
          catatan: "Teks deskripsi berbeda dengan teks laporan. Teks deskripsi bersifat subjektif dan melibatkan kesan penulis, sedangkan teks laporan bersifat objektif dan berdasarkan fakta.",
        },
        {
          judul: "2. Komposisi Umum Isi Teks Deskripsi",
          isi: [
            "Pokok-pokok isi yang membangun teks deskripsi meliputi tiga hal utama:",
            "",
            "1. Objek yang dideskripsikan — apa yang menjadi fokus penggambaran",
            "2. Ciri-ciri atau karakteristik objek — bagaimana wujud, sifat, atau keadaan objek tersebut",
            "3. Kesan penulis — bagaimana perasaan atau tanggapan penulis terhadap objek",
            "",
            "Saat menulis teks deskripsi, pastikan ketiga unsur ini ada agar pembaca mendapat gambaran utuh:",
            "• Objek jelas dan spesifik (bukan \"pemandangan\" tetapi \"pantai Pasir Putih pukul 06.00\")",
            "• Ciri-ciri terperinci dan melibatkan pancaindra (apa yang dilihat, didengar, dicium, dirasakan)",
            "• Kesan penulis membuat tulisan hidup dan tidak kaku",
          ],
          contoh: [],
        },
        {
          judul: "3. Jenis atau Varian Teks Deskripsi",
          isi: [
            "Berdasarkan pendekatannya, teks deskripsi dibedakan menjadi tiga jenis:",
            "",
            "1. Teks Deskripsi Objektif — menggambarkan objek apa adanya tanpa pendapat pribadi",
            "✓ Meja itu terbuat dari kayu jati, berukuran 120 cm x 60 cm, dengan permukaan yang dihaluskan dan dilapisi pernis bening.",
            "",
            "2. Teks Deskripsi Subjektif — menggambarkan objek dengan melibatkan perasaan penulis",
            "✓ Meja tua itu menyimpan seribu kenangan. Goresan-goresan di permukaannya bagaikan peta perjalanan waktu yang tak ternilai.",
            "",
            "3. Teks Deskripsi Spasial — menggambarkan ruang, tempat, atau lokasi secara terperinci",
            "✓ Di sebelah timur lapangan, berdiri tegak sebuah pohon beringin raksasa. Akar-akar gantungnya menjuntai bagai tirai alami. Di bawahnya, beberapa bangku taman tersusun rapi mengelilingi batang pohon.",
            "",
            "Setiap jenis memiliki fungsi yang berbeda. Pilih jenis yang sesuai dengan tujuan penulisanmu.",
          ],
          contoh: [],
        },
        {
          judul: "4. Pola Struktur Teks Deskripsi",
          isi: [
            "Struktur teks deskripsi terdiri dari tiga bagian utama:",
            "",
            "1. IDENTIFIKASI (Pernyataan Umum) — berisi pengenalan objek yang akan dideskripsikan",
            "2. DESKRIPSI BAGIAN — berisi penggambaran ciri-ciri objek secara terperinci",
            "3. SIMPULAN — berisi kesan atau simpulan penulis tentang objek (bersifat opsional)",
            "",
            "PENTING: Deskripsi bagian adalah inti dari teks deskripsi. Semakin terperinci deskripsi bagian, semakin hidup tulisanmu.",
            "",
            "Tips menulis struktur yang baik:",
            "• Mulailah dengan kalimat pembuka yang menarik perhatian",
            "• Urutkan deskripsi bagian dari yang umum ke yang khusus",
            "• Gunakan kata penghubung seperti: di samping itu, selain itu, sementara itu, tidak hanya itu",
            "• Akhiri dengan simpulan yang meninggalkan kesan",
          ],
          contoh: [
            "Contoh struktur teks deskripsi tentang \"Kucing Kesayanganku\":",
            "",
            "[IDENTIFIKASI]",
            "Kucingku bernama Milo, seekor kucing persia berbulu oranye tebal yang sudah tiga tahun menemani hari-hariku.",
            "",
            "[DESKRIPSI BAGIAN]",
            "Bulu Milo sangat lembut dan tebal, terutama di bagian leher dan dadanya. Matanya bulat dan besar, berwarna hijau terang seperti batu giok. Setiap pagi, Milo selalu duduk di ambang pintu kamarku sambil mengeong kecil, menungguku bangun. Cara berjalannya anggun, langkahnya pelan dan hati-hati seperti sedang menari di atas lantai.",
            "",
            "[SIMPULAN]",
            "Milo bukan sekadar kucing peliharaan, ia adalah sahabat setia yang membuat setiap hari terasa lebih hangat.",
          ],
        },
        {
          judul: "5. Kaidah dan Fitur Kebahasaan Teks Deskripsi",
          isi: [
            "Teks deskripsi memiliki ciri kebahasaan yang khas:",
            "",
            "1. Menggunakan kata sifat (adjektiva) untuk menggambarkan sifat objek",
            "   Contoh: indah, megah, lembut, harum, hangat, tua, sunyi",
            "",
            "2. Menggunakan kata kerja (verba) untuk menggambarkan aktivitas objek",
            "   Contoh: menjulang, berkilau, mengalir, berayun, merebak",
            "",
            "3. Menggunakan majas (gaya bahasa) untuk memperindah tulisan",
            "   • Personifikasi: \"Angin berbisik di telingaku\"",
            "   • Metafora: \"Mataharimu adalah bintang dalam hidupku\"",
            "   • Perumpamaan: \"Wajahnya bersinar bagaikan bulan purnama\"",
            "",
            "4. Menggunakan kata depan yang menunjukkan lokasi",
            "   Contoh: di, ke, dari, pada, dalam, antara",
            "",
            "5. Menggunakan kalimat rincian untuk memberikan gambaran detail",
            "   Contoh: \"Dindingnya dicat biru muda, lantainya marmer putih, dan di sudut ruangan terdapat vas bunga setinggi satu meter.\"",
          ],
          contoh: [
            "Identifikasi unsur kebahasaan dalam kalimat berikut:",
            "",
            "\"Pohon beringin itu berdiri megah di tengah alun-alun. Daun-daunnya lebat dan hijau, memberikan keteduhan bagi siapa pun yang berteduh di bawahnya. Akar-akar gantungnya menjuntai panjang, bergoyang lembut ditiup angin.\"",
            "",
            "Kata sifat: megah, lebat, hijau, panjang, lembut",
            "Kata kerja: berdiri, berteduh, menjuntai, bergoyang",
            "Majas: \"Akar menjuntai bergoyang lembut\" (personifikasi — akar digambarkan seperti makhluk hidup yang bisa bergoyang)",
          ],
        },
        {
          judul: "6. Pendalaman Kebahasaan — Kalimat Rincian dan Majas",
          isi: [
            "Pendalaman lebih lanjut tentang dua fitur bahasa utama dalam teks deskripsi:",
            "",
            "A. KALIMAT RINCIAN",
            "",
            "Kalimat rincian adalah kalimat yang memberikan detail spesifik tentang suatu objek. Ciri-cirinya:",
            "• Menggunakan kata hubung dan, serta, maupun",
            "• Menyebutkan bagian-bagian secara berurutan",
            "• Memberikan ukuran, warna, bentuk, atau sifat yang konkret",
            "",
            "Contoh kalimat rincian:",
            "✓ Ruangan itu memiliki tiga jendela besar di sisi timur, dua rak buku dari kayu jati di sisi barat, dan sebuah meja marmer putih di tengahnya.",
            "✗ Ruangan itu memiliki jendela dan rak buku.",
            "",
            "B. MAJAS DALAM TEKS DESKRIPSI",
            "",
            "Majas adalah gaya bahasa yang digunakan untuk membuat tulisan lebih hidup dan ekspresif.",
            "",
            "Jenis majas yang sering digunakan dalam teks deskripsi:",
            "",
            "1. Personifikasi — memberikan sifat manusia pada benda mati",
            "   Contoh: \"Matahari tersenyum ramah dari balik bukit.\"",
            "",
            "2. Metafora — perbandingan tanpa kata pembanding",
            "   Contoh: \"Dia adalah mutiara dalam keluarga.\"",
            "",
            "3. Perumpamaan (asosiasi) — perbandingan dengan kata bagaikan, laksana, seperti",
            "   Contoh: \"Suaranya merdu bagaikan alun-alun gamelan.\"",
            "",
            "4. Hiperbola — pernyataan yang dilebih-lebihkan",
            "   Contoh: \"Aku menunggunya seabad lamanya.\"",
          ],
          contoh: [
            "Latihan mengidentifikasi majas:",
            "",
            "Bacalah kalimat berikut dan tentukan jenis majas yang digunakan:",
            "1. \"Ombak berkejaran menuju pantai.\" — Personifikasi",
            "2. \"Kulitnya putih bagaikan mutiara.\" — Perumpamaan",
            "3. \"Dia adalah lilin dalam kegelapan.\" — Metafora",
            "4. \"Tangisnya memecahkan kesunyian malam.\" — Hiperbola",
          ],
          catatan: "Kuasai kalimat rincian dan majas, karena dua fitur inilah yang membedakan teks deskripsi yang baik dari yang biasa-biasa saja.",
        },
        {
          judul: "7. Prosedur Memproduksi Teks Deskripsi",
          isi: [
            "Ikuti langkah-langkah berikut untuk menulis teks deskripsi yang baik:",
            "",
            "TAHAP PRA-PRODUKSI:",
            "1. Pilih objek yang akan dideskripsikan (bisa tempat, benda, orang, atau peristiwa)",
            "2. Amati objek dengan saksama — gunakan semua pancaindra",
            "3. Catat kata kunci dan kesan yang muncul saat mengamati",
            "4. Tentukan sudut pandang yang akan digunakan",
            "",
            "TAHAP PRODUKSI:",
            "5. Tulis kerangka dengan struktur: Identifikasi → Deskripsi Bagian → Simpulan",
            "6. Kembangkan kerangka menjadi paragraf dengan kalimat rincian",
            "7. Gunakan kata sifat dan majas yang tepat untuk menghidupkan tulisan",
            "",
            "TAHAP PASCA-PRODUKSI:",
            "8. Baca kembali dan periksa ejaan serta tanda baca (EYD)",
            "9. Perbaiki kalimat yang kurang jelas atau kurang terperinci",
            "10. Minta teman atau guru memberi masukan",
            "",
            "Tips untuk menghasilkan karya terbaik:",
            "• Pilih objek yang benar-benar kamu kenal atau sukai",
            "• Jangan terburu-buru — deskripsi yang baik butuh pengamatan yang teliti",
            "• Gunakan perbandingan yang unik dan tidak biasa",
            "• Baca ulang dan bayangkan apakah pembaca bisa 'melihat' objekmu",
          ],
          contoh: [
            "Contoh teks deskripsi karya siswa (tema: Ruang Kelasku):",
            "",
            "IDENTIFIKASI",
            "Ruang kelas 7A adalah ruangan yang sederhana namun penuh kehangatan. Terletak di lantai dua, menghadap ke timur, kelas ini menjadi saksi bisu perjalanan belajar kami setiap hari.",
            "",
            "DESKRIPSI BAGIAN",
            "Dindingnya dicat putih bersih, dihiasi dengan poster-poster pendidikan dan hasil karya siswa yang ditempel rapi. Dua puluh meja dan kursi kayu tersusun rapi dalam lima baris. Di sudut kanan depan, sebuah peta Indonesia besar terpajang, menemani papan tulis putih yang setiap hari dipenuhi coretan rumus dan catatan penting. Jendela-jendela besar di sisi timur membiarkan sinar matahari pagi masuk, membuat ruangan terasa terang dan segar. Aroma kapur tulis dan buku-buku baru bercampur menjadi satu, menciptakan aroma khas yang langsung terasa ketika memasuki ruangan.",
            "",
            "SIMPULAN",
            "Ruang kelas 7A mungkin tidak mewah, tetapi ia memiliki kehangatan yang membuat kami betah berlama-lama belajar.",
          ],
        },
      ],
      rangkuman: [
        "Teks deskripsi adalah teks yang menggambarkan objek dengan kata-kata terperinci sehingga pembaca seolah mengalami langsung.",
        "Teks deskripsi memiliki tiga jenis: objektif, subjektif, dan spasial.",
        "Struktur teks deskripsi terdiri dari identifikasi, deskripsi bagian, dan simpulan.",
        "Ciri kebahasaan meliputi kata sifat, kata kerja, majas, dan kalimat rincian.",
        "Langkah menulis: pilih objek → amati → buat kerangka → kembangkan → revisi.",
        "Gunakan pancaindra dan majas untuk membuat deskripsi lebih hidup.",
      ],
    },
    latihan: [
      { id: 1, tipe: "PG", soal: "Berikut ini yang bukan merupakan ciri-ciri teks deskripsi adalah...", opsi: ["Menggambarkan objek secara terperinci", "Melibatkan pancaindra pembaca", "Bersifat objektif tanpa kesan penulis", "Menggunakan majas dan kalimat rincian"], jawaban: 2, penjelasan: "Teks deskripsi bersifat subjektif karena melibatkan kesan penulis. Sifat objektif tanpa kesan penulis adalah ciri teks laporan." },
      { id: 2, tipe: "BENAR_SALAH", soal: "Teks deskripsi hanya menggunakan satu jenis majas, yaitu personifikasi.", opsi: ["Benar", "Salah"], jawaban: 1, penjelasan: "Teks deskripsi dapat menggunakan berbagai jenis majas: personifikasi, metafora, perumpamaan, dan hiperbola." },
      { id: 3, tipe: "PG", soal: "Bagian struktur teks deskripsi yang berisi penggambaran ciri-ciri objek secara terperinci disebut...", opsi: ["Identifikasi", "Deskripsi bagian", "Simpulan", "Orientasi"], jawaban: 1, penjelasan: "Deskripsi bagian adalah inti dari teks deskripsi." },
      { id: 4, tipe: "PG", soal: "Kalimat 'Angin berbisik di telingaku' menggunakan majas...", opsi: ["Metafora", "Personifikasi", "Hiperbola", "Perumpamaan"], jawaban: 1, penjelasan: "Personifikasi memberikan sifat manusia pada benda mati." },
      { id: 5, tipe: "BENAR_SALAH", soal: "Deskripsi bagian dalam teks deskripsi bersifat opsional — boleh ada boleh tidak.", opsi: ["Benar", "Salah"], jawaban: 1, penjelasan: "Deskripsi bagian adalah inti teks deskripsi dan WAJIB ada. Bagian opsional adalah simpulan." },
      { id: 6, tipe: "ISIAN", soal: "Sebutkan salah satu jenis teks deskripsi berdasarkan pendekatannya!", opsi: ["objektif"], jawaban: "objektif", penjelasan: "Jenis: objektif, subjektif, dan spasial." },
      { id: 7, tipe: "PG", soal: "Fungsi majas dalam teks deskripsi adalah...", opsi: ["Membuat tulisan lebih panjang", "Memperindah dan menghidupkan tulisan", "Mengganti kata-kata sulit", "Membingungkan pembaca"], jawaban: 1, penjelasan: "Majas membuat tulisan lebih ekspresif dan menarik." },
      { id: 8, tipe: "PG", soal: "Contoh kalimat rincian yang tepat adalah...", opsi: ["Rumah itu besar.", "Rumah itu memiliki tiga jendela besar, dua pintu kayu jati, dan halaman yang ditumbuhi bunga mawar merah.", "Rumah itu bagus.", "Rumah itu tidak jelek."], jawaban: 1, penjelasan: "Kalimat rincian memberikan detail spesifik secara konkret." },
      { id: 9, tipe: "BENAR_SALAH", soal: "'Ia adalah lilin dalam kegelapan' adalah contoh majas perumpamaan.", opsi: ["Benar", "Salah"], jawaban: 1, penjelasan: "Kalimat tersebut adalah majas metafora (tanpa kata pembanding seperti/bagaikan)." },
      { id: 10, tipe: "PG", soal: "Langkah pertama dalam menulis teks deskripsi adalah...", opsi: ["Langsung menulis paragraf penuh", "Memilih objek yang akan dideskripsikan", "Mencari referensi di internet", "Meminta teman membaca"], jawaban: 1, penjelasan: "Pilih objek, lalu amati dengan pancaindra." },
    ],
    praktik: {
      petunjuk: "Pilihlah satu objek di sekitarmu (ruang kelas, halaman sekolah, pasar, atau anggota keluarga). Tulislah teks deskripsi sepanjang 3-5 paragraf dengan struktur: identifikasi, deskripsi bagian (minimal 2 paragraf), dan simpulan. Gunakan minimal 5 kata sifat, 3 majas berbeda, dan kalimat rincian di setiap paragraf.",
      tips: [
        "Amati objek selama 5 menit sebelum menulis — catat semua yang kamu lihat, dengar, cium, dan rasakan.",
        "Buat kerangka dulu sebelum menulis paragraf penuh.",
        "Gunakan majas personifikasi, metafora, atau perumpamaan untuk menghidupkan tulisan.",
        "Baca ulang tulisanku dan pastikan pembaca bisa 'membayangkan' objek yang dideskripsikan.",
        "Minta teman membaca tulisanku dan tanya apakah mereka bisa membayangkan objek tersebut.",
      ],
      contoh: "Lihat contoh teks deskripsi tentang ruang kelas pada materi Prosedur Memproduksi Teks di atas.",
    },
    kuis: [
      { id: 1, tipe: "PG", soal: "Teks deskripsi adalah teks yang...", opsi: ["Menjelaskan prosedur melakukan sesuatu", "Menggambarkan objek dengan kata-kata terperinci", "Menceritakan kisah fiktif", "Meyakinkan pembaca"], jawaban: 1, penjelasan: "Teks deskripsi menggambarkan objek sehingga pembaca seolah mengalami langsung." },
      { id: 2, tipe: "BENAR_SALAH", soal: "Teks deskripsi subjektif menggambarkan objek tanpa melibatkan perasaan penulis.", opsi: ["Benar", "Salah"], jawaban: 1, penjelasan: "Teks subjektif justru melibatkan perasaan dan kesan pribadi penulis." },
      { id: 3, tipe: "PG", soal: "Urutan struktur teks deskripsi yang tepat adalah...", opsi: ["Identifikasi → Simpulan → Deskripsi bagian", "Deskripsi bagian → Identifikasi → Simpulan", "Identifikasi → Deskripsi bagian → Simpulan", "Simpulan → Identifikasi → Deskripsi bagian"], jawaban: 2, penjelasan: "Urutan: identifikasi → deskripsi bagian → simpulan." },
      { id: 4, tipe: "PG", soal: "'Ombak berkejaran menuju pantai' menggunakan majas...", opsi: ["Metafora", "Hiperbola", "Perumpamaan", "Personifikasi"], jawaban: 3, penjelasan: "Ombak digambarkan berkejaran seperti manusia (personifikasi)." },
      { id: 5, tipe: "BENAR_SALAH", soal: "Kalimat rincian harus menggunakan kata hubung seperti 'dan', 'serta', 'maupun'.", opsi: ["Benar", "Salah"], jawaban: 0, penjelasan: "Kalimat rincian menggunakan kata hubung untuk menggabungkan detail." },
      { id: 6, tipe: "ISIAN", soal: "Sebutkan dua dari tiga jenis teks deskripsi!", opsi: ["objektif subjektif"], jawaban: "objektif subjektif", penjelasan: "Jenis: objektif, subjektif, dan spasial." },
      { id: 7, tipe: "PG", soal: "Teks deskripsi spasial menggambarkan...", opsi: ["Perasaan penulis", "Ruang, tempat, atau lokasi", "Urutan waktu kejadian", "Pendapat tentang suatu isu"], jawaban: 1, penjelasan: "Deskripsi spasial fokus pada penggambaran ruang/tempat." },
      { id: 8, tipe: "PG", soal: "Yang termasuk kata sifat dalam teks deskripsi adalah...", opsi: ["berlari, melompat", "indah, megah, lembut", "dan, atau, tetapi", "ke, di, dari"], jawaban: 1, penjelasan: "Kata sifat menggambarkan sifat objek: indah, megah, lembut." },
      { id: 9, tipe: "BENAR_SALAH", soal: "Simpulan dalam teks deskripsi adalah bagian yang wajib ada.", opsi: ["Benar", "Salah"], jawaban: 1, penjelasan: "Simpulan opsional. Yang wajib: identifikasi dan deskripsi bagian." },
      { id: 10, tipe: "PG", soal: "Tujuan penggunaan pancaindra dalam menulis teks deskripsi adalah...", opsi: ["Membuat tulisan lebih panjang", "Agar pembaca seolah mengalami langsung", "Memenuhi syarat paragraf", "Menunjukkan kosakata"], jawaban: 1, penjelasan: "Pancaindra membuat deskripsi lebih konkret dan hidup." },
    ],
  };

export default konten;
