// @ts-nocheck
import type { Konten } from "../types";

const kd = "3.4/4.4";

/* =============================================
   Unit 4: Teks Puisi Rakyat — VII S1
   KD 3.4/4.4 — Mengidentifikasi & Menulis Puisi Rakyat (Pantun, Syair, Gurindam)
   ============================================= */
const konten: Konten = {
    belajar: {
      tujuan: [
        "Memahami hakikat, ciri, dan jenis-jenis puisi rakyat dalam khazanah sastra Indonesia",
        "Mengidentifikasi karakteristik pantun, syair, dan gurindam secara tepat",
        "Menganalisis unsur-unsur pembangun puisi rakyat (larik, bait, rima, sampiran, isi)",
        "Membandingkan perbedaan antarajenis puisi rakyat dari segi struktur dan fungsi",
        "Memproduksi puisi rakyat sesuai dengan konvensi masing-masing jenis",
      ],
      materi: [
        {
          judul: "1. Hakikat Puisi Rakyat",
          isi: [
            "Puisi rakyat adalah karya sastra lisan yang berkembang di masyarakat tradisional Indonesia. Puisi ini diwariskan secara turun-temurun tanpa diketahui pengarangnya, dan menjadi bagian dari budaya serta keseharian masyarakat.",
            "",
            "Ciri-ciri umum puisi rakyat:",
            "• Bersifat anonim — tidak diketahui pengarangnya",
            "• Disampaikan secara lisan (tradisi lisan)",
            "• Terikat oleh aturan: jumlah baris, jumlah suku kata, rima",
            "• Mengandung nilai-nilai luhur: moral, agama, budi pekerti",
            "• Menggunakan bahasa yang sederhana dan mudah dipahami",
            "• Berfungsi sebagai alat komunikasi, pendidikan, dan hiburan",
            "",
            "Fungsi puisi rakyat dalam kehidupan:",
            "• Mendidik — menyampaikan nasihat dan ajaran moral",
            "• Menghibur — sebagai permainan kata atau hiburan dalam acara",
            "• Mengkritik — menyindir secara halus melalui kiasan",
            "• Melestarikan budaya — menjaga tradisi sastra lisan Nusantara",
            "",
            "Jenis puisi rakyat yang dipelajari di kelas VII:",
            "1. Pantun — 4 baris, bersajak a-b-a-b",
            "2. Syair — 4 baris, bersajak a-a-a-a",
            "3. Gurindam — 2 baris, bersajak a-a",
            "",
            "PENTING: Puisi rakyat BUKAN puisi bebas. Ibarat bermain di lapangan yang sudah ada garis-garisnya — kamu harus mengikuti aturan yang sudah ditetapkan. Semakin patuh pada aturan, semakin indah puisinya.",
          ],
          contoh: [
            "Ketiga jenis puisi rakyat dengan tema 'nasihat belajar':",
            "",
            "Pantun:",
            "Jalan-jalan ke kota Blitar (sampiran)",
            "Jangan lupa membeli duku (sampiran)",
            "Jika ingin pintar dan mahir (isi)",
            "Rajin-rajinlah membaca buku (isi)",
            "",
            "Syair:",
            "Wahai anak janganlah malas (a)",
            "Belajarlah dengan tekun dan keras (a)",
            "Ilmu itu bagaikan kuncup emas (a)",
            "Bekal hidup di masa nanti lepas (a)",
            "",
            "Gurindam:",
            "Jika hendak menjadi orang pandai (syarat)",
            "Rajin belajar janganlah mulai (akibat)",
          ],
        },
        {
          judul: "2. Pantun — Ciri, Struktur, dan Jenis",
          isi: [
            "Pantun adalah jenis puisi rakyat yang paling dikenal di Nusantara. Pantun digunakan dalam berbagai acara adat, permainan, dan komunikasi sehari-hari.",
            "",
            "Ciri-ciri pantun:",
            "• Setiap bait terdiri dari 4 baris",
            "• Setiap baris terdiri dari 8—12 suku kata",
            "• Bersajak a-b-a-b (baris 1 bersajak dengan baris 3, baris 2 dengan baris 4)",
            "• Baris 1—2 adalah sampiran (pengantar/pembukaan)",
            "• Baris 3—4 adalah isi (pesan inti)",
            "",
            "Apa itu sampiran?",
            "• Bagian pembuka yang secara tidak langsung mengantarkan isi",
            "• Biasanya berupa gambaran alam, kegiatan sehari-hari, atau situasi",
            "• Tidak mengandung pesan langsung, hanya sebagai pengantar",
            "• Fungsinya: menyiapkan rima dan irama untuk isi",
            "",
            "Apa itu isi?",
            "• Bagian inti yang mengandung pesan, nasihat, atau maksud",
            "• Isi harus bersajak dengan sampiran",
            "",
            "Tips: Sampiran dan isi TIDAK perlu berhubungan makna. Yang penting adalah kesamaan rima di akhir baris. Contoh: baris 1 'Blitar' (a) harus bersajak dengan baris 3 'pintar' (a).",
            "",
            "Jenis pantun berdasarkan tema:",
            "• Pantun nasihat — berisi petuah dan ajaran baik",
            "• Pantun jenaka — bertujuan menghibur dengan candaan",
            "• Pantun teka-teki — berisi tebakan yang harus dijawab",
            "• Pantun percintaan — mengungkapkan perasaan sayang",
            "• Pantun agama — berisi ajaran keagamaan",
          ],
          contoh: [
            "Contoh pantun nasihat:",
            "Buah semangka buah kedondong (a — sampiran)",
            "Jangan lupa dibawa ke pasar (b — sampiran)",
            "Hiduplah rukun sesama tetangga (a — isi)",
            "Agar damai dan terasa nyaman (b — isi)",
            "",
            "Contoh pantun jenaka:",
            "Anak kera turun ke sawah (a)",
            "Melihat kambing makan nanas (b)",
            "Wajahmu sungguh amat resah (a)",
            "Ternyata dompetmu kemasukan kelas (b)",
            "",
            "Tips Membuat Pantun:",
            "1. Tentukan dulu isi (baris 3-4)",
            "2. Buat sampiran yang bersajak dengan isi",
            "3. Pastikan jumlah suku kata 8-12 per baris",
            "4. Hitung dengan jari untuk memastikan jumlah suku kata",
          ],
        },
        {
          judul: "3. Syair — Ciri, Struktur, dan Fungsi",
          isi: [
            "Syair adalah puisi rakyat yang berasal dari tradisi Melayu. Berbeda dengan pantun, syair lebih panjang dan digunakan untuk bercerita atau menyampaikan ajaran.",
            "",
            "Ciri-ciri syair:",
            "• Setiap bait terdiri dari 4 baris",
            "• Semua baris adalah isi (tidak ada sampiran)",
            "• Bersajak a-a-a-a (semua baris berakhiran sama)",
            "• Setiap baris terdiri dari 8—14 suku kata",
            "• Berisi cerita, nasihat, ajaran agama, atau kisah kepahlawanan",
            "",
            "Perbedaan syair dengan pantun:",
            "| Aspek | Pantun | Syair |",
            "|-------|--------|-------|",
            "| Sampiran | Ada (baris 1-2) | Tidak ada |",
            "| Rima | a-b-a-b | a-a-a-a |",
            "| Isi | Baris 3-4 | Semua baris |",
            "| Fungsi | Berbalas/komunikasi | Bercerita/mendidik |",
            "",
            "Fungsi syair dalam masyarakat:",
            "• Media dakwah dan penyebaran agama (syair agama)",
            "• Media pendidikan (syair nasihat)",
            "• Hiburan dan kesenian (syair cerita/kisah)",
            "• Dokumentasi sejarah (syair sejarah/peristiwa)",
            "",
            "Tips: Syair harus dibaca dari baris 1 sampai 4 secara berurutan karena semuanya adalah isi. Tidak seperti pantun yang bisa dibaca hanya baris isi (3-4).",
          ],
          contoh: [
            "Contoh syair nasihat:",
            "",
            "Wahai ananda intan pilihan (a)",
            "Dengarkan ibu beri petuahan (a)",
            "Janganlah engkau bersifat malasan (a)",
            "Ilmu dicari dengan kesungguhan (a)",
            "",
            "Belajar janganlah engkau jemu (a)",
            "Pagi petang baca buku (a)",
            "Jangan ikut hawa nafsu (a)",
            "Kelak menyesal tidak bertentu (a)",
            "",
            "Tips Membuat Syair:",
            "1. Tentukan tema terlebih dahulu",
            "2. Tulis baris pertama, lalu buat baris 2-4 dengan rima yang sama",
            "3. Syair bisa terdiri dari beberapa bait yang saling berkaitan",
            "4. Baca keras-keras untuk memeriksa kelancaran rima",
          ],
        },
        {
          judul: "4. Gurindam — Ciri, Struktur, dan Makna",
          isi: [
            "Gurindam adalah puisi rakyat yang sangat ringkas — hanya terdiri dari 2 baris dalam satu bait. Meskipun pendek, gurindam sarat dengan nasihat dan ajaran hidup.",
            "",
            "Ciri-ciri gurindam:",
            "• Setiap bait terdiri dari 2 baris",
            "• Bersajak a-a (baris 1 dan 2 berakhiran sama)",
            "• Baris 1: syarat, sebab, atau pernyataan",
            "• Baris 2: akibat, jawaban, atau kesimpulan",
            "• Berisi nasihat, petuah, atau ajaran moral",
            "• Bahasa padat, ringkas, dan penuh makna",
            "",
            "Struktur 'Syarat-Akibat' dalam gurindam:",
            "Baris 1: Jika/Siapa/Barang siapa ... (syarat)",
            "Baris 2: Maka/ ... lah/Maka ... lah (akibat)",
            "",
            "Contoh pola syarat-akibat:",
            "\"Barang siapa mengenal Allah\" (syarat)",
            "\"Suruh dan tegahnya tiada menyalah\" (akibat)",
            "",
            "Fungsi gurindam:",
            "• Memberikan nasihat secara singkat dan padat",
            "• Mengajarkan nilai-nilai moral dan agama",
            "• Sebagai pedoman hidup dalam berbagai situasi",
            "",
            "Gurindam terkenal: Gurindam Dua Belas karya Raja Ali Haji (abad ke-19) — 12 pasal berisi nasihat tentang kehidupan beragama, bermasyarakat, dan bernegara.",
          ],
          contoh: [
            "Contoh gurindam:",
            "",
            "Kurang pikir kurang siasat (a — syarat)",
            "Tentu dirimu akan tersesat (a — akibat)",
            "",
            "Jika ingin hidupmu teratur (a — syarat)",
            "Belajar disiplin dan tertib diatur (a — akibat)",
            "",
            "Hati yang bersih dan suci (a — syarat)",
            "Membawa berkah sepanjang hari (a — akibat)",
            "",
            "Barang siapa meninggalkan salat (a)",
            "Hidupnya akan terasa sempit (a)",
            "",
            "Tips Membuat Gurindam:",
            "1. Tentukan nasihat yang ingin disampaikan",
            "2. Rumuskan dalam dua bagian: syarat (baris 1) dan akibat (baris 2)",
            "3. Pastikan rima akhir sama (a-a)",
            "4. Gunakan kata-kata yang padat dan bermakna dalam",
          ],
        },
        {
          judul: "5. Perbandingan Pantun, Syair, dan Gurindam",
          isi: [
            "Untuk memudahkan pemahaman, mari bandingkan ketiga jenis puisi rakyat dalam satu tabel.",
            "",
            "Perbandingan Lengkap:",
            "| Aspek | Pantun | Syair | Gurindam |",
            "|-------|--------|-------|----------|",
            "| Jumlah baris per bait | 4 | 4 | 2 |",
            "| Rima | a-b-a-b | a-a-a-a | a-a |",
            "| Sampiran | Ada (baris 1-2) | Tidak ada | Tidak ada |",
            "| Isi | Baris 3-4 | Semua baris Semua baris |",
            "| Jumlah suku kata | 8-12 per baris | 8-14 per baris | 10-14 per baris |",
            "| Hubungan baris | Sampiran ≠ Isi (tdk berhubungan) | Semua baris berhubungan | Syarat (baris 1) → Akibat (baris 2) |",
            "| Fungsi utama | Hiburan & komunikasi | Cerita & pendidikan | Nasihat singkat & padat |",
            "",
            "Tips mengingat:",
            "• Pantun = 4 baris, a-b-a-b (ingat: P-A-B-A-B → Pantun ABAB)",
            "• Syair = 4 baris, a-a-a-a (ingat: S-A-A-A-A → Syair semua A)",
            "• Gurindam = 2 baris, a-a (ingat: G-2-A-A → Gurindam 2 baris AA)",
          ],
          contoh: [
            "Perbandingan dalam satu tema 'Pendidikan':",
            "",
            "Pantun:",
            "Belah durian belah nangka (a)",
            "Jangan lupa beli ketupat (b)",
            "Rajin belajar sepanjang masa (a)",
            "Agar masa depan menjadi cemerlang (b)",
            "",
            "Syair:",
            "Belajar tak kenal waktu dan usia (a)",
            "Ilmu dicari dengan suka cita (a)",
            "Guru dihormati setiap masa (a)",
            "Supaya hidup penuh berkah (a)",
            "",
            "Gurindam:",
            "Jika ingin cita-cita tercapai (a)",
            "Belajar rajin jangan dibuat main (a)",
          ],
        },
        {
          judul: "6. Nilai-Nilai dalam Puisi Rakyat",
          isi: [
            "Puisi rakyat bukan sekadar permainan kata. Di balik keindahan bahasanya, puisi rakyat menyimpan nilai-nilai luhur yang relevan hingga saat ini.",
            "",
            "1. Nilai Religius/Agama",
            "• Ajaran tentang keimanan dan ketakwaan",
            "• Contoh: \"Jika hendak mengenal Tuhan, / Pada hati bersih dan pikiran jernih\"",
            "• Mengingatkan untuk selalu bersyukur dan beribadah",
            "",
            "2. Nilai Moral",
            "• Ajaran tentang baik dan buruk dalam hidup",
            "• Contoh: \"Barang siapa mengenal dirinya, / Tuhannya pasti dikenal olehnya\"",
            "• Nasihat tentang kejujuran, kerja keras, kesabaran",
            "",
            "3. Nilai Budaya",
            "• Mencerminkan tradisi dan kearifan lokal Nusantara",
            "• Penggunaan istilah-istilah budaya: sirih, pinang, tanah leluhur",
            "• Menjaga warisan sastra tradisional agar tidak punah",
            "",
            "4. Nilai Sosial",
            "• Mengajarkan cara bergaul dan berkomunikasi yang santun",
            "• Contoh: \"Kalau kita pergi ke pekan, / Jangan lupa membeli labu\"",
            "• Nilai gotong royong, saling menghormati, dan kekeluargaan",
            "",
            "5. Nilai Pendidikan",
            "• Mendorong semangat belajar dan menuntut ilmu",
            "• Contoh: \"Rajin-rajinlah membaca buku, / Agar kau pintar dan berilmu\"",
            "• Ilmu sebagai bekal hidup yang paling berharga",
            "",
            "PENTING: Dalam setiap puisi rakyat, carilah nilai-nilai di atas. Diskusikan dengan teman bagaimana nilai-nilai itu masih relevan dengan kehidupan remaja masa kini.",
          ],
          contoh: [
            "Analisis nilai dalam pantun:",
            "",
            "\"Buah cempedak buah nangka\"",
            "\"Jangan lupa beli ketupat\"",
            "\"Jika hati selalu gembira\"",
            "\"Tubuh sehat jiwa pun kuat\"",
            "",
            "Nilai yang terkandung:",
            "• Nilai moral: pentingnya menjaga kesehatan mental (hati gembira)",
            "• Nilai pendidikan: hubungan antara kondisi psikis dan fisik",
            "• Nilai sosial: disampaikan dengan bahasa yang santun dan tidak menggurui",
          ],
        },
        {
          judul: "7. Prosedur Menulis Puisi Rakyat",
          isi: [
            "Sekarang saatnya kamu menulis puisi rakyat sendiri. Ikuti prosedur berikut sesuai dengan jenis yang kamu pilih.",
            "",
            "A. Menulis Pantun",
            "Langkah 1: Tentukan isi pantun (baris 3-4). Apa pesan yang ingin disampaikan?",
            "Langkah 2: Pilih kata terakhir baris 3 (misal: 'buku' bersajak '-uku')",
            "Langkah 3: Cari kata bersajak sama untuk baris 4",
            "Langkah 4: Buat sampiran (baris 1-2) yang bersajak a-b (terakhir baris 1 sajak '-a', baris 2 sajak '-b')",
            "Langkah 5: Hitung suku kata setiap baris (8-12 suku kata)",
            "Langkah 6: Sesuaikan jika ada kelebihan/kekurangan suku kata",
            "",
            "B. Menulis Syair",
            "Langkah 1: Tentukan tema dan cerita/nasihat yang ingin disampaikan",
            "Langkah 2: Tulis 4 baris dengan rima a-a-a-a (akhir baris sama)",
            "Langkah 3: Pastikan setiap baris berisi bagian dari kesatuan cerita",
            "Langkah 4: Jika cerita panjang, buat beberapa bait yang saling sambung",
            "",
            "C. Menulis Gurindam",
            "Langkah 1: Tentukan nasihat singkat yang ingin disampaikan",
            "Langkah 2: Rumuskan baris 1: 'Jika ...' atau 'Barang siapa ...' (syarat)",
            "Langkah 3: Rumuskan baris 2: 'Maka ...' atau '...lah ...' (akibat)",
            "Langkah 4: Pastikan rima a-a dan jumlah suku kata seimbang",
            "",
            "Tips Akhir: Setelah selesai, bacakan puisimu dengan suara nyaring. Apakah rimanya terdengar indah? Apakah jumlah suku katanya pas? Minta teman mendengarkan dan memberi masukan.",
          ],
          rangkuman: [
            "Rumus Cepat Menulis Puisi Rakyat:",
            "",
            "Pantun: ISI dulu (baris 3-4) → SAMPIran (baris 1-2) → cek RIMA (a-b-a-b) → cek SUKU KATA (8-12)",
            "Syair: TEMA → 4 baris → RIMA (a-a-a-a) → CERITA (semua baris isi)",
            "Gurindam: NASIHAT → SYARAT (baris 1) → AKIBAT (baris 2) → RIMA (a-a)",
            "",
            "✓ Semakin sering berlatih, semakin mahir membuat puisi rakyat!",
          ],
        },
      ],
    },
    latihan: [
      {
        id: 1,
        tipe: "PG",
        soal: "Puisi rakyat yang setiap baitnya terdiri dari 4 baris dengan rima a-b-a-b disebut...",
        opsi: ["Syair", "Pantun", "Gurindam", "Seloka"],
        jawaban: 1,
        penjelasan: "Pantun memiliki ciri 4 baris per bait dengan rima a-b-a-b serta baris 1-2 sebagai sampiran.",
      },
      {
        id: 2,
        tipe: "PG",
        soal: "Baris 1 dan 2 dalam pantun disebut...",
        opsi: ["Isi", "Sampiran", "Amanat", "Tema"],
        jawaban: 1,
        penjelasan: "Sampiran adalah bagian pembuka pantun (baris 1-2) yang berfungsi mengantarkan isi.",
      },
      {
        id: 3,
        tipe: "PG",
        soal: "Ciri khas syair yang membedakannya dari pantun adalah...",
        opsi: ["Memiliki sampiran", "Bersajak a-a-a-a", "Hanya 2 baris", "Tidak memiliki isi"],
        jawaban: 1,
        penjelasan: "Syair bersajak a-a-a-a (semua baris rima sama), sedangkan pantun a-b-a-b.",
      },
      {
        id: 4,
        tipe: "PG",
        soal: "Gurindam terdiri dari... baris dalam satu bait.",
        opsi: ["2", "3", "4", "5"],
        jawaban: 0,
        penjelasan: "Gurindam hanya terdiri dari 2 baris dalam setiap baitnya.",
      },
      {
        id: 5,
        tipe: "PG",
        soal: "Dalam gurindam, baris pertama berisi...",
        opsi: ["Akibat", "Kesimpulan", "Syarat atau sebab", "Sampiran"],
        jawaban: 2,
        penjelasan: "Baris 1 gurindam berisi syarat/sebab, baris 2 berisi akibat/kesimpulan.",
      },
      {
        id: 6,
        tipe: "PG",
        soal: "Berikut yang bukan merupakan ciri puisi rakyat adalah...",
        opsi: ["Anonim", "Terikat aturan", "Diketahui pengarangnya", "Bersifat lisan"],
        jawaban: 2,
        penjelasan: "Puisi rakyat bersifat anonim (tidak diketahui pengarangnya), bukan sebaliknya.",
      },
      {
        id: 7,
        tipe: "PG",
        soal: "Pantun yang berisi tebakan yang harus dijawab disebut pantun...",
        opsi: ["Nasihat", "Jenaka", "Teka-teki", "Agama"],
        jawaban: 2,
        penjelasan: "Pantun teka-teki berisi pertanyaan atau tebakan yang jawabannya harus ditebak.",
      },
      {
        id: 8,
        tipe: "PG",
        soal: "Jumlah suku kata dalam setiap baris pantun adalah...",
        opsi: ["5-7 suku kata", "8-12 suku kata", "10-15 suku kata", "12-18 suku kata"],
        jawaban: 1,
        penjelasan: "Setiap baris pantun terdiri dari 8-12 suku kata.",
      },
      {
        id: 9,
        tipe: "PG",
        soal: "Sastrawan terkenal yang menulis Gurindam Dua Belas adalah...",
        opsi: ["Chairil Anwar", "Raja Ali Haji", "Sutan Takdir Alisjahbana", "W.S. Rendra"],
        jawaban: 1,
        penjelasan: "Gurindam Dua Belas dikarang oleh Raja Ali Haji, seorang sastrawan dan ulama Melayu abad ke-19.",
      },
      {
        id: 10,
        tipe: "PG",
        soal: "Nilai yang terkandung dalam puisi rakyat yang mengajarkan tentang baik-buruk perbuatan disebut nilai...",
        opsi: ["Religius", "Moral", "Budaya", "Sosial"],
        jawaban: 1,
        penjelasan: "Nilai moral berkaitan dengan ajaran tentang perbuatan baik dan buruk dalam kehidupan.",
      },
    ],
    praktik: {
      tujuan: "Memproduksi tiga jenis puisi rakyat (pantun, syair, gurindam) dengan tema yang ditentukan.",
      instruksi: "Buatlah satu bait pantun, satu bait syair, dan satu bait gurindam dengan tema bebas. Pastikan mengikuti aturan masing-masing jenis puisi rakyat.",
      langkah: [
        "Tentukan tema puisimu (contoh: pendidikan, persahabatan, lingkungan, cita-cita)",
        "Buat satu bait pantun: 4 baris, rima a-b-a-b, baris 1-2 sampiran, baris 3-4 isi",
        "Buat satu bait syair: 4 baris, rima a-a-a-a, semua baris isi",
        "Buat satu bait gurindam: 2 baris, rima a-a, baris 1 syarat baris 2 akibat",
        "Hitung jumlah suku kata setiap baris untuk memastikan sesuai aturan",
        "Periksa rima: apakah bunyi akhir setiap baris sudah sesuai?",
        "Bacakan puisimu dengan suara nyaring. Apakah terdengar indah dan lancar?",
        "Kumpulkan ketiga puisi dalam satu karya tulis. Beri judul kumpulan puisimu.",
      ],
      tips: [
        "Gunakan kamus rima (kamus saku atau online) untuk mencari kata yang bersajak.",
        "Mulailah dengan tema yang dekat dengan keseharianmu.",
        "Untuk pantun, buat isi dulu baru sampiran agar lebih mudah.",
        "Jangan takut bereksperimen dengan pilihan kata.",
        "Minta temanmu menanggapi puisimu — kritik yang membangun akan membuat puisimu lebih baik.",
      ],
      contoh: "Lihat contoh pantun, syair, dan gurindam pada materi 'Perbandingan Pantun, Syair, dan Gurindam' di atas.",
    },
    kuis: [
      {
        id: 1,
        tipe: "PG",
        soal: "Apa rima yang benar untuk satu bait pantun?",
        opsi: ["a-a-a-a", "a-b-a-b", "a-b-b-a", "a-a-b-b"],
        jawaban: 1,
        penjelasan: "Pantun memiliki rima a-b-a-b: baris 1 dan 3 bersajak, baris 2 dan 4 bersajak.",
      },
      {
        id: 2,
        tipe: "PG",
        soal: "Bagian pantun yang berisi pesan atau nasihat adalah...",
        opsi: ["Baris 1-2 (sampiran)", "Baris 3-4 (isi)", "Baris 1 saja", "Baris 4 saja"],
        jawaban: 1,
        penjelasan: "Isi pantun berada pada baris 3 dan 4, sedangkan baris 1-2 adalah sampiran.",
      },
      {
        id: 3,
        tipe: "PG",
        soal: "Berapa jumlah bait minimal syair yang dapat berdiri sendiri?",
        opsi: ["1 bait", "2 bait", "3 bait", "4 bait"],
        jawaban: 0,
        penjelasan: "Syair dapat terdiri dari 1 bait (4 baris) yang sudah mengandung pesan utuh.",
      },
      {
        id: 4,
        tipe: "PG",
        soal: "Puisi rakyat yang berfungsi untuk menyampaikan nasihat secara singkat dan padat adalah...",
        opsi: ["Pantun", "Syair", "Gurindam", "Karmina"],
        jawaban: 2,
        penjelasan: "Gurindam menyampaikan nasihat secara sangat singkat — hanya 2 baris per bait.",
      },
      {
        id: 5,
        tipe: "PG",
        soal: "Jika sebuah puisi memiliki rima a-a-a-a dan 4 baris per bait, puisi tersebut adalah...",
        opsi: ["Pantun", "Syair", "Gurindam", "Seloka"],
        jawaban: 1,
        penjelasan: "Syair: 4 baris, rima a-a-a-a, semua baris isi.",
      },
      {
        id: 6,
        tipe: "PG",
        soal: "Dalam gurindam, hubungan baris 1 dan 2 bersifat...",
        opsi: ["Sampiran dan isi", "Syarat dan akibat", "Setara", "Pertentangan"],
        jawaban: 1,
        penjelasan: "Baris 1 gurindam berisi syarat, baris 2 berisi akibat dari syarat tersebut.",
      },
      {
        id: 7,
        tipe: "PG",
        soal: "Nilai yang berkaitan dengan ajaran keagamaan dalam puisi rakyat disebut nilai...",
        opsi: ["Moral", "Sosial", "Religius", "Pendidikan"],
        jawaban: 2,
        penjelasan: "Nilai religius berkaitan dengan ajaran keagamaan, iman, dan takwa kepada Tuhan.",
      },
      {
        id: 8,
        tipe: "PG",
        soal: "Pilihan kata yang tepat untuk melengkapi pantun rima a-b-a-b: 'Belanja ke pasar membeli ketan' (a) — 'Jangan lupa membeli roti' (b) — '...' — 'Supaya hidupmu selalu berarti' (b). Baris 3 yang tepat adalah...",
        opsi: ["Rajin-rajinlah membaca buku (a)", "Pergi ke hutan mencari jamur (a)", "Bersikaplah jujur dan santun (a)", "Belajar dengan tekun dan giat (a)"],
        jawaban: 2,
        penjelasan: "Baris 3 harus bersajak 'a' dengan baris 1 ('ketan'). 'Santun' bersajak 'an' dengan 'ketan'. Baris 3 juga harus merupakan isi.",
      },
      {
        id: 9,
        tipe: "PG",
        soal: "Puisi rakyat bersifat anonim, artinya...",
        opsi: ["Memiliki banyak penulis", "Tidak diketahui pengarangnya", "Ditulis oleh rakyat", "Diterbitkan secara anonim"],
        jawaban: 1,
        penjelasan: "Anonim berarti tidak diketahui nama pengarangnya. Puisi rakyat diwariskan secara lisan dari generasi ke generasi.",
      },
      {
        id: 10,
        tipe: "PG",
        soal: "Contoh kata yang tepat untuk mengakhiri baris pantun dengan rima '-at' di baris ke-4 adalah...",
        opsi: ["Pergi", "Cepat", "Ketupat", "Tidur"],
        jawaban: 2,
        penjelasan: "'Ketupat' berakhiran '-at' dan sesuai untuk rima pantun baris ke-4 apabila baris ke-2 juga berakhiran '-at'.",
      },
    ],
  };

export default konten;
