// @ts-nocheck
import type { Konten, Soal } from "../types";

const kd = "3.5/4.5";

/* =============================================
   Unit 5: Teks Cerita Inspiratif — IX S2
   KD 3.5/4.5 — Mengidentifikasi Unsur & Menyusun Teks Cerita Inspiratif
   ============================================= */
const konten: Konten = {
    belajar: {
      tujuan: [
        "Memahami hakikat, ciri-ciri, dan tujuan teks cerita inspiratif",
        "Mengidentifikasi struktur teks cerita inspiratif: orientasi, peristiwa, reaksi, dan koda",
        "Menganalisis unsur kebahasaan yang menonjol dalam teks cerita inspiratif",
        "Mengenali nilai-nilai inspiratif (moral, sosial, spiritual) dalam berbagai cerita",
        "Membedakan teks cerita inspiratif dengan cerpen dan teks nonfiksi",
        "Menyusun teks cerita inspiratif secara mandiri dengan struktur dan kaidah yang tepat",
      ],
      materi: [
        {
          judul: "1. Hakikat Teks Cerita Inspiratif",
          catatan: "Teks cerita inspiratif mengisahkan pengalaman hidup yang membangkitkan semangat pembaca.",
          isi: [
            "Teks cerita inspiratif adalah teks narasi yang mengisahkan perjalanan hidup seseorang — baik tokoh nyata maupun fiktif — yang mampu membangkitkan motivasi, semangat, dan tekad pembaca untuk berbuat lebih baik. Cerita ini menyajikan perjuangan, kegagalan, hingga keberhasilan yang menginspirasi.",
            "",
            "Ciri-ciri teks cerita inspiratif:",
            "• Bersumber dari kisah nyata atau peristiwa yang dialami tokoh",
            "• Mengandung pesan moral atau nilai kehidupan yang mendalam",
            "• Berfokus pada perjuangan tokoh melawan keterbatasan atau kesulitan",
            "• Membangkitkan emosi pembaca: haru, kagum, semangat, dan termotivasi",
            "• Memiliki alur yang mengarah pada perubahan sikap atau pandangan hidup",
            "• Menggunakan sudut pandang orang pertama atau ketiga",
            "• Gaya bahasa persuasif dan emotif untuk menyentuh perasaan",
            "",
            "Tujuan teks cerita inspiratif:",
            "✓ Memberikan motivasi dan dorongan kepada pembaca",
            "✓ Menanamkan nilai-nilai positif seperti pantang menyerah, kejujuran, dan kerja keras",
            "✓ Menyadarkan pembaca bahwa setiap kesulitan pasti ada jalan keluar",
            "✓ Mengajak pembaca merefleksikan kehidupan dan memperbaiki diri",
            "",
            "PENTING: Cerita inspiratif berbeda dengan cerita hiburan biasa. Cerita inspiratif selalu meninggalkan 'sesuatu' pada pembaca — berupa dorongan, pemikiran baru, atau tekad untuk berubah. Tanpa dampak emosional tersebut, sebuah cerita belum layak disebut inspiratif.",
          ],
          contoh: [
            "Contoh tema cerita inspiratif yang sering diangkat:",
            "",
            "• Perjuangan anak desa meraih mimpi — kisah perintis teknologi dari Nusa Tenggara Timur yang berhasil kuliah di luar negeri",
            "• Kegigihan seorang veteran — mantan tentara yang menjadi pengusaha sukses di usia senja",
            "• Kisah penyandang disabilitas berprestasi — peraih medali emas Paralimpiade dari Solo",
            "• Perjalanan seorang guru di pelosok — mengajar puluhan tahun tanpa listrik demi masa depan anak-anak",
            "• Pengusaha muda yang bangkit dari kebangkrutan tujuh kali hingga akhirnya sukses",
            "",
            "Setiap tema di atas memiliki benang merah yang sama: tokoh menghadapi rintangan, tidak menyerah, dan akhirnya berhasil mencapai sesuatu yang bermakna.",
          ],
        },
        {
          judul: "2. Ciri-Ciri dan Tujuan Teks Cerita Inspiratif",
          isi: [
            "Setiap teks cerita inspiratif memiliki ciri khas yang membedakannya dari jenis teks narasi lainnya. Memahami ciri-ciri ini penting agar kamu dapat mengenali dan menulis teks cerita inspiratif dengan tepat.",
            "",
            "A. Ciri-Ciri Teks Cerita Inspiratif",
            "Berdasarkan Isi:",
            "• Mengisahkan peristiwa yang membekas dan mengubah hidup tokoh",
            "• Berfokus pada momen 'titik balik' (turning point) dalam kehidupan tokoh",
            "• Mengandung konflik batin atau tantangan eksternal yang berat",
            "• Penyelesaian cerita bersifat membangkitkan semangat",
            "",
            "Berdasarkan Bahasa:",
            "• Menggunakan kata-kata konotatif yang bermuatan emosi",
            "    — Contoh: 'terpukul', 'tersungkur', 'berbinar', 'terekam dalam relung hati'",
            "• Banyak menggunakan kata seruan dan kalimat persuasif",
            "    — Contoh: 'Betapa besar perjuangannya!'",
            "• Menggunakan majas perbandingan (metafora, simile) untuk memperkuat makna",
            "    — Contoh: 'Hidupnya bagaikan lilin yang menerangi kegelapan'",
            "• Kata ganti orang pertama atau ketiga yang konsisten",
            "",
            "B. Tujuan Teks Cerita Inspiratif",
            "✓ Membangkitkan motivasi dan semangat pembaca",
            "✓ Menanamkan nilai-nilai kehidupan yang luhur",
            "✓ Mendorong perubahan sikap atau perilaku ke arah yang lebih baik",
            "✓ Memberikan perspektif baru dalam menghadapi masalah",
            "✓ Menginspirasi pembaca untuk tidak mudah menyerah",
            "",
            "PENTING: Tujuan utama teks cerita inspiratif bukan sekadar menghibur, melainkan 'menggerakkan' — membuat pembaca merasa 'Saya juga bisa!'. Jika cerita tidak mampu membangkitkan perasaan itu, maka teks tersebut belum memenuhi fungsi inspiratifnya.",
          ],
          contoh: [
            "Bandingkan dua teks berikut untuk memahami ciri cerita inspiratif:",
            "",
            "Teks A (bukan inspiratif):",
            "\"Pak Budi adalah seorang nelayan. Setiap pagi ia pergi melaut. Ia menangkap ikan lalu menjualnya di pasar. Ia pulang sore hari dan istirahat.\"",
            "",
            "Teks B (inspiratif):",
            "\"Pak Budi pernah kehilangan satu-satunya perahu akibat badai. Ia jatuh miskin dan sempat putus asa. Namun, dengan sisa tabungan, ia membeli jaring bekas dan mulai dari nol. Kini, ia memiliki tiga perahu dan mempekerjakan lima pemuda desa. 'Kegagalan bukan akhir,' katanya, 'tapi awal dari perjuangan yang lebih keras.'\"",
            "",
            "Perbedaan: Teks B memiliki konflik, titik balik, dan pesan motivasi yang membangkitkan semangat pembaca.",
          ],
        },
        {
          judul: "3. Struktur Teks Cerita Inspiratif",
          isi: [
            "Teks cerita inspiratif memiliki struktur yang khas dan berbeda dengan jenis teks narasi lainnya. Struktur ini membantu pembaca mengikuti perjalanan tokoh secara logis dan emosional.",
            "",
            "1. Orientasi (Pembukaan)",
            "  • Memperkenalkan tokoh, latar tempat, waktu, dan situasi awal kehidupan tokoh",
            "  • Menggambarkan kondisi tokoh sebelum mengalami perubahan",
            "  • Biasanya dimulai dengan gambaran kehidupan tokoh yang biasa-biasa saja atau penuh keterbatasan",
            "  • Contoh: \"Seorang anak laki-laki bernama Fadli tumbuh di kampung terpencil di lereng Gunung Rinjani. Setiap hari ia berjalan kaki sepuluh kilometer menuju sekolah satu-satunya di kecamatan.\"",
            "",
            "2. Peristiwa (Rangkaian Kejadian)",
            "  • Bagian yang menceritakan tantangan, kesulitan, atau konflik yang dihadapi tokoh",
            "  • Dapat berupa peristiwa tunggal yang mengubah hidup atau serangkaian perjuangan panjang",
            "  • Bagian ini membangun emosi dan membuat pembaca ikut merasakan kesulitan tokoh",
            "  • Titik balik (turning point) sering muncul di bagian ini — saat tokoh mengambil keputusan penting",
            "  • Contoh: \"Fadli nyaris putus sekolah saat ibunya sakit parah. Ia harus membagi waktu antara belajar, bekerja sebagai kuli bangunan, dan merawat ibunya. Namun, ia berjanji pada dirinya: 'Aku harus sekolah.'\"",
            "",
            "3. Reaksi (Respon Tokoh terhadap Peristiwa)",
            "  • Menunjukkan bagaimana tokoh merespons tantangan yang dihadapi",
            "  • Bagian ini yang paling 'inspiratif' — menunjukkan kegigihan, keberanian, dan tekad tokoh",
            "  • Reaksi tokoh menjadi sumber inspirasi bagi pembaca",
            "  • Contoh: \"Setiap subuh Fadli bangun lebih awal untuk belajar. di siang hari ia bekerja, dan malam harinya ia belajar lagi di bawah lampu minyak. Teman-temannya menertawakannya, tetapi ia tidak peduli.\"",
            "",
            "4. Koda (Penutup / Amanat)",
            "  • Bagian penutup yang berisi hasil akhir dari perjuangan tokoh",
            "  • Menyampaikan pesan moral atau pelajaran hidup yang dapat dipetik",
            "  • Sering kali berisi kalimat bijak atau refleksi tokoh tentang perjalanannya",
            "  • Contoh: \"Dua puluh tahun kemudian, Fadli lulus sebagai doktor di bidang pendidikan. Ia kembali ke kampungnya dan membangun sekolah gratis. 'Keterbatasan bukan alasan,' katanya, 'justru itulah bahan bakarnya.'\"",
            "",
            "Tips Membaca struktur: Saat membaca teks cerita inspiratif, cari kata-kata kunci seperti 'awalnya', 'namun', 'tetapi', 'akhirnya', 'sejak saat itu', 'kini' — kata-kata ini menandai perpindahan antarbagian struktur.",
          ],
          contoh: [
            "Analisis struktur pada cerita inspiratif 'Kisah Seorang Tukang Becak':",
            "",
            "Orientasi: \"Pak Saiful adalah tukang becak di Yogyakarta. Ia hanya lulusan SD dan hidup sederhana bersama istri dan tiga anaknya di sebuah rumah kontrakan sempit.\"",
            "",
            "Peristiwa: \"Suatu hari, anak bungsunya jatuh sakit dan membutuhkan biaya operasi besar. Pak Saiful tidak punya uang. Ia berkeliling meminjam ke tetangga dan saudara, tetapi tidak cukup. Ia hampir menyerah.\"",
            "",
            "Reaksi: \"Namun, Pak Saiful tidak mau menyerah. Setiap hari ia menarik becak lebih keras, dari subuh hingga tengah malam. Ia juga mulai menjual gorengan buatan istrinya di sela-sela waktu. Peluh bercucuran, tetapi ia terus bergerak.\"",
            "",
            "Koda: \"Setelah tiga bulan, tabungannya cukup untuk biaya operasi. Anaknya sembuh. Kini Pak Saiful memiliki warung kecil di samping rumahnya. 'Rezeki tidak akan tertukar,' katanya. 'Yang penting niat dan usaha.'\"",
          ],
        },
        {
          judul: "4. Unsur Kebahasaan Teks Cerita Inspiratif",
          isi: [
            "Teks cerita inspiratif memiliki kekhasan dalam penggunaan bahasa. Unsur kebahasaan ini yang membuat cerita terasa hidup, menyentuh, dan membekas di hati pembaca.",
            "",
            "1. Kata Kerja Mental (Verba Mentalis)",
            "• Kata kerja yang berkaitan dengan pikiran, perasaan, dan persepsi",
            "• Contoh: merenung, membayangkan, berharap, merasa, terpukul, bersyukur, termotivasi",
            "• Fungsi: menggambarkan kondisi batin tokoh sehingga pembaca ikut merasakan emosinya",
            "• \"Ia merenung panjang di tepi pantai, membayangkan masa depan yang tak pasti.\"",
            "",
            "2. Kata Seruan (Interjeksi)",
            "• Kata seru yang mengungkapkan perasaan tokoh",
            "• Contoh: Aduh!, Oh!, Ya Tuhan!, Alhamdulillah!, Syukurlah!, Hebat!",
            "• Fungsi: memperkuat ekspresi emosi dalam cerita",
            "",
            "3. Majas Perbandingan (Metafora, Simile, Personifikasi)",
            "• Metafora: perbandingan tanpa kata pembanding — 'Lautan masalah menghadangnya'",
            "• Simile: perbandingan dengan kata 'bagaikan', 'seperti' — 'Semangatnya seperti api yang tak kunjung padam'",
            "• Personifikasi: benda mati seolah hidup — 'Kesulitan itu berbisik pelan di telinganya'",
            "",
            "4. Konjungsi Urutan Waktu (Temporal)",
            "• Kata hubung yang menunjukkan urutan peristiwa",
            "• Contoh: kemudian, setelah itu, akhirnya, pada akhirnya, sejak saat itu, dua tahun berselang",
            "• Fungsi: merangkai alur cerita secara kronologis dan logis",
            "",
            "5. Kata Sifat Deskriptif",
            "• Kata sifat yang menggambarkan keadaan tokoh, suasana, atau situasi secara mendetail",
            "• Contoh: gigih, terpukul, tak tergoyahkan, pilu, haru, tegar, tabah",
            "• Fungsi: membuat cerita lebih hidup dan imajinatif",
            "",
            "6. Kalimat Langsung dan Kalimat Tidak Langsung",
            "• Kalimat langsung untuk mengutip ucapan tokoh, memberi kesan autentik",
            "• Kalimat tidak langsung untuk meringkas dialog atau pikiran tokoh",
            "• Contoh langsung: \"Aku tidak akan menyerah!\" serunya.",
            "• Contoh tidak langsung: Ia mengatakan bahwa ia tidak akan menyerah.",
          ],
          rangkuman: [
            "Ingat rumus 'KeSinar-KaLa' untuk unsur kebahasaan teks cerita inspiratif:",
            "Ke = Kerja mental (verba mentalis)",
            "Si = Sifat deskriptif (kata sifat)",
            "na = nada seruan (interjeksi)",
            "r = retoris (majas perbandingan)",
            "",
            "Ka = Kalimat langsung/tidak langsung",
            "La = Laku waktu (konjungsi temporal)",
          ],
        },
        {
          judul: "5. Nilai-Nilai Inspiratif dalam Cerita",
          isi: [
            "Cerita inspiratif tidak hanya memotivasi, tetapi juga menanamkan nilai-nilai kehidupan yang mendalam. Nilai-nilai inilah yang membuat cerita tetap relevan dan bermakna lintas zaman.",
            "",
            "1. Nilai Moral",
            "• Ajaran tentang baik dan buruk yang berkaitan dengan perilaku manusia",
            "• Contoh nilai moral: kejujuran, keberanian, tanggung jawab, disiplin",
            "• Dalam cerita inspiratif, nilai moral sering muncul dari pilihan sulit yang diambil tokoh",
            "• Seorang pejabat yang memilih hidup sederhana meskipun memiliki banyak kesempatan untuk korupsi",
            "• Seorang siswa yang mengakui kesalahannya meskipun harus menerima hukuman",
            "",
            "2. Nilai Sosial",
            "• Nilai yang berkaitan dengan hubungan antarmanusia dalam masyarakat",
            "• Contoh: gotong royong, kepedulian, toleransi, solidaritas, rela berkorban",
            "• Dalam cerita inspiratif, nilai sosial tampak dari bagaimana tokoh berinteraksi dan membantu sesama",
            "• Seorang pengusaha sukses yang membangun sekolah di kampung halamannya",
            "• Relawan yang mengajar anak-anak jalanan di stasiun kereta",
            "",
            "3. Nilai Spiritual / Religius",
            "• Nilai yang berkaitan dengan hubungan manusia dengan Tuhan dan keyakinan",
            "• Contoh: tawakal, ikhlas, sabar, syukur, pasrah, keyakinan kepada takdir",
            "• Nilai ini memberi dimensi batin yang dalam pada cerita inspiratif",
            "• Seseorang yang tetap bersyukur meskipun hidup dalam kekurangan",
            "• Keyakinan bahwa setiap ujian adalah bagian dari rencana Tuhan yang lebih baik",
            "",
            "4. Nilai Perjuangan (Etos Kerja)",
            "• Semangat pantang menyerah, kerja keras, dan ketekunan",
            "• Ini adalah nilai yang paling menonjol dalam teks cerita inspiratif",
            "• Contoh: tokoh yang gagal berkali-kali tetapi terus bangkit, terus belajar, dan akhirnya berhasil",
            "• Thomas Alva Edison gagal ribuan kali sebelum menemukan bola lampu",
            "• Atlet yang tetap berlatih meskipun cedera dan divonis tidak bisa bertanding lagi",
            "",
            "5. Nilai Pendidikan",
            "• Pelajaran hidup atau hikmah yang dapat dipetik dan diterapkan pembaca",
            "• Biasanya dirangkum dalam koda atau amanat di akhir cerita",
            "• Contoh: 'Kegagalan adalah guru terbaik', 'Jangan pernah menyerah pada mimpi'",
            "",
            "PENTING: Satu cerita inspiratif biasanya mengandung lebih dari satu nilai secara bersamaan. Tugasmu saat membaca adalah mengidentifikasi nilai-nilai tersebut dan merenungkan bagaimana menerapkannya dalam kehidupan sehari-hari.",
          ],
          contoh: [
            "Contoh analisis nilai dalam cerita inspiratif 'Kisah Tukang Becak':",
            "",
            "Nilai Moral: Kejujuran Pak Saiful yang tidak pernah mencuri meskipun sangat membutuhkan uang.",
            "Nilai Sosial: Bantuan tetangga yang menjenguk dan menyumbang saat anaknya sakit.",
            "Nilai Spiritual: Kesabaran dan keikhlasan Pak Saiful menerima cobaan hidup.",
            "Nilai Perjuangan: Kerja keras dari subuh hingga tengah malam tanpa kenal lelah.",
            "",
            "Sebuah cerita inspiratif mengandung beberapa nilai sekaligus. Tugas pembaca adalah mengidentifikasi dan menerapkannya.",
          ],
        },
        {
          judul: "6. Perbedaan Teks Cerita Inspiratif dengan Cerpen dan Teks Nonfiksi",
          isi: [
            "Banyak siswa kesulitan membedakan teks cerita inspiratif dengan cerpen atau teks nonfiksi. Ketiganya memang sama-sama berbentuk narasi, tetapi memiliki perbedaan mendasar.",
            "",
            "A. Perbedaan dengan Cerpen",
            "1. Tujuan utama:",
            "• Cerpen → menghibur dan menyampaikan amanat secara artistik",
            "• Cerita inspiratif → memotivasi dan membangkitkan semangat pembaca",
            "",
            "2. Sumber cerita:",
            "• Cerpen → umumnya fiksi murni hasil imajinasi pengarang",
            "• Cerita inspiratif → bersumber dari kisah nyata atau peristiwa yang benar-benar terjadi, meskipun dikemas secara naratif",
            "",
            "3. Efek pada pembaca:",
            "• Cerpen → apresiasi estetis, hiburan, kadang introspeksi",
            "• Cerita inspiratif → dorongan untuk bertindak, motivasi kuat, perubahan sikap",
            "",
            "4. Penokohan:",
            "• Cerpen → karakter bisa siapa saja, konflik bisa apa saja",
            "• Cerita inspiratif → tokoh adalah 'pahlawan sehari-hari' yang perjuangannya relevan dengan kehidupan nyata",
            "",
            "B. Perbedaan dengan Teks Nonfiksi (Biografi/Autobiografi)",
            "1. Gaya penulisan:",
            "• Nonfiksi → objektif, faktual, berbasis data dan kronologi akurat",
            "• Cerita inspiratif → naratif-subjektif, mengandung dramatisasi dan emosi yang kuat",
            "",
            "2. Struktur:",
            "• Nonfiksi → struktur informatif (per bab tematis atau kronologis kaku)",
            "• Cerita inspiratif → struktur naratif (orientasi, peristiwa, reaksi, koda) yang lebih bebas dan mengalir",
            "",
            "3. Sisi emosi:",
            "• Nonfiksi → lebih datar, menekankan fakta dan informasi",
            "• Cerita inspiratif → kaya emosi, menggetarkan perasaan, menggunakan bahasa persuasif",
            "",
            "4. Contoh:",
            "• Biografi (nonfiksi): 'BJ Habibie lahir di Parepare, 25 Juni 1936. Ia menempuh pendidikan teknik di Jerman...'",
            "• Cerita inspiratif: 'Seorang pemuda dari kota kecil merantau ke Jerman dengan bekal tekad yang membaja. Ia belajar dengan gigih, meskipun harus bekerja di malam hari untuk membiayai hidup...'",
          ],
          contoh: [
            "Perbandingan Tiga Jenis Teks:",
            "",
            "| Aspek | Cerita Inspiratif | Cerpen | Biografi (Nonfiksi) |",
            "|-------|-------------------|--------|---------------------|",
            "| Tujuan | Memotivasi | Menghibur | Menginformasikan |",
            "| Sumber | Nyata/faktual | Fiksi | Nyata dan faktual |",
            "| Gaya Bahasa | Emotif, persuasif | Artistik, sastrawi | Objektif, informatif |",
            "| Struktur | Narasi 4 tahap | Struktur cerpen bebas | Kronologis tematis |",
            "| Efek | Dorongan bertindak | Kenikmatan estetis | Pengetahuan baru |",
          ],
        },
        {
          judul: "7. Prosedur Menulis Teks Cerita Inspiratif",
          isi: [
            "Setelah memahami hakikat, struktur, dan unsur kebahasaan teks cerita inspiratif, saatnya berlatih menulis. Ikuti langkah-langkah berikut untuk menghasilkan cerita inspiratif yang memukau.",
            "",
            "Langkah 1: Tentukan Tokoh dan Tema",
            "• Pilih tokoh inspiratif yang kamu kagumi (nyata atau fiktif berdasarkan gabungan orang-orang nyata)",
            "• Tentukan tema perjuangan: melawan keterbatasan, mengejar mimpi, berkorban untuk orang lain, dll.",
            "• Pastikan tokoh memiliki 'momen inspiratif' yang kuat — sesuatu yang membuat pembaca terharu atau kagum",
            "",
            "Langkah 2: Kumpulkan Detail Peristiwa",
            "• Catat informasi selengkap mungkin tentang perjuangan tokoh",
            "• Jika tokoh nyata: cari sumber dari buku, artikel, atau wawancara",
            "• Fokus pada 'titik balik' — momen ketika segalanya berubah",
            "",
            "Langkah 3: Buat Kerangka Berdasarkan Struktur",
            "• Orientasi: siapa tokoh, di mana, kapan, bagaimana kondisi awalnya?",
            "• Peristiwa: apa tantangan/konflik yang dihadapi?",
            "• Reaksi: bagaimana tokoh merespons dan berjuang?",
            "• Koda: apa hasilnya? Apa pesan moral yang bisa dipetik?",
            "",
            "Langkah 4: Kembangkan Menjadi Cerita Utuh",
            "• Gunakan bahasa yang mengalir, hidup, dan emosional",
            "• Terapkan unsur kebahasaan: kata kerja mental, majas, kalimat langsung, konjungsi temporal",
            "• Tulis dengan sudut pandang orang ketiga (ia/dia) agar lebih objektif",
            "• Buat pembaca 'merasakan' apa yang tokoh rasakan",
            "",
            "Langkah 5: Beri Dialog dan Detail Sensorik",
            "• Tambahkan kutipan langsung tokoh untuk memberi kesan autentik",
            "• Gunakan detail panca indera (apa yang dilihat, didengar, dirasakan tokoh)",
            "• Contoh: 'Ia menggenggam ijazahnya erat-erat. Tangannya gemetar. Air mata haru mengalir di pipinya yang keriput.'",
            "",
            "Langkah 6: Sunting dan Perbaiki",
            "• Periksa kembali struktur: apakah orientasi, peristiwa, reaksi, dan koda sudah lengkap?",
            "• Periksa ejaan, tanda baca, dan pilihan kata",
            "• Apakah nilai inspiratifnya tersampaikan dengan jelas?",
            "• Baca keras-keras untuk merasakan alurnya",
            "",
            "Langkah 7: Beri Judul yang Menarik",
            "• Judul yang baik membuat orang penasaran dan ingin membaca",
            "• Contoh judul: 'Dari Kuli Bangunan Menjadi Doktor', 'Guru di Atas Awan', 'Sepatu Butut dan Mimpi Besar'",
          ],
          rangkuman: [
            "Rumus menulis teks cerita inspiratif: TOKOH → KERANGKA → KEMBANG → DIALOG → SUNING → JUDUL",
            "",
            "Tips: Cerita inspiratif yang paling kuat adalah yang dekat dengan kehidupan sehari-hari. Kamu bisa menulis tentang perjuangan orang tuamu, kakakmu, gurumu, atau temanmu. Yang penting, cerita itu mampu membuat orang lain tersentuh dan termotivasi.",
          ],
        },
      ],
    },
    latihan: [
      {
        id: 1,
        soal: "Teks cerita inspiratif adalah teks narasi yang bertujuan...",
        opsi: [
          "Menghibur pembaca dengan cerita lucu",
          "Membangkitkan motivasi dan semangat pembaca melalui kisah perjuangan tokoh",
          "Memberikan informasi faktual tentang peristiwa sejarah",
          "Mendeskripsikan suatu objek secara rinci",
        ],
        jawaban: 1,
        penjelasan: "Teks cerita inspiratif bertujuan membangkitkan motivasi, semangat, dan dorongan kepada pembaca melalui kisah perjuangan tokoh.",
      },
      {
        id: 2,
        tipe: "BENAR_SALAH",
        soal: "Bagian struktur teks cerita inspiratif yang menceritakan tantangan atau kesulitan yang dihadapi tokoh disebut peristiwa.",
        opsi: ["Benar", "Salah"],
        jawaban: 0,
        penjelasan: "Peristiwa adalah bagian yang menceritakan rangkaian kejadian, tantangan, atau konflik yang dihadapi tokoh.",
      },
      {
        id: 3,
        soal: "Kata kerja yang berkaitan dengan pikiran, perasaan, dan persepsi dalam cerita inspiratif disebut...",
        opsi: ["Kata kerja material", "Kata kerja mental", "Kata seruan", "Kata sifat"],
        jawaban: 1,
        penjelasan: "Kata kerja mental (verba mentalis) adalah kata kerja yang berkaitan dengan aktivitas pikiran dan perasaan, seperti merenung, berharap, merasa, dan bersyukur.",
      },
      {
        id: 4,
        tipe: "ISIAN",
        soal: "Kata seruan seperti 'Aduh!', 'Ya Tuhan!', 'Alhamdulillah!' dalam teks cerita inspiratif secara istilah disebut...",
        opsi: "interjeksi",
        jawaban: "0",
        penjelasan: "Kata seruan seperti 'Aduh!', 'Ya Tuhan!', 'Alhamdulillah!' berfungsi mengungkapkan perasaan tokoh secara langsung dan disebut interjeksi.",
      },
      {
        id: 5,
        soal: "Perbedaan utama teks cerita inspiratif dengan cerpen terletak pada...",
        opsi: ["Panjang cerita", "Tujuan dan sumber cerita", "Jumlah tokoh", "Penggunaan majas"],
        jawaban: "1",
        penjelasan: "Cerpen bertujuan menghibur dan bersumber dari fiksi, sedangkan cerita inspiratif bertujuan memotivasi dan bersumber dari kisah nyata atau peristiwa faktual.",
      },
      {
        id: 6,
        tipe: "BENAR_SALAH",
        soal: "Bagian struktur teks cerita inspiratif yang berisi hasil akhir perjuangan dan pesan moral disebut koda.",
        opsi: ["Benar", "Salah"],
        jawaban: 0,
        penjelasan: "Koda adalah bagian penutup yang berisi hasil akhir perjuangan tokoh dan amanat atau pesan moral yang dapat dipetik.",
      },
      {
        id: 7,
        soal: "Nilai yang berkaitan dengan hubungan antarmanusia dan kepedulian sosial dalam cerita inspiratif disebut...",
        opsi: ["Nilai moral", "Nilai sosial", "Nilai spiritual", "Nilai perjuangan"],
        jawaban: 1,
        penjelasan: "Nilai sosial berkaitan dengan hubungan antarmanusia, seperti gotong royong, kepedulian, toleransi, dan solidaritas.",
      },
      {
        id: 8,
        soal: "Cermati kalimat berikut: 'Semangatnya seperti api yang tak kunjung padam.' Kalimat tersebut menggunakan majas...",
        opsi: ["Personifikasi", "Metafora", "Simile", "Hiperbola"],
        jawaban: 2,
        penjelasan: "Kalimat tersebut menggunakan majas simile (perbandingan) yang ditandai dengan kata 'seperti'.",
      },
      {
        id: 9,
        soal: "Yang dimaksud dengan 'titik balik' (turning point) dalam teks cerita inspiratif adalah...",
        opsi: [
          "Akhir dari cerita",
          "Momen ketika tokoh mengambil keputusan penting yang mengubah hidupnya",
          "Bagian yang memperkenalkan tokoh",
          "Pesan moral di akhir cerita",
        ],
        jawaban: 1,
        penjelasan: "Titik balik adalah momen penting ketika tokoh mengambil keputusan atau mengalami peristiwa yang mengubah arah hidupnya secara fundamental.",
      },
      {
        id: 10,
        soal: "Seorang penulis ingin membuat cerita inspiratif tentang seorang anak jalanan yang menjadi pengusaha sukses. Langkah pertama yang harus dilakukan adalah...",
        opsi: [
          "Langsung menulis cerita dari awal hingga akhir",
          "Menentukan tokoh dan tema serta mengumpulkan detail peristiwa",
          "Membuat judul yang menarik terlebih dahulu",
          "Mencari gambar ilustrasi untuk cerita",
        ],
        jawaban: 1,
        penjelasan: "Langkah pertama menulis cerita inspiratif adalah menentukan tokoh dan tema, serta mengumpulkan detail peristiwa tentang perjuangan tokoh tersebut.",
      },
    ],
    praktik: {
      tujuan: "Menulis teks cerita inspiratif tentang tokoh nyata di sekitar dengan struktur dan kaidah kebahasaan yang tepat.",
      instruksi: "Pilihlah satu orang inspiratif di sekitarmu — bisa orang tua, guru, tetangga, atau tokoh masyarakat — yang memiliki kisah perjuangan hidup mengesankan. Tuliskan kisahnya dalam bentuk teks cerita inspiratif dengan struktur yang benar.",
      langkah: [
        "Pilih satu tokoh inspiratif di sekitarmu yang kamu kagumi. Bisa ayah/ibu, kakak, guru, atau tokoh di lingkunganmu.",
        "Lakukan wawancara singkat atau ingat kembali kisah perjuangannya. Catat fakta-fakta penting: latar belakang, tantangan yang dihadapi, momen titik balik, dan pencapaiannya.",
        "Buat kerangka cerita berdasarkan struktur: orientasi → peristiwa → reaksi → koda.",
        "Kembangkan kerangka menjadi cerita utuh. Gunakan sudut pandang orang ketiga (ia/dia).",
        "Terapkan unsur kebahasaan: kata kerja mental, kata seruan, majas perbandingan, konjungsi temporal, dan kalimat langsung.",
        "Berikan detail sensorik (penglihatan, pendengaran, perasaan) agar cerita terasa hidup. Misalnya: 'Matanya berkaca-kaca saat mengenang masa sulit itu.'",
        "Buat judul yang menarik dan mencerminkan inti cerita. Contoh: 'Sang Pejuang Subuh', 'Dari Dapur Kecil Menuju Mimpi Besar'.",
        "Sunting kembali: periksa ejaan, struktur kalimat, dan alur cerita. Pastikan nilai inspiratifnya tersampaikan dengan kuat.",
      ],
      tips: [
        "Pilih tokoh yang kisahnya paling kamu kuasai — semakin detail kamu tahu perjuangannya, semakin kuat cerita yang dihasilkan.",
        "Jangan takut menunjukkan emosi dalam tulisan. Cerita inspiratif justru kuat karena menyentuh perasaan.",
        "Gunakan pembuka yang menarik: kutipan tokoh, pertanyaan retoris, atau gambaran suasana yang menggugah.",
        "Hindari menulis seperti laporan faktual. Cerita inspiratif harus 'bernyawa' — seolah-olah pembaca ikut mengalami peristiwa tersebut.",
        "Minta teman atau gurumu membaca draf pertama dan memberi masukan sebelum versi final.",
      ],
      contoh: "Lihat contoh analisis struktur 'Kisah Seorang Tukang Becak' pada materi Struktur Teks Cerita Inspiratif di atas sebagai panduan menulis.",
    },
    kuis: [
      {
        id: 1,
        soal: "Cermati kutipan berikut: 'Ia merenung lama di bawah pohon rindang itu. Air matanya jatuh tanpa bisa dibendung. Namun, ia segera mengusapnya dan bangkit dengan tekad yang membaja.' Bagian ini termasuk dalam struktur...",
        opsi: ["Orientasi", "Peristiwa", "Reaksi", "Koda"],
        jawaban: 2,
        penjelasan: "Cuplikan tersebut menunjukkan reaksi tokoh terhadap peristiwa yang dialami — ia merenung, menangis, lalu bangkit dengan tekad membaja.",
      },
      {
        id: 2,
        soal: "Perbedaan mendasar teks cerita inspiratif dengan teks biografi adalah...",
        opsi: [
          "Cerita inspiratif lebih panjang dari biografi",
          "Biografi bersifat objektif dan faktual, cerita inspiratif bersifat naratif-subjektif dengan dramatisasi",
          "Biografi menggunakan bahasa kiasan, cerita inspiratif menggunakan bahasa lugas",
          "Cerita inspiratif tidak boleh menggunakan tokoh nyata",
        ],
        jawaban: 1,
        penjelasan: "Biografi bersifat objektif dan faktual berbasis data, sedangkan cerita inspiratif bersifat naratif-subjektif dengan dramatisasi emosional untuk membangkitkan motivasi.",
      },
      {
        id: 3,
        tipe: "BENAR_SALAH",
        soal: "'Lautan masalah menghadangnya' mengandung majas metafora.",
        opsi: ["Benar", "Salah"],
        jawaban: 0,
        penjelasan: "'Lautan masalah' adalah majas metafora — perbandingan langsung tanpa kata pembanding, yang menyamakan masalah dengan lautan yang luas dan dalam.",
      },
      {
        id: 4,
        soal: "Nilai yang paling menonjol dalam kalimat 'Ia bersyukur meskipun hidup dalam kekurangan, karena ia yakin semua adalah rencana Tuhan' adalah nilai...",
        opsi: ["Moral", "Sosial", "Spiritual/Religius", "Perjuangan"],
        jawaban: 2,
        penjelasan: "Nilai spiritual/religius tampak dari sikap bersyukur dan keyakinan kepada rencana Tuhan dalam menghadapi keterbatasan hidup.",
      },
      {
        id: 5,
        soal: "Seorang penulis ingin membuat cerita inspiratif yang kuat. Unsur yang paling penting harus ada agar cerita benar-benar menginspirasi adalah...",
        opsi: [
          "Tokoh terkenal dan kaya raya",
          "Konflik yang ringan dan mudah diselesaikan",
          "Momen titik balik yang mengubah hidup tokoh dan reaksi tokoh yang menggetarkan",
          "Akhir cerita yang bahagia tanpa kekurangan",
        ],
        jawaban: 2,
        penjelasan: "Inti cerita inspiratif adalah momen titik balik ketika tokoh menghadapi kesulitan dan menunjukkan reaksi yang luar biasa. Inilah sumber inspirasi bagi pembaca.",
      },
      {
        id: 6,
        soal: "Cermati penggalan berikut: 'Dulu ia hanyalah pemulung. Kini, ia memiliki pabrik daur ulang yang mempekerjakan lima puluh orang.' Struktur yang tepat untuk penggalan tersebut adalah...",
        opsi: ["Orientasi", "Peristiwa", "Reaksi", "Koda"],
        jawaban: 3,
        penjelasan: "Bagian ini termasuk koda karena menunjukkan hasil akhir dari perjuangan tokoh, dari pemulung menjadi pemilik pabrik — mencerminkan keberhasilan dan pesan inspiratif.",
      },
      {
        id: 7,
        tipe: "BENAR_SALAH",
        soal: "Menggunakan data statistik dan tabel pendukung merupakan ciri dari teks cerita inspiratif.",
        opsi: ["Benar", "Salah"],
        jawaban: 1,
        penjelasan: "Data statistik dan tabel pendukung bukan ciri teks cerita inspiratif. Ciri tersebut justru melekat pada teks nonfiksi atau teks laporan.",
      },
      {
        id: 8,
        tipe: "ISIAN",
        soal: "Kata 'bersyukur', 'terpukul', 'merenung', 'berharap' dalam teks cerita inspiratif termasuk dalam kategori...",
        opsi: "kata kerja mental",
        jawaban: "0",
        penjelasan: "Keempat kata tersebut adalah kata kerja mental (verba mentalis) yang berkaitan dengan aktivitas batin, perasaan, dan pikiran tokoh.",
      },
      {
        id: 9,
        soal: "Nilai yang berkaitan dengan sikap pantang menyerah dan kerja keras dalam cerita inspiratif disebut...",
        opsi: ["Nilai moral", "Nilai sosial", "Nilai perjuangan", "Nilai pendidikan"],
        jawaban: "2",
        penjelasan: "Nilai perjuangan mencakup semangat pantang menyerah, kerja keras, ketekunan, dan kegigihan — nilai yang paling menonjol dalam teks cerita inspiratif.",
      },
      {
        id: 10,
        soal: "Seorang siswa menulis cerita inspiratif tetapi pembaca merasa datar dan tidak tersentuh. Kemungkinan penyebabnya adalah...",
        opsi: [
          "Cerita terlalu pendek",
          "Penulis tidak menghadirkan detail emosi, konflik yang kuat, dan reaksi tokoh yang menggetarkan",
          "Tokoh dalam cerita terlalu terkenal",
          "Judul cerita kurang menarik",
        ],
        jawaban: 1,
        penjelasan: "Cerita inspiratif terasa datar jika penulis tidak menghadirkan detail emosi, konflik yang nyata, dan reaksi tokoh yang menggetarkan hati. Inilah 'nyawa' dari cerita inspiratif.",
      },
    ],
  };

export default konten;
