import type { Konten } from "../types"
import { makeSoal } from "../types"

const konten: Konten = {
  belajar: {
    tujuan: [
      "Membaca suku kata dengan benar",
      "Merangkai suku kata menjadi kata",
      "Membaca kalimat sederhana dengan lancar",
    ],
    materi: [
      {
        judul: "Apa Itu Suku Kata?",
        isi: [
          "Teman-teman, coba bayangkan kata 'BOLA'. Kalau diucapkan, kata ini bisa dipecah menjadi dua bagian: BO dan LA.",
          "",
          "Setiap bagian itu disebut suku kata!",
          "",
          "✓ Suku kata adalah potongan bunyi dalam sebuah kata.",
          "✓ Satu suku kata biasanya terdiri dari satu huruf vokal (bisa ditambah konsonan).",
          "",
          "Contoh suku kata:",
          "1. ba — seperti pada kata BAJU",
          "2. bi — seperti pada kata BIBIR",
          "3. bu — seperti pada kata BUKU",
          "4. ka — seperti pada kata KAKI",
          "5. ma — seperti pada kata MATA",
          "",
          "[Ilustrasi: Sebuah pohon besar dengan ranting-ranting bertuliskan suku kata. Di akar pohon tertulis 'BA', ranting kiri 'JU', 'TU', ranting kanan 'GA', 'SIR'. Buah-buah di pohon bergambar benda seperti baju, buku, mata, kucing, bebek.]",
        ],
        contoh: [
          "Ayo lihat tabel suku kata ini:",
          "",
          "✓ ba — bi — bu — be — bo",
          "✓ ca — ci — cu — ce — co",
          "✓ da — di — du — de — do",
          "✓ ka — ki — ku — ke — ko",
          "✓ ma — mi — mu — me — mo",
          "",
          "Tips: Coba ucapkan suku kata di atas dengan suara nyaring. Rasakan perbedaan bunyi 'ba' dan 'bi'!",
        ],
        catatan: "Suku kata yang paling mudah adalah yang terdiri dari satu konsonan + satu vokal, seperti ba, ci, du, dan sebagainya.",
      },
      {
        judul: "Merangkai Suku Kata Menjadi Kata",
        isi: [
          "Setelah bisa membaca suku kata, sekarang ayo kita rangkai suku kata menjadi kata!",
          "",
          "Caranya mudah: ambil dua suku kata, lalu gabungkan.",
          "",
          "• ba + ju = BAJU",
          "• ka + ki = KAKI",
          "• bu + ku = BUKU",
          "• ma + ta = MATA",
          "• ku + cing = KUCING",
          "",
          "PENTING: Waktu merangkai suku kata, ucapkan dengan cepat. ba-ju... baju!",
          "",
          "[Ilustrasi: Dua balok warna-warni bertuliskan suku kata saling mendekat dan bergabung menjadi satu balok bertuliskan kata utuh. Misalnya balok 'KU' (biru) + balok 'CING' (kuning) menjadi 'KUCING' dengan gambar kucing lucu.]",
        ],
        contoh: [
          "Ayo coba rangkai suku kata berikut:",
          "",
          "1. ka + pu + as = KAPUAS (nama sungai)",
          "2. se + ko + lah = SEKOLAH",
          "3. pe + na + pensil = PENSIL (perhatikan: pe-na-pensil, ada suku 3 huruf!)",
          "4. bu + ru + ng = BURUNG",
          "5. pe + la + ngi = PELANGI",
        ],
      },
      {
        judul: "Membaca Kalimat Sederhana",
        isi: [
          "Sekarang kamu sudah siap membaca kalimat! Kalimat adalah kumpulan kata yang utuh.",
          "",
          "Ayo baca kalimat-kalimat berikut:",
          "",
          "1. Ini buku Budi.",
          "2. Ibu membeli baju.",
          "3. Adik minum susu.",
          "4. Kucing makan ikan.",
          "5. Ayah pergi ke kantor.",
          "",
          "• Awali membaca dengan tenang.",
          "• Baca kata per kata dengan jelas.",
          "• Pilih suara yang cukup keras.",
          "",
          "[Ilustrasi: Seorang anak duduk di meja belajar, membaca buku dengan jari menunjuk ke arah kata-kata. Di sekelilingnya ada gambar-gambar lucu yang sesuai dengan kalimat yang dibaca — gambar buku, bola, kucing, dan bunga.]",
        ],
        contoh: [
          "Tips membaca kalimat:",
          "",
          "1. Lihat kata pertama, baca dengan perlahan",
          "2. Lanjut ke kata berikutnya",
          "3. Setelah selesai satu kalimat, ambil napas",
          "4. Ulangi sekali lagi agar lancar",
          "",
          "BENAR: \"I-ni bu-ku Bu-di.\" (dipotong per suku kata, lalu dirangkai)",
          "✓ Setelah lancar: \"Ini buku Budi.\" (satu kalimat utuh)",
        ],
      },
    ],
    rangkuman: [
      "[Ilustrasi: Seorang anak tersenyum bangga sambil memegang buku bertuliskan 'AKU BISA MEMBACA'. Di sekelilingnya ada huruf-huruf dan suku kata seperti bintang-bintang kecil.]",
      "Suku kata adalah potongan bunyi dalam sebuah kata. Contoh: ba, ju, ka, ki.",
      "Gabungkan dua atau lebih suku kata untuk membentuk kata: ba+ju = baju, bu+ku = buku.",
      "Kalimat adalah kumpulan kata yang utuh dan punya arti.",
      "Tips membaca: baca suku kata per suku kata, lalu rangkai jadi kata utuh.",
    ],
  },
  latihan: makeSoal([
    ["Gabungan ba + ju = ...", ["baju", "baja", "biji", "bahu"], 0, "ba + ju = baju."],
    ["Gabungan ka + ki = ...", ["kaki", "kakek", "kaku", "kata"], 0, "ka + ki = kaki."],
    ["Gabungan bu + ku = ...", ["buku", "buka", "bumi", "buah"], 0, "bu + ku = buku."],
    ["Berapa suku kata dalam kata 'SEKOLAH'?", ["2", "3", "4", "5"], 1, "SE-KO-LAH = 3 suku kata."],
    ["Bacalah: 'Adik minum susu.' Kalimat ini memberitahu...", ["Adik bermain", "Adik minum susu", "Adik tidur", "Adik makan"], 1, "Kalimat 'Adik minum susu' menceritakan kegiatan adik."],
    ["Suku kata 'bi' ditemukan dalam kata...", ["babi", "batu", "bola", "buku"], 0, "Kata BABI = ba-bi, jadi suku kata 'bi' ada di situ."],
    ["Kata 'MATA' terdiri dari suku kata...", ["ma - ta", "mat - a", "m - ata", "ma - at"], 0, "MATA = ma + ta."],
    ["Satu suku kata biasanya memiliki minimal...", ["Satu konsonan", "Satu vokal", "Dua vokal", "Tiga huruf"], 1, "Setiap suku kata minimal memiliki satu huruf vokal."],
    ["Kata berikut yang terdiri dari 3 suku kata adalah...", ["Bola", "Kucing", "Budi", "Buku"], 1, "Ku-cing = 3 suku kata."],
    ["Kalimat 'Ibu pergi ke pasar' menceritakan tentang...", ["Ayah pergi", "Ibu pergi ke pasar", "Adik belajar", "Kakak bermain"], 1, "Kalimat tersebut menceritakan ibu pergi ke pasar."],
  ]),
  praktik: {
    petunjuk: "Bacalah kalimat berikut dengan suara nyaring, lalu tulis ulang di buku tulismu: 'Siti suka membaca buku. Setiap hari ia membaca cerita. Buku cerita Siti sangat banyak.'",
    tips: [
      "Tunjuk setiap kata dengan jarimu saat membaca",
      "Baca perlahan dulu, lalu ulangi lebih cepat",
      "Mintalah orang tuamu mendengarkan saat kamu membaca",
      "Setelah lancar, coba baca tanpa menunjuk kata",
    ],
    contoh: "Kalimat: 'Kucingku lucu sekali.' Bacaan yang benar: 'Ku-cing-ku lu-cu se-ka-li.' Setelah lancar: 'Kucingku lucu sekali.'",
  },
  kuis: makeSoal([
    ["Gabungan ma + ta = ...", ["mata", "mati", "madu", "mama"], 0, "ma + ta = mata."],
    ["Gabungan ku + cing = ...", ["kucing", "kacang", "kacamata", "kucuran"], 0, "ku + cing = kucing."],
    ["Berapa suku kata dalam kata 'BURUNG'?", ["1", "2", "3", "4"], 1, "Bu-rung = 2 suku kata."],
    ["Suku kata 'la' ditemukan dalam kata...", ["bola", "batu", "kaki", "buku"], 0, "Kata BOLA = bo-la, jadi ada suku kata 'la'."],
    ["Kata 'PELANGI' terdiri dari suku kata...", ["pe - la - ngi", "pel - angi", "pe - langi", "pela - ngi"], 0, "Pe-la-ngi = 3 suku kata."],
    ["Kalimat dimulai dengan huruf...", ["Kecil", "Kapital", "Tebal", "Miring"], 1, "Setiap kalimat dimulai dengan huruf kapital."],
    ["Kata 'SEPATU' terdiri dari... suku kata", ["2", "3", "4", "5"], 1, "Se-pa-tu = 3 suku kata."],
    ["Bacalah: 'Ayah membaca koran.' Siapa yang membaca koran?", ["Ibu", "Ayah", "Adik", "Kakak"], 1, "Kalimat tersebut menyatakan Ayah yang membaca koran."],
    ["Gabungan sa + pu = ...", ["sapu", "sapi", "sate", "saku"], 0, "sa + pu = sapu."],
    ["Kata 'BEBEK' terdiri dari...?", ["be - bek", "be - be - k", "be - bek (tanpa k)", "b - e - b - e - k"], 0, "Be-bek = 2 suku kata."],
  ]),
}

export default konten
