import type { Konten } from "../types"
import { makeSoal } from "../types"

const konten: Konten = {
  belajar: {
    tujuan: [
      "Mengenal puisi sebagai ungkapan perasaan dengan kata indah",
      "Memahami rima dalam puisi",
      "Membaca puisi dengan ekspresi yang tepat",
      "Menulis puisi sederhana 4 baris",
    ],
    materi: [
      {
        judul: "Apa Itu Puisi?",
        isi: [
          "Pernahkah kamu merasa senang lalu mengucapkan 'Indah sekali hari ini' dengan nada yang berbeda? Itu sudah seperti puisi!",
          "",
          "✓ Puisi adalah ungkapan perasaan yang ditulis dengan kata-kata indah.",
          "✓ Puisi tidak perlu panjang — bisa 2 baris, 4 baris, atau lebih.",
          "✓ Puisi kadang punya bunyi yang sama di akhir baris (rima).",
          "",
          "Contoh puisi pendek:",
          "",
          "\"Ibu\"",
          "Ibu, engkaulah pelitaku",
          "Terangi malam yang gelap gulita",
          "Ibu, engkaulah bintangku",
          "Bersinar di setiap masa",
          "",
          "[Ilustrasi: Selembar kertas bergaris dengan puisi ditulis tangan rapi. Di sampingnya ada gambar seorang ibu tersenyum memeluk anaknya. Jantung-jantung kecil berterbangan di sekitar mereka.]",
        ],
        contoh: [
          "Ciri-ciri puisi:",
          "",
          "1. Menggunakan kata-kata indah",
          "2. Mengungkapkan perasaan penyair",
          "3. Kadang punya rima (bunyi yang sama)",
          "4. Tidak perlu panjang",
          "",
          "BENAR (puisi): 'Pelangi / Warnamu indah sekali / Menghias langit / Kau buatku tersenyum'",
          "✓ Ada perasaan, ada kata indah, ada rima.",
        ],
        catatan: "Puisi tidak harus selalu berima. Yang terpenting adalah ungkapan perasaan yang tulus!",
      },
      {
        judul: "Rima dalam Puisi",
        isi: [
          "Rima adalah bunyi yang sama di akhir baris puisi. Rima membuat puisi terdengar indah.",
          "",
          "Jenis rima:",
          "1. RIMA AKHIR: bunyi sama di akhir baris.",
          "2. RIMA AWAL: bunyi sama di awal baris (jarang).",
          "",
          "Contoh rima akhir (a-b-a-b):",
          "\"Bunga di taman\" (a)",
          "\"Mekar berseri\" (b)",
          "\"Hatiku senang\" (a)",
          "\"Melihatnya setiap hari\" (b)",
          "",
          "[Ilustrasi: Dua baris puisi bergarisbawah dengan warna berbeda — baris 1 dan 3 bergaris bawah merah (rima a), baris 2 dan 4 bergaris bawah biru (rima b). Di sampingnya ada gambar orang bernyanyi dengan not balok.]",
        ],
        contoh: [
          "Ayo cari rima dalam puisi ini:",
          "",
          "'Kupu-kupu yang lucu' (u)",
          "'Terbang ke sana kemari' (i)",
          "'Hinggap di bungaku' (u)",
          "'Sungguh indah sekali' (i)",
          "",
          "✓ Rima akhir: u - i - u - i (pola a-b-a-b)",
          "Tips: Semakin sering membaca puisi, semakin terbiasa dengan rima!",
        ],
      },
      {
        judul: "Menulis Puisi Sederhana",
        isi: [
          "Sekarang giliranmu menulis puisi!",
          "",
          "Langkah-langkah menulis puisi:",
          "",
          "1. Tentukan tema (misalnya: ibu, kucing, hujan, buku)",
          "2. Tulis perasaanmu tentang tema itu",
          "3. Gunakan kata-kata yang indah",
          "4. Buat 4 baris dengan rima a-b-a-b",
          "",
          "Contoh: tema = HUJAN",
          "",
          "\"Hujan\"",
          "Rintik hujan turun membasahi bumi",
          "Tanaman bergembira menyambut datangmu",
          "Suaranya merdu bagai simfoni",
          "Hujan, kau buat hatiku tenang dan rindu",
          "",
          "[Ilustrasi: Seorang anak duduk di dekat jendela, memandang hujan di luar sambil menulis di buku. Tampak dari jendela: hujan, pohon basah, dan langit kelabu. Di buku tulis anak itu tertulis bait puisi.]",
        ],
        contoh: [
          "Perbandingan: bukan puisi vs puisi",
          "",
          "✗ BUKAN PUISI: 'Aku suka kucingku. Dia lucu. Dia suka bermain.' (kalimat biasa)",
          "✓ PUISI: 'Kucingku yang manis / Bulumu lembut dan halus / Kau teman setia / Bermain bersamaku tak pernah bosan'",
          "",
          "Tips: Bait puisi tidak harus berima sempurna. Yang penting adalah perasaan!",
        ],
      },
    ],
    rangkuman: [
      "[Ilustrasi: Papan pengumuman berbentuk buku besar yang bertuliskan 'PUISI' dengan huruf warna-warni. Di sekelilingnya ada kertas-kertas kecil berisi puisi karya anak-anak dengan gambar lucu.]",
      "Puisi adalah ungkapan perasaan dengan kata-kata indah.",
      "Rima adalah bunyi yang sama di akhir baris puisi.",
      "Puisi bisa ditulis dengan 4 baris dengan pola rima a-b-a-b.",
      "Menulis puisi dimulai dari menentukan tema dan mengungkapkan perasaan.",
    ],
  },
  latihan: makeSoal([
    ["Puisi adalah...", ["Cerita panjang", "Ungkapan perasaan dengan kata indah", "Laporan", "Pengumuman"], 1, "Puisi adalah ungkapan perasaan dengan kata indah."],
    ["Rima adalah...", ["Judul puisi", "Bunyi sama di akhir baris", "Panjang baris", "Kata pertama"], 1, "Rima adalah bunyi yang sama atau mirip di akhir baris."],
    ["Puisi anak biasanya bersifat...", ["Sulit", "Sederhana dan penuh perasaan", "Panjang", "Ilmiah"], 1, "Puisi anak sederhana dan mengungkapkan perasaan."],
    ["Yang termasuk puisi adalah...", ["Ibu memasak di dapur", "Ibu, kau bagai mentari / Terangi hidupku setiap hari", "Ibu pergi ke pasar", "Ibu membeli sayur"], 1, "Kalimat kedua adalah puisi karena ada rima dan kata indah."],
    ["Rima a-b-a-b artinya...", ["Semua baris sama", "Baris 1 dan 3 sama, 2 dan 4 sama", "Baris 1 dan 2 sama", "Tidak berima"], 1, "Rima a-b-a-b: baris 1 dan 3 berima (a), baris 2 dan 4 berima (b)."],
    ["Puisi biasanya ditulis dalam bentuk...", ["Paragraf panjang", "Baris-baris pendek", "Tabel", "Angka"], 1, "Puisi ditulis dalam baris-baris pendek yang disebut bait."],
    ["Satu bait puisi biasanya terdiri dari... baris", ["2", "4", "6", "Bebas"], 3, "Satu bait bisa 2, 4, atau berapa pun. Yang penting adalah ekspresi perasaan."],
    ["'Bunga mawar merah / Aku suka sekali' — puisi ini memiliki rima...", ["Sama", "Tidak sama", "Indah", "Panjang"], 1, "'Merah' dan 'sekali' tidak memiliki bunyi akhir yang sama."],
    ["Kata 'bagaikan' dalam puisi berarti...", ["Sama dengan", "Seperti", "Berbeda", "Bersama"], 1, "'Bagaikan' berarti 'seperti' — sering digunakan dalam puisi."],
    ["Tujuan menulis puisi adalah...", ["Melaporkan kejadian", "Mengungkapkan perasaan", "Memberi petunjuk", "Menjelaskan cara"], 1, "Puisi bertujuan mengungkapkan perasaan penyair."],
  ]),
  praktik: {
    petunjuk: "Buatlah sebuah puisi 4 baris dengan tema 'BINATANG KESAYANGANKU'! Gunakan kata-kata indah dan usahakan punya rima.",
    tips: [
      "Bayangkan binatang kesayanganmu: bagaimana rupanya? tingkahnya?",
      "Tulis perasaanmu tentang binatang itu (senang, lucu, gemas)",
      "Coba buat baris 1 dan 3 berima, baris 2 dan 4 berima",
      "Baca puisi dengan keras — jika terdengar indah, berarti puisi kamu bagus!",
    ],
    contoh: "Kucingku (tema). Puisi: 'Kucingku bernama Mimi / Bulumu putih bersih / Kau suka tidur di sini / Bermain bersamamu membuatku tersih.'",
  },
  kuis: makeSoal([
    ["Puisi untuk anak sebaiknya...", ["Sulit dipahami", "Sederhana dan ceria", "Panjang", "Serius"], 1, "Puisi untuk anak bersifat sederhana dan ceria."],
    ["Apa yang dimaksud dengan bait?", ["Baris dalam puisi", "Kumpulan baris dalam puisi", "Kata dalam puisi", "Judul puisi"], 1, "Bait adalah kumpulan baris dalam puisi."],
    ["Mana rima pada kata 'pagi' dan 'mandi'?", ["Sama", "Tidak sama", "Mirip", "Hampir sama"], 1, "Pagi (a) dan mandi (i) — tidak sama bunyi akhirnya."],
    ["Puisi 'Ibu' bertema tentang...", ["Ayah", "Kasih sayang ibu", "Sekolah", "Teman"], 1, "Puisi 'Ibu' bertema tentang kasih sayang seorang ibu."],
    ["Kata-kata yang sering ada dalam puisi adalah...", ["Pertama, kedua", "Indah, bagaikan, rindu", "Meja, kursi", "Makan, minum"], 1, "Puisi menggunakan kata-kata indah seperti 'indah', 'bagaikan', 'rindu'."],
    ["'Mentari' artinya...", ["Bulan", "Matahari", "Bintang", "Awan"], 1, "'Mentari' artinya matahari — sering dipakai dalam puisi."],
    ["Puisi 'Pelangi' bisa bertema tentang...", ["Kendaraan", "Keindahan alam", "Makanan", "Pekerjaan"], 1, "Pelangi adalah keindahan alam, tema yang cocok untuk puisi."],
    ["Apakah semua puisi harus memiliki rima?", ["Ya, harus", "Tidak, tidak harus", "Hari libur", "Puisi panjang"], 1, "Puisi tidak harus selalu berima. Ekspresi perasaan lebih utama."],
    ["Berapa baris minimal sebuah puisi?", ["2 baris", "4 baris", "Tidak ada aturan", "8 baris"], 2, "Puisi bisa 1 baris, 2 baris, atau lebih. Tidak ada aturan baku."],
    ["Membaca puisi sebaiknya dengan...", ["Diam saja", "Ekspresi dan intonasi", "Cepat", "Berbisik"], 1, "Puisi dibaca dengan ekspresi dan intonasi agar terasa indahnya."],
  ]),
}

export default konten
