import type { Konten } from "../types"
import { makeSoal } from "../types"

const konten: Konten = {
  belajar: {
    tujuan: [
      "Memegang pensil dengan cara yang benar",
      "Menebalkan garis putus-putus menjadi huruf",
      "Menulis kata dan kalimat sederhana",
    ],
    materi: [
      {
        judul: "Cara Memegang Pensil",
        isi: [
          "Sebelum menulis, kamu harus tahu cara memegang pensil yang benar!",
          "",
          "✓ Pegang pensil dengan tiga jari: ibu jari, telunjuk, dan jari tengah.",
          "✓ Jari manis dan kelingking ditekuk ke dalam.",
          "✓ Posisi duduk tegak, jangan membungkuk.",
          "✓ Jarak mata ke buku sekitar 30 cm.",
          "",
          "PENTING: Pegang pensil dengan rileks, jangan terlalu kuat mencekak!",
          "",
          "[Ilustrasi: Tangan anak yang sedang memegang pensil dengan posisi benar — tiga jari (ibu jari, telunjuk, tengah) memegang pensil, dua jari lainnya ditekuk. Ada tanda centang hijau. Di sebelahnya, tangan dengan posisi salah — menggenggam erat — dengan tanda silang merah.]",
        ],
        contoh: [
          "Periksa posisi dudukmu:",
          "",
          "✓ Duduk tegak seperti pohon pinus",
          "✓ Kaki menapak rata di lantai",
          "✓ Buku miring sedikit ke kanan (jika kamu kidal, miring ke kiri)",
          "✓ Pensil dipegang 2-3 cm dari ujung runcing",
          "",
          "Tips: Bayangkan ada tali dari ubun-ubunmu yang menarikmu ke atas. Itu posisi duduk yang benar!",
        ],
        catatan: "Jika kamu kidal, pegang pensil dengan tangan kiri. Buku dimiringkan ke kiri. Tidak apa-apa! Banyak orang hebat yang kidal.",
      },
      {
        judul: "Menebalkan Garis Putus-putus",
        isi: [
          "Ayo berlatih menulis huruf! Pertama, kita akan menebalkan garis putus-putus.",
          "",
          "1. Siapkan buku tulis dan pensil.",
          "2. Ikuti garis putus-putus dengan pensil.",
          "3. Gerakkan tangan perlahan dari kiri ke kanan.",
          "4. Usahakan garisnya rapi dan tidak keluar jalur.",
          "",
          "• Menebalkan garis melatih otot tanganmu.",
          "• Semakin sering berlatih, tulisanku semakin rapi!",
          "",
          "[Ilustrasi: Garis putus-putus membentuk huruf A besar dan kecil, dengan panah petunjuk arah menulis. Seorang anak sedang menelusuri garis putus-putus dengan pensil warna. Di bawahnya sudah ada hasil tulisan rapi.]",
        ],
        contoh: [
          "Ayo tiru bentuk-bentuk ini:",
          "",
          "GARIS LURUS: _ _ _ _ _ (buat garis lurus dari kiri ke kanan)",
          "GARIS LENGKUNG: ~~ ~~ ~~ (buat garis lengkung seperti ombak)",
          "GARIS LINGKARAN: O O O O (buat lingkaran kecil-kecil)",
          "",
          "Tips: Latihan membuat garis membantu tanganmu terbiasa!",
        ],
      },
      {
        judul: "Menulis Kata dan Kalimat",
        isi: [
          "Setelah lancar menebalkan, saatnya menulis sendiri!",
          "",
          "Mulailah dengan menulis namamu:",
          "",
          "1. Tulis huruf pertama dengan huruf KAPITAL (besar).",
          "2. Huruf selanjutnya ditulis dengan huruf kecil.",
          "3. Contoh: B u d i (B-nya besar, u-d-i kecil).",
          "",
          "✓ Setelah bisa menulis nama, coba tulis kata-kata lain:",
          "  ibu, ayah, adik, kakak",
          "  buku, pensil, meja, kursi",
          "",
          "[Ilustrasi: Selembar kertas bergaris dengan contoh tulisan tangan anak yang rapi. Ada kata 'Budi', 'Ibu', 'Ayah', 'Buku', dan 'Sekolah'. Setiap kata ditulis dengan huruf kapital di awal dan huruf kecil selanjutnya.]",
        ],
        contoh: [
          "Ayo tulis kalimat:",
          "",
          "1. Ini buku. (I = huruf kapital, titik di akhir)",
          "2. Itu meja. (diawali huruf kapital, diakhiri titik)",
          "3. Budi minum susu. (B = kapital, titik di akhir)",
          "",
          "Ingat aturan menulis kalimat:",
          "✓ Awali dengan huruf kapital",
          "✓ Akhiri dengan tanda titik",
          "✓ Beri jarak antar kata",
        ],
      },
    ],
    rangkuman: [
      "[Ilustrasi: Tangan anak menulis di buku bergaris dengan pensil. Hasil tulisannya rapi dan jelas terbaca. Di pojok buku bertuliskan 'KARYAKU'.]",
      "Pegang pensil dengan tiga jari (ibu jari, telunjuk, tengah) dan duduk tegak.",
      "Berlatih menebalkan garis putus-putus melatih otot tangan untuk menulis.",
      "Tulis nama dengan huruf kapital di awal, lalu huruf kecil.",
      "Aturan kalimat: huruf kapital di awal + kata + spasi antar kata + titik di akhir.",
    ],
  },
  latihan: makeSoal([
    ["Pegang pensil dengan...", ["Lima jari", "Tiga jari", "Dua jari", "Satu jari"], 1, "Pegang pensil dengan tiga jari: ibu jari, telunjuk, dan jari tengah."],
    ["Posisi duduk saat menulis sebaiknya...", ["Tiduran", "Tegak", "Miring", "Membungkuk"], 1, "Duduk tegak agar tulisan rapi dan punggung tidak sakit."],
    ["Huruf pertama pada nama orang ditulis dengan huruf...", ["Kecil", "Kapital", "Tebal", "Miring"], 1, "Huruf pertama nama orang adalah huruf kapital."],
    ["Kalimat 'adik tidur' penulisan yang benar adalah...", ["adik tidur", "Adik tidur", "Adik tidur.", "ADIK TIDUR"], 2, "Penulisan benar: diawali kapital dan diakhiri titik."],
    ["Jarak mata ke buku saat menulis sekitar...", ["10 cm", "20 cm", "30 cm", "50 cm"], 2, "Jarak yang baik adalah sekitar 30 cm dari buku."],
    ["Latihan menebalkan garis berguna untuk...", ["Menghias buku", "Melatih otot tangan", ["Menggambar"], "Mewarnai"], 1, "Menebalkan garis melatih otot tangan agar terbiasa menulis."],
    ["Jika kamu kidal, pegang pensil dengan tangan...", ["Kiri", "Kanan", ["Kiri dan kanan"], "Bergantian"], 0, "Jika kidal, gunakan tangan kiri untuk memegang pensil."],
    ["Menulis kalimat diawali dengan huruf...", ["Tebal", "Kapital", ["Biasa"], "Miring"], 1, "Setiap kalimat dimulai dengan huruf kapital."],
    ["Kata berikut yang ditulis dengan benar adalah...", ["bUku", "Buku", "buku", "BUKU"], 1, "Buku ditulis dengan huruf kapital B, lalu huruf kecil u-k-u."],
    ["Akhir kalimat berita diberi tanda...", ["Tanya", "Titik", ["Seru"], "Koma"], 1, "Kalimat berita diakhiri dengan tanda titik (.)."],
  ]),
  praktik: {
    petunjuk: "Tulislah namamu sendiri di buku tulis sebanyak 5 baris dengan rapi. Baris pertama: huruf kapital semua. Baris kedua: huruf kapital di awal saja. Baris ketiga sampai kelima: ulangi dengan rapi.",
    tips: [
      "Lihat contoh tulisan guru atau orang tuamu",
      "Tulis perlahan, jangan terburu-buru",
      "Gunakan pensil yang sudah diraut dengan baik",
      "Kalau salah, hapus dengan penghapus yang bersih",
    ],
    contoh: "Nama: SITI. Baris 1: S-I-T-I. Baris 2: Siti. Baris 3-5: Siti Siti Siti (tulisan yang rapi).",
  },
  kuis: makeSoal([
    ["Pegang pensil terlalu kuat akan membuat...", ["Tulisan rapi", "Tangan cepat lelah", ["Pensil patah"], "Tulisan tebal"], 1, "Memegang pensil terlalu kuat membuat tangan lelah dan tulisan tidak rapi."],
    ["Apa yang dilakukan sebelum menulis huruf?", ["Langsung menulis", "Menebalkan garis putus-putus", ["Menggambar"], "Mewarnai"], 1, "Latihan menebalkan garis membantu tangan terbiasa."],
    ["Huruf kapital A berbeda dengan huruf...", ["Konsonan", "Kecil a", ["Angka"], "Vokal"], 1, "Huruf kapital A dan huruf kecil a bentuknya berbeda."],
    ["Penulisan yang benar: 'Ibu memasak'", ["ibu memasak", "Ibu memasak.", "Ibu memasak", "ibu Memasak"], 1, "Penulisan benar: Ibu memasak. dengan I kapital dan titik."],
    ["Berapa jari yang digunakan untuk memegang pensil?", ["2", "3", "4", "5"], 1, "Tiga jari: ibu jari, telunjuk, dan jari tengah."],
    ["Latihan menulis sebaiknya dimulai dari...", ["Kalimat panjang", "Huruf dan kata sederhana", ["Cerita"], "Puisi"], 1, "Mulailah dari huruf, lalu kata sederhana, baru kalimat."],
    ["Jika menulis dengan tangan kanan, buku dimiringkan ke...", ["Kiri", "Kanan", "Depan", "Belakang"], 1, "Buku dimiringkan sedikit ke kanan."],
    ["Tanda titik (.) diletakkan di...", ["Awal kalimat", "Akhir kalimat", ["Tengah kalimat"], "Setiap kata"], 1, "Tanda titik diletakkan di akhir kalimat berita."],
    ["'Budi' ditulis dengan...", ["b kapital, udi kecil", "B kapital, udi kecil", ["semua besar"], "semua kecil"], 1, "Budi = B (kapital) + udi (huruf kecil)."],
    ["Supaya tulisan rapi, kita harus...", ["Cepat-cepat", "Berlatih setiap hari", ["Tidak perlu latihan"], "Menyontek"], 1, "Semakin sering berlatih, tulisan semakin rapi."],
  ]),
}

export default konten
