import type { Konten } from "../types"
import { makeSoal } from "../types"

const konten: Konten = {
  belajar: {
    tujuan: [
      "Menulis cerita dengan urutan awal, tengah, dan akhir",
      "Mengembangkan ide cerita dari pengalaman sehari-hari",
      "Menggunakan kosa kata yang tepat dalam cerita",
    ],
    materi: [
      {
        judul: "Awal Cerita — Perkenalan",
        isi: [
          "Setiap cerita punya bagian awal, tengah, dan akhir. Mari belajar menulis cerita!",
          "",
          "AWAL CERITA berisi pengenalan:",
          "• Siapa tokohnya?",
          "• Di mana tempatnya?",
          "• Kapan kejadiannya?",
          "",
          "Contoh awal cerita:",
          "\"Pada hari Minggu, Budi pergi ke taman bersama ayah.\" — Di sini kita tahu siapa (Budi dan ayah), di mana (taman), kapan (hari Minggu).",
          "",
          "[Ilustrasi: Sebuah buku terbuka dengan halaman pertama bertuliskan 'AWAL CERITA'. Dari buku itu keluar gambar-gambar kecil — seorang anak, taman, matahari — mewakili tokoh, tempat, dan waktu.]",
        ],
        contoh: [
          "Mana awal cerita yang lebih menarik?",
          "",
          "✗ 'Aku bangun tidur.' (kurang menarik)",
          "✓ 'Matahari pagi bersinar cerah ketika Budi bangun tidur. Hari itu ia akan pergi ke kebun binatang pertama kalinya!' (lebih menarik)",
          "",
          "Tips: Gunakan kata-kata yang membuat pembaca penasaran!",
        ],
      },
      {
        judul: "Tengah Cerita — Kejadian Seru",
        isi: [
          "Bagian tengah cerita adalah inti dari cerita. Di sinilah hal seru terjadi!",
          "",
          "TENGAH CERITA berisi:",
          "• Kejadian atau masalah (konflik)",
          "• Tokoh melakukan sesuatu",
          "• Peristiwa menarik yang membuat cerita tidak membosankan",
          "",
          "Contoh tengah cerita:",
          "\"Di kebun binatang, Budi melihat seekor monyet yang lucu. Monyet itu mengambil topi Budi dan memakainya! Semua orang tertawa.\"",
          "",
          "[Ilustrasi: Halaman tengah buku terbuka dengan gambar seorang anak mengejar monyet yang membawa topi. Di latar belakang terlihat kandang-kandang hewan. Gaya ilustrasi kartun lucu dan penuh gerakan.]",
        ],
        contoh: [
          "Bandingkan cerita yang biasa vs seru:",
          "",
          "✗ 'Budi bermain di taman.' (biasa saja)",
          "✓ 'Budi bermain ayunan di taman. Tiba-tiba, ia melihat seekor burung kecil jatuh dari sarang! Budi segera menolongnya.' (ada kejadian seru)",
          "",
          "PENTING: Bagian tengah adalah bagian paling menarik dalam cerita. Buatlah pembaca penasaran!",
        ],
      },
      {
        judul: "Akhir Cerita — Penyelesaian",
        isi: [
          "Setiap cerita harus punya akhir. Bagian akhir menutup cerita dengan rapi.",
          "",
          "AKHIR CERITA berisi:",
          "• Penyelesaian dari masalah yang terjadi",
          "• Perasaan tokoh di akhir cerita",
          "• Pesan atau kesimpulan",
          "",
          "Contoh akhir cerita:",
          "\"Budi mengembalikan topinya. Ia sangat senang karena hari itu penuh petualangan seru. Ia pulang sambil tersenyum dan bercerita pada ibu.\"",
          "",
          "[Ilustrasi: Halaman terakhir buku cerita dengan gambar anak tersenyum pulang bersama ayah, matahari terbenam di belakang. Ada tulisan 'TAMAT' di pojok kanan bawah.]",
        ],
        contoh: [
          "Akhir cerita yang baik:",
          "",
          "1. Menyelesaikan semua masalah",
          "2. Memberi perasaan puas pada pembaca",
          "3. Bisa berisi pesan moral",
          "",
          "BENAR: 'Akhirnya, Budi pulang dengan hati gembira. Ia belajar bahwa menolong itu menyenangkan.'",
          "✓ Akhir yang bahagia dan bermakna.",
          "",
          "SALAH: '…dan kemudian Budi bangun. Ternyata itu hanya mimpi.' (akhir yang mengecewakan — seperti tidak selesai)",
        ],
      },
    ],
    rangkuman: [
      "[Ilustrasi: Sebuah papan tulis kecil berbentuk buku dengan tiga bagian yang jelas: AWAL (gambar pengenalan), TENGAH (gambar petualangan), AKHIR (gambar penyelesaian). Di bawahnya tertulis 'CERPENKU' dengan bintang-bintang.]",
      "Awal cerita: perkenalan tokoh, tempat, dan waktu.",
      "Tengah cerita: kejadian seru atau masalah (konflik).",
      "Akhir cerita: penyelesaian dan pesan moral.",
      "Gunakan kata-kata menarik agar pembaca tidak bosan!",
    ],
  },
  latihan: makeSoal([
    ["Bagian awal cerita berisi tentang...", ["Masalah", "Pengenalan tokoh dan tempat", "Penyelesaian", "Pesan moral"], 1, "Awal cerita memperkenalkan tokoh, tempat, dan waktu."],
    ["Bagian paling seru dalam cerita ada di...", ["Awal", "Tengah", "Akhir", "Sampul"], 1, "Bagian tengah berisi kejadian seru atau konflik."],
    ["Konflik adalah...", ["Pengenalan tokoh", "Masalah dalam cerita", "Akhir cerita", "Judul cerita"], 1, "Konflik adalah masalah yang terjadi di tengah cerita."],
    ["Akhir cerita sebaiknya berisi...", ["Konflik baru", "Penyelesaian", "Pengenalan", "Tokoh baru"], 1, "Akhir cerita adalah penyelesaian dari semua masalah."],
    ["Cerita yang baik harus punya...", ["Awal saja", "Awal, tengah, akhir", "Tengah saja", "Akhir saja"], 1, "Cerita yang lengkap punya awal, tengah, dan akhir."],
    ["'Pada suatu hari...' adalah contoh kalimat...", ["Akhir", "Awal cerita", "Tengah", "Judul"], 1, "'Pada suatu hari' adalah pembuka yang umum untuk awal cerita."],
    ["Pesan moral sebaiknya ada di bagian...", ["Awal", "Tengah", "Akhir", "Semua bagian"], 2, "Pesan moral biasanya disampaikan di akhir cerita."],
    ["Mana yang termasuk tengah cerita?", ["Perkenalan tokoh", "Kejadian seru", "Penutup", "Judul"], 1, "Kejadian seru atau konflik adalah bagian tengah cerita."],
    ["Agar cerita menarik, gunakan...", ["Kata yang itu-itu saja", "Kata-kata yang bervariasi", " Kata panjang", "Kata sulit"], 1, "Gunakan kosa kata yang bervariasi agar cerita tidak membosankan."],
    ["Cerita yang tidak punya akhir disebut...", ["Cerita pendek", "Cerita tidak selesai", "Dongeng", "Fabel"], 1, "Cerita tanpa akhir membuat pembaca bingung."],
  ]),
  praktik: {
    petunjuk: "Tulis sebuah cerita pendek tentang pengalaman liburanmu! Gunakan 3-5 kalimat dengan struktur: Awal (perkenalan), Tengah (kejadian seru), Akhir (penyelesaian).",
    tips: [
      "Tentukan dulu temanya: liburan ke mana? Dengan siapa?",
      "Tulis 1-2 kalimat untuk bagian awal",
      "Tulis 1-2 kalimat untuk bagian tengah (kejadian seru)",
      "Tulis 1 kalimat untuk bagian akhir (kesimpulan)",
      "Jangan lupa huruf kapital dan tanda titik!",
    ],
    contoh: "AWAL: Pada liburan sekolah, aku pergi ke rumah nenek di desa. TENGAH: Di sana, aku membantu nenek memberi makan ayam. Tiba-tiba, seekor ayam jago mengejarku! Aku lari sambil tertawa. AKHIR: Nenek tersenyum melihatku. Aku senang bisa membantu nenek.",
  },
  kuis: makeSoal([
    ["Struktur cerita yang benar adalah...", ["Awal - akhir - tengah", "Awal - tengah - akhir", "Tengah - awal - akhir", "Akhir - tengah - awal"], 1, "Urutan cerita: Awal → Tengah → Akhir."],
    ["Bagian yang memperkenalkan tokoh adalah...", ["Awal", "Tengah", "Akhir", "Judul"], 0, "Awal cerita memperkenalkan tokoh dan tempat."],
    ["Konflik atau masalah terletak di bagian...", ["Awal", "Tengah", "Akhir", "Sampul"], 1, "Konflik adalah bagian tengah cerita."],
    ["Akhir cerita berfungsi untuk...", ["Memulai cerita", "Menyelesaikan cerita", "Membuat bingung", "Memperkenalkan"], 1, "Akhir cerita menutup dan menyelesaikan semua masalah."],
    ["Judul cerita sebaiknya...", ["Panjang", "Menarik dan sesuai isi", "Acak", "Sulit"], 1, "Judul yang baik menarik perhatian dan sesuai isi cerita."],
    ["Apa yang membuat cerita menarik?", ["Tidak ada konflik", "Ada konflik dan penyelesaian", "Satu tokoh", "Tidak seru"], 1, "Konflik dan penyelesaian membuat cerita menarik."],
    ["Cerita 'Liburan ke Pantai' — bagian awalnya bisa berisi...", ["Aku berenang", "Pada liburan kemarin, aku pergi ke pantai bersama keluarga", "Aku pulang", "Pantainya indah"], 1, "Awal cerita memperkenalkan kapan dan dengan siapa."],
    ["'Akhirnya, aku pulang dengan senang.' Kalimat ini bagian...", ["Awal", "Tengah", "Akhir", "Judul"], 2, "Kalimat ini adalah penutup atau akhir cerita."],
    ["Dalam menulis cerita, kita perlu...", ["Menulis asal-asalan", "Menyusun kalimat dengan urut", "Menulis panjang", "Pakai kata sulit"], 1, "Cerita harus ditulis dengan urut dan rapi."],
    ["Mana yang bukan bagian dari struktur cerita?", ["Awal", "Tengah", "Akhir", "Gambar"], 3, "Gambar adalah pelengkap, bukan bagian struktur cerita."],
  ]),
}

export default konten
