import type { Konten } from "../types"
import { makeSoal } from "../types"

const konten: Konten = {
  belajar: {
    tujuan: [
      "Memahami pengertian dan jenis cerita rakyat",
      "Mengenal legenda, fabel, dan mite",
      "Menemukan nilai budaya dalam cerita rakyat",
    ],
    materi: [
      {
        judul: "Apa Itu Cerita Rakyat?",
        isi: [
          "Indonesia kaya dengan cerita rakyat. Setiap daerah punya cerita khasnya sendiri!",
          "",
          "✓ Cerita rakyat adalah cerita yang berasal dari masyarakat dan berkembang secara lisan.",
          "✓ Cerita rakyat menyimpan nilai-nilai budaya dan kearifan lokal.",
          "",
          "Jenis cerita rakyat:",
          "1. LEGENDA — cerita tentang asal-usul suatu tempat.",
          "  Contoh: Tangkuban Perahu, Malin Kundang, Danau Toba.",
          "",
          "2. FABEL — cerita hewan yang berperilaku seperti manusia.",
          "  Contoh: Kancil dan Buaya, Kura-kura dan Kelinci.",
          "",
          "3. MITE — cerita tentang dewa atau makhluk gaib.",
          "  Contoh: Jaka Tarub dan Nawang Wulan, Nyi Roro Kidul.",
          "",
          "[Ilustrasi: Peta Indonesia dengan ikon-ikon cerita rakyat dari setiap daerah. Sumatera: Malin Kundang. Jawa: Tangkuban Perahu. Bali: Keong Emas. Kalimantan: Asal Mula Sungai. Sulawesi: Putri Tidur. Setiap ikon digambar gaya kartun lucu.]",
        ],
        contoh: [
          "Kenali cerita rakyat dari daerah asalnya:",
          "",
          "✓ Malin Kundang → Sumatera Barat",
          "✓ Tangkuban Perahu → Jawa Barat",
          "✓ Keong Emas → Jawa Timur",
          "✓ Danau Toba → Sumatera Utara",
          "✓ Kancil dan Buaya → Jawa (cerita rakyat umum)",
          "",
          "Tips: Cerita rakyat setiap daerah biasanya menceritakan asal-usul nama tempat atau danau di daerah tersebut!",
        ],
        catatan: "Cerita rakyat berbeda dengan dongeng biasa. Cerita rakyat melekat pada suatu daerah dan dianggap sebagai bagian dari sejarah budaya masyarakat setempat.",
      },
      {
        judul: "Legenda dan Fabel",
        isi: [
          "Mari kita pelajari dua jenis cerita rakyat yang paling populer!",
          "",
          "✓ LEGENDA",
          "• Cerita tentang asal-usul tempat, benda, atau kejadian alam.",
          "• Dipercaya oleh masyarakat setempat sebagai kisah nyata.",
          "• Tokohnya biasanya manusia.",
          "",
          "Contoh legenda: 'Tangkuban Perahu' — cerita Sangkuriang yang gagal menikahi Dayang Sumbi, lalu menendang perahu hingga menjadi gunung.",
          "",
          "✓ FABEL",
          "• Cerita dengan tokoh hewan yang bisa bicara dan berpikir seperti manusia.",
          "• Mengandung pesan moral.",
          "• Tokoh hewan mewakili sifat manusia.",
          "",
          "Contoh fabel: 'Kura-kura dan Kelinci' — kelinci sombong, kura-kura tekun.",
          "",
          "[Ilustrasi: Dua panel berdampingan. Panel kiri (LEGENDA): Gunung Tangkuban Perahu dengan gambar Sangkuriang di atas perahu. Panel kanan (FABEL): Kura-kura dan kelinci sedang berlomba, kura-kura di garis finish, kelinci tidur di bawah pohon.]",
        ],
        contoh: [
          "Perbedaan legenda dan fabel:",
          "",
          "LEGENDA:",
          "✓ Tokoh: manusia",
          "✓ Tujuan: menjelaskan asal-usul tempat",
          "✓ Contoh: Malin Kundang (asal usul batu)",
          "",
          "FABEL:",
          "✓ Tokoh: hewan",
          "✓ Tujuan: memberi pesan moral",
          "✓ Contoh: Kancil dan Buaya (kecerdikan)",
          "",
          "PENTING: Fabel selalu punya tokoh hewan, sedangkan legenda tokohnya manusia.",
        ],
      },
      {
        judul: "Nilai Budaya dalam Cerita Rakyat",
        isi: [
          "Setiap cerita rakyat mengandung nilai budaya yang luhur.",
          "",
          "Nilai budaya adalah kebiasaan baik yang dijunjung masyarakat dan tercermin dalam cerita.",
          "",
          "Contoh nilai budaya dalam cerita rakyat:",
          "",
          "1. 'Malin Kundang' — Jangan durhaka pada orang tua.",
          "2. 'Tangkuban Perahu' — Jangan melanggar janji.",
          "3. 'Danau Toba' — Jangan ingkar janji yang sudah dibuat.",
          "4. 'Kancil dan Buaya' — Kecerdikan untuk kebaikan.",
          "5. 'Bawang Merah Bawang Putih' — Kebaikan akan berbuah manis.",
          "",
          "[Ilustrasi: Sebuah buku besar terbuka dengan halaman bertuliskan 'NILAI BUDAYA'. Dari buku keluar gambar-gambar: anak menghormati orang tua, orang berjabat tangan, orang bekerja bakti. Setiap gambar mewakili satu nilai budaya dari cerita rakyat.]",
        ],
        contoh: [
          "Nilai budaya dari beberapa cerita rakyat:",
          "",
          "'Malin Kundang':",
          "✓ Nilai budaya: hormat kepada orang tua.",
          "✓ Pesan: jangan durhaka, balas budi orang tua.",
          "",
          "'Kancil dan Buaya':",
          "✓ Nilai budaya: kecerdikan mengatasi masalah.",
          "✓ Pesan: gunakan akal sehat dalam kesulitan.",
          "",
          "'Danau Toba':",
          "✓ Nilai budaya: menepati janji.",
          "✓ Pesan: jangan sembarangan berjanji jika tidak sanggup menepati.",
          "",
          "Tips: Coba cari tahu cerita rakyat dari daerahmu sendiri! Apa nilai budayanya?",
        ],
      },
    ],
    rangkuman: [
      "[Ilustrasi: Tiga pilar berwarna berbeda. Pilar hijau (LEGENDA): gambar gunung dan danau. Pilar biru (FABEL): gambar hewan-hewan. Pilar kuning (NILAI BUDAYA): gambar hati, jabat tangan, dan bintang.]",
      "Cerita rakyat: cerita dari masyarakat yang berkembang secara lisan dan mengandung nilai budaya.",
      "Legenda: cerita asal-usul tempat (tokoh manusia). Fabel: cerita hewan (tokoh hewan).",
      "Nilai budaya dalam cerita rakyat: hormat pada orang tua, menepati janji, kecerdikan, kebaikan.",
      "Setiap daerah di Indonesia punya cerita rakyat yang khas dengan nilai budayanya masing-masing.",
    ],
  },
  latihan: makeSoal([
    ["Cerita rakyat disebarkan secara...", ["Tertulis", "Lisan turun-temurun", ["Online"], "Gambar"], 1, "Cerita rakyat berkembang secara lisan dari mulut ke mulut."],
    ["Cerita tentang asal-usul suatu tempat disebut...", ["Fabel", "Legenda", ["Mite"], "Dongeng"], 1, "Legenda adalah cerita tentang asal-usul tempat."],
    ["Fabel adalah cerita yang tokohnya...", ["Manusia", "Hewan", ["Dewa"], "Tumbuhan"], 1, "Fabel adalah cerita dengan tokoh hewan."],
    ["Malin Kundang adalah cerita rakyat dari...", ["Jawa Barat", "Sumatera Barat", ["Bali"], "Sulawesi"], 1, "Malin Kundang berasal dari Sumatera Barat."],
    ["Nilai budaya dalam cerita 'Malin Kundang' adalah...", ["Rajin belajar", "Hormat pada orang tua", ["Suka menolong"], "Jujur"], 1, "Malin Kundang mengajarkan untuk hormat dan tidak durhaka pada orang tua."],
    ["Tokoh dalam fabel adalah hewan yang...", ["Diam saja", "Bisa bicara seperti manusia", ["Tidak bergerak"], "Hanya makan"], 1, "Dalam fabel, hewan bisa bicara dan berperilaku seperti manusia."],
    ["'Tangkuban Perahu' adalah legenda dari...", ["Jawa Tengah", "Jawa Barat", ["Jawa Timur"], "Banten"], 1, "Tangkuban Perahu adalah legenda dari Jawa Barat."],
    ["Contoh fabel yang terkenal adalah...", ["Malin Kundang", "Kancil dan Buaya", ["Tangkuban Perahu"], "Keong Emas"], 1, "Kancil dan Buaya adalah fabel karena tokohnya hewan."],
    ["Cerita rakyat mengandung...", ["Ilmu pengetahuan", "Nilai budaya dan pesan moral", ["Angka"], "Rumus"], 1, "Cerita rakyat mengandung nilai budaya dan pesan moral."],
    ["Mite adalah cerita tentang...", ["Hewan", "Dewa atau makhluk gaib", ["Tempat"], "Manusia"], 1, "Mite berkisah tentang dewa, roh, atau makhluk gaib."],
  ]),
  praktik: {
    petunjuk: "Carilah satu cerita rakyat dari daerahmu atau daerah lain di Indonesia. Bacalah, lalu tuliskan: judul, asal daerah, jenis cerita (legenda/fabel/mite), tokoh-tokohnya, dan nilai budaya yang terkandung!",
    tips: [
      "Tanyakan pada orang tua atau kakek/nenek tentang cerita rakyat daerahmu",
      "Cari di buku cerita rakyat di perpustakaan",
      "Identifikasi jenis ceritanya (legenda/fabel/mite)",
      "Temukan nilai budaya yang diajarkan cerita itu",
    ],
    contoh: "Cerita: 'Danau Toba' dari Sumatera Utara. Jenis: Legenda. Tokoh: Toba (petani), ikan mas (istri Samosir). Nilai budaya: jangan ingkar janji, tepatilah perkataanmu.",
  },
  kuis: makeSoal([
    ["Cerita rakyat adalah cerita yang berasal dari...", ["Penulis terkenal", "Masyarakat dan turun-temurun", ["Guru"], "Televisi"], 1, "Cerita rakyat berasal dari masyarakat dan disebarkan secara lisan."],
    ["Legenda 'Danau Toba' berasal dari...", ["Jawa", "Sumatera Utara", ["Bali"], "Kalimantan"], 1, "Danau Toba adalah legenda dari Sumatera Utara."],
    ["Perbedaan legenda dan fabel terletak pada...", ["Panjang cerita", "Tokohnya (manusia vs hewan)", ["Tempat"], "Waktu"], 1, "Legenda tokohnya manusia, fabel tokohnya hewan."],
    ["'Kancil dan Buaya' termasuk jenis...", ["Legenda", "Fabel", ["Mite"], "Sage"], 1, "Kancil dan Buaya adalah fabel karena tokohnya hewan."],
    ["Nilai budaya dalam 'Kancil dan Buaya' adalah...", ["Kekuatan", "Kecerdikan", ["Kekayaan"], "Kekuasaan"], 1, "Kancil mengajarkan bahwa kecerdikan bisa mengatasi masalah."],
    ["Mite berbeda dengan legenda karena mite tentang...", ["Tempat", "Dewa/gaib", ["Hewan"], "Manusia"], 1, "Mite berkisah tentang dewa atau makhluk gaib."],
    ["'Keong Emas' adalah cerita rakyat dari...", ["Sumatera", "Jawa Timur", ["Bali"], "Sulawesi"], 1, "Keong Emas adalah cerita rakyat dari Jawa Timur."],
    ["Cerita rakyat biasanya diakhiri dengan...", ["Tamat", "Pesan moral", ["Tanda tanya"], "Selesai"], 1, "Cerita rakyat biasanya diakhiri dengan pesan moral atau amanat."],
    ["Nilai budaya 'gotong royong' tercermin dalam cerita...", ["Malin Kundang", "Roro Jonggrang (kerja bakti membangun candi)", ["Kancil"], "Danau Toba"], 1, "Roro Jonggrang menceritakan tentang kerja bakti (gotong royong) membangun candi."],
    ["Manfaat membaca cerita rakyat adalah...", ["Tahu sejarah daerah", "Mengenal nilai budaya daerah", ["Bisa tidur"], "Hafal nama tempat"], 1, "Cerita rakyat membantu kita mengenal nilai budaya dari berbagai daerah."],
  ]),
}

export default konten
