import type { Konten } from "../types"
import { makeSoal } from "../types"

const konten: Konten = {
  belajar: {
    tujuan: [
      "Membaca puisi dengan ekspresi, intonasi, dan lafal yang tepat",
      "Memahami intonasi dan lafal dalam membaca puisi",
      "Menulis puisi 4 baris dengan tema bebas",
    ],
    materi: [
      {
        judul: "Membaca Puisi dengan Ekspresi",
        isi: [
          "Membaca puisi berbeda dengan membaca cerita. Puisi harus dibaca dengan ekspresi!",
          "",
          "✓ EKSPRESI: raut wajah yang sesuai dengan isi puisi.",
          "",
          "Apa yang harus diperhatikan:",
          "1. Ekspresi sedih jika puisi bertema kesedihan.",
          "2. Ekspresi gembira jika puisi bertema kegembiraan.",
          "3. Ekspresi kagum jika puisi bertema keindahan.",
          "",
          "Contoh:",
          "'Aduh, indahnya pelangi' — baca dengan mata berbinar dan tersenyum.",
          "'Kucingku hilang, sedih hatiku' — baca dengan wajah sedih.",
          "",
          "[Ilustrasi: Empat panel wajah kartun dengan ekspresi berbeda: gembira (mulut lebar, mata berbinar), sedih (mulut turun, air mata), kagum (mulut 'O', mata besar), tenang (tersenyum tipis). Setiap panel terhubung ke teks puisi yang sesuai.]",
        ],
        contoh: [
          "Latihan ekspresi:",
          "",
          "1. Puisi gembira: 'Bunga-bunga mekar / Hatiku senang sekali' → baca sambil tersenyum!",
          "2. Puisi sedih: 'Hujan turun / Aku merindu' → baca dengan wajah sendu.",
          "3. Puisi alam: 'Gunung menjulang / Indah terlihat' → baca dengan mata terbelalak kagum.",
          "",
          "Tips: Coba berdiri di depan cermin saat berlatih ekspresi membaca puisi!",
        ],
      },
      {
        judul: "Intonasi dan Lafal",
        isi: [
          "Selain ekspresi, ada dua hal penting lain: intonasi dan lafal.",
          "",
          "✓ INTONASI: naik turunnya suara saat membaca.",
          "• Suara naik untuk kata penting atau pertanyaan.",
          "• Suara turun di akhir kalimat berita.",
          "",
          "✓ LAFAL: cara mengucapkan kata dengan jelas.",
          "• Ucapkan setiap kata dengan benar.",
          "• Jangan ada yang tertelan atau terlewat.",
          "",
          "[Ilustrasi: Seorang anak berdiri di atas panggung kecil, memegang mikrofon, membaca puisi dengan percaya diri. Di sekelilingnya ada gelombang suara yang naik turun (intonasi). Di bawah ada tulisan 'LAFAL: ucapkan dengan jelas'.]",
        ],
        contoh: [
          "Latihan intonasi:",
          "",
          "Baca kalimat ini dengan intonasi yang berbeda:",
          "",
          "1. 'Hari ini cerah.' → intonasi datar (berita).",
          "2. 'Hari ini cerah?' → intonasi naik di akhir (tanya).",
          "3. 'Hari ini cerah!' → intonasi tegas (seru).",
          "",
          "BENAR: 'Aku cinta Ibu' — baca dengan suara lembut, naik di kata 'cinta'.",
          "SALAH: 'AKU CINTA IBU!' — teriak semua, tidak sesuai puisi.",
        ],
        catatan: "Latihan lafal: ucapkan 'Kakakku mencari kakekku' 3 kali dengan cepat. Pastikan tidak terbata-bata!",
      },
      {
        judul: "Menulis Puisi 4 Baris",
        isi: [
          "Sekarang kita akan menulis puisi 4 baris!",
          "",
          "Langkah menulis:",
          "",
          "1. Pilih tema (alam, keluarga, persahabatan, binatang).",
          "2. Pikirkan perasaanmu tentang tema itu.",
          "3. Tulis 4 baris dengan rima yang indah.",
          "4. Jangan lupa judul!",
          "",
          "Contoh tema 'ALAM':",
          "",
          "\"Pagi yang Indah\"",
          "Fajar merekah di ufuk timur",
          "Burung-burung bernyanyi riang",
          "Embun pagi berkilau bagai mutiara",
          "Alam bangun, pagi yang cerah cemerlang",
          "",
          "[Ilustrasi: Pemandangan alam dengan gunung, sawah, dan matahari terbit. Di atas pemandangan ada teks puisi 4 baris dalam bentuk awan putih. Gaya ilustrasi ceria warna pastel.]",
        ],
        contoh: [
          "Bandingkan puisi yang baik dan kurang baik:",
          "",
          "✗ KURANG BAIK: 'Bunga itu indah / Aku suka sekali / Bunganya warna merah / Aku petik setiap hari'",
          "  → Terlalu sederhana, rima kurang indah, seperti laporan biasa.",
          "",
          "✓ BAIK: 'Bunga mawar di taman hati / Merah merebak penuh pesona / Harum semerbak engkau beri / Indahmu tiada duanya'",
          "  → Ada perasaan, pilihan kata indah, rima a-b-a-b.",
          "",
          "Tips: Gunakan kata-kata kiasan seperti 'bagai', 'laksana', 'semerbak', 'merah merebak' untuk memperindah puisi!",
        ],
      },
    ],
    rangkuman: [
      "[Ilustrasi: Seorang penyair cilik di atas panggung, membaca puisi dengan gaya percaya diri. Penonton bertepuk tangan. Di atas panggung tertulis 'PEMBACA PUISI CILIK'.]",
      "Ekspresi: raut wajah yang sesuai dengan isi puisi (senang, sedih, kagum).",
      "Intonasi: naik turun suara saat membaca puisi.",
      "Lafal: cara mengucapkan kata dengan jelas dan benar.",
      "Menulis puisi: pilih tema, ungkapkan perasaan, buat 4 baris dengan rima yang indah.",
    ],
  },
  latihan: makeSoal([
    ["Ekspresi saat membaca puisi gembira adalah...", ["Menangis", "Tersenyum", "Marah", "Datar"], 1, "Puisi gembira dibaca dengan ekspresi senang atau tersenyum."],
    ["Intonasi adalah...", ["Cara berjalan", "Naik turun suara", "Ekspresi wajah", "Gerakan tangan"], 1, "Intonasi adalah naik turunnya suara saat membaca."],
    ["Lafal yang baik berarti...", ["Suara keras", "Pengucapan jelas dan benar", "Cepat", "Berbisik"], 1, "Lafal baik berarti mengucapkan kata dengan jelas dan benar."],
    ["Puisi 'Aku cinta Ibu' — ekspresi yang tepat adalah...", ["Datar", "Lembut penuh kasih", "Marah", "Bingung"], 1, "Puisi tentang cinta pada ibu dibaca dengan lembut dan penuh kasih."],
    ["Membaca puisi dengan suara datar tanpa ekspresi disebut...", ["Indah", "Monoton", "Bagus", "Menyentuh"], 1, "Membaca tanpa ekspresi disebut monoton, tidak menarik."],
    ["Satu bait puisi biasanya terdiri dari...", ["1 baris", "4 baris", "10 baris", "1 paragraf"], 1, "Satu bait puisi biasanya 4 baris."],
    ["'Mentari pagi bersinar cerah' — intonasi yang tepat...", ["Datar", "Naik di 'cerah'", "Turun semua", "Cepat"], 1, "Intonasi naik di kata 'cerah' karena itu kata penting."],
    ["Kata 'bagai' dalam puisi artinya...", ["Berbeda", "Seperti", "Bersama", "Berlawanan"], 1, "'Bagai' artinya 'seperti' — kata kiasan dalam puisi."],
    ["Sebelum membaca puisi, sebaiknya...", ["Langsung baca", "Pahami isi puisi dulu", "Tidur", "Makan"], 1, "Pahami dulu isi puisi agar ekspresi dan intonasi sesuai."],
    ["Tujuan membaca puisi dengan ekspresi adalah...", ["Biar cepat selesai", "Agar pendengar merasakan isi puisi", "Biar keras", "Biar panjang"], 1, "Ekspresi membantu pendengar merasakan perasaan dalam puisi."],
  ]),
  praktik: {
    petunjuk: "Tulis sebuah puisi 4 baris dengan tema 'KELUARGAKU', lalu bacakan di depan orang tua atau gurumu dengan ekspresi, intonasi, dan lafal yang benar!",
    tips: [
      "Pilih perasaan tentang keluargamu (senang, bangga, sayang)",
      "Gunakan kata-kata indah: bagai, laksana, indah, hangat",
      "Usahakan rima: baris 1 dan 3 berima, baris 2 dan 4 berima",
      "Berlatih di depan cermin sebelum membacakan",
    ],
    contoh: "'Keluargaku' / Ayah, ibu, dan aku / Bagai pelangi penuh warna / Kasih sayang melingkupi / Bahagia bersama selamanya.",
  },
  kuis: makeSoal([
    ["Intonasi yang tepat saat membaca puisi sedih adalah...", ["Ceria", "Lembut dan sendu", "Keras", "Cepat"], 1, "Puisi sedih dibaca dengan intonasi lembut dan sendu."],
    ["Lafal yang kurang jelas menyebabkan...", ["Pendengar paham", "Pendengar kesulitan mengerti", "Puisi lebih indah", "Suara lebih keras"], 1, "Lafal tidak jelas membuat pendengar sulit mengerti kata-kata puisi."],
    ["'Ayah, engkaulah pahlawanku' — kata 'pahlawanku' dibaca dengan intonasi...", ["Datar", "Agak tinggi (kagum)", "Rendah", "Cepat"], 1, "Kata 'pahlawanku' adalah kata penting, dibaca dengan intonasi lebih tinggi."],
    ["Ekspresi wajah saat membaca puisi tentang bencana alam...", ["Tersenyum", "Sedih dan prihatin", "Tertawa", "Biasa"], 1, "Puisi bertema bencana dibaca dengan ekspresi sedih dan prihatin."],
    ["Mana yang bukan teknik membaca puisi?", ["Ekspresi", "Menari", "Intonasi", "Lafal"], 1, "Menari bukan teknik membaca puisi. Tekniknya: ekspresi, intonasi, lafal."],
    ["Puisi akan lebih hidup jika dibaca dengan...", ["Datar", "Ekspresi dan intonasi", "Pelankan", "Cepat"], 1, "Ekspresi dan intonasi membuat puisi lebih hidup dan bermakna."],
    ["'Sungai mengalir tenang' — cara membaca yang tepat...", ["Tergesa", "Perlahan dan tenang", "Keras", "Cepat-cepat"], 1, "Puisi tentang sungai tenang dibaca perlahan dan tenang sesuai isinya."],
    ["Puisi yang baik memiliki...", ["Pilihan kata indah", "Kata asal-asalan", "Kata kasar", "Kata ulang"], 0, "Puisi yang baik menggunakan pilihan kata yang indah dan tepat."],
    ["Membaca puisi sebaiknya tidak...", ["Tersendat-sendat", "Jelas", "Ada intonasi", "Ada ekspresi"], 0, "Membaca puisi sebaiknya lancar, tidak tersendat-sendat."],
    ["Rima dalam puisi membuatnya terdengar...", ["Kasar", "Indah dan merdu", "Biasa", "Cepat"], 1, "Rima membuat puisi terdengar indah dan merdu."],
  ]),
}

export default konten
