import type { Konten } from "../types"
import { makeSoal } from "../types"

const konten: Konten = {
  belajar: {
    tujuan: [
      "Memahami pengertian dan tujuan pengumuman",
      "Mengenal unsur-unsur dalam pengumuman",
      "Menulis teks pengumuman sederhana",
    ],
    materi: [
      {
        judul: "Apa Itu Pengumuman?",
        isi: [
          "Pernahkah kamu melihat tulisan di papan sekolah yang memberitahu tentang lomba? Atau mendengar informasi dari pengeras suara di sekolah?",
          "",
          "Itu namanya pengumuman!",
          "",
          "✓ Pengumuman adalah informasi yang disampaikan kepada banyak orang.",
          "✓ Tujuan pengumuman: memberitahukan sesuatu kepada khalayak umum.",
          "✓ Pengumuman bisa disampaikan secara lisan atau tertulis.",
          "",
          "Contoh pengumuman di sekolah:",
          "• Lomba mewarnai dalam rangka 17 Agustus.",
          "• Libur sekolah pada hari tertentu.",
          "• Pengumpulan buku perpustakaan.",
          "",
          "[Ilustrasi: Papan pengumuman sekolah dengan tempelan-tempelan kertas warna-warni. Ada pengumuman lomba, jadwal piket, dan informasi libur. Beberapa siswa sedang membaca papan pengumuman.]",
        ],
        contoh: [
          "Pengumuman lisan vs tertulis:",
          "",
          "✓ LISAN: Guru berbicara di depan kelas: 'Besok libur, ya, anak-anak!'",
          "✓ TERTULIS: Selembar kertas ditempel di papan: 'DIBERITAHUKAN...'",
          "",
          "SALAH: Pengumuman yang tidak jelas — 'Nanti ada acara.' (kapan? di mana? jam berapa?)",
          "✓ Pengumuman yang baik: 'Besok, Sabtu 10 Mei 2025, akan diadakan lomba mewarnai di aula sekolah, pukul 08.00 WIB.'",
        ],
      },
      {
        judul: "Unsur-Unsur Pengumuman",
        isi: [
          "Setiap pengumuman harus punya unsur-unsur berikut:",
          "",
          "1. JUDUL — 'PENGUMUMAN' atau topik pengumuman.",
          "2. ISI — informasi yang ingin disampaikan (apa, kapan, di mana).",
          "3. PENANGGUNG JAWAB — siapa yang mengeluarkan pengumuman.",
          "4. TEMPAT dan TANGGAL — kapan pengumuman dibuat.",
          "",
          "Contoh pengumuman:",
          "",
          "\"PENGUMUMAN\"",
          "Diberitahukan kepada seluruh siswa bahwa hari Sabtu, 17 Agustus 2025, akan diadakan lomba mewarnai. Acara dimulai pukul 08.00 di aula sekolah. Semua siswa kelas 1-2 diharap ikut serta.",
          "Bandung, 10 Agustus 2025",
          "Kepala Sekolah",
          "",
          "[Ilustrasi: Template pengumuman kosong dengan kotak-kotak bertanda: JUDUL (atas), ISI (tengah besar), PENANGGUNG JAWAB (kanan bawah), dan TANGGAL (kiri bawah). Anak panah menunjuk setiap bagian.]",
        ],
        contoh: [
          "Periksa apakah pengumuman ini lengkap:",
          "",
          "✗ 'Besok ada lomba.' — Tidak lengkap! Kapan tepatnya? Di mana? Siapa yang mengumumkan?",
          "",
          "✓ 'PENGUMUMAN. Diberitahukan bahwa besok, Rabu 15 Maret 2025, akan diadakan lomba baca puisi di perpustakaan sekolah pukul 09.00. Semua siswa kelas 2 diharap ikut serta. Bandung, 14 Maret 2025. Kepala Sekolah.'",
          "✓ Lengkap: judul, isi (apa, kapan, di mana), penanggung jawab, tanggal!",
        ],
        catatan: "Bahasa pengumuman harus singkat, jelas, dan mudah dipahami. Pengumuman bukan cerita, jadi tidak perlu panjang-panjang!",
      },
      {
        judul: "Menulis Pengumuman",
        isi: [
          "Sekarang giliranmu menulis pengumuman! Ikuti langkah-langkah ini:",
          "",
          "1. Tentukan topik pengumuman (misalnya: lomba, libur, rapat).",
          "2. Tulis judul 'PENGUMUMAN' di bagian atas.",
          "3. Tulis isi: APA yang diumumkan, KAPAN, DI MANA.",
          "4. Tulis penanggung jawab dan tanggal.",
          "5. Gunakan bahasa yang singkat dan jelas.",
          "",
          "Contoh:",
          "",
          "\"PENGUMUMAN\"",
          "Diberitahukan kepada seluruh siswa Kelas 2 bahwa besok, Kamis 20 Maret 2025, akan diadakan kerja bakti membersihkan kelas. Semua siswa diharap membawa alat kebersihan dari rumah.",
          "Bandung, 19 Maret 2025",
          "Wali Kelas 2",
          "",
          "[Ilustrasi: Selembar kertas putih dengan tulisan pengumuman rapi. Di atas kertas ada gambar lampu bohlam (ide). Pensil dan penghapus di samping kertas. Gaya ilustrasi anak sekolah.]",
        ],
        contoh: [
          "Bandingkan pengumuman yang baik dan kurang baik:",
          "",
          "✗ KURANG BAIK: 'Hey, besok ada acara lomba ya. dateng semua. pokoknya seru.'",
          "  — Bahasa tidak baku, tidak jelas, tidak ada penanggung jawab.",
          "",
          "✓ BAIK: 'PENGUMUMAN. Diberitahukan bahwa besok, Jumat 21 Maret 2025, akan diadakan lomba menggambar di kelas masing-masing pukul 09.00. Bandung, 20 Maret 2025. Panitia Lomba.'",
          "  — Bahasa baku, jelas, lengkap!",
          "",
          "Tips: Gunakan kata 'Diberitahukan' atau 'Disampaikan' sebagai pembuka isi pengumuman.",
        ],
      },
    ],
    rangkuman: [
      "[Ilustrasi: Papan pengumuman besar dengan contoh pengumuman lengkap yang ditempel rapi. Semua unsur ditandai dengan stiker: JUDUL (bintang), ISI (panah), PENANGGUNG JAWAB (gambar orang), TANGGAL (kalender).]",
      "Pengumuman adalah informasi yang disampaikan kepada banyak orang, bisa lisan atau tertulis.",
      "Unsur pengumuman: judul, isi (apa, kapan, di mana), penanggung jawab, tanggal.",
      "Bahasa pengumuman: singkat, jelas, mudah dipahami, dan baku.",
      "Gunakan kata 'Diberitahukan' sebagai pembuka isi pengumuman.",
    ],
  },
  latihan: makeSoal([
    ["Pengumuman adalah...", ["Cerita pendek", "Informasi untuk banyak orang", "Puisi", "Laporan"], 1, "Pengumuman adalah informasi yang ditujukan kepada banyak orang."],
    ["Unsur yang HARUS ada dalam pengumuman adalah...", ["Gambar", "Isi informasi", "Puisi", "Hiasan"], 1, "Isi informasi (apa, kapan, di mana) adalah unsur wajib."],
    ["Judul pengumuman yang tepat adalah...", ["PENGUMUMAN", "Cerita", "Puisi", "Laporan"], 0, "Judul pengumuman biasanya 'PENGUMUMAN'."],
    ["Bahasa dalam pengumuman harus...", ["Panjang", "Singkat dan jelas", "Berima", "Indah"], 1, "Pengumuman harus singkat, jelas, dan mudah dipahami."],
    ["Penanggung jawab pengumuman ditulis di...", ["Awal", "Akhir", "Tengah", "Judul"], 1, "Penanggung jawab ditulis di bagian akhir pengumuman."],
    ["Contoh penanggung jawab yang tepat adalah...", ["Hormat kami", "Kepala Sekolah", "Terima kasih", "Salam"], 1, "'Kepala Sekolah' adalah penanggung jawab yang jelas."],
    ["Pengumuman lisan disampaikan dengan...", ["Tulisan", "Bicara langsung", "Gambar", "Teks"], 1, "Pengumuman lisan disampaikan secara langsung melalui bicara."],
    ["Tujuan pengumuman adalah...", ["Menghibur", "Memberi informasi", "Mendidik", "Menceritakan"], 1, "Tujuan utama pengumuman adalah memberi informasi."],
    ["Yang tidak perlu dicantumkan dalam pengumuman adalah...", ["Tanggal", "Harga pribadi", "Tempat", "Penanggung jawab"], 1, "Harga pribadi atau informasi tidak relevan tidak perlu dicantumkan."],
    ["Pengumuman yang baik menggunakan bahasa...", ["Baku", "Santai", "Daerah", "Gaul"], 0, "Pengumuman menggunakan bahasa baku yang resmi dan sopan."],
  ]),
  praktik: {
    petunjuk: "Buatlah sebuah pengumuman tentang lomba menyanyi yang akan diadakan di sekolahmu! Sertakan semua unsur yang benar.",
    tips: [
      "Mulai dengan judul 'PENGUMUMAN'",
      "Tentukan hari, tanggal, jam, dan tempat lomba",
      "Siapa yang boleh ikut? (kelas berapa?)",
      "Siapa yang mengeluarkan pengumuman?",
      "Jangan lupa tanggal pembuatan pengumuman",
    ],
    contoh: "PENGUMUMAN. Diberitahukan kepada seluruh siswa Kelas 1 dan 2 bahwa pada hari Sabtu, 25 Oktober 2025, akan diadakan lomba menyanyi lagu wajib. Acara dimulai pukul 08.00 di aula sekolah. Pendaftaran dibuka sampai 23 Oktober. Bandung, 20 Oktober 2025. Panitia Lomba.",
  },
  kuis: makeSoal([
    ["Unsur wajib dalam pengumuman adalah...", ["Judul, isi, penanggung jawab", "Gambar, warna, hiasan", "Puisi, lagu", "Cerita, dongeng"], 0, "Pengumuman harus punya judul, isi, dan penanggung jawab."],
    ["'Diberitahukan bahwa...' adalah kalimat pembuka yang...", ["Tidak perlu", "Baik dan baku", "Panjang", "Salah"], 1, "'Diberitahukan bahwa' adalah pembuka yang baku untuk pengumuman."],
    ["Bagian isi pengumuman menjawab pertanyaan...", ["Apa, kapan, di mana", "Siapa, mengapa", "Berapa", "Bagaimana"], 0, "Isi pengumuman harus mencakup apa, kapan, dan di mana."],
    ["Penanggung jawab berguna untuk...", ["Menghias", "Menunjukkan siapa yang berwenang", "Menambah kata", "Membingungkan"], 1, "Penanggung jawab menunjukkan pihak yang mengeluarkan pengumuman."],
    ["Pengumuman yang tidak ada penanggung jawab...", ["Lebih baik", "Tidak jelas asalnya", "Lebih singkat", "Lebih menarik"], 1, "Pengumuman tanpa penanggung jawab tidak jelas sumbernya."],
    ["Mana yang termasuk pengumuman?", ["Guru mengajar", "Libur sekolah tanggal 1 Mei", "Budi bermain", "Ibu memasak"], 1, "'Libur sekolah' adalah informasi untuk banyak orang — termasuk pengumuman."],
    ["'PENGUMUMAN' ditulis dengan huruf...", ["Kecil", "Kapital", "Tebal", "Miring"], 1, "Judul pengumuman ditulis dengan huruf kapital (besar semua)."],
    ["Tempat dan tanggal pembuatan pengumuman diletakkan di...", ["Atas", "Bawah setelah isi", "Tengah", "Samping"], 1, "Tempat dan tanggal pembuatan ditempatkan di bawah setelah isi pengumuman."],
    ["Pengumuman disampaikan kepada...", ["Diri sendiri", "Banyak orang", "Satu orang", "Teman saja"], 1, "Pengumuman ditujukan kepada khalayak ramai atau banyak orang."],
    ["Salah satu ciri pengumuman yang baik adalah...", ["Berbelit-belit", "Singkat dan padat", "Panjang", "Tidak jelas"], 1, "Pengumuman yang baik singkat, padat, dan jelas."],
  ]),
}

export default konten
