import type { Konten } from "../types"
import { makeSoal } from "../types"

const konten: Konten = {
  belajar: {
    tujuan: [
      "Mengenal ciri-ciri pantun",
      "Memahami bagian sampiran dan isi pantun",
      "Membuat pantun anak sederhana",
    ],
    materi: [
      {
        judul: "Apa Itu Pantun?",
        isi: [
          "Teman-teman, siapa yang pernah mendengar pantun? Pantun adalah salah satu jenis puisi lama!",
          "",
          "✓ Pantun adalah puisi yang terdiri dari 4 baris.",
          "✓ Pantun punya sajak a-b-a-b (baris 1 dan 3 berima, baris 2 dan 4 berima).",
          "✓ Dua baris pertama disebut sampiran.",
          "✓ Dua baris terakhir disebut isi.",
          "",
          "Contoh pantun:",
          "",
          "Jalan-jalan ke kota Blitar (a)",
          "Jangan lupa membeli duku (b)",
          "Rajin-rajinlah belajar (a)",
          "Supaya pintar dan berilmu (b)",
          "",
          "[Ilustrasi: Empat baris pantun dalam bentuk balok warna-warni. Balok 1 (merah) dan 3 (merah) berima 'a'. Balok 2 (biru) dan 4 (biru) berima 'b'. Dua balok pertama (sampiran) di atas, dua balok terakhir (isi) di bawah.]",
        ],
        contoh: [
          "Ciri-ciri pantun:",
          "",
          "1. Setiap baris terdiri dari 8-12 suku kata.",
          "2. Bersajak a-b-a-b.",
          "3. Baris 1-2 = sampiran (pembuka, tidak berhubungan langsung dengan isi).",
          "4. Baris 3-4 = isi (pesan atau maksud pantun).",
          "",
          "BENAR: 'Pergi ke pasar membeli sapu / Sapu dibeli warna hijau / Jika ingin jadi pintar / Belajar jangan pernah ragu'",
          "✓ 4 baris, sajak a-b-a-b.",
          "",
          "SALAH: 'Aku pergi ke sekolah / Belajar dengan giat / Rajin setiap hari / Supaya jadi pintar'",
          "✗ Ini bukan pantun — sajaknya tidak a-b-a-b, tidak ada sampiran.",
        ],
        catatan: "Pantun termasuk puisi lama. Berbeda dengan puisi modern, pantun punya aturan yang tetap: 4 baris, sajak a-b-a-b.",
      },
      {
        judul: "Sampiran dan Isi",
        isi: [
          "Pantun punya dua bagian penting: sampiran dan isi.",
          "",
          "✓ SAMPIRAN: dua baris pertama (baris 1 dan 2).",
          "  • Fungsinya sebagai pengantar.",
          "  • Biasanya tentang alam, kegiatan sehari-hari, atau benda.",
          "  • Tidak berhubungan langsung dengan isi.",
          "",
          "✓ ISI: dua baris terakhir (baris 3 dan 4).",
          "  • Berisi pesan, nasihat, atau maksud pantun.",
          "  • Ini yang ingin disampaikan oleh pembuat pantun.",
          "",
          "Contoh:",
          "'Pergi ke pasar naik delman' (sampiran baris 1)",
          "'Jangan lupa membeli roti'   (sampiran baris 2)",
          "'Hormati ibu dan ayahmu'     (isi baris 3)",
          "'Agar hidupmu diberkahi'     (isi baris 4)",
          "",
          "[Ilustrasi: Dua kotak besar. Kotak atas (warna hijau muda) bertuliskan 'SAMPIRAN' dengan gambar pasar, delman, dan roti. Kotak bawah (warna emas) bertuliskan 'ISI' dengan gambar anak menghormati orang tua.]",
        ],
        contoh: [
          "Ayo bedakan sampiran dan isi:",
          "",
          "Pantun:",
          "'Belanja ke pasar membeli batu' → sampiran",
          "'Batu dibeli warna hitam' → sampiran",
          "'Katakanlah selalu yang jujur' → isi",
          "'Meskipun pahit rasanya pahit' → isi",
          "",
          "Tips: Kalau bingung membedakan, lihat baris 3-4. Di situlah pesan pantun berada!",
        ],
      },
      {
        judul: "Membuat Pantun Anak",
        isi: [
          "Sekarang giliranmu membuat pantun!",
          "",
          "Langkah membuat pantun:",
          "",
          "1. Tentukan isi pesan (baris 3 dan 4) — misalnya: nasihat belajar.",
          "2. Buat sampiran (baris 1 dan 2) — tidak perlu berhubungan dengan isi.",
          "3. Pastikan sajak a-b-a-b.",
          "4. Usahakan setiap baris 8-12 suku kata.",
          "",
          "Contoh langkah:",
          "",
          "Isi pesan: 'Rajin belajar supaya pintar.'",
          "→ Baris 3: 'Rajin-rajinlah belajar'",
          "→ Baris 4: 'Agar pintar dan berilmu'",
          "",
          "Sampiran (cari yang berima dengan belajar/berilmu):",
          "→ Baris 1: 'Pagi-pagi pergi ke kota' (berima a dengan belajar)",
          "→ Baris 2: 'Jangan lupa membawa bekal' (berima u dengan berilmu)",
          "",
          "[Ilustrasi: Seorang anak duduk di meja belajar, memegang pensil dan kertas, sedang menulis pantun. Di atas meja ada buku terbuka berisi contoh pantun. Di sekelilingnya ada stiker kata-kata yang bisa digunakan untuk membuat pantun.]",
        ],
        contoh: [
          "Contoh pantun anak:",
          "",
          "Pantun Nasihat Belajar:",
          "'Pergi ke hutan menangkap ular'",
          "'Ular ditangkap pakai jaring'",
          "'Jangan malas dan suka menunda'",
          "'Belajar tiap hari biar jadi pintar'",
          "",
          "Pantun Nasihat Kebersihan:",
          "'Ke kebun binatang naik bendi'",
          "'Bendi dinaiki bersama adik'",
          "'Buanglah sampah pada tempatnya'",
          "'Agar lingkungan bersih dan asri'",
          "",
          "Tips: Pantun anak sebaiknya berisi nasihat yang baik dan mudah dipahami!",
        ],
      },
    ],
    rangkuman: [
      "[Ilustrasi: Empat kartu bergambar dengan teks pantun. Kartu sampiran (2 kartu atas) bergambar kegiatan sehari-hari. Kartu isi (2 kartu bawah) bergambar anak rajin belajar, anak membuang sampah. Di sudut ada tulisan 'PANTUNKU'.]",
      "Pantun: puisi lama 4 baris dengan sajak a-b-a-b.",
      "Sampiran: 2 baris pertama (pengantar, tidak berhubungan langsung dengan isi).",
      "Isi: 2 baris terakhir (pesan atau nasihat).",
      "Cara membuat: tentukan isi dulu, baru buat sampiran yang berima.",
    ],
  },
  latihan: makeSoal([
    ["Pantun terdiri dari... baris", ["2", "4", "6", "8"], 1, "Pantun terdiri dari 4 baris."],
    ["Sajak pantun adalah...", ["a-a-a-a", "a-b-a-b", "a-b-b-a", "b-a-b-a"], 1, "Pantun bersajak a-b-a-b."],
    ["Bagian sampiran adalah baris...", ["1-2", "3-4", "2-3", "1-4"], 0, "Sampiran adalah baris 1 dan 2 dalam pantun."],
    ["Bagian isi pantun berisi...", ["Pengantar", "Pesan atau nasihat", "Hiasan", "Gambar"], 1, "Isi pantun adalah pesan yang ingin disampaikan."],
    ["'Pergi ke pasar naik sepeda' — ini adalah bagian...", ["Isi", "Sampiran", "Kesimpulan", "Judul"], 1, "Baris tentang kegiatan adalah sampiran."],
    ["Pantun anak biasanya berisi...", ["Masalah orang dewasa", "Nasihat yang baik", "Cerita sedih", "Ilmu sulit"], 1, "Pantun anak berisi nasihat yang sederhana dan baik."],
    ["'Rajin-rajinlah belajar' — baris ini termasuk...", ["Sampiran", "Isi", "Judul", "Penutup"], 1, "'Rajin belajar' adalah nasihat, jadi bagian isi."],
    ["Setiap baris pantun terdiri dari... suku kata", ["4-6", "8-12", "14-16", "Berapa saja"], 1, "Setiap baris pantun idealnya 8-12 suku kata."],
    ["Pantun termasuk jenis puisi...", ["Baru", "Lama", "Modern", "Bebas"], 1, "Pantun adalah puisi lama dengan aturan tetap."],
    ["Sampiran berfungsi sebagai...", ["Pesan utama", "Pengantar", "Kesimpulan", "Judul"], 1, "Sampiran berfungsi sebagai pengantar sebelum isi."],
  ]),
  praktik: {
    petunjuk: "Buatlah 2 pantun anak: satu tentang nasihat rajin belajar, satu tentang sayang orang tua!",
    tips: [
      "Tentukan isi pesan dulu (baris 3-4)",
      "Cari kata yang mudah berima untuk isi",
      "Buat sampiran (baris 1-2) yang berima dengan isi",
      "Baca keras-keras, pastikan bunyinya enak didengar",
    ],
    contoh: "Pantun 1 (Rajin Belajar): 'Pergi ke kebun memetik jambu / Jambu dipetik buahnya ranum / Belajar jangan pernah ragu / Agar kelak jadi yang utama.' Pantun 2 (Sayang Orang Tua): 'Berlayar ke laut membawa jaring / Jaring ditebar mencari ikan / Kepada ibu dan ayah sayang / Agar hidup penuh berkah Tuhan.'",
  },
  kuis: makeSoal([
    ["Ciri pantun adalah...", ["5 baris", "Sajak a-b-a-b", "Sajak a-a-a-a", "Tidak berima"], 1, "Pantun bersajak a-b-a-b (baris 1=3, baris 2=4)."],
    ["'Jalan-jalan ke rumah paman' — termasuk bagian...", ["Sampiran", "Isi", "Judul", "Penutup"], 0, "Baris tentang kegiatan adalah sampiran."],
    ["Isi pantun terletak di baris...", ["1-2", "3-4", "1 dan 3", "2 dan 4"], 1, "Isi pantun ada di baris 3 dan 4."],
    ["'Jika ingin menjadi pintar' — baris ini membutuhkan pasangan berima...", ["Pintar", "Belajar", "Rajin", "Sekolah"], 1, "Pintar berima dengan... belajar? Tidak. Cari kata yang berima dengan 'pintar': pintar-ajar. Ya 'ajar' berima dengan 'pintar'."],
    ["Pantun biasanya berisi...", ["Cerita panjang", "Nasihat atau pesan", "Laporan", "Puisi cinta"], 1, "Pantun biasanya berisi nasihat, pesan, atau hiburan."],
    ["Sampiran tidak perlu...", ["Berima dengan isi", "Berhubungan langsung dengan isi", "4 baris", "Berima a-b"], 1, "Sampiran tidak perlu berhubungan langsung dengan isi pantun."],
    ["Manakah rima yang benar untuk pantun?", ["a-a-a-a", "a-b-a-b", "a-b-c-d", "b-b-a-a"], 1, "Pantun bersajak a-b-a-b."],
    ["Baris 1: 'Pergi ke pasar naik becak', Baris 2: 'Becak dikayuh dengan kaki' — rima baris 1 dan 2 adalah...", ["Sama (a-a)", "Tidak sama (a-b)", "Berima", "Sempurna"], 1, "'Becak' dan 'kaki' tidak berima. Jadi ini rima a-b."],
    ["Pantun 'Buah mangga buah pepaya / Dibeli ibu di pasar pagi / Rajin belajar setiap hari / Agar kelak jadi yang berarti' — mana isinya?", ["Buah mangga buah pepaya", "Rajin belajar setiap hari / Agar kelak jadi yang berarti", "Dibeli ibu di pasar pagi", "Semua baris"], 1, "Baris 3-4 adalah isi pantun."],
    ["Mengapa pantun disebut puisi lama?", ["Karena panjang", "Karena aturannya tetap dan sudah ada sejak dulu", "Karena susah", "Karena tidak populer"], 1, "Pantun adalah puisi lama karena sudah ada sejak zaman dulu dan aturannya tetap."],
  ]),
}

export default konten
