import type { Konten } from "../types"
import { makeSoal } from "../types"

const konten: Konten = {
  belajar: {
    tujuan: [
      "Memahami isi bacaan dengan membaca dalam hati",
      "Menemukan informasi penting dalam bacaan",
      "Menjawab pertanyaan berdasarkan bacaan",
    ],
    materi: [
      {
        judul: "Membaca dengan Pemahaman",
        isi: [
          "Membaca bukan sekadar melihat huruf. Membaca juga berarti memahami isi bacaan!",
          "",
          "Tips membaca dengan pemahaman:",
          "",
          "1. Bacalah dengan tenang dan fokus.",
          "2. Cari tahu: tentang apa bacaan ini?",
          "3. Garis bawahi kata-kata penting.",
          "4. Ulangi membaca jika ada bagian yang belum dipahami.",
          "",
          "[Ilustrasi: Seorang anak duduk di sudut perpustakaan, membaca buku dengan kaca pembesar kecil di tangannya. Di sekelilingnya ada tumpukan buku. Dari buku yang dibaca keluar gelembung berisi gambar-gambar tentang isi bacaan.]",
        ],
        contoh: [
          "Baca teks berikut dengan saksama:",
          "",
          "\"Kebun Binatang\"",
          "Hari Minggu, Budi dan ayah pergi ke kebun binatang. Di sana, mereka melihat berbagai hewan. Ada gajah yang besar, jerapah yang tinggi, dan monyet yang lucu. Budi sangat senang. Ia belajar banyak tentang hewan.",
          "",
          "Setelah membaca, tanyakan pada diri sendiri:",
          "✓ Siapa yang pergi ke kebun binatang? (Budi dan ayah)",
          "✓ Hewan apa saja yang mereka lihat? (gajah, jerapah, monyet)",
          "✓ Bagaimana perasaan Budi? (sangat senang)",
        ],
        catatan: "Membaca dengan pemahaman berbeda dengan membaca sekilas. Kita perlu fokus dan merenungkan isi bacaan.",
      },
      {
        judul: "Menemukan Informasi Penting",
        isi: [
          "Dalam setiap bacaan, ada informasi penting yang harus ditemukan.",
          "",
          "Informasi penting bisa berupa:",
          "• Siapa tokohnya",
          "• Di mana kejadiannya",
          "• Kapan kejadiannya",
          "• Apa yang terjadi",
          "• Mengapa itu terjadi",
          "• Bagaimana cara penyelesaiannya",
          "",
          "Gunakan 5W+1H untuk menemukan informasi penting!",
          "",
          "[Ilustrasi: Papan tulis dengan 6 kotak berwarna. Setiap kotak berisi satu kata tanya: WHAT (Apa) merah, WHO (Siapa) biru, WHERE (Di mana) hijau, WHEN (Kapan) kuning, WHY (Mengapa) oranye, HOW (Bagaimana) ungu. Ikon sederhana di setiap kotak.]",
        ],
        contoh: [
          "Baca teks dan temukan informasinya:",
          "",
          "\"Pada hari Sabtu, Siti belajar naik sepeda di halaman rumah. Ayah membantunya memegang sepeda. Setelah beberapa kali jatuh, akhirnya Siti bisa naik sepeda. Ia sangat gembira.\"",
          "",
          "Informasi penting:",
          "✓ Siapa? — Siti dan Ayah",
          "✓ Apa? — Belajar naik sepeda",
          "✓ Di mana? — Halaman rumah",
          "✓ Kapan? — Hari Sabtu",
          "✓ Bagaimana? — Ayah membantu, Siti beberapa kali jatuh lalu bisa",
          "✓ Perasaan? — Sangat gembira",
        ],
      },
      {
        judul: "Kata Tanya: Apa, Siapa, Kapan, Di Mana, Mengapa, Bagaimana",
        isi: [
          "Ada enam kata tanya yang membantu kita menemukan informasi:",
          "",
          "1. APA — menanyakan benda atau hal",
          "  Contoh: 'Apa yang dibawa Budi?' → Buku.",
          "",
          "2. SIAPA — menanyakan orang",
          "  Contoh: 'Siapa yang pergi ke pasar?' → Ibu.",
          "",
          "3. DI MANA — menanyakan tempat",
          "  Contoh: 'Di mana buku itu?' → Di atas meja.",
          "",
          "4. KAPAN — menanyakan waktu",
          "  Contoh: 'Kapan kamu lahir?' → Tanggal 10 Mei.",
          "",
          "5. MENGAPA — menanyakan alasan",
          "  Contoh: 'Mengapa kamu menangis?' → Karena jatuh.",
          "",
          "6. BAGAIMANA — menanyakan cara atau keadaan",
          "  Contoh: 'Bagaimana cara membuat jus?' → Blender buah.",
          "",
          "[Ilustrasi: Enam gelembung percakapan dari tokoh kartun. Setiap gelembung berisi satu kata tanya dengan ikon: APA (tanda tanya), SIAPA (orang), DI MANA (peta), KAPAN (jam), MENGAPA (roda gigi), BAGAIMANA (panah proses).]",
        ],
        contoh: [
          "Latihan bertanya:",
          "",
          "1. '______ yang kamu suka?' → Jawaban: Membaca buku. (Kata tanya: APA)",
          "2. '______ namamu?' → Jawaban: Budi. (Kata tanya: SIAPA)",
          "3. '______ kamu tinggal?' → Jawaban: Di Bandung. (Kata tanya: DI MANA)",
          "4. '______ kamu lahir?' → Jawaban: Tahun 2018. (Kata tanya: KAPAN)",
          "",
          "Tips: Pilih kata tanya yang tepat sesuai dengan jawaban yang diinginkan!",
        ],
      },
    ],
    rangkuman: [
      "[Ilustrasi: Seorang anak memegang piala bertuliskan 'AKU BISA MEMBACA' dengan latar belakang buku dan huruf berterbangan. Anak itu tersenyum bangga.]",
      "Membaca dengan pemahaman: baca dengan fokus, cari informasi penting.",
      "Informasi penting: siapa, apa, di mana, kapan, mengapa, bagaimana (5W+1H).",
      "Kata tanya yang tepat: apa (benda), siapa (orang), di mana (tempat), kapan (waktu), mengapa (alasan), bagaimana (cara/keadaan).",
      "Ulangi membaca jika belum paham, dan tanyakan pada diri sendiri tentang isi bacaan.",
    ],
  },
  latihan: makeSoal([
    ["'Siapa' digunakan untuk menanyakan...", ["Benda", "Orang", "Tempat", "Waktu"], 1, "'Siapa' menanyakan orang atau pelaku."],
    ["'Di mana' digunakan untuk menanyakan...", ["Alasan", "Tempat", "Waktu", "Cara"], 1, "'Di mana' menanyakan tempat kejadian."],
    ["Kata tanya 'Kapan' bertanya tentang...", ["Tempat", "Orang", "Waktu", "Cara"], 2, "'Kapan' menanyakan waktu kejadian."],
    ["Budi membawa buku ke sekolah. Pertanyaan yang tepat: '____ yang dibawa Budi?'", ["Siapa", "Apa", "Di mana", "Kapan"], 1, "'Apa yang dibawa Budi?' — buku adalah benda."],
    ["Dalam membaca dengan pemahaman, kita harus...", ["Terburu-buru", "Fokus dan pahami isi", "Hanya melihat gambar", "Membaca cepat tanpa paham"], 1, "Membaca dengan pemahaman berarti fokus dan memahami isi."],
    ["5W+1H membantu kita...", ["Menulis cepat", "Menemukan informasi penting", "Menambah huruf", "Membaca lebih cepat"], 1, "5W+1H membantu menemukan informasi penting dalam bacaan."],
    ["Kata tanya 'Mengapa' bertanya tentang...", ["Cara", "Alasan", "Tempat", "Waktu"], 1, "'Mengapa' menanyakan alasan atau sebab."],
    ["'Bagaimana cara membuat layang-layang?' — ini menanyakan...", ["Alasan", "Cara", "Tempat", "Waktu"], 1, "'Bagaimana' menanyakan cara atau proses."],
    ["Setelah membaca, sebaiknya kita...", ["Langsung tidur", "Merenungkan isi bacaan", "Membuang buku", "Lupa"], 1, "Setelah membaca, renungkan dan pahami isinya."],
    ["Bacaan 'Kebun Binatang' menceritakan tentang...", ["Sekolah", "Binatang di kebun binatang", "Rumah Budi", "Taman bermain"], 1, "Bacaan itu menceritakan kunjungan ke kebun binatang."],
  ]),
  praktik: {
    petunjuk: "Bacalah teks pendek berikut, lalu jawab pertanyaan dengan kata tanya yang tepat: 'Hari Minggu lalu, Siti membantu ibu membuat kue di dapur. Siti mengocok telur, sementara ibu mencampur tepung. Kue buatan mereka sangat enak.'",
    tips: [
      "Baca teks dengan saksama 2 kali",
      "Temukan siapa, apa, di mana, kapan, mengapa, bagaimana",
      "Tulis jawaban dengan kalimat lengkap",
      "Gunakan huruf kapital dan tanda titik",
    ],
    contoh: "Pertanyaan: Siapa yang membantu ibu? Jawaban: Siti yang membantu ibu. Pertanyaan: Apa yang mereka buat? Jawaban: Mereka membuat kue.",
  },
  kuis: makeSoal([
    ["Kata tanya untuk menanyakan tempat adalah...", ["Apa", "Di mana", "Siapa", "Kapan"], 1, "'Di mana' menanyakan tempat."],
    ["'Mengapa Siti menangis?' — jawaban yang tepat...", ["Di sekolah", "Karena jatuh dari sepeda", "Kemarin", "Dengan tertib"], 1, "'Karena jatuh' adalah alasan — sesuai pertanyaan 'mengapa'."],
    ["5W+1H terdiri dari...", ["5 kata tanya + 1 kata kerja", "6 kata tanya", "5 huruf + 1 angka", "5 kalimat + 1 paragraf"], 1, "5W+1H adalah 6 kata tanya: What, Who, Where, When, Why, How."],
    ["'Kapan kamu lahir?' — jawaban yang tepat...", ["Di Bandung", "Tanggal 10 Mei 2018", "Karena senang", "Dengan sehat"], 1, "'Kapan' menanyakan waktu, jawaban tepat adalah tanggal."],
    ["Apa yang dilakukan setelah membaca?", ["Langsung tutup buku", "Merenungkan dan memahami isi", "Melempar buku", "Mengabaikan"], 1, "Setelah membaca, kita merenungkan isi bacaan."],
    ["'Apa' digunakan untuk menanyakan...", ["Orang", "Benda atau hal", "Tempat", "Alasan"], 1, "'Apa' menanyakan benda, hewan, atau hal."],
    ["Informasi penting dalam bacaan bisa ditemukan dengan...", ["Menebak", "Membaca saksama", "Mengabaikan", "Menghafal"], 1, "Baca dengan saksama untuk menemukan informasi penting."],
    ["Kata tanya 'Bagaimana' menanyakan...", ["Tempat", "Waktu", "Cara", "Orang"], 2, "'Bagaimana' menanyakan cara atau proses."],
    ["Setelah membaca, kita bisa bertanya: 'Apa inti dari bacaan ini?' Pertanyaan ini termasuk...", ["Tidak penting", "Penting untuk pemahaman", "Membuang waktu", "Sulit"], 1, "Bertanya tentang inti bacaan membantu pemahaman."],
    ["'Mengapa kita harus membaca?' — pertanyaan ini mencari...", ["Tempat membaca", "Alasan membaca", "Cara membaca", "Waktu membaca"], 1, "'Mengapa' mencari alasan atau tujuan membaca."],
  ]),
}

export default konten
