import type { Konten } from "../types"
import { makeSoal } from "../types"

const konten: Konten = {
  belajar: {
    tujuan: [
      "Menyusun kalimat dengan Subjek, Predikat, dan Objek (SPO)",
      "Mengembangkan kalimat sederhana menjadi lebih lengkap",
      "Menulis paragraf pendek dengan kalimat yang baik",
    ],
    materi: [
      {
        judul: "Subjek, Predikat, Objek (SPO)",
        isi: [
          "Di kelas 1, kita belajar SP (Subjek dan Predikat). Sekarang di kelas 2, kita tambah Objek!",
          "",
          "✓ Subjek (S): pelaku kegiatan (siapa?).",
          "✓ Predikat (P): kegiatannya (melakukan apa?).",
          "✓ Objek (O): yang dikenai kegiatan (apa yang dikenai?).",
          "",
          "Contoh SPO:",
          "• Adik (S) memakan (P) kue (O).",
          "• Ibu (S) mencuci (P) piring (O).",
          "• Ayah (S) membaca (P) koran (O).",
          "",
          "[Ilustrasi: Tiga balok susun berwarna: Balok biru (SUBJEK) dengan gambar orang, balok hijau (PREDIKAT) dengan gambar tangan bergerak, balok oranye (OBJEK) dengan gambar benda. Panah menghubungkan S → P → O.]",
        ],
        contoh: [
          "Cari S, P, O dalam kalimat:",
          "",
          "1. 'Kucing memakan ikan.'",
          "   S = Kucing, P = memakan, O = ikan.",
          "",
          "2. 'Budi menendang bola.'",
          "   S = Budi, P = menendang, O = bola.",
          "",
          "3. 'Siti membaca buku.'",
          "   S = Siti, P = membaca, O = buku.",
          "",
          "PENTING: Tidak semua kalimat punya Objek. 'Ayah tidur' hanya SP, tidak ada O.",
        ],
        catatan: "Objek biasanya terletak setelah Predikat. Objek bisa berupa orang, hewan, atau benda.",
      },
      {
        judul: "Kalimat Lengkap dan Jelas",
        isi: [
          "Kalimat yang baik harus lengkap dan jelas. Apa maksudnya?",
          "",
          "1. LENGKAP: punya minimal S dan P (atau S-P-O).",
          "2. JELAS: pembaca langsung mengerti maksudnya.",
          "",
          "Bandingkan:",
          "✗ 'Membaca buku.' — tidak jelas siapa yang membaca.",
          "✓ 'Adik membaca buku.' — jelas, pelakunya Adik.",
          "",
          "✗ 'Budi.' — hanya satu kata, tidak jelas.",
          "✓ 'Budi bermain.' — jelas Budi melakukan apa.",
          "",
          "[Ilustrasi: Dua panel. Panel kiri (merah) berisi kalimat tidak lengkap 'Membaca buku.' dengan tanda silang. Panel kanan (hijau) berisi 'Adik membaca buku.' dengan tanda centang dan gambar adik membaca.]",
        ],
        contoh: [
          "Kalimat lengkap vs tidak lengkap:",
          "",
          "✗ 'Bola.' → tidak lengkap (hanya 1 kata)",
          "✗ 'Menendang bola.' → tidak jelas siapa yang menendang",
          "✓ 'Budi menendang bola.' → lengkap (S-P-O)",
          "",
          "Tips: Setelah menulis kalimat, baca ulang. Tanya 'Apakah kalimatku sudah jelas?'",
        ],
      },
      {
        judul: "Mengembangkan Kalimat",
        isi: [
          "Kalimat sederhana bisa dikembangkan dengan menambah keterangan: tempat, waktu, atau cara.",
          "",
          "KALIMAT DASAR → KALIMAT BERKEMBANG",
          "",
          "1. 'Budi bermain.'",
          "   → 'Budi bermain bola di halaman rumah.'",
          "",
          "2. 'Ibu memasak.'",
          "   → 'Ibu memasak sayur di dapur pagi ini.'",
          "",
          "3. 'Kucing tidur.'",
          "   → 'Kucing tidur di kursi ruang tamu.'",
          "",
          "[Ilustrasi: Tangga dengan 3 anak tangga. Anak tangga 1 tertulis 'Budi bermain.', anak tangga 2 'Budi bermain bola.', anak tangga 3 'Budi bermain bola di halaman rumah.' Semakin ke atas semakin panjang kalimatnya.]",
        ],
        contoh: [
          "Kembangkan kalimat ini:",
          "",
          "Dasar: 'Adik minum.'",
          "✓ Ditambah objek: 'Adik minum susu.'",
          "✓ Ditambah tempat: 'Adik minum susu di ruang makan.'",
          "✓ Ditambah waktu: 'Adik minum susu di ruang makan pagi ini.'",
          "",
          "Tips: Gunakan kata depan seperti 'di', 'ke', 'dari', 'pada' untuk menambah keterangan tempat dan waktu!",
        ],
      },
    ],
    rangkuman: [
      "[Ilustrasi: Sebuah rumah kalimat — atapnya SUBJEK, dindingnya PREDIKAT, pintunya OBJEK, halaman rumahnya KETERANGAN (tempat, waktu, cara). Semua bagian lengkap membuat rumah berdiri kokoh.]",
      "Kalimat SPO: Subjek (pelaku) + Predikat (kegiatan) + Objek (yang dikenai).",
      "Kalimat lengkap minimal punya Subjek dan Predikat.",
      "Kalimat bisa dikembangkan dengan menambah keterangan tempat, waktu, atau cara.",
      "Baca ulang kalimat untuk memastikan sudah jelas dan lengkap.",
    ],
  },
  latihan: makeSoal([
    ["'Ayah membaca koran.' — Objeknya adalah...", ["Ayah", "Membaca", "Koran", "Koran."], 2, "Koran adalah objek (yang dibaca oleh Ayah)."],
    ["'Siti menulis surat.' — Subjeknya adalah...", ["Menulis", "Surat", "Siti", "Siti."], 2, "Siti adalah pelaku (subjek) yang menulis surat."],
    ["Kalimat 'Membaca buku.' termasuk...", ["Lengkap", "Tidak lengkap", "Tidak jelas", "Salah ejaan"], 1, "'Membaca buku' tidak punya subjek — tidak jelas siapa yang membaca."],
    ["Kalimat berikut yang LENGKAP adalah...", ["Bola", "Menendang", "Budi menendang bola.", "di halaman"], 2, "'Budi menendang bola' punya S-P-O, lengkap."],
    ["Kata depan yang menunjukkan tempat adalah...", ["Di", "Dan", "Atau", "Karena"], 0, "'Di' adalah kata depan yang menunjukkan tempat."],
    ["'Ibu memasak sayur di dapur.' — kata 'di dapur' menunjukkan...", ["Waktu", "Tempat", "Cara", "Alat"], 1, "'Di dapur' adalah keterangan tempat."],
    ["Manakah yang merupakan kalimat SPO?", ["Adik tidur", "Ibu memasak sayur", "Budi bermain", "Kucing lucu"], 1, "'Ibu memasak sayur' punya S (Ibu), P (memasak), O (sayur)."],
    ["Predikat dalam kalimat 'Buku itu milik Budi' adalah...", ["Buku", "Itu", "Milik", "Budi"], 2, "'Milik' adalah predikat (kata kerja/kata keadaan)."],
    ["'Budi bermain bola di halaman' — jika ditambah waktu...", ["Budi bermain bola", "Budi bermain bola di halaman sore hari", "Budi bermain", "Budi dan bola"], 1, "Menambahkan 'sore hari' menunjukkan waktu."],
    ["Kalimat 'Kucing tidur' tidak punya...", ["Subjek", "Predikat", "Objek", "Kata"], 2, "'Kucing tidur' hanya SP, tidak punya Objek."],
  ]),
  praktik: {
    petunjuk: "Buatlah 3 kalimat SPO tentang kegiatan di sekolahmu. Lalu, kembangkan setiap kalimat dengan menambah keterangan tempat dan waktu!",
    tips: [
      "Tentukan kegiatannya: belajar, membaca, menulis, bermain?",
      "Siapa pelakunya? (S)",
      "Kegiatannya apa? (P)",
      "Apa yang dikenai kegiatan? (O)",
      "Kembangkan dengan keterangan tempat (di...) dan waktu (pada.../setelah...)",
    ],
    contoh: "Dasar: Guru mengajar. SPO: Guru mengajar murid. Dikembang: Guru mengajar murid di kelas pada pagi hari.",
  },
  kuis: makeSoal([
    ["'Adik memakan kue.' — Obyeknya adalah...", ["Adik", "Memakan", "Kue", "Kue."], 2, "Kue adalah objek yang dimakan oleh Adik."],
    ["Susunan SPO yang benar adalah...", ["P - S - O", "S - P - O", "O - S - P", "S - O - P"], 1, "Urutan yang benar: Subjek - Predikat - Objek."],
    ["'Kakak mencuci sepeda.' — Subjeknya...", ["Mencuci", "Sepeda", "Kakak", "Sepeda."], 2, "Kakak adalah pelaku (subjek)."],
    ["Kalimat yang hanya memiliki SP adalah...", ["Adik makan nasi", "Ayah tidur", "Ibu membeli sayur", "Budi membaca buku"], 1, "'Ayah tidur' hanya SP (tanpa objek)."],
    ["'Pada pagi hari, Budi berlari di taman.' — keterangan waktu adalah...", ["Pada pagi hari", "Budi", "Berlari", "Di taman"], 0, "'Pada pagi hari' menunjukkan waktu."],
    ["Kalimat 'Bermain bola' tidak punya...", ["Predikat", "Subjek", "Kata kerja", "Huruf"], 1, "'Bermain bola' tidak punya subjek (siapa yang bermain?)."],
    ["Kata 'di' termasuk...", ["Kata sifat", "Kata depan", "Kata benda", "Kata kerja"], 1, "'Di' adalah kata depan yang menunjukkan tempat."],
    ["'Ibu memasak di dapur' — kalimat ini bisa ditambah...", ["Waktu", "Warna", "Ukuran", "Bentuk"], 0, "Kalimat bisa dikembangkan dengan menambah waktu: Ibu memasak di dapur pagi ini."],
    ["Objek dalam kalimat 'Siti menyiram bunga' adalah...", ["Siti", "Menyiram", "Bunga", "Siram"], 2, "Bunga adalah objek yang disiram oleh Siti."],
    ["Kalimat yang baik harus...", ["Panjang", "Lengkap dan jelas", "Indah", "Susun acak"], 1, "Kalimat yang baik minimal lengkap (ada S-P) dan jelas maknanya."],
  ]),
}

export default konten
