import type { Konten } from "../types"
import { makeSoal } from "../types"

const konten: Konten = {
  belajar: {
    tujuan: [
      "Mengenal unsur-unsur puisi (diksi, rima, majas)",
      "Memahami majas personifikasi sederhana",
      "Menulis puisi 4-8 baris dengan tema bebas",
    ],
    materi: [
      {
        judul: "Unsur-Unsur Puisi",
        isi: [
          "Puisi bukan sekadar kumpulan kata indah. Puisi memiliki unsur-unsur yang membuatnya istimewa!",
          "",
          "✓ DIKSI — pilihan kata yang tepat dan indah.",
          "  Contoh: 'Mentari' lebih indah dari 'matahari'. 'Mengintip' lebih puitis dari 'melihat'.",
          "",
          "✓ RIMA — bunyi yang sama atau mirip di akhir baris.",
          "  Contoh: 'pagi' dan 'berlari' (rima i).",
          "",
          "✓ MAJAS — gaya bahasa kiasan untuk memperindah puisi.",
          "  Contoh: 'Angin malam berbisik' — seolah angin bisa bicara.",
          "",
          "[Ilustrasi: Tiga pilar berlabel DIKSI (kata-kata indah di sekeliling), RIMA (dua baris dengan warna akhir sama), MAJAS (gambar angin berwajah sedang berbisik). Gaya infografis puisi.]",
        ],
        contoh: [
          "Bandingkan kata biasa dan diksi puitis:",
          "",
          "BIASA: 'Matahari terbit di pagi hari.'",
          "PUISI: 'Sang mentari merekah di ufuk timur, menyapa dunia dengan kehangatan.'",
          "",
          "BIASA: 'Bunga itu harum sekali.'",
          "PUISI: 'Harum semerbak bunga mawar, memabukkan jiwa yang merindu.'",
          "",
          "Tips: Pilih kata yang jarang dipakai sehari-hari agar puisimu lebih indah!",
        ],
        catatan: "Diksi yang baik membuat puisi lebih hidup. Semakin banyak kamu membaca puisi, semakin kaya diksimu!",
      },
      {
        judul: "Majas Personifikasi",
        isi: [
          "Majas personifikasi adalah gaya bahasa yang membuat benda mati seolah-olah hidup seperti manusia.",
          "",
          "✓ Ciri: benda mati bisa bicara, tertawa, menari, berbisik, dll.",
          "",
          "Contoh personifikasi:",
          "",
          "1. 'Angin malam berbisik lembut di telingaku.'",
          "  — Angin tidak punya mulut, tapi seolah berbisik.",
          "",
          "2. 'Matahari tersenyum hangat di pagi hari.'",
          "  — Matahari tidak bisa tersenyum, tapi seolah melakukannya.",
          "",
          "3. 'Daun-daun menari riang ditiup angin.'",
          "  — Daun tidak bisa menari, tapi gerakannya seperti tarian.",
          "",
          "[Ilustrasi: Pemandangan alam dengan sentuhan personifikasi: matahari punya wajah tersenyum, awan berbentuk seperti kapas lembut, pohon melambai-lambaikan ranting seperti tangan, angin berwujud sosok transparan yang berbisik. Gaya ilustrasi fantasi.]",
        ],
        contoh: [
          "Perbandingan tanpa dan dengan personifikasi:",
          "",
          "TANPA PERSONIFIKASI: 'Angin bertiup kencang. Daun bergerak. Hujan turun.'",
          "  — Biasa, seperti laporan.",
          "",
          "DENGAN PERSONIFIKASI: 'Angin menderu marah, daun-daun berlari ketakutan, hujan menangis membasahi bumi.'",
          "  — Hidup, seolah benda punya perasaan!",
          "",
          "Tips: Coba bayangkan benda di sekitarmu punya perasaan. Apa yang akan mereka katakan? Itulah personifikasi!",
        ],
      },
      {
        judul: "Menulis Puisi 4-8 Baris",
        isi: [
          "Sekarang saatnya menulis puisi!",
          "",
          "Langkah-langkah:",
          "",
          "1. Tentukan tema (alam, persahabatan, cita-cita, sekolah).",
          "2. Tulis kata-kata kunci yang berhubungan dengan tema.",
          "3. Susun kata-kata itu menjadi baris puisi.",
          "4. Gunakan diksi yang indah.",
          "5. Tambahkan majas personifikasi jika bisa.",
          "6. Usahakan ada rima meskipun tidak sempurna.",
          "",
          "Contoh puisi 8 baris:",
          "",
          "\"Sekolahku\"",
          "Sekolahku, taman ilmuku",
          "Di sanalah aku belajar",
          "Guru membimbing dengan sabar",
          "Ilmu diberikan penuh cinta",
          "",
          "Sekolahku, rumah keduaku",
          "Teman-teman bermain bersama",
          "Belajar sambil tertawa gembira",
          "Kenangan indah takkan kulupa",
          "",
          "[Ilustrasi: Sebuah buku tulis terbuka berisi puisi yang ditulis tangan dengan tinta biru. Di pinggirnya ada gambar-gambar kecil: sekolah, pohon, buku, pensil. Gaya buku harian anak.]",
        ],
        contoh: [
          "Contoh puisi dengan majas personifikasi:",
          "",
          "\"Hujan\"",
          "Awan hitam menari di langit",
          "Angin berbisik, 'Hujan akan turun'",
          "Rintik air mengetuk jendela",
          "Membangunkan bunga yang tertidur",
          "",
          "Tanaman menyambut dengan suka cita",
          "Daun-daun menari basah diguyur",
          "Hujan, kau bagai sahabat setia",
          "Menyirami bumi yang merindu",
          "",
          "Tips: Gunakan kata 'bagai', 'laksana', 'seperti' untuk perbandingan dalam puisi!",
        ],
      },
    ],
    rangkuman: [
      "[Ilustrasi: Langit malam dengan bintang-bintang bertuliskan DIKSI, RIMA, MAJAS. Di bawahnya ada penyair cilik sedang menulis dengan pena bercahaya. Gaya ilustrasi magis-edukatif.]",
      "Unsur puisi: diksi (pilihan kata indah), rima (bunyi akhir), majas (gaya bahasa).",
      "Personifikasi: majas yang membuat benda mati seolah hidup/manusiawi.",
      "Menulis puisi: tentukan tema, gunakan diksi indah, tambahkan majas, usahakan rima.",
      "Semakin sering membaca puisi, semakin kaya kosa kata puitismu.",
    ],
  },
  latihan: makeSoal([
    ["Diksi dalam puisi berarti...", ["Bunyi akhir", "Pilihan kata", "Gaya bahasa", "Jumlah baris"], 1, "Diksi adalah pilihan kata yang tepat dan indah dalam puisi."],
    ["Rima adalah...", ["Kata utama", "Bunyi sama di akhir baris", "Judul puisi", "Tema puisi"], 1, "Rima adalah bunyi yang sama atau mirip di akhir baris."],
    ["'Angin menari-nari di atas dedaunan' — ini contoh majas...", ["Personifikasi", "Metafora", "Hiperbola", "Litotes"], 0, "Angin seolah-olah menari — personifikasi (benda mati seperti manusia)."],
    ["Kata 'mentari' lebih puitis dari...", ["Bulan", "Matahari", "Bintang", "Awan"], 1, "'Mentari' adalah diksi puitis untuk 'matahari'."],
    ["Puisi 'Sekolahku' bertema tentang...", ["Alam", "Sekolah", "Cinta", "Persahabatan"], 1, "Puisi itu menceritakan tentang sekolah."],
    ["Majas personifikasi membuat benda mati seolah...", ["Hidup/manusiawi", "Mati", "Jauh", "Keras"], 0, "Personifikasi membuat benda mati seolah hidup seperti manusia."],
    ["Rima a-b-a-b berarti...", ["Baris 1=2, 3=4", "Baris 1=3, 2=4", "Baris 1=4, 2=3", "Semua sama"], 1, "Rima a-b-a-b: baris 1 dan 3 berima, baris 2 dan 4 berima."],
    ["'Bunga mawar tersenyum padaku' — benda yang dipersonifikasi adalah...", ["Aku", "Bunga mawar", "Senyum", "Padaku"], 1, "Bunga mawar dipersonifikasi karena 'tersenyum'."],
    ["Contoh diksi puitis untuk 'indah' adalah...", ["Bagus", "Elok", "Cantik", "Baik"], 1, "'Elok' adalah diksi yang lebih puitis untuk 'indah'."],
    ["Puisi yang baik memadukan...", ["Diksi, rima, majas", "Panjang dan pendek", "Lucu dan sedih", "cepat dan lambat"], 0, "Puisi yang baik memadukan diksi indah, rima, dan majas."],
  ]),
  praktik: {
    petunjuk: "Buatlah puisi 8 baris dengan tema 'ALAM'. Gunakan diksi yang indah, usahakan ada rima, dan sertakan minimal satu majas personifikasi!",
    tips: [
      "Tulis kata-kata kunci tentang alam: hijau, segar, indah, mentari, angin, pelangi",
      "Gunakan diksi puitis: mentari (matahari), semburat (warna), semilir (angin)",
      "Buat benda mati jadi hidup: 'Matahari tersenyum', 'Angin berbisik', 'Daun menari'",
      "Baca keras-keras, perbaiki jika ada kata yang kurang pas",
    ],
    contoh: "'Alamku' / Mentari pagi tersenyum ramah / Menyapa bumi dengan cahaya / Angin semilir berbisik lembut / Daun-daun menari penuh suka cita / Burung berkicau merdu sekali / Seolah bernyanyi untuk dunia / Alam indah anugerah Tuhan / Mensyukuri selalu setiap masa.",
  },
  kuis: makeSoal([
    ["'Sang surya mulai merangkak naik' — kata 'surya' berarti...", ["Bulan", "Matahari", "Bintang", "Awan"], 1, "'Surya' berarti matahari — diksi puitis."],
    ["'Matahari' dalam puisi sering disebut...", ["Mentari", "Bulan purnama", "Bintang kejora", "Rembulan"], 0, "'Mentari' adalah kata puitis untuk matahari."],
    ["Contoh majas personifikasi yang tepat adalah...", ["Budi berlari kencang", "Awan hitam menangis", "Siti anak rajin", "Kucing itu lucu"], 1, "'Awan menangis' — awan dipersonifikasi seolah bisa menangis (hujan)."],
    ["'Gemercik air sungai bernyanyi riang' — majas yang digunakan...", ["Metafora", "Personifikasi", "Hiperbola", "Ironi"], 1, "Air sungai bernyanyi — personifikasi."],
    ["Rima pada kata 'pagi' dan 'berlari' adalah...", ["Sama (i)", "Berbeda", "Sempurna", "Hampir"], 0, "'Pagi' dan 'berlari' memiliki bunyi akhir 'i' (rima sama)."],
    ["Tujuan penggunaan majas dalam puisi adalah...", ["Membingungkan", "Memperindah puisi", "Membuat panjang", "Menyembunyikan arti"], 1, "Majas digunakan untuk memperindah puisi."],
    ["'Bulan purnama tersenyum di malam hari' — yang dipersonifikasi...", ["Malam", "Bulan", "Aku", "Hari"], 1, "Bulan purnama dipersonifikasi karena 'tersenyum'."],
    ["Kata 'semerbak' berarti...", ["Warna", "Bau harum", "Bentuk", "Rasa"], 1, "'Semerbak' berarti bau yang harum dan menyebar."],
    ["Puisi 'Alamku' bertema...", ["Persahabatan", "Alam/lingkungan", "Keluarga", "Sekolah"], 1, "Puisi 'Alamku' bertema tentang alam."],
    ["Satu bait puisi bisa terdiri dari...", ["4-8 baris", "2 baris harus", "10 baris", "1 baris"], 0, "Satu bait puisi bisa 4 baris, 6 baris, atau 8 baris, tergantung keinginan penyair."],
  ]),
}

export default konten
