import type { Konten } from "../types"
import { makeSoal } from "../types"

const konten: Konten = {
  belajar: {
    tujuan: [
      "Memahami pengertian dan tujuan wawancara",
      "Menyusun daftar pertanyaan wawancara",
      "Melakukan wawancara sederhana dengan narasumber",
    ],
    materi: [
      {
        judul: "Apa Itu Wawancara?",
        isi: [
          "Pernahkah kamu melihat reporter di TV yang mewawancarai seseorang?",
          "",
          "Wawancara adalah kegiatan tanya jawab antara pewawancara dan narasumber untuk mendapatkan informasi.",
          "",
          "Istilah penting:",
          "1. PEWAWANCARA (interviewer) — orang yang bertanya.",
          "2. NARASUMBER (responden) — orang yang memberi jawaban.",
          "3. DAFTAR PERTANYAAN — pertanyaan yang sudah disiapkan.",
          "",
          "Tujuan wawancara:",
          "✓ Mendapatkan informasi langsung dari sumbernya.",
          "✓ Mengetahui pendapat atau pengalaman seseorang.",
          "✓ Mengumpulkan data untuk tugas atau laporan.",
          "",
          "[Ilustrasi: Seorang anak memegang mik imajiner (atau botol sampo) sedang mewawancarai temannya yang duduk di kursi. Di latar belakang ada papan tulis bertuliskan 'WAWANCARA'. Gaya ilustrasi reporter cilik.]",
        ],
        contoh: [
          "Contoh situasi wawancara:",
          "",
          "1. Pewawancara: 'Selamat pagi, Kak. Boleh aku bertanya?'",
          "2. Narasumber: 'Selamat pagi. Tentu saja, silakan.'",
          "3. Pewawancara: 'Kak, sudah berapa lama Kakak belajar melukis?'",
          "4. Narasumber: 'Aku sudah belajar melukis sejak kelas 1 SD.'",
          "",
          "Tips: Saat mewawancarai, bersikaplah sopan dan ramah!",
        ],
        catatan: "Wawancara berbeda dengan tanya jawab biasa. Wawancara sudah direncanakan, ada tujuan tertentu, dan pertanyaan disiapkan sebelumnya.",
      },
      {
        judul: "Menyusun Pertanyaan Wawancara",
        isi: [
          "Kunci wawancara yang baik adalah pertanyaan yang baik!",
          "",
          "Gunakan kata tanya 5W+1H:",
          "",
          "1. APA — menanyakan hal atau kegiatan.",
          "  'Apa yang membuatmu suka melukis?'",
          "",
          "2. SIAPA — menanyakan orang.",
          "  'Siapa gurumu pertama kali?'",
          "",
          "3. DI MANA — menanyakan tempat.",
          "  'Di mana kamu biasa melukis?'",
          "",
          "4. KAPAN — menanyakan waktu.",
          "  'Kapan pertama kali kamu melukis?'",
          "",
          "5. MENGAPA — menanyakan alasan.",
          "  'Mengapa kamu memilih tema alam?'",
          "",
          "6. BAGAIMANA — menanyakan cara.",
          "  'Bagaimana cara kamu mencampur warna?'",
          "",
          "[Ilustrasi: Papan tulis kecil dengan 6 gelembung kata tanya berwarna-warni. Setiap gelembung berisi contoh pertanyaan. Seorang anak memegang buku catatan berisi daftar pertanyaan. Gaya ilustrasi anak SD.]",
        ],
        contoh: [
          "Membandingkan pertanyaan baik dan kurang baik:",
          "",
          "✗ KURANG BAIK: 'Kamu suka melukis ya?' — hanya jawab ya/tidak.",
          "✓ BAIK: 'Apa yang membuatmu tertarik pada dunia melukis?' — jawabannya panjang.",
          "",
          "✗ KURANG BAIK: 'Hobimu apa?' — terlalu umum.",
          "✓ BAIK: 'Bagaimana perasaanmu saat pertama kali berhasil melukis pemandangan?' — spesifik.",
          "",
          "PENTING: Buat pertanyaan terbuka (bukan ya/tidak) agar narasumber bisa bercerita lebih banyak!",
        ],
      },
      {
        judul: "Melakukan Wawancara",
        isi: [
          "Setelah pertanyaan siap, saatnya wawancara!",
          "",
          "Langkah-langkah wawancara:",
          "",
          "1. Perkenalkan diri dan jelaskan tujuan wawancara.",
          "2. Mulai dengan pertanyaan ringan terlebih dahulu.",
          "3. Ajukan pertanyaan sesuai daftar, boleh bertanya tambahan.",
          "4. Catat atau rekam jawaban narasumber (minta izin dulu).",
          "5. Akhiri dengan ucapan terima kasih.",
          "",
          "Etika wawancara:",
          "• Bersikap sopan dan ramah.",
          "• Jangan memotong pembicaraan narasumber.",
          "• Dengarkan dengan saksama.",
          "• Catat poin-poin penting.",
          "",
          "[Ilustrasi: Dua anak duduk berhadapan. Satu bertanya sambil mencatat di buku, satu lagi menjawab dengan tersenyum. Di atas kepala mereka ada gelembung dialog berisi tanya jawab. Gaya ilustrasi percakapan anak-anak.]",
        ],
        contoh: [
          "Contoh pembukaan wawancara:",
          "",
          "'Selamat pagi, Kak Rina. Perkenalkan, aku Budi dari kelas 3 SD. Aku ingin mewawancarai Kakak tentang hobi melukis Kakak untuk tugas sekolah. Apakah Kakak bersedia?'",
          "",
          "Contoh penutup wawancara:",
          "",
          "'Terima kasih banyak, Kak Rina, atas waktunya. Aku mendapat banyak informasi baru tentang melukis. Semoga sukses selalu untuk Kakak!'",
          "",
          "Tips: Sebelum mulai, tanya dulu 'Apakah Kakak bersedia saya wawancarai?' — itu sopan!",
        ],
      },
    ],
    rangkuman: [
      "[Ilustrasi: Lembar kerja wawancara dengan bagian-bagian: PERKENALAN, PERTANYAAN 1-5, CATATAN JAWABAN, KESIMPULAN. Ada gambar mikrofon dan buku catatan.]",
      "Wawancara: tanya jawab terencana antara pewawancara dan narasumber untuk mendapat informasi.",
      "Gunakan 5W+1H untuk menyusun pertanyaan.",
      "Buat pertanyaan terbuka agar narasumber bisa bercerita panjang.",
      "Etika: sopan, jangan potong bicara, catat jawaban, ucapkan terima kasih.",
    ],
  },
  latihan: makeSoal([
    ["Orang yang diwawancarai disebut...", ["Pewawancara", "Narasumber", "Reporter", "Penonton"], 1, "Narasumber adalah orang yang memberikan informasi dalam wawancara."],
    ["Tujuan wawancara adalah...", ["Bertengkar", "Mendapatkan informasi", "Bercerita", "Bernyanyi"], 1, "Tujuan wawancara adalah mendapatkan informasi dari narasumber."],
    ["Pertanyaan yang baik dalam wawancara adalah...", ["Ya/tidak", "Terbuka (mengapa, bagaimana)", "Pendek", "Tidak jelas"], 1, "Pertanyaan terbuka membuat narasumber bisa menjelaskan lebih banyak."],
    ["'Mengapa kamu suka membaca?' — kata tanya ini menanyakan...", ["Waktu", "Alasan", "Tempat", "Cara"], 1, "'Mengapa' menanyakan alasan atau sebab."],
    ["Sebelum wawancara dimulai, kita harus...", ["Langsung bertanya", "Perkenalan diri dan tujuan", "Pulang", "Bernyanyi"], 1, "Perkenalkan diri dan jelaskan tujuan wawancara terlebih dahulu."],
    ["Etika yang baik saat wawancara adalah...", ["Memotong bicara", "Mendengarkan dengan saksama", "Bermain HP", "Membaca buku"], 1, "Dengarkan narasumber dengan saksama, jangan memotong."],
    ["Pertanyaan 'Apakah kamu suka melukis?' termasuk...", ["Terbuka", "Tertutup (ya/tidak)", "Panjang", "Sulit"], 1, "Pertanyaan itu hanya bisa dijawab 'ya' atau 'tidak'."],
    ["'Di mana kamu belajar menari?' — kata tanya yang digunakan...", ["Apa", "Di mana", "Kapan", "Siapa"], 1, "'Di mana' menanyakan tempat."],
    ["Hal pertama yang dilakukan saat wawancara adalah...", ["Mengucap salam dan perkenalan", "Langsung bertanya", "Mencatat", "Pulang"], 0, "Awali dengan salam dan perkenalan diri."],
    ["Setelah wawancara selesai, kita mengucapkan...", ["Selamat tinggal", "Terima kasih", "Sampai jumpa", "Maaf"], 1, "Ucapkan terima kasih atas waktu dan informasi yang diberikan."],
  ]),
  praktik: {
    petunjuk: "Lakukan wawancara singkat dengan salah satu teman atau anggota keluargamu tentang hobi mereka! Siapkan 5 pertanyaan terlebih dahulu, lakukan wawancara, lalu catat hasilnya.",
    tips: [
      "Cari tahu dulu hobi orang yang akan diwawancarai",
      "Buat 5 pertanyaan menggunakan 5W+1H",
      "Minta izin dan jelaskan tujuan wawancara",
      "Catat jawabannya di buku",
      "Akhiri dengan terima kasih",
    ],
    contoh: "Pewawancara: Budi. Narasumber: Kakak (Sari), hobi: memasak. Pertanyaan: 1. Sejak kapan suka memasak? 2. Apa masakan pertama yang berhasil? 3. Di mana belajar memasak? 4. Mengapa suka memasak? 5. Bagaimana cara membuat kue favoritmu? Hasil: Kak Sari suka memasak sejak kelas 4 SD. Masakan pertama: telur dadar. Belajar dari ibu di dapur rumah.",
  },
  kuis: makeSoal([
    ["Pewawancara adalah orang yang...", ["Menjawab", "Bertanya", "Mencatat", "Menonton"], 1, "Pewawancara mengajukan pertanyaan."],
    ["Pertanyaan 'Bagaimana caranya?' menggunakan kata tanya...", ["Apa", "Bagaimana", "Mengapa", "Di mana"], 1, "'Bagaimana' menanyakan cara atau proses."],
    ["Wawancara yang baik dilakukan secara...", ["Tergesa-gesa", "Terencana dan sopan", "Marah", "Bercanda"], 1, "Wawancara dilakukan secara terencana dan sopan."],
    ["Kata tanya 'kapan' digunakan untuk menanyakan...", ["Tempat", "Waktu", "Alasan", "Cara"], 1, "'Kapan' menanyakan waktu."],
    ["Saat narasumber bicara, pewawancara sebaiknya...", ["Memotong", "Mendengarkan dan mencatat", "Bermain", "Menelepon"], 1, "Dengarkan dan catat informasi penting."],
    ["'Siapa guru pertama yang mengajarimu melukis?' — menanyakan...", ["Orang", "Tempat", "Waktu", "Alat"], 0, "'Siapa' menanyakan orang."],
    ["Hasil wawancara sebaiknya...", ["Dilupakan", "Dicatat dan dirangkum", "Dihafal", "Dibuang"], 1, "Catat dan rangkum hasil wawancara agar informasinya tidak hilang."],
    ["Pertanyaan tertutup hanya bisa dijawab...", ["Panjang", "Ya atau tidak", "Cerita", "Alasan"], 1, "Pertanyaan tertutup seperti 'Apakah...' hanya dijawab ya/tidak."],
    ["Tujuan perkenalan sebelum wawancara adalah...", ["Agar narasumber kenal dan percaya", "Membuang waktu", "Agar panjang", "Tidak penting"], 0, "Perkenalan membangun kepercayaan dengan narasumber."],
    ["Wawancara termasuk kegiatan...", ["Bertanya jawab untuk informasi", "Bermain", "Belajar sendiri", "Menulis"], 0, "Wawancara adalah tanya jawab untuk mendapatkan informasi."],
  ]),
}

export default konten
