import type { Konten } from "../types"
import { makeSoal } from "../types"

const konten: Konten = {
  belajar: {
    tujuan: [
      "Memahami jenis-jenis pantun (nasihat, jenaka, teka-teki)",
      "Menganalisis sampiran dan isi dalam pantun",
      "Menciptakan pantun nasihat dan jenaka",
    ],
    materi: [
      {
        judul: "Jenis-Jenis Pantun",
        isi: [
          "Di kelas 2 kita sudah belajar pantun. Sekarang kita akan mendalami jenis-jenisnya!",
          "",
          "✓ Pantun adalah puisi lama 4 baris dengan sajak a-b-a-b.",
          "",
          "Ada beberapa jenis pantun:",
          "",
          "1. PANTUN NASIHAT — berisi pesan moral atau nasihat.",
          "  Contoh: 'Rajin belajar setiap hari / Agar pintar dan berilmu'",
          "",
          "2. PANTUN JENAKA — berisi humor atau kelucuan.",
          "  Contoh: 'Anak monyet makan pisang / Dimakan sambil bergelayutan'",
          "",
          "3. PANTUN TEKA-TEKI — berisi tebakan yang harus dijawab.",
          "  Contoh: 'Kalau tuan pergi ke kota / Jangan lupa bawa ketan'",
          "",
          "[Ilustrasi: Tiga kartu besar: Pantun Nasihat (gambar anak belajar), Pantun Jenaka (gambar monyet lucu), Pantun Teka-teki (gambar tanda tanya). Setiap kartu berisi contoh pantun. Gaya kartu permainan anak-anak.]",
        ],
        contoh: [
          "Contoh pantun nasihat:",
          "'Pergi ke kebun memetik jambu'",
          "'Jambu dipetik dalam keranjang'",
          "'Belajar jangan pernah ragu'",
          "'Agar kelak jadi orang terdepan'",
          "",
          "Contoh pantun jenaka:",
          "'Anak kucing turun ke bawah'",
          "'Mencari ikan di kolam dangkal'",
          "'Gigi ompong suka ketawa'",
          "'Lucu sekali kelihatannya'",
          "",
          "Tips: Pantun jenaka tidak perlu serius, yang penting lucu dan menghibur!",
        ],
      },
      {
        judul: "Ciri Khas Setiap Jenis Pantun",
        isi: [
          "Setiap jenis pantun punya ciri khas:",
          "",
          "✓ PANTUN NASIHAT:",
          "  • Berisi nasihat, ajakan berbuat baik.",
          "  • Kata-kata: jangan, rajin, hormati, sayangi.",
          "  • Tujuan: mendidik pembaca.",
          "",
          "✓ PANTUN JENAKA:",
          "  • Berisi kelucuan atau hal menggelikan.",
          "  • Membuat orang tertawa.",
          "  • Tidak perlu pesan moral.",
          "",
          "✓ PANTUN TEKA-TEKI:",
          "  • Baris 3-4 berisi tebakan.",
          "  • Pendengar harus menebak jawabannya.",
          "  • Biasanya diawali 'Kalau tuan...' atau 'Coba tebak...'",
          "",
          "[Ilustrasi: Tiga kotak karakter. Kotak 1: Wajah bijak (nasihat) dengan label 'NASIHAT'. Kotak 2: Wajah tertawa (jenaka) dengan label 'JENAKA'. Kotak 3: Wajah bingung (teka-teki) dengan tanda tanya di atas kepala.]",
        ],
        contoh: [
          "Contoh pantun teka-teki:",
          "",
          "'Kalau tuan pergi ke kota'",
          "'Jangan lupa membawa bedak'",
          "'Coba tebak, hewan apakah dia'",
          "'Berkepala dua, berbadan satu?'",
          "(Jawaban: gunting)",
          "",
          "Perhatikan:",
          "✓ Sampiran: pergi ke kota, membawa bedak (tidak berhubungan dengan tebakan)",
          "✓ Isi: tebakan 'hewan berkepala dua, berbadan satu'",
        ],
        catatan: "Pantun teka-teki biasanya diakhiri dengan pertanyaan atau ajakan menebak. Jawaban bisa berupa benda, hewan, atau tumbuhan di sekitar kita.",
      },
      {
        judul: "Menciptakan Pantun",
        isi: [
          "Sekarang, ayo menciptakan pantun!",
          "",
          "Cara membuat pantun:",
          "",
          "1. Tentukan jenis pantun (nasihat/jenaka/teka-teki).",
          "2. Tentukan isi (baris 3-4) — pesan atau kelucuan.",
          "3. Cari sampiran (baris 1-2) yang berima dengan isi.",
          "4. Pastikan sajak a-b-a-b.",
          "5. Usahakan setiap baris 8-12 suku kata.",
          "",
          "Tips: Buat isi dulu, baru sampiran! lebih mudah.",
          "",
          "Contoh membuat pantun nasihat:",
          "1. Isi: 'Hormati ibu dan ayahmu' (baris 3). 'Agar hidupmu penuh berkah' (baris 4). Rima: u - ah.",
          "2. Sampiran: 'Pergi ke sawah membawa cangkul' (baris 1, rima u). 'Jangan lupa bawa topi' (baris 2, rima i → tidak cocok). Cari lagi...",
          "3. Sampiran yang pas: 'Pergi ke sawah membawa cangkul' (u). 'Jangan lupa membawa amplop' (op → tidak). Nah, 'Pergi ke sawah membawa cangkul' (u) / 'Cangkul dipakai untuk mencangkul' (ul). Hmm, 'Pergi ke masjid bawa mukena' (a) / 'Mukena putih penuh berkah' (ah). Ya, 'berkah' sama dengan 'berkah'!",
          "",
          "Jadi: 'Pergi ke masjid bawa mukena' (a)",
          "'Mukena putih penuh berkah' (b)",
          "'Hormati ibu dan ayahmu' (a)",
          "'Agar hidupmu penuh berkah' (b)",
          "",
          "[Ilustrasi: Meja dengan kertas coretan pembuatan pantun. Ada kata-kata dicoret-coret, rima dicocokkan, dan hasil akhir pantun yang rapi. Gaya proses kreatif anak-anak.]",
        ],
        contoh: [
          "Contoh pantun buatan anak:",
          "",
          "Pantun Nasihat Belajar:",
          "'Pagi-pagi makan ketupat'",
          "'Ketupat dimakan dengan sambal'",
          "'Belajar sungguh-sungguh, jangan keparat'",
          "'Agar masa depan gemilang dan tidak gagal'",
          "",
          "Pantun Jenaka:",
          "'Anak kucing naik pohon'",
          "'Pohonnya tinggi menjulang'",
          "'Lihat teman gigi ompong'",
          "'Tertawa-tawa terpingkal-pingkal'",
        ],
      },
    ],
    rangkuman: [
      "[Ilustrasi: Kumpulan pantun dalam bentuk gulungan kertas bertali. Setiap gulungan bertuliskan jenis pantun: 'Nasihat', 'Jenaka', 'Teka-teki'. Ada yang sudah terbuka memperlihatkan isi pantun. Gaya perpustakaan mini.]",
      "Pantun nasihat: berisi pesan moral dan nasihat baik.",
      "Pantun jenaka: berisi kelucuan untuk menghibur.",
      "Pantun teka-teki: berisi tebakan yang harus dijawab.",
      "Cara membuat: tentukan isi (baris 3-4) dulu, lalu cari sampiran (baris 1-2) yang berima.",
    ],
  },
  latihan: makeSoal([
    ["Pantun nasihat berisi...", ["Kelucuan", "Pesan moral/nasihat", "Tebakan", "Cerita"], 1, "Pantun nasihat berisi pesan moral dan nasihat."],
    ["Pantun jenaka bertujuan...", ["Mendidik", "Menghibur/membuat tertawa", "Bertanya", "Melaporkan"], 1, "Pantun jenaka bertujuan menghibur."],
    ["Pantun teka-teki diakhiri dengan...", ["Tanda titik", "Tebakan pertanyaan", "Tanda seru", "Tanya"], 1, "Pantun teka-teki berisi tebakan di baris isi."],
    ["Rima pantun adalah...", ["a-a-a-a", "a-b-a-b", "a-b-b-a", "b-a-b-a"], 1, "Pantun bersajak a-b-a-b."],
    ["Sampiran dalam pantun adalah baris...", ["1-2", "3-4", "2-3", "1-4"], 0, "Sampiran adalah baris 1 dan 2."],
    ["'Jangan suka berkata bohong' — ini cocok untuk pantun...", ["Jenaka", "Nasihat", "Teka-teki", "Cinta"], 1, "'Jangan bohong' adalah nasihat."],
    ["Pantun teka-teki biasanya diawali kata...", ["Ayo", "Kalau tuan", "Jangan", "Pergi"], 1, "Banyak pantun teka-teki diawali 'Kalau tuan...'"],
    ["'Anak monyet naik ke atap' — ini baris...", ["Isi", "Sampiran", "Judul", "Penutup"], 1, "'Anak monyet naik ke atap' adalah sampiran (baris 1)."],
    ["Mana yang termasuk pantun jenaka?", ["Rajin-rajinlah belajar", "Gigi ompong suka ketawa", "Hormati orang tua", "Buang sampah pada tempatnya"], 1, "'Gigi ompong suka ketawa' lucu, termasuk jenaka."],
    ["Isi pantun adalah baris yang menyampaikan...", ["Pengantar", "Pesan utama", "Sampiran", "Hiasan"], 1, "Isi pantun (baris 3-4) menyampaikan pesan utama."],
  ]),
  praktik: {
    petunjuk: "Buatlah 3 pantun dengan jenis berbeda: satu pantun nasihat, satu pantun jenaka, dan satu pantun teka-teki!",
    tips: [
      "Tentukan isi (baris 3-4) terlebih dahulu",
      "Cari kata berima yang cocok untuk sampiran",
      "Untuk pantun jenaka, pikirkan hal lucu yang pernah kamu alami",
      "Untuk pantun teka-teki, pilih benda sederhana sebagai jawaban",
    ],
    contoh: "NASIHAT: 'Pergi ke kebun memetik jambu / Jambu dimakan dengan gula / Belajar jangan pernah ragu / Agar kelak berguna semua.' JENAKA: 'Anak kucing naik perahu / Perahu bocor tenggelam sudah / Melihat teman gigi ompong / Tertawa sampai terpingkal-pingkal.' TEKA-TEKI: 'Kalau tuan pergi ke pasar / Jangan lupa membawa kain / Coba tebak, apakah dia / Semakin diisi semakin ringan?' (Jawaban: balon).",
  },
  kuis: makeSoal([
    ["Pantun 'Rajin belajar setiap hari / Agar pintar dan berilmu' termasuk...", ["Jenaka", "Nasihat", "Teka-teki", "Cinta"], 1, "'Rajin belajar' adalah nasihat."],
    ["Pantun terdiri dari... baris", ["2", "4", "6", "8"], 1, "Pantun terdiri dari 4 baris."],
    ["Sampiran pantun berfungsi sebagai...", ["Pesan utama", "Pengantar", "Kesimpulan", "Penutup"], 1, "Sampiran adalah pengantar sebelum isi."],
    ["'Kalau tuan pergi ke kota' — baris ini biasanya untuk pantun...", ["Nasihat", "Teka-teki", "Jenaka", "Semua"], 1, "'Kalau tuan' adalah ciri khas pantun teka-teki."],
    ["Pembuatan pantun sebaiknya dimulai dari...", ["Sampiran", "Isi", "Judul", "Baris 1"], 1, "Lebih mudah membuat isi (pesan) dulu, baru sampiran."],
    ["Mana kata berima dengan 'belajar'?", ["Pintar", "Sekolah", "Buku", "Tugas"], 1, "'Belajar' berima dengan... 'ajar'. Cari kata dengan 'ar': 'sekolah' tidak, 'pintar' (tar) — ya! 'pintar' dan 'belajar' punya rima 'ar'."],
    ["Rima sempurna: baris 1 dan 3 berima...", ["Sama", "Berbeda", "Konsonan", "Vokal"], 0, "Rima a-b-a-b berarti baris 1 dan 3 berima sama."],
    ["Pantun jenaka tidak perlu...", ["Sampiran", "Pesan moral", "Isi", "Rima"], 1, "Pantun jenaka tidak perlu pesan moral, cukup lucu."],
    ["Jawaban pantun teka-teki 'Semakin diisi semakin ringan?' adalah...", ["Air", "Balon", "Batu", "Pasir"], 1, "Balon semakin diisi udara semakin ringan (naik)."],
    ["Pantun nasihat biasanya bertema...", ["Lucu", "Kebaikan/moral", "Tebakan", "Permainan"], 1, "Pantun nasihat bertema kebaikan dan moral."],
  ]),
}

export default konten
