import type { Konten } from "../types"
import { makeSoal } from "../types"

const konten: Konten = {
  belajar: {
    tujuan: [
      "Memahami struktur dongeng (awal, konflik, penyelesaian)",
      "Menganalisis watak tokoh dalam dongeng",
      "Menulis dongeng pendek dengan struktur yang benar",
    ],
    materi: [
      {
        judul: "Struktur Dongeng",
        isi: [
          "Setiap dongeng memiliki struktur yang khas, seperti bangunan yang punya fondasi, dinding, dan atap.",
          "",
          "Struktur dongeng:",
          "",
          "1. AWAL (Orientasi) — pengenalan tokoh, tempat, dan waktu.",
          "  Contoh: 'Pada zaman dahulu, di sebuah desa di Jawa Tengah, hiduplah seorang janda miskin bersama anaknya yang bernama Bawang Putih.'",
          "",
          "2. KONFLIK (Komplikasi) — munculnya masalah atau pertentangan.",
          "  Contoh: 'Bawang Merah dan ibunya selalu iri pada Bawang Putih. Mereka menyuruh Bawang Putih melakukan pekerjaan berat.'",
          "",
          "3. PENYELESAIAN (Resolusi) — masalah selesai, biasanya tokoh baik bahagia.",
          "  Contoh: 'Akhirnya Bawang Putih hidup bahagia bersama suami pangeran, sedangkan Bawang Merah mendapat balasan atas kejahatannya.'",
          "",
          "[Ilustrasi: Sebuah jembatan dengan tiga tiang penyangga. Tiang 1 'AWAL' — gambar perkenalan. Tiang 2 'KONFLIK' — gambar masalah. Tiang 3 'SELESAI' — gambar tokoh tersenyum. Gaya ilustrasi anak-anak.]",
        ],
        contoh: [
          "Analisis struktur dongeng 'Kura-kura dan Kelinci':",
          "",
          "AWAL: Kura-kura dan Kelinci tinggal di hutan. Kelinci sombong dengan kecepatannya.",
          "KONFLIK: Kelinci menantang kura-kura lomba lari. Kura-kura menerima. Kelinci berlari cepat lalu tidur di tengah jalan.",
          "PENYELESAIAN: Kura-kura terus berjalan tanpa berhenti dan mencapai garis finish lebih dulu. Kelinci kalah karena sombong.",
          "",
          "Tips: Saat membaca dongeng, coba identifikasi bagian awal, konflik, dan penyelesaiannya!",
        ],
      },
      {
        judul: "Watak Tokoh dalam Dongeng",
        isi: [
          "Watak adalah sifat atau karakter tokoh dalam cerita. Watak bisa diketahui dari:",
          "",
          "1. APA YANG DIKATAKAN tokoh — dialog.",
          "2. APA YANG DILAKUKAN tokoh — tindakan.",
          "3. APA YANG DIKATAKAN TOKOH LAIN tentang tokoh tersebut.",
          "4. PENGGAMBARAN LANGSUNG oleh penulis.",
          "",
          "Contoh watak:",
          "• Kancil: cerdik, licik, cerdas.",
          "• Bawang Putih: rajin, jujur, sabar.",
          "• Bawang Merah: malas, iri, pemarah.",
          "• Kelinci: sombong, angkuh, ceroboh.",
          "• Kura-kura: tekun, sabar, pantang menyerah.",
          "",
          "[Ilustrasi: Lima lingkaran wajah dengan ekspresi dan label watak. Wajah 1: Kancil (senyum licik, mata sipit) — CERDIK. Wajah 2: Bawang Putih (tersenyum lembut) — BAIK. Wajah 3: Bawang Merah (cemberut) — IRI. Wajah 4: Kelinci (angkat hidung) — SOMBONG. Wajah 5: Kura-kura (tekad kuat) — TEKUN.]",
        ],
        contoh: [
          "Cara menentukan watak tokoh:",
          "",
          "Perhatikan dialog ini:",
          "'Aku yang paling cepat di hutan ini! Tidak ada yang bisa mengalahkanku!' seru Kelinci.",
          "",
          "✓ Dari dialog itu, kita tahu Kelinci bersifat sombong dan angkuh.",
          "",
          "Perhatikan tindakan:",
          "'Bawang Putih bangun sebelum subuh, menimba air, menyapu halaman, lalu memasak.'",
          "",
          "✓ Dari tindakan itu, kita tahu Bawang Putih bersifat rajin.",
        ],
        catatan: "Satu tokoh bisa memiliki lebih dari satu watak. Misalnya: Kancil cerdik tapi juga suka menipu. Watak tokoh bisa baik, buruk, atau campuran.",
      },
      {
        judul: "Menulis Dongeng Pendek",
        isi: [
          "Sekarang giliranmu menulis dongeng!",
          "",
          "Langkah-langkah:",
          "",
          "1. Tentukan tema dan pesan moral.",
          "2. Tentukan tokoh dan wataknya.",
          "3. Tentukan latar (tempat dan waktu).",
          "4. Tulis awal cerita (pengenalan).",
          "5. Tulis konflik (masalah yang terjadi).",
          "6. Tulis penyelesaian dan pesan moral.",
          "",
          "Gunakan bahasa yang menarik! Mulailah dengan:",
          "• 'Pada zaman dahulu...'",
          "• 'Di sebuah hutan yang lebat...'",
          "• 'Alkisah, di suatu desa...'",
          "",
          "[Ilustrasi: Sebuah meja dengan buku tulis terbuka, pena, dan lampu meja. Di buku tulis sudah ada tulisan dongeng pendek. Di sekelilingnya ada tempelan kertas berisi kata-kata: TOKOH, LATAR, KONFLIK, PESAN MORAL.]",
        ],
        contoh: [
          "Kerangka dongeng 'Semut dan Belalang':",
          "",
          "AWAL: Di sebuah padang rumput, hiduplah semut yang rajin dan belalang yang pemalas. Setiap hari semut bekerja mengumpulkan makanan.",
          "KONFLIK: Belalang menertawakan semut yang kerja terus. Belalang lebih suka bernyanyi dan bersantai. Tiba musim dingin, belalang kelaparan.",
          "PENYELESAIAN: Semut berbagi makanan dengan belalang. Belalang berjanji tidak akan malas lagi.",
          "PESAN MORAL: Jangan malas, persiapkan masa depan sejak sekarang.",
        ],
      },
    ],
    rangkuman: [
      "[Ilustrasi: Buku dongeng terbuka dengan 3 tab penanda: AWAL (hijau), KONFLIK (kuning), SELESAI (biru). Di setiap halaman ada ilustrasi adegan dongeng. Gaya buku cerita anak.]",
      "Struktur dongeng: Awal (pengenalan) → Konflik (masalah) → Penyelesaian (selesai).",
      "Watak tokoh bisa diketahui dari dialog, tindakan, keterangan penulis, atau pendapat tokoh lain.",
      "Menulis dongeng: tentukan tema, tokoh, latar, lalu tulis dengan struktur yang benar.",
      "Pesan moral adalah nasihat baik yang bisa dipetik dari dongeng.",
    ],
  },
  latihan: makeSoal([
    ["Bagian dongeng yang memperkenalkan tokoh dan latar adalah...", ["Konflik", "Awal (orientasi)", "Penyelesaian", "Pesan moral"], 1, "Awal cerita memperkenalkan tokoh, tempat, dan waktu."],
    ["Konflik dalam dongeng adalah...", ["Perkenalan", "Masalah yang terjadi", "Penutup", "Judul"], 1, "Konflik adalah masalah atau pertentangan dalam cerita."],
    ["Watak tokoh dapat diketahui dari...", ["Judul cerita", "Dialog dan tindakan tokoh", "Sampul buku", "Halaman buku"], 1, "Watak diketahui dari apa yang dikatakan dan dilakukan tokoh."],
    ["'Bawang Putih bangun pagi dan bekerja tanpa mengeluh.' — watak Bawang Putih adalah...", ["Malas", "Rajin", "Pemarah", "Sombong"], 1, "Bangun pagi dan bekerja tanpa mengeluh menunjukkan kerajinan."],
    ["Bagian penyelesaian dalam dongeng disebut...", ["Orientasi", "Resolusi", "Komplikasi", "Amanat"], 1, "Resolusi adalah bagian penyelesaian masalah."],
    ["Pesan moral dalam dongeng 'Kura-kura dan Kelinci' adalah...", ["Sombong itu baik", "Ketekunan mengalahkan kesombongan", "Lari itu penting", "Kelinci itu bodoh"], 1, "Kura-kura menang karena tekun, kelinci kalah karena sombong."],
    ["'Pada zaman dahulu, di sebuah hutan...' — ini bagian...", ["Awal", "Tengah", "Akhir", "Judul"], 0, "Frasa 'Pada zaman dahulu' adalah pembuka awal cerita."],
    ["Antagonis adalah tokoh yang berwatak...", ["Baik", "Jahat", "Lucu", "Bijak"], 1, "Antagonis adalah tokoh jahat atau lawan protagonis."],
    ["Tokoh protagonis dalam 'Bawang Merah Bawang Putih' adalah...", ["Bawang Merah", "Bawang Putih", "Ibu tiri", "Kucing"], 1, "Bawang Putih adalah tokoh baik (protagonis)."],
    ["Struktur dongeng yang benar adalah...", ["Konflik - Awal - Selesai", "Awal - Konflik - Selesai", "Selesai - Awal - Konflik", "Acak"], 1, "Urutan: Awal → Konflik → Selesai."],
  ]),
  praktik: {
    petunjuk: "Tulis sebuah dongeng pendek 4-5 paragraf dengan struktur yang benar (awal, konflik, penyelesaian). Tema bebas: persahabatan, kejujuran, atau kerja keras.",
    tips: [
      "Tentukan tokoh: manusia atau hewan?",
      "Buat konflik yang sederhana (misalnya: salah paham, iri hati, atau tantangan)",
      "Akhiri dengan penyelesaian yang bahagia",
      "Sertakan pesan moral di akhir cerita",
    ],
    contoh: "Judul: 'Kancil dan Buaya'. — AWAL: Kancil ingin menyeberang sungai. — KONFLIK: Banyak buaya di sungai, berbahaya. — PENYELESAIAN: Kancil menipu buaya dengan menyuruh mereka berbaris, lalu melompati punggung mereka. — PESAN MORAL: Kecerdikan bisa mengatasi masalah.",
  },
  kuis: makeSoal([
    ["Awal dongeng disebut juga...", ["Resolusi", "Orientasi", "Konflik", "Klimaks"], 1, "Orientasi adalah bagian awal yang memperkenalkan tokoh dan latar."],
    ["'Iri hati' adalah contoh...", ["Tempat", "Watak", "Waktu", "Latar"], 1, "Iri hati adalah watak atau sifat tokoh."],
    ["Bagian dongeng yang paling menegangkan adalah...", ["Awal", "Konflik", "Penyelesaian", "Penutup"], 1, "Konflik adalah puncak masalah yang menegangkan."],
    ["Dongeng 'Kancil dan Petani' — watak Kancil adalah...", ["Jujur", "Cerdik", "Pemalas", "Sombong"], 1, "Kancil dikenal sebagai tokoh yang cerdik."],
    ["Amanat dalam dongeng biasanya disampaikan di...", ["Awal", "Akhir", "Tengah", "Judul"], 1, "Amanat atau pesan moral biasanya di akhir cerita."],
    ["'Sifat atau karakter tokoh' disebut...", ["Latar", "Watak", "Alur", "Tema"], 1, "Watak adalah sifat atau karakter tokoh."],
    ["Dongeng termasuk jenis cerita...", ["Fiksi", "Nonfiksi", "Biografi", "Laporan"], 0, "Dongeng adalah cerita fiksi (khayalan)."],
    ["Bagian yang berisi pesan moral adalah...", ["Orientasi", "Amanat", "Konflik", "Latar"], 1, "Amanat adalah pesan moral dalam cerita."],
    ["'Belalang yang sombong' — kata 'sombong' menunjukkan...", ["Tempat", "Watak", "Waktu", "Alat"], 1, "'Sombong' adalah watak tokoh."],
    ["Alur adalah...", ["Tempat cerita", "Jalan cerita dari awal hingga akhir", "Tokoh", "Pesan"], 1, "Alur adalah urutan peristiwa dalam cerita dari awal hingga akhir."],
  ]),
}

export default konten
