import type { Konten } from "../types"
import { makeSoal } from "../types"

const konten: Konten = {
  belajar: {
    tujuan: [
      "Memahami pengertian dan tujuan iklan",
      "Mengenal bahasa persuasif dalam iklan",
      "Membuat iklan sederhana dengan gambar dan kata ajakan",
    ],
    materi: [
      {
        judul: "Apa Itu Iklan?",
        isi: [
          "Coba ingat-ingat, apa yang kamu lihat di TV atau di pinggir jalan? Ada gambar atau video yang menawarkan produk?",
          "",
          "Itu namanya iklan!",
          "",
          "✓ Iklan adalah pemberitahuan yang bertujuan membujuk atau mengajak orang untuk membeli produk atau menggunakan jasa.",
          "",
          "Tujuan iklan:",
          "1. Mengenalkan produk baru.",
          "2. Membujuk orang untuk membeli.",
          "3. Mengingatkan tentang produk yang sudah ada.",
          "4. Mempromosikan acara atau kegiatan.",
          "",
          "[Ilustrasi: Papan reklame besar di pinggir jalan dengan gambar jus segar dan tulisan 'SEGAR! MINUMAN ALAMI'. Di depannya ada orang-orang yang tertarik melihat. Gaya ilustrasi jalanan anak-anak.]",
        ],
        contoh: [
          "Contoh iklan sederhana:",
          "",
          "'Minum Susu Sehat!'",
          "Tulang kuat, badan sehat, otak cerdas!",
          "Tersedia di warung terdekat.'",
          "",
          "✓ Unsur iklan: nama produk ('Susu Sehat'), keunggulan (tulang kuat, sehat, cerdas), ajakan membeli (tersedia di warung).",
          "",
          "Tips: Iklan yang baik langsung menarik perhatian dengan kata-kata singkat dan jelas!",
        ],
        catatan: "Iklan berbeda dengan pengumuman. Pengumuman memberi informasi, iklan mengajak atau membujuk.",
      },
      {
        judul: "Bahasa dalam Iklan",
        isi: [
          "Iklan menggunakan bahasa persuasif — bahasa yang membujuk dan menarik perhatian!",
          "",
          "Ciri bahasa iklan:",
          "",
          "1. MENARIK — menggunakan kata-kata indah dan menarik.",
          "  Contoh: 'Segar!', 'Mantap!', 'Istimewa!'",
          "",
          "2. PERSUASIF (mengajak) — menggunakan kata ajakan.",
          "  Contoh: 'Ayo!', 'Dapatkan sekarang!', 'Jangan lewatkan!'",
          "",
          "3. SINGKAT DAN JELAS — langsung ke sasaran.",
          "  Contoh: 'Belajar jadi menyenangkan!' bukan 'Kami menyediakan alat belajar yang akan membuat proses belajar menjadi menyenangkan'.",
          "",
          "4. MENONJOLKAN KEUNGGULAN — menggunakan kata ' paling', 'nomor satu', 'terbaik'.",
          "",
          "[Ilustrasi: Gelembung-gelembung berisi kata-kata iklan: 'MURAH!', 'DISKON!', 'SEGAR!', 'AYO!', 'HEMAT!', 'PALING ENAK!'. Gelembung warna-warni seperti balon. Gaya ilustrasi promosi anak-anak.]",
        ],
        contoh: [
          "Bandingkan iklan yang menarik vs biasa:",
          "",
          "✗ BIASA: 'Ini pensil. Harganya murah. Warnanya merah.'",
          "  — Tidak menarik, tidak ada ajakan.",
          "",
          "✓ MENARIK: 'Pensil Ajaib! Warna merah menyala, tulisan rapi, harga hemat! Dapatkan sekarang di toko alat tulis terdekat!'",
          "  — Ada kata menarik, ajakan, keunggulan.",
          "",
          "PENTING: Iklan harus jujur, tidak boleh berbohong! 'Paling enak' harus benar-benar enak.",
        ],
      },
      {
        judul: "Membuat Iklan Sederhana",
        isi: [
          "Sekarang kita akan membuat iklan!",
          "",
          "Langkah-langkah:",
          "",
          "1. Tentukan produk atau jasa yang akan diiklankan.",
          "2. Tentukan target pembeli (anak-anak, remaja, orang tua).",
          "3. Tulis nama produk yang menarik.",
          "4. Tulis keunggulan produk (2-3 kalimat).",
          "5. Tambahkan kata ajakan (Ayo, Dapatkan, Jangan lewatkan).",
          "6. Buat gambar atau ilustrasi yang menarik.",
          "",
          "Struktur iklan sederhana:",
          "✓ JUDUL yang menarik perhatian.",
          "✓ GAMBAR atau ilustrasi produk.",
          "✓ TEKS yang menjelaskan keunggulan.",
          "✓ AJAKAN untuk membeli.",
          "",
          "[Ilustrasi: Selembar poster iklan buatan anak di kertas karton. Ada gambar pensil besar dengan topi, tulisan 'PENSIL HEBAT!', poin keunggulan: 'Tulisan rapi, Tidak mudah patah, Harga bersahabat'. Di bawah: 'Dapatkan di koperasi sekolah!']",
        ],
        contoh: [
          "Contoh iklan produk 'Pensil Hebat':",
          "",
          "[Gambar pensil besar dengan bintang-bintang]",
          "",
          "PENSIL HEBAT!",
          "Tulisan rapi dan jelas!",
          "Tidak mudah patah!",
          "Harga bersahabat untuk pelajar!",
          "",
          "Dapatkan sekarang di koperasi sekolah!",
          "",
          "Tips: Buat gambarmu sendiri semenarik mungkin! Gunakan spidol warna-warni.",
        ],
      },
    ],
    rangkuman: [
      "[Ilustrasi: Poster iklan dengan logo bintang, gambar produk (sepatu), dan tulisan 'SEPATU KUAT! Nyaman dipakai, awet bertahun-tahun! Dapatkan sekarang!' Gaya poster anak-anak.]",
      "Iklan: pemberitahuan yang membujuk/mengajak orang untuk membeli produk atau jasa.",
      "Bahasa iklan: persuasif, menarik, singkat, jelas, menonjolkan keunggulan.",
      "Struktur iklan: judul menarik, gambar, teks keunggulan, ajakan membeli.",
      "Iklan harus jujur dan tidak boleh mengandung kebohongan.",
    ],
  },
  latihan: makeSoal([
    ["Tujuan utama iklan adalah...", ["Mendidik", "Membujuk/mengajak membeli", ["Melaporkan"], ["Menghibur"]], 1, "Tujuan iklan membujuk orang untuk membeli produk."],
    ["'Ayo, dapatkan sekarang!' — ini adalah kalimat...", ["Berita", "Ajakan/persuasif", ["Tanya"], ["Laporan"]], 1, "Kalimat itu mengajak orang untuk membeli."],
    ["Bahasa dalam iklan harus...", ["Panjang", "Singkat dan menarik", ["Berbelit"], ["Tidak jelas"]], 1, "Iklan harus singkat, jelas, dan menarik perhatian."],
    ["Yang termasuk kata persuasif adalah...", ["Mungkin", "Ayo", ["Tidak"], ["Bukan"]], 1, "'Ayo' adalah kata ajakan yang persuasif."],
    ["Iklan yang baik harus...", ["Bohong", "Jujur dan sesuai fakta", ["Berlebihan"], ["Menakut-nakuti"]], 1, "Iklan harus jujur, tidak boleh berbohong tentang produk."],
    ["'Paling enak, paling segar!' — ini menunjukkan...", ["Kelemahan", "Keunggulan produk", ["Harga"], ["Nama"]], 1, "Kata 'paling' menonjolkan keunggulan produk."],
    ["Bagian iklan yang berisi ajakan membeli disebut...", ["Judul", "Ajakan", ["Gambar"], ["Nama produk"]], 1, "Ajakan adalah bagian yang mendorong pembaca untuk membeli."],
    ["Iklan berbeda dengan pengumuman karena iklan...", ["Memberi informasi", "Mengajak/membujuk", ["Panjang"], ["Resmi"]], 1, "Iklan mengajak, pengumuman memberi informasi."],
    ["Gambar dalam iklan berfungsi...", ["Hiasan", "Menarik perhatian dan mendukung pesan", ["Pengganti teks"], ["Tidak penting"]], 1, "Gambar membuat iklan lebih menarik dan mendukung pesan."],
    ["Contoh produk yang bisa diiklankan adalah...", ["Pensil", ["Perasaan"], "Angka", "Ukuran"], 0, "Pensil adalah produk yang bisa diiklankan."],
  ]),
  praktik: {
    petunjuk: "Buat sebuah iklan sederhana untuk produk 'Pensil Warna 12 Warna'! Sertakan judul menarik, gambar, keunggulan, dan ajakan membeli.",
    tips: [
      "Buat judul yang menarik perhatian (misal: 'Warnai Duniaku!')",
      "Sebutkan keunggulan: warna cerah, mudah diraut, tidak mudah patah",
      "Tambahkan harga yang terjangkau",
      "Akhiri dengan ajakan: 'Dapatkan sekarang di toko alat tulis!'",
    ],
    contoh: "'PENSIL WARNA 12 WARNA! Warnai duniaku! Warna cerah dan tajam. Mudah diraut, tidak mudah patah. Cocok untuk mewarnai gambar favoritmu. Hanya Rp15.000! Dapatkan sekarang di toko alat tulis langgananmu!'",
  },
  kuis: makeSoal([
    ["Iklan termasuk teks...", ["Fiksi", "Persuasif", ["Laporan"], ["Deskripsi"]], 1, "Iklan termasuk teks persuasif karena membujuk."],
    ["Kata 'Dapatkan' dalam iklan termasuk...", ["Kata tanya", "Kata ajakan", ["Kata sifat"], ["Kata benda"]], 1, "'Dapatkan' adalah kata kerja yang mengajak."],
    ["Iklan 'MINUMAN SEHAT! Segar alami, baik untuk pencernaan!' — keunggulan produk adalah...", ["Murah", "Segar alami, baik untuk pencernaan", ["Enak"], ["Manis"]], 1, "'Segar alami dan baik untuk pencernaan' adalah keunggulan."],
    ["'Jangan lewatkan kesempatan ini!' — kalimat ini bertujuan...", ["Mengancam", "Mendesak/mengajak segera", ["Bertanya"], ["Melapor"]], 1, "Kalimat itu mendesak pembaca untuk segera bertindak."],
    ["Media yang bisa memuat iklan adalah...", ["Koran, TV, internet", ["Buku tulis"], ["Pensil"], ["Meja"]], 0, "Iklan bisa di koran, TV, radio, internet, atau poster."],
    ["Iklan yang tidak jujur termasuk...", ["Kreatif", "Penipuan", ["Menarik"], ["Baik"]], 1, "Iklan bohong adalah penipuan dan melanggar aturan."],
    ["'Hanya Rp5.000!' — ini informasi tentang...", ["Kualitas", "Harga", ["Rasa"], ["Ukuran"]], 1, "'Hanya Rp5.000' adalah informasi harga."],
    ["Kalimat 'Segar! Nikmat! Sehat!' — termasuk iklan produk...", ["Minuman", "Pakaian", ["Alat tulis"], ["Sepatu"]], 0, "'Segar' dan 'nikmat' berkaitan dengan minuman atau makanan."],
    ["Target iklan pensil warna adalah...", ["Orang tua", "Anak-anak/pelajar", ["Bayi"], ["Kakek"]], 1, "Pensil warna targetnya anak-anak dan pelajar."],
    ["Iklan yang baik menggunakan kalimat...", ["Panjang berbelit", "Singkat padat jelas", ["Tidak jelas"], ["Rumit"]], 1, "Iklan yang baik singkat, padat, dan jelas."],
  ]),
}

export default konten
