import type { Konten } from "../types"
import { makeSoal } from "../types"

const konten: Konten = {
  belajar: {
    tujuan: [
      "Memahami pengertian teks petunjuk/prosedur",
      "Mengidentifikasi urutan langkah dalam petunjuk",
      "Menulis teks petunjuk sederhana",
    ],
    materi: [
      {
        judul: "Apa Itu Teks Petunjuk?",
        isi: [
          "Pernahkah kamu membaca petunjuk penggunaan mainan baru? Atau resep masakan ibu?",
          "",
          "Itu semua adalah teks petunjuk!",
          "",
          "✓ Teks petunjuk adalah teks yang berisi langkah-langkah untuk melakukan sesuatu atau membuat sesuatu.",
          "✓ Tujuannya: memandu pembaca agar bisa melakukan sesuatu dengan benar.",
          "",
          "Contoh teks petunjuk:",
          "• Cara membuat jus jeruk.",
          "• Cara mengoperasikan remote TV.",
          "• Petunjuk permainan tradisional.",
          "• Resep makanan sederhana.",
          "",
          "[Ilustrasi: Selembar kertas resep masakan dengan langkah-langkah bernomor 1-5. Di sampingnya ada bahan-bahan masakan: telur, tepung, gula, mentega. Gaya ilustrasi dapur yang rapi dan ceria.]",
        ],
        contoh: [
          "Ciri teks petunjuk yang baik:",
          "",
          "1. Menggunakan kalimat perintah (imperatif): siapkan, aduk, tuang, panaskan.",
          "2. Langkah tersusun secara urut (pertama, kedua, ketiga...).",
          "3. Bahasa jelas dan mudah dipahami.",
          "4. Kadang disertai gambar atau ilustrasi.",
          "",
          "BENAR: 'Pertama, siapkan gelas dan sendok. Kedua, tuangkan susu bubuk ke dalam gelas. Ketiga, tambahkan air hangat, lalu aduk hingga rata.'",
          "✓ Ada urutan, kalimat perintah, jelas.",
        ],
      },
      {
        judul: "Urutan Langkah dalam Petunjuk",
        isi: [
          "Urutan langkah dalam teks petunjuk harus logis dan tidak boleh terbalik.",
          "",
          "✓ Gunakan kata penghubung urutan (konjungsi kronologis):",
          "",
          "1. Pertama / Pertama-tama — langkah awal.",
          "2. Kedua, Ketiga, Keempat — langkah selanjutnya.",
          "3. Kemudian / Selanjutnya — setelah satu langkah selesai.",
          "4. Setelah itu — setelah langkah sebelumnya.",
          "5. Akhirnya / Terakhir — langkah penutup.",
          "",
          "PENTING: Jika langkah terbalik, hasilnya bisa gagal! Contoh: membuat mie instan — harus direbus dulu baru diberi bumbu, bukan sebaliknya.",
          "",
          "[Ilustrasi: Diagram alur dengan 5 kotak berwarna pelangi yang saling terhubung panah. Kotak 1 (merah): 'Pertama', Kotak 2 (jingga): 'Kedua', Kotak 3 (kuning): 'Ketiga', Kotak 4 (hijau): 'Keempat', Kotak 5 (biru): 'Terakhir'. Setiap kotak berisi ikon langkah.]",
        ],
        contoh: [
          "Petunjuk menanam biji kacang hijau:",
          "",
          "1. Siapkan: pot, tanah, biji kacang hijau, air.",
          "2. Isi pot dengan tanah hingga ¾ bagian.",
          "3. Buat lubang sedalam 2 cm di tengah tanah.",
          "4. Masukkan 3 biji kacang hijau ke lubang.",
          "5. Tutup lubang dengan tanah tipis-tipis.",
          "6. Siram dengan air secukupnya.",
          "7. Letakkan pot di tempat yang terkena sinar matahari.",
          "8. Siram setiap hari dan amati pertumbuhannya.",
        ],
        catatan: "Teks petunjuk sering disebut juga teks prosedur. Kata 'prosedur' berasal dari bahasa Inggris 'procedure' yang berarti langkah-langkah.",
      },
      {
        judul: "Menulis Teks Petunjuk",
        isi: [
          "Sekarang, ayo menulis teks petunjuk!",
          "",
          "Langkah menulis petunjuk:",
          "",
          "1. Tentukan kegiatan yang akan dijelaskan.",
          "2. Coba lakukan sendiri kegiatannya, catat setiap langkah.",
          "3. Tulis daftar alat dan bahan yang diperlukan.",
          "4. Tulis langkah-langkah secara berurutan.",
          "5. Gunakan kalimat perintah yang jelas.",
          "6. Tambahkan tips atau peringatan jika perlu.",
          "",
          "Struktur teks petunjuk:",
          "✓ Tujuan — apa yang akan dibuat/dilakukan.",
          "✓ Alat dan Bahan — apa saja yang diperlukan.",
          "✓ Langkah-langkah — urutan cara melakukannya.",
          "",
          "[Ilustrasi: Seorang anak sedang membuat origami (lipatan kertas). Di atas meja ada kertas warna-warni, gunting, lem. Di depannya ada buku petunjuk origami bergambar langkah demi langkah.]",
        ],
        contoh: [
          "Teks petunjuk 'Membuat Layang-Layang Sederhana':",
          "",
          "Tujuan: Membuat layang-layang sederhana.",
          "",
          "Alat dan Bahan:",
          "- Kertas minyak atau kertas tipis ukuran 30×30 cm",
          "- 2 batang bambu tipis (panjang 30 cm dan 25 cm)",
          "- Benang, gunting, lem, spidol",
          "",
          "Langkah:",
          "1. Bentuk salib dari dua batang bambu. Bambu panjang vertikal, bambu pendek horizontal.",
          "2. Ikat kedua bambu dengan benang hingga kuat.",
          "3. Letakkan rangka bambu di atas kertas, potong kertas mengikuti bentuk layang-layang.",
          "4. Lem kertas pada rangka bambu.",
          "5. Ikat benang pada bagian tengah rangka untuk tali layang-layang.",
          "6. Hias layang-layang dengan spidol.",
          "7. Jemur sebentar agar lem kering.",
          "",
          "Tips: Pilih hari yang berangin untuk menerbangkan layang-layang!",
        ],
      },
    ],
    rangkuman: [
      "[Ilustrasi: Buku petunjuk terbuka dengan ikon langkah 1-2-3. Di sampingnya ada hasil jadi: origami burung, layang-layang, gelas jus. Gaya ilustrasi panduan anak-anak.]",
      "Teks petunjuk: teks yang berisi langkah-langkah untuk melakukan/membuat sesuatu.",
      "Ciri: kalimat perintah, kata penghubung urutan (pertama, kedua...), langkah logis.",
      "Struktur: tujuan → alat dan bahan → langkah-langkah.",
      "Gunakan kata kerja aktif seperti siapkan, aduk, tuang, potong, rekatkan.",
    ],
  },
  latihan: makeSoal([
    ["Teks petunjuk juga disebut...", ["Teks narasi", "Teks prosedur", ["Teks deskripsi"], "Teks laporan"], 1, "Teks petunjuk = teks prosedur (procedure text)."],
    ["Kalimat yang tepat dalam petunjuk adalah...", ["Siapkan air dan gelas", "Air dan gelas disiapkan", ["Aku menyiapkan air"], "Air itu disiapkan"], 0, "Teks petunjuk menggunakan kalimat perintah (imperatif): 'Siapkan...'"],
    ["Kata 'Pertama, Kedua, Ketiga' termasuk...", ["Kata sifat", "Konjungsi kronologis", ["Kata tanya"], "Kata benda"], 1, "Kata-kata itu menunjukkan urutan waktu (kronologis)."],
    ["Apa yang terjadi jika langkah petunjuk terbalik?", ["Hasil tetap baik", "Bisa gagal", ["Tidak masalah"], "Lebih cepat"], 1, "Langkah yang terbalik bisa menyebabkan kegagalan."],
    ["Struktur teks petunjuk yang benar adalah...", ["Langkah - Tujuan - Alat", "Tujuan - Alat/Bahan - Langkah", ["Alat - Langkah - Tujuan"], "Langkah - Alat - Tujuan"], 1, "Urutan yang benar: Tujuan → Alat/Bahan → Langkah-langkah."],
    ["'Aduk hingga rata' adalah contoh kalimat...", ["Berita", "Perintah", ["Tanya"], "Seru"], 1, "'Aduk' adalah kata kerja perintah (imperatif)."],
    ["Teks petunjuk 'Cara Membuat Jus' — bagian langkah berisi...", ["Manfaat jus", "Urutan membuat jus", ["Harga jus"], "Sejarah jus"], 1, "Langkah berisi urutan cara membuat jus."],
    ["Mana kata penghubung urutan?", ["Dan", "Kemudian", ["Atau"], "Tetapi"], 1, "'Kemudian' menunjukkan urutan langkah selanjutnya."],
    ["Petunjuk harus menggunakan bahasa yang...", ["Berbelit", "Jelas dan mudah dipahami", ["Sulit"], "Indah"], 1, "Petunjuk harus jelas dan mudah dipahami agar bisa diikuti."],
    ["Bagian 'Alat dan Bahan' bertujuan...", ["Menambah panjang", "Memberi tahu apa yang diperlukan", ["Menghias"], "Penutup"], 1, "Alat dan bahan memberi tahu perlengkapan yang perlu disiapkan."],
  ]),
  praktik: {
    petunjuk: "Buat teks petunjuk tentang 'Cara Membuat Teh Manis'! Gunakan struktur yang benar: tujuan, alat dan bahan, langkah-langkah.",
    tips: [
      "Tulis dulu daftar alat dan bahan yang diperlukan",
      "Urutkan langkah dari awal hingga selesai",
      "Gunakan kalimat perintah (siapkan, masukkan, aduk, tuang)",
      "Tambahkan kata penghubung urutan: pertama, kemudian, selanjutnya, akhirnya",
    ],
    contoh: "Tujuan: Membuat segelas teh manis. Alat dan Bahan: 1 kantong teh celup, 1 sendok gula pasir, 200 ml air panas, gelas, sendok. Langkah: 1. Siapkan gelas dan masukkan kantong teh celup. 2. Tuangkan air panas ke dalam gelas. 3. Tambahkan 1 sendok gula pasir. 4. Aduk hingga gula larut. 5. Diamkan 2-3 menit hingga teh meresap. 6. Angkat kantong teh. Teh manis siap dinikmati!",
  },
  kuis: makeSoal([
    ["Teks petunjuk bertujuan untuk...", ["Menghibur", "Memandu melakukan sesuatu", ["Mendeskripsikan"], ["Melaporkan"]], 1, "Teks petunjuk memandu pembaca melakukan sesuatu."],
    ["'Alat dan Bahan' dalam teks petunjuk berisi...", ["Cara membuat", "Peralatan yang diperlukan", ["Hasil akhir"], "Kesimpulan"], 1, "Alat dan Bahan berisi daftar perlengkapan yang diperlukan."],
    ["Kata 'tuangkan' termasuk jenis kata...", ["Benda", "Kerja (perintah)", ["Sifat"], ["Sambung"]], 1, "'Tuangkan' adalah kata kerja perintah (imperatif)."],
    ["'Pertama, ... Kedua, ...' — fungsi kata ini adalah...", ["Menghias tulisan", "Menunjukkan urutan", ["Menjelaskan"], ["Menanyakan"]], 1, "Kata-kata itu menunjukkan urutan langkah."],
    ["Mana yang termasuk teks petunjuk?", ["Liburan sekolah", "Resep membuat kue", ["Kucingku lucu"], ["Pantai indah"]], 1, "Resep adalah teks petunjuk cara membuat kue."],
    ["Kalimat perintah biasanya diakhiri...", ["Tanya", "Titik atau seru", ["Koma"], ["Titik dua"]], 1, "Kalimat perintah diakhiri titik (.) atau seru (!)."],
    ["Bagian pertama teks petunjuk adalah...", ["Langkah", "Tujuan", ["Alat"], ["Penutup"]], 1, "Bagian pertama adalah tujuan (apa yang akan dibuat)."],
    ["Jika langkah tidak urut, akibatnya...", ["Lebih cepat selesai", "Hasil mungkin gagal", ["Tidak apa-apa"], ["Lebih mudah"]], 1, "Urutan langkah penting agar hasil sesuai yang diharapkan."],
    ["Teks petunjuk yang baik bersifat...", ["Subjektif", "Objektif dan jelas", ["Panjang"], ["Artistik"]], 1, "Teks petunjuk harus objektif, jelas, dan langsung ke sasaran."],
    ["'Aduk hingga rata' — kata 'hingga' berarti...", ["Sampai", "Dari", ["Untuk"], ["Oleh"]], 0, "'Hingga' berarti 'sampai' — batas waktu melakukan tindakan."],
  ]),
}

export default konten
