import type { Konten } from "../types"
import { makeSoal } from "../types"

const konten: Konten = {
  belajar: {
    tujuan: [
      "Memahami pengertian dan ciri teks deskripsi",
      "Mengidentifikasi objek dalam teks deskripsi",
      "Menulis teks deskripsi tentang benda atau hewan",
    ],
    materi: [
      {
        judul: "Apa Itu Teks Deskripsi?",
        isi: [
          "Coba bayangkan kamu melihat pemandangan indah. Jika kamu menggambarkannya dengan kata-kata sehingga orang lain bisa membayangkannya — itulah deskripsi!",
          "",
          "✓ Teks deskripsi adalah teks yang menggambarkan suatu objek (benda, hewan, tempat) secara rinci sehingga pembaca seolah-olah melihat, mendengar, atau merasakannya.",
          "",
          "Ciri-ciri teks deskripsi:",
          "1. Menggambarkan objek secara detail (warna, bentuk, ukuran, rasa).",
          "2. Menggunakan kata-kata sifat (indah, besar, mungil, wangi).",
          "3. Membuat pembaca seolah-olah melihat objek yang dideskripsikan.",
          "",
          "[Ilustrasi: Sebuah lukisan pemandangan gunung, sawah, dan sungai yang indah. Di sampingnya ada teks deskripsi yang mendetail tentang pemandangan tersebut. Gaya ilustrasi realis dengan warna pastel.]",
        ],
        contoh: [
          "Bandingkan:",
          "",
          "✗ BUKAN DESKRIPSI: 'Ini kucingku.' (hanya informasi, tidak ada gambaran)",
          "",
          "✓ DESKRIPSI: 'Kucingku berbulu putih bersih seperti kapas. Matanya bulat berwarna biru. Ekornya panjang dan selalu digerak-gerakkan. Bulunya sangat lembut saat dielus.'",
          "  — Ada detail: warna, bentuk mata, tekstur bulu!",
        ],
        catatan: "Teks deskripsi berbeda dengan teks laporan. Deskripsi lebih artistik dan subjektif, laporan lebih faktual dan objektif.",
      },
      {
        judul: "Objek dalam Teks Deskripsi",
        isi: [
          "Objek deskripsi bisa apa saja: benda, hewan, tempat, atau bahkan perasaan.",
          "",
          "✓ Sebelum menulis deskripsi, amati objek dengan saksama.",
          "",
          "Aspek yang bisa dideskripsikan:",
          "1. Bentuk: bulat, lonjong, persegi, panjang.",
          "2. Warna: merah menyala, biru langit, hijau lumut.",
          "3. Ukuran: raksasa, mungil, sedang, raksasa.",
          "4. Bau/aroma: harum semerbak, wangi, anyir.",
          "5. Suara: merdu, nyaring, lembut.",
          "6. Rasa: manis, asam, pahit, gurih.",
          "7. Tekstur: halus, kasar, licin, lembut, keras.",
          "",
          "[Ilustrasi: Sebuah meja dengan berbagai benda: apel merah mengkilap, boneka berbulu halus, bunga mawar merah, batu kasar. Setiap benda memiliki label aspek deskripsi — APEL: merah, bulat, manis. BONEKA: lembut, mungil, lucu.]",
        ],
        contoh: [
          "Deskripsi APEL:",
          "",
          "✓ Apel itu berwarna merah menyala seperti delima. Kulitnya mengkilap dan halus saat disentuh. Bentuknya bulat sempurna sebesar kepalan tangan. Saat digigit, daging buahnya putih kekuningan, renyah, dan terasa manis segar.",
          "",
          "Deskripsi BUNGA MATAHARI:",
          "✓ Bunga matahari menjulang tinggi hingga 2 meter. Kelopaknya berwarna kuning cerah mengelilingi bagian tengah yang cokelat besar. Bunganya selalu menghadap ke arah matahari.",
        ],
      },
      {
        judul: "Menulis Teks Deskripsi",
        isi: [
          "Sekarang giliranmu menulis deskripsi!",
          "",
          "Langkah-langkah:",
          "",
          "1. Pilih objek yang akan dideskripsikan.",
          "2. Amati objek dengan saksama (gunakan panca indra).",
          "3. Catat detail-detail penting: warna, bentuk, ukuran, bau, tekstur.",
          "4. Tulis kalimat dengan kata-kata yang indah dan spesifik.",
          "5. Susun paragraf dengan rapi.",
          "",
          "Tips menulis deskripsi:",
          "• Gunakan kata sifat yang spesifik (bukan hanya 'besar' tapi 'raksasa').",
          "• Gunakan perbandingan (seperti, bagaikan, laksana).",
          "• Libatkan panca indra (penglihatan, pendengaran, penciuman, peraba, pengecap).",
          "",
          "[Ilustrasi: Seorang anak sedang menulis di meja belajar. Di depannya ada sebuah mangkuk berisi buah-buahan yang sedang diamati. Di kertas tulisnya sudah ada beberapa kalimat deskripsi. Gaya ilustrasi anak sekolah.]",
        ],
        contoh: [
          "Kerangka menulis deskripsi 'KUCINGKU':",
          "",
          "Paragraf 1 (penampilan fisik):",
          "Kucingku bernama Mimi. Bulunya putih bersih seperti kapas. Matanya bulat, biru seperti langit. Ekornya panjang dan lentik.",
          "",
          "Paragraf 2 (sifat dan tingkah laku):",
          "Mimi sangat manja. Ia suka tidur di pangkuanku sambil mendengkur. Suara dengkurannya lembut seperti suara mesin kecil.",
          "",
          "Paragraf 3 (kesan):",
          "Mimi adalah sahabatku yang paling setia. Aku sangat menyayanginya.",
        ],
      },
    ],
    rangkuman: [
      "[Ilustrasi: Papan tulis bertuliskan 'TEKS DESKRIPSI' dengan ikon mata, telinga, hidung, tangan, lidah — melambangkan panca indra untuk mendeskripsikan objek.]",
      "Teks deskripsi: teks yang menggambarkan objek secara rinci sehingga pembaca bisa membayangkannya.",
      "Ciri: detail, kata sifat, melibatkan panca indra, menimbulkan kesan seolah-olah melihat.",
      "Aspek deskripsi: bentuk, warna, ukuran, bau, suara, rasa, tekstur.",
      "Tips: gunakan kata sifat spesifik, perbandingan, dan libatkan panca indra.",
    ],
  },
  latihan: makeSoal([
    ["Teks deskripsi bertujuan untuk...", ["Menghibur", "Menggambarkan objek secara rinci", ["Memberi petunjuk"], "Melaporkan kejadian"], 1, "Teks deskripsi menggambarkan objek dengan rinci agar pembaca bisa membayangkannya."],
    ["Yang BUKAN ciri teks deskripsi adalah...", ["Menggunakan kata sifat", "Bersifat objektif seperti laporan", ["Detail dan rinci"], "Melibatkan panca indra"], 1, "Teks deskripsi bersifat subjektif dan artistik, tidak harus objektif seperti laporan."],
    ["Kata 'bagaikan' dalam deskripsi berfungsi...", ["Menambah panjang", "Membandingkan sesuatu", ["Mengakhiri"], "Menanyakan"], 1, "'Bagaikan' digunakan untuk perbandingan, seperti 'bulunya putih bagaikan kapas'."],
    ["'Kucingku berbulu putih seperti kapas.' — ini menggunakan...", ["Data angka", "Perbandingan", ["Petunjuk"], "Pertanyaan"], 1, "Kalimat menggunakan perbandingan 'seperti kapas'."],
    ["Manakah yang merupakan teks deskripsi?", ["Ibu pergi ke pasar", "Mawar itu merah merebak, kelopaknya lembut, dan baunya semerbak", ["Belajarlah yang rajin"], "Besok libur"], 1, "Kalimat kedua menggambarkan bunga mawar secara detail."],
    ["Benda yang dideskripsikan disebut...", ["Subjek", "Objek", ["Predikat"], "Pelaku"], 1, "Objek adalah benda yang dideskripsikan."],
    ["Contoh kata sifat yang spesifik adalah...", ["Bagus", "Menyala (merah menyala)", ["Cantik"], "Baik"], 1, "'Menyala' lebih spesifik daripada 'bagus' atau 'cantik'."],
    ["Panca indra yang digunakan untuk mendeskripsikan tekstur adalah...", ["Mata", "Tangan/kulit", ["Hidung"], "Telinga"], 1, "Tangan/kulit digunakan untuk meraba tekstur (halus, kasar, lembut)."],
    ["'Langit biru, awan putih bergerak pelan' — ini mendeskripsikan...", ["Suara", "Penglihatan", ["Penciuman"], "Peraba"], 1, "Langit biru dan awan putih adalah hal yang terlihat (penglihatan)."],
    ["Kata 'semerbak' biasanya digunakan untuk...", ["Warna", "Bau", ["Rasa"], "Bentuk"], 1, "'Semerbak' adalah kata untuk bau yang harum dan menyebar."],
  ]),
  praktik: {
    petunjuk: "Pilih salah satu benda di sekitarmu (buku, pensil, tas, atau tanaman). Amati dengan saksama, lalu tulis teks deskripsi 3 paragraf tentang benda tersebut!",
    tips: [
      "Gunakan panca indra: lihat, raba, cium jika perlu",
      "Catat minimal 5 detail tentang benda itu",
      "Gunakan kata sifat dan perbandingan",
      "Susun dari detail umum ke detail khusus",
    ],
    contoh: "Benda: Pensil. Paragraf 1: Pensilku berwarna biru dongker dengan motif batik kawung. Panjangnya sekitar 17 cm, ramping dan ringan. Paragraf 2: Ujungnya runcing, siap untuk menulis. Karet penghapus di ujung satunya masih baru, berwarna merah muda. Paragraf 3: Saat menulis, goresannya halus dan tidak patah-patah. Pensil ini menemaniku belajar setiap hari.",
  },
  kuis: makeSoal([
    ["Teks deskripsi menggunakan banyak...", ["Kata kerja", "Kata sifat", ["Kata tanya"], "Kata sambung"], 1, "Teks deskripsi kaya akan kata sifat untuk menggambarkan objek."],
    ["'Buah itu manis' — kata 'manis' menggunakan indra...", ["Mata", "Lidah", ["Hidung"], "Telinga"], 1, "Rasa manis dirasakan oleh lidah (pengecap)."],
    ["Agar deskripsi hidup, gunakan...", ["Kata yang sama berulang", "Perbandingan dan detail", ["Kata singkat"], "Angka"], 1, "Perbandingan dan detail membuat deskripsi lebih hidup."],
    ["'Bunga mawar merah merebak' — kata 'merebak' berarti...", ["Menyebar/Mekar", "Layu", ["Kuncup"], "Kering"], 0, "'Merebak' berarti mekar sempurna atau menyebar."],
    ["Deskripsi 'Pensil' yang baik adalah...", ["Pensil itu panjang", "Pensilku berbentuk silindris, biru dongker, dengan ujung runcing dan penghapus merah muda", ["Pensil itu bagus"], "Aku punya pensil"], 1, "Deskripsi yang baik memberikan detail spesifik."],
    ["Mengapa teks deskripsi menggunakan panca indra?", ["Agar panjang", "Agar pembaca seolah merasakan objek", ["Biar susah"], "Tidak penting"], 1, "Panca indra membuat deskripsi lebih hidup dan nyata."],
    ["'Suaranya merdu bagai burung berkicau' — ini deskripsi...", ["Penglihatan", "Pendengaran", ["Penciuman"], "Peraba"], 1, "'Suara' dan 'merdu' berkaitan dengan pendengaran."],
    ["Kata 'bak' dalam 'bak pahlawan' artinya...", ["Seperti", "Untuk", ["Dari"], "Oleh"], 0, "'Bak' berarti 'seperti' — kata perbandingan dalam deskripsi."],
    ["Bagian akhir deskripsi biasanya berisi...", ["Data", "Kesan atau penutup", ["Alat"], "Bahan"], 1, "Bagian akhir biasanya berisi kesan penulis tentang objek."],
    ["'Renyah' adalah kata yang menggambarkan...", ["Warna", ["Rasa/tekstur saat digigit"], "Bau", "Bentuk"], 1, "'Renyah' menggambarkan tekstur makanan saat digigit."],
  ]),
}

export default konten
