import type { Konten } from "../types"
import { makeSoal } from "../types"

const konten: Konten = {
  belajar: {
    tujuan: [
      "Memahami struktur laporan sederhana",
      "Mengamati dan mencatat data untuk laporan",
      "Menulis laporan hasil pengamatan dengan sistematis",
    ],
    materi: [
      {
        judul: "Apa Itu Laporan?",
        isi: [
          "Pernahkah kamu diminta guru untuk menceritakan hasil pengamatan? Atau menulis kegiatan percobaan sains?",
          "",
          "Itu namanya laporan!",
          "",
          "✓ Laporan adalah teks yang menyajikan informasi berdasarkan fakta atau hasil pengamatan.",
          "✓ Laporan bersifat faktual (berdasarkan kenyataan) dan objektif (tidak memihak).",
          "",
          "Struktur laporan sederhana:",
          "1. JUDUL — nama kegiatan atau objek laporan.",
          "2. TUJUAN — maksud dari kegiatan.",
          "3. HASIL PENGAMATAN — data dan fakta yang ditemukan.",
          "4. KESIMPULAN — ringkasan dari hasil pengamatan.",
          "",
          "[Ilustrasi: Seorang anak memegang clipboard dengan kertas laporan. Di atas kertas tertulis 'LAPORAN PENGAMATAN' dengan bagian-bagian yang jelas: Judul, Tujuan, Hasil, Kesimpulan. Gaya ilustrasi anak sekolah.]",
        ],
        contoh: [
          "Perbedaan laporan dengan deskripsi:",
          "",
          "✓ LAPORAN: 'Daun mangga berbentuk lonjong, panjang 15-25 cm, tepi rata, warna hijau tua pada permukaan atas dan hijau muda pada permukaan bawah.' (faktual, data)",
          "",
          "✓ DESKRIPSI: 'Daun mangga itu hijau segar, melambai-lambai ditiup angin, seolah menyapaku.' (artistik, perasaan)",
          "",
          "PENTING: Laporan harus jujur sesuai fakta, meskipun hasilnya tidak sesuai harapan!",
        ],
        catatan: "Laporan berbeda dengan cerita. Laporan berdasarkan fakta, cerita bisa berdasarkan imajinasi. Dalam laporan, data adalah segalanya!",
      },
      {
        judul: "Mengamati dan Mencatat Data",
        isi: [
          "Sebelum menulis laporan, kita harus mengamati dan mencatat data terlebih dahulu.",
          "",
          "Langkah-langkah:",
          "",
          "1. Tentukan objek yang akan diamati.",
          "2. Siapkan alat pengamatan (mata, kaca pembesar, penggaris).",
          "3. Amati dari berbagai sisi (depan, belakang, atas, bawah).",
          "4. Catat data: warna, bentuk, ukuran, jumlah, bau, tekstur.",
          "5. Jika perlu, ukur dengan alat ukur (penggaris, timbangan).",
          "",
          "Tips mencatat data:",
          "• Gunakan tabel agar rapi.",
          "• Tulis angka yang akurat.",
          "• Jangan menambahkan opini pribadi.",
          "",
          "[Ilustrasi: Meja laboratorium sederhana dengan alat: kaca pembesar, penggaris, timbangan, buku catatan. Seorang anak mengamati daun dengan kaca pembesar dan mencatat hasilnya. Gaya ilustrasi sains anak-anak.]",
        ],
        contoh: [
          "Contoh tabel pengamatan 'Daun Sirih':",
          "",
          "| Aspek | Hasil Pengamatan |",
          "| Warna | Hijau tua mengkilap di atas, hijau muda di bawah |",
          "| Bentuk | Jantung, tepi rata, ujung runcing |",
          "| Ukuran | Panjang 12 cm, lebar 8 cm |",
          "| Tekstur | Halus, agak tebal, licin |",
          "| Bau | Harum khas menyegarkan |",
          "| Tulang Daun | Menyirip rapi dari pangkal ke ujung |",
        ],
      },
      {
        judul: "Menulis Laporan Hasil Pengamatan",
        isi: [
          "Setelah data terkumpul, saatnya menulis laporan!",
          "",
          "Contoh laporan sederhana:",
          "",
          "LAPORAN PENGAMATAN DAUN SIRIH",
          "",
          "Tujuan: Mengamati ciri-ciri daun sirih.",
          "",
          "Hasil Pengamatan:",
          "Daun sirih berwarna hijau tua mengkilap di permukaan atas dan hijau muda di bawahnya. Bentuknya seperti jantung dengan ujung runcing dan tepi rata. Panjang daun sekitar 12 cm, lebar 8 cm. Permukaannya halus dan licin saat disentuh. Daun ini memiliki aroma harum yang khas. Tulang daun menyirip rapi dari pangkal hingga ujung.",
          "",
          "Kesimpulan: Daun sirih memiliki ciri-ciri: hijau tua, bentuk jantung, panjang 12 cm, berbau harum khas, dan bertulang daun menyirip.",
          "",
          "[Ilustrasi: Laporan tertulis rapi di atas meja. Di sampingnya ada tanaman sirih asli sebagai objek pengamatan. Ada centang hijau di pojok laporan.]",
        ],
        contoh: [
          "Bandingkan laporan yang baik dan kurang baik:",
          "",
          "✗ KURANG BAIK: 'Daunnya hijau, bentuknya seperti hati, baunya harum.'",
          "  — Terlalu singkat, tidak ada data ukuran, tidak sistematis.",
          "",
          "✓ BAIK: 'Daun sirih berwarna hijau tua di atas dan hijau muda di bawah. Panjang 12 cm, lebar 8 cm, berbentuk jantung dengan ujung runcing. Beraroma harum khas. Tulang daun menyirip.'",
          "  — Detail, ada data ukuran, sistematis, faktual.",
        ],
      },
    ],
    rangkuman: [
      "[Ilustrasi: Folder laporan dengan tab warna: JUDUL (merah), TUJUAN (biru), HASIL (kuning), KESIMPULAN (hijau). Data dan angka berterbangan di sekeliling. Gaya infografis anak-anak.]",
      "Laporan: teks faktual berdasarkan hasil pengamatan, bersifat objektif.",
      "Struktur laporan: judul, tujuan, hasil pengamatan, kesimpulan.",
      "Mengamati: gunakan panca indra, catat data dengan tabel, ukur jika perlu.",
      "Ciri laporan baik: detail, faktual, sistematis, menggunakan data akurat.",
    ],
  },
  latihan: makeSoal([
    ["Laporan bersifat...", ["Fiktif", "Faktual", "Artistik", "Imajinatif"], 1, "Laporan berdasarkan fakta (faktual)."],
    ["Struktur laporan yang benar adalah...", ["Judul - Hasil - Tujuan - Kesimpulan", "Judul - Tujuan - Hasil - Kesimpulan", "Tujuan - Judul - Hasil", "Hasil - Kesimpulan - Judul"], 1, "Urutan yang benar: Judul → Tujuan → Hasil → Kesimpulan."],
    ["Bagian yang berisi ringkasan hasil adalah...", ["Judul", "Kesimpulan", "Tujuan", "Hasil"], 1, "Kesimpulan adalah ringkasan dari hasil pengamatan."],
    ["Mana data yang bersifat faktual?", ["Daun itu indah", "Panjang daun 12 cm", "Daun itu cantik", "Daun menari"], 1, "'Panjang daun 12 cm' adalah data faktual yang bisa diukur."],
    ["Tujuan laporan adalah untuk...", ["Menghibur", "Menyajikan informasi faktual", "Mendongeng", "Berpuisi"], 1, "Laporan bertujuan menyajikan informasi berdasarkan fakta."],
    ["Alat yang berguna untuk mengukur panjang daun adalah...", ["Timbangan", "Penggaris", "Termometer", "Jam"], 1, "Penggaris digunakan untuk mengukur panjang."],
    ["Laporan yang baik ditulis dengan bahasa...", ["Berima", "Baku dan jelas", "Artistik", "Berbelit"], 1, "Laporan menggunakan bahasa baku dan jelas."],
    ["'Berdasarkan pengamatan, dapat disimpulkan...' — kalimat ini untuk bagian...", ["Tujuan", "Kesimpulan", "Hasil", "Judul"], 1, "Kalimat itu adalah ciri khas bagian kesimpulan."],
    ["Data dalam laporan sebaiknya disajikan dalam bentuk...", ["Puisi", "Angka dan tabel", "Cerita", "Gambar saja"], 1, "Data sebaiknya disajikan dengan angka dan tabel agar jelas."],
    ["Yang membedakan laporan dengan cerita fiksi adalah...", ["Laporan panjang", "Laporan berdasarkan fakta", "Laporan lucu", "Laporan sedih"], 1, "Laporan berdasarkan fakta, cerita fiksi berdasarkan khayalan."],
  ]),
  praktik: {
    petunjuk: "Ambillah satu jenis daun (daun mangga, daun sirih, atau daun lain). Amati dengan saksama, catat data dalam tabel, lalu tulis laporan singkat dengan struktur yang benar!",
    tips: [
      "Gunakan penggaris untuk mengukur panjang dan lebar",
      "Amati warna, bentuk, tepi, ujung, dan tulang daun",
      "Raba permukaannya (halus/kasar/licin)",
      "Tulis kesimpulan yang merangkum semua ciri",
    ],
    contoh: "LAPORAN PENGAMATAN DAUN MANGGA. Tujuan: Mengamati ciri-ciri daun mangga. Hasil: Daun mangga berbentuk lonjong memanjang, panjang 25 cm, lebar 6 cm. Tepi rata, ujung runcing. Warna hijau tua, permukaan halus mengkilap. Tulang daun menyirip dengan tulang utama di tengah. Bau: khas daun segar. Kesimpulan: Daun mangga berbentuk lonjong, hijau tua, panjang 25 cm, bertulang menyirip.",
  },
  kuis: makeSoal([
    ["Bagian laporan yang menjelaskan maksud kegiatan adalah...", ["Hasil", "Tujuan", "Kesimpulan", "Judul"], 1, "Tujuan menjelaskan maksud dari kegiatan pengamatan."],
    ["Laporan harus ditulis secara...", ["Acak", "Sistematis", "Cepat", "Indah"], 1, "Laporan ditulis secara sistematis (berurutan dan rapi)."],
    ["Contoh data kuantitatif (berupa angka) adalah...", ["Daun hijau", "Panjang 12 cm", "Daun halus", "Daun harum"], 1, "'Panjang 12 cm' adalah data kuantitatif karena berupa angka."],
    ["Kesimpulan laporan terdapat di bagian...", ["Awal", "Akhir", "Tengah", "Judul"], 1, "Kesimpulan adalah bagian akhir laporan."],
    ["Data yang dicatat harus sesuai dengan...", ["Opini", "Fakta di lapangan", "Perasaan", "Harapan"], 1, "Data harus sesuai fakta, bukan opini atau harapan."],
    ["'Daun berwarna hijau tua' — ini adalah...", ["Data", "Opini", "Kesimpulan", "Tujuan"], 0, "Warna daun adalah data hasil pengamatan."],
    ["Tabel dalam laporan berguna untuk...", ["Menghias", "Menyajikan data rapi", "Menggambar", "Berhitung"], 1, "Tabel menyajikan data dengan rapi dan mudah dibaca."],
    ["Bagian 'Hasil' berisi...", ["Alat yang digunakan", "Data pengamatan", "Kesimpulan", "Tujuan"], 1, "Hasil berisi data dan fakta dari pengamatan."],
    ["'Sirih' dalam laporan di atas adalah...", ["Judul", "Objek pengamatan", "Kesimpulan", "Alat"], 1, "Daun sirih adalah objek yang diamati."],
    ["Mengapa laporan harus objektif?", ["Agar panjang", "Karena berdasarkan fakta", "Biar sulit", "Agar indah"], 1, "Laporan harus objektif karena berdasarkan fakta, bukan perasaan."],
  ]),
}

export default konten
