import type { Konten } from "../types"
import { makeSoal } from "../types"

const konten: Konten = {
  belajar: {
    tujuan: [
      "Memahami pengertian dan ciri cerita fantasi",
      "Mengidentifikasi unsur keajaiban dalam cerita fantasi",
      "Menulis cerita fantasi pendek dengan imajinasi",
    ],
    materi: [
      {
        judul: "Apa Itu Cerita Fantasi?",
        isi: [
          "Pernahkah kamu membayangkan punya sahabat peri? Atau pergi ke istana di awan?",
          "",
          "Imajinasi seperti itu ada dalam cerita fantasi!",
          "",
          "✓ Cerita fantasi adalah cerita fiksi yang penuh dengan hal-hal ajaib dan imajinatif.",
          "",
          "Ciri-ciri cerita fantasi:",
          "1. Ada keajaiban atau hal mustahil yang terjadi.",
          "2. Tokoh: peri, naga, penyihir, makhluk ajaib.",
          "3. Latar: dunia imajinatif (negeri dongeng, istana awan, dunia bawah laut).",
          "4. Logika cerita tidak terikat dunia nyata.",
          "5. Ada pesan moral di dalamnya.",
          "",
          "[Ilustrasi: Sebuah gerbang pelangi menuju dunia fantasi. Di seberang gerbang terlihat: kastil terbang di awan, naga kecil ramah, peri bersayap, pohon permen, sungai cokelat. Gaya ilustrasi fantasi penuh warna.]",
        ],
        contoh: [
          "Bandingkan cerita nyata dan fantasi:",
          "",
          "✓ NYATA: 'Budi pergi ke pasar bersama ibu. Mereka membeli sayur dan ikan.'",
          "  — Kejadian biasa, masuk akal.",
          "",
          "✓ FANTASI: 'Budi menemukan gerbang ajaib di pasar. Saat memasukinya, ia masuk ke dunia di mana sayuran bisa bicara dan ikan bisa terbang!'",
          "  — Ada keajaiban, tidak masuk akal di dunia nyata.",
        ],
        catatan: "Cerita fantasi berbeda dengan dongeng. Fantasi sengaja dibuat oleh penulis dengan dunia imajinatif baru. Dongeng adalah cerita rakyat turun-temurun.",
      },
      {
        judul: "Unsur Keajaiban dalam Fantasi",
        isi: [
          "Apa yang membuat cerita fantasi terasa ajaib? Unsur-unsur berikut:",
          "",
          "1. TEMPAT AJAIB: negeri awan, sekolah sihir, hutan terlarang, istana bawah laut.",
          "2. TOKOH AJAIB: peri, penyihir, naga, unicorn, raksasa, kurcaci.",
          "3. BENDA AJAIB: tongkat sihir, sepatu terbang, jubah tembus pandang, cermin ajaib.",
          "4. KEJADIAN AJAIB: bisa terbang, bicara dengan hewan, berubah wujud.",
          "",
          "[Ilustrasi: Tiga benda ajaib bersinar: tongkat sihir dengan bintang di ujungnya, sepatu bersayap, dan cermin bundar yang memancarkan cahaya. Di sekelilingnya ada peri dan kurcaci. Gaya ilustrasi fantasi anak-anak.]",
        ],
        contoh: [
          "Contoh unsur fantasi dalam cerita:",
          "",
          "'Rara menemukan sebuah cermin tua di loteng. Saat ia menyentuhnya, cermin itu bersinar terang dan menarik Rara masuk ke dalamnya. Ia tiba di dunia di mana bunga-bunga bisa bernyanyi dan kupu-kupu sebesar burung beterbangan di sekitarnya.'",
          "",
          "Unsur fantasi:",
          "✓ Cermin ajaib (benda ajaib).",
          "✓ Dunia di dalam cermin (tempat ajaib).",
          "✓ Bunga bernyanyi, kupu-kupu besar (kejadian ajaib).",
        ],
      },
      {
        judul: "Menulis Cerita Fantasi",
        isi: [
          "Sekarang giliranmu menulis cerita fantasi!",
          "",
          "Langkah-langkah:",
          "",
          "1. Tentukan latar (dunia fantasi: negeri awan, hutan sihir, planet lain).",
          "2. Tentukan tokoh (biasa atau ajaib).",
          "3. Tentukan konflik (masalah yang harus dihadapi).",
          "4. Tentukan benda ajaib yang membantu tokoh.",
          "5. Tulis dengan imajinasi sebebas mungkin!",
          "",
          "Tips menulis fantasi:",
          "• Ciptakan dunia dengan aturannya sendiri.",
          "• Gunakan kata-kata yang menggambarkan keajaiban.",
          "• Tambahkan dialog tokoh agar cerita hidup.",
          "",
          "[Ilustrasi: Seorang anak duduk di meja, menulis dengan pena yang mengeluarkan percikan bintang. Di sekelilingnya, imajinasinya menjadi nyata: naga kecil, kastil, dan peri melayang-layang di atas kertas. Gaya ilustrasi imajinatif anak-anak.]",
        ],
        contoh: [
          "Kerangka cerita fantasi 'Petualangan di Negeri Awan':",
          "",
          "AWAL: Bimo, anak kelas 3, menemukan tangga pelangi di halaman rumahnya.",
          "KONFLIK: Ia naik dan tiba di Negeri Awan. Ternyata negeri itu kering karena awan-awan bahagia hilang. Ratu Awan meminta bantuan Bimo.",
          "PENYELESAIAN: Bimo menggunakan peluit ajaib untuk memanggil angin senang. Awan-awan kembali dan Negeri Awan hujan lagi.",
          "PESAN: Kebahagiaan bisa menyebar jika kita peduli pada orang lain.",
        ],
      },
    ],
    rangkuman: [
      "[Ilustrasi: Peta dunia fantasi dengan nama-nama tempat: Negeri Awan, Hutan Peri, Istana Kristal, Lautan Bintang. Ada jalur garis putus-putus petualangan. Gaya peta harta karun fantasi.]",
      "Cerita fantasi: cerita fiksi dengan keajaiban dan hal mustahil, penuh imajinasi.",
      "Ciri: tempat ajaib, tokoh ajaib, benda ajaib, kejadian ajaib, logika tidak terikat dunia nyata.",
      "Unsur pembangun: latar imajinatif, tokoh unik, konflik, dan benda ajaib.",
      "Tips: ciptakan duniamu sendiri dengan aturan imajinatif yang seru!",
    ],
  },
  latihan: makeSoal([
    ["Cerita fantasi bersifat...", ["Nyata", "Khayal dan imajinatif", ["Sejarah"], ["Ilmiah"]], 1, "Cerita fantasi adalah khayalan/imajinasi, bukan kenyataan."],
    ["Contoh tokoh dalam cerita fantasi adalah...", ["Dokter", "Peri", ["Guru"], ["Petani"]], 1, "Peri adalah tokoh khas cerita fantasi."],
    ["Benda ajaib dalam cerita fantasi contohnya...", ["Pensil", "Tongkat sihir", ["Buku"], ["Meja"]], 1, "Tongkat sihir adalah benda ajaib khas fantasi."],
    ["Yang membedakan fantasi dengan dongeng adalah...", ["Fantasi lebih panjang", "Fantasi sengaja dibuat penulis, dongeng turun-temurun", ["Fantasi sedih"], ["Dongeng lucu"]], 1, "Fantasi adalah ciptaan penulis, dongeng adalah cerita rakyat turun-temurun."],
    ["Latar dalam cerita fantasi biasanya...", ["Sekolah biasa", "Dunia imajinatif", ["Pasar"], ["Rumah sakit"]], 1, "Latar fantasi adalah dunia imajinatif seperti negeri awan, istana sihir, dll."],
    ["'Rara menemukan cermin ajaib di loteng' — ini bagian...", ["Awal", "Tengah", ["Akhir"], ["Penutup"]], 0, "Ini adalah awal cerita (pengenalan benda ajaib)."],
    ["Unsur keajaiban dalam cerita fantasi berfungsi...", ["Membosankan", "Membuat cerita menarik dan tidak terduga", ["Menyulitkan"], ["Menakutkan"]], 1, "Unsur keajaiban membuat cerita fantasi menarik."],
    ["Contoh tempat ajaib dalam cerita fantasi adalah...", ["Kelas 3 SD", "Negeri Awan", ["Terminal bus"], ["Rumah sakit"]], 1, "Negeri Awan adalah tempat ajaib dalam cerita fantasi."],
    ["'Bimo menggunakan peluit ajaib' — ini adalah contoh...", ["Tempat ajaib", "Benda ajaib", ["Tokoh ajaib"], ["Konflik"]], 1, "Peluit ajaib adalah benda ajaib."],
    ["Cerita fantasi biasanya memiliki...", ["Pesan moral", ["Data penelitian"], "Laporan", "Angka"], 0, "Seperti cerita lain, fantasi juga punya pesan moral."],
  ]),
  praktik: {
    petunjuk: "Buat cerita fantasi pendek 3-4 paragraf dengan tema 'Menemukan Benda Ajaib'. Gunakan struktur: awal (menemukan benda), tengah (petualangan), akhir (penyelesaian)!",
    tips: [
      "Benda ajaib bisa apa saja: kacamata, pensil, buku, atau batu",
      "Ciptakan dunia baru tempat petualangan terjadi",
      "Buat tokoh yang menghadapi masalah",
      "Akhiri dengan penyelesaian yang bahagia",
    ],
    contoh: "Judul: 'Pensil Ajaib'. — AWAL: Dita menemukan pensil emas di perpustakaan sekolah. — TENGAH: Saat Dita menulis dengan pensil itu, tulisannya menjadi nyata! Ia tidak sengaja menulis 'naga' dan naga kecil muncul. Naga itu mengajak Dita ke dunia pensil. — AKHIR: Di dunia pensil, semua benda terbuat dari krayon raksasa. Dita membantu penduduk mewarnai kota mereka yang pudar. — PESAN: Kreativitas bisa mengubah dunia.",
  },
  kuis: makeSoal([
    ["'Seperti apa rasanya tinggal di istana awan?' — ini contoh...", ["Cerita nyata", "Imajinasi fantasi", ["Laporan"], ["Sejarah"]], 1, "Istana awan adalah dunia imajinatif dalam fantasi."],
    ["Yang termasuk tokoh fantasi adalah...", ["Polisi", "Penyihir", ["Nelayan"], ["Dokter"]], 1, "Penyihir adalah tokoh khas cerita fantasi."],
    ["Cerita fantasi biasanya penuh dengan...", ["Kebosanan", "Keajaiban", ["Kesedihan"], ["Kemarahan"]], 1, "Cerita fantasi penuh dengan keajaiban dan hal mustahil."],
    ["Unsur yang membuat fantasi berbeda dari cerita biasa adalah...", ["Tokohnya banyak", "Ada keajaiban/ hal mustahil", ["Latar jelas"], ["Bahasa indah"]], 1, "Unsur keajaiban adalah pembeda utama cerita fantasi."],
    ["'Jubah tembus pandang' termasuk...", ["Tempat ajaib", "Benda ajaib", ["Tokoh ajaib"], ["Konflik"]], 1, "Jubah tembus pandang adalah benda ajaib."],
    ["Dalam cerita fantasi, hewan bisa...", ["Diam saja", "Bicara seperti manusia", ["Tidak bergerak"], ["Hanya makan"]], 1, "Dalam fantasi, hewan bisa bicara, berpikir, dan bertindak seperti manusia."],
    ["Konflik dalam cerita fantasi sering berkaitan dengan...", ["PR sekolah", "Menyelamatkan dunia ajaib", ["Ujian"], ["Pekerjaan rumah"]], 1, "Konflik fantasi biasanya tentang petualangan menyelamatkan sesuatu."],
    ["Contoh kalimat pembuka cerita fantasi adalah...", ["Hari ini Budi bangun pagi", "Di balik lemari tuanya, Lina menemukan pintu kecil bercahaya", ["Ibu pergi ke pasar"], "Kucingku makan ikan"], 1, "Pintu kecil bercahaya adalah awal yang fantastis."],
    ["Pesan moral dalam cerita fantasi disampaikan melalui...", ["Data", "Petualangan tokoh", ["Angka"], ["Tabel"]], 1, "Pesan moral disampaikan melalui pengalaman dan petualangan tokoh."],
    ["Cerita fantasi termasuk jenis...", ["Nonfiksi", "Fiksi", ["Biografi"], ["Laporan"]], 1, "Cerita fantasi adalah fiksi (khayalan)."],
  ]),
}

export default konten
