import type { Konten } from "../types"
import { makeSoal } from "../types"

const konten: Konten = {
  belajar: {
    tujuan: [
      "Menemukan gagasan pokok dalam paragraf",
      "Membedakan kalimat utama dan kalimat penjelas",
      "Meringkas bacaan berdasarkan gagasan pokok",
    ],
    materi: [
      {
        judul: "Apa Itu Gagasan Pokok?",
        isi: [
          "Setiap paragraf punya satu ide utama. Ide utama itu disebut gagasan pokok!",
          "",
          "✓ Gagasan pokok adalah ide atau topik utama yang dibahas dalam suatu paragraf.",
          "✓ Gagasan pokok biasanya terletak di kalimat utama (bisa di awal, tengah, atau akhir paragraf).",
          "",
          "Cara menemukan gagasan pokok:",
          "1. Baca paragraf dengan saksama.",
          "2. Tanyakan: 'Tentang apa paragraf ini?'",
          "3. Cari kalimat yang paling mewakili isi paragraf.",
          "4. Kalimat itu adalah kalimat utama yang berisi gagasan pokok.",
          "",
          "[Ilustrasi: Sebuah paragraf dengan kalimat utama dilingkari warna merah bertuliskan 'GAGASAN POKOK'. Kalimat lainnya diberi warna biru dengan label 'KALIMAT PENJELAS'. Gaya diagram paragraf.]",
        ],
        contoh: [
          "Analisis paragraf:",
          "",
          "\"Kebersihan lingkungan sangat penting bagi kesehatan. Lingkungan yang bersih membuat kita terhindar dari penyakit. Sampah yang berserakan bisa menjadi sarang nyamuk. Oleh karena itu, kita harus menjaga kebersihan lingkungan sekitar kita.\"",
          "",
          "✓ Gagasan pokok: 'Kebersihan lingkungan penting bagi kesehatan.' (kalimat pertama)",
          "✓ Kalimat penjelas: kalimat 2-4 (menjelaskan dan mendukung gagasan pokok).",
          "",
          "Tips: Jika bingung, coba buang kalimat demi kalimat. Kalimat yang jika dibuang membuat paragraf tidak jelas — itulah gagasan pokok!",
        ],
        catatan: "Gagasan pokok disebut juga 'ide pokok', 'pikiran utama', atau 'gagasan utama'. Semua istilah itu sama artinya.",
      },
      {
        judul: "Letak Gagasan Pokok",
        isi: [
          "Gagasan pokok bisa terletak di beberapa tempat dalam paragraf:",
          "",
          "1. DI AWAL (deduktif) — paling umum.",
          "  'Belajar kelompok memiliki banyak manfaat. Kita bisa bertukar pikiran dengan teman. Kita juga bisa saling membantu jika ada yang kesulitan.'",
          "  ✓ Gagasan pokok: Belajar kelompok bermanfaat (kalimat 1).",
          "",
          "2. DI AKHIR (induktif) — kesimpulan di akhir.",
          "  'Kita bisa bertukar pikiran. Kita saling membantu. Teman yang kesulitan dibantu. Jadi, belajar kelompok sangat bermanfaat.'",
          "  ✓ Gagasan pokok: Belajar kelompok bermanfaat (kalimat terakhir).",
          "",
          "3. DI AWAL DAN AKHIR (campuran) — gagasan pokok diulang.",
          "  'Belajar kelompok bermanfaat. Kita... (penjelasan). Jadi, jelas bahwa belajar kelompok bermanfaat.'",
          "",
          "[Ilustrasi: Tiga paragraf dengan tanda panah merah menunjuk letak gagasan pokok. Paragraf 1: panah ke awal. Paragraf 2: panah ke akhir. Paragraf 3: panah ke awal dan akhir.]",
        ],
        contoh: [
          "Cari gagasan pokok dalam paragraf ini:",
          "",
          "'Bermain di luar ruangan sangat baik untuk anak-anak. Tubuh mereka bergerak aktif sehingga sehat. Mereka juga bisa bersosialisasi dengan teman. Selain itu, mereka mengenal alam sekitar. Dengan demikian, bermain di luar memberi banyak manfaat untuk tumbuh kembang anak.'",
          "",
          "✓ Gagasan pokok di AWAL: 'Bermain di luar baik untuk anak-anak.'",
          "✓ Juga ditegaskan di AKHIR: 'Bermain di luar bermanfaat untuk tumbuh kembang.'",
          "",
          "PENTING: Dalam satu paragraf, gagasan pokok hanya SATU, meskipun ditulis di awal dan akhir.",
        ],
      },
      {
        judul: "Meringkas Bacaan",
        isi: [
          "Kemampuan menemukan gagasan pokok berguna untuk meringkas bacaan.",
          "",
          "Langkah meringkas:",
          "",
          "1. Baca bacaan secara keseluruhan.",
          "2. Temukan gagasan pokok setiap paragraf.",
          "3. Catat gagasan pokok dalam 1-2 kalimat per paragraf.",
          "4. Gabungkan semua gagasan pokok menjadi paragraf baru.",
          "5. Gunakan bahasa sendiri, jangan menyalin kalimat asli.",
          "",
          "Contoh ringkasan:",
          "",
          "Bacaan asli (3 paragraf):...",
          "Ringkasan: 'Kebersihan lingkungan penting untuk kesehatan. Belajar kelompok bermanfaat. Membaca buku memperluas wawasan.'",
          "",
          "[Ilustrasi: Buku tebal diubah menjadi kertas kecil berisi ringkasan. Ada panah dari buku besar ke ringkasan. Ikon: buku + panah → kertas catatan. Gaya meringkas visual.]",
        ],
        contoh: [
          "Bandingkan ringkasan baik dan kurang baik:",
          "",
          "✗ KURANG BAIK: 'Menyalin kalimat pertama setiap paragraf...'",
          "  — Hanya menyalin, belum meringkas dengan kata sendiri.",
          "",
          "✓ BAIK: 'Kebersihan lingkungan penting untuk mencegah penyakit. Menjaga kebersihan adalah tanggung jawab bersama. Lingkungan bersih membuat hidup lebih nyaman dan sehat.'",
          "  — Menggunakan kata sendiri, hanya gagasan pokok.",
          "",
          "Tips: Ringkasan harus lebih pendek dari bacaan asli! Jika masih panjang, berarti belum benar.",
        ],
      },
    ],
    rangkuman: [
      "[Ilustrasi: Peta pikiran dengan 'GAGASAN POKOK' di tengah, cabang: LETAK DI AWAL, LETAK DI AKHIR, LETAK CAMPURAN, CARI DENGAN TANYA 'TENTANG APA?'. Gaya mind map anak-anak.]",
      "Gagasan pokok: ide utama dalam paragraf. Biasanya di kalimat utama.",
      "Letak gagasan pokok: awal (deduktif), akhir (induktif), atau awal & akhir (campuran).",
      "Kalimat penjelas: kalimat yang mendukung gagasan pokok.",
      "Meringkas: temukan gagasan pokok tiap paragraf, tulis ulang dengan kata sendiri.",
    ],
  },
  latihan: makeSoal([
    ["Gagasan pokok adalah...", ["Ide utama dalam paragraf", "Kalimat penjelas", ["Kata sulit"], ["Judul bacaan"]], 0, "Gagasan pokok adalah ide utama dalam paragraf."],
    ["Kalimat yang berisi gagasan pokok disebut...", ["Kalimat penjelas", "Kalimat utama", ["Kalimat tanya"], ["Kalimat perintah"]], 1, "Kalimat utama adalah kalimat yang berisi gagasan pokok."],
    ["Jika gagasan pokok di awal paragraf disebut...", ["Induktif", "Deduktif", ["Campuran"], ["Acak"]], 1, "Deduktif: gagasan pokok di awal paragraf."],
    ["Tanyakan 'Tentang apa paragraf ini?' untuk menemukan...", ["Kalimat penjelas", "Gagasan pokok", ["Kata sulit"], ["Judul"]], 1, "Pertanyaan 'Tentang apa?' membantu menemukan gagasan pokok."],
    ["Yang BUKAN fungsi kalimat penjelas adalah...", ["Mendukung gagasan pokok", "Menjadi ide utama", ["Memberi contoh"], ["Menjelaskan"]], 1, "Kalimat penjelas bukan ide utama; gagasan pokok adalah ide utama."],
    ["'Belajar kelompok bermanfaat. Kita bisa bertukar pikiran...' — gagasan pokoknya...", ["Bertukar pikiran", "Belajar kelompok bermanfaat", ["Belajar kelompok"], ["Kita bisa"]], 1, "Kalimat pertama adalah gagasan pokok (deduktif)."],
    ["Ringkasan yang baik menggunakan...", ["Kalimat asli", "Kata sendiri", ["Kalimat panjang"], ["Semua kata"]], 1, "Ringkasan menggunakan kata sendiri, bukan menyalin kalimat asli."],
    ["Gagasan pokok dalam satu paragraf berjumlah...", ["Banyak", "Satu", ["Dua"], ["Tidak ada"]], 1, "Setiap paragraf hanya punya SATU gagasan pokok."],
    ["'Jadi, ...' atau 'Dengan demikian, ...' — kata ini menandai gagasan pokok di...", ["Awal", "Akhir", ["Tengah"], ["Semua"]], 1, "Kata 'jadi' atau 'dengan demikian' menandai kesimpulan (gagasan pokok di akhir)."],
    ["Meringkas berarti...", ["Memperpanjang", "Memendekkan dengan mengambil inti", ["Menyalin semua"], ["Mengubah"]], 1, "Meringkas berarti memendekkan bacaan dengan mengambil inti atau gagasan pokok."],
  ]),
  praktik: {
    petunjuk: "Bacalah paragraf berikut, temukan gagasan pokoknya, lalu buat ringkasan satu paragraf!",
    tips: [
      "Baca setiap paragraf dan cari kalimat utamanya",
      "Tulis gagasan pokok dengan kata-katamu sendiri",
      "Gabungkan semua gagasan pokok jadi satu paragraf pendek",
      "Pastikan ringkasan lebih pendek dari bacaan asli",
    ],
    contoh: "Paragraf 1: Membaca buku adalah jendela dunia. Dengan membaca, kita tahu banyak hal tanpa harus pergi ke tempatnya. Buku memberi ilmu dan pengetahuan. Paragraf 2: Perpustakaan adalah tempat yang tepat untuk membaca. Di perpustakaan banyak buku tersedia. Suasana hening membuat kita fokus. Paragraf 3: Rajin membaca membuat kita pintar. Pengetahuan bertambah, wawasan meluas. Membaca juga melatih otak berpikir. Ringkasan: Membaca buku memberi banyak pengetahuan dan wawasan. Perpustakaan adalah tempat ideal untuk membaca. Rajin membaca membuat kita pintar karena otak terlatih berpikir.",
  },
  kuis: makeSoal([
    ["Paragraf deduktif memiliki gagasan pokok di...", ["Awal", "Akhir", ["Tengah"], ["Campuran"]], 0, "Deduktif: gagasan pokok di awal paragraf."],
    ["'Oleh karena itu, ...' — biasanya menandai...", ["Gagasan pokok", "Kalimat penjelas", ["Kata tanya"], ["Judul"]], 0, "'Oleh karena itu' menandai kesimpulan atau gagasan pokok."],
    ["Jumlah gagasan pokok dalam bacaan 5 paragraf adalah...", ["1", "5", ["Tidak tentu"], ["10"]], 1, "Setiap paragraf punya 1 gagasan pokok, jadi 5 paragraf = 5 gagasan pokok."],
    ["Kalimat penjelas berfungsi...", ["Mendukung gagasan pokok", "Menjadi ide utama", ["Menjadi judul"], ["Penutup"]], 0, "Kalimat penjelas mendukung dan menjelaskan gagasan pokok."],
    ["Ringkasan harus...", ["Lebih panjang", "Lebih pendek dari asli", ["Sama panjang"], ["Berbeda topik"]], 1, "Ringkasan harus lebih pendek karena hanya berisi inti."],
    ["'Belajar di rumah juga penting. Kita bisa mengulang pelajaran. Orang tua bisa membantu.' — gagasan pokoknya...", ["Belajar di rumah penting", "Mengulang pelajaran", ["Orang tua membantu"], ["Belajar"]], 0, "Kalimat pertama adalah gagasan pokok."],
    ["Mana yang termasuk kalimat penjelas?", ["Kebersihan itu penting", "Sampah bisa menjadi sarang penyakit", ["Belajar itu perlu"], ["Membaca itu baik"]], 1, "'Sampah menjadi sarang penyakit' adalah penjelas dari gagasan 'kebersihan penting'."],
    ["Ciri paragraf induktif: gagasan pokok di...", ["Awal", "Akhir", ["Tengah"], ["Semua"]], 1, "Induktif: gagasan pokok di akhir paragraf."],
    ["'Dengan kata lain, ...' — menandai...", ["Gagasan pokok", "Kalimat penjelas", ["Kata baru"], ["Contoh"]], 0, "'Dengan kata lain' menandai penegasan gagasan pokok."],
    ["Meringkas melatih kemampuan...", ["Menulis cepat", "Memahami inti bacaan", ["Menghafal"], ["Berhitung"]], 1, "Meringkas melatih kemampuan memahami inti bacaan."],
  ]),
}

export default konten
