import type { Konten } from "../types"
import { makeSoal } from "../types"

const konten: Konten = {
  belajar: {
    tujuan: [
      "Membedakan cerita fiksi dan nonfiksi",
      "Mengenal unsur intrinsik cerita fiksi",
      "Mengapresiasi cerita fiksi dengan memberikan komentar",
    ],
    materi: [
      {
        judul: "Fiksi vs Nonfiksi",
        isi: [
          "Setiap buku yang kita baca bisa digolongkan menjadi fiksi atau nonfiksi.",
          "",
          "✓ FIKSI: cerita rekaan/khayalan penulis.",
          "  • Berdasarkan imajinasi, bukan fakta.",
          "  • Tujuan: menghibur dan menyampaikan pesan moral.",
          "  • Contoh: novel, cerpen, dongeng, komik, cerita fantasi.",
          "",
          "✓ NONFIKSI: buku berdasarkan fakta dan data.",
          "  • Berdasarkan kenyataan dan penelitian.",
          "  • Tujuan: memberi informasi dan pengetahuan.",
          "  • Contoh: ensiklopedia, biografi, buku pelajaran, laporan.",
          "",
          "[Ilustrasi: Rak buku terbagi dua sisi. Sisi kiri (FIKSI) dengan buku-buku bergambar: novel, komik, dongeng — warna-warni. Sisi kanan (NONFIKSI) dengan buku-buku rapi: ensiklopedia, atlas, buku sains — warna kalem.]",
        ],
        contoh: [
          "Perbandingan fiksi dan nonfiksi:",
          "",
          "FIKSI:",
          "✓ 'Kancil dan Buaya' — cerita hewan bisa bicara (khayalan).",
          "✓ 'Petualangan di Negeri Awan' — dunia imajinasi.",
          "",
          "NONFIKSI:",
          "✓ 'Ensiklopedia Hewan' — data tentang hewan nyata.",
          "✓ 'Biografi Ki Hajar Dewantara' — kisah nyata pahlawan.",
          "",
          "Tips: Cek sampul buku. Jika ada kata 'novel' atau 'cerita' biasanya fiksi. Jika ada 'fakta', 'data', 'ilmiah' biasanya nonfiksi.",
        ],
      },
      {
        judul: "Unsur Intrinsik Cerita Fiksi",
        isi: [
          "Cerita fiksi memiliki unsur-unsur pembangun dari dalam (intrinsik):",
          "",
          "1. TEMA — topik utama cerita (persahabatan, petualangan).",
          "2. TOKOH — pelaku cerita (protagonis/antagonis).",
          "3. ALUR — urutan peristiwa (awal, tengah, akhir).",
          "4. LATAR — tempat, waktu, dan suasana.",
          "5. SUDUT PANDANG — cara penulis menceritakan (aku/dia).",
          "6. AMANAT — pesan moral yang ingin disampaikan.",
          "",
          "[Ilustrasi: Buku cerita terbuka dengan kata-kata kunci melayang keluar: TEMA (bintang), TOKOH (orang), ALUR (panah), LATAR (rumah), SUDUT PANDANG (mata), AMANAT (hati). Gaya infografis sastra anak.]",
        ],
        contoh: [
          "Analisis unsur intrinsik 'Kura-kura dan Kelinci':",
          "",
          "✓ TEMA: Ketekunan vs Kesombongan.",
          "✓ TOKOH: Kura-kura (tekun), Kelinci (sombong).",
          "✓ ALUR: Awal (tantangan lomba) → Tengah (lomba, kelinci tidur) → Akhir (kura-kura menang).",
          "✓ LATAR: Hutan, jalan lomba, waktu siang.",
          "✓ SUDUT PANDANG: Orang ketiga (dia).",
          "✓ AMANAT: Ketekunan dan kerendahan hati akan menang.",
        ],
        catatan: "Selain unsur intrinsik, ada juga unsur ekstrinsik: latar belakang penulis, nilai sosial-budaya, dan kondisi masyarakat saat cerita dibuat.",
      },
      {
        judul: "Mengapresiasi Cerita Fiksi",
        isi: [
          "Mengapresiasi berarti memberi tanggapan atau penilaian terhadap cerita.",
          "",
          "Cara mengapresiasi cerita fiksi:",
          "",
          "1. Baca cerita sampai selesai.",
          "2. Pahami unsur intrinsiknya.",
          "3. Beri komentar tentang:",
          "  • Bagian yang paling menarik.",
          "  • Tokoh favorit dan alasannya.",
          "  • Pesan moral yang didapat.",
          "  • Kelebihan dan kekurangan cerita.",
          "",
          "Contoh apresiasi:",
          "'Cerita Kura-kura dan Kelinci sangat menarik. Tokoh favoritku adalah kura-kura karena ia tekun dan tidak menyerah. Pesan moralnya mengajarkan bahwa kesombongan bisa menjatuhkan. Ceritanya seru, tapi aku ingin tahu lebih banyak tentang kehidupan kura-kura setelah lomba.'",
          "",
          "[Ilustrasi: Seorang anak memegang buku dengan jempol ke atas (suka) dan buku catatan berisi komentar tentang buku yang dibaca. Gaya book reviewer cilik.]",
        ],
        contoh: [
          "Contoh apresiasi buku fiksi:",
          "",
          "Judul: Si Kancil yang Cerdik",
          "",
          "✓ Bagian paling seru: saat Kancil menipu buaya.",
          "✓ Tokoh favorit: Kancil, karena cerdik dan pemberani.",
          "✓ Pesan moral: Kecerdikan bisa menyelamatkan diri.",
          "✓ Saran: Ceritanya seru, sebaiknya ditambah ilustrasi yang lebih banyak.",
          "",
          "Tips: Apresiasi tidak harus pujian. Kamu juga bisa memberi kritik membangun (saran perbaikan)!",
        ],
      },
    ],
    rangkuman: [
      "[Ilustrasi: Dua tumpukan buku: FIKSI (warna-warni, gambar menarik) dan NONFIKSI (warna kalem, rapi). Di tengah ada timbangan yang seimbang — keduanya sama pentingnya untuk dibaca.]",
      "Fiksi: cerita khayalan (novel, dongeng, komik). Nonfiksi: berdasarkan fakta (ensiklopedia, biografi).",
      "Unsur intrinsik: tema, tokoh, alur, latar, sudut pandang, amanat.",
      "Mengapresiasi: memberi komentar tentang bagian seru, tokoh favorit, pesan moral, dan saran.",
      "Apresiasi bisa berupa pujian (kelebihan) dan kritik membangun (saran perbaikan).",
    ],
  },
  latihan: makeSoal([
    ["Buku berdasarkan khayalan penulis disebut...", ["Nonfiksi", "Fiksi", "Ensiklopedia", "Biografi"], 1, "Fiksi adalah cerita rekaan/khayalan penulis."],
    ["Contoh buku nonfiksi adalah...", ["Novel", "Ensiklopedia", "Komik", "Dongeng"], 1, "Ensiklopedia berisi fakta, termasuk nonfiksi."],
    ["Unsur intrinsik yang berupa urutan peristiwa disebut...", ["Tema", "Alur", "Tokoh", "Latar"], 1, "Alur adalah urutan peristiwa dalam cerita."],
    ["Tokoh baik dalam cerita disebut...", ["Antagonis", "Protagonis", "Figuran", "Penjahat"], 1, "Protagonis adalah tokoh baik/utama."],
    ["Latar meliputi...", ["Tema dan amanat", "Tempat, waktu, suasana", "Tokoh dan alur", "Judul"], 1, "Latar mencakup tempat, waktu, dan suasana cerita."],
    ["Mengapresiasi cerita artinya...", ["Membaca cepat", "Memberi tanggapan/penilaian", "Menyalin", "Menghafal"], 1, "Apresiasi adalah tanggapan atau penilaian terhadap cerita."],
    ["Sudut pandang 'aku' berarti penulis sebagai...", ["Orang ketiga", "Orang pertama (pelaku)", "Orang kedua", "Pengamat"], 1, "'Aku' adalah sudut pandang orang pertama sebagai pelaku."],
    ["'Ceritanya seru, tapi alurnya lambat di tengah' — ini contoh...", ["Apresiasi", "Sinopsis", "Ringkasan", "Laporan"], 0, "Ini adalah apresiasi berupa kritik membangun."],
    ["Amanat adalah...", ["Tempat cerita", "Pesan moral", "Tokoh", "Judul"], 1, "Amanat adalah pesan moral dalam cerita."],
    ["Contoh buku fiksi adalah...", ["Buku IPA", "Novel anak", "Atlas", "Kamus"], 1, "Novel anak adalah fiksi."],
  ]),
  praktik: {
    petunjuk: "Bacalah satu cerita fiksi pendek (dongeng atau cerpen anak), lalu buat apresiasi singkat yang mencakup: judul, tokoh favorit, bagian paling seru, pesan moral, dan saranmu!",
    tips: [
      "Pilih cerita yang kamu suka",
      "Identifikasi unsur intrinsiknya",
      "Tulis pendapatmu dengan jujur",
      "Sertakan alasan, jangan hanya 'suka' atau 'tidak suka'",
    ],
    contoh: "Judul: 'Kancil dan Buaya'. Tokoh favorit: Kancil, karena cerdik. Bagian seru: saat Kancil menipu buaya untuk berbaris. Pesan moral: Kecerdikan mengalahkan kekuatan. Saran: Ceritanya seru, tapi akan lebih baik jika ditambahkan dialog yang lebih banyak.",
  },
  kuis: makeSoal([
    ["Perbedaan utama fiksi dan nonfiksi adalah...", ["Panjang buku", "Fiksi khayalan, nonfiksi fakta", "Warna sampul", "Harga"], 1, "Fiksi khayalan, nonfiksi berdasarkan fakta."],
    ["Tokoh antagonis bersifat...", ["Baik", "Jahat", "Lucu", "Pendiam"], 1, "Antagonis adalah tokoh jahat."],
    ["Alur mundur (flashback) berarti...", ["Cerita dari awal", "Cerita kembali ke masa lalu", "Cerita acak", "Cerita cepat"], 1, "Flashback adalah alur mundur ke masa lalu."],
    ["'Buku ini membosankan karena tidak ada konflik' — ini apresiasi berupa...", ["Pujian", "Kritik", "Sinopsis", "Ringkasan"], 1, "Ini kritik (bagian dari apresiasi)."],
    ["Tema cerita 'Malin Kundang' adalah...", ["Persahabatan", "Durhaka pada orang tua", "Petualangan", "Cinta"], 1, "Tema Malin Kundang adalah durhaka pada orang tua."],
    ["Latar waktu dalam 'Kancil dan Buaya' adalah...", ["Malam", "Siang hari", "Pagi", "Sore"], 1, "Cerita Kancil terjadi di siang hari saat Kancil menyeberang."],
    ["Ensiklopedia termasuk buku...", ["Fiksi", "Nonfiksi", "Dongeng", "Novel"], 1, "Ensiklopedia berisi data dan fakta ilmiah."],
    ["Apresiasi setidaknya harus mencantumkan...", ["Harga buku", "Pendapat dan alasan", "Tebal buku", "Penerbit"], 1, "Apresiasi berisi pendapat yang disertai alasan."],
    ["Tokoh figuran adalah tokoh yang...", ["Paling penting", "Muncul sebentar", "Jahat", "Baik"], 1, "Figuran muncul sebentar, tidak terlalu penting."],
    ["Membaca fiksi dan nonfiksi sama pentingnya karena...", ["Fiksi menghibur, nonfiksi menambah ilmu", "Fiksi lebih baik", "Nonfiksi lebih baik", "Sama saja"], 0, "Fiksi menghibur, nonfiksi menambah pengetahuan."],
  ]),
}

export default konten
