import type { Konten } from "../types"
import { makeSoal } from "../types"

const konten: Konten = {
  belajar: {
    tujuan: [
      "Mengenal jenis-jenis pantun (nasihat, jenaka, teka-teki, kias)",
      "Menganalisis nilai moral dalam pantun",
      "Menciptakan pantun dengan tema tertentu",
    ],
    materi: [
      {
        judul: "Jenis-Jenis Pantun Lengkap",
        isi: [
          "Selain nasihat, jenaka, dan teka-teki yang sudah kita pelajari, ada satu jenis lagi: pantun kias!",
          "",
          "1. PANTUN NASIHAT — berisi pesan moral, nasihat, atau ajaran.",
          "2. PANTUN JENAKA — berisi kelucuan, menghibur.",
          "3. PANTUN TEKA-TEKI — berisi tebakan yang harus dijawab.",
          "4. PANTUN KIAS — berisi perbandingan atau sindiran halus.",
          "",
          "Contoh pantun kias:",
          "'Bagai air di daun talas'",
          "'Susah terurai karena sempit'",
          "'Hidup di dunia hanya sementara'",
          "'Jangan lupa bekal akhirat'",
          "",
          "[Ilustrasi: Empat kartu pantun dengan ikon: Nasihat (bintang), Jenaka (tertawa), Teka-teki (tanya), Kias (timbangan). Masing-masing dengan contoh singkat. Gaya kartu permainan edukasi.]",
        ],
        contoh: [
          "Perbandingan semua jenis pantun:",
          "",
          "✓ NASIHAT: 'Rajin belajar setiap hari / Agar pintar dan berilmu'",
          "✓ JENAKA: 'Anak kucing turun ke bawah / Mencari ikan di kolam dangkal'",
          "✓ TEKA-TEKI: 'Kalau tuan pergi ke kota / Jangan lupa membawa bedak' (jawab: gunting)",
          "✓ KIAS: 'Bagaikan pungguk merindukan bulan' (kiasan tentang sesuatu yang sulit tercapai)",
          "",
          "Tips: Pantun kias menggunakan perbandingan atau perumpamaan untuk menyampaikan maksud.",
        ],
      },
      {
        judul: "Nilai Moral dalam Pantun",
        isi: [
          "Pantun tidak hanya indah, tapi juga mengandung nilai moral yang luhur.",
          "",
          "✓ Nilai moral adalah ajaran tentang baik buruk yang bisa dipetik dari pantun.",
          "",
          "Contoh nilai moral:",
          "",
          "1. NILAI RELIGIUS — ajaran tentang Tuhan dan agama.",
          "  'Sebelum makan baca doa'",
          "  'Agar hidup penuh berkah'",
          "",
          "2. NILAI SOSIAL — hubungan dengan sesama.",
          "  'Tolong-menolong sesama'",
          "  'Hidup rukun damai sentosa'",
          "",
          "3. NILAI PENDIDIKAN — ajaran tentang belajar.",
          "  'Rajin belajar tekun berlatih'",
          "  'Agar cita-cita tercapai'",
          "",
          "[Ilustrasi: Tiga pilar: RELIGIUS (gambar tangan berdoa), SOSIAL (gambar tolong-menolong), PENDIDIKAN (gambar anak belajar). Masing-masing dengan contoh baris pantun. Gaya pilar nilai moral.]",
        ],
        contoh: [
          "Analisis nilai moral:",
          "",
          "Pantun:",
          "'Pergi ke masjid bawa mukena'",
          "'Mukena putih penuh berkah'",
          "'Hormati ibu dan ayahmu'",
          "'Agar hidupmu penuh berkah'",
          "",
          "Nilai moral:",
          "✓ Religius: pergi ke masjid, berkah.",
          "✓ Sosial: hormati orang tua.",
          "",
          "Tips: Cari kata kunci seperti 'jangan', 'rajin', 'hormat', 'sayang' untuk menemukan nilai moral!",
        ],
      },
      {
        judul: "Menciptakan Pantun Bertema",
        isi: [
          "Sekarang, ciptakan pantun dengan tema tertentu!",
          "",
          "Langkah menciptakan pantun:",
          "",
          "1. Tentukan tema (kebersihan, persahabatan, cinta tanah air).",
          "2. Tentukan pesan yang ingin disampaikan (baris 3-4).",
          "3. Cari sampiran (baris 1-2) yang berima dengan isi.",
          "4. Pastikan sajak a-b-a-b.",
          "5. Usahakan setiap baris 8-12 suku kata.",
          "",
          "Contoh tema 'KEBERSIHAN':",
          "",
          "Pesan: Buang sampah pada tempatnya / Agar lingkungan bersih dan sehat.",
          "Sampiran: pergi ke pasar membeli sapu (a) / Sapu dibeli warna hijau (b)",
          "",
          "Hasil:",
          "'Pergi ke pasar membeli sapu'",
          "'Sapu dibeli warna hijau'",
          "'Buanglah sampah pada tempatnya'",
          "'Agar lingkungan bersih dan sehat'",
          "",
          "[Ilustrasi: Anak-anak sedang membuat pantun di kelas. Papan tulis berisi coretan pembuatan pantun. Beberapa anak memegang kertas hasil pantun mereka. Gaya kelas menulis kreatif.]",
        ],
        contoh: [
          "Contoh pantun bertema 'PERSAHABATAN':",
          "",
          "'Pergi ke hutan mencari rotan'",
          "'Rotan dicari untuk kerajinan'",
          "'Sahabat sejati bagai saudara'",
          "'Saling membantu dalam kesulitan'",
          "",
          "Nilai moral: persahabatan, tolong-menolong.",
          "",
          "Tips: Jika kesulitan mencari rima, gunakan kamus rima atau cari kata berakhiran sama!",
        ],
      },
    ],
    rangkuman: [
      "[Ilustrasi: Kumpulan empat pantun dalam frame berbeda: Nasihat (bingkai emas), Jenaka (bingkai warna-warni), Teka-teki (bingkai tanda tanya), Kias (bingkai perbandingan). Di bawah tertulis 'PANTUN NUSANTARA'.]",
      "Jenis pantun: nasihat, jenaka, teka-teki, dan kias.",
      "Nilai moral pantun: religius, sosial, dan pendidikan.",
      "Cara membuat: tentukan tema dan pesan, buat isi dulu, baru sampiran yang berima.",
      "Pantun kias menggunakan perbandingan untuk menyampaikan maksud.",
    ],
  },
  latihan: makeSoal([
    ["Pantun kias berisi...", ["Nasihat", "Perbandingan/sindiran halus", ["Kelucuan"], ["Tebakan"]], 1, "Pantun kias berisi perbandingan atau sindiran halus."],
    ["Nilai moral yang mengajarkan tentang Tuhan disebut...", ["Sosial", "Religius", ["Pendidikan"], ["Budaya"]], 1, "Nilai religius berkaitan dengan ajaran agama dan Tuhan."],
    ["'Tolong-menolong sesama' — ini nilai moral...", ["Religius", "Sosial", ["Pendidikan"], ["Ekonomi"]], 1, "Tolong-menolong adalah nilai sosial."],
    ["'Rajin belajar tekun berlatih' — ini nilai moral...", ["Religius", "Pendidikan", ["Sosial"], ["Budaya"]], 1, "'Rajin belajar' adalah nilai pendidikan."],
    ["Pantun 'Bagaikan pungguk merindukan bulan' termasuk jenis...", ["Nasihat", "Kias", ["Jenaka"], ["Teka-teki"]], 1, "Perbandingan 'seperti pungguk merindukan bulan' adalah kias."],
    ["Nilai moral 'hormati orang tua' termasuk nilai...", ["Religius", "Sosial", ["Pendidikan"], ["Ekonomi"]], 1, "Menghormati orang tua adalah nilai sosial."],
    ["Ciptaan pantun sebaiknya dimulai dari...", ["Sampiran", "Isi/pesan", ["Judul"], ["Baris 1"]], 1, "Lebih mudah membuat isi dulu, baru sampiran."],
    ["'Pergi ke pasar membeli jamu' — baris ini rima 'u'. Cari pasangan rima 'u'...", ["Indah", "Selalu", ["Cepat"], ["Murah"]], 1, "'Selalu' berima 'u' dengan 'jamu'."],
    ["Pantun bertema 'cinta tanah air' termasuk nilai moral...", ["Religius", "Nasionalisme", ["Pendidikan"], ["Sosial"]], 1, "Cinta tanah air adalah nilai nasionalisme."],
    ["Mana rima yang tepat untuk 'belajar'?", ["Pintar", "Sekolah", ["Buku"], ["Guru"]], 0, "'Belajar' dan 'pintar' berima 'ar'."],
  ]),
  praktik: {
    petunjuk: "Buatlah 2 pantun: satu pantun nasihat bertema 'KEBERSIHAN' dan satu pantun jenaka bertema 'HEWAN LUCU'!",
    tips: [
      "Tentukan pesan dulu untuk pantun nasihat",
      "Pikirkan hal lucu tentang hewan untuk pantun jenaka",
      "Cari kata berima yang cocok",
      "Baca keras-keras, pastikan bunyinya pas",
    ],
    contoh: "NASIHAT KEBERSIHAN: 'Pergi ke hutan membawa golok / Golok tajam untuk merambah / Jagalah kebersihan setiap saat / Agar hidup sehat dan berkah.' JENAKA HEWAN LUCU: 'Anak kucing naik pohon / Pohonnya tinggi menjulang / Melihat anak kucing lucu / Tertawa-tawa terpingkal-pingkal.'",
  },
  kuis: makeSoal([
    ["Pantun yang berisi sindiran halus termasuk jenis...", ["Nasihat", "Kias", ["Jenaka"], ["Teka-teki"]], 1, "Pantun kias berisi sindiran halus melalui perbandingan."],
    ["'Rajin pangkal pandai' — ini nilai moral...", ["Sosial", "Pendidikan", ["Religius"], ["Ekonomi"]], 1, "'Rajin pangkal pandai' adalah nilai pendidikan."],
    ["Baris 'Jangan lupa bawa bekal' — rima 'al'. Cari kata berima 'al'...", ["Pintar", "Kebal", ["Indah"], ["Murah"]], 1, "'Kebal' berima 'al' dengan 'bekal'."],
    ["Nilai religius dalam pantun berhubungan dengan...", ["Sekolah", "Tuhan/agama", ["Teman"], ["Keluarga"]], 1, "Religius berkaitan dengan Tuhan dan ajaran agama."],
    ["Pantun 'Buanglah sampah pada tempatnya' — jenis pantun...", ["Jenaka", "Nasihat", ["Kias"], ["Teka-teki"]], 1, "'Buanglah sampah' adalah nasihat."],
    ["Sampiran dalam pantun berfungsi...", ["Pesan utama", "Pengantar berima", ["Kesimpulan"], ["Penutup"]], 1, "Sampiran adalah pengantar yang berima dengan isi."],
    ["Pantun 'Kalau tuan pergi ke kota' termasuk jenis...", ["Nasihat", "Teka-teki", ["Jenaka"], ["Kias"]], 1, "'Kalau tuan...' adalah ciri pantun teka-teki."],
    ["Nilai 'berdoa sebelum makan' termasuk...", ["Sosial", "Religius", ["Pendidikan"], ["Budaya"]], 1, "Berdoa adalah nilai religius."],
    ["Menciptakan pantun memerlukan...", ["Kemampuan berima", ["Kecepatan lari"], ["Kekuatan"], ["Nyanyian"]], 0, "Menciptakan pantun memerlukan kemampuan mencari rima."],
    ["'Sebelum makan cuci tangan' — ini bisa menjadi isi pantun bertema...", ["Kebersihan", "Persahabatan", ["Cinta"], ["Alam"]], 0, "Cuci tangan berkaitan dengan kebersihan."],
  ]),
}

export default konten
