import type { Konten } from "../types"
import { makeSoal } from "../types"

const konten: Konten = {
  belajar: {
    tujuan: [
      "Mengamati objek secara sistematis",
      "Mencatat data pengamatan dengan tabel",
      "Menyusun laporan pengamatan dengan struktur yang benar",
    ],
    materi: [
      {
        judul: "Mengamati Secara Sistematis",
        isi: [
          "Laporan pengamatan yang baik dimulai dari pengamatan yang sistematis.",
          "",
          "✓ Sistematis berarti dilakukan dengan cara yang teratur dan berurutan.",
          "",
          "Langkah pengamatan sistematis:",
          "1. Tentukan objek yang akan diamati.",
          "2. Tentukan aspek yang diamati (warna, bentuk, ukuran, jumlah, dll).",
          "3. Siapkan alat bantu (kaca pembesar, penggaris, termometer).",
          "4. Amati satu per satu aspeknya.",
          "5. Catat hasilnya dengan tabel atau catatan.",
          "",
          "PENTING: Catat apa yang kamu lihat, bukan apa yang kamu rasa atau pikirkan!",
          "",
          "[Ilustrasi: Seorang anak dengan kaca pembesar dan buku catatan, mengamati serangga di taman. Di buku catatannya tertulis tabel pengamatan. Gaya ilustrasi naturalis cilik.]",
        ],
        contoh: [
          "Contoh aspek pengamatan 'Batu':",
          "",
          "| Aspek | Hasil Pengamatan |",
          "| Warna | Abu-abu kehitaman |",
          "| Bentuk | Tidak beraturan, pinggir tajam |",
          "| Ukuran | Panjang 5 cm, lebar 3 cm |",
          "| Permukaan | Kasar dan berpori |",
          "| Berat | Sekitar 50 gram |",
          "| Bau | Tidak berbau |",
          "",
          "Tips: Semakin detail data yang dicatat, semakin baik laporanmu!",
        ],
        catatan: "Pengamatan bisa dilakukan dengan alat sederhana. Tidak perlu laboratorium canggih. Yang terpenting adalah ketelitian dan kejujuran dalam mencatat.",
      },
      {
        judul: "Mencatat Data dalam Tabel",
        isi: [
          "Tabel membantu menyajikan data dengan rapi dan mudah dibaca.",
          "",
          "Cara membuat tabel pengamatan:",
          "",
          "1. Buat kolom 'Aspek' dan 'Hasil Pengamatan'.",
          "2. Tulis aspek-aspek yang diamati di kolom kiri.",
          "3. Tulis data di kolom kanan.",
          "4. Tambahkan kolom 'Keterangan' jika perlu.",
          "",
          "Contoh tabel pengamatan 'Tanaman Kacang Hijau' (hari ke-7):",
          "",
          "| Aspek | Hasil | Keterangan |",
          "| Tinggi | 8,5 cm | Diukur dari tanah |",
          "| Jumlah daun | 4 helai | Daun terbuka semua |",
          "| Warna batang | Hijau muda | Sehat |",
          "| Warna daun | Hijau segar | Tidak menguning |",
          "| Kondisi | Tumbuh baik | Disiram setiap hari |",
          "",
          "[Ilustrasi: Buku catatan terbuka dengan tabel pengamatan rapi bergaris. Ada gambar tanaman kacang hijau kecil di samping tabel. Gaya ilustrasi jurnal sains anak.]",
        ],
        contoh: [
          "Data kualitatif vs kuantitatif:",
          "",
          "✓ KUANTITATIF (dapat diukur dengan angka):",
          "  • Tinggi tanaman: 8,5 cm",
          "  • Suhu air: 30°C",
          "  • Jumlah daun: 4 helai",
          "",
          "✓ KUALITATIF (deskripsi, bukan angka):",
          "  • Warna: hijau segar",
          "  • Permukaan: halus",
          "  • Bau: harum khas",
          "",
          "Tips: Usahakan punya data kuantitatif (angka) agar laporan lebih akurat!",
        ],
      },
      {
        judul: "Menyusun Laporan Pengamatan",
        isi: [
          "Setelah data terkumpul, susun laporan dengan struktur berikut:",
          "",
          "1. JUDUL — nama kegiatan pengamatan.",
          "2. TUJUAN — tujuan melakukan pengamatan.",
          "3. ALAT DAN BAHAN — alat yang digunakan.",
          "4. CARA KERJA — langkah-langkah pengamatan.",
          "5. HASIL — data pengamatan (tabel).",
          "6. KESIMPULAN — ringkasan hasil pengamatan.",
          "",
          "Contoh laporan:",
          "",
          "Laporan Pengamatan Tanaman Kacang Hijau",
          "",
          "Tujuan: Mengamati pertumbuhan tanaman kacang hijau selama 7 hari.",
          "Alat: Pot, tanah, biji kacang hijau, air, penggaris, buku catatan.",
          "",
          "Hasil Pengamatan: (lihat tabel)",
          "",
          "Kesimpulan: Tanaman kacang hijau tumbuh 8,5 cm dalam 7 hari, memiliki 4 daun, dan kondisi sehat berkat penyiraman rutin dan sinar matahari yang cukup.",
          "",
          "[Ilustrasi: Laporan lengkap di atas meja, dengan bagian-bagian ditandai stiker berwarna. Ada grafik pertumbuhan tanaman kecil di sampingnya.]",
        ],
        contoh: [
          "Bandingkan kesimpulan yang baik dan kurang baik:",
          "",
          "✗ KURANG BAIK: 'Tanaman kacang hijau tumbuh.'",
          "  — Terlalu umum, tanpa data.",
          "",
          "✓ BAIK: 'Tanaman kacang hijau tumbuh dengan baik. Dalam 7 hari, tinggi mencapai 8,5 cm dengan 4 helai daun. Pertumbuhan optimal karena penyiraman rutin dan sinar matahari yang cukup.'",
          "  — Spesifik, ada data, ada analisis.",
        ],
      },
    ],
    rangkuman: [
      "[Ilustrasi: Folder laporan bertuliskan 'LAPORAN PENGAMATAN' dengan tab: JUDUL, TUJUAN, ALAT, HASIL, KESIMPULAN. Ada gambar mikroskop dan tanaman di samping folder.]",
      "Pengamatan sistematis: tentukan objek, aspek, alat, amati, catat.",
      "Data kuantitatif (angka) dan kualitatif (deskripsi).",
      "Tabel: sajikan aspek di kiri, hasil di kanan.",
      "Struktur laporan: judul, tujuan, alat/cara, hasil, kesimpulan.",
    ],
  },
  latihan: makeSoal([
    ["Data yang berupa angka disebut...", ["Kualitatif", "Kuantitatif", "Deskripsi", "Informasi"], 1, "Data kuantitatif berupa angka (panjang 5 cm, suhu 30°C)."],
    ["'Warna daun hijau' termasuk data...", ["Kuantitatif", "Kualitatif", "Angka", "Ukuran"], 1, "'Warna hijau' adalah deskripsi, termasuk kualitatif."],
    ["Tabel dalam laporan berguna untuk...", ["Menghias", "Menyajikan data rapi", "Menggambar", "Berhitung"], 1, "Tabel membuat data lebih rapi dan mudah dibaca."],
    ["Bagian yang merangkum hasil pengamatan adalah...", ["Tujuan", "Kesimpulan", "Alat", "Cara kerja"], 1, "Kesimpulan merangkum hasil pengamatan."],
    ["Alat yang cocok untuk mengukur tinggi tanaman adalah...", ["Timbangan", "Penggaris", "Termometer", "Jam"], 1, "Penggaris mengukur panjang/tinggi."],
    ["Contoh data kualitatif adalah...", ["Suhu 30°C", "Permukaan halus", "Tinggi 8 cm", "Jumlah daun 4"], 1, "'Permukaan halus' adalah deskripsi kualitatif."],
    ["Laporan pengamatan bersifat...", ["Fiktif", "Faktual/ilmiah", "Artistik", "Subjektif"], 1, "Laporan pengamatan bersifat faktual dan ilmiah."],
    ["Bagian yang menjelaskan langkah pengamatan adalah...", ["Tujuan", "Cara kerja", "Hasil", "Kesimpulan"], 1, "Cara kerja berisi langkah-langkah pengamatan."],
    ["Kesimpulan yang baik mengandung...", ["Data dan analisis", "Opini tanpa data", "Cerita", "Puisi"], 0, "Kesimpulan berisi data dan analisis singkat."],
    ["Tujuan laporan pengamatan adalah...", ["Menghibur", "Melaporkan hasil secara ilmiah", "Berpuisi", "Berdongeng"], 1, "Tujuan laporan adalah melaporkan hasil pengamatan secara ilmiah."],
  ]),
  praktik: {
    petunjuk: "Lakukan pengamatan sederhana terhadap tanaman di halaman sekolah atau rumahmu selama 3 hari. Catat data dalam tabel, lalu buat laporan lengkap dengan struktur yang benar!",
    tips: [
      "Pilih satu tanaman dan beri nama",
      "Ukur tinggi setiap hari dengan penggaris",
      "Catat jumlah daun, warna, dan kondisi",
      "Bandingkan data hari ke-1, 2, dan 3",
      "Buat kesimpulan tentang pertumbuhannya",
    ],
    contoh: "Laporan Pengamatan Tanaman Bunga Matahari. Tujuan: Mengamati pertumbuhan bunga matahari. Hasil: Hari 1: tinggi 5 cm, 2 daun. Hari 2: tinggi 6,5 cm, 2 daun. Hari 3: tinggi 8 cm, 4 daun (2 baru mekar). Warna batang hijau segar. Kesimpulan: Bunga matahari tumbuh rata-rata 1,5 cm per hari dengan daun baru muncul di hari ke-3.",
  },
  kuis: makeSoal([
    ["Pengamatan sistematis artinya...", ["Acak", "Teratur dan terencana", "Cepat", "Asal-asalan"], 1, "Sistematis berarti dilakukan secara teratur dan terencana."],
    ["Data 'suhu air 30°C' termasuk data...", ["Kualitatif", "Kuantitatif", "Deskripsi", "Informasi"], 1, "Suhu 30°C adalah angka (kuantitatif)."],
    ["Alat untuk mengukur suhu adalah...", ["Penggaris", "Termometer", "Timbangan", "Jam"], 1, "Termometer mengukur suhu."],
    ["Kolom dalam tabel pengamatan biasanya...", ["Aspek dan Hasil", "Judul dan penutup", "Hanya angka", "Gambar"], 0, "Tabel biasanya berisi kolom Aspek dan Hasil."],
    ["Kesimpulan laporan diletakkan di...", ["Awal", "Akhir", "Tengah", "Judul"], 1, "Kesimpulan di bagian akhir laporan."],
    ["Yang diamati dalam pengamatan tanaman adalah...", ["Harga", "Tinggi, daun, warna", "Tempat beli", "Pemilik"], 1, "Aspek fisis seperti tinggi, daun, dan warna."],
    ["Laporan pengamatan ditulis dengan bahasa...", ["Artistik", "Ilmiah dan baku", "Santai", "Berima"], 1, "Laporan pengamatan menggunakan bahasa ilmiah dan baku."],
    ["Jika data berbeda dengan perkiraan, sebaiknya...", ["Mengubah data", "Melaporkan sesuai data asli", "Membuang data", "Mengulang"], 1, "Laporan harus jujur sesuai data yang diamati."],
    ["Tabel memudahkan...", ["Membaca data", "Menulis puisi", "Menggambar", "Bernyanyi"], 0, "Tabel memudahkan pembacaan dan perbandingan data."],
    ["'Berdasarkan pengamatan, dapat disimpulkan...' — ini kalimat...", ["Pembuka", "Kesimpulan", "Tujuan", "Alat"], 1, "Kalimat itu adalah ciri bagian kesimpulan."],
  ]),
}

export default konten
