import type { Konten } from "../types"
import { makeSoal } from "../types"

const konten: Konten = {
  belajar: {
    tujuan: [
      "Menganalisis tema dan amanat dalam puisi",
      "Memahami unsur rasa dan nada dalam puisi",
      "Menulis puisi dengan tema bebas dan memperhatikan diksi",
    ],
    materi: [
      {
        judul: "Tema dan Amanat dalam Puisi",
        isi: [
          "Setiap puisi punya tema dan amanat seperti dongeng dan cerita.",
          "",
          "✓ TEMA adalah pokok pikiran atau topik utama puisi.",
          "  Contoh tema: alam, persahabatan, cinta ibu, perjuangan.",
          "",
          "✓ AMANAT adalah pesan yang ingin disampaikan penyair melalui puisinya.",
          "  Contoh amanat: 'Hargailah alam', 'Sayangi orang tuamu'.",
          "",
          "Cara menentukan tema:",
          "• Baca puisi secara keseluruhan.",
          "• Tanyakan: 'Tentang apa puisi ini?'",
          "• Lihat kata-kata yang diulang atau paling menonjol.",
          "",
          "[Ilustrasi: Sebuah puisi dengan kata-kata kunci dilingkari warna berbeda: tema (merah), amanat (biru), kata kunci (kuning). Di sampingnya ada dua kotak: TEMA dan AMANAT. Gaya analisis sastra anak.]",
        ],
        contoh: [
          "Analisis puisi 'Pelangi':",
          "",
          "'Pelangi di ufuk barat'",
          "'Warnamu indah berseri'",
          "'Meski sebentar kau tampak'",
          "'Namun pesonamu tak terganti'",
          "",
          "✓ TEMA: Keindahan alam (pelangi).",
          "✓ AMANAT: Hargailah keindahan alam meskipun hanya sesaat.",
          "",
          "Tips: Tema adalah JAWABAN dari pertanyaan 'Tentang apa?', amanat adalah 'Pesan apa?'.",
        ],
        catatan: "Satu puisi bisa memiliki lebih dari satu tema. Misalnya puisi tentang ibu bisa bertema kasih sayang sekaligus pengorbanan.",
      },
      {
        judul: "Rasa dan Nada dalam Puisi",
        isi: [
          "Selain tema dan amanat, puisi juga punya rasa dan nada.",
          "",
          "✓ RASA (feeling): perasaan penyair yang tercermin dalam puisi.",
          "  • Senang: 'Hatiku berbunga-bunga'",
          "  • Sedih: 'Hujan turun, aku sendiri'",
          "  • Kagum: 'Indah sekali ciptaan Tuhan'",
          "  • Marah: 'Tak adil benar kenyataan ini'",
          "",
          "✓ NADA (tone): sikap penyair terhadap pembaca.",
          "  • Nada nasihat: 'Belajarlah, hai anakku'",
          "  • Nada doa: 'Ya Tuhan, lindungilah'",
          "  • Nada sindiran: 'Kau pikir kau yang paling hebat?'",
          "",
          "[Ilustrasi: Empat wajah dengan ekspresi berbeda (senang, sedih, kagum, marah) dihubungkan ke kata-kata puisi yang sesuai. Gaya diagram perasaan puisi.]",
        ],
        contoh: [
          "Bandingkan rasa dalam puisi:",
          "",
          "RASA SENANG: 'Mentari pagi tersenyum / Hatiku senang bukan main'",
          "  — Kata 'senang', 'tersenyum' menunjukkan rasa gembira.",
          "",
          "RASA KAGUM: 'Indahnya alam ciptaan Tuhan / Sungguh sempurna tanpa cela'",
          "  — Kata 'indah', 'sempurna' menunjukkan rasa kagum.",
          "",
          "Tips: Perhatikan kata-kata yang menunjukkan perasaan untuk menentukan rasa puisi!",
        ],
      },
      {
        judul: "Menulis Puisi dengan Diksi yang Tepat",
        isi: [
          "Menulis puisi yang baik membutuhkan pemilihan kata (diksi) yang tepat!",
          "",
          "Langkah menulis puisi:",
          "",
          "1. Tentukan tema puisimu.",
          "2. Tulis perasaanmu tentang tema itu.",
          "3. Pilih kata-kata yang indah (diksi puitis).",
          "4. Atur dalam baris-baris pendek, tidak perlu kalimat lengkap.",
          "5. Usahakan ada rima meskipun tidak sempurna.",
          "",
          "Tips diksi puitis:",
          "• Daripada 'matahari' → 'mentari' atau 'surya'.",
          "• Daripada 'indah' → 'elok', 'permai'.",
          "• Daripada 'harum' → 'semerbak', 'wangi'.",
          "• Daripada 'jatuh' → 'gugur', 'tumpah'.",
          "",
          "[Ilustrasi: Selembar kertas puisi dengan beberapa kata dicoret dan diganti dengan diksi yang lebih puitis. Contoh: 'matahari' dicoret, diganti 'mentari'. 'harum' dicoret, diganti 'semerbak'. Gaya proses editing puisi.]",
        ],
        contoh: [
          "Bandingkan puisi awal dan setelah revisi diksi:",
          "",
          "VERSI AWAL: 'Bunga itu indah / Aku suka sekali / Warna merah muda / Harum setiap hari'",
          "",
          "VERSI REVISI: 'Bunga mawar elok berseri / Kusuka benar pesonamu / Merah muda merebak di hati / Semerbak wangi selalu'",
          "",
          "Perbedaan:",
          "✓ 'indah' → 'elok berseri' (lebih indah)",
          "✓ 'suka sekali' → 'kusuka benar' (lebih puitis)",
          "✓ 'harum' → 'semerbak wangi' (lebih spesifik)",
        ],
      },
    ],
    rangkuman: [
      "[Ilustrasi: Buku sastra terbuka dengan tab: TEMA (topik), AMANAT (pesan), RASA (perasaan), NADA (sikap), DIKSI (pilihan kata). Setiap tab ada contohnya. Gaya buku panduan sastra anak.]",
      "Tema: pokok pikiran puisi. Amanat: pesan yang ingin disampaikan.",
      "Rasa: perasaan penyair (senang, sedih, kagum). Nada: sikap penyair (nasihat, sindiran, doa).",
      "Diksi puitis: pilih kata yang lebih indah (mentari, elok, semerbak, gugur).",
      "Menulis puisi: tentukan tema, ungkapkan perasaan, pilih diksi indah, atur dalam bait.",
    ],
  },
  latihan: makeSoal([
    ["Pokok pikiran dalam puisi disebut...", ["Amanat", "Tema", ["Rasa"], ["Nada"]], 1, "Tema adalah pokok pikiran atau topik utama puisi."],
    ["Pesan yang ingin disampaikan penyair disebut...", ["Tema", "Amanat", ["Rima"], ["Diksi"]], 1, "Amanat adalah pesan moral dalam puisi."],
    ["'Hatiku sedih, pilu, dan luka' — ini menunjukkan rasa...", ["Senang", "Sedih", ["Kagum"], ["Marah"]], 1, "Kata 'sedih', 'pilu', 'luka' menunjukkan rasa sedih."],
    ["Nada nasihat dalam puisi ditunjukkan dengan kata...", ["Ayo", "Belajarlah", ["Indah"], ["Tuhan"]], 1, "'Belajarlah' adalah kata nasihat."],
    ["Kata 'mentari' lebih puitis dari...", ["Bulan", "Matahari", ["Bintang"], ["Awan"]], 1, "'Mentari' adalah diksi puitis untuk 'matahari'."],
    ["Puisi 'Aku Ingin' karya Sapardi Djoko Damono bertema...", ["Alam", "Cinta/ kasih sayang", ["Perjuangan"], ["Sekolah"]], 1, "Puisi 'Aku Ingin' bertema cinta yang sederhana."],
    ["'Sungguh indah ciptaan-Mu' — nada puisi ini adalah...", ["Doa/pujian", ["Nasihat"], "Sindiran", "Marah"], 0, "'Sungguh indah ciptaan-Mu' bernada doa dan pujian."],
    ["Diksi yang tepat untuk 'daun berguguran' adalah...", ["Daun jatuh", "Daun gugur", ["Daun turun"], ["Daun melayang"]], 1, "'Gugur' lebih puitis daripada 'jatuh'."],
    ["Tema puisi 'Hijaunya Alamku' adalah...", ["Persahabatan", "Alam/lingkungan", ["Keluarga"], ["Sekolah"]], 1, "'Hijau' dan 'alam' menunjukkan tema alam/lingkungan."],
    ["Perasaan penyair dalam puisi disebut...", ["Tema", "Rasa", ["Amanat"], ["Nada"]], 1, "Rasa adalah perasaan yang tercermin dalam puisi."],
  ]),
  praktik: {
    petunjuk: "Buatlah sebuah puisi 8 baris (2 bait) dengan tema 'CITA-CITAKU'. Perhatikan: tema yang jelas, diksi yang puitis, dan usahakan ada rima!",
    tips: [
      "Tentukan cita-citamu (dokter, guru, pilot, pelukis, dll)",
      "Tulis perasaanmu tentang cita-cita itu",
      "Gunakan diksi puitis: cita, asa, impian, menggapai, meraih",
      "Buat 2 bait, masing-masing 4 baris",
    ],
    contoh: "'Cita-Citaku' / Aku ingin menjadi guru / Membagi ilmu pada sesama / Mengajar dengan sabar dan cinta / Mencerdaskan anak bangsa / Aku akan belajar sungguh-sungguh / Meraih asa yang kupendam / Doa ibu dan ayah selalu / Mengiringi langkahku setiap saat.",
  },
  kuis: makeSoal([
    ["Amanat puisi 'Jadilah pribadi yang berguna' adalah...", ["Jadilah pintar", "Jadilah berguna bagi sesama", ["Jadilah kaya"], ["Jadilah terkenal"]], 1, "Amanat: jadilah pribadi yang berguna bagi orang lain."],
    ["Nada dalam puisi 'Kuingat selalu nasihat ibu' adalah...", ["Marah", "Haru/kenangan", ["Sindiran"], ["Lucu"]], 1, "'Kuingat selalu nasihat ibu' bernada haru dan penuh kenangan."],
    ["Rasa kagum ditunjukkan kata...", ["Sedih", "Indah sekali", ["Marah"], ["Bosan"]], 1, "'Indah sekali' menunjukkan rasa kagum."],
    ["Kata 'surya' berarti...", ["Bulan", "Matahari", ["Bintang"], ["Pelangi"]], 1, "'Surya' berarti matahari."],
    ["'Elok' artinya...", ["Sedih", "Indah", ["Cepat"], ["Berat"]], 1, "'Elok' berarti indah atau cantik."],
    ["Tema dan amanat berbeda. Amanat adalah...", ["Topik", "Pesan", ["Judul"], ["Baris"]], 1, "Amanat adalah pesan, tema adalah topik."],
    ["Puisi bertema 'Ibu' biasanya mengandung rasa...", ["Senang", "Kasih sayang", ["Marah"], ["Takut"]], 1, "Puisi tentang ibu penuh rasa kasih sayang."],
    ["Kata 'gugur' lebih puitis dari...", ["Tumbuh", "Jatuh", ["Mekar"], ["Layu"]], 1, "'Gugur' lebih puitis daripada 'jatuh'."],
    ["Puisi 'Doa' karya Chairil Anwar bernada...", ["Marah", "Religius/doa", ["Lucu"], ["Sindiran"]], 1, "'Doa' bernada religius, penuh pengharapan kepada Tuhan."],
    ["Satu bait dalam puisi biasnya terdiri dari... baris", ["2", "4", ["6"], ["8"]], 1, "Satu bait biasanya 4 baris."],
  ]),
}

export default konten
