import type { Konten } from "../types"
import { makeSoal } from "../types"

const konten: Konten = {
  belajar: {
    tujuan: [
      "Memahami pengertian dan ciri teks narasi",
      "Mengenal alur dalam cerita narasi",
      "Menulis teks narasi berdasarkan pengalaman pribadi",
    ],
    materi: [
      {
        judul: "Apa Itu Teks Narasi?",
        isi: [
          "Setiap kali kamu bercerita tentang liburan atau pengalaman seru, kamu sedang membuat narasi!",
          "",
          "✓ Teks narasi adalah teks yang menceritakan peristiwa atau kejadian secara berurutan berdasarkan waktu.",
          "",
          "Ciri teks narasi:",
          "1. Menceritakan peristiwa (ada kejadian).",
          "2. Berdasarkan urutan waktu (kronologis).",
          "3. Ada tokoh yang mengalami peristiwa.",
          "4. Ada konflik atau masalah.",
          "5. Tujuan: menghibur dan memberikan pengalaman estetis.",
          "",
          "[Ilustrasi: Roda waktu dengan 4 panel berurutan. Panel 1: Bangun pagi. Panel 2: Sarapan. Panel 3: Berangkat sekolah. Panel 4: Belajar di kelas. Panah menghubungkan setiap panel. Gaya komik strip sederhana.]",
        ],
        contoh: [
          "Perbedaan narasi dengan teks lain:",
          "",
          "✓ NARASI: 'Kemarin, Budi pergi ke taman bersama ayah. Mereka bermain ayunan dan perosotan. Tiba-tiba, hujan turun deras. Budi dan ayah berlari berteduh.'",
          "  — Ada urutan waktu, ada tokoh, ada kejadian.",
          "",
          "✗ DESKRIPSI: 'Taman itu indah. Bunga warna-warni mekar. Rumputnya hijau.'",
          "  — Hanya menggambarkan, tidak ada cerita.",
        ],
        catatan: "Narasi berbeda dengan laporan. Narasi bersifat subjektif dan artistik, laporan bersifat objektif dan faktual. Narasi 'menceritakan', laporan 'melaporkan'.",
      },
      {
        judul: "Alur dalam Narasi",
        isi: [
          "Alur adalah urutan peristiwa dalam cerita narasi. Ada beberapa tahapan:",
          "",
          "1. ORIENTASI — pengenalan tokoh, tempat, dan waktu.",
          "  'Pada hari Minggu pagi, Dinda bersiap pergi ke perpustakaan.'",
          "",
          "2. KOMLIKASI — mulai muncul masalah atau konflik.",
          "  'Di perpustakaan, Dinda tidak menemukan buku yang dicari. Petugas bilang buku itu sedang dipinjam.'",
          "",
          "3. RESOLUSI — masalah selesai atau terpecahkan.",
          "  'Dinda lalu meminjam buku lain yang tak kalah menarik. Ia pun senang.'",
          "",
          "4. KODA (opsional) — pesan moral atau kesimpulan.",
          "  'Dinda belajar bahwa kadang kita harus menerima alternatif lain.'",
          "",
          "[Ilustrasi: Gunung alur cerita — garis naik dari orientasi (lembah) naik ke komplikasi (puncak), lalu turun ke resolusi (lembah). Setiap titik ada ikon: orang (orientasi), tanda seru (komplikasi), bintang (resolusi).]",
        ],
        contoh: [
          "Analisis alur cerita 'Kancil dan Buaya':",
          "",
          "ORIENTASI: Kancil ingin menyeberang sungai. Banyak buaya di sungai.",
          "KOMLIKASI: Kancil harus menghadapi buaya-buaya yang siap memangsa.",
          "RESOLUSI: Kancil menipu buaya, menyuruh mereka berbaris, lalu melompati punggung mereka.",
          "KODA: Kecerdikan bisa menyelamatkan diri dari bahaya.",
          "",
          "Tips: Saat membaca cerita, coba cari bagian orientasi, komplikasi, dan resolusinya!",
        ],
      },
      {
        judul: "Menulis Teks Narasi",
        isi: [
          "Sekarang, ayo menulis narasi berdasarkan pengalamanmu!",
          "",
          "Langkah-langkah:",
          "",
          "1. Tentukan peristiwa yang akan diceritakan.",
          "2. Susun urutan kejadian (awal, tengah, akhir).",
          "3. Tentukan tokoh (bisa diri sendiri).",
          "4. Tulis dengan bahasa yang menarik.",
          "5. Gunakan kata penghubung waktu: kemudian, setelah itu, akhirnya, tiba-tiba, lalu.",
          "",
          "Tips:",
          "• Gunakan kata 'aku' atau 'saya' jika menceritakan pengalaman sendiri.",
          "• Gunakan kata 'dia' atau nama tokoh jika menceritakan orang lain.",
          "• Buat pembaca ikut merasakan kejadian yang kamu ceritakan.",
          "",
          "[Ilustrasi: Seorang anak tersenyum sambil menulis di buku harian. Di sekelilingnya ada foto-foto kenangan: liburan pantai, kebun binatang, dan pesta ulang tahun. Gaya ilustrasi scrapbook.]",
        ],
        contoh: [
          "Contoh narasi 'Liburan ke Pantai':",
          "",
          "Liburan sekolah kemarin, aku pergi ke Pantai Pangandaran bersama keluarga. Aku sangat senang karena sudah lama tidak ke pantai.",
          "",
          "Setelah sampai, aku langsung berlari ke tepi pantai. Ombaknya kecil dan airnya jernih. Aku bermain air sambil mencari kerang.",
          "",
          "Tiba-tiba, aku melihat seekor kepiting kecil berjalan di pasir. Aku mencoba menangkapnya, tetapi ia cepat sekali. Aku tertawa dan terus mengejarnya.",
          "",
          "Akhirnya, ibu memanggilku untuk makan siang. Aku meninggalkan kepiting itu dan bergabung dengan keluarga. Hari itu sangat menyenangkan.",
        ],
      },
    ],
    rangkuman: [
      "[Ilustrasi: Buku harian terbuka dengan tulisan 'Hari Ini...' dan gambar-gambar peristiwa dalam gelembung: bangun tidur, sarapan, sekolah, bermain, tidur. Ada panah kronologis dari awal hingga akhir.]",
      "Teks narasi: teks yang menceritakan peristiwa secara kronologis (berdasarkan urutan waktu).",
      "Alur narasi: orientasi (pengenalan) → komplikasi (masalah) → resolusi (penyelesaian) → koda (pesan).",
      "Ciri: ada tokoh, ada konflik, ada urutan waktu, bertujuan menghibur.",
      "Gunakan kata penghubung waktu: kemudian, lalu, setelah itu, tiba-tiba, akhirnya.",
    ],
  },
  latihan: makeSoal([
    ["Teks narasi adalah teks yang...", ["Menggambarkan benda", "Menceritakan peristiwa secara kronologis", "Memberi petunjuk", "Melaporkan data"], 1, "Narasi menceritakan peristiwa berdasarkan urutan waktu."],
    ["Bagian pengenalan tokoh dan latar disebut...", ["Komplikasi", "Orientasi", "Resolusi", "Koda"], 1, "Orientasi memperkenalkan tokoh, tempat, dan waktu."],
    ["Konflik dalam narasi terletak di bagian...", ["Orientasi", "Komplikasi", "Resolusi", "Koda"], 1, "Komplikasi adalah bagian munculnya masalah."],
    ["'Kemudian', 'setelah itu', 'akhirnya' — termasuk kata...", ["Sifat", "Penghubung waktu", "Tanya", "Bilangan"], 1, "Kata-kata itu adalah konjungsi kronologis (penghubung waktu)."],
    ["Tujuan teks narasi adalah...", ["Melapor", "Menghibur/menceritakan", "Memandu", "Mendeskripsikan"], 1, "Narasi bertujuan menghibur dengan cerita."],
    ["Yang BUKAN ciri teks narasi adalah...", ["Ada tokoh", "Berdasarkan data angka", "Ada konflik", "Urutan waktu"], 1, "Data angka bukan ciri narasi. Data angka lebih cocok untuk laporan."],
    ["'Tiba-tiba, hujan turun deras!' — kalimat ini menunjukkan...", ["Orientasi", "Kejadian mendadak (komplikasi)", "Resolusi", "Penutup"], 1, "'Tiba-tiba' menandakan kejadian tak terduga, bagian komplikasi."],
    ["Contoh narasi berdasarkan pengalaman adalah...", ["Cara membuat jus", "Liburanku ke rumah nenek", "Pengumuman lomba", "Iklan susu"], 1, "'Liburanku ke rumah nenek' adalah narasi pengalaman."],
    ["Bagian akhir narasi yang berisi pesan moral disebut...", ["Orientasi", "Koda", "Komplikasi", "Konflik"], 1, "Koda adalah bagian pesan moral atau amanat."],
    ["Kata 'aku' dalam narasi menunjukkan sudut pandang...", ["Orang pertama", "Orang ketiga", "Orang kedua", "Semua"], 0, "'Aku' adalah sudut pandang orang pertama (pelaku cerita)."],
  ]),
  praktik: {
    petunjuk: "Tulislah teks narasi 3-4 paragraf tentang pengalamanmu yang paling berkesan! Gunakan struktur: orientasi, komplikasi, resolusi. Jangan lupa kata penghubung waktu.",
    tips: [
      "Pilih pengalaman yang paling kamu ingat",
      "Ceritakan secara urut dari awal hingga akhir",
      "Gunakan kata-kata yang membuat pembaca ikut merasakan",
      "Akhiri dengan kesan atau pesan dari pengalaman itu",
    ],
    contoh: "ORIENTASI: Liburan lalu, aku diajak ayah memancing di sungai. Aku sangat bersemangat karena baru pertama kali. KOMLIKASI: Setelah satu jam, aku belum mendapat ikan satu pun. Aku mulai bosan. Ayah tersenyum dan mengajarkanku cara yang benar. RESOLUSI: Aku mengikuti cara Ayah: sabar dan tenang. Akhirnya, kailku bergerak! Aku dapat ikan! KODA: Aku belajar bahwa kesabaran akan membuahkan hasil.",
  },
  kuis: makeSoal([
    ["Alur cerita adalah...", ["Tempat cerita", "Urutan peristiwa", "Tokoh", "Latar"], 1, "Alur adalah urutan peristiwa dalam cerita dari awal hingga akhir."],
    ["Bagian yang berisi penyelesaian masalah disebut...", ["Orientasi", "Resolusi", "Komplikasi", "Koda"], 1, "Resolusi adalah bagian penyelesaian masalah."],
    ["'Ketika aku sampai di sekolah...' — ini menunjukkan...", ["Waktu", "Tempat", "Tokoh", "Masalah"], 0, "'Ketika' menunjukkan keterangan waktu."],
    ["Teks narasi berbeda dengan laporan karena narasi...", ["Berdasarkan data", "Bersifat subjektif/menceritakan", "Faktual", "Objektif"], 1, "Narasi bersifat subjektif dan menceritakan, laporan objektif dan faktual."],
    ["Konflik adalah...", ["Pengenalan tokoh", "Masalah dalam cerita", "Akhir cerita", "Judul"], 1, "Konflik adalah masalah yang terjadi dalam cerita."],
    ["'Akhirnya, ia pun tersenyum lega.' — kalimat ini bagian...", ["Orientasi", "Resolusi", "Komplikasi", "Pengenalan"], 1, "'Akhirnya' dan 'lega' menunjukkan masalah selesai (resolusi)."],
    ["Koda dalam narasi berisi...", ["Tokoh baru", "Pesan moral", "Konflik baru", "Tempat"], 1, "Koda berisi pesan moral atau kesimpulan dari cerita."],
    ["Narasi 'Liburan ke Pantai' menggunakan sudut pandang...", ["Orang pertama (aku)", "Orang ketiga (dia)", "Orang kedua (kamu)", "Campuran"], 0, "Pengalaman pribadi diceritakan dengan 'aku'."],
    ["Kata 'lalu' termasuk jenis kata...", ["Benda", "Penghubung", "Sifat", "Tanya"], 1, "'Lalu' adalah kata penghubung urutan waktu."],
    ["Mana yang termasuk teks narasi?", ["Cara membuat teh", "Pengalaman pertama naik sepeda", "Iklan sabun", "Pengumuman lomba"], 1, "'Pengalaman naik sepeda' adalah narasi."],
  ]),
}

export default konten
