import type { Konten } from "../types"
import { makeSoal } from "../types"

const konten: Konten = {
  belajar: {
    tujuan: [
      "Memahami unsur-unsur pengumuman secara lengkap",
      "Menggunakan bahasa efektif dalam pengumuman",
      "Menulis pengumuman dengan struktur yang baik",
    ],
    materi: [
      {
        judul: "Unsur-Unsur Pengumuman Lengkap",
        isi: [
          "Di kelas 2 kita sudah belajar pengumuman. Di kelas 4, kita akan belajar lebih mendalam!",
          "",
          "Unsur-unsur pengumuman:",
          "",
          "1. JUDUL — 'PENGUMUMAN' atau topik spesifik.",
          "2. SASARAN — kepada siapa pengumuman ditujukan.",
          "  Contoh: 'Kepada seluruh siswa kelas 4...'",
          "3. ISI — informasi yang disampaikan (apa, kapan, di mana).",
          "4. PENANGGUNG JAWAB — pihak yang mengeluarkan pengumuman.",
          "5. TEMPAT DAN TANGGAL PEMBUATAN.",
          "6. KONTAK (opsional) — nomor atau alamat untuk informasi lebih.",
          "",
          "[Ilustrasi: Papan pengumuman digital dengan 6 ikon: JUDUL (bintang), SASARAN (orang), ISI (informasi), PJ (centang), TANGGAL (kalender), KONTAK (telepon). Gaya infografis pengumuman.]",
        ],
        contoh: [
          "Analisis pengumuman:",
          "",
          "'PENGUMUMAN' — Judul",
          "'Diberitahukan kepada seluruh siswa kelas 4' — Sasaran",
          "'Bahwa besok, Sabtu 22 Maret 2025, akan diadakan lomba kebersihan kelas. Setiap kelas diharap membersihkan ruang kelas masing-masing. Lomba dimulai pukul 08.00.' — Isi",
          "'Bandung, 21 Maret 2025' — Tempat dan tanggal",
          "'Panitia Lomba Kebersihan' — Penanggung jawab",
          "",
          "Tips: Pastikan semua unsur ada agar pengumuman jelas dan tidak membingungkan!",
        ],
      },
      {
        judul: "Bahasa Efektif dalam Pengumuman",
        isi: [
          "Pengumuman harus menggunakan bahasa yang efektif: singkat, jelas, dan mudah dipahami.",
          "",
          "Ciri bahasa efektif:",
          "",
          "1. SINGKAT — tidak bertele-tele, langsung ke pokok.",
          "  ✗ 'Dengan ini kami ingin memberitahukan kepada Bapak/Ibu sekalian bahwa...'",
          "  ✓ 'Diberitahukan bahwa...'",
          "",
          "2. JELAS — informasi spesifik (tanggal, jam, tempat).",
          "  ✗ 'Besok ada acara.'",
          "  ✓ 'Besok, Sabtu 22 Maret 2025, pukul 08.00 di aula.'",
          "",
          "3. BAKU — menggunakan bahasa Indonesia yang benar.",
          "  ✗ 'Buat yg ikut lomba, kumpul di sini.'",
          "  ✓ 'Peserta lomba harap berkumpul di aula.'",
          "",
          "[Ilustrasi: Dua panel. Panel kiri (merah) berisi pengumuman tidak efektif: panjang, tidak jelas, tidak baku. Panel kanan (hijau) berisi pengumuman efektif: singkat, jelas, baku. Ada tanda centang dan silang.]",
        ],
        contoh: [
          "Perbandingan pengumuman efektif vs tidak efektif:",
          "",
          "✗ TIDAK EFEKTIF:",
          "'Hai teman-teman, besok ada lomba lho, ramein ya, pokoknya seru, jangan lupa bawa alat masing-masing ya guys, makasih.'",
          "  — Bahasa santai, tidak jelas kapan dan di mana, tidak baku.",
          "",
          "✓ EFEKTIF:",
          "'PENGUMUMAN. Kepada seluruh siswa kelas 4, diberitahukan bahwa besok, Sabtu 22 Maret 2025, akan diadakan lomba mewarnai di aula sekolah pukul 09.00. Peserta harap membawa alat mewarnai sendiri. Bandung, 21 Maret 2025. Panitia.'",
          "  — Singkat, jelas, baku, lengkap.",
        ],
        catatan: "Pengumuman yang ditulis di papan atau media sosial berbeda dengan surat resmi. Pengumuman lebih singkat dan langsung ke sasaran.",
      },
      {
        judul: "Menulis Pengumuman yang Baik",
        isi: [
          "Langkah-langkah menulis pengumuman:",
          "",
          "1. Tentukan topik pengumuman (lomba, libur, rapat, kegiatan).",
          "2. Tentukan sasaran pembaca (siapa yang perlu tahu).",
          "3. Kumpulkan informasi: apa, kapan, di mana, siapa.",
          "4. Tulis dengan urutan: judul → sasaran → isi → penutup.",
          "5. Gunakan kalimat singkat dan jelas.",
          "6. Cantumkan penanggung jawab dan tanggal.",
          "",
          "Contoh pengumuman kegiatan:",
          "",
          "'PENGUMUMAN'",
          "Kepada seluruh anggota Pramuka kelas 4 dan 5,",
          "Diberitahukan bahwa latihan Pramuka minggu ini akan dilaksanakan pada:",
          "Hari: Sabtu, 29 Maret 2025",
          "Waktu: 14.00 - 16.00 WIB",
          "Tempat: Lapangan Sekolah",
          "Pakaian: Seragam Pramuka lengkap",
          "Harap hadir tepat waktu.",
          "Bandung, 27 Maret 2025",
          "Pembina Pramuka",
          "",
          "[Ilustrasi: Seorang anak menempel pengumuman di papan pengumuman sekolah. Di papan sudah ada beberapa pengumuman lain. Anak itu tersenyum bangga. Gaya aktivitas sekolah.]",
        ],
        contoh: [
          "Pengumuman yang baik vs kurang baik:",
          "",
          "✗ KURANG BAIK: 'Besok malam ada pentas seni. Datang ya.'",
          "  — Tidak jelas: jam berapa? di mana? siapa yang mengumumkan?",
          "",
          "✓ BAIK:",
          "'PENGUMUMAN'",
          "'Kepada seluruh siswa SD Harapan Bangsa,'",
          "'Diberitahukan bahwa pada hari Sabtu, 29 Maret 2025, pukul 19.00-21.00 WIB, akan diadakan Pentas Seni Akhir Tahun di halaman sekolah. Semua siswa diharap hadir dan membawa tikar duduk. Bandung, 25 Maret 2025. Panitia Pentas Seni.'",
          "  — Jelas: kapan, jam berapa, di mana, siapa yang mengumumkan.",
          "",
          "Tips: Sebelum menempel, baca ulang pengumumanmu. Pastikan semua informasi penting sudah ada!",
        ],
      },
    ],
    rangkuman: [
      "[Ilustrasi: Papan besar bertuliskan 'PENGUMUMAN' dengan checklist: ✓ JUDUL, ✓ SASARAN, ✓ ISI (APA, KAPAN, DI MANA), ✓ PENANGGUNG JAWAB, ✓ TANGGAL. Gaya papan ceklis.]",
      "Unsur pengumuman: judul, sasaran, isi (apa/kapan/di mana), penanggung jawab, tanggal.",
      "Bahasa efektif: singkat, jelas, baku, langsung ke sasaran.",
      "Cara menulis: tentukan topik dan sasaran, kumpulkan info, tulis urut dengan bahasa singkat.",
      "Baca ulang sebelum dipublikasikan untuk memastikan tidak ada info yang terlewat.",
    ],
  },
  latihan: makeSoal([
    ["Unsur pengumuman yang menunjukkan siapa yang berwenang adalah...", ["Judul", "Penanggung jawab", "Sasaran", "Tanggal"], 1, "Penanggung jawab menunjukkan pihak yang mengeluarkan pengumuman."],
    ["Bahasa efektif dalam pengumuman berarti...", ["Panjang", "Singkat dan jelas", "Berima", "Artistik"], 1, "Efektif berarti singkat, jelas, dan mudah dipahami."],
    ["'Diberitahukan bahwa...' adalah contoh pembuka yang...", ["Tidak baku", "Baku dan formal", "Santai", "Salah"], 1, "'Diberitahukan' adalah kata baku dan formal."],
    ["Sasaran pengumuman adalah...", ["Topik", "Kepada siapa pengumuman ditujukan", "Isi", "Tanggal"], 1, "Sasaran adalah pihak yang dituju oleh pengumuman."],
    ["Bagian isi pengumuman mencakup...", ["Apa, kapan, di mana", "Salam", "Kop surat", "Stempel"], 0, "Isi pengumuman berisi informasi apa, kapan, dan di mana."],
    ["Mana pengumuman yang menggunakan bahasa efektif?", ["Diberitahukan bahwa besok libur", "Hai teman, besok libur lho, yey", "Yo bro, besok libur", "Besok... ehm... libur"], 0, "'Diberitahukan bahwa besok libur' adalah bahasa efektif."],
    ["Penanggung jawab ditulis di bagian...", ["Awal", "Akhir", "Tengah", "Judul"], 1, "Penanggung jawab ditulis di bagian akhir pengumuman."],
    ["Kalimat 'Harap hadir tepat waktu' termasuk...", ["Ajakan sopan", "Perintah keras", "Pertanyaan", "Laporan"], 0, "'Harap' adalah ajakan yang sopan dan formal."],
    ["Pengumuman berbeda dengan iklan karena pengumuman...", ["Mengajak membeli", "Memberi informasi", "Menghibur", "Mendidik"], 1, "Pengumuman memberi informasi, iklan mengajak membeli."],
    ["Sebelum menempel pengumuman, sebaiknya...", ["Langsung tempel", "Baca ulang periksa info", "Fotokopi", "Tidak perlu"], 1, "Baca ulang untuk memastikan semua informasi benar dan lengkap."],
  ]),
  praktik: {
    petunjuk: "Buat pengumuman tentang lomba membaca puisi dalam rangka peringatan Hari Pendidikan Nasional! Cantumkan semua unsur: judul, sasaran, isi (hari, tanggal, waktu, tempat), penanggung jawab, dan tanggal pembuatan.",
    tips: [
      "Tentukan hari dan tanggal pelaksanaan (misal: 2 Mei 2025)",
      "Tentukan tempat lomba (aula, kelas, perpustakaan)",
      "Tentukan siapa yang boleh ikut (kelas berapa?)",
      "Tentukan penanggung jawab (panitia, guru, kepala sekolah)",
    ],
    contoh: "PENGUMUMAN. Kepada seluruh siswa SD Harapan Bangsa, dalam rangka memperingati Hari Pendidikan Nasional, OSIS akan mengadakan Lomba Baca Puisi. Hari/Tanggal: Jumat, 2 Mei 2025. Waktu: 09.00 - 12.00 WIB. Tempat: Aula Sekolah. Peserta: siswa kelas 4-5 (masing-masing kelas 2 perwakilan). Pendaftaran ditutup 28 April. Bandung, 20 April 2025. Panitia Peringatan Hardiknas.",
  },
  kuis: makeSoal([
    ["Unsur yang HARUS ada dalam setiap pengumuman adalah...", ["Gambar", "Isi informasi", "Hiasan", "Puisi"], 1, "Isi informasi adalah unsur wajib pengumuman."],
    ["'Kepada seluruh siswa kelas 4' — ini bagian...", ["Sasaran", "Isi", "Judul", "Penutup"], 0, "Kalimat itu menunjukkan sasaran pengumuman."],
    ["Pengumuman yang baik bersifat...", ["Berbelit", "Informatif dan singkat", "Artistik", "Berima"], 1, "Pengumuman yang baik informatif dan singkat."],
    ["Tempat dan tanggal pembuatan diletakkan di...", ["Awal", "Akhir", "Tengah", "Judul"], 1, "Tempat dan tanggal pembuatan di bagian akhir."],
    ["'Diberitahukan' adalah bentuk kata kerja...", ["Aktif", "Pasif", "Perintah", "Tanya"], 1, "'Diberitahukan' adalah bentuk pasif (di- + beritahukan)."],
    ["Sasaran pengumuman 'kepada seluruh siswa' berarti...", ["Guru", "Siswa", "Orang tua", "Kepala sekolah"], 1, "Sasarannya adalah seluruh siswa."],
    ["Pengumuman lisan bisa disampaikan melalui...", ["Poster", "Pengeras suara", "Baliho", "Brosur"], 1, "Pengumuman lisan lewat pengeras suara."],
    ["Informasi 'pukul 08.00' termasuk bagian...", ["Sasaran", "Isi (waktu)", "Penanggung jawab", "Judul"], 1, "Waktu pelaksanaan termasuk isi pengumuman."],
    ["Penanggung jawab 'OSIS' berarti yang mengumumkan adalah...", ["Kepala sekolah", "Organisasi siswa", "Guru", "Satpam"], 1, "OSIS adalah organisasi siswa yang berwenang mengeluarkan pengumuman."],
    ["Pengumuman yang baik harus menggunakan bahasa...", ["Daerah", "Baku dan jelas", "Asing", "Santai"], 1, "Pengumuman menggunakan bahasa baku dan jelas."],
  ]),
}

export default konten
