import type { Konten } from "../types"
import { makeSoal } from "../types"

const konten: Konten = {
  belajar: {
    tujuan: [
      "Memahami struktur teks prosedur (tujuan, bahan, langkah)",
      "Mengidentifikasi kalimat perintah dalam prosedur",
      "Menulis teks prosedur dengan langkah yang urut dan jelas",
    ],
    materi: [
      {
        judul: "Struktur Teks Prosedur",
        isi: [
          "Di kelas 3 kita belajar teks petunjuk. Sekarang di kelas 4, kita belajar versi yang lebih lengkap: teks prosedur!",
          "",
          "✓ Teks prosedur adalah teks yang berisi langkah-langkah untuk melakukan atau membuat sesuatu secara urut.",
          "",
          "Struktur teks prosedur:",
          "1. TUJUAN — hasil yang ingin dicapai (judul atau pengantar).",
          "  Contoh: 'Cara Membuat Jus Jeruk'",
          "",
          "2. ALAT DAN BAHAN — perlengkapan yang diperlukan.",
          "  Contoh: 'Jeruk 2 buah, gula, air, gelas, blender'",
          "",
          "3. LANGKAH-LANGKAH — urutan cara membuat.",
          "  Contoh: 'Pertama, kupas jeruk...'",
          "",
          "[Ilustrasi: Tiga kotak bersusun. Kotak 1 'TUJUAN' — gambar gelas jus. Kotak 2 'ALAT & BAHAN' — gambar jeruk, gula, blender. Kotak 3 'LANGKAH' — gambar urutan 1-2-3. Gaya infografis dapur.]",
        ],
        contoh: [
          "Bandingkan petunjuk sederhana vs prosedur lengkap:",
          "",
          "✗ SEDERHANA: 'Potong, rebus, sajikan.'",
          "  — Terlalu singkat, tidak jelas.",
          "",
          "✓ PROSEDUR:",
          "  Tujuan: Membuat telur rebus.",
          "  Alat: Panci, kompor, sendok.",
          "  Bahan: 2 butir telur, air.",
          "  Langkah: 1. Isi panci dengan air. 2. Masukkan telur. 3. Rebus 10 menit. 4. Angkat dan sajikan.",
          "  — Jelas, urut, lengkap.",
        ],
      },
      {
        judul: "Kalimat Perintah dalam Prosedur",
        isi: [
          "Teks prosedur menggunakan banyak kalimat perintah (imperatif).",
          "",
          "✓ Kalimat perintah diawali dengan kata kerja tanpa subjek.",
          "",
          "Contoh kalimat perintah:",
          "• Siapkan alat dan bahan.",
          "• Kupas jeruk hingga bersih.",
          "• Masukkan ke dalam blender.",
          "• Tekan tombol 'On'.",
          "• Tuang ke dalam gelas.",
          "",
          "PENTING: Jangan gunakan subjek 'kamu' atau 'anda' dalam setiap langkah. Langsung gunakan kata kerja!",
          "",
          "SALAH: 'Kamu siapkan alat dan bahan.'",
          "BENAR: 'Siapkan alat dan bahan.'",
          "",
          "[Ilustrasi: Rambu lalu lintas berbentuk lingkaran hijau bertuliskan kata kerja perintah: Siapkan, Kupas, Masukkan, Tekan, Tuang, Aduk. Setiap kata kerja punya ikon sederhana. Gaya rambu dapur.]",
        ],
        contoh: [
          "Bandingkan kalimat perintah dan bukan perintah:",
          "",
          "✓ PERINTAH: 'Aduk hingga rata.' — langsung, jelas.",
          "✗ BUKAN: 'Kita perlu mengaduknya hingga rata.' — tidak tegas.",
          "✓ PERINTAH: 'Tuangkan jus ke dalam gelas.' — langsung.",
          "✗ BUKAN: 'Jusnya bisa dituang ke dalam gelas.' — pasif, kurang tegas.",
          "",
          "Tips: Gunakan kata kerja aktif tanpa awalan 'me-' jika bisa. 'Potong' lebih tegas dari 'memotong'.",
        ],
        catatan: "Dalam teks prosedur, gunakan kata kerja dasar (tanpa awalan) untuk kalimat perintah: potong, aduk, tuang, masukkan, bukan memotong, mengaduk, menuang, memasukkan.",
      },
      {
        judul: "Menulis Teks Prosedur",
        isi: [
          "Sekarang, ayo menulis teks prosedur!",
          "",
          "Langkah-langkah menulis:",
          "",
          "1. Tentukan kegiatan (membuat sesuatu atau melakukan sesuatu).",
          "2. Coba lakukan sendiri kegiatan itu, catat setiap langkah.",
          "3. Tulis tujuan di bagian awal.",
          "4. Tulis daftar alat dan bahan.",
          "5. Tulis langkah-langkah dengan nomor urut.",
          "6. Gunakan kalimat perintah yang jelas.",
          "",
          "Tips menulis:",
          "• Pastikan langkah-langkah tidak ada yang terlewat.",
          "• Jika perlu, tambahkan gambar ilustrasi.",
          "• Gunakan kata 'Pertama', 'Kedua', 'Selanjutnya', 'Terakhir'.",
          "",
          "[Ilustrasi: Seorang anak berdiri di dapur sambil memegang buku resep. Di atas meja terlihat bahan-bahan: tepung, telur, susu. Si anak tersenyum percaya diri mau memasak. Gaya ilustrasi junior chef.]",
        ],
        contoh: [
          "Teks prosedur 'Cara Membuat Teh Manis':",
          "",
          "Tujuan: Membuat segelas teh manis hangat.",
          "",
          "Alat dan Bahan:",
          "- 1 kantong teh celup",
          "- 2 sendok gula pasir",
          "- 200 ml air panas",
          "- Gelas dan sendok",
          "",
          "Langkah-langkah:",
          "1. Siapkan gelas dan masukkan kantong teh celup.",
          "2. Tuangkan air panas ke dalam gelas hingga penuh.",
          "3. Tambahkan 2 sendok gula pasir.",
          "4. Aduk hingga gula larut dan air berubah warna.",
          "5. Diamkan 3 menit agar teh meresap.",
          "6. Angkat kantong teh celup.",
          "7. Teh manis hangat siap dinikmati.",
        ],
      },
    ],
    rangkuman: [
      "[Ilustrasi: Buku resep terbuka dengan tab penanda 'TUJUAN', 'ALAT & BAHAN', 'LANGKAH'. Ada gambar hasil akhir yang lezat. Gaya buku masak anak-anak.]",
      "Teks prosedur: teks yang menjelaskan langkah-langkah melakukan sesuatu secara urut.",
      "Struktur: tujuan → alat dan bahan → langkah-langkah.",
      "Gunakan kalimat perintah (imperatif) yang jelas dan tegas.",
      "Gunakan kata kerja dasar: siapkan, potong, aduk, tuang (bukan menyiapkan, memotong).",
    ],
  },
  latihan: makeSoal([
    ["Teks prosedur bertujuan...", ["Menghibur", "Memandu melakukan sesuatu", "Mendeskripsikan", "Melaporkan"], 1, "Teks prosedur memandu langkah-langkah melakukan sesuatu."],
    ["Struktur teks prosedur yang benar adalah...", ["Langkah - Bahan - Tujuan", "Tujuan - Alat/Bahan - Langkah", "Bahan - Langkah", "Alat - Tujuan - Langkah"], 1, "Urutan benar: Tujuan → Alat/Bahan → Langkah-langkah."],
    ["'Potong bawang hingga halus.' — kalimat ini termasuk...", ["Berita", "Perintah", "Tanya", "Seru"], 1, "'Potong' adalah kata kerja perintah (imperatif)."],
    ["Kata yang tepat untuk mengawali langkah pertama adalah...", ["Dan", "Pertama", "Tetapi", "Atau"], 1, "'Pertama' menunjukkan langkah awal."],
    ["Mana kalimat perintah yang benar?", ["Kita potong bawang", "Potong bawang hingga halus", "Bawang dipotong", "Memotong bawang"], 1, "'Potong bawang' adalah kalimat perintah yang benar dan tegas."],
    ["Bagian 'Alat dan Bahan' berisi...", ["Cara membuat", "Peralatan yang diperlukan", "Hasil akhir", "Kesimpulan"], 1, "Alat dan Bahan berisi daftar perlengkapan yang diperlukan."],
    ["'Tuangkan' berasal dari kata dasar...", ["Menuang", "Tuang", "Tuangkan", "Menuangkan"], 1, "'Tuangkan' berasal dari kata dasar 'tuang'."],
    ["Jika langkah tidak urut, akibatnya...", ["Lebih cepat", "Bisa gagal", "Tetap berhasil", "Lebih mudah"], 1, "Urutan langkah harus benar agar hasil sesuai."],
    ["'Masukkan gula, lalu aduk' — kata 'lalu' menunjukkan...", ["Waktu bersamaan", "Urutan langkah", "Alasan", "Tujuan"], 1, "'Lalu' menunjukkan langkah selanjutnya setelah langkah sebelumnya."],
    ["Teks prosedur yang baik bersifat...", ["Subjektif", "Objektif dan jelas", "Artistik", "Berima"], 1, "Teks prosedur harus objektif, jelas, dan mudah diikuti."],
  ]),
  praktik: {
    petunjuk: "Buat teks prosedur tentang 'Cara Membuat Telur Dadar'! Gunakan struktur lengkap: tujuan, alat dan bahan, langkah-langkah dengan nomor urut.",
    tips: [
      "Coba ingat-ingat cara ibu atau ayah membuat telur dadar",
      "Tulis semua alat yang digunakan: wajan, spatula, mangkuk, kompor",
      "Tulis semua bahan: telur, garam, minyak, daun bawang",
      "Urutkan langkah dari memecah telur hingga selesai",
    ],
    contoh: "Tujuan: Membuat telur dadar sederhana. Alat: Mangkuk, garpu, wajan, spatula, kompor. Bahan: 2 butir telur, 1/4 sdt garam, 2 sdm minyak goreng, daun bawang secukupnya. Langkah: 1. Pecahkan telur ke dalam mangkuk. 2. Tambahkan garam dan daun bawang iris. 3. Kocok telur hingga rata. 4. Panaskan minyak di wajan. 5. Tuang kocokan telur ke wajan. 6. Masak hingga pinggirnya kering, lalu lipat. 7. Balik telur, masak sebentar. 8. Angkat dan sajikan.",
  },
  kuis: makeSoal([
    ["Teks prosedur menggunakan kalimat...", ["Berita", "Perintah", "Tanya", "Seru"], 1, "Teks prosedur menggunakan kalimat perintah (imperatif)."],
    ["Bagian yang menjelaskan tujuan disebut...", ["Judul/pengantar", "Alat dan bahan", "Langkah", "Penutup"], 0, "Tujuan biasanya di judul atau pengantar teks."],
    ["Kata 'pertama, kedua, ketiga' termasuk...", ["Kata tanya", "Kata bilangan urut", "Kata sifat", "Kata kerja"], 1, "Kata bilangan urut menunjukkan urutan langkah."],
    ["Mana yang BUKAN kalimat perintah?", ["Siapkan wajan", "Api kecilkan", "Wajan sudah siap", "Potong bawang"], 2, "'Wajan sudah siap' adalah kalimat berita, bukan perintah."],
    ["Tujuan alat dan bahan adalah...", ["Menambah panjang", "Memberi tahu perlengkapan", "Menghias", "Penutup"], 1, "Alat dan bahan memberitahu perlengkapan yang harus disiapkan."],
    ["'Aduk hingga rata' — kata 'hingga' berarti...", ["Sampai", "Dari", "Untuk", "Oleh"], 0, "'Hingga' berarti 'sampai' sebagai batas."],
    ["Jika membuat resep, langkah pertama biasanya...", ["Menyiapkan alat dan bahan", "Langsung memasak", "Mencuci piring", "Makan"], 0, "Langkah pertama selalu menyiapkan alat dan bahan."],
    ["Kalimat 'Masukkan gula' menggunakan pola...", ["S-P-O", "Predikat-Objek (tanpa subjek)", "S-P", "O-P"], 1, "'Masukkan gula' = Predikat (masukkan) + Objek (gula), tanpa subjek."],
    ["Yang dimaksud 'kata kerja dasar' adalah...", ["Kata kerja tanpa awalan", "Kata kerja berawalan me-", "Kata kerja berawalan ber-", "Kata kerja berakhiran -kan"], 0, "Kata kerja dasar adalah kata kerja tanpa awalan atau akhiran."],
    ["Teks prosedur berbeda dengan teks narasi karena prosedur...", ["Menghibur", "Memandu langkah, bukan bercerita", "Subjektif", "Artistik"], 1, "Prosedur memandu langkah, narasi bercerita."],
  ]),
}

export default konten
