import type { Konten } from "../types"
import { makeSoal } from "../types"

const konten: Konten = {
  belajar: {
    tujuan: [
      "Memahami pengertian dan ciri teks tanggapan",
      "Membedakan tanggapan santun dan tidak santun",
      "Menulis teks tanggapan yang baik dengan struktur lengkap",
    ],
    materi: [
      {
        judul: "Apa Itu Teks Tanggapan?",
        isi: [
          "Teks tanggapan adalah teks yang berisi komentar, pendapat, atau penilaian terhadap sesuatu. Sesuatu itu bisa berupa buku, film, lagu, lukisan, peristiwa, atau hal lainnya.",
          "",
          "✓ Teks tanggapan berisi pendapat pribadi yang didukung alasan.",
          "✓ Teks tanggapan bersifat objektif dan berdasarkan fakta.",
          "✓ Teks tanggapan disampaikan dengan bahasa yang santun.",
          "",
          "Ciri-ciri teks tanggapan:",
          "1. Ada objek yang ditanggapi (buku, film, peristiwa, dll).",
          "2. Berisi penilaian berupa kelebihan dan kekurangan.",
          "3. Dilengkapi alasan yang logis dan masuk akal.",
          "4. Menggunakan bahasa yang sopan dan santun.",
          "",
          "Teks tanggapan berbeda dengan kritik pedas. Tanggapan yang baik bersifat membangun, bukan menjatuhkan.",
          "",
          "[Ilustrasi: Seorang anak memegang buku sambil tersenyum. Di sekelilingnya ada gelembung pikiran berisi ikon bintang (pujian) dan ikon kunci inggris (saran perbaikan). Gaya ilustrasi anak sekolah.]",
        ],
        contoh: [
          "Contoh teks tanggapan tentang sebuah buku cerita:",
          "",
          "✓ 'Buku cerita ini sangat seru. Gambarnya indah dan ceritanya mudah dipahami. Namun, ada beberapa kata yang sulit bagi anak kelas 5. Sebaiknya ditambahkan glosarium di bagian belakang buku.'",
          "  — Tanggapan berisi pujian dan saran yang membangun.",
          "",
          "✗ 'Buku ini jelek. Gambarnya jelek. Ceritanya membosankan. Tidak layak dibaca.'",
          "  — Tanggapan kasar, tidak sopan, dan tidak memberi alasan jelas.",
        ],
        catatan: "Tanggapan berbeda dengan kritik keras. Tanggapan santun selalu menghargai karya orang lain, meskipun kita menemukan kekurangan.",
      },
      {
        judul: "Tanggapan Santun",
        isi: [
          "Tanggapan santun adalah cara menyampaikan pendapat dengan sopan dan menghargai orang lain. Tujuannya bukan untuk menyakiti, melainkan untuk membantu agar lebih baik.",
          "",
          "Cara memberi tanggapan santun:",
          "",
          "1. Mulai dengan hal positif — sampaikan kelebihan atau hal yang kamu suka.",
          "  'Gambar pada buku ini sangat menarik dan penuh warna.'",
          "",
          "2. Sampaikan kekurangan dengan sopan — gunakan kata 'sebaiknya' atau 'alangkah baiknya'.",
          "  'Alangkah baiknya jika cerita ditambah dengan dialog agar lebih hidup.'",
          "",
          "3. Beri alasan yang jelas — jangan hanya mengatakan 'kurang bagus' tanpa penjelasan.",
          "  'Ceritanya kurang seru karena tokoh utamanya tidak mengalami tantangan.'",
          "",
          "4. Akhiri dengan semangat — beri dorongan positif.",
          "  'Semoga karya selanjutnya lebih baik! Teruslah berkarya.'",
          "",
          "[Ilustrasi: Dua anak sedang berbicara. Satu memegang gambar, satu lagi memberi komentar dengan tangan terbuka dan ekspresi ramah. Balon dialog berisi kata 'Bagus!', 'Sebaiknya...'. Gaya ilustrasi anak sekolah.]",
        ],
        contoh: [
          "Bandingkan tanggapan santun dan tidak santun:",
          "",
          "✓ SANTUN: 'Karya lukisanmu bagus sekali warnanya. Untuk bentuk pohonnya, mungkin bisa lebih rajin lagi berlatih. Terus semangat ya!'",
          "  — Pujian dulu, lalu saran membangun, dan dorongan positif.",
          "",
          "✗ TIDAK SANTUN: 'Lukisanmu jelek. Pohonnya tidak seperti pohon. Kamu tidak bakat.'",
          "  — Menjatuhkan, tidak membangun, dan menyakiti perasaan.",
          "",
          "PENTING: Tanggapan santun dimulai dengan pujian, bukan langsung kritik!",
        ],
      },
      {
        judul: "Menulis Teks Tanggapan",
        isi: [
          "Teks tanggapan memiliki struktur yang terdiri dari tiga bagian: konteks, deskripsi, dan penilaian.",
          "",
          "1. KONTEKS — pengenalan objek yang akan ditanggapi.",
          "  'Hari ini saya membaca buku berjudul Petualangan di Hutan Mangrove. Buku ini ditulis oleh Kak Rina dan diterbitkan tahun 2024.'",
          "",
          "2. DESKRIPSI — gambaran singkat tentang objek.",
          "  'Buku ini bercerita tentang seorang anak bernama Raka yang menjelajahi hutan mangrove bersama kakeknya. Buku ini memiliki 50 halaman dengan ilustrasi yang indah.'",
          "",
          "3. PENILAIAN — pendapat tentang kelebihan dan kekurangan.",
          "  'Kelebihan buku ini adalah ilustrasinya yang sangat detail dan warnanya cerah. Ceritanya juga mengandung pesan lingkungan yang bagus. Kekurangannya, ada beberapa istilah ilmiah yang belum dijelaskan. Sebaiknya ditambahkan glosarium.'",
          "",
          "[Ilustrasi: Tiga kotak berisi teks. Kotak 1 'KONTEKS' dengan ikon kaca pembesar. Kotak 2 'DESKRIPSI' dengan ikon buku terbuka. Kotak 3 'PENILAIAN' dengan ikon bintang dan jempol. Panah mengalir dari 1 ke 2 ke 3. Gaya diagram anak-anak.]",
        ],
        contoh: [
          "Contoh teks tanggapan lengkap:",
          "",
          "KONTEKS: 'Film pendek \"Kecil-Kecil Hebat\" yang ditayangkan di kelas tadi sangat menarik.'",
          "",
          "DESKRIPSI: 'Film ini bercerita tentang sekelompok anak yang membersihkan sungai di desa mereka. Durasi film sekitar 15 menit.'",
          "",
          "PENILAIAN: 'Kelebihan film ini adalah pesan moralnya yang jelas tentang menjaga lingkungan. Akting anak-anaknya alami. Kekurangannya, suara musik terlalu keras sehingga dialog kadang tidak terdengar. Saran saya, volume musik dikurangi agar dialog lebih jelas.'",
          "",
          "Tips: Setelah menulis, baca ulang dan pastikan bahasanya sopan dan tidak menyakiti!",
        ],
        catatan: "Struktur konteks-deskripsi-penilaian membuat teks tanggapan menjadi jelas, lengkap, dan mudah dipahami.",
      },
    ],
    rangkuman: [
      "[Ilustrasi: Peta pikiran 'TEKS TANGGAPAN' di tengah. Cabang: PENGERTIAN (komentar/pendapat), CIRI (objektif, santun, beralasan), STRUKTUR (konteks, deskripsi, penilaian), KATA KUNCI (pujian, saran, sebaiknya). Gaya mind map anak-anak.]",
      "Teks tanggapan adalah teks berisi komentar atau penilaian terhadap sesuatu (buku, film, dll).",
      "Tanggapan santun: pujian dulu, saran dengan kata 'sebaiknya', akhiri dengan dorongan positif.",
      "Struktur teks tanggapan: konteks (pengenalan), deskripsi (gambaran), penilaian (kelebihan/kekurangan).",
      "Tanggapan yang baik bersifat membangun, objektif, dan menggunakan bahasa sopan.",
    ],
  },
  latihan: makeSoal([
    ["Teks tanggapan berisi...", ["Cerita fiksi", "Komentar atau penilaian", "Petunjuk", "Laporan"], 1, "Teks tanggapan berisi komentar atau penilaian terhadap sesuatu."],
    ["Objek teks tanggapan bisa berupa berikut, KECUALI...", ["Buku", "Perasaan sendiri", "Film", "Lukisan"], 1, "Perasaan sendiri bukan objek tanggapan; tanggapan tentang karya/hal di luar diri."],
    ["Bagian yang menjelaskan gambaran objek disebut...", ["Konteks", "Deskripsi", "Penilaian", "Kesimpulan"], 1, "Deskripsi berisi gambaran singkat tentang objek."],
    ["Tanggapan santun sebaiknya diawali dengan...", ["Kritik keras", "Hal positif/pujian", "Langsung saran", "Hinaan"], 1, "Tanggapan santun diawali dengan pujian."],
    ["Kata yang baik untuk memberi saran adalah...", ["Kamu salah!", "Sebaiknya...", "Ini jelek!", "Tidak benar!"], 1, "'Sebaiknya' adalah kata yang sopan untuk memberi saran."],
    ["Bagian konteks dalam teks tanggapan berisi...", ["Kelebihan objek", "Pengenalan objek", "Kekurangan objek", "Kesimpulan"], 1, "Konteks memperkenalkan objek yang akan ditanggapi."],
    ["Teks tanggapan yang baik menggunakan bahasa...", ["Kasar", "Santun dan sopan", "Marah", "Bercanda"], 1, "Bahasa santun dan sopan adalah ciri teks tanggapan yang baik."],
    ["Bagian penilaian berisi...", ["Pengenalan objek", "Kelebihan dan kekurangan", "Salam pembuka", "Daftar isi"], 1, "Penilaian berisi kelebihan dan kekurangan objek."],
    ["Berikut contoh tanggapan santun, yaitu...", ["'Gambarmu jelek!'", "'Warnamu bagus, mungkin bentuknya bisa dilatih lagi'", "'Kamu tidak bisa menggambar'", "'Buang gambarmu'"], 1, "Tanggapan santun: pujian lalu saran membangun."],
    ["Tujuan teks tanggapan adalah...", ["Menyakiti perasaan", "Memberi penilaian membangun", "Bercerita fiksi", "Melaporkan berita"], 1, "Tujuan teks tanggapan adalah memberi penilaian yang membangun."],
  ]),
  praktik: {
    petunjuk: "Pilihlah salah satu: buku cerita yang pernah kamu baca, film yang pernah kamu tonton, atau lukisan yang pernah kamu lihat. Tulislah teks tanggapan dengan struktur konteks, deskripsi, dan penilaian!",
    tips: [
      "Kenali objek dengan baik sebelum memberi tanggapan",
      "Mulai dengan hal positif yang kamu suka dari objek tersebut",
      "Sampaikan saran dengan kata 'sebaiknya' atau 'alangkah baiknya'",
      "Akhiri dengan semangat dan dorongan positif",
    ],
    contoh: "KONTEKS: Saya baru saja membaca buku cerita berjudul 'Si Kancil dan Buaya' yang ada di perpustakaan sekolah. DESKRIPSI: Buku ini bercerita tentang kecerdikan Kancil yang berhasil menyeberangi sungai dengan mengelabui Buaya. Ilustrasinya penuh warna. PENILAIAN: Kelebihan buku ini adalah ceritanya seru dan pesan moralnya bagus, yaitu kecerdikan lebih baik daripada kekuatan. Kekurangannya, bahasa yang digunakan agak sulit untuk anak kelas 5. Sebaiknya ditambahkan penjelasan kata-kata sulit di bagian belakang.",
  },
  kuis: makeSoal([
    ["Struktur teks tanggapan yang benar adalah...", ["Penilaian-konteks-deskripsi", "Konteks-deskripsi-penilaian", "Deskripsi-penilaian-konteks", "Deskripsi-konteks-penilaian"], 1, "Struktur: konteks, deskripsi, penilaian."],
    ["Berikut adalah ciri tanggapan tidak santun, yaitu...", ["Menggunakan kata 'sebaiknya'", "Langsung menjatuhkan tanpa alasan", "Memberi pujian dulu", "Memberi saran membangun"], 1, "Tanggapan tidak santun langsung menjatuhkan tanpa alasan."],
    ["'Film ini bagus alur ceritanya. Namun, durasinya terlalu panjang.' Ini adalah bagian...", ["Konteks", "Deskripsi", "Penilaian", "Pembukaan"], 2, "Penilaian berisi kelebihan dan kekurangan."],
    ["Kata 'alangkah baiknya' termasuk dalam jenis kalimat...", ["Perintah", "Saran", "Larangan", "Tanya"], 1, "Kata 'alangkah baiknya' digunakan untuk memberi saran."],
    ["Objek teks tanggapan bisa berupa...", ["Cuaca", "Buku atau film", "Mimpi", "Angin"], 1, "Buku dan film adalah objek yang bisa ditanggapi."],
    ["Bagian deskripsi berisi...", ["Pendapat pribadi", "Gambaran objek", "Salam", "Kesimpulan"], 1, "Deskripsi berisi gambaran singkat objek."],
    ["Tanggapan santun sebaiknya diakhiri dengan...", ["Kritik pedas", "Dorongan positif", "Tidak ada ucapan", "Kalimat marah"], 1, "Tanggapan santun diakhiri dengan dorongan positif."],
    ["Buku cerita bergambar yang indah namun ceritanya kurang seru. Tanggapanmu?",
      ["'Buku ini jelek, buang saja'",
       "'Ilustrasinya bagus, semoga cerita selanjutnya lebih seru'",
       "'Gambarnya tidak berguna'",
       "'Ceritanya paling buruk'"],
      1, "Tanggapan santun: puji kelebihan, saran untuk kekurangan."],
    ["Teks tanggapan bersifat objektif artinya...", ["Berdasarkan perasaan", "Berdasarkan fakta", "Berdasarkan mimpi", "Berdasarkan tebakan"], 1, "Objektif berarti berdasarkan fakta dan kenyataan."],
    ["Berikut contoh kalimat konteks, yaitu...", ["'Buku ini bagus sekali'", "'Hari ini saya menonton film tentang pahlawan'", "'Warnanya kurang cerah'", "'Sebaiknya ditambah ilustrasi'"], 1, "Kalimat konteks memperkenalkan objek yang akan ditanggapi."],
  ]),
}
export default konten
