import type { Konten } from "../types"
import { makeSoal } from "../types"

const konten: Konten = {
  belajar: {
    tujuan: [
      "Memahami pengertian dan tujuan resensi",
      "Mengidentifikasi unsur-unsur resensi buku",
      "Menulis resensi buku dengan bahasa kritis dan objektif",
    ],
    materi: [
      {
        judul: "Mengenal Resensi",
        isi: [
          "Resensi adalah ulasan atau penilaian terhadap sebuah buku. Resensi juga sering disebut timbangan buku atau bedah buku. Tujuan resensi adalah memberi informasi dan penilaian kepada pembaca tentang isi buku.",
          "",
          "✓ Resensi memberi gambaran isi buku tanpa harus membaca seluruhnya.",
          "✓ Resensi membantu pembaca memutuskan apakah buku itu layak dibaca.",
          "✓ Resensi berisi pendapat yang disertai alasan.",
          "",
          "Manfaat membaca resensi:",
          "1. Mengetahui isi buku secara singkat sebelum membeli atau meminjamnya.",
          "2. Mendapat sudut pandang baru tentang buku dari orang lain.",
          "3. Belajar menilai kualitas buku secara objektif.",
          "",
          "Orang yang menulis resensi disebut peresensi. Peresensi harus jujur dalam memberi penilaian.",
          "",
          "[Ilustrasi: Sebuah buku terbuka dengan kaca pembesar di atasnya. Di sekitar buku ada ikon bintang, jempol naik, dan catatan kecil berisi tulisan 'MENARIK!'. Gaya ilustrasi anak-anak.]",
        ],
        contoh: [
          "Resensi singkat buku cerita:",
          "",
          "✓ RESENSI BAIK: 'Buku \"Petualangan di Hutan\" menceritakan perjalanan tiga sahabat mencari harta karun. Ilustrasinya menarik dan penuh warna. Ceritanya seru dengan pesan tentang persahabatan. Kekurangannya, beberapa bab terlalu pendek.'",
          "  — Memberi gambaran, kelebihan, dan kekurangan.",
          "",
          "✗ BUKAN RESENSI: 'Buku ini bagus. Aku suka. Pokoknya keren deh.'",
          "  — Tidak ada gambaran isi dan alasan yang jelas.",
        ],
        catatan: "Resensi berbeda dengan sinopsis. Sinopsis hanya berisi ringkasan cerita, sedangkan resensi berisi ringkasan dan penilaian (kelebihan dan kekurangan).",
      },
      {
        judul: "Unsur-Unsur Resensi",
        isi: [
          "Sebuah resensi yang lengkap memiliki beberapa unsur penting:",
          "",
          "1. IDENTITAS BUKU — informasi tentang buku yang diulas.",
          "  • Judul buku",
          "  • Nama pengarang/penulis",
          "  • Penerbit",
          "  • Tahun terbit",
          "  • Tebal halaman",
          "  • Harga buku (jika ada)",
          "",
          "2. SINOPSIS — ringkasan isi buku secara singkat.",
          "  'Buku ini bercerita tentang seorang anak bernama Dika yang menemukan seekor kucing ajaib...'",
          "",
          "3. PENILAIAN — kelebihan dan kekurangan buku.",
          "  ✓ Kelebihan: bahasa mudah dipahami, ilustrasi menarik, pesan moral bagus.",
          "  ✗ Kekurangan: beberapa istilah asing tanpa penjelasan, cetakan kurang rapi.",
          "",
          "[Ilustrasi: Diagram tiga lingkaran yang saling terhubung. Lingkaran 1 'IDENTITAS BUKU' dengan ikon buku. Lingkaran 2 'SINOPSIS' dengan ikon kertas. Lingkaran 3 'PENILAIAN' dengan ikon bintang setengah. Gaya diagram anak-anak.]",
        ],
        contoh: [
          "Contoh identitas buku dalam resensi:",
          "",
          "Judul Buku: Si Kancil yang Cerdik",
          "Pengarang: Kak Rina Wijaya",
          "Penerbit: Pustaka Cerdas",
          "Tahun Terbit: 2025",
          "Tebal: 64 halaman",
          "",
          "✓ Identitas ditulis lengkap agar pembaca tahu persis buku yang diulas.",
          "  — Memudahkan pembaca mencari buku jika tertarik.",
          "",
          "✗ Hanya menulis judul tanpa informasi lain.",
          "  — Pembaca tidak tahu penerbit atau pengarangnya.",
        ],
      },
      {
        judul: "Menulis Resensi Buku",
        isi: [
          "Setelah memahami unsur-unsur resensi, sekarang saatnya menulis! Berikut langkah-langkahnya:",
          "",
          "1. Baca buku dengan saksama — pahami isi cerita dan pesan yang ingin disampaikan.",
          "2. Catat informasi penting — judul, pengarang, penerbit, dll.",
          "3. Tulis sinopsis singkat — 3-5 kalimat yang menggambarkan isi buku.",
          "4. Tulis penilaian — apa kelebihan dan kekurangan buku?",
          "5. Beri kesimpulan — apakah buku ini layak dibaca? Untuk siapa buku ini cocok?",
          "",
          "Tips menulis resensi yang baik:",
          "",
          "✓ Gunakan bahasa yang kritis tetapi santun.",
          "✓ Beri alasan untuk setiap pendapat yang kamu sampaikan.",
          "✓ Bandingkan dengan buku lain jika perlu.",
          "✓ Jangan lupa mencantumkan identitas buku.",
          "",
          "[Ilustrasi: Seorang anak sedang menulis di atas meja. Di depannya ada buku terbuka, pensil, dan kertas. Wajahnya konsentrasi. Di dinding ada poster 'LANGKAH MERESENSI'. Gaya ilustrasi anak sekolah.]",
        ],
        contoh: [
          "Contoh resensi buku SD kelas 5:",
          "",
          "IDENTITAS BUKU",
          "Judul: Kumpulan Dongeng Nusantara",
          "Pengarang: Dian Puspita",
          "Penerbit: Gramedia Pustaka",
          "Tahun: 2024 | Tebal: 88 halaman",
          "",
          "SINOPSIS: Buku ini berisi 10 dongeng dari berbagai daerah di Indonesia. Ada dongeng Malin Kundang dari Sumatera Barat, Roro Jonggrang dari Jawa Tengah, dan Asal Mula Danau Toba dari Sumatera Utara. Setiap dongeng disertai ilustrasi indah.",
          "",
          "PENILAIAN: Kelebihan buku ini adalah bahasa yang sederhana dan mudah dipahami. Ilustrasinya memukau penuh warna. Pesan moral setiap dongeng sangat bagus. Kekurangannya, ada beberapa dongeng yang terlalu pendek sehingga cerita terasa cepat selesai.",
          "",
          "Kesimpulan: Buku ini sangat cocok untuk anak SD. Dongeng Nusantara mengajarkan kita tentang kearifan lokal dan nilai-nilai luhur bangsa.",
        ],
        catatan: "Saat menulis penilaian, pastikan kamu sudah membaca buku seutuhnya. Jangan memberi penilaian hanya berdasarkan sampul atau judul saja!",
      },
    ],
    rangkuman: [
      "[Ilustrasi: Peta pikiran 'RESENSI' di tengah. Cabang: PENGERTIAN (ulasan/penilaian buku), UNSUR (identitas, sinopsis, penilaian), LANGKAH (baca, catat, tulis sinopsis, nilai, simpulkan), KATA KUNCI (kelebihan, kekurangan, saran). Gaya mind map anak-anak.]",
      "Resensi adalah ulasan atau penilaian tentang sebuah buku.",
      "Unsur resensi: identitas buku (judul, pengarang, penerbit), sinopsis (ringkasan), dan penilaian (kelebihan/kekurangan).",
      "Langkah menulis resensi: baca buku, catat info, tulis sinopsis, tulis penilaian, beri kesimpulan.",
      "Gunakan bahasa kritis dan santun, serta beri alasan untuk setiap pendapat.",
    ],
  },
  latihan: makeSoal([
    ["Resensi adalah...", ["Sinopsis buku", "Ulasan atau penilaian buku", "Daftar isi buku", "Biografi penulis"], 1, "Resensi adalah ulasan/penilaian terhadap buku."],
    ["Berikut termasuk identitas buku dalam resensi, KECUALI...", ["Judul buku", "Harga pensil", "Nama pengarang", "Tahun terbit"], 1, "Harga pensil tidak termasuk identitas buku."],
    ["Sinopsis dalam resensi berisi...", ["Penilaian buku", "Ringkasan isi buku", "Harga buku", "Kritik"], 1, "Sinopsis berisi ringkasan isi buku."],
    ["Bagian yang berisi kelebihan dan kekurangan buku disebut...", ["Identitas", "Sinopsis", "Penilaian", "Kesimpulan"], 2, "Penilaian berisi kelebihan dan kekurangan buku."],
    ["Bahasa yang digunakan dalam resensi sebaiknya...", ["Kasar dan keras", "Kritis dan santun", "Bercanda", "Marah"], 1, "Resensi menggunakan bahasa kritis tetapi santun."],
    ["Orang yang menulis resensi disebut...", ["Pengarang", "Peresensi", "Penerbit", "Pembaca"], 1, "Peresensi adalah orang yang menulis resensi."],
    ["Tujuan resensi adalah...", ["Menjual buku", "Memberi informasi dan penilaian buku", "Menceritakan ulang", "Mencari kesalahan"], 1, "Tujuan resensi memberi informasi dan penilaian."],
    ["Berikut yang termasuk dalam identitas buku adalah...", ["Nama peresensi", "Penerbit", "Tanggal resensi", "Harga kertas"], 1, "Penerbit termasuk identitas buku."],
    ["Resensi yang baik harus bersifat...", ["Subjektif", "Objektif", "Asal-asalan", "Bergurau"], 1, "Resensi yang baik bersifat objektif (berdasarkan fakta)."],
    ["Resensi berbeda dengan sinopsis karena resensi juga berisi...", ["Judul buku", "Penilaian", "Nama penulis", "Sampul buku"], 1, "Resensi berisi penilaian, sinopsis hanya ringkasan."],
  ]),
  praktik: {
    petunjuk: "Pilihlah satu buku cerita yang pernah kamu baca. Tulislah resensi singkat dengan mencantumkan identitas buku, sinopsis, penilaian, dan kesimpulan!",
    tips: [
      "Pastikan sudah membaca seluruh buku sebelum menulis resensi",
      "Catat identitas buku: judul, pengarang, penerbit, tahun terbit",
      "Tulis sinopsis 3-5 kalimat saja, jangan terlalu panjang",
      "Berikan penilaian jujur tentang kelebihan dan kekurangan buku",
    ],
    contoh: "IDENTITAS BUKU: Judul: Si Juki & Petualangan Makanan. Pengarang: Faza Meonk. Penerbit: Bukune. Tahun: 2023. Tebal: 56 halaman. SINOPSIS: Buku ini bercerita tentang Juki yang berpetualang mencicipi berbagai makanan tradisional Indonesia. Dari sate, gado-gado, hingga rendang. Setiap makanan punya cerita unik. PENILAIAN: Kelebihan buku ini adalah lucu dan informatif. Kita jadi tahu makanan tradisional dari berbagai daerah. Gambarnya kocak dan penuh ekspresi. Kekurangannya, beberapa istilah daerah tidak dijelaskan artinya. KESIMPULAN: Buku ini cocok untuk anak yang suka petualangan dan ingin tahu kuliner Nusantara.",
  },
  kuis: makeSoal([
    ["Sinopsis adalah...", ["Penilaian buku", "Ringkasan isi buku", "Identitas buku", "Kritik buku"], 1, "Sinopsis adalah ringkasan isi buku."],
    ["Berikut yang TIDAK perlu dicantumkan dalam identitas buku adalah...", ["Judul buku", "Nama pembaca", "Pengarang", "Penerbit"], 1, "Nama pembaca tidak perlu dicantumkan."],
    ["Penilaian dalam resensi berisi...", ["Harga buku", "Kelebihan dan kekurangan", "Daftar bab", "Sampul buku"], 1, "Penilaian berisi kelebihan dan kekurangan."],
    ["Kata 'kritis' dalam resensi berarti...", ["Pemarah", "Menganalisis dengan alasan", "Menghina", "Bergurau"], 1, "Kritis berarti menganalisis dengan alasan yang logis."],
    ["Resensi buku membantu pembaca untuk...", ["Membeli buku tanpa tahu isinya", "Mengetahui isi buku secara singkat", "Menyalin buku", "Menjual buku"], 1, "Resensi membantu mengetahui isi buku secara singkat."],
    ["Langkah pertama menulis resensi adalah...", ["Menulis penilaian", "Membaca buku dengan saksama", "Mencari harga", "Membuat sampul"], 1, "Langkah pertama adalah membaca buku dengan saksama."],
    ["Peresensi harus bersikap...", ["Memihak", "Jujur dalam penilaian", "Tidak peduli", "Pilih kasih"], 1, "Peresensi harus jujur dalam penilaian."],
    ["Bagian resensi yang menjawab 'tentang apa buku ini?' adalah...", ["Identitas", "Sinopsis", "Penilaian", "Kesimpulan"], 1, "Sinopsis menjawab tentang apa isi buku tersebut."],
    ["'Buku ini kurang bagus karena tidak ada gambar.' Termasuk bagian...", ["Identitas", "Sinopsis", "Penilaian", "Judul"], 2, "Penilaian berisi pendapat tentang kekurangan buku."],
    ["Tujuan mencantumkan identitas buku adalah...", ["Agar terlihat panjang", "Supaya pembaca tahu buku yang diulas", "Agar mahal", "Supaya terkenal"], 1, "Identitas buku membantu pembaca tahu buku yang dimaksud."],
  ]),
}
export default konten
