import type { Konten } from "../types"
import { makeSoal } from "../types"

const konten: Konten = {
  belajar: {
    tujuan: [
      "Memahami pengertian dan tujuan pidato",
      "Mengidentifikasi struktur pidato yang benar",
      "Berpidato dengan bahasa yang baik dan percaya diri",
    ],
    materi: [
      {
        judul: "Apa Itu Pidato?",
        isi: [
          "Pidato adalah kegiatan berbicara di depan umum untuk menyampaikan pendapat, gagasan, atau informasi. Orang yang berpidato disebut orator.",
          "",
          "✓ Pidato informatif: memberi informasi atau pengetahuan kepada pendengar.",
          "✓ Pidato persuasif: mengajak atau memengaruhi pendengar untuk melakukan sesuatu.",
          "✓ Pidato rekreatif: menghibur pendengar dengan cerita atau humor.",
          "",
          "Pernahkah kamu melihat orang berpidato?",
          "1. Saat upacara bendera, pembina upacara menyampaikan pidato.",
          "2. Saat perayaan hari besar, ada sambutan dari kepala sekolah.",
          "3. Saat lomba pidato, peserta menyampaikan gagasannya.",
          "",
          "Tujuan pidato bermacam-macam, tergantung acaranya. Pidato juga harus disesuaikan dengan siapa pendengarnya.",
          "",
          "[Ilustrasi: Seorang anak berdiri di mimbar upacara bendera. Tangan memegang mikrofon, di depan teman-teman dan guru. Bendera merah putih berkibar di belakang. Gaya ilustrasi anak sekolah kartun.]",
        ],
        contoh: [
          "Contoh kalimat pembuka pidato:",
          "",
          "✓ 'Selamat pagi, Bapak/Ibu Guru dan teman-teman yang saya sayangi. Pertama-tama, marilah kita panjatkan puji syukur ke hadirat Tuhan Yang Maha Esa.'",
          "  — Salam pembuka yang sopan dan lengkap.",
          "",
          "✗ 'Hai semuanya! Dengarkan aku ya!'",
          "  — Terlalu santai dan tidak sopan untuk pidato formal.",
        ],
        catatan: "Orator adalah sebutan untuk orang yang berpidato. Lawan bicara dalam pidato disebut audiens atau pendengar.",
      },
      {
        judul: "Struktur Pidato",
        isi: [
          "Pidato yang baik memiliki tiga bagian utama: pembukaan, isi, dan penutup.",
          "",
          "1. PEMBUKAAN — salam, ucapan syukur, dan pengenalan topik.",
          "  'Assalamu\'alaikum Wr. Wb. Selamat pagi, Bapak/Ibu Guru dan teman-teman. Mari kita bersyukur atas nikmat Tuhan. Pada kesempatan ini, saya akan menyampaikan pidato tentang pentingnya membaca.'",
          "",
          "2. ISI — gagasan atau informasi yang disampaikan.",
          "  'Membaca adalah jendela dunia. Dengan membaca, kita bisa tahu banyak hal. buku memberi ilmu dan pengetahuan. Oleh karena itu, kita harus rajin membaca.'",
          "",
          "3. PENUTUP — kesimpulan, permintaan maaf, dan salam penutup.",
          "  'Demikian pidato saya. Mohon maaf jika ada kesalahan. Wassalamu\'alaikum Wr. Wb.'",
          "",
          "[Ilustrasi: Diagram tiga kotak berjejer vertikal. Kotak 1: 'PEMBUKAAN' dengan ikon mikrofon. Kotak 2: 'ISI' dengan ikon buku. Kotak 3: 'PENUTUP' dengan ikon tangan melambai. Gaya diagram anak-anak.]",
        ],
        contoh: [
          "Bandingkan urutan pidato yang benar dan salah:",
          "",
          "✓ STRUKTUR LENGKAP:",
          "  Pembukaan → 'Selamat pagi...'",
          "  Isi → 'Hari ini saya akan bicara tentang disiplin...'",
          "  Penutup → 'Demikian... mohon maaf...'",
          "",
          "✗ STRUKTUR TIDAK LENGKAP:",
          "  Langsung isi tanpa salam → 'Disiplin itu penting...'",
          "  — Tidak sopan, pendengar belum siap.",
        ],
      },
      {
        judul: "Berpidato yang Baik",
        isi: [
          "Berpidato yang baik tidak hanya soal apa yang diucapkan, tetapi juga bagaimana cara mengucapkannya.",
          "",
          "Hal-hal penting saat berpidato:",
          "",
          "1. Suara jelas dan lantang — semua pendengar harus mendengar.",
          "2. Pandangan mata ke audiens — jangan melihat ke lantai atau ke kertas terus.",
          "3. Ekspresi wajah sesuai — tersenyum bila perlu, serius bila topiknya penting.",
          "4. Gerakan tubuh wajar — gunakan tangan untuk menekankan poin.",
          "5. Bahasa sopan dan mudah dipahami — gunakan kata-kata yang dimengerti semua orang.",
          "",
          "Latihan sebelum pidato juga penting! Berlatihlah di depan cermin atau di depan keluarga.",
          "",
          "[Ilustrasi: Seorang anak berpidato di depan kelas dengan percaya diri. Tangan terbuka lebar, senyum ramah, teman-teman memperhatikan. Balon dialog berisi 'Pagi ini saya akan...'. Gaya ilustrasi anak sekolah.]",
        ],
        contoh: [
          "Perbedaan pidato yang baik dan kurang baik:",
          "",
          "✓ PIDATO BAIK: Suara jelas, melihat audiens, tersenyum, gerakan tangan wajar.",
          "  — Audiens tertarik dan memahami isi pidato.",
          "",
          "✗ PIDATO KURANG BAIK: Suara pelan, menunduk, membaca terus, tidak ada gerakan.",
          "  — Audiens bosan dan tidak memperhatikan.",
          "",
          "Tips: Tarik napas dalam sebelum mulai bicara. Ini membuatmu lebih tenang dan percaya diri!",
        ],
        catatan: "Demam panggung atau grogi saat berbicara di depan umum itu wajar. Semakin sering latihan, rasa grogi akan berkurang.",
      },
    ],
    rangkuman: [
      "[Ilustrasi: Peta pikiran dengan 'PIDATO' di tengah. Cabang: PENGERTIAN (bicara di depan umum), TUJUAN (informatif, persuasif, rekreatif), STRUKTUR (pembukaan, isi, penutup), TIPS (suara jelas, pandangan, ekspresi). Gaya mind map anak-anak.]",
      "Pidato adalah kegiatan berbicara di depan umum untuk menyampaikan gagasan atau informasi.",
      "Tiga tujuan pidato: informatif (memberi tahu), persuasif (mengajak), rekreatif (menghibur).",
      "Struktur pidato: pembukaan (salam, syukur), isi (gagasan), penutup (kesimpulan, maaf, salam).",
      "Berpidato yang baik: suara jelas, pandangan ke audiens, ekspresi sesuai, bahasa sopan.",
    ],
  },
  latihan: makeSoal([
    ["Pidato adalah kegiatan berbicara di depan...", ["Teman sendiri", "Umum/orang banyak", "Keluarga", "Guru saja"], 1, "Pidato dilakukan di depan umum atau orang banyak."],
    ["Orang yang berpidato disebut...", ["Audien", "Orator", "Presenter", "Pembaca"], 1, "Orator adalah sebutan untuk orang yang berpidato."],
    ["Pidato yang bertujuan mengajak pendengar disebut pidato...", ["Informatif", "Persuasif", "Rekreatif", "Formal"], 1, "Pidato persuasif bertujuan mengajak atau memengaruhi."],
    ["Bagian pembukaan pidato biasanya berisi...", ["Salam dan ucapan syukur", "Gagasan utama", "Kesimpulan", "Cerita lucu"], 0, "Pembukaan pidato berisi salam dan ucapan syukur."],
    ["Bagian isi pidato berisi...", ["Salam penutup", "Gagasan yang disampaikan", "Ucapan terima kasih", "Permintaan maaf"], 1, "Bagian isi berisi gagasan atau informasi yang disampaikan."],
    ["Berikut adalah ciri pidato yang baik, KECUALI...", ["Suara jelas", "Membaca terus tanpa melihat audiens", "Pandangan ke pendengar", "Ekspresi sesuai"], 1, "Pidato yang baik tidak membaca terus; harus melihat audiens."],
    ["Pidato rekreatif bertujuan...", ["Mengajak", "Menghibur", "Memberi info", "Menyuruh"], 1, "Pidato rekreatif bertujuan menghibur pendengar."],
    ["Bagian penutup pidato sebaiknya berisi...", ["Salam pembuka", "Kesimpulan dan permintaan maaf", "Topik baru", "Lagu"], 1, "Penutup pidato berisi kesimpulan dan permintaan maaf."],
    ["Sebelum berpidato, sebaiknya kita...", ["Langsung bicara", "Berlatih terlebih dahulu", "Diam saja", "Menulis tanpa baca"], 1, "Berlatih sebelum pidato penting agar lebih percaya diri."],
    ["Audiens dalam pidato adalah...", ["Orang yang berpidato", "Pendengar pidato", "Penulis pidato", "Penyelenggara"], 1, "Audiens adalah pendengar pidato."],
  ]),
  praktik: {
    petunjuk: "Buatlah teks pidato singkat tentang 'Pentingnya Membaca'! Gunakan struktur pembukaan, isi, dan penutup. Setelah itu, praktikkan berpidato di depan teman atau keluarga!",
    tips: [
      "Tulis dulu kerangka pidato: pembukaan, isi, penutup",
      "Gunakan bahasa yang sopan dan mudah dimengerti",
      "Latih di depan cermin agar lebih percaya diri",
      "Perhatikan suara, pandangan, dan ekspresi saat berpidato",
    ],
    contoh: "Assalamu'alaikum Wr. Wb. Selamat pagi, Bapak/Ibu Guru dan teman-teman yang saya sayangi. Mari kita bersyukur kepada Tuhan karena masih diberi kesehatan. Hari ini saya akan berpidato tentang pentingnya membaca. Membaca adalah jendela dunia. Dengan membaca, kita bisa tahu banyak hal tanpa harus pergi ke tempatnya. Buku memberi ilmu dan pengetahuan yang tak terbatas. Oleh karena itu, marilah kita rajin membaca setiap hari. Mulailah dari buku yang kita suka. Demikian pidato saya. Mohon maaf jika ada kesalahan. Wassalamu'alaikum Wr. Wb.",
  },
  kuis: makeSoal([
    ["Pidato informatif bertujuan...", ["Menghibur", "Memberi informasi", "Mengajak", "Melarang"], 1, "Pidato informatif memberi informasi atau pengetahuan."],
    ["Kata lain untuk pendengar pidato adalah...", ["Orator", "Audiens", "Pembicara", "Moderator"], 1, "Audiens adalah pendengar pidato."],
    ["Bagian pidato yang berisi salam dan ucapan syukur adalah...", ["Isi", "Pembukaan", "Penutup", "Kesimpulan"], 1, "Pembukaan berisi salam dan ucapan syukur."],
    ["Pidato persuasif bertujuan...", ["Memberi hiburan", "Mengajak atau memengaruhi", "Memberi info", "Menjelaskan"], 1, "Persuasif berarti mengajak atau memengaruhi."],
    ["Saat berpidato, pandangan mata sebaiknya...", ["Ke lantai", "Ke audiens", "Ke langit-langit", "Tertutup"], 1, "Pandangan ke audiens agar mereka merasa diajak bicara."],
    ["Berikut yang termasuk pidato rekreatif adalah...", ["Pidato sambutan hari kemerdekaan yang lucu", "Pidato tentang bahaya narkoba", "Pidato ajakan menabung", "Pidato laporan"], 0, "Pidato rekreatif menghibur, misalnya pidato lucu."],
    ["Struktur pidato yang benar adalah...", ["Isi-pembukaan-penutup", "Pembukaan-isi-penutup", "Penutup-isi-pembukaan", "Pembukaan-penutup-isi"], 1, "Susunan pidato: pembukaan, isi, penutup."],
    ["Salah satu tips agar pidato tidak grogi adalah...", ["Bicara cepat", "Berlatih sebelumnya", "Membaca dalam hati", "Tidak usah lihat audiens"], 1, "Berlatih sebelumnya mengurangi rasa grogi."],
    ["Kalimat 'Demikian pidato saya. Mohon maaf jika ada kesalahan.' adalah bagian...", ["Pembukaan", "Isi", "Penutup", "Salam"], 2, "Penutup berisi kesimpulan dan permintaan maaf."],
    ["Tujuan pidato harus disesuaikan dengan...", ["Keinginan orator", "Acara dan pendengar", "Panjang teks", "Hari"], 1, "Pidato disesuaikan dengan acara dan siapa pendengarnya."],
  ]),
}
export default konten
