import type { Konten } from "../types"
import { makeSoal } from "../types"

const konten: Konten = {
  belajar: {
    tujuan: [
      "Memahami pengertian dan tujuan wawancara",
      "Menyusun pertanyaan wawancara yang baik",
      "Membuat laporan hasil wawancara dengan benar",
    ],
    materi: [
      {
        judul: "Apa Itu Wawancara?",
        isi: [
          "Wawancara adalah kegiatan tanya jawab antara pewawancara dan narasumber untuk mendapatkan informasi. Pewawancara bertanya, narasumber menjawab.",
          "",
          "✓ Pewawancara: orang yang mengajukan pertanyaan.",
          "✓ Narasumber: orang yang memberikan jawaban atau informasi.",
          "✓ Tujuan wawancara: mendapatkan data atau informasi yang akurat.",
          "",
          "Jenis-jenis wawancara berdasarkan tujuannya:",
          "1. Wawancara berita — untuk mendapatkan informasi peristiwa terkini.",
          "2. Wawancara penelitian — untuk mengumpulkan data tugas sekolah atau penelitian.",
          "3. Wawancara profil — untuk mengenal lebih dekat tokoh atau seseorang.",
          "4. Wawancara kerja — untuk seleksi calon pekerja.",
          "",
          "Pernahkah kamu mewawancarai seseorang? Mungkin saat tugas sekolah, kamu mewawancarai pedagang di pasar atau ketua RT.",
          "",
          "[Ilustrasi: Seorang anak duduk berhadapan dengan seorang petani. Anak memegang buku catatan dan pena, tersenyum ramah. Petani menjawab dengan ekspresi bersahabat. Gaya ilustrasi anak sekolah.]",
        ],
        contoh: [
          "Contoh situasi wawancara di sekolah:",
          "",
          "✓ Situasi: Tugas membuat laporan tentang profesi.",
          "  Pewawancara: 'Selamat pagi, Pak. Saya ingin mewawancarai Bapak tentang pekerjaan sebagai nelayan.'",
          "  Narasumber: 'Selamat pagi, silakan. Saya senang membantu.'",
          "",
          "✗ Situasi: Langsung bertanya tanpa salam.",
          "  Pewawancara: 'Pak, berapa banyak ikan yang ditangkap?'",
          "  — Tidak sopan, belum memperkenalkan diri dan tujuan.",
        ],
        catatan: "Narasumber adalah 'sumber berita'. Pilihlah narasumber yang benar-benar tahu tentang topik yang kamu tanyakan.",
      },
      {
        judul: "Menyusun Pertanyaan",
        isi: [
          "Pertanyaan yang baik adalah kunci wawancara yang sukses. Berikut langkah-langkah menyusun pertanyaan:",
          "",
          "1. Tentukan topik wawancara.",
          "  Misal: 'Kebiasaan Membaca di Kelas 5'",
          "",
          "2. Cari tahu tentang topik dan narasumber.",
          "  Pelajari sedikit tentang topik agar pertanyaan relevan.",
          "",
          "3. Buat daftar pertanyaan — gunakan 5W+1H (Apa, Siapa, Kapan, Di mana, Mengapa, Bagaimana).",
          "  Apa: 'Apa yang membuatmu suka membaca?'",
          "  Mengapa: 'Mengapa membaca itu penting?'",
          "  Bagaimana: 'Bagaimana cara membagi waktu antara belajar dan membaca?'",
          "",
          "4. Susun dari yang mudah ke yang sulit.",
          "  Mulai dengan pertanyaan ringan agar narasumber nyaman.",
          "",
          "[Ilustrasi: Sebuah buku catatan terbuka dengan daftar pertanyaan. Di atasnya ada ikon 5W+1H: Apa (tanda tanya), Siapa (orang), Kapan (jam), Di mana (peta), Mengapa (koma besar), Bagaimana (roda gigi). Gaya ilustrasi catatan anak-anak.]",
        ],
        contoh: [
          "Perbandingan pertanyaan baik dan kurang baik:",
          "",
          "✓ PERTANYAAN BAIK (menggunakan 5W+1H):",
          "  'Apa yang membuat Ibu tertarik menjadi guru?'",
          "  'Sudah berapa lama Ibu mengajar di sekolah ini?'",
          "  — Terbuka, mendorong narasumber bercerita.",
          "",
          "✗ PERTANYAAN KURANG BAIK (hanya ya/tidak):",
          "  'Apakah Ibu senang menjadi guru?' (jawab: 'Ya.')",
          "  'Apakah Ibu mengajar lama?' (jawab: 'Iya.')",
          "  — Terlalu pendek, informasi yang didapat sedikit.",
        ],
      },
      {
        judul: "Melapor Hasil Wawancara",
        isi: [
          "Setelah wawancara selesai, langkah selanjutnya adalah membuat laporan hasil wawancara. Laporan harus ditulis dengan rapi dan mudah dipahami.",
          "",
          "Struktur laporan wawancara:",
          "",
          "1. JUDUL — topik wawancara.",
          "  'Laporan Wawancara: Kebiasaan Membaca Siswa Kelas 5'",
          "",
          "2. IDENTITAS — nama pewawancara, narasumber, tanggal, tempat.",
          "  'Pewawancara: Siti Nurhaliza'",
          "  'Narasumber: Ibu Dewi, Guru Kelas 5'",
          "  'Tanggal: 10 Maret 2026'",
          "  'Tempat: Ruang Guru SDN Cerdas'",
          "",
          "3. ISI WAWANCARA — tulis dalam bentuk narasi atau tanya jawab.",
          "  'Ibu Dewi menjelaskan bahwa kebiasaan membaca siswa kelas 5 sudah cukup baik. Setiap hari ada waktu 15 menit membaca sebelum pelajaran. Menurut Ibu Dewi, membaca membuat siswa lebih pintar dan kreatif.'",
          "",
          "4. KESIMPULAN — ringkasan hasil wawancara.",
          "  'Kesimpulannya, membaca adalah kebiasaan baik yang perlu terus ditingkatkan.'",
          "",
          "[Ilustrasi: Sebuah kertas laporan dengan judul 'LAPORAN WAWANCARA'. Ada ikon orang (pewawancara), ikon buku (narasumber), ikon kalender (tanggal), dan ikon lokasi (tempat). Gaya dokumen anak-anak.]",
        ],
        contoh: [
          "Contoh laporan wawancara singkat:",
          "",
          "JUDUL: Laporan Wawancara tentang Profesi Nelayan",
          "IDENTITAS: Pewawancara: Andi. Narasumber: Pak Rudi (Nelayan). Tanggal: 5 April 2026.",
          "",
          "ISI: Pak Rudi mulai melaut pukul 04.00 pagi. Ia menggunakan perahu motor kecil. Dalam sehari, ia bisa menangkap 10-20 kg ikan. Pak Rudi menjual ikannya ke TPI (Tempat Pelelangan Ikan). Ia sudah menjadi nelayan selama 15 tahun.",
          "",
          "KESIMPULAN: Menjadi nelayan adalah pekerjaan mulia. Mereka bangun pagi dan bekerja keras untuk menangkap ikan. Kita harus menghargai jasa nelayan dengan tidak membuang sampah di laut.",
          "",
          "Tips: Gunakan bahasa yang jelas dan mudah dipahami saat menulis laporan!",
        ],
        catatan: "Laporan wawancara bisa ditulis dalam bentuk narasi (cerita) atau bentuk tanya jawab. Keduanya sama baiknya.",
      },
    ],
    rangkuman: [
      "[Ilustrasi: Peta pikiran 'WAWANCARA' di tengah. Cabang: PENGERTIAN (tanya jawab), PELAKU (pewawancara + narasumber), PERSIAPAN (topik, daftar pertanyaan 5W+1H), LAPORAN (judul, identitas, isi, kesimpulan). Gaya mind map anak-anak.]",
      "Wawancara adalah kegiatan tanya jawab antara pewawancara dan narasumber untuk mendapatkan informasi.",
      "Pewawancara adalah yang bertanya, narasumber adalah yang menjawab/memberi informasi.",
      "Pertanyaan wawancara yang baik menggunakan 5W+1H (Apa, Siapa, Kapan, Di mana, Mengapa, Bagaimana).",
      "Laporan wawancara berisi: judul, identitas, isi wawancara, dan kesimpulan.",
    ],
  },
  latihan: makeSoal([
    ["Wawancara adalah kegiatan...", ["Bertanya pada diri sendiri", "Tanya jawab dengan narasumber", "Berbicara di depan umum", "Menulis cerita"], 1, "Wawancara adalah tanya jawab dengan narasumber."],
    ["Orang yang memberi informasi dalam wawancara disebut...", ["Pewawancara", "Narasumber", "Moderator", "Penyiar"], 1, "Narasumber adalah orang yang memberi informasi."],
    ["Tujuan wawancara yang benar adalah...", ["Bersenang-senang", "Mendapatkan informasi akurat", "Berdebat", "Menghibur"], 1, "Tujuan wawancara adalah mendapat informasi akurat."],
    ["Pertanyaan yang baik menggunakan rumus...", ["ABC", "5W+1H", "ABCD", "1+1=2"], 1, "Pertanyaan baik menggunakan 5W+1H (Apa, Siapa, Kapan, Di mana, Mengapa, Bagaimana)."],
    ["Berikut adalah contoh pertanyaan 5W+1H, KECUALI...", ["'Apa yang kamu lakukan?'", "'Ya atau tidak?'", "'Mengapa kamu suka?'", "'Bagaimana caranya?'"], 1, "'Ya atau tidak?' bukan pertanyaan 5W+1H yang baik."],
    ["Bagian laporan wawancara yang berisi identitas narasumber adalah...", ["Judul", "Identitas", "Isi", "Kesimpulan"], 1, "Identitas berisi nama pewawancara, narasumber, tanggal, dan tempat."],
    ["Saat mewawancarai seseorang, kita harus bersikap...", ["Sombong", "Sopan dan ramah", "Acuh", "Marah"], 1, "Sopan dan ramah adalah sikap yang baik saat wawancara."],
    ["Pertanyaan 'Apakah kamu suka membaca?' kurang baik karena...", ["Terlalu panjang", "Hanya jawab ya/tidak", "Sulit dipahami", "Tidak sopan"], 1, "Pertanyaan yang hanya dijawab 'ya' atau 'tidak' menghasilkan informasi sedikit."],
    ["Laporan wawancara sebaiknya ditulis dengan bahasa...", ["Rumit", "Jelas dan mudah dipahami", "Panjang", "Asing"], 1, "Laporan ditulis dengan bahasa yang jelas dan mudah dipahami."],
    ["Kesimpulan dalam laporan wawancara berisi...", ["Daftar pertanyaan", "Ringkasan hasil wawancara", "Salam pembuka", "Topik baru"], 1, "Kesimpulan berisi ringkasan hasil wawancara."],
  ]),
  praktik: {
    petunjuk: "Wawancarailah salah satu teman atau anggota keluargamu tentang hobi mereka! Buatlah laporan wawancara lengkap dengan judul, identitas, isi, dan kesimpulan!",
    tips: [
      "Tentukan dulu topik wawancara, misalnya 'Hobi Membaca'",
      "Siapkan 5-7 pertanyaan menggunakan 5W+1H",
      "Catat jawaban narasumber dengan rapi",
      "Tulis laporan segera setelah wawancara selesai, jangan ditunda",
    ],
    contoh: "JUDUL: Laporan Wawancara tentang Hobi Memasak. IDENTITAS: Pewawancara: Nuri. Narasumber: Ibu Sari (tetangga). Tanggal: 12 April 2026. Tempat: Rumah Ibu Sari. ISI: Ibu Sari memiliki hobi memasak sejak kecil. Ia belajar memasak dari neneknya. Menu favorit yang sering dimasak adalah rendang dan soto. Menurut Ibu Sari, memasak adalah kegiatan yang menyenangkan dan membuat keluarga bahagia. Ia biasa memasak setiap hari sepulang kerja. KESIMPULAN: Memasak adalah hobi yang bermanfaat karena bisa membuat orang lain senang.",
  },
  kuis: makeSoal([
    ["Narasumber adalah...", ["Orang yang bertanya", "Orang yang memberi informasi", "Pencatat jawaban", "Pembuat laporan"], 1, "Narasumber memberi informasi."],
    ["5W+1H digunakan untuk...", ["Menulis cerita", "Menyusun pertanyaan", "Menggambar", "Bernyanyi"], 1, "5W+1H digunakan untuk menyusun pertanyaan wawancara."],
    ["Berikut yang termasuk pertanyaan menggunakan 'Mengapa' adalah...", ["'Di mana kamu tinggal?'", "'Mengapa kamu suka membaca?'", "'Kapan kamu lahir?'", "'Siapa namamu?'"], 1, "'Mengapa' adalah salah satu kata tanya 5W+1H."],
    ["Sikap yang harus dimiliki pewawancara adalah...", ["Pemarah", "Sopan dan sabar", "Pemalu", "Banyak bicara"], 1, "Pewawancara harus sopan dan sabar."],
    ["Bagian laporan yang berisi ringkasan adalah...", ["Judul", "Isi", "Kesimpulan", "Identitas"], 2, "Kesimpulan adalah ringkasan hasil wawancara."],
    ["Pertanyaan 'Apa hobi kamu?' termasuk jenis pertanyaan...", ["Tertutup (ya/tidak)", "Terbuka (5W+1H)", "Larangan", "Perintah"], 1, "'Apa' termasuk 5W+1H, membuat narasumber bercerita."],
    ["Laporan wawancara ditulis setelah...", ["Sebelum wawancara", "Sesudah wawancara", "Saat wawancara berlangsung", "Seminggu kemudian"], 1, "Laporan ditulis setelah wawancara selesai."],
    ["Tempat dan tanggal wawancara dicantumkan di bagian...", ["Judul", "Identitas", "Isi", "Kesimpulan"], 1, "Identitas berisi tempat dan tanggal wawancara."],
    ["Berikut adalah tujuan wawancara, KECUALI...", ["Mendapat informasi", "Mencari teman", "Mengumpulkan data", "Mengetahui pendapat"], 1, "Wawancara bertujuan mendapat informasi, bukan mencari teman."],
    ["Sebelum wawancara, pewawancara sebaiknya...", ["Langsung bertanya", "Menyiapkan daftar pertanyaan", "Pulang", "Tidur"], 1, "Persiapan daftar pertanyaan penting sebelum wawancara."],
  ]),
}
export default konten
