import type { Konten } from "../types"
import { makeSoal } from "../types"

const konten: Konten = {
  belajar: {
    tujuan: [
      "Memahami pengertian dan ciri teks eksplanasi",
      "Mengetahui struktur teks eksplanasi",
      "Mengidentifikasi kebahasaan dalam teks eksplanasi",
    ],
    materi: [
      {
        judul: "Apa Itu Teks Eksplanasi?",
        isi: [
          "Pernahkah kamu bertanya-tanya mengapa hujan turun? Atau bagaimana pelangi terbentuk? Jawaban dari pertanyaan-pertanyaan itu bisa ditemukan dalam teks eksplanasi!",
          "",
          "✓ Teks eksplanasi adalah teks yang menjelaskan proses terjadinya suatu fenomena, baik fenomena alam maupun sosial.",
          "",
          "Ciri-ciri teks eksplanasi:",
          "1. Menjelaskan 'mengapa' dan 'bagaimana' suatu peristiwa terjadi.",
          "2. Berisi fakta-fakta ilmiah (bukan opini atau karangan).",
          "3. Bersifat informatif dan objektif.",
          "4. Menggunakan istilah-istilah ilmiah yang sesuai.",
          "",
          "Contoh fenomena yang bisa dijelaskan: hujan, banjir, gempa bumi, fotosintesis, sistem tata surya, dan proses terjadinya angin.",
          "",
          "[Ilustrasi: Bumi dengan berbagai fenomena alam di sekelilingnya — hujan dari awan, pelangi, gunung berapi meletus, dan matahari bersinar. Panah-panah menjelaskan proses. Gaya infografis sains anak-anak.]",
        ],
        contoh: [
          "Bandingkan teks eksplanasi dengan teks lain:",
          "",
          "✓ EKSPLANASI: 'Hujan terjadi karena air laut menguap menjadi awan. Awan kemudian naik ke atmosfer yang lebih dingin, mengembun menjadi titik air, lalu jatuh sebagai hujan.'",
          "  — Menjelaskan proses secara ilmiah.",
          "",
          "✗ NARASI: 'Kemarin hujan turun sangat deras. Aku bermain hujan-hujanan bersama adik.'",
          "  — Hanya menceritakan pengalaman, bukan menjelaskan proses.",
        ],
        catatan: "Teks eksplanasi berbeda dengan teks deskripsi. Eksplanasi menjelaskan proses (bagaimana sesuatu terjadi), deskripsi menggambarkan sesuatu (seperti apa bentuknya).",
      },
      {
        judul: "Struktur Teks Eksplanasi",
        isi: [
          "Teks eksplanasi memiliki struktur yang khas. Ada tiga bagian utama:",
          "",
          "1. PERNYATAAN UMUM — berisi gambaran umum tentang fenomena yang akan dijelaskan. Bagian ini menjawab pertanyaan 'Apa yang akan dijelaskan?'",
          "  Contoh: 'Hujan adalah peristiwa turunnya air dari atmosfer ke permukaan bumi.'",
          "",
          "2. DERETAN PENJELAS — berisi penjelasan detail tentang proses terjadinya fenomena. Bagian ini menjawab pertanyaan 'Bagaimana prosesnya?'",
          "  Contoh: 'Air laut menguap karena panas matahari. Uap air naik ke langit dan berkumpul menjadi awan...'",
          "",
          "3. INTERPRETASI — berisi kesimpulan atau penutup. Bisa juga berisi dampak atau manfaat dari fenomena tersebut.",
          "  Contoh: 'Hujan sangat penting bagi kehidupan. Tanpa hujan, tumbuhan tidak bisa tumbuh.'",
          "",
          "[Ilustrasi: Diagram piramida tiga tingkat. Tingkat 1: 'Pernyataan Umum' — ikon tanda tanya. Tingkat 2: 'Deretan Penjelas' — ikon panah proses 1→2→3. Tingkat 3: 'Interpretasi' — ikon bintang kesimpulan. Gaya diagram belajar sederhana.]",
        ],
        contoh: [
          "Analisis struktur teks eksplanasi 'Proses Terjadinya Pelangi':",
          "",
          "PERNYATAAN UMUM: Pelangi adalah fenomena optik yang terjadi ketika sinar matahari dibiaskan oleh tetesan air hujan.",
          "",
          "DERETAN PENJELAS: Sinar matahari masuk ke dalam tetesan air hujan. Di dalam tetesan air, sinar itu dibelokkan (dibiaskan) dan terurai menjadi tujuh warna: merah, jingga, kuning, hijau, biru, nila, ungu. Sinar warna-warni itu lalu dipantulkan keluar dan membentuk busur pelangi.",
          "",
          "INTERPRETASI: Pelangi adalah salah satu keindahan alam yang menunjukkan bahwa cahaya putih terdiri dari berbagai warna.",
        ],
      },
      {
        judul: "Kebahasaan Eksplanasi",
        isi: [
          "Teks eksplanasi menggunakan beberapa ciri kebahasaan khusus:",
          "",
          "1. Kata kerja kausal — kata yang menunjukkan hubungan sebab-akibat.",
          "  Contoh: menyebabkan, mengakibatkan, disebabkan oleh, karena, sehingga.",
          "  'Panas matahari menyebabkan air laut menguap.'",
          "",
          "2. Konjungsi waktu — kata penghubung yang menunjukkan urutan waktu.",
          "  Contoh: kemudian, setelah itu, lalu, selanjutnya, akhirnya.",
          "  'Air menguap, kemudian naik ke langit, lalu berkumpul menjadi awan.'",
          "",
          "3. Istilah ilmiah — kata-kata khusus yang berkaitan dengan fenomena yang dibahas.",
          "  Contoh: evaporasi (penguapan), kondensasi (pengembunan), gravitasi, fotosintesis.",
          "",
          "4. Kata kerja pasif — sering digunakan untuk menjelaskan proses.",
          "  Contoh: dilepaskan, dihasilkan, dipanaskan, dibiaskan, terbentuk.",
          "",
          "[Ilustrasi: Papan tulis dengan empat kotak kategori. Kotak 1 'Sebab-Akibat' — ikon panah sebab→akibat. Kotak 2 'Kata Waktu' — ikon jam. Kotak 3 'Istilah Ilmiah' — ikon buku. Kotak 4 'Kata Pasif' — ikon tanda terima. Gaya papan tulis sekolah.]",
        ],
        contoh: [
          "Bandingkan kalimat tanpa dan dengan ciri kebahasaan eksplanasi:",
          "",
          "✗ TANPA: 'Air laut panas. Air naik. Jadi awan.'",
          "  — Terlalu sederhana, tidak jelas hubungannya.",
          "",
          "✓ DENGAN: 'Air laut dipanaskan oleh sinar matahari, sehingga menguap. Uap air kemudian naik ke atmosfer dan akhirnya berkumpul menjadi awan.'",
          "  — Jelas hubungan sebab-akibat dan urutan waktu.",
        ],
      },
    ],
    rangkuman: [
      "[Ilustrasi: Buku catatan terbuka dengan judul 'Eksplanasi' dan tiga tab: Pengertian, Struktur, Kebahasaan. Ada gambar proses hujan dari laut ke awan ke hujan. Gaya catatan belajar.]",
      "Teks eksplanasi: teks yang menjelaskan proses terjadinya fenomena alam atau sosial secara ilmiah.",
      "Struktur: pernyataan umum → deretan penjelas → interpretasi.",
      "Ciri kebahasaan: kata kerja kausal (sebab-akibat), konjungsi waktu, istilah ilmiah, kata kerja pasif.",
      "Teks eksplanasi bersifat informatif, faktual, dan objektif.",
    ],
  },
  latihan: makeSoal([
    ["Teks eksplanasi adalah teks yang...", ["Menghibur pembaca", "Menjelaskan proses terjadinya fenomena", "Menceritakan kisah fiksi", "Mendeskripsikan benda"], 1, "Eksplanasi menjelaskan proses terjadinya fenomena alam/sosial."],
    ["Struktur teks eksplanasi yang benar adalah...", ["Orientasi-komplikasi-resolusi", "Pernyataan umum-deretan penjelas-interpretasi", "Pembuka-isi-penutup", "Tujuan-bahan-langkah"], 1, "Struktur eksplanasi: pernyataan umum, deretan penjelas, interpretasi."],
    ["'Hujan terjadi karena...' — kata 'karena' menunjukkan hubungan...", ["Waktu", "Sebab-akibat", "Tempat", "Cara"], 1, "'Karena' adalah konjungsi sebab-akibat (kausal)."],
    ["Bagian yang berisi kesimpulan atau penutup disebut...", ["Pernyataan umum", "Interpretasi", "Deretan penjelas", "Orientasi"], 1, "Interpretasi adalah bagian kesimpulan/penutup."],
    ["Contoh istilah ilmiah dalam teks eksplanasi adalah...", ["Rumah", "Evaporasi", "Meja", "Buku"], 1, "Evaporasi adalah istilah ilmiah untuk penguapan."],
    ["Teks eksplanasi bersifat...", ["Subjektif", "Faktual dan objektif", "Fiktif", "Imajinatif"], 1, "Eksplanasi berisi fakta ilmiah yang objektif."],
    ["'Air menguap, kemudian naik ke langit.' — kata 'kemudian' termasuk...", ["Konjungsi waktu", "Konjungsi sebab", "Konjungsi tujuan", "Konjungsi cara"], 0, "'Kemudian' adalah konjungsi yang menunjukkan urutan waktu."],
    ["Yang BUKAN contoh fenomena untuk teks eksplanasi adalah...", ["Proses terjadinya hujan", "Cara membuat layang-layang", "Proses fotosintesis", "Terjadinya gempa bumi"], 1, "Cara membuat layang-layang adalah teks prosedur, bukan eksplanasi."],
    ["Bagian 'deretan penjelas' berisi...", ["Gambaran umum", "Penjelasan detail proses", "Kesimpulan", "Judul"], 1, "Deretan penjelas berisi penjelasan proses secara detail."],
    ["Kata 'disebabkan oleh' termasuk kata...", ["Benda", "Kausal (sebab-akibat)", "Sifat", "Bilangan"], 1, "'Disebabkan oleh' menunjukkan hubungan sebab-akibat."],
  ]),
  praktik: {
    petunjuk: "Buatlah teks eksplanasi sederhana tentang 'Proses Terjadinya Angin'! Gunakan struktur lengkap: pernyataan umum, deretan penjelas, dan interpretasi. Sertakan kata kausal dan konjungsi waktu.",
    tips: [
      "Mulailah dengan pernyataan umum tentang apa itu angin",
      "Jelaskan prosesnya secara urut: dari panas matahari hingga udara bergerak",
      "Gunakan kata karena, sehingga, akibatnya, kemudian, lalu",
      "Akhiri dengan manfaat angin bagi kehidupan",
      "Gambar ilustrasi sederhana bisa membantu penjelasan",
    ],
    contoh: "PERNYATAAN UMUM: Angin adalah udara yang bergerak dari tempat bertekanan tinggi ke tempat bertekanan rendah. DERETAN PENJELAS: Matahari memanaskan permukaan bumi. Udara di tempat yang panas menjadi lebih ringan dan naik. Tempat itu menjadi bertekanan rendah. Udara dari tempat lain yang lebih dingin (tekanan tinggi) bergerak mengisi tempat kosong itulah yang kita rasakan sebagai angin. INTERPRETASI: Angin bermanfaat untuk mengeringkan pakaian, menggerakkan kincir angin, dan membantu penyerbukan tanaman.",
  },
  kuis: makeSoal([
    ["Tujuan teks eksplanasi adalah...", ["Menghibur", "Menjelaskan proses terjadinya sesuatu", "Menceritakan dongeng", "Membuat sesuatu"], 1, "Tujuan eksplanasi adalah menjelaskan proses secara ilmiah."],
    ["Bagian pengantar yang memperkenalkan fenomena disebut...", ["Interpretasi", "Pernyataan umum", "Deretan penjelas", "Kesimpulan"], 1, "Pernyataan umum adalah gambaran awal tentang fenomena."],
    ["Konjungsi yang tepat untuk hubungan sebab-akibat adalah...", ["Kemudian", "Karena", "Lalu", "Selanjutnya"], 1, "'Karena' menunjukkan hubungan sebab-akibat."],
    ["'Sinar matahari dibiaskan oleh tetesan air.' — kata 'dibiaskan' adalah kata...", ["Aktif", "Pasif", "Perintah", "Tanya"], 1, "'Dibiaskan' adalah kata kerja pasif (berawalan di-)."],
    ["Mana yang termasuk istilah ilmiah?", ["Meja hijau", "Fotosintesis", "Pintu kayu", "Buku tulis"], 1, "Fotosintesis adalah istilah ilmiah dalam biologi."],
    ["Interpretasi terletak di bagian...", ["Awal", "Akhir", "Tengah", "Sebelum pernyataan umum"], 1, "Interpretasi adalah bagian akhir/penutup teks eksplanasi."],
    ["Teks eksplanasi tentang pelangi termasuk fenomena...", ["Sosial", "Alam", "Ekonomi", "Budaya"], 1, "Pelangi adalah fenomena alam (optik)."],
    ["'Setelah menguap, air naik ke langit.' — kata 'setelah' menunjukkan...", ["Sebab", "Waktu", "Tempat", "Akibat"], 1, "'Setelah' menunjukkan hubungan waktu."],
    ["Kata 'menyebabkan' termasuk jenis kata...", ["Sifat", "Kerja kausal", "Benda", "Bilangan"], 1, "'Menyebabkan' adalah kata kerja yang menunjukkan hubungan sebab-akibat."],
    ["Ciri utama teks eksplanasi adalah...", ["Subjektif dan imajinatif", "Berdasarkan fakta dan ilmiah", "Berisi dialog tokoh", "Menggunakan rima"], 1, "Eksplanasi berdasarkan fakta ilmiah, bukan opini atau imajinasi."],
  ]),
}
export default konten
