import type { Konten } from "../types"
import { makeSoal } from "../types"

const konten: Konten = {
  belajar: {
    tujuan: [
      "Memahami pengertian dan ciri-ciri cerpen",
      "Mengenal unsur intrinsik cerpen",
      "Menulis cerpen sederhana berdasarkan pengalaman",
    ],
    materi: [
      {
        judul: "Apa Itu Cerpen?",
        isi: [
          "Siapa yang suka membaca cerita pendek? Cerita-cerita pendek yang sering kamu baca itu disebut cerpen!",
          "",
          "✓ Cerpen adalah singkatan dari cerita pendek. Cerpen adalah karangan fiksi yang menceritakan satu peristiwa penting dalam kehidupan tokoh secara singkat.",
          "",
          "Ciri-ciri cerpen:",
          "1. Ceritanya pendek — bisa dibaca sekali duduk (15-30 menit).",
          "2. Fokus pada satu peristiwa atau konflik utama.",
          "3. Jumlah tokoh terbatas (biasanya 2-5 tokoh).",
          "4. Alurnya sederhana dan mudah diikuti.",
          "5. Memberikan pesan moral kepada pembaca.",
          "",
          "Cerpen berbeda dengan novel. Novel lebih panjang, punya banyak tokoh, dan alurnya lebih kompleks.",
          "",
          "[Ilustrasi: Sebuah buku kecil terbuka dengan halaman-halaman pendek. Di halaman terlihat gambar tokoh-tokoh sederhana: anak laki-laki, kakek, dan seekor kucing. Dari buku keluar gelembung cerita. Gaya ilustrasi buku bacaan anak.]",
        ],
        contoh: [
          "Bandingkan cerpen dan novel:",
          "",
          "✓ CERPEN: 'Kancil dan Buaya' — singkat, satu konflik, 3 tokoh.",
          "  — Bisa dibaca sekali duduk.",
          "",
          "✗ NOVEL: 'Laskar Pelangi' — panjang, banyak konflik, banyak tokoh.",
          "  — Butuh waktu berhari-hari untuk membaca.",
        ],
        catatan: "Cerpen berbeda dengan dongeng. Dongeng biasanya bersifat tradisional dan ada unsur magis, sedangkan cerpen bisa tentang kehidupan sehari-hari yang realistis.",
      },
      {
        judul: "Unsur Intrinsik Cerpen",
        isi: [
          "Setiap cerpen memiliki unsur-unsur yang membangunnya dari dalam. Ini disebut unsur intrinsik.",
          "",
          "1. TEMA — gagasan utama cerita. Apa yang ingin disampaikan penulis?",
          "  Contoh tema: persahabatan, kejujuran, keberanian, kasih sayang keluarga.",
          "",
          "2. TOKOH — orang yang terlibat dalam cerita.",
          "  • Tokoh utama: tokoh yang paling sering muncul (contoh: Kancil).",
          "  • Tokoh pembantu: tokoh pendukung (contoh: Buaya, Kera).",
          "  • Tokoh protagonis: tokoh baik (contoh: Kancil).",
          "  • Tokoh antagonis: tokoh jahat/lawan (contoh: Buaya).",
          "",
          "3. ALUR — urutan peristiwa dalam cerita.",
          "  Alur maju: dari awal ke akhir berurutan.",
          "  Alur mundur: ada kilas balik ke masa lalu.",
          "",
          "4. LATAR — tempat, waktu, dan suasana cerita.",
          "  Contoh: 'Di tepi sungai, pada siang hari yang terik.'",
          "",
          "5. AMANAT — pesan moral yang ingin disampaikan penulis.",
          "  Contoh: 'Kecerdikan lebih berharga daripada kekuatan fisik.'",
          "",
          "[Ilustrasi: Lingkaran dengan 5 bagian seperti potongan pizza. Masing-masing berisi ikon: lampu (tema), orang (tokoh), panah (alur), rumah (latar), bintang (amanat). Di tengah tulisan 'Unsur Intrinsik Cerpen'. Gaya diagram lingkaran warna-warni.]",
        ],
        contoh: [
          "Analisis unsur intrinsik cerpen 'Kancil dan Buaya':",
          "",
          "TEMA: Kecerdikan mengatasi masalah.",
          "TOKOH: Kancil (protagonis, cerdik), Buaya (antagonis, mudah ditipu).",
          "ALUR: Alur maju — Kancil ingin ke seberang → bertemu buaya → menipu buaya → berhasil menyeberang.",
          "LATAR: Sungai, siang hari.",
          "AMANAT: Dengan kecerdikan, masalah berat bisa diselesaikan.",
        ],
      },
      {
        judul: "Menulis Cerpen Sederhana",
        isi: [
          "Sekarang, saatnya kamu menjadi penulis cerpen! Berikut langkah-langkahnya:",
          "",
          "1. Tentukan tema — apa yang ingin kamu ceritakan? Pilih tema yang kamu kuasai.",
          "  Contoh tema: pengalaman lucu, persahabatan, liburan.",
          "",
          "2. Tentukan tokoh — siapa saja tokohnya? Beri nama dan sifat yang jelas.",
          "  Contoh: Rina (baik hati, suka menolong), Dodi (ceria, lucu).",
          "",
          "3. Buat alur — susun cerita dari awal, tengah, hingga akhir.",
          "  Awal: perkenalan tokoh dan latar.",
          "  Tengah: muncul masalah atau konflik.",
          "  Akhir: masalah selesai, ada pesan moral.",
          "",
          "4. Tulis dengan bahasa yang menarik — gunakan dialog dan deskripsi.",
          "  Contoh: 'Halo, Rina! Hari ini aku membawa bekal istimewa!' seru Dodi riang.",
          "",
          "5. Beri judul yang menarik — judul membuat orang ingin membaca.",
          "",
          "[Ilustrasi: Meja belajar dengan buku catatan terbuka, pensil, dan penghapus. Di buku catatan sudah ada tulisan judul 'Petualangan di Taman Kota'. Beberapa kata digarisbawahi. Tersedia gambar tokoh-tokoh kecil di pinggir halaman. Gaya meja penulis cilik.]",
        ],
        contoh: [
          "Contoh cerpen pendek 'Kue Cokelat Ibu':",
          "",
          "Rina pulang sekolah dengan hati gembira. Hari ini ia mendapat nilai bagus. Ia ingin memberi kejutan untuk Ibu.",
          "",
          "Rina mengambil resep kue cokelat simpanan Ibu. Diam-diam ia mulai membuat kue di dapur. Telur pecah, tepung tumpah, tapi Rina terus mencoba.",
          "",
          "'Rina, sedang apa kamu?' Ibu terkejut melihat dapur berantakan. 'Aku buat kue untuk Ibu!' Rina tersenyum lebar.",
          "",
          "Ibu tersentuh. Meskipun kuenya tidak sempurna, rasa cinta Rina membuatnya istimewa. Mereka memanggang kue bersama-sama.",
        ],
      },
    ],
    rangkuman: [
      "[Ilustrasi: Buku catatan dengan tab 'CERPEN' di samping. Isi catatan: pengertian cerpen, bagan unsur intrinsik (lingkaran 5 bagian), dan langkah menulis (1-2-3-4-5). Ada gambar pena dan buku kecil. Gaya catatan pelajaran.]",
      "Cerpen: cerita fiksi pendek yang bisa dibaca sekali duduk, fokus pada satu konflik.",
      "Unsur intrinsik: tema, tokoh, alur, latar, dan amanat.",
      "Alur cerpen: orientasi (awal) → komplikasi (masalah) → resolusi (penyelesaian).",
      "Tips menulis: tentukan tema, tokoh, alur, tulis dengan bahasa menarik, beri judul.",
    ],
  },
  latihan: makeSoal([
    ["Cerpen adalah singkatan dari...", ["Cerita panjang", "Cerita pendek", "Cerita bersambung", "Cerita bergambar"], 1, "Cerpen = cerita pendek, karangan fiksi singkat."],
    ["Jumlah tokoh dalam cerpen biasanya...", ["Banyak sekali", "Terbatas (2-5 tokoh)", "Tidak ada tokoh", "Ratusan"], 1, "Cerpen memiliki tokoh yang terbatas."],
    ["Bagian cerita yang memperkenalkan tokoh dan latar disebut...", ["Komplikasi", "Orientasi", "Resolusi", "Amanat"], 1, "Orientasi adalah bagian pengenalan."],
    ["Tokoh yang berwatak baik disebut...", ["Antagonis", "Protagonis", "Figuran", "Pembantu"], 1, "Protagonis adalah tokoh baik/utama."],
    ["'Di sebuah desa kecil, hiduplah seorang nenek...' — ini menunjukkan unsur...", ["Tema", "Latar", "Tokoh", "Amanat"], 1, "'Di sebuah desa' adalah latar tempat."],
    ["Pesan yang ingin disampaikan penulis disebut...", ["Tema", "Amanat", "Alur", "Latar"], 1, "Amanat adalah pesan moral dari cerita."],
    ["Yang BUKAN ciri cerpen adalah...", ["Cerita pendek", "Alur kompleks dan panjang", "Fokus satu konflik", "Tokoh terbatas"], 1, "Cerpen memiliki alur sederhana, bukan kompleks dan panjang."],
    ["Urutan peristiwa dalam cerita disebut...", ["Tema", "Alur", "Latar", "Tokoh"], 1, "Alur adalah urutan peristiwa dari awal hingga akhir."],
    ["Contoh tema cerpen yang tepat adalah...", ["Cara membuat nasi goreng", "Persahabatan sejati", "Rumus matematika", "Iklan sabun"], 1, "'Persahabatan sejati' adalah tema cerita yang tepat."],
    ["Cerpen termasuk jenis karangan...", ["Nonfiksi", "Fiksi", "Laporan", "Ilmiah"], 1, "Cerpen adalah karangan fiksi (rekaan/imajinasi)."],
  ]),
  praktik: {
    petunjuk: "Tulislah sebuah cerpen pendek 3-4 paragraf tentang 'Pengalaman Berkesanku'! Sertakan unsur intrinsik: tema, tokoh, alur, latar, dan amanat. Gunakan dialog untuk membuat cerita lebih hidup.",
    tips: [
      "Pilih pengalaman nyata yang paling kamu ingat",
      "Tentukan tokoh utama (bisa dirimu sendiri)",
      "Ceritakan secara urut: awal, tengah, akhir",
      "Gunakan dialog untuk menghidupkan cerita",
      "Akhiri dengan pesan moral dari pengalaman itu",
    ],
    contoh: "TEMA: Keberanian mengatasi rasa takut. TOKOH: Diriku (berani), Ayah (penyemangat). LATAR: Taman bermain, Minggu pagi. ALUR: Awal - Ajakanku ke taman bermain. Tengah - Aku takut naik flying fox. Akhir - Ayah menyemangati, aku berhasil. AMANAT: Berani mencoba hal baru akan menyenangkan.",
  },
  kuis: makeSoal([
    ["Berapa kali membaca cerpen yang ideal?", ["Berhari-hari", "Sekali duduk", "Sejam sekali", "Sepekan"], 1, "Cerpen dirancang untuk dibaca sekali duduk."],
    ["Antagonis adalah tokoh yang berwatak...", ["Baik", "Jahat/lawan", "Lucu", "Bijak"], 1, "Antagonis adalah tokoh jahat atau lawan protagonis."],
    ["'Rina tersenyum lebar.' — kalimat ini menunjukkan...", ["Dialog", "Deskripsi", "Amanat", "Tema"], 1, "Ini adalah deskripsi tentang ekspresi tokoh."],
    ["Bagian di mana masalah mulai muncul disebut...", ["Orientasi", "Komplikasi", "Resolusi", "Penutup"], 1, "Komplikasi adalah bagian munculnya konflik."],
    ["Latar dalam cerita mencakup...", ["Tema dan amanat", "Tempat, waktu, suasana", "Tokoh dan alur", "Judul dan pengarang"], 1, "Latar mencakup tempat, waktu, dan suasana."],
    ["Mana yang termasuk tokoh pembantu?", ["Tokoh utama", "Teman tokoh utama", "Penulis", "Pembaca"], 1, "Tokoh pembantu adalah pendukung tokoh utama."],
    ["Cerpen 'Kancil dan Buaya' bertema...", ["Persahabatan", "Kecerdikan", "Kekuatan", "Kekayaan"], 0, "Cerita Kancil dan Buaya bertema kecerdikan mengatasi masalah."],
    ["Yang dimaksud 'alur mundur' adalah...", ["Cerita dari awal ke akhir", "Ada kilas balik ke masa lalu", "Cerita berputar", "Tidak ada urutan"], 1, "Alur mundur menggunakan kilas balik (flashback)."],
    ["Fungsi dialog dalam cerpen adalah...", ["Menambah tebal buku", "Menghidupkan cerita", "Membingungkan", "Memperpanjang"], 1, "Dialog membuat cerita lebih hidup dan alami."],
    ["Judul cerpen yang baik harus...", ["Panjang dan rumit", "Menarik dan sesuai isi", "Mengandung rumus", "Berbahasa asing"], 1, "Judul harus menarik dan relevan dengan isi cerita."],
  ]),
}
export default konten
