import type { Konten } from "../types"
import { makeSoal } from "../types"

const konten: Konten = {
  belajar: {
    tujuan: [
      "Memahami pengertian dan ciri-ciri pantun",
      "Membedakan jenis-jenis pantun",
      "Mengidentifikasi nilai moral dalam pantun",
    ],
    materi: [
      {
        judul: "Mengenal Pantun",
        isi: [
          "Pantun adalah salah satu bentuk puisi lama yang sangat terkenal di Indonesia. Pantun berasal dari tradisi Melayu dan telah ada sejak ratusan tahun yang lalu.",
          "",
          "Ciri-ciri pantun:",
          "",
          "1. Setiap bait terdiri dari 4 baris.",
          "2. Baris 1 dan 2 adalah sampiran (pembuka).",
          "3. Baris 3 dan 4 adalah isi (pesan utama).",
          "4. Bersajak a-b-a-b (baris 1 sama dengan baris 3, baris 2 sama dengan baris 4).",
          "5. Setiap baris terdiri dari 8-12 suku kata.",
          "",
          "Contoh pantun:",
          "'Kalau ada jarum yang patah, (a)'",
          "'Jangan simpan di dalam peti. (b)'",
          "'Kalau ada kata yang salah, (a)'",
          "'Jangan simpan di dalam hati. (b)'",
          "",
          "Lihatlah! Baris 1 berakhiran 'patah' dan baris 3 berakhiran 'salah' (a-a). Baris 2 berakhiran 'peti' dan baris 4 berakhiran 'hati' (b-b). Inilah yang disebut sajak a-b-a-b.",
          "",
          "[Ilustrasi: Empat baris pantun ditulis dalam papan tulis. Baris 1 dan 3 diberi lingkaran merah (sajak a). Baris 2 dan 4 diberi lingkaran biru (sajak b). Ada label 'SAMPIRAN' di baris 1-2, 'ISI' di baris 3-4. Gaya papan tulis kelas.]",
        ],
        contoh: [
          "Contoh pantun dengan sajak a-b-a-b:",
          "",
          "✓ PANTUN BENAR (a-b-a-b):",
          "'Pergi ke pasar membeli mangga' (a)",
          "'Jangan lupa membeli duku' (b)",
          "'Rajin belajar sepanjang masa' (a)",
          "'Agar kelak jadi anak bermutu' (b)",
          "  — Baris 1 dan 3 sama bunyi akhir 'ga', baris 2 dan 4 sama bunyi akhir 'ku'.",
          "",
          "✗ BUKAN PANTUN (sajaknya a-a-b-b atau a-b-b-a):",
          "'Pergi ke pasar membeli mangga' (a)",
          "'Mangga dibeli di waktu pagi' (a)",
          "'Rajin belajar sepanjang masa' (b)",
          "'Agar kelak jadi anak bermutu' (b)",
          "  — Sajaknya a-a-b-b, bukan a-b-a-b. Jadi bukan pantun yang benar.",
        ],
        catatan: "Baris sampiran (1-2) biasanya tidak berhubungan langsung dengan isi (3-4). Namun kadang sampiran bisa juga mengandung makna yang mendukung isi.",
      },
      {
        judul: "Jenis-Jenis Pantun",
        isi: [
          "Pantun memiliki beberapa jenis berdasarkan isinya:",
          "",
          "1. PANTUN NASIHAT — berisi pesan moral, nasihat, atau ajaran tentang kebaikan.",
          "  'Rajin pangkal menjadi pandai,'",
          "  'Hemat membuat hidup kaya.'",
          "  'Cita-cita janganlah lalai,'",
          "  'Belajar pantang menyerah dan lelah.'",
          "",
          "2. PANTUN JENAKA — berisi humor atau lelucon yang menghibur.",
          "  'Ada kambing memakan kacang,'",
          "  'Kacang dimakan sampai habis.'",
          "  'Ada teman tertawa terpingkal-pingkal,'",
          "  'Rupanya gigi palsu ikut menari menari.'",
          "",
          "3. PANTUN TEKA-TEKI — berisi tebakan yang mengajak pembaca berpikir.",
          "  'Kalau tuan pergi ke Kediri,'",
          "  'Jangan lupa beli sukun.'",
          "  'Kalau tuan bijak bestari,'",
          "  'Hewan apa jago memikul beban?'",
          "  — Jawaban: 'Kuda' atau 'Keledai'",
          "",
          "[Ilustrasi: Tiga kotak berisi jenis pantun. Kotak 1: 'PANTUN NASIHAT' dengan ikon buku dan lampu. Kotak 2: 'PANTUN JENAKA' dengan ikon wajah tertawa. Kotak 3: 'PANTUN TEKA-TEKI' dengan ikon tanda tanya. Gaya diagram anak-anak.]",
        ],
        contoh: [
          "Bandingkan jenis pantun berdasarkan isinya:",
          "",
          "✓ PANTUN NASIHAT: 'Buah duren buah kedondong, jangan dimakan di atas bale. Hai kawan sayanglah orang tua, karena mereka peduli pada kita.'",
          "  — Berisi nasihat untuk menyayangi orang tua.",
          "",
          "✓ PANTUN JENAKA: 'Naik sepeda ke kota Medan, boncengan dengan si kucing belang. Kakak tertawa setiap hari, ternyata celana kebesaran.'",
          "  — Lucu, menghibur, tentang celana kebesaran.",
          "",
          "✓ PANTUN TEKA-TEKI: 'Di dalam kolam ada ikan, memakan kangkang di waktu pagi. Coba tebak wahai teman, benda apa jika dipukul justru berdiri?'",
          "  — Jawabannya: 'Paku' atau 'Paku payung'.",
        ],
      },
      {
        judul: "Nilai dalam Pantun",
        isi: [
          "Pantun tidak hanya indah didengar, tetapi juga mengandung nilai-nilai luhur yang penting untuk kehidupan sehari-hari. Nilai-nilai itu antara lain:",
          "",
          "1. NILAI RELIGIUS — mengingatkan kita kepada Tuhan.",
          "  'Banyak bulan di atas langit,'",
          "  'Cahaya dari bulan purnama.'",
          "  'Banyak amal selama masih hidup,'",
          "  'Bekal di akhirat kelak utama.'",
          "  — Mengingatkan kita untuk berbuat baik sebagai bekal di akhirat.",
          "",
          "2. NILAI SOSIAL — tentang hubungan dengan sesama manusia.",
          "  'Pohon kelapa tinggi menjulang,'",
          "  'Daun melambai tertiup angin.'",
          "  'Hidup rukun saling sayang,'",
          "  'Hati tenang penuh kedamaian.'",
          "  — Mengajarkan kerukunan dan kasih sayang.",
          "",
          "3. NILAI MORAL — tentang baik buruknya perilaku.",
          "  'Terbang rendah burung kenari,'",
          "  'Hinggap di pucuk pohon jambu.'",
          "  'Berkata jujur pada ibu dan bapak,'",
          "  'Itulah tanda anak yang berbudi.'",
          "  — Mengajarkan kejujuran sebagai akhlak mulia.",
          "",
          "[Ilustrasi: Sebuah hati besar di tengah, dikelilingi tiga lingkaran. Lingkaran 1 'RELIGIUS' dengan ikon masjid. Lingkaran 2 'SOSIAL' dengan ikon orang bergandengan. Lingkaran 3 'MORAL' dengan ikon bintang. Gaya diagram nilai kehidupan.]",
        ],
        contoh: [
          "Analisis nilai dalam pantun:",
          "",
          "✓ PANTUN DENGAN NILAI SOSIAL:",
          "'Jalan-jalan ke kota Blitar,'",
          "'Jangan lupa membeli jamu.'",
          "'Bila hidup saling menghormati dan bekerja sama,'",
          "'Semua pekerjaan terasa mudah dan beres.'",
          "  — Nilai sosial: menghormati dan kerja sama membuat pekerjaan mudah.",
          "",
          "PENTING: Sebuah pantun bisa mengandung lebih dari satu nilai!",
        ],
        catatan: "Nilai-nilai dalam pantun membuat pantun tidak sekadar puisi biasa, tetapi juga sarana pendidikan karakter yang efektif.",
      },
    ],
    rangkuman: [
      "[Ilustrasi: Peta pikiran 'PANTUN' di tengah. Cabang: CIRI (4 baris, a-b-a-b, sampiran+isi), JENIS (nasihat, jenaka, teka-teki), NILAI (religius, sosial, moral), CONTOH (pantun dengan berbagai tema). Gaya mind map anak-anak.]",
      "Pantun adalah puisi lama yang terdiri dari 4 baris dengan sajak a-b-a-b.",
      "Baris 1-2 adalah sampiran, baris 3-4 adalah isi.",
      "Jenis pantun: nasihat (pesan moral), jenaka (humor), teka-teki (tebakan).",
      "Nilai dalam pantun: religius (ketuhanan), sosial (sesama), moral (perilaku baik).",
    ],
  },
  latihan: makeSoal([
    ["Setiap bait pantun terdiri dari... baris.", ["2", "4", "3", "5"], 1, "Satu bait pantun terdiri dari 4 baris."],
    ["Bagian yang merupakan isi pantun adalah baris...", ["1 dan 2", "3 dan 4", "1 dan 3", "2 dan 4"], 1, "Baris 3 dan 4 adalah isi pantun."],
    ["Sajak pantun yang benar adalah...", ["a-b-b-a", "a-b-a-b", "a-a-b-b", "a-b-c-b"], 1, "Pantun bersajak a-b-a-b."],
    ["Baris 1 dan 2 dalam pantun disebut...", ["Isi", "Sampiran", "Judul", "Penutup"], 1, "Baris 1 dan 2 disebut sampiran (pembuka)."],
    ["Pantun yang berisi pesan moral disebut pantun...", ["Jenaka", "Nasihat", "Teka-teki", "Cinta"], 1, "Pantun nasihat berisi pesan moral."],
    ["Pantun jenaka bertujuan...", ["Menakut-nakuti", "Menghibur", "Memberi nasihat", "Menggurui"], 1, "Pantun jenaka bertujuan menghibur."],
    ["Setiap baris pantun umumnya terdiri dari... suku kata.", ["4-6", "8-12", "14-16", "20-24"], 1, "Pantun umumnya memiliki 8-12 suku kata per baris."],
    ["Nilai yang mengajarkan hubungan dengan Tuhan disebut nilai...", ["Sosial", "Religius", "Moral", "Budaya"], 1, "Nilai religius berkaitan dengan hubungan manusia dengan Tuhan."],
    ["Nilai yang mengajarkan kejujuran termasuk nilai...", ["Religius", "Sosial", "Moral", "Estetika"], 2, "Kejujuran termasuk nilai moral tentang baik buruknya perilaku."],
    ["Pantun teka-teki biasanya diakhiri dengan...", ["Jawaban", "Pertanyaan", "Nasihat", "Lelucon"], 1, "Pantun teka-teki berisi pertanyaan yang harus ditebak."],
  ]),
  praktik: {
    petunjuk: "Buatlah 3 buah pantun dengan tema berbeda: satu pantun nasihat, satu pantun jenaka, dan satu pantun teka-teki! Perhatikan sajak a-b-a-b dan jumlah suku kata setiap baris!",
    tips: [
      "Tentukan dulu isi pantun (baris 3-4), baru buat sampiran (baris 1-2)",
      "Pastikan bunyi akhir baris 1 sama dengan baris 3 (a-a), baris 2 sama dengan baris 4 (b-b)",
      "Gunakan kata-kata sederhana yang mudah dipahami",
      "Periksa kembali: setiap baris 8-12 suku kata, hitung dengan jari",
    ],
    contoh: "PANTUN NASIHAT: 'Pergi ke ladang bersama Nenek, / Membawa bekal nasi dan sayur. / Rajin belajar janganlah malas, / Agar cita-cita kelak terkabul.' PANTUN JENAKA: 'Ada kucing naik ke atap, / Melompat-lompat seperti kanguru. / Melihat adik makan bubur di lantai, / Ternyata buburnya bukan bubur tapi batu.' PANTUN TEKA-TEKI: 'Buah semangka buah pepaya, / Dibeli di pasar tradisi. / Coba tebak wahai semua, / Benda apa yang berisi listrik tapi tak bisa menulis?' (Jawaban: Radio).",
  },
  kuis: makeSoal([
    ["Sampiran dalam pantun adalah baris...", ["3 dan 4", "1 dan 2", "2 dan 3", "4 saja"], 1, "Sampiran adalah baris 1 dan 2."],
    ["Kata 'pantun' berasal dari tradisi...", ["Jawa", "Melayu", "Sunda", "Batak"], 1, "Pantun berasal dari tradisi Melayu."],
    ["Pantun yang berisi tebakan disebut pantun...", ["Nasihat", "Jenaka", "Teka-teki", "Kias"], 2, "Pantun teka-teki berisi tebakan."],
    ["Bersajak a-b-a-b artinya...", ["Baris 1=2, baris 3=4", "Baris 1=3, baris 2=4", "Baris 1=4, baris 2=3", "Semua sama"], 1, "Sajak a-b-a-b berarti baris 1 sama dengan baris 3, baris 2 sama dengan baris 4."],
    ["Nilai sosial dalam pantun mengajarkan tentang...", ["Hubungan dengan Tuhan", "Hubungan dengan sesama", "Perilaku baik", "Keindahan"], 1, "Nilai sosial tentang hubungan dengan sesama manusia."],
    ["Berikut yang BUKAN ciri pantun adalah...", ["4 baris", "Bersajak a-b-a-b", "Sampiran selalu berhubungan dengan isi", "8-12 suku kata"], 2, "Sampiran tidak harus berhubungan langsung dengan isi."],
    ["'Rajin pangkal menjadi pandai, / Hemat membuat hidup kaya.' — Ini adalah bagian...", ["Sampiran", "Isi", "Judul", "Penutup"], 1, "Baris ini adalah isi pantun (baris 3-4)."],
    ["Pantun jenis apa yang cocok untuk menghibur teman yang sedih?", ["Pantun nasihat", "Pantun jenaka", "Pantun teka-teki", "Pantun agama"], 1, "Pantun jenaka cocok untuk menghibur."],
    ["'Jika ingin menjadi juara, / belajar keras tiap masa.' Kata 'juara' dan 'masa' bersajak...", ["a", "b", "c", "d"], 0, "'Juara' dan 'masa' sama bunyi akhir 'ra' dan 'sa'... sebenarnya tidak sama persis. Tapi dalam konteks pantun, 'ra' dan 'sa' dianggap sajak a karena keduanya bunyi vokal 'a'."],
    ["Amanat atau pesan dalam pantun biasanya terletak di bagian...", ["Sampiran", "Isi", "Baris 1", "Baris 2"], 1, "Pesan atau amanat terletak di bagian isi (baris 3-4)."],
  ]),
}
export default konten
