import type { Konten } from "../types"
import { makeSoal } from "../types"

const konten: Konten = {
  belajar: {
    tujuan: [
      "Memahami pengertian dan ciri laporan",
      "Menyusun laporan sederhana dengan sistematika yang benar",
      "Mempresentasikan laporan dengan percaya diri",
    ],
    materi: [
      {
        judul: "Laporan dan Cirinya",
        isi: [
          "Pernahkah kamu diminta mengamati sesuatu lalu menceritakan hasilnya? Itulah yang disebut laporan!",
          "",
          "✓ Laporan adalah teks yang menyajikan informasi berdasarkan hasil pengamatan, penelitian, atau kegiatan secara faktual dan objektif.",
          "",
          "Ciri-ciri laporan yang baik:",
          "1. Bersifat faktual — berdasarkan fakta nyata, bukan khayalan.",
          "2. Objektif — sesuai kenyataan, tidak memihak.",
          "3. Sistematis — disusun dengan urutan yang logis.",
          "4. Lengkap — semua informasi penting disertakan.",
          "5. Menggunakan bahasa baku dan jelas.",
          "",
          "Laporan berbeda dengan cerita. Laporan harus berdasarkan data dan fakta, sedangkan cerita bisa berdasarkan imajinasi.",
          "",
          "[Ilustrasi: Seorang anak berdiri di taman sambil memegang buku catatan dan pensil. Di sekelilingnya ada tanaman, bunga, kupu-kupu. Ia sedang mengamati dan mencatat. Gaya ilustrasi naturalis cilik.]",
        ],
        contoh: [
          "Bandingkan laporan dengan cerita tentang tema yang sama:",
          "",
          "✓ LAPORAN: 'Berdasarkan pengamatan pada hari Sabtu, 10 Maret, tanaman kacang hijau di pot A tumbuh setinggi 5 cm. Warna daunnya hijau muda. Penyiraman dilakukan setiap pagi.'",
          "  — Faktual, data jelas, objektif.",
          "",
          "✗ CERITA: 'Tanaman kacang hijauku tumbuh dengan cantik. Daunnya hijau seperti permata. Aku sangat senang melihatnya.'",
          "  — Subjektif, berisi perasaan, bukan data faktual.",
        ],
      },
      {
        judul: "Menyusun Laporan",
        isi: [
          "Laporan yang baik memiliki susunan atau sistematika tertentu. Mari pelajari bagian-bagiannya!",
          "",
          "1. JUDUL — mencerminkan isi laporan, ditulis di bagian paling atas.",
          "  Contoh: 'Laporan Pengamatan Pertumbuhan Kacang Hijau'",
          "",
          "2. TUJUAN — menjelaskan maksud pengamatan atau kegiatan.",
          "  Contoh: 'Tujuan pengamatan ini adalah untuk mengetahui pertumbuhan kacang hijau selama 7 hari.'",
          "",
          "3. ISI LAPORAN — bagian utama berisi data dan penjelasan.",
          "  • Waktu dan tempat pengamatan.",
          "  • Alat dan bahan yang digunakan.",
          "  • Hasil pengamatan (bisa dalam bentuk tabel).",
          "  • Pembahasan atau penjelasan hasil.",
          "",
          "4. KESIMPULAN — ringkasan hasil dan jawaban dari tujuan.",
          "  Contoh: 'Kacang hijau dapat tumbuh dengan baik jika disiram setiap hari dan mendapat sinar matahari.'",
          "",
          "[Ilustrasi: Lembaran kertas laporan dengan empat bagian berwarna berbeda. Bagian 1 'JUDUL' — warna biru. Bagian 2 'TUJUAN' — warna hijau. Bagian 3 'ISI' — warna kuning dengan tabel kecil. Bagian 4 'KESIMPULAN' — warna oranye. Gaya dokumen anak-anak.]",
        ],
        contoh: [
          "Contoh laporan pengamatan sederhana:",
          "",
          "JUDUL: Laporan Pengamatan Tanaman Bawang Merah",
          "",
          "TUJUAN: Mengamati pertumbuhan bawang merah selama 5 hari.",
          "",
          "ISI: Pengamatan dilakukan di rumah, pada tanggal 5-9 Mei. Alat: pot, tanah, bawang merah, air. Hari ke-1: bawang mulai tumbuh akar. Hari ke-3: muncul tunas hijau setinggi 2 cm. Hari ke-5: tunas sudah setinggi 5 cm.",
          "",
          "KESIMPULAN: Bawang merah dapat tumbuh dengan cepat jika disiram secara teratur.",
        ],
        catatan: "Dalam laporan, kita bisa menambahkan tabel, diagram, atau gambar untuk memperjelas data. Tabel sangat membantu saat menyajikan data pengamatan harian.",
      },
      {
        judul: "Mempresentasikan Laporan",
        isi: [
          "Setelah laporan selesai, saatnya menyampaikan hasilnya di depan kelas!",
          "",
          "Tips presentasi laporan yang baik:",
          "",
          "1. Berdiri tegak dan percaya diri.",
          "2. Suara jelas dan tidak terlalu pelan.",
          "3. Perhatikan teman-teman yang mendengarkan.",
          "4. Jelaskan laporan secara urut: judul, tujuan, isi, kesimpulan.",
          "5. Gunakan alat bantu seperti gambar atau tabel.",
          "",
          "PENTING: Jangan membaca laporan terus-menerus. Lihat catatan sesekali, lalu jelaskan dengan kata-katamu sendiri.",
          "",
          "Hal-hal yang perlu disiapkan sebelum presentasi:",
          "",
          "1. Pahami isi laporan yang sudah dibuat.",
          "2. Siapkan poin-poin penting di kartu catatan.",
          "3. Latihan berbicara di depan cermin.",
          "4. Siapkan alat bantu (poster, gambar, tabel).",
          "",
          "[Ilustrasi: Seorang anak berdiri di depan kelas dengan poster laporan di tangan. Teman-teman duduk mendengarkan. Guru tersenyum memberi semangat. Papan tulis di belakang bertuliskan 'PRESENTASI LAPORAN'. Gaya ruang kelas ceria.]",
        ],
        contoh: [
          "Contoh pembukaan presentasi laporan:",
          "",
          "'Assalamualaikum, salam sejahtera untuk kita semua. Pada kesempatan ini, saya akan menyampaikan laporan pengamatan pertumbuhan kacang hijau. Pengamatan ini saya lakukan selama 7 hari di rumah.'",
          "",
          "Contoh penutup presentasi:",
          "",
          "'Demikian laporan pengamatan saya. Terima kasih atas perhatian teman-teman. Ada pertanyaan? Saya persilakan.'",
          "",
          "Tips: Setelah presentasi, jangan lupa menerima pertanyaan dan menjawab dengan sopan!",
        ],
      },
    ],
    rangkuman: [
      "[Ilustrasi: Buku laporan terbuka dengan stiker 'LAPORANKU'. Ada bagan sistematika laporan: Judul → Tujuan → Isi → Kesimpulan. Juga ada ikon mikrofon untuk presentasi. Gaya scrapbook pelajaran.]",
      "Laporan: teks faktual dan objektif berdasarkan hasil pengamatan atau kegiatan.",
      "Ciri laporan: faktual, objektif, sistematis, lengkap, bahasa baku.",
      "Sistematika laporan: judul, tujuan, isi, kesimpulan.",
      "Presentasi: sampaikan dengan percaya diri, suara jelas, dan gunakan alat bantu.",
    ],
  },
  latihan: makeSoal([
    ["Laporan harus bersifat...", ["Subjektif", "Faktual dan objektif", "Imajinatif", "Fiktif"], 1, "Laporan harus berdasarkan fakta (faktual) dan sesuai kenyataan (objektif)."],
    ["Bagian pertama dalam sistematika laporan adalah...", ["Tujuan", "Judul", "Isi", "Kesimpulan"], 1, "Judul adalah bagian paling awal dari laporan."],
    ["Tujuan laporan ditulis setelah...", ["Kesimpulan", "Judul", "Isi", "Daftar pustaka"], 1, "Setelah judul, kita tulis tujuan laporan."],
    ["Data dalam laporan bisa disajikan dalam bentuk...", ["Dongeng", "Tabel", "Pantun", "Puisi"], 1, "Tabel membantu menyajikan data dengan rapi dan jelas."],
    ["Yang BUKAN ciri laporan adalah...", ["Berdasarkan fakta", "Bersifat khayalan", "Objektif", "Sistematis"], 1, "Khayalan/imajinasi bukan ciri laporan. Laporan berdasarkan fakta."],
    ["Bagian yang merangkum hasil laporan disebut...", ["Judul", "Kesimpulan", "Tujuan", "Alat dan bahan"], 1, "Kesimpulan adalah ringkasan hasil laporan."],
    ["Bahasa yang digunakan dalam laporan adalah...", ["Bahasa gaul", "Bahasa baku", "Bahasa daerah", "Bahasa asing"], 1, "Laporan menggunakan bahasa baku Indonesia yang baik dan benar."],
    ["Saat presentasi, sebaiknya kita...", ["Membaca terus", "Menjelaskan dengan kata sendiri", "Berdiri membelakangi", "Bermain ponsel"], 1, "Presentasi yang baik menjelaskan dengan kata-kata sendiri."],
    ["Contoh kegiatan yang bisa dilaporkan adalah...", ["Membuat cerpen", "Pengamatan pertumbuhan tanaman", "Menulis puisi", "Mengarang dongeng"], 1, "Pengamatan ilmiah seperti pertumbuhan tanaman bisa dilaporkan."],
    ["Kesimpulan laporan berisi...", ["Ajakan membeli", "Ringkasan hasil", "Cerita baru", "Iklan"], 1, "Kesimpulan berisi ringkasan dari hasil pengamatan."],
  ]),
  praktik: {
    petunjuk: "Lakukan pengamatan sederhana selama 5 hari! Pilih salah satu: (1) pertumbuhan kacang hijau di kapas basah, (2) perubahan cuaca setiap hari, atau (3) kebiasaan belajar teman sekelas. Buat laporan lengkap dengan judul, tujuan, isi (dengan tabel), dan kesimpulan. Presentasikan di depan kelas!",
    tips: [
      "Siapkan buku catatan khusus untuk menulis data setiap hari",
      "Catat tanggal, waktu, dan hasil pengamatan dengan detail",
      "Gunakan tabel untuk memudahkan melihat perubahan",
      "Ambil foto atau gambar hasil pengamatan sebagai bukti",
      "Latihan presentasi di rumah sebelum tampil di kelas",
    ],
    contoh: "JUDUL: Laporan Pengamatan Pertumbuhan Kacang Hijau. TUJUAN: Mengetahui pertumbuhan kacang hijau selama 5 hari. ISI: Hari ke-1: biji mulai membesar. Hari ke-2: muncul akar kecil. Hari ke-3: tunas muncul 1 cm. Hari ke-4: tunas 3 cm, daun mulai terbuka. Hari ke-5: tinggi 6 cm dengan 2 daun. KESIMPULAN: Kacang hijau tumbuh cepat jika mendapat air dan sinar matahari yang cukup.",
  },
  kuis: makeSoal([
    ["Teks laporan termasuk jenis teks...", ["Fiksi", "Nonfiksi", "Dongeng", "Puisi"], 1, "Laporan adalah teks nonfiksi berdasarkan fakta."],
    ["'Berdasarkan hasil pengamatan...' — frasa ini cocok untuk bagian...", ["Judul", "Isi laporan", "Kesimpulan", "Pantun"], 1, "Frasa 'berdasarkan hasil pengamatan' cocok di bagian isi."],
    ["Tujuan laporan adalah...", ["Menghibur", "Menyampaikan informasi faktual", "Menceritakan dongeng", "Beriklan"], 1, "Tujuan laporan adalah menyampaikan informasi berdasarkan fakta."],
    ["Laporan yang baik menggunakan data yang...", ["Subjektif", "Akurat", "Imajinatif", "Abstrak"], 1, "Data dalam laporan harus akurat (tepat dan benar)."],
    ["Saat presentasi, volume suara sebaiknya...", ["Sangat pelan", "Jelas dan terdengar", "Berbisik", "Berteriak"], 1, "Suara harus jelas dan terdengar oleh semua teman."],
    ["Yang termasuk alat bantu presentasi adalah...", ["Buku catatan", "Poster/gambar", "Pensil", "Tas"], 1, "Poster atau gambar membantu menjelaskan laporan."],
    ["'Laporan Pengamatan Tanaman Kacang Hijau' — ini adalah bagian...", ["Tujuan", "Judul", "Isi", "Kesimpulan"], 1, "Itu adalah judul laporan."],
    ["Sistematika berarti...", ["Acak", "Berurutan dan teratur", "Panjang", "Pendek"], 1, "Sistematis berarti tersusun secara urut dan teratur."],
    ["Mana kalimat yang objektif?", ["Tanaman ini indah sekali", "Suhu air 30 derajat Celsius", "Aku suka tanaman ini", "Tanaman itu cantik"], 1, "'Suhu air 30 derajat Celsius' adalah fakta objektif."],
    ["Setelah presentasi, sebaiknya kita...", ["Langsung pulang", "Menerima pertanyaan", "Merobek laporan", "Berteriak"], 1, "Sesi tanya jawab dilakukan setelah presentasi."],
  ]),
}
export default konten
