import type { Konten } from "../types"
import { makeSoal } from "../types"

const konten: Konten = {
  belajar: {
    tujuan: [
      "Memahami pengertian teks tanggapan",
      "Mengenal struktur teks tanggapan yang baik",
      "Memberi tanggapan secara santun dan membangun",
    ],
    materi: [
      {
        judul: "Tanggapan Kritis",
        isi: [
          "Ketika temanmu bercerita, pasti kamu akan memberi tanggapan, bukan? Nah, dalam pelajaran bahasa Indonesia, memberi tanggapan bisa dilakukan secara tertulis. Teks tanggapan adalah teks yang berisi penilaian, kritik, atau pujian terhadap suatu hal yang disertai alasan yang logis.",
          "",
          "✓ Teks tanggapan harus berisi argumen — alasan yang mendukung tanggapan kita. Tidak boleh asal 'bagus' atau 'jelek' tanpa penjelasan.",
          "",
          "Ciri teks tanggapan:",
          "1. Berisi tanggapan terhadap karya, peristiwa, atau fenomena.",
          "2. Tanggapan disertai alasan (argumen).",
          "3. Menggunakan bahasa yang santun.",
          "4. Bersifat objektif (berdasarkan fakta, bukan perasaan pribadi semata).",
          "",
          "[Ilustrasi: Seorang anak duduk di meja sambil memegang buku cerita. Di sekelilingnya ada gelembung pikiran berisi ikon jempol ke atas, jempol ke bawah, dan tanda tanya — menunjukkan proses memberi tanggapan. Gaya ilustrasi kartun ceria.]",
        ],
        contoh: [
          "Contoh tanggapan beralasan vs tidak beralasan:",
          "",
          "✓ Beralasan: 'Lukisan ini sangat menarik karena penggunaan warnanya cerah dan membuat orang yang melihatnya merasa senang.'",
          "  — Ada alasan: karena warna cerah dan efeknya.",
          "",
          "✗ Tidak beralasan: 'Lukisan ini bagus.'",
          "  — Hanya pendapat tanpa alasan.",
        ],
        catatan: "Membedakan kritik dan pujian: kritik bukan berarti marah atau mencela. Kritik adalah tanggapan yang menunjukkan kekurangan dengan tujuan membantu memperbaiki. Pujian adalah tanggapan yang menunjukkan kelebihan. Keduanya sama-sama penting dan harus disertai alasan.",
      },
      {
        judul: "Struktur Teks Tanggapan",
        isi: [
          "Teks tanggapan memiliki struktur yang terdiri dari tiga bagian utama:",
          "",
          "1. KONTEKS — Pengantar tentang objek yang akan ditanggapi. Apa yang sedang dibicarakan? Siapa pembuatnya? Di mana dan kapan?",
          "",
          "2. DESKRIPSI — Gambaran singkat tentang objek tanggapan. Ceritakan secara ringkas apa yang dilihat atau diketahui.",
          "",
          "3. PENILAIAN — Bagian terpenting! Berisi pujian atau kritik yang disertai alasan. Gunakan bahasa yang santun dan membangun.",
          "",
          "Tips:",
          "• Mulailah dengan konteks agar pembaca tahu apa yang kamu tanggapi.",
          "• Sertakan deskripsi secukupnya, jangan terlalu panjang.",
          "• Penilaian harus logis dan didukung bukti.",
          "",
          "[Ilustrasi: Piramida tiga tingkat: tingkat bawah 'Konteks' (biru), tengah 'Deskripsi' (hijau), atas 'Penilaian' (kuning). Masing-masing dengan ikon: kaca pembesar (konteks), buku (deskripsi), bintang (penilaian). Gaya infografis anak.]",
        ],
        contoh: [
          "Contoh teks tanggapan untuk cerpen 'Kancil dan Buaya':",
          "",
          "KONTEKS: Cerpen 'Kancil dan Buaya' adalah cerita rakyat yang sangat populer di Indonesia. Cerita ini mengajarkan tentang kecerdikan.",
          "",
          "DESKRIPSI: Cerita ini menceritakan Kancil yang cerdik menyeberangi sungai dengan menipu buaya. Kancil menyuruh buaya berbaris, lalu melompati punggung mereka.",
          "",
          "PENILAIAN: Cerita ini sangat bagus karena mengandung pesan moral tentang kecerdikan dan keberanian. Alurnya mudah dipahami anak-anak. Namun, kekurangannya adalah tokoh buaya terlalu mudah ditipu. Sebaiknya ada sedikit perlawanan dari buaya agar cerita lebih seru.",
        ],
      },
      {
        judul: "Memberi Tanggapan Santun",
        isi: [
          "Memberi tanggapan bukan sekadar menyampaikan pendapat. Kita harus memperhatikan cara menyampaikannya agar tidak menyinggung perasaan orang lain.",
          "",
          "Tips santun dalam memberi tanggapan:",
          "",
          "1. Mulai dengan hal positif terlebih dahulu. Contoh: 'Ceritamu menarik, ada beberapa bagian yang kusuka...'",
          "",
          "2. Sampaikan kritik dengan bahasa yang halus. Gunakan kata 'sebaiknya', 'akan lebih baik jika', atau 'mungkin bisa dicoba...'",
          "",
          "3. Beri saran, bukan hanya menunjukkan kesalahan.",
          "",
          "4. Jangan gunakan kata-kata kasar atau merendahkan.",
          "",
          "5. Hargai perbedaan pendapat. Belum tentu pendapatmu yang paling benar.",
          "",
          "PENTING: Tujuan memberi tanggapan adalah membantu, bukan menjatuhkan. Bayangkan jika kamu yang mendapat tanggapan — pasti kamu ingin dikritik dengan cara yang baik, bukan?",
          "",
          "[Ilustrasi: Dua anak duduk berhadapan di meja. Satu anak sedang berbicara dan yang lain mendengarkan sambil tersenyum. Di atas meja ada buku dan pensil. Gelembung dialog berisi kata 'menarik', 'baiknya', 'saran'. Gaya ilustrasi pertemanan yang hangat.]",
        ],
        contoh: [
          "Contoh tanggapan santun vs tidak santun:",
          "",
          "✓ SANTUN: 'Gambarmu sudah bagus, warnanya cerah. Akan lebih menarik lagi jika proporsi tubuhnya diperbaiki. Coba perhatikan ukuran kepala dan badan.'",
          "  — Diawali pujian, kritik disampaikan dengan saran.",
          "",
          "✗ TIDAK SANTUN: 'Gambarmu jelek, kepalanya terlalu besar. Tidak mirip sama sekali!'",
          "  — Langsung menjatuhkan tanpa saran.",
        ],
      },
    ],
    rangkuman: [
      "[Ilustrasi: Timbangan dengan dua sisi: satu sisi 'Pujian', satu sisi 'Kritik'. Di tengah ada kata 'Santun'. Di bawah timbangan ada buku terbuka dengan tulisan 'Teks Tanggapan'. Gaya infografis keseimbangan.]",
      "Teks tanggapan: teks yang berisi penilaian, kritik, atau pujian terhadap suatu hal dengan alasan yang logis.",
      "Struktur teks tanggapan: konteks → deskripsi → penilaian (pujian/kritik beralasan).",
      "Tanggapan harus santun: awali dengan hal positif, gunakan bahasa halus, beri saran, jangan merendahkan.",
      "Tujuan memberi tanggapan: membantu memperbaiki, bukan menjatuhkan. Kritik yang membangun itu baik!",
    ],
  },
  latihan: makeSoal([
    ["Teks tanggapan adalah teks yang berisi...", ["Cerita fiksi", "Penilaian, kritik, atau pujian beralasan", "Petunjuk", "Laporan"], 1, "Teks tanggapan berisi penilaian terhadap sesuatu dengan alasan logis."],
    ["Bagian pertama struktur teks tanggapan adalah...", ["Penilaian", "Konteks", "Deskripsi", "Kesimpulan"], 1, "Konteks adalah pengantar tentang objek yang akan ditanggapi."],
    ["Kritik yang baik disertai dengan...", ["Amarah", "Alasan dan saran", "Hinaan", "Celaan"], 1, "Kritik yang baik mengandung alasan dan saran untuk perbaikan."],
    ["Bahasa yang digunakan dalam teks tanggapan harus...", ["Kasar", "Santun", "Santai", "Baku"], 1, "Tanggapan harus menggunakan bahasa yang santun dan sopan."],
    ["Agar tanggapan tidak menyinggung, sebaiknya...", ["Langsung mengkritik", "Mulai dengan hal positif", "Diam saja", "Memarahi"], 1, "Awali dengan hal positif agar tanggapan diterima dengan baik."],
    ["Tujuan memberi tanggapan adalah...", ["Menjatuhkan", "Membantu memperbaiki", "Membandingkan", "Menghakimi"], 1, "Tanggapan bertujuan membantu, bukan menjatuhkan."],
    ["Yang BUKAN bagian teks tanggapan adalah...", ["Konteks", "Penilaian", "Deskripsi", "Alur"], 3, "Alur adalah bagian dari cerita fiksi, bukan struktur teks tanggapan."],
    ["Kata yang tepat untuk memberi saran adalah...", ["Sebaiknya", "Bodoh", "Jelek", "Parah"], 0, "'Sebaiknya' adalah kata yang santun untuk memberi saran."],
    ["Contoh tanggapan yang baik adalah...", ["Ceritamu jelek", "Ceritamu menarik, tapi alurnya bisa dipercepat sedikit", "Tidak suka", "Membosankan"], 1, "Tanggapan yang baik berisi pujian dan kritik membangun."],
    ["Penilaian dalam teks tanggapan harus didukung oleh...", ["Perasaan", "Argumen atau alasan", "Hayalan", "Keinginan"], 1, "Penilaian harus logis dan didukung alasan yang jelas."],
  ]),
  praktik: {
    petunjuk: "Bacalah cerpen pendek berjudul 'Semut dan Belalang' (cerita tentang semut yang bekerja keras dan belalang yang bermalas-malasan). Tulis teks tanggapan dengan struktur lengkap: konteks, deskripsi, dan penilaian. Sertakan pujian dan kritik yang membangun!",
    tips: [
      "Tentukan konteks: cerita apa yang kamu tanggapi?",
      "Deskripsi: ceritakan secara singkat isi cerita",
      "Penilaian: beri pujian untuk hal baik, kritik untuk kekurangan",
      "Gunakan bahasa santun dan akhiri dengan saran",
    ],
    contoh: "KONTEKS: Cerita 'Semut dan Belalang' adalah fabel klasik yang mengajarkan pentingnya kerja keras. Cerita ini sangat dikenal oleh anak-anak Indonesia.\n\nDESKRIPSI: Cerita ini menceritakan semut yang bekerja keras mengumpulkan makanan setiap hari, sementara belalang hanya bermalas-malasan dan bernyanyi. Saat musim dingin tiba, belalang kedinginan dan kelaparan, sedangkan semut bertahan dengan persediaannya.\n\nPENILAIAN: Cerita ini memiliki pesan moral yang sangat baik tentang pentingnya kerja keras. Anak-anak bisa belajar bahwa malas itu tidak baik. Ilustrasinya juga menarik dan warna-warni. Namun, kekurangannya adalah cerita ini terkesan menghukum belalang terlalu keras. Sebaiknya ada bagian di mana semut membantu belalang setelah belalang berjanji akan berubah, agar nilai kebaikan juga diajarkan.",
  },
  kuis: makeSoal([
    ["Konteks dalam teks tanggapan berfungsi untuk...", ["Menilai", "Memperkenalkan objek tanggapan", "Menyimpulkan", "Mengkritik"], 1, "Konteks memperkenalkan objek yang akan ditanggapi."],
    ["Syarat tanggapan yang baik adalah...", ["Panjang", "Disertai alasan", "Keras", "Banyak"], 1, "Tanggapan baik harus disertai alasan atau argumen."],
    ["Kritik disampaikan dengan tujuan...", ["Menyakiti", "Membangun", "Marah", "Menghina"], 1, "Kritik yang baik bertujuan membangun, bukan menyakiti."],
    ["Kata 'akan lebih baik jika' termasuk...", ["Pujian", "Saran yang santun", "Makian", "Larangan"], 1, "'Akan lebih baik jika' adalah ungkapan saran yang santun."],
    ["Objek teks tanggapan bisa berupa...", ["Karya, peristiwa, fenomena", "Hanya lukisan", "Hanya buku", "Hanya film"], 0, "Objek tanggapan beragam: karya, peristiwa, fenomena, dll."],
    ["Tanggapan yang tidak disertai alasan disebut...", ["Kritik", "Pendapat tanpa argumen", "Saran", "Penilaian"], 1, "Tanggapan tanpa alasan hanyalah pendapat kosong."],
    ["Bagian deskripsi dalam teks tanggapan berisi...", ["Alasan", "Gambaran singkat objek", "Kritik", "Simpulan"], 1, "Deskripsi memberikan gambaran singkat tentang objek."],
    ["Sikap yang baik saat menanggapi adalah...", ["Merasa paling benar", "Menghargai pendapat orang lain", "Memaksa", "Mengabaikan"], 1, "Sikap menghargai pendapat orang lain sangat penting."],
    ["Tanggapan santun berarti...", ["Berkata apa adanya tanpa filter", "Menggunakan bahasa yang sopan dan tidak menyakitkan", "Memuji terus", "Diam saja"], 1, "Santun berarti sopan dan tidak menyakiti perasaan."],
    ["Fungsi teks tanggapan adalah...", ["Menghibur", "Memberi masukan terhadap suatu hal", "Melapor", "Mendongeng"], 1, "Teks tanggapan berfungsi memberi masukan atau penilaian."],
  ]),
}
export default konten
