import type { Konten } from "../types"
import { makeSoal } from "../types"

const konten: Konten = {
  belajar: {
    tujuan: [
      "Memahami pengertian dan fungsi resensi buku",
      "Mengenal unsur-unsur resensi buku fiksi",
      "Menulis resensi buku fiksi dengan bahasa yang baik",
    ],
    materi: [
      {
        judul: "Mengenal Resensi Buku",
        isi: [
          "Pernahkah kamu membaca ulasan buku di koran atau internet? Ulasan itu disebut resensi.",
          "",
          "✓ Resensi adalah tulisan yang berisi penilaian atau ulasan terhadap sebuah buku.",
          "",
          "Resensi bertujuan untuk:",
          "1. Memberi gambaran isi buku kepada pembaca.",
          "2. Menilai kualitas buku (kelebihan dan kekurangan).",
          "3. Membantu pembaca memutuskan apakah buku itu layak dibaca.",
          "4. Memberi masukan kepada penulis buku.",
          "",
          "Resensi berbeda dengan ringkasan. Resensi berisi pendapat dan penilaian, sedangkan ringkasan hanya menceritakan kembali isi buku.",
          "",
          "[Ilustrasi: Sebuah meja dengan buku terbuka di atasnya. Di samping buku ada secangkir kopi dan buku catatan kecil dengan pena. Latar belakang rak buku penuh warna. Gaya ilustrasi cozy reading corner.]",
        ],
        contoh: [
          "Perbedaan resensi dan sinopsis:",
          "",
          "✓ RESENSI: 'Buku ini sangat menarik karena alur ceritanya tidak terduga. Tokoh utama digambarkan dengan detail. Namun, cover buku kurang menarik.'",
          "  — Ada penilaian: 'sangat menarik', 'kurang menarik'.",
          "",
          "✗ SINOPSIS: 'Buku ini menceritakan seorang anak yang berpetualang di hutan bersama teman-temannya.'",
          "  — Hanya menceritakan isi, tanpa penilaian.",
        ],
        catatan: "Sumber resensi bisa dari koran, majalah, blog, atau YouTube. Saat ini banyak juga resensi dalam bentuk video yang disebut book review.",
      },
      {
        judul: "Unsur Resensi",
        isi: [
          "Sebuah resensi yang baik memiliki unsur-unsur berikut:",
          "",
          "1. IDENTITAS BUKU — judul, pengarang, penerbit, tahun terbit, jumlah halaman.",
          "  Contoh: 'Judul: Si Kancil Anak Pintar. Pengarang: Ida Fitri. Penerbit: Gramedia, 2024. 120 halaman.'",
          "",
          "2. ORIENTASI — pengantar yang menarik minat pembaca.",
          "  Contoh: 'Pernahkah kamu membayangkan hidup di desa yang penuh petualangan?'",
          "",
          "3. SINOPSIS/RINGKASAN — gambaran singkat isi buku (bukan seluruh cerita).",
          "",
          "4. ANALISIS — kelebihan dan kekurangan buku.",
          "  ✓ Kelebihan: bahasa mudah dipahami, cerita seru, pesan moral yang baik.",
          "  ✗ Kekurangan: ilustrasi kurang, ukuran huruf terlalu kecil.",
          "",
          "5. PENILAIAN — kesimpulan berupa rekomendasi.",
          "  Contoh: 'Buku ini cocok untuk anak seusiamu. Nilai: 4/5 bintang.'",
          "",
          "[Ilustrasi: Diagram peta konsep berjudul 'Unsur Resensi'. Ada 5 kotak berwarna berbeda: Identitas Buku (biru), Orientasi (hijau), Sinopsis (kuning), Analisis (merah), Penilaian (ungu). Masing-masing terhubung dengan panah ke pusat bertuliskan 'Resensi'. Gaya infografis.]",
        ],
        contoh: [
          "Contoh analisis kelebihan dan kekurangan:",
          "",
          "✓ KELEBIHAN: 'Bahasa dalam buku ini sederhana dan mudah dipahami. Ceritanya seru dan penuh kejutan. Pesan moralnya tersampaikan dengan baik.'",
          "  — Menyebutkan aspek positif secara spesifik.",
          "",
          "✗ KEKURANGAN: 'Sayangnya, ilustrasi dalam buku ini hanya hitam putih. Beberapa bab terasa terlalu panjang untuk anak seusia SD.'",
          "  — Menyebut kekurangan dengan sopan, bukan mencela.",
        ],
      },
      {
        judul: "Menulis Resensi",
        isi: [
          "Ayo, kita praktik menulis resensi buku fiksi!",
          "",
          "Langkah-langkah:",
          "",
          "1. Bacalah buku yang akan diresensi sampai selesai.",
          "2. Catat identitas buku: judul, pengarang, penerbit, tahun.",
          "3. Tulis sinopsis singkat (3-4 kalimat).",
          "4. Analisis kelebihan dan kekurangan buku.",
          "5. Beri penilaian/rekomendasi di akhir.",
          "",
          "Tips menulis resensi yang baik:",
          "• Gunakan bahasa yang sopan dan objektif.",
          "• Jangan hanya menyebut kekurangan, sebut juga kelebihannya.",
          "• Beri penjelasan, jangan hanya 'bagus' atau 'jelek'.",
          "• Akhiri dengan kesimpulan yang jelas.",
          "",
          "[Ilustrasi: Seorang anak duduk di meja belajar dengan buku terbuka di depan. Di tangan kanannya memegang pensil, di tangan kiri memegang buku yang sedang dibaca. Notebook terbuka dengan tulisan 'Resensi Buku: ...' dan poin-poin. Gaya ilustrasi anak sekolah.]",
        ],
        contoh: [
          "Contoh resensi sederhana:",
          "",
          "Judul: Petualangan di Hutan Pelangi",
          "Pengarang: Rina Wijaya",
          "Penerbit: Pustaka Ceria, 2024",
          "",
          "Buku ini bercerita tentang tiga sahabat yang tersesat di hutan. Mereka harus bekerja sama untuk keluar. Setiap bab penuh petualangan seru.",
          "",
          "✓ Kelebihan: Bahasanya ringan dan ada pesan tentang persahabatan. Ilustrasinya bagus dan penuh warna.",
          "✗ Kekurangan: Beberapa istilah sulit, tapi ada glosarium di bagian belakang.",
          "",
          "Kesimpulan: Buku ini sangat direkomendasikan untuk anak SD. Nilai: 8/10.",
        ],
      },
    ],
    rangkuman: [
      "[Ilustrasi: Peta pikiran resensi — pusat 'Resensi' dengan cabang: Identitas Buku, Orientasi, Sinopsis, Analisis, Penilaian. Masing-masing cabang memiliki ikon: buku, kaca pembesar, ringkasan, timbangan, bintang. Gaya infografis warna-warni.]",
      "Resensi adalah ulasan atau penilaian terhadap sebuah buku.",
      "Unsur resensi: identitas buku, orientasi, sinopsis, analisis (kelebihan & kekurangan), penilaian.",
      "Resensi berbeda dengan sinopsis — resensi berisi penilaian, sinopsis hanya ringkasan.",
      "Menulis resensi: baca buku → catat identitas → tulis sinopsis → analisis → beri penilaian.",
    ],
  },
  latihan: makeSoal([
    ["Resensi adalah...", ["Ringkasan buku", "Ulasan/penilaian buku", "Sinopsis film", "Daftar isi buku"], 1, "Resensi berisi ulasan dan penilaian, bukan sekadar ringkasan."],
    ["Yang termasuk identitas buku adalah...", ["Judul dan pengarang", "Isi cerita", "Kelebihan buku", "Kesimpulan"], 0, "Identitas buku meliputi judul, pengarang, penerbit, tahun terbit, dan jumlah halaman."],
    ["Bagian yang berisi pengantar menarik disebut...", ["Sinopsis", "Orientasi", "Analisis", "Penilaian"], 1, "Orientasi adalah pengantar yang menarik minat pembaca."],
    ["Analisis dalam resensi berisi...", ["Hanya kelebihan", "Kelebihan dan kekurangan", "Hanya kekurangan", "Identitas buku"], 1, "Analisis mencakup baik kelebihan maupun kekurangan buku."],
    ["Resensi berbeda dengan sinopsis karena resensi...", ["Lebih panjang", "Berisi penilaian", "Tidak perlu dibaca", "Hanya untuk buku tebal"], 1, "Resensi mengandung penilaian/opini, sinopsis hanya menceritakan isi."],
    ["Bahasa dalam resensi sebaiknya...", ["Kasar dan keras", "Sopan dan objektif", "Berbelit-belit", "Hanya pujian"], 1, "Resensi ditulis dengan bahasa sopan, objektif, dan jelas."],
    ["Tujuan resensi adalah...", ["Menjual buku", "Memberi gambaran dan penilaian buku", "Menghapus buku", "Mencari teman"], 1, "Resensi memberi gambaran isi dan penilaian untuk membantu pembaca."],
    ["Contoh penilaian dalam resensi: 'Nilai 4/5 bintang' — termasuk bagian...", ["Identitas", "Penilaian", "Sinopsis", "Analisis"], 1, "Penilaian berupa skor atau rekomendasi di akhir resensi."],
    ["Sebelum menulis resensi, langkah pertama adalah...", ["Membaca buku sampai selesai", "Menulis sinopsis", "Mencari kelemahan", "Memberi bintang"], 0, "Langkah pertama adalah membaca buku yang akan diresensi."],
    ["Sinopsis dalam resensi sebaiknya...", ["Panjang dan detail", "Singkat dan jelas", "Tidak perlu ada", "Sama dengan buku"], 1, "Sinopsis cukup 3-4 kalimat, gambaran singkat isi buku."],
  ]),
  praktik: {
    petunjuk: "Pilihlah satu buku fiksi yang pernah kamu baca. Tulis resensi sederhana dengan unsur: identitas buku, orientasi, sinopsis singkat, kelebihan dan kekurangan, serta penilaian. Panjang tulisan 3-4 paragraf.",
    tips: [
      "Pilih buku yang benar-benar kamu ingat isinya",
      "Catat identitas buku sebelum menulis",
      "Beri 2 kelebihan dan 1-2 kekurangan secara sopan",
      "Akhiri dengan kalimat rekomendasi",
    ],
    contoh: "Identitas Buku — Judul: Kancil dan Siput. Pengarang: Dian Kurniawan. Penerbit: Bintang Anak, 2024. 80 halaman. Orientasi — Siapa bilang kancil selalu menang? Buku ini mengajarkan bahwa kepintaran tidak menjamin kemenangan. Sinopsis — Kancil yang sombong menantang Siput berlomba lari. Siput yang cerdik bekerja sama dengan teman-temannya. Mereka menyusun strategi sehingga Siput berhasil menang. Analisis — ✓ Kelebihan: Cerita penuh pesan moral tentang kerendahan hati. Ilustrasi lucu dan berwarna. Bahasa mudah dipahami. ✗ Kekurangan: Cerita terlalu pendek, hanya 4 bab. Penilaian — Buku ini sangat baik untuk anak SD. Nilai: 4/5 bintang. Sangat direkomendasikan!",
  },
  kuis: makeSoal([
    ["Unsur resensi yang berisi nama penulis buku adalah...", ["Sinopsis", "Identitas buku", "Analisis", "Orientasi"], 1, "Nama penulis bagian dari identitas buku."],
    ["Kalimat 'Buku ini sangat direkomendasikan' termasuk bagian...", ["Orientasi", "Penilaian", "Identitas", "Sinopsis"], 1, "Penilaian berisi rekomendasi atau kesimpulan."],
    ["Yang bukan unsur resensi adalah...", ["Identitas buku", "Analisis", "Sinopsis", "Harga buku"], 3, "Harga buku tidak termasuk unsur wajib resensi."],
    ["Resensi yang baik menggunakan bahasa...", ["Kasar", "Objektif dan santun", "Memuji terus", "Menyalahkan"], 1, "Resensi ditulis secara objektif dengan bahasa santun."],
    ["Tujuan orientasi dalam resensi adalah...", ["Menilai buku", "Menarik minat pembaca", "Meringkas buku", "Mencantumkan harga"], 1, "Orientasi berfungsi sebagai pengantar yang menarik."],
    ["Contoh kalimat analisis kekurangan yang sopan adalah...", ["Buku ini jelek", "Ilustrasi kurang bervariasi, namun tetap menarik", "Buku ini membosankan", "Jangan baca buku ini"], 1, "Kekurangan disampaikan dengan sopan dan disertai sisi positif."],
    ["Setelah membaca buku untuk diresensi, langkah selanjutnya adalah...", ["Langsung menilai", "Mencatat identitas dan isi buku", "Memberi bintang", "Membagikan ke teman"], 1, "Catat dulu identitas dan hal penting dari buku."],
    ["Sinopsis dalam resensi berfungsi untuk...", ["Menilai buku", "Memberi gambaran isi buku", "Mencari kesalahan", "Menambah halaman"], 1, "Sinopsis memberi gambaran singkat tentang isi buku."],
    ["Penilaian dalam resensi biasanya berupa...", ["Hanya angka", "Rekomendasi atau skor", "Hanya kelebihan", "Daftar bab"], 1, "Penilaian bisa berupa rekomendasi atau skor (bintang/angka)."],
    ["Manfaat membaca resensi adalah...", ["Membuat malas membaca", "Membantu memilih buku yang baik", "Membuang waktu", "Hanya untuk penulis"], 1, "Resensi membantu pembaca memutuskan buku yang layak dibaca."],
  ]),
}
export default konten
