import type { Konten } from "../types"
import { makeSoal } from "../types"

const konten: Konten = {
  belajar: {
    tujuan: [
      "Memahami pengertian dan tujuan pidato persuasif",
      "Menyusun argumen yang kuat untuk pidato",
      "Berkpidato dengan percaya diri dan bahasa yang baik",
    ],
    materi: [
      {
        judul: "Pidato Persuasif",
        isi: [
          "Pernahkah kamu melihat seseorang berpidato di upacara bendera? Pidato adalah cara menyampaikan gagasan di depan umum. Ada pidato yang informatif (memberitahu), ada yang persuasif (mengajak).",
          "",
          "✓ Pidato persuasif adalah pidato yang bertujuan mengajak, memengaruhi, atau meyakinkan pendengar untuk melakukan sesuatu. Pidato ini menggunakan argumen yang kuat dan kata-kata yang membangkitkan semangat.",
          "",
          "Ciri pidato persuasif:",
          "1. Ada ajakan (menggunakan kata: mari, ayo, marilah).",
          "2. Disertai argumen atau alasan yang meyakinkan.",
          "3. Bahasa yang menggugah emosi pendengar.",
          "4. Tujuan akhir: menggerakkan pendengar untuk bertindak.",
          "",
          "[Ilustrasi: Seorang anak berdiri di podium, memegang mikrofon, dengan tangan terbuka lebar. Di depannya ada hadirin yang duduk rapi. Dari atas kepala anak itu keluar gelembung berisi kata 'Mari kita...', 'Ayo...', 'Marilah...'. Gaya ilustrasi semangat dan percaya diri.]",
        ],
        contoh: [
          "Perbedaan pidato informatif dan persuasif:",
          "",
          "✓ INFORMATIF: 'Sekolah kita akan mengadakan lomba kebersihan pada hari Sabtu. Setiap kelas diharapkan berpartisipasi.'",
          "  — Hanya memberitahu informasi.",
          "",
          "✓ PERSUASIF: 'Marilah kita bersama-sama menjaga kebersihan kelas! Dengan kelas yang bersih, kita akan nyaman belajar dan semangat meraih prestasi. Ayo, buang sampah pada tempatnya!'",
          "  — Ada ajakan dan alasan mengapa harus dilakukan.",
        ],
        catatan: "Pidato persuasif banyak digunakan dalam kampanye, penggalangan dana, pidato lingkungan, dan pidato motivasi. Kemampuan berpidato persuasif akan sangat berguna di masa depan!",
      },
      {
        judul: "Menyusun Argumen",
        isi: [
          "Agar pidato persuasif berhasil, kita perlu argumen yang kuat. Argumen adalah alasan yang mendukung ajakan kita. Tanpa argumen, pidato hanya akan seperti perintah tanpa alasan.",
          "",
          "Langkah menyusun argumen:",
          "",
          "1. Tentukan topik dan tujuan pidato. Misalnya: 'Mengajak teman-teman gemar membaca.'",
          "",
          "2. Cari alasan mengapa topik itu penting. Contoh: Membaca menambah ilmu, melatih otak, memperkaya kosakata.",
          "",
          "3. Kumpulkan bukti atau contoh nyata. Contoh: 'Teman kita, Sari, rajin membaca dan juara kelas.'",
          "",
          "4. Gunakan kata persuasif seperti 'mari', 'ayo', 'marilah', 'sebaiknya', 'alangkah baiknya'.",
          "",
          "Tips argumen kuat:",
          "• Gunakan fakta (bukan sekadar opini).",
          "• Sertakan contoh yang dekat dengan pendengar.",
          "• Gunakan bahasa yang menggugah perasaan.",
          "",
          "PENTING: Argumen yang baik adalah yang masuk akal dan bisa diterima oleh pendengar. Jangan memaksakan kehendak dengan argumen yang tidak logis!",
          "",
          "[Ilustrasi: Seorang anak memegang kertas yang bertuliskan 'ARGUMEN' dengan beberapa butir poin: Fakta, Contoh, Kata Ajakan. Di sekelilingnya ada ikon buku, lampu ide, dan tanda seru. Gaya infografis langkah-langkah.]",
        ],
        contoh: [
          "Membangun argumen untuk ajakan 'Gemar Membaca':",
          "",
          "ARGUMEN 1 (Fakta): Membaca buku selama 15 menit setiap hari bisa meningkatkan kemampuan otak kita. Penelitian mengatakan membaca itu seperti olahraga untuk otak!",
          "",
          "ARGUMEN 2 (Contoh): Kak Rina, alumni sekolah kita, sekarang jadi penulis terkenal. Ia mulai rajin membaca sejak kelas VI.",
          "",
          "ARGUMEN 3 (Perasaan): Bayangkan, dengan membaca kita bisa jalan-jalan keliling dunia tanpa harus bepergian. Buku adalah jendela dunia!",
          "",
          "AJAKAN: Maka dari itu, ayo kita luangkan waktu 15 menit setiap hari untuk membaca! Mulailah dari buku cerita favoritmu!",
        ],
      },
      {
        judul: "Berkpidato dengan Percaya Diri",
        isi: [
          "Sudah punya argumen yang kuat? Sekarang saatnya berpidato! Banyak orang merasa gugup saat berbicara di depan umum. Itu wajar! Berikut cara mengatasinya:",
          "",
          "1. PERSIAPAN — Kuasai materi pidatomu. Berlatihlah di depan cermin. Hafalkan poin-poin penting.",
          "",
          "2. BAHASA TUBUH — Berdiri tegak, pandang pendengar bergantian, gunakan gerakan tangan untuk menekankan poin.",
          "",
          "3. INTONASI — Suara tidak boleh monoton. Naikkan volume saat poin penting, turunkan saat penutup. Bicara jelas dan tidak terburu-buru.",
          "",
          "4. KONTROL GUGUP — Tarik napas dalam sebelum mulai. Ingat, pendengar tidak tahu jika kamu gugup. Anggap saja sedang bicara dengan teman.",
          "",
          "5. PAKAIAN — Berpakaian rapi membuat kita lebih percaya diri.",
          "",
          "6. MINTA MAAF DI AWAL (jika gemetar/tersendat) — Boleh minta maaf, lalu lanjutkan. Jangan berhenti di tengah!",
          "",
          "[Ilustrasi: Dua gambar berdampingan. Gambar kiri: anak terlihat gugup, badan membungkuk, kertas gemetar, keringat di dahi (dengan label 'Gugup'). Gambar kanan: anak yang sama berdiri tegak, tersenyum, percaya diri (dengan label 'Percaya Diri'). Gaya perbandingan sebelum-sesudah.]",
        ],
        contoh: [
          "Contoh pembukaan pidato persuasif:",
          "",
          "'Assalamu\'alaikum Wr. Wb.",
          "",
          "Yang terhormat Ibu Guru dan teman-teman yang saya sayangi,",
          "",
          "Pertama-tama, mari kita panjatkan puji syukur ke hadirat Allah SWT karena kita masih bisa berkumpul di sini.",
          "",
          "Teman-teman, hari ini saya ingin mengajak kalian untuk peduli terhadap lingkungan sekolah kita. Pernahkah kalian melihat sampah berserakan di halaman? Sampah yang dibiarkan akan membuat sekolah kita kotor dan tidak nyaman...'",
          "",
          "Tips: Awali dengan salam dan sapa pendengar. Sampaikan apresiasi. Baru masuk ke isi pidato.",
        ],
      },
    ],
    rangkuman: [
      "[Ilustrasi: Seorang anak di podium dengan latar bendera dan hadirin. Dari podium keluar kata-kata kunci: 'Persuasif', 'Ajakan', 'Argumen', 'Percaya Diri'. Gaya poster motivasi dengan warna-warna cerah.]",
      "Pidato persuasif adalah pidato yang bertujuan mengajak atau memengaruhi pendengar untuk bertindak.",
      "Struktur pidato persuasif: pembukaan → argumen (alasan) → ajakan → penutup.",
      "Argumen yang kuat menggunakan fakta, contoh nyata, dan bahasa yang menggugah.",
      "Berkpidato dengan percaya diri: persiapan matang, bahasa tubuh baik, intonasi tepat, kendalikan gugup.",
    ],
  },
  latihan: makeSoal([
    ["Pidato persuasif bertujuan untuk...", ["Menghibur", "Mengajak atau memengaruhi", "Melapor", "Mendongeng"], 1, "Pidato persuasif bertujuan mengajak pendengar melakukan sesuatu."],
    ["Kata yang termasuk ajakan adalah...", ["Mari", "Tidak", "Jangan", "Siapa"], 0, "'Mari' adalah kata ajakan yang khas dalam pidato persuasif."],
    ["Argumen dalam pidato berfungsi untuk...", ["Memperpanjang pidato", "Mendukung ajakan dengan alasan", "Menghias pidato", "Membingungkan"], 1, "Argumen memberi alasan mengapa ajakan harus diikuti."],
    ["Bagian pembukaan pidato sebaiknya berisi...", ["Ajakan", "Salam dan sapa", "Argumen", "Penutup"], 1, "Pembukaan diawali dengan salam dan sapaan."],
    ["Hal penting saat berpidato adalah...", ["Membaca terus tanpa melihat", "Kontak mata dengan pendengar", "Bicara cepat", "Lihat ke atas"], 1, "Kontak mata membuat pendengar merasa diperhatikan."],
    ["Sebelum berpidato, sebaiknya kita...", ["Tidur", "Berlatih di depan cermin", "Makan", "Bermain"], 1, "Berlatih di depan cermin membantu mengurangi gugup."],
    ["Intonasi dalam pidato artinya...", ["Kecepatan", "Naik turunnya suara", "Gerakan tangan", "Ekspresi wajah"], 1, "Intonasi adalah variasi suara (tinggi-rendah, keras-lembut)."],
    ["Yang BUKAN bagian pidato persuasif adalah...", ["Pembukaan", "Argumen", "Ajakan", "Alur cerita"], 3, "Alur cerita adalah bagian dari cerita fiksi, bukan pidato."],
    ["Contoh kalimat persuasif adalah...", ["Hari ini hari Senin", "Ayo, kita jaga kebersihan kelas!", "Budi pergi ke pasar", "Ibu sedang masak"], 1, "'Ayo' menunjukkan ajakan, ciri kalimat persuasif."],
    ["Tujuan akhir pidato persuasif adalah...", ["Mendapat tepuk tangan", "Menggerakkan pendengar bertindak", "Selesai bicara", "Dikenal banyak orang"], 1, "Tujuan akhir adalah menggerakkan pendengar untuk melakukan sesuatu."],
  ]),
  praktik: {
    petunjuk: "Buatlah teks pidato persuasif singkat dengan tema 'Mengajak teman-teman mengurangi sampah plastik di sekolah'. Gunakan struktur: pembukaan, argumen (minimal 2), ajakan, dan penutup. Tulis sekitar 2-3 paragraf.",
    tips: [
      "Awali dengan salam dan sapaan hangat",
      "Gunakan fakta tentang bahaya sampah plastik",
      "Sertakan contoh: 'setiap hari kita menghasilkan sampah plastik dari bungkus jajan'",
      "Akhiri dengan ajakan yang kuat dan penutup yang berkesan",
    ],
    contoh: "Assalamu'alaikum Wr. Wb.\n\nSelamat pagi Ibu Guru dan teman-teman yang saya banggakan. Puji syukur kita panjatkan ke hadirat Tuhan karena kita masih bisa berkumpul di sini.\n\nTeman-teman, tahukah kamu bahwa sampah plastik sulit terurai? Satu bungkus jajan plastik butuh ratusan tahun untuk hancur. Setiap hari, kita menghasilkan sampah plastik dari bungkus jajan, sedotan, dan botol minuman. Jika tidak dikelola, sekolah kita akan dipenuhi sampah!\n\nOleh karena itu, saya mengajak teman-teman semua untuk mulai mengurangi sampah plastik. Ayo, bawa botol minum dan tempat bekal dari rumah! Bawa juga tas belanja saat jajan di kantin. Hal kecil ini akan sangat membantu lingkungan kita.\n\nMulailah dari diri sendiri, mulai dari sekarang. Mari kita jaga sekolah kita bersama!\n\nWassalamu'alaikum Wr. Wb.",
  },
  kuis: makeSoal([
    ["Ciri utama pidato persuasif adalah ada...", ["Cerita lucu", "Ajakan", "Data", "Gambar"], 1, "Ajakan adalah ciri utama pidato persuasif."],
    ["Kata persuasif yang tepat untuk mengajak teman adalah...", ["Marilah", "Pergilah", "Diamlah", "Tutuplah"], 0, "'Marilah' adalah kata ajakan yang persuasif dan sopan."],
    ["Argumen yang baik harus didukung...", ["Opini", "Fakta dan contoh", "Hayalan", "Omongan teman"], 1, "Argumen kuat menggunakan fakta dan contoh nyata."],
    ["Saat berpidato, pandangan sebaiknya...", ["Ke lantai", "Menyebar ke seluruh pendengar", "Ke atas", "Tertutup"], 1, "Pandangan menyebar menunjukkan percaya diri dan menghargai pendengar."],
    ["Tujuan utama pidato persuasif adalah...", ["Menyampaikan informasi", "Memengaruhi dan mengajak bertindak", "Menulis laporan", "Bercerita"], 1, "Pidato persuasif bertujuan memengaruhi dan mengajak."],
    ["Bagian yang berisi alasan disebut...", ["Pembukaan", "Argumen", "Ajakan", "Penutup"], 1, "Argumen berisi alasan untuk mendukung ajakan."],
    ["Kalimat penutup pidato yang baik adalah...", ["Sekian dulu ya", "Demikian pidato saya, mohon maaf jika ada kesalahan", "Selesai", "Itu aja"], 1, "Penutup yang baik berisi permohonan maaf dan salam."],
    ["Bahasa tubuh yang baik saat berpidato adalah...", ["Membungkuk", "Berdiri tegak", "Tangan di saku", "Menunduk"], 1, "Berdiri tegak menunjukkan sikap percaya diri."],
    ["Sebelum berpidato, langkah pertama yang harus dilakukan adalah...", ["Berteriak", "Berlatih dan menguasai materi", "Langsung bicara", "Minta tepuk tangan"], 1, "Persiapan dengan berlatih dan menguasai materi sangat penting."],
    ["Ajakan 'Ayo kita tanam pohon!' termasuk jenis pidato...", ["Informatif", "Persuasif", "Rekreatif", "Deskriptif"], 1, "'Ayo' menunjukkan ajakan, ciri pidato persuasif."],
  ]),
}
export default konten
