import type { Konten } from "../types"
import { makeSoal } from "../types"

const konten: Konten = {
  belajar: {
    tujuan: [
      "Memahami pengertian dan fungsi teks diskusi",
      "Mengenal struktur teks diskusi yang benar",
      "Berdiskusi dengan santun dan menghargai pendapat orang lain",
    ],
    materi: [
      {
        judul: "Apa Itu Teks Diskusi?",
        isi: [
          "Pernahkah kamu berdebat dengan teman tentang hal yang kamu yakini? Misalnya, 'Lebih baik bermain di luar atau di dalam rumah?' Nah, ketika pendapat yang berbeda ditulis secara terstruktur, itulah teks diskusi!",
          "",
          "✓ Teks diskusi adalah teks yang menyajikan dua sudut pandang berbeda tentang suatu isu atau topik. Teks ini membahas sisi pro (setuju) dan sisi kontra (tidak setuju) secara berimbang.",
          "",
          "Tujuan teks diskusi:",
          "1. Menyajikan informasi dari berbagai sudut pandang.",
          "2. Membantu pembaca melihat suatu isu secara utuh.",
          "3. Melatih kita berpikir kritis dan terbuka.",
          "",
          "PENTING: Teks diskusi tidak memihak satu sisi. Teks ini menyajikan argumen pro dan kontra secara adil, lalu memberi kesimpulan di akhir.",
          "",
          "[Ilustrasi: Dua kelompok anak duduk melingkar. Satu kelompok dengan bendera 'Pro' (hijau), kelompok lain dengan bendera 'Kontra' (merah). Di tengah ada meja bundar. Semua tampak saling mendengarkan. Gaya ilustrasi diskusi kelas yang hidup.]",
        ],
        contoh: [
          "Contoh isu dalam teks diskusi:",
          "",
          "ISU: 'Apakah pekerjaan rumah (PR) bermanfaat bagi siswa?'",
          "",
          "✓ ARGUMEN PRO: PR membantu siswa mengulang pelajaran di rumah. Dengan PR, siswa lebih paham materi yang diajarkan di sekolah.",
          "",
          "✓ ARGUMEN KONTRA: PR membuat siswa kelelahan. Setelah seharian di sekolah, siswa perlu waktu istirahat dan bermain.",
          "",
          "Keduanya adalah argumen yang sah dan perlu dipertimbangkan secara adil!",
        ],
        catatan: "Ingat ya, teks diskusi berbeda dengan debat. Dalam debat, kita berusaha memenangkan sisi kita. Dalam teks diskusi, kita menyajikan kedua sisi dengan tujuan memberi informasi yang seimbang kepada pembaca.",
      },
      {
        judul: "Struktur Teks Diskusi",
        isi: [
          "Teks diskusi memiliki struktur yang khas. Mari kita pelajari satu per satu!",
          "",
          "1. ISU — Pengenalan topik atau masalah yang akan dibahas. Bagian ini berisi latar belakang dan mengapa topik ini penting.",
          "",
          "2. ARGUMEN PENDUKUNG (PRO) — Argumen yang mendukung atau setuju dengan isu. Setiap argumen harus disertai alasan dan bukti.",
          "",
          "3. ARGUMEN MENENTANG (KONTRA) — Argumen yang menentang atau tidak setuju dengan isu. Sama seperti argumen pro, harus disertai alasan.",
          "",
          "4. KESIMPULAN — Simpulan yang merangkum kedua argumen. Bisa berupa posisi penulis atau rekomendasi netral.",
          "",
          "Tips: Gunakan kata penghubung seperti 'di satu sisi... di sisi lain...', 'selain itu...', 'oleh karena itu...', 'dengan demikian...' untuk menghubungkan argumen.",
          "",
          "[Ilustrasi: Diagram alur vertikal dengan 4 kotak berwarna berbeda. Kotak 1 (biru) 'ISU', panah ke kotak 2 (hijau) 'ARGUMEN PRO', panah ke kotak 3 (merah) 'ARGUMEN KONTRA', panah ke kotak 4 (kuning) 'KESIMPULAN'. Setiap kotak ada ikon kecil. Gaya infografis anak.]",
        ],
        contoh: [
          "Contoh struktur teks diskusi tentang 'Penggunaan Ponsel di Sekolah':",
          "",
          "ISU: Banyak siswa membawa ponsel ke sekolah. Ada yang setuju dan tidak setuju dengan hal ini. Mari kita bahas kedua sisi.",
          "",
          "ARGUMEN PRO: Ponsel berguna untuk mencari informasi pelajaran, menghubungi orang tua jika ada keperluan mendadak, dan merekam materi.",
          "",
          "ARGUMEN KONTRA: Ponsel sering disalahgunakan untuk bermain game saat pelajaran, mengganggu konsentrasi, dan bisa hilang.",
          "",
          "KESIMPULAN: Ponsel boleh dibawa ke sekolah tetapi harus digunakan dengan bijak dan sesuai aturan yang berlaku.",
        ],
      },
      {
        judul: "Berdiskusi dengan Santun",
        isi: [
          "Dalam teks diskusi maupun diskusi langsung di kelas, kita harus menjaga kesantunan. Berikut panduannya:",
          "",
          "1. BERBICARA BERGILIRAN — Jangan memotong pembicaraan orang lain. Angkat tangan jika ingin berbicara.",
          "",
          "2. HARGAI PENDAPAT ORANG LAIN — Meskipun tidak setuju, kita harus menghargai. Semua orang berhak berpendapat.",
          "",
          "3. SAMPARKAN ARGUMEN DENGAN BAHASA SANTUN — Gunakan 'menurut pendapat saya', 'saya kurang setuju karena...', 'saya setuju dengan...'.",
          "",
          "4. JANGAN MEMAKSA — Tujuan diskusi bukan menang-menangan, tetapi mencari solusi terbaik.",
          "",
          "5. TIDAK BOLEH MENGHINA ATAU MERENDAHKAN — Fokus pada argumen, bukan pada orangnya.",
          "",
          "6. BERI TANGGAPAN YANG RELEVAN — Sesuaikan tanggapan dengan topik diskusi, jangan melenceng.",
          "",
          "PENTING: Dalam diskusi, yang terpenting bukan siapa yang benar, tetapi apa yang benar. Boleh berbeda pendapat, tetapi tetap bersahabat!",
          "",
          "[Ilustrasi: Lingkaran diskusi siswa di kelas. Seorang guru berdiri di samping papan tulis yang bertuliskan 'Aturan Diskusi: 1. Bergiliran 2. Hargai teman 3. Bahasa santun'. Semua siswa duduk rapi dan mengangkat tangan. Gaya ilustrasi suasana kelas yang tertib.]",
        ],
        contoh: [
          "Cara menyampaikan ketidaksetujuan dengan santun:",
          "",
          "✓ SANTUN: 'Maaf, saya kurang setuju dengan pendapatmu. Menurut saya, bekerja kelompok juga kadang tidak efektif karena ada teman yang tidak ikut bekerja.'",
          "  — Menggunakan 'maaf' di awal, memberikan alasan jelas.",
          "",
          "✗ TIDAK SANTUN: 'Kamu salah! kerja kelompok itu buang waktu aja!'",
          "  — Langsung menyalahkan, tanpa alasan, nada kasar.",
        ],
      },
    ],
    rangkuman: [
      "[Ilustrasi: Timbangan dengan dua sisi. Sisi kiri 'Pro' dengan icon centang hijau, sisi kanan 'Kontra' dengan icon silang merah. Di tengah ada kata 'Diskusi'. Di bawah ada buku terbuka. Gaya infografis anak ceria.]",
      "Teks diskusi adalah teks yang menyajikan dua sudut pandang (pro dan kontra) tentang suatu isu.",
      "Struktur: isu → argumen pendukung (pro) → argumen menentang (kontra) → kesimpulan.",
      "Diskusi yang baik: bergiliran, hargai pendapat, gunakan bahasa santun, jangan memaksakan kehendak.",
      "Tujuan: melihat isu secara utuh, bukan mencari siapa yang menang.",
    ],
  },
  latihan: makeSoal([
    ["Teks diskusi menyajikan...", ["Satu sudut pandang", "Dua sudut pandang (pro dan kontra)", "Hanya pro", "Hanya kontra"], 1, "Teks diskusi menyajikan dua sudut pandang secara berimbang."],
    ["Bagian yang memperkenalkan topik diskusi disebut...", ["Argumen", "Isu", "Kesimpulan", "Penutup"], 1, "Isu adalah pengenalan topik atau masalah yang dibahas."],
    ["Argumen pendukung disebut juga argumen...", ["Pro", "Kontra", "Netral", "Penolak"], 0, "Pro adalah argumen yang mendukung isu."],
    ["Tujuan teks diskusi adalah...", ["Memenangkan pendapat", "Menyajikan informasi dari berbagai sudut pandang", "Menyerang lawan", "Menghibur"], 1, "Teks diskusi memberi informasi dari berbagai sudut pandang."],
    ["Sikap yang baik saat berdiskusi adalah...", ["Memotong pembicaraan", "Menghargai pendapat orang lain", "Memaksa", "Marah"], 1, "Kita harus menghargai pendapat orang lain saat berdiskusi."],
    ["Kata penghubung yang tepat untuk membandingkan adalah...", ["Kemudian", "Di satu sisi... di sisi lain...", "Akhirnya", "Lalu"], 1, "'Di satu sisi... di sisi lain...' untuk membandingkan dua argumen."],
    ["Bagian akhir teks diskusi berisi...", ["Isu baru", "Kesimpulan", "Argumen", "Kontra"], 1, "Kesimpulan merangkum kedua argumen dan memberi simpulan."],
    ["Yang BUKAN termasuk struktur teks diskusi adalah...", ["Isu", "Alur", "Argumen pro", "Kesimpulan"], 1, "Alur adalah struktur cerita fiksi, bukan teks diskusi."],
    ["Jika tidak setuju dengan pendapat teman, sebaiknya...", ["Diam saja", "Sampaikan dengan santun beserta alasan", "Berteriak", "Meninggalkan ruangan"], 1, "Sampaikan ketidaksetujuan dengan santun dan beralasan."],
    ["Teks diskusi bersifat...", ["Memihak", "Netral dan berimbang", "Memojokkan", "Subjektif"], 1, "Teks diskusi bersifat netral dan menyajikan kedua sisi secara berimbang."],
  ]),
  praktik: {
    petunjuk: "Buatlah teks diskusi singkat tentang topik 'Apakah siswa SD boleh memiliki media sosial?' Gunakan struktur lengkap: isu, argumen pro, argumen kontra, dan kesimpulan. Tulis minimal 3-4 paragraf.",
    tips: [
      "Mulai dengan isu: kenapa topik ini penting dibahas?",
      "Argumen pro: beri 2-3 alasan mengapa boleh",
      "Argumen kontra: beri 2-3 alasan mengapa tidak boleh",
      "Kesimpulan: ambil posisi netral atau beri rekomendasi",
    ],
    contoh: "ISU: Di zaman digital sekarang, banyak siswa SD yang sudah memiliki media sosial seperti Instagram atau TikTok. Ada yang berpendapat hal ini baik, ada juga yang mengkhawatirkannya.\n\nARGUMEN PRO: Media sosial bisa menjadi sarana belajar dan berkreasi. Siswa bisa mencari informasi pelajaran, menonton video edukasi, dan menunjukkan bakat mereka. Selain itu, media sosial juga membantu mereka tetap terhubung dengan teman.\n\nARGUMEN KONTRA: Media sosial berbahaya bagi anak SD. Banyak konten yang tidak pantas, risiko perundungan siber, dan menghabiskan waktu. Anak-anak juga bisa kecanduan sehingga lupa belajar dan bermain di dunia nyata.\n\nKESIMPULAN: Siswa SD sebaiknya boleh memiliki media sosial tetapi harus dalam pengawasan orang tua. Waktu penggunaan perlu dibatasi dan konten yang diakses harus sesuai usia.",
  },
  kuis: makeSoal([
    ["Argumen yang menentang isu disebut argumen...", ["Pro", "Kontra", "Netral", "Pendukung"], 1, "Kontra adalah argumen yang menentang atau tidak setuju."],
    ["Dalam diskusi, kita harus...", ["Memaksakan pendapat", "Berbicara bergiliran", "Mengabaikan teman", "Bicara terus"], 1, "Berbicara bergiliran adalah sikap santun dalam diskusi."],
    ["Fungsi kesimpulan dalam teks diskusi adalah...", ["Menambah argumen", "Merangkum dan memberi simpulan akhir", "Memperpanjang teks", "Memperkenalkan isu baru"], 1, "Kesimpulan merangkum isi diskusi secara keseluruhan."],
    ["'Oleh karena itu' termasuk jenis kata...", ["Penghubung", "Benda", "Sifat", "Tanya"], 0, "'Oleh karena itu' adalah kata penghubung antarkalimat."],
    ["Yang paling penting dalam diskusi adalah...", ["Menang", "Mencari kebenaran dan solusi", "Berteriak kencang", "Paling banyak bicara"], 1, "Tujuan diskusi adalah mencari solusi terbaik, bukan menang."],
    ["Teks diskusi berbeda dengan debat karena diskusi...", ["Mencari pemenang", "Menyajikan secara berimbang", "Hanya satu sisi", "Penuh emosi"], 1, "Diskusi menyajikan dua sisi secara berimbang, berbeda dengan debat."],
    ["Saat menyampaikan argumen, sebaiknya disertai...", ["Teriakan", "Alasan dan bukti", "Hinaan", "Candaan"], 1, "Argumen harus didukung alasan yang logis dan bukti."],
    ["Contoh kalimat santun saat tidak setuju adalah...", ["Kamu salah!", "Maaf, saya punya pendapat berbeda", "Tidak benar!", "Omong kosong"], 1, "Awali dengan 'maaf' lalu sampaikan pendapat berbeda."],
    ["Bagian isu berfungsi untuk...", ["Menutup diskusi", "Memperkenalkan topik", "Memberi argumen", "Menyimpulkan"], 1, "Isu berfungsi memperkenalkan topik yang akan dibahas."],
    ["Topik yang cocok untuk teks diskusi adalah...", ["Resep masakan", "Kebijakan larangan ponsel di sekolah", "Cara menggambar", "Cerita liburan"], 1, "Topik diskusi adalah isu yang memiliki pro dan kontra."],
  ]),
}
export default konten
