import type { Konten } from "../types"
import { makeSoal } from "../types"

const konten: Konten = {
  belajar: {
    tujuan: [
      "Memahami pengertian dan fungsi surat resmi",
      "Mengenal struktur surat resmi yang benar",
      "Menulis surat resmi sederhana dengan bahasa baku",
    ],
    materi: [
      {
        judul: "Mengenal Surat Resmi",
        isi: [
          "Dalam kehidupan sehari-hari, kadang kita perlu menulis surat. Ada surat untuk teman (surat pribadi) dan ada surat untuk keperluan formal. Nah, surat untuk keperluan formal disebut surat resmi!",
          "",
          "✓ Surat resmi adalah surat yang digunakan untuk keperluan formal atau kedinasan, seperti surat undangan, surat izin tidak masuk sekolah, surat permohonan, dan surat pemberitahuan.",
          "",
          "Ciri-ciri surat resmi:",
          "1. Menggunakan bahasa baku dan formal.",
          "2. Ada kop surat atau kepala surat (jika dari lembaga).",
          "3. Memiliki nomor surat, lampiran, dan perihal.",
          "4. Formatnya teratur dan rapi.",
          "5. Menggunakan stempel atau cap (jika dari instansi).",
          "",
          "PENTING: Bahasa yang digunakan dalam surat resmi haruslah bahasa Indonesia yang baik dan benar, sesuai Ejaan Yang Disempurnakan (EYD). Hindari bahasa sehari-hari atau singkatan tidak resmi!",
          "",
          "[Ilustrasi: Sebuah meja dengan amplop cokelat terbuka, di dalamnya terlihat surat resmi dengan kop surat dan stempel. Di sampingnya ada pulpen dan segel lilin merah. Gaya ilustrasi meja kerja rapi.]",
        ],
        contoh: [
          "Perbedaan surat resmi dan surat pribadi:",
          "",
          "✓ SURAT RESMI: 'Dengan hormat, kami mengundang Bapak/Ibu untuk hadir pada acara perpisahan kelas VI yang akan diselenggarakan pada hari Sabtu, 15 Juni 2026.'",
          "  — Bahasa formal, ada struktur baku, keperluan resmi.",
          "",
          "✗ SURAT PRIBADI: 'Halo Sari, gimana kabar? Aku kangen banget! Kapan kita ketemu ya?'",
          "  — Bahasa santai, akrab, tidak ada struktur formal.",
        ],
        catatan: "Surat resmi berbeda dengan surat pribadi. Surat resmi harus menggunakan bahasa baku, memiliki nomor surat, dan format yang rapi. Bayangkan surat resmi seperti seragam sekolah — harus rapi dan sesuai aturan!",
      },
      {
        judul: "Struktur Surat Resmi",
        isi: [
          "Surat resmi memiliki bagian-bagian yang harus ada. Mari kita pelajari satu per satu!",
          "",
          "1. KOP SURAT — kepala surat berisi nama lembaga, alamat, logo, nomor telepon. Hanya untuk surat dari lembaga/instansi.",
          "2. NOMOR SURAT — nomor urut surat yang dikeluarkan.",
          "3. LAMPIRAN — jumlah berkas yang disertakan (bisa ditulis '—' jika tidak ada).",
          "4. PERIHAL — judul atau pokok isi surat, misalnya 'Undangan Rapat'.",
          "5. ALAMAT TUJUAN — nama dan alamat penerima. Awali dengan 'Yth.' (Yang terhormat).",
          "6. SALAM PEMBUKA — 'Dengan hormat,' atau 'Assalamu\'alaikum Wr. Wb.'",
          "7. ISI SURAT — paragraf pembuka, isi, dan penutup.",
          "8. SALAM PENUTUP — 'Hormat kami,' atau 'Wassalamu\'alaikum Wr. Wb.'",
          "9. PENANDA TANGAN — nama jelas, jabatan, tanda tangan, stempel.",
          "",
          "Tips: Urutan ini penting! Jangan membalik-balik ya. Coba bayangkan seperti kamu merangkai puzzle — setiap bagian punya tempatnya sendiri.",
          "",
          "[Ilustrasi: Diagram surat resmi dengan setiap bagian diberi label dan panah. Kop surat di bagian atas (biru), lalu nomor dan perihal (hijau), alamat tujuan (kuning), isi surat (merah muda), dan penutup serta tanda tangan (ungu). Gaya infografis sederhana.]",
        ],
        contoh: [
          "Mari lihat struktur pada contoh surat undangan:",
          "",
          "KOP SURAT:",
          "  SD NEGERI HARAPAN BANGSA",
          "  Jalan Merdeka No. 15, Jakarta",
          "",
          "NOMOR: 001/SD-HB/V/2026",
          "LAMPIRAN: 1 lembar",
          "PERIHAL: Undangan Rapat Orang Tua",
          "",
          "Yth. Orang Tua/Wali Murid",
          "Kelas VI SD Negeri Harapan Bangsa",
          "di tempat",
          "",
          "Dengan hormat,",
          "Kami mengundang Bapak/Ibu untuk hadir pada rapat orang tua...",
          "",
          "Hormat kami,",
          "Kepala Sekolah",
          "",
          "Tips: Perhatikan penempatan setiap bagian. Alamat tujuan jangan pakai 'di' seperti 'di Jalan' — tulis langsung 'Jalan Merdeka No. 15'.",
        ],
      },
      {
        judul: "Menulis Surat Resmi",
        isi: [
          "Ayo praktik menulis surat resmi! Berikut langkah-langkahnya:",
          "",
          "1. Tentukan tujuan surat (undangan, izin, pemberitahuan, dll.).",
          "2. Tentukan penerima surat.",
          "3. Susun bagian-bagian surat dengan urutan yang benar.",
          "4. Tulis isi surat dengan jelas dan padat.",
          "5. Gunakan bahasa baku yang sopan.",
          "6. Periksa tanda baca dan ejaan.",
          "",
          "Tips penting:",
          "• Gunakan kata 'kami' jika surat dari lembaga/kelompok.",
          "• Gunakan kata 'saya' jika surat pribadi untuk keperluan resmi (contoh: surat izin sekolah).",
          "• Hindari singkatan seperti 'dll', 'dsb', 'yg' — tulis lengkap!",
          "• Jangan gunakan kata 'aku', 'kamu', 'lo', 'gue' — tidak sopan untuk surat resmi.",
          "",
          "PENTING: Surat resmi mencerminkan sikap penulis. Surat yang rapi dan menggunakan bahasa yang baik menunjukkan bahwa kita menghormati penerima surat.",
          "",
          "[Ilustrasi: Tangan anak sedang menulis surat di atas meja. Di depannya ada contoh surat izin yang sudah jadi. Di dinding ada poster 'Langkah Menulis Surat Resmi' bergambar. Gaya ilustrasi ruang kelas yang hangat.]",
        ],
        contoh: [
          "Contoh surat izin tidak masuk sekolah dari siswa:",
          "",
          "Jakarta, 12 Mei 2026",
          "",
          "Yth. Ibu Wali Kelas VI",
          "SD Negeri Harapan Bangsa",
          "di tempat",
          "",
          "Dengan hormat,",
          "Saya yang bertanda tangan di bawah ini:",
          "Nama: Aditya Pratama",
          "Kelas: VI A",
          "",
          "Memberitahukan bahwa saya tidak dapat mengikuti pelajaran pada hari Rabu, 13 Mei 2026, karena sakit. Sebagai bukti, saya lampirkan surat keterangan dokter.",
          "",
          "Demikian surat ini saya sampaikan. Atas perhatian Ibu, saya ucapkan terima kasih.",
          "",
          "Hormat saya,",
          "",
          "Aditya Pratama",
        ],
      },
    ],
    rangkuman: [
      "[Ilustrasi: Peta pikiran berbentuk amplop besar. Dari amplop keluar cabang-cabang: kop surat, nomor, lampiran, perihal, alamat, isi, penutup, tanda tangan. Setiap cabang berwarna berbeda. Gaya infografis anak.]",
      "Surat resmi adalah surat untuk keperluan formal yang menggunakan bahasa baku.",
      "Struktur surat resmi: kop surat → nomor → lampiran → perihal → alamat → salam pembuka → isi → salam penutup → tanda tangan.",
      "Gunakan bahasa baku, sopan, dan sesuai EYD. Hindari bahasa sehari-hari.",
      "Perhatikan urutan bagian surat dan kelengkapan seperti tanda tangan serta stempel (jika perlu).",
    ],
  },
  latihan: makeSoal([
    ["Surat resmi digunakan untuk keperluan...", ["Pribadi", "Formal atau kedinasan", "Santai", "Hiburan"], 1, "Surat resmi digunakan untuk keperluan formal, bukan pribadi."],
    ["Bagian yang berisi nama lembaga dan alamat disebut...", ["Perihal", "Kop surat", "Lampiran", "Nomor surat"], 1, "Kop surat adalah kepala surat berisi identitas lembaga."],
    ["'Yth.' adalah singkatan dari...", ["Yang terhormat", "Yang terakhir", "Yayasan", "Yang penting"], 0, "Yth. adalah singkatan dari 'Yang terhormat' untuk alamat tujuan."],
    ["Bahasa yang digunakan dalam surat resmi adalah...", ["Bahasa gaul", "Bahasa baku", "Bahasa daerah", "Bahasa asing"], 1, "Surat resmi harus menggunakan bahasa Indonesia baku."],
    ["Bagian yang berisi pokok isi surat secara singkat disebut...", ["Nomor surat", "Perihal", "Lampiran", "Salam"], 1, "Perihal adalah judul atau pokok isi surat."],
    ["Kata 'kami' dalam surat resmi digunakan untuk...", ["Orang seorang", "Surat dari lembaga atau kelompok", "Penerima surat", "Semua jawaban"], 1, "'Kami' dipakai jika surat berasal dari lembaga atau kelompok."],
    ["Yang BUKAN bagian surat resmi adalah...", ["Kop surat", "Salam pembuka", "Nomor surat", "Bait puisi"], 3, "Bait puisi tidak termasuk bagian surat resmi."],
    ["Salam pembuka yang tepat untuk surat resmi adalah...", ["Halo apa kabar?", "Dengan hormat,", "Hey gimana?", "Apa khabar"], 1, "'Dengan hormat,' adalah salam pembuka resmi yang sopan."],
    ["Lampiran dalam surat resmi berfungsi untuk...", ["Menambah panjang surat", "Menyebutkan jumlah berkas yang disertakan", "Menutup surat", "Membuka surat"], 1, "Lampiran berisi keterangan tentang berkas tambahan yang disertakan."],
    ["Penulisan alamat tujuan yang benar adalah...", ["Di Jalan Merdeka No. 15", "Jalan Merdeka No. 15", "Di Jl. Merdeka No. 15", "Jln. Merdeka 15"], 1, "Penulisan alamat langsung dengan nama jalan, tanpa kata 'di'."],
  ]),
  praktik: {
    petunjuk: "Buatlah surat izin tidak masuk sekolah karena alasan menghadiri acara keluarga! Gunakan struktur surat resmi yang benar: alamat, salam pembuka, isi, salam penutup, dan tanda tangan. Tulis minimal 3 paragraf.",
    tips: [
      "Tulis tempat dan tanggal surat di bagian paling atas",
      "Awali alamat dengan 'Yth.' dan nama wali kelas",
      "Jelaskan alasan izin dengan sopan dan jelas",
      "Akhiri dengan ucapan terima kasih dan tanda tangan",
    ],
    contoh: "Jakarta, 15 Mei 2026\n\nYth. Ibu Wali Kelas VI A\nSD Negeri Harapan Bangsa\ndi tempat\n\nDengan hormat,\nSaya yang bertanda tangan di bawah ini:\nNama: Siti Aisyah\nKelas: VI A\n\nMemberitahukan bahwa saya tidak dapat mengikuti pelajaran pada hari Jumat, 16 Mei 2026, karena harus menghadiri acara pernikahan kakak saya di luar kota.\n\nDemikian surat izin ini saya buat. Atas perhatian dan pengertian Ibu, saya ucapkan terima kasih.\n\nHormat saya,\n\nSiti Aisyah",
  },
  kuis: makeSoal([
    ["Surat resmi bersifat...", ["Pribadi", "Formal", "Santai", "Rahasia"], 1, "Surat resmi bersifat formal dan resmi."],
    ["Bagian nomor surat berguna untuk...", ["Hiasan", "Mengatur urutan surat", "Penutup", "Pengganti tanggal"], 1, "Nomor surat berfungsi sebagai pengatur urutan administrasi."],
    ["Jika surat tidak memiliki lampiran, maka ditulis...", ["0", "— (strip)", "Tidak ada", "Kosong"], 1, "Tanda strip (—) menunjukkan tidak ada lampiran."],
    ["'Hormat kami,' termasuk bagian...", ["Pembuka", "Salam penutup", "Isi", "Lampiran"], 1, "'Hormat kami,' adalah salam penutup surat resmi."],
    ["Bahasa baku berarti bahasa yang...", ["Santai", "Sesuai aturan dan ejaan yang benar", "Gaul", "Daerah"], 1, "Bahasa baku adalah bahasa yang sesuai dengan kaidah yang berlaku."],
    ["Kata 'saya' dalam surat izin sekolah menunjukkan...", ["Penulis surat", "Penerima surat", "Kepala sekolah", "Guru"], 0, "'Saya' merujuk pada penulis surat (siswa)."],
    ["Yang termasuk surat resmi adalah...", ["Surat untuk sahabat", "Surat undangan rapat sekolah", "Catatan untuk ibu", "Pesan singkat"], 1, "Surat undangan rapat sekolah adalah surat resmi."],
    ["Stempel dalam surat resmi biasanya terdapat pada...", ["Kop surat", "Bagian tanda tangan", "Perihal", "Salam pembuka"], 1, "Stempel / cap ditempatkan di bagian tanda tangan."],
    ["Tujuan menulis perihal surat adalah...", ["Memperindah surat", "Memudahkan penerima mengetahui pokok surat", "Mengganti nomor", "Penutup"], 1, "Perihal membantu penerima langsung mengetahui isi pokok surat."],
    ["Penulisan yang benar: 'Dengan hormat,' huruf D ditulis...", ["Kapital (D)", "Kecil (d)", "Kapital semua", "Kecil semua"], 0, "Huruf pertama 'Dengan' ditulis kapital karena awal kalimat."],
  ]),
}
export default konten
