// @ts-nocheck
import { db } from "../lib/db"

type Soal = { id: number; soal: string; opsi: string[]; jawaban: number; penjelasan: string }
type Konten = {
  belajar: { tujuan: string[]; materi: { judul: string; isi: string[]; contoh: string[]; catatan?: string }[]; rangkuman: string[] }
  latihan: Soal[]
  praktik: { petunjuk: string; tips: string[]; contoh?: string }
  kuis: Soal[]
}
function makeSoal(arr: [string, string[], number, string][]): Soal[] {
  return arr.map(([soal, opsi, jawaban, penjelasan], i) => ({ id: i + 1, soal, opsi, jawaban, penjelasan }))
}

function buatKonten(tujuan: string[], materiJudul: string, materiIsi: string[], latihanArr: [string, string[], number, string][], praktikPetunjuk: string, kuisArr: [string, string[], number, string][]): Konten {
  return {
    belajar: {
      tujuan,
      materi: [{ judul: materiJudul, isi: materiIsi, contoh: [] }],
      rangkuman: materiIsi.filter(l => l.startsWith("R:")).map(l => l.replace("R:", "")),
    },
    latihan: makeSoal(latihanArr),
    praktik: { petunjuk: praktikPetunjuk, tips: [] },
    kuis: makeSoal(kuisArr),
  }
}

const levels = [
  // === KELAS VII SEMESTER 1 ===
  {
    level: 1, grade: "VII", semester: 1, title: "Kelas VII Semester 1", description: "Teks deskripsi, fantasi, prosedur, LHO, puisi rakyat, cerpen",
    bab: [
      ["Bab 1: Teks Deskripsi", "3.1/4.1", "DESKRIPSI", ["Memahami pengertian teks deskripsi", "Mengidentifikasi struktur", "Menulis teks deskripsi"], "Apa Itu Teks Deskripsi?", ["Teks deskripsi menggambarkan objek secara detail.", "Struktur: identifikasi, klasifikasi, deskripsi bagian.", "R:Teks deskripsi menggambarkan objek secara detail.", "R:Struktur: identifikasi, klasifikasi, deskripsi bagian."], [["Teks deskripsi bertujuan...", ["Menceritakan kisah", "Menggambarkan objek", "Mengajak pembaca"], 1, ""], ["Bagian pertama teks deskripsi disebut...", ["Identifikasi", "Klasifikasi", "Deskripsi"], 0, ""]], "Tulis teks deskripsi tentang kelasmu 3-5 kalimat.", [["Teks deskripsi termasuk jenis teks...", ["Naratif", "Faktual", "Imajinatif"], 1, ""], ["Kata yang sering muncul dalam deskripsi...", ["Kata kerja", "Kata sifat", "Kata sambung"], 1, ""]]],
      ["Bab 2: Cerita Fantasi", "3.2/4.2", "FANTASI", ["Memahami cerita fantasi", "Mengidentifikasi struktur", "Menulis cerita fantasi"], "Apa Itu Cerita Fantasi?", ["Cerita fantasi mengandung unsur keajaiban.", "Struktur: orientasi, konflik, resolusi.", "R:Cerita fantasi penuh imajinasi.", "R:Struktur: orientasi, konflik, resolusi."], [["Yang termasuk ciri cerita fantasi...", ["Berdasarkan fakta", "Ada unsur keajaiban", "Tokoh nyata"], 1, ""], ["Bagian pengenalan disebut...", ["Konflik", "Orientasi", "Resolusi"], 1, ""]], "Buat cerita fantasi 3-4 kalimat tentang kucing bisa bicara.", [["Cerita fantasi berbeda karena...", ["Tokohnya hewan", "Ada unsur mustahil", "Latar sekolah"], 1, ""], ["Contoh cerita fantasi...", ["Laskar Pelangi", "Harry Potter", "Ronggeng Dukuh Paruk"], 1, ""]]],
      ["Bab 3: Teks Prosedur", "3.3/4.3", "PROSEDUR", ["Memahami teks prosedur", "Mengidentifikasi kebahasaan", "Menulis prosedur sederhana"], "Apa Itu Teks Prosedur?", ["Teks prosedur berisi langkah melakukan sesuatu.", "Ciri: kata imperatif, konjungsi temporal.", "R:Teks prosedur = langkah melakukan sesuatu.", "R:Ciri: kata imperatif dan konjungsi temporal."], [["Kalimat imperatif adalah kalimat...", ["Berita", "Perintah", "Tanya"], 1, ""], ["Kata 'pertama, kedua' termasuk...", ["Konjungsi kausal", "Konjungsi temporal", "Konjungsi tujuan"], 1, ""]], "Tulis prosedur cara menyikat gigi 4-5 langkah.", [["Tujuan teks prosedur...", ["Menghibur", "Memandu", "Menceritakan"], 1, ""], ["'Tuangkan air' termasuk kalimat...", ["Berita", "Perintah", "Seru"], 1, ""]]],
      ["Bab 4: Teks LHO", "3.4/4.4", "LAPORAN", ["Memahami teks LHO", "Mengidentifikasi struktur", "Menulis LHO"], "Apa Itu Teks LHO?", ["LHO melaporkan hasil pengamatan sistematis.", "Bersifat objektif dan faktual.", "R:LHO = laporan hasil pengamatan.", "R:Bersifat objektif dan faktual."], [["Teks LHO bersifat...", ["Subjektif", "Objektif", "Imajinatif"], 1, ""], ["Bagian pertama LHO berisi...", ["Deskripsi bagian", "Pernyataan umum", "Kesimpulan"], 1, ""]], "Observasi lingkungan sekolah, tulis 3-4 kalimat.", [["Perbedaan LHO dengan deskripsi...", ["LHO subjektif", "LHO berdasarkan data", "LHO pakai majas"], 1, ""], ["Contoh kalimat LHO...", ["Kantin itu sepertinya kotor", "Kantin memiliki 5 meja", "Saya suka kantin"], 1, ""]]],
      ["Bab 5: Puisi Rakyat", "3.5/4.5", "PUISI_RAKYAT", ["Memahami puisi rakyat", "Membedakan pantun, syair, gurindam", "Menulis pantun"], "Apa Itu Puisi Rakyat?", ["Puisi rakyat: pantun (a-b-a-b), syair (a-a-a-a), gurindam (2 baris).", "Pantun: 4 baris, sampiran dan isi.", "R:Puisi rakyat: pantun, syair, gurindam.", "R:Pantun bersajak a-b-a-b."], [["Pantun bersajak...", ["a-a-a-a", "a-b-a-b", "a-b-b-a"], 1, ""], ["Baris 1-2 pantun disebut...", ["Isi", "Sampiran", "Amanat"], 1, ""]], "Buat satu pantun tema pendidikan (a-b-a-b).", [["Syair bersajak...", ["a-b-a-b", "a-a-a-a", "a-b-b-a"], 1, ""], ["Gurindam terdiri dari...", ["4 baris", "2 baris", "6 baris"], 1, ""]]],
      ["Bab 6: Cerpen", "3.6/4.6", "CERPEN", ["Memahami cerpen", "Mengidentifikasi unsur intrinsik", "Menulis cerpen"], "Apa Itu Cerpen?", ["Cerpen: cerita sekali duduk, konflik tunggal.", "Unsur intrinsik: tema, tokoh, alur, latar, amanat.", "R:Cerpen: cerita sekali duduk.", "R:Unsur intrinsik: tema, tokoh, alur, latar, amanat."], [["Cerpen kependekan dari...", ["Cerita panjang", "Cerita pendek", "Cerita pengalaman"], 1, ""], ["Unsur 'di mana cerita terjadi' disebut...", ["Tema", "Tokoh", "Latar"], 2, ""]], "Tulis cerpen 3-5 kalimat tentang pertemuan tak terduga.", [["Yang termasuk unsur intrinsik...", ["Biografi penulis", "Tema", "Tahun terbit"], 1, ""], ["Amanat adalah...", ["Judul", "Pesan moral", "Nama tokoh"], 1, ""]]],
    ],
  },
  // === KELAS VII SEMESTER 2 ===
  {
    level: 2, grade: "VII", semester: 2, title: "Kelas VII Semester 2", description: "Surat pribadi/dinas, berita, iklan/slogan/poster, eksposisi, fiksi/nonfiksi, pantun/syair",
    bab: [
      ["Bab 1: Surat Pribadi dan Dinas", "3.7/4.7", "SURAT", ["Membedakan surat pribadi dan dinas", "Mengidentifikasi struktur", "Menulis surat"], "Jenis Surat", ["Surat pribadi: santai, tidak baku, untuk keluarga/teman.", "Surat dinas: resmi, format baku, berkop surat.", "R:Surat pribadi santai, surat dinas resmi."], [["Surat dinas menggunakan bahasa...", ["Santai", "Resmi", "Daerah"], 1, ""], ["Bagian yang ada di surat dinas saja...", ["Tanggal", "Nomor surat", "Salam"], 1, ""]], "Tulis surat pribadi untuk teman yang pindah.", [["Surat lamaran termasuk...", ["Pribadi", "Dinas", "Niaga"], 1, ""], ["Bahasa surat pribadi...", ["Baku", "Santai", "Formal"], 1, ""]]],
      ["Bab 2: Teks Berita", "3.8/4.8", "BERITA", ["Memahami unsur berita", "Mengidentifikasi 5W+1H", "Menulis berita"], "Apa Itu Berita?", ["Berita: laporan peristiwa terkini yang faktual.", "Unsur: 5W+1H (What, Who, When, Where, Why, How).", "R:Berita: laporan faktual peristiwa terkini.", "R:Unsur: 5W+1H."], [["Unsur Why menanyakan...", ["Apa", "Kapan", "Mengapa"], 2, ""], ["Kepala berita disebut...", ["Lead", "Body", "Ekor"], 0, ""]], "Tulis berita kegiatan sekolah 3-5 kalimat.", [["Berita bersifat...", ["Fiktif", "Faktual", "Subjektif"], 1, ""], ["5W+1H yang menanyakan tempat...", ["What", "Where", "When"], 1, ""]]],
      ["Bab 3: Iklan, Slogan, Poster", "3.9/4.9", "IKLAN", ["Membedakan iklan, slogan, poster", "Mengidentifikasi ciri", "Membuat iklan"], "Iklan, Slogan, Poster", ["Iklan: ajakan melalui media.", "Slogan: kalimat pendek mudah diingat.", "Poster: iklan bergambar + teks.", "R:Iklan = ajakan, Slogan = kalimat pendek, Poster = bergambar."], [["'Membaca Membuka Jendela Dunia' termasuk...", ["Iklan", "Slogan", "Poster"], 1, ""], ["Poster mengutamakan...", ["Suara", "Gambar dan teks", "Gerakan"], 1, ""]], "Buat slogan kebersihan sekolah.", [["Tujuan iklan...", ["Mendidik", "Membujuk", "Menghibur"], 1, ""], ["'Bhinneka Tunggal Ika' slogan...", ["Dagang", "Kebangsaan", "Pendidikan"], 1, ""]]],
      ["Bab 4: Teks Eksposisi", "3.10/4.10", "EKSPOSISI", ["Memahami eksposisi", "Mengidentifikasi struktur", "Menulis eksposisi"], "Apa Itu Eksposisi?", ["Eksposisi menjelaskan informasi agar pembaca tahu.", "Struktur: tesis, argumen, penegasan ulang.", "R:Eksposisi: menjelaskan informasi.", "R:Struktur: tesis, argumen, penegasan ulang."], [["Tujuan eksposisi...", ["Menghibur", "Menjelaskan", "Mendeskripsikan"], 1, ""], ["Bagian awal eksposisi disebut...", ["Argumen", "Tesis", "Penegasan"], 1, ""]], "Tulis eksposisi tentang pentingnya olahraga.", [["Eksposisi menekankan...", ["Perasaan", "Informasi", "Imajinasi"], 1, ""], ["Data dalam eksposisi berfungsi...", ["Menghias", "Memperkuat argumen", "Membingungkan"], 1, ""]]],
      ["Bab 5: Buku Fiksi dan Nonfiksi", "3.11/4.11", "FIKSI_NONFIKSI", ["Membedakan fiksi dan nonfiksi", "Mengidentifikasi unsur", "Membuat resensi"], "Fiksi vs Nonfiksi", ["Fiksi: imajinatif, hiburan, bahasa figuratif.", "Nonfiksi: faktual, informasi, bahasa denotatif.", "R:Fiksi imajinatif, nonfiksi faktual."], [["Buku pelajaran termasuk...", ["Fiksi", "Nonfiksi", "Dongeng"], 1, ""], ["Novel adalah contoh...", ["Nonfiksi", "Fiksi", "Ensiklopedia"], 1, ""]], "Sebutkan 1 fiksi dan 1 nonfiksi, jelaskan bedanya.", [["Resensi adalah...", ["Ringkasan", "Ulasan buku", "Daftar isi"], 1, ""], ["Biografi termasuk...", ["Fiksi", "Nonfiksi", "Novel"], 1, ""]]],
      ["Bab 6: Pantun dan Syair", "3.12/4.12", "PANTUN_SYAIR", ["Membedakan pantun dan syair", "Mengidentifikasi ciri", "Menulis pantun/syair"], "Pantun vs Syair", ["Pantun: a-b-a-b, sampiran + isi.", "Syair: a-a-a-a, semua baris isi.", "R:Pantun a-b-a-b, syair a-a-a-a."], [["Ciri pantun...", ["Semua isi", "Ada sampiran", "Sajak a-a-a-a"], 1, ""], ["Syair berasal dari...", ["Melayu", "Arab", "Jawa"], 1, ""]], "Buat syair 4 baris tentang semangat belajar.", [["Jumlah baris pantun dan syair...", ["2", "4", "6"], 1, ""], ["'Jika rajin membaca' termasuk baris...", ["Sampiran", "Isi", "Judul"], 1, ""]]],
    ],
  },
  // === KELAS VIII SEMESTER 1 ===
  {
    level: 3, grade: "VIII", semester: 1, title: "Kelas VIII Semester 1", description: "Berita, iklan, eksposisi, puisi, prosedur, drama",
    bab: [
      ["Bab 1: Teks Berita", "3.1/4.1", "BERITA", ["Menganalisis berita", "Menyusun berita", "Menulis berita"], "Menyusun Berita", ["Berita: 5W+1H, struktur: judul, lead, isi, penutup.", "Bahasa: singkat, padat, objektif.", "R:Berita: 5W+1H, objektif."], [["Bagian terpenting berita...", ["Judul", "Lead", "Penutup"], 1, ""], ["'Mengapa' adalah unsur...", ["What", "Why", "When"], 1, ""]], "Tulis berita HUT RI di sekolah.", [["Berita harus bersifat...", ["Subjektif", "Objektif", "Menghibur"], 1, ""], ["Lead berisi...", ["Kesimpulan", "Inti berita", "Opini"], 1, ""]]],
      ["Bab 2: Iklan, Slogan, Poster", "3.2/4.2", "IKLAN", ["Menganalisis iklan", "Mengidentifikasi persuasi", "Membuat iklan"], "Unsur Persuasif", ["Iklan: bahasa menarik + visual.", "Kata imperatif dan ajakan.", "R:Iklan: bahasa persuasif + visual."], [["Kata 'Ayo' termasuk...", ["Imperatif", "Interogatif", "Deklaratif"], 0, ""], ["Poster termasuk media...", ["Audio", "Visual", "Audiovisual"], 1, ""]], "Buat poster tentang bahaya merokok.", [["Iklan baik harus...", ["Panjang", "Menarik perhatian", "Mahal"], 1, ""], ["'Hemat listrik' termasuk...", ["Iklan", "Slogan", "Poster"], 1, ""]]],
      ["Bab 3: Teks Eksposisi", "3.3/4.3", "EKSPOSISI", ["Menganalisis struktur eksposisi", "Mengembangkan argumen", "Menulis eksposisi"], "Mengembangkan Eksposisi", ["Tesis: pendapat penulis.", "Argumen: data dan fakta.", "Penegasan ulang: kesimpulan.", "R:Eksposisi: tesis → argumen → penegasan."], [["Bagian pendapat penulis disebut...", ["Argumen", "Tesis", "Penegasan"], 1, ""], ["Fungsi argumen...", ["Menghias", "Memperkuat pendapat", "Menceritakan"], 1, ""]], "Tulis eksposisi 'Manfaat Membaca' 2 argumen.", [["Eksposisi bersifat...", ["Subjektif", "Informatif", "Fiktif"], 1, ""], ["Penegasan ulang di...", ["Awal", "Akhir", "Tengah"], 1, ""]]],
      ["Bab 4: Puisi", "3.4/4.4", "PUISI", ["Memahami unsur puisi", "Menganalisis makna", "Menulis puisi"], "Unsur Puisi", ["Diksi: pilihan kata.", "Imaji: gambaran (penglihatan, pendengaran).", "Majas: personifikasi, metafora, simile.", "R:Unsur: diksi, imaji, majas, rima."], [["'Angin berbisik' mengandung majas...", ["Personifikasi", "Metafora", "Simile"], 0, ""], ["Pilihan kata dalam puisi disebut...", ["Rima", "Diksi", "Imaji"], 1, ""]], "Tulis puisi 4 baris tema alam.", [["'Bagai air di daun talas' majas...", ["Personifikasi", "Simile", "Metafora"], 1, ""], ["Imaji penglihatan berkaitan...", ["Suara", "Warna/bentuk", "Rasa"], 1, ""]]],
      ["Bab 5: Teks Prosedur", "3.5/4.5", "PROSEDUR", ["Menganalisis prosedur", "Kebahasaan", "Menulis prosedur"], "Struktur Prosedur", ["Tujuan, bahan/alat, langkah-langkah.", "Kata imperatif, temporal.", "R:Prosedur: tujuan, bahan, langkah."], [["Tujuan prosedur...", ["Menghibur", "Memandu", "Menceritakan"], 1, ""], ["'Pertama, kedua' konjungsi...", ["Kausal", "Temporal", "Tujuan"], 1, ""]], "Tulis prosedur daftar email 5-6 langkah.", [["'Siapkan alat' kalimat...", ["Berita", "Imperatif", "Tanya"], 1, ""], ["Bagian tujuan berisi...", ["Cara", "Hasil akhir", "Bahan"], 1, ""]]],
      ["Bab 6: Drama", "3.6/4.6", "DRAMA", ["Memahami struktur drama", "Mengidentifikasi tokoh", "Menulis naskah"], "Apa Itu Drama?", ["Drama: cerita dipentaskan.", "Unsur: tokoh, dialog, latar, konflik.", "Naskah: dialog + petunjuk laku.", "R:Drama: cerita dipentaskan."], [["Petunjuk laku ditulis dalam...", ["Kutipan", "Kurung", "Cetak tebal"], 1, ""], ["Inti drama adalah...", ["Dialog", "Konflik", "Latar"], 1, ""]], "Tulis naskah drama 2 tokoh tentang study tour.", [["Yang membedakan drama-cerpen...", ["Ada tokoh", "Ada pementasan", "Ada latar"], 1, ""], ["'(tersenyum)' disebut...", ["Dialog", "Petunjuk laku", "Judul"], 1, ""]]],
    ],
  },
  // === KELAS VIII SEMESTER 2 ===
  {
    level: 4, grade: "VIII", semester: 2, title: "Kelas VIII Semester 2", description: "Ulasan, persuasi, drama, fiksi/nonfiksi, surat resmi, tanggapan",
    bab: [
      ["Bab 1: Teks Ulasan", "3.7/4.7", "ULASAN", ["Memahami ulasan", "Mengidentifikasi struktur", "Menulis ulasan"], "Apa Itu Ulasan?", ["Ulasan: teks yang mengulas karya (buku, film).", "Struktur: identitas, orientasi, sinopsis, analisis, evaluasi.", "R:Ulasan: identitas → orientasi → sinopsis → analisis → evaluasi."], [["Bagian evaluasi berisi...", ["Ringkasan", "Kelebihan/kekurangan", "Identitas"], 1, ""], ["Sinopsis berisi...", ["Analisis", "Ringkasan cerita", "Kritik"], 1, ""]], "Tulis ulasan film/novel favorit 3-5 kalimat.", [["Ulasan baik bersifat...", ["Memuji", "Objektif", "Menyalahkan"], 1, ""], ["Teks ulasan termasuk...", ["Naratif", "Ekspositori", "Deskripsi"], 1, ""]]],
      ["Bab 2: Teks Persuasi", "3.8/4.8", "PERSUASI", ["Memahami persuasi", "Mengidentifikasi ajakan", "Menulis persuasi"], "Apa Itu Persuasi?", ["Persuasi: membujuk pembaca.", "Kata ajakan, argumen logis dan emosional.", "R:Persuasi: membujuk pembaca."], [["Tujuan persuasi...", ["Menghibur", "Membujuk", "Mendidik"], 1, ""], ["Kata 'Mari' termasuk...", ["Berita", "Ajakan", "Tanya"], 1, ""]], "Tulis teks persuasi tentang hidup sehat.", [["Persuasi vs prosedur...", ["Ada langkah", "Bertujuan membujuk", "Ada bahan"], 1, ""], ["'Kurangi gula' bagian...", ["Pengantar", "Ajakan", "Argumen"], 1, ""]]],
      ["Bab 3: Drama", "3.9/4.9", "DRAMA", ["Menganalisis naskah", "Karakter tokoh", "Pementasan"], "Mementaskan Drama", ["Penghayatan, ekspresi, blocking.", "Intonasi sesuai karakter.", "R:Pementasan: ekspresi, blocking, penghayatan."], [["Gerakan pemain di panggung...", ["Ekspresi", "Blocking", "Improvisasi"], 1, ""], ["Intonasi berkaitan...", ["Gerakan", "Volume suara", "Posisi"], 1, ""]], "Latih adegan drama pendek dengan teman.", [["Yang bukan unsur pementasan...", ["Penonton", "Naskah", "Kostum"], 0, ""], ["Mimik wajah termasuk...", ["Ekspresi", "Blocking", "Tata rias"], 0, ""]]],
      ["Bab 4: Fiksi/Nonfiksi", "3.10/4.10", "FIKSI_NONFIKSI", ["Membandingkan fiksi/nonfiksi", "Unsur buku", "Resensi"], "Membandingkan Buku", ["Fiksi: imajinasi, hiburan.", "Nonfiksi: fakta, informasi.", "R:Fiksi imajinatif, nonfiksi faktual."], [["Bahasa fiksi cenderung...", ["Denotatif", "Figuratif", "Ilmiah"], 1, ""], ["Tujuan resensi...", ["Membujuk", "Mengulas kritis", "Menghibur"], 1, ""]], "Bandingkan 1 fiksi dan 1 nonfiksi.", [["Daftar isi ada di buku...", ["Fiksi", "Nonfiksi", "Novel"], 1, ""], ["Novel termasuk...", ["Nonfiksi", "Fiksi", "Ensiklopedia"], 1, ""]]],
      ["Bab 5: Surat Resmi", "3.11/4.11", "SURAT", ["Struktur surat resmi", "Jenis surat", "Menulis surat resmi"], "Menulis Surat Resmi", ["Kop surat, nomor, perihal, alamat, isi, ttd.", "Bahasa baku dan formal.", "R:Surat resmi: kop, nomor, perihal, isi, ttd."], [["Lampiran berisi...", ["Foto", "Dokumen tambahan", "Tanggal"], 1, ""], ["'Yth.' singkatan...", ["Yang Terhormat", "Yayasan", "Yakin"], 0, ""]], "Tulis surat izin sakit format resmi.", [["Pembeda surat resmi-pribadi...", ["Panjang", "Format baku", "Isi"], 1, ""], ["Bahasa surat resmi...", ["Santai", "Baku", "Daerah"], 1, ""]]],
      ["Bab 6: Teks Tanggapan", "3.12/4.12", "TANGGAPAN", ["Memahami tanggapan", "Kritik dan pujian", "Menulis tanggapan"], "Apa Itu Tanggapan?", ["Tanggapan: kritik/pujian beralasan.", "Struktur: konteks, deskripsi, penilaian.", "R:Tanggapan: konteks → deskripsi → penilaian."], [["Tanggapan harus disertai...", ["Alasan", "Emosi", "Teriakan"], 0, ""], ["'Kantin bersih' tanggapan...", ["Kritik", "Pujian", "Hinaan"], 1, ""]], "Tulis tanggapan tentang 'tugas tanpa kertas'.", [["Tanggapan baik bersifat...", ["Subjektif", "Logis", "Provokatif"], 1, ""], ["Deskripsi berisi...", ["Pendapat", "Gambaran objek", "Alasan"], 1, ""]]],
    ],
  },
  // === KELAS IX SEMESTER 1 ===
  {
    level: 5, grade: "IX", semester: 1, title: "Kelas IX Semester 1", description: "Laporan percobaan, pidato persuasi, cerpen, tanggapan, diskusi, puisi",
    bab: [
      ["Bab 1: Laporan Percobaan", "3.1/4.1", "LAPORAN", ["Memahami laporan percobaan", "Struktur", "Menulis laporan"], "Laporan Percobaan", ["Laporan percobaan: hasil eksperimen ilmiah.", "Struktur: tujuan, alat, langkah, hasil, kesimpulan.", "R:Laporan: tujuan → alat → langkah → hasil → kesimpulan."], [["Bagian hasil berisi...", ["Alat", "Data pengamatan", "Cara"], 1, ""], ["Sumber laporan percobaan...", ["Opini", "Eksperimen", "Imajinasi"], 1, ""]], "Lakukan percobaan baking soda + cuka, tulis laporan.", [["Struktur laporan yang benar...", ["Tujuan-langkah-hasil", "Tujuan-alat-langkah-hasil-kesimpulan", "Judul-alat-cara"], 1, ""], ["Kesimpulan berisi...", ["Alat", "Hasil dan maknanya", "Langkah"], 1, ""]]],
      ["Bab 2: Pidato Persuasif", "3.2/4.2", "PIDATO", ["Struktur pidato", "Kalimat persuasif", "Menulis naskah"], "Menyusun Naskah Pidato", ["Pembukaan: salam, syukur.", "Isi: pesan, argumen, ajakan.", "Penutup: kesimpulan, salam.", "R:Pidato: pembukaan, isi, penutup."], [["Bagian inti pidato...", ["Pembukaan", "Isi", "Penutup"], 1, ""], ["'Marilah kita' kalimat...", ["Berita", "Ajakan", "Tanya"], 1, ""]], "Tulis naskah pidato tentang disiplin.", [["Pidato baik disesuaikan...", ["Keinginan", "Audiens", "Pembicara"], 1, ""], ["Salam penutup...", ["Assalamualaikum", "Wassalamualaikum", "Halo"], 1, ""]]],
      ["Bab 3: Cerpen", "3.3/4.3", "CERPEN", ["Unsur ekstrinsik cerpen", "Menulis cerpen", "Tanggapan"], "Unsur Ekstrinsik", ["Ekstrinsik: latar penulis, sosial, budaya.", "Mempengaruhi isi dan pesan.", "R:Unsur ekstrinsik: dari luar cerita."], [["Unsur ekstrinsik berasal...", ["Dalam cerita", "Luar cerita", "Tokoh"], 1, ""], ["Contoh ekstrinsik...", ["Tema", "Latar penulis", "Alur"], 1, ""]], "Analisis cerpen: intrinsik dan ekstrinsik.", [["Yang termasuk ekstrinsik...", ["Tema", "Latar penulis", "Tokoh"], 1, ""]]],
      ["Bab 4: Teks Tanggapan", "3.4/4.4", "TANGGAPAN", ["Tanggapan kritis", "Memberi tanggapan", "Menulis tanggapan"], "Tanggapan Kritis", ["Identifikasi isu, evaluasi, saran.", "Beralasan dan membangun.", "R:Tanggapan kritis: identifikasi → evaluasi → saran."], [["Tanggapan kritis bersifat...", ["Menyalahkan", "Membangun", "Marah"], 1, ""], ["Saran bersifat...", ["Perintah", "Usulan", "Paksaan"], 1, ""]], "Tanggapi 'makan sambil main HP'.", [["Tanggapan baik...", ["Emosional", "Logis", "Kasar"], 1, ""]]],
      ["Bab 5: Teks Diskusi", "3.5/4.5", "DISKUSI", ["Memahami diskusi", "Argumen pro/kontra", "Menulis diskusi"], "Apa Itu Diskusi?", ["Diskusi: dua sudut pandang (pro, kontra).", "Struktur: isu, pro, kontra, kesimpulan.", "R:Diskusi: isu → pro → kontra → kesimpulan."], [["Teks diskusi menyajikan...", ["Satu sisi", "Dua sisi", "Tiga sisi"], 1, ""], ["Kesimpulan bersifat...", ["Memihak", "Seimbang", "Marah"], 1, ""]], "Tulis diskusi 'gawai di sekolah'.", [["Konjungsi untuk kontra...", ["Dan", "Namun", "Lalu"], 1, ""]]],
      ["Bab 6: Puisi", "3.6/4.6", "PUISI", ["Menganalisis makna puisi", "Majas", "Menulis puisi"], "Menganalisis Puisi", ["Tema, rasa, nada, amanat.", "Empat aspek analisis.", "R:Analisis: tema, rasa, nada, amanat."], [["Rasa berkaitan...", ["Ide", "Perasaan penyair", "Bunyi"], 1, ""], ["Amanat disebut juga...", ["Tema", "Pesan", "Nada"], 1, ""]], "Analisis puisi 'Aku Ingin' Sapardi.", [["Nada adalah...", ["Sajak", "Sikap penyair", "Pilihan kata"], 1, ""]]],
    ],
  },
  // === KELAS IX SEMESTER 2 ===
  {
    level: 6, grade: "IX", semester: 2, title: "Kelas IX Semester 2", description: "Eksplanasi, laporan, drama, resensi, artikel, KTI",
    bab: [
      ["Bab 1: Teks Eksplanasi", "3.7/4.7", "EKSPLANASI", ["Memahami eksplanasi", "Struktur kausal", "Menulis eksplanasi"], "Apa Itu Eksplanasi?", ["Eksplanasi: proses terjadinya fenomena.", "Struktur: pernyataan, sebab-akibat, interpretasi.", "R:Eksplanasi: pernyataan → sebab-akibat → interpretasi."], [["Eksplanasi menjelaskan...", ["Cara", "Proses terjadinya", "Kisah"], 1, ""], ["'Akibatnya' konjungsi...", ["Temporal", "Kausal", "Tujuan"], 1, ""]], "Tulis eksplanasi proses hujan.", [["Interpretasi berisi...", ["Data", "Kesimpulan/saran", "Alat"], 1, ""]]],
      ["Bab 2: Laporan", "3.8/4.8", "LAPORAN", ["Kebahasaan laporan", "Menyusun laporan", "Presentasi"], "Kebahasaan Laporan", ["Kata kerja aktif, data tabel/grafik.", "Kesimpulan menjawab tujuan.", "R:Laporan: data, kesimpulan."], [["Kata 'mengukur' termasuk...", ["Kata sifat", "Kata kerja aktif", "Kata benda"], 1, ""], ["Kesimpulan harus...", ["Panjang", "Menjawab tujuan", "Opini"], 1, ""]], "Laporan mini kebiasaan membaca 5 orang.", [["Data berguna untuk...", ["Hiasan", "Dasar kesimpulan", "Opini"], 1, ""]]],
      ["Bab 3: Drama", "3.9/4.9", "DRAMA", ["Menulis naskah", "Mengembangkan konflik", "Pementasan"], "Menulis Naskah Drama", ["Tema, tokoh, sinopsis, dialog, petunjuk laku.", "Konflik sebagai inti.", "R:Naskah: tema, tokoh, sinopsis, dialog."], [["Petunjuk laku dalam...", ["Kurung", "Kutip", "Tebal"], 0, ""], ["Latar meliputi...", ["Tempat waktu suasana", "Tema tokoh", "Dialog babak"], 0, ""]], "Tulis naskah 2 tokoh 1 adegan kerja sama.", [["Pesan drama disebut...", ["Tema", "Amanat", "Alur"], 1, ""]]],
      ["Bab 4: Resensi", "3.10/4.10", "RESENSI", ["Memahami resensi", "Menganalisis", "Menulis resensi"], "Menulis Resensi", ["Identitas, orientasi, sinopsis, analisis, evaluasi.", "Bahasa kritis objektif.", "R:Resensi: identitas → orientasi → sinopsis → analisis → evaluasi."], [["Bagian ringkasan cerita...", ["Analisis", "Sinopsis", "Orientasi"], 1, ""], ["Evaluasi berisi...", ["Ringkasan", "Penilaian/rekomendasi", "Identitas"], 1, ""]], "Tulis resensi buku pelajaran B. Indonesia.", [["Resensi baik bersifat...", ["Memuji", "Objektif", "Subjektif"], 1, ""]]],
      ["Bab 5: Artikel", "3.11/4.11", "ARTIKEL", ["Memahami artikel", "Fakta dan opini", "Menulis artikel"], "Artikel Ilmiah Populer", ["Informasi ilmiah bahasa populer.", "Struktur: judul, pendahuluan, isi, penutup.", "R:Artikel: ilmiah + bahasa populer."], [["Artikel populer vs laporan...", ["Ada data", "Ada opini", "Formal"], 1, ""], ["Judul harus...", ["Panjang", "Menarik", "Baku"], 1, ""]], "Tulis artikel 'Cara Meningkatkan Konsentrasi'.", [["Sumber artikel sebaiknya...", ["Opini", "Penelitian", "Gosip"], 1, ""]]],
      ["Bab 6: Karya Tulis Ilmiah", "3.12/4.12", "KTI", ["Memahami KTI", "Struktur KTI", "Menulis KTI"], "Apa Itu KTI?", ["KTI: tulisan berdasarkan penelitian.", "Struktur: pendahuluan, teori, metodologi, pembahasan, penutup.", "R:KTI: pendahuluan → teori → metode → pembahasan → penutup."], [["Rumusan masalah di bab...", ["I", "II", "III"], 0, ""], ["Teori pendukung di...", ["Pendahuluan", "Kajian teori", "Metode"], 1, ""]], "Buat kerangka KTI 'Pengaruh Medsos pada Prestasi'.", [["KTI bersumber dari...", ["Opini", "Data penelitian", "Cerita"], 1, ""]]],
    ],
  },
  // === KELAS X SEMESTER 1 ===
  {
    level: 7, grade: "X", semester: 1, title: "Kelas X Semester 1", description: "LHO, eksposisi, anekdot, hikayat, negosiasi, debat",
    bab: [
      ["Bab 1: Teks LHO", "3.1/4.1", "LAPORAN", ["LHO tingkat lanjut", "Data kualitatif/kuantitatif", "Menulis LHO"], "LHO Tingkat Lanjut", ["Observasi sistematis terencana.", "Data kualitatif (sifat) + kuantitatif (angka).", "R:LHO: data kualitatif + kuantitatif."], [["Data angka disebut...", ["Kualitatif", "Kuantitatif", "Deskriptif"], 1, ""], ["'Kantin ramai' data...", ["Kuantitatif", "Kualitatif", "Statistik"], 1, ""]], "Observasi perpustakaan, catat 2 jenis data.", [["Observasi sistematis artinya...", ["Acak", "Terencana", "Cepat"], 1, ""]]],
      ["Bab 2: Eksposisi", "3.2/4.2", "EKSPOSISI", ["Argumen kompleks", "Menganalisis", "Menulis eksposisi"], "Eksposisi Analitis", ["Tesis, argumen data/fakta, penegasan.", "Konjungsi argumentatif.", "R:Eksposisi analitis: tesis → argumen → penegasan."], [["'Oleh karena itu' konjungsi...", ["Temporal", "Argumentatif", "Kausal"], 1, ""], ["Tujuan eksposisi analitis...", ["Mendeskripsikan", "Menyakinkan", "Menghibur"], 1, ""]], "Tulis eksposisi 'Pendidikan Karakter' 2 argumen.", [["Eksposisi vs persuasi...", ["Eksposisi logis", "Ada data", "Sama"], 0, ""]]],
      ["Bab 3: Anekdot", "3.3/4.3", "ANEKDOT", ["Memahami anekdot", "Struktur humor", "Menulis anekdot"], "Apa Itu Anekdot?", ["Anekdot: cerita lucu + kritik.", "Struktur: abstraksi, orientasi, krisis, reaksi, koda.", "R:Anekdot: lucu + kritik."], [["Tujuan anekdot...", ["Menghibur", "Kritik dengan humor", "Mendidik"], 1, ""], ["Krisis berisi...", ["Pembuka", "Konflik lucu", "Penutup"], 1, ""]], "Tulis anekdot tentang kemacetan.", [["Anekdot termasuk teks...", ["Naratif", "Ekspositori", "Deskripsi"], 0, ""]]],
      ["Bab 4: Hikayat", "3.4/4.4", "HIKAYAT", ["Memahami hikayat", "Karakteristik", "Perbandingan"], "Apa Itu Hikayat?", ["Hikayat: cerita Melayu klasik.", "Ciri: istana sentris, kesatria, kemustahilan.", "R:Hikayat: cerita Melayu klasik istana."], [["Latar hikayat biasanya...", ["Istana", "Sekolah", "Pasar"], 0, ""], ["'Hatta' artinya...", ["Maka", "Dan", "Tetapi"], 0, ""]], "Bandingkan hikayat dan cerpen modern.", [["Kemustahilan artinya...", ["Logis", "Tidak masuk akal", "Nyata"], 1, ""]]],
      ["Bab 5: Negosiasi", "3.5/4.5", "NEGOSIASI", ["Memahami negosiasi", "Struktur", "Bernegosiasi"], "Apa Itu Negosiasi?", ["Negosiasi: tawar-menawar untuk sepakat.", "Struktur: orientasi, pengajuan, penawaran, kesepakatan.", "R:Negosiasi: orientasi → pengajuan → penawaran → sepakat."], [["Tujuan negosiasi...", ["Menang sendiri", "Kesepakatan bersama", "Bertengkar"], 1, ""], ["Penawaran berisi...", ["Salam", "Tawar-menawar", "Penutup"], 1, ""]], "Buat teks negosiasi jual-beli di pasar.", [["Ciri kebahasaan negosiasi...", ["Imperatif", "Persuasif", "Deklaratif"], 1, ""]]],
      ["Bab 6: Debat", "3.6/4.6", "DEBAT", ["Memahami debat", "Unsur debat", "Berdebat"], "Apa Itu Debat?", ["Debat: adu argumen pro vs kontra.", "Unsur: mosi, tim pro, kontra, moderator.", "R:Debat: pro vs kontra, mosi, moderator."], [["Topik debat disebut...", ["Mosi", "Tim", "Argumen"], 0, ""], ["Tugas moderator...", ["Berdebat", "Mengatur debat", "Menilai"], 1, ""]], "Buat argumen pro-kontra 'Medsos Negatif'.", [["Yang bukan unsur debat...", ["Mosi", "Penonton", "Tim pro"], 1, ""]]],
    ],
  },
  // === KELAS X SEMESTER 2 ===
  {
    level: 8, grade: "X", semester: 2, title: "Kelas X Semester 2", description: "Biografi, puisi, cerpen, fiksi/nonfiksi, pantun/syair, prosedur kompleks",
    bab: [
      ["Bab 1: Biografi", "3.7/4.7", "BIOGRAFI", ["Memahami biografi", "Struktur", "Menulis biografi"], "Apa Itu Biografi?", ["Biografi: riwayat hidup oleh orang lain.", "Struktur: orientasi, peristiwa, reorientasi.", "R:Biografi: orientasi → peristiwa → reorientasi."], [["Biografi ditulis oleh...", ["Diri sendiri", "Orang lain", "Pemerintah"], 1, ""], ["Reorientasi berisi...", ["Kesimpulan", "Pandangan penulis", "Peristiwa"], 1, ""]], "Tulis biografi pahlawan/idola 4-5 kalimat.", [["Otobiografi ditulis...", ["Orang lain", "Diri sendiri", "Pengarang"], 1, ""]]],
      ["Bab 2: Puisi Kontemporer", "3.8/4.8", "PUISI", ["Puisi kontemporer", "Perbandingan", "Menulis puisi"], "Puisi Kontemporer", ["Puisi modern bebas ikatan tradisional.", "Tipografi (bentuk visual), makna simbolis.", "R:Puisi kontemporer: bebas rima, tipografi."], [["Puisi kontemporer tidak terikat...", ["Makna", "Rima", "Tema"], 1, ""], ["Tipografi adalah...", ["Bunyi", "Bentuk visual", "Majas"], 1, ""]], "Tulis puisi kontemporer 6 baris.", [["Penyair kontemporer...", ["Chairil Anwar", "WS Rendra", "Hamka"], 1, ""]]],
      ["Bab 3: Cerpen", "3.9/4.9", "CERPEN", ["Alur kompleks", "Konflik", "Mengedit cerpen"], "Teknik Menulis Cerpen", ["Alur: maju, mundur, campuran.", "Konflik: internal (batin), eksternal.", "Sudut pandang: pertama, ketiga.", "R:Alur, konflik, sudut pandang."], [["'Ia berjalan' sudut pandang...", ["Pertama", "Ketiga", "Kedua"], 1, ""], ["Konflik batin disebut...", ["Eksternal", "Internal", "Fisik"], 1, ""]], "Tulis cerpen 1 paragraf konflik internal.", [["Alur mundur artinya...", ["Dari awal", "Flashback", "Campuran"], 1, ""]]],
      ["Bab 4: Fiksi/Nonfiksi", "3.10/4.10", "FIKSI_NONFIKSI", ["Nilai buku", "Keunggulan", "Resensi kritis"], "Nilai dalam Buku", ["Moral, sosial, budaya, estetika.", "Resensi kritis: analisis nilai.", "R:Nilai: moral, sosial, budaya, estetika."], [["Nilai keindahan disebut...", ["Moral", "Estetika", "Sosial"], 1, ""], ["Nilai sosial berkaitan...", ["Individu", "Hubungan masyarakat", "Politik"], 1, ""]], "Analisis 2 nilai dari novel favorit.", [["Analisis nilai berguna...", ["Menghibur", "Resensi", "Promosi"], 1, ""]]],
      ["Bab 5: Pantun/Syair", "3.11/4.11", "PANTUN_SYAIR", ["Nilai budaya", "Mencipta", "Menganalisis"], "Nilai Pantun Syair", ["Nilai agama, moral, sosial, pendidikan.", "Sarana nasihat dan hiburan.", "R:Pantun/syair: nilai agama, moral, sosial, pendidikan."], [["'Rajin membaca' nilai...", ["Agama", "Pendidikan", "Sosial"], 1, ""], ["Pantun sering untuk...", ["Cerita", "Nasihat/hiburan", "Laporan"], 1, ""]], "Ciptakan 2 pantun: pendidikan + persahabatan.", [["Syair dominan mengandung...", ["Humor", "Nasihat", "Kritik"], 1, ""]]],
      ["Bab 6: Prosedur Kompleks", "3.12/4.12", "PROSEDUR", ["Prosedur kompleks", "Kebahasaan", "Menulis"], "Prosedur Kompleks", ["Banyak langkah + sub-langkah.", "Konjungsi syarat: jika, apabila.", "R:Prosedur kompleks: sub-langkah + syarat."], [["Ciri prosedur kompleks...", ["3 langkah", "Sub-langkah", "1 langkah"], 1, ""], ["Konjungsi syarat...", ["Dan", "Apabila", "Lalu"], 1, ""]], "Tulis prosedur daftar kuliah 5+ langkah.", [["Prosedur kompleks di...", ["Resep", "Panduan resmi", "Catatan"], 1, ""]]],
    ],
  },
  // === KELAS XI SEMESTER 1 ===
  {
    level: 9, grade: "XI", semester: 1, title: "Kelas XI Semester 1", description: "Prosedur, eksplanasi, ceramah, cerpen, puisi, drama",
    bab: [
      ["Bab 1: Prosedur", "3.1/4.1", "PROSEDUR", ["Menganalisis", "Menyempurnakan", "Presentasi"], "Penyempurnaan Prosedur", ["Cek tujuan, alat, langkah.", "Urutan logis, bahasa imperatif.", "R:Prosedur: lengkap, urut, imperatif."], [["Langkah prosedur harus...", ["Acak", "Urut", "Pendek"], 1, ""], ["'Potong, tempel' kata...", ["Sifat", "Kerja imperatif", "Benda"], 1, ""]], "Sempurnakan teks prosedur + ilustrasi.", [["Ilustrasi berfungsi...", ["Hiasan", "Memperjelas", "Memanjangkan"], 1, ""]]],
      ["Bab 2: Eksplanasi", "3.2/4.2", "EKSPLANASI", ["Eksplanasi kompleks", "Kausal berantai", "Menulis"], "Eksplanasi Kompleks", ["Fenomena alam dan sosial.", "Kausal berantai: A→B→C.", "R:Eksplanasi: hubungan kausal berantai."], [["Eksplanasi sosial contoh...", ["Gempa", "Kemacetan", "Gunung"], 1, ""], ["Rantai kausal artinya...", ["Satu sebab", "Sebab-akibat berantai", "Acak"], 1, ""]], "Tulis eksplanasi kemacetan 3 tingkat.", [["Interpretasi berisi...", ["Data", "Pandangan penulis", "Langkah"], 1, ""]]],
      ["Bab 3: Ceramah", "3.3/4.3", "CERAMAH", ["Memahami ceramah", "Struktur", "Menulis naskah"], "Apa Itu Ceramah?", ["Ceramah: pidato pengetahuan/agama.", "Struktur: pembukaan, isi, penutup.", "R:Ceramah: pembukaan, isi, penutup."], [["Ceramah termasuk pidato...", ["Persuasif", "Informatif", "Hiburan"], 1, ""], ["Salam pembuka...", ["Terima kasih", "Assalamualaikum", "Halo"], 1, ""]], "Tulis naskah ceramah 'Kejujuran' 3 paragraf.", [["Ceramah vs pidato...", ["Sama", "Ceramah lebih religius", "Pidato panjang"], 1, ""]]],
      ["Bab 4: Cerpen", "3.4/4.4", "CERPEN", ["Nilai cerpen", "Mengapresiasi", "Menulis"], "Nilai Cerpen", ["Moral, sosial, budaya, estetika.", "Apresiasi: menghargai nilai.", "R:Nilai: moral, sosial, budaya, estetika."], [["Nilai budaya berkaitan...", ["Individu", "Tradisi", "Agama"], 1, ""], ["Nilai estetika berkaitan...", ["Pesan", "Keindahan", "Sejarah"], 1, ""]], "Analisis nilai cerpen 'Senyum Karyamin'.", [["Apresiasi cerpen berarti...", ["Menghafal", "Menghargai nilai", "Mengkritik"], 1, ""]]],
      ["Bab 5: Puisi Angkatan", "3.5/4.5", "PUISI", ["Puisi angkatan 66", "Membandingkan", "Mengapresiasi"], "Puisi Angkatan 66", ["Lahir setelah G30S, kritik sosial.", "Penyair: Rendra, Taufiq Ismail.", "R:Angkatan 66: kritik sosial politik."], [["Angkatan 66 setelah...", ["Kemerdekaan", "G30S", "Reformasi"], 1, ""], ["Ciri puisi 66...", ["Cinta", "Kritik sosial", "Alam"], 1, ""]], "Analisis puisi Rendra/Taufiq Ismail.", [["Penyair angkatan 66...", ["Chairil Anwar", "WS Rendra", "Hamka"], 1, ""]]],
      ["Bab 6: Drama", "3.6/4.6", "DRAMA", ["Analisis naskah", "Apresiasi", "Kritik drama"], "Kritik Drama", ["Analisis naskah + pementasan.", "Kelebihan dan kekurangan.", "R:Kritik: naskah + pementasan."], [["Aspek penilaian drama...", ["Harga tiket", "Akting", "Penonton"], 1, ""], ["Tata panggung termasuk...", ["Naskah", "Pementasan", "Promosi"], 1, ""]], "Tulis kritik drama yang ditonton.", [["Kritik drama bersifat...", ["Menghina", "Membangun", "Memuji"], 1, ""]]],
    ],
  },
  // === KELAS XI SEMESTER 2 ===
  {
    level: 10, grade: "XI", semester: 2, title: "Kelas XI Semester 2", description: "Artikel, resensi, proposal, KTI, novel, debat",
    bab: [
      ["Bab 1: Artikel", "3.7/4.7", "ARTIKEL", ["Menganalisis", "Opini/fakta", "Menulis artikel"], "Menulis Artikel Opini", ["Judul, pendahuluan, isi, penutup.", "Fakta (data) + opini (pendapat).", "R:Artikel: judul → pendahuluan → isi → penutup."], [["'AQI 200' termasuk...", ["Opini", "Fakta", "Saran"], 1, ""], ["Kesimpulan di...", ["Awal", "Akhir", "Tengah"], 1, ""]], "Tulis artikel 'Pentingnya Literasi Digital'.", [["Artikel vs berita...", ["Faktual", "Ada opini", "Singkat"], 1, ""]]],
      ["Bab 2: Resensi", "3.8/4.8", "RESENSI", ["Analisis resensi", "Menilai", "Menulis resensi"], "Resensi Kritis", ["Identitas, orientasi, sinopsis.", "Analisis: gaya bahasa, karakter.", "Evaluasi: perbandingan.", "R:Resensi kritis: analisis + perbandingan."], [["Resensi vs sinopsis...", ["Ada ringkasan", "Ada analisis", "Panjang"], 1, ""], ["Perbandingan buku lain termasuk...", ["Sinopsis", "Evaluasi", "Identitas"], 1, ""]], "Tulis resensi kritis novel favorit.", [["Resensi baik tidak...", ["Objektif", "Memihak", "Kritis"], 1, ""]]],
      ["Bab 3: Proposal", "3.9/4.9", "PROPOSAL", ["Memahami proposal", "Struktur", "Menulis proposal"], "Apa Itu Proposal?", ["Proposal: rencana kegiatan tertulis.", "Struktur: latar belakang, tujuan, sasaran, waktu, anggaran.", "R:Proposal: latar belakang → tujuan → sasaran → waktu → anggaran."], [["Tujuan proposal...", ["Melapor", "Merencanakan", "Menghibur"], 1, ""], ["Alasan kegiatan di...", ["Tujuan", "Latar belakang", "Sasaran"], 1, ""]], "Buat proposal lomba baca puisi.", [["Bahasa proposal...", ["Santai", "Formal", "Daerah"], 1, ""]]],
      ["Bab 4: KTI", "3.10/4.10", "KTI", ["Sistematika", "Menulis KTI", "Orisinalitas"], "Sistematika KTI", ["Judul, kata pengantar, daftar isi.", "Bab I-V: pendahuluan, teori, metode, pembahasan, penutup.", "R:KTI: I pendahuluan, II teori, III metode, IV pembahasan, V penutup."], [["Rumusan masalah bab...", ["I", "II", "III"], 0, ""], ["Daftar pustaka berisi...", ["Biodata", "Sumber referensi", "Lampiran"], 1, ""]], "Buat kerangka KTI 'Game Online pada Remaja'.", [["KTI orisinal artinya...", ["Copy", "Karya sendiri", "Panjang"], 1, ""]]],
      ["Bab 5: Novel", "3.11/4.11", "NOVEL", ["Unsur novel", "Pesan", "Apresiasi"], "Unsur Novel", ["Tema, alur, tokoh, latar, sudut pandang, amanat.", "Lebih kompleks dari cerpen.", "R:Novel: tema, alur, tokoh, latar, sudut pandang, amanat."], [["Novel vs cerpen...", ["Novel pendek", "Novel lebih kompleks", "Sama"], 1, ""], ["Penokohan bulat...", ["Datar", "Berkembang", "Tetap"], 1, ""]], "Analisis unsur intrinsik novel.", [["Laskar Pelangi bertema...", ["Cinta", "Perjuangan", "Horor"], 1, ""]]],
      ["Bab 6: Debat", "3.12/4.12", "DEBAT", ["Analisis debat", "Argumen", "Debat formal"], "Debat Formal", ["Mosi, tim pro/kontra, moderator.", "Format: argumen, rebuttal, kesimpulan.", "R:Debat: argumen, rebuttal, kesimpulan."], [["Rebuttal artinya...", ["Pembukaan", "Sanggahan", "Kesimpulan"], 1, ""], ["Tim dukung mosi...", ["Kontra", "Pro", "Netral"], 1, ""]], "Buat argumen pro-kontra 'Online Efektif'.", [["Tugas moderator...", ["Berdebat", "Memimpin", "Menilai"], 1, ""]]],
    ],
  },
  // === KELAS XII SEMESTER 1 ===
  {
    level: 11, grade: "XII", semester: 1, title: "Kelas XII Semester 1", description: "Surat lamaran, cerita sejarah, editorial, novel, artikel, puisi",
    bab: [
      ["Bab 1: Surat Lamaran", "3.1/4.1", "SURAT_LAMARAN", ["Struktur surat lamaran", "Menulis", "Kebahasaan"], "Surat Lamaran Kerja", ["Tempat/tanggal, perihal, alamat, salam, isi, ttd.", "Isi: identitas, posisi, kualifikasi.", "R:Surat lamaran: identitas, posisi, kualifikasi."], [["Surat lamaran termasuk...", ["Pribadi", "Dinas", "Niaga"], 1, ""], ["Posisi dilamar di...", ["Pembuka", "Isi", "Penutup"], 1, ""]], "Tulis surat lamaran untuk posisi impian.", [["Lampiran berisi...", ["Foto kopi KTP/ijazah", "Surat", "Undangan"], 0, ""]]],
      ["Bab 2: Cerita Sejarah", "3.2/4.2", "SEJARAH", ["Teks cerita sejarah", "Struktur", "Menulis"], "Cerita Sejarah", ["Cerita berdasarkan peristiwa sejarah.", "Struktur: orientasi, urutan peristiwa, reorientasi.", "R:Cerita sejarah: orientasi → peristiwa → reorientasi."], [["Cerita sejarah berdasarkan...", ["Imajinasi", "Fakta sejarah", "Dongeng"], 1, ""], ["Reorientasi berisi...", ["Pembuka", "Komentar penulis", "Konflik"], 1, ""]], "Tulis cerita singkat proklamasi kemerdekaan.", [["Cerita sejarah vs fiksi...", ["Fiksi lebih bebas", "Sama", "Sejarah lebih lucu"], 0, ""]]],
      ["Bab 3: Teks Editorial", "3.3/4.3", "EDITORIAL", ["Memahami editorial", "Opini redaksi", "Menganalisis"], "Apa Itu Editorial?", ["Editorial: opini resmi media.", "Struktur: isu, argumen, saran.", "R:Editorial: isu → argumen → saran."], [["Editorial ditulis...", ["Pembaca", "Redaksi", "Siswa"], 1, ""], ["Saran dalam editorial...", ["Isu", "Rekomendasi", "Argumen"], 1, ""]], "Analisis editorial koran tentang pendidikan.", [["Editorial bersifat...", ["Subjektif", "Opini institusi", "Netral"], 1, ""]]],
      ["Bab 4: Novel", "3.4/4.4", "NOVEL", ["Analisis novel", "Unsur ekstrinsik", "Apresiasi"], "Analisis Novel", ["Intrinsik + ekstrinsik.", "Nilai moral, sosial, budaya.", "R:Analisis novel: intrinsik + ekstrinsik."], [["Unsur ekstrinsik...", ["Tema", "Latar penulis", "Alur"], 1, ""], ["Nilai moral berkaitan...", ["Keindahan", "Baik-buruk", "Tradisi"], 1, ""]], "Analisis novel Indonesia: unsur intrinsik + ekstrinsik.", [["Novel 'Bumi Manusia' karya...", ["Andrea Hirata", "Pramoedya", "Rendra"], 1, ""]]],
      ["Bab 5: Artikel", "3.5/4.5", "ARTIKEL", ["Artikel ilmiah", "Kebahasaan", "Menulis"], "Artikel Ilmiah", ["Judul, abstrak, pendahuluan, metode, hasil, diskusi.", "Bahasa ilmiah, objektif.", "R:Artikel ilmiah: abstrak, pendahuluan, metode, hasil, diskusi."], [["Abstrak berisi...", ["Judul", "Inti artikel", "Daftar pustaka"], 1, ""], ["Diskusi berisi...", ["Alat", "Interpretasi hasil", "Cara"], 1, ""]], "Tulis artikel ilmiah populer 'Polusi Udara'.", [["Artikel ilmiah vs opini...", ["Ada abstrak", "Ada opini", "Subjektif"], 0, ""]]],
      ["Bab 6: Puisi", "3.6/4.6", "PUISI", ["Puisi kontemporer", "Membandingkan", "Esai sastra"], "Puisi dan Esai Sastra", ["Esai sastra: analisis karya sastra.", "Pendapat pribadi didukung bukti.", "R:Esai sastra: analisis + pendapat."], [["Esai sastra membahas...", ["Politik", "Karya sastra", "Sejarah"], 1, ""], ["Pendapat esai harus...", ["Bebas", "Didukung bukti", "Subjektif"], 1, ""]], "Tulis esai sastra tentang puisi 'Aku' Chairil Anwar.", [["Esai vs resensi...", ["Esai lebih subjektif", "Sama", "Resensi untuk buku"], 1, ""]]],
    ],
  },
  // === KELAS XII SEMESTER 2 ===
  {
    level: 12, grade: "XII", semester: 2, title: "Kelas XII Semester 2", description: "Kritik sastra, esai, KTI, resensi, drama, prosedur",
    bab: [
      ["Bab 1: Kritik Sastra", "3.7/4.7", "KRITIK_SASTRA", ["Memahami kritik sastra", "Menganalisis", "Menulis kritik"], "Kritik Sastra", ["Kritik sastra: analisis, interpretasi, evaluasi.", "Objektif, didukung bukti.", "R:Kritik sastra: analisis, interpretasi, evaluasi."], [["Tujuan kritik sastra...", ["Menghina", "Menganalisis", "Promosi"], 1, ""], ["Kritik didukung...", ["Opini", "Bukti teks", "Gosip"], 1, ""]], "Tulis kritik sastra cerpen terkenal.", [["Kritik vs resensi...", ["Kritik lebih dalam", "Sama", "Resensi lebih kritis"], 0, ""]]],
      ["Bab 2: Esai", "3.8/4.8", "ESAI", ["Memahami esai", "Struktur", "Menulis esai"], "Menulis Esai", ["Pendahuluan (tesis), isi (argumen), penutup (kesimpulan).", "Gagasan pribadi, logis.", "R:Esai: pendahuluan → isi → penutup."], [["Tesis dalam esai di...", ["Akhir", "Awal", "Tengah"], 1, ""], ["Esai bersifat...", ["Objektif", "Pendapat pribadi", "Faktual"], 1, ""]], "Tulis esai 'Pendidikan di Era Digital'.", [["Esai berbeda artikel...", ["Esai lebih pribadi", "Sama", "Artikel lebih pribadi"], 0, ""]]],
      ["Bab 3: KTI", "3.9/4.9", "KTI", ["KTI lanjutan", "Metodologi", "Penulisan"], "KTI Lanjutan", ["Metode: kualitatif, kuantitatif, campuran.", "Data, analisis, kesimpulan.", "R:KTI: metode, data, analisis, kesimpulan."], [["Metode wawancara termasuk...", ["Kuantitatif", "Kualitatif", "Campuran"], 1, ""], ["Kesimpulan KTI...", ["Opini", "Menjawab rumusan", "Saran"], 1, ""]], "Buat bab III (metode) KTI sederhana.", [["Daftar pustaka berguna...", ["Hiasan", "Sumber rujukan", "Lampiran"], 1, ""]]],
      ["Bab 4: Resensi", "3.10/4.10", "RESENSI", ["Resensi kritis", "Perbandingan", "Menulis"], "Resensi Kritis Lanjutan", ["Analisis perbandingan multidisiplin.", "Konteks sosial, politik, budaya.", "R:Resensi kritis: multidisiplin."], [["Resensi multidisiplin...", ["Satu aspek", "Banyak aspek", "Subjektif"], 1, ""], ["Konteks sosial memengaruhi...", ["Harga", "Isi dan pesan", "Sampul"], 1, ""]], "Tulis resensi dengan analisis multidisiplin.", [["Resensi baik...", ["Memihak", "Seimbang", "Promosi"], 1, ""]]],
      ["Bab 5: Drama", "3.11/4.11", "DRAMA", ["Pementasan", "Apresiasi", "Kritik"], "Apresiasi Drama", ["Naskah + pementasan + konteks.", "Analisis sutradara, aktor, tata panggung.", "R:Apresiasi: naskah, pementasan, konteks."], [["Sutradara bertanggung jawab...", ["Aktor", "Konsep pementasan", "Tiket"], 1, ""], ["Tata lampu termasuk...", ["Naskah", "Pementasan", "Promosi"], 1, ""]], "Tulis apresiasi pementasan drama yang ditonton.", [["Apresiasi vs kritik...", ["Apresiasi positif", "Sama", "Kritik negatif"], 0, ""]]],
      ["Bab 6: Prosedur", "3.12/4.12", "PROSEDUR", ["Prosedur kompleks", "Evaluasi", "Revisi"], "Evaluasi Prosedur", ["Kelengkapan, urutan, kebahasaan.", "Revisi: perbaiki langkah kabur.", "R:Evaluasi: lengkap, urut, bahasa tepat."], [["Langkah kabur harus...", ["Dihapus", "Diperbaiki", "Dibiarkan"], 1, ""], ["Evaluasi bahasa...", ["Imperatif", "Sopan", "Panjang"], 0, ""]], "Evaluasi dan revisi teks prosedur kompleks.", [["Prosedur baik...", ["Langkah jelas", "Panjang", "Banyak gambar"], 0, ""]]],
    ],
  },
]

async function seed() {
  console.log("Seeding Buku Panduan Guru...")

  for (const lvl of levels) {
    const { bab: babData, grade, semester, ...levelRest } = lvl
    const created = await db.learningLevel.create({
      data: {
        ...levelRest,
        type: "PANDUAN",
        color: "from-emerald-500 to-teal-600",
        order: lvl.level,
        xpReward: 1000,
        coinReward: 200,
      },
    })
    console.log(`Level ${levelRest.title}: ${babData.length} bab`)

    for (let i = 0; i < babData.length; i++) {
      const [title, kd, topik, tujuan, materiJudul, materiIsi, latihanArr, praktikPetunjuk, kuisArr] = babData[i]
      const content: Konten = buatKonten(tujuan, materiJudul, materiIsi, latihanArr, praktikPetunjuk, kuisArr)
      const unitOrder = i + 1
      await db.learningUnit.create({
        data: {
          levelId: created.id,
          title,
          kd,
          topik,
          grade,
          semester,
          order: unitOrder,
          content: JSON.stringify(content),
          xpReward: 60,
          coinReward: 15,
          isActive: true,
        },
      })
      console.log(`  ${title}`)
    }
  }

  console.log("\nSeeding selesai! 12 level dengan " + levels.reduce((sum, l) => sum + l.bab.length, 0) + " bab.")
}

seed().catch(e => { console.error(e); process.exit(1) })
