/** Exercises actual routes and transactions against an isolated local database. */
import assert from "node:assert/strict";
import Module from "node:module";
import {PrismaClient,User} from "@prisma/client";
import {verifiedMidtransSignature} from "../lib/compliance/payment-signature";
import {randomUUID,createHash} from "node:crypto";
import {ageBandFor,serviceAllowed,NOTICE_VERSION,sensitivePurposeRestricted} from "../lib/compliance/policy";
const url=process.env.COMPLIANCE_TEST_DATABASE_URL;
if(!url || !['localhost','127.0.0.1'].includes(new URL(url).hostname)||!new URL(url).pathname.includes('bc_compliance_local'))throw new Error('Isolated LOCAL database required');
const db=new PrismaClient({datasources:{db:{url}}});
let identity:User|null=null; let verified=true;const signedPaths:string[]=[];
const original=(Module as unknown as {_load:(name:string,parent:unknown,isMain:boolean)=>unknown})._load;
(Module as unknown as {_load:typeof original})._load=function(name,parent,isMain){
 if(name==='server-only')return {};
 if(name==='@supabase/supabase-js')return {createClient:()=>({storage:{from:()=>({createSignedUrl:async(path:string)=>{signedPaths.push(path);return {data:{signedUrl:`https://storage.example.test/${path}`},error:null};}})}})};
 if(name==='@/lib/db')return {db};
 if(name==='@/lib/supabase/server')return {getIdentityUser:async()=>identity,getUser:async()=>identity,createClient:async()=>({auth:{getUser:async()=>({data:{user:{id:identity?.supabaseId,email_confirmed_at:verified?'2026-01-01':null}}})}})};
 if(name==='@/lib/gamification/teacher-xp')return {awardGuruXp:async()=>{},notifyGuruMurid:async()=>{}};
 if(name==='@/lib/rate-limit')return {rateLimitRoute:async()=>null};
 if(name==='@/lib/redis')return {del:async()=>{},delPattern:async()=>{}};
 return original(name,parent,isMain);
};
const account=require('../app/api/privacy/account/route');
const guardian=require('../app/api/privacy/guardian/route');
const admin=require('../app/api/admin/compliance/route');
const report=require('../app/api/safety/reports/route');
const assetRoute=require('../app/api/privacy/assets/route');
const service=require('../lib/compliance/service');
const deletion=require('../lib/account/deletion');
const cleanup=require('../lib/compliance/deletion-job');
const request=(body:unknown,origin='https://qa.example.test')=>new Request('https://qa.example.test/api/privacy/account',{method:'POST',headers:{origin,'Content-Type':'application/json'},body:JSON.stringify(body)});
const ids:string[]=[];const sessionIds:string[]=[];
async function user(role:'MURID'|'GURU'|'ADMIN'='MURID'){
 const id='qa-'+randomUUID();ids.push(id);return db.user.create({data:{id,supabaseId:randomUUID(),email:`${id}@example.test`,fullName:'Local QA',role}});
}
async function main(){
 assert.equal(ageBandFor(new Date('2008-10-03'),new Date('2026-10-02T17:01:00Z')),'ADULT');
 assert.equal(ageBandFor(new Date('2008-10-03'),new Date('2026-10-02T16:59:00Z')),'16_17');
 for(const [age,band] of [[2,'UNDER_3'],[3,'3_5'],[6,'6_9'],[10,'10_12'],[13,'13_15'],[16,'16_17'],[18,'ADULT']] as const)assert.equal(ageBandFor(new Date(`${2026-age}-10-03`),new Date('2026-10-03')) ,band);
 assert.equal(serviceAllowed(null,true),false);
 assert.equal(sensitivePurposeRestricted("13_15","GUARDIAN_VERIFIED","/api/billing/checkout"),true);assert.equal(sensitivePurposeRestricted("ADULT","SELF_DECLARED","/api/billing/checkout"),true);assert.equal(sensitivePurposeRestricted("ADULT","REVIEWED","/api/billing/checkout"),false);assert.equal(sensitivePurposeRestricted("13_15","GUARDIAN_VERIFIED","/api/payment/webhook"),false);
 const signature=createHash('sha512').update('order-qa'+'200'+'10000.00'+'local-key').digest('hex');
 assert.equal(verifiedMidtransSignature('order-qa','200','10000.00',signature,'local-key'),true);
 assert.equal(verifiedMidtransSignature('order-qa','200','90000.00',signature,'local-key'),false);
 assert.equal(verifiedMidtransSignature('order-qa','200','10000.00','x','local-key'),false);
 assert.equal(verifiedMidtransSignature('order-qa','200','10000.00',signature,''),false);
 process.env.NEXT_PUBLIC_SUPABASE_URL='https://local.example.test';process.env.SUPABASE_SERVICE_ROLE_KEY='local-test-only';
 const credentials=require('../src/main-bersama/infrastructure/repositories/player-credential');
 const c=credentials.issuePlayerCredential('player-qa','session-qa');assert.equal(credentials.resolvePlayerCredential(c).ok,true);assert.equal(credentials.resolvePlayerCredential(c.replace('session-qa','session-other')).ok,false);
 const child=await user(),parent=await user(),reviewer=await user('ADMIN'),stranger=await user();
 identity=child;
 assert.equal((await account.POST(request({birthDate:'2014-02-30',acceptedNotice:true}))).status,400);
 assert.equal((await account.POST(request({birthDate:'2014-10-01',acceptedNotice:true,publicWorks:true,publicProfile:true,analytics:true,aiAssistance:true}))).status,200);
 const p=await db.privacyAccount.findUniqueOrThrow({where:{userId:child.id}});
 assert.equal(p.publicWorks,false);assert.equal(p.publicProfile,false);assert.equal(p.analytics,false);assert.equal(p.aiAssistance,false);
 assert.equal((await account.POST(request({birthDate:'2000-01-01',acceptedNotice:true}))).status,400);
 assert.equal((await account.POST(request({acceptedNotice:true},'https://evil.test'))).status,400);
 assert.equal(await service.canUseService(child.id),false);
 const invite=await guardian.POST(request({action:'request',guardianEmail:parent.email}));assert.equal(invite.status,200);
 const inv=await invite.json();const token=new URL(inv.invitation).searchParams.get('token');assert.equal(token.length,64);
 const row=await db.guardianRequest.findUniqueOrThrow({where:{id:inv.requestId}});assert.notEqual(row.tokenHash,token);
 identity=parent;assert.equal((await account.POST(request({birthDate:'1980-01-01',acceptedNotice:true}))).status,200);
 identity=stranger;assert.equal((await guardian.POST(request({action:'agree',token,attestation:true}))).status,403);
 identity=parent;verified=false;assert.equal((await guardian.GET(new Request(`https://qa.example.test/api/privacy/guardian?token=${token}`))).status,403);assert.equal((await guardian.POST(request({action:'agree',token,attestation:true}))).status,403);verified=true;
 assert.equal((await guardian.POST(request({action:'agree',token,attestation:true,aiAssistance:true}))).status,200);
 assert.equal((await guardian.POST(request({action:'agree',token,attestation:true}))).status,400);
 assert.equal(await service.canUseService(child.id),false);
 identity=reviewer;assert.equal((await admin.POST(request({action:'guardian',id:row.id,approve:true,evidenceRef:'school-verification-local-qa'}))).status,200);
 process.env.CHILD_LOW_RISK_APPROVAL='verified';process.env.CHILD_RISK_EVIDENCE_REF='local-qa';
 assert.equal(await service.canUseService(child.id),true);
 const teacher=await user('GURU');
 const group=await db.group.create({data:{name:'Local QA consent class',grade:'SMP',teacherId:teacher.id,accessCode:randomUUID(),members:{create:{userId:child.id}}}});
 const session=await db.mainSession.create({data:{pin:String(Math.floor(100000+Math.random()*899999)),teacherId:teacher.id,classId:group.id,gameMode:'JELAJAH_KATA',totalRounds:1}});sessionIds.push(session.id);
 const classroom=require('../lib/compliance/classroom');
 assert.equal(await classroom.classroomAllowed(session.id),false);
 assert.equal(await classroom.classroomAllowed(session.id,{userId:parent.id}),true);
 identity=reviewer;assert.equal((await admin.POST(request({action:'classroom',classId:group.id,evidenceRef:'local-qa-class-roster-guardian-consent',approve:true,expiresAt:new Date(Date.now()+30*86400000).toISOString()}))).status,200);
 assert.equal(await classroom.classroomAllowed(session.id),true);
 await db.privacyAccount.update({where:{userId:child.id},data:{guardianConsentVersion:'old'}});assert.equal(await service.canUseService(child.id),false);
 await db.privacyAccount.update({where:{userId:child.id},data:{guardianConsentVersion:NOTICE_VERSION}});
 identity=parent;assert.equal((await guardian.POST(request({action:'withdraw',childId:child.id}))).status,200);assert.equal(await service.canUseService(child.id),false);
 assert.equal(await classroom.classroomAllowed(session.id),false);
 assert.equal(await service.canReadPrivateSubject(child.id,stranger),false);assert.equal(await service.canReadPrivateSubject(child.id,child),true);
 const privatePath=`${parent.id}/${randomUUID()}.png`;const assetUrl=`/api/privacy/assets?path=${encodeURIComponent(privatePath)}`;
 await db.user.update({where:{id:parent.id},data:{avatar:assetUrl}});
 identity=null;const assetReq=()=>new Request(`https://qa.example.test${assetUrl}`);
 assert.equal((await assetRoute.GET(assetReq())).status,404);assert.equal(signedPaths.length,0);
 await db.privacyAccount.update({where:{userId:parent.id},data:{publicProfile:true}});
 assert.equal((await assetRoute.GET(assetReq())).status,307);assert.equal(signedPaths.length,1);
 assert.equal((await assetRoute.GET(new Request(`https://qa.example.test/api/privacy/assets?path=${encodeURIComponent(`${parent.id}/${randomUUID()}.png`)}`))).status,404);
 await db.privacyAccount.update({where:{userId:parent.id},data:{publicProfile:false}});assert.equal((await assetRoute.GET(assetReq())).status,404);
 identity=null;const response=await report.POST(request({targetType:'OTHER',targetId:'https://qa.example.test/content',category:'CHILD_SAFETY',detail:'Local QA report detail'}));assert.equal(response.status,201);
 const ref=(await response.json()).reference;
 identity=stranger;assert.equal((await admin.GET()).status,403);
 identity=reviewer;assert.equal((await admin.POST(request({action:'moderate',id:ref,decision:'ESCALATE',reason:'Local QA independent review'}))).status,200);
 assert.equal((await db.safetyReport.findUniqueOrThrow({where:{id:ref}})).status,'ESCALATED');
 const ledger=await db.consentEvent.findFirstOrThrow({where:{subjectId:child.id}});
 await assert.rejects(db.consentEvent.update({where:{id:ledger.id},data:{action:'CHANGED'}}));
 const simulation=require('../lib/simulation/SimulationAnalyticsService');
 const answer=await db.testAnswer.create({data:{userId:child.id,questionType:'ESAI',score:0,aiSuggestedScore:72,reviewStatus:'PENDING'}});
 assert.equal(answer.score,0);assert.equal((await simulation.approveAnswers([answer.id],reviewer.id)).ok,1);
 assert.equal((await db.testAnswer.findUniqueOrThrow({where:{id:answer.id}})).score,72);
 await simulation.saveManualScore(answer.id,reviewer.id,38,'Human correction');assert.equal((await db.testAnswer.findUniqueOrThrow({where:{id:answer.id}})).score,38);
 const doomed=await user();await db.privacyAccount.create({data:{userId:doomed.id}});
 await deletion.anonymizeAccount(doomed.id,doomed.supabaseId,[{bucket_id:'student-private',name:`${doomed.id}/local.png`}]);
 assert.ok((await db.user.findUniqueOrThrow({where:{id:doomed.id}})).email.endsWith('@account.invalid'));
 assert.equal(await db.privacyAccount.count({where:{userId:doomed.id}}),0);
 let fail=true;const calls:string[]=[];
 const vendor={storage:{from:()=>({remove:async()=>{calls.push('storage');return {error:fail?{}:null};}})},auth:{admin:{signOut:async()=>{calls.push('revoke');return {error:null};},deleteUser:async()=>{calls.push('auth');return {error:null};}}}};
 await assert.rejects(cleanup.finishDeletion(doomed.id,vendor,'test-token'));
 assert.equal((await db.deletionJob.findUniqueOrThrow({where:{userId:doomed.id}})).status,'RETRY_REQUIRED');assert.ok(!calls.includes('auth'));
 fail=false;await cleanup.finishDeletion(doomed.id,vendor,'test-token');assert.ok(calls.indexOf('revoke')<calls.indexOf('auth'));
 assert.equal((await db.deletionJob.findUniqueOrThrow({where:{userId:doomed.id}})).status,'COMPLETED');
 await db.safetyReport.delete({where:{id:ref}});
 console.log('PASS: local route/database integration: age boundaries, locked DOB, safe defaults, CSRF, verified email, token binding/replay, independent guardian review, version expiry, withdrawal, private asset IDOR, anonymous reports, admin authorization, immutable ledger, account anonymization, durable vendor retry, session credential binding and human grading approval/correction.');
}
main().catch(e=>{console.error(e);process.exitCode=1;}).finally(async()=>{await db.mainSession.deleteMany({where:{id:{in:sessionIds}}});await db.user.deleteMany({where:{id:{in:ids}}});await db.$disconnect();(Module as unknown as {_load:typeof original})._load=original;});
